### ISSUE TITLE
java.net.BindException: Address already in use: bind

### ISSUE THREAD

**Issue by Zethalion** [CoFH/Feedback#1]
I got a failure on loading java.net.BindException: Address already in use: bind

I installed these 4 mods:
- CoFHCore-[1.7.10]3.1.4-329.jar
- ThermalDynamics-[1.7.10]1.2.1-172.jar
- ThermalExpansion-[1.7.10]4.1.5-248.jar
- ThermalFoundation-[1.7.10]1.2.6-118.jar

Using these 4 version do not cause any problem:
- CoFHCore-[1.7.10]3.1.3-327.jar
- ThermalDynamics-[1.7.10]1.2.0-171.jar
- ThermalExpansion-[1.7.10]4.1.4-247.jar
- ThermalFoundation-[1.7.10]1.2.5-115.jar

See this fml-server log: https://gist.github.com/Zethalion/26403f75dc166250b24950aa86f32c90

**Comment by UnRealDinnerbone** [comment]
In Less then 3 hours people already post about 1.7.10... what has the world come to

**Comment by KingLemming** [comment]
This isn't something we see. But we also don't support Sponge.

**Comment by Zethalion** [comment]
With Baughn again checking the issue on IRC. Something derped at the same moment. Blaming my OS. Sorry!

**Comment by Zethalion** [comment]
@KingLemming It's isn't actually Sponge what you see in the log. Just mixins from ForgeEssentials.
