### ISSUE TITLE
Cross-mod conflict: Plates cause client-side crash

### ISSUE THREAD

**Issue by Cobra1117** [CoFH/Feedback#1]
The new plates can cause a client-side crash when one is placed in a block containing RailCraft's invisible blocks. (Produced by RailCraft's anchors, signals, etc.)

Error log: http://pastebin.com/gWBFsSeP

Relevant versions:
Forge: 10.13.2.1277
Thermal Foundation: 1.0.0RC1-13
Thermal Expansion: 4.0.0B8-23
RailCraft: 9.4.0.0

**Comment by Cobra1117** [comment]
Yeah... those RailCraft invisible blocks have been the cause of more crashes on my server than I care to think about. :-P

**Comment by skyboy** [comment]
Fixed by https://github.com/CoFH/CoFHCore/commit/387af4b1a28708dec48fb681ed0517079c9c89bf
(The comments in this particular method show how wonderful mojang's code is)
