### ISSUE TITLE
Can't figure out what the augments do...

### ISSUE THREAD

**Issue by Tokoshoran** [CoFH/Feedback#10]
I've been trying to look around for a quick list of what all of the augments do, but can't seem to find any answers. The pack I'm playing on has an unusual bug associated with the Shift key, so anything relying on that key, I've gone and moved to another key, but this cannot be modified for Thermal Expansion's augment information. Can we get a list of what they all do?

**Comment by bochen415** [comment]
http://teamcofh.com/thermal-expansion/machines/augments/

**Comment by KingLemming** [comment]
Please do not use this tracker for questions. We have an IRC channel and a website. Now this issue only serves as a permanent reminder that you didn't look very hard.
