### ISSUE TITLE
[thermal foundation] Breaks IE Creosote

### ISSUE THREAD

**Issue by GameKnyte** [CoFH/Feedback#100]
I have a small custome made mod pack for 1.10.2 and recently added Immersive Engineering for its machines and power transfer. For some reasons the creosote is bugged and unable to be obtained from the IE coke oven. It's texture is broken and the bucket in JEI is labeled as follows:
Creosote Oil bucket
Temperature: 300k
Added by: Thermal Foundation
Minecraft forge 

I've already reported this to BluSunrize.

**Comment by KingLemming** [comment]
We aren't doing anything outside of creating a standard fluid, so I'm pretty sure this is entirely on IE's end.

**Comment by codewarrior0** [comment]
For what it's worth...

Creosote can't be poured into the world from a bucket. In other words, it doesn't exist in Block form. Ran into this in a bug in Charset's fluid pipes which tried to render the fluid using its Block form.

**Comment by KingLemming** [comment]
Ours can't either.
