### ISSUE TITLE
When I download alpha versions from CurseForge instead of Curse, I crash (obviously)

### ISSUE THREAD

**Issue by crunkazcanbe** [CoFH/Feedback#100]
http://pastebin.com/548T702y

I have to go all the way back to ThermalFoundation-[1.7.10]1.0.0RC1-35 for this crash to stop .

**Comment by bochen415** [comment]
Actually the versions at Curse work. 
The ones on CurseForge are snapshots made in the middle of developing. 
Do not use them and yes, they know about it
https://github.com/CoFH/Feedback/issues/98

**Comment by nister6000** [comment]
Anyone know newest working alpha combination?

**Comment by Sasikaa** [comment]
I also have the same fault!
The
ThermalFoundation- [1.7.10] 1.0.0RC1-35
version works perfectly !!

**Comment by FrostySigh** [comment]
Maybe you should write that on the curseforge pages then? Just a thought....

**Comment by KingLemming** [comment]
Please do not say "Curse" when you mean "CurseForge." Just stop.

**Comment by DigitolMC** [comment]
I found deleting ProjRed;Compat fixes the TFItems smeltermanager bug.

**Comment by crunkazcanbe** [comment]
Thank you everyone for your arrogance. Much appreciated , and I will never post anymore problems .

I love the new big shinny title that you try to make me out to be a dumb ass on when in fact the dumb ass are the one's who are arrogant . The only reason I use alpha is because it fixes some of the problems I was having on your so called BETA builds.



-Crunk

**Comment by bochen415** [comment]
@crunkazcanbe why use alphas when so called "stable" versions are out?

**Comment by crunkazcanbe** [comment]
I said the above on the assumption that stable builds where not out yet . I didn't know . I still have to wait on a few mods to update before I can move to the stable builds .

**Comment by codexnovus** [comment]
Downloaded latest version from Curse (not curseforge). Having the same problem, as the download from Curse and Curseforge is the same (RC4-58). Also; is marked as "release" not "alpha".
