### ISSUE TITLE
Are items leaking out of itemducts intended behaviour or is it a bug?

### ISSUE THREAD

**Issue by pmmeyourpassword** [CoFH/Feedback#1000]
I'm using impulse itemducts with a servo to extract items from a mob crusher (industrial foregoing) and occasionally it starts dropping some of the items into the world. 

I don't know if that's supposed to happen since AFAIK the impulse itemducts are the top tier for transportation in this mod so it seems a little weird..
___
I'm playing with these versions: 

- ThermalFoundation-1.12.2-2.3.10.6-universal
- ThermalExpansion-1.12.2-5.3.10.15-universal
- ThermalDynamics-1.12.2-2.3.10.4-universal
- CoFHCore-1.12.2-4.3.10.5-universal
- CoFHWorld-1.12.2-1.1.1.12-universal

**Comment by KingLemming** [comment]
Need a video of this. Definitely unintended, but also literally can't happen unless another tile is doing something really stupid.

**Comment by KingLemming** [comment]
There are a lot of possible factors here, but the only way I can see this actually happening is when receiving tiles are liars. So...yeah.

TD is up for a rewrite so this is basically a moot issue anyways.
