### ISSUE TITLE
[Thermal Dynamics] mystical agriculture furnace not working with itemducts/servos

### ISSUE THREAD

**Issue by Bircko** [CoFH/Feedback#1001]
![2018-03-31_17 10 11](https://user-images.githubusercontent.com/29576723/38164632-9a5c7d60-3507-11e8-9171-bfa3cfad3c07.png)

when i remove the hopper and connect it directly it just stops importing items, when only one itemduct is connected (import/export) it works fine but if both (import and export) used none works

mysticalagriculture-1.12-1.6.8
ThermalDynamics-1.12.2-2.3.10.4-universal

**Comment by KingLemming** [comment]
Okay so.

Ducts use capabilities. They are agnostic. They do not special case things. If it doesn't work with something, it's because of how that thing is using capabilties. :)
