### ISSUE TITLE
COFH Crashing on Startup.

### ISSUE THREAD

**Issue by SivashX** [CoFH/Feedback#1001]
Hello all of tam CoFH.

I was open and prompt a pre startup CoFH Core and the game stopped working
My Java version and 8:45 (64-bit) Windows 10 Pro.
I tried to open only with the Core CoFH but to no avail continued with error.

Thanks.
SivashX

**Comment by XFactHD** [comment]
What about posting your crash report via pastebin.com?

**Comment by skyboy** [comment]
Closing due to lack of response.
