### ISSUE TITLE
@Nullable parameter used without check -> NPE

### ISSUE THREAD

**Issue by HenryLoenwind** [CoFH/Feedback#1002]
https://github.com/CoFH/ThermalDynamics/blob/1.12/src/main/java/cofh/thermaldynamics/block/BlockDuct.java#L426-L446

The parameter `side` fro Chisels's `getFacade` is `@Nullable`, but it is handed off to `BlockDuckt.getVisualState()` which uses it without null checking.

Crashlog see https://github.com/SleepyTrousers/EnderIO/issues/4508

**Comment by KingLemming** [comment]
Interesting. Just curious, why are you actually using a null there when literally nothing else has apparently done so?

**Comment by HenryLoenwind** [comment]
Ender IO doesn't know anything about sides as it doesn't do connected textures, it does connected models.

The code further up in the stacktrace is the code that allows blocks that connect to their neighbors but are not aware of painted blocks to see the world as if all painted blocks were replaced with their paint source.
