### ISSUE TITLE
[1.10.2, Crash] "Tesselating Texture" on a Device/Machine

### ISSUE THREAD

**Issue by MainFreak** [CoFH/Feedback#1003]
A player of my modpack sent me this crashlog today. 
He reported that he only had an Igneous Extruder, some Fluiducts and a Portable Tank nearby.

Minecraft: 1.10.2

Forge: forge-12.18.3.2511

CoFH Mods and Dependencies: 
>CoFHCore-1.10.2-4.1.12.17-universal
>CodeChickenLib-1.10.2-2.5.9.320-universal
>ThermalDynamics-1.10.2-2.0.11.19-universal
>ThermalExpansion-1.10.2-5.1.10.28-universal

Crashlog: https://pastebin.com/05CPrgxN

If more info is needed please tell me, I will try to provide it ASAP

**Comment by KingLemming** [comment]
1.10.2 is no longer supported, sorry.
