### ISSUE TITLE
[COFH World] Feature Request: "builder" generator faithful to material entry.

### ISSUE THREAD

**Issue by Arakhor** [CoFH/Feedback#1004]
Unless I'm missing something, it is currently impossible to configure "builder" generator to only replace certain blocks. Trying to use material "stone" results in builders being created, presumably, around the block specified in "material" entry, but the additional blocks forming a cluster will ignore the setting completely.
Example:
`{
	"populate": {
		"granite": {
			"distribution": "uniform",
			"generator": {
				"type": "boulder",
				"block": {
					"name": "stone",
					"properties": {"variant": "granite"}
				},
				"diameter": 4,
				"material": "minecraft:stone"
			},
			"cluster-count": 5,
			"min-height": 40,
			"max-height": 180,
			"biome": {
				"restriction": "whitelist",
				"value": [
					{"type": "dictionary","entry": "MOUNTAINS"},
					{"type": "dictionary","entry": "HILLS"}
				]
			},
			"dimension": {
				"restriction": "blacklist",
				"value": [-1,1]
			}
		}
	}
}`
https://i.imgur.com/DxmVpqi.jpg

Is that something you might consider changing, or implementing another generation option that would follow these rules?

**Comment by KingLemming** [comment]
The issue here is specifically "boulder."

Right now the generators sort of do their own thing when finding the target material, based on what they are.

The whole thing will be rewritten at some point in the future, so I can't really address this one way or another at this time.
