### ISSUE TITLE
[Thermal Dynamics] Cryo-stabilized fluxduct losing energy when connected to mekanism cables (Elite, Ultimate)

### ISSUE THREAD

**Issue by TheSprtCz** [CoFH/Feedback#1006]
When connecting Cryo-stabilized flux duct to Elite Universal Cable or Ultimate Universal cable from Mekanism energy gets lost. I tested it with [these mods](http://pastebin.com/wChPHnd3) by simply creating loop from one energy storage to another, in this case Ultimate Energy Cube. Here is picture of my testing loop.
![How I tested it](https://cloud.githubusercontent.com/assets/5594403/12521876/8ff89dac-c14d-11e5-9c47-50e67812701e.png)

**Comment by skyboy** [comment]
This is not an issue with cryo-stabalized fluxducts. They work correctly with other types of cable.
