### ISSUE TITLE
Crash with the new update

### ISSUE THREAD

**Issue by NanayaQ** [CoFH/Feedback#1007]
Just updated the whole thermal expansion suite:

https://pastebin.com/NguVsf71

So far I disable it and game runs fine atm...

**Comment by KingLemming** [comment]
Duplicate of #1006. Please look before you post.

**Comment by NanayaQ** [comment]
Sorry about that when I was writing up the post I didnt see another one 10 minutes ago since i was double checking with the update.

**Comment by KingLemming** [comment]
No worries.
