### ISSUE TITLE
[Request] Changelog

### ISSUE THREAD

**Issue by accessdenied0** [CoFH/Feedback#1008]
Hey @CoFH-Team,

I hope this issue isn't a waste of your time, but I wanted to request a kind of Changelog between Version (in special Full-Working-Versions) to see what is been done.

I would love to see the recent changes and tweaks you guys made, but I didn't found a changelog to the latest version(s). Maybe distribute it on your new website, would be cool.

access_denied

**Comment by KingLemming** [comment]
We do changelogs when we do releases.

**Comment by accessdenied0** [comment]
Maybe I mistake this mod group with a other one. But here you go:
http://minecraft.curseforge.com/projects/thermal-foundation/files/2277480
http://minecraft.curseforge.com/projects/thermalexpansion/files/2277482

One or two examples why I got confused,
sorry

**Comment by skyboy** [comment]
I had been working on the change logs, but with 7 mods and 6+ months of changes to compress into something meaningful for the user, it took a bit of time.
