### ISSUE TITLE
Bug from New Update

### ISSUE THREAD

**Issue by DrakoAlcarus** [CoFH/Feedback#1009]
Right clicking on the new plates turns them into regular plates. i.e. Excursion plate (which I fell in love with immediately) turns into an impulse plate, wasting valuable metal.

**Comment by DrakoAlcarus** [comment]
Also, I love the new sawmill texture. <3

**Comment by KingLemming** [comment]
We need a video and a modlist. Because this absolutely does not happen.

**Comment by DrakoAlcarus** [comment]
Mod list: http://imgur.com/UyAOcOc

Video: https://www.youtube.com/watch?v=SfORSpzEyEM

If I say anything stupid, I was recording this early in the morning.

**Comment by skyboy** [comment]
That's kinda hilarious. I never thought about them being rotated, and I didn't realize the code I had for beam projection could even work at angles like that.

In the mean time, you can wrench any up that are rotated incorrectly and that will fix them.

**Comment by DrakoAlcarus** [comment]
Yay, I actually helped submit a real bug. :D

**Comment by DrakoAlcarus** [comment]
I also meant to say: "Right clicking of the new plates with the wrench". That's what threw @KingLemming off.

**Comment by DrakoAlcarus** [comment]
Also, would it be possible to add two more crafting slots for schematics and output in the cyclic assembler? On top of this, a button could be added that switches the modes of crafting schematics: round robin, random, first only.

Or the higher the level, the more schematic slots.

**Comment by skyboy** [comment]
Open new issues for unrelated suggestions/bugs.
