### ISSUE TITLE
Cofh(1.7.10) core and Gregtech 5.09.29

### ISSUE THREAD

**Issue by Pilad** [CoFH/Feedback#101]
I used GT ore in the generation. And the ore does not appear correctly in the world. Maybe because in the name of the ore there are two times (:). He wrote both with the metadata and the vocabulary(oredict) of the ores. An empty block is generated.

**Comment by KingLemming** [comment]
As I understand, Greg uses tile entities for ore, and it'll just be fundamentally incompatible.

Check with Greg, but we're no longer supporting 1.7.10 and I feel that there's nothing we can do on our end anyways.

**Comment by Pilad** [comment]
Ok. Thanks for answer.
