### ISSUE TITLE
Tesselating block model

### ISSUE THREAD

**Issue by Xiaminou** [CoFH/Feedback#1010]
Client crashed when joining my server after updating CoFH mods.
[crash-2018-04-07_14.07.17-client.txt](https://github.com/CoFH/Feedback/files/1886334/crash-2018-04-07_14.07.17-client.txt)

Edit: Yep, it crashes instantly as soon as I get anywhere near my base.
Edit2: Downgrading Thermal Dynamics fixed it.

**Comment by covers1624** [comment]
Yeah i thought CTM's api had changed, but their default branch wasn't 1.12, partly my fault, partly their repo being dumb and reversed's fault.

**Comment by TheSnowyChickens** [comment]
Hello,
I think I have the same crash.

Log (Client) : [crash-2018-04-07_18.33.34-client.txt](https://github.com/CoFH/Feedback/files/1886554/crash-2018-04-07_18.33.34-client.txt)

Log (Server) : MC create one, but it is empty
