### ISSUE TITLE
[Suggestion] Thermal Innovation Item Tweaks

### ISSUE THREAD

**Issue by Xydryhn** [CoFH/Feedback#1011]
Not sure how exactly to word the title, but Just 2 small requests for enhancing the usability of some of the new items. I Mentioned these in the reddit announcement but Figured I'd post them here as proper suggestions

Drills: A request for either a new mode, or just for the 5x5 to have an offset to make digging long tunnels a bit easier.

Hypoinfusers: While the Auto Inject Feature is handy, I wanted to make in a request for the ability to shift right click to force inject yourself with a full dose of said potion. Right now Having a instant healing potion will automatically inject even if you are at full health, as well as being able to get a long term dose of a potion or maybe even stacking doses would be handy. 

This would make it easier to use potions that have more of a need on demand instead of having to turn auto inject on and then turn it back off again to get some quick healing/effects.

**Comment by KingLemming** [comment]
Injector now self-injects if used while sneaking.

I'm still thinking about the drill. I really don't want to add another mode, and offsetting the 5x5 feels inconsistent.

**Comment by Serifina** [comment]
Botania's Terra Shatterer offsets on horizontal mine only, so that you can make smooth use o the larger AoE mining, and it works very well.

**Comment by KingLemming** [comment]
I'm pondering it. Right now I'm actually thinking about adding more modes to the drill in general. Probably a 1x3 tunnel and a 3x3x3 as well.

**Comment by KingLemming** [comment]
Okay, so.

Drills now have up to 5 modes: Single Block, Tunnel (1x2), 3x3, 3x3x3, and 5x5. The 5x5 has an offset.

I've also ported the 5x5 offset to Redstone Arsenal. :)
