### ISSUE TITLE
Problem due to the thermal? [Crush]

### ISSUE THREAD

**Issue by HurtsAsHell** [CoFH/Feedback#1012]
I'm creating a modpack, I installed the latest versions of cofh and cofh world in addition to simply jetpacks2, thermal dynamics, thermal fundations, thermal expansion; The modpack is at version 1.12.2; I deleted the cofh folder as written on the mod thermal innovation page.
Today this problem arises that, by removing all the mods, adds today, continues to recur; What can I do?
The mods that have the crush are:
| UCE | thermalexpansion | 5.3.10 | ThermalExpansion-1.12.2-5.3.10.15-universal.jar | None |
| UCE | simplyjetpacks | 2.2.2.28 | SimplyJetpacks2-1.12.2-2.2.2.28.jar | None |

Have you already encountered the problem?
Do you know how to solve it?
All logs, crush reports[https://www.dropbox.com/s/7nck4yqlje1ldf8/Crush.zip?dl=0](url)

Sorry for my bad english but i use google traslate.

**Comment by KingLemming** [comment]
Please update ALL of your mods. You didn't update Thermal Expansion.
