### ISSUE TITLE
Thermal Innovation chat messages

### ISSUE THREAD

**Issue by Xiaminou** [CoFH/Feedback#1013]
Chat messages are bugged.

![2018-04-07_18 05 40](https://user-images.githubusercontent.com/8670392/38457288-943b6ab8-3a8e-11e8-9ac8-927b43cf0357.png)

**Comment by KingLemming** [comment]
Here's the thing - they aren't.

This is something unique to you. Let's see if we can't debug it.

![2018-04-07 12_51_56-minecraft 1 12 2](https://user-images.githubusercontent.com/2118598/38457731-84ef18e2-3a62-11e8-9bd2-1a3874528512.png)

**Comment by Xiaminou** [comment]
could it be what it was with the Multimeter messages? Did you try it on the a server?

**Comment by KingLemming** [comment]
That was taken on a server.

**Comment by KingLemming** [comment]
Apparently dev servers have a weird quirk. Got it figured out.
