### ISSUE TITLE
Suggestion:Thermal Innovation chainsaws and minecarts

### ISSUE THREAD

**Issue by Wotzinator** [CoFH/Feedback#1014]
so i just started using thermal innovation and its incredibly good but it lacks content(quiet normal for mods that are just released i know)so i had a few ideas that came into my mind while i was mining .chainsaws because we have drills so why not chainsaws and instead of chopping a 3x3 radius of blocks it could felling a whole tree or parts of it .and a thing that could fit but i don't know how it would be best implemented : more mine cart stuff ,so since rail craft didn't update for a long time and most other mods that try to aim on trains and min carts are to lagy or just don't play well with other mods or vanilla in general so i thought it could fit in thermal innovation(yes im aware of the fact that thermal dynamics already adds player transportation but in my case im using mine carts in my mine and id have to set up multiple item-ducts to )it could add bigger carts where you can pack a few more things into or some sort of cart linking mechanic it would also be cool if you could attach the drills of this mod to them or add a motor(electrical or powered like dynamos)to them instead of furnaces.
so i dont know if my ideas are good but i hope you like them.

**Comment by KingLemming** [comment]
Yes, there are more things coming to TI. ;)

Saws are already planned (and basically just waiting on art). Minecarts, I don't know.

I'll probably set up a general TI suggestions post to prevent the tracker from getting cluttered.
