### ISSUE TITLE
[CoFH Tweaks] Mob rendering issue

### ISSUE THREAD

**Issue by Psithief** [CoFH/Feedback#1017]
I just installed CoFH Tweaks and now I'm having a problem with mobs not being rendered when close by.

* Just moving the cursor around a (well-populated) village will cause most villagers to flicker into existence for a frame or so before they disappear again.
* Moving ~40 blocks from most mobs causes them to be rendered, moving within 10 blocks and they start flickering.
* There's also a huge dip in FPS as I approach the village proper and mobs start to vanish.

To test for conflicts, I removed all my other mods and deleted everything in the `/config/` directory, yet the problem persists.

## Mods
Minecraft Forge 10.13.4.1558
MCP 9.05, FML 7.10.99.99
CoFH Tweak ASM 1.7.10R1.1.0
CoFH Core 3.0.3
Forge Multipart, Mincart Multipart Plugin Forge Microblocks 1.2.0.345

## Log
http://paste.atlauncher.com/view/bc32b46b

## Screenshots
I attempted to show the problem of disappearing villagers by taking these as I approached them.
![2016-01-28_14 04 47](https://cloud.githubusercontent.com/assets/1124846/12636503/5ba78f3e-c5c8-11e5-905e-2df7b7fea379.png)
![2016-01-28_14 04 51](https://cloud.githubusercontent.com/assets/1124846/12636504/5babcc66-c5c8-11e5-9330-bb421da22ee6.png)
![2016-01-28_14 04 54](https://cloud.githubusercontent.com/assets/1124846/12636505/5bac7c06-c5c8-11e5-8d58-39f2d76b6e4d.png)
![2016-01-28_14 04 57](https://cloud.githubusercontent.com/assets/1124846/12636506/5bafd608-c5c8-11e5-843c-5693a23b7d53.png)
By the final shot it can be seen that nearly every villager has stopped being rendered, though the <3 particles are still being produced by these invisible villagers.

**Comment by TheTrueForce** [comment]
I can confirm this. I updated to CoFHTweaks 1.1.0-82 just today, and I got the exact same issue.
I'm going to roll back version by version until the problem disappears, and then report back.

**Comment by Psithief** [comment]
Good to know it's not just my hardware! :+1:

**Comment by skyboy** [comment]
I had been experiencing this too, but only when my framerate was above vsync. It wasn't unexpected in that case, as the resolution of the timer used to determine what frame was being rendered isn't always accurate enough at very high framerates.
But since it's happening well under that, I'll look more into it

**Comment by TheTrueForce** [comment]
OK. I've rolled back, and the error happens in these CoFHTweaks versions:
1.1.0-82
1.1.0B2-77
      I didn't get a massive performance hit in this version, it just didn't render the mob all the time.
1.1.0B2-76
1.1.0B2-75
It doesn't happen in build 74 and earlier.
I run MC with the framerate throttled to 50 and vsync off, for reference.
Also, are there changelogs about, apart from the commit log?

**Comment by Psithief** [comment]
@skyboy AggressiveCulling was set to false, it seems to be ignored by the config.

**Comment by skyboy** [comment]
@TheTrueForce Is there still a performance hit in build 84?

**Comment by TheTrueForce** [comment]
@skyboy There doesn't appear to be a performance hit or flickering in build 84.
