### ISSUE TITLE
[TD] Allow specification of exact amount for extraction by servos and retrievers

### ISSUE THREAD

**Issue by Parker8283** [CoFH/Feedback#1019]
For some cases, it may be nice to be able to specify an "exact extraction amount" for servos and retrievers, as opposed to a "max extraction amount". I've run into a couple of cases where it would be nice to have this (generally for automating certain machines which need a certain amount of input to function, and having less stuck in one would gum up the system). If I had to spitball some ideas as to how to implement this:

* Make it a button to toggle on/off, much like the buttons that already exist on the GUI
  * Maybe in a different style than those that already exist to have it fit better
* Possibly restrict it to higher levels of servos and retrievers
  * Maybe just resonant? As besides the increased filter size and speed bonus, the Signalum and Resonant variants are essentially the same. This would give some users more of a reason to upgrade.

Thanks for your work as always!

**Comment by KingLemming** [comment]
TD is being rewritten. We're keeping tabs on things like this we aren't even sure if the rewrite will have servos as they exist in their current form.

**Comment by Parker8283** [comment]
Alrighty! Thank you sir!

**Comment by KingLemming** [comment]
NP. :) I know that it's marked as closed, but that's just to unclutter the tracker so it's focused on mods which aren't pending rewrites.

We are marking all of these down for TD 3.0, which may or may not be completely different. The underlying grid logic definitely is, heh.
