### ISSUE TITLE
Desabling ThermalExpansion's Ore Generation

### ISSUE THREAD

**Issue by vigia122** [CoFH/Feedback#102]
Hi! I have a modpack, and there are 843684864 mods making the same ores, but I want to use the IC2's cooper, tin and lead... I tried to disable the ore gen from ThermalExpansion by editing the **ThermalExpansion-Ores.json** file in */.minecraft/config/cofh/world* (look the attached image, I removed copper, tin and lead ores), but "ThermalFundation" continued spawning them. How can I remove them?

P.S.: Sorry for my English.

![screenshot_4](https://cloud.githubusercontent.com/assets/2721565/6131005/3fe72c26-b130-11e4-968a-bb2eb1a6b412.png)

**Comment by KingLemming** [comment]
Hi!

No, it didn't. Thermal Foundation doesn't spawn anything - CoFH Core does. Also, if you removed the ores from the json, they'll no longer generate, but it does not remove existing ores from the world.

**Comment by XanderGryphon** [comment]
Apologies if I'm chiming in where I shouldn't be, but I'm unable to disable ore generation as well. I've edited the JSON file similarly to the above photo (removing all unwanted ores from the file), but they still generate as normal.

Currently using COFH Core 3.0.0B9-40 with Thermal Foundation 1.0.0RC1-13 and Thermal Expansion 4.0.0B8-23.
