### ISSUE TITLE
The problem with creative tools on server.

### ISSUE THREAD

**Issue by YungJora** [CoFH/Feedback#102]
Hello, I have a server FTB project Ozone and are faced with a problem, I can't twist wrenches items from creative while in survival mode, replaced the configs with new one, but it does not help! Help please, players complain because they can't go any further in development.

**Comment by KingLemming** [comment]
Yes. Creative items are meant for creative mode and ops only. This is intentional.

**Comment by YungJora** [comment]
Crafting these things provided.

**Comment by YungJora** [comment]
![2017-03-18_01 10 42](https://cloud.githubusercontent.com/assets/26492779/24063176/9d5dcd06-0b6f-11e7-90e7-b8010252b731.png)

**Comment by KingLemming** [comment]
Yeah I don't add the ability to do that. The pack has made an error here.

**Comment by covers1624** [comment]
This is 1.7 btw lemming..

**Comment by KingLemming** [comment]
Yeah I realized that.
