### ISSUE TITLE
TE 4.1.1 Glitch - Copper Gears in Pulverizer Crafting aren't oredicted

### ISSUE THREAD

**Issue by BlazingGamer** [CoFH/Feedback#1021]
![2016-01-29_13 02 27](https://cloud.githubusercontent.com/assets/13196222/12672669/d1699b02-c688-11e5-8786-e736b423375c.png)
Nope, this is not Minetweaker or mods like that.

**Comment by skyboy** [comment]
This is happening because forestry is loading before TE, something that normally doesn't happen so it wasn't found before (or at least no one bothered to report the inconsistency).
