### ISSUE TITLE
Suggestion/new item?/feature request

### ISSUE THREAD

**Issue by popps73x** [CoFH/Feedback#1021]
Block Materializer.  

Item would have three modes
Extend - would extend existing structures with matching blocks from the players inventory
Extend (selected block) - would extend existing structures using a selected block from the players inventory
Build to (selected block) - would build a line of blocks to the player (ie 8,16,24,32,64 given available space) with a selected block from the players inventory.

while this functionality is available in builders wands they are almost exclusively in magic mods.  I cannot think of one that is tech based but am probably missing something.

thanks for your consideration.  :)

**Comment by popps73x** [comment]
did not realize this was in general cofh was suggesting for thermal innovation

**Comment by KingLemming** [comment]
I think @Direwolf20 has taken care of this now. ;)
