### ISSUE TITLE
Add keybind option for "key.cofh.augments"

### ISSUE THREAD

**Issue by unpure** [CoFH/Feedback#1022]
Hey there.
I'm using the G key to open my inventory.
In the latest versions of cofhcore the G key is used by KEYBINDING_AUGMENTS.
Would it be possible to add an option to the keybinds menu to change the key for that?

Sorry for my bad english, i hope its not to hard to understand.

**Comment by KingLemming** [comment]
Augments is a feature that won't be in until 1.8+. We've already removed it in dev.
