### ISSUE TITLE
Add additional outputs to Phytogenic Insolator

### ISSUE THREAD

**Issue by EnderiumSmith** [CoFH/Feedback#1022]
Currently its not possible to grow apples in the insolator. I can think of 2 options to fix this. 1) a second secondary slot or 2) a variant of the sapling infuser that makes fruits as a main product instead of wood.
According to the MC wiki the chance per tree to get an apple is 25% for oak and 60% for dark oak. It would be especially useful for modded fruit trees like iron berrys and olives from rustic. Speaking of olives, olive oil should be a fuel in the compression dynamo.

**Comment by KingLemming** [comment]
I considered adding additional outputs but there's a concern of machine balance and then also the fact that it'd have to be rewritten in a fairly intrusive fashion.

There's not a *great* solution on this one but I'll think about it.

**Comment by Mementh** [comment]
FYI it can with pamscraft. not a ideal.. but they have saplings...

simple solution, a apple is a "seed carrier" 
use a apple to grow the new apples.. simple solution it wont make logs, just apples?

**Comment by KingLemming** [comment]
This will happen with the TE 6 rewrite, but not before.
