### ISSUE TITLE
Destabilized redstone

### ISSUE THREAD

**Issue by HurtsAsHell** [CoFH/Feedback#1025]
I can somehow disable the destabilized redstone fluid in the world gen and from breaking of destabilized redstone ore?

**Comment by KingLemming** [comment]
You can edit the world gen files, yes. /config/cofh/world/03_thermalfoundation_clathrates.json

At the moment, you can't disable the fluid on breaking, but I'll add a config option for that in the next release.

In the future for questions like these, please use the Discord. The issue tracker isn't a forum. Thanks. :)

**Comment by HurtsAsHell** [comment]
Okay;sorry and thanks

**Comment by HurtsAsHell** [comment]
can u share the discord's link?

**Comment by KingLemming** [comment]
https://discordapp.com/invite/uRKrnbH
