### ISSUE TITLE
[TE 4.1.1-237] New Igneous Extruder consumption configs broken in various ways

### ISSUE THREAD

**Issue by SanityCh3ck** [CoFH/Feedback#1025]
To both my dismay and relief I learned that this functionality had been gone and just made a comeback with greater flexibility.
However, while toying around with it I ran into some interesting behaviour:

a) Cobblestone, set to 10mB Lava/100mB Water
- ~~To operate, at least 1000mB of each liquid has to be present. While I'm perfectly fine with that, I do wonder if it is intended.~~
- Applying the augments to the Extruder causes it to not consume water at all, lava works fine though.

b) Cobblestone, set to 1100mB Lava/100mB Water
- With 1000mB of both liquids present, an operation starts. If the output slot is empty 1 Stone is generated, if it already contains Stone nothing happens. Then a new operation starts without consuming either liquid. Augments have no effect on this.
- With actually enough of both liquids (>1000mB) present, water and lava appear to be properly consumed, except with augments (same as above).

c) Smooth Stone, set to 1500mB Lava/1000mB Water
- With 1000mB of both liquids present, see b).
- With actually enough of both liquids present, water and lava appear to be properly consumed, even with augments.

I didn't test any Obsidian settings thus far, but I would expect them to produce similar results.

**Comment by KingLemming** [comment]
Yeah, it wasn't actually intended for anyone to make it cost more, since that's just kind of silly.

**Comment by SanityCh3ck** [comment]
Although I did just test scenarios b and c out of curiosity, I don't think they're that silly after all. Introducing a cost to cobblestone is just taxing the easy automation of what would otherwise be a free, albeit tedious, manual process. Applying that to obsidian would inherently drive the cost above 1000mB.
On second thought, the 1000mB requirement to operate does make perfect sense. As a wild guess, maybe instead using the maximum of 1000mB and the respective config value would get rid of that weird behaviour?

Since the TE source isn't public though I can't judge how much would actually be involved in fxing that.

**Comment by KingLemming** [comment]
At this point it's looking like the best option is to remove customization again. :) Augments threw a wrench into it that I don't really feel like messing with.

**Comment by SanityCh3ck** [comment]
Well, that's not good. I was planning on using that. I guess i'll have to think of some other balance point then.

**Comment by skyboy** [comment]
It'll work fine in 4.1.2

**Comment by SanityCh3ck** [comment]
I updated to 4.1.2B1-238 and everything appears to be sorted, with one exception:
The Level 3 augment still causes the Extruder not to consume water when producing cobblestone.

**Comment by skyboy** [comment]
Fixed.
