### ISSUE TITLE
[Suggestion] Expand limits for config values

### ISSUE THREAD

**Issue by OneEyeMaker** [CoFH/Feedback#1028]
Hello.
Subject mostly the same as in #849.
But I'm speaking not about Thermal Expansion, but about all Thermal mods.
Right now I suggest to expand limitations on such config values as:
- Base energy transfer for fluxducts (Thermal Dynamics),
- Base energy storage for each tool class (Thermal Innovation),
- Base charge rate for each tool class (Thermal Innovation).

And thank you  for your work!

**Comment by KingLemming** [comment]
Ehh...what ranges are you really interested in using?

Or is this just a request for the sake of a request?

**Comment by OneEyeMaker** [comment]
This isn't request just for the sake of a request. I'm currently working on modpack in wich I plan to move all Thermal mods to end-game stage. 
And all, what stops me right now is these 3 config limitations:
- Fluxducts transfer rate (config value limit can be safely bumped up to 100k RF);
- Tools (mostly drills) energy capacity and energy transfer rate (can be bumped up to 1M and 100k respectively without any problems with overlapping of Integer.MaxValue).
.

**Comment by KingLemming** [comment]
Tools are done. Fluxducts are not as simple as you think, so may end up being a hard no, sorry.
