### ISSUE TITLE
ArrayIndexOutoOfBoundsException:0 After removing optifine..

### ISSUE THREAD

**Issue by LoGiiKz-x-K1LLA** [CoFH/Feedback#1028]
So im trying to put together a modpack and have been getting error after error. This one comes when i try to load or create a world. 

Crash Report: https://gist.github.com/anonymous/ae260973705903b40279

**Comment by skyboy** [comment]
The error you posted and the error in the title are not the same, nor is the one you posted in any way meaningful.
