### ISSUE TITLE
[Thermal Expansion 1.10.2] Random crash when ExtraUtils2 pipe connects to dynamo

### ISSUE THREAD

**Issue by Bobynoby** [CoFH/Feedback#103]
Before the crash I was playing around with the Numismatic Dynamo. That one that accepts coins. I went to connect it to my power system. Next to it was a nearby extrautils2 transfer pipe and I didn't think to much of. After placing it down all of a sudden the server crashed.

Unable to list mods that were also running as there's 100+ and by the looks of it does not seem like any other mods were in effect.

Versions:
Forge: 1.10.2 12.18.3.2239
Thermal Expansion: 1.10.2-5.0.3.86
ExtraUtils2: 1.10.2-1.3.3

Crash Reports:
Server: http://pastebin.com/viTcfXPz
Client just acts as the server closed normally. So nothing special there.

**Comment by KingLemming** [comment]
What were you putting into the dynamo? Looking at the code, the crash literally doesn't make sense.

**Comment by Bobynoby** [comment]
The transfer pipes were transferring cobblestone and lava. And before I did place a Enderium Coin into the machine before I broke it. That's about it

**Comment by KingLemming** [comment]
Fixed. TE build 89.
