### ISSUE TITLE
Ehhh I don`t now why but i crash on my minecraft startup....

### ISSUE THREAD

**Issue by Karso12** [CoFH/Feedback#103]
I check if i had the latest java and i did I removed all my mods to see if its a mod issue but its not here is the crash report Please help    
http://pastebin.com/NdWWdH49 Im using forge10.13.2.1277 and im using the latest CoFH mods and core

**Comment by bochen415** [comment]
Please use http://pastebin.com or http://paste.ubuntu.com for crash logs.
The crash log isn't complete. Please post the complete logs.
Please post the mod version/versions and preferably MinecraftForge version when posting issues.
A qualified coder is on it's way to help diagnose the issue.

**Comment by Karso12** [comment]
Sorry for that i just updated the post Once again sorry and thanks in advance

**Comment by bochen415** [comment]
> im using the latest CoFH mods and core

Actually you overdid it.
Use the latest version from Curse.com marked as beta (not CurseForge), don't mix alpha versions with beta versions.
Your CoFHCore is an alpha.
Your ThermalExpansion is slightly out of date.

Redownload, test and come back.

**Comment by Karso12** [comment]
Will do

**Comment by Karso12** [comment]
I was using the version on the Team CoFH site At first i was not able to find the CoFH core on Curse And thanks it worked

**Comment by bochen415** [comment]
Close the issue to mark it as solved.
