### ISSUE TITLE
[Thermal Expansion] Tiles crashing world

### ISSUE THREAD

**Issue by NicosaurusRex99** [CoFH/Feedback#1030]
CofhCore: 1.12.2 - 4.3.9.2
MC:1.12.2
Forge:14.23.2.2627
TE 1.12.2 - 5.3.9.9
TF 1.12.2 - 2.3.9.4
Log: `https://pastebin.com/FhdeApRy`
Notes:
This is the debug world mode (press shift when changing world type). It is also in a dev environment

**Comment by KingLemming** [comment]
Sorry, but I'm not even going to attempt to address this unless you're on the most recent versions.

**Comment by NicosaurusRex99** [comment]
@KingLemming can confirm still happens on 
CofhCore : 4.3.11.6
TE : 5.3.11.14
TF : 2.3.11.8

**Comment by KingLemming** [comment]
Can you provide the log for that please? Because the log you posted doesn't make sense - those lines don't exist in the current version.

**Comment by KingLemming** [comment]
Oh wait, debug mode. Sorry, missed that before.

Yeah, debug mode sucks. Minecraft is stupid and it's unsupported. Don't use it.

**Comment by NicosaurusRex99** [comment]
Ahh, ok
