### ISSUE TITLE
[CoFH Tweaks v1.1.0-83] Using the latest test version of FastCraft

### ISSUE THREAD

**Issue by xJon** [CoFH/Feedback#1032]
With FastCraft v1.21 we couldn't even get inside the worlds, so I tried using v1.22-ctest18 and I was able to launch; yet there was a slight issue.
I couldn't get a single block to render.
![image](https://cloud.githubusercontent.com/assets/8945347/12702890/842b280e-c83d-11e5-9183-380549781ed1.png)
Is there anything to do? Or do we, the users, need to choose between the two mods?

**Comment by KingLemming** [comment]
You need to choose. See #481.
