### ISSUE TITLE
Satchel not auto-collecting items

### ISSUE THREAD

**Issue by Xiaminou** [CoFH/Feedback#1033]
I sat next to my mob farm in order to collect wills, using a satchel to collect the additional drops, however to my surprise the drops did not directly into the satchel.
However if I dropped items or used auto-collect for anything else, it works fine.

https://youtu.be/T7mPs-p0WYE

Minecraft: 1.12.2
Forge: 2641
Mods: [list.txt](https://github.com/CoFH/Feedback/files/1915889/list.txt)

**Comment by KingLemming** [comment]
What mob farm?

**Comment by Solousia** [comment]
Maybe the magnet thing? It put stuff in player inventory rather than “pickup” the item.

**Comment by KingLemming** [comment]
Never could get this to happen, sorry. I'm thinking it's some sort of tag being applied by one of the blocks involved. The magnet pulls the item to the player, it doesn't insert into inventory.
