### ISSUE TITLE
XP Dupe Bug

### ISSUE THREAD

**Issue by 2ndkirbyever** [CoFH/Feedback#1034]
Last night, I found out that I can use the Tome of Knowledge to take experience out of the Ender IO experience obelisk. When I took those levels out of the tome, I discovered that I had one extra level. Here's the dupe bug [in action](https://youtu.be/EnnhmJ5TmGw).

Forge: 14.23.3.2668
Ender IO: 5.0.21
Thermal Foundation: 2.3.11.9

**Comment by KingLemming** [comment]
You 100% sure that your Tome was empty?

I'm not getting any duping when testing with tanks, so this is likely something x-mod.

**Comment by 2ndkirbyever** [comment]
I am certain my tome is empty. I emptied it in between tests, and I am getting the same results. The tank I'm using is the Ender IO experience obelisk if that helps narrow down your results.

**Comment by KingLemming** [comment]
Please let EnderIO know about this. There is no such duping action with any other container, so I'm very confident that it's on their end.

The Tome has been tested to the extreme to make sure that the xp formula matches up with Minecraft *exactly*.

**Comment by 2ndkirbyever** [comment]
Okay. Thanks for your help.
