### ISSUE TITLE
Thermal Expansion tesseract GUIthrow 'Ticking memory connection' error

### ISSUE THREAD

**Issue by Theta1996** [CoFH/Feedback#1035]
I haven't had this problem until now, but every time I right-click on a tesseract from Thermal Expansion my client crashes and the crash log shows a Ticking Memory Connection error. I googled this a bit but couldn't find anything helpful. If anyone could help it would be greatly appreciated.

Crash log: http://pastebin.com/m2FUXuMf
[crash-2016-02-01_21.09.03-server.txt](https://github.com/CoFH/Feedback/files/113101/crash-2016-02-01_21.09.03-server.txt)

**Comment by KingLemming** [comment]
Offhand there's nothing in the log to suggest a problem with Thermal Expansion or any other CoFH mod.

**Comment by skyboy** [comment]
We need the server and client logs. The crash itself provides nothing useful.

**Comment by Theta1996** [comment]
I believe that this is the log you want:
http://pastebin.com/mfa5ruLe

**Comment by KingLemming** [comment]
There's still nothing in there that points to us in any way. It could be any number of mods that try to ride on top of GUIs.

**Comment by Theta1996** [comment]
To my knowledge, there are no other mods whic hare trying to use or ride on the tesseract GUI. There seem to be no other interactive blocks in the game which cause this same error. I never had an issue with any updates prior to this one, but I guess it could be any mod in my pack. I guess it's time to start fishing for the source

**Comment by skyboy** [comment]
That log was one of the many useless ones that FML stores every time the game launches. It'd be nice if it didn't bother creating that one.

The logs we need are fml-server-latest.log (if you run a dedicated server) and fml-client-latest.log

**Comment by Theta1996** [comment]
I have the right log this time, unfortunately it was too big to paste into Pastebin so I have uploaded it to Google Drive - The link is here: https://drive.google.com/open?id=0Bybhhr1KlBA3d0pMWWJjak43eHM

**Comment by skyboy** [comment]
The file is not public.

**Comment by Theta1996** [comment]
My apologies, try again, the file should be open now

**Comment by skyboy** [comment]
Does the error persist if you open the tesseract GUI with an empty hand?

**Comment by Theta1996** [comment]
The GIU functions normally when I'm holding either a vanilla item or nothing at all, so problem solved. Thanks man! Is there any reason in particular which causes this bug, or would it probably just be some kind of incompatibility with my mods?

**Comment by skyboy** [comment]
It's a bug with forge, being triggered the item in your hand.

**Comment by skyboy** [comment]
You can track the issue here https://github.com/MinecraftForge/MinecraftForge/issues/1354
