### ISSUE TITLE
Sawmill not processing some Natura woods

### ISSUE THREAD

**Issue by weirleader** [CoFH/Feedback#1035]
Hey folks,

Using FTB Revelation modpack and trying to process Natura wood in the Sawmill.  Can insert Amaranth, Sakura, Tiger woods but Sawmill will not process them.  Furthermore, when I leave GUI, the wood drops to the floor.  Checked the recipe and it implies this should work.  Tried it with Maple Wood (Natura) and it did work!

Just for the heck of it, I tried placing it via a hopper, but the problematic woods remain in the hopper.
Also tried updating to the most recent CoFH releases manually, but the behavior remained.  

For a list of all included mods (huge list!): https://ftb.gamepedia.com/FTB_Revelation

Thx!

**Comment by KingLemming** [comment]
Update Mantle. This is actually on their end. :) I reported it a while ago and the new build supposedly fixed it.

**Comment by weirleader** [comment]
Thanks for the quick reply!  Will take it over there...

**Comment by weirleader** [comment]
Sure enough, they fixed it 8 days ago; just tested it and it did the trick.  Nice!
