### ISSUE TITLE
please read this 

### ISSUE THREAD

**Issue by jelly1994** [CoFH/Feedback#1036]
please update the curse voice beta mod luancher for ur mod it does let me update to the lates\t version of ur mod so that i can play minecraft 1.7.10 modded

**Comment by KingLemming** [comment]
We have absolutely no control over any of that. None whatsoever. And please do not misuse the issue tracker in this fashion.

**Comment by jelly1994** [comment]
w is this miss using the issue tracker when this is a issue and i cant even get the right update versoin for ur mod when its not on ur website so u wanna tell me that this is not a issue u need to solve

**Comment by XFactHD** [comment]
Curse doesn't have anything to do with TeamCoFH. You can download the mod from curse, that's all. TeamCoFH does not have any control over the version that is provided by the curse voice launcher. To be fair, the 1.7.10 versions are on curse meaning that they can also be found in the curse voice launcher.

**Comment by jelly1994** [comment]
I can not find the latest version of your mod on teamcofh website or the
curse voice beta launcher or on the curse website

**Comment by XFactHD** [comment]
First, I am not part of TeamCofH, so it is not my mod. Secondly, which version are you looking for.

**Comment by jelly1994** [comment]
I am looking for cofh core version 1.7.10R3.1.1B1 or 1.7.10R3.2.0 and curse
voice beta launcher does not have it and its not on their website or curse.
Com I can't find either one of those versions any where

**Comment by XFactHD** [comment]
What makes you think that those versions exist?

**Comment by jelly1994** [comment]
Every time I try to play minecraft using the curse voice beta launcher it
tells me that it could not find either one of those versions

**Comment by XFactHD** [comment]
Then you are using some mod that is depending on an invalid version.

**Comment by jelly1994** [comment]
K if I post the fml on minecraft forum and email you a link would you be
willing to take a look at it and see if you can find the mod that is
causing this problem and let me know
I would do it myself but I don't know what to look for

**Comment by jelly1994** [comment]
http://www.minecraftforum.net/forums/support/modded-client-support/create-thread

**Comment by jelly1994** [comment]
sorry didn't realize that I didn't paste the fml log I will send you a
second link

**Comment by XFactHD** [comment]
The FML log doesn't tell anything about dependencies. You need to take one mod after the other out of the pack and when the error stops then you found the offending mod.

**Comment by jelly1994** [comment]
I will email you the fml log

**Comment by XFactHD** [comment]
Again, the FML log doesn't help, you have to take the mod pack apart to see what mod is causing this.
