### ISSUE TITLE
[Thermal Expansion 4.0.3B1-218] Energy Cell controls visual bug/glitch.

### ISSUE THREAD

**Issue by St0rmbow** [CoFH/Feedback#1037]
Visual bug/glitch: http://imgur.com/UYKSn6x side configuration control not showing (even though still clickable) on all tiers of energy cells (tested in creative). Restarting the game and reloading the world doesn't fix the issue. No optifine installed.

**Comment by skyboy** [comment]
Don't report issues with old betas, current release has several months of code changes over the version you have.

**Comment by St0rmbow** [comment]
Thank you! I will update my mods then.
