### ISSUE TITLE
[Suggestion] [Doc] Add fertilizer use expectation to the Nutrient Recovery wiki page

### ISSUE THREAD

**Issue by KaseiFR** [CoFH/Feedback#1037]
Hi,

The [Nutrient Recovery augment](https://teamcofh.com/docs/augment-nutrient-recovery/) wiki page only includes the fertilizer reuse chance per round, not the expected total number of use. I suggest adding a column to the effect table, something like that:

| Installed amount | Fertilizer reuse chance | Energy increase | Expected use per fertilizer |
|------------------|-------------------------|-----------------|-----------------------------|
| 1                | 20%                     | + 5%            | 1.25                        |
| 2                | 40%                     | + 10%           | 1.67                        |
| 3                | 60%                     | + 15%           | 2.5                         |
| 4                | 80%                     | + 20%           | 5                           |

The math I used is here:
https://www.wolframalpha.com/input/?i=sum+p%5E(n-1)+*+(1-p)+*+n+with+n+%3D+1..inf
https://www.wolframalpha.com/input/?i=Table+%5B1+%2F+(1-x),+%7Bx,+0,+.8,+0.2%7D%5D

**Comment by KingLemming** [comment]
You could have just PR'd this to the repo you know. ;)

**Comment by KaseiFR** [comment]
I had no idea the wiki sources were public !
Will do next time.

**Comment by KingLemming** [comment]
No worries. @Tonius has been assigned. :)

**Comment by Tonius** [comment]
Moved to CoFH/cofh.github.io#58
