### ISSUE TITLE
[TE] [World crash] Exception getting block type in world

### ISSUE THREAD

**Issue by St0rmbow** [CoFH/Feedback#1038]
World crashed on start after updating Thermal Expansion and Thermal Foundation to versions as of January 26, 2016. The world was generated with previous versions of mentioned mods. Crash report: http://pastebin.com/zHKAizeZ
_java.lang.IllegalAccessError: tried to access class cofh.api.transport.IEnderAttuned from class cofh.lib.transport.EnderRegistry_
P.S. Rolling back to TE 4.0.3B1-218 and TF 1.2.0-102 fixes the issue.

**Comment by skyboy** [comment]
This is caused by EnderIO.
