### ISSUE TITLE
Thermal Innovation Bore Crash.

### ISSUE THREAD

**Issue by Fortist** [CoFH/Feedback#1039]
So, I was in in the Nether, and I went to collect a spawner and this crash happened.
https://pastebin.com/pbVBAUKc

Though, this could be a myriad of things. My drill was enchanted with silktouch (possibly a part), The spawner was a wither skellington spawner, I have a mod (or two) that changes spawners being silk touched, and I was using a Refined Storage Addon Network bag (Basically shoves items collected into the network)
Also, looking into the crash a bit, it mentions chickencore, and a newer mod called "Vise" which changes gui scales and what not.

Gonna look into it a bit.

**Comment by KingLemming** [comment]
at com.elytradev.vise.Vise.onPreRenderGameOverlay(Vise.java:180)

Yeah, it's Vise. I dunno wtf it's doing but basically it seems as though it called for re-registration of the textures when it really shouldn't be doing that.

**Comment by covers1624** [comment]
Actually the nullpointer is coming from inside the lambda not the method, I think it's invalid metadata.
