### ISSUE TITLE
Portable Tank, Visual Bug.

### ISSUE THREAD

**Issue by Masuro-Takohiko** [CoFH/Feedback#1040]
I found visual bug, it can be caused when you place 2 portable tanks to each other.
And when you fill upper tank, lower tank also fills.
Here is the [video](https://youtu.be/4gdPMRLV1Us)

**Comment by KingLemming** [comment]
The upper tank filling the lower tank is working as intended - you have it auto-ejecting the one below it. ;)

The visual bug is infact purely visual and client only, caused by a weird quirk of Forge's fluid handling.
