### ISSUE TITLE
Ore generation can't be disabled.

### ISSUE THREAD

**Issue by dragon3025** [CoFH/Feedback#1043]
This might also be true for oils and clathrates, but I added "enabled": "false", to all the ores in 01_thermalfoundation_ores.json and they still generated. I also tried replacing the entire text with just "{}", but it still generated everything. I have an example of the 01_thermalfoundation_ores.json I used: https://pastebin.com/ztxgqndd

**Comment by KingLemming** [comment]
Okay so, you made me double check here to be sure that the code isn't broken somehow.

It isn't. Disabling the gen works, and clearing the file completely DEFINITELY works.

Which means that you are editing the wrong files somehow. CoFHWorld cannot generate things if the file is blank, that is literally impossible and would imply that reality itself is somehow broken. Reality isn't broken and neither is the code.

Feel free to swing by the discord for tech support, but this is 100% just you doing something wrong.
