### ISSUE TITLE
Tutorial text on GUIs with +/- buttons should mention shift/control

### ISSUE THREAD

**Issue by Gunner76th** [CoFH/Feedback#1043]
On the retrievers, there is the -/+ option for the "Inc. Max Total Items in Inventory" setting. While the -/+ buttons are nice in theory, for any amount over about 32 it becomes a serious PITA. For example, say you need to maintain 4+ stacks of items in the inventory of the connected inventory, as it is, you have to sit there and click the + button ideally 256 times assuming that your server is running a perfectly, and your lag to the server does not interfere. 

My suggestion is this, instead of only having the -/+ buttons, could it be possible to add or change it over to a data entry field that is coded to only accept numeric entries? And if it is possible, have it default to 1,728 items (which is the max number of items in a standard vanilla single chest at 9 stacks per row, 3 total rows). That was it would function similarly to the current "infinite" default setting, but would allow the user better flexibility and easier selection of the number of items to allow to be pulled in.

**Comment by KingLemming** [comment]
Sounds like somebody has never tried holding shift or Ctrl...

**Comment by Gunner76th** [comment]
Nope, I did not know that was an option. Perhaps amending my previous suggestion, and instead having that show up as a pop up? That way those who are not familiar with that ability would know it is an option.
