### ISSUE TITLE
1.12.2 Client crash when magnet is shift clicked

### ISSUE THREAD

**Issue by DingoX3** [CoFH/Feedback#1045]
Crafted the first tier magnet. Wasnt sure how to use it so i shift right clicked it while it was in my hand. Then my client crashed to desktop.

Modpack: All The Mods 3 v.5.9.3b
Thermal Inovation: ThermalInnovation-1.12.2-0.1.0.3-universal
Cofh core: CoFHCore-1.12.2-4.3.11.6-universal
Forge: 2669

Full crash: https://pastebin.com/p33aYadN

**Comment by KingLemming** [comment]
That shouldn't be possible and I absolutely can't replicate it whatsoever, but I'll be sure there's a mitigation just incase something really weird happens.
