### ISSUE TITLE
Suggestion for Machines

### ISSUE THREAD

**Issue by SonarSonic** [CoFH/Feedback#1047]
Could you possibly add a way to get the current progress of a machine in ticks and the completion time in ticks? You may already have this but I couldn't seem to find it in CoFHLib.

**Comment by KingLemming** [comment]
For what purpose exactly?

**Comment by GenuineSounds** [comment]
I would assume for use in conjunction with computers. At least that's the first thing that came to my mind.

**Comment by SonarSonic** [comment]
Mostly for use with my mod which is basically for Displaying Info about blocks. However, I could see other uses for it also.

**Comment by KingLemming** [comment]
Not possible then. You're asking that we not only provide a way to get that info, but send it to the client every single tick.

**Comment by SonarSonic** [comment]
No only server side my mod does all the syncing already.

**Comment by KingLemming** [comment]
And actually, thinking about this more, it's not possible anyways since the machines don't work in ticks and are fundamentally variable speed.

Sorry, no can do.
