### ISSUE TITLE
Thermal Dynamics Fluiduct and ExtraPlanets Basic Densifier crashes game

### ISSUE THREAD

**Issue by billyma6** [CoFH/Feedback#1047]
Hello, I am using Thermal Dynamics 2.3.11 with the ExtraPlanets 0.3.3 addon for Galacticraft 1.12.2.  When I connected a Super Luminar Fluiduct to the Basic Densifier side and set the Portable tank to output, the game crashed. 

Steps to reproduce:
1. Place a Basic Densifier, and connect a Super Luminar Fluiduct onto (your) left side of the machine.
2. Place a portable tank on top of that fluiduct.
3. Use the crescent hammer and set the tank to output (orange bottom)
After it tries to output, it should crash your game.

Here's my list of mods: https://pastebin.com/mcaHthE3

And Here's my crash log: https://pastebin.com/T63VKSUV

I have already posted about this bug on the ExtraPlanets github repo, so they should be notified soon.

**Comment by KingLemming** [comment]
Yeah that's gonna be 100% on their end.
