### ISSUE TITLE
(1.7.10) CoFH Core conflicing with Optifine.

### ISSUE THREAD

**Issue by ZcanKal** [CoFH/Feedback#1048]
CoFHCore-[1.7.10]3.1.4-329

OptiFine_1.7.10_HD_U_E7

1.7.10-Forge10.13.4.1614-1.7.10

I crashes whenever I try to run Minecraft with Optifine in the pack, it seems to be CoFH Core conflicting with it.

[crash-2018-04-22_15.15.08-client.txt](https://github.com/CoFH/Feedback/files/1945049/crash-2018-04-22_15.15.08-client.txt)

**Comment by KingLemming** [comment]
No. That's CoFH tweaks. Which yes, conflicts with Optifine. Pick one.

**Comment by ZcanKal** [comment]
Thank you, I'm going to be honest, I forgot I had CoFH Tweaks in there.
