### ISSUE TITLE
[Thermal Foundation] Suggestion on Tinkers Construct Handlers

### ISSUE THREAD

**Issue by AlexanderBulanov** [CoFH/Feedback#1049]
I am currently rewriting all of Tinkers Construct material stats with Minetweaker. However, Minetweaker doesn't work on metals like Shiny and Silver (there are two sets of Silver tool parts, there are also two sets of Platinum tool parts, one of them being Shiny). Is it possible to add an option in the common.cfg file to edit ranged statistics of Silver and Shiny materials that come from Thermal Foundation?

**Comment by skyboy** [comment]
Duplicate materials are not the fault of Thermal Foundation, there is another mod adding them.
