### ISSUE TITLE
Main Menu screen render issue

### ISSUE THREAD

**Issue by teoryan2** [CoFH/Feedback#105]
I am not sure what has happened. Added in CoFHcore and CoFHlib and i got this problem where the main menu does not render

https://paste.ee/p/JcgqM

**Comment by teoryan2** [comment]
This is for 1.10.2
The same problem is occurring for 1.7.10

**Comment by KingLemming** [comment]
Can you get this to happen with *only* CoFH mods?

**Comment by covers1624** [comment]
Seems to be an issue with your graphics card not liking frame buffers, try updating your drivers, short of that you may have to dissable the forge loading screen.

**Comment by teoryan2** [comment]
@KingLemming I only have CoFHCore and CoFHlib in the mods list

**Comment by teoryan2** [comment]
@covers1624 How do i do that?

**Comment by KingLemming** [comment]
Add "-Dforge.forceNoStencil=true" to your JVM arguments. This is a Forge bug.
