### ISSUE TITLE
Client crash NoClassDefFoundError: cofh/thermalexpansion/gui/container/storage/ContainerSatchel

### ISSUE THREAD

**Issue by ProsperCraft** [CoFH/Feedback#1050]
https://gist.github.com/ProsperCraft/44613c2077852f7390bf5ee9b83d02a1

Forge 14.23.1.2554

ThermalExpansion-1.12.2-5.4.0.19-universal.jar

**Comment by ProsperCraft** [comment]
Server does not crash, only the client.

**Comment by KingLemming** [comment]
This is why I originally removed InvTweak support from Satchels. They need to get this fixed. >:(

**Comment by KingLemming** [comment]
Hotfix up.

**Comment by ProsperCraft** [comment]
Thank you, waiting on curse approval.
