### ISSUE TITLE
[COL] after updating to ThermalInnovation-1.12.2-0.2.0.4 from 0.1.0.3

### ISSUE THREAD

**Issue by drakray** [CoFH/Feedback#1051]
Crash on load
https://pastebin.com/Dn1WuSn6
Bunch of UE in Details

**Comment by KingLemming** [comment]
Totem Expansion.

**Comment by drakray** [comment]
Found in debug.log https://pastebin.com/CFsu3qAF

**Comment by KingLemming** [comment]
You have a bad version of Baubles. Go download the latest. It's a common issue to both of those mods.

**Comment by drakray** [comment]
I'm already using the latest, 1.5.2
My modpack was working before updating TE, RA, TC,TI, TD, TF, CoFHCore, ThaumicJEI, BoP, FamFauna and JEI

**Comment by drakray** [comment]
Trying something

**Comment by KingLemming** [comment]
Something happened with Baubles with the TC release. It's strange. I had to update the API on my end.

**Comment by drakray** [comment]
renaming Bauble to 0-Bauble seems to fix, seems like a dependency problem?

**Comment by KingLemming** [comment]
Yeah, what's happening here is that you have a mod which is including the Baubles API inside itself. That's bad juju and that dev needs a bus dropped on them.

**Comment by drakray** [comment]
Got this now, https://pastebin.com/jUgpy1WV, new problem, caused by recent change

**Comment by KingLemming** [comment]
Yeah, API rework. They need to update to match, sorry.

**Comment by drakray** [comment]
its ok, I must now find the Bauble culprit, and I just noticed BaseMetal of the changing API
