### ISSUE TITLE
[TD] [Suggestion] RF to EU Servo

### ISSUE THREAD

**Issue by FirzenDark** [CoFH/Feedback#1051]
First want to say thanks for the wonderful mod. Especially the fluctuating item duct pipe. Supplying power and can be used to extract items. 

I would like to suggest, (maybe there is something like this already, not sure) a servo that could convert the RF power to other types of power.

**Comment by skyboy** [comment]
No.

**Comment by FirzenDark** [comment]
Thanks for the straight answer. Much appreciated
