### ISSUE TITLE
cyclic assembler crash

### ISSUE THREAD

**Issue by Joshwoo69** [CoFH/Feedback#1054]
Log:
http://pastebin.com/4RuaZ2x4

Using mod from thirst mod from [here](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1282656-thirst-mod-1-8-15-updated-to-minecraft-1-8-100k)
and put the recipe of water bottle and charcoal filter crashes the game.

PS. using latest versions of TE

Openeye Report: http://openeye.openmods.info/crashes/f6e79b05eddda4db1b35fd0beaa8b871

**Comment by skyboy** [comment]
Duplicate of https://github.com/CoFH/Feedback/issues/1018
