### ISSUE TITLE
CoFHCore-[1.7.10]3.1.1-324 - Crash on Start Up

### ISSUE THREAD

**Issue by badams2193** [CoFH/Feedback#1055]
http://pastebin.com/rFiRuAGp

At this point, I just downloaded the latest Java, Version 8 Update 73, and uninstalled all previous versions.
I'm running the most recent forge, forge-1.7.10-10.13.4.1558-1.7.10, and have tried with  just CoFH, Thermal Foundation, and Thermal Expansion in the folder as well as only CoFH in the folder. Same error message every time. If this is still something on my end, I apologize. I noticed that this version of CoFH was very recently updated, so I figured I'd give you any error message I got after checking the basics. Thank you!

**Comment by skyboy** [comment]
There is no crash in your log.
