### ISSUE TITLE
[1.12.2] Random crash

### ISSUE THREAD

**Issue by TheSnowyChickens** [CoFH/Feedback#1057]
Hello,
at first, I dont know if the crash comes from your mod, but in the crash report stand something with TE and my task, what I did, has a connection to TE stuff. :)

https://paste.dimdev.org/saluqigepa.txt

In the log Link is a list with all my mods + versions from forge, TE, TF, TD, IE and and and.

The log is created with the "VanillaFix" mod.

-------------------------
My Task:
I right clicked with 1 HV Connector from IE on a basic energy cell.

**Comment by KingLemming** [comment]
Does this consistently happen or was it a one off? Because after tracing the code...yeah, literally makes no sense.

**Comment by TheSnowyChickens** [comment]
For the moment, it was the first time, but maybe it stands in context with this bug : 
https://github.com/BluSunrize/ImmersiveEngineering/issues/2699

But in 1.11.2 I had this bug when dismantling a energy cell with the crescent hammer.

Because this type of bug destroys the block above the input of IE machines and also your energy cell is completely out of work, no interaction with it is possible + the one probe shows an error.

**Comment by KingLemming** [comment]
Hmm. This sounds like it's something IE is doing which accidentally wipes out the Tile Entity.

Can you make it happen with anything else? I think you've just figured out the cause.

**Comment by TheSnowyChickens** [comment]
Your resonant flux ducts lose the contact to each other, Ender IO Ender Energy Conduits lose the connection and the main conduit is bended, IE capacitors dont work, IE connectors change there rotation and many more. xD

I have already github issues to this points agains Ender IO and IE.^^

**Comment by TheSnowyChickens** [comment]
I think this is a new The one probe bug? I will report it to the TOP Github, except it is a little problem from you. I'd rather ask first. :D

![2018-04-28_21 35 00](https://user-images.githubusercontent.com/29357962/39400199-10d6d348-4b2c-11e8-88df-2a40eb09614b.png)
ALL blocks show that. (machines and more)

**Comment by malte0811** [comment]
Something potentially interesting about that screenshot: The IE wire seems to end at the point where the connector should be (if it was placed against the energy cell) rather than the point where it is visually. This may just be because of the perspective, @TheSnowyChickens could you confirm this?
The visual wire offsets are calculated on the client side, so the connector model and the wire model seem to be generated from different data for some reason (they are both part of the connector block model/`IBakedModel`).

**Comment by TheSnowyChickens** [comment]
This bug I reported also to Immersive Github, it is a type of bug, where the block above the energy input is "destroyed" after relog / load the world (If I replace it new (connector on top of the energ cell) and reload the world, this bug occures again and again and again)

**Comment by KingLemming** [comment]
Wish I knew what the original cause was, but on my end, it's simply the result of the tile having been wiped out. And another mod is doing that. :/

**Comment by TheSnowyChickens** [comment]
Okay.
