### ISSUE TITLE
Bug with Retriever in mod ThermalDynamics-[1.7.10]1.1.0-161

### ISSUE THREAD

**Issue by q178666380** [CoFH/Feedback#1057]
Item full name : item.thermaldynamics.filter
mod version [minecraft 1.7.10] - 1.1.0-161

the Retriever can Extract from Container by pipeline,but when Number of extraction is more than the
Container have,it cause the count of item in  container to be negative
Below is the result that i seen in nbtedit,the count of item is negative
![error](https://cloud.githubusercontent.com/assets/9610060/12918089/27090be0-cf78-11e5-8dec-f49506c6cbf4.png)

**Comment by KingLemming** [comment]
We'll need a video of this as we've never seen any evidence that this can happen.

**Comment by skyboy** [comment]
Additionally, does the problem present in the 1.2.0 alpha release (note: it's for testing only, not general use)?

**Comment by XFactHD** [comment]
Are you using any third party server software like kcauldron? Can you reproduce this with a vanilla chest?

**Comment by q178666380** [comment]
I have test ,it looks like only happened if the extraction boxes is Hungry Chest in M-Thaumcraft-1.7.10-4.2.3.5  whatever multiplayer or single games,maybe is a bug with Thaumcraft in item update code

**Comment by q178666380** [comment]
the link of video zip
http://pan.baidu.com/s/1hrqDnqk

**Comment by KingLemming** [comment]
This is entirely on ThaumCraft's end.
