### ISSUE TITLE
Thermal Dynamics 1.12.2 Alone - Can't find a wrench that works

### ISSUE THREAD

**Issue by AbieTheFishman** [CoFH/Feedback#1058]
Have just  Thermal Dynamics and Core installed
None of the wrenches I have work on Itemducts  and the like - for turning off connection and such

Wrenches tried for mods installed
- Buildcraft
- Forestry
- Gadgetry
- TechReborn

**Comment by KingLemming** [comment]
Crescent Hammer works. It's part of Thermal Foundation, which is required for Dynamics.

**Comment by AbieTheFishman** [comment]
Damn... I keep forgetting your wrench is a hammer!

I do very much appreciate your work.

Thanks

**Comment by KingLemming** [comment]
Well it's a wrench, but anything is a hammer when you need it to be.

I'll see about adding flavor text so it shows up in JEI.
