### ISSUE TITLE
CofhCore 3.0.0B9-106 "Alpha" currently in FTB Resurrection and Infinity packs

### ISSUE THREAD

**Issue by eXiGe** [CoFH/Feedback#106]
Figured you should know.
https://feedthebeast.atlassian.net/wiki/display/PML/Infinity+1.7+1.0.1
https://feedthebeast.atlassian.net/wiki/display/PML/FTB+Resurrection+1.0.1

Causing a bit of problems with satchels and RA tools.
http://forum.feed-the-beast.com/forum/infinity-1-7-10.190/
http://forum.feed-the-beast.com/forum/resurrection-1-7-10.177/

I guess my suggestion of informing people properly about your "Alpha versions" wasn't seen or was ignored. Oh well, GLHF.

**Comment by KingLemming** [comment]
We did inform people. But we can't fix stupid.

**Comment by eXiGe** [comment]
Then who am I to argue, I won't interrupt your desire to insult the ignorant and uninformed anymore.

**Comment by KingLemming** [comment]
FTB has *long* known not to use alphas. For some reason, they derped hard here.

**Comment by eXiGe** [comment]
What does the B in 3.0.0B9-106 stand for? Where is it stated on CurseForge, "DO NOT DOWNLOAD HERE" ? Name any other Dev(s) that use CurseForge as a Dev Build dump?

I think FTB made a fair mistake as did many others. Let's just go with "You can't fix stupid" though, I know in this case, I surely can't.

**Comment by KingLemming** [comment]
What does the "A" on CurseForge mean? Means alpha. The filename having B in it is a limitation of CurseForge; we are unable to change it specifically for those builds and it's something CF is working on.

**Comment by eXiGe** [comment]
Do you think that "A" has been sufficient? How many individual times have you had to tell people they should be downloading from Curse only? Judging by CofhCore's recent download numbers on CurseForge, you need only type it a few hundred more.

**Comment by KingLemming** [comment]
It hasn't been, no. And I'm annoyed with the situation, but it's being resolved through other channels. We're dealing with Curse right now to try and enact some changes.

I'm not sure what you're really looking for here. The mistake in this particular instance was that the member of the FTB team in charge of that pack screwed up HARD. The rest of the FTB team is aware of how it works, and I know they've already given him some head slaps.

Will it get rectified? Sure. Will it take time? Yes. But that's okay.

**Comment by eXiGe** [comment]
I can understand your annoyance, but I can't help but think it could have been rectified sooner. I brought up the issue 17 days ago here.

https://github.com/CoFH/Feedback/issues/49#issuecomment-71696712

My problem is that you are blaming everyone that has downloaded these versions, berating them for something that wasn't and still isn't documented in the appropriate areas to prevent further downloading.

I don't know what I am looking for either, or why I even care. I understand you deal with a lot of ignorance here, but in this case, I don't feel people deserved the full brunt of the blame.

**Comment by KingLemming** [comment]
Pretty much immediately following your comments we changed things around and tweeted that people shouldn't be using CurseForge. We don't have any control over the actual CurseForge page.

As far as berating people, I've seen a lot of "I read the instructions and did exactly what they said, and *this* happens," at which point they are outright lying and that's something that should not be tolerated, as the instructions quite clearly state to use Curse, and the links all point to Curse.

It's one thing if people download an alpha and have an oops - it's another thing entirely if they lie and tell us they did not.

**Comment by eXiGe** [comment]
I would think it bold to call people outright liars, but perhaps I give them too much credit. It's a shame about the limited access you have to curseforge, I feel that would have been your best bet to cull the issue. I apologize for my snarky comments. Thanks for your time.

**Comment by KingLemming** [comment]
You may be correct, but basically if there's a sign that says "Go west for an apple, and then you go east, end up with a banana, and then scream at me because you wanted a banana and swear that you read the sign...well..."

Perhaps you saw the sign, but you didn't read it. It might not be an intentional lie, but it's definitely a problem.

We're working on the whole thing, and no offense taken. The whole thing could be handled better, I agree. We've started putting alphas of TE up there as well, which mitigates it in so far as updating all mods at the same time should not cause too many issues.

**Comment by eXiGe** [comment]
I have to say, the metaphor pre-edit gave me a chuckle. :)
