### ISSUE TITLE
Feature request, sawdust to paper!

### ISSUE THREAD

**Issue by killerscorpion** [CoFH/Feedback#106]
In 1.7.10 you could make paper from three sawdust. In 1.10.2, that recipe is no longer around from what i see. Please add it back?

**Comment by codewarrior0** [comment]
Isn't 3 Sawdust -> 6 Paper a recipe added by Mekanism? IIRC, it worked with TE sawdust in the past due to OreDict tags.

TE always had 4 Sawdust, 1 Water Bucket -> 2 Paper, which you could easily automate using a Cyclic Assembler and Aqueous Accumulator.

**Comment by killerscorpion** [comment]
i never played using mekanism, but i do remember the 4 sawdust and 1 water bucket recipe. I swear i remember putting in 3 sawdust to get one paper though as a normal shapeless recipe though. Anyways, theres no way to get any paper without sugar canes right now.

**Comment by KingLemming** [comment]
It was wood pulp actually, and not sawdust. But we removed that item, since it was so single-purpose.

Let me think on it.
