### ISSUE TITLE
Tool tip names in satchels 

### ISSUE THREAD

**Issue by Weissmoon** [CoFH/Feedback#1060]
If an item uses NBT to determine it's name and there are more than one in a satchel, the tool tip for the satchel will display the name of the first item for the all the items of the same item ID.

![2016-02-10_17 19 57](https://cloud.githubusercontent.com/assets/6648797/12967520/206f69ce-d01c-11e5-835c-8dc674032764.png)

![2016-02-10_17 20 03](https://cloud.githubusercontent.com/assets/6648797/12967523/26584e14-d01c-11e5-869a-9e0620a6654a.png)
![2016-02-10_17 20 07](https://cloud.githubusercontent.com/assets/6648797/12967525/2c8eaeae-d01c-11e5-9e29-e72e3d2ce558.png)

**Comment by KingLemming** [comment]
I'm not 100% sure if this is something that should be addressed, honestly. NBT comparison gets ugly and providing a summary of things in the Satchel tends to be more useful than listing every single name.

**Comment by KingLemming** [comment]
"Fix" is currently in. I'm still iffy on it though.
