### ISSUE TITLE
thermal dynamics filters and servos

### ISSUE THREAD

**Issue by yudge03** [CoFH/Feedback#1061]
will not take saplings to filter or any items

**Comment by KingLemming** [comment]
Can't replicate this at all. Please provide a video.

**Comment by KingLemming** [comment]
I'm telling you, I can't make this happen. Filters and servos correctly accept items. They work.

**Comment by yudge03** [comment]
Okay I haven't been on Minecraft since last night cuz it wasn't working I
just logged on to try it since you said it's working and it's working now
must have been a glitch in my Minecraft I'm sorry to bother you

**Comment by KingLemming** [comment]
Fair enough.
