### ISSUE TITLE
Cache Duplication Bug

### ISSUE THREAD

**Issue by Programmix** [CoFH/Feedback#1063]
Mod: Thermal Expansion (v [1.7.10]4.1.1-237)
Mod list: http://pastebin.com/NZ6DDr5Q

Rapidly depositing and withdrawing items from a cache will cause the items to be duplicated, likely because of desynchronization and/or lag between the server and client.

**Comment by skyboy** [comment]
Make a video showing that it's not a client-side only (ghost items) issue

**Comment by Programmix** [comment]
Here's a link to a video showing that these aren't ghost items. I did this in singleplayer, and the issue still occurred. I suggest it's possible that this is a result of the InventoryTweaks mod.

https://youtu.be/DjRbzQfnEwI

**Comment by GenuineSounds** [comment]
Same, made a video and said something on IRC then saw this.

https://www.youtube.com/watch?v=luKRQImjtAo

My thoughts were also InventoryTweaks, can confirm it doesn't behave like this with any other carrel type item.

**Comment by GenuineSounds** [comment]
Just a little more info: 

Double clicking to add all from inventory will remove all, then a stack will appear because of Inventory Tweaks' refill thing. Creating a stack. So long as you had two or more stacks of whatever you're adding into the cache. And of course if you double click fast enough.

**Comment by GenuineSounds** [comment]
UPDATE: The stack in the inventory IS a ghost stack; however, when double clicking it has already added the extra stack.

**Comment by GenuineSounds** [comment]
UPDATE: Last update hopefully, holding right click and single clicking the cache will dupe an entire stack, no need to have more than the one stack in the inventory of your player. It's nasty.
