### ISSUE TITLE
Alchemical quiver (and Redstone Arsenal quiver) suggestion

### ISSUE THREAD

**Issue by Fortist** [CoFH/Feedback#1065]
Dont know if it's possible, but a baubles body slot quiver would be great addition to the quivers

**Comment by KingLemming** [comment]
Not possible with a hard dep on Baubles I'm afraid, so won't be doing it.

Also, I really don't understand why people are so gung ho on converting items which work perfectly fine in Inventory into Baubles. Bauble slots are more valuable. It's actively worse to use such an item as a Bauble.
