### ISSUE TITLE
Blizz & Blitz & Basalt Bug

### ISSUE THREAD

**Issue by Wasabules** [CoFH/Feedback#1066]
If i spawn Blitz with a "Blitz egg" (minecraft vanilla), i spawn a Basalt.
And, if i kill a Blizz, Blizz drop Blitz Rod and Niter.
If i set a Blizz in a Soul Vial (Ender IO), i have a soul vial of Bliz

The shoot of Blizz is not normal oO
http://image.noelshack.com/fichiers/2016/06/1455390029-2016-02-13-19-57-08.png
http://image.noelshack.com/fichiers/2016/06/1455390026-2016-02-13-19-57-15.png
http://image.noelshack.com/fichiers/2016/06/1455390035-2016-02-13-19-57-30.png
http://image.noelshack.com/fichiers/2016/06/1455390033-2016-02-13-19-57-35.png

I use latest version of Thermal Expension/Dynamics/Foundation and CoFH Core.

**Comment by KingLemming** [comment]
We in no way experience any of this and nobody else is reporting it.

Can you make it happen with *only* CoFH mods? If not, another mod is interfering somehow.

**Comment by bookerthegeek** [comment]
Is this on a server? We are experiencing the same issue, just have not had the time to debug it yet. (Dirty enviroment, need to test in clean forge enviroment.)

**Comment by Wasabules** [comment]
We are a community of some players and we all have the same problem.
This is therefore a server.
I tested without any other "mod" but when I spawn a Blitz with egg, its spawn a Basalt

**Comment by Wasabules** [comment]
.. ?

**Comment by KingLemming** [comment]
You didn't answer if you can make this happen with only CoFH mods. I'm about 99% sure this is x-mod interference.

**Comment by bookerthegeek** [comment]
KL, I'll test tonight and post here for you.

**Comment by JennyLeeP** [comment]
This is happening on my server as well. Been a bit lazy to figure it out.  With 196 mods some times too much effort to try 1 mod at a time to narrow it down, especially since it is not a crash bug.  If I had to guess though it say it might have something todo with SpecialMobs.  Thought I would give my 2 cents since this is still an open issue.
