### ISSUE TITLE
[1.12.2] No ore generation

### ISSUE THREAD

**Issue by ZoeyDaFawn** [CoFH/Feedback#1067]
So for some reason, Thermal Expansion is not generating any ore.. Sadly Calclavia has abandoned my prime solution to this which was the mod that added in a lot of ores other mods use. Me and a few friends have been attempting to use galacticraft as a substitute. Only problem is A, to much lag from that mod, and B, silver is not apart of it..

We are basing all our mods in 1.12.2 so if there is a version with this not being a problem then please do tell!

**Comment by KingLemming** [comment]
Do you have CoFH World installed?

**Comment by ZoeyDaFawn** [comment]
I have:
CoFHCore-1.12.2-4.4.1.12
and
ThermalExpansion-1.12.2-5.4.2.27

**Comment by KingLemming** [comment]
Need a modlist and logs then please.

Either you've actively killed the CoFH World generation or you have another mod which is doing it.

**Comment by ZoeyDaFawn** [comment]
Full mod list:
Backpacks Mod
Block Armor
Buildcraft
CodeChickenLib
CoFHCore 4.4.1.12
Ender Storage
Extreme Reactors
Familiar Fauna
Forgelin
Galacticraft Core
Industrial Forefgoing
inventory tweaks
just enough items
micdoodlecore
optifine
redstoneflux
reforged mod
teslacorelib
thermaldynamics
thermalexpansion
thermalfoundation
treecapitator
zerocore

**Comment by ZoeyDaFawn** [comment]
I also have not touched the forge mod list in the main menu. Even then I just checked and CoFH's config is grayed out

**Comment by ZoeyDaFawn** [comment]
Wrong button .-.

**Comment by KingLemming** [comment]
I literally don't see CoFH World in that list. You said you had it.

**Comment by KingLemming** [comment]
https://teamcofh.com/downloads/

See the note with Thermal Foundation. You need World if you don't have any other oregen.

**Comment by ZoeyDaFawn** [comment]
Oh my god ok. . . I didn't realise there was more then one CoFH..
