### ISSUE TITLE
Viaduct Jittering with MorePlayerModels 2 Installed

### ISSUE THREAD

**Issue by minimuss01** [CoFH/Feedback#1067]
When travelling through a viaduct with moreplayermodels 2, your camera/player model jumps up and down rapidly. Example: https://i.gyazo.com/bec3be3f30a9dfe6a179ddf041dd5ddf.gif
Using CoFH Core 3.1.1-324, TD 1.2.0B2-169, TE 4.1.1-237, TF 1.2.2-211, MPM 1.7.10b.

**Comment by KingLemming** [comment]
This is probably not fixable simply because MorePlayerModels 2 does some extreme base editing and there's no expectation of compatibility.

**Comment by minimuss01** [comment]
I had a feeling. Thanks anyway, though!
