### ISSUE TITLE
The launcher says Redstone Flux is crashing my game.

### ISSUE THREAD

**Issue by ZcanKal** [CoFH/Feedback#1068]
Applied Energistics
Backpacks
BattleTowers
Baubles
Chisel
ToroQuest
CodeChickenCode
CoFHCore
EnderCore
EnderIO
Ex Astris
Ex Nihilo
extrautilities
iChunUtil
InfernalMobs
journeymap
LootBags
Mantle
MCA
NotEnoughItems
OpenBlocks (not currently in)
OpenModsLib (Also not currently in)
Optifine (again, not currently in)
ProjectE
RadixCore
SecretRoomsMod
TConstruct
ThermalExpansion
ThermalFoundation
TwilightForestMod
VeinMiner

[crash-2018-05-01_16.38.11-client.txt](https://github.com/CoFH/Feedback/files/1965614/crash-2018-05-01_16.38.11-client.txt)

It almost finishes loading up, and then it crashes back, saying that there's something wrong with Redstone Flux.

**Comment by ZcanKal** [comment]
RedstoneFlux-1.12-2.0.1.2-universal

Sorry, I forgot that in the original post.

**Comment by covers1624** [comment]
The crash clearly tells you you have a mod packing the old RF api, intact the mod is actually for the wrong minecraft version, remove ExAstris.
