### ISSUE TITLE
[TE] [4.1.1-237] [MC 1.7.10] Tesseract wrenching world crash

### ISSUE THREAD

**Issue by St0rmbow** [CoFH/Feedback#1068]
Wrenching a tesseract with a crescent hammer (or breaking it) causes game to crash
http://pastebin.com/0BPfQxhb
Changing any of the configurations in the tesseract GUI (input/output, redstone control) causes the world to exit with the following message: _Connection lost. A fatal error has occured, this connection is terminated._ Clicking **Back to title screen** brings the user to the multiplayer screen (although THIS is probably a bug of Mojangs)
P.S. After I broke the tesseract with a pickaxe and relogged (because it crashed the game) the item was on the ground. When I picked it up I ended up with an extra tesseract, so it doubled. I tried placing one of them back, here is another crash report: http://pastebin.com/AQU4VAfy
P.P.S. I tried placing a creative spawned tesseract in a new world. It crashed with the same error.

**Comment by skyboy** [comment]
Caused by EnderCore.
