### ISSUE TITLE
The "DBaJ" license is self-contradictory

### ISSUE THREAD

**Issue by ColonelThirtyTwo** [CoFH/Feedback#1069]
I am not a lawyer. This is not legal advice.

The "Don't Be a Jerk" license is self-contradictory, which can potentially cause issues for people wanting to contribute to or distribute any projects covered by it. I'm requesting that these contradictions be fixed, as a clear license lowers the barrier for contributing and using the projects.

This issue refers to the DBaJ license [described here](https://github.com/CoFH/CoFHCore/blob/master/README.md).

---

> You CANNOT
> * Redistribute this in its entirety as source or compiled code.

Forking the code (which is allowed by the GitHub terms of service and explicitly allowed earlier in the license) creates a clone of the entire source tree which is, by default, publicly available. Since anyone can create a clone of the fork, this counts as redistributing, and is "not allowed".

Additionally, modpacks must redistribute the compiled code, conflicting with the [permissions page](http://teamcofh.com/permissions/) that states that creating modpacks is allowed.

---

> * Create or distribute code which contains 50% or more Functionally Equivalent Statements* from this repository.
>
>*A Functionally Equivalent Statement is a code fragment which, regardless of whitespace and object names, achieves the same result. Basically you can't copy the code, rename the variables, add whitespace and say it's different. It's not.

Again, forking the code creates an exact copy of the code, containing 100% "functionally equivalent statements".

It is also unenforceable. Copyright law only protects the program text. If another project independently (i.e. without copying the source code) develops a "code fragment that ... achieves the same result" as a code fragment in a DBaJ-covered project, they are not in violation of any copyright law. (A practical example would be Project Red; it is effectively a clone of the old RedPower2 mod, with almost the exact same functionality, but it did not use any of the RedPower source code, and is therefore not a derivative work)

The last two sentences indicate that this is to protect the source code from a modification that would sweep the entire code base, making minor changes to create a project that is very textually different different but functionally equivalent to the old project. [Such a modification is just that - a modification, and the resulting code would be a derivative work.](http://programmers.stackexchange.com/a/86762/102349)

---

I also have some minor nitpicks:

> You'll notice that this repository does not have a license!

It does; in fact, the word "License" is in the header. This should be reworded.

> Maintain a visible repository of your code which is **inspired by**, derived from, or copied from this code.

The "inspired by" part is unenforceable for the reasons discussed above.

> Not be a jerk**. Seriously, if you're a jerk, you can't use this code. That's part of the agreement.

This is mostly my opinion, but the casual "don't be a jerk" language is prone to misinterpretations and loopholes. The bullet point could be replaced with the "Don't claim the code as your own" part of the footnote without any loss of meaning.

**Comment by KingLemming** [comment]
Thanks for your input. It's noted. The simple fact is that in terms of Minecraft modding, basically all licenses are unenforceable. Unless you plan on being a jerk in the near future, then it's all pretty much moot.
