### ISSUE TITLE
[Thermal Expansion 1.10.2] Server Crash when using Stone Hammer

### ISSUE THREAD

**Issue by SpyingSentry-Okami** [CoFH/Feedback#107]
Server crashed when the Stone Hammer was used, dont know if it crashes with other hammers.

It was on FTB Beyond version 1.2.1

[Link to Crash Log](http://pastebin.com/sFC5v8vL)

**Comment by KingLemming** [comment]
It doesn't happen with any hammers. At least we can't make it happen.

The only time this can possibly happen is when the player object is null, in which case you have far larger problems.

**Comment by Rubbertjuh** [comment]
Same issue - Actually most hammers make the server crash =/

**Comment by KingLemming** [comment]
Sorry, but just can't make this happen. No idea what it is.

**Comment by codewarrior0** [comment]
Just a hunch, but does it happen at the extreme edge of the hammer's range?

**Comment by Serifina** [comment]
I have a similar crash, using the RA Flux-infused Hammer. Brought down an FTB Beyond server twice today, but seemingly randomly as I was hammering away. I was dealing with a bit of lag in the process. Not sure if it was the edge of the hammer's range, though. That said, when using the hammer during lag, I do sometimes get ghost blocks.

[crash-2017-03-25_21.20.58-server.txt](https://github.com/CoFH/Feedback/files/870504/crash-2017-03-25_21.20.58-server.txt)

**Comment by KingLemming** [comment]
Still not seeing this. Looking at both crashlogs, the only common theme seems to be that it happens in a Forge method.

**Comment by codewarrior0** [comment]
Found another instance of `RayTracer.retrace()` returning `null` in a completely unrelated issue.

**Comment by KingLemming** [comment]
I've added a catch for that, but that wasn't actually where the crash was occurring.

**Comment by codewarrior0** [comment]
Are you sure? I went back through your git history to find the revision for the release versions and found the crash occurs [when calling `RayTraceResult.getBlockPos()`](https://github.com/TheCBProject/CoFHCore/blob/b89148d6c94533fefb104b2e3a937839a482929d/src/main/java/cofh/core/item/tool/ItemHammerCore.java#L58)

Also, may I beg you to use git tags to mark the release versions? I had to scroll through the commits and inspect ones titled "update version" to find the 4.0.1 release.

**Comment by KingLemming** [comment]
Ah fair enough. I for some reason saw Beyond 1.2.1 and thought they of course would have been updated to the latest version. Dunno wtf I was thinking.

And the tag thing is a maybe, since this is sort of a temporary repo. We'll be migrating back to the old ones, and maybe doing so in a not super-elegant way.

**Comment by legodude17** [comment]
@KingLemming Just wondering, is there a reason this issue isn't closed?

**Comment by KingLemming** [comment]
I haven't pushed an update yet. It's been a bit of a busy time.
