### ISSUE TITLE
Crash: NuclearCraft Liquid Helium in Fluiducts

### ISSUE THREAD

**Issue by CerberusRCAF** [CoFH/Feedback#1070]
I've been testing the NuclearCraft mod for compatibility with my group's server modpack, centred around CoFH mods as the primary industrial/resource transport system.  A recent update to NuclearCraft added a Liquid Helium fluid, and it seems that Liquid Helium and Fluiducts don't get along.

I first ran into this issue when using a Resonant Servo and Temperate Fluiduct to extract Liquid Helium from a NuclearCraft machine to send it to an AE2 Fluid Interface:

http://pastebin.ca/3373126

I did a couple of more focused tests:
-Liquid Helium is place-able in the world in Creative mode;
-Liquid Helium is store-able in an OpenBlocks tank;
-Liquid Helium is store-able in a Portable Tank (tested with a Reinforced);
-Liquid Helium is store-able in an AE2/ExtraCells2 fluid ME system.

This is from trying to use a Resonant Servo and Super-Laminar Fluiduct to send LHe from an OpenBlocks tank to a Portable Tank:

http://pastebin.ca/3374101

And this was a test where I imported LHe from an OpenBlocks tank into a ME system, then tried to export into a Temperate Fluiduct:

http://pastebin.ca/3374103

It seems to me that, as soon as the fluid would have 'touched' any Fluiduct, something tries to divide by zero and the integrated server crashes.  It's never 'survived' to the point where I actually see any fluid in the duct; when I've used a Servo, as soon as I turn it on and before I can leave the Servo's UI, it's toast.

I understand that this is at least as likely to be an issue with the NuclearCraft fluid as it is to be an issue with Fluiducts, and I have an [issue](https://github.com/turbodiesel4598/NuclearCraft/issues/16) open on that mod's GitHub to that effect, but if there are any insights I can get from folks who know a hell of a lot more than I do about Fluids and Fluiducts alike, I'd appreciate it.

**Comment by skyboy** [comment]
@KingLemming Kinda on you as to whether or not a viscosity of 0 on a fluid is even reasonable, since you wrote that API.

**Comment by KingLemming** [comment]
The viscosity probably shouldn't be 0, in all honesty.

**Comment by skyboy** [comment]
I mean, superfluidity is a real thing, but what would that even do in minecraft? Should we just make all our tanks leak this fluid or something in addition to making this not crash?

**Comment by KingLemming** [comment]
This is being addressed on their end, but I've also added stupid-proofing just incase other mods want to get clever with an API not really meant for those numbers.

**Comment by CerberusRCAF** [comment]
I appreciate the help!
