### ISSUE TITLE
[Bug] Factorizer dupe

### ISSUE THREAD

**Issue by OneEyeMaker** [CoFH/Feedback#1071]
Hello.
Found dupe with Factorizer. It interprets 2x2 recipes as 3x3 ones.
This allows to transform 4 items to 9.
Simple example:
![2018-05-03_11 06 30](https://user-images.githubusercontent.com/14104815/39566050-e22da81a-4ec2-11e8-8e14-d8fdc96df61a.png)
Nether quartz block required 4 items to craft, but Factorizer decompresses it to 9 items. The same occurs with Prismarine (and Prismarine shard) and some other items.

And it's not JEI visual glitch - these recipes work in machine.

Please fix this bug (either by removing 2x2 recipes from Factorizer, or by adding proper handler for them).

**Comment by KingLemming** [comment]
Odd. I can't make this happen in dev.

**Comment by KingLemming** [comment]
I think I know why this can happen, actually. Will have a mitigation for it.

**Comment by OneEyeMaker** [comment]
@Drullkus 
I can confirm this just with Thermal mods:
https://imgur.com/a/sqfgiII
Mod list:
CodeChickenLib 3.1.7.340
CoFHCore 4.4.1.12
CoFHWorld 1.1.1.12
JEI 4.9.1.175 (optionally)
RedstoneFlux 2.0.1.2
ThermalExpansion 5.4.2.27
ThermalFoundation 2.4.1.15
