### ISSUE TITLE
[Thermal Dynamics] Mekanism machines not auto-outputting into itemducts

### ISSUE THREAD

**Issue by Zaflis** [CoFH/Feedback#1072]
Mekanism developer would need confirmation if this bug is on his end. Using servos to pull from the machine does work, but they're just too slow. I've tried tesseract feeding into itemduct and it can send at speed of transfer node using 1 stack and 64 speed upgrades rate.

https://github.com/aidancbrady/Mekanism/issues/3100

What i gathered based on its comments, is that Mekanism expects there to be 1 buffer slot in the pipe it can output to and it's not using cofh api. You would know more details.

**Comment by KingLemming** [comment]
Put in a feature request for Mekanism to use our API. There's nothing we can do on our end.
