### ISSUE TITLE
[Bug] Phytogenic Isolator issues with Mystical Agriculture Seeds 

### ISSUE THREAD

**Issue by thejims** [CoFH/Feedback#1072]
When using Mystical Agriculture seeds in the Phytogenic Isolator the Phytogenic Isolator changes the item ID of some of the seeds.  
Also, the Monoculture Cycle augment does not work with them either.

This issue started in the latest release of the modpack Allthemods3 v5.9.4 which contains Mystical Agriculture version 1.6.9, Thermal Expansion version 5.4.1.24, and forge-14.23.3.2674

**Comment by KingLemming** [comment]
This has been fixed for over a week. Please tell ATM to update.
