### ISSUE TITLE
Phytogenic Insolator Augments with Mystical Agri

### ISSUE THREAD

**Issue by TwilightPSN** [CoFH/Feedback#1073]
I've have found a bug currently that if you are using the phytogenic insulator and trying to grow anything from mystical agriculture, it will ignore all the augments installed in the machine

**Comment by KingLemming** [comment]
Well that literally isn't possible, so please explain what behavior you are seeing and why you believe that augments are being ignored.

**Comment by TwilightPSN** [comment]
i put in the augment that is supposed to keep the seed in the inputs slot and it doesnt work at all as well as the fertilizer ones unless im just super unlucky with 4 of the one to not consume fertilizer out of 300 pyro it used them all but that could just be my luck its more the seed on that i can 100% say wasnt working

**Comment by KingLemming** [comment]
Just tested with versions published on Curseforge. It works, so apparently you aren't on the latest.

Please go update your mods, the latest versions are a week old.

**Comment by TwilightPSN** [comment]
im currently on the latest version and it doesnt seem to be working still im using a tier 5 inferium seed
