### ISSUE TITLE
Compatibility between Color Applicator (AE2) and Rockwool

### ISSUE THREAD

**Issue by DrakoAlcarus** [CoFH/Feedback#1073]
Basically, what the title says. The AE2 color applicator doesn't dye regular rockwool. Also, the Flux Igniter doesn't ignite Tiny TNT that AE2 has.

**Comment by skyboy** [comment]
Open separate issues for separate ... issues.

**Comment by DrakoAlcarus** [comment]
Sorry, I just didn't want to be redundant.
