### ISSUE TITLE
Redstone Relay doesn't provide redstone off signal to side-connected iron door

### ISSUE THREAD

**Issue by zangai** [CoFH/Feedback#1078]
When you connect an iron door with a redstone source (button) via fluxducts with redstone relays, the door opens when the button is pushed, but doesn't close back the moment the signal is low. The Redstone Relay is connected to the door from the side, bottom part.

Thermal Foundation 2.3.10.6
Thermal Dynamics 2.3.10.4

**Comment by zangai** [comment]
Just noticed that there is a new version, and the changelog mentions making redstone relays better. Ill check if it still occurs with the newest version.

**Comment by zangai** [comment]
Alright, updated all the mods and still experiencing this behavior.

Thermal Foundation: 2.4.1.15
Thermal Dynamics: 2.4.1.10

**Comment by KingLemming** [comment]
This isn't something we'll be looking into until TD3, sorry. The redstone relays were intentionally left out of the initial port, and a PR put them back in. I'd sooner remove the thing entirely than debug it.

**Comment by zangai** [comment]
Luckily I'm a developer too, so I might look into this myself then. I'd really like it to work :)

**Comment by KingLemming** [comment]
If you get a fix, let me know and I'm willing to accept a PR. Bear in mind it may well be in vanilla logic. There are a couple of known vanilla redstone bugs and this may be one of them, depending on your timing.
