### ISSUE TITLE
[Thermal Expansion 1.10.2] Fractionning Still Extraction Issue (EnderIO)

### ISSUE THREAD

**Issue by MrMaleficus** [CoFH/Feedback#108]
Hello,
 My enderIO fluid conduits doesn't extract the output fluid from the fractionning still.
I've tried on every sides and with my conduits in every modes. Here's my setup :

![2017-03-18_23 46 24](https://cloud.githubusercontent.com/assets/5609863/24076608/57b655e0-0c35-11e7-8cb9-4f3e24d6da18.png)
![2017-03-18_23 47 04](https://cloud.githubusercontent.com/assets/5609863/24076610/57bbec94-0c35-11e7-98e1-6c2f85562fc9.png)
![2017-03-18_23 46 21](https://cloud.githubusercontent.com/assets/5609863/24076611/57be9e44-0c35-11e7-9c08-6c3da876a647.png)

**Comment by KingLemming** [comment]
Okay so here's the deal. The Still isn't coded any differently than any other TE machine.

So I'm pretty confident this is on their end. Can you get their conduits to extract from other machines?

**Comment by MrMaleficus** [comment]
Yes, i'm extracting the resin from the arboreal extractor with the fluid conduits from enderIO

**Comment by KingLemming** [comment]
Try the Magma Crucible and let me know, because there's literally NO REASON in TE code that this wouldn't work.

**Comment by MrMaleficus** [comment]
It's works with the magma crucible.

![2017-03-19_00 25 06](https://cloud.githubusercontent.com/assets/5609863/24076806/934bb596-0c3a-11e7-8d41-d6c29a65c751.png)
![2017-03-19_00 25 11](https://cloud.githubusercontent.com/assets/5609863/24076807/935046ba-0c3a-11e7-8e93-4e1fd22cf84d.png)
![2017-03-19_00 25 15](https://cloud.githubusercontent.com/assets/5609863/24076808/935238a8-0c3a-11e7-849b-7f7599edff5a.png)

**Comment by KingLemming** [comment]
...what version of the mod are you using?

**Comment by MrMaleficus** [comment]
The latest in the FTB Beyond Pack (1.2.1) : TE 5.0.3.86

**Comment by KingLemming** [comment]
Dunno what to tell you. It could just be that Conduits get confused when there are two tanks in the same block, but the code on our end is correct.

Also, the Still will auto-output to things, so you can just do that. Or do conduits have some sort of strange issue with that too?

**Comment by KingLemming** [comment]
Ah actually wait, found it. Code was adjusted in the dev branch but not the repo, to address a corner case.

For now, just use auto-output. This is super low priority to say the least, sorry.
