### ISSUE TITLE
java.lang.NoClassDefFoundError: thermalexpansion/util/crafting/SmelterManager (EDIT)

### ISSUE THREAD

**Issue by Tsyklop** [CoFH/Feedback#108]
http://pastebin.com/vDuYRdBL

ThermalExpansion-[1.7.10]4.0.0B9-87
ProjectRed-1.7.10-4.5.10.61

**Comment by bochen415** [comment]
Duplicates https://github.com/CoFH/Feedback/issues/98 and https://github.com/CoFH/Feedback/issues/100

**Comment by Tsyklop** [comment]
Close please.

**Comment by bochen415** [comment]
@Tsyklop There's a button for that below my comment :) You can use it

**Comment by Tsyklop** [comment]
New crash. EDIT

**Comment by bochen415** [comment]
New crash log not complete. Post the entire crash log. Use http://paste.ubuntu.com/ if pastebin failed.

**Comment by Tsyklop** [comment]
New crash log here http://pastebin.com/vDuYRdBL

**Comment by bochen415** [comment]
@Tsyklop Here's a quote from the Readme
>Include a pastebin (or equivalent) link to a list of all your mods.
Your crash log still has that part edited out. It's the last part of the crash log.

**Comment by skyboy** [comment]
Support is not offered for mods that do not use the actually provided API for adding recipes.

Remove project red to resolve your problem.
