### ISSUE TITLE
[ThermalExpansion] SimplyHammers compatibility.

### ISSUE THREAD

**Issue by Tsyklop** [CoFH/Feedback#1081]
In mod - Simply Hammers can put modifiers for hammers. The young can be inserted an axe or shovel. Vanilla and other mod tools are working properly. But tools (axe and shovel) from ThermalExpansion not give modifier. As I found out, in mod there is a check on the inheritance AxeItem.

Vanilla axe:
![wqhtvjn9lss](https://cloud.githubusercontent.com/assets/6783568/13203143/02c0d66a-d8b9-11e5-8bcd-9da40e694be9.jpg)

Shiny Axe:
![luhxd8v0a-4](https://cloud.githubusercontent.com/assets/6783568/13203147/0b97d3e2-d8b9-11e5-82ee-562e9a2f830c.jpg)

Please. Fix this. Thanks

**Comment by KingLemming** [comment]
Sorry, can't. We don't inherit from those classes because they're Mojang garbage.

**Comment by Tsyklop** [comment]
@KingLemming what api? CoFHLib?

**Comment by KingLemming** [comment]
No, they would have to create an API for us to tell them, "Hey, these are tools."

**Comment by Tsyklop** [comment]
@KingLemming Okay. How i can get HarvestLevel and Efficiency for tools from ThermalExpansion

**Comment by skyboy** [comment]
There's no solid way to get the information you need from the item. Much of it is going to be locked away inside code, which you can't just read from other code. There has to be an API to allow other mods to register any arbitrary item as a tool; and able to read the item's nbt to get the data for the tool.

**Comment by Tsyklop** [comment]
@skyboy Simply Hammers Update and his have API.
http://minecraft.curseforge.com/projects/simply-hammers/files/2289818

Please fix this issue
