### ISSUE TITLE
Autocrafting not working with induction smelter + refined storage

### ISSUE THREAD

**Issue by Triviuhh** [CoFH/Feedback#1082]
Can't seem to get autocrafting to work on the induction smelter when paired with refined storage. Most recent mod version, only change I noticed is that I can no longer make hardened glass with Lead Ingot + Pulverized Obsidian. I did change my recipe to 4 Pulverized Obsidian + 1 Lead Dust and it still will not craft hardened glass.

**Comment by KingLemming** [comment]
Ingot recipe was removed, but the dust recipe works. Just tested it. My guess is that you have a locked Flux slot, so both ingredients can't be inserted at the same time.

**Comment by Triviuhh** [comment]
Unfortunately I don't have a locked slot, could be an issue with refined storage. I'm gonna look a little further into it.
