### ISSUE TITLE
Cyclic Assembler Crash

### ISSUE THREAD

**Issue by Cazadorsniper** [CoFH/Feedback#1083]
Hello, I am the modpack author of Project Ozone and people have been having issues using the Cyclic Assembler. Here is the crash report that was reported to me: http://pastebin.com/Wth2vrMG
The unknown RF API in the crash report is treegrowthsimulator and Optifine was used in the crash.

There is also an issue with tesseracts where if clicked with an open hand or vanilla items it won't crash but when clicked with a modded item it will crash. If you need a crash report of this let me know.

**Comment by KingLemming** [comment]
-_- Please use up to date mods when reporting bugs. These issues have been fixed.

**Comment by KingLemming** [comment]
As far as the Tesseract thing goes, that's a Forge bug I'm afraid.
