### ISSUE TITLE
Crash with Arboreal Extractor

### ISSUE THREAD

**Issue by th4umiel** [CoFH/Feedback#1083]
I'm trying to place the Arboreal extractor near a spruce tree and this is the result.

https://pastebin.com/kbX1EAUZ

Running latest version of Thermal mods

**Comment by KingLemming** [comment]
You are not running the latest version of the Thermal mods. I don't understand why people say that they are and then post a log that shows otherwise. :/

Your TE is not up to date. That is literally the cause.

**Comment by th4umiel** [comment]
Really sorry for the inconvenience, I don't know why but I have previously updated only half of the thermal mods. 

Btw, thanks for your rapid feedback 😄
