### ISSUE TITLE
Energetic Infuser does not accept AE2 certus quartz

### ISSUE THREAD

**Issue by mskurnik** [CoFH/Feedback#1084]
Your [documentation ](http://teamcofh.com/docs/thermal-expansion/machines/energetic-infuser/)says that AE2 Certus Quartz should charge in the infuser but I have yet to see it work.  It does not seem to add the recipe.  I tried using DynIMC to inject the values for `ChargerRecipe` to no avail.

I am using ThermalExpansion-[1.7.10]4.1.2-240 but this has existed for at least 6 months.

**Comment by KingLemming** [comment]
Issue here is actually on AE2's end.

TE's code was put in a LONG time ago and AE agreed to properly OreDict their charged crystals. They have not done so.

**Comment by mskurnik** [comment]
Shouldn't entering the ID do the same thing?  I tried it with DynIMC but it does not work.  What is funny is if I change `ChargerRecipe` to `FurnaceRecipe` it works.
```json
[
  {
    "modid": "ThermalExpansion",
    "string": {},
    "itemstack": {},
	"_RecipeTypes": [
		"FurnaceRecipe",
		"PulverizerRecipe",
		"SawmillRecipe",
		"SmelterRecipe",
		"CrucibleRecipe",
		"TransposerFill",
		"TransposerExtract",
		"ChargerRecipe",
		"InsolatorRecipe"
	],
    "nbt": {
      "ChargerRecipe": [
        {
          "compound:": [
            { "int:energy": 3200 },
            {
              "compound:input": [
                { "short:id": "appliedenergistics2:item.ItemMultiMaterial" },
                { "byte:Count": 1 },
                { "short:Damage": 0 }
              ]
            },
            {
              "compound:output": [
                { "short:id": "appliedenergistics2:item.ItemMultiMaterial" },
                { "byte:Count": 1 },
                { "short:Damage": 1 }
              ]
            }
          ]
        }
      ]
    }
  }
]
```
