### ISSUE TITLE
Error with default ThermalFoundation.json

### ISSUE THREAD

**Issue by dungeonmaster372** [CoFH/Feedback#1085]
I get the following error at first start with your default ThermalFoundation-ores.json file.

Mod Version: ThermalFoundation-[1.7.10]1.2.3-112, CoFHCore-[1.7.10]3.1.2-325, ThermalDynamics-[1.7.10]1.1.0-161, ThermalExpansion-[1.7.10]4.1.2-240

Erorr: http://pastebin.com/erA50Zut

I am trying to prevent duplicate ores from spawning however the initial config is erroring.

Saying expecting : @line 4 col 41

**Comment by dungeonmaster372** [comment]
I have tried to delete the file and it gets regenned like that.

**Comment by KingLemming** [comment]
This doesn't seem to happen. Redownload the jar, but it literally only happens for you. There's about a 99.9% chance you just messed up the file.

**Comment by dungeonmaster372** [comment]
that isn't plausible, considering I haven't even touched files and I know there isnt any incompatibilities w/ what I have installed.

**Comment by XFactHD** [comment]
You do not need to do anything with the file to damage it, this can happen when downloading the file.
