### ISSUE TITLE
Crash! Please Help Figure Out What's Causing It :(

### ISSUE THREAD

**Issue by nlhammonds** [CoFH/Feedback#1086]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CTMCorePlugin (CTM-MC1.12-0.2.3.12.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.64-dev.jar)
  ForgelinPlugin (Forgelin-1.6.0.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.174.jar)
  OpenModsCorePlugin (OpenModsLib-1.12.2-0.11.5.jar)
  LoadingPlugin (RandomThings-MC1.12.2-4.1.5.jar)
  ObfuscatePlugin (obfuscate-0.2.4-1.12.2.jar)
Contact their authors BEFORE contacting forge

// Uh... Did I do that?

Time: 5/11/18 3:46 PM
Description: Initializing game

java.lang.NullPointerException: Initializing game
	at cofh.thermaldynamics.duct.attachments.cover.CoverHelper.getCoverStack(CoverHelper.java:187)
	at cofh.thermaldynamics.duct.attachments.cover.CoverHelper.getCoverStack(CoverHelper.java:174)
	at cofh.thermaldynamics.item.ItemCover$$Lambda$1047/165825008.apply(Unknown Source)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at cofh.thermaldynamics.item.ItemCover.getCoverList(ItemCover.java:105)
	at cofh.thermaldynamics.item.ItemCover.func_150895_a(ItemCover.java:39)
	at net.minecraft.client.Minecraft.func_193986_ar(Minecraft.java:586)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:528)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at cofh.thermaldynamics.duct.attachments.cover.CoverHelper.getCoverStack(CoverHelper.java:187)
	at cofh.thermaldynamics.duct.attachments.cover.CoverHelper.getCoverStack(CoverHelper.java:174)
	at cofh.thermaldynamics.item.ItemCover$$Lambda$1047/165825008.apply(Unknown Source)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at cofh.thermaldynamics.item.ItemCover.getCoverList(ItemCover.java:105)
	at cofh.thermaldynamics.item.ItemCover.func_150895_a(ItemCover.java:39)
	at net.minecraft.client.Minecraft.func_193986_ar(Minecraft.java:586)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:528)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2449814304 bytes (2336 MB) / 5838471168 bytes (5568 MB) up to 6442450944 bytes (6144 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.3.2673 Optifine OptiFine_1.12.2_HD_U_D2 80 mods loaded, 80 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                        | Version                      | Source                                           | Signature                                |
	|:----- |:------------------------- |:---------------------------- |:------------------------------------------------ |:---------------------------------------- |
	| UCH   | minecraft                 | 1.12.2                       | minecraft.jar                                    | None                                     |
	| UCH   | mcp                       | 9.42                         | minecraft.jar                                    | None                                     |
	| UCH   | FML                       | 8.0.99.99                    | forge-1.12.2-14.23.3.2673.jar                    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge                     | 14.23.3.2673                 | forge-1.12.2-14.23.3.2673.jar                    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | micdoodlecore             |                              | minecraft.jar                                    | None                                     |
	| UCH   | openmodscore              | 0.11.5                       | minecraft.jar                                    | None                                     |
	| UCH   | obfuscate                 | 0.2.4                        | minecraft.jar                                    | None                                     |
	| UCH   | movillages                | 1.5.4                        | [1.12]MoVillages-1.5.4.jar                       | None                                     |
	| UCH   | orbis_api                 | 1.12.2-1.0.3                 | orbis_api-1.12.2-1.0.3.jar                       | None                                     |
	| UCH   | aether                    | 1.12.2-1.0.3                 | aether_ii-1.12.2-1.0.3.1.jar                     | None                                     |
	| UCH   | biomesoplenty             | 7.0.1.2383                   | BiomesOPlenty-1.12.2-7.0.1.2383-universal.jar    | None                                     |
	| UCH   | craftstudioapi            | 1.0.0                        | CraftStudio-1.0.0.93-mc1.12-alpha.jar            | None                                     |
	| UCH   | animania                  | 1.4.7                        | animania-1.12.2-1.4.8.jar                        | None                                     |
	| UCH   | baubles                   | 1.5.2                        | Baubles-1.12-1.5.2.jar                           | None                                     |
	| UCH   | bibliocraft               | 2.4.3                        | BiblioCraft[v2.4.3][MC1.12.0].jar                | None                                     |
	| UCH   | jei                       | 4.9.1.168                    | jei_1.12.2-4.9.1.168.jar                         | None                                     |
	| UCH   | mantle                    | 1.12-1.3.2.24                | Mantle-1.12-1.3.2.24.jar                         | None                                     |
	| UCH   | natura                    | 1.12.2-4.3.2.49              | natura-1.12.2-4.3.2.49.jar                       | None                                     |
	| UCH   | forestry                  | 5.8.0.270                    | forestry_1.12.2-5.8.0.270.jar                    | None                                     |
	| UCH   | binniecore                | 2.5.0.163                    | binnie-mods-1.12.2-2.5.0.163.jar                 | None                                     |
	| UCH   | binniedesign              | 2.5.0.163                    | binnie-mods-1.12.2-2.5.0.163.jar                 | None                                     |
	| UCH   | genetics                  | 2.5.0.163                    | binnie-mods-1.12.2-2.5.0.163.jar                 | None                                     |
	| UCH   | botany                    | 2.5.0.163                    | binnie-mods-1.12.2-2.5.0.163.jar                 | None                                     |
	| UCH   | extrabees                 | 2.5.0.163                    | binnie-mods-1.12.2-2.5.0.163.jar                 | None                                     |
	| UCH   | extratrees                | 2.5.0.163                    | binnie-mods-1.12.2-2.5.0.163.jar                 | None                                     |
	| UCH   | cfm                       | 4.2.0                        | cfm-4.2.0-mc1.12.2.jar                           | None                                     |
	| UCH   | chameleon                 | 1.12-4.1.3                   | Chameleon-1.12-4.1.3.jar                         | None                                     |
	| UCH   | ctm                       | MC1.12-0.2.3.12              | CTM-MC1.12-0.2.3.12.jar                          | None                                     |
	| UCH   | chisel                    | MC1.12.2-0.2.0.31            | Chisel-MC1.12.2-0.2.0.31.jar                     | None                                     |
	| UCH   | chiselsandbits            | 14.16                        | chiselsandbits-14.16.jar                         | None                                     |
	| UCH   | codechickenlib            | 3.1.8.341                    | CodeChickenLib-1.12.2-3.1.8.341-universal.jar    | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCH   | redstoneflux              | 2.0.1                        | RedstoneFlux-1.12-2.0.1.2-universal.jar          | d4f1503fbacd9b9fb767720420c5395104239ec9 |
	| UCH   | cofhcore                  | 4.3.11                       | CoFHCore-1.12.2-4.3.11.6-universal.jar           | None                                     |
	| UCH   | cofhworld                 | 1.1.1                        | CoFHWorld-1.12.2-1.1.1.12-universal.jar          | None                                     |
	| UCH   | cookingforblockheads      | 6.3.26                       | CookingForBlockheads_1.12.2-6.3.26.jar           | None                                     |
	| UCH   | erebus                    | 1.0.22                       | Erebus-1.0.22.jar                                | None                                     |
	| UCH   | tconstruct                | 1.12.2-2.9.1.65              | TConstruct-1.12.2-2.9.1.65.jar                   | None                                     |
	| UCH   | galacticraftcore          | 4.0.1.174                    | GalacticraftCore-1.12.2-4.0.1.174.jar            | None                                     |
	| UCH   | galacticraftplanets       | 4.0.1.174                    | Galacticraft-Planets-1.12.2-4.0.1.174.jar        | None                                     |
	| UCH   | mjrlegendslib             | 1.12.2-1.1.3                 | MJRLegendsLib-1.12.2-1.1.3.jar                   | b02331787272ec3515ebe63ecdeea0d746653468 |
	| UCH   | extraplanets              | 1.12.2-0.3.3                 | ExtraPlanets-1.12.2-0.3.3.jar                    | b02331787272ec3515ebe63ecdeea0d746653468 |
	| UCH   | fastleafdecay             | v14                          | FastLeafDecay-v14.jar                            | None                                     |
	| UCH   | flatcoloredblocks         | mc1.12-6.6                   | flatcoloredblocks-mc1.12-6.6.jar                 | None                                     |
	| UCH   | forgelin                  | 1.6.0                        | Forgelin-1.6.0.jar                               | None                                     |
	| UCH   | forgemultipartcbe         | 2.4.2.58                     | ForgeMultipart-1.12.2-2.4.2.58-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCH   | microblockcbe             | 2.4.2.58                     | ForgeMultipart-1.12.2-2.4.2.58-universal.jar     | None                                     |
	| UCH   | minecraftmultipartcbe     | 2.4.2.58                     | ForgeMultipart-1.12.2-2.4.2.58-universal.jar     | None                                     |
	| UCH   | gardenstuff               | 1.12-2.1.1                   | GardenStuff-1.12-2.1.1.jar                       | None                                     |
	| UCH   | geneticsreborn            | 1.09                         | geneticsreborn-1.12-1.09.jar                     | None                                     |
	| UCH   | waila                     | 1.8.25                       | Hwyla-1.8.25-B40_1.12.jar                        | None                                     |
	| UCH   | tesla                     | 1.0.63                       | Tesla-1.12.2-1.0.63.jar                          | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCH   | teslacorelib              | 1.0.13                       | tesla-core-lib-1.12-1.0.13.jar                   | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCH   | industrialforegoing       | 1.12.2-1.12.2                | industrialforegoing-1.12.2-1.9.0-163.jar         | None                                     |
	| UCH   | inventorytweaks           | 1.64-dev+release.110.b4fac73 | InventoryTweaks-1.64-dev.jar                     | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCH   | malisiscore               | 1.12.2-6.4.0                 | malisiscore-1.12.2-6.4.0.jar                     | None                                     |
	| UCH   | malisisdoors              | 1.12.2-7.3.0                 | malisisdoors-1.12.2-7.3.0.jar                    | None                                     |
	| UCH   | mapwriter                 | 2.8.2                        | MapWriter-1.12.2-2.8.2.jar                       | None                                     |
	| UCH   | moreplanets               | 2.0.14                       | More-Planets-1.12.2-2.0.14-GC156.jar             | b3468b224a74e296555ad7efeb35f482e6f445de |
	| UCH   | mousetweaks               | 2.8                          | MouseTweaks-2.8-mc1.12.1.jar                     | None                                     |
	| UCH   | mrtjpcore                 | 2.1.1.27                     | MrTJPCore-1.12.2-2.1.1.27-universal.jar          | None                                     |
	| UCH   | openmods                  | 0.11.5                       | OpenModsLib-1.12.2-0.11.5.jar                    | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| UCH   | openblocks                | 1.7.6                        | OpenBlocks-1.12.2-1.7.6.jar                      | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| UCH   | pizzacraft                | 1.0.0                        | PizzaCraft-1.12.2-1.0.5.jar                      | None                                     |
	| UCH   | projectred-core           | 4.8.6.74                     | ProjectRed-1.12.2-4.8.6.74-Base.jar              | None                                     |
	| UCH   | projectred-illumination   | 4.8.6.74                     | ProjectRed-1.12.2-4.8.6.74-lighting.jar          | None                                     |
	| UCH   | projectred-expansion      | 4.8.6.74                     | ProjectRed-1.12.2-4.8.6.74-mechanical.jar        | None                                     |
	| UCH   | projectred-transportation | 4.8.6.74                     | ProjectRed-1.12.2-4.8.6.74-mechanical.jar        | None                                     |
	| UCH   | randomthings              | 4.1.5                        | RandomThings-MC1.12.2-4.1.5.jar                  | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| UCH   | storagedrawers            | 1.12-5.3.5                   | StorageDrawers-1.12.2-5.3.6.jar                  | None                                     |
	| UCH   | storagedrawersextra       | @VERSION@                    | StorageDrawersExtras-1.12-3.1.0.jar              | None                                     |
	| UCH   | thaumcraft                | 6.1.BETA13                   | Thaumcraft-1.12.2-6.1.BETA13.jar                 | None                                     |
	| UCH   | thermalfoundation         | 2.3.11                       | ThermalFoundation-1.12.2-2.3.12.10-universal.jar | None                                     |
	| UCH   | thermaldynamics           | 2.3.11                       | ThermalDynamics-1.12.2-2.3.11.7-universal.jar    | None                                     |
	| UCH   | tinkersaddons             | 1.0.7                        | Tinkers'+Addons-1.12.1-1.0.7.jar                 | None                                     |
	| UCH   | tropicraft                | 7.1.3.62                     | tropicraft-MC1.12.2-7.1.3.62.jar                 | None                                     |
	| UCH   | twilightforest            | 3.6.345                      | twilightforest-1.12.2-3.6.345-universal.jar      | None                                     |
	| UCH   | undergroundbiomes         | 1.0.1                        | UndergroundBiomesConstructs-1.12-1.0.1.jar       | None                                     |
	| UCH   | vehicle                   | 0.8.1                        | vehicle-mod-0.8.1-1.12.2.jar                     | None                                     |
	| UCH   | xlfoodmod                 | 1.12.2-1.5.0                 | XL+Food+Mod-1.12.2-1.5.0.jar                     | None                                     |
	| UCH   | teslacorelib_registries   | 1.0.13                       | tesla-core-lib-1.12-1.0.13.jar                   | None                                     |

	Loaded coremods (and transformers): 
CTMCorePlugin (CTM-MC1.12-0.2.3.12.jar)
  team.chisel.ctm.client.asm.CTMTransformer
MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  
Inventory Tweaks Coremod (InventoryTweaks-1.64-dev.jar)
  invtweaks.forge.asm.ContainerTransformer
ForgelinPlugin (Forgelin-1.6.0.jar)
  
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.174.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
OpenModsCorePlugin (OpenModsLib-1.12.2-0.11.5.jar)
  openmods.core.OpenModsClassTransformer
LoadingPlugin (RandomThings-MC1.12.2-4.1.5.jar)
  lumien.randomthings.asm.ClassTransformer
ObfuscatePlugin (obfuscate-0.2.4-1.12.2.jar)
  com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
	GL info: ' Vendor: 'Intel' Version: '4.3.0 - Build 20.19.15.4835' Renderer: 'Intel(R) HD Graphics 4600'
	OpenModsLib class transformers: [llama_null_fix:FINISHED],[horse_base_null_fix:FINISHED],[pre_world_render_hook:FINISHED],[player_render_hook:FINISHED],[horse_null_fix:FINISHED]
	Pulsar/natura loaded Pulses: 
		- NaturaCommons (Enabled/Forced)
		- NaturaOverworld (Enabled/Not Forced)
		- NaturaNether (Enabled/Not Forced)
		- NaturaDecorative (Enabled/Not Forced)
		- NaturaTools (Enabled/Not Forced)
		- NaturaEntities (Enabled/Not Forced)
		- NaturaOredict (Enabled/Forced)
		- NaturaWorld (Enabled/Not Forced)

	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- wailaIntegration (Enabled/Not Forced)

	Launched Version: 1.12.2-forge1.12.2-14.23.3.2673
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 4600 GL version 4.3.0 - Build 20.19.15.4835, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-4210M CPU @ 2.60GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_D2
	OptiFine Build: 20180430-132249
	Render Distance Chunks: 11
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.3.0 - Build 20.19.15.4835
	OpenGlRenderer: Intel(R) HD Graphics 4600
	OpenGlVendor: Intel
	CpuCount: 4

**Comment by KingLemming** [comment]
Please only post crashes if you're on the latest versions. I'm pretty sure I've already fixed this.

**Comment by nlhammonds** [comment]
The lastest of COFH? because I am on the latest...
