### ISSUE TITLE
Game crashes after exiting one world and trying to load another

### ISSUE THREAD

**Issue by jaallman** [CoFH/Feedback#1087]
This doesn't happen all the time, but it happens far more often than not. I will be playing on one world; I'll save and quit to title; I'll load another world; then the game will crash. When launching the game and loading a world for the first time, though, there is never a crash.

---- Minecraft Crash Report ----
// But it works on my machine.

Time: 2/27/16 9:57 AM
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at com.google.common.collect.LinkedHashMultimap.create(LinkedHashMultimap.java:119)
	at net.minecraftforge.common.ForgeChunkManager.unforceChunk(ForgeChunkManager.java:783)
	at mods.railcraft.common.blocks.machine.alpha.TileAnchorWorld.setTicket(TileAnchorWorld.java:370)
	at mods.railcraft.common.blocks.machine.alpha.TileAnchorWorld.forceChunkLoading(TileAnchorWorld.java:385)
	at mods.railcraft.common.util.misc.ChunkManager.ticketsLoaded(ChunkManager.java:174)
	at net.minecraftforge.common.ForgeChunkManager.loadWorld(ForgeChunkManager.java:523)
	at net.minecraftforge.common.ForgeInternalHandler.onDimensionLoad(ForgeInternalHandler.java:64)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_16_ForgeInternalHandler_onDimensionLoad_Load.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:73)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:92)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Mac OS X (x86_64) version 10.10.5
	Java Version: 1.8.0_73, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 466574896 bytes (444 MB) / 929886208 bytes (886 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 5 total; -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 15, tcache: 0, allocated: 15, tallocated: 95
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1448 42 mods loaded, 42 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1448-1.7.10.jar) 
	UCHIJAAAAAAA	Forge{10.13.4.1448} [Minecraft Forge] (forge-1.7.10-10.13.4.1448-1.7.10.jar) 
	UCHIJAAAAAAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJAAAAAAA	advancedgenetics{1.5.7} [Advanced Genetics] (advancedgenetics-1.7.10-1.5.7.jar) 
	UCHIJAAAAAAA	koresample{1.7.10-1.3.2} [Kore Sample] (KoreSample-1.7.10-1.3.2.jar) 
	UCHIJAAAAAAA	dendrology{1.7.10-1.6.3} [Ancient Trees] (AncientTrees-1.7.10-1.6.3.jar) 
	UCHIJAAAAAAA	AppleCore{1.1.0} [AppleCore] (AppleCore-mc1.7.10-1.1.0.jar) 
	UCHIJAAAAAAA	BiblioCraft{1.11.2} [BiblioCraft] (BiblioCraft[v1.11.2][MC1.7.10].jar) 
	UCHIJAAAAAAA	CoFHCore{1.7.10R3.1.2} [CoFH Core] (CoFHCore-[1.7.10]3.1.2-325.jar) 
	UCHIJAAAAAAA	BuildCraft|Core{7.1.13} [BuildCraft] (buildcraft-7.1.13.jar) 
	UCHIJAAAAAAA	BuildCraft|Builders{7.1.13} [BC Builders] (buildcraft-7.1.13.jar) 
	UCHIJAAAAAAA	BuildCraft|Transport{7.1.13} [BC Transport] (buildcraft-7.1.13.jar) 
	UCHIJAAAAAAA	BuildCraft|Energy{7.1.13} [BC Energy] (buildcraft-7.1.13.jar) 
	UCHIJAAAAAAA	BuildCraft|Silicon{7.1.13} [BC Silicon] (buildcraft-7.1.13.jar) 
	UCHIJAAAAAAA	BuildCraft|Robotics{7.1.13} [BC Robotics] (buildcraft-7.1.13.jar) 
	UCHIJAAAAAAA	BuildCraft|Factory{7.1.13} [BC Factory] (buildcraft-7.1.13.jar) 
	UCHIJAAAAAAA	craftguide{1.6.8.2} [CraftGuide] (CraftGuide-1.6.8.2-forge.jar) 
	UCHIJAAAAAAA	eplus{3.0.2-d} [Enchanting Plus] (EnchantingPlus-1.7.10-3.0.2-d.jar) 
	UCHIJAAAAAAA	factorization.notify{1.0} [Factorization Notification System] (Factorization-1.7.10-0.8.88.8.8888f.jar) 
	UCHIJAAAAAAA	factorization.dimensionalSlice{0.8.88.8.8888f} [Factorization Dimensional Slices] (Factorization-1.7.10-0.8.88.8.8888f.jar) 
	UCHIJAAAAAAA	factorization{0.8.88.8.8888f} [Factorization] (Factorization-1.7.10-0.8.88.8.8888f.jar) 
	UCHIJAAAAAAA	factorization.misc{0.8.88.8.8888f} [Factorization Miscellaneous Nonsense] (Factorization-1.7.10-0.8.88.8.8888f.jar) 
	UCHIJAAAAAAA	ForgeMultipart{1.1.1.322} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.1.322-universal.jar) 
	UCHIJAAAAAAA	McMultipart{1.1.1.322} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.1.322-universal.jar) 
	UCHIJAAAAAAA	iChunUtil{4.1.0} [iChunUtil] (iChunUtil-4.1.0.jar) 
	UCHIJAAAAAAA	JABBA{1.2.1} [JABBA] (Jabba-1.2.1a_1.7.10.jar) 
	UCHIJAAAAAAA	lloverlay{@VERSION@} [Light Level Overlay] (lloverlay-0.23a-10.12.0.1007-forge.jar) 
	UCHIJAAAAAAA	MoarSigns{1.1.4} [MoarSigns] (MoarSigns-1.7.10-1.1.4.jar) 
	UCHIJAAAAAAA	cfm{3.4.8} [�9MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.4.8(1.7.10).jar) 
	UCHIJAAAAAAA	harvestcraft{1.7.10j} [Pam's HarvestCraft] (Pam's HarvestCraft 1.7.10j.jar) 
	UCHIJAAAAAAA	Railcraft{9.8.0.0} [Railcraft] (Railcraft_1.7.10-9.8.0.0.jar) 
	UCHIJAAAAAAA	ThermalFoundation{1.7.10R1.2.2} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.2.2-111.jar) 
	UCHIJAAAAAAA	ThermalExpansion{1.7.10R4.1.2} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.1.2-240.jar) 
	UCHIJAAAAAAA	RedstoneArsenal{1.7.10R1.1.2} [Redstone Arsenal] (RedstoneArsenal-[1.7.10]1.1.2-92.jar) 
	UCHIJAAAAAAA	SolarFlux{1.7.10-0.8b} [Solar Flux] (SolarFlux-1.7.10-0.8b.jar) 
	UCHIJAAAAAAA	SpiceOfLife{1.2.4} [The Spice of Life] (SpiceOfLife-mc1.7.10-1.2.4.jar) 
	UCHIJAAAAAAA	StevesCarts{2.0.0.b18} [Steve's Carts 2] (StevesCarts2.0.0.b18.jar) 
	UCHIJAAAAAAA	ThermalDynamics{1.7.10R1.1.0} [Thermal Dynamics] (ThermalDynamics-[1.7.10]1.1.0-161.jar) 
	UCHIJAAAAAAA	universalcoins{1.7.10-1.6.38} [Universal Coins] (UniversalCoins-1.7.10-1.6.38.jar) 
	UCHIJAAAAAAA	witchery{0.24.1} [Witchery] (witchery-1.7.10-0.24.1.jar) 
	UCHIJAAAAAAA	ForgeMicroblock{1.1.1.322} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.1.322-universal.jar) 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	CoFHCore: -[1.7.10]3.1.2-325
	ThermalFoundation: -[1.7.10]1.2.2-111
	ThermalExpansion: -[1.7.10]4.1.2-240
	RedstoneArsenal: -[1.7.10]1.1.2-92
	ThermalDynamics: -[1.7.10]1.1.0-161
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by XFactHD** [comment]
Report this on the Railcraft issue tracker, it has nothing to do with any of the CoFH mods.
