### ISSUE TITLE
Feature Request: Support Add-On Machines

### ISSUE THREAD

**Issue by TomShkurti** [CoFH/Feedback#1087]
I've been trying to make a few TE machines for personal use and maybe releasing down the road as add-ons (work I carried over from MineFactoryReloaded on 1.7), but have not been able to figure out how to do so short of creating essentially duplicates of BlockMachine, TileMachineBase, and possibly others.

It'd be great for addon makers like myself if the base functionality of a 'generic' TE machine was split off from the registration of the specific TM machines themselves and made a set of classes that other mods could inherit from.

**Comment by KingLemming** [comment]
No, sorry. That's a full rewrite of the system for something that doesn't really offer any benefit for me.

If you want new machines, request them and I'm willing to consider them on a case by case basis.
