### ISSUE TITLE
ender IO conduits not removable with 1.12.2-5.4.2.27 update or core 1.12.2-4.4.1.12

### ISSUE THREAD

**Issue by Mementh** [CoFH/Feedback#1088]
its expected to be able to remove the conduits from Ender IO that are placed. that function stopped working in latest

epic squid said in the ender io said the cofh core needed updating? 

thermal expansion prior version 1.12.2.5.3.12.7
core old version 1.12.2-4.3.11.6

**Comment by KingLemming** [comment]
We have literally nothing to do with the ability to remove EnderIO conduits.

**Comment by Mementh** [comment]
sorry but it was working in prior.. now your wrench is not working.. something changed in your system to make it different where it was working with other mods propperly
