### ISSUE TITLE
Redstone furnace and printed circuits.

### ISSUE THREAD

**Issue by Fluoxi** [CoFH/Feedback#1089]
ThermalExpansion-[1.7.10]4.1.2-240
List of mods:http://pastebin.com/CE6hBqFb
Sky Factory 2 - 2.4

So you can smelt printed circuits from the AE2 mod. Most furnaces seem to work, redstone furnaces do not. Not sure if intended or a bug.

![javaw 2016-02-29 02-25-36-63](https://cloud.githubusercontent.com/assets/17535693/13383567/c97b6a7c-de8b-11e5-9154-c69e5e69e982.png)

**Comment by XFactHD** [comment]
This is AFAIK no vanilla AE2 behaviour. What is the smelting output supposed to be?

**Comment by Fluoxi** [comment]
You can smelt the processors in Sky Factory 2... I didn't even know till a few days ago I realized there were more recipes for them. You can shape craft the printed circuits and then just throw them in a furnace. It's overpowered I know but it's just a part of the modpack I guesse.

**Comment by KingLemming** [comment]
This sounds like an issue with the modpack and how they're adding recipes.

**Comment by XFactHD** [comment]
@Fluoxi you should report this to the mod pack author and tell them that they should make a utility mod for the pack. With TE's IMC interface it is really easy to add those recipes.

**Comment by Fluoxi** [comment]
Alright, will do.
