### ISSUE TITLE
Suggestion: Disabling ore augments if input and output are ores

### ISSUE THREAD

**Issue by trabpukcip** [CoFH/Feedback#1089]
While working on my mod I have run into a bit of an issue with the Flux Anodizer Augment.

When adding a vanilla furnace / redstone furnace / pulverizer recipes, the flux anodizer and tectonic initator augment is automatically added if the input matches the ore dictionary as being an ore.
However my input is a Nether/End ore that is designed to be smelted into 2x normal ores on mode 2 and pulverises to 4x dusts.
Mode 3 smelts to 3x normal ore and pulverises to 4x ore, like the mod dense ores used to do.

The flux augment adds 1x extra ore and the tectonic initiator multiplies by 1.5x
So on mode 2 you get 3x ore on flux anodizer (too much) and 6x dusts from the tectonic initiator (acceptable).
Mode 3 yields 4x ore (way too much) and a ridiculous 6x ore from the tectonic initiator.

What would balance it out without breaking it, is simply disable the augment recipes if the input and output are both ore prefixed blocks. Could this be looked into?

Does this qualify as "really stupid" ;) https://github.com/CoFH/Feedback/issues/581#issuecomment-338315672

**Comment by KingLemming** [comment]
Current augment behavior is in line with the operational modes of this mod:

https://minecraft.curseforge.com/projects/nether-foundation

If you are deviating from those, in terms of nether/end ores, I suggest that you do not.

**Comment by trabpukcip** [comment]
That mod has exactly the same issue.

3x **ores** from from the vastly cheaper flux anodizer vs only gets 4x dusts from the pulverizer.
Plus the fact that you can combine the two to get 9 dusts from 1 nether ore.
It is vastly unbalanced.
If the flux anodizer block smelt output was diabled at least it would be a more reasonable 6x dusts using the two machines.

**Comment by KingLemming** [comment]
It's not 3x ores though. It's +50% output, which is what the augment does, period.

It is entirely your determination that a nether ore smelts into 2 regular ores. Make it ingots instead.

**Comment by trabpukcip** [comment]
Worked around it my own way, reduced the output and energy costs to match what it is was doing before without augments, making them the defacto standard.

The vanilla furnace has been left as is or if Mekanism is installed they can use that instead and get the expected output.
