### ISSUE TITLE
Thermal dynamics energy pipes not returning how much energy they got

### ISSUE THREAD

**Issue by Silly511** [CoFH/Feedback#1090]
I have a energy storage block that stores energy from a custom energy api I made and I want to make my energy api compatible with the RF api. But the problem I'm running into is that thermal dynamics energy pipes are not returning how much energy they received, so if I connect a generator from my mod up to a energy cell using thermal dynamics cable, the energy cell starts getting power but energy is not extracted from the generator so the generators power buffer fills up. However power is transmitted fine if the generator is right next to the energy cell, so it only does this with pipes. Here is the code I use to extract power from the generators buffer and place it in the blocks beside it:

```java
int i = 0;
		
		for (PositionInWorld pos : WorldHelper.getListOfPositionsAroundBlock(xCoord, yCoord, zCoord)) {
			TileEntity tile = worldObj.getTileEntity(pos.getX(), pos.getY(), pos.getZ());
			
			if (tile instanceof IAuraUser) {
				this.extractAura(((BaseEnergyStorageBlock)tile).receiveAura(this.getStoredAura(), false), false);
			} else if (tile instanceof IEnergyHandler) {
				this.extractAura(((IEnergyHandler)tile).receiveEnergy(ForgeDirection.getOrientation(i).getOpposite(), (int) this.extractAura(this.getMaxStoredAura(), true), false), false);
			}
			
			i++;
		}
```

Am I doing something wrong, or is this a bug?

**Comment by KingLemming** [comment]
You're doing something wrong. For starters, stop using IEnergyHandler. Be sure you're on the up to date RF API.
