### ISSUE TITLE
[Compatability] Blood Magic Lava Crystal won't work in Steam Dynamo

### ISSUE THREAD

**Issue by Dragnier** [CoFH/Feedback#1091]
I had this idea to power my steam dynamos with lava crystals from Blood Magic which state they should work in anything that burns the same stuff as a furnace. However, they will not even place in the steam dynamo. Is there a config somewhere for this? If not, could this compatibility be added?

Lava Crystals are not free since they take 50 LP per item plus the need to craft one per dynamo, so I figured it wouldn't be super unbalanced.

**Comment by KingLemming** [comment]
Steam dynamos don't work with anything that has a Container Item or has a total RF value < 3000.

Those are the only conditions, so if the crystal doesn't work, one of those is true. Unfortunately, this will not be changing, sorry.
