### ISSUE TITLE
Tesseract Crashing the game 

### ISSUE THREAD

**Issue by 4zedia** [CoFH/Feedback#1092]
the game crash the moment I open the Tesseract, before starting to crash the Tesseract did not crash the game but after a while started I do not know if it was too much items in it or energy but just below is the crash report
 https://pastebin.com/aaB9AJJN

**Comment by KingLemming** [comment]
There is nothing in that crash log that points to a Tesseract at all. You are apparently placing a block, however.

Also, 1.7.10 is unsupported, sorry.
