### ISSUE TITLE
[all cofh mods] version checking 

### ISSUE THREAD

**Issue by johnfg12** [CoFH/Feedback#1093]
as far as i can see there is no current method of disableing version checking when making a pack this is amazingly annoying how many people moan about updates and the "cofh said this needs updating" and so on would it be posibble to add a config opption to turn version checking off

**Comment by XFactHD** [comment]
Version checking has a good reason. Else, even more people would use outdated versions and report bugs that have been fixed ages ago. This isn't fun for the devs at all.

**Comment by johnfg12** [comment]
i understand that but for pack devs it is a total pain when they get like 20 messages say "why dont you update x,y,z why dont you look after this pack properly" and so on

**Comment by KingLemming** [comment]
It can be disabled if you distribute client configs.

**Comment by johnfg12** [comment]
ok thanks didnt see that :D
