### ISSUE TITLE
ME Interface interaction with itemducts with automating Rich Phyto-Grow.  

### ISSUE THREAD

**Issue by Kraxion** [CoFH/Feedback#1093]
https://imgur.com/a/WM7e2yQ

ATM3 5.9.5 has CoFH mod versions:

CoFH core 4.4.1.12
T Cultivation 0.2.0.6
T Dynamics 2.4.1.10
T Expansion 5.4.2.27
T Foundation 2.4.1.15
T Innovation 0.2.1.6

Essentially the interface wont push phyto-grow and logs into a sawmil and transposer.
It will however work with magma crucibles and transposers (and the respective items)  

The imgur album includes pictures with details.

**Comment by KingLemming** [comment]
There is absolutely no code in TE that deals with AE2 at all. As you pointed out, it works with the ducts. Sorry, but this just isn't on our end.
