### ISSUE TITLE
Clientside Crash MC 1.7.10

### ISSUE THREAD

**Issue by IceT2** [CoFH/Feedback#1094]
I started having problems when updating beyond cofhcore version - CoFHCore-[1.7.10]3.0.3-303.
Up to this cofhcore version -    I have a client with 178 mods in, all working fine with their latest versions, but beyond this version - crash every startup.
I had to assume the issue was at my end since no-one else was reporting the same problem, and this turned out to be the case.
I have only just tracked down the cause. It's because I'm using an oracle Java 9 pre-release version which I downloaded from here - https://jdk9.java.net/download/
If I revert to java 8, your cofhcore version - CoFHCore-[1.7.10]3.1.2-325 works ok and the client loads.
I suppose this is more of a 'heads-up', that this is an issue which might only hit your mod if java 9 continues to a release candidate ( which it eventually will ) with this problem still evident. Anyway, I'm hoping you'll at least consider looking at the issue, and many thanks for listening.
A paste of the crash is below from a much 'mod reduced' test client build of mine. The crash happens in both the jdk and jre versions.
Using Win 7 64bit with java 9 64bit. MultiMC 4.11.751 MC1.7.10 Forge 1.7.10-10.13.4.1614
---------------------------------------------------
MultiMC version: 0.4.11-751

Minecraft folder is:
G:/Minecraft/MultiMC/instances/MC1710-CS3Test/minecraft

Java path is:
C:/Program Files/Java/jre1.9.0/bin/javaw.exe

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms2048m, -Xmx2048m, -Duser.language=en, -jar, G:/Minecraft/MultiMC/New folder/MultiMC/jars/NewLaunch.jar]

Minecraft process ID: 6668

Using onesix launcher.

Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  G:/Minecraft/MultiMC/instances/MC1710-CS3Test/natives

Traits:
  []

Libraries:
  G:/Minecraft/MultiMC/New folder/MultiMC/libraries/com/mojang/realms/1.3.5/realms-1.3.5.jar
  G:/Minecraft/MultiMC/New folder/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  G:/Minecraft/MultiMC/New folder/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  G:/Minecraft/MultiMC/New folder/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  G:/Minecraft/MultiMC/New folder/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  G:/Minecraft/MultiMC/New folder/MultiMC/libraries/java3d/vecmath/1.3.1/vecmath-1.3.1.jar
  G:/Minecraft/MultiMC/New folder/MultiMC/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  G:/Minecraft/MultiMC/New folder/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  G:/Minecraft/MultiMC/New folder/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/4.5/jopt-simple-4.5.jar
  G:/Minecraft/MultiMC/New folder/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  G:/Minecraft/MultiMC/New folder/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  G:/Minecraft/MultiMC/New folder/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  G:/Minecraft/MultiMC/New folder/MultiMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  G:/Minecraft/MultiMC/New folder/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  G:/Minecraft/MultiMC/New folder/MultiMC/libraries/io/netty/netty-all/4.0.10.Final/netty-all-4.0.10.Final.jar
  G:/Minecraft/MultiMC/New folder/MultiMC/libraries/com/google/guava/guava/17.0/guava-17.0.jar
  G:/Minecraft/MultiMC/New folder/MultiMC/libraries/org/apache/commons/commons-lang3/3.3.2/commons-lang3-3.3.2.jar
  G:/Minecraft/MultiMC/New folder/MultiMC/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar
  G:/Minecraft/MultiMC/New folder/MultiMC/libraries/commons-codec/commons-codec/1.9/commons-codec-1.9.jar
  G:/Minecraft/MultiMC/New folder/MultiMC/libraries/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar
  G:/Minecraft/MultiMC/New folder/MultiMC/libraries/com/mojang/authlib/1.5.21/authlib-1.5.21.jar
  G:/Minecraft/MultiMC/New folder/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9/log4j-api-2.0-beta9.jar
  G:/Minecraft/MultiMC/New folder/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9/log4j-core-2.0-beta9.jar
  G:/Minecraft/MultiMC/New folder/MultiMC/libraries/tv/twitch/twitch/5.16/twitch-5.16.jar
  G:/Minecraft/MultiMC/New folder/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  G:/Minecraft/MultiMC/New folder/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  G:/Minecraft/MultiMC/New folder/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.1/lwjgl-2.9.1.jar
  G:/Minecraft/MultiMC/New folder/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.1/lwjgl_util-2.9.1.jar
  G:/Minecraft/MultiMC/New folder/MultiMC/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  G:/Minecraft/MultiMC/New folder/MultiMC/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
  G:/Minecraft/MultiMC/New folder/MultiMC/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
  G:/Minecraft/MultiMC/New folder/MultiMC/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
  G:/Minecraft/MultiMC/New folder/MultiMC/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
  G:/Minecraft/MultiMC/New folder/MultiMC/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
  G:/Minecraft/MultiMC/New folder/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar
  G:/Minecraft/MultiMC/New folder/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar
  G:/Minecraft/MultiMC/New folder/MultiMC/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
  G:/Minecraft/MultiMC/New folder/MultiMC/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
  G:/Minecraft/MultiMC/New folder/MultiMC/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar
  G:/Minecraft/MultiMC/New folder/MultiMC/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
  G:/Minecraft/MultiMC/New folder/MultiMC/libraries/org/ow2/asm/asm-all/5.0.3/asm-all-5.0.3.jar
  G:/Minecraft/MultiMC/New folder/MultiMC/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
  G:/Minecraft/MultiMC/New folder/MultiMC/libraries/net/minecraftforge/forge/1.7.10-10.13.4.1614-1.7.10/forge-1.7.10-10.13.4.1614-1.7.10-universal.jar
  G:/Minecraft/MultiMC/New folder/MultiMC/versions/1.7.10/1.7.10.jar

Mods:
  ChickenChunks-1.7.10-1.3.4.19-universal
  CodeChickenCore-1.7.10-1.0.7.47-universal
  CoFHCore-[1.7.10]3.1.2-325
  CyanosLootableBodies-1.3.5-backport
  CustomStuff3-0.7.4-MC1.7.10
  fastcraft-1.21
  journeymap-1.7.10-5.1.0-fairplay
  js
  MineFactoryReloaded-[1.7.10]2.8.1-174(2)
  Night-Vision-Mining-Hats-Mod-1.7.10
  NetherOres-[1.7.10]2.3.1-22(2)
  NotEnoughItems-1.7.10-1.0.5.118-universal
  ThermalDynamics-[1.7.10]1.1.0-161(3)
  ThermalExpansion-[1.7.10]4.1.2-240
  ThermalFoundation-[1.7.10]1.2.3-112
  TooMuchTime-1.7.10-2.3.2.B13-universal
  Waila-1.5.10_1.7.10

Params:
  [--username, <PROFILE NAME>, --version, MultiMC5, --gameDir, G:/Minecraft/MultiMC/instances/MC1710-CS3Test/minecraft, --assetsDir, G:/Minecraft/MultiMC/New folder/MultiMC/assets, --assetIndex, 1.7.10, --uuid, <PROFILE ID>, --accessToken, <ACCESS TOKEN>, --userProperties, {}, --userType, legacy, --tweakClass, cpw.mods.fml.common.launcher.FMLTweaker]

Window size: 854 x 480

Preparing native libraries...
Extracting twitch-platform-5.16-natives-windows-64.jar
Extracting twitch-external-platform-4.5-natives-windows-64.jar
Extracting jinput-platform-2.0.5-natives-windows.jar
Extracting lwjgl-platform-2.9.1-natives-windows.jar

Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:520)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395)
	at org.multimc.EntryPoint.listen(EntryPoint.java:170)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)
Caused by: java.lang.NoClassDefFoundError: com/sun/management/internal/GarbageCollectorExtImpl
	at sun.management.MemoryImpl.getMemoryManagers0(Native Method)
	at sun.management.MemoryImpl.getMemoryManagers(MemoryImpl.java:98)
	at sun.management.ManagementFactoryHelper.getGarbageCollectorMXBeans(ManagementFactoryHelper.java:133)
	at java.lang.management.DefaultPlatformMBeanProvider$4.nameToMBeanMap(DefaultPlatformMBeanProvider.java:185)
	at java.lang.management.ManagementFactory.lambda$getPlatformMBeanServer$0(ManagementFactory.java:478)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:269)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1664)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:430)
	at java.lang.management.ManagementFactory.getPlatformMBeanServer(ManagementFactory.java:479)
	at org.apache.logging.log4j.core.jmx.Server.registerMBeans(Server.java:107)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.<init>(Log4jContextFactory.java:59)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:426)
	at java.lang.Class.newInstance(Class.java:465)
	at org.apache.logging.log4j.LogManager.<clinit>(LogManager.java:85)
	at net.minecraft.launchwrapper.LogWrapper.configureLogging(LogWrapper.java:14)
	at net.minecraft.launchwrapper.LogWrapper.log(LogWrapper.java:28)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:94)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	... 8 more
Exiting with -1
Process exited with code -1.

**Comment by Glease** [comment]
Something internal of jdk9 is broken. For temporary workaround, add "Dlog4j2.disable.jmx=true" to launch command if you insisted to use jdk9.

 I should really warn you not to use these nice new pre-releases because bugs like this may pop up at **anytime and anywhere**, and there may not be any easy workaround at that time.

You should also post your jdk9 version(obtained via <code>java -version</code>) or we can't make a bug report for that.

**Comment by KingLemming** [comment]
Appreciate the heads up, but this is way out of our control. Also, Minecraft itself in no way is expected to support Java 9.

**Comment by IceT2** [comment]
Your replies are appreciated. Although I like to test upcoming versions, at least I have more idea where to look if things should happen like this in the future.

**Comment by XFactHD** [comment]
@Glease I would rather say that oracle removed the specific GC that mojang is using. If you look at the last lines from the game log, it says that this GC is deprecated.

**Comment by Glease** [comment]
Well, I just didn't noticed that. comments at bug.java.net didn't show its cause is the removal of a GC (they had a discussion, but the reporter of that bug is missing).

Anyway, thanks for mentioning that.

--- Original Message ---
