### ISSUE TITLE
[Nether Ores] Crash Alongside CustomItems

### ISSUE THREAD

**Issue by CyricV** [CoFH/Feedback#1095]
A crash occurs whenever a Nether Ore detonates when the mod is in a pack with [CustomItems](http://minecraft.curseforge.com/projects/customitems).

Crash Report:
http://pastebin.com/0HnNimHY

**Comment by skyboy** [comment]
This is an error in CustomItems, due to that developer not reading the documentation of the methods they use.

**Comment by CyricV** [comment]
Thanks for the update! [Adding the issue on their bit bucket.](https://bitbucket.org/Otho/metamod-customitems/issues/24/crash-with-nether-ores#comment-25930056)
