### ISSUE TITLE
Thermal Expansion Crash on Startup

### ISSUE THREAD

**Issue by portres** [CoFH/Feedback#1095]
Hello!

When starting my Custom Modpack The game starts on Startup, and leaves this message:
The game crashed whilst initializing game
The game crashed whilst initializing game
Error: java.lang.NoSuchMethodError: cofh.api.util.ThermalExpansionHelper.addCompactorStorageRecipe(ILnet/minecraft/item/ItemStack;Lnet/minecraft/item/ItemStack;)V
When removing all Thermal Expansion related stuff it works.
Please help I really want to use this Mod its one of my Favorites.
Thank you!
[crash-2018-05-18_19.05.51-client.txt](https://github.com/CoFH/Feedback/files/2017820/crash-2018-05-18_19.05.51-client.txt)

**Comment by covers1624** [comment]
Duplicate. https://github.com/CoFH/Feedback/issues/1079 https://github.com/CoFH/Feedback/issues/1094 (and many more).  
Please look before posting issues.
