### ISSUE TITLE
Redstone Furnace + OreCore dupe

### ISSUE THREAD

**Issue by EPSIL0N** [CoFH/Feedback#1096]
When both are installed the redstone furnace has a recipe that appears in JEI to be cycling through all the oredict:oreIron (OC's nether iron and end iron and minecraft iron ore) and cooks them into 2 minecraft:iron_ore which is itself an oreIron list member and in that initial cycle of recipe display, this is the only furnace that seems to have the loop issue so this is why I am asking here.

Also applies to coal, gold and diamond.

**Comment by KingLemming** [comment]
Take it back to them and tell them not to break OreDict convention.

Their ores should be oreNether<thing> and oreEnd<thing>. This is the standard and every other Nether/End ore mod I know of does things this way.

They are literally registering them so as to create a dupe.
