### ISSUE TITLE
Problem with build last CoFHCore

### ISSUE THREAD

**Issue by Ivan-Istomin** [CoFH/Feedback#1097]
So, I want to make minor fix for my modpack, but when I make `gradlew build` I get this error:
[click!](http://hastebin.com/igirohinix.java)

P.S. I don't edit any files in log

**Comment by KingLemming** [comment]
What "minor fix" are you trying to add?

We use non-standard ATs and you won't be able to build the mod.

**Comment by Ivan-Istomin** [comment]
I'm trying to change method which return version of java on system, because when I'm starting my launcher with your mod I get this error:  [click!](http://hastebin.com/ehasihebuq.avrasm)
