### ISSUE TITLE
[Thermal Expansion] Fluid tank voiding liquids

### ISSUE THREAD

**Issue by ZnDevelopment** [CoFH/Feedback#1099]
Dear CoFH team,

when right-clicking a (partially) filled fluid tank in creative mode with an empty fluid container item, some liquid is drained from the container, however without returning any fluid container item holding the drained fluid.
This has been tested on Thermal Expansion 4.0.1-182 on Minecraft 1.7.10. The test included right-clicking tanks of several mods containing the liquids "Petrol" and "Tar" from Zora no Densha in varying amounts. Confirmed while using "Primal Mana" of Thermal Expansion. Both liquids of Zora no Densha are properly registered and show normal behavior in connection with other mods.
Perhaps this is a compatibility issue?

**Mod list**
BigReactors: 0.4.3A
CodeChickenCore: 1.0.4.29-dev
CoFHCore: 3.0.2-262
EnderIO: 2.2.8.367
Mantle: 0.3.2
MinecraftForge: 10.13.2.1230
MineFactoryReloaded: 2.8.0-104
NotEnoughItems: 1.0.3.74
Railcraft: 9.6.1.0
StevesCarts: 2.0.0.b18
TConstruct: 1.8.4a
ThermalDynamics: 1.0.0-122
ThermalExpansion: 4.0.1-182
ThermalFoundation: 1.0.0-81
_All mods on Minecraft 1.7.10._

If there are any further questions, I'll gladly answer them.
Of course it may be an intended feature, however it has been reported to me as a bug of Zora no Densha, and thus - as I was unable to determine any fault on my side - I handed it over to you. I am sorry for any inconveniences.

Greetings!

**Comment by XFactHD** [comment]
This is how creative mode works! If you click on a source block with a bucket, the source block will be removed but you won't get a filled bucket.
