### ISSUE TITLE
Items/Blocks going Invisible

### ISSUE THREAD

**Issue by gigabit101** [CoFH/Feedback#110]
So I left my world running last and came back to this
http://i.imgur.com/vNGVMW1.png
and 
http://i.imgur.com/xuJrAbh.png
re-logging dose not fix
restarting client fix's

**Comment by KingLemming** [comment]
Duplicate of #82.

Also, please go over the readme for how to properly submit an issue. You have included *nothing* about your version or a modlist, so this really tells us nothing.
