### ISSUE TITLE
Launch Failure

### ISSUE THREAD

**Issue by Johnny1023** [CoFH/Feedback#1100]
So basically, I made a test instance in Curse, added **only** CoFHCore-[1.7.10]3.1.2.325.jar and did all the recommendations (Update Java to 8u73, remove old Java, download from official source, and checked for duplicates), and yet, the game **always** stall and crash at the CoFHCore initialization stage.

Below is my specs and Game Output (Game did not generate crash report)

http://pastebin.com/7tyU9Nnr

Mods:
As told above, only CoFHCore

**Comment by XFactHD** [comment]
Can you allocate more than 1 GB of RAM to Minecraft?

**Comment by Johnny1023** [comment]
I usually do, but my PC lowers it down to 958MB for some reason.

**Comment by XFactHD** [comment]
That doesn't make sense.

**Comment by KingLemming** [comment]
Your log doesn't indicate any issues other than you not allocating enough RAM. Sorry, this isn't the fault of the mod. Try IRC for tech support.
