### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by lobbienjonsji** [CoFH/Feedback#1100]
The game crashed whilst initializing game
Error: java.lang.NoSuchMethodError: cofh.api.util.ThermalExpansionHelper.addCompactorStorageRecipe(ILnet/minecraft/item/ItemStack;Lnet/minecraft/item/ItemStack;)V

I got this crash when starting up the game.

**Comment by lobbienjonsji** [comment]
It might be a mod trying to add a recipe to the compactor, that has changed.

**Comment by KingLemming** [comment]
Disable ThermalExpansion compatibility in BaseMetals.
