### ISSUE TITLE
Crash with foundry

### ISSUE THREAD

**Issue by lobbienjonsji** [CoFH/Feedback#1101]
The newest version of thermal crashes with foundry. I already put this issue on the foundry github, but by the looks of it the mod is probably never going to be updated again. 
[crash-2018-05-22_19.22.11-server.txt](https://github.com/CoFH/Feedback/files/2028352/crash-2018-05-22_19.22.11-server.txt)

**Comment by lobbienjonsji** [comment]
This only happens on servers by the way.

**Comment by KingLemming** [comment]
You don't have CoFH World installed. Please go install it.
