### ISSUE TITLE
[ThermalDynamics] Chunk Error with Fluiducts

### ISSUE THREAD

**Issue by DrakoAlcarus** [CoFH/Feedback#1101]
When logging into the game, ducts bordering the edge of a chunk tend to disconnect:

<a href="http://imgur.com/UGy1bIa"><img src="http://i.imgur.com/UGy1bIa.png" title="source: imgur.com" /></a>

**Comment by Fabboz** [comment]
I had got the same problem but with fluxducts. I solved that using a chunkloader or ending the line in the bugged chunk with a battery. I wa using the lastest optifine ultra. With me happend not everytime at the world load... but everytime going very far to that chunk and then coming back(chunk unload/reload). Do some test and say the results plz

**Comment by DrakoAlcarus** [comment]
A chunk loader doesn't help. Flying out of the chunk to refresh fixes it, but only temporarily.

**Comment by Fabboz** [comment]
i think is better if you test in a forest not in flatland

2016-03-08 14:50 GMT+01:00 DrakoAlcarus <notifications@github.com>:

**Comment by DrakoAlcarus** [comment]
I am in a birch forest. I used RS tools to flatten it out for a village.

**Comment by KingLemming** [comment]
If leaving the chunk fixes it, then this seems to be visual only.

**Comment by DrakoAlcarus** [comment]
Any permanent fix?

And yes, it's definitely visual,  because water still flows through to my Igneous Extruder.

**Comment by skyboy** [comment]
Then it's not a major concern, the client-side logic is being iffy.

**Comment by DrakoAlcarus** [comment]
Yes, I know it's at the bottom list of priorities, but is there a chance it will ever get fixed?

**Comment by Fabboz** [comment]
Try moving the tank in the place of the igneous and see if temporary fix ... maybe can help finding a solution

**Comment by DrakoAlcarus** [comment]
I don't think it will help find a solution, but it's fine. It's not game breaking, otherwise I would have been fixed by now.
