### ISSUE TITLE
TE Fluid Transposer and Lava Eggs

### ISSUE THREAD

**Issue by Shixpe** [CoFH/Feedback#1107]
Using the Lava Eggs from the Chickens mod in the fluid transposer leaves a non-item egg with a red 0, it doesn't disappear or move to the leftover slot.  I know it works with enderio tanks. but it didn't leave anything after melting the egg.

![image](https://user-images.githubusercontent.com/39637796/40570503-9a8f3cfa-6059-11e8-89f4-a1cf905d94ca.png)

ThermalExpansion-1.10.2-5.1.9.23-universal

**Comment by KingLemming** [comment]
1.10.2 is unsupported now, sorry. The way this code works, however, the quirk is on the egg. If there's a 1.12 version of the mod and it still happens, I'd advise you report it to them.
