### ISSUE TITLE
[Suggestion] Shortening the RF numbers

### ISSUE THREAD

**Issue by CaptainBacon94** [CoFH/Feedback#1108]
The number of RF you have in a machine (the actual number) is hard to read, because it's very long.
This is specially annoying when comparing two devices with stored RF in them (ex. 1945631 and 117630. My suggestion is to add commas and/or points to it, so "1945633 and 117630" is just "1945.633 and 117.630" or "1,945,633 and 117,630", maybe even "1,945.633 and 117.633" so it is a lot easyer to determine how much RF is in your machine. A lot easyer to read isn't it? 

PS: Sorry for my bad english

**Comment by KingLemming** [comment]
It's already shortened in item form, which is where it actually matters. Commas/points requires localization code that there isn't really cost/benefit for.
