### ISSUE TITLE
[Thermal Expansion] Energy Cell Configuration Tab Glitch??

### ISSUE THREAD

**Issue by pchard** [CoFH/Feedback#1109]
Hello.

Everything was working perfectly fine a few days ago, but today, when I got on my server (it happens to everyone on the server), this has happened on the Energy Cell Configuration Tab:

https://pchard.gyazo.com/087abe96db6a34726f8499fe70024062

This happens on ALL of the Thermal Expansion Energy Cells.

**Comment by pchard** [comment]
Relevant to #1107 - So clearly, this is an issue with something.

**Comment by pchard** [comment]
I see this in my client log:
`[11/3/2016 10:21:43 AM] [Client thread/INFO] [inventorytweaks]: cofh.thermalexpansion.gui.client.GuiCell
[11/3/2016 10:21:43 AM] [Client thread/INFO] [inventorytweaks]: cofh.thermalexpansion.gui.container.ContainerTEBase`

Could be relevant?

**Comment by XFactHD** [comment]
No, that's just the InvTweaks dev being dumb and not removing his debug output.

**Comment by KingLemming** [comment]
This isn't on us. If you updated mods and some of them are screwing with us, then that could be it. But it's not CoFH.
