### ISSUE TITLE
With all the latest versions on curse I get a crash at start up if install laset ProjectRed

### ISSUE THREAD

**Issue by Tsyklop** [CoFH/Feedback#111]
If install laset ProjectRed server crash.
CrashLog: http://pastebin.com/vDuYRdBL

**Comment by KingLemming** [comment]
No, what you meant to say is "With the alpha versions on CurseForge..."

Try again with the versions the Feedback page clearly tells you to use. You're using alphas.

However, you did show us that Project Red is doing something they aren't supposed to, so thank you for that. :) I'll have to go yell at them.
