### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by ParkerJones** [CoFH/Feedback#1111]
I'm creating a custom modpack and received this crash, I'm not sure whats going on here. Any suggestions?

Crash Report:
[crash-2018-05-28_14.14.13-client.txt](https://github.com/CoFH/Feedback/files/2045887/crash-2018-05-28_14.14.13-client.txt)

Modlist:
![image](https://user-images.githubusercontent.com/34404606/40625951-8968249c-6283-11e8-8364-8f761083a754.png)

**Comment by KingLemming** [comment]
No idea what's happening there, but it's not in our code.

If it were on our end, literally everyone would get that crash all the time and nobody would be able to play. We'd have been inundated with reports and would have issued a fix immediately. We also never would have shipped something that broken in the first place.

Obviously, that isn't the case, so either you have busted mods and you didn't download the latest versions from CurseForge, or you have another mod shredding our API. Start with CoFH mods and add jars until you figure out who is at fault.
