### ISSUE TITLE
Thermal Dynamics, the chunks are not unloaded after they are left by the player.

### ISSUE THREAD

**Issue by Mr-Krab** [CoFH/Feedback#1112]
Mod conflicts with SpongeForge.
Minecraft: 1.12.2
SpongeAPI: 7.1.0-SNAPSHOT-43d8496
SpongeForge: 1.12.2-2703-7.1.0-BETA-3119
Minecraft Forge: 14.23.4.2703
Thermal Dynamics v2.4.1

Chunks are not unloaded even after the player leaves the server.
This creates performance problems.

**Comment by KingLemming** [comment]
We don't do anything with chunkloading. There's a callback for when a chunk is unloaded, and stuff happens.

That is normal Forge behavior - blocks/tiles are allowed to do things when chunks unload - and SpongeForge needs to handle it. That's not on us.
