### ISSUE TITLE
[DEV] MCP Mappings

### ISSUE THREAD

**Issue by XFactHD** [CoFH/Feedback#1113]
After updating the mcp mappings of my workspace to stable-12, I am unable to start MC indev if I have CoFHCore, Thermal Foundation and Thermal Expansion in the lib folder. I suspect that the dev versions of those mods are not using the latest mcp mappings for 1.7.10.
This is the startup log: http://pastebin.com/r6XPurcK
The versions used are the latest ones as of now.

**Comment by skyboy** [comment]
Fixing it for you breaks it for everyone else. Hands are tied.

**Comment by XFactHD** [comment]
Is there a way for me to fix this without you giving me the raw source code?

**Comment by skyboy** [comment]
You can use my fork of BON to remap the obf versions to your MCP version

**Comment by XFactHD** [comment]
Ok, I'll try that.

**Comment by XFactHD** [comment]
I reverted back to the old mappings because nobody seems to be interested in using the latest mappings and it is just to big of a hassle for me to deobfuscate all my dependencies with BON. Thanks anyway for your help.
