### ISSUE TITLE
[1.7.10] forge requesting specific CoFHCore version

### ISSUE THREAD

**Issue by ProxyPlayerHD** [CoFH/Feedback#1114]
said version is not on curse.
![2018-05-29_15-34-21](https://user-images.githubusercontent.com/13576843/40662452-adf518f0-6356-11e8-9fa8-41e3d650bcf1.png)
it either wants 1.7.10 R3.2.0 or R3.1.0 and the ONLY version on curse is R3.1.4, if i use that it will just crash with a mod sorting error.

https://pastebin.com/UPR4jncS

I'm not even 100% sure if this is a CoFHCore problem, but i cannot really test it since i have no access to the versions Forge wants.

**Comment by Tahakk** [comment]
**1.** 1.7.10 is not supported
**2.** I was able to lauch Minecraft 1.7.10 with basic CoFH mods and Forge 10.13.4.1614

If you have any following problems you should go to Discord.

**Comment by KingLemming** [comment]
That is not what that says. It says it requires a version between 3.1.0 and 3.2.0.
