### ISSUE TITLE
COFH/Chromaticraft cross mod problems

### ISSUE THREAD

**Issue by 1skandar** [CoFH/Feedback#1114]
See this: https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/686

**Comment by skyboy** [comment]
fluid registration: https://github.com/CoFH/ThermalFoundation/blob/master/src/main/java/cofh/thermalfoundation/fluid/TFFluids.java#L50-L56

recipe registration: https://github.com/CoFH/ThermalFoundation/blob/master/src/main/java/cofh/thermalfoundation/item/TFItems.java#L212-L213

TE itself will auto-regonize buckets for filling/draining via the transposer, and all other interactions are handled by forge. There's no bug on our side, and the only bug i would guess Reika has is that his buckets aren't in the oredict but that wouldn't explain those buckets becoming useless for interacting with tanks.

**Comment by ReikaKalseki** [comment]
As per my thread, my guess is Forge only half-implementing fluid persistence.
