### ISSUE TITLE
Redstone Arsenal crashes on using Omniwrench on Minechem blueprint projector without IC2 installed?

### ISSUE THREAD

**Issue by BlazingGamer** [CoFH/Feedback#1115]
http://codepad.org/GNTiNfAV
RA build 92, Cofh core 325, Minechem 406 and other mods (list in crash report)

**Comment by KingLemming** [comment]
Just checked the jar. It's there. What is likely happening is that you have a mod improperly shipping only part of the IC2 API (with package-info) and claiming that it's the full thing.

Try making it happen with only CoFH mods and Minechem.

**Comment by BlazingGamer** [comment]
Just tested with RA+Minechem+TE and all was fine, thats not ur mod issue, sorry.
