### ISSUE TITLE
Java crash in Thermal Expansion

### ISSUE THREAD

**Issue by Travis9x** [CoFH/Feedback#1116]
The game crashed whilst initializing game
Error: java.lang.NoSuchMethodError: cofh.api.util.ThermalExpansionHelper.addCompactorStorageRecipe(ILnet/minecraft/item/ItemStack;Lnet/minecraft/item/ItemStack;)V

**Comment by Travis9x** [comment]
Not sure how to label this as a bug

**Comment by KingLemming** [comment]
This is a duplicate like 50x over. Disable Thermal Expansion compatibility in Base Metals.
