### ISSUE TITLE
Cryo-stabilized fluxducts can input power above the recipient's max input rate when connected to multiple power producing sources

### ISSUE THREAD

**Issue by Divran** [CoFH/Feedback#1117]
It seems that when you connect cryo fluxducts to multiple energy producing sources, and then hook them up to an energy storage (ender io capacitors, or thermal expansion energy cells, doesn't matter), then the cryo-fluxducts have the ability to insert energy faster than the max transfer limits of the receiving device, depending on how many inputs your cryo-fluxduct network has.

Example:
1. Place a creative energy cell.
2. Connect three of its sides to a few cryo fluxducts.
3. Place a leadstone energy cell (max input, supposedly 200 rf/t)
4. Connect the cryo fluxducts to the leadstone energy cell.

The leadstone energy cell will now receive 600 rf/t, due to the fluxducts being connected to three energy producing sources. You can more easily see this effect if you use an ender io capacitor bank, since they will tell you their current input rate when you look at them.

I believe this might be caused by the cryo-fluxducts transfering power three times per tick, due to having three seperate connections to the creative energy cell (this also works if the sources of energy are three different sources). Brandon3055 over at draconic evolution also thinks this is the case (see link below).

See https://github.com/brandon3055/Draconic-Evolution/issues/236#issuecomment-199019654 for more information

**Comment by KingLemming** [comment]
This is correct behavior. Limit is not per tick. It's per transaction.

**Comment by Zaflis** [comment]
Doesn't that make it a bug on Energycells side then? We have learned to believe that the input limit is absolute per side. Cryotheum duct sort of overdrives the input rate here, you could inject over a million RF/t into a single leadstone energycell per tick, providing enough outputs to it.

**Comment by skyboy** [comment]
There's no practical benefit to limiting energy cells per tick. So it is a "bug" but it's one with consequences that amount to nil and so is not worth the time nor effort of correcting.

You're welcome to complain about it, but it's not a bug that will be corrected unless someone pays one of us to do so.

**Comment by Divran** [comment]
Saying it's intended behavior to bypass the input rate of nearly every block in all of minecraft is a bit strange, and it's easy to fix. Also,  it is a problem for blocks where limiting the energy input is important, such as the draconic generator. However, the Flux gate has already been fixed according to brandon.  It just looks like I'm using a slightly older version of DE.

**Comment by KingLemming** [comment]
> It's easy to fix, too

Oh really? Please, go on.

It's the reality of a push-based power system. Any block which really wants to limit the input going to it in a given tick needs to do that on its end. There's not actually any way to do that with ducts.

**Comment by Divran** [comment]
Well I'm not a minecraft developer, but... One way I can see it being solved is if you keep a list of how much power each machine that's connected to the network has received in the current tick. Listening to myself say this I can hear it doesn't really make sense to do this in Java, although it wouldn't have been crazy to do it in other things I've developed for.

So since the above solution would probably be bad, you could limit it per output. Each cryo-duct output can simply retrieve the max input of whatever it's connected to and then ensure that it doesn't output more than that in a single tick. This shouldn't be hard to implement, but it will only solve half of the problem. If you connect the same machine on multiple sides, it's possible you'd still see the same problematic effect. It would help, but it wouldn't be a complete solution.

So yes it seems you're right and the real way to solve it is on the receiving end. No one does this at the moment, though. Luckily it's not such a big deal, except in the case of the draconic reactor (where it's a very big deal). In that case, though, we have the flux gate to solve the problem.

Alright then, this issue can remain closed. Thanks for your help.

**Comment by skyboy** [comment]
Yes connecting on multiple sides has the same problem, but worse: what if you connect two generators to that block raw, suddenly you have 2x the input rate; and it's impossible to stop on the delivery side because what if someone does the unthinkable! They might use different mods to do this!
Of course, this frequently doesn't matter. on energy cells the input limiting is rarely, if ever, a critical concern; while the output rate may be, that's unaffected by the input rate. For things like pulverizers, it also doesn't matter because they're going to spend most of their time full, and when in-use they're being capacity-limited to their usage rate, etc. It's just something that has to be resolved case-by-case in other mods that need strict input limits.

**Comment by Divran** [comment]
Well I'm definitely not afraid to admit when I'm wrong!
