### ISSUE TITLE
[1.12.2] [Thermal Dynamics] Inventory Glitch when placing a Servo

### ISSUE THREAD

**Issue by MasterEnderman** [CoFH/Feedback#1117]
Everytime on a server when a player places a servo on a duct the items in the inventory are placed in weird positions. Everything works fine in Singleplayer.

Screenshots of Inventories after placing a Servo:
https://cdn.discordapp.com/attachments/420941560683954176/451416365610565633/Screenshot_9.png

https://images-ext-2.discordapp.net/external/875trN-2KAy7x8wm7IlVZyY-0i8Njb6TIV68is61rHQ/https/image.prntscr.com/image/UP7z-gg3Q1mxysSfbAcNGw.png

https://cdn.discordapp.com/attachments/420941560683954176/443765902291501057/unknown.png

Forge: 14.23.4.2705 
CoFH Core: 4.5.1
CoFH World: 1.2.0
Thermal Dynamics: 2.5.1
Thermal Expansion: 5.5.0
Thermal Foundation: 2.5.0

Modlist: https://pastebin.com/8Lqktp2V

**Comment by MasterEnderman** [comment]
It isn't caused by Inventory Tweaks, which was my first guess.

**Comment by MasterEnderman** [comment]
Does this point to something?
https://paste.dimdev.org/iguficofap.mccrash
A player got that crash after he placed down a servo and his inventory freaked out again. Then he opened his inventory and clicked on the servo.

**Comment by KingLemming** [comment]
It points to you having something installed which is doing something dumb, but beyond that no.

**Comment by KingLemming** [comment]
This ultimately isn't caused by our code, as I cannot replicate it under any circumstances on a normal MP server.
