### ISSUE TITLE
[ThermalExpansion] Serious dupe bug with Caches and Chisel

### ISSUE THREAD

**Issue by Esctogrillo** [CoFH/Feedback#1118]
Right click a Chisel and put any block/item do you want and close the GUI.
Right click with the chisel on a Cache and the Chisel GUI will open (with your itens) and will save on cache. Move the items (from the GUI) to your inventory and remove the chisel on cache, you will receive a new chisel with the same items.

I can make a video if do you want.

**Comment by skyboy** [comment]
This is a bug with chisel.
