### ISSUE TITLE
[Thermal Dynamics] Suggestion: An item to replace/upgrade already placed  fluxducts

### ISSUE THREAD

**Issue by TheDarkLordZ10** [CoFH/Feedback#1118]
You should add a tool or item which lets you replace a section of fluxducts with a different tier. It could be an upgrade or feature to the crescent hammer.

**Comment by leojaxx** [comment]
Ya, or even able to right click the placed ones with the new ones like the EIO ones.

**Comment by KingLemming** [comment]
Might happen with a rewrite. Tagging and closing for now, but keeping in mind.
