### ISSUE TITLE
Item disappearing in itemducts

### ISSUE THREAD

**Issue by Lazyboy007** [CoFH/Feedback#1119]
Hey!

I was using itemducts to transport items from one place to another (using FTB Revelations, latest version), and noticed items were disappearing in my inventory. I ran further tests in a test world (see video, you can see 64 coal become 8). You will see in the video that I placed a servo by mistake midway, that doesn't affect the bug. I can recreate it very consistently with the setup shown.

https://youtu.be/P1hMgBMEBh4

I hope this issue hasn't been fixed already, in which case I'm very sorry :x 

Good luck!

**Comment by KingLemming** [comment]
Bug with vanilla furnaces. Don't use them.
