### ISSUE TITLE
[CoFHCore-1.10.2-4.1.0.155-universal] Crash on load; NullPointerException

### ISSUE THREAD

**Issue by CocoaMix86** [CoFH/Feedback#112]
Attempting to add CoFHCore to my mc 1.10.2 modpack in order to use Thermal Foundation and such results in a crash shortly after launching the pack. Something along the lines of a Null Pointer to a Rendering Screen. Removing CoFHCore fixes the issue. Issue persists even while having this version of CoFHCore on its own

Crash: [http://pastebin.com/0TJ7XmKC](http://pastebin.com/0TJ7XmKC)
modlist: [http://pastebin.com/pbVSCutb](http://pastebin.com/pbVSCutb)

**Comment by KingLemming** [comment]
Update Forge. We aren't anywhere in that stack trace.
