### ISSUE TITLE
Suggestion for Vanilla Tools for better cross-mod compat

### ISSUE THREAD

**Issue by Sunconure11** [CoFH/Feedback#1122]
Since multiple mods implement the same materials your flagship mod uses, would it be possible to add support for other various modded materials in it, provided they are detected? I.e for instance, one could have copper sickles without having thermal foundation installed.

If accepted, porting over the horse armor might also be nice.

Also, is redstone flux really needed as a dependency for it? It's downloaded as such via curse.

**Comment by KingLemming** [comment]
For 1.13+, it's a maybe, and in that case I would remove them from Thermal Foundation. But I'm not going to duplicate all of the content AND add a bunch of extra checks right now, sorry.
