### ISSUE TITLE
Make the Induction Smelter accept the Zinc from Flaxbeard's Steam Power...

### ISSUE THREAD

**Issue by Krands** [CoFH/Feedback#1122]
### ... so we could make Brass without having to build an Immersive Engineering's Arc Furnace.

Hi,

I am playing on yet another server, and the operator have been clear about this: 
> _we will not add Railcraft because it makes the Vanilla rails unecesseraly expensive._

This means no Steam Boiler from this mod, which is 2.4 times more interesting in the long term, relying to the wiki. To find a solution to use my big charcoal production, we found the _[Flaxbeard's Steam Power] (https://github.com/Flaxbeard/SteamPower)_ mod and installed it.

The main material of this mod, is **Brass**. To product this alloy, we need 3 pulverized copper for 1 zinc ingot. The Induction Smelter can do that.

However, the only available recipe is available in BluSunrize's _[Immersive Engineering] (https://github.com/BluSunrize/ImmersiveEngineering)_'s Arc Furnace, which is a pain to build, but even more: to use. To be fair, it's unecesseraly adding difficulty. :sob: 

The Furnace is only usable with _Graphite Electrodes_, needing a blueprint to be crafted, probably almost impossible to get, as **it's not craftable**, but you have to get it from chests and villagers. The ability to get this is 6%, so we have to generate the World.

So, would you, in next update, make possible to alloying Brass  in your Induction Smelter? This would make players' life "_a bit_" easier.

Thank you! :beers:

**Comment by XFactHD** [comment]
Tell the devs of Flaxbeard's Steam Power to add this recipe to the induction smelter via IMC. The CoFH devs can't account for every damn alloy some mod might add.

**Comment by Krands** [comment]
Ho I am sorry. I thought it was CoFH's team to do that.

I will ask to them, then.

Thanks.

**Comment by KingLemming** [comment]
To be fair, if this is an agreed upon blend for zinc, I don't have an objection.

**Comment by Krands** [comment]
Well, i don't know. I actually talked about it with Esteemed Innovation staff. I made an (issue) [https://github.com/Esteemed-Innovation/Flaxbeards-Steam-Power/issues/375].

AWhileI was at it, I asked for a bit more, and asked for further compatibility. This mod is new born, but really promising.
