### ISSUE TITLE
Block duplication bug.

### ISSUE THREAD

**Issue by wsanders99** [CoFH/Feedback#1123]
- Pack: Foolcraft 3 v1.1.1
- Thermal Foundation 2.4.1.15
- Thermal Expansion 5.4.2.27
- MeeCreeps 1.1.0
- Forge 14.23.3.2673

Referencing McJtyMods/MeeCreeps#38 in regard to a duplication bug when a creep cube is used to flatten an area, build a platform, (possibly others, as evident by the above issue).

When the blocks are broken, two drop in their place.

**Comment by KingLemming** [comment]
This is on the mod doing the breaking.
