### ISSUE TITLE
Thermal Expansion - Energy cell energy control option

### ISSUE THREAD

**Issue by tytannial** [CoFH/Feedback#1124]
100/1000 for 32000 ....320/32 clicks, It's not cool.
Suggestion:
1000/10000 for >10000 per click
200/2000 for <=10000 per click
100/1000 for <=3000 per click

**Comment by skyboy** [comment]
What?

**Comment by tytannial** [comment]
....I mean this
![qq 20160331190756](https://cloud.githubusercontent.com/assets/11215623/14173969/f3415b54-f773-11e5-84b5-fe80aea31ad1.png)

**Comment by skyboy** [comment]
Hold down ctrl+shift.

**Comment by tytannial** [comment]
Thanks
