### ISSUE TITLE
Server crashes when blocking damages from guardians using redstone arsenal shield

### ISSUE THREAD

**Issue by modmuss50** [CoFH/Feedback#1124]
Issue: Server crashes when taking guardian laser attack damage

Link to Log or Crash File Paste: https://paste.feed-the-beast.com/view/4939775d

Is it Repeatable?: yes, get hit by a guardian using the redstone arsenal shield

Mod/s Affected: Redstone arsenal

Taken from: https://github.com/FTBTeam/FTB-Continuum/issues/122

**Comment by KingLemming** [comment]
This was fixed last night already.

**Comment by modmuss50** [comment]
Nice, thanks sorry for not seeing that 👍

**Comment by KingLemming** [comment]
Actually, last "night" is incorrect. It's been 17 hours.
