### ISSUE TITLE
Fluxducts not stacking properly

### ISSUE THREAD

**Issue by SlyJacobTheBeast** [CoFH/Feedback#1126]
I have ran into this issue (my version: ThermalDynamics-1.12.2-2.5.1.13-universal) where fluxducts are not stacking (some are, some are not), instead they will be placed either individually or into groups. For example I would go and break leadstone fluxducts in my network with crescent hammer and I would get 5 individual ducts, group of 4 ducts and group of 2 ducts. Is that because of their RF content? When I place them down and break them with pickaxe, it seems to fix that problem,

**Comment by KingLemming** [comment]
Yes known. It's minor, fixed in dev. No ETA because it really doesn't matter.
