### ISSUE TITLE
Mechanics do not work

### ISSUE THREAD

**Issue by Kreatifchk** [CoFH/Feedback#1127]
Hello! Mechanisms do not work. All. Earlier helped restart the game, now it does not work either. If you put things into the mechanism and restart the game, they will lie in the finished version, but if you put them again there they will not be recycled. Sometimes they start working in after a long while. Redstone control off

**Comment by Kreatifchk** [comment]
Sometimes they start working in after a long while.

**Comment by KingLemming** [comment]
This is not the case at all, no. You have something else going on, but the mod works.
