### ISSUE TITLE
Fluxducts not combining (Holding their energy?)

### ISSUE THREAD

**Issue by 34486** [CoFH/Feedback#1128]
Ok I updated to the very latest version, running Forge 2705 and the latest version of all the current 1.12.2 Team CofH mods.. 

I break a conduit, a couple, they didn't stack. I am assuming this is because they are holding their energy? I get no errors in the console/client output.

**Comment by Notawallplan** [comment]
Install Actually Additons and press F3-H

Then check the NBT of the conduits. :D

**Comment by KingLemming** [comment]
Very latest version? I don't believe you. What's the version number?

**Comment by KingLemming** [comment]
I'm going to go ahead and close this now, because that was a rhetorical question and I felt a bit Socratic in my response.

You do not have 2.5.1.14. Go download it.

**Comment by 34486** [comment]
Its not even up for download now, huh. It is ThermalDynamics-1.12.2-2.5.1.13-universal all I see now is 1.14 and before that is 0.12....... I'll have to update when I get time

**Comment by Tahakk** [comment]
I can see [it](https://minecraft.curseforge.com/projects/thermal-dynamics/files/2569008/download)
