### ISSUE TITLE
Thermal Expansion

### ISSUE THREAD

**Issue by lightning02** [CoFH/Feedback#1128]
![agricraft 1 5 thermal expansion crash on thermos](https://cloud.githubusercontent.com/assets/11884147/14234078/273759be-f9da-11e5-8b31-54a86fce8740.png)

crash when trying to added agricraft 1.5.0 by the way the server logs seems to blame thermal expansion

**Comment by KingLemming** [comment]
The issue there is with AgriCraft not correctly OreDicting things. It's doing it too late and/or improperly.

**Comment by lightning02** [comment]
thanks for the answare, i'm apologize to have think that is your mod error! 
i ask to agricraft owner so!

**Comment by KingLemming** [comment]
No worries. The error would certainly suggest that it is.

**Comment by lightning02** [comment]
They told me that is your mod error.
I post here the full log: http://pastebin.com/ZFSRSKkC (take a look of the referenced agricraft)

**Comment by KingLemming** [comment]
It is not. Sorry. That error gets thrown when things are being OreDicted late or properly, period.
