### ISSUE TITLE
[Thermal Expansion] Cyclic assembler not take items automatic

### ISSUE THREAD

**Issue by Usernm0** [CoFH/Feedback#1129]
I use simple setup, cyclic assembler should take items from left chest using integrated hopper apparatus and output items to the right chest:
![](http://i.imgur.com/eyyuqpy.png)

If i put items in cyclic manually or using pipes - it craft recipe correctly. If i use pulverizer or other machine in same setup it works correctly too. 

I play FTB Infinity Evolved modpack, if it important.

**Comment by KingLemming** [comment]
Intentional. Auto-Input is extremely CPU intensive and I don't want people killing servers with it.
