### ISSUE TITLE
Ores Aren't Generating

### ISSUE THREAD

**Issue by Sweddy** [CoFH/Feedback#1129]
This is quite odd. When I created my world, none of the Thermal ores generated, and they were all excluded from Just Enough Items' menu. 
I could find them in recipes displayed by JEI and in the creative menu, but as I said, none of the ores generated and they can't be searched for in JEI.

I am using the latest version of all the Thermal mods.

As for other mods, the only other ones I could consider to maybe have an effect are:
- Galacticraft v.177
- Dungeons2
- maybe JEI??
(I have some more installed but none I could consider to be the cause of this issue)

**Comment by Tahakk** [comment]
Then you probably set up something wrong. Tell us more what you did.

**Comment by Sweddy** [comment]
I don't know what I could've set up wrong. All 5 Thermal mods are placed within the mods folder alongside all other mods, etc.

## Anyway so, here's an extensive list, excluding the Thermal mods of course:
Content:
- ChickenChunks _2.4.1.71_
- Pam's HarvestCraft
- Cooking for Blockheads _6.3.26_
- Doomlike Dungeons _1.11.1_
- Dungeons2 _f14.21.1.2387_
- Familiar Fauna _1.0.10_
- Galacticraft Core _4.0.1.177_
- Galacticraft Planets _4.0.1.177_
- Extra Planets _0.3.8_
- More Planets _2.0.14_
- Gravestone _1.10.1_
- Hopper Ducts _1.5_
- Hunger Overhaul _1.3.3_
- Industrial Foregoing _1.9.2-170_
- Intergration Foregoing _1.6_
- Instant Unify _1.1.1_
- Just Enough Items _4.9.2.196_
- Just Enough Resources _0.8.5.27_
- Just Enough HarvestCraft _1.5.1.0_
- MystCraft _0.13.4.02_
- OptiFine _HD-U-C8_
- Recurrent Complex _1.4.7_
- Steve's Carts _2.4.18.92_
- UniDict _2.5b_

Minor/Cosmetic:
- Dynamic Dynamos _1.8_
- Dynamic Lights
- Dynamic Surroundings _3.4.7.2_
- Fast Leaf Decay _v14_
- Finite Water Control _1.0_
- Inventory Tweaks _1.63_
- No Recipe Book _1.1.0_
- Serene Seasons _1.0.0_
- Simulated Nights _2.1.0_
- Sound Filters _0.10_

Core/Library:
- AppleCore _3.1.1_
- AutoRegLib _1.3-17_
- Bookshelf _2.3.544_
- CodeChickenLib _3.1.8.341_
- CoFHCore _4.4.1.12_
- ForgeLin _1.6.0_
- GottschCore _f14.21.1.2387_
- IvToolkit _1.3.3_
- MicdoodleCore _4.0.1.177
- MJRLegendsLib _1.1.4_
- Model Loader _1.0.5_
- RebornCore _3.8.3.279_
- Redstone Flux _2.0.1.2_
- Tesla _1.0.63_
- Tesla Core Lib _1.0.14_
- WanionLib _1.5_
- WrapUp _1.1.3_

**Comment by KingLemming** [comment]
I don't see CoFHWorld on there. There's your issue.

**Comment by Sweddy** [comment]
Nonononono I simply forgot to list it! This will require some explaining. 
I have a seperate folder where I store all my personal mod packs. I was using an older version of the Thermal mods which had no requirement for CoFHWorld. I updated the Thermal mods which now required CoFHWorld, so I added that. (This did not work)
After removing and re-adding mods for some while I gave up and overwrote the mods folder with my backup which I had not updated the mods in.
The list I made was of those mods, and I simply forgot having added CoFHWorlds!

**Comment by KingLemming** [comment]
Right, the point is, you have messed something up on your end.

If you have all the mods correctly installed and have not screwed up your worldgen files, the ores generate.

**Comment by Sweddy** [comment]
Well that's terrible then isn't it. What could it possibly be? Do you have any possible idea? I'm up for anything at this point.
Even weirder is that I haven't touched Minecraft in months nor have I ever in my life touched anything other than the mods folder. And it worked last time I played.

**Comment by KingLemming** [comment]
So, I downloaded jars from CurseForge, put them in a fresh instance, fired it up and...ores generate, as expected.

Delete your config folder and let it regen. Ensure that it isn't write-protected.

**Comment by Sweddy** [comment]
It actually worked, thanks!
