### ISSUE TITLE
Other mods improperly interfacing with TE crafting handlers

### ISSUE THREAD

**Issue by Cronosus** [CoFH/Feedback#113]
TE crashing on server (b9-88): http://pastebin.com/NnMkd42P

core b9-142

**Comment by KingLemming** [comment]
You have another mod directly manipulating Smelter behavior. This is dangerous and stupid on the part of that mod author.

I'll see about adding something to guard against this.

**Comment by Cronosus** [comment]
ok, thanks.
i think its by Thermal Smeltery
i remove it from server

**Comment by KingLemming** [comment]
I don't think it's actually on Thermal Smeltery. Despite the name, I'm fairly sure that's a mod for the Crucible.
