### ISSUE TITLE
[UPDATED] Ores Aren't Generating

### ISSUE THREAD

**Issue by Sweddy** [CoFH/Feedback#1130]
The ores in this mod are not generating in the overworld.
I am currently using NO OTHER MODS than the latest/recommended versions of all the Thermal mods and their requirements. To prove it, here's a list of the only mods I have installed:

- CoFHWorld _1.2.0.5_
- CoFHCore _4.5.2.19_
- Thermal Expansion _5.5.0.29_
- Thermal Dynamics _2.5.1.14_
- Thermal Foundation _2.5.0.19_
- Thermal Innovation _0.3.0.7_
- Thermal Cultivation _0.3.0.7_
- RedstoneFlux _2.0.2.3_
- CodeChickenLib _3.1.8.341_

**Comment by KingLemming** [comment]
Do not open duplicate issues.
