### ISSUE TITLE
Autonomous Activator Effecting WorldEdit

### ISSUE THREAD

**Issue by Zendrex** [CoFH/Feedback#1132]
The Autonomous Activator seems to bug worldedit when it does its left and right click events.

Warmroast stack here.

https://i.gyazo.com/285b45e282fae40013fb681e5cc80dac.png

This seems to effect any type of permissions database.

**Comment by KingLemming** [comment]
Elaborate on what exactly you're trying to show here.

The AA is a player. It needs permissions. If the database can't handle that, welp. :|

**Comment by Zendrex** [comment]
The issue is that WorldEdit cant seem to tell that the block is an actual player with potential permissions. 

Even if I were to know the name of the block (as defined by the game as a player) and give it worldedit permissions, WE stalls when trying to search for what the block/player is. Does it have a uuid? If not, maybe give it one?

**Comment by Zendrex** [comment]
WE then stalls out and kills server performance. It makes the server unplayable, non responsive, etc.

Also, this isnt a mod that handles permissions, its permissionsEx. (FTB Infinity with Thermos)

**Comment by bookerthegeek** [comment]
You need all the fake player names for cofh

**Comment by skyboy** [comment]
UUID: https://github.com/CoFH/CoFHCore/blob/master/src/main/java/cofh/core/entity/CoFHFakePlayer.java#L21

As for hanging and such, that's not our issue. It's the bukkit plugin which lacks any form of quality.
