### ISSUE TITLE
[code] Custom worldgen issues

### ISSUE THREAD

**Issue by AnrDaemon** [CoFH/Feedback#1133]
http://pastebin.com/gkzgjvVQ

I have tried this stuff to get me some Sky Stone in the world.
Nothing succeed.

**Comment by KingLemming** [comment]
Well according to http://jsonlint.com/ you aren't giving it a valid JSON file.

**Comment by AnrDaemon** [comment]
That link spewing bullshit. I can't comprehend its ranting. Complete nonsense.
Says it expect "string, then '}'", points to EXACTLY that construct, and claims that it's "undefined".
Mod parsed it just fine, so did all the tools I've on hand.
The similar JSON
```
{
    "airInfusedOre": {
        "template": "uniform",
        "block": { // Air
                "name": "Thaumcraft:blockCustomOre",
                "metadata": 1
            },
        "material": "minecraft:netherrack",
        "clusterSize": 4,
        "numClusters": 3,
        "minHeight": 0,
        "maxHeight": 128,
        "retrogen": "false",
        "biomeRestriction": "none",
        "biomes": [],
        "dimensionRestriction": "none",
        "dimensions": []
    }
}
```
provides desired results.

**Comment by AnrDaemon** [comment]
So, another attempt. http://jsonlint.com/?json=http://pastebin.com/raw/xSP1d7PS
This time, your testing suite doesn't complain about its validity. Neither the mod complains.
Yet, the BlockSkyStone:0 does nothing.
The BlockSkyStone:1, however, generating stuff just fine.

**Comment by AnrDaemon** [comment]
This is Forge/Mojang issue. It just doesn't call populateChunk() in superflat. Pity, really. It's the only configurable generator…
