### ISSUE TITLE
[CoFH CORE 4.5.2.19 - 1.12.2] Enchanting Problem in server.

### ISSUE THREAD

**Issue by Mxater** [CoFH/Feedback#1134]
Some enchanting are buged, I cant made the enchanting books, recipe dont work, and some are changed.
In the picture, I search "poison" and show the enchanting "Holding".
![imagen](https://user-images.githubusercontent.com/4630666/41069626-ca8196bc-69bc-11e8-88a4-3647db97a7ad.png)
And when search "holding", show "Leech".
![imagen](https://user-images.githubusercontent.com/4630666/41069636-d431c088-69bc-11e8-865f-22a93f56f450.png)

But I cant craft the holding and poison enchanting bug.

In singleplayer work fine, but in multiplayer are the problem.

**Comment by KingLemming** [comment]
This is a JEI issue. It's caused by desync with the Enchantment map ID. The correct enchants will go on the correct items, but JEI won't handle the lookup properly.

**Comment by Mxater** [comment]
It not JEI, I remove JEI from mod list, this problem happend when update to last version.
![imagen](https://user-images.githubusercontent.com/4630666/41072948-cfa1a378-69ce-11e8-9985-0627c558d7d5.png)

**Comment by KingLemming** [comment]
I don't add that recipe. You have another mod adding the recipe and not remapping when the server remaps.
