### ISSUE TITLE
[core:worldgen] Integer numClusters is unnecessarily restricting.

### ISSUE THREAD

**Issue by AnrDaemon** [CoFH/Feedback#1135]
This is more of an enhancement request… but I wanted to generate some midair clusters. And I wanted them to be somewhat scarce-y. But the least number of attempts I can enter is "1" per chunk. Which is for my purposes is somewhat "common".
Thus, this feature request.
Please?

**Comment by KingLemming** [comment]
There's already a chunkChance parameter for this. Documentation is at:

http://teamcofh.com/docs/cofh-core/features/custom-world-generation/

**Comment by AnrDaemon** [comment]
Oh, sorry! I shouldn't read documentation past midnight >.<
Probably…
