### ISSUE TITLE
[Thermal Dynamics 2.5.1.14] "Pick Block" doesn't work with item/fluid/energy ducts.

### ISSUE THREAD

**Issue by Sinxar** [CoFH/Feedback#1135]
When using the "Pick Block" (middle click targeting the block you want to select), it will not put the duct from your inventory into your hand.

**Comment by KingLemming** [comment]
Yes. That's because Pick Block takes an exact snapshot of the duct in the world, which can be useful for debugging purposes. It's not the same as ducts that can be normally acquired.

Sorry, this is a working as intended, since it's Creative Mode only.
