### ISSUE TITLE
Some Mystical Agriculture recipes missing in Phytogenic Insolater

### ISSUE THREAD

**Issue by Azami1990** [CoFH/Feedback#1136]
Hey!

i have some recipes missing from Mystical Agriculture in the Phytogenic Insolater.
In my case the Grains of Infiity Seed and End Steel Seed from EnderIO and the Alumite Seed from PlusTiC. Other Crops from Mystical Agriculture from these Mods work perfectly,

Is this a bug or a feature^^?

Thanks

**Comment by KingLemming** [comment]
It's not a bug, it's just that the plugins don't get automatically updated.

**Comment by Azami1990** [comment]
Ah Okay.
So the support for the other EnderIO Mystical Plants is left from the old versions and didnt get updated for the new Materials?

**Comment by KingLemming** [comment]
Right. I've added it in dev now.

**Comment by Azami1990** [comment]
Thank you!
