### ISSUE TITLE
Exception in World Tick

### ISSUE THREAD

**Issue by CashMoneyLife** [CoFH/Feedback#1137]
first hello,

ehmm yeah im new here so i hope i get help here

my problem is i get always a crash when i explore my world:
http://pastebin.com/HDsyimLW

i tried 2 different java version (the runtime of minecraft and java 8 Update 77)
and still no changes

if i change to peacful it works but if i change back to normal it crashes and i dont want to play on peaceful ;(

if someone can help me i would very appreciate that and be very thankful i tried so many things and worked on it in hours...

Minecraft Version: 1.6.4
Forge Version: 9.11.1.1345
im using:
CoFHCore-2.0.0.5 for 1.6.4
ThermalExpansion-3.0.0.7 for 1.6.4

if i remove both mods my game works perfectly so i got something wrong with one of them above
i found the mods on http://teamcofh.com/ and the page redirected me to curseforge for the downloads

i hope i didnt forget something if u need some more information just tell me

im thankful for every kind of help !

**Comment by skyboy** [comment]
No support is offered for 1.6.4.
