### ISSUE TITLE
Proposition against changed my translates.

### ISSUE THREAD

**Issue by karakufire** [CoFH/Feedback#1137]
[English]  

The proposition against these Pull Requests:  
 * [CoFH/CoFHCore #49 at 2018/04/26](https://github.com/CoFH/CoFHCore/pull/49)  
 * [CoFH/ThermalDynamics #15 at 2018/05/24](https://github.com/CoFH/ThermalDynamics/pull/15)

Not only two PRs mentioned above,  @koh-gh contributed to Japanese translation of Minecraft mods developed by Team CoFH. He( or She?) worked fixing many not-translated properties that arised after my works. It's so thankful.  
HOWEVER, sadly, these works also contain OVERWRITTEN ones that I already translated(exclude punctuation marks and spacing fix).

So all of developers and contributors, I propose these OVERWRITTEN translates. I hope your opinions, indications and discussion.
By all means, I hope for fair discussion and judgement.  
Thank you.

----
[Japanese]

以下のpull requestに対する申し立てです。
 * [CoFH/CoFHCore #49 at 2018/04/26](https://github.com/CoFH/CoFHCore/pull/49)  
 * [CoFH/ThermalDynamics #15 at 2018/05/24](https://github.com/CoFH/ThermalDynamics/pull/15)

これらのみならず、CoFHチームの開発したMinecraft Modの日訳に、@koh-gh 氏はありがたいことに、私の最後の仕事から今までに生じてしまった、沢山の未翻訳の項目を翻訳してくださりました。  
しかし、悲しいことに、それらには私がすでに翻訳したのにもかかわらず上書きされたものもいくつか存在します(句読点や空白の補正は除く)。

そこで、私はCoFHチームやそのコントリビュータの皆様に、これらの上書きされた翻訳に対するご意見・ご指摘の募集と議論を望みます。
ぜひ、公正な議論と判断を望みます。
以上、よろしくお願いします。

**Comment by karakufire** [comment]
I think it is bad manners to change enable translates that already exist without explaining the reason.
I hope [koh-gh](https://github.com/koh-gh) to explain why changed it and find a compromise with me.

**Comment by koh-gh** [comment]
First of all, the file has not been updated for a long time. So I thought the former translator is not playing this mod now. Thus I have updated this file. 
And when doing it, I surely have changed some translation. The reason is that I thought some translation was too hard to understand the functions of items for many Japanese people.

**Comment by karakufire** [comment]
> And when doing it, I surely have changed some translation. The reason is that I thought some translation was too hard to understand the functions of items for many Japanese people.

OK, I understand.  
You have a misunderstanding: I'm continuing to use the mods, I just rested maintenance of translation for a while.

Certainly some my translates are hard to see features for Japanese users.
Aqua chow or Phyto-gro for example, I think I over-seasoned them with my humor and it is hard to recognize how to use. (So I recognized them as something like a product name!)  

However most translates are my works as result of my study: what it means and where reference it, and my thinking: how translate keep atmosphere of original words.  
Enchantment names leech and multishot for example:
Leech is an blood-sucking boneless creature like worm lives in wet places and it will give you a creepy impression. My translation of leech is born by my effort to keep its creepy impression as possible.
Multishot, I impressed some precise many shot than random firing. So I translated this it will impressed users it is some precise.
In addition, there are also that dare to transliterate into Katakana for giving unique feelings, Viaduct is.

These is my principle in Japanese translation.

Please tell me what thinking when you work to translate with.

**Comment by Drullkus** [comment]
>Aqua chow or Phyto-gro for example

>(So I recognized them as something like a product name!)

You know, there's a bit of a true story there :>

**Comment by KingLemming** [comment]
Okay so, here's how I'd like this to be handled moving forward, please.

I'm going to try and wait a week before accepting translation PRs. Feel free to comment and discuss any changes / localizations in those PR threads. Then they can be edited/adjusted or whatever you feel like.

I don't speak or read Japanese, so I just have to trust you. :)

And, thank you both for your assistance in localizing. It's very much appreciated.

**Comment by koh-gh** [comment]
Thanks, I will use Japanese later.

私は自分からPRを出すことはしません。
日本人がわざわざ英語で議論するのも無駄だと思うので、あなたがこうあるべきというPRを出してください。必要であればそのPRで話をしましょう。
ただし、私個人としては、継続的な日本語ファイルの更新がされるのであれば、Thermalシリーズについて自分で更新することにはそこまでこだわりはないことは伝えておきます。

**Comment by karakufire** [comment]
> I'm going to try and wait a week before accepting translation PRs. Feel free to comment and discuss any changes / localizations in those PR threads. Then they can be edited/adjusted or whatever you feel like.

OK. I'm preparing my pull request now. I appreciate your consideration.

----
>ただし、私個人としては、継続的な日本語ファイルの更新がされるのであれば、Thermalシリーズについて自分で更新することにはそこまでこだわりはないことは伝えておきます。

了解しました。
では、@KingLemming 氏の意向に沿ってPRを出しますので、そのPRに異論等あればそちらで妥協点を探っていきましょう。
よろしくおねがいします。

**Comment by koh-gh** [comment]
せっかくなので、既に上がっている指摘分について、持論を書いておきます。
あくまで私の意見なので、判断はお任せします。

まず、バニラでも翻訳は直訳ではなく効果に即したものに変更しているものがあることはご理解ください。Smiteがアンデッド特効、Sweeping edgeが範囲ダメージ増加など。

それを踏まえて、Leechは「蛭憑き」だったと思いますが、直訳に近いのはそうだと思いますが、たぶん多くの日本人には分からないです。Multishotは「多重射撃」でしたが、日本のRPGでは弓使いのアビリティとしては「乱れ撃ち」という用語が多用されている印象があります。その他、機械の翻訳なども、直訳ではなく機能を意識した意訳はありだというのが私の考えです。

カタカナ読みそのままは、対応する日本語がない場合は仕方がないと思いますが、上記と同様に機能に着目して意訳するのはありだと思います。

フィトグローやアクアチャウが商品名だというのは、意見として理解したので、お任せします。

**Comment by karakufire** [comment]
Above, I made these pull-requests.
