### ISSUE TITLE
Crash with Crescent Hammer

### ISSUE THREAD

**Issue by bookerthegeek** [CoFH/Feedback#1138]
Right-clicking an Electric Kinetic Generator with a Crescent Hammer crashes the client. Other wrenches have no issue.
Modpack: IE Skyblock.
Server: Kcauldron

http://pastebin.com/v09hwwSB

Cross post from our forums. Sorry for the lack of other information. Posting so you know.

**Comment by Slind14** [comment]
Looks like RedstoneArsenal had this issue too https://github.com/CoFH/RedstoneArsenal/commit/780024410921b57b3dda07541c8f5241518d4490 and @skyboy fixed it.

**Comment by skyboy** [comment]
This is not an issue with the crescent hammer.

**Comment by Slind14** [comment]
Reproduce-able in single player with FTB Infinity Skyblock. If its not the Crescent Hammer, why do all the other wrenches work fine?

**Comment by skyboy** [comment]
They're not using the forge API for rotating blocks. The problem is that IC2's implementation of rotating blocks via forge's API is broken.

**Comment by bookerthegeek** [comment]
Ok, I'll go inform the industrial-craft guys. Thank you for the information.
