### ISSUE TITLE
Crash trying to view recipes in NEI.

### ISSUE THREAD

**Issue by 61352151511** [CoFH/Feedback#114]
I downloaded all the mods from your site, so they should be the correct version, sorry if this has been fixed already. I disabled florbs and the recipes and noticed they were still in NEI, I thought it would just disable the registering altogether, I pressed R over the florb to see the recipe and crashed.

I posted the issue here because it's saying something about thermal expansion. If it's not your mods fault please let me know who to blame

http://pastebin.com/ry3Cfp2h

Edit: It happens with every recipe (Maybe even when I just press R)

**Comment by KingLemming** [comment]
I'd love to know who to blame. The NPE there can't happen unless another mod is screwing with the Smelter.

Are you on a server? Do mods on client and server match? Can you provide a modlist?

**Comment by 61352151511** [comment]
Yes this is on a server. I set the server up myself so I'm sure the mods and configs on the server and client match. Here is a list of mods:

http://pastebin.com/GHNdZZEP

The ones marked with ">>" At the start are ones I've never used before, so they could be the source of the problem but I can't say they are.

**Comment by KingLemming** [comment]
Okay, so I've tried to replicate this and just can't. Are you Minetweaking recipes in/out?

And yes, disabling florbs correctly disables the recipes. There is no way to make them in game but they still remain registered. The error there is really with the comment. Removing them entirely is bad for the stability of the game.

**Comment by 61352151511** [comment]
No MineTweaking is involved with my setup.

I'll start fresh with CodeChickenCore, NEI, Thermal Expansion, Foundation, and CoFHCore. And I'll add the mods one by one and see which one is causing it. I'll comment again when I figure out which it is.

**Comment by 61352151511** [comment]
Oddly enough this seems to be extra utilities doing. With the following mods installed it works fine,
- Code Chicken Core
- CoFH Core
- Iguana Tweaks
- Mantle
- Not Enough ITems
- Thermal Expansion
- Thermal Foundation
- TiC Tooltips
- Tinkers Construct

NEI works fine, however adding Extra Utilities to the mix causes the crash upon trying to look at recipes. This has to do with one of the following config changes I made in the extra utilities config. Using a default config for extra utilities there appears to be no issue, however changing one of the following items (I'm not yet sure which) Causes the crash.

Blocks:
B:Decorative_1Enabled=false
B:Decorative_2Enabled=false
B:GreenScreenEnabled=false
B:PeacefultableEnabled=false
B:PureLoveBlockEnabled=false
B:QEDEnabled=false
Items:
B:CreativeBuildersWandEnabled=false
B:PaintBrushEnabled=false
B:SonarGogglesEnabled=false
B:SoulEnabled=false
Options:
B:soulDrainResetsOnDeath=true
QEDCrafting:
* Emptied list so nothing requires QED *
I:QEDVersion=-1
Recipes:
B:disableColoredBlocksRecipes=true
B:disablePaintbrushRecipe=true
B:disablePeacefulTableRecipe=true
B:disablePeacefulWitherRecipe=true
B:disableQEDIngotSmeltRecipes=true
B:disableSonarGogglesRecipe=true

I'll continue trying to narrow down the cause of the issue (Which config option it is)

CC: @RWTema Maybe you could look into this?

**Comment by KingLemming** [comment]
I've redone a lot of NEI things on our end, and I could never actually make this happen.

Going to close it out since I'd imagine the relevant code paths have already changed anyways.
