### ISSUE TITLE
shift + left click to turn off all inputs on hardened redstone furnace makes block transparent.

### ISSUE THREAD

**Issue by andyglover** [CoFH/Feedback#114]
I shift + left clicked on the center square of the configuration tab on my RS furnace to turn off all the inputs. The block is now transparent. Breaking and replacing block, or reloading world does not fix block's transparency.

https://drive.google.com/file/d/0B7VA8ZJKhIxDY3dkUlp1MWs5R2s/view?usp=sharing

**Comment by KingLemming** [comment]
You have Project Red I'm guessing.

**Comment by andyglover** [comment]
Interesting. Reloading the resource pack crashed my client, but when I relaunched the block was all good again.

**Comment by KingLemming** [comment]
You DO have Project Red though, don't you?

**Comment by andyglover** [comment]
Sorry, yes. Forgot to mention I was using the FTB Beyond pack. :)

**Comment by KingLemming** [comment]
Yeah we're trying to figure out the conflict. Will close then since it's a duplicate. :)
