### ISSUE TITLE
Thermal Expansion: Fluid Transposer stops working

### ISSUE THREAD

**Issue by TheRedMelon** [CoFH/Feedback#1140]
No idea what causes it so can't reproduce, but I think it has something to do with turning the machine on and off with redstone.  The fluid transposer just stops, it has the appropriate items and fluids to continue but doesn't.   There is an item in the middle, 'processing' slot.  Tested with converting phyto-gro to rich phyto-gro, and sulfur to blaze powder.

**Comment by KingLemming** [comment]
Redstone behavior was changed, yes. I'll be changing it back in the next release.

So for now, don't do that.
