### ISSUE TITLE
Cannot open gui of any type of energy cell

### ISSUE THREAD

**Issue by Yzelast** [CoFH/Feedback#1141]
Hi guys,i'm having a problem with the energy cells. The problem is that i can't open the gui to configure the block,neither connect any cable on it.
Them,i removed all the mods(176) i was using alongside thermal expansion,and the problem still remains.

The versions are:

forge 10.13.4.1614

linux deepin x64
openjdk 8 x64 

cofhCore 3.1.2-325
thermalFoundation 1.2.3-112
thermalDynamics 1.1.0-161
thermalExpansion4.1.2-240

**Comment by skyboy** [comment]
It sounds like you've mistaken energy cell frames for energy cells themselves.

**Comment by Yzelast** [comment]
well.. what a shame, i'm sorry for this, next time i will read and search the names twice, or not use other languages than english..

**Comment by skyboy** [comment]
If it's a problem with the translation, it would be appreciated if you help improve it: https://github.com/CoFH/ThermalExpansion-Localization
