### ISSUE TITLE
Thermal Expansion - Client Disconnect when mod not present on server

### ISSUE THREAD

**Issue by kencinder** [CoFH/Feedback#1141]
Forge 1.12.2.-14.23.4.2705
Thermal Expansion 5.5.0.29

We run a network of servers, where Thermal Expansion is not present(or wanted) on every server. Client is being disconnected with the following client-side error on servers where the mod is not in use.

https://gist.github.com/kencinder/7832af127650cde4b1649ef4d2bfb620

Ran a test server with forge-1.12.2-14.23.4.2705 and absolutely no mods to confirm the problem. Tried older versions of TE and corresponding dependencies, with no change.

**Comment by covers1624** [comment]
Seems Enchantment#getEnchantmentByLocation can return null, not sure why in this case, enchantments are handled really weirdly.

**Comment by kencinder** [comment]
I have a feeling it's related to this change - https://github.com/MinecraftForge/MinecraftForge/pull/4880

I'd have to set up a client and test server running Forge 2655 to test it, but I do believe this only became apparent once we moved the client and some servers to Forge 2705, when all were still on Forge 2655 this didn't happen.

**Comment by KingLemming** [comment]
This might be an issue for Forge to handle, then. Sounds like they broke it on their end.

**Comment by kencinder** [comment]
Can confirm after testing with Forge 2655 server, with 0 mods, and client running Forge 2655 with TE + Dependencies, that it doesn't occur.
Tested with 2655 due to it being previous RB in use, and last build we happened to be making use of.

If it's Forge's fault, I'm not sure how to convey that to them. Our pack uses ~50 mods, some of which provide their own enchantments, and the problem is only experienced with TE. Remove TE, no issues.

**Comment by KingLemming** [comment]
Try with Forge 2695 and let us know what happens please. If there's no error, then it's definitely in the commit you're suspecting.

**Comment by kencinder** [comment]
Tested again with Forge 2695 in the same manner, and the error returns. So somewhere between 2655-2695, so it's not that commit...

I can try to further narrow it down if unsure of the culprit build where it first happens.

**Comment by kencinder** [comment]
Ok spent some time narrowing it down between 2656 to 2694, and 2688 is where the error starts.

2686 - OK

2688 - ERROR

**Comment by KingLemming** [comment]
No idea exactly what they've done, but I've added a mitigation in dev for this anyways.

**Comment by kencinder** [comment]
Awesome, thank you
