### ISSUE TITLE
Crashing every time

### ISSUE THREAD

**Issue by tornadodylan** [CoFH/Feedback#1142]
The game crashed whilst initializing game
Error: java.lang.NoSuchMethodError: cofh.api.util.ThermalExpansionHelper.addCompactorStorageRecipe(ILnet/minecraft/item/ItemStack;Lnet/minecraft/item/ItemStack;)V

**Comment by KingLemming** [comment]
Yup. Caused by BaseMetals. Please disable Thermal Expansion compat in its config.

**Comment by tornadodylan** [comment]
(*seven days later*) Uh... I've never had to access the config before, how do I do that?
