### ISSUE TITLE
[Thermal Expansion]Crash when trying to pickup machines

### ISSUE THREAD

**Issue by Yous34** [CoFH/Feedback#1142]
always when i try to pick up any thermal expansion machine it crashes some times with a server side crash report other time with a client side one,
i tryied picking them up with different tools; ender io, buildcraft, thermal expansion wrences, with the draconic staff of power in either wrench function and pickaxe function, and with minecraft pickaxe 

[crash-2016-04-09_14.39.39-server.txt](https://github.com/CoFH/Feedback/files/222789/crash-2016-04-09_14.39.39-server.txt)
[crash-2016-04-08_16.37.12-client.txt](https://github.com/CoFH/Feedback/files/222791/crash-2016-04-08_16.37.12-client.txt)
[crash-2016-04-02_23.35.28-client.txt](https://github.com/CoFH/Feedback/files/222792/crash-2016-04-02_23.35.28-client.txt)
[crash-2016-04-02_23.35.21-server.txt](https://github.com/CoFH/Feedback/files/222793/crash-2016-04-02_23.35.21-server.txt)
[crash-2016-04-02_22.47.02-client.txt](https://github.com/CoFH/Feedback/files/222794/crash-2016-04-02_22.47.02-client.txt)

P.S: this is my computer infos:
Wndows 7 64-bit
ram: 6 gb 
cpu: intel core i5 2430M 2.40 ghz overcloked to 2.9ghz 512kb/3mb cache
gpu: nvidia geforce 410M 1gb vram 

P.P.S: mod list: http://pastebin.com/9sFDU4hL

**Comment by skyboy** [comment]
Does it still crash without magneticcraft?

**Comment by Yous34** [comment]
@skyboy haven't tryied, i'll try it tomorrow

**Comment by Yous34** [comment]
@SKYBOY yes after removing hydraulicraft jar it still crashing 
[crash-2016-04-18_16.15.29-client.txt](https://github.com/CoFH/Feedback/files/224185/crash-2016-04-18_16.15.29-client.txt)

**Comment by Yous34** [comment]
i think the crash has something to do with this: **Unexpected error java.lang.NoSuchMethodError: cofh.api.tileentity.ISecurable.canPlayerAccess(Lnet/minecraft/entity/player/EntityPlayer;)Z** 
because this line appears in all crash reports

**Comment by KingLemming** [comment]
@Yous34 - this is caused by another mod, unquestionably.

Try it with only CoFH mods. Won't happen. You have something else screwing up the API.

**Comment by Yous34** [comment]
@kinglemming yeah you are right but what does this line mean ?
Unexpected error java.lang.NoSuchMethodError:cofh.api.tileentity.ISecurable.canPlayerAccess(Lnet/minecraft/entity/player/EntityPlayer;)Z

**Comment by Yous34** [comment]
@kinglemming yeah you are right but what does this line mean ?
Unexpected error java.lang.NoSuchMethodError:cofh.api.tileentity.ISecurable.canPlayerAccess(Lnet/minecraft/entity/player/EntityPlayer;)Z

**Comment by Yous34** [comment]
@kinglemming yeah you are right but what does this line mean ?
Unexpected error java.lang.NoSuchMethodError:cofh.api.tileentity.ISecurable.canPlayerAccess(Lnet/minecraft/entity/player/EntityPlayer;)Z

**Comment by Yous34** [comment]
@kinglemming yeah you are right but what does this line mean ?
Unexpected error java.lang.NoSuchMethodError:cofh.api.tileentity.ISecurable.canPlayerAccess(Lnet/minecraft/entity/player/EntityPlayer;)Z

**Comment by Yous34** [comment]
@kinglemming yeah you are right but what does this line mean ?
Unexpected error java.lang.NoSuchMethodError:cofh.api.tileentity.ISecurable.canPlayerAccess(Lnet/minecraft/entity/player/EntityPlayer;)Z

**Comment by Yous34** [comment]
@kinglemming yeah you are right but what does this line mean ?
Unexpected error java.lang.NoSuchMethodError:cofh.api.tileentity.ISecurable.canPlayerAccess(Lnet/minecraft/entity/player/EntityPlayer;)Z

**Comment by Yous34** [comment]
@kinglemming yeah you are right but what does this line mean ?
Unexpected error java.lang.NoSuchMethodError:cofh.api.tileentity.ISecurable.canPlayerAccess(Lnet/minecraft/entity/player/EntityPlayer;)Z

**Comment by Yous34** [comment]
@kinglemming yeah you are right but what does this line mean ?
Unexpected error java.lang.NoSuchMethodError:cofh.api.tileentity.ISecurable.canPlayerAccess(Lnet/minecraft/entity/player/EntityPlayer;)Z

**Comment by Yous34** [comment]
@kinglemming yeah you are right but what does this line mean ?
Unexpected error java.lang.NoSuchMethodError:cofh.api.tileentity.ISecurable.canPlayerAccess(Lnet/minecraft/entity/player/EntityPlayer;)Z

**Comment by Yous34** [comment]
@kinglemming yeah you are right but what does this line mean ?
Unexpected error java.lang.NoSuchMethodError:cofh.api.tileentity.ISecurable.canPlayerAccess(Lnet/minecraft/entity/player/EntityPlayer;)Z

**Comment by Yous34** [comment]
@kinglemming yeah you are right but what does this line mean ?
Unexpected error java.lang.NoSuchMethodError:cofh.api.tileentity.ISecurable.canPlayerAccess(Lnet/minecraft/entity/player/EntityPlayer;)Z

**Comment by Yous34** [comment]
@kinglemming yeah you are right but what does this line mean ?
Unexpected error java.lang.NoSuchMethodError:cofh.api.tileentity.ISecurable.canPlayerAccess(Lnet/minecraft/entity/player/EntityPlayer;)Z

**Comment by Yous34** [comment]
@kinglemming yeah you are right but what does this line mean ?
Unexpected error java.lang.NoSuchMethodError:cofh.api.tileentity.ISecurable.canPlayerAccess(Lnet/minecraft/entity/player/EntityPlayer;)Z

**Comment by Yous34** [comment]
@kinglemming yeah you are right but what does this line mean ?
Unexpected error java.lang.NoSuchMethodError:cofh.api.tileentity.ISecurable.canPlayerAccess(Lnet/minecraft/entity/player/EntityPlayer;)Z

**Comment by KingLemming** [comment]
So basically what is probably happening is that you have another mod shipping a partial CoFH API and is doing it wrong. Forge sees the partial API, loads that up, and then when we expect the FULL API to be there, it isn't.

So basically, this is 100% the fault of another mod and you'll have to figure out which one, sorry.

**Comment by Yous34** [comment]
my comment got multiplicated by 10 XD
i wasn't spamming
