### ISSUE TITLE
Small mistake in documentation: tar cannot be produced into creosote oil

### ISSUE THREAD

**Issue by AaronSzaboo** [CoFH/Feedback#1143]
The documentation page for Tar (https://teamcofh.com/docs/thermal-foundation/tar/) says "It can also be processed into creosote oil".

This is false both according to the May 29 updates page (https://teamcofh.com/posts/2018/05/29/may-29-updates/): "Magma crucibles can no longer process tar into creosote oil", and the creosote oil page (https://teamcofh.com/docs/thermal-foundation/creosote-oil/), where there are no mentions of this.

**Comment by KingLemming** [comment]
Yes. Correct. You really could have come by the discord for this.

**Comment by KingLemming** [comment]
No worries! It's just easier for little things like this. :)
