### ISSUE TITLE
New features for Lumium Lamps

### ISSUE THREAD

**Issue by MrStaples** [CoFH/Feedback#1144]
**Mod: Thermal Expansion**
- A way to copy a lumium lamps settings to other ones, it is very annoying having to configure ecvery lamp by itself _(there might already be a way to do this, if so, i'm unaware of it_).

- It would also be fun if you could wire them up in
 some way (maybe with a cable or a wireless option) so that you could change colour on multiple lamps at the same time.

**Thanks for taking your time reading this. :)**

**Comment by KingLemming** [comment]
As to your first point, Redprints already exist.

Changing color based on signal? Not likely something we'll do.
