### ISSUE TITLE
Strange bug with a Fluid Transposer not accepting energy from SolarFluxReborn cables

### ISSUE THREAD

**Issue by Superickypower** [CoFH/Feedback#1145]
ThermalExpansion-1.12.2-5.5.0.29-universal
Mod List: https://pastebin.com/zUUmWdmi

I've used the "Second Cable" from SolarFluxReborn and the fluid transposer seems to accept energy only from the left side. The "First Cable" and the "Second Cable" are able to transfer energy normally.

**Comment by KingLemming** [comment]
That's going to be something on their end.

When it comes to accepting RF, our machines absolutely do not have any side sensitivity whatsoever.
