### ISSUE TITLE
[CoFHCore] Crash at PreInit using only CoFH Core

### ISSUE THREAD

**Issue by Peruibeloko** [CoFH/Feedback#1147]
Forge version is 10.13.4.1558 (1.7.10 recommended)
Using only the automatically downloaded libs from Forge and CoFH Core v.3.1.2-325 (1.7.10 latest)

Game starts but crashes at PreInit of CoFH Core

Game Output log (Java crashed, no crashlog given): http://hastebin.com/raw/unomukofim
FML Log: http://hastebin.com/raw/awehazegaj

Good hunt!

**Comment by KingLemming** [comment]
Yeah, you straight up aren't allocating enough RAM to run modded MC. Also, you're loading up a lot more than CoFHCore there.

**Comment by Peruibeloko** [comment]
Can't be. I was running 38 mods fine in the same MC version with a older version of mods and Core. Tried jumping from 1Gb to 2Gb and 3Gb and I crashed in all of them. Already tried both Recommended and Latest installations of Forge.
