### ISSUE TITLE
[Thermal Expansion] Config RF cell values not holding

### ISSUE THREAD

**Issue by DoragonKeiyou** [CoFH/Feedback#1148]
The Redstone and Resonant energy cells do not carry the configs to ingame.  No matter what I've changed them to in the configs, they remain at 20mil and 80mil respectively.

**Comment by KingLemming** [comment]
What are you trying to change them to? There are limits.

**Comment by DoragonKeiyou** [comment]
Lower them to 800K and 2.5M respectively.

**Comment by KingLemming** [comment]
What are you trying to lower the others to? That matters as well.

**Comment by KingLemming** [comment]
Actually, just tested this. It works, except the minimum possible values are 1/10th of the defaults. So 2 million and 8 million, respectively.

If it's not working for you, then you are attempting to change a client config on a server, or something of that nature.

**Comment by DoragonKeiyou** [comment]
So for reference, 1/10th is the lowest it can be set?  I've got the first two tiers set to 100k and 250k.
