### ISSUE TITLE
Thermal Foundation: Forge Lexicon deleting ingots

### ISSUE THREAD

**Issue by linesey** [CoFH/Feedback#1148]
While playing on a survival single player world i put some ingots in the lexicon and converted them and then accidentally close it before collecting my ingots out of it.

To make sure this was an issue with the lexicon and not me not paying attention i placed another ingot in it and attempted to convert, closing the book with the converted ingot still in the slot.

The world had been opened to LAN before (making it a server) but at the time it was not open and ruining only as a single player world.

Versions in use
Forge: 14.23.42707
Cofh core: 4.5.2.19
Cofh world: 1.2.0.5
Thermal Foundation: 2.5.0.19

please let me know if any other information is needed.

PS: for anyone else having this issue at this time, using /give or entering creative can help recover items if you have /op permissions.

**Comment by KingLemming** [comment]
Fair enough. For now, don't do that.

**Comment by covers1624** [comment]
We keep issues open untill the fix has been pushed.
