### ISSUE TITLE
Arboreal Extractor stops producing Sap/Resin

### ISSUE THREAD

**Issue by KuiKeN127** [CoFH/Feedback#1149]
After installing the mod I start setting up the extractors around Oak trees to gather Sap. The internal buffer will fill up to 8,000 mB quickly. As soon as I start using the Sap/Resin the buffer drops but never fills itself up when I stop using the Sap/Resin in my machines. The extractors face is still animated as if its still working. The extractors will fill up pipes but not the internal buffer. Pliz halp :(

**Comment by KingLemming** [comment]
Can't replicate this in any way and it's almost certainly something you're doing on your end. Drop by the discord if you like, but this is just tech support.
