### ISSUE TITLE
[MineFactory Reloaded] Planter and chunk weardness (Planter block not working)

### ISSUE THREAD

**Issue by Karolis2011** [CoFH/Feedback#1149]
I got a planter, set up like this ![This](http://i.imgur.com/F0Nso6E.png)
When planter gets loaded / unloaded instantly (in this case RF Tools transmitter was used to teleport away) planter block stops. Replacing block seems to fix issue temporally, another chunk loading shock, will cause issue to reappear. 

Important info:
MFR version - 2.8.1-174
Modpack - FTB Infinity Evolved 2.5.0
Minecraft Version - 1.7.10
Chunk loading - FTB utilities chunk claiming? (I am not sure if it actually keeps chunks loaded, but machines seem to run when I am not in area)

**Comment by skyboy** [comment]
I'm going to say this is a problem with FTB utilities. No other method of chunk loading causes something like this to occur.
