### ISSUE TITLE
Compatibility problem 

### ISSUE THREAD

**Issue by HydrogenC** [CoFH/Feedback#1150]
It seems that CoFH World conflicts with some other core mods, such as VMW (https://minecraft.curseforge.com/projects/vics-modern-warfare-mod). When I use the old version of TE that do not requires CoFH World, it worked well. But after I added CoFH World, it started to crash when joining a server.

**Comment by HydrogenC** [comment]
I’ll provide the log later. No crash report because it’s not really a crash, it’s just turning not responding and I have to quit it manually.

**Comment by KingLemming** [comment]
CoFH World is not a core mod and cannot cause this. Please provide a crash log.

**Comment by KingLemming** [comment]
Downloaded and tested. The gun mod certainly has bugs in it, but CoFH World is not incompatible.
