### ISSUE TITLE
Shift-clicking items out of a redstone furnace doesn't give you xp

### ISSUE THREAD

**Issue by blockingHD** [CoFH/Feedback#1150]
Right clicking items out of a redstone furnace doesn't give you xp from what i have tested where as a normal furnace gives you the xp.

**Comment by KingLemming** [comment]
We have an optimized generic shift click behavior compared to vanilla. Won't be special casing the Furnace, sorry.

**Comment by skyboy** [comment]
Sorry, but I'm going to override that call and address it. It is an issue, as the furnace should give XP in all cases, not just slot pickup. It should be easy enough, I wrote the container functions to be easily extendable.
