### ISSUE TITLE
Fluxbore doesn't use charge from Flux Capacitor

### ISSUE THREAD

**Issue by JayaramV-Hexaware** [CoFH/Feedback#1151]
Tested Flux Bores (Hardened to Resonant) against fully charged Flux Capacitor (Hardened).

The flux bore doesn't use the charge from the flux capacitor.  Don't know if the feature is implemented yet or not, and couldn't find an equivalent defect, so raising one here.

Tested the flux capacitor in Charge Armor, Charge Equipment AND Charge Everything modes.  None seem to work.

**Versions:**

CoFHCore-1.12.2-4.5.2.19-universal
CoFHWorld-1.12.2-1.2.0.5-universal
RedstoneFlux-1.12-2.0.2.3-universal
RedstoneArsenal-1.12.2-2.5.1.13-universal
ThermalCultivation-1.12.2-0.3.0.7-universal
ThermalDynamics-1.12.2-2.5.1.14-universal
ThermalExpansion-1.12.2-5.5.0.29-universal
ThermalFoundation-1.12.2-2.5.0.19-universal
ThermalInnovation-1.12.2-0.3.0.7-universal

**Comment by KingLemming** [comment]
Yeah the reason there's no issue reported is that they do in fact receive charge from the capacitor. Just tested with all fresh downloads and it 100% works as expected.

Your issue is almost definitely that you didn't actually turn the capacitor on.

**Comment by JayaramV-Hexaware** [comment]
First off, thank you for the prompt response.  Attaching screenshot to highlight the settings on the flux capacitor and the flux bore.  Please let me know if I'm doing anything wrong here.  You can see that the screenshots are taken around 10 - 20 seconds from each other from the timestamp.  You can also see from the tooltip that the flux capacitor can charge equipment & armor.  You can also see the charge levels on the fluxbore remain unchanged across the time the screenshots were taken.


JV


________________________________

**Comment by KingLemming** [comment]
So...yes. It's exactly as I stated. You didn't turn the capacitor on.

Read the tooltip - use it while sneaking to turn it on.

**Comment by JayaramV-Hexaware** [comment]
😁 I did NOT notice that.  Thanks again.
