### ISSUE TITLE
TE Cache randomly lost items on place

### ISSUE THREAD

**Issue by donbubu** [CoFH/Feedback#1153]
ThermalExpansion-[1.7.10]4.1.2-240
CoFHCore-[1.7.10]3.1.2-325
Hi, i found a bug with caches (any tier). I take a Cache with item in my inventory, the item shown with mouse over but if i place it again, sometimes it lost all items and is empty and unlocked.
Not every time. You can test it, if you get and place a filled cache many times. I found it as i replaced 6 caches to another loaction and some of its are empty then.

**Comment by skyboy** [comment]
We need a mod list.

**Comment by donbubu** [comment]
The blocks i lost was sand, gravel and cobble (vanilla-blocks).
Here are all mods, updated to last version:
CodeChickenCore
NotEnoughItems
OpenModsCore
ArmorStatusHUD
Treecapitator
appliedenergistics2
Backpack
BiblioCraft
BigReactors
BuildCraft
BuildCraft Compat
CarpentersBlocks
CoFHCore
ComputerCraft
DimensionalAnchors
endercore
EnderIO
EnderStorage
enhancedportals
ExtraUtilities
FlatBedrock
GraveStone
IGWMod
ImmibisCore
IronChest
Mantle
MineFactoryReloaded
powersuits
NEIAddons
neiintegration
numina
OpenBlocks
OpenMods
openmodularturrets
ProjectE
RedLogic
RedstoneArsenal
simplyjetpacks
TConstruct
ThermalDynamics
ThermalExpansion
ThermalFoundation
TMechworks
Tubestuff
voxelmap
Waila
weather2
WR-CBE
bspkrsCore

**Comment by pchard** [comment]
I can confirm!

**Comment by skyboy** [comment]
We need a log for when this issue occurs.

**Comment by donbubu** [comment]
No error in log-file, all clear.
I test it again with this mods only:

- CoFHCore-[1.7.10]3.1.2-325
- ThermalFoundation-[1.7.10]1.2.3-112
- ThermalExpansion-[1.7.10]4.1.2-240

and server was
- KCauldron-1.7.10-1614.201

**Comment by XFactHD** [comment]
Can you reproduce this on a normal forge server?

**Comment by donbubu** [comment]
Thats not funny and i'm sorry for waste your time :(
I test it 20 minutes on normal forge server and no issues with cache. Must be a bug in kcauldron but there is no way to post the bug there, issues-link is down. Why i think it was a TE bug, the deep storage work perfectly. Now i must look where i can get some plugins as forge mods. for essentials i found essentials-forge. thats really bad, no forge+bukkit server out there for 1.7.10.
