### ISSUE TITLE
Fluxbore support to break beehives and the like

### ISSUE THREAD

**Issue by JayaramV-Hexaware** [CoFH/Feedback#1153]
This is a feature request and intends to make the fluxbore the only tool of choice.

Right now, Actually Additions drill and Mekanism atomic disassembler are incredible universal tools since they break all blocks (including beehives).  The fluxbore doesn't break beehives.  Could we please add this functionality to make the fluxbore, the tool of choice?

**Comment by KingLemming** [comment]
I have no desire to ever "compete" with Mekanism's overpowered nonsense. I took a look at the AA code though and I don't actually see anywhere that it has scoop functionality.

So I'll think about it, but it depends on how the beehives are implemented.

**Comment by KingLemming** [comment]
Can you confirm that the AA drill actually breaks all blocks? The code suggests that if it does, that is a bug.

**Comment by KingLemming** [comment]
The AA code doesn't seem to agree with point 1. Are you sure that you or your pack hasn't explicitly whitelisted beehives?

**Comment by JayaramV-Hexaware** [comment]
I use direwolf20 version 1.11 for Minecraft 1.12.2.  I'll check the config and get back in a bit on whether it's explicitly whitelisted or not.
________________________________

**Comment by JayaramV-Hexaware** [comment]
The drill works with beehives by default.  I checked the config in the pack.  The only whitelisted item is Tinker's GravelOre.


# By default, the Drill can mine certain blocks. If there is one that it can't mine, but should be able to, put its REGISTRY NAME here. These are the actual registered Item Names, the ones you use, for example, when using the /give Command.
    S:"Drill Extra Whitelist" <
        TConstruct:GravelOre
     >


JV

________________________________

**Comment by KingLemming** [comment]
I'm inclined to believe this may be unintentional on the part of Actually Additions and they actually should not be breaking the block. Trying to go over their code and see what's going wrong here.

Their drill is explicitly not a scoop.

Mekanism's thing instead looks specifically for bedrock which is a lazy, terrible hack.

**Comment by KingLemming** [comment]
Just discussed this with Ellpeck. The interaction is unintentional and he feels a scoop should be required. Will let Forestry know what needs to be done to fix on their end.

**Comment by JayaramV-Hexaware** [comment]
WHAT DID I DO????????? ;)
