### ISSUE TITLE
Input text not visible in Tesseracts

### ISSUE THREAD

**Issue by Anno861** [CoFH/Feedback#1154]
Couldn't find this anywhere in Issues, so I assume this is either unknown or just me.

Tessaracts (or any other device with a similar GUI, such as the Teleport Plates) do not seem to display any frequencies, names or saved entries, although I can still enter such things and use the Tesseract without any other problems.

![2016-05-14_13 44 27](https://cloud.githubusercontent.com/assets/7048999/15268536/bf5e48d6-19da-11e6-8640-cbab7c546608.png)

I am using:

• Minecraft 1.7.10
• Forge 10.13.4.1558
• CoFH Core 3.1.2-325
• Thermal Expansion 4.1.2-240

I have also tried updating Java (JRE and the JDK).

**Comment by XFactHD** [comment]
Are you using Optifine or Fastcraft?

**Comment by Anno861** [comment]
Ah yes, just before I returned to this issue I found the 'Fast Render' option (Optifine?) within my settings. I turned it off and loe and behold, suddenly I can see the text.

I suppose it probably would have been good to try TE on its own before submitting this, but oh well.

Thanks anyway.

**Comment by skyboy** [comment]
CoFHTweaks should give you the same performance benefit optifine does and more, and it won't break things like this.
