### ISSUE TITLE
Vacuum Itemducts don't seem to increase priority

### ISSUE THREAD

**Issue by Kzorith** [CoFH/Feedback#1155]
I have set up a set of itemducts, pulling out of an Actually Additions Ranged Collector using a reinforced servo.  It travels a short distance before the line splits and can go into an Actually Additions Small Crate or the Drawer Controller from Storage Drawers.  To prioritize the drawers first, I placed three vacuum itemducts in line but the majority of the items still go into the crate.  There is sufficient space in the drawers for the items that are being deposited so I'm at a loss as to why the vacuum itemducts aren't being respected.

Modpack: Enigmatica 2, version 1.38

CoFH mods:
CoFH Core 4.5.2.19
CoFH World 1.2.0.5
Thermal Foundation 2.5.0.19
Thermal Expansion 5.5.0.29
Thermal Cultivation 0.3.0.7
Thermal Dynamics 2.5.1.14
Thermal Innovation 0.3.0.7

Interfaced mods:
Actually Additions 1.12.2-r135
Storage Drawers 1.12.2-5.3.6

Image of the junction and items in motion.
![2018-06-15_20 37 51](https://user-images.githubusercontent.com/13224348/41495156-01ea5666-70de-11e8-8e18-a34f61ec4920.png)

**Comment by KingLemming** [comment]
Yes - this is the nature of storage drawers and how they expose slots.
