### ISSUE TITLE
Energetic Infuser + Parabolic Flux Coupling - Not charging some items

### ISSUE THREAD

**Issue by JayaramV-Hexaware** [CoFH/Feedback#1156]
Energetic Infuser + Parabolic Flux Coupling don't charge enderio items or mekanism machines except a few odd ones (pressurized reaction chamber & crusher got their energy buffers filled up, while configurator, eletrolytic separator, etc. don't).

I understand if it's the other mods that need to handle wireless charging appropriately, but since I wasn't sure whose side the responsibility lay, I'm raising this defect (?).

**Comment by KingLemming** [comment]
Read the augment. It only works with Flux Capacitors. This is 100% intended.
