### ISSUE TITLE
Thermal Foundation 5.3.6.20 for 1.12 Crashes servers

### ISSUE THREAD

**Issue by edbefee3-3888-462a-9411-741b7e9eb54e** [CoFH/Feedback#1158]
I want to play an 1.12 modded survival with friends, but As I See From The Log And The Crash Report That The Latest Version Making Servers Crash.

**Comment by edbefee3-3888-462a-9411-741b7e9eb54e** [comment]
[crash-2018-06-17_18.07.18-server.txt](https://github.com/CoFH/Feedback/files/2109116/crash-2018-06-17_18.07.18-server.txt)
[fml-junk-earlystartup.log](https://github.com/CoFH/Feedback/files/2109117/fml-junk-earlystartup.log)
[fml-server-latest.log](https://github.com/CoFH/Feedback/files/2109118/fml-server-latest.log)

**Comment by PanSzelescik** [comment]
Why 1.12? You have 1.12.2 which is very good

**Comment by KingLemming** [comment]
Yup. That sure says TCon and not us.
