### ISSUE TITLE
Fluid Transposer not accepting logs

### ISSUE THREAD

**Issue by linesey** [CoFH/Feedback#1159]
Hello.
I recently installed immersive engineering into my game and got a coke oven set up and running.
using the IE pump i am able to get creosote oil from the oven into the TE fluid transposer, however i can't get the transposer to take logs into it's fill slot to make the treated planks (JEI says this should work)

since JEI can see the recipe i think it's a problem with the transposer and not with how IE is adding the recipe, though if it is i will submit my issue over there instead, since it's an inter mod issue i'm not entirely sure how to report the issue.

Version info.
Forge: 14.23.42707
Cofh core: 4.5.2.19
Cofh world: 1.2.0.5
Thermal Foundation: 2.5.0.19
Immersive engineering: 0.12-82

if you need any more info from me please just let me know, and sorry if this is irrelevant and a waste of your time.

**Comment by KingLemming** [comment]
Yeah, that recipe was intended to be removed and apparently wasn't, sorry.

**Comment by medic68** [comment]
So then... how do you make Treated Wood whatevers and/or those items that depend on them?!
