### ISSUE TITLE
Server crash when loading. Laset Versions mods

### ISSUE THREAD

**Issue by Tsyklop** [CoFH/Feedback#116]
I have a problem . Updated on the latest versions mods of the CF and is now immediately when the server starts it falls with this error:
http://pastebin.com/VeRkKUsu

Remove it , I can not because the server falls instantly.

Region-Fixer not help me.

**Comment by 61352151511** [comment]
Do not download alphas then.

"If your game is crashing on startup:
Update your mods! Use mods ONLY from http://teamcofh.com/downloads."

Downloading them from curseforge is getting yourself into a lot of trouble and it is not their problem if you don't understand the "Alpha" tag on the mods.

**Comment by skyboy** [comment]
Your world is corrupted and needs deleted. See #110
