### ISSUE TITLE
Can't use Minefactory Reloaded without Thermal Expansion

### ISSUE THREAD

**Issue by skippyroo86** [CoFH/Feedback#1160]
"http://teamcofh.com/downloads" lists MineFactory Reloaded as requiring Minecraft Forge and CoFH Core but loading a server with only these two mods in the mods folder and I get:

[15:24:55] [Server thread/ERROR]: Encountered an unexpected exception
cpw.mods.fml.common.MissingModsException:
Missing Mods:
        null : ThermalExpansion

Full patebin here: http://pastebin.com/gYzhxYi5

**Comment by skyboy** [comment]
You have enabled ThermalExpansion recipes. They require ThermalExpansion for obvious reasons, disable them if you don't want to play with ThermalExpansion.

**Comment by skippyroo86** [comment]
My apologies. I had old config files left behind from a previous install of MFR.
