### ISSUE TITLE
[ThermalExpansion] Cache dupe-bug.

### ISSUE THREAD

**Issue by yaroslav4167** [CoFH/Feedback#1161]
If inventory is full, and there are , for example, 1 unit Redstone ( Cache 64 units), it will not be reduced by removing the cache in Redstone. But the player will receive 64 units.

**Comment by Ghostlyr** [comment]
@skyboy, when it will be released?

**Comment by skyboy** [comment]
In longer than the 3 days it took you to ask.

**Comment by Magicfar4** [comment]
So, is when will fix this bug?

**Comment by KingLemming** [comment]
Probably next year if people keep asking.

**Comment by bookerthegeek** [comment]
Yes! No new features for a year!.....

@Magicfar4 stfu.
