### ISSUE TITLE
Watering Can Thermal Cultivation Dupe

### ISSUE THREAD

**Issue by Goofyschooler** [CoFH/Feedback#1161]
Literatly dupes the item.
Version #:
Thermal Cultivation: 1.12.2-0.2.0.6-universal
ThermalDynamics: 1.12.2-2.4.1.10-universal
ThermalExpansion: 1.12.2-5.4.2.27-universal
ThermalFoundation: 1.12.2-2.4.1.15-universal
ThermalInnovation: 1.12.2-0.2.1.6-universal

## Expected Behavior
Should fill the can with water

## Current Behavior
Dupes the item

## Steps to Reproduce
https://youtu.be/uaQBgLSJFLA

Apologize if this is duplicate or has been fixed

**Comment by KingLemming** [comment]
This has indeed been fixed. Please update mods before submitting bug reports.
