### ISSUE TITLE
[1.12.2] Cache compatibility (or display) issue with Refined Storage (External Storage Adapter)

### ISSUE THREAD

**Issue by PearlCanopus** [CoFH/Feedback#1162]
Right yesterday I played with the latest release versions of Thermal Expansion and Refines Storage.
When I peered the filled Basic Cashes with an RS External Storage Adapter, the adapter showed 1.163/64 and full. So I removed the adapters again and didn't check whether caches work as external storage finally.

But it's a strange behaviour. I (of course) not know which mod is the reason of this behaviour.
It's not hot topic, but only a thing I'm aware of.

I will try that with a "Storage Drawers" drawer again tonight.

**Comment by KingLemming** [comment]
This is going to be something on RS's end. The Cache is just an inventory. If special handling is required, I'd say that it is a questionable design.

I'll leave this up for now, but it's definitely not a bug on our end.

**Comment by PearlCanopus** [comment]
It's no further issue for me since I use Storage Drawers instead. That's an acceptable workaround. :)
Thx for checking that out.
