### ISSUE TITLE
[1.12.2] Game crash on startup

### ISSUE THREAD

**Issue by Automatizer** [CoFH/Feedback#1163]
Ok so, I get a NoSuchMethodError when I have thermal expansion installed, otherwise the game launches normally with no errors.

` ---- Minecraft Crash Report ----

WARNING: coremods are present:
  MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  CTMCorePlugin (CTM-MC1.12-0.3.0.15.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-82.jar)
  OpenModsCorePlugin (OpenModsLib-1.12.2-0.11.5.jar)
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.9.9.1-1.12.2-anarchy.jar)
  AstralCore (astralsorcery-1.12.2-1.9.1.jar)
Contact their authors BEFORE contacting forge

// Don't do that.

Time: 6/19/18 9:54 AM
Description: Initializing game

java.lang.NoSuchMethodError: cofh.api.util.ThermalExpansionHelper.addCompactorStorageRecipe(ILnet/minecraft/item/ItemStack;Lnet/minecraft/item/ItemStack;)V
	at com.mcmoddev.lib.integration.plugins.ThermalExpansionBase.addCompactorStorageRecipe(ThermalExpansionBase.java:54)
	at com.mcmoddev.lib.integration.plugins.ThermalExpansionBase.addPressStorage(ThermalExpansionBase.java:209)
	at com.mcmoddev.lib.integration.plugins.ThermalExpansionBase.addPressStorage(ThermalExpansionBase.java:193)
	at com.mcmoddev.basemetals.integration.plugins.ThermalExpansion.lambda$regShit$1(ThermalExpansion.java:51)
	at com.mcmoddev.basemetals.integration.plugins.ThermalExpansion$$Lambda$1581/476238338.accept(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at com.mcmoddev.basemetals.integration.plugins.ThermalExpansion.regShit(ThermalExpansion.java:47)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_388_ThermalExpansion_regShit_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:750)
	at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:622)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:742)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:329)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.mcmoddev.lib.integration.plugins.ThermalExpansionBase.addCompactorStorageRecipe(ThermalExpansionBase.java:54)
	at com.mcmoddev.lib.integration.plugins.ThermalExpansionBase.addPressStorage(ThermalExpansionBase.java:209)
	at com.mcmoddev.lib.integration.plugins.ThermalExpansionBase.addPressStorage(ThermalExpansionBase.java:193)
	at com.mcmoddev.basemetals.integration.plugins.ThermalExpansion.lambda$regShit$1(ThermalExpansion.java:51)
	at com.mcmoddev.basemetals.integration.plugins.ThermalExpansion$$Lambda$1581/476238338.accept(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at com.mcmoddev.basemetals.integration.plugins.ThermalExpansion.regShit(ThermalExpansion.java:47)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_388_ThermalExpansion_regShit_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:750)
	at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:622)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:742)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:329)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1054722864 bytes (1005 MB) / 3287810048 bytes (3135 MB) up to 5726797824 bytes (5461 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6144m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.4.2708 104 mods loaded, 104 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                   | Version                  | Source                                           | Signature                                |
	|:----- |:-------------------- |:------------------------ |:------------------------------------------------ |:---------------------------------------- |
	| UCH   | minecraft            | 1.12.2                   | minecraft.jar                                    | None                                     |
	| UCH   | mcp                  | 9.42                     | minecraft.jar                                    | None                                     |
	| UCH   | FML                  | 8.0.99.99                | forge-1.12.2-14.23.4.2708.jar                    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge                | 14.23.4.2708             | forge-1.12.2-14.23.4.2708.jar                    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | openmodscore         | 0.11.5                   | minecraft.jar                                    | None                                     |
	| UCH   | foamfixcore          | 7.7.4                    | minecraft.jar                                    | None                                     |
	| UCH   | appliedenergistics2  | rv5-stable-11            | appliedenergistics2-rv5-stable-11.jar            | None                                     |
	| UCH   | bdlib                | 1.14.3.12                | bdlib-1.14.3.12-mc1.12.2.jar                     | None                                     |
	| UCH   | ae2stuff             | 0.7.0.4                  | ae2stuff-0.7.0.4-mc1.12.2.jar                    | None                                     |
	| UCH   | baubles              | 1.5.2                    | Baubles-1.12-1.5.2.jar                           | None                                     |
	| UCH   | astralsorcery        | 1.9.1                    | astralsorcery-1.12.2-1.9.1.jar                   | a0f0b759d895c15ceb3e3bcb5f3c2db7c582edf0 |
	| UCH   | autoreglib           | 1.3-18                   | AutoRegLib-1.3-18.jar                            | None                                     |
	| UCH   | ctm                  | MC1.12-0.3.0.15          | CTM-MC1.12-0.3.0.15.jar                          | None                                     |
	| UCH   | chisel               | MC1.12.2-0.2.0.31        | Chisel-MC1.12.2-0.2.0.31.jar                     | None                                     |
	| UCH   | jei                  | 4.10.0.198               | jei_1.12.2-4.10.0.198.jar                        | None                                     |
	| UCH   | mantle               | 1.12-1.3.2.24            | Mantle-1.12-1.3.2.24.jar                         | None                                     |
	| UCH   | tconstruct           | 1.12.2-2.10.1.87         | TConstruct-1.12.2-2.10.1.87.jar                  | None                                     |
	| UCH   | basemetals           | 2.5.0-beta5              | BaseMetals-1.12-2.5.0-beta5.214.jar              | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCH   | betteradvancements   | 0.0.5.17                 | BetterAdvancements-1.12.2-0.0.5.17.jar           | None                                     |
	| UCH   | betterbuilderswands  | 0.11.1                   | BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar  | None                                     |
	| UCH   | bibliocraft          | 2.4.4                    | BiblioCraft[v2.4.4][MC1.12.2].jar                | None                                     |
	| UCH   | natura               | 1.12.2-4.3.2.49          | natura-1.12.2-4.3.2.49.jar                       | None                                     |
	| UCH   | forestry             | 5.8.0.303                | forestry_1.12.2-5.8.0.303.jar                    | None                                     |
	| UCH   | binniecore           | 2.5.0.165                | binnie-mods-1.12.2-2.5.0.165.jar                 | None                                     |
	| UCH   | binniedesign         | 2.5.0.165                | binnie-mods-1.12.2-2.5.0.165.jar                 | None                                     |
	| UCH   | genetics             | 2.5.0.165                | binnie-mods-1.12.2-2.5.0.165.jar                 | None                                     |
	| UCH   | botany               | 2.5.0.165                | binnie-mods-1.12.2-2.5.0.165.jar                 | None                                     |
	| UCH   | extrabees            | 2.5.0.165                | binnie-mods-1.12.2-2.5.0.165.jar                 | None                                     |
	| UCH   | extratrees           | 2.5.0.165                | binnie-mods-1.12.2-2.5.0.165.jar                 | None                                     |
	| UCH   | biomesoplenty        | 7.0.1.2384               | BiomesOPlenty-1.12.2-7.0.1.2384-universal.jar    | None                                     |
	| UCH   | codechickenlib       | 3.1.9.344                | CodeChickenLib-1.12.2-3.1.9.344-universal.jar    | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCH   | redstoneflux         | 2.0.2                    | RedstoneFlux-1.12-2.0.2.3-universal.jar          | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCH   | brandonscore         | 2.4.2                    | BrandonsCore-1.12-2.4.2.157-universal.jar        | None                                     |
	| UCH   | chesttransporter     | 2.8.8                    | ChestTransporter-1.12.2-2.8.8.jar                | None                                     |
	| UCH   | chiselsandbits       | 14.17                    | chiselsandbits-14.17.jar                         | None                                     |
	| UCH   | clienttweaks         | 3.1.8                    | ClientTweaks_1.12.2-3.1.8.jar                    | None                                     |
	| UCH   | cofhcore             | 4.5.2                    | CoFHCore-1.12.2-4.5.2.19-universal.jar           | None                                     |
	| UCH   | cofhworld            | 1.2.0                    | CoFHWorld-1.12.2-1.2.0.5-universal.jar           | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCH   | conarm               | 1.0.0                    | conarm-1.12.2-1.0.0.jar                          | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| UCH   | controlling          | 3.0.6                    | Controlling-3.0.6.jar                            | None                                     |
	| UCH   | thermalfoundation    | 2.5.0                    | ThermalFoundation-1.12.2-2.5.0.19-universal.jar  | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCH   | draconicevolution    | 2.3.11                   | Draconic-Evolution-1.12-2.3.11.290-universal.jar | None                                     |
	| UCH   | elevatorid           | 1.3.6                    | ElevatorMod-1.12.2-1.3.6.jar                     | None                                     |
	| UCH   | enderstorage         | 2.4.3.131                | EnderStorage-1.12.2-2.4.3.131-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCH   | waila                | 1.8.26                   | Hwyla-1.8.26-B41_1.12.2.jar                      | None                                     |
	| UCH   | extracells           | 2.5.13                   | ExtraCells-1.12.2-2.5.13a58.jar                  | None                                     |
	| UCH   | extrautils2          | 1.0                      | extrautils2-1.12-1.7.6.jar                       | None                                     |
	| UCH   | foamfix              | 0.9.9.1-1.12.2           | foamfix-0.9.9.1-1.12.2-anarchy.jar               | None                                     |
	| UCH   | ichunutil            | 7.1.4                    | iChunUtil-1.12.2-7.1.4.jar                       | None                                     |
	| UCH   | ftblib               | 5.1.0.22                 | FTBLib-5.1.0.22.jar                              | None                                     |
	| UCH   | ftbutilities         | 5.1.0.27                 | FTBUtilities-5.1.0.27.jar                        | None                                     |
	| UCH   | immersiveengineering | 0.12-82                  | ImmersiveEngineering-0.12-82.jar                 | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| UCH   | immersivetech        | 1.3.10                   | immersivetech-1.12-1.3.10.jar                    | None                                     |
	| UCH   | lunatriuscore        | 1.2.0.42                 | LunatriusCore-1.12.2-1.2.0.42-universal.jar      | None                                     |
	| UCH   | ingameinfoxml        | 2.8.2.94                 | InGameInfoXML-1.12.2-2.8.2.94-universal.jar      | None                                     |
	| UCH   | inventorytweaks      | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                         | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCH   | ironchest            | 1.12.2-7.0.40.824        | ironchest-1.12.2-7.0.40.824.jar                  | None                                     |
	| UCH   | journeymap           | 1.12.2-5.5.2             | journeymap-1.12.2-5.5.2.jar                      | None                                     |
	| UCH   | jeresources          | 0.8.5.27                 | JustEnoughResources-1.12.2-0.8.5.27.jar          | None                                     |
	| UCH   | kleeslabs            | 5.4.10                   | KleeSlabs_1.12.2-5.4.10.jar                      | None                                     |
	| UCH   | malisiscore          | 1.12.2-6.4.0             | malisiscore-1.12.2-6.4.0.jar                     | None                                     |
	| UCH   | malisisdoors         | 1.12.2-7.3.0             | malisisdoors-1.12.2-7.3.0.jar                    | None                                     |
	| UCH   | mcjtylib_ng          | 3.0.1                    | mcjtylib-1.12-3.0.1.jar                          | None                                     |
	| UCH   | mekanism             | 1.12.2-9.4.13.349        | Mekanism-1.12.2-9.4.13.349.jar                   | None                                     |
	| UCH   | mekanismgenerators   | 9.4.11                   | MekanismGenerators-1.12.2-9.4.13.349.jar         | None                                     |
	| UCH   | minicoal             | 1.0                      | minicoal-1.12.2-1.0.jar                          | None                                     |
	| UCH   | moreoverlays         | 1.13                     | moreoverlays-1.13-mc1.12.1.jar                   | None                                     |
	| UCH   | mousetweaks          | 2.8                      | MouseTweaks-2.8-mc1.12.1.jar                     | None                                     |
	| UCH   | neat                 | 1.4-16                   | Neat 1.4-16.jar                                  | None                                     |
	| UCH   | thermalexpansion     | 5.5.0                    | ThermalExpansion-1.12.2-5.5.0.29-universal.jar   | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCH   | netherfoundation     | 1.2.0                    | NetherFoundation-1.12.2-1.2.0-universal.jar      | None                                     |
	| UCH   | notenoughwands       | 1.7.0                    | notenoughwands-1.12-1.7.0.jar                    | None                                     |
	| UCH   | oreexcavation        | 1.4.119                  | OreExcavation-1.4.119.jar                        | None                                     |
	| UCH   | oeintegration        | 2.3.3                    | oeintegration-2.3.3.jar                          | None                                     |
	| UCH   | openmods             | 0.11.5                   | OpenModsLib-1.12.2-0.11.5.jar                    | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| UCH   | openblocks           | 1.7.6                    | OpenBlocks-1.12.2-1.7.6.jar                      | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| UCH   | orespawn             | 3.3.0                    | OreSpawn-1.12-3.3.0.136.jar                      | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCH   | placebo              | 1.3.4                    | Placebo-1.12.2-1.3.4.jar                         | None                                     |
	| UCH   | portalgun            | 7.0.2                    | PortalGun-1.12.2-7.0.2.jar                       | None                                     |
	| UCH   | projecte             | 1.12-PE1.3.0             | ProjectE-1.12-PE1.3.0.jar                        | None                                     |
	| UCH   | reborncore           | 3.8.9.300                | RebornCore-1.12.2-3.8.9.300-universal.jar        | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
	| UCH   | quantumstorage       | 4.5.0                    | QuantumStorage-1.12-4.5.0.jar                    | None                                     |
	| UCH   | quickleafdecay       | 1.2.4                    | QuickLeafDecay-MC1.12.1-1.2.4.jar                | None                                     |
	| UCH   | refinedstorage       | 1.5.34                   | refinedstorage-1.5.34.jar                        | 57893d5b90a7336e8c63fe1c1e1ce472c3d59578 |
	| UCH   | rebornstorage        | 1.0.0                    | RebornStorage-1.12.2-3.1.0.50.jar                | None                                     |
	| UCH   | redstonearsenal      | 2.5.1                    | RedstoneArsenal-1.12.2-2.5.1.13-universal.jar    | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCH   | refinedstorageaddons | 0.3                      | refinedstorageaddons-0.3.jar                     | None                                     |
	| UCH   | xreliquary           | 1.12.2-1.3.4.767         | Reliquary-1.12.2-1.3.4.767.jar                   | None                                     |
	| UCH   | valkyrielib          | 1.12.2-2.0.11a           | valkyrielib-1.12.2-2.0.11a.jar                   | None                                     |
	| UCH   | simplegenerators     | 1.12.2-2.0.11a           | simplegenerators-1.12.2-2.0.11a.jar              | None                                     |
	| UCH   | soulshardstow        | 1.12-2.7.6-56            | SoulShards-TOW-1.12-2.7.6-56.jar                 | None                                     |
	| UCH   | thermaldynamics      | 2.5.1                    | ThermalDynamics-1.12.2-2.5.1.14-universal.jar    | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCH   | tinkersaddons        | 1.0.7                    | Tinkers' Addons-1.12.1-1.0.7.jar                 | None                                     |
	| UCH   | tcomplement          | ${version}               | TinkersComplement-1.12.2-0.2.3b.jar              | None                                     |
	| UCH   | tinkersjei           | 1.0                      | tinkersjei-1.0.jar                               | None                                     |
	| UCH   | tinkertoolleveling   | 1.12.2-1.0.5.DEV.30c7957 | TinkerToolLeveling-1.12.2-1.0.5.jar              | None                                     |
	| UCH   | toastcontrol         | 1.6.0                    | Toast Control-1.12.2-1.6.0.jar                   | None                                     |
	| UCH   | twilightforest       | 3.7.424                  | twilightforest-1.12.2-3.7.424-universal.jar      | None                                     |
	| UCH   | universalmodifiers   | 1.12.2-1.0.9a            | valkyrielib-1.12.2-2.0.11a.jar                   | None                                     |
	| UCH   | wailaharvestability  | 1.1.12                   | WailaHarvestability-mc1.12-1.1.12.jar            | None                                     |
	| UCH   | wanionlib            | 1.12.2-1.5               | WanionLib-1.12.2-1.5.jar                         | None                                     |
	| UCH   | wawla                | 2.5.257                  | Wawla-1.12.2-2.5.257.jar                         | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCH   | yoyos                | 1.12.2-1.2.2.20          | yoyos_1.12.2-1.2.2.20.jar                        | None                                     |
	| UCH   | reauth               | 3.6.0                    | reauth-3.6.0.jar                                 | daba0ec4df71b6da841768c49fb873def208a1e3 |

	Loaded coremods (and transformers): 
MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
CTMCorePlugin (CTM-MC1.12-0.3.0.15.jar)
  team.chisel.ctm.client.asm.CTMTransformer
IELoadingPlugin (ImmersiveEngineering-core-0.12-82.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
OpenModsCorePlugin (OpenModsLib-1.12.2-0.11.5.jar)
  openmods.core.OpenModsClassTransformer
Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.9.9.1-1.12.2-anarchy.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
AstralCore (astralsorcery-1.12.2-1.9.1.jar)
  
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 397.64' Renderer: 'GeForce GT 730/PCIe/SSE2'
	OpenModsLib class transformers: [llama_null_fix:FINISHED],[horse_base_null_fix:FINISHED],[pre_world_render_hook:FINISHED],[player_render_hook:FINISHED],[horse_null_fix:FINISHED]
	AE2 Version: stable rv5-stable-11 for Forge 14.23.1.2554
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- wailaIntegration (Enabled/Not Forced)

	Pulsar/natura loaded Pulses: 
		- NaturaCommons (Enabled/Forced)
		- NaturaOverworld (Enabled/Not Forced)
		- NaturaNether (Enabled/Not Forced)
		- NaturaDecorative (Enabled/Not Forced)
		- NaturaTools (Enabled/Not Forced)
		- NaturaEntities (Enabled/Not Forced)
		- NaturaOredict (Enabled/Forced)
		- NaturaWorld (Enabled/Not Forced)

	Pulsar/tcomplement loaded Pulses: 
		- ModuleCommons (Enabled/Forced)
		- ModuleFeature (Enabled/Not Forced)
		- ChiselPlugin (Enabled/Not Forced)

	List of loaded APIs: 
		* appliedenergistics2|API (rv5) from appliedenergistics2-rv5-stable-11.jar
		* Baubles|API (1.4.0.2) from Baubles-1.12-1.5.2.jar
		* betteradvancements|API (0.0.5.17) from BetterAdvancements-1.12.2-0.0.5.17.jar
		* chesttransporter|api (2) from ChestTransporter-1.12.2-2.8.8.jar
		* Chisel-API (0.0.1) from Chisel-MC1.12.2-0.2.0.31.jar
		* ChiselAPI|Carving (0.0.1) from Chisel-MC1.12.2-0.2.0.31.jar
		* ChiselsAndBitsAPI (13.8.0) from chiselsandbits-14.17.jar
		* cofhapi (2.5.0) from CoFHCore-1.12.2-4.5.2.19-universal.jar
		* ctm-api (0.1.0) from CTM-MC1.12-0.3.0.15.jar
		* ctm-api-events (0.1.0) from CTM-MC1.12-0.3.0.15.jar
		* ctm-api-models (0.1.0) from CTM-MC1.12-0.3.0.15.jar
		* ctm-api-textures (0.1.0) from CTM-MC1.12-0.3.0.15.jar
		* ctm-api-utils (0.1.0) from CTM-MC1.12-0.3.0.15.jar
		* DraconicEvolution|API (1.3) from Draconic-Evolution-1.12-2.3.11.290-universal.jar
		* ForestryAPI|apiculture (5.0.0) from forestry_1.12.2-5.8.0.303.jar
		* ForestryAPI|arboriculture (4.3.0) from forestry_1.12.2-5.8.0.303.jar
		* ForestryAPI|book (5.8.1) from forestry_1.12.2-5.8.0.303.jar
		* ForestryAPI|circuits (3.1.0) from forestry_1.12.2-5.8.0.303.jar
		* ForestryAPI|climate (5.0.0) from forestry_1.12.2-5.8.0.303.jar
		* ForestryAPI|core (5.7.0) from forestry_1.12.2-5.8.0.303.jar
		* ForestryAPI|farming (5.8.0) from forestry_1.12.2-5.8.0.303.jar
		* ForestryAPI|food (1.1.0) from forestry_1.12.2-5.8.0.303.jar
		* ForestryAPI|fuels (3.0.0) from forestry_1.12.2-5.8.0.303.jar
		* ForestryAPI|genetics (5.7.0) from forestry_1.12.2-5.8.0.303.jar
		* ForestryAPI|greenhouse (5.2.0) from forestry_1.12.2-5.8.0.303.jar
		* ForestryAPI|gui (5.8.0) from forestry_1.12.2-5.8.0.303.jar
		* ForestryAPI|hives (4.1.0) from forestry_1.12.2-5.8.0.303.jar
		* ForestryAPI|lepidopterology (1.4.0) from forestry_1.12.2-5.8.0.303.jar
		* ForestryAPI|mail (3.1.0) from forestry_1.12.2-5.8.0.303.jar
		* ForestryAPI|modules (5.7.0) from forestry_1.12.2-5.8.0.303.jar
		* ForestryAPI|multiblock (3.0.0) from forestry_1.12.2-5.8.0.303.jar
		* ForestryAPI|recipes (5.4.0) from forestry_1.12.2-5.8.0.303.jar
		* ForestryAPI|storage (5.0.0) from forestry_1.12.2-5.8.0.303.jar
		* ForestryAPI|world (2.1.0) from forestry_1.12.2-5.8.0.303.jar
		* iChunUtil API (1.2.0) from iChunUtil-1.12.2-7.1.4.jar
		* ImmersiveEngineering|API (1.0) from ImmersiveEngineering-0.12-82.jar
		* ImmersiveEngineering|ImmersiveFluxAPI (1.0) from ImmersiveEngineering-0.12-82.jar
		* jeresources|API (0.8.5.27) from JustEnoughResources-1.12.2-0.8.5.27.jar
		* journeymap|client-api (1.4) from journeymap-1.12.2-5.5.2.jar
		* journeymap|client-api-display (1.4) from journeymap-1.12.2-5.5.2.jar
		* journeymap|client-api-event (1.4) from journeymap-1.12.2-5.5.2.jar
		* journeymap|client-api-model (1.4) from journeymap-1.12.2-5.5.2.jar
		* journeymap|client-api-util (1.4) from journeymap-1.12.2-5.5.2.jar
		* JustEnoughItemsAPI (4.13.0) from jei_1.12.2-4.10.0.198.jar
		* MekanismAPI|core (9.0.0) from Mekanism-1.12.2-9.4.13.349.jar
		* MekanismAPI|energy (9.0.0) from Mekanism-1.12.2-9.4.13.349.jar
		* MekanismAPI|gas (9.0.0) from Mekanism-1.12.2-9.4.13.349.jar
		* MekanismAPI|infuse (9.0.0) from Mekanism-1.12.2-9.4.13.349.jar
		* MekanismAPI|laser (9.0.0) from Mekanism-1.12.2-9.4.13.349.jar
		* MekanismAPI|transmitter (9.0.0) from Mekanism-1.12.2-9.4.13.349.jar
		* MekanismAPI|util (9.0.0) from Mekanism-1.12.2-9.4.13.349.jar
		* MouseTweaks|API (1.0) from MouseTweaks-2.8-mc1.12.1.jar
		* openblocks|api (1.2) from OpenBlocks-1.12.2-1.7.6.jar
		* projecteapi (1.12.2-1.0.0) from ProjectE-1.12-PE1.3.0.jar
		* reborncoreAPI (3.8.9.300) from RebornCore-1.12.2-3.8.9.300-universal.jar
		* reborncoreAPI|Power (3.8.9.300) from RebornCore-1.12.2-3.8.9.300-universal.jar
		* reborncoreAPI|Recipe (3.8.9.300) from RebornCore-1.12.2-3.8.9.300-universal.jar
		* reborncoreAPI|Tile (3.8.9.300) from RebornCore-1.12.2-3.8.9.300-universal.jar
		* valkyrielib.api (1.12.2-2.0.10a) from valkyrielib-1.12.2-2.0.11a.jar
		* WailaAPI (1.3) from Hwyla-1.8.26-B41_1.12.2.jar
	RebornCore: 
		Plugin Engine: 0
		RebornCore Version: 3.8.9.300
		Runtime Debofucsation 1
		RenderEngine: 0
	Launched Version: forge-14.23.4.2708
	LWJGL: 2.9.4
	OpenGL: GeForce GT 730/PCIe/SSE2 GL version 4.6.0 NVIDIA 397.64, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Soartex_Fanver_Modded_Universal.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i3-4160 CPU @ 3.60GHz`

Sorry if this is because I'm dumb, thanks for your time.

**Comment by PanSzelescik** [comment]
Disable Thermal Expansion integration in Base Metals

**Comment by Automatizer** [comment]
Thanks for the heads up, it worked.
