### ISSUE TITLE
Flux infused sword makes endermen disengage

### ISSUE THREAD

**Issue by psusi** [CoFH/Feedback#1164]
When fighting endermen being spawned by an MFR spawner ( or otherwise ), at least 4/5 teleport away and disengage ( as if touched by water ) when I attack them with a flux infused sword.  When using a normal steel sword, maybe 2 or 3 out of 5 teleport away before I can kill them, but they continue to growl at me and if I look around a bit, I find them and they continue to attack me.

This is with RedstoneArsenal-[1.7.10]1.1.1-89.jar

**Comment by KingLemming** [comment]
Vanilla mob code and AI behavior when they take a hit of a certain size. There's nothing wrong here.
