### ISSUE TITLE
[Suggestion] Thermal Expansion: Cache Storage Controller

### ISSUE THREAD

**Issue by PearlCanopus** [CoFH/Feedback#1165]
I don't know whether this has been suggested, because I found nothing with my search criterias.
Moreover I'm aware that Thermal Expansion is not storage centered. So far I want not suggest a complete storage system.

I could imagine to have a controller item for caches. It could have 9 slots inside where to place the caches. For each entered cache you can filter the storing item as a free accessible stack.
Brother in mind:
Black Hole Unit (https://ftb.gamepedia.com/Black_Hole_Unit) and Black Hole Controller (https://ftb.gamepedia.com/Black_Hole_Controller) from Industrial Forgoing.

It uses a special amount of RF for each controlled cache inside. It's available in tiers.
examples:
basic: 1x cache storage
hardened: 1,3x cache storage
reinforced: 2x cache storage
signalum: 4x cache storage
resonant: 8x cache storage
This stacks with the cache tiers up to 4 million items per cache.

Squeezing and densing in every tier raises the amount of energy needed but also the controllers energy buffer.
Example:
- Basic 10RF/t empty - Doubling with every controller tier
- 10RF/t for each basic cache inside - Doubling with every cache tier

It allows to have "block in block". It will save space and allows to store masses.
The controller should be possible to get peered with AE2, RS and other storage mods. You can acces it with Thermal Dynamics (and others) pipes/ducts or manually.
---
I could imagine to have that for fluid control as a "tank controller" too.
---
Right now I have no ideas about augments or enchantments beside once more storage capacity and energy needed... ;)

If it does'nt matches your mod philosophy, you may close the thread.

**Comment by KingLemming** [comment]
Sorry, but this isn't something I'll be doing in 1.12.2, and 1.13 is going to be a completely different ball game. :)
