### ISSUE TITLE
FTB Infinity 2.5.0 Watering Can get instant damage 

### ISSUE THREAD

**Issue by Kratzwurst** [CoFH/Feedback#1165]
Hey all, i play with friends the modpack ftb Infinity evolved 2.5.0. and we crafting a autonomous activator for fast growing with a normal watering can from extra utilities...when i putt the can in the inventory than get the can instandly damaged.
https://www.youtube.com/watch?v=Xcrklz7pBGw as of 12 minutes can u see what i mean ;)

greets

**Comment by KingLemming** [comment]
This has nothing to do with us. That's an ExU design decision.

**Comment by Kratzwurst** [comment]
Okay Thank you!
