### ISSUE TITLE
[Suggestion] Sneak right click to change fluxbore mode

### ISSUE THREAD

**Issue by ilhamsitok** [CoFH/Feedback#1166]
Having fun with fluxbore in my mining trip, but i have to change my cofh key binding every time i go and done mining, maybe using specific key binding, like sneak right-click?

**Comment by KingLemming** [comment]
Why do you have to change it? I don't understand your complaint.

**Comment by ilhamsitok** [comment]
srry for late reply, so I'm basically using the mouse (;)  button for my COFH key when i'm not mining, but because I'm only using one tool to mine, which is fluxbore I need to change the cofh key to some where close to either to movement key or to mouse button. usually i move the key to my mouse 4 button, but because i use that key for something more important when I'm not mining, I need to keep change the key bind for my COFH key. not just me actually, some of my friends had the same problem

**Comment by CrossVas** [comment]
Hey!

I personally use Grave (`) or/and TabKey for any Thermal Expansion's tools when they are in my pack and have no problem.

Here we have to set the priority of things. If you use Drills (Fluxbore) all the time you will need to bind a key which is more convenient for you and forget about this key when you set another's key bindings.

**Comment by KingLemming** [comment]
Yeah sorry but the key is used across all tools, including those which already have sneak-use. It's inconsistent and inelegant to change things.
