### ISSUE TITLE
Client-side crash possibly caused by thermal foundation

### ISSUE THREAD

**Issue by m1jordanallen** [CoFH/Feedback#1167]
A few players on a server I run are experiencing a client side only crash and the report doesn't point to much except for..... well, you'll see :)  

If this is an issue not caused by a COFH mod, let me know and I will try to find the right place to post this.  

http://pastebin.com/WdjUxXRp

**Comment by skyboy** [comment]
The problem is caused by net.ilexiconn.llibrary
