### ISSUE TITLE
[Thermal Expansion 1.10.2] Suggestion: "Augment: Power Transmission Bus"

### ISSUE THREAD

**Issue by rbuckton** [CoFH/Feedback#117]
This suggestion is for an augment that could be used on any machine that allows for RF retransmission to machines on any side. This could help reduce the complexity of multi-step processing systems by removing the need for (most) power conduits/flux ducts to distribute power to each machine. This is somewhat similar to how Applied Energistics blocks retransmit AE when placed adjacent to each other. 

Possible options:

1. RF retransmission per side is configurable.
2. RF transmitted to each side is pulled from the machine's internal buffer.
3. Multiple augments would increase the maximum RF/t that the machine can transmit to any side.
4. Alternatively, instead of implementing [3], maximum RF/t that the machine can transmit is limited to its machine tier.
5. Alternatively, instead of implementing [3] or [4], maximum RF/t that the machine can transmit is determined by placing a compatible power conduit/flux duct in either the "battery" slot of the machine or a dedicated slot in the power configuration tab in [1] above.

Proposed Crafting Recipe:
```
+---+---+---+    1. Electrum Ingot
|   | 1 |   |    2. Redstone Transmission Coil
+---+---+---+    3. Redstone Dust
| 1 | 2 | 1 |
+---+---+---+
| 3 | 1 | 3 |
+---+---+---+
```

**Comment by KingLemming** [comment]
Here's the problem - Fluxducts are optimized for this, machines aren't.

So overall, this sort of thing is a liability for the server, full stop.

Not to mention the configuration of this is also somewhat confusing.

I'm not saying no yet, but I'll need to be swayed.

**Comment by transcondriver** [comment]
Just my two cents:
This sounds interesting. Power transmission via the fourth point sounds the most reasonable, in my opinion, due to the benefits tiered machines provide. I don't know what strain this would cause code-wise, or its complexity. On the other hand, it would essentially turn individual machines into energy conduits or cells.

I think an additional question could be "does this add or detract from the intent of Thermal Expansion?"

**Comment by rbuckton** [comment]
@KingLemming If TD will have the necessary optimizations for energy transmission, perhaps it would be an augment that is only available if TD is also installed. That would allow you to leverage the existing energy transmission logic in TD. Of course, without spending some time becoming familiar with the TD and TE codebases I couldn't begin to estimate the complexity of such a change.

As far as configuration, are you talking about the end-user of the machine? I would see the configuration as either an addition to the energy tab or through a new tab with a control similar to the existing side configuration tab on the right of the machine GUI. Alternatively (and more simply), it could supply power in a fashion similar to the Tesseract to machines/ducts/conduits on any side.

**Comment by KingLemming** [comment]
After giving this a lot of thought, I'm going to have to say no. I appreciate the idea, and I really was torn on it, but I thought about the actual gameplay a bit more and it just didn't seem fantastic.

I do, however, have some ideas on how to more conveniently get power to machines in tight places. ;)
