### ISSUE TITLE
Suggestion: Allow specifying different liquid inputs for Phytogenic Insolator recipes via Modtweaker

### ISSUE THREAD

**Issue by Tyrant0x1** [CoFH/Feedback#1170]
I had a thought the other day that it would be neat if I could grow my Astral Sorcery rock/celestial crystals in the Phytogenic Insolator instead of in-world (somewhat like AE2 certus/fluix). I can essentially do this already with a modtweaker script (even including the crystal splitting mechanic via the Insolator's secondary output, if I can figure out the logic there), but I can't specify that I'd like the recipe to require Liquid Starlight. Would it be possible to add an ILiquidStack parameter to the Insolator's addRecipe function?

Thanks for your consideration!

**Comment by KingLemming** [comment]
No, sorry. It's water only. Allowing another fluid is basically a full rewrite of the machine and I simply don't wish to do that.
