### ISSUE TITLE
[Suggestion] Other coolants can produce more RF

### ISSUE THREAD

**Issue by PanSzelescik** [CoFH/Feedback#1171]
Example:
Compression Dynamo: Creosote Oil + Water + 1x Augment: Closed-Loop Cooling + 3x Augment: Auxiliary Transmission Coil = 480 rf/t
Compression Dynamo: Creosote Oil + Gelid Cryoyheum + 1x Augment: Closed-Loop Cooling + 3x Augment: Auxiliary Transmission Coil = 640 rf/t

This is example, amount of RF can you change

**Comment by KingLemming** [comment]
Coolants already produce more total RF, just not more RF/t - Cryo is even 40% more. This change would way overpower the Closed-Loop augment to the point where I'd have to remove it.

Sorry, but this is a no.
