### ISSUE TITLE
Inside of head visible while in bed (COFH tweaks)

### ISSUE THREAD

**Issue by jkenyonc** [CoFH/Feedback#1171]
the inside of the player head is visible while sleeping. this does not happen in vanilla minecraft. 
![2016-06-06_18 09 54](https://cloud.githubusercontent.com/assets/12718528/15842037/ce84bd3c-2c12-11e6-9280-edc89b5d8624.png)

**Comment by KingLemming** [comment]
This either isn't us, unless you've tested in isolation, or...if it is us, then too bad and it's a side-effect of render optimization.

This is a pretty trivial issue given what Tweaks does.

**Comment by skyboy** [comment]
It's a vanilla issue, or maybe a forge issue. At the least it's been present in all modded installs for a few years now.
