### ISSUE TITLE
Thermal Innovation：Incompatible with Thaumcraft

### ISSUE THREAD

**Issue by YonChun** [CoFH/Feedback#1172]
Because there is a Thermal Innovation that causes the installation of Thaumcraft6.1.BETA16 to crash the game.

**Comment by KingLemming** [comment]
Have a crashlog? This is *highly* unlikely to be anything on our end.

**Comment by YonChun** [comment]
[crash-2018-06-24_01.19.45-client.txt](https://github.com/CoFH/Feedback/files/2130110/crash-2018-06-24_01.19.45-client.txt)

**Comment by KingLemming** [comment]
Thaumcraft seems to be breaking Baubles somehow. That's not on us.

**Comment by YonChun** [comment]
OK, then I'll go to the author of Thaumcraft. Thank you for your answer.
