### ISSUE TITLE
Game crash on startup. 

### ISSUE THREAD

**Issue by ConnCraft** [CoFH/Feedback#1173]
Title.
CodeChickenLib 1.12.2-3.1.9.344
CoFHCore 1.12.2-4.5.2.19
CoFHLib 1.7.10 1.2.1-185
CoFHWorld 1.12.2-1.2.0.5
RedstoneFlux 1.12-2.0.2.3
ThermalCultivation 1.12.2-0.3.0.7
ThermalDynamics 1.12.2-2.5.1.14
ThermalExpansion 1.12.2-5.5.0.29
ThermalFoundation 1.12.2-2.5.0.19
https://pastebin.com/LitEckmt

**Comment by KingLemming** [comment]
Yeah, legit have no idea what to tell you there except to reinstall everything. All mods, Minecraft, Java, Windows, whatever.

You either have a busted jar or busted Java. If this error were in our code, literally everyone would get this every time. As such, it is tech support. Feel free to swing by the Discord and see if they can help you debug it.
