### ISSUE TITLE
Thermal Expansion Doesn't Load Into My Server

### ISSUE THREAD

**Issue by oX5Dylan5Ox** [CoFH/Feedback#1173]
I Have Created A Private Modpack Of My Own All Mods Are Stable And Up To Date Currently Working Perfect On My Client But After Uploading It To My Server To Play With My Friend It Wouldn't Load Thermal Expansion And Replied With "Mod Rejections : Thermal Expansion" So I Removed It From My Client To Check And It Wasn't On The Server Although It Is In The Mods Folder. Also It Didn't Generate A Crash Report And There Was Nothing Indicating Why In The Server Console.

I Have All Dependencies + Thermal Dynamics

Mod Versions:
CoFHCore-[1.7.10]3.1.2-325
ThermalFoundation-[1.7.10]1.2.4-114
ThermalExpansion-[1.7.10]4.1.2-240
ThermalDynamics-[1.7.10]1.2.0-171

Mod List:
http://pastebin.com/TRVs0mfQ

Thanks In Advance.

**Comment by skyboy** [comment]
Redownload and trying uploading again, occasionally errors do happen when uploading/downloading files that corrupt them.
