### ISSUE TITLE
[Thermal Expansion] JSON Recipe system does not load all ore dictionary entries

### ISSUE THREAD

**Issue by rikpronk** [CoFH/Feedback#1174]
TE Version:   ThermalExpansion-1.12.2-5.5.0.29-universal
Mod list: https://pastebin.com/UypBqdfw

**What I did:**
Used the default recipe configs from Thermal Expansion, provided in the `src/main/resources/assets/thermalexpansion/content/machine/sawmill/sawmill_biomass.json` file, both from the package and explicitly provided in the config folder. Also edited the config file with entries added for Pam's Harvestcraft foods, using ore dictionary entries "listAllfruit" and "listAllveggie". [Edited config file here](https://pastebin.com/42VnYQGk).

**What I expected to happen:**
According to the ore dictionary in game, the Biomes o' Plenty Saplings are registered as "treeSapling". As the default config adds the recipe for biomash using "treeSapling" as input, the recipe should allow all BoP saplings. The same goes for the Pam's Harvestcraft foods in my custom config.

**What happened:**
Only the vanilla saplings appeared in the ore-dictionaried recipe. None of the Pam's Harvestcraft foods are accepted as input. Since two popular, long-living mods seem to exhibit the same behavior, I am assuming their oredict values are correctly and timely registered and TE should pick up on them.

**Comment by KingLemming** [comment]
The sapling thing is addressed in dev already. The "listAllWhatever" is not and will not.

Internally, only certain ore names/prefixes are valid for auto-conversion. treeSapling and treeLeaves were mistakenly left off the list.

listAllVeggie/Fruit will not be added, as it simply causes too many problems.
