### ISSUE TITLE
[1.12.2] Morb with Animania Rabbits

### ISSUE THREAD

**Issue by TheSnowyChickens** [CoFH/Feedback#1176]
Hello,
I tryed to catch a rabbit from Animania with a morb (reusable and normal), but it was not possible to catch it. The morb just irgored it and it just lying around there. (after the throw)

![2018-06-27_09 42 23](https://user-images.githubusercontent.com/29357962/41959851-69554798-79ee-11e8-9f40-a9e4746de196.png)

MC 1.12.2
Forge 2705
ThermalExpansion-1.12.2-5.5.0.29-universal
ThermalFoundation-1.12.2-2.5.0.19-universal
CoFHCore-1.12.2-4.5.2.19-universal
Animania 1.4.8

**Comment by KingLemming** [comment]
Morbs only work on mobs which have *normal* spawn eggs registered with Minecraft. If the mob doesn't have that, then it isn't supported atm.

Just how it works, sorry.
