### ISSUE TITLE
[RedstoneArsenal] Unbreaking enchantment on flux tools

### ISSUE THREAD

**Issue by Creeperman8362** [CoFH/Feedback#1178]
The unbreaking enchantment on flux tools is not implemented properly. According to the Minecraft wiki, the unbreaking enchantment on tools makes it so that there is a "(100/(Level+1))% chance a use reduces durability." However, on the flux tools, this is not the case. Obviously the chance aspect can't work on flux tools, but adjusting the rf per use to match regular tools unbreaking would work. "On average, lifetime is (Level+1) times as long." The rf per use levels should be 200, 100, 67, 50, going by the wiki's approximations, and matching levels for unbreaking on normal tools.

The current system is 200, 160, 120, 80, which is not how unbreaking works.

For unbreaking 1, the chance a use reduces durability is (100/(1+1))=50%. This would translate into the flux tools having 100rf per use, since both would result in an average of 2x lifespan.

For unbreaking 2, the chance a use reduces durability is (100/(2+1))=33.33333%. This would translate into the flux tools having 67rf per use, since both would result in an average of 3x lifespan.

For unbreaking 3, the chance a use reduces durability is (100/(3+1))=25%. This would translate into the flux tools having 50rf per use, since both would result in an average of 4x lifespan.

Yes, this is a bug. According to wikipedia, "A software bug is an error, flaw, failure or fault in a computer program or system that causes it to produce an incorrect or unexpected result, or to behave in unintended ways." This is an error made in coding which causes an incorrect result of the enchantment.

**Comment by KingLemming** [comment]
This is not a bug. This is intentionally how I coded it and how I want it implemented for balance reasons.

Thanks for your input though. :)
