### ISSUE TITLE
Thermal Expansion Factorizer gives infinite quartz

### ISSUE THREAD

**Issue by ProfessorCool** [CoFH/Feedback#1178]
In Thermal Expansion 5.4.2.27, the Factorizer on split turns a block of quartz into 9 nether quartz. However, you can turn 4 nether quartz into a block, effectively allowing infinite nether quartz.

**Comment by KingLemming** [comment]
Yup. Sure does.

This is why Thermal Expansion is on 5.5.x now. We do fix bugs...just need people to download the updates.

**Comment by ProfessorCool** [comment]
Lol, my bad. I didn't have time to update and didn't see it in a quick run down on the patch notes. Nice job.

**Comment by KingLemming** [comment]
Yeah, dupe bugs and fixes don't really get announced with notes...tends to just be rolled under "recipe changes." ;)
