### ISSUE TITLE
[Thermal Expansions] Tesseact Client closed

### ISSUE THREAD

**Issue by Kratzwurst** [CoFH/Feedback#1179]
hey ho....i played actually the modpack project ozone and i have a little problem with your tesseact. when i it first installed, than runs with no problems...but when i looking (much later) into the interface from the tessact...than crash it my game and client.

here the last crash report:
http://pastebin.com/3768wBDY
Modversion: 4.1.2-240 update not available

greets

**Comment by skyboy** [comment]
This is a bug related to the item you were holding in your hand when you opened the tesseract, not the tesseract.

**Comment by Kratzwurst** [comment]
i think i have not any item in my right hand to open the gui from the tesseact.
