### ISSUE TITLE
[Suggestion] Thermal Innovation: Hypoinfuser to only inject Health when needed

### ISSUE THREAD

**Issue by exube** [CoFH/Feedback#1179]
As of 0.3.0.7 (MC 1.12), the Hypoinfuser loaded with Instant Health or Regeneration and set to auto-infuse is active even when at full health, wasting the potion.  

I wanted to make a request for Hypoinfusers configured with auto-infuse and loaded with Instant Health or Regeneration to only activate when the player isn't at full health, or maybe when at half health.  

This is more of a convenience thing than a real issue though, as some people like to just stick buff injectors in their Bauble slots and forget about them.

**Comment by KingLemming** [comment]
Sorry, but no. I'd rather come up with some other way of making the player functionally invulnerable.

Mechanics-wise the Infuser is already incredibly powerful and other (modded) potions may also grant health regen effects, not just those. We'd have to maintain an opt-in whitelist and API to handle those, or it's just kludgey and inelegant.

As far as the Bauble thing goes...well, it works in a normal slot. The fact that people insist on wasting what is frankly a more valuable inventory slot still baffles me.
