### ISSUE TITLE
[1.10.2] Morph o Tool not recognizing TE machines

### ISSUE THREAD

**Issue by Firestar311** [CoFH/Feedback#118]
Not sure if this Ken's problem with Morph o Tool or TE, but when I have the crescent hammer installed on the Morphing Tool, it does not auto-switch when looking  at a TE machine. 
Mod Page: https://minecraft.curseforge.com/projects/morph-o-tool

**Comment by KingLemming** [comment]
This isn't going to be a TE problem, that much I can tell you.

I think this is relevant though:
https://www.reddit.com/r/feedthebeast/comments/5zbku9/how_to_add_the_crescent_hammer_to_morphotool/

**Comment by Firestar311** [comment]
Oh, I just realized that the Crescent Hammer comes from Thermal Foundation. My mistake...
