### ISSUE TITLE
Water in Nether

### ISSUE THREAD

**Issue by mofocro** [CoFH/Feedback#1181]
This might not be the best place for this, but I'm looking for a way to allow for water in the nether. Possibly someway to bypass the block file that replaces water when placed in the nether. I'm pretty new at this and currently have no clue at what to do as removing those files crashes the game. Any help would greatly be appreciated! Thanks.

**Comment by TheTrueForce** [comment]
This would need a mod, but I have no idea where you could find such a mod, or how one would be made. Try looking and asking on the Minecraft Forums, at http://www.minecraftforum.net/, or try looking on the mod list, at http://modlist.mcf.li.
If you removed a file from the Minecraft jar(which is what it sounds like you did), that will nearly always crash the game, as it needs 99% of those files to run.

**Comment by KingLemming** [comment]
Sorry, but at the moment CoFHCore actually fixes bugs which ALLOW this to happen. While we will be removing that for 1.9, it's not really something we have interest in supporting.
