### ISSUE TITLE
[Suggestion] Forestry saplings for Phytogenic Insolator?

### ISSUE THREAD

**Issue by exykai** [CoFH/Feedback#1182]
Is it possible for the Phytogenic Insolator to grow Forestry (and Binnie's Extra Trees) saplings regardless of what genes they have? I really like Larch wood planks and would be so happy if it could be grown in the Phytogenic Insolator. I see that non-vanilla wood blocks can be processed in the sawmill, hopefully it's not too far a stretch for that to be implemented.

(Maybe you can make the arboreal extractor extract fruit juice out of applicable trees too? ;) )

**Comment by KingLemming** [comment]
Sorry, can't be done, as you have probably already surmised.

Forestry stuff uses NBT. It's a non-starter.
