### ISSUE TITLE
Item Allocator + Minecraft Hopper + Forge MicroBlocks = Duplication Glitch

### ISSUE THREAD

**Issue by fijodi** [CoFH/Feedback#1183]
XD

![2016-06-17_04 40 51](https://cloud.githubusercontent.com/assets/19339770/16135525/0453387c-3446-11e6-9704-e6b83653231f.png)
![2016-06-17_04 41 04](https://cloud.githubusercontent.com/assets/19339770/16135529/089a353e-3446-11e6-9b63-1bf0ec59b3de.png)
![2016-06-17_04 41 19](https://cloud.githubusercontent.com/assets/19339770/16135530/0ab6a258-3446-11e6-8aeb-6b78f5cbf928.png)
FTB Automata Mod Pack

**Comment by KingLemming** [comment]
Yeah, that's 100% on the hopper. It's notorious for not getting things right.
