### ISSUE TITLE
block hardness

### ISSUE THREAD

**Issue by captainbritian** [CoFH/Feedback#1184]
all thermal machines and conduits can be broken by hand i have tested this in a pack with only thermal mods installed as i am making a pack and this came up at first i thought it was the tool progression mod but i was wrong when i tried to add the wrench to being the only block that could break the machines but it still with the tool progression mod shows up as null-1 as the mining level i was wondering if there was anyway for me to fix this 

versions of the thermal mods are  for 
cofh core 4.5.2.12
cofh world 1.2.0.5
thermal foundation 2.5.0.19
thermal expansion 5.5.0.29
version of minecraft is 1.12.2

**Comment by KingLemming** [comment]
There's not a "fix" for it because it isn't broken. This is working as intended, although if you try and break one by hand, it's going to take a *really* long time.
