### ISSUE TITLE
[Thermal Dynamics] Mekanism 9 Creative Energy Cube doesn't output to fluxducts of any kind

### ISSUE THREAD

**Issue by mattfreyer** [CoFH/Feedback#1184]
It seems when the Creative Energy Cube tries to output to any kind of fluxduct it shows a negative amount of energy in the fluxduct. Not sure if this is on your or Mekanism's end so i decided to report it here.
Cofh 3.1.2
Thermal Dynamics 1.2.0
Mekanism 9.0.0

**Comment by KingLemming** [comment]
That's going to be on Mekanism's end. If the ducts were broken, they'd be broken for everything. Just how RF works.
