### ISSUE TITLE
Showing crafting recipe's with ingots but working with gears

### ISSUE THREAD

**Issue by Theslimygarbo** [CoFH/Feedback#1185]
I found enabling this config option show crafting recipes with ingots but I tried it with ingots and it didn't work so I tried it with gears and it worked. Here are my mods and config folders config -->

[config.zip](https://github.com/CoFH/Feedback/files/321905/config.zip)

I cannot upload mods folder as it is to big but you can probably tell from config folder

**Comment by skyboy** [comment]
Configuration needs to be the same on both server and client.
