### ISSUE TITLE
Request: Add your own ingot with Thermal Foundation

### ISSUE THREAD

**Issue by TheDeviantCrafter** [CoFH/Feedback#1186]
There are quite a few mods that add metals that aren't present in Thermal Foundation. Osmium is a good example. Thermal Foundation is a fantastic mod for pack makers, but I'd like the ability to add my own metals.

Specifically, I'd like to be able to choose a name and a hex color value in a config. The mod would then generate an ingot for that item, with the specified name and color.

For example, naming something osium and supplying the hex color `13335F` would make something comparable to Mekanism's osmium.

It would also regenerate items for dust, plates, gears, blocks, nuggets, and optionally hardened glass. These could be dynamically generated at run time using greyscale textures for each texture.

**Creating tool types:**

I don't think this is critical, but it's a fun idea so I figured I'd expand on it. Currently the mod adds tools, armor and other gear items for each metal. This could be expanded to include custom metal types.

Armor and tools would be difficult since the pack maker would need to supply unique stats for each item. To simplify this, you could let the pack maker supply values for speed, durability, and toughness. These would be ranges between 0 and 1.

Stats would be dynamically generated based on these stats. For example, let's say the pack maker chose that a metal would have high speed but low toughness. A pickaxe of this type would be fast since that stat is drawn from speed, but have a low mining level since that's determined by toughness.

| Tool type     | Stat name    | Effect          |
| ------------- | ------------- |------------- |
| Armor          | Toughness   | Protection  |
| Armor          | Speed          |   N/A    |
| Armor          |  Durability    |    Durability      |
| Tools            | Toughness   |   Mining level    |
| Tools            | Speed          | Mining speed   |
| Tools            | Durability     |  Durability    |
| Swords         | Toughness |  Damage    |
| Swords         |  Speed     |  Swing speed    |
| Swords         | Durability    |  Durability    |
| Bow |  Toughness | Projectile distance |
| Bow |  Speed | Draw speed |
| Bow |  Durability | Durability |

This graph is an example, but it could probably be expanded. I'd probably add a way to control the innate luck of the sea and lure effects on fishing rods, for example.

Values would range from 0 to 1. It would be a float value. The mod would choose an upper and lower bound for each stat. When deciding the damage of a sword, for example, the mod would decide that a value of 0 should compare to a wooden sword, and the upper bound is twice as powerful as a diamond sword. Therefor a value of 0.5 would be roughly the strength of a diamond sword.

The goal of this is to make it easier for pack makers to edit tools. Packs rarely require fine tuned control over this. The only exception is mining level, so it may make sense to give these fixed values. Controlling each value in a JSON file is another option, but realistically a frustratingly small percentage of pack developers would bother.

**Comment by KingLemming** [comment]
At this point, it'd be a new mod entirely and not Thermal Foundation. I'll consider making such a mod in 1.13, when there's no metadata to worry with.

Right now though, I'm afraid not.
