### ISSUE TITLE
coFH core Java se binary (forge)

### ISSUE THREAD

**Issue by WHOSAMAZINGGGG** [CoFH/Feedback#1186]
So i just tried to load minecraft with cofh core as one of my mods it came up with a java se binary has stop working and the mod that was last shown was cofh core. the i tried to load minecraft with only cofh core installed it did the same thing

**Comment by KingLemming** [comment]
Try IRC for tech support. This is an issue with your version of java, or your potato computer, or some such, but it's not a code problem.
