### ISSUE TITLE
Cryo-Stablilized Fluxduct Not connecting when i load the world

### ISSUE THREAD

**Issue by xp0colipse** [CoFH/Feedback#1187]
I opened up my test world and all my cryo fluxducts were not connected and I have to break everyone of them to fix it, any idea why this is happening?
![2018-07-06_07 48 32](https://user-images.githubusercontent.com/19493262/42377517-9695f6ee-80f1-11e8-8d6b-c6a4550e1073.png)

**Comment by KingLemming** [comment]
Nope, but likely the fault of what they're connected to. This came up previously and it was determined that something was screwing with either tile entity data or load processing. It isn't the duct, though.
