### ISSUE TITLE
[MFR] does not activate all child mods

### ISSUE THREAD

**Issue by Esmey** [CoFH/Feedback#1188]
Dear CoFH Team,
if i install Minefactory reloaded, Minecraft did not load all childmods. 23 are loaded 8 are activated
The game doesn't crash but i dont know what to do now. please help me. :)

Minecraft 1.7.10
Minecraft Forge 10.13.4.1614-1.7.10

Mods:
MineFactoryReloaded-[1.7.10]2.8.1-174
CoFHCore-[1.7.10]3.1.2-325

Best Greetings
Esmey

**Comment by KingLemming** [comment]
Nothing is wrong. If the conditions aren't met, the child mods don't load. That's how MFR does plugins. It's fine.

**Comment by Esmey** [comment]
Thanks a lot!!
