### ISSUE TITLE
[Foundation] BlockOre.getLightValue

### ISSUE THREAD

**Issue by iamomicron** [CoFH/Feedback#1189]
More recent forge versions for 1.7.10 require setLightLevel to use a float, rather than an integer value of 0-15.

For example, the registry of glowstone currently, is:

`blockRegistry.addObject(89, "glowstone", (new BlockGlowstone(Material.glass)).setHardness(0.3F).setStepSound(soundTypeGlass).setLightLevel(1.0F).setBlockName("lightgem").setBlockTextureName("glowstone"));`

Which uses the float value 1.0F. The current release of TF uses values of 0-15 which causes crashes such as the ones below: 
#570 
http://pastebin.com/hp8uA2y7

Specifically an error with [this](https://github.com/CoFH/ThermalFoundation/blob/master/src/main/java/cofh/thermalfoundation/block/BlockOre.java#L51)

**Comment by KingLemming** [comment]
setLightLevel uses a float, it's always returned as an int.

What you are seeing is an ID mismatch due to a corrupted world.

**Comment by iamomicron** [comment]
Alright, makes sense. How would that go about happening though?
