### ISSUE TITLE
Thermal Expansion/Foundation tinker's bug. (Please read)

### ISSUE THREAD

**Issue by DigitolMC** [CoFH/Feedback#119]
I KNOW that this isn't a bug report/suggestion but It's super annoying for me and my friend as we're trying to play FTB Infinity and we can't exactly repair our tinkers tools and get our modifiers back etc. 

This is due to a bug caused by thermal e,f or cofh.

Skyboy mentioned in #15 that he'd fixed the issue in development. Which version on curseforge is this actually fixed in? I've downloaded Expansion, Foundation and CoFHCore (latest) off of curseforge. They don't crash on startup or anything. I loaded a new world and made a silver hammer. I got it down to half of it's HP and tried to repair it, and it didn't work. Also, Skyboy, not to be pushy or anything, but with these bugs and stuff would you mind editing what your reply is with a link to download the version where it's fixed off of curseforge? I appreciate that it's meant to be only for people who want to bug fix, but it's nice to be able to play the game without it being bugged and you having to try and fix it yourself.
Thanks.

**Comment by DigitolMC** [comment]
Why hasn't anybody read this yet?

**Comment by KingLemming** [comment]
Read it, but I just don't have any familiarity with what you're referring to.

Have you tried with the newest release versions?

**Comment by skyboy** [comment]
This requires a new tcon release, but TE is telling tcon the tools are repairable.

**Comment by bochen415** [comment]
https://github.com/SlimeKnights/TinkersConstruct/issues/1399
