### ISSUE TITLE
Thermal Expansion Machine Upgrade Suggestion

### ISSUE THREAD

**Issue by y2clay14** [CoFH/Feedback#1190]
First of all I think Thermal Expansion/Dynamics/Foundation are my favorite minecraft mods.  I love the fact that you can upgrade existing machines with your existing machine, but what if you could just craft a Machine Upgrade?  You could have a recipe for a Hardened, Reinforced, and Resonant machine upgrade.  Same recipe as the current upgrade recipe but just without the machine in the middle.  This way you wouldn't have to pick up your machine and disrupt your processing and or use.  You could shift+right click on the machine with the upgrade and it would just upgrade to the next tier in place. This would provide you with on the fly upgrading.  Of course you could only use a hardened upgrade on a basic machine, only Reinforced on a Hardened Machine etc.  Unsure if this is feasible or not but I think this would be a great addition that would make this already amazing mod even better!

**Comment by skyboy** [comment]
You can also just craft the resonant machine frame from the start and have a resonant machine instead of a basic machine for your factory setups.

**Comment by y2clay14** [comment]
That's what I do when I have access to the higher tier materials, but It
would be nice to upgrade the starting machines without having to pick em up
since most the time I cant start out by making a resonant machine frame.

**Comment by KingLemming** [comment]
I'm not ruling it out personally, but I don't know how much code I'll be writing in the near/far future.
