### ISSUE TITLE
[BUG] Making Enderium blend in Sequential fabricator produces nothing but uses resources

### ISSUE THREAD

**Issue by Ax1007** [CoFH/Feedback#1190]
Thermal expansion 1.12.2-5.0.19 as part of Modern Sky block 3 Departed.

The SF with the fluid augment uses resources but creates nothing. Tested with every export setting, not product is is made at all.

**Comment by KingLemming** [comment]
Can't replicate. If it's happening, it's because of something that the pack is doing. Or you really are just ejecting the product.
