### ISSUE TITLE
[TE] Cyclic Assembler client NPE crash setting a schematic's NBT.

### ISSUE THREAD

**Issue by Paul17041993** [CoFH/Feedback#1191]
This is an odd one as I don't see why it would occur, but putting in a glowing reed from Gany's Nether, to make 2 glowstone dust, into any crafting slot and pressing the tick to set the schematic results in a NPE. Other items from the mod work fine and this item should be no different to any other, so I cant immediately point out what it could be.

The shematic remains blank after joining back into the server, so I would assume it either crashes before sending the "tick" packet, or it sends it and the server rejects it and sends null NBT back.

Haven't checked whether the item uses metadata or not but I'll get back to that.

http://pastebin.com/GB3C0BVT

**Comment by Paul17041993** [comment]
Is there a way to flush the NBT data of a machine?

**Comment by XFactHD** [comment]
You could use the IngameNBTEdit mod to read the NBT data of the machine. Or if you are really patient, you can search for the particular block in the save files with the help of the NBTExplorer.

**Comment by Paul17041993** [comment]
Or I could just jump into creative, break it and place a fresh one. However I'm asking if there's already a way to flush the machine similar to flushing the schematics.

**Comment by skyboy** [comment]
Update to 4.1.2.
