### ISSUE TITLE
1.12 Auxiliary Sieves not working in Resonant machines

### ISSUE THREAD

**Issue by Zygus42** [CoFH/Feedback#1192]
ThermalExpansion-1.12.2-5.5.0.29-universal
forge-1.12.2-14.23.4.2703-installer-win

I just upgraded all the machines in my base to Resonant, and it would appear that the Auxiliary Sieves are no longer working.  They don't increase the power demand of the machines, and the ratios i'm seeing for secondary outputs is way down on the previous tier of machines and pretty much matches the JEI percentages for the base machine outputs.

Happy to provide more detailed information or testing if you need it.

**Comment by KingLemming** [comment]
This is literally impossible. The code doesn't work that way and it can't happen without the fabric of the universe itself being broken.

Sorry, but you simply aren't correct. There *may* be something else happening, such as another mod breaking things so that augments aren't being properly installed at all. But that's entirely separate and co-incidental.

**Comment by Zygus42** [comment]
Further testing, no mods other than dependencies:
CodeChickenLib-1.12.2-3.2.0.345-universal
CoFHCore-1.12.2-4.5.2.19-universal
CoFHWorld-1.12.2-1.2.0.5-universal
ThermalExpansion-1.12.2-5.5.0.29-universal
ThermalFoundation-1.12.2-2.5.0.19-universal
RedstoneFlux-1.12-2.0.2.3-universal
forge-1.12.2-14.23.4.2703-installer-win

Test Machine: Pulverizer.

No augments, 1 stack of Gold Ore:
                   Power Usage             Pulverized Gold          Cinnabar
Basic:                20                                  128                         7
Hardened:        30                                  128                         9
Reinforced:       40                                  128                         6
Signalum:         50                                  128                         4
Resonant:         60                                  128                       11

Full Augments (Auxillary Sieves), 1 stack of Gold Ore:
                   Power Usage             Pulverized Gold          Cinnabar
Basic:                20                                  128                         9
Hardened:        30                                  128                          7
Reinforced:       40                                  128                        12
Signalum:         50                                  128                        12
Resonant:         60                                  128                       12

Note that power usage has not changed, despite the tooltip on the Auxillary Sieves which clearly states "Additional Energy required per operation".

Note that the amount of Cinnabar has not significantly changed with the Resonant despite the 4 Sieves.

Obviously (for anyone who's studied Statistics anyway), this sample size is too low to draw general conclusions, but have frankly already wasted too much of my time proving a point that you ought to have tested, not just called "impossible".
