### ISSUE TITLE
ThermalDynamics Duct seem to cause crash on server/clients after updating.

### ISSUE THREAD

**Issue by Wissi** [CoFH/Feedback#1194]
Awesome Mod, we love it. Thank you very much for your great work. 
We're updating our server/clients and it _seems_ we have this issue with existing ducts from Thermal Dynamics crashing the server and clients (that have SP worlds w/placed ducts)  after updating to latest versions.

Crash log: https://gist.github.com/Wissi/77cec6a44a0c361770f124dd5f84f729

Old versions: 
CoFHCore-1.12.2-4.3.10.5-universal.jar
CoFHWorld-1.12.2-1.1.1.12-universal.jar
ThermalDynamics-1.12.2-2.3.10.4-universal.jar
ThermalExpansion-1.12.2-5.3.10.15-universal.jar
ThermalFoundation-1.12.2-2.3.10.6-universal.jar

New versions:
CoFHCore-1.12.2-4.5.2.19-universal.jar
CoFHWorld-1.12.2-1.2.0.5-universal.jar
ThermalDynamics-1.12.2-2.5.1.14-universal.jar
ThermalExpansion-1.12.2-5.5.0.29-universal.jar
ThermalFoundation-1.12.2-2.5.0.19-universal.jar

Any help is greatly appreciated. Thank you.

**Comment by KingLemming** [comment]
at org.mcupdater.autopackager.TilePackager.getCapability(TilePackager.java:377)

^ This seems to be either the cause or somehow very related to it.

I wish I had a better answer for you, but I'm very confident that it's not us. Absolutely nothing changed in that portion of the duct code between versions.

**Comment by Wissi** [comment]
Thank you so much for such a quick response. 
I have checked the narrowed down the issue with your very accurate finger pointing to it.
It is definitely another mod.

Again thank you for all your help.

**Comment by KingLemming** [comment]
Quite welcome. :)
