### ISSUE TITLE
[Suggestion] [Thermal Expansion - Creative Strongbox] Allow satchels and strongboxes in creative strongboxes

### ISSUE THREAD

**Issue by planetguy32** [CoFH/Feedback#1194]
I'm using TE 4.1.2-240 - I got it a few months ago, but it's still the version your downloads page points me at.

I wanted to provide an infinite supply of strongboxes using a creative strongbox, but creative strongboxes do not accept other strongboxes or satchels. Could you please allow creative strongboxes to contain container items?

**Comment by KingLemming** [comment]
No, sorry.
