### ISSUE TITLE
COFH World generators not working in nether

### ISSUE THREAD

**Issue by Kyrinon** [CoFH/Feedback#1195]
Other than ore generation (uniform-cluster) I can not get anything to generate in  the nether. I have specifically tried cave-stalagmite and decoration-decoration with see-sky set to false. After it didn't work in my mod pack I isolated the mod with no change. Thank you for your time and an awesome mod set!

**Comment by KingLemming** [comment]
Nope. They do work. Please swing by the Discord for tech support so we can figure out what you're doing wrong.

**Comment by Kyrinon** [comment]
Ok, will do, thanks for the quick response
