### ISSUE TITLE
Update request [1.10.2]

### ISSUE THREAD

**Issue by EnderT5** [CoFH/Feedback#1195]
IC2, Blood Magic, EnderIO and Tinkers' Construct updates to newer versions. Substratum mod becames popular because Thermal Foundation is not updating. NeoTech started being alternative of thermal expansion and dynamics.

My question is:

CoFH mods gonna die or update to newer versions of minecraft?

**Comment by XFactHD** [comment]
First of all, making an "update request" is always bad and mod authors don't really like that.
Secondly, I am certain that updates will come but they will take their time because the Thermal mods are pretty big mods.

**Comment by KingLemming** [comment]
Please don't misuse the issue tracker. It gets old.
