### ISSUE TITLE
[Bug Report] CoFH/thermal dynamics crash report

### ISSUE THREAD

**Issue by StarsPath** [CoFH/Feedback#1196]
Random crashes after mod updates
direct cause of crash: unknown

The vanillaFix mod caught the crash. It was caused by CoFH/ thermal dynamics.
The past 4 crashes that I had are all related to CoFH/ thermal dynamics

Anyways here is the most recent crash files: [crash-2018-07-10_12.12.59-client.txt](https://github.com/CoFH/Feedback/files/2181277/crash-2018-07-10_12.12.59-client.txt)
The earliest crash: [crash-2018-07-09_19.57.33-client.txt](https://github.com/CoFH/Feedback/files/2181296/crash-2018-07-09_19.57.33-client.txt)

**Comment by KingLemming** [comment]
Pretty sure we've seen this before and it's actually another mod entirely - something is screwing up the render pipeline.

Tagging for Covers to take a look.

**Comment by covers1624** [comment]
Can i get a full launch log? This was fixed ages ago, turned out to be a vanilla bug that i submitted a pr for.

**Comment by covers1624** [comment]
Also, you are running CCL 3.2, i have a feature that catches block rendering crashes, enable it in the CCL config.

**Comment by StarsPath** [comment]
Here is the latest launch log: 
[latest.log](https://github.com/CoFH/Feedback/files/2181375/latest.log)

**Comment by covers1624** [comment]
I've looked at the code, forge still has the patch i made, i don't know what else this could be. my best guess is someone is either breaking the patch, or messing with the buffers. Best bet is to remove BetterFPS and VanillaFix / any other mods allong the same lines and see if that fixes the issue.
