### ISSUE TITLE
Binnie's Extra Trees Saplings support?

### ISSUE THREAD

**Issue by Zetharion** [CoFH/Feedback#1197]
The Phytogenic Insolator with the Sapling Infuser Augemnt currently doesnt support saplings frokm Binnies Extra Trees.  Is this something that can be supported on your end or does it need to be added on Binnies side?

Playing FTB Revelations 2 modpack version 2.1.0
Thermal Expansion version:  5.5.0.29
Binnies Extra Trees version: 2.5.0.165

**Comment by KingLemming** [comment]
Sorry, those trees use NBT. Support just isn't possible.
