### ISSUE TITLE
CoFH World zh_CN translation file

### ISSUE THREAD

**Issue by xhz313123** [CoFH/Feedback#1198]
cofhworld.reload.usage=重载CoFHWorld的配置文件
cofhworld.reload.successful=配置文件重载成功。
cofhworld.reload.failed=配置文件重失败;请检查你的日志文件.
cofhworld.list.usage=列出使用CoFHWorld的特性
cofhworld.list=--- 加载CoFHWorld的特性 第 %d 页总共 %d 页---

**Comment by KingLemming** [comment]
Wrong repo but I think I got it.
