### ISSUE TITLE
Request: Use another satchel as a filter

### ISSUE THREAD

**Issue by TheDeviantCrafter** [CoFH/Feedback#1199]
The emerald satchel from Vanilla Satchels can only fit 12 items in the filter. This isn't very many items, especially if you want to use it to pick up ores while mining.

To fix that, I recommend letting you use a satchel as a filter. Place the items you want to filter in the first satchel and then place that satchel in the filter section of another. It will place a ghost item there. The backpack will now pick up any items that are in the filter satchel.

The items will be listed on the tooltip of the satchel. Clicking will open the UI letting you see the items inside. Shift clicking removes it.

**Comment by KingLemming** [comment]
No, sorry. Also, 12 items is substantial when you consider using a blacklist instead of a whitelist. ;)
