### ISSUE TITLE
induction Smelter refined Iron

### ISSUE THREAD

**Issue by OldManCraft** [CoFH/Feedback#1199]
Just updated the FTB skyblock to latest TF and TD.
ThermalFoundation-[1.7.10]1.2.4-114
ThermalDynamics-[1.7.10]1.2.0-171
ThermalExpansion-[1.7.10]4.1.2-240
CoFHCore-[1.7.10]3.1.2-325
CoFHLib-[1.7.10]1.1.1-181

Issue that we ran into is the the Induction Smelter no longer can make refined iron with pulverized coal. It still works with EIO coal dust and IC2 coal dust. Was this done on purpose or a bug. There are no recipes  that alter refined iron in the pack.

**Comment by RalphFox** [comment]
Confirm +1.

just tried pulverized iron with two pulverized coal from thermal expansion and (even hardened) induction smelter does not accept the pulverized coal.  It did accept pulverized charcoal thought.

**Comment by MJRLegends** [comment]
@skyboy Any ETA on when we will get a release to fix this?

**Comment by zhongjiedong** [comment]
Bump, this is kinda annoying :P

**Comment by skyboy** [comment]
Everyone asking extends the release date 2 weeks.
