### ISSUE TITLE
Dynamics with newest releases?

### ISSUE THREAD

**Issue by DeadSix27** [CoFH/Feedback#12]
(Talking about 1.10)

I've been playing with own builds of master for a bit now (Mainly to help test and 'cuz I like to)
What's the deal with dynamics requiring thermalfoundation 1.3.0-1.4.0? (_Missing Mods: thermalfoundation : [1.3.0,1.4.0)_)

I tried looking through your repos but couldn't find the slightest mention of "1.3.0" anywhere in dynamics-source. (If I could I would have just changed that version tag.. to make it work)

Can you point me in the right direction?

(In the compiled main ThermalDynamics class I can see `required-after:thermalfoundation@[1.3.0,1.4.0)`
however in the source there is no mention of it..
```
public static final String VERSION = "2.0.0";
public static final String VERSION_MAX = "2.1.0";
String VERSION_GROUP = "required-after:" + MOD_ID + "@[" + VERSION + "," + VERSION_MAX + ");";
```
Only 2 - 2.1

(Same thing happens with RA from master, wants 1.3.0 too)

**Comment by KingLemming** [comment]
Dynamics has not been released yet.

**Comment by DeadSix27** [comment]
@KingLemming did you read the entire post?

**Comment by KingLemming** [comment]
I did, and basically you're filing a bug report about a mod that isn't out yet. The compile scripts work against a Maven, which may or may not be outdated depending on when you compile.

That's all that's going on here.

**Comment by DeadSix27** [comment]
@KingLemming Alright, was just wondering.

**Comment by KingLemming** [comment]
Sorry, I'm a little touchy about it because some people have deigned to compile and release the mods early on their own terms. That's kind of upset me a bit.

Basically if you compile everything fresh, that shouldn't happen.

**Comment by DeadSix27** [comment]
@KingLemming 
:) It's alright, you did apologize that makes me feel less bad for asking that right in the release stress. 

About the hint: I will compile it all fresh again, all tho I think I did try that already.. but ill check again just to be sure.

**Comment by DeadSix27** [comment]
@KingLemming Just wanted to let you know, it was a odd caching issue on my jenkins server.. No clue how that happened.. but wiping the entire cache folder and manually telling it to rebuild everything made it work fine.

Thanks for your time again :)

**Comment by DeadSix27** [comment]
@KingLemming any chance you'll make dynamics compile with newest cofh core for private use? Currently requires older cofh while the other mods want a newer
