### ISSUE TITLE
[Thermal Foundation 1.10] Minor bug: Recipe mixup with Aluminum and Lead Nuggets

### ISSUE THREAD

**Issue by Doomathon** [CoFH/Feedback#120]
Expected Behavior: I should be able to craft 1 Aluminium Ingot into 9 Aluminium Nuggets.
Actual Behavior: The recipe outputs 9 lead nuggets instead. Aluminium Nuggets are uncraftable.

I'm working around this with CraftTweaker for now, so it's low priority for me, but hadn't seen a report of this yet.

**Comment by KingLemming** [comment]
I *really* wish you'd mentioned this sooner.

**Comment by KingLemming** [comment]
Redownload TF when it comes up. Build 80. I'm not updating the version number for this. But in the future, please please just report bugs when you know about them.

**Comment by Doomathon** [comment]
Sadly, I only noticed it today while doing some sanity checks on crafting recipes (mostly involving other mods' nuggets) in my personal mod pack. If little things can slip past the mod devs themselves, they can often just as easily slip past modpack builders :/

**Comment by KingLemming** [comment]
Oh fair enough. I read your post as stating that you had been working around it. Like, for a long time.
