### ISSUE TITLE
Autonomous Activators attempt to attack/left-click intangible entities.

### ISSUE THREAD

**Issue by Mysteryem** [CoFH/Feedback#120]
Reading http://www.reddit.com/r/feedthebeast/comments/2w4fdj/autonomous_activators_bugged_in_dire_17/ I think I know why people often find that their autonomous activators stop attacking mobs, that reason being that the autonomous activators will attempt to left-click entities that are normally intangible to the player.

The usual culprits for stopping auto mob grinders from working are dropped items, Thaumcraft's aspect orbs or arrows shot into the AA (e.g. skeleton grinder). Presumably experience orbs are a problem as well, but they have a tendency to fly everywhere and are attracted to the player, so difficult to screenshot.

For reference, I'm using ThermalExpansion-[1.7.10]4.0.0B8-23 in the Direwolf 20 1.7 pack (v1.0.3) in single player. The issue was also in 1.6.4 with ThermalExpansion-3.0.0.7 (TPPI pack).

Aspect orb is in the way somehow
![Aspect orb is in the way](http://imgkk.com/i/ku-k.png)

Aspect orb has despawned (AA has Tinkers' construct bane of pigs in it)
![Aspect orb has despawned](http://imgkk.com/i/e798.png)

Similar thing with an item being in the way. As soon as I pick up the item, the AA kills the zombie pigman.
![Similar thing with an item being in the way](http://imgkk.com/i/hj_b.png)

**Comment by skyboy** [comment]
Fixed in dev

**Comment by KingLemming** [comment]
As mentioned in the other issue, thanks again for the detailed report. Glad to have cleared that up.
