### ISSUE TITLE
Client can't enter the server after installing Forestry

### ISSUE THREAD

**Issue by Lambda-incraft** [CoFH/Feedback#1200]
Using build 57, also tried build 56
The client reports "Fatally missing blocks and items"
And server shows: 
Client attempting to join with 84 mods : gregtech@MC1710,MineFa
ctoryReloaded|CompatForgeMicroblock@1.7.10R2.8.0,DynamicLights_dropItems@1.0.8,B
uildCraft|Robotics@7.0.19,AS_UpdateCheck@1.1.6,DynamicLights_flameArrows@1.0.0,B
iblioCraft@1.10.5,MineFactoryReloaded|CompatRailcraft@1.7.10R2.8.0,MineFactoryRe
loaded|CompatMystcraft@1.7.10R2.8.0,TwilightForest@2.3.5,BuildCraft|Transport@7.
0.19,WailaHarvestability@1.1.2,mcp@9.05,RotaryCraft@1.0,NEIAddons|Forestry@1.12.
10.33,DynamicLights_otherPlayers@1.0.8,NEIAddons|CraftingTables@1.12.10.33,NEIAd
dons|ExNihilo@1.12.10.33,DamageIndicatorsMod@3.2.3,InputFix@1.7.10-v5,Forestry@4
.2.14.62,TConstruct@1.7.10-1.6.0.build611,FastCraft@1.21,<CoFH ASM>@000,<DragonA
PI ASM>@0,MineFactoryReloaded|CompatAtum@1.7.10R2.8.0,appliedenergistics2@rv2-st
able-8,DragonAPI@1.0,CodeChickenCore@1.0.7.46,MineFactoryReloaded|CompatThermalE
xpansion@1.7.10R2.8.0,BuildCraft|Energy@7.0.19,Railcraft@9.7.0.0,appliedenergist
ics2-core@rv2-stable-8,ThermalDynamics@1.7.10R1.1.0,NEIAddons@1.12.10.33,Dynamic
Lights_entityClasses@1.0.1,DynamicLights@1.3.8,Waila@1.5.10,CoFHCore@1.7.10R3.0.
3,MineFactoryReloaded|CompatAppliedEnergistics@1.7.10R2.8.0,Mineshot@v1.61-1.7.1
0,MineFactoryReloaded@1.7.10R2.8.0,journeymap@5.1.4p1,uniskinmod@1.2-dev4,Therma
lExpansion@1.7.10R4.0.3B1,ProfilerEvents@1.0,ArmorStatusHUD@1.28,MineFactoryRelo
aded|CompatBackTools@1.7.10R2.8.0,MineFactoryReloaded|CompatProjRed@1.7.10R2.8.0
,inventorytweaks@1.59-dev-152-cf6e263,DynamicLights_onFire@1.0.4,BuildCraft|Sili
con@7.0.19,MineFactoryReloaded|CompatIC2@1.7.10R2.8.0,DynamicLights_mobEquipment
@1.0.8,MineFactoryReloaded|CompatVanilla@1.7.10R2.8.0,NEIAddons|AppEng@1.12.10.3
3,MineFactoryReloaded|CompatThaumcraft@1.7.10R2.8.0,FML@7.10.99.99,BuildCraft|Co
re@7.0.19,NEIAddons|Botany@1.12.10.33,NotEnoughItems@1.0.5.120,MouseTweaks@2.4.4
,IC2@2.2.749-experimental,MineFactoryReloaded|CompatExtraBiomes@1.7.10R2.8.0,nei
integration@1.1.2,Mantle@1.7.10-0.3.1.jenkins180,LunatriusCore@1.1.2.21,DynamicL
ights_creepers@1.0.4,MineFactoryReloaded|CompatChococraft@1.7.10R2.8.0,DynamicLi
ghts_thePlayer@1.1.4,DynamicLights_floodLights@1.0.2,MineFactoryReloaded|CompatT
wilightForest@1.7.10R2.8.0,BuildCraft|Factory@7.0.19,Forge@10.13.4.1614,MineTwea
ker3@3.0.10,BigReactors@0.4.3A,MineFactoryReloaded|CompatBuildCraft@1.7.10R2.8.0
,bspkrsCore@6.16,MineFactoryReloaded|CompatForestry@1.7.10R2.8.0,OpenEye@0.6,Min
eFactoryReloaded|CompatSufficientBiomes@1.7.10R2.8.0,BuildCraft|Builders@7.0.19,
MineFactoryReloaded|CompatTConstruct@1.7.10R2.8.0,ThermalFoundation@1.7.10R1.2.0
Attempting connection with missing mods [kimagine] at CLIENT
 jewelspetblu lost connection: Disconnected
In the client latest.log,it shows
[Netty Client IO #1/INFO]: Injecting existing block and item data into this client instance
[Netty Client IO #1/INFO]: Found a missing id from the world Forestry:fluid.milk
[Netty Client IO #1/INFO]: Found a missing id from the world Forestry:canOil
[Netty Client IO #1/INFO]: Found a missing id from the world Forestry:refractoryFuel
[Netty Client IO #1/INFO]: Found a missing id from the world Forestry:canFuel
[Netty Client IO #1/INFO]: Found a missing id from the world Forestry:fluid.milk
[Netty Client IO #1/INFO]: Found a missing id from the world Forestry:waxCapsuleFuel
[Netty Client IO #1/INFO]: Found a missing id from the world Forestry:waxCapsuleOil
[Netty Client IO #1/INFO]: Found a missing id from the world Forestry:refractoryOil
[Netty Client IO #0/ERROR]: Failed to connect to server: there are 8 missing blocks and items
Just tell me how to fix it. thx.

**Comment by XFactHD** [comment]
This has nothing to do with CoFH mods, the blocks and items are all from Forestry.
