### ISSUE TITLE
Disabling Thermal Expansion machines, still show recipes in the JEI categories.

### ISSUE THREAD

**Issue by Axieum** [CoFH/Feedback#1201]
Disabling a Thermal Expansion machine (and upgrades) still shows that you can use the machine to obtain other resources upon viewing recipes. Perhaps disable the JEI Category should the machine be disabled?

**Comment by KingLemming** [comment]
No, sorry.

It used to do this, and then people complained, so I changed it to what it is now. I'm not doing tug-of-war changes.

**Comment by Axieum** [comment]
I understand, but if there's two ends of the spectrum, shouldn't be too hard to add a configuration option; then everyone gets their way.

Just super confusing in my pack, when you click on how to get something and it shows you an - literally - impossible recipe.

**Comment by KingLemming** [comment]
It's not that simple. "Add a config," isn't a magic solution. There are sync issues with JEI, and this is something that could be done on a per-client as well as per-login basis.

**Comment by Axieum** [comment]
Okay, I understand. Would you happen to know a way to list all the recipes for each machine so I can remove them with CraftTweaker/ModTweaker?

Since the command noted on this [modtweaker wiki](http://minetweaker3.powerofbytes.com/wiki/ModTweaker:Thermal_Expansion_Support) page does not seem to be in my 1.12.2 instance

**Comment by serialtasted** [comment]
**For future reference!** This function will hide the category from JEI (the tab when seeing recipes). This are all the categories for Thermal Expansion (as of today). 
To check more categories do:
>  /ct jeiCategories

```
import mods.jei.JEI.hideCategory as hc;

var categoriesToHide as string[] = [
	"thermalexpansion.furnace",
	"thermalexpansion.furnace_food",
	"thermalexpansion.furnace_ore",
	"thermalexpansion.furnace_pyrolysis",
	"thermalexpansion.pulverizer",
	"thermalexpansion.pulverizer_petrotheum",
	"thermalexpansion.sawmill",
	"thermalexpansion.sawmill_tapper",
	"thermalexpansion.smelter",
	"thermalexpansion.smelter_pyrotheum",
	"thermalexpansion.insolator",
	"thermalexpansion.insolator_tree",
	"thermalexpansion.compactor",
	"thermalexpansion.compactor_mint",
	"thermalexpansion.compactor_gear",
	"thermalexpansion.crucible",
	"thermalexpansion.crucible_lava",
	"thermalexpansion.refinery",
	"thermalexpansion.refinery_fossil",
	"thermalexpansion.refinery_potion",
	"thermalexpansion.transposer_fill",
	"thermalexpansion.transposer_extract",
	"thermalexpansion.charger",
	"thermalexpansion.centrifuge",
	"thermalexpansion.centrifuge_mobs",
	"thermalexpansion.brewer",
	"thermalexpansion.enchanter",
	"thermalexpansion.precipitator",
	"thermalexpansion.extruder",
	"thermalexpansion.extruder_sedimentary",
	"thermalexpansion.steam",
	"thermalexpansion.magmatic",
	"thermalexpansion.compression",
	"thermalexpansion.reactant",
	"thermalexpansion.reactant_elemental",
	"thermalexpansion.enervation",
	"thermalexpansion.numismatic",
	"thermalexpansion.numismatic_gem",
	"thermalexpansion.factorizer_combine",
	"thermalexpansion.factorizer_split",
	"thermalexpansion.coolant"
];

for category in categoriesToHide {
	hc(category);
}
```
