### ISSUE TITLE
[Thermal Foundation 1.2.4]New tools compatibility problem with EnderCore

### ISSUE THREAD

**Issue by tytannial** [CoFH/Feedback#1202]
Since I updated TF 1.2.3 to 1.2.4. There are too many tools made by vanilla minecraft materials  :joy: . This problem only appears vanilla minecraft material tools.
![20160709103934](https://cloud.githubusercontent.com/assets/11215623/16705608/2d2072e6-45c2-11e6-8b1d-1b5d9cc1c1ba.png)

Forge 1614 for 1.7.10
Mod list:
CodeChickenCore-1.7.10-1.0.7.47-universal
NotEnoughItems-1.7.10-1.0.5.120-universal
CoFHCore-[1.7.10]3.1.2-325
ThermalFoundation-[1.7.10]1.2.4-114
EnderCore-1.7.10-0.2.0.36_beta

This is EnderCore config. This feature has compatibility problem with TF vanilla minecraft material tools and no problem with TF material tools.
![20160709104931](https://cloud.githubusercontent.com/assets/11215623/16705660/f0700806-45c2-11e6-9bbb-c5e72ba1fe7a.png)

**Comment by skyboy** [comment]
The new tools are identical to the old tools (literally - they don't have new classes, just different texture and stats, same code), so this has to be an issue in EnderCore.

**Comment by tytannial** [comment]
Thanks, I will get touch with them.
