### ISSUE TITLE
Still having nullpointexception crash

### ISSUE THREAD

**Issue by Amintie** [CoFH/Feedback#1203]
Hello, I was trying to put together some mods to not be over the top and really want to use mfr but i crash every time. i looked and could not find a fix for this. "The game crashed whilst initializing game
Error: java.lang.NullPointerException: Initializing game" is what i get. any help would be great.

**Comment by KingLemming** [comment]
Please go to the discord. The link is on our website. There is a tech support channel for stuff like this.
