### ISSUE TITLE
[Thermal Dynamics] Server crash at startup

### ISSUE THREAD

**Issue by kerts93** [CoFH/Feedback#1204]
https://openeye.openmods.info/crashes/9e66b74d4379c4418c0dbc0d795d351e

We have a problem that server won't start up since last night. I imagine there is some kind of incompatiblity between some mod and TD.

As the map is big and we have a lot of players and error does not give any location, we are unable to determine what is causing this.

**Comment by kerts93** [comment]
It looks like server starts up when Storage Drawers is taken out so I guess that is where the issue lies.

**Comment by kerts93** [comment]
https://github.com/jaquadro/StorageDrawers/issues/309

**Comment by kerts93** [comment]
When taking the world to Singleplayer, we recive the same issue:
https://openeye.openmods.info/crashes/b85c66c530b91e1008cc4d7fca846286

We have an idea that it could be TD servos trying to take items out of empty drawers

**Comment by KingLemming** [comment]
According to that crash, it's simply a matter of Storage Drawers being incorrectly coded.

It basically goes like this:

Servo: "How many slots do you have?"
Drawer: "I have 4 slots."
Servo: "Okay, I'm going to pull the thing out of slot 4."
"Drawer: "What I don't have 4 slots lol, I'm going to crash the game now."

So yeah. Better let them know.
