### ISSUE TITLE
Crash on using a viaduct to go somewhere

### ISSUE THREAD

**Issue by mattfreyer** [CoFH/Feedback#1205]
I crash when trying to enter the viaduct system its to do with Ars Magica 2 wasn't sure if I should report here or there but since it was an interaction with your mod I thought this is.

Click on the viaduct and choose destination with Ars Magica 2 installed. 
ThermalDynamics 1.7.10 1.2.0-17
CoFHCore 1.7.10 3.1.2-325
Ars Magica 2 1.7.10_AM2-1.4.0.009.jar 
http://pastebin.com/cVNvuv1K

**Comment by KingLemming** [comment]
It's on their end. They have some sort of entity construction thing going on there that seems to be erroring out.

**Comment by mattfreyer** [comment]
Nvm it was on Hardcore Ender Expansion was simple config option thanks for your time.
