### ISSUE TITLE
Disabled machines/augments still show in JEI

### ISSUE THREAD

**Issue by Golrith** [CoFH/Feedback#1206]
When disabling any machine/augment in the config, JEI still shows tabs for that machine/augment when looking at recipes, giving a false impression that the machine or augment is actually available.

**Comment by KingLemming** [comment]
Yes, because disabling it disables the recipe, not the entire machine. The config clearly states that.

This functionality is provided as an easy way to allow modpack creators to limit how the machine can be obtained.
