### ISSUE TITLE
crash ??

### ISSUE THREAD

**Issue by runescapejon** [CoFH/Feedback#1206]
When i place down a Tesseract and right click it i crash the server here is the crash report 
http://hastebin.com/ewanekiwoz.coffee

**Comment by KingLemming** [comment]
Yeah you have a mod breakin things that isn't us. It's including parts of the API it shouldn't be and it's getting all screwed up.

**Comment by runescapejon** [comment]
do you know which mod ?

**Comment by skyboy** [comment]
We do not. You can only make an instance with just the CoFH mods then add others until it crashes.

**Comment by runescapejon** [comment]
i found it, its buildcraft mod
