### ISSUE TITLE
my client (1.7.10) hangs for minutes at a time with certain particle effects

### ISSUE THREAD

**Issue by LAX1DUDE** [CoFH/Feedback#1207]
Java Mission Control reveals it has something to do with cofhcore https://gyazo.com/60e35c2afb1e7de84cd0c734ea9217f3 doing collision checks. I'm using minecraft 1.7.10 with the newest cofh mods

**Comment by KingLemming** [comment]
Mission Control also reveals DragonAPI, and a bunch of other things.

Also, 1.7.10 is totally unsupported at this point. Please play 1.12.2.
