### ISSUE TITLE
Crash with Forge 2739+...ANSWER: UPDATE COFHCORE!!! DO NOT COME HERE AND POST WITHOUT UPDATING.

### ISSUE THREAD

**Issue by MineProjectZ** [CoFH/Feedback#1208]
I installed the newest version of Thermal Foundation and the other thermal mods via curse. But when i start the modpack i get a strange crash, that says that a class file from cofhcore is missing: https://pastebin.com/1jQfKynH

**Comment by MineProjectZ** [comment]
The error can be fixed by downgrading forge.

**Comment by nick-johnson** [comment]
Issue seems to be with forge-14.23.4.2739 specifically?

**Comment by MineProjectZ** [comment]
yes, older forge versions works fine.

**Comment by covers1624** [comment]
This is a forge bug. @mezz https://github.com/MinecraftForge/MinecraftForge/pull/4763 has breaking changes.

**Comment by covers1624** [comment]
Actually seems to be due to CoFHCore adding its own getter for density, but one now exists in forge.

**Comment by TheSnowyChickens** [comment]
This: https://paste.dimdev.org/ohidimigoc.mccrash is the same, I think. :)

**Comment by KingLemming** [comment]
Sure is. Downgrade Forge.

**Comment by covers1624** [comment]
Moved placeholder issue here: https://github.com/CoFH/Feedback/issues/1289
