### ISSUE TITLE
Autonomous Activators that are rotated while breaking a block become unable to break other blocks.

### ISSUE THREAD

**Issue by Mysteryem** [CoFH/Feedback#121]
For reference, this is occuring in ThermalExpansion-[1.7.10]4.0.0B8-23 in the Direwolf 20 1.7 pack (v1.0.3) in my single player, creative test world.

Rotating an AA (with crescent hammer right click) while it is breaking a block will result in it glitching out and being unable to break other blocks. Either rotating the AA back so it is facing the block it was breaking originally or breaking that block yourself or through other means, will fix the AA's behaviour.

Interestingly, the AA appears to continue mining the original block when given another block to break after being rotated, continuing the block breaking animation, but not breaking the block, resulting in the block instantly breaking if the AA is rotated back round to it and the block breaking animation had completed.

The AA is still capable of attacking entities when in this state.

Edit: Forgot to add, quitting and reloading the world(save) fixes this bugged state, haven't checked reloading of the chunk, I would guess it would be the same.

AA mining away on the wrong block (it was facing the stone originally)
![AA mining away on the wrong block](http://imgkk.com/i/ndel.png)

Eventually the block breaking effect disappears
![Eventually the block breaking effect disappears](http://imgkk.com/i/51c-.png)

**Comment by skyboy** [comment]
Fixed in dev

**Comment by KingLemming** [comment]
Just wanted to add - thank you for the really detailed report!
