### ISSUE TITLE
Crashing Server [loop missing mods CoFHCore : [1.7.10R3.0.0RC1,)] (but cofh core is in mods folder)

### ISSUE THREAD

**Issue by zarzwour** [CoFH/Feedback#1210]
whenever i try to run my server i get this error

---- Minecraft Crash Report ----
// Ouch. That hurt :(

Time: 7/13/16 4:12 PM
Description: Exception in server tick loop

Missing Mods:
	CoFHCore : [1.7.10R3.0.0RC1,)

but i have the latest version oc CoFH core in my mods folder i tried removing all of the mods i thought required it and it still says that error someone please help me
the full error report is below

---- Minecraft Crash Report ----
// Ouch. That hurt :(

Time: 7/13/16 4:12 PM
Description: Exception in server tick loop

Missing Mods:
	CoFHCore : [1.7.10R3.0.0RC1,)

cpw.mods.fml.common.MissingModsException
	at cpw.mods.fml.common.Loader.sortModList(Loader.java:241)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:491)
	at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:87)
	at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:318)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:176)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:620)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_91, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3944210568 bytes (3761 MB) / 5145362432 bytes (4907 MB) up to 5145362432 bytes (4907 MB)
	JVM Flags: 2 total; -Xms5G -Xms5G
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.114.1388 Minecraft Forge 10.13.3.1403 73 mods loaded, 73 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded
	FML{7.10.114.1388} [Forge Mod Loader] (cauldron-1.7.10-2.1403.1.54-server.jar) Unloaded
	Forge{10.13.3.1403} [Minecraft Forge] (cauldron-1.7.10-2.1403.1.54-server.jar) Unloaded
	appliedenergistics2-core{rv2-stable-10} [AppliedEnergistics2 Core] (minecraft.jar) Unloaded
	ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core] (minecraft.jar) Unloaded
	OpenModsCore{0.9.1} [OpenModsCore] (minecraft.jar) Unloaded
	Treecapitator{1.7.10} [Treecapitator] ([1.7.10]Treecapitator-universal-2.0.4 (1).jar) Unloaded
	appliedenergistics2{rv2-stable-10} [Applied Energistics 2] (appliedenergistics2-rv2-stable-10.jar) Unloaded
	Backpack{2.0.1} [Backpack] (backpack-2.0.1-1.7.x.jar) Unloaded
	betterrecords{@VERSION@} [Better Records] (BetterRecords-1.7.10-1.2.0.jar) Unloaded
	BiblioCraft{1.11.4} [BiblioCraft] (BiblioCraft[v1.11.4][MC1.7.10].jar) Unloaded
	AWWayofTime{v1.3.3} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.7.10-1.3.3-17 (1).jar) Unloaded
	bookshelf{1.0.4.187} [Bookshelf] (Bookshelf-1.7.10-1.0.4.187.jar) Unloaded
	BuildCraft|Builders{7.1.16} [BC Builders] (buildcraft-7.1.16.jar) Unloaded
	BuildCraft|Transport{7.1.16} [BC Transport] (buildcraft-7.1.16.jar) Unloaded
	BuildCraft|Energy{7.1.16} [BC Energy] (buildcraft-7.1.16.jar) Unloaded
	BuildCraft|Silicon{7.1.16} [BC Silicon] (buildcraft-7.1.16.jar) Unloaded
	BuildCraft|Robotics{7.1.16} [BC Robotics] (buildcraft-7.1.16.jar) Unloaded
	BuildCraft|Core{7.1.16} [BuildCraft] (buildcraft-7.1.16.jar) Unloaded
	BuildCraft|Factory{7.1.16} [BC Factory] (buildcraft-7.1.16.jar) Unloaded
	CarpentersBlocks{3.3.5} [Carpenter's Blocks] (Carpenter's Blocks v3.3.5 - MC 1.7.10.jar) Unloaded
	chisel{2.9.5.11} [Chisel] (Chisel-2.9.5.11.jar) Unloaded
	darkcore{0.3} [Dark Core] (darkcore-0.3-86.jar) Unloaded
	PTRModelLib{1.0.0} [PTRModelLib] (Decocraft-2.3.2_1.7.10.jar) Unloaded
	props{2.3.2} [Decocraft] (Decocraft-2.3.2_1.7.10.jar) Unloaded
	debug{1.0} [debug] (denseores-1.6.2.jar) Unloaded
	denseores{1.0} [Dense Ores] (denseores-1.6.2.jar) Unloaded
	EnderIO{1.7.10-2.2.8.381} [Ender IO] (EnderIO-1.7.10-2.2.8.381.jar) Unloaded
	extracells{2.3.14} [Extra Cells 2] (ExtraCells-1.7.10-2.3.14b197.jar) Unloaded
	ExtraUtilities{1.2.12} [Extra Utilities] (extrautilities-1.2.12.jar) Unloaded
	FoodPlus{3.0rS} [Food Plus] (Food-Plus-Mod-1.7.10.jar) Unloaded
	ForbiddenMagic{1.7.10-0.572} [Forbidden Magic] (Forbidden Magic-1.7.10-0.572.jar) Unloaded
	gadomancy{1.0.7.2} [Gadomancy] (gadomancy-1.7.10-1.0.7.2.jar) Unloaded
	ImmersiveEngineering{0.7.7} [Immersive Engineering] (ImmersiveEngineering-0.7.7.jar) Unloaded
	ImmibisCore{59.1.4} [Immibis Core] (immibis-core-59.1.4.jar) Unloaded
	ImmibisMacroblocks{59.1.1} [Immibis's Macroblocks] (immibis-macroblocks-59.1.1.jar) Unloaded
	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) Unloaded
	MineFactoryReloaded{1.7.10R2.8.0RC7} [MineFactory Reloaded] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded
	MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.0RC7} [MFR Compat: Applied Energistics] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded
	MineFactoryReloaded|CompatAtum{1.7.10R2.8.0RC7} [MFR Compat: Atum] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded
	MineFactoryReloaded|CompatBackTools{1.7.10R2.8.0RC7} [MFR Compat: BackTools] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded
	MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.0RC7} [MFR Compat: BuildCraft] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded
	MineFactoryReloaded|CompatChococraft{1.7.10R2.8.0RC7} [MFR Compat: Chococraft] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded
	MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.0RC7} [MFR Compat: ExtraBiomes] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded
	MineFactoryReloaded|CompatForestry{1.7.10R2.8.0RC7} [MFR Compat: Forestry] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded
	MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.0RC7} [MFR Compat: ForgeMicroblock] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded
	MineFactoryReloaded|CompatIC2{1.7.10R2.8.0RC7} [MFR Compat: IC2] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded
	MineFactoryReloaded|CompatMystcraft{1.7.10R2.8.0RC7} [MFR Compat: Mystcraft] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded
	MineFactoryReloaded|CompatProjRed{1.7.10R2.8.0RC7} [MFR Compat ProjectRed] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded
	MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.0RC7} [MFR Compat: Railcraft] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded
	MineFactoryReloaded|CompatRP2{1.7.10R2.8.0RC7} [MFR Compat: RP2] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded
	MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.0RC7} [MFR Compat: Sufficient Biomes] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded
	MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.0RC7} [MFR Compat: Thaumcraft] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded
	MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.0RC7} [MFR Compat: Thermal Expansion] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded
	MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.0RC7} [MFR Compat: Tinkers' Construct] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded
	MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.0RC7} [MFR Compat: TwilightForest] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded
	MineFactoryReloaded|CompatVanilla{1.7.10R2.8.0RC7} [MFR Compat: Vanilla] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded
	OpenBlocks{1.5.1} [OpenBlocks] (OpenBlocks-1.7.10-1.5.1.jar) Unloaded
	OpenMods{0.9.1} [OpenMods] (OpenModsLib-1.7.10-0.9.1.jar) Unloaded
	harvestcraft{1.7.10j} [Pam's HarvestCraft] (Pam's HarvestCraft 1.7.10La.jar) Unloaded
	PneumaticCraft{1.12.7-150} [PneumaticCraft] (PneumaticCraft-1.7.10-1.12.7-150-universal.jar) Unloaded
	ProjectE{1.7.10-PE1.10.0} [ProjectE] (ProjectE-1.7.10-PE1.10.0.jar) Unloaded
	Railcraft{9.12.2.0} [Railcraft] (Railcraft_1.7.10-9.12.2.0.jar) Unloaded
	SolarExpansion{1.6a} [Solar Expansion] (SolarExpansion-Basic-1.6a.jar) Unloaded
	TardisMod{0.994} [Tardis Mod] (tardismod-1.7.10-0.994-124-DS.jar) Unloaded
	TConstruct{1.7.10-1.8.8.build988} [Tinkers' Construct] (TConstruct-1.7.10-1.8.8.jar) Unloaded
	Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar) Unloaded
	ThaumicHorizons{1.1.9} [Thaumic Horizons] (thaumichorizons-1.7.10-1.1.9 (1).jar) Unloaded
	ThaumicTinkerer{unspecified} [Thaumic Tinkerer] (ThaumicTinkerer-2.5-1.7.10-164.jar) Unloaded
	TwilightForest{2.3.7} [The Twilight Forest] (twilightforest-1.7.10-2.3.7.jar) Unloaded
	witchery{0.24.1} [Witchery] (witchery-1.7.10-0.24.1 (1).jar) Unloaded
	bspkrsCore{6.16} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.16.jar) Unloaded
	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) Unloaded
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'cauldron,craftbukkit,mcpc,fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by zarzwour** [comment]
i can see thermal expansion stuff in their so i removed minefactoryreloaded and it still does this. i literlaly removed every mod expect cofh core and it still gives me this god **** error!

**Comment by zarzwour** [comment]
i fixed it but i would still like to know what was happening because i am dumbfounded on how i fixed it.

**Comment by KingLemming** [comment]
Yeah this is just something you did. The mod list clearly shows that it was NOT in the mods folders.

Also, that version is WAAAAAY out of date. You should update.

**Comment by zarzwour** [comment]
it was thats the thing

**Comment by zarzwour** [comment]
it was thats the thing!
