### ISSUE TITLE
Thermal Expansion Factorizer allowing reversal of Natura cloud -> charcoal recipe

### ISSUE THREAD

**Issue by FakoTheGreat** [CoFH/Feedback#1211]
Minecraft Version: 1.12.2
Modlist: [here](https://pastebin.com/a4skfLH9)
Images: [here](https://imgur.com/a/yPYzjge)

Description:

Natura's Ash Clouds can be converted into charcoal using a 3x3 recipe (9 clouds -> 1 charcoal), but the reverse normally is not true.  However, a Factorizer set to Split mode will turn charcoal into clouds.  While this is an exceptionally tame "issue", I am bringing this up in case there are other 3x3 -> 1 recipes in other mods that aren't intended to be reversed, just to be safe.

Thank you for your time, and for providing such a wonderful series of mods!

**Comment by KingLemming** [comment]
This shouldn't be too hard to handle.

**Comment by KingLemming** [comment]
Merging into #1254, may happen as part of rework.
