### ISSUE TITLE
Should Blizzes be invisible?

### ISSUE THREAD

**Issue by CoolSkeleton97** [CoFH/Feedback#1212]
Alright, so, I'm running Thermal Foundation 1.2.3. I have encountered Blizzes only twice as of now. Both times, they were invisible and annoying as heck. Two questions: Are Blizzes SUPPOSED to be invisible? If not, is this bug fixed in 1.2.4? I appreciate any feedback you wonderful people could give me. Have a spectacular experience.

**Comment by skyboy** [comment]
Sounds like some form of conflict. Try just Thermal Foundation in its own instance and see if they're still invisible.

**Comment by KingLemming** [comment]
They're not supposed to be, nor are they with only CoFH mods installed. You have a conflict.

**Comment by skyboy** [comment]
Closing this as a mod conflict.
