### ISSUE TITLE
Thermal Foundation elementals cause aggro on Creepers

### ISSUE THREAD

**Issue by TheLEGObrick** [CoFH/Feedback#1213]
Basically, it seems like that Creepers getting hit by TF elementals' projectiles will aggro towards the said elemental, causing the Creeper to come after the elemental and explode, potentially causing collateral damage to surroundings.

I'm not entirely sure, but I think that the only vanilla entity Creepers attack under any circumstances, is players, so the aforementioned behaviour seems strange?

**Comment by KingLemming** [comment]
Working as intended. This is vanilla Minecraft at work. If a skeleton hits one with an arrow, it will also aggro.

**Comment by TheLEGObrick** [comment]
It does? I thought that it used to do that in earlier versions of the game but... I guess it was never removed. Alright, well, I suppose I just didn't remember how it works in vanilla
