### ISSUE TITLE
(TF)Blitz and Basalz have not translated in zh-CN yet

### ISSUE THREAD

**Issue by ShiningBRS** [CoFH/Feedback#1213]
I didn't find where to submit translate,so I think they should be translated as:
Blitz--闪电
Basalz--幽冥
(My English is not so good,please forgive)

**Comment by KingLemming** [comment]
This should be handled through PRs, but I'll make sure they go in anyways.

**Comment by skyboy** [comment]
For future reference, PRs for Thermal Foundation's language files can be done on the Thermal Foundation repo: https://github.com/CoFH/ThermalFoundation/tree/master/src/main/resources/assets/thermalfoundation/lang
