### ISSUE TITLE
Arboreal Extractor not working with Dynamic Trees

### ISSUE THREAD

**Issue by Mantic** [CoFH/Feedback#1216]
I'm using [Dynamic Trees](https://minecraft.curseforge.com/projects/dynamictrees) and can't seem to get arboreal extractors to work with these dynamic trees. I've tried growing the trees w/ bone meal, placing wood down to "create" a tree, etc. but nothing really works. Dynamic trees really adds to the world, IMHO, it'll suck to have to cut that mod. :/ 

Any suggestions?

**Comment by KingLemming** [comment]
Sorry, just isn't compatible. :/

**Comment by Mantic** [comment]
Gotcha, drats. :P Thanks for the quick input!
