### ISSUE TITLE
[Thermal Dynamics (1.7.10) 1.2.0-171 crashes with Shaders mod

### ISSUE THREAD

**Issue by JFMillerUSA** [CoFH/Feedback#1217]
Shaders Mod v2.3.31 Forge Edition for Minecraft 1.7.10

[mod list](http://pastebin.com/raw/k1RcUWmY)
[crash log](http://pastebin.com/raw/Xbf65EUW)

Before it started crashing game the duct covers had a graphical clitch. I would like to be able to use both mods but taking off shaders makes game not crash.

**Comment by KingLemming** [comment]
Sorry, this is completely on them to fix.

**Comment by skyboy** [comment]
Thermal Dynamics 1.2 has the ability to co-function with shader mods, if the shader mod uses reflection to change the value of the static field `cofh.thermaldynamics.duct.attachments.cover.CoverRenderer.VERTEX_SIZE` to the new size of the shader mod's vertices .

**Comment by ferreusveritas** [comment]
I whipped up a mod to do exactly that.

http://minecraft.curseforge.com/projects/thermalshade

Hope it helps.  Let me know how it goes :)

I researched the issue for the past couple of days and I have a good understanding of the problem and other possible solutions if anyone is interested.  Nothing but love for the cofh team. :)
