### ISSUE TITLE
Can't make fluxducts!

### ISSUE THREAD

**Issue by Bishop435** [CoFH/Feedback#1219]
I have CoFH core, thermal dynamics and thermal foundation installed. The red stone energy fluxducts (empty) are shown in NEI but do not have recipes to make them. Am I missing something?

Here is my modlist: http://i.imgur.com/DITitp8.png

**Comment by KingLemming** [comment]
Yes. You are undoubtedly missing something.

Not a mod, just you, the user, are missing something.

If the jars shipped with the ducts being uncraftable, we'd have had tens of thousands of people complaining. I don't know what interactions you have amongst your mods, but I guarantee you that this is not a problem on our end.
