### ISSUE TITLE
ModTweaker has problem with removing recipes in Induction Smelter

### ISSUE THREAD

**Issue by PanSzelescik** [CoFH/Feedback#1219]
This is my script:
`InductionSmelter.removeRecipe(<thermalfoundation:material:768> * 4, <minecraft:iron_ingot>);
InductionSmelter.removeRecipe(<thermalfoundation:material:768> * 4, <thermalfoundation:material:0>);
InductionSmelter.removeRecipe(<thermalfoundation:material:769> * 4, <thermalfoundation:material:0>);
InductionSmelter.removeRecipe(<thermalfoundation:material:769> * 4, <minecraft:iron_ingot>);`

This is crafttweaker.log:
`[AVAILABLE][CLIENT][INFO] Altering InductionSmelter Recipe(s) for <thermalfoundation:material:768> * 4 and <minecraft:iron_ingot>
[AVAILABLE][CLIENT][INFO] Altering InductionSmelter Recipe(s) for <thermalfoundation:material:768> * 4 and <thermalfoundation:material>
[AVAILABLE][CLIENT][INFO] Altering InductionSmelter Recipe(s) for <thermalfoundation:material:769> * 4 and <thermalfoundation:material>
[AVAILABLE][CLIENT][INFO] Altering InductionSmelter Recipe(s) for <thermalfoundation:material:769> * 4 and <minecraft:iron_ingot>`

But in JEI removed recipes are still showing, and I can still use this recipe

I found a similar issue in ModTweaker Github:
https://github.com/jaredlll08/ModTweaker/issues/622

Minecraft - 1.12.2
Forge - 14.23.4.2739

CraftTweaker - 4.1.9
ModTweaker - 4.0.13
MTLib - 3.0.5

Thermal Expansion - 5.5.0.29
Thermal Foundation - 2.5.0.19
CoFH Core - 4.5.3.20
CoFH World - 1.2.0.5

**Comment by KingLemming** [comment]
We don't manage any of the ModTweaker code. I've verified that IMC correctly removes things, including that recipe.

Try swapping the order of your inputs.

**Comment by PanSzelescik** [comment]
Wow swap is working :D I did not think about it, thanks :D
