### ISSUE TITLE
[Thermal Foundation] Shears items disappeared in 2.0.4

### ISSUE THREAD

**Issue by RhinoKneel** [CoFH/Feedback#122]
Just noticed this from starting a new map and trying to craft wooden shears. No TF shears appear in JEI either, and all shears are turned on in configs.

**Comment by KingLemming** [comment]
Wooden Shears are kind of dumb, so they're disabled by default in the configs anyway.

However, the new config options apparently weren't all working properly, which left a lot of the tools uncraftable. Will probably push a new version to remedy this.
