### ISSUE TITLE
Low FPS while Workbench is open.

### ISSUE THREAD

**Issue by codewarrior0** [CoFH/Feedback#122]
Using CofHCore 3.0.0B9-40 and ThermalExpansion 4.0.0B8-23 with Minecraft 1.7.10.

After playing for a while, FPS drops from 30 to <10 while the TE Workbench interface is open and items are in the crafting grid. This does not happen reliably enough for me to give you steps to reproduce. However, upon using the Java VisualVM's Sampler on it, I saw that the workbench is searching for matching recipes every frame when the GUI is redrawn. Sadly, I don't have a screenshot of the sampler output right now but I will follow up with one when this happens again. The FPS drop only happens with TE Workbenches, and only when any items are placed in the crafting grid. Other crafting tables such as the vanilla crafting table and Tinker's Construct crafting stations are unaffected.

I am using FTB Infinity 1.0.2 with several of the cosmetic mods disabled. I have a feeling that the root cause is the crafting recipe database being bloated with lots of possibly duplicate recipes.

Regardless, I'm requesting that the Workbench crafting UI only search for matching recipes when the items in the grid are changed, instead of searching for them each time the UI is redrawn.

**Comment by KingLemming** [comment]
We've never heard of or seen this FPS drop in testing on any modpack; I assume you aren't playing on a potato, right? I maintain a constant 60 at all times, but maybe FTB infinity is just that stupid.

We'll see what we can do. The tradeoff with our workbench is that the server is doing absolutely 0 work at the same time. There's probably a fix in here, but it may not be an easy one.

**Comment by codewarrior0** [comment]
Thanks. I'm using a Core i5-750 with 16GB RAM and 64-bit Windows 7 and 64-bit Java 7u76. Hardly a potato, even if it's a few years old.

It seems to only happen after some playing - maybe certain uses of NEI or other mod features sets it off. It goes away after restarting Minecraft. I still need to narrow it down some more.

**Comment by KingLemming** [comment]
I agree - that's not a potato, but now you've got me wondering what might be happening client-side for this to be an issue.

I'm curious if a mod is duplicating recipes. Either way, there's *probably* a way to handle this; the way we're doing it currently saves some bandwidth but I imagine there's some sort of slot check we can do.
