### ISSUE TITLE
[CoFH] Disable old java version warning

### ISSUE THREAD

**Issue by ExDomino** [CoFH/Feedback#1220]
Hello, CoFH is generating an always-on-top-modal-window that display an error message to indicate that the java version is out of date. On our server, our modpack works better with Java 7 and we distribute our modpack with Java 7 in order to allow our players to use Optifine and to reduce lags and bugs. For example, a random crahs in the nether with Fastcraft and Java 8. Your message is really not appropriate and should be disabled. Does it exist a config option to disable it? Or a way to prevent its apparition? Thank in advance! We're using version 3.1.2-325 for minecraft 1.7.10 : "CoFHCore-[1.7.10]3.1.2-325.jar".

**Comment by KingLemming** [comment]
Have a screenshot of this? I'm pretty sure we don't actually do this.

**Comment by ExDomino** [comment]
https://github.com/CoFH/CoFHCore/blob/master/src/main/java/cofh/asm/LoadingPlugin.java
Line 112.

**Comment by skyboy** [comment]
The plan is to migrate to requiring java 8, so we can make use of the various new features, which is the purpose of displaying this warning to users on older versions.

If you are having problems with fastcraft and optifine on java 8 then you need to report these errors to hose mods to have them make their mods function correctly. You may also try using CoFHTweaks as a replacement for both, as many people get the same or better performance improvements, with fewer issues like this.

**Comment by ExDomino** [comment]
You should remove this warning for the 1.7.10 version of CoFH. The 1.7.10 runs better with Java 7 and everyone should know that. It's okay to force players that play 1.8+ to go to Java 8, but please, don't force 1.7.10 players to migrate to Java 8. Please make a version without warning for the Minecraft 1.7.10, or at least add a config option. It's important to us !

**Comment by skyboy** [comment]
You don't actually know what you're talking about.

**Comment by ExDomino** [comment]
All of my players have less bugs and lags when they use Java 7 instead of Java 8 for Minecraft 1.7.10, the only problem is that warning dialog, so I think that I know what I'm talking about ! We don't like to play with lag and we don't have a powerful computer like you. Only one of my players have better performances with Java 8 and CoFHTweaks but his computer is really powerful, probably like yours.

And I'm wondering why I lost my time with you, it's just a nag-dialog that you will not remove because you think you're right. I will try to ask another Java Developper to create a mod just to block your warning dialog, I think I will have more luck.

**Comment by XFactHD** [comment]
Having less bugs with Java 7 than with Java 8 is bullshit, I am playing 1.7.10 with Java 8 for a pretty long time now. Also, if I where you I would sacrifice a little bit of performance rather than having massive security holes in the software on my computer.

**Comment by ExDomino** [comment]
It's for that reason I prefered to ask you to remove that warning. What do you want in exchange?

**Comment by bookerthegeek** [comment]
@ExDomino For you to stop arguing with people who actually know what they are doing and accept the fact that you are wrong. That would be a good start. Also it is considered rude to tell people you are going to modify their stuff because you disagree with them. Just out of curiousity, what server do you run?
