### ISSUE TITLE
Thermal foundation Freezing game

### ISSUE THREAD

**Issue by jurassicjordan** [CoFH/Feedback#1220]
This may be caused by an out of date version of thermal foundation (2.3.5), but I have been encountering major freezes that occur right after breaking a block. 
log: https://pastebin.com/bGW6qN5z. 
The game freezes when mining specific ores that have ore dictionaries, as in any form of copper, lead, etc ore. it also occurred when mining mossy cobblestone, and vines. I suspect This is due to my installation is out of date, and may attempt to remedy it. a list of installed mod is shown in the log. thank you.

**Comment by covers1624** [comment]
You clearly haven't read the readme on the repo.. Please update your mods, you are running ainchent versions of CoFH stuff.
