### ISSUE TITLE
Thermal Expansion Creative items glitch

### ISSUE THREAD

**Issue by Eidelmaim** [CoFH/Feedback#1221]
not sure if this stems from the Thermal Expansion mod, but figured i would let you know about it as well.... i have also posted this to the Twilight Forest github.

this glitch does not generate a error log.

FTB Infinity Evolved 1.7 v2.5.0

Twilight Forest 1.7.10-2.3.7
Thermal Expansion [1.7.10] 4.1.2-240

on our Infinity Evolved 1.7 MP server, you are able to use the antibuilder block found in the towers in the Twilight Forest to cause thermal expansion items to break and spawn in as creative items. please see the video ....

https://www.youtube.com/watch?v=Ek3NaHy-qaQ

**Comment by KingLemming** [comment]
Yes, that's a bug with how Twilight Forest is doing things. Basically it's ignoring metadata and being derpy.

**Comment by Eidelmaim** [comment]
ok, thanks for your input. i will pursue this with the twilight guys :)

**Comment by clienthax** [comment]
https://github.com/CoFH/Feedback/issues/1262
