### ISSUE TITLE
CoFHCore for Minecraft 1.12.1

### ISSUE THREAD

**Issue by ZcanKal** [CoFH/Feedback#1221]
There is nothing that works with 1.12.1, and if you're wondering, 1.12.2 wasn't quite working correctly with Multiplayer...

**Comment by Tahakk** [comment]
I have no idea what are you talking about. I play just fine with most of the CoFH mods on 1.12.2. Multiple Modpacks, always MP

**Comment by ZcanKal** [comment]
Wait, what?  What version of CoFH was it using?  
Or if you mean the CoFH 1.12.2 mods, I mean that 1.12.2 vanilla wasn't working.

**Comment by covers1624** [comment]
No, we support the versions we support. You require 1.12.2 to use the CoFH mods.
