### ISSUE TITLE
People travel out of the Viaduct？

### ISSUE THREAD

**Issue by ShiningBRS** [CoFH/Feedback#1222]
It's so ridiculous....
![Uploading 2016-07-27_23.00.05.png…]()

**Comment by KingLemming** [comment]
Yeah so this tells us literally nothing.

**Comment by skyboy** [comment]
Next time you attempt to upload an image, wait for it to upload. And include a useful text description of what was going on instead of mindlessly complaining, yeah?

**Comment by ShiningBRS** [comment]
Oh,failed to upload the screenshot,it said"Something went really wrong, and we can’t process that file."
http://imgsrc.baidu.com/forum/w%3D580/sign=e5d1a34bb87eca80120539efa1229712/e2a45eafa40f4bfbac2d9b3c0b4f78f0f636187a.jpg

**Comment by skyboy** [comment]
That would be hilarious if the viaduct was a block underground.

I expect you have a mod like optifine or fastcraft or something that's causing that.

**Comment by skyboy** [comment]
Closing due to lack of response and apparent cause being unsupported graphical mods.
