### ISSUE TITLE
Ticking Block Entity crash

### ISSUE THREAD

**Issue by Flexico** [CoFH/Feedback#1223]
The crash seems to be caused by my autonomous activator, but I can't make it to it in time to break it before the game crashes. I can't get to it with MCEdit either, because it's inside my TARDIS and for some reason MCEdit can't see the chunks in there. :\

Oh yeah, crash report: http://pastebin.com/5Cxr4eTj

**Comment by skyboy** [comment]
This is an error with Steve's Carts.

**Comment by Flexico** [comment]
Oh! Thanks.
