### ISSUE TITLE
[CoFH World] Underwater generation not working properly in ocean

### ISSUE THREAD

**Issue by nihiltres** [CoFH/Feedback#1223]
I've been trying to use CoFH World to get Biomes'O'Plenty's Kelp (`biomesoplenty:seaweed`) and Coral to generate across all ocean biomes (normally they only generate in dense-but-infrequent Kelp Forest and Coral Reef biomes).

I'm trying to use the `surface` distribution (with `follow-terrain` true) and the `decoration` generator (since it appears to be the only one that'll generate columns). I'm generating in ocean-dictionaried biomes.

The kelp and coral in practice only generate in the water along the shoreline, and often above the water or reaching to the surface (I wish I could limit generators by y-value to stop this!). None generate below y=60 or so, meaning most of the ocean remains bare.

I've tested and reproduced the issue in a reasonably minimal instance containing Biomes'O'Plenty (1.12.2-7.0.1.2384), CoFH World (1.12.2-1.2.0.5), and, for convenience in checking underwater, Clarity (1.1). My tests use a world set to Creative Mode with the BoP world type and its "Archipelago" terrain distribution so as to easily reach ocean. My JSON follows. I've taken a quick peek at CoFH World code but don't see any obvious roadblocks to this working properly.

If this is not a bug, sorry to waste your time; I'd appreciate knowing what I'm doing wrong. If it is a bug, please fix it. :)

Following are the contents of my oceanDecoration.json:
```
{
	"populate": {
		"kelp": {
			"biome": {
				"restriction": "whitelist",
				"value": [{"type": "dictionary", "entry": "OCEAN"}]
			},
			"chunk-chance": 1,
			"cluster-count": 18,
			"dimension": {"restriction": "whitelist", "value": [0]},
			"distribution": "surface",
			"follow-terrain": true,
			"generator": [
				{
					"block": {"name": "biomesoplenty:seaweed"},
					"see-sky": false,
					"check-stay": false,
					"cluster-size": 1,
					"stack-height": {"min": 2, "max": 5},
					"surface": ["clay", "dirt", "gravel", "sand"],
					"material": "water",
					"type": "decoration",
					"weight": 100
				},
				{
					"block": {"name": "biomesoplenty:seaweed"},
					"see-sky": false,
					"check-stay": false,
					"cluster-size": 1,
					"stack-height": {"min": 2, "max": 5},
					"surface": ["clay", "dirt", "gravel", "sand"],
					
					"type": "decoration",
					"weight": 100
				},
				{
					"block": {"name": "biomesoplenty:seaweed"},
					"see-sky": false,
					"check-stay": false,
					"cluster-size": 1,
					"stack-height": {"min": 5, "max": 6},
					"surface": ["clay", "dirt", "gravel", "sand"],
					"material": "water",
					"type": "decoration",
					"weight": 100
				}
			]
		},
		"coral": {
			"biome": {
				"restriction": "whitelist",
				"value": [{"type": "dictionary", "entry": "OCEAN"}]
			},
			"chunk-chance": 1,
			"cluster-count": 20,
			"dimension": {"restriction": "whitelist", "value": [0]},
			"distribution": "surface",
			"follow-terrain": true,
			"generator": {
				"block": [
					{"name": "biomesoplenty:coral", "metadata": 0, "weight": 400},
					{"name": "biomesoplenty:coral", "metadata": 1, "weight": 400},
					{"name": "biomesoplenty:coral", "metadata": 2, "weight": 400},
					{"name": "biomesoplenty:coral", "metadata": 3, "weight": 400},
					{"name": "biomesoplenty:coral", "metadata": 4, "weight": 100}
				],
				"surface": ["clay", "dirt", "gravel", "sand"],
				"material": "water",
				"cluster-size": 1,
				"see-sky": false,
				"check-stay": false,
				"type": "decoration"
			}
		}
	}
}
```
(Some notes: I use multiple identical kelp generators to try to get multiple random height values per chunk for the columns, "biomesoplenty:seaweed" == kelp, and "biomesoplenty:coral:4" is not strictly "coral" but "algae", hence the weighting)

**Comment by KingLemming** [comment]
Strictly speaking, since this is a, "Hey this doesn't work," and not a minimal possible bug...please come to Discord and discuss it in tech support. It could be any number of things, and at this point World is due for a 2.0 rewrite anyways, so a "fix" isn't gonna happen as such.

**Comment by nihiltres** [comment]
Adding a bit of a note: after getting some help on the Discord, it turns out that the problem is that `follow-terrain` apparently works in the opposite way from how it's documented; the problem is effectively resolved by using `"follow-terrain": false`, but *that* is more demonstrably a bug.

**Comment by KingLemming** [comment]
Agreed. And will be fixed in rewrite.
