### ISSUE TITLE
[ThermalFoundation] Сrash with volatile liquids to the server.

### ISSUE THREAD

**Issue by yaroslav4167** [CoFH/Feedback#1225]
When entering any volatile liquid , for example Energized Glowstone - kick occurs from the server.
When reconnecting immediately kicked from server .

Server Core : Thermos 1614 .

Client log : [Pastebin](http://pastebin.com/vAGiCMtc)

**Comment by skyboy** [comment]
On testing, this cannot be reproduced with just our mods, and your log points to nothing in particular. I have to assume this is caused by another mod somewhere somehow.
