### ISSUE TITLE
Retrievers with limited in-inventory size do not consider items already in transit

### ISSUE THREAD

**Issue by pascal-aman** [CoFH/Feedback#1226]
The Problem:
Hooking up a retriever to a network, setting max total items in inventory to a low number, like one. If the network has a large amount of items, the retriever will continue to request items until the first item arrives. It will then reject the stream of items it requested after the first, sending them back.

Expected:
Like the servo and filter, the retriever should respect items in transit when it figures out if it should request an item.

Forge Version: 1.12.2 - 14.23.4.2739
Thermal Dynamics Version: 1.12.2 - 2.5.1.14

**Comment by KingLemming** [comment]
Duplicate. Slated to change during the rewrite. Probably not this year, sorry.
