### ISSUE TITLE
Error caught using VanillaFix and/or Gadgetry:Transmission

### ISSUE THREAD

**Issue by Killerhurtz** [CoFH/Feedback#1227]
I was told to leave this here. I'm not sure where the interaction lies - but it doesn't crash when VanillaFix isn't on, and when it IS on, it just spams that error. 

Something about invalid UUIDs. 

Log is here: https://paste.dimdev.org/ulehokivat.mccrash

**Comment by KingLemming** [comment]
This is something that Elu causes, it's not us. Something about that TEMessageUpdateHolder or whatever just screws up tiles from other mods.
