### ISSUE TITLE
[1.12.2] Disabling Horse Armor leaves empty recipes in Induction Furnace

### ISSUE THREAD

**Issue by tgstyle** [CoFH/Feedback#1228]
The induction recipes also cannot be removed with crafttweaker when enabled, it gives an error that they do not exist.

TE 5.5.0.29
TF 2.5.0.19

![2018-07-27_14 13 55](https://user-images.githubusercontent.com/5832709/43345230-e45a9222-91a9-11e8-99e7-9e8df6bd78df.png)

**Comment by KingLemming** [comment]
This is a strange JEI quirk. The reason that Crafttweaker can't remove the "bugged" recipes is because they actually do not exist.

Disabling the horse armors prevents them from being craftable or showing in Creative. Apparently JEI also prevents them from showing in other contexts.

**Comment by KingLemming** [comment]
My guess is that you aren't removing them properly in your crafttweaker script. Try swapping your inputs.

**Comment by tgstyle** [comment]
Tried both ways, it does not work.

Here is the script
https://gist.github.com/tgstyle/6bc3b9dd3df7911e11daed8984d90b7d

This is the crafttweakerlog.
https://gist.github.com/tgstyle/291af343a70c313345d71f12fb9a9971

This is the mods list.
https://gist.github.com/tgstyle/b765578233985754e34818dec900c0cf

**Comment by tgstyle** [comment]
Ah yep that did it, I should have known. Thanks!
