### ISSUE TITLE
Can't use rosin as fuel...but only in one save?

### ISSUE THREAD

**Issue by OldSedan** [CoFH/Feedback#123]
Neither a steam dynamo or a vanilla furnace will accept rosin as fuel. The issue seems limited to one save; rosin slots in just fine in a new world created to test. All mods and forge updated. I can add more information about mods and such but thought since it's limited to one save maybe there was an easy answer I'm missing. 

Thanks!

**Comment by KingLemming** [comment]
This isn't anything on our end. We add it as a standard Furnace fuel, and it's completely out of our hands after that. This sounds like a Forge or Mojang bug.
