### ISSUE TITLE
Small request. Compatibility

### ISSUE THREAD

**Issue by Badcholo** [CoFH/Feedback#123]
Redstone Arsenal lacks the compatibility with Simply Jet-packs. Redstone Arsenal boots lack protection from fall damage. We could really use an enchantment or config option to remove fall damage with the boots on. Also a Paxel version that combines all the tools into one. Paxel or multi tools have become a need for me. Also my mod-pack is for very tough pro gamers. A fist that can do all, fight, break stone, trees, mine ores and have enchant ability. It surrounds your fist. Just ideas that my server seems to like and want. Thank you so much for an awesome mod!!

**Comment by KingLemming** [comment]
What compatibility is there to add? Simply Jetpacks adds its own recipes. I don't understand.

**Comment by skyboy** [comment]
Fall damage: Feather falling
Paxel: no
Multi-tools: empower the existing tools
MMMPS's power fist: no
Very tough pro gamers: no

**Comment by jadedcat** [comment]
"Very tough pro gamers" ... and you want a "one tool does everything" .... /me laughs hysterically. Y'all are so cute..

**Comment by Badcholo** [comment]
Sorry for my poor choice of words. I just ment it would be nice to add an option to remove fall damage from the boots. Also a paxel was just a suggestion to save inventory slots on players.
jadedcat----------------
Living like a caveman doesn't make you tough. Also on Mojangsters mod pack (my server) you start out with 1 heart, have a thirst bar, health regeneration has had a debuff, Hunger overhaul, Infernal mobs, 30min of day and night, plants only grown in sunlight, pvp, factions with no lands claim. or set faction home, food replenished less with a big increase to hunger max, flans Guns, Pack a punch, Mutant creatures, wait, did you say you laugh hysterically? My server is going though an update, from 1.6.4, but i'll make sure i add you to my wall of rage quits(aka wall of shame) if you ever dare to visit. comes with a server ip. boooya,, nailed it. what server you play on i'll come visit.
