### ISSUE TITLE
when i use viaducts visually i appear 1 block above them. how do i fix it?

### ISSUE THREAD

**Issue by emkline2004** [CoFH/Feedback#1230]
![2018-07-29_12 34 36](https://user-images.githubusercontent.com/36211550/43368499-d8418d3c-932b-11e8-9d58-9e335de04659.png)

**Comment by KingLemming** [comment]
This is going to be caused by something else entirely I'm afraid. Just happens sometimes.

Also, this seems to be on 1.7.10, which is unsupported.
