### ISSUE TITLE
Looking up uses for fluiduct in JEI crashes game

### ISSUE THREAD

**Issue by Syltann** [CoFH/Feedback#1231]
What happens:
Game crashes while looking up uses for fluiduct in JEI.

Hit uses hotkey on fluiduct and it pulled up JEI to the crafting section.
When I click on the "painting machine" (enderio) section this crashes game.

Crash reports:

Crash 1: https://pastebin.com/TA5myze1
Crash 2: (latest): https://pastebin.com/L1b1vkLg

**Comment by covers1624** [comment]
EnderIO is attempting to facade Ducts, that's invalid. Poke EnderIO about this.

**Comment by HenryLoenwind** [comment]
Your model returns null when asked for its particle texture. That's invalid.

**Comment by covers1624** [comment]
Fixed via https://github.com/TheCBProject/CodeChickenLib/commit/9649e178c82d39541f43617eaddfd48c3d8ec9d3
