### ISSUE TITLE
Underwater Hardened Glass is invisible from above water

### ISSUE THREAD

**Issue by ShoeLace1291** [CoFH/Feedback#1232]
I'm not really sure if the hardened glass(HG) is supposed to be like this, but I can't see HG when it is underwater from above the water. I really don't like this. Here are some screenshots to demonstrate:

https://i.imgur.com/wYUiuTM.png
https://i.imgur.com/JjvCwMV.jpg

The larger dome and "hallway" in the screenshots are made of vanilla glass but the small dome is made of HG.

**Comment by covers1624** [comment]
I can't reproduce this. Works fine for me.
![](https://cdn.discordapp.com/attachments/343689435789000705/481623286023716869/Screenshot_from_2018-08-22_10-07-41.png)

**Comment by ShoeLace1291** [comment]
Oh ok so I must be making this up. Shit mod.

**Comment by covers1624** [comment]
I did clear the water out actually. What version of ThermalFoundation are you using?

**Comment by KingLemming** [comment]
Have a modlist for us? If you have Optifine, then this is a total nonstarter, because that mod is a ruinous mess that just takes a sledgehammer to MC's entire rendering pipeline.
