### ISSUE TITLE
Generation of blocks replacing a certain specified block

### ISSUE THREAD

**Issue by danikk14g** [CoFH/Feedback#1234]
Hello,
i am making a modpack and i got an idea to make AE2 meteorites more interesting to find and loot, so i created a valuable custom ore which i want to be only generated in the meteorites. But i think the "material" entry option doesn't allow this. 

I know i can create a cluster of skyblocks and give weight 1-5 to the custom ore but this would need a  high chunk-chance and a whitelist of biomes to make it less common like a meteorite would be.

If thats the case, is there any way i can make a rounded shaped chunk to "simulate" a meteorite?

Thanks.

**Comment by KingLemming** [comment]
Please use the Discord channel for questions. The Issue tracker is not a forum.
