### ISSUE TITLE
The future of Thermal Foundation

### ISSUE THREAD

**Issue by jaredlll08** [CoFH/Feedback#1234]
Hey, so I was looking around reddit and I came across a post by @KingLemming saying that no one is helping out for TF, even though it is open source, so I decided to take a stab at it, and see what was actually stopping the update...
After about 8 hours I got the game to run. Those 8 hours consisted of figuring out why classes were not there, such as StateMapper, which does not exist anywhere in the CoFH repo's but it was being called.

Honestly, having dealt with the code for 8+ hours, I would recommend a rewrite, base up, which is something that I would be willing to do or help with. It is just a matter of me not wanting to spend a day or two rewriting the mod, submitting the PR and then it getting denied, so this is what I am willing to do, if it is OK with you guys, the CoFH owners, I would like to either work with you guys on updating the mod, or I would like to update the mod on my own, and make a PR that would then get accepted, either way, I don't mind, as long as the mod does not die.

Also if you are interested, here is my "duct tape'd" repo of Thermal Foundation: https://github.com/jaredlll08/ThermalFoundation/tree/1.9

**Comment by jaredlll08** [comment]
I should also add that I ported CoFH lib: https://github.com/jaredlll08/CoFHLib
And CoFHCore: https://github.com/jaredlll08/CoFHCore

**Comment by KingLemming** [comment]
I actually already did a pretty big rewrite of it. I assume you started from the "1.9" branch? If not...oh lord.

**Comment by jaredlll08** [comment]
I did start from the 1.9 branch, so it wasn't that bad, but there was still
many things missing, off the top of my head: StateMapper, ItemCoFHBase and
ItemBlockCoFH.
Also the registering if items, just wouldn't happen, I had to add code in
for that.

**Comment by jaredlll08** [comment]
Oh also, the code I did on that port, was just to get it in a working
state, once it was in a working state I was going to clean it up, reduce
redundant methods etc

**Comment by KingLemming** [comment]
See I'm a bit confused - I had TF working with the 1.9 Lib and Core, so I'm confused when you say that there were missing classes.

**Comment by jaredlll08** [comment]
Maybe git didn't sync them? But but for instance,
https://github.com/CoFH/ThermalFoundation/blob/1.9/src/main/java/cofh/thermalfoundation/item/ItemMaterial.java
extends ItemCoFHBase, which should be located here in cofh.core.item, which
it is not...
https://github.com/CoFH/CoFHCore/tree/1.9/src/main/java/cofh/core/item

So not sure what happened, but according to git, the files are not there.

**Comment by KingLemming** [comment]
Yeah. Just checked my local copy and they are there. Huh. Interesting. I'll see about pushing things and maybe it'll all make more sense to you :P

**Comment by jaredlll08** [comment]
Yea, I was wondering what was going on, and I thought the initial issues
were normal, since I updated to 1.10, then the missing classes were a bit
confusing xD

**Comment by Beardedlizzy** [comment]
Nice to see the mod is being updated

**Comment by accessdenied0** [comment]
Even I might have not the right to write here and risk to put here my opinion who no-one cares about,

I'm happy to see this mod is being updated and not are going to die. I want to thank you guys for maintaining this mod and put all this time and effort into this.

The only question I might have here is what CoFH mods are included in this update?

Anyway,

Thank you.

**Comment by KingLemming** [comment]
This is being ported.
