### ISSUE TITLE
[API] Set energy value

### ISSUE THREAD

**Issue by DarkGuardsman** [CoFH/Feedback#1235]
**Request**
Add :
IEnergyReceiver#getEnergyStorage(ForgeDirection side)
IEnergyProvider#getEnergyStorage(ForgeDirection side)
IEnergyStorage#setEnergy(int energy)

**Reason**
I'm working on an EMP that drains all energy from all power tiles. While testing thermal expansion I noticed that the EMP was only draining 32k max from most tiles. Through debugging I found this to be caused by a hard limit on both the tile and its energy storage. Exploring the API I have found no way to get around this hard limit. So I am left with using reflection, or direct references to the mod's code. I rather avoid both and request some API changes.

**Comment by KingLemming** [comment]
I don't like you screwing with our code directly, but frankly that's going to be the only option you have.

I'm not going to add exposure to the internal energy storage. That's not something other mods need to know about.

RF is for transferring energy in a logical way. I suggest you write an IEMPable interface and let modders utilize it to whatever effect they want.

RF isn't electromagnetic, there's no reason to think EMP would work on it. Also, I'm curious what you think happens in real life when EMP hits a battery. Because it's definitely not what you're trying to mod here.

**Comment by DarkGuardsman** [comment]
Well, it's not about the realistic behavior but rather the gameplay aspect. As I can come up with some BS lore explaining away how it works. That being, said what are the chances of you implementing an interface like that if I created it? As I suspect it's either a no or maybe later answer. Which is why I am coding direct support rather than waiting on mod developers to implement my API. As I use to have an EMP interface dating back to 2012 and only had 3 mods implement it.

> Also, I'm curious what you think happens in real life when EMP hits a battery

To be honest i don't really know what would happen and need to read into EMPs more. I suspect it would cause some kind of short between the plates of the cell. However, this depends on the design of the battery, how it's connected to circuitry, and other factors. All I know is that EMPs, in the case of nukes, generate high-powered radio waves. Which then induce effects into the electronics causing damage or other odd effects.

Regardless, I went ahead and coded two solutions to the problem. One is a broad range reflection system that looks for IEnergyStorage and attempts to zero it out. As well I made a proxy that directly gets the EnergyStorage from TilePowered and calls setEnergy(0). I would have rather avoided doing this as I'm now forced to maintain support for your mod, and a few others. Rather than just calling APIs that could have encapsulated the setting of the energy value.

**Comment by KingLemming** [comment]
I'd rather you avoid doing it to. Maybe I don't want energy zeroed out in my tiles.

The problem with this is that you're inherently stating, "My mod is more important than yours," which is wrong. That's why opt-in interfaces are the proper way to handle this.

**Comment by bookerthegeek** [comment]
Just saying....

https://youtu.be/qZ6PWh91VW0

**Comment by DarkGuardsman** [comment]
Not trying to be mean but it goes both ways, "Maybe I don't want energy zeroed out in my tiles." is the same as saying "I don't want your EMP to function". I rather have the users decide what works and doesn't. Its up to them to pick balance in most cases when dealing with mod compatibility. As well I'm more than happy to have developers use the EMP interface to opt-out. However, by default I want to ensure that the EMP works well on everything without forcing 50 mods to opt-in.

**Comment by DarkGuardsman** [comment]
@bookerthegeek I've actually read a study similar to that a while back that explains cars still run due to being isolated from the ground. If connected to the ground or very very close they are still effected. As well I'm basing the EMP clearing the energy off of destroying the charging mechanism causing a leak of energy into the ground. Or in the case of RF disrupting the magic energy? I really don't know what RF is based off of and last time I talked to @KingLemming in TS he said it's based on whatever you want it to be.

**Comment by MyNameIsKodos** [comment]
Honestly, at this point, with how irrelevant RF is anyway now that most folks are using Tesla and 1.10.2, and since there's no official RF api for any of the newer versions of minecraft, this seems like a nonissue that will go away once you guys (BBM) update MFFS and everything else to 1.10.2

**Comment by DarkGuardsman** [comment]
@MyNameIsKodos Technically we just finished the main update a few days ago. Just working on updating all the power code and ensuring support is spot on. Part of that support is ensuring EMPs can disable the power source for a forcefield.

**Comment by MyNameIsKodos** [comment]
Maybe add in a warning that it won't work with TE/CoFH stuff?  Still works with IC2, right?

**Comment by DarkGuardsman** [comment]
@MyNameIsKodos Have not added back IC2 support yet, that is after getting RF done as RF is still the primary power system for 1.7.10. As well it does actually work, I just had to add several hacky ways of bypassing the API. Really don't like doing it this way as it breaks support on so many mods. As I have to make a hacky solution for every RF mod that exists. Instead of just doing getStorage.setEnergy(zero).

**Comment by MyNameIsKodos** [comment]
I don't know that I'd call RF the 'primary' power system of 1.7.10.  IC2's EU is still fairly popular.

**Comment by DarkGuardsman** [comment]
@MyNameIsKodos well it's used more than IC2 or gregtech, but it's more of a superficial title. I just want to ensure that support for it does exist. As I don't like the idea of a user setting off the EMP and getting a no-effect result. As well the code is important for many additional features. Such as the Energy nos(steals energy) and neut(wastes energy) that both effect energy. In which in order to get to work with the API would mean I have to wait 2500+ ticks for all 80M RF to drain. Something that is not a very good idea as it would bog down the game over time.

**Comment by skyboy** [comment]
Wow this got way off topic pretty fast.

But yes, this isn't something chat can be added anyway - not all implementations of RF utilize the EnergyStorage concept, such as with MFR, and there's no reason to enforce it as it's just a useful abstraction of logic, in much the same way as the FluidTank in Forge.
