### ISSUE TITLE
Thermal Expansion: CTD after putting two satchels to crafting panel

### ISSUE THREAD

**Issue by Blatts12** [CoFH/Feedback#1236]
I put 2 satchels(signalum) with different enchantments to crafting panel and ctd happens.

COFHCore 4.5.3.20
ThermalExpansion 5.5.0.29
Forge 1.12.2-14.23.4.2739

https://pastebin.com/cCuRnu0X

**Comment by KingLemming** [comment]
What's a crafting panel?

That crashlog shows that they have a metadata of 6. That's incorrect and they are corrupted items.

**Comment by Blatts12** [comment]
Crafting panel - 2x2 crafting in inventory

**Comment by KingLemming** [comment]
Interesting.

Well, don't do that.

**Comment by covers1624** [comment]
You /can/ hide the issue, by updating to CCL 3.2.1 and turning on the opt-in, attempt recovery on item render exception flag in the config ;)

**Comment by KingLemming** [comment]
I know what the underlying issue is. Will figure out a fix once I'm back at a dev machine.

**Comment by KingLemming** [comment]
Spoke too soon. I do not. I have literally no idea why this happens and every attempt to trace the codepath has resulted in nothing. There is no reason for this to occur at all.

**Comment by KingLemming** [comment]
Okay well actually...vanilla Mojang stupidity. Mitigated.
