### ISSUE TITLE
Crashed when using arcane ensorcellator

### ISSUE THREAD

**Issue by RandomLibrarian** [CoFH/Feedback#1237]
Was doing my first craft using the arcane ensorcellator and just as the machine finished it crashed. Let me know if its a cofh issue or not and I can cross post.

https://pastebin.com/vt9cSNLL

**Comment by KingLemming** [comment]
100% Ex Nihilo.

**Comment by RandomLibrarian** [comment]
OK I'll post over there. Thanks
