### ISSUE TITLE
Compatibility of thuamcraft 6 mobs Morbs and Augmented Centrifugal separator

### ISSUE THREAD

**Issue by Rubywolffire** [CoFH/Feedback#1238]
I was testing a mob farm idea using mainly Thermal Expansion for mob processing and found that the Angry Zombie Morbs were clogging my system they can't be processed by the augmented centrifugal separator witch i believe is a bug, I also found that tinkers blue slime don't work ether

**Comment by KingLemming** [comment]
Not a bug, they don't have loot tables which are compatible.
