### ISSUE TITLE
[Question] Is there a way to Load Balance outputs?

### ISSUE THREAD

**Issue by Lion4K** [CoFH/Feedback#1239]
Take a look at this setup:
![2018-08-03_09 51 46](https://user-images.githubusercontent.com/10391955/43643873-08e5de2c-9703-11e8-98e1-fea73ad48485.png)
see how only 2 chests gets stuff while one is not?
I wanted to make so all chests gets the same amout of stuff.
Is that possible?

Sorry if here was a bad place for asking.

**Comment by KingLemming** [comment]
We have a Discord for this. There's a link to it on our website. The issue tracker is not a forum.

Also, without knowing the rest of what's going on in your setup, that really can't be answered. No clue what you are doing there.
