### ISSUE TITLE
[Thermal Expansion 1.10.2] New compression dynamo fuels not showing in JEI

### ISSUE THREAD

**Issue by bbgott** [CoFH/Feedback#124]
I tried adding forestry ethanol as a fuel source for the compression dynamo.  After adding the entry to the fuels.cfg the dynamo would accept ethanol into its fuel tank and burn it, but the fuel doesn't show up in JEI like the other fuels.

Forge: 12.18.3.2185
CoFH Core: 4.1.1.156
Forestry: 5.2.17.368
JEI: 3.14.7.416
TE: 5.0.4.90
TF: 2.0.5.81

**Comment by KingLemming** [comment]
Yeah that's just how it's going to work due to ordering and when things get processed. Sorry.

Also, come 5.1 that's all being stripped out and revamped anyways.
