### ISSUE TITLE
Item Blocker for Thermal Dynamics

### ISSUE THREAD

**Issue by TheOnePath** [CoFH/Feedback#1242]
This would be like an item filter except it doesn't allow for items to pass through from either direction. This allows for tiling machines for processing but still allowing for RF to pass through; by this I mean it would be great for Signalum-Plated Impulse Itemducts.
The same could be performed for fluiducts, but that's not a priority for me; though would be cool.

I hope you can create something like this.
Thanks.

**Comment by Tora-B** [comment]
If you don't want items to pass through in either direction, why not just configure the machine so that it doesn't have an input or output on that side? RF still passes through solid sides.
