### ISSUE TITLE
Not an issue, a bother.

### ISSUE THREAD

**Issue by chezpaul** [CoFH/Feedback#1242]
When my server launches, it hangs for 5 minutes on this line:
: There are no crafting files present in /Users/bwayserver/Desktop/KCauldron/config/cofh/thermalexpansion/crafting.

And then keep going... Just a little annoying to have to wait so long each time.

**Comment by KingLemming** [comment]
That definitely sounds like an issue with your server. It shouldn't take that long to scan. No files? Cool, move on. And that's exactly how it actually behaves for everyone else.

**Comment by chezpaul** [comment]
Well it used to behave like this for me too. I just updated to your latest updates in the past 2 weeks.
And now it happens.
Does everyone take the time to look at their server logs go through?  ;-)

**Comment by KingLemming** [comment]
Probably not. But given that we *do* test the server jar, I can pretty confidently say it doesn't happen all the time. Try making it happen with only CoFH mods.

It's *very* possible that you are seeing that message and then you have another mod taking 5 minutes directly after it with no feedback.

**Comment by skyboy** [comment]
That line is printed after it's scanned, so if you see that line in the log it's already finished scanning and moved on to someone else's code.
