### ISSUE TITLE
Vacuumulator NBT tag check

### ISSUE THREAD

**Issue by comp500** [CoFH/Feedback#1243]
I'm making a mod [(Demagnetize)](https://github.com/comp500/demagnetize) that adds the PreventRemoteMovement (CoreProps.CONVEYOR_COMPAT in CoFH core) NBT tag to items within an area around a block. This stops item magnets (such as the Fluxomagnet from TI and the Ring of Magnetizing from AA) from picking up items around the block, so that crafting systems that use item entities (e.g. the Atomic Reconstructor) are not affected by magnets.

However, the Vacuumulator also checks this NBT tag, which means that my mod blocks the Vacuumulator from picking up items. Removing this check in the Vacuumulator is not a good idea, as it would break conveyor belts. I propose to add a check for an extra NBT tag, called AllowMachineRemoteMovement (or similar) that permits machines (but not item magnets) to remotely move (e.g. Vacuumulate) items with it.

**Comment by KingLemming** [comment]
So the problem is that I didn't invent that tag. That's from Immersive Engineering, and there's cross compat with Botania, EnderIO, etc.

So basically, you want to invent a new tag and change the entire modded Minecraft ecosystem. Which is something you can do, but you'll just have to release the mod first and then plead your case to every mod which deals with magnets/attraction I'm afraid.

**Comment by comp500** [comment]
It won't affect existing uses of PreventRemoteMovement, and my mod will add both tags to the items. Every existing mod that deals with magnets and attraction will still be able to use PreventRemoteMovement in the normal way.

The only mods that will have to change (for my mod to work) will be mods that add ranged item collection (e.g. the Vacuumulator and the AA Ranged Collector). The AA Ranged Collector works fine anyway as it doesn't check PreventRemoteMovement; the Vacuumulator is the only block I've seen that checks it.

**Comment by comp500** [comment]
I did some more testing, and found that Ender IO's Vacuum Chest also checks the PreventRemoteMovement tag, and have submitted an issue on their repo.

**Comment by HenryLoenwind** [comment]
Just for clarification: Do you actually need those items to be moved by the machine or would it be ok if they'd just to pick up items in their pickup range (that's touch+.5 for eio)?

**Comment by comp500** [comment]
I'm not sure exactly how the Vacuum Chest works, but the NBT tag should tell the Vacuum Chest (or Vacuumulator) to carry out it's default behaviour, as if the PreventRemoteMovement tag didn't exist. If the default behaviour is to move items, that should be done.

**Comment by KingLemming** [comment]
Okay, so what is the actual specific tag that you are using? I don't mind adding this, but I need to know *exactly* what it is. :)

**Comment by comp500** [comment]
I added a boolean tag called `AllowMachineRemoteMovement` on the EntityItem. If it is set to true and the object that does the remote movement is a machine (basically anything that isn't a player), the PreventRemoteMovement tag must be ignored. If it is set to false or is unset, the PreventRemoteMovement tag is not ignored.

If the PreventRemoteMovement tag is not set to true, the AllowMachineRemoteMovement tag _must_ have no effect. This is to ensure consistency with IE's conveyors that remove the PreventRemoteMovement tag when items fall from it; so that if a conveyor moves an item outside the range of a Demagnetizer (that applies both tags) the item can be picked up normally.  Unfortunately, one side effect of this is that items on a conveyor within the range of a Demagnetizer will be picked up remotely by machines, however conveyors apply the PreventRemoteMovement tag anyway, so a Demagnetizer is not needed.

Thanks for considering my issue!

**Comment by comp500** [comment]
Was [Solegnolia compatibility](https://www.reddit.com/r/feedthebeast/comments/99emw9/demagnetize_stop_item_magnets_from_destroying/e4n0z2l/) ever properly implemented for the Fluxomagnets?

It (and other magnets that support the Solegnolia) could cause a problem for my mod as my Botania compatibility works by imitating a Solegnolia. Solegnolias don't have an item filter, so if both the Solegnolia check and PreventRemoteMovement are used, the item filter in my Demagnetizers is ignored. I'll probably submit a PR to Botania to add support for PreventRemoteMovement to Botania's ring, however it could cause problems before that is merged.

**Comment by KingLemming** [comment]
It wasn't because I was waiting on Botania to fix an API issue first. I'm unsure if that's happened yet.
