### ISSUE TITLE
[bug] [Thermal Expansion] [Thermal Dynamics] TGSI shading error on xf86-video-radeon driver

### ISSUE THREAD

**Issue by knight-ryu12** [CoFH/Feedback#1246]
Mod construct: TE TD only does happen same thing

When I see Tesseract and/or TD/TE Item that using shader will cause TGSI shading error. and lags horribly.
I can suppress error and stop lags by removing sharder by editing config

OS: Arch Linux
Using AMD Radeon HD6570 with mesa-libgl and AMD radeon opensource driver

**Comment by knight-ryu12** [comment]
If you need logs or something else, I'll provide.

**Comment by KingLemming** [comment]
IMO this is working fine. That's why the config options exist.

**Comment by knight-ryu12** [comment]
So is it driver's fault?

2016/09/01 2:40 "KingLemming" <notifications@github.com>:

**Comment by KingLemming** [comment]
Basically, yeah. We use standard openGL calls. If it's not workin', that's on them.
