### ISSUE TITLE
Agitative Manifold and Closed-Loop Cooling augments block

### ISSUE THREAD

**Issue by ThatGuy435** [CoFH/Feedback#1246]
I'm not sure if this is intended or not, but each augment put into a Compression Dynamo individually behaves as expected, but they cannot be stacked - there is no mention of a conflict in the wiki docs nor the in-game description.

**Comment by KingLemming** [comment]
Both the wiki and in-game documentations state this behavior.

They are both Specialization augments. This is 100% working as intended, and as documented in both places.
