### ISSUE TITLE
Add an option to remove enchantment aura from colored items

### ISSUE THREAD

**Issue by fluid-uu-matter** [CoFH/Feedback#1248]
With the enchantment aura, colors on colored items become hard to seperate. all items come in purple aura. Could you add a option to remove these aura from colored items? I want my holding IV satchels to be seperated more clearly.

**Comment by KingLemming** [comment]
I'll see if this can be done. I believe it can be.

**Comment by MrLavender** [comment]
I'd also like this please. Not because I care much about the colours but because I think that the aura, when on an item like a satchel that I keep on my hotbar all the time, is pretty obnoxious to be honest. It's very... loud :P

So any way to remove it is fine by me.

**Comment by KingLemming** [comment]
Implemented as a Global setting in CoFH Core, client-side. Not going to get into per item type or per item.
