### ISSUE TITLE
Redstone Arsenal Fluxed Quiver acting as Melee weapon

### ISSUE THREAD

**Issue by Cheezy16** [CoFH/Feedback#1249]
I have the Rough Mobs mod for 1.12.2, and blazes inflict damage on players that use melee force such as a sword. However, while using the flux-infused bow I was also hurt which leads me to believe that the bow inflicts melee damage wrongfully. I already tried with thermal foundation bows, and they worked properly, so this appears to be a bug with redstone arsenal. This is in version 1.12.2 - 2.5.1.13 of redstone arsenal.

**Comment by Cheezy16** [comment]
I made a mistake, its not the bow that is causing this but the fluxed quiver in conjunction with the fluxed bow. Normal arrows work correctly with the bow.

**Comment by KingLemming** [comment]
Nope. This is just how "Rough Mobs" is determining "melee" damage, and it seems that they have a very loose interpretation which is incorrect.

Flux arrows deal flux damage. Flux damage is not marked as melee damage, but apparently reads as such with their filter.

**Comment by Cheezy16** [comment]
Alright, ill let them know if they dont already. thanks
