### ISSUE TITLE
Ejector Dupe Bug

### ISSUE THREAD

**Issue by Centax** [CoFH/Feedback#125]
![blockgate dupe](https://cloud.githubusercontent.com/assets/8799862/6260614/8f92a31a-b7af-11e4-9255-654bd8bd761c.jpg)

**Comment by KingLemming** [comment]
WTF is a block gate and what mod is it from?

**Comment by skyboy** [comment]
This is an error entirely with the block gate.

**Comment by Xee1** [comment]
Block gate from Steve's factory manager
