### ISSUE TITLE
[CoFH Core 1.10.2] Commands cannot find player name

### ISSUE THREAD

**Issue by ulkunderscore** [CoFH/Feedback#125]
The "/cofh countblocks" command doesn't work for me ("Player cannot be found", even when using only coordinates). This also happen with the removeblocks command. I tested it with world stripper and all other mods removed after.
It may be related to the underscore in my username, Or maybe I am doing something wrong?

[countblock radius](http://i.imgur.com/AHqDqsF.png) - [countblock coords](http://i.imgur.com/I5zmNvR.png)

This is on MC 1.10.2 and cofh core 4.1.1.156

**Comment by KingLemming** [comment]
Are you able to use Mojang commands with your name? That's not one of our error messages and we're using Minecraft's method of getting a player.

**Comment by ulkunderscore** [comment]
Well, this is embarassing.. I looked over it with fresh eyes and turns out I kept typing in the "{ }" brackets. I could swear I tested this.

Thanks for responding and sorry for the bother.

**Comment by KingLemming** [comment]
No worries!
