### ISSUE TITLE
[Bug?] Blizz, Basalz and Blitz are inivisble.

### ISSUE THREAD

**Issue by karakufire** [CoFH/Feedback#1250]
I encountered Thermal Foundation's 'Blaze'-like mobs are not visible and targetable when making mod environment.
Use spawn eggs of them, Console printed "Skipping Entity with id -x(x is 94~96)" and invisible untargetable mob spawned.

mod list
http://pastebin.com/dNQHkEek

**Comment by KingLemming** [comment]
You've got another mod breaking it. Isn't us, sorry.
