### ISSUE TITLE
Standalone options for Innovation

### ISSUE THREAD

**Issue by Atskadan** [CoFH/Feedback#1251]
I like the Thermal suite of mods, but they don't fit in every pack I make. However, I personally have yet to find a toolset mod that is as convenient as Thermal Innovations, meaning I require a good number of mods (cofh core/world and thermal foundation) just to use drills and such. I can work with that, but by default the drills also require thermal expansion machines to craft the items needed for them.
Is there any possibility for more individual support for this mod? Even something simple such as a vanilla style recipe config (like the Exchangers mod) would be great.

**Comment by KingLemming** [comment]
In the 1.12 era, the answer is currently Crafttweaker. It's probably your best actual bet too. Strictly speaking, TE isn't required for those materials, however. Other mods are capable of producing them.

In 1.13, things will be changing dramatically. Only CoFHCore will be an absolute requirement for any of the Thermal mods.
