### ISSUE TITLE
PrecipitatorManager doesn't return any recipes

### ISSUE THREAD

**Issue by andrewminer** [CoFH/Feedback#1252]
I'm the author of [Crafting Guide](http://crafting-guide.com), and I'm writing [a mod](https://github.com/andrewminer/crafting-guide-exporter) to export data for the website.  So far, I've been having great luck using the various `*Manager` classes to get the recipes for the various ThermalExpansion machines, but that seems to have run out with the Glacial Precipitator.  I'm calling `PrecipitatorManager.getRecipeList()` but I get an empty list as a result.  Is there some better way to get a list of recipes for that machine?

**Comment by KingLemming** [comment]
That class isn't finished and likely won't be. It's a placeholder for when the machine gets a revamp.
