### ISSUE TITLE
MultiBlock compat?

### ISSUE THREAD

**Issue by atanamir** [CoFH/Feedback#1253]
It seems that I can't put multiblock covers/panels on the same block as the ducts from thermal dynamics.  However, I've seen posts elsewhere that seem to indicate that it is supposed to be supported.  If not, is it a lot of work to register the ducts as multiblocks so they can be enclosed hollow blocks, panels, covers, etc.?

Thanks!

**Comment by KingLemming** [comment]
It is not supported, no. They have their own cover system.

**Comment by atanamir** [comment]
Does that mean there's a cover system for Thermal Dynamics?  If so, is it in NEI? (I wasn't aware there was a cover in TD)

**Comment by KingLemming** [comment]
Yes, any block + a structural duct.
