### ISSUE TITLE
Cache with Ender Pearls allows continued extraction even if player inventory full - items voided

### ISSUE THREAD

**Issue by MCdonut** [CoFH/Feedback#1256]
This is in FTB Infinity Evolved 2.6.0 - Expert mode, TE version 4.1.3-246

If my player inventory is full, and I shift click to pull a stack of Ender Pearls (16) from a cache, it will continue to allow withdrawal of Ender Pearls, even though my inventory is full, and there is nowhere for them to go. The extra pearls just disappear. This doesn't happen with items that have a stack size of 64, such as stone, gravel, dirt, etc. The only item with a stack size of 16 that I've tried is Ender Pearls; I haven't tried with chicken eggs or anything else.

**Comment by C1ffisme** [comment]
Can't confirm with ender pearls using Thermal Expansion 4.1.4-247.
