### ISSUE TITLE
Thermal Foundation Crash

### ISSUE THREAD

**Issue by HydrogenC** [CoFH/Feedback#1256]
I updated forge to the latest version. Then I started the game, it crashed. 
Version: 1.12.2
TE version: latest
It crashes with 14.23.4.2750, while it works well with 14.23.4.2732
[CrashReport](https://pastebin.com/4N1CBqjY)

**Comment by KingLemming** [comment]
Oh. So you updated Forge.

But then you DID NOT update your other mods.

I'm going to close this. I think you know what you should do.
