### ISSUE TITLE
Allow friends command without admin permissions

### ISSUE THREAD

**Issue by phill3** [CoFH/Feedback#1257]
The only way to add people to your friends list is with /cofh friends, but one can only use that command with admin permissions, so that doesn't really work well for servers. Please add a separate friends command which allows non admin users to manage their friend lists.

**Comment by KingLemming** [comment]
You would be incorrect. The friend command is usable without being an admin, as shown here:
http://teamcofh.com/docs/cofh-core/features/commands/

However, certain permission-managing mods/addons screw it up. Anything with a "node" for example.
