### ISSUE TITLE
Unknown crash after an hour of gameplay

### ISSUE THREAD

**Issue by GmanAtheist** [CoFH/Feedback#1258]
Minecraft 1.12.2
Crash log:
https://paste.dimdev.org/ikevuroyev.mccrash

CoFHCore-1.12.2-4.5.3.20-universal
![snag-0001 14-08-2018 18 30 36 james1](https://user-images.githubusercontent.com/5624207/44107794-6c650356-9ff0-11e8-9583-3de29670bc8b.jpg)
![snag-0002 14-08-2018 18 30 53 james1](https://user-images.githubusercontent.com/5624207/44107795-6c7cc180-9ff0-11e8-9539-21e5fe4f57f3.jpg)
![snag-0003 14-08-2018 18 31 27 james1](https://user-images.githubusercontent.com/5624207/44107796-6c91d994-9ff0-11e8-9331-aa1a39ff55e0.jpg)
![snag-0004 14-08-2018 18 32 18 james1](https://user-images.githubusercontent.com/5624207/44107797-6ca89bc0-9ff0-11e8-8bd1-04e8de952383.jpg)

Please help. Thanks :-)

**Comment by KingLemming** [comment]
Caused by Mekanism.
