### ISSUE TITLE
Duplication Glitch. Thermal Dynamics

### ISSUE THREAD

**Issue by Gohu29** [CoFH/Feedback#1258]
https://www.youtube.com/watch?v=sx7uiBlBpx4

Dupe with an Hungry Chest, warp itemduct and resonant retriever (from thermal dynamics).

Only work with Hungry chest.

**Comment by KingLemming** [comment]
If it only happens with a Hungry Chest, that means it's the Hungry Chest.

**Comment by bookerthegeek** [comment]
It actually happens work the retrievers.  Has for a long time.

Hungry chest, locked Jabba barrels, sfm block gates.

I'll make a proper bug report when I get home.
