### ISSUE TITLE
[1.10.2] Crescent Hammer acts like Crystal Binder from Draconic Evolution

### ISSUE THREAD

**Issue by Jason505** [CoFH/Feedback#1259]
Hey there!
For some reason, from time to time Crescent Hammer doesn't work like Crescent Hammer, but like Crystal Binder from Draconic Evolution.

Using:
CoFHCore-1.10.2-4.1.12.17
ThermalExpansion-1.10.2-5.1.10.28
Draconic-Evolution-1.10.2-2.1.8.273
Forge 12.18.3.2511

I don't know, which mod causes this issue, so i decided to post it here.

**Comment by KingLemming** [comment]
That's because it implements that interface. Intentional.
