### ISSUE TITLE
Redstone Arsenal Bug, and Thermal Expansion Bug

### ISSUE THREAD

**Issue by Wolfseverest93** [CoFH/Feedback#126]
I'm using the latest version of thermal expansion/foundation/cofh core/redstone arsenal, and oddly, the redstone arsenal tools and weapons require rf to run (duh) BUT instead of using their rf when used, they use up their durability, eventually breaking (i highly doubt thats intended TwT), last time i used the redstone arsenal was back on 1.6.4, and it was working fine back then, the weapons and tools would never break, had iron grade stats plus their buffs and whatever enchantments we put on them, but here i am in 1.7.10 trying to use a flux-infused pickaxe in hopes i could use my other materials on machine making from then on (exception of making a diamond pickaxe in the rare occasion i ever need one), and it doesn't do what it's supposed to... I not once saw its energy levels go down, but instead it eventually broke when i mined around 2k cobblestone and ore in a man-made quarry...

I'd also like to point out that on rare occasions, placing a leadstone energy cell crashes the game on an entity function error to set the 6 sides to their first settings. this has only happened to me twice however, and only when it was raining in the game if that means anything idk though.

really looking forward to that top one getting fixed asap, the second one i can live with waiting for though.

**Comment by KingLemming** [comment]
Awesome. Have logs? Have a modlist?

Otherwise this is a bunch of things that we can't reproduce.

**Comment by Wolfseverest93** [comment]
XD ok here's the immense modlist:

bspkrsCore6.16
CodeChickenlib1.1.1.99
LibSandstone1.0.0
StartingInventory1.7.10r03
StatusEffectHUDClient1.27
BattleGear2-1.0.7.0
zeldaswordskills2.2.2
appliedEnergistics2-rv1-stable-1
bdlib1.5.1.32
buildcraft6.3.3
chickenchunks1.3.4.16
codechickencore1.0.4.29
cofhcore3.0.0b9.40
compactmachines1.17
computercraft1.65
craftguide1.7.10(doesnt have a version tag but it's the latest according to minecraftforum.net)
DraconicEvolution1.0.0e
enchantingplus3.0.2
enderio2.2.8.349
factorization0.8.88.7
forestry3.4.0.7
funkylocomotionbeta-4
advancedgenerators0.9.6.27
inventorytweaks1.59-dev-152
journeymap5.0.1unlimited
levelup0.9
lootbags1.5.1
minetweaker3-3.0.9C
mystcraft0.11.0.00
naturalabsorbtion1.2.1
openmodularturrets1.3.4-27
orespawn20.2
quiverbowb90
railcraft9.4.0
recallstones0.4.16
redstonearsenal1.1.0rc1-19
reliquary1.2
runicdungeons1.0.2
solarflux0.5a
thermalexpansion4.0.0b8-23
thermalfoundation1.0.0rc1-13
twilightforest2.3.3
ultracompression0.5.1
waila1.5.8a
zeldaswordskillsaddon0.0.4a
zz-backpacks3.0.2

(going to reopen my world with the debug on so everything my character does is dumped to a file, and then ill post it through a pastebin so it wont take up so much room like this reply did)

**Comment by Wolfseverest93** [comment]
note: it appears now that ive tested it different ways since i went on my test world, that the issue happens when the tools and weapons are in battlegear slots. and also when i have a quiver from quiverbow anywhere in my inventory. for now i can live with hiding my quiver when i go to use flux tools.
as for the log, i don't think it noted what was shot and when, but if needed i have a few screenshots i can add showing the bows damage and rf. the log is too big for pastebin and too big for here, and im not all that desperate that id go hunting through it for anything important to quote out... shall i just send the fml-client-latest file through zip on dropbox or make a repository on my page to gradually post all of it in? im too tired to play word search atm anyway...

**Comment by Wolfseverest93** [comment]
nevermind, i fixed it by making a small directory adjusting mod because the use of the items was being forced to durability rather than rf because of the quiver from quiverbow being in my inventory. (note: it affected all rf tools, not just the bow), this is the last time i report a bug, since it seems that i usually encounter bugs that don't generate anything in the log since they aren't logged events. and no one cares when they arent logged.

**Comment by KingLemming** [comment]
It's not that we don't care, it's just that things like this become *very* hard to reproduce without a log.

Thanks for a heads up on this.

**Comment by Wolfseverest93** [comment]
alright, sorry i'm a bit too used to dealing with the lazy mod owners from the smaller mods so i sometimes snap and fix the issue myself. nothing against you guys, ive just gotta adjust and stop taking everything on myself to handle so often.

**Comment by Wolfseverest93** [comment]
also, i'll open a new issue with the crash log when the occasion arises that the leadstone energy cell crashes the game again, lately ive just been skipping to hardened to avoid it. although i might end up making a small fix on my side, it would still help to give you guys that to fix for those who don't know how to snatch code through a java binary and fix things on their own.
