### ISSUE TITLE
So I ported this to 1.10.2

### ISSUE THREAD

**Issue by gameofblocksdev** [CoFH/Feedback#1260]
As the name implies: https://github.com/gameofblocksdev/CoFHLib

Nothing overt has broken yet in my totally exhaustive (/s) testing process. That said it's not like I've had a chance to try implementing much - I'm sketchy on anything rendering related for obvious reasons. But hey, it compiles, no errors, doesn't crash the game. RF seems usable, as do most of the helper methods.

Only moderate change so far is adding in methods to use take advantage of the offhand slot. Everything else is updating to the newer API.

Do with it as you wish TeamCOFH!!! If you'd like me to remove it naturally I will. I've left in all default licenses and whatnot. 

I won't provide the built jar either unless you give me go-ahead, or post anything publicly. I just needed this for another project I'm working on and decided to get the ball rolling.

Edit: Btw I based this off the 1.9 branch in the hope whatever stuff had already been done would help.

**Comment by danielhickman** [comment]
While still following the license, you could still provide built copies. Just make sure to attribute them and whatever else is marked in the license.

https://tldrlegal.com/license/gnu-lesser-general-public-license-v2.1-(lgpl-2.1)

**Comment by danielhickman** [comment]
You should also take a look on [this Reddit thread](https://www.reddit.com/r/feedthebeast/comments/4t7qes/where_have_the_cofh_team_gone/). One of the two founding members of CoFH stated that:

>Life happens. Frankly, I'm burned out on Minecraft in a big way. And there's a part of me that thinks it'd be a good thing to ride off into the sunset. There's not a whole lot of joy left for me in modding this. Yeah, I got a lot of the code done for 1.9+ and it's in a semi-workable state. We'll see what happens. [...]

and

>The vast majority of the code - CoFHCore and TF - is already visible. I don't see anyone jumping up to contribute.

And here's the [last official post I could find](https://www.reddit.com/r/feedthebeast/comments/4ctddh/cofh_progress_189/)

And the license is okay on the lib repo, but not the others it seems. You may want to contact the members directly instead of the feedback repo.

**Comment by KingLemming** [comment]
We're porting to 1.10.2 at the moment.
