### ISSUE TITLE
CoFHCore override causing metadata stripping when calling dropBlockAsItem

### ISSUE THREAD

**Issue by clienthax** [CoFH/Feedback#1262]
In the process of patching a bug with twilight forest antibuilders i came across this bug in your override.

Example.
Twilight calls blockstrongbox.dropBlockAsItem with correct metadata.
dropBlockAsItem in turn calls getDrops in vanilla.
getDrops is overridden in CoFHCore here https://github.com/CoFH/CoFHCore/blob/master/src/main/java/cofh/core/block/BlockCoFHBase.java#L280

At this point the metadata value is completely ignored.

This leads to getDrops returning the creative (meta 0) value for any block in CoFHCore
This bug was reported before a year ago but was brushed off putting the blame on twilight forest for not handling meta correctly, this proves this is not the case.

It also seems at no point (atleast in strongboxs flow) is the meta attempted to be restored by the info left over in the tileentity

**Comment by skyboy** [comment]
The pertinent data isn't part of the metadata to begin with. It's part of the tile.

The problem is that Twilight Forest is setting the block to air *before* getting the drops. This erases the tile and all its data.

**Comment by clienthax** [comment]
@skyboy Aha that makes sense, got it working now, thanks
