### ISSUE TITLE
Stalactites don't seem to support the "chunk-chance" object

### ISSUE THREAD

**Issue by TheDeviantCrafter** [CoFH/Feedback#1263]
I want to add rare stalactites containing diamond, lapis and emerald ores. I've had no issue making the stalactites generate, but it stops working when I add the "chunk-chance" object. I'd like to use that to make them rare but rich in ores.

This is the code I've been using:

```
"lapis_stalactite": {
			"distribution": "cave",
			"generator": {
					"type": "stalactite",
					"block": [
						{
							"name": "minecraft:stone",
							"weight": 78
						},
						{
							"name": "minecraft:lapis_ore",
							"weight": 20
						},
						{
							"name": "minecraft:diamond_ore",
							"weight": 2
						}
					],
					"material": [
						"minecraft:obsidian",
						"minecraft:stone"
					],
					"gen-body": [
						"minecraft:air",
						"minecraft:lava"
						],
					"smooth": false,
					"fat": false,
					"min-height": 10,
					"height-variance": 6,
					"height-mod": 3,
					"gen-size": 4,
					"size-variance": 1
				},
			"cluster-count": 2,
			"ceiling": true,
			"retrogen": false,
			"biome": "all",
			"dimension": {
				"restriction": "blacklist",
				"value": [
					-1,
					1
				]
			}
		},
```

This appears correctly in `/cofhworld list` and generates in the world. However, if I replace `"cluster-count": 2` with `"chunk-chance": 2` it stops working.

**Comment by KingLemming** [comment]
Please come by the Discord and hit the tech-support channel. Offhand I'm not sure if what you're trying to do is intended or not.

cluster-count and chunk-chance are not exclusive parameters though, so overwriting cluster-count entirely is incorrect.
