### ISSUE TITLE
[Thermal Expansion] Autonomous Activator dupping TNTs

### ISSUE THREAD

**Issue by Esctogrillo** [CoFH/Feedback#1263]
Video: https://youtu.be/Z19GOTVIMIU
Autonomous is dupping TNTs.
Using Thermos as server software.
Forge 1614.
ThermalExpansion-[1.7.10]4.1.4-247
CoFHCore-[1.7.10]3.1.3-328

**Comment by skyboy** [comment]
This is a bug with your server software as it does not happen in vanilla.
