### ISSUE TITLE
Visual Glitche with all kinds of ducts

### ISSUE THREAD

**Issue by DerpTehTurtle** [CoFH/Feedback#1265]
![image](https://user-images.githubusercontent.com/42400953/44436484-0b10a200-a57b-11e8-8e88-993ca6d05333.png)
 All types of ducts look like this. Something must be wrong.

I have other mods installed, I have my own resourcepack but it doesn't change the way ducts look and i also have optifine.

**Comment by KingLemming** [comment]
Yes, something is terribly wrong. You have Optifine.
