### ISSUE TITLE
[TD] [Logistics] Connection limit

### ISSUE THREAD

**Issue by firelizzard18** [CoFH/Feedback#1265]
Background:
I created a very large warp itemduct network. It was the backbone of my logistics network.

Scenario:
I connect any additional logistics pipe to the warp itemduct network.

What should happen:
The pipe and the duct connect. The duct's connector turns green. The pipe becomes part of the logistics network.

What actually happens:
**Every single connector between that warp itemduct network and any logistics pipe turns red.** The entire logistics network becomes fragmented into little pieces because the itemducts are no longer connecting to them.

Hacky fix:
Break up the warp itemduct network into smaller bits by placing basic logistics pipes at strategic locations.

Comments:
When I say 'warp itemduct network' I mean a bunch of warp itemducts that are all directly connected to each other, forming one giant branching pipe system that is all powered as a unit.

I cross-posted this issue on the logistics repo: RS485/LogisticsPipes#1069

**Comment by KingLemming** [comment]
This seems to be entirely an issue on LP's end. We use caching, there's no issue internally with any of our stuff, so not sure what they're doing.

**Comment by firelizzard18** [comment]
Bitterholz, from the LP linked issue:

> The Number of allowed Connections per Itemduct Line is there for a reason, ive debugged that with davboeki for a long time.
> 
> Basicly if we go above our current Cap of, 32 I think it is, you quickly run into problems where the discovery algorithm for routes to take, that is based on the Thermal Dynamics internal routing algorithm, runs so long that it halts your server and causes it to think its frozen and shuts down.
> 
> So, the Disconnecting effect is entirely Intentional.
> 
> Davboeki allready mitigated the crippling effects of the discovery by caching the routes once they have been taken, so discovery only runs exactly once for N routes, given the connections are unchanged. But everything over 32 I/O Connections on a Duct line is basically impossible to handle for a Server.
