### ISSUE TITLE
[TD] Impulse plate velocity limit

### ISSUE THREAD

**Issue by firelizzard18** [CoFH/Feedback#1266]
Feature request: Configurable speed limit for impulse plates. If an entity's speed does or would exceed a limit, then either don't accelerate it or scale it's velocity down to the max.

Related issue: Playing on a server and chaining a bunch of impulse plates has unexpected behavior. The server decides that the entity is going too fast and resets its position and/or velocity. This results in the entity freezing/jerking around a fixed point, as the impulse plate tries to accelerate the entity but the server refuses. Thus, chaining impulse plates doesn't work.

Related: How do I build ThermalExpansion? I tried to implement a simple fix on my own, but A) I had to change the minecraft version to `1.7.10-10.13.4.1448-1.7.10` to get `gradlew` to work and B) it doesn't build. Do I need to set up an environment with CoFHCore too? How do I do that?

**Comment by skyboy** [comment]
Impulse plates have configurable acceleration via the multimeter already, it's up to players to not violate whatever the server's limits are.

**Comment by firelizzard18** [comment]
That is not at all the issue. A) I can't change the server's limits.
They're baked in to minecraft/forge. If I could have changed them, I would
have. B) The acceleration is completely not the issue or the solution. The
acceleration from a single plate will never result in exceeding the speed
limit. But enough, chained, will. Even at the default acceleration. That
makes impulse plates utterly useless for anything other than extremely
simple setups.

**Comment by skyboy** [comment]
You can reduce the acceleration of later plates in the series, and even space them out to avoid hitting the limit. We even have a tool for duplicating settings: the red print, so this it not a deeply involved task.

**Comment by firelizzard18** [comment]
Which fails if I want a chain that you can enter at any plate
