### ISSUE TITLE
[TD] LuxDucts chain causes significant lag

### ISSUE THREAD

**Issue by Sorbe** [CoFH/Feedback#1267]
Modpack: Skyfactory 2.5.5 - Opened To LAN, Multiplayer
Version: ThermalDynamics-[1.7.10]1.2.0-171.jar

_LuxDucts_ are a pretty cool way to get a linear path / road / rail / _viaduct_ lit -- primarily because they only need to a _redstone_ signal at one end to light up all of them, no matter the length of the luxduct chain.

Within the Last Millennium, I put the _Luxducts_ on top of my _Long Range ViaDucts_ to light them up.  I was building a "BiFrost Bridge" using the _ViaDuct_ and _LuxDucts_ on top of a rainbow of stained glass.

Unfortunately, this made the game have extreme lag every few seconds if I travel in the _Viaduct_ (tested with a longish 1000 meters path).  Without the _luxducts_, the _viaduct_ worked great!  What seems to be happening is that when the chunks on the path try to render the _luxduct_, the _luxduct_ searches back/forward along the entire _luxduct_ path to find a _redstone_ signal to determine whether the freshly loaded _luxduct_ is currently on or off.  The net result is **severe lag** each time a new chunk is loaded.

I mitigated this "somewhat" by putting a _redstone block_ every 64m along the _luxduct_, but this still causes significant and obvious lag spikes every few seconds.  (See attached F3+ with lag graph)

*_Speculation: The lag could perhaps be fixed by having the each _luxduct_ retain its state when the chunk is saved/loaded and then only updating the _luxduct_ chain in response to adjacent _luxduct_ block updates.   But that's a wild guess at a fix without looking at the code. *_

(Screenshot with redstone blocks every 64 blocks attached, it was intolerable without this hack)
![2016-10-23_23 29 38](https://cloud.githubusercontent.com/assets/7958470/19636482/6d76de38-997e-11e6-8c90-9b953a15f859.png)

**Comment by skyboy** [comment]
The problem is mojang's lighting calculations combined with forge asynchronously loading chunks; every individual luxduct block, when it changes state needs to light or unlight a 4,096 block area and forge will sometimes load a chunk in your setup that contains no redstone, triggering a state change. There just isn't a good solution for this.
