### ISSUE TITLE
[Suggestion] Add visual effect to Vorpal procs

### ISSUE THREAD

**Issue by Lykrast** [CoFH/Feedback#1267]
Making critical strikes caused by Vorpal to spawn particles and/or play a sound to indicate them would be a really nice touch. Currently it is very hard to tell when they proc, which is a shame for such an impactful effect.

**Comment by KingLemming** [comment]
Sound is possible, visual apparently is not.

**Comment by KingLemming** [comment]
Never mind. Just requires a strange cast. :)

**Comment by Drullkus** [comment]
Thought I read “requires a strange cat” for a second!
