### ISSUE TITLE
Fluid duplication using fluiducts and another mod's tanks

### ISSUE THREAD

**Issue by Divran** [CoFH/Feedback#1270]
Hi

I was able to duplicate fluids using a combination of your fluiducts and tanks from another mod called Inductive Logistics. I reported the issue to IL's repo first, and the dev explained that the source of the issue is in your fluiducts.

Here is a link with more info
https://github.com/CD4017BE/InductiveLogistics/issues/32

You'd probably be better off asking questions of the dev of IL if you need any more info than what I have already provided in that thread, since I've got no clue how your code works.

Thanks!

**Comment by KingLemming** [comment]
We don't insert negative fluids. That's not how the ducts work at all. That issue says it's fixed on his end...which frankly given that it has never happened with any other tanks ever...yeah it was on his end. ;)
