### ISSUE TITLE
CoFHLib ISound Server Side

### ISSUE THREAD

**Issue by blunty666** [CoFH/Feedback#1270]
It's looks as though something is using an ISound reference on the server side.
[http://pastebin.com/Tj0zq9zS](http://pastebin.com/Tj0zq9zS)

Might be something to do with the tesserect as this seems to cause the crash when I try to use it as a peripheral for ComputerCraft via OpenPeripherals.

Happens during runtime and doesn't throw a full crash, but causes the ComputerCraft Lua thread to hang and OpenPeripherals outputs the above error.

Relevant Mod Versions:
Forge - 1614
CoFHCore - 3.1.3.327
ThermalFoundation - 1.2.5-115
ThermalExpansion - 4.1.4-247
ComputerCraft - 1.75
OpenModsLib - 0.9.1
OpenPeripheralCore - 1.3
OpenPeripheralIntegration - 0.5
FastCraft - 1.23

**Comment by KingLemming** [comment]
This is an OpenPeripherals error. That interface is client side only and we have code in place to handle it. They aren't handling it.
