### ISSUE TITLE
Pulverizer stops pulverizing. Bug

### ISSUE THREAD

**Issue by Sinfuldeity** [CoFH/Feedback#1271]
I was pulverizing a mass amount of gold and smelting it in my redstone furnace automatically. when i reached 64 cinnabar and the gold stopped pulverizing, exporting all of the currently pulverized gold to the redstone furnace directly beside it. Upon running out of pulverized gold inside the current pulverizer, the import slot being full of gold and the secondary export slot having a stack of cinnibar, i swapped worlds to check what a machine was that i needed to make. when returning to the world. i was unable to pulverize any items until i relaunched minecraft. i even selected brand new pulverizers that i just crafted, gave them energy and they would not pulverize anything either. i dont know how to explain it too well, but i left the world and loaded a different one, upon returning it was broken, thats about it.

**Comment by skyboy** [comment]
You need to handle secondary outputs of the pulverizer or it will stop so it doesn't void items.
