### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by GabrielGamer66** [CoFH/Feedback#1272]
I have updated Optifine and I get this crash report
[crash-2018-08-31_13.27.01-client.txt](https://github.com/CoFH/Feedback/files/2340840/crash-2018-08-31_13.27.01-client.txt)

**Comment by KingLemming** [comment]
Cool. Go tell Optifine.

**Comment by covers1624** [comment]
Also, CoFH doesnt support 1.7.10 anymore, double wammy sorry..
