### ISSUE TITLE
[TD] Servos not pulling correctly

### ISSUE THREAD

**Issue by Holzsteiner** [CoFH/Feedback#1272]
I'm saying "not pulling correctly", because retrievers act differently at the same task which in my eyes they shouldn't do.

Example having this setup
![2016-10-30_13 03 46](https://cloud.githubusercontent.com/assets/23149790/19836464/8aff3bf8-9ea1-11e6-878f-65df7e7a00b9.png)

and 64 copper in the wooden chest like this
![2016-10-30_13 04 12](https://cloud.githubusercontent.com/assets/23149790/19836470/a4182ba4-9ea1-11e6-8f41-3b268bbb5080.png)

Now activating the servo with 64 stack extracting size results in two pulls, first the first slot and then the second slot being pulled into the iron chest.

Doing the same thing without the servo but with a retriever will only take one pull directly sending 64 copper into the iron chest.

I don't know if this is intended, but if yes, it really makes no sense.
If it does make sense an explanation would be great, thanks

**Comment by KerbalNerd123** [comment]
Did you only use resont servo things? try using a siglanum servo and see

**Comment by KingLemming** [comment]
Intentional. Computational efficiency.
