### ISSUE TITLE
Crash on Startup-> Latest CofH Core (.20) Latest Forge (.2759)

### ISSUE THREAD

**Issue by Nick-77ab2** [CoFH/Feedback#1273]
After checking through the Issues, finding one related and checking to see if it the same exact issue, I can conclude that this might be related in the fact that it's a CofH and Forge issue, but i can't confirm more than that. Here's the Error (on a server startup): https://pastebin.com/M91BvDWv
If this is the same issue, thanks for letting me know, as always thanks for your work on such a fabulous set of mods. ;P (all other mods are at the latest version as well)

**Comment by Nick-77ab2** [comment]
The issue calls out Thermal Foundation, though I'm not sure if that's what's actually going on.

**Comment by KingLemming** [comment]
You've installed something wrong. You may have installed CoFHLib when you explicitly should not be doing that.

100% it's something with your install and not our code though.

**Comment by Nick-77ab2** [comment]
Thanks for letting me know, during the process I'm pretty sure i thought it was CofH Lib but wrote it off, thanks.
