### ISSUE TITLE
Suggestion: Arboreal Extractor: Craft/Modtweaker Support

### ISSUE THREAD

**Issue by Guinaro** [CoFH/Feedback#1275]
When looking over the provided functionality of Modtweaker support for Thermal Expansion's Arboreal Extractor. I see this device is missing.
I hope you could extend the functionality of this device with modtweaker support so that the following is possible:

- [ ] tapper.removeTree(log) (Remove trees permanently or allow for the next command to alter the previously removed tree)
- [ ] tapper.addTree(log, fluid, amount) (Configure any log to provide a specific fluid and amount)
- [ ] tapper.removeAllTrees() (Easier to start with a clean slate if you want to do a lot of tweaking)

Reasoning:
I'm trying to create an integrated tech modpack uses several tech mods like TE, EnderIO, Immersive Engineering, Industrial Foregoing, ...
The goal is to limit each machine useable in the modpack to have defined non-overlapping functionality.
Currently the Industrial Foregoing Tree Fluid Extractor and TE's Arboreal Extractor provide likewise functionality, but cannot be configured/integrated. The Arboreal Extractor has in essence the capabilities to provide various fluids depending on the tree already built in, plus has the added advantage that it doesn't destroy trees. I hope you consider adding support for modpack makers to tweak your machine to fit in the whole pack, rather than being stuck with hardcoded defaults.

Thank you for your consideration,
Guinaro

**Comment by KingLemming** [comment]
Sorry, but this isn't really feasible due to how the tapper has to determine tree validity. There's a lot behind the scenes that has to happen with blockstates.

1.13 *might* allow for something like this, but 1.12 just doesn't.

**Comment by Guinaro** [comment]
Would it then be feasable to alter the fluid stack (type and amount) for already registered trees including those added for compatibility?
This would probably need a dump handler /te tapper registeredtrees.
And a crafttweaker tapper.altertree(treeidentifier, fluidstack)

Guinaro
