### ISSUE TITLE
Please help! Thermal Expansion crash when right clicking a tesseract.

### ISSUE THREAD

**Issue by Strider060103** [CoFH/Feedback#1276]
Hi,
I have a problem concerning the tesseract, whenever I right click a tesseract to open it's GUI, my game freezes for a few seconds then crashes. Please help!

A link to the crash report on pastebin is down below.

http://pastebin.com/VqividZQ

**Comment by KingLemming** [comment]
This isn't tech support, and please don't report problems unless you are using up to date mods.

You aren't - that is almost certainly the issue.
