### ISSUE TITLE
Thermal Foundation Fluiduct + Agricraft Tank crash

### ISSUE THREAD

**Issue by Black0305** [CoFH/Feedback#1278]
Game crashes when you break a filled Fluiduct from Thermal Foundation, which is attached to a AgriCraft tank.
Crash: https://pastebin.com/19uEKcCB

Not sure if TF or Agricraft caused this, so I opend a issue there aswell. https://github.com/AgriCraft/AgriCraft/issues/1184

**Comment by KingLemming** [comment]
Bit of both, kinda. They're actively throwing a crash on their end when they should be handling it more gracefully, like literally every other tank does. ;)

But, there is a corner case on our end that precipitates this. I've got a fix.
