### ISSUE TITLE
Latest DEV builds of TE on curse

### ISSUE THREAD

**Issue by crunkazcanbe** [CoFH/Feedback#128]
As the title says , and game loads fine , but I see this http://pastebin.com/fqSW4tTN in the console . It looks important . :) So I thought I would help .

Thank you!

-Crunk

EDIT: I See this may be a LogisticsPipes issue with them needing to update with your API maybe , but still not for sure . Just a wild guess .

**Comment by KingLemming** [comment]
Ahem. CurseForge. And yes, that's entirely on their end. Nothing to do with their API, they're looking for classes which have moved.
