### ISSUE TITLE
Energy cells' randomly changing

### ISSUE THREAD

**Issue by Gamingdaredevil** [CoFH/Feedback#128]
I've stated to get a random problem energy cell changes randomly in my inventory, say i have a resonant one it will turn to any other one and keep going.

**Comment by KingLemming** [comment]
Yeah we need a video of this as well as a modlist.

Offhand I can basically guarantee the issue isn't in our code.

**Comment by Gamingdaredevil** [comment]
https://youtu.be/-pHAiFNyLMc

http://pastebin.com/iLQxQGtX

**Comment by Gamingdaredevil** [comment]
This was on my server so far i can't replicated it on single player

**Comment by KingLemming** [comment]
Ohhh 1.7.10. Sorry, but we're not supporting that anymore. I have an idea of what might cause this, and it's basically something which charges/discharges items in inventory and does it VERY VERY improperly.
