### ISSUE TITLE
[COFHcore][1.7.10] server freezing

### ISSUE THREAD

**Issue by Cronosus** [CoFH/Feedback#1281]
hello, i have on server problem with freezing.
i report this to thermos too, and they respond its COFHcore problem.
help please.

**Server Log:** 
http://cronos.wz.cz/mc/281116latest.log
**FML Log(s):**
http://cronos.wz.cz/mc/281116fml-server-1.log
**Explanation of issue:**
server freezing, and can't restart (no crashing)
**How to recreate this issue:**
after some time of server running
**Modpack Name:** 
traincraft.cz (on technic platform)
**Mods Installed:**
http://cronos.wz.cz/mc/mods.PNG
**Plugins Installed:**
http://cronos.wz.cz/mc/plugins.PNG
**Thermos Version:**
Build 58
**COFHcore Version:**
CoFHCore-[1.7.10]3.1.3-328
**Forge Version:**
10.13.4.1617.1710

thanks in advance

**Comment by KingLemming** [comment]
Sorry, we don't offer Thermos support. Unfamiliar with it and this doesn't happen with Forge only.
