### ISSUE TITLE
Installing the mod 

### ISSUE THREAD

**Issue by Runnerxenomorph** [CoFH/Feedback#1282]
Whenever I installed the latest version of redstone arsenal, and get the mod that requires it to work, which is also at it's latest version, I get a message that says "You must include the right dependencies for CoFH Core: Requires redstone flux 2.0.2 or above, and below 2.1.0 (missing)"

**Comment by KingLemming** [comment]
Okay. So install it. What's the problem?

Redstone Flux is NOT Redstone Arsenal.
