### ISSUE TITLE
UI's incompatible with ViveCraft

### ISSUE THREAD

**Issue by KillerCoati** [CoFH/Feedback#1283]
So I've been enjoying minecraft in VR on the HTC Vive thanks to the guys over at ViveCraft which supports 1.7.10 with forge - I have a ton of mods installed with custom machines and UI's much like the thermal mods you offer yet your UIs are incompatible with the selection system ViveCraft uses for some reason. No other mod I've come across have this problem. You can still select things, it's just the 'cursor' is invisible when over your UI. ViveCraft devs confirmed its incompatible but haven't spoken to their resident forge expert yet (as the guy i spoke to was working on their latest minecraft version support)  so might be fixable their end, but not sure why yours is the only mod to create this error. Otherwise, your mods are awesome, thank you so much for all your hard work :)

**Comment by KingLemming** [comment]
We use a custom modular UI system which allows for really rapid development and functionality layering.

Even so, we don't use anything outside of standard OpenGL calls, so it's really on them to fix, sorry.
