### ISSUE TITLE
Thermal Foundation problems 

### ISSUE THREAD

**Issue by lordHelix15** [CoFH/Feedback#1284]
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Thermal Foundation (thermalfoundation)
the crash report+mods:
--- Minecraft Crash Report ----

WARNING: coremods are present:
  CoreMod (Aroma1997Core-1.12.2-2.0.0.0.b156.jar)
Contact their authors BEFORE contacting forge

// Sorry :(

Time: 9/11/18 4:05 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Thermal Foundation (thermalfoundation)
Caused by: java.lang.NoClassDefFoundError: cofh/core/fluid/BlockFluidCore
	at cofh.thermalfoundation.block.BlockOreFluid.<clinit>(BlockOreFluid.java:429)
	at cofh.thermalfoundation.init.TFBlocks.preInit(TFBlocks.java:23)
	at cofh.thermalfoundation.ThermalFoundation.preInit(ThermalFoundation.java:83)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: cofh.core.fluid.BlockFluidCore
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 43 more
Caused by: java.lang.VerifyError: class cofh.core.fluid.BlockFluidCore overrides final method getDensity.()I
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 45 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 346559800 bytes (330 MB) / 1056964608 bytes (1008 MB) up to 1073741824 bytes (1024 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.4.2759 64 mods loaded, 64 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                   | Version           | Source                                              | Signature                                |
	|:----- |:-------------------- |:----------------- |:--------------------------------------------------- |:---------------------------------------- |
	| UCH   | minecraft            | 1.12.2            | minecraft.jar                                       | None                                     |
	| UCH   | mcp                  | 9.42              | minecraft.jar                                       | None                                     |
	| UCH   | FML                  | 8.0.99.99         | forge-1.12.2-14.23.4.2759.jar                       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge                | 14.23.4.2759      | forge-1.12.2-14.23.4.2759.jar                       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | actuallyadditions    | 1.12.2-r140       | ActuallyAdditions-1.12.2-r140.jar                   | None                                     |
	| UCH   | baubles              | 1.5.2             | Baubles-1.12-1.5.2.jar                              | None                                     |
	| UCH   | actuallybaubles      | 1.1               | ActuallyBaubles-1.12-1.1.jar                        | None                                     |
	| UCH   | appliedenergistics2  | rv6-alpha-4       | appliedenergistics2-rv6-alpha-4.jar                 | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
	| UCH   | bdlib                | 1.14.3.12         | bdlib-1.14.3.12-mc1.12.2.jar                        | None                                     |
	| UCH   | ae2stuff             | 0.7.0.4           | ae2stuff-0.7.0.4-mc1.12.2.jar                       | None                                     |
	| UCH   | aroma1997core        | 2.0.0.0.b156      | Aroma1997Core-1.12.2-2.0.0.0.b156.jar               | dfbfe4c473253d8c5652417689848f650b2cbe32 |
	| UCH   | aroma1997sdimension  | 2.0.0.2.b77       | Aroma1997s-Dimensional-World-1.12.2-2.0.0.2.b77.jar | dfbfe4c473253d8c5652417689848f650b2cbe32 |
	| UCH   | aromabackup          | 2.1.1.3           | AromaBackup-1.12.2-2.1.1.3.jar                      | dfbfe4c473253d8c5652417689848f650b2cbe32 |
	| UCH   | aromabackuprecovery  | 2.1.1.3           | AromaBackup-1.12.2-2.1.1.3.jar                      | None                                     |
	| UCH   | betterbedrockgen     | 6.0.2             | BetterBedrockGenerator-1.12-6.1.1.jar               | None                                     |
	| UCH   | betterbuilderswands  | 0.11.1            | BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar     | None                                     |
	| UCH   | buildinggadgets      | 2.2.1             | BuildingGadgets-2.2.1.jar                           | None                                     |
	| UCH   | chameleon            | 1.12-4.1.3        | Chameleon-1.12-4.1.3.jar                            | None                                     |
	| UCH   | clumps               | 3.1.1             | Clumps-3.1.1.jar                                    | None                                     |
	| UCH   | codechickenlib       | 3.2.1.351         | CodeChickenLib-1.12.2-3.2.1.351-universal.jar       | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCH   | redstoneflux         | 2.0.2             | RedstoneFlux-1.12-2.0.2.3-universal.jar             | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCH   | cofhcore             | 4.5.2             | CoFHCore-1.12.2-4.5.2.19-universal.jar              | None                                     |
	| UCH   | cofhworld            | 1.2.0             | CoFHWorld-1.12.2-1.2.0.5-universal.jar              | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCH   | compactmachines3     | 3.0.12            | compactmachines3-1.12.2-3.0.12-b215.jar             | None                                     |
	| UCH   | craftingtweaks       | 8.1.9             | CraftingTweaks_1.12.2-8.1.9.jar                     | None                                     |
	| UCH   | cucumber             | 1.1.1             | Cucumber-1.12.2-1.1.1.jar                           | None                                     |
	| UCH   | diethopper           | 1.1               | diethopper-1.1.jar                                  | None                                     |
	| UCH   | valkyrielib          | 1.12.2-2.0.15.1   | valkyrielib-1.12.2-2.0.15.1.jar                     | None                                     |
	| UCH   | environmentaltech    | 1.12.2-2.0.15.1   | environmentaltech-1.12.2-2.0.15.1.jar               | None                                     |
	| UCH   | etlunar              | 1.12.2-2.0.15.1   | etlunar-1.12.2-2.0.15.1.jar                         | None                                     |
	| UCH   | exnihilocreatio      | 1.12-0.2.4        | exnihilocreatio-1.12-0.2.4.jar                      | None                                     |
	| UCH   | forgivingvoid        | 1.0.18            | ForgivingVoid_1.12.2-1.0.18.jar                     | None                                     |
	| UCH   | ic2                  | 2.8.89-ex112      | industrialcraft-2-2.8.89-ex112.jar                  | de041f9f6187debbc77034a344134053277aa3b0 |
	| UCEE  | thermalfoundation    | 2.5.0             | ThermalFoundation-1.12.2-2.5.0.19-universal.jar     | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UC    | advgenerators        | 0.9.20.12         | generators-0.9.20.12-mc1.12.2.jar                   | None                                     |
	| UC    | inventorysorter      | 1.13.3+57         | inventorysorter-1.12.2-1.13.3+57.jar                | None                                     |
	| UC    | jaopcacustom         | 1.12-2.2.2.14     | JAOPCACustom-1.12-2.2.2.14.jar                      | None                                     |
	| UC    | jaopca               | 1.12.2-2.2.8.91   | JAOPCA-1.12.2-2.2.8.91.jar                          | None                                     |
	| UC    | oredictinit          | 1.12.2-2.2.1.68   | JAOPCA-1.12.2-2.2.8.91.jar                          | None                                     |
	| UC    | jei                  | 4.12.0.214        | jei_1.12.2-4.12.0.214.jar                           | None                                     |
	| UC    | jeiintegration       | 1.5.1.36          | jeiintegration_1.12.2-1.5.1.36.jar                  | None                                     |
	| UC    | mcjtylib_ng          | 3.0.4             | mcjtylib-1.12-3.0.4.jar                             | None                                     |
	| UC    | mekanism             | 1.12.2-9.4.13.349 | Mekanism-1.12.2-9.4.13.349.jar                      | None                                     |
	| UC    | mekanismgenerators   | 9.4.11            | MekanismGenerators-1.12.2-9.4.13.349.jar            | None                                     |
	| UC    | mysticalagriculture  | 1.6.13            | MysticalAgriculture-1.12-1.6.13.jar                 | None                                     |
	| UC    | mysticalagradditions | 1.2.8             | mysticalagradditions-1.12-1.2.8.jar                 | None                                     |
	| UC    | naturescompass       | 1.5.1             | NaturesCompass-1.12.2-1.5.1.jar                     | None                                     |
	| UC    | oreexcavation        | 1.4.123           | OreExcavation-1.4.123.jar                           | None                                     |
	| UC    | reborncore           | 3.10.0.332        | RebornCore-1.12.2-3.10.0.332-universal.jar          | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
	| UC    | skyresources         | 2.3.7             | skyresources-2.3.7.jar                              | None                                     |
	| UC    | sc                   | 1.2.2.2           | Sky+Compression-1.2.2.2.jar                         | None                                     |
	| UC    | starterkit           | 1.12.2-1.0.15.1   | starterkit-1.12.2-1.0.15.1.jar                      | None                                     |
	| UC    | storagedrawers       | 1.12-5.3.5        | StorageDrawers-1.12.2-5.3.7.jar                     | None                                     |
	| UC    | theoneprobe          | 1.4.23            | theoneprobe-1.12-1.4.23.jar                         | None                                     |
	| UC    | thermalexpansion     | 5.5.0             | ThermalExpansion-1.12.2-5.5.0.29-universal.jar      | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UC    | thermaldynamics      | 2.5.1             | ThermalDynamics-1.12.2-2.5.1.14-universal.jar       | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UC    | thermalinnovation    | 0.3.0             | ThermalInnovation-1.12.2-0.3.0.7-universal.jar      | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UC    | topaddons            | 1.12.2-1.8.0      | topaddons-1.12.2-1.8.0.jar                          | None                                     |
	| UC    | treegrowingsimulator | 0.0.4             | TreeGrowingSimulator2017-1.0.1.jar                  | None                                     |
	| UC    | valkyriecompat       | 1.12.2-2.0.15.1   | valkyriecompat-1.12.2-2.0.15.1.jar                  | None                                     |
	| UC    | universalmodifiers   | 1.12.2-1.0.9a     | valkyrielib-1.12.2-2.0.15.1.jar                     | None                                     |
	| UC    | voidislandcontrol    | 1.4.2             | voidislandcontrol-1.4.2.jar                         | None                                     |
	| UC    | xaerominimap         | 1.14.5            | Xaeros_Minimap_1.14.5_Forge_1.12.jar                | None                                     |
	| UC    | wrapup               | 1.12-1.1.3        | WrapUp-1.12-1.1.3.jar                               | None                                     |

	Loaded coremods (and transformers): 
CoreMod (Aroma1997Core-1.12.2-2.0.0.0.b156.jar)
  
	AE2 Version: alpha rv6-alpha-4 for Forge 14.23.3.2655
	List of loaded APIs: 
		* actuallyadditionsapi (34) from ActuallyAdditions-1.12.2-r140.jar
		* appliedenergistics2|API (rv6) from appliedenergistics2-rv6-alpha-4.jar
		* AromaBackupAPI (1.0) from AromaBackup-1.12.2-2.1.1.3.jar
		* Baubles|API (1.4.0.2) from Baubles-1.12-1.5.2.jar
		* cofhapi (2.5.0) from CoFHCore-1.12.2-4.5.2.19-universal.jar
		* CraftingTweaks|API (4.1) from CraftingTweaks_1.12.2-8.1.9.jar
		* JustEnoughItemsAPI (4.13.0) from jei_1.12.2-4.12.0.214.jar
		* MekanismAPI|core (9.0.0) from Mekanism-1.12.2-9.4.13.349.jar
		* MekanismAPI|energy (9.0.0) from Mekanism-1.12.2-9.4.13.349.jar
		* MekanismAPI|gas (9.0.0) from Mekanism-1.12.2-9.4.13.349.jar
		* MekanismAPI|infuse (9.0.0) from Mekanism-1.12.2-9.4.13.349.jar
		* MekanismAPI|laser (9.0.0) from Mekanism-1.12.2-9.4.13.349.jar
		* MekanismAPI|transmitter (9.0.0) from Mekanism-1.12.2-9.4.13.349.jar
		* MekanismAPI|util (9.0.0) from Mekanism-1.12.2-9.4.13.349.jar
		* reborncoreAPI (3.10.0.332) from RebornCore-1.12.2-3.10.0.332-universal.jar
		* reborncoreAPI|Power (3.10.0.332) from RebornCore-1.12.2-3.10.0.332-universal.jar
		* reborncoreAPI|Recipe (3.10.0.332) from RebornCore-1.12.2-3.10.0.332-universal.jar
		* reborncoreAPI|Tile (3.10.0.332) from RebornCore-1.12.2-3.10.0.332-universal.jar
		* StorageDrawersAPI (2.1.0) from StorageDrawers-1.12.2-5.3.7.jar
		* StorageDrawersAPI|event (2.1.0) from StorageDrawers-1.12.2-5.3.7.jar
		* StorageDrawersAPI|registry (2.1.0) from StorageDrawers-1.12.2-5.3.7.jar
		* StorageDrawersAPI|render (2.1.0) from StorageDrawers-1.12.2-5.3.7.jar
		* StorageDrawersAPI|storage (2.1.0) from StorageDrawers-1.12.2-5.3.7.jar
		* StorageDrawersAPI|storage-attribute (2.1.0) from StorageDrawers-1.12.2-5.3.7.jar
		* theoneprobe_api (1.4.4) from theoneprobe-1.12-1.4.23.jar
		* valkyrielib.api (1.12.2-2.0.10a) from valkyrielib-1.12.2-2.0.15.1.jar

**Comment by KingLemming** [comment]
Congratulations. You updated Forge but failed to update CoFH Core.

There is a very apparent issue here: #1208.

Whenever you get a crash, always always always update before you come here.

**Comment by lordHelix15** [comment]
Ok and Thanks
