### ISSUE TITLE
question is this intended?

### ISSUE THREAD

**Issue by CharCharthemonkey** [CoFH/Feedback#1285]
in the pictures it shows a very simple way to make a quartz farm using a thermal expansion pulverizer and redstone furnace is that intended or no? asking cause alot of ppl i asked in discord said its a dupe glitch so was wondering
![2018-09-12_21 31 48](https://user-images.githubusercontent.com/30783285/45529696-336f7300-b7ac-11e8-9622-c12c80d4b540.png)
![2018-09-12_21 31 54](https://user-images.githubusercontent.com/30783285/45529699-35393680-b7ac-11e8-9981-ff9d48b6c376.png)

hope to know soon please and thank you <3 (ps love the mod keep up the good work)

**Comment by KingLemming** [comment]
The issue tracker isn't for questions. We have a Discord for that.

And honestly I don't know what's going on there - that's a recipe being added by another mod.
