### ISSUE TITLE
[Thermal Foundation 1.7.10]  (Bug maybe) Blitz,Basalz and  Blizz  are INVISIBLE! There Projectiles aren't the mob  is

### ISSUE THREAD

**Issue by KerbalNerd123** [CoFH/Feedback#1285]
So in Thermal Foundation the Blitz,Basalz and Blizz are invisible to me.Can someone help me here? Only the mob is invisible,But there shooting Projectiles aren't invisible.(By invisible i mean i can't see them).I can hear its noises and all that stuff but can't see it.I have a mini-map mod installed and the mini-map also doesn't know there is a hostile mob (in this case the blitz or blizz) I checked the thermal foundation.jar if the mob's textures are missing or something like that,But the textures are there and there .class file are also there to.
so can anyone help me for tell me what's the problem and yes I have CoFH file in  my mods folder

Ok here is the Blitz attacking me in my survival world

![2016-12-09_12 17 24](https://cloud.githubusercontent.com/assets/24470269/21040971/39ee641e-be0e-11e6-99ca-47c758cdb33c.png)

![2016-12-09_12 17 46](https://cloud.githubusercontent.com/assets/24470269/21040815/4cc32936-be0d-11e6-8be1-280445776ff7.png)

**Comment by KingLemming** [comment]
We need a modlist, but I can pretty confidently say this isn't our fault. Something is jacking with the mobs.

**Comment by KerbalNerd123** [comment]
I mean when I started installing mods, the first few mods I installed were TF,TE and TD in those days i had only like 16 mods. And even those days I had the same problems for sure. But still can you at least  tell me what kinds of things can jack up the mob? And BTW, I have installed like tinker'sCon.,OpenBlocks,Journy Map,ExtraUtilities,Flan's mod,Build Craft ,IndustrialCraft2 and like that sort of mods I have And many more to.And no I don't have like Mutant Creatures mod like that. I tried even downloaded different versions of TF.TE and TD and I still have the problem
