### ISSUE TITLE
Upgrading multiple caches in project bench leads to duplicates

### ISSUE THREAD

**Issue by Psy185** [CoFH/Feedback#1286]
Hi,

When I wanted to upgrade some caches to hardened caches on a ProjectRed Expansion's Project Bench I stumbled upon a bug. Let's say I have 4 different caches filled with different items (e.g. Dirt, Stone, Wood, Sand). I put the cache filled with dirt along with 4 Invar ingots into the crafting grid of the project bench. The other three caches and ingots are placed in the bench's inventory. I Shift-click on the hardened cache filled with dirt so I upgrade all caches in the inventory at once.

Expected result: 1 cache filled with dirt, 1 cache filled with stone, 1 cache filled with wood, 1 cache filled with sand

But I get 4 caches filled with dirt.

I'm using ThermalExpansion-[1.7.10]4.1.4-247.jar

See attached screenshot:
![2016-12-17_00 28 45](https://cloud.githubusercontent.com/assets/24615128/21281773/d2ac5058-c3ef-11e6-98fc-9d55293f340e.png)

**Comment by KingLemming** [comment]
This is an issue with Project Red, not us.
