### ISSUE TITLE
Server don't open

### ISSUE THREAD

**Issue by Baumme** [CoFH/Feedback#1287]
When I try to launch my server , to use ThermalExpansion/Dynamics... I must have CoFH core, I just installed it and.. My server don't open
There's the error http://pastebin.com/4rT419MH
It only happens when I try to use CoFH core
I couldn't update forge because it's a Cauldron server

**Comment by KingLemming** [comment]
Sorry, but this isn't tech support. Tons of other people run it without issue. We don't officially support Cauldron, but do require specific versions of Forge. That might be your problem.
