### ISSUE TITLE
(Resonant) Servo - Nearest First vs. Furthest first

### ISSUE THREAD

**Issue by E14** [CoFH/Feedback#1288]
I am assuming my irritation by the servo behaviour is a bug.

I have the following test-setup:
![2017-01-01_14 51 25](https://cloud.githubusercontent.com/assets/1640391/21581455/d0a8d20a-d032-11e6-9249-00c40a30cf46.png)

The servo is pulling items from Chest 1 (the right one)
* If I set the servo to deliver **NEAREST-FIRST**, it will deliver to chest 3, which is the one that is furthest away (in both X and Z coordinates)
* If I set the servo to deliver **FURTHEST-FIRST**, it will deliver to chest 2, which is the one that is closest

This behaviour is repeatable every single time.

In my opinion, this is the complete opposite of what should happen, unless there is something else going on.

(TD Version 1.7.10 / 1.2.0-171)

**Comment by KingLemming** [comment]
Not a bug. You're using Vacuum Ducts. Those change the weighting of the system so that the "farther" chest is seen as closer, as there are more ducts on the path and each one is a -1000 weight on the distance.

**Comment by E14** [comment]
So each duct (block) actually reduces the distance? How would the different ducts behave in this scenario?

**Comment by XFactHD** [comment]
The normal duct adds one block to the distance per block used and the dense duct adds (most likely) 1000 blocks of distance per block.
