### ISSUE TITLE
i cant start the game

### ISSUE THREAD

**Issue by elestratega** [CoFH/Feedback#1288]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  ShetiPhian-ASM (shetiphiancore-1.12.0-3.5.6.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.181.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.37.jar)
  OpenModsCorePlugin (OpenModsLib-1.12.2-0.11.5.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-85.jar)
Contact their authors BEFORE contacting forge

// Don't be sad, have a hug! <3

Time: 9/15/18 11:00 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Thermal Foundation (thermalfoundation)
Caused by: java.lang.NoClassDefFoundError: cofh/core/fluid/BlockFluidCore
	at cofh.thermalfoundation.block.BlockOreFluid.<clinit>(BlockOreFluid.java:429)
	at cofh.thermalfoundation.init.TFBlocks.preInit(TFBlocks.java:23)
	at cofh.thermalfoundation.ThermalFoundation.preInit(ThermalFoundation.java:83)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:627)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: cofh.core.fluid.BlockFluidCore
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 43 more
Caused by: java.lang.VerifyError: class cofh.core.fluid.BlockFluidCore overrides final method getDensity.()I
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 45 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_181, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 269649008 bytes (257 MB) / 653348864 bytes (623 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.4.2749 Optifine OptiFine_1.12.2_HD_U_E2 53 mods loaded, 53 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                                | Version       | Source                                          | Signature                                |
	|:----- |:--------------------------------- |:------------- |:----------------------------------------------- |:---------------------------------------- |
	| UCH   | minecraft                         | 1.12.2        | minecraft.jar                                   | None                                     |
	| UCH   | mcp                               | 9.42          | minecraft.jar                                   | None                                     |
	| UCH   | FML                               | 8.0.99.99     | forge-1.12.2-14.23.4.2749.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge                             | 14.23.4.2749  | forge-1.12.2-14.23.4.2749.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | micdoodlecore                     |               | minecraft.jar                                   | None                                     |
	| UCH   | openmodscore                      | 0.11.5        | minecraft.jar                                   | None                                     |
	| UCH   | appliedenergistics2               | rv5-stable-11 | appliedenergistics2-rv5-stable-11.jar           | None                                     |
	| UCH   | betterslabsmod                    | 0.0.7         | Better+Slabs+Mod+[0.0.7].jar                    | None                                     |
	| UCH   | buildcraftlib                     | 7.99.17       | buildcraft-7.99.17.jar                          | None                                     |
	| UCH   | buildcraftcore                    | 7.99.17       | buildcraft-7.99.17.jar                          | None                                     |
	| UCH   | buildcraftbuilders                | 7.99.17       | buildcraft-7.99.17.jar                          | None                                     |
	| UCH   | buildcraftenergy                  | 7.99.17       | buildcraft-7.99.17.jar                          | None                                     |
	| UCH   | buildcraftfactory                 | 7.99.17       | buildcraft-7.99.17.jar                          | None                                     |
	| UCH   | buildcraftrobotics                | 7.99.17       | buildcraft-7.99.17.jar                          | None                                     |
	| UCH   | buildcrafttransport               | 7.99.17       | buildcraft-7.99.17.jar                          | None                                     |
	| UCH   | buildcraftsilicon                 | 7.99.17       | buildcraft-7.99.17.jar                          | None                                     |
	| UCH   | codechickenlib                    | 3.2.1.351     | CodeChickenLib-1.12.2-3.2.1.351-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCH   | redstoneflux                      | 2.0.2         | RedstoneFlux-1.12-2.0.2.3-universal.jar         | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCH   | cofhcore                          | 4.5.1         | CoFHCore-1.12.2-4.5.1.17-universal.jar          | None                                     |
	| UCH   | cofhworld                         | 1.2.0         | CoFHWorld-1.12.2-1.2.0.5-universal.jar          | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCH   | endercore                         | 1.12.2-0.5.37 | EnderCore-1.12.2-0.5.37.jar                     | None                                     |
	| UCH   | jei                               | 4.11.0.212    | jei_1.12.2-4.11.0.212.jar                       | None                                     |
	| UCEE  | thermalfoundation                 | 2.5.0         | ThermalFoundation-1.12.2-2.5.0.18-universal.jar | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UC    | thermalexpansion                  | 5.5.0         | ThermalExpansion-1.12.2-5.5.0.29-universal.jar  | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UC    | enderio                           | 5.0.31        | EnderIO-1.12.2-5.0.31.jar                       | None                                     |
	| UC    | enderiointegrationtic             | 5.0.31        | EnderIO-1.12.2-5.0.31.jar                       | None                                     |
	| UC    | enderiobase                       | 5.0.31        | EnderIO-1.12.2-5.0.31.jar                       | None                                     |
	| UC    | enderioconduits                   | 5.0.31        | EnderIO-1.12.2-5.0.31.jar                       | None                                     |
	| UC    | enderioconduitsappliedenergistics | 5.0.31        | EnderIO-1.12.2-5.0.31.jar                       | None                                     |
	| UC    | enderioconduitsopencomputers      | 5.0.31        | EnderIO-1.12.2-5.0.31.jar                       | None                                     |
	| UC    | enderioconduitsrefinedstorage     | 5.0.31        | EnderIO-1.12.2-5.0.31.jar                       | None                                     |
	| UC    | enderiointegrationforestry        | 5.0.31        | EnderIO-1.12.2-5.0.31.jar                       | None                                     |
	| UC    | enderiointegrationticlate         | 5.0.31        | EnderIO-1.12.2-5.0.31.jar                       | None                                     |
	| UC    | enderiomachines                   | 5.0.31        | EnderIO-1.12.2-5.0.31.jar                       | None                                     |
	| UC    | enderiopowertools                 | 5.0.31        | EnderIO-1.12.2-5.0.31.jar                       | None                                     |
	| UC    | shetiphiancore                    | 3.5.6         | shetiphiancore-1.12.0-3.5.6.jar                 | None                                     |
	| UC    | endertanks                        | 1.6.6         | endertanks-1.12.0-1.6.6.jar                     | None                                     |
	| UC    | ic2                               | 2.8.73-ex112  | industrialcraft-2-2.8.73-ex112.jar              | de041f9f6187debbc77034a344134053277aa3b0 |
	| UC    | galacticraftcore                  | 4.0.1.181     | GalacticraftCore-1.12.2-4.0.1.181.jar           | None                                     |
	| UC    | galacticraftplanets               | 4.0.1.181     | Galacticraft-Planets-1.12.2-4.0.1.181.jar       | None                                     |
	| UC    | waila                             | 1.8.26        | Hwyla-1.8.26-B41_1.12.2.jar                     | None                                     |
	| UC    | openmods                          | 0.11.5        | OpenModsLib-1.12.2-0.11.5.jar                   | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| UC    | openblocks                        | 1.7.6         | OpenBlocks-1.12.2-1.7.6.jar                     | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| UC    | prefab                            | 1.3.0.24      | prefab-1.3.0.24.jar                             | None                                     |
	| UC    | subcommonlib                      | 1.2.0.1       | subcommonlib-sublib-1.12.2-1.2.0.4.jar          | None                                     |
	| UC    | telepads                          | $version      | telepads-1.12.2-1.1.0.5.jar                     | None                                     |
	| UC    | thermaldynamics                   | 2.5.1         | ThermalDynamics-1.12.2-2.5.1.14-universal.jar   | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UC    | uteamcore                         | 1.3.0.72      | u_team_core-1.12.2-1.3.0.72.jar                 | None                                     |
	| UC    | usefulbackpacks                   | 1.2.0.8       | useful_backpacks-1.12.2-1.2.0.8.jar             | None                                     |
	| UC    | vanillafoodpantry                 | 4.2.0         | vanillafoodpantry-mc1.12.1-4.2.jar              | None                                     |
	| UC    | veining                           | 1.3.2         | veining-1.3.2-1.12.x.jar                        | None                                     |
	| UC    | xaerominimap                      | 1.15.4        | Xaeros_Minimap_1.15.4_Forge_1.12.jar            | None                                     |
	| UC    | immersiveengineering              | 0.12-85       | ImmersiveEngineering-0.12-85.jar                | 4cb49fcde3b43048c9889e0a3d083225da926334 |

	Loaded coremods (and transformers): 
ShetiPhian-ASM (shetiphiancore-1.12.0-3.5.6.jar)
  shetiphian.asm.ClassTransformer
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.181.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
EnderCorePlugin (EnderCore-1.12.2-0.5.37.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
  com.enderio.core.common.transform.SimpleMixinPatcher
OpenModsCorePlugin (OpenModsLib-1.12.2-0.11.5.jar)
  openmods.core.OpenModsClassTransformer
IELoadingPlugin (ImmersiveEngineering-core-0.12-85.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
	GL info: ' Vendor: 'Intel' Version: '4.0.0 - Build 10.18.10.4358' Renderer: 'Intel(R) HD Graphics'
	OpenModsLib class transformers: [llama_null_fix:FINISHED],[horse_base_null_fix:FINISHED],[pre_world_render_hook:FINISHED],[player_render_hook:FINISHED],[horse_null_fix:FINISHED]
	AE2 Version: stable rv5-stable-11 for Forge 14.23.1.2554
	OptiFine Version: OptiFine_1.12.2_HD_U_E2
	OptiFine Build: 20180728-185429
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.0.0 - Build 10.18.10.4358
	OpenGlRenderer: Intel(R) HD Graphics
	OpenGlVendor: Intel
	CpuCount: 2

**Comment by covers1624** [comment]
https://github.com/CoFH/Feedback/issues/1289
