### ISSUE TITLE
[Suggestion] Thermal Dynamics integration with Cyclic Assembler

### ISSUE THREAD

**Issue by ShneekeyTheLost** [CoFH/Feedback#129]
I really like Thermal Dynamics. To me, it is the natural successor to BC pipes and RP2's Tubes. It has a simple and consistent logic, and is comparatively very low on resource demand. There's just one thing missing to make my life complete... auto-crafting and crafting on demand.

Basically, everything Logistics Pipes does, Thermal Dynamics can do as well... except auto-crafting and crafting on demand. And hey, there's this nifty little Cyclic Assembler in Thermal Expansion. Which does autocrafting, and has a blueprinting system already set up. So I'm wondering how possible it would be to do something like this:

Retriever (perhaps gated to Signalum or Enderium retriever) attached to a Cyclic Assembler 'sees' the blueprint, and will be able to import the blueprinted recipe. Then you can set a 'minimum in storage' for the product through the normal interface, and if the product has less than x amount in attached inventories the Retriever can 'see', then it will import the ingredients from attached inventories, if possible, and passes them on to the Cyclic Assembler to be assembled. 

I realize you guys are really busy with the 1.10.2 updates, and I totally respect that, but if it isn't too hard, it's an interesting idea to maybe put on the 'maybe once everything slows down a bit' pile.

**Comment by KingLemming** [comment]
Both the Assembler and TD are getting some pretty substantial reworks, so we'll see.

**Comment by KingLemming** [comment]
The way the Cyclic Assembler is shaping up, this won't be possible. But it also might not be necessary. :)
