### ISSUE TITLE
Fractionating Still with Alchemical Retort Augment not accepting Potion of Haste Fluid

### ISSUE THREAD

**Issue by Artimus-Albosa** [CoFH/Feedback#1290]
Mod Version: Thermal Expansion 5.5.0.29
Mod List: https://pastebin.com/NbR8kv6N

Description:
     I'm trying to setup production of Haste IV potions and have an Alchemic Imbuer next to a Fractionating Still. The Imbuer is set to automatically output the Potion of Haste fluid it produces into the Still, and the Still is set to accept inputs from the appropriate side. Even though the still is upgraded with an Alchemical Retort Augment, it will not accept the Potion of Haste fluid as an input. I also attempted to transfer the fluid via both an Ender Fluid Conduit and a Hardened Fluiduct but was unsuccessful. I also used a bucket to extract a Potion of Haste Bucket from the Imbuer, but right clicking on the Still did not input the potion fluid. It's worth noting that Potion of Haste II fluid can be inserted into the Fractioning Still, however, JEI lists upgrading Haste to Haste II in the Still as a valid recipe.

Reproduction Steps:
1. Acquire Potion of Haste fluid
2. Place Fractionating Still
3. Upgrade Fractionating Still such that...
4. Add Alchemical Retort Augmentation
5. Attempt to input Potion of Haste fluid into the Still
  a. By using an adjacent machine with auto-output
  b. By using an Ender IO Fluid Conduit
  c. By using a Fluiduct
  d. By using a bucket

**Comment by KingLemming** [comment]
Works fine for me.

This is one of those things where it really helps to provide screenshots so that we can point out exactly what you're doing wrong, and why you should have come to the Discord for tech support instead of opening an issue.

I'm almost positive that you're trying to refine a Haste I Potion. You can't do that. Needs to be either Long Haste or Haste II.
