### ISSUE TITLE
Thermal Expansion for MC 1.7.10 

### ISSUE THREAD

**Issue by Doussin6834** [CoFH/Feedback#1290]
Hi, i  am currently not having any crashes with the mod but when i try to craft something there is no crafting recipe for that item i have tried crafting every item in the mod but still i get no crafted item from that mod. I have ThermalExpansion-[1.7.10]4.1.4-247.jar
Thermal Expansion and  CoFHCore-[1.7.10]3.1.3-327.jar and ThermalFoundation-[1.7.10]1.2.5-115.jar all installed. Am i missing anything in the mods folder or something or is it a bug

**Comment by KingLemming** [comment]
This isn't tech support. Use IRC for that.

It is definitely something on your end. If this were a bug on the mod, we would have thousands of reports and it would have been fixed immediately.
