### ISSUE TITLE
Suggestion - 1.10.2 Compatability

### ISSUE THREAD

**Issue by ViperZeroOne** [CoFH/Feedback#1292]
Probably been brought up before, but any chance we'll see some 1.10.2 compatibility happen?  We've been slowly updating our modpack to that version and TE is one of the mods at the core of our pack, kind of sucks not having it.

**Comment by KingLemming** [comment]
Yep, it's been brought up lots of times. They've been ported and are being cleaned now. Release will probably be next month.

**Comment by ViperZeroOne** [comment]
Thanks for the reply, great news!  The Thermal system is really the best way to go, I find.
