### ISSUE TITLE
Various additional recipes

### ISSUE THREAD

**Issue by WrongWeekend** [CoFH/Feedback#1293]
Some potential recipes in COFH mods that I believe are missing:

**Induction Furnace:**

1 Sand, Iron Bars -> 3 Iron Nuggets, 10% slag

1 Sand, Tripwire Hook -> 1 Iron Ingot, 10% slag

1 Sand, Iron Trapdoor -> 3 Iron Ingots, 10% slag

1 Sand, Rail -> 3 Iron Nuggets, 10% slag

1 Sand, Detector/Activator Rail -> 1 Iron Ingot, 10% redstone dust

1 Sand, Powered Rail -> 1 Gold Ingot, 10% redstone dust

1 Sand, Fluxed Electrum Plate -> 1 Fluxed Electrum Ingot

1 Sand, Minecart (Empty, Chest, or Command Block) -> 4 Iron Ingots, 10% slag.

1 Sand, Minecart with Hopper -> 8 Iron Ingots, 20% slag.

1 Sand, Minecart with Furnace -> 4 Iron Ingots, 30% slag.

1 Sand, Minecart with TNT -> 4 Iron Ingots, 30% rich slag (Machine explodes?)

**Centrifugal Separator:**

Flux Crystal -> Diamond, 500 mB destabilized redstone

2x Fluxed Electrum Blend -> 1 gold dust, 1 silver dust, 1000 mB destabilized redstone

**Sawmill:**

Dead Bush -> 3 sticks

Saddle -> 3 Leather

12x Leaves -> Pulped Biomass, 20% Sapling

10x Grass/Fern -> Pulped Biomass, 10% Seeds

5x Double Grass/Fern -> Pulped Biomass, 10% Seeds

**Pulverizer:**

Lapis Lazuli -> 2x Blue Pigment

Brick -> 1 Clay ball

Wooden Pressure Plate -> 2 Sawdust

Wooden Trapdoor -> 2 Sawdust

Fluxed Electrum Ingot -> Fluxed Electrum Blend

**Steam Dynamo:**

Pulverized Coal -> 24000 RF

Pulverized Charcoal -> 24000 RF

**Redstone Furnace:**

3x Pulped Biomass -> Sawdust

**Comment by KingLemming** [comment]
I'll add some of these. Will skip the ones which provide possible resource duplication.

**Comment by KingLemming** [comment]
I've added a lot of these. Didn't add some for balance concerns, though may at a later time. You can easily add them to your own game using content jsons though. :)
