### ISSUE TITLE
[INFO] Working on CoFHLib "functional" port to 1.10.2

### ISSUE THREAD

**Issue by garciastl** [CoFH/Feedback#1294]
Hi, there. 

Since I wanted to personally use the 1.10.2 version of Minecraft (plenty of other mods that I want to use work on it), I decided to try my hand not at rewriting all of the CoFH code, but at least trying to modify it to function, based on the existing working code, on 1.10.2.

I've been slowly working on this over a few days now and am making some consistent progress on the lib/world part of the source code.

I don't have plans to distribute the code; this is more of a private exercise (I'm not particularly amazing at Java; I know C and a few other languages, so I know how to pick around as long as I have a few clues and Google). However, I wanted to know if having access to whatever code I manage to modify is something that CoFH would want? I would love to (eventually) see Thermal Expansion on 1.10.2 (which is the whole reason I started working on CoFHLib in the first place), and I wasn't sure if this would be a way I could potentially help.

Please let me know if this is something the team is (or is not) interesting in being able to access/peruse as it changes. 

Thanks!

**Comment by KingLemming** [comment]
We've already done this. You can go ahead and stop. :)

No ETA on the 1.10.2 release, but it'll likely be within 2 weeks.

**Comment by garciastl** [comment]
Awesome! Thanks very much for the heads up!
