### ISSUE TITLE
Thermal expansion, foundation, dynamics

### ISSUE THREAD

**Issue by Gamer666** [CoFH/Feedback#1296]
Please, update mods for 1.10.2 . And if you have them updated, I would like to join testing. Thanks for reply. 🙂

**Comment by XFactHD** [comment]
They are already working on it, just be patient. You should also have looked in the closed issue as this question has been asked multiple times already.

**Comment by KingLemming** [comment]
Oh. My. God. I'm going to shut this tracker down if people keep doing this.
