### ISSUE TITLE
Exception from Thermal Expansion

### ISSUE THREAD

**Issue by JathTyki** [CoFH/Feedback#1297]
Hello,

I am experiencing an issue when attempting to connect to my server I created. I can play mostly fine on SP but I am freezing up quite a bit when playing, so I am attempting to migrate it over to the server and used to not have an issue at all. For some reason though, I have started to receive this error message when connecting to the server. Not sure what is causing it.

https://pastebin.com/ejrn3CRr

Thank you.

**Comment by KingLemming** [comment]
Not sure either. Could you please list your versions?

**Comment by covers1624** [comment]
```
Caused by: java.lang.NullPointerException
    at net.minecraft.enchantment.EnchantmentData.<init>(SourceFile:10) ~[aln.class:?]
    at cofh.thermalexpansion.util.managers.machine.EnchanterManager.refresh(EnchanterManager.java:120) ~[EnchanterManager.class:?]
```
The field passed into EnchantmentData is null-checked in dev, this is likely fixed.

**Comment by covers1624** [comment]
I'm saying, that this bug is impossible on the dev branch and has likely been fixed, with a release pending.

**Comment by KingLemming** [comment]
Yeah. I went back and checked. The problem with this issue is that it hints at something *very* wrong with the server / world.

I have mitigated it in dev, but I worry that I'm just masking the actual problem.

**Comment by JathTyki** [comment]
Thank you. I wait in anticipation of next release!
