### ISSUE TITLE
Forge 2764 crash with Thermal Dynamics

### ISSUE THREAD

**Issue by tgstyle** [CoFH/Feedback#1298]
The changes introduced in 2763 - 2764 produce the following.

https://gist.github.com/tgstyle/815cef3fa21f6212178906d54f9e146b

**Comment by KingLemming** [comment]
Okay, well don't use Forge 2764 then. I dunno what they did, but if they broke that, then screw them.

**Comment by tgstyle** [comment]
https://github.com/MinecraftForge/MinecraftForge/pull/5170

**Comment by davidgauch** [comment]
> Okay, well don't use Forge 2764 then. I dunno what they did, but if they broke that, then screw them.

No need to be rude, there is already a fix made and version 2765 will be out very soon.

**Comment by KingLemming** [comment]
Sorry, maybe you haven't seen #1289 but it gets a little bit old when upstream breaks result in people coming here. Dozens (hundreds, counting Discord) of reports tend to wear on one's patience.

**Comment by KingLemming** [comment]
This has apparently been handled in Forge. Future releases of our mods will target the recommended version if at all possible (2739 required a temp hotfix, releases later today have a better workaround and use 2705).

So in general, please try to use 2705, as Forge sometimes breaks things unnecessarily.
