### ISSUE TITLE
[Thermal Expansion] Augments that increase secondary chance are not working very well...

### ISSUE THREAD

**Issue by Skillotic0703** [CoFH/Feedback#1298]
I'm using forge 1.7.10 - 10.13.4.1614
Thermal expansion 4.1.4-247
Thermal foundation 1.2.5-115
CoFH core 3.1.3-327
These augments work in a very awkward manner. 
When I use them in an induction smelter they improve the secondary loot but are not as efficient as they should be.
If you want an example I put 1 stack of ferrous ore with a stack of cinnabar and I only received 76 shiny ingot. I should have gotten (100+81)/100*64 which is about 116 shiny ingots.
They seem to not work at all in a Pulverizer.
I know you're working on the 1.10 release but I thought it would be great to report this anyway.
Thanks for all the efforts you put to make the community happy!

**Comment by KingLemming** [comment]
They work as intended, and they do work on the Pulverizer.

The issue is more one of tooltips, so it'll all be changing in 1.10.
