### ISSUE TITLE
Game Crash while loading.

### ISSUE THREAD

**Issue by JaceDankhover** [CoFH/Feedback#1299]
Hi, i keep getting this error whenever i launch Minecraft, i tried changing mods and settings, but it won't do anything. If anybody can tell me how to fix this, please do.
[crash-2018-09-28_15.44.35-client.txt](https://github.com/CoFH/Feedback/files/2429522/crash-2018-09-28_15.44.35-client.txt)

**Comment by KingLemming** [comment]
You updated Forge and failed to update CoFH Core. You also failed to read #1289.

If you are going to update, update EVERYTHING. Otherwise, absolutely do not update Forge.
