### ISSUE TITLE
Power Transfer with Ender IO isn't working

### ISSUE THREAD

**Issue by XxSonic4xX** [CoFH/Feedback#13]
When I tried transferring power from the dynamos to the conduits (ender io ones) the power didn't go through. I tried adding a place for the power to go other than the dynamo's internal buffer and still no transfer. Please fix this, I'm eager to play TE 5!

**Comment by KingLemming** [comment]
Sounds to me like EnderIO no longer uses the RF API.

**Comment by RedBullSlurpie** [comment]
I can confirm that the Ender IO conduits are working fine for me, haven't tested them with every thing in TE yet, but so far they transfer power just fine.

**Comment by Butterwhales** [comment]
Interesting i had the same problem between two energy cells.

![image](https://cloud.githubusercontent.com/assets/20495588/23585388/c625fc1e-014b-11e7-8dbd-213c7b4a2a71.png)

**Comment by jem991** [comment]
works well for me
http://i.hizliresim.com/QaA7rA.png

**Comment by ELChris414** [comment]
@Butterwhales what version of Ender IO do you have? is it the latest? Or did this functionality got removed from a version and you @jem991 haven't updated?

**Comment by VT-14** [comment]
Ender IO will only accept Forge Energy or Tesla when charging its items (Energetic Infuser probably won't charge them); but it should be able to use the CoFH RF API for its conduits and machines when the API is provided by another mod.

Possible 3rd mod conflict?

**Comment by KingLemming** [comment]
Infuser will charge them, it does Forge Energy.

**Comment by jem991** [comment]
@ELChris414 I'm using the latest versions of all mod

**Comment by ELChris414** [comment]
@jem991 then he is not.

**Comment by KingLemming** [comment]
Okay then, sounds like this is simply an issue of not using the latest EIO.

**Comment by ELChris414** [comment]
Verified that it is just a version issue.
![2017-03-05_16 32 01](https://cloud.githubusercontent.com/assets/8685248/23588118/593864ea-01c1-11e7-95aa-cf1d815c7251.png)
