### ISSUE TITLE
What DEV build was this fixed in

### ISSUE THREAD

**Issue by crunkazcanbe** [CoFH/Feedback#130]
This MFR http://pastebin.com/3tyNV4AF
And
This NetherOres http://pastebin.com/zF14zGsf

Thanx

-Crunk

**Comment by KingLemming** [comment]
No idea, but you should update to the latest releases of things ;)

**Comment by crunkazcanbe** [comment]
Thank you sir! You are the only one to respond to me. You seem to be a nice fella. I am updating ASAP when other mods update your API . Thanx again.

-Crunk
