### ISSUE TITLE
Hardened Metal Glasses should color Beacon Beams

### ISSUE THREAD

**Issue by Drullkus** [CoFH/Feedback#130]
![2017-03-26_12 12 13](https://cloud.githubusercontent.com/assets/5010174/24334359/bc82a120-121d-11e7-9a72-aed960e8a7c4.png)

I just finished messing around with adding Beacon coloring for Chisel Glasses and noticed that your glass doesn't color beacon beams. There's a method in the block class `public float[] getBeaconColorMultiplier(IBlockState, World, BlockPos, BlockPos)` that lets you give an array of 3 floats that lets you define RGB multipliers between `0.0` and `1.0`. Since your metal glasses are not actual vanilla dye colors, you could use this chance to introduce some custom colors that are off the vanilla color wheel.

**Comment by KingLemming** [comment]
Sounds good. :)
