### ISSUE TITLE
Weird bug with Flux Capacators

### ISSUE THREAD

**Issue by BRFNGRNBWS** [CoFH/Feedback#1300]
I'm using a custom 1.7.10 modpack, here's a modlist: http://imgur.com/a/MedcW, in case something is conflicting. I have Thermal Expansion v4.1.4-247. I normally carry a Redstone flux capacator, to charge my jetpack, and all of the sudden, it's now a creative flux capacator. I'm baffled for a few moments when I decide to just throw it away and cheat myself back in another Redstone one. Within about ten seconds, it  magically changes into a hardened one, then a leadstone, then a tuberous, and finally magically transforms into a creative one.
I'm not doing anything to or even holding the capacator, it just changes on its own before coming to rest at Creative Flux Capacator.

**Comment by KingLemming** [comment]
Something is conflicting, I just don't know what, sorry. You have a mod that is setting metadata values on something it shouldn't be. :(

It's out of our control I'm afraid.

**Comment by BRFNGRNBWS** [comment]
Ok, thank you for responding. I'll try to look for what's conflicting.
