### ISSUE TITLE
Compatibility with Forge 14.23.4.2705 (recommended version for 1.12.2)

### ISSUE THREAD

**Issue by BrainStone** [CoFH/Feedback#1300]
I have noticed that CoFH Core requires at least 14.23.4.2739. Is there are particular reason for that? I'm asking because I plan to run a Modded Survival Server with Sponge. And SpongeForge is only compatible with the recommended version of Forge (currently 14.23.4.2705).

So if possible, it would be incredibly nice to have that mod being built against the recommended version of Forge, so that it can be used with SpongeForge servers.

If there's nothing specific you need that got added in the few versions, it shouldn't be much more than changing the Forge version in the build.gradle file.

**Comment by covers1624** [comment]
Gonna close this sorry, same sender I gave you on the CCL tracker applis here, we need the forge version we dep on.

**Comment by covers1624** [comment]
Gonna close this sorry, same sender I gave you on the CCL tracker applis here, we need the forge version we dep on.

**Comment by BrainStone** [comment]
All good. I opened both tickets shortly after eachother. I have a few more too. 😅

**Comment by KingLemming** [comment]
Right, so the reason for this is that the newest CoFHCore literally fixes a bug that 2739 introduced. However, due to the nature of that fix, it won't work with versions PRIOR.

You can use 1 version back though and it'll be fine. I will investigate a workaround for our next release.
