### ISSUE TITLE
Latest build, 0.29, machines are empty of fluid, but do not show it.

### ISSUE THREAD

**Issue by carlucci9660** [CoFH/Feedback#1301]
![2018-09-29_16 11 13](https://user-images.githubusercontent.com/31194015/46250141-621f5780-c402-11e8-8a23-00f5cb1914f7.png)

**Comment by KingLemming** [comment]
I'm afraid I don't understand what you're trying to show here. Could you please explain?

**Comment by carlucci9660** [comment]
sorry typo, Latest build, 0.29, machines are empty of fluid, but it still shows fluid..ill see if i can make a video and zip it up.

**Comment by KingLemming** [comment]
Why do you think that machine is empty exactly? It seems to have 4 buckets of lava in it. In fact, the way it works, I am *extremely* confident that it has 4 buckets of lava in it. Like 100%, because that info is synced from the server to the client every tick that you're staring at the GUI.

**Comment by KingLemming** [comment]
Sorry, I just tested on release builds and I'm completely unable to replicate this. What you're describing is more of a bucket filling thing, and I'm very confident that it's not something in machine code or it would have been reported many, many times with the current build as it's been out for months.

Feel free to drop by the tech support channel on the Discord and maybe we can suss it out though. :)

**Comment by carlucci9660** [comment]
gonna try to make video. thanks
