### ISSUE TITLE
Random Crashes with Induction Smelter and Refined Storage

### ISSUE THREAD

**Issue by Sunekaer** [CoFH/Feedback#1302]
Crashes randomly when using the Induction Smelter's UI or when I try auto-crafting in Refined Storage.

Steps to Reproduce (for bugs)
Have things already inside the Induction Smelter or try auto-crafting with it.
Try pressing the "Lock Flux Slot" button or taking things out manually.

Logs
Client/Server Log: https://gist.github.com/ThePlantPrince/f33e21fc1b3ea0bfaa45a92a42ba0b5a
Crash Log: https://pastebin.com/fEfqbGXW

https://github.com/Sunekaer/stoneBlock/issues/172

**Comment by KingLemming** [comment]
Yeah, that seems to be working as intended. RS seems to "cache" what can go into a slot, and changing what that is apparently doesn't sit well with it.

I guess the solution is well...don't do that, sorry. That exception is being very intentionally thrown by RS - it is not a "random" crash at all.
