### ISSUE TITLE
Thermal Dynamics 2.5.1 - Crash due to attempting to cast an IE TileEntityBellJar to TileGrid

### ISSUE THREAD

**Issue by SirLyle** [CoFH/Feedback#1303]
[Pastebin of Crash Report](https://pastebin.com/j4CxqU4j)

I have itemducts hooked up to a bunch of cloches going to a drawer slave, there is a resonant retriever on the drawer slave. Worked for several days, then it is crashed. Now I crash while the world is loading. Not sure if this is an IE or a TD issue, I think TD since its your function trying to cast the cloche into something it isn't. Mods are listed in the report, it is a slightly modified version of the StoneBlock pack.

**Comment by KingLemming** [comment]
This is caused by Realdrops, actually. It seems to be targeting an incorrect block.

**Comment by Funwayguy** [comment]
I highly doubt that. The code firing this crash stems from vanilla's built-in code for moving entities out of blocks. I haven't modified that or the bounding box of the item entity and I don't do any "targeting" of any kind in that stack trace. As a matter of fact, the `BlockPos` passed to your ducts is defined in `World.getCollisionBoxes()` way outside the scope of my code. Any other Entity calling these methods would cause a similar crash.

The better question here would be how or why did Immersive Engineering's bell overwrite the tile entity within a duct block?

**Comment by SirLyle** [comment]
I have gotten the same error, but now with a player and a storage drawer, so I am fairly confident this is TD's fault.

Based on [this line](https://github.com/CoFH/ThermalDynamics/blob/6e28537d42c66d476ecfdfa2f11e081f59df90f2/src/main/java/cofh/thermaldynamics/block/BlockDuct.java#L152) it is likely a similar issue as this Issue #995. I was jumping over a duct/drawer setup when this happened.

[Pastebin](https://pastebin.com/z08qihBD)
