### ISSUE TITLE
Latest TE 5.5.1.33 appears to have broke removing recycle recipes (possibly more) with CraftTweaker

### ISSUE THREAD

**Issue by tgstyle** [CoFH/Feedback#1308]
I have tried my script to remove them both ways even in succession. There is no error in the CT log, it even shows it removed them both ways, yet they still process in the machine and show in JEI.

Example would be removing a Minecraft Iron Helmet

Script -

https://gist.github.com/tgstyle/d3dfba1c25f373807a5f5180f2951f78

Tested with these mods only -
![capture](https://user-images.githubusercontent.com/5832709/46369688-e8c17800-c640-11e8-87d2-828b01de9de2.JPG)

**Comment by KingLemming** [comment]
Come to the Discord tech support please. Recycle recipes are working as intended and better than ever with the new patch, they aren't broken and we don't do the CT integration on our end.

Offhand, my guess is that your metadata values need to be wildcards now (32767).

**Comment by tgstyle** [comment]
If I do wild cards it says the item is not found.

**Comment by KingLemming** [comment]
That's a bit of an unfortunate catch-22 then because the Recycle Recipes use those. This is something you may need to take up with Minetweaker.

Unfortunately, I can't just do a blanket wildcard assumption, because some recycle recipes use it and some don't.
