### ISSUE TITLE
Flux infused omni-wrench with ae

### ISSUE THREAD

**Issue by bigpodgurc** [CoFH/Feedback#131]
please make so omni wrench with AE shifting dissasembels block

**Comment by KingLemming** [comment]
That's probably on AE's end honestly, but I'll mention it to them.

**Comment by FireBall1725** [comment]
I will look into it on our end and check the api, the crescent hammer is working, so i don't know why the flux infused one wouldn't work.

**Comment by FireBall1725** [comment]
I just tested it, and yea, the flux infused wrench does not work

**Comment by bigpodgurc** [comment]
i hope it will be soon fixed because i realy liked using it

**Comment by KingLemming** [comment]
This may not be fixable. It's not a bug actually; it's just the fact that AE supports the IC2 interface.

**Comment by KingLemming** [comment]
This will be resolved on AE's end; there's nothing we can do on ours. @FireBall1725 said he'd look into adding IDismantleable support.
