### ISSUE TITLE
Crash when picking up cache with crescent hammer while standing on EIO conduits. 

### ISSUE THREAD

**Issue by zackeezy** [CoFH/Feedback#131]
http://pastebin.com/SrJ2Cgp7 <-- crash log

**Comment by KingLemming** [comment]
Does it happen every single time consistently, or this was a one off?

The EnderIO part makes me wonder wtf they might be doing.

**Comment by zackeezy** [comment]
It appeared to be a rendering issue.  When I loaded the world back up the cache was not in world and it had dropped as an item.  To answer your question, though, it just happened the one time. I might have just been clocking them too quickly. It also listed CodeChickenLib in the crash log so like I said, it seems to be a rendering problem.  If you want to replicate it, stand on some EIO conduits and try using the Crescent hammer to pick up caches in succession (by shift-clicking).

**Comment by codewarrior0** [comment]
Looks like the chunk update thread gets a private copy of the blocks in the chunk being rendered, but it needs to go back to the worldObj to get the TileEntity. This means you can get a kind of race condition where a block and its TE were removed on the main thread, but the rendering thread is still rendering that block, so when it goes to get its TE it gets a null instead.

But chunks the player is in should be rendered on the main thread, not the chunk update thread. I heard there was a Forge option or something to force all chunks to the chunk update thread - you didn't turn that option on, did you?

**Comment by Ushupiuck** [comment]
I was about to report this same issue. Oh well! I can only wish you luck, and ask... is next release coming soon? (not asking for a date, just if it's coming)

**Comment by KingLemming** [comment]
Pretty confident this has been handled upstream.
