### ISSUE TITLE
OreDict fail with redstone/glowstone/oil liquids

### ISSUE THREAD

**Issue by Vic3Dexe** [CoFH/Feedback#1310]
Forge 14.23.4.2765.

Problem:
- resonant end stone registered as oreClathrateOilSand and produces oil in magma crucible
- destabilized redstone ore registered as oreClathrateGlowstone and produces energized glowstone
- energized netherrack registeres as oreClathrateEnder and produces resonant ender

Tried delete all mods except TE/TF. Doesn't help.
Also didn't find any config about this.
Maybe it's a Forge bug or my hands are broken... Idk.

Mod list:
CodeChickenLib-1.12.2-3.2.2.353-universal
CoFHCore-1.12.2-4.6.0.21-universal
CoFHWorld-1.12.2-1.3.0.6-universal
jei_1.12.2-4.8.5.138
jeiintegration_1.12.2-1.5.1.36
RedstoneFlux-1.12-2.1.0.6-universal
ThermalCultivation-1.12.2-0.3.1.8-universal
ThermalDynamics-1.12.2-2.5.2.15-universal
ThermalExpansion-1.12.2-5.5.1.34-universal
ThermalFoundation-1.12.2-2.6.0.20-universal

**Comment by KingLemming** [comment]
Already fixed. Go update.
