### ISSUE TITLE
New iron gear recipe conflicts with Advanced Generators mod

### ISSUE THREAD

**Issue by Vic3Dexe** [CoFH/Feedback#1312]
Recently changed iron gear recipe (4 iron ingots, not 5) conflicts with Iron Frame recipe from Advanced Generators mod.

Forge 14.23.4.2765.

Mod list:
bdlib-1.14.3.12-mc1.12.2
CodeChickenLib-1.12.2-3.2.2.353-universal
CoFHCore-1.12.2-4.6.1.22-universal
CoFHWorld-1.12.2-1.3.0.6-universal
generators-0.9.20.12-mc1.12.2
jei_1.12.2-4.8.5.138
jeiintegration_1.12.2-1.5.1.36
RedstoneFlux-1.12-2.1.0.6-universal
ThermalCultivation-1.12.2-0.3.1.8-universal
ThermalDynamics-1.12.2-2.5.2.15-universal
ThermalExpansion-1.12.2-5.5.2.35-universal
ThermalFoundation-1.12.2-2.6.1.22-universal

**Comment by KingLemming** [comment]
Well, sorry. :/ This is something you'll have to CraftTweak I suppose.

**Comment by VladimirMangos** [comment]
Workaround for iron gear: create iron gear from stone gear 

Bad side: Tin Gear in same way conflict with TechReborn
And for Tin Gear no similar indirect path...
