### ISSUE TITLE
Redstone Relay colours not differentiating signals through duct network

### ISSUE THREAD

**Issue by doxlulzem** [CoFH/Feedback#1315]
Complex title, but in essence I'm setting up a Thermal Expansion blast furnace, and this time tried using a singular structuralduct network to transfer all signals across to different toggleable servos. I connected four levers, with four relays, all set to input and each set to different colours to a singular structuralduct, that went back along the machines and connected to each of the servos, with a relay connected to the servo set to output, and set to the corresponding colour. The issue, however, is that no matter which lever I pull, all four servos light up and start attempting to pull from the chests they're connected to, regardless of colour.

![2018-10-07_21 11 57](https://user-images.githubusercontent.com/10574261/46586400-c29f3c00-ca75-11e8-91b0-2d87581536a1.png)
Note all four levers with their relays connected, they all connect to the same structuralduct that goes up and behind the wall to the machines (dirt blocks are for the machines, I was planning it out and haven't built them yet)

![2018-10-07_21 12 17](https://user-images.githubusercontent.com/10574261/46586416-e793af00-ca75-11e8-8354-7731725bf1ef.png)
This particular relay is set to brown, but from left to right they go red, green, brown and blue. I have checked and all input and output relays have different colours set

![2018-10-07_21 12 33](https://user-images.githubusercontent.com/10574261/46586423-02662380-ca76-11e8-878c-4440e0bb99bd.png)

If I pull a lever, notice how all the servos (the one in the top left by the dirt block, and ones connected to the two middle chests are the most noticeable) have become lit up, despite me only pulling the brown lever, and so only the brown relay-connected servo should light up (in this case, only the centre, top chest)

![2018-10-07_21 12 47](https://user-images.githubusercontent.com/10574261/46586431-39d4d000-ca76-11e8-9571-ba0f30e9956a.png)
Additional proof, this is the relay on the top left (by the dirt block), showing that it is set to a different colour to the lever I pulled and also set to output.

If my interpretation of the [https://teamcofh.com/docs/thermal-dynamics/redstone-relay/](url) CoFH Wiki article on the relay is correct, setting it to input will "beam" that specific colour down the duct network, where any relay set to output and having that colour will apply it to the block the relay is connected to, unless there is only a single relay in the network. Shouldn't a single lever activating a single input relay colour only send a signal to output relays with that specific colour? Am I doing something wrong, like interpreting the article wrong or is this a genuine bug? I've done it with a single relay connected to a direct structural duct going to the servo, but I wanted to make my blast furnace on this server more compact and easier to maintain, so I tried going for the multiple-signals-down-one-duct method.

Please let me know if I'm just doing something wrong.

**Comment by KingLemming** [comment]
I'll be honest, I have no idea. The color thing was submitted via Pull Request and seemed to work at the time, but I don't know if anything like this particular case was tested.

If it is a bug, then I'm afraid it won't be getting fixed. It's not something I ever had designs for and at this point I'm no longer working on 1.12 stuff unless it's critical. Please drop by the Discord and ask around in tech support.
