### ISSUE TITLE
1.7.10 Thermal Expansion Crash

### ISSUE THREAD

**Issue by Danklinsda** [CoFH/Feedback#1316]
when i right click a machine from the mod it crashes my game 
Minecraft Crash Report ----
// Why did you do that?
Time: 10/7/18 9:16 PM
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
 at lotr.client.LOTRGuiHandler.preDrawScreen(LOTRGuiHandler.java:228)
 at cpw.mods.fml.common.eventhandler.ASMEventHandler_40_LOTRGuiHandler_preDrawScreen_Pre.invoke(.dynamic)
 at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
 at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
 at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1060)
 at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
 at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
 at net.minecraft.client.main.Main.main(SourceFile:148)
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.lang.reflect.Method.invoke(Method.java:497)
 at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
 at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
 at lotr.client.LOTRGuiHandler.preDrawScreen(LOTRGuiHandler.java:228)
 at cpw.mods.fml.common.eventhandler.ASMEventHandler_40_LOTRGuiHandler_preDrawScreen_Pre.invoke(.dynamic)
 at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
 at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)

-- Screen render details --
Details:
 Screen name: cofh.thermalexpansion.gui.client.machine.GuiPulverizer
 Mouse location: Scaled: (256, 191). Absolute: (512, 384)
 Screen size: Scaled: (512, 384). Absolute: (1024, 768). Scale factor of 2

-- Affected level --
Details:
 Level name: MpServer
 All players: 1 total; [GCEntityClientPlayerMP['Frunklin'/422, l='MpServer', x=298.59, y=65.62, z=216.67]]
 Chunk stats: MultiplayerChunkCache: 542, 542
 Level seed: 0
 Level generator: ID 00 - default, ver 1. Features enabled: false
 Level generator options: 
 Level spawn location: World: (285,64,228), Chunk: (at 13,4,4 in 17,14; contains blocks 272,0,224 to 287,255,239), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
 Level time: 3311 game time, 3311 day time
 Level dimension: 0
 Level storage version: 0x00000 - Unknown?
 Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
 Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
 Forced entities: 99 total; [EntityBat['Bat'/260, l='MpServer', x=334.25, y=34.10, z=173.41], EntitySheep['Sheep'/261, l='MpServer', x=335.91, y=66.00, z=218.13], EntitySheep['Sheep'/262, l='MpServer', x=332.78, y=66.00, z=213.63], EntitySheep['Sheep'/263, l='MpServer', x=324.77, y=75.00, z=266.53], EntitySheep['Sheep'/264, l='MpServer', x=321.06, y=74.00, z=268.34], EntityZombie['Zombie'/274, l='MpServer', x=351.47, y=19.00, z=150.97], EntitySkeleton['Skeleton'/275, l='MpServer', x=350.38, y=19.00, z=156.94], BlueSlime['Blue Slime'/276, l='MpServer', x=350.78, y=62.00, z=158.03], EntitySkeleton['Skeleton'/277, l='MpServer', x=346.69, y=20.00, z=161.03], EntityItem['item.item.string'/278, l='MpServer', x=346.22, y=20.13, z=160.63], EntitySheep['Sheep'/279, l='MpServer', x=347.22, y=63.00, z=173.47], EntitySheep['Sheep'/280, l='MpServer', x=341.50, y=67.00, z=221.34], EntitySheep['Sheep'/281, l='MpServer', x=344.28, y=69.00, z=227.41], EntitySheep['Sheep'/282, l='MpServer', x=339.50, y=67.00, z=237.50], EntitySheep['Sheep'/283, l='MpServer', x=341.50, y=67.00, z=236.50], EntitySheep['Sheep'/284, l='MpServer', x=339.88, y=66.00, z=224.31], EntitySheep['Sheep'/285, l='MpServer', x=345.91, y=70.00, z=228.59], EntitySheep['Sheep'/286, l='MpServer', x=329.25, y=67.00, z=234.53], EntitySheep['Sheep'/287, l='MpServer', x=350.38, y=71.00, z=260.91], EntitySheep['Sheep'/293, l='MpServer', x=361.38, y=64.00, z=151.53], EntitySpider['Spider'/294, l='MpServer', x=364.22, y=31.00, z=160.91], EntityZombie['Zombie'/295, l='MpServer', x=363.53, y=33.00, z=165.03], EntitySheep['Sheep'/296, l='MpServer', x=362.44, y=63.00, z=166.53], EntitySheep['Sheep'/297, l='MpServer', x=352.97, y=63.00, z=168.97], EntitySheep['Sheep'/298, l='MpServer', x=367.50, y=69.00, z=208.66], EntitySheep['Sheep'/299, l='MpServer', x=358.53, y=78.00, z=231.63], EntitySheep['Sheep'/300, l='MpServer', x=363.94, y=80.00, z=232.97], EntitySheep['Sheep'/301, l='MpServer', x=362.50, y=82.00, z=254.28], EntitySheep['Sheep'/302, l='MpServer', x=359.34, y=80.00, z=259.53], EntityZombie['Zombie'/325, l='MpServer', x=372.47, y=33.00, z=168.03], EntitySheep['Sheep'/328, l='MpServer', x=378.03, y=66.00, z=203.06], EntitySheep['Sheep'/329, l='MpServer', x=374.81, y=70.00, z=203.50], EntityZombie['Zombie'/330, l='MpServer', x=372.47, y=15.00, z=213.31], EntityZombie['Zombie'/331, l='MpServer', x=371.63, y=17.00, z=216.00], EntityBat['Bat'/332, l='MpServer', x=377.25, y=24.10, z=234.25], EntitySheep['Sheep'/333, l='MpServer', x=365.49, y=80.00, z=230.53], EntityCow['Cow'/334, l='MpServer', x=378.53, y=79.00, z=271.53], EntitySheep['Sheep'/335, l='MpServer', x=374.63, y=82.00, z=256.53], EntityCow['Cow'/336, l='MpServer', x=376.09, y=80.00, z=261.50], EntityItem['item.item.tardrop'/1622, l='MpServer', x=253.63, y=58.13, z=160.56], EntityTarSlime['Tar Slime'/1624, l='MpServer', x=251.05, y=59.00, z=155.97], EntityTarSlime['Tar Slime'/1625, l='MpServer', x=254.21, y=59.00, z=156.50], EntityTarSlime['Tar Slime'/1626, l='MpServer', x=251.50, y=59.00, z=159.09], EntitySheep['Sheep'/96, l='MpServer', x=221.19, y=63.00, z=152.28], EntityCreeper['Creeper'/99, l='MpServer', x=219.44, y=43.00, z=187.44], EntityTarSlime['Tar Slime'/102, l='MpServer', x=219.69, y=62.00, z=196.72], EntitySheep['Sheep'/105, l='MpServer', x=219.50, y=64.00, z=283.50], EntitySheep['Sheep'/106, l='MpServer', x=219.50, y=64.00, z=283.50], EntityTarSlime['Tar Slime'/115, l='MpServer', x=230.50, y=63.85, z=139.50], EntityTarSlime['Tar Slime'/117, l='MpServer', x=227.13, y=64.85, z=144.81], EntityTarSlime['Tar Slime'/118, l='MpServer', x=232.56, y=64.43, z=145.41], EntityTarSlime['Tar Slime'/119, l='MpServer', x=234.56, y=64.43, z=145.69], EntitySpider['Spider'/120, l='MpServer', x=221.72, y=20.00, z=209.28], EntitySkeleton['Skeleton'/121, l='MpServer', x=230.69, y=42.00, z=202.69], EntitySkeleton['Skeleton'/122, l='MpServer', x=228.70, y=42.00, z=193.30], EntitySkeleton['Skeleton'/123, l='MpServer', x=227.70, y=41.92, z=203.63], EntitySkeleton['Skeleton'/124, l='MpServer', x=228.70, y=42.00, z=204.70], EntitySkeleton['Skeleton'/125, l='MpServer', x=228.53, y=41.00, z=194.65], EntitySkeleton['Skeleton'/126, l='MpServer', x=227.75, y=42.00, z=193.56], EntitySkeleton['Skeleton'/127, l='MpServer', x=230.22, y=41.00, z=196.66], EntityCreeper['Creeper'/128, l='MpServer', x=226.72, y=41.00, z=203.31], EntityCreeper['Creeper'/129, l='MpServer', x=238.00, y=25.00, z=215.63], EntityBat['Bat'/130, l='MpServer', x=228.69, y=19.98, z=220.50], EntitySkeleton['Skeleton'/131, l='MpServer', x=228.56, y=34.00, z=224.01], EntitySkeleton['Skeleton'/132, l='MpServer', x=227.38, y=34.00, z=220.31], EntityBat['Bat'/133, l='MpServer', x=218.72, y=38.10, z=223.25], EntityFeeder['Spotted Bottom Feeder'/134, l='MpServer', x=240.34, y=58.00, z=220.13], EntitySkeleton['Skeleton'/135, l='MpServer', x=227.09, y=35.00, z=225.50], EntitySheep['Sheep'/136, l='MpServer', x=239.38, y=63.00, z=248.28], EntitySkeleton['Skeleton'/137, l='MpServer', x=232.91, y=57.00, z=268.50], EntitySheep['Sheep'/138, l='MpServer', x=235.47, y=63.00, z=257.63], EntitySkeleton['Skeleton'/139, l='MpServer', x=229.72, y=19.00, z=278.84], EntitySheep['Sheep'/140, l='MpServer', x=228.47, y=64.00, z=286.38], EntityAlligatorGar['Alligator Gar'/160, l='MpServer', x=253.31, y=58.72, z=198.09], EntityFeeder['Spotted Bottom Feeder'/161, l='MpServer', x=235.55, y=59.05, z=198.77], EntityZombie['Zombie'/162, l='MpServer', x=254.69, y=23.33, z=232.69], EntityZombie['Zombie'/163, l='MpServer', x=242.84, y=23.00, z=236.50], EntitySheep['Sheep'/164, l='MpServer', x=241.34, y=63.00, z=254.19], EntityBat['Bat'/165, l='MpServer', x=255.75, y=52.10, z=264.06], EntityBat['Bat'/166, l='MpServer', x=251.41, y=50.92, z=266.38], GCEntityClientPlayerMP['Frunklin'/422, l='MpServer', x=298.59, y=65.62, z=216.67], EntityBat['Bat'/167, l='MpServer', x=250.97, y=53.10, z=268.31], EntityBat['Bat'/168, l='MpServer', x=250.94, y=50.27, z=265.78], EntityCreeper['Creeper'/169, l='MpServer', x=251.22, y=20.00, z=279.22], EntitySkeleton['Skeleton'/170, l='MpServer', x=248.50, y=47.00, z=284.50], EntityBat['Bat'/171, l='MpServer', x=257.47, y=46.57, z=288.75], EntityZombie['Zombie'/172, l='MpServer', x=249.13, y=47.00, z=290.50], EntityZombie['Zombie'/180, l='MpServer', x=259.44, y=33.00, z=203.59], EntityAlligatorGar['Alligator Gar'/181, l='MpServer', x=270.50, y=61.01, z=197.83], EntityZombie['Zombie'/182, l='MpServer', x=262.91, y=33.01, z=216.88], EntitySheep['Sheep'/183, l='MpServer', x=252.53, y=63.00, z=263.22], EntityBat['Bat'/194, l='MpServer', x=290.84, y=22.00, z=158.53], EntitySpider['Spider'/197, l='MpServer', x=292.34, y=23.00, z=142.75], EntityBat['Bat'/200, l='MpServer', x=301.69, y=28.51, z=149.53], EntitySkeleton['Skeleton'/201, l='MpServer', x=305.28, y=32.00, z=178.25], EntityTrail['unknown'/1227, l='MpServer', x=298.59, y=65.62, z=216.67], EntityBat['Bat'/215, l='MpServer', x=311.72, y=35.51, z=184.50], EntitySheep['Sheep'/216, l='MpServer', x=317.06, y=73.00, z=267.91], EntitySheep['Sheep'/217, l='MpServer', x=309.22, y=70.00, z=263.47]]
 Retry entities: 0 total; []
 Server brand: fml,forge
 Server type: Integrated singleplayer server
Stacktrace:
 at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
 at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
 at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:919)
 at net.minecraft.client.main.Main.main(SourceFile:148)
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.lang.reflect.Method.invoke(Method.java:497)
 at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
 at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
 Minecraft Version: 1.7.10
 Operating System: Windows 10 (amd64) version 10.0
 Java Version: 1.8.0_51, Oracle Corporation
 Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
 Memory: 497161976 bytes (474 MB) / 2090860544 bytes (1994 MB) up to 2863661056 bytes (2731 MB)
 JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3072m -Xms256m -XX:PermSize=256m
 AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
 IntCache: cache: 1, tcache: 1, allocated: 12, tallocated: 94
 FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 79 mods loaded, 67 mods active
 States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
 UCHIJAAAA    mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
 UCHIJAAAA    FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
 UCHIJAAAA    Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
 UCHIJAAAA    CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
 UCHIJAAAA    Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
 UCHIJAAAA    NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
 UCHIJAAAA    OpenModsCore{0.10} [OpenModsCore] (minecraft.jar) 
 UCHIJAAAA    <CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
 UCHIJAAAA    ATG{0.10.0} [Alternate Terrain Generation] (ATG-1.7.10-0.12.0.jar) 
 UCHIJAAAA    betterbuilderswands{0.8.1} [Better Builder's Wands] (BetterBuildersWands-0.8.1-1.7.10r92+aec06c3.jar) 
 UCHIJAAAA    BiblioCraft{1.11.7} [BiblioCraft] (BiblioCraft[v1.11.7][MC1.7.10].jar) 
 UCHIJAAAA    ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
 UCHIJAAAA    chisel{2.9.5.11} [Chisel] (Chisel-2.9.5.11.jar) 
 UCHIJAAAA    CarpentersBlocks{3.3.8.1} [Carpenter's Blocks] (Carpenter's Blocks v3.3.8.1 - MC 1.7.10.jar) 
 UCHIJAAAA    chocolateQuest{1.0} [Chocolate Quest] (chocolateQuest-1.7.10-1.0.jar) 
 UCHIJAAAA    CoFHCore{1.7.10R3.1.4} [CoFH Core] (CoFHCore-[1.7.10]3.1.4-329.jar) 
 UCHIJAAAA    ThermalFoundation{1.7.10R1.2.6} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.2.6-118.jar) 
 UCHIJAAAA    ExtraUtilities{1.2.12} [Extra Utilities] (extrautilities-1.2.12.jar) 
 UCHIJAAAA    fantastic{1.0.0} [Fantastic Fish] (fantastic-1.4.jar) 
 UCHIJAAAA    flansmod{4.10.0} [Flan's Mod] (Flans Mod-1.7.10-4.10.0.jar) 
 UCHIJAAAA    llibrary{1.5.1} [LLibrary] (llibrary-1.5.1-1.7.10.jar) 
 UCHIJAAAA    fossil{7.3.2} [Fossils and Archeology Revival] (fossilsarcheology-7.3.2.jar) 
 UCHIJAAAA    Mantle{1.7.10-0.3.2.jenkins191} [Mantle] (Mantle-1.7.10-0.3.2b.jar) 
 UCHIJAAAA    MineFactoryReloaded{1.7.10R2.8.1} [MineFactory Reloaded] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
 UCHIJAAAA    ThermalExpansion{1.7.10R4.1.5} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.1.5-248.jar) 
 UCHIJAAAA    Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
 UCHIJAAAA    TConstruct{1.7.10-1.8.8.build988} [Tinkers' Construct] (TConstruct-1.7.10-1.8.8.jar) 
 UCHIJAAAA    GalacticraftCore{3.0.12} [Galacticraft Core] (GalacticraftCore-1.7-3.0.12.504.jar) 
 UCHIJAAAA    iChunUtil{4.2.3} [iChunUtil] (iChunUtil-4.2.3.jar) 
 UCHIJAAAA    journeymap{5.1.4p2} [JourneyMap] (journeymap-1.7.10-5.1.4p2-unlimited.jar) 
 UCHIJAAAA    jurassicraft{1.5.0} [JurassiCraft] (JurassiCraft-1.4.0.jar) 
 UCHIJAAAA    lotr{Update v34.3 for Minecraft 1.7.10} [The Lord of the Rings Mod] (LOTRMod v34.3.jar) 
 UCHIJAAAA    RadixCore{2.1.3} [RadixCore] (RadixCore-1.7.10-2.1.3-universal.jar) 
 UCHIJAAAA    MCA{1.7.10-5.2.2} [Minecraft Comes Alive] (MCA-1.7.10-5.2.2-universal.jar) 
 UCHIJAAAA    MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.1} [MFR Compat: ForgeMicroblock] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
 UCHIJAAAA    MrTJPCoreMod{1.1.0.33} [MrTJPCore] (MrTJPCore-1.1.0.33-universal.jar) 
 UCHIJAAAA    ProjRed|Core{4.7.0pre12.95} [ProjectRed Core] (ProjectRed-1.7.10-4.7.0pre12.95-Base.jar) 
 UCHIJAAAA    ProjRed|Exploration{4.7.0pre12.95} [ProjectRed Exploration] (ProjectRed-1.7.10-4.7.0pre12.95-World.jar) 
 UCHIJAAAA    MineFactoryReloaded|CompatProjRed{1.7.10R2.8.1} [MFR Compat ProjectRed] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
 UCHIJAAAA    MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.1} [MFR Compat: Thermal Expansion] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
 UCHIJAAAA    MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.1} [MFR Compat: Tinkers' Construct] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
 UCHIJAAAA    MineFactoryReloaded|CompatVanilla{1.7.10R2.8.1} [MFR Compat: Vanilla] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
 UCHIJAAAA    Morph{0.9.3} [Morph] (Morph-Beta-0.9.3.jar) 
 UCHIJAAAA    cfm{3.4.7} [§9MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.4.7(1.7.10).jar) 
 UCHIJAAAA    recipehandler{1.7.10} [NoMoreRecipeConflict] (NoMoreRecipeConflict-0.3(1.7.10).jar) 
 UCHIJAAAA    OpenMods{0.10} [OpenMods] (OpenModsLib-1.7.10-0.10.jar) 
 UCHIJAAAA    OpenBlocks{1.6} [OpenBlocks] (OpenBlocks-1.7.10-1.6.jar) 
 UCHIJAAAA    harvestcraft{1.7.10j} [Pam's HarvestCraft] (Pam's HarvestCraft 1.7.10Lb.jar) 
 UCHIJAAAA    ProjRed|Transmission{4.7.0pre12.95} [ProjectRed Transmission] (ProjectRed-1.7.10-4.7.0pre12.95-Integration.jar) 
 UCHIJAAAA    ProjRed|Transportation{4.7.0pre12.95} [ProjectRed Transportation] (ProjectRed-1.7.10-4.7.0pre12.95-Mechanical.jar) 
 UCHIJAAAA    ProjRed|Compatibility{4.7.0pre12.95} [ProjectRed Compatibility] (ProjectRed-1.7.10-4.7.0pre12.95-Compat.jar) 
 UCHIJAAAA    ProjRed|Integration{4.7.0pre12.95} [ProjectRed Integration] (ProjectRed-1.7.10-4.7.0pre12.95-Integration.jar) 
 UCHIJAAAA    ProjRed|Fabrication{4.7.0pre12.95} [ProjectRed Fabrication] (ProjectRed-1.7.10-4.7.0pre12.95-Fabrication.jar) 
 UCHIJAAAA    ProjRed|Illumination{4.7.0pre12.95} [ProjectRed Illumination] (ProjectRed-1.7.10-4.7.0pre12.95-Lighting.jar) 
 UCHIJAAAA    ProjRed|Expansion{4.7.0pre12.95} [ProjectRed Expansion] (ProjectRed-1.7.10-4.7.0pre12.95-Mechanical.jar) 
 UCHIJAAAA    RedstonePasteMod{1.6.2} [Redstone Paste] (RedstonePasteMod-1.7.10-1.6.2.jar) 
 UCHIJAAAA    Roguelike{1.5.0} [Roguelike Dungeons] (roguelike-1.7.10-1.5.0b.jar) 
 UCHIJAAAA    secretroomsmod{4.7.1} [The SecretRoomsMod] (secretroomsmod-1.7.10-4.7.1.413.jar) 
 UCHIJAAAA    ThermalDynamics{1.7.10R1.2.1} [Thermal Dynamics] (ThermalDynamics-[1.7.10]1.2.1-172.jar) 
 UCHIJAAAA    WailaHarvestability{1.1.6} [Waila Harvestability] (WailaHarvestability-mc1.7.10-1.1.6.jar) 
 UCHIJAAAA    witchery{0.24.1} [Witchery] (witchery-1.7.10-0.24.1.jar) 
 UCHIJAAAA    witcherypatch{1.0.0} [WitcheryPatch] (WitcheryPatch-1.7.10-1.0.0.jar) 
 UCHIJAAAA    McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
 UCHIJAAAA    ForgeRelocation{0.0.1.4} [ForgeRelocation] (ForgeRelocation-0.0.1.4-universal.jar) 
 UCHIJAAAA    MCFrames{1.0} [MCFrames] (ForgeRelocation-0.0.1.4-universal.jar) 
 UCHIJAAAA    RelocationFMP{0.0.1.2} [RelocationFMP] (ForgeRelocationFMP-0.0.1.2-universal.jar) 
 UCHIJAAAA    ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
 UD    MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.1} [MFR Compat: Applied Energistics] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
 UD    MineFactoryReloaded|CompatAtum{1.7.10R2.8.1} [MFR Compat: Atum] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
 UD    MineFactoryReloaded|CompatBackTools{1.7.10R2.8.1} [MFR Compat: BackTools] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
 UD    MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.1} [MFR Compat: BuildCraft] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
 UD    MineFactoryReloaded|CompatChococraft{1.7.10R2.8.1} [MFR Compat: Chococraft] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
 UD    MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.1} [MFR Compat: ExtraBiomes] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
 UD    MineFactoryReloaded|CompatForestry{1.7.10R2.8.1} [MFR Compat: Forestry] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
 UD    MineFactoryReloaded|CompatIC2{1.7.10R2.8.1} [MFR Compat: IC2] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
 UD    MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.1} [MFR Compat: Railcraft] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
 UD    MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.1} [MFR Compat: Sufficient Biomes] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
 UD    MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.1} [MFR Compat: Thaumcraft] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
 UD    MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.1} [MFR Compat: TwilightForest] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
 GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 416.16' Renderer: 'GeForce GTX 970/PCIe/SSE2'
 OpenModsLib class transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[player_damage_hook:FINISHED],[map_gen_fix:FINISHED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
 Class transformer null safety: all safe
 CoFHCore: -[1.7.10]3.1.4-329
 ThermalFoundation: -[1.7.10]1.2.6-118
 Mantle Environment: Environment healthy.
 MineFactoryReloaded: -[1.7.10]2.8.1-174
 ThermalExpansion: -[1.7.10]4.1.5-248
 TConstruct Environment: Environment healthy.
 ThermalDynamics: -[1.7.10]1.2.1-172
 Chisel: Errors like "[FML]: Unable to lookup ..." are NOT the cause of this crash. You can safely ignore these errors. And update forge while you're at it.
 Stencil buffer state: Function set: GL30, pool: forge, bits: 8
 Launched Version: forge-10.13.4.1614
 LWJGL: 2.9.1
 OpenGL: GeForce GTX 970/PCIe/SSE2 GL version 4.6.0 NVIDIA 416.16, NVIDIA Corporation
 GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

 Is Modded: Definitely; Client brand changed to 'fml,forge'
 Type: Client (map_client.txt)
 Resource Packs: []
 Current Language: English (US)
 Profiler Position: N/A (disabled)
 Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
 Anisotropic Filtering: Off (1)

**Comment by Tahakk** [comment]
1.7.10 is not supported anymore, move on

**Comment by KingLemming** [comment]
That crash is LOTR, not us
