### ISSUE TITLE
Disabled Excavator Tools still show in JEI for Induction

### ISSUE THREAD

**Issue by tgstyle** [CoFH/Feedback#1317]
Easy fix I should think.

![image](https://user-images.githubusercontent.com/5832709/46631564-068d5200-cb05-11e8-8060-118216f4ccc5.png)

**Comment by KingLemming** [comment]
Is it *just* the Excavator that does this, or is the Excavator the only tool that you've disabled?

**Comment by tgstyle** [comment]
It is just the excavator, other disabled tools remove out of the induction furnace just fine.

**Comment by KingLemming** [comment]
So this actually affects all tools, and not just the Excavator. I feel like you didn't properly check that.

Also, there is no good fix for this that isn't a horrible ugly kludge and wouldn't potentially break other mods entirely, so sorry.

**Comment by KingLemming** [comment]
Eh, I don't care about the code quality at this point I suppose, so I'll kludge it up. It makes me physically ill on some level, but whatever.

**Comment by tgstyle** [comment]
Odd here is my configs tools section, the only ones showing are the excavators.

https://gist.github.com/tgstyle/1ce98fbff7f4f196e7bc4088e6d4f6cf

**Comment by tgstyle** [comment]
Full Equipment section after it reloads it in.

https://gist.github.com/tgstyle/2ff4813b8d9484ca7db06ddec70b663a
