### ISSUE TITLE
[Support?] CoFH Core and it's enchanting methods

### ISSUE THREAD

**Issue by ZombieHDGaming** [CoFH/Feedback#1319]
Hello.
I'm ZombieHDGaming and I'm a mod developer and head of DimensionalDevelopment and I work on the mods VanillaFix and JustEnoughIDs. Recently, I released an update for JustEnoughIDs that expands the normal vanilla enchantment limits and potion limits (I haven't looked into potions and how they are handled throughout the thermal series, but we'll come back to that later) to Integer.MAX_VALUE -1 by modifying some classes via ASM and Mixins, to which I've found that CoFHCore has it's own enchantment methods for some reason (if you'd be willing to shed some light, that would be great) and it uses basically the vanilla way of getting enchantments but via your own methods. I was hoping there could be some way that we could work on compatibility between the mods and possibly prevent an issue from happening, even if getting to the normal Vanilla enchantment ID limit is very rare. I know the mod isn't very big yet, but it's slowly being put into more and more packs and would like to prevent headaches on both sides if possible.

I'm on your Discord and can find me with the same name on there if you'd like to talk on there or limit conversations to this issue would be fine as well.

Thanks,
Zombie

**Comment by KingLemming** [comment]
I'd prefer to handle stuff like this in the Discord, yes. I don't use the Issue Tracker as a forum.
