### ISSUE TITLE
Suggestion, config to disable storage mod of compactor.

### ISSUE THREAD

**Issue by Malus-Lupo** [CoFH/Feedback#132]
I would love a way to disable the storage mod of the compactor with out having to disable the whole thing. It would make a project I am working on a little easier and some people might like it because you can craft nuggets and blocks in a table as well.

**Comment by KingLemming** [comment]
> some people might like it because you can craft nuggets and blocks in a table as well.

The compactor doesn't remove those recipes, so I don't understand how this is relevant.

As it stands I'm not really likely to do this, because it's a fairly substantial rewrite to the machine for what I consider to be no actual gain. What are you working on exactly?

**Comment by Malus-Lupo** [comment]
I made it so you use plates instead of ingots, I also made it so you can craft 3 plates for 2 ingots, to encourage using machines instead of just using hammer IE crafting of plates. But because I change the ore dictionary in such a way you can loop craft blocks with plates then turn the blocks back into ingots and craft plates out of them increasing the amount of plates each loop. I can craft tweaker away the crafting of blocks but the Compactor does not seem to have craft tweaker support yet so you can still make blocks in it. I like the compactor because I am currently using it as mid tier plate crafting and do not wish to disable all of it. 

If its a lot of coding tho It is not a huge deal I can work around it. Thank you for replying tho, I love your new versions of Thermal Mods, the moment they came out I started using them xD

**Comment by KingLemming** [comment]
Ah okay. Yeah, the more elegant solution is for CraftTweaker to simply support the device.

Disabling Storage entirely would mean that Dust -> Block recipes would also disappear for things like Redstone and Glowstone. I'll see what can be done.

**Comment by Malus-Lupo** [comment]
I think they are working on updating there Thermal support. Pretty sure I saw a thing about it in there Gethub. Thanks again.

**Comment by KingLemming** [comment]
Yeah, after giving it more thought, I have to give this one a solid, "won't add," sorry.
