### ISSUE TITLE
Induction Smelter recipe removal via ModTweaker fails since TE 5.5.1.33

### ISSUE THREAD

**Issue by duely** [CoFH/Feedback#1320]
ModTweaker [#692](https://github.com/jaredlll08/ModTweaker/issues/692) has an issue where the most recent release of Thermal Expansion causes recipe removals for the Induction Smelter involving flux (i.e., sand) to fail silently. 

Changes to getRecipe involved a considerable amount of work modifying ComparableItemStacks to find the correct recipe to remove; removeRecipe, on the other hand, simply converts the inputs directly and then calls Object2ObjectHashMap::remove with them. This means that while getRecipe will return the correct recipe, there's a chance that removeRecipe will fail completely and return null.

I'll file a PR for this shortly, although I do not believe this is necessarily the best nor correct method for fixing it as it involves code duplication.

**Comment by KingLemming** [comment]
Please don't make an Issue AND a PR. Just make the PR.

I'll think about a "more proper" way to handle it, but see my concerns about the metadata syntax.
