### ISSUE TITLE
CofH Not Working Please Help

### ISSUE THREAD

**Issue by GoldChamber63** [CoFH/Feedback#1323]
I have some problem with some mods but for some reason cofhcore keeps saying 

you must include the right dependencies for CoFH Core:

btw i tried ALL of the redstone flux version top to bottom

Requires Redstone Flux 2.1.0 or above, and below 2.2.0 (you have 2.0.2)

my forge is forge-1.12.2-14.23.5.2768-installer-win

All Mods
aether_legacy-1.12.2-v3.2
candyworld-1.1.1
CodeChickenLib-1.12.2-3.2.2.353-universal
CoFHCore-1.12.2-4.6.1.22-universal
Extra-Utilities-Mod-1.12.1
ForgeMultipart-1.12.2-2.4.2.60-universal
jei_1.12.2-4.8.0.118
JustEnoughResources-1.12.2-0.8.7.41
MrTJPCore-1.12.2-2.1.3.35-universal
Not-Enough-Items-1.12.2-Recommended
OptiFine_1.12.2_HD_U_C8
ProjectRed-1.12.2-4.9.1.92-Base
RedstoneFlux-1.12-2.0.2.3-universal

**Comment by Tahakk** [comment]
You are doing something wrong on top of your mod versions, I was able to replicate your pack in 2 minutes with successful start to menu. Use proper version.

**Comment by covers1624** [comment]
You literelly state your issue in the description, `Requires Redstone Flux 2.1.0 or above, and below 2.2.0 (you have 2.0.2)`, You need RedstoneFlux 2.1.0, you even list `RedstoneFlux-1.12-2.0.2.3-universal` and that is 2.0.2. Update, Its not rocket science. https://minecraft.curseforge.com/projects/redstone-flux/files/2623090
