### ISSUE TITLE
Fluxbore targeting issue in Mechanical Users

### ISSUE THREAD

**Issue by Djd96** [CoFH/Feedback#1326]
Thermal Innovation 0.3.1  MC 1.12.2
Modlist:
https://pastebin.com/9RezRKVR

All CoFH mods are updated, and the issue is repeatable with mods other than ExUtil, so I believe that this is a Thermal issue.  

https://imgur.com/gallery/Q9CSheV

Essentially, any time a machine uses the fluxbore on a block, the affected block is not centered where the machine is facing.  Instead it seems offset, and includes the machine in the mining radius.  

Let me know if there is any more information you need or if there's any testing I can do.

**Comment by KingLemming** [comment]
Not actually going to be on our end. The fact that you get the same behavior with 2 Fake Players just means that they are both coded in such a way to make this happen.

The Fluxbore performs a retrace from the player. If the targeting is "off", it's because the player is off to begin with.
