### ISSUE TITLE
Suggestion: Thermal Expansion Augments, make them easier searchable through JEI

### ISSUE THREAD

**Issue by Linkitch** [CoFH/Feedback#1327]
I would love if we could use the #item description to find Augments for a specific machine. Right now it's not possible to search e.g. @thermal augment #redstone, since the label is hidden behind having to hold down Shift.
This change would make it much easier to find the augments you are looking for.

**Comment by Tonius** [comment]
You could make it so that the first part of the tooltip (e.g. `Redstone Furnace: Specialization`) is always shown. That way, JEI should find it when you search for the name of a machine or dynamo.
