### ISSUE TITLE
Unknown crash in insertItem

### ISSUE THREAD

**Issue by puujam** [CoFH/Feedback#1328]
My server's crashing readily on restart with the associated callstack. Every time I restart it it's happening again, even before anyone connects. Unsure of the cause, hoping for a solution/suggestion. Thanks!

[crash-2018-10-18_21.20.50-server.txt](https://github.com/CoFH/Feedback/files/2494108/crash-2018-10-18_21.20.50-server.txt)

**Comment by KingLemming** [comment]
Sorry, but 1.10.2 is unsupported. The particular error here is that something has incorrectly decided to provide a null ItemStack (that's bad).

Unfortunately there's no way to know which mod provided said stack or how it became null. You can "save" your server by temporarily uninstalling TD, or using MCEdit to remove the tile entity in question.

I really recommend updating to 1.12.2 though, as mods seem to have figured it out and no longer do the stupid stuff that causes this.

**Comment by puujam** [comment]
Thanks so much for the quick reply! And for all the work you do!

**Comment by KingLemming** [comment]
Sure thing. I'm sorry that I don't have a better answer for you. The stacktrace shows what happened but not the root cause I'm afraid. :(

Good luck!
