### ISSUE TITLE
1.12.2 crash with redstone flux

### ISSUE THREAD

**Issue by XxRockDudexX** [CoFH/Feedback#1329]
help my game crash when i start with redstone flux
crash report things
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Redstone Flux (redstoneflux)

---- Minecraft Crash Report ----

WARNING: coremods are present:
  PistonExpansionLoadingPlugin (pistonexpansion-1.12.2-1.0.1-core.jar)
  ObfuscatePlugin (obfuscate-0.2.6-1.12.2.jar)
  NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
  ShutdownPatcher (mcef-1.12.2-0.9-coremod.jar)
Contact their authors BEFORE contacting forge

// My bad.

Time: 10/18/18 7:22 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Redstone Flux (redstoneflux)
Caused by: java.lang.RuntimeException: 
RedstoneFlux has detected that the following OLD API classes from CoFHLib are being repacked!
    cofh.api.energy.ItemEnergyContainer, loaded from: ElectricalAge-1.14.2.jar
    cofh.api.energy.EnergyStorage, loaded from: ElectricalAge-1.14.2.jar
    cofh.api.energy.TileEnergyHandler, loaded from: ElectricalAge-1.14.2.jar
    cofh.api.energy.IEnergyConnection, loaded from: ElectricalAge-1.14.2.jar
    cofh.api.energy.IEnergyProvider, loaded from: ElectricalAge-1.14.2.jar
    cofh.api.energy.IEnergyHandler, loaded from: ElectricalAge-1.14.2.jar
    cofh.api.energy.IEnergyStorage, loaded from: ElectricalAge-1.14.2.jar
    cofh.api.energy.IEnergyContainerItem, loaded from: ElectricalAge-1.14.2.jar
    cofh.api.energy.IEnergyReceiver, loaded from: ElectricalAge-1.14.2.jar

To prevent this crash, add "-Dcofh.rf.crashOnOldAPI=false" to your command line arguments.

	at cofh.redstoneflux.internal.OldAPIChecker.check(OldAPIChecker.java:64)
	at cofh.redstoneflux.RedstoneFlux.preInit(RedstoneFlux.java:25)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2824863712 bytes (2693 MB) / 3221225472 bytes (3072 MB) up to 3221225472 bytes (3072 MB)
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G -Xms3G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2770 Optifine OptiFine_1.12.2_HD_U_E2 38 mods loaded, 38 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                        | Version         | Source                                        | Signature                                |
	|:----- |:------------------------- |:--------------- |:--------------------------------------------- |:---------------------------------------- |
	| UCH   | minecraft                 | 1.12.2          | minecraft.jar                                 | None                                     |
	| UCH   | mcp                       | 9.42            | minecraft.jar                                 | None                                     |
	| UCH   | FML                       | 8.0.99.99       | forge-1.12.2-14.23.5.2770.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge                     | 14.23.5.2770    | forge-1.12.2-14.23.5.2770.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | obfuscate                 | 0.2.6           | minecraft.jar                                 | None                                     |
	| UCH   | bookshelf                 | 2.3.559         | Bookshelf-1.12.2-2.3.559.jar                  | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCH   | cfm                       | 5.14.0          | cfm-5.14.0-mc1.12.2.jar                       | None                                     |
	| UCH   | codechickenlib            | 3.2.2.353       | CodeChickenLib-1.12.2-3.2.2.353-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCH   | computercraft             | 1.80pr1         | ComputerCraft-Mod-1.12.1.jar                  | None                                     |
	| UCH   | customnpcs                | 1.12            | Custom-NPCs-Mod-1.12.2.jar                    | None                                     |
	| UCH   | jei                       | 4.12.1.217      | jei_1.12.2-4.12.1.217.jar                     | None                                     |
	| UCH   | darkutils                 | 1.8.211         | DarkUtils-1.12.2-1.8.211.jar                  | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCH   | elevatorid                | 1.3.6           | ElevatorMod-1.12.2-1.3.6.jar                  | None                                     |
	| UCEE  | redstoneflux              | 2.0.1           | RedstoneFlux-1.12-2.0.1.2-universal (1).jar   | d4f1503fbacd9b9fb767720420c5395104239ec9 |
	| UC    | sonarcore                 | 5.0.16          | sonarcore-1.12.2-5.0.16-16.jar                | None                                     |
	| UC    | fluxnetworks              | 3.0.16          | fluxnetworks-1.12.2-3.0.16-11.jar             | None                                     |
	| UC    | forgemultipartcbe         | 2.6.0.79        | ForgeMultipart-1.12.2-2.6.0.79-universal.jar  | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UC    | microblockcbe             | 2.6.0.79        | ForgeMultipart-1.12.2-2.6.0.79-universal.jar  | None                                     |
	| UC    | minecraftmultipartcbe     | 2.6.0.79        | ForgeMultipart-1.12.2-2.6.0.79-universal.jar  | None                                     |
	| UC    | harvestcraft              | 1.12.2w         | HarvestCraft-Mod-1.12.2.jar                   | None                                     |
	| UC    | icbmclassic               | 1.12.2-3.0.0.29 | ICBM-classic-1.12.2-3.0.0b29.jar              | None                                     |
	| UC    | mcef                      | 0.9             | mcef-1.12.2-0.9.jar                           | None                                     |
	| UC    | cgm                       | 0.6.3           | MrCrayfishs-Gun-1.12.2.jar                    | None                                     |
	| UC    | mrtjpcore                 | 2.1.3.35        | MrTJPCore-1.12.2-2.1.3.35-universal.jar       | None                                     |
	| UC    | projectred-core           | 4.9.1.92        | ProjectRed-1.12.2-4.9.1.92-Base.jar           | None                                     |
	| UC    | projectred-integration    | 4.9.1.92        | ProjectRed-1.12.2-4.9.1.92-integration.jar    | None                                     |
	| UC    | projectred-transmission   | 4.9.1.92        | ProjectRed-1.12.2-4.9.1.92-integration.jar    | None                                     |
	| UC    | projectred-fabrication    | 4.9.1.92        | ProjectRed-1.12.2-4.9.1.92-fabrication.jar    | None                                     |
	| UC    | projectred-illumination   | 4.9.1.92        | ProjectRed-1.12.2-4.9.1.92-lighting.jar       | None                                     |
	| UC    | projectred-expansion      | 4.9.1.92        | ProjectRed-1.12.2-4.9.1.92-mechanical.jar     | None                                     |
	| UC    | projectred-relocation     | 4.9.1.92        | ProjectRed-1.12.2-4.9.1.92-mechanical.jar     | None                                     |
	| UC    | projectred-transportation | 4.9.1.92        | ProjectRed-1.12.2-4.9.1.92-mechanical.jar     | None                                     |
	| UC    | projectred-exploration    | 4.9.1.92        | ProjectRed-1.12.2-4.9.1.92-world.jar          | None                                     |
	| UC    | redstonepaste             | 1.7.5           | redstonepaste-mc1.12-1.7.5.jar                | None                                     |
	| UC    | webdisplays               | 1.0             | webdisplays-1.12.2-1.0.jar                    | None                                     |
	| UC    | wrcbe                     | 2.3.1           | WR-CBE-1.12.2-2.3.1.30-universal.jar          | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UC    | xaerominimap              | 1.13.9          | Xaeros-Minimap-Mod-1.12.jar                   | None                                     |
	| UC    | pistonexpansion           | 1.0.1           | pistonexpansion-1.12.2-1.0.1.jar              | 7b14aaee2dd17b12a140baecab28948fff3a263f |

	Loaded coremods (and transformers): 
PistonExpansionLoadingPlugin (pistonexpansion-1.12.2-1.0.1-core.jar)
  com.github.upcraftlp.pistonexpansion.asm.PistonExpansionTransformer
ObfuscatePlugin (obfuscate-0.2.6-1.12.2.jar)
  com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
  net.fybertech.nwr.NWRTransformer
ShutdownPatcher (mcef-1.12.2-0.9-coremod.jar)
  net.montoyo.mcef.coremod.ShutdownPatcher
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13539 Compatibility Profile Context 24.20.13011.1009' Renderer: 'Radeon 550 Series'
	OptiFine Version: OptiFine_1.12.2_HD_U_E2
	OptiFine Build: 20180728-185429
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.13539 Compatibility Profile Context 24.20.13011.1009
	OpenGlRenderer: Radeon 550 Series
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 4

**Comment by covers1624** [comment]
```
RedstoneFlux has detected that the following OLD API classes from CoFHLib are being repacked!
cofh.api.energy.ItemEnergyContainer, loaded from: ElectricalAge-1.14.2.jar
cofh.api.energy.EnergyStorage, loaded from: ElectricalAge-1.14.2.jar
cofh.api.energy.TileEnergyHandler, loaded from: ElectricalAge-1.14.2.jar
cofh.api.energy.IEnergyConnection, loaded from: ElectricalAge-1.14.2.jar
cofh.api.energy.IEnergyProvider, loaded from: ElectricalAge-1.14.2.jar
cofh.api.energy.IEnergyHandler, loaded from: ElectricalAge-1.14.2.jar
cofh.api.energy.IEnergyStorage, loaded from: ElectricalAge-1.14.2.jar
cofh.api.energy.IEnergyContainerItem, loaded from: ElectricalAge-1.14.2.jar
cofh.api.energy.IEnergyReceiver, loaded from: ElectricalAge-1.14.2.jar
```
Remove that mod from your mods folder. It isn't even displayed in the mods list meaning its probably a mod for 1.7 not 1.12.
