### ISSUE TITLE
CoFH Core causes Cauldron server crash when installed

### ISSUE THREAD

**Issue by thormbush42** [CoFH/Feedback#133]
This issue was previously reported, however the given response was somewhere along the lines of "Because Cauldron is not available any more, I will not support it" - Cauldron is now (legally) publicly available.

No crash log was created, so this is directly copied from the server: http://pastebin.com/zccwR7dp

Minecraft 1.7.10; CoFH Core 3.0.0B9-40

**Comment by skyboy** [comment]
This crash is caused by you not having the ASM5 library (instead having ASM4) on your path and is unrelated to any other reported crashes. This is a problem explicitly with your installation and you will need to correct it.

**Comment by thormbush42** [comment]
How would I go about doing that exactly?
