### ISSUE TITLE
Crash when placing Igneous Extruder

### ISSUE THREAD

**Issue by Luckyday84** [CoFH/Feedback#1330]
Java 9 -191
Single player game
Forge 14.23.5.2772
ThermalExpansion-1.12.2-5.5.2.39
https://pastebin.com/9GuP9T5U

Everytime I place a Igneous Extruder it crashes my client and when I boot back into my game I have the one placed in the world and one still in my inventory. I tested Forge 14.23.5.2768 and still got the same crash.

**Comment by Luckyday84** [comment]
So when I place any Thermal expansion machine block I get this crash.

**Comment by Luckyday84** [comment]
so with just thermal expansion and its core mods it works fine. So its a conflict with another mod. Ive already tried removing and testing without optifine, foam fix and better fps with no luck.

**Comment by KingLemming** [comment]
Yup. Another mod entirely I'm afraid. You seem to have something which changes the ID of the Purpur Slab.

No bueno. Dunno what that is, but it's not us, sorry.

**Comment by KingLemming** [comment]
Nope, and I also can't replicate that either I'm afraid.

**Comment by neronakoma** [comment]
ok. we did a pack update. if it still happens ill see about getting you logs
