### ISSUE TITLE
Suggestion: Oxygen recovery augment for Pytogenic insolator

### ISSUE THREAD

**Issue by EnderiumSmith** [CoFH/Feedback#1331]
This will add a secondary tank to the insolator that will accumulate oxygen gas. The main point for this is as compat for galacticraft. The default amount generated should be set as to have a reinforced insolator power an oxygen sealer. The oxygen counts as secondary output so if the nullification chamber is installed the insolator will still work with a full tank.

Why add this? Because off-world hydrophonics is way cooler than farms! That and the oxygen collector does not collect from full grown crops so you need another mod to add autofarms.

PS: This should be a normal augment so it does not conflict with the monoculture specialization

**Comment by KingLemming** [comment]
Sorry, but no. I don't plan on adding augments to support very specific things relating to very specific mods. This is a very niche application and TE itself would have no use for such a thing.

**Comment by EnderiumSmith** [comment]
Would an outside mod even have access the the internals needed to calculate how much it should generate?
