### ISSUE TITLE
Disabled tools still showing in JEI v2.6.1.22

### ISSUE THREAD

**Issue by TheQuantumGeneral** [CoFH/Feedback#1332]
# Configuration file

}

Equipment {
    # If TRUE, recipes for all Armor Sets are disabled. [default: false]
    B:DisableAllArmorRecipes=true

    # If TRUE, recipes for all new Bows will be disabled, leaving only the Vanilla Bow [default: false]
    B:DisableAllBows=true

    # If TRUE, recipes for all new Fishing Rods will be disabled, leaving only the Vanilla (Wood) Fishing Rod [default: false]
    B:DisableAllFishingRods=true

    # If TRUE, recipes for all new Shears will be disabled, leaving only the Vanilla (Iron) Shears. [default: false]
    B:DisableAllShears=true

    # If TRUE, recipes for all new Shields will be disabled, leaving only the Vanilla (Wood) Shield [default: false]
    B:DisableAllShields=true

    # If TRUE, recipes for all Tools are disabled. [default: false]
    B:DisableAllToolRecipes=true

    # If TRUE, recipes for new Vanilla material (Wood, Stone, Iron, Gold, Diamond) Tools are disabled. [default: false]
    B:DisableVanillaToolRecipes=false

    # If TRUE, items which have had their recipes disabled will show in the Creative Tab and JEI. [default: false]
    B:ShowDisabledEquipment=false

![2018-10-21_18 59 10](https://user-images.githubusercontent.com/7843312/47264465-897dc600-d563-11e8-9f06-c77a752cbb99.png)

**Comment by KingLemming** [comment]
Just tested with the latest releases. This absolutely isn't the case.

I don't know what you're doing wrong, but the config works as expected.
