### ISSUE TITLE
Servo pulling from empty portable tank causing chunk updates

### ISSUE THREAD

**Issue by jamthief** [CoFH/Feedback#1334]
Using version 5.5.0.29.
FPS spikes occurring due to an abundance of chunk updates.
Reproducible by placing any fluiduct + any servo set to 'Ignore' and pulling from an empty portable tank.

**Comment by KingLemming** [comment]
Okay, cool. Don't do that then.

**Comment by Tora-B** [comment]
Ooh, I wonder if this was actually the cause of my FPS issue with tanks. Empty tanks outputting into other tanks...
