### ISSUE TITLE
MC1.12.2 Thermal Innovation : Crafting potion + Hypoinfuser causes java.lang.ArithmeticException: / by zero after use

### ISSUE THREAD

**Issue by n-3-0** [CoFH/Feedback#1336]
Using Forge in a server environment (server + client version 14.23.5.2768), I have Thermal Foundation (2.6.1.22), Expansion (5.5.2.39), Innovation (0.3.1.8), and Dynamics (2.5.3.16) installed amongst [my usual mods](https://pastebin.com/3Nw3UVa5).

In a crafting table, I combined a Creative Hypoinfuser with a [Potion-Core](https://minecraft.curseforge.com/projects/potion-core) Potion of Mending (Repairing II), went into survival mode, and used it upon myself (shift + right click). Worked fine for a moment, and then my client crashed. I was wearing damaged enchanted vanilla armor (some enchantments were from other mods like OpenBlocks), and had some damaged tools in my inventory. Server is behaving normally, however, now every attempt to connect to it results in the same crash.

Attached below is the client crashlog, the server reports no errors aside from the fact that my client socket has closed due to the crash. It seems that [`ItemInjector`'s `typeMap` could be the problem](https://github.com/CoFH/ThermalInnovation/blob/76d2a0e164462275a13eb4d2cb3f3e29671050bb/src/main/java/cofh/thermalinnovation/item/ItemInjector.java#L209), or the `capacity` for that entry is somehow set to zero (not sure this is the case, since in my config [BaseCapacity is set to 2000 for the injector](https://pastebin.com/4ywnvwU3)). Naturally, if neither of those are the issue, then perhaps it's Potion-Core's potion effect. I thought I'd go to you folks first, since the exception is thrown on your side.

Please let me know if you need more information. I assume that I'll not be able to get into the server until the potion effect wears off (going to attempt to use an NBT editor to delete the status effect on my player file), but I can do my best to provide more details.

[crash-2018-10-23_23.56.35-client.txt](https://github.com/CoFH/Feedback/files/2509186/crash-2018-10-23_23.56.35-client.txt)

**Comment by n-3-0** [comment]
I used NBTExplorer to delete the Hypoinfuser from my inventory, and I am once again able to connect. I'm guessing it's a rendering issue with ItemInjector.

**Comment by KingLemming** [comment]
This can't actually happen without some sort of item corruption, but I've gone ahead and added a mitigation in dev.
