### ISSUE TITLE
Game Crash when Shift Right-Click with Auxiliary Reception Coil for add upgrade

### ISSUE THREAD

**Issue by Fireztonez** [CoFH/Feedback#1338]
During some tests in creative I create a redstone Furnace and upgrade to Resonant Tier and i Shift Click on a stack of Auxiliary Reception Coil question to rapidly add all upgrade needed on the machine and the game crash directly after I see the 4 augments added on the machine.

When I try on server the server both client and server have crash... And on Single player, the game crash too. 

I try on a compactor and it does the same thing, so I imagine this will happen on all machines.

I try with "Hardened Tier" and there have no problem when I shift-click to add the augments, but with the "Reinforced Tier" the same bug happen. And if you have only one slot upgrade available this bug doesn't happen... So the bug look to be only when it add multiple upgrade at the same time...

Crash logs: https://gist.github.com/Fireztonez/dd8d45b7ee9d708e5c3cfa63103c32e7

Version:
Minecraft: 1.12.2
Forge: 14.23.5.2768
CoFH Core: 4.6.1.22
CoFH World: 1.3.0.6
Thermal Fondation: 2.6.1.22
Thermal Expension: 5.5.2.39
Thermal Dynamics: 2.5.3.16
Java: 8 upgrade 181

If you need more information, I will try my best to give you the information you need.

Fireztonez

**Comment by covers1624** [comment]
```
java.lang.NullPointerException: Ticking player
	at thut.essentials.util.InventoryLogger$Listener.func_71111_a(InventoryLogger.java:43)
```
This is not a crash from CoFH, Report to the owner of `thutessentials-1.12.2-2.2.16.jar`
