### ISSUE TITLE
[Version Problem] Requiring Wrong Version.

### ISSUE THREAD

**Issue by KakarotoCm** [CoFH/Feedback#134]
I just make a quick modpack to test the new thermal dynamics mod and got this bug:
![](http://i.gyazo.com/492c5c7ea56b76761a42731809512687.png)

dont think you will need the log but here it is: http://paste.ee/p/fFLr3

**Comment by KingLemming** [comment]
You downloaded TE for 1.6.4.

Curse has been derping. Try downloading all of them fresh please - they've just sorted it out.
