### ISSUE TITLE
[1.7.10] [Thermal dynamics] A TileEntity type cofh.thermaldynamics.duct.item.TileItemDuct has throw an exception trying to write state.

### ISSUE THREAD

**Issue by zerofex** [CoFH/Feedback#134]
**Include the mod name and version.**
Looks like it is Thermal Dynamics.   

Minecraft version 1.7.10 
ThermalDynamics-[1.7.10]1.2.0-171
Forge 1614

**Include a pastebin (or equivalent) link to a list of all your mods.**
http://www.fileconvoy.com/dfl.php?id=ga0feb006c8b79c1999994668510f675985063c75d
**_DUE TO POOR CHOICES IN THE FREE-FILE UPLOAD MARKET, THIS LINK WILL BE VALID FOR ONLY 21 DAYS PAST THE CREATION OF THIS POST. SORRY._**

**Include the crash log**
It doesn't crash. But I kept noticing this error pop up on my server console: http://imgur.com/a/Gubfi

Investigating further, I found this in my client log: 
[14:02:35] [pool-6-thread-1/ERROR] [FML]: A TileEntity type cofh.thermaldynamics.duct.item.TileItemDuct has throw an exception trying to write state. It will not persist. Report this to the mod author
java.lang.NullPointerException    

Which is why I am here. It asked me to report it, so report I am.   

**FULL CLIENT LOG**: https://paste.ee/p/luZub

**FULL SERVER LOG**: https://paste.ee/p/UDxEm

**Be descriptive.**
First noticed an error on my server console screen after dying. This error in particular: http://imgur.com/a/Gubfi   
Then I noticed in my client log it said COFH. And the error asked me to report it here.   
The error seems to trigger when I die, but not every time. I have an occasional and random lag spike that occurs too; I tried to see if the error pops up at the same time, but it hasn't yet. So it may or may not be related. Gameplay is very smooth and normal other than these spikes. I included my configs and mods folder too, as well as full logs from my client and server. Please let me know if there is anything else you need to fix this and I would be glad to provide it.   

Cheers!

**Be respectful.**
Done.

**Use proper grammar and spelling.**
nou

**Comment by KingLemming** [comment]
There's really nothing to do here. You either have corruption in your save, or that's a quirk of something strange that MapWriter is doing. If this were in our code, it would happen consistently to every save out there.

Also, you're out of date. 1.2.1 is the final version for 1.7.10. :)

**Comment by zerofex** [comment]
Is this a world destroying error or something that can be ignored?

**Comment by KingLemming** [comment]
It's likely safe to ignore. My guess is that it's something MapWriter does. You can fix it by removing your duct connections and replacing them.

If you've recently added/removed mods, then it's possible that the duct connection (filter/retriever/servo) has an invalid item in one of the slots or something like that.

**Comment by zerofex** [comment]
I see. I'll will change things around and see how they work.  

Thanks again.
