### ISSUE TITLE
Server Tick Loop Error with a Servo

### ISSUE THREAD

**Issue by Algester** [CoFH/Feedback#1342]
https://pastebin.com/PqxMCT7j

I'm not sure if pastebin was the right place to go with... but yeah it maybe partially be my fault as well

**Comment by KingLemming** [comment]
Caused by a tile entity which is lying. Basically you have something which claims to be a tank and then isn't actually one.

I can see changing up that code to call out the liars, but unfortunately I can't stop them. :( This is something you'll have to worldedit out.

**Comment by Algester** [comment]
thanks for the heads up
