### ISSUE TITLE
CoFHCore 3.1.4 source code?

### ISSUE THREAD

**Issue by kmecpp** [CoFH/Feedback#1344]
The source code of the 1.7.10 branch of CoFHCore has the [version 3.0.4](https://github.com/CoFH/CoFHCore/blob/1.7.10/build.gradle#L20) but the latest version released on curse is 3.1.4.

Is it possible the source code for the latest version could be added to the repository's 1.7.10 branch?

**Comment by KingLemming** [comment]
That's literally just a thing in the gradle, the code is 3.1.4. For 1.7.10, we didn't use gradle at all.

Also, please go to the Discord for stuff like this - this isn't an issue.
