### ISSUE TITLE
Redstone flux issue

### ISSUE THREAD

**Issue by obsoHD** [CoFH/Feedback#1345]
i have a problem with minecraft redstoneflux i am unable to play using y custom modpack 

The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Redstone Flux (redstoneflux)

**Comment by KingLemming** [comment]
Yeah, so basically you made your pack wrong. Feel free to come by the Discord and ask, but please don't use the tracker for stuff like this. This is clearly something on your end.
