### ISSUE TITLE
Minecraft Crash with RedstoneFlux 2.1.0.6

### ISSUE THREAD

**Issue by ItzPezus** [CoFH/Feedback#1346]
Hello, i have a problem, im trying to play Minecraft, and CoFH World and core requires redstoneflux, the problem is when i put Redstoneflux2.1.0.6 in the mods folder my game crashes, here is the console with all the errors, Thanks in advance 
---- Minecraft Crash Report ----

WARNING: coremods are present:
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.41.jar)
  AstralCore (astralsorcery-1.12.2-1.9.4.jar)
  LoadingPlugin (Quark-r1.5-130.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.2-1.12.2.jar)
Contact their authors BEFORE contacting forge

// My bad.

Time: 10/31/18 10:14 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Redstone Flux (redstoneflux)
Caused by: java.lang.RuntimeException: 
RedstoneFlux has detected that the following OLD API classes from CoFHLib are being repacked!
    cofh.api.energy.ItemEnergyContainer, loaded from: PRExtended%5B1.7.10%5D-BETA-0.3.jar
    cofh.api.energy.EnergyStorage, loaded from: PRExtended%5B1.7.10%5D-BETA-0.3.jar
    cofh.api.energy.TileEnergyHandler, loaded from: PRExtended%5B1.7.10%5D-BETA-0.3.jar
    cofh.api.energy.IEnergyConnection, loaded from: PRExtended%5B1.7.10%5D-BETA-0.3.jar
    cofh.api.energy.IEnergyProvider, loaded from: PRExtended%5B1.7.10%5D-BETA-0.3.jar
    cofh.api.energy.IEnergyHandler, loaded from: PRExtended%5B1.7.10%5D-BETA-0.3.jar
    cofh.api.energy.IEnergyStorage, loaded from: PRExtended%5B1.7.10%5D-BETA-0.3.jar
    cofh.api.energy.IEnergyContainerItem, loaded from: PRExtended%5B1.7.10%5D-BETA-0.3.jar
    cofh.api.energy.IEnergyReceiver, loaded from: PRExtended%5B1.7.10%5D-BETA-0.3.jar

To prevent this crash, add "-Dcofh.rf.crashOnOldAPI=false" to your command line arguments.

	at cofh.redstoneflux.internal.OldAPIChecker.check(OldAPIChecker.java:64)
	at cofh.redstoneflux.RedstoneFlux.preInit(RedstoneFlux.java:18)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_191, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 247547984 bytes (236 MB) / 697733120 bytes (665 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 Optifine OptiFine_1.12.2_HD_U_E2 52 mods loaded, 52 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                                | Version                  | Source                                          | Signature                                |
	|:----- |:--------------------------------- |:------------------------ |:----------------------------------------------- |:---------------------------------------- |
	| UCH   | minecraft                         | 1.12.2                   | minecraft.jar                                   | None                                     |
	| UCH   | mcp                               | 9.42                     | minecraft.jar                                   | None                                     |
	| UCH   | FML                               | 8.0.99.99                | forge-1.12.2-14.23.5.2768.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge                             | 14.23.5.2768             | forge-1.12.2-14.23.5.2768.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | foamfixcore                       | 7.7.4                    | minecraft.jar                                   | None                                     |
	| UCH   | actuallyadditions                 | 1.12.2-r143              | ActuallyAdditions-1.12.2-r143.jar               | None                                     |
	| UCH   | jei                               | 4.12.1.217               | jei_1.12.2-4.12.1.217.jar                       | None                                     |
	| UCH   | appleskin                         | 1.0.9                    | AppleSkin-mc1.12-1.0.9.jar                      | None                                     |
	| UCH   | baubles                           | 1.5.2                    | Baubles-1.12-1.5.2.jar                          | None                                     |
	| UCH   | astralsorcery                     | 1.9.4                    | astralsorcery-1.12.2-1.9.4.jar                  | a0f0b759d895c15ceb3e3bcb5f3c2db7c582edf0 |
	| UCH   | quark                             | r1.5-130                 | Quark-r1.5-130.jar                              | None                                     |
	| UCH   | autoreglib                        | 1.3-20                   | AutoRegLib-1.3-20.jar                           | None                                     |
	| UCH   | thaumcraft                        | 6.1.BETA26               | Thaumcraft-1.12.2-6.1.BETA26.jar                | None                                     |
	| UCH   | botania                           | r1.10-357                | Botania+r1.10-357.jar                           | None                                     |
	| UCH   | clumps                            | 3.1.1                    | Clumps-3.1.1.jar                                | None                                     |
	| UCH   | codechickenlib                    | 3.2.2.353                | CodeChickenLib-1.12.2-3.2.2.353-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCEE  | redstoneflux                      | 2.1.0                    | RedstoneFlux-1.12-2.1.0.6-universal.jar         | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UC    | cofhcore                          | 4.6.0                    | CoFHCore-1.12.2-4.6.0.21-universal.jar          | None                                     |
	| UC    | cofhworld                         | 1.2.0                    | CoFHWorld-1.12.2-1.2.0.5-universal.jar          | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UC    | mantle                            | 1.12-1.3.3.39            | Mantle-1.12-1.3.3.39.jar                        | None                                     |
	| UC    | endercore                         | 1.12.2-0.5.41            | EnderCore-1.12.2-0.5.41.jar                     | None                                     |
	| UC    | thermalfoundation                 | 2.6.1                    | ThermalFoundation-1.12.2-2.6.1.22-universal.jar | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UC    | enderio                           | 5.0.36                   | EnderIO-1.12.2-5.0.36.jar                       | None                                     |
	| UC    | enderiointegrationtic             | 5.0.36                   | EnderIO-1.12.2-5.0.36.jar                       | None                                     |
	| UC    | tconstruct                        | 1.12.2-2.10.1.87         | TConstruct-1.12.2-2.10.1.87.jar                 | None                                     |
	| UC    | conarm                            | 1.2.0                    | conarm-1.12.2-1.2.0.jar                         | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| UC    | enderiobase                       | 5.0.36                   | EnderIO-1.12.2-5.0.36.jar                       | None                                     |
	| UC    | enderioconduits                   | 5.0.36                   | EnderIO-1.12.2-5.0.36.jar                       | None                                     |
	| UC    | enderioconduitsappliedenergistics | 5.0.36                   | EnderIO-1.12.2-5.0.36.jar                       | None                                     |
	| UC    | enderioconduitsopencomputers      | 5.0.36                   | EnderIO-1.12.2-5.0.36.jar                       | None                                     |
	| UC    | enderioconduitsrefinedstorage     | 5.0.36                   | EnderIO-1.12.2-5.0.36.jar                       | None                                     |
	| UC    | ic2                               | 2.8.101-ex112            | industrialcraft-2-2.8.101-ex112.jar             | de041f9f6187debbc77034a344134053277aa3b0 |
	| UC    | natura                            | 1.12.2-4.3.2.62          | natura-1.12.2-4.3.2.62.jar                      | None                                     |
	| UC    | forestry                          | 5.8.1.322                | forestry_1.12.2-5.8.1.322.jar                   | None                                     |
	| UC    | enderiointegrationforestry        | 5.0.36                   | EnderIO-1.12.2-5.0.36.jar                       | None                                     |
	| UC    | enderiointegrationticlate         | 5.0.36                   | EnderIO-1.12.2-5.0.36.jar                       | None                                     |
	| UC    | enderiomachines                   | 5.0.36                   | EnderIO-1.12.2-5.0.36.jar                       | None                                     |
	| UC    | enderiopowertools                 | 5.0.36                   | EnderIO-1.12.2-5.0.36.jar                       | None                                     |
	| UC    | fastleafdecay                     | v14                      | FastLeafDecay-v14.jar                           | None                                     |
	| UC    | fencejumper                       | 1.0.5                    | fencejumper-1.12-1.0.5.jar                      | None                                     |
	| UC    | foamfix                           | 0.10.2-1.12.2            | foamfix-0.10.2-1.12.2.jar                       | None                                     |
	| UC    | inventorytweaks                   | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                        | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UC    | ironbackpacks                     | 1.12.2-3.0.8-12          | IronBackpacks-1.12.2-3.0.8-12.jar               | None                                     |
	| UC    | journeymap                        | 1.12.2-5.5.2             | journeymap-1.12.2-5.5.2.jar                     | None                                     |
	| UC    | modnametooltip                    | 1.10.0                   | modnametooltip_1.12.2-1.10.0.jar                | None                                     |
	| UC    | harvestcraft                      | 1.12.2z                  | Pam's+HarvestCraft+1.12.2za.jar                 | None                                     |
	| UC    | spectrite                         | 1.6.7                    | spectrite-1.6.7.jar                             | 00119cfc089819bbcd2f9166a50c7f3df88ded78 |
	| UC    | theoneprobe                       | 1.4.25                   | theoneprobe-1.12-1.4.25.jar                     | None                                     |
	| UC    | thermaldynamics                   | 2.5.3                    | ThermalDynamics-1.12.2-2.5.3.16-universal.jar   | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UC    | thutcore                          | 5.19.8                   | thutcore-1.12.2-5.19.8.jar                      | None                                     |
	| UC    | thutcore_compat                   | 1.0                      | thutcore-1.12.2-5.19.8.jar                      | None                                     |
	| UC    | thuttech                          | 6.1.5                    | thuttech-1.12.2-6.1.5.jar                       | None                                     |

	Loaded coremods (and transformers): 
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
EnderCorePlugin (EnderCore-1.12.2-0.5.41.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
  com.enderio.core.common.transform.SimpleMixinPatcher
AstralCore (astralsorcery-1.12.2-1.9.4.jar)
  
LoadingPlugin (Quark-r1.5-130.jar)
  vazkii.quark.base.asm.ClassTransformer
Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.2-1.12.2.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 416.34' Renderer: 'GeForce GTX 750 Ti/PCIe/SSE2'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- theoneprobeIntegration (Enabled/Not Forced)

	Pulsar/natura loaded Pulses: 
		- NaturaCommons (Enabled/Forced)
		- NaturaOverworld (Enabled/Not Forced)
		- NaturaNether (Enabled/Not Forced)
		- NaturaDecorative (Enabled/Not Forced)
		- NaturaTools (Enabled/Not Forced)
		- NaturaEntities (Enabled/Not Forced)
		- NaturaOredict (Enabled/Forced)
		- NaturaWorld (Enabled/Not Forced)

	OptiFine Version: OptiFine_1.12.2_HD_U_E2
	OptiFine Build: 20180728-185429
	Render Distance Chunks: 5
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 416.34
	OpenGlRenderer: GeForce GTX 750 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 2

**Comment by KingLemming** [comment]
The error log very clearly states the problem. Why are you here? :/

PRExtended%5B1.7.10%5D-BETA-0.3.jar is the problem. You should remove it.
