### ISSUE TITLE
[Thermal Expansion] Crash with Nullifier NPE

### ISSUE THREAD

**Issue by Dyonovan** [CoFH/Feedback#135]
Could be an issue with Actually Additions as the collector was attached to this. @Ellpeck

Crashlog (Includes mod list): https://gist.github.com/Dyonovan/3e7867b5953b999522388ad1a41dd746
TE: 5.0.4.90
Forge: 12.18.3.2254

**Comment by KingLemming** [comment]
I'll mitigate this, but it's an utter failure on Forge's part.
