### ISSUE TITLE
Arcane Ensorcellator can craft disabled CoFH Core enchantments

### ISSUE THREAD

**Issue by Lykrast** [CoFH/Feedback#1350]
Disabling an individual enchantment in CoFH Core does not remove the TE Arcane Ensorcellator recipe for it. The resulting book is as expected not working.

CoFH Core: 1.12.2-4.6.1.22
Thermal Expansion: 1.12.2-5.5.2.39

**Comment by KingLemming** [comment]
Oh, well as long as the book is not working, I'm honestly not too worried. I thought for a moment that it was.

**Comment by KingLemming** [comment]
Due to current wonkiness with Enchants, JEI, and 1.12, this can't be addressed. Possibly in 1.13.
