### ISSUE TITLE
Broken Marble and Basalt dust centrifuge recipes in Centrifugal Separator

### ISSUE THREAD

**Issue by coderbot16** [CoFH/Feedback#1352]
It appears that in `PluginTechReborn`, the marble dust and basalt dust centrifuge recipes are added without an input stack size. This means that it's possible to turn a single marble dust into 7 calcite dust + 1 magnesium dust, and a single basalt into 8 flint dust + 4 dark ashes + 3 calcite dust + 1 peridot dust, much more than what one should get.

![2018-11-03_21 08 04](https://user-images.githubusercontent.com/22420959/47959919-13d71880-dfad-11e8-8e74-67828709f27a.png)
![2018-11-03_21 08 12](https://user-images.githubusercontent.com/22420959/47959920-15084580-dfad-11e8-847f-a7c80d035210.png)

**Comment by KingLemming** [comment]
So, at the time I added those recipes...that was correct. Has it changed?

**Comment by coderbot16** [comment]
I reported an issue to TechReborn regarding the Marble Dust recipe (https://github.com/TechReborn/TechReborn/issues/1629), as they broke their recipe in https://github.com/TechReborn/TechReborn/commit/eef08aa3decf46558643d33c986c97a626e0e092.

**Comment by KingLemming** [comment]
I'll make the adjustments on my end then, no problem.

**Comment by coderbot16** [comment]
Alright, thanks!
