### ISSUE TITLE
[CoFH World] Minor oregen inconsistency

### ISSUE THREAD

**Issue by lOmicronl** [CoFH/Feedback#1353]
Chanced across this because I was curious about how many blocks of ore actually can be found on average in a cluster of a given size. I knew it was not linear, but nothing more than that. So I thought I'd download WorldEdit and simply let it count through a bunch of sample generations. I modified the 00_minecraft.json file to suit my needs and activated overriding vanilla generation. Threw out everything aside from coal, iron, gold, diamond, redstone, and lapis, told it to generate just a single cluster per chunk in air blocks in distinct height bands, and set them to sizes 1 through 6 to start with. That way I could test six sizes at once.

Config file: https://pastebin.com/GrmfxQqj

Loaded into a superflat world that consisted of nothing but one layer of bedrock, with the ore floating above in the air. After letting it finish generate out to view distance 22, I selected a 40x40 chunk area with WorldEdit, and let it count the ores. Here's what it found:

    Cluster Size    Sample 1    Sample 2    Sample 3    Sample 4
        1:            1600        1603        1595        1606
        2:            3002        2992        2971        2972
        3:            4244        4222        4254        4242
        4:            3766        3848        3877        3861
        5:            5871        5828        5615        5728
        6:            6945        7230        7096        7000

As you can see, I actually repeated this test three more times, to make sure that what I was seeing wasn't a fluke. But, everytime I tried, I got the same result: numbers for cluster size 3 and cluster size 4 seem as if swapped. Size 4 should produce the larger number, but it consistently does the opposite. This includes deleting the world and generating a new one; the effect still persisted. And yes, I doublechecked that I had set the right numbers for the right ores in the config.

Since WorldEdit is limited to 1.12.0, I used the following mod versions in this instance:

* Forge 14.21.1.2443
* CoFHWorld-1.12-1.0.1.8-universal
* worldedit-forge-mc1.12-6.1.8-dist

No other mods were present.

I know this is not exactly the most serious of issues - and, who knows if you even have all that much control over the way these clusters generate. But I hope this helps anyway! :)

**Comment by KingLemming** [comment]
All we're doing is replicating the vanilla oregen function, exactly as written. So this is 100% a quirk of how they have written it.

**Comment by lOmicronl** [comment]
Well, guess I'll be making a vanilla bug report then :)

**Comment by KingLemming** [comment]
To be fair, vanilla also doesn't have anything at all generating at that size. So it's probably never come up.
