### ISSUE TITLE
[1.12.2] thermal expansion﻿ dupe glitth

### ISSUE THREAD

**Issue by bigenergy** [CoFH/Feedback#1354]
Dupe mod thermal expansion and works for people who have a bad Internet connection and so the dupe.

The key and absolutely any mechanism that collapses and falls in the form of a item begins to be duplicated with a short time loss of signal (3-6 seconds.) of the player to the server, if it is to collapse during the loss of signal, and everything is working fine.

**Comment by KingLemming** [comment]
That sounds like a more general Minecraft glitch. We use standard method calls to drop items. If that somehow causes dupes, welp.
