### ISSUE TITLE
Ducts not feeding Iron Chests correctly

### ISSUE THREAD

**Issue by xenoflot** [CoFH/Feedback#1355]
Hi folks,

Playing Enigmatica 2, v1.49. I'm outputting with Impulse ducts to diamond chests and the ducts won't fill past the half way point. That is, the diamond chest offers a 12 x 9 inventory space. The ducts will fill up to and including the 6th column of the 5th row, then won't insert any more. It's happening both furnace to chest and chest to chest.

Let me know if you think this is one for the Iron Chests dev.

MC 1.12.2
Forge 14.23.4.2751
CoFH Core 4.6.1.22
Dynamics 2.5.3.16
Expansion 5.5.2.36
Foundation 2.6.1.22
Iron Chest 7.0.51 build 836

**Comment by KingLemming** [comment]
Yup. Definitely one to bring up with them. This would only happen if the chest was somehow lying about its size.

Try Strongboxes, you'll see those work properly.
