### ISSUE TITLE
[Bug] Retriver pull item even when not on

### ISSUE THREAD

**Issue by Tupilak** [CoFH/Feedback#1357]
I have 5 retriver pulling the same item from one chest. All be set to pull one item and can only hold one item in the inventory. One of the retriver is set to only on with a redstone signal.
When I put in a stack of the item to pull the one with the redstone off still get items and I can see item returning to the chest pulling from. As if the pulled lot more then needed.

**Comment by KingLemming** [comment]
Well this was disproven quite easily. Retrievers which are off do not pull items.

Feel free to drop by our Discord tech support channel though to better explain this.
