### ISSUE TITLE
Machines with options causing server crash

### ISSUE THREAD

**Issue by skellitor301** [CoFH/Feedback#1358]
I've had an issue with both the glacial precipitator and the Igneous extruder so
far that has lead to immediate crashing of the dedicated server. This has been
consistent on the server thus far when I attempt to cycle through what either
machine is going to produce. As soon as I click the arrow the server crashes,
and when I restart it back up and check the machine, the option has changed to
the next option.
Crash report:
https://gist.github.com/skellitor301/58d1465108f8e287b51186874c49f64f#file-crash-2018-11-01_01-10-50-server-txt
If you need easy access to the mods used on the server, I have the modpack on
Curse, just search for Project Orion Modpack. The version of the pack the server
is running at the time of the crashes is 2.4

**Comment by KingLemming** [comment]
Seems to be thut essentials doing something it shouldn't be. Machine is being hijacked. Not us, sorry.
