### ISSUE TITLE
GUI interface disappeared

### ISSUE THREAD

**Issue by Dragonracer73** [CoFH/Feedback#136]
Playing on a small put together pack. Noticed that the gui for the redstone controls disappears after going into another dimension (in this case the nether). Attached is a file with several screen shots of the bug. I have labeled each screenshot SP is single player instance, and MP is multiplayer. The bug is persistant across all machines, and in both single and multi player. I use multi Mc as my launcher, but other players on the server do not and have the same issue. Multi Mc gives you the version of the mod listed on the right hand side of the page, which I have also taken screenshots of.
[screenshots.zip](https://github.com/CoFH/Feedback/files/875854/screenshots.zip)

**Comment by KingLemming** [comment]
Known. It's fixed in dev but frankly didn't think anyone would care. Upgrade your machines and this won't happen.

**Comment by cncwarlord** [comment]
Hello, I have this issue as well, using version 2.0.3.77, however its not uniform. It will show up on some machines, and not on others, and also effects upgraded machines as well.
