### ISSUE TITLE
[1.12.2] [CoFH World] Decoration Generator Only Working on Grass

### ISSUE THREAD

**Issue by 77wisher77** [CoFH/Feedback#1361]
It appears the Decoration (and surface) Generators can only place blocks on Grass (and dirt).

In this issue I have included an example of the **Distribution** -  **Decoration** working  when not using the **Decoration** - **Generator**.

I have also included several examples of the **Decoration** - **Generator** not working.

I am trying to get ender lillys to spawn on end_stone in Mystcraft dimensions. However after some experimenting i found they refused to do so, but would happily spawn on grass and dirt blocks
The following examples failed: 
(this also includes 1 try with the surface generator possibly indicating it also only works on grass/dirt)
(i turned them to enabled: false after i finished testing them, this is the config history of my tests)

>     "enderlily_plant": {
> 			"enabled": false,
>       "distribution": "decoration",
>       "generator": {
>         "type": "decoration",
>         "material": "minecraft:air",
>         "block": {
>           "name": "extrautils2:enderlilly",
>           "metadata": 7
>         },
>         "surface": "minecraft:end_stone",
>         "cluster-size": 5,
>         "see-sky": true,
>         "check-stay": false,
>         "x-variance": 4,
>         "y-variance": 2,
>         "z-variance": 4
>       },
>       "cluster-count": 1,
>       "chunk-chance": 1,
>       "biome": "all",
>       "dimension": {
>         "restriction": "blacklist",
>         "value": [
>           1
>         ]
>       }
> 		},
>     "enderlily_plant_v2": {
> 			"enabled": false,
>       "distribution": "decoration",
>       "generator": {
>         "type": "cluster",
>         "material": "minecraft:air",
>         "block": {
>           "name": "extrautils2:enderlilly"
>         },
>         "surface": "minecraft:end_stone",
>         "cluster-size": 5
>       },
>       "cluster-count": 5,
>       "chunk-chance": 1,
>       "biome": "all",
>       "dimension": {
>         "restriction": "blacklist",
>         "value": [
>           1
>         ]
>       }
> 		},
>     "enderlily_plant_v3": {
> 			"enabled": false,
>       "distribution": "decoration",
>       "generator": {
>         "type": "small-tree",
>         "surface": "minecraft:end_stone",
>         "material": "minecraft:air",
>         "min-height": 1,
>         "height-variance": 0,
>         "tree-checks": false,
>         "block": {
>           "name": "extrautils2:enderlilly",
>           "metadata": 7
>         }
>       },
>       "cluster-count": 3,
>       "chunk-chance": 1,
>       "biome": "all",
>       "dimension": {
>         "restriction": "blacklist",
>         "value": [
>           1
>         ]
>       }
> 		},
>     "enderlily_plant_v5": {
> 			"enabled": false,
>       "distribution": "decoration",
>       "generator": {
>         "type": "decoration",
>         "material": "minecraft:air",
>         "block": {
>           "name": "extrautils2:enderlilly",
>           "metadata": 0
>         },
>         "cluster-size": 3,
>         "see-sky": true,
>         "check-stay": false,
>         "x-variance": 4,
>         "y-variance": 2,
>         "z-variance": 4
>       },
>       "cluster-count": 1,
>       "chunk-chance": 1,
>       "biome": "all",
>       "dimension": {
>         "restriction": "blacklist",
>         "value": [
>           0,
>           1
>         ]
>       }
> 		},
>     "enderlily_plant_v6": {
> 			"enabled": false,
>       "distribution": "surface",
>       "generator": {
>         "type": "decoration",
>         "material": "minecraft:air",
>         "surface": "minecraft:grass",
>         "block": {
>           "name": "extrautils2:enderlilly",
>           "metadata": 0
>         },
>         "cluster-size": 3,
>         "see-sky": true,
>         "check-stay": false,
>         "x-variance": 4,
>         "y-variance": 2,
>         "z-variance": 4
>       },
>       "cluster-count": 1,
>       "chunk-chance": 1,
>       "biome": "all",
>       "dimension": {
>         "restriction": "blacklist",
>         "value": [
>           0,
>           1
>         ]
>       }
> 		},

the small-tree generator also didnt work, but that was probably an error i made

The following is a cluster generator, this worked. This shows the Decoration Distributor itself works:

>     "enderlily_plant_v4": {
> 			"enabled": true,
>       "distribution": "decoration",
>       "generator": {
>         "type": "cluster",
>         "material": "minecraft:air",
>         "block": {
>           "name": "extrautils2:enderlilly",
>           "metadata": 7
>         },
>         "cluster-size": 1
>       },
>       "cluster-count": 1,
>       "chunk-chance": 4,
>       "biome": "all",
>       "dimension": {
>         "restriction": "blacklist",
>         "value": [
>           -11325,
>           -9999,
>           -1,
>           0,
>           1,
>           2,
>           7,
>           111,
>           144
>         ]
>       }
> 		},

I have also posted in the discord asking for assistance leading up to this point, a short history of my efforts to get this working can be seen in the tech-support channel.

**Comment by KingLemming** [comment]
Answered in tech support. Old format; will be addressed with future rewrite.
