### ISSUE TITLE
2 Errors while Loading Forge [Thermal Foundation ]

### ISSUE THREAD

**Issue by zShahin** [CoFH/Feedback#1362]
Idk why but i dont get or cant load the Mod Screenshot: 
![screenshot_9](https://user-images.githubusercontent.com/44923433/48301626-ffd17080-e4f0-11e8-8302-450834874c6a.png) im looking too for the error but im not finding the fixes

**Comment by KingLemming** [comment]
You literally don't have the right mods installed. That's it.
