### ISSUE TITLE
Suggestions:ideas for the "new thermal series"

### ISSUE THREAD

**Issue by Wotzinator** [CoFH/Feedback#1363]
so ive read that the thermal series is being rewritten and changed in a lot ways(ive read it [here](http://teamcofh.com/posts/2018/11/02/the-new-thermal-series/)).so i wanted to write down ideas i have for it.

1.oil rework:ok we all know that oil is bad for the enviroment but hey were in minecraft so i wanted a rework of the oil system .my first thought was make oil availible and yes i know you can get it by mining oil sand and oil shale but that somehow doesnt feel right atleast to me (i also know that you can get the same effect by using liquified coul but its the same problem as before) so i my idea for it was to let oil spawn in nature (somewhat similar to buildcraft(most of the inspiration for the oil rework is from buildcraft and immersive petroleum)) and you need a pump(a block ill talk about later) to get it then you need to further refine it in to many different fuels or even gases that then can be used to generate power .the other thing i would love to see would be plastics. plastics would be created using oil in a new machine(i have no idea how to call it) plastic could be used for the following things:plastic bottles wich would allow you to put potions in and be stackable to an amount of 8 the downside would be that they only useable once so they break into plastic trash after using it,i imagening a longer slimmer bottle as the texture and the ability to dye etticets(i probably butchered the spelling of that word) so you can better know wich potion is wich.using plastic componets instead of metal ones would be seriusly cool because you could replace some metal parts in recipes so that u dont dont waste so much metal.

2.energy rework. i cant be the only one who is confused by the power not because i dont understand it but because the numbers are somewhat weird.for me thats because the numbers are in most casses pretty big (i mean seriusly one bucket of refiend fuel can generate 1500000 rf without upgrades)and that doesnt make much sense because most of the machines are actually using way less power wich makes powering the machines atleast for me way to easy.maybe just make the numbers smaller in general that would be cool.

3.enrgy generation rework:i know i just said something about energy above but i still want to say something about energy generation because it feels a little bit unbalanced espacially in earlygame i mean you can make a really good passive energy generation with just a tree as fuel.it just doesnt feel like youre getting a real upgrade when youre changing youre energy generation.maybe add new ways of generating energy like expanding on steampower or build gas turbines.

4.glowing pipes and fluxducts:so this may be just something small but it would look extremly cool
the idea behind this is that if a pipe has a light emitting liquid in it that the pipe carrying it would glow to,and the other thing is that i fluxducts have energy in them they will glow very dim and have a glowing texture.

5.better models:there is one thing that bothers me about the style of these mods ,everything nearly looks the same the only thing that in most casses changes is the color of the texure as an example if youre upgrading an dynamo to an steamboiler there is only a texture change it doesnt look like a boiler and thats the thing with many things in the mod  and i personaly would enjoy if there would be better models and textures for the stuff in the mod because if you remove the texture problem nearly anithing about this mod is great.

6.multibocks:i have no examples for this one it would just love to see some multiblocks.

7.Rubber trees:i know many mods are adding rubber but in this case i would want i to be so that if you find a rubber tree you have to extract the liquid and then further process it.atm i dunno what to do with i but it sounded like a good idea.i have the general idea that there are more ways to make new materials instead of consuming materials.

i know thats a lot and i still have many ideas maybe ill make another issue page later.

**Comment by KingLemming** [comment]
Please keep suggestions like these to the Discord. This is a manifesto and not a concrete specific thing.

The new framework is still entirely in development and as such there's not much point in cluttering up the board with suggestions at this point.
