### ISSUE TITLE
Soulbound enchantment still disappears even when set to permanent in the config

### ISSUE THREAD

**Issue by QuadBoy** [CoFH/Feedback#1366]
I set B:PermanentSoulboundEnchant=true in the CoFH Core config file, but it still behaves as if it was set to false. I tested it with a Diamond Sword, a Diamond Pickaxe, a pumpkin that I wore on my head, and on a Diamond helmet. I used the /kill command to kill myself, and all of the items had a 50% chance to lose the Soulbound enchantment. However the helmet never lost the enchantment if I was wearing it when I died, but if I had two helmets in my inventory both with the Soulbound enchantment when I died when I respawned one ended up in my helmet slot an the other had a chance to lose the enchantment. However the pumpkin had a chance to lose the enchantment even if I was wearing it. And the tools always had a chance to lost the enchantment.

I first noticed this while playing with a bunch of other mods, but I was able to recreate the bug with only the following three mods:
Forge 14.23.5.2768
CoFHCore-1.12.2-4.6.1.22-universal.jar
RedstoneFlux-1.12-2.1.0.6-universal.jar

I have also attached the cofh folder from the config just in case any of the files from any of the thermal mods are relevant.
[config.zip](https://github.com/CoFH/Feedback/files/2597893/config.zip)

**Comment by KingLemming** [comment]
Fixed in dev, but I was 100% unable to replicate the case where it would drop from a worn item. That just doesn't happen.

**Comment by QuadBoy** [comment]
Yeah sorry if it was unclear. I was trying to point out that it never would drop from a worn helmet, which seems to be the same thing that you encountered.

**Comment by QuadBoy** [comment]
Thanks for getting to the issue so quickly! 👍
