### ISSUE TITLE
[Thermal Foundation and Redstone Arsenal] Use Fluxbore and Flux-Infused Hammer to drop server TPS.

### ISSUE THREAD

**Issue by Heiwen34** [CoFH/Feedback#1368]
If you use the drill and hammer in the modes: 3x3x3 and 5x5 leads to a drop in the TPS server.

**Comment by KingLemming** [comment]
Come by tech support. You're the first to ever mention this, so I'm pretty sure that you have other mods or something else going on.

I definitely do not see any drop with just CoFH mods.

**Comment by Heiwen34** [comment]
Modifications used:
<img src="http://skrinshoter.ru/i/231118/HXX3Wylu.jpg" width="706" height="426"/>
