### ISSUE TITLE
Magma Crucible Not Working as Intended

### ISSUE THREAD

**Issue by MastaC729** [CoFH/Feedback#137]
Thermal Expansion Version: 5.0.4.90
Forge Version: 2254

When I try to use items in the magma crucible, there is no processing of the item. Am I missing something, or is this a bug? Let me know if you need any other info to debug this.

**Comment by Tahakk** [comment]
Depend what items you are fitting into it. Give us some screenshot of settings of your machine.

**Comment by KingLemming** [comment]
Yeah, we need to know what you're doing wrong. Provide some screenshots.

**Comment by MastaC729** [comment]
Ugh, this issue seems more complicated, because it's not happening now that I restarted the server. If it happens again, I'll provide some evidence of the issue.
