### ISSUE TITLE
EnderIO/Thermal Foundation Compat Issue

### ISSUE THREAD

**Issue by CloWnicide** [CoFH/Feedback#1371]
I keep running into this issue between the two mods and a log being generated saying that the gearStone item regristration is missing upon the game trying to load into the main menu. Log specifically says that it is not an issue with EnderIO, and after removing mods, it seems TF is the issue. Posting log below.

https://docs.google.com/document/d/1KPGSQplj6fH8RohuyYMyaUWuIH_4n5lJkKIEyyYP9ew/edit?usp=sharing

**Comment by KingLemming** [comment]
That page actually wrecks my browser just to visit. That's a terrible log. Come by #tech-support on the Discord.

I imagine there's a config issue or something on your end. You may have the gear set to disabled.
