### ISSUE TITLE
Item Duplication - Item Allocator and Black Hole Controller (@Industrial Foregoing)

### ISSUE THREAD

**Issue by AndryaDE** [CoFH/Feedback#1372]
Hello,
im playing After Humans 1.12.2 v1.8.1 modpack
Includes:
Item Allocator from Thermal Expansion 1.12.2 v5.5.239
Black Hole Controller and Black Hole Unit from Industrial Foregoing 1.12.2 v1.11.6-216

Bug: The allocator adds the items to the black hole unit (inside of the controller) >without< them removing from the allocator.

Demo video: https://youtu.be/Ie6p4ytNPIM

**Comment by KingLemming** [comment]
Cool. Let Industrial Foregoing know please. The Allocator is agnostic in its operation. There's no line of code to break specifically with one other block.

If the Allocator were broken, this would happen with *all* blocks. ;)
