### ISSUE TITLE
[1.12.2] Resonant End Stone Name

### ISSUE THREAD

**Issue by TheSnowyChickens** [CoFH/Feedback#1374]
![grafik](https://user-images.githubusercontent.com/29357962/49332152-1e82ce80-f5a8-11e8-9cc6-211c05589f45.png)

MC: 1.12.2
Forge: 2784
TE: 5.5.2.39
TF: 2.6.1.22
CoFH Core: 4.6.1.22
RF API: 2.1.0.6
CoFH World: 1.3.0.6

**Comment by KingLemming** [comment]
Please just report tiny things like this in the Discord.
