### ISSUE TITLE
Suggestion: Add a config to increase the sawmill multiplier

### ISSUE THREAD

**Issue by Tfarcenim** [CoFH/Feedback#1375]
Right now it's coded to 1.5x whatever the  vanilla crafting recipe is which leads to issues when attempting to design a progression pack.

The reason is if I set the vanilla recipe to 2 planks vs 4, then the sawmill only outputs 3 planks which is undesirable because most players (including myself) would rather use the vanilla recipe because it's faster and cheaper to setup.

Other modded log processing doesn't seem to have this "feature" and I don't want thermal machines skipped over, because they're going to be a part of the progression.

But I want to set the multiplier higher to encourage the usage of the sawmill over hand crafting similar to what thermal expansion 4 did.

**Comment by KingLemming** [comment]
You already asked for this in Discord and it's already been implemented in dev. You didn't have to post this here.
