### ISSUE TITLE
Chunk Resetting

### ISSUE THREAD

**Issue by andr9528** [CoFH/Feedback#1376]
See https://github.com/raoulvdberge/refinedstorage/issues/2126 for description, as i first believed it to be a issue caused by Refined Storage.

Under each chest a different machine is suppose to be there. i removed them for testing purposes, which stopped my chunk from resetting

![2018-12-04_17 13 16](https://user-images.githubusercontent.com/21788044/49455824-1913c700-f7e8-11e8-9a0a-8ab2d95154f9.png)

The supposed machines from left to right
- Pulverizer
- Redstone Furnace
- Induction Smelter
- Compacter
- Redstone Furnace for food
- Fluid Transposer
- Magma Crucible

Any Thermal expansion machine will trigger the reset in the chunk in question, as i placed two machines down in two different chunk, to see if both would disappear, but as it can be seen on the images, only the machine in the afflicted chunk vanished.

![2018-12-04_17 19 48](https://user-images.githubusercontent.com/21788044/49456481-78260b80-f7e9-11e8-846c-8ff9ee43de30.png)

![2018-12-04_17 26 52](https://user-images.githubusercontent.com/21788044/49456706-d94ddf00-f7e9-11e8-84b9-6f709a27101f.png)

Stoneblock Version: 1.0.31
Minecraft Version: 1.12.2
Forge Version: 14.23.5.2768
Thermal Expansion Version: 5.5.2.39 
Thermal Foundation Version: 2.6.1.22

Write to me if there is any other information you want, or anything you want me to test in the afflicted chunk

**Comment by ktole1999** [comment]
first thing you will want to do is keep machines off the chunk border. see if that stops the issue.

**Comment by andr9528** [comment]
Well right under the chests is in the center of chunk. placing machines there also causes the chunk to reset, so it doesn't matter where i place the machines relative to the border.

![2018-12-04_17 56 53](https://user-images.githubusercontent.com/21788044/49458879-0dc39a00-f7ee-11e8-97d9-a4288a6c8906.png)

**Comment by KingLemming** [comment]
Occam's Razor - tens of thousands of people use our mods. This doesn't happen to them.

You have something else causing it. I'll leave it up for now, but you'll need to provide way more than you have I'm afraid.

There's nothing IN our logic that would make a chunk do that. There are however, other mods which may see TE, try to be clever, and screw things up. I can't rule that out, but I can tell you now that if our machines were actually the cause, this would happen 100% every time to everybody, and that definitely isn't the case.

**Comment by andr9528** [comment]
Ya you are right @Tora-B,  what i meant was that any changes made to the chunk would disappear next time the world was loaded, so to say the chunk reset is the wrong words, i m sorry about that. One thing i do want to make clear is that at the moment it is only this one specific chunk that does this.

As i'm writing this, i'm opening my minecraft to go in and strip the hole chunk for all tile-entities, and then one by one re adding them. All while placing down TE machines in the chunk at the same time, to find the combination of mods/blocks that will trigger the revert. Doing this i will also see if TE machines alone in the chunk will trigger the revert, in which case i will be really confused, and looking for inputs as too what materials you need @KingLemming to find the cause.

**Comment by andr9528** [comment]
Right after connecting i can immediately tell that even without any TE machines in the chunk, the chunk reverted to before i placed down my security terminal from AE2, so TE is most likely not to blame, After removing every tile-entity in the chunk, it did not revert back after login out and back in, which usually caused the revert, so far so good...

**Comment by andr9528** [comment]
So after removing all Tile-entities from the chunk, i'm unable to get it to revert again, meaning a break and replace of everything might have fixed it. i will try to rebuild my setup, to see if it reemerges, but i doubt it and also hope it doesn't.

**Comment by covers1624** [comment]
A tile might be throwing an error whilst the chunk is saving, that error could be getting swallowed or printed to the log/console. If you can start your client, reporoduce the issue (login to world, remove stuff, save, login and verify things are 'broken'), then send us your `debug.log` file, using [gist](https://gist.github.com) preferably.

**Comment by KingLemming** [comment]
Yeah this can safely be closed out. It's nothing we're doing.
