### ISSUE TITLE
Plate Generation missing 1.7.10

### ISSUE THREAD

**Issue by MusaFuchs** [CoFH/Feedback#1377]
Plate Generation of ores is entirely non-functional in 1.7.10. 

`	"populate": {
        "coal_layer": {
			"distribution": "uniform",
			"generator": {
				"type": "plate",
				"block": "minecraft:coal_ore",
				"material": "minecraft:stone",
				"radius": 5,
				"height": 1,
				"slim": true
			},
			"cluster-count": 1,
			"chunk-chance": 1,
			"min-height": 60,
			"max-height": 65,
			"retrogen": false,
			"biome": "all",
			"dimension": {
				"restriction": "blacklist",
				"value": [
					-1,
					1
				]
			}
		}`

Results in no coal being generated.

**Comment by MusaFuchs** [comment]
I realize 1.7.10 is no longer supported, but if this issue isn't going to get fixed could it at least be noted on CurseForge so people don't waste time learning the system only to find out one of it's core features is completely broken? Thanks.

**Comment by KingLemming** [comment]
I'm not even sure plate gen "existed" in 1.7.10. I don't think it was a feature. Your complaint seems to be that we aren't backporting all new features to previous versions.

**Comment by MusaFuchs** [comment]
Apologies. There is nothing in the documentation I could find that states
what version features are in, or what version they were introduced for, and
COFH doesn't throw any sort of error when an invalid generator type is
selected.

**Comment by Tora-B** [comment]
Curseforge has poor support for documenting major changes between versions. Tonius has done some work on the [Team CoFH website](http://teamcofh.com/) with the intention of providing documentation for older versions, but it's not there yet. Documentation just isn't that much fun to write, particularly for something that's no longer relevant.
