### ISSUE TITLE
Induction Smelter fluid not inputing

### ISSUE THREAD

**Issue by JFMillerUSA** [CoFH/Feedback#1378]
minecraft 1.12.2
ThermalExpansion-1.12.2-5.5.2.39-universal

**Comment by NillerMedDild** [comment]
Was this closed due to lack of information, or did you require more information?

**Comment by NillerMedDild** [comment]
In case it's the latter:

When the Induction Smelter is supplied with the Pyro-Concentrator Augment, it is impossible to input fluids automatically and manually. It does not accept buckets, or pipes.
The fluid area does not get toggled, nor highlighted or coloured when changing the input/output configuration.

### Version
- ThermalExpansion-1.12.2-5.5.2.39-universal
- CoFHCore-1.12.2-4.6.1.22-universal
- ThermalFoundation-1.12.2-2.6.1.22-universal

Modpack version (Do not use "latest")

**Comment by JFMillerUSA** [comment]
Not sure what version of mod or modpak your playing,  but I still can't get it to work.

**Comment by NillerMedDild** [comment]
Don't mind me, I can't reproduce it with just Thermal Expansion, its dependencies and JEI.
