### ISSUE TITLE
CoFHcore error before pre-init

### ISSUE THREAD

**Issue by SrHusky** [CoFH/Feedback#1379]
Hey, i went play this modpack in yours lasted version:
 https://www.technicpack.net/modpack/play-craft-brasil.844377

All people can run the pack except me.. 
I've already tested the multimc by putting it in latest modpack version of 1.7.10(3.1.4-329) with the lasted version too.. and anything do right.

No crash report..

My computer configs:

Win 7 ultimate 64bits
4GB RAM
1TB HDD
Onboard videocard
Pentium Dual Core

Java versions:

Java 7 Update 75 (64-bit)
Java 8 Update 171 (64-bit)
Java 8 Update 181 (64-bit)

sorry for english broken, i'm brazilian and i need you! Help me please

**Comment by KingLemming** [comment]
1.7.10 is unsupported, sorry. You can come by the Discord server and ask there , but it's not a code issue.
