### ISSUE TITLE
Texture missing for invar fishing rod and full flux infused fishing rod

### ISSUE THREAD

**Issue by adudney** [CoFH/Feedback#138]
![2015-02-21_22 37 35](https://cloud.githubusercontent.com/assets/246232/6317603/9fb2c352-ba1a-11e4-942f-3f72648fa93a.png)
![2015-02-21_22 37 40](https://cloud.githubusercontent.com/assets/246232/6317604/9fffac76-ba1a-11e4-91e2-334c18450b30.png)

Newest RCs, downloaded from Curseforge. Only CoFH RCs installed, no MFR or any other mods.

**Comment by KingLemming** [comment]
Yeah, windows/Linux desync issue. Fixed in dev.
