### ISSUE TITLE
[REQUEST] Release a 1.11.2 version of COFH

### ISSUE THREAD

**Issue by spindisc** [CoFH/Feedback#138]
Being able to control ore generation in a custom mod pack is essential, at least to me. COFH is the ideal way to do this. Many mods are being released to MC 1.11.2, and I am creating a modpack for this version now,
COFH would really help me with ore generation in that pack.

**Comment by KingLemming** [comment]
It'll happen when it happens. TD 2.0, TE 5.1, and MFR will get 1.10.2 releases first, then we migrate.

Also, please don't misuse the issue tracker for this. We're aware there is another version of Minecraft out.

**Comment by bookerthegeek** [comment]
Lmao.... Are you sure you are aware it came out?

Joking aside, keep up the great work and i look forward to the cofh mods when they come out.

**Comment by SourcePowered** [comment]
@KingLemming No, please do not update, do not make so many version changes. Those of us who open the server, can not afford. All you have to do is support ONE versions ( Like a ...  Long Term Support Version? ... What ever. ). That's all. Minecraft biggest problem is that the change is too fast, after all, Mod server data can not be upgraded or interoperability. Thank you very much for all job.
