### ISSUE TITLE
Factorizer Disabled shows Item usage

### ISSUE THREAD

**Issue by dhtdesign** [CoFH/Feedback#1380]
i have disabled factorizer in the config file and it still shows uses in JEI, is there a way to hide this?

to disable all recipes from the disabled machine.

(is there a way to add Modtweaker support to remove all recipes from machines, so u can add your costum recipes and dont need to remove each item ?)

**Comment by KingLemming** [comment]
Not at this time, sorry.

Also, something like this is much better inquired about on the Discord.
