### ISSUE TITLE
Reflux column loses fluid

### ISSUE THREAD

**Issue by JimusHimus** [CoFH/Feedback#1381]
I produce naphtha with reflux column. If 150mB is left in the distiller, the machine starts working, consumes 200mB of crude oil and produces only 150mB of naphtha. Such a bug in all types of liquids.
![default](https://user-images.githubusercontent.com/39002687/50051271-0c646c80-0120-11e9-8e53-0ff1b512d182.png)
![default](https://user-images.githubusercontent.com/39002687/50051278-29993b00-0120-11e9-9e8a-3a6477477f1a.png)

**Comment by KingLemming** [comment]
Yeah it's a bonus. Validity is based on the base recipe.
