### ISSUE TITLE
Phytogenic Insolator inferium seed energy requirements should not be tier dependent

### ISSUE THREAD

**Issue by GaboonViper** [CoFH/Feedback#1382]
For the Phytogenic Insolator the MA inferium seed energy requirements are as follows:

- Tier 1: 4800 rf -> 1 inferium
- Tier 2: 9600 rf -> 2 inferium
- Tier 3: 14400 rf -> 3 inferium
- etc...

This seems perfectly logical at first glance. However, the way the Phytogenic Insolator works is that the more energy a seed requires, the more time it takes to grow, because energy intake is always the same. So the tier 2 inferium does not in fact take twice as much energy to grow, but twice as much time. In effect that means a tier 5 inferium seed is right now exactly as fast as a tier 1 inferium seed when using a phytogenic insolator, making the higher tiers useless.

I think the best way to deal with this is to give them all the same energy requirements.

**Comment by KingLemming** [comment]
No, sorry.
