### ISSUE TITLE
Broken Tinkers’ tools aren’t properly fixed by Flux Reconstruction

### ISSUE THREAD

**Issue by Gameactive** [CoFH/Feedback#1383]
When a broken Tinkers’ Construct tool is placed in an Energetic Infuser with the Flux Reconstruction augment, the tool’s durability is restored as it should be. However, its status as “Broken” is not updated to reflect that, making the tool unusable until manually repaired (e.g. with sharpening kits).
```
Minecraft version 1.12.2
Thermal Expansion version 5.5.2.39
Tinkers’ Construct version 2.11.0.106
```
I was able to replicate the issue with only Thermal Expansion, Tinkers’ Construct, and their dependencies loaded (all of which were up to date). I discovered the issue with these mods loaded: https://pastebin.com/sQdMGKTS

This isn’t too relevant, but I discovered the issue when trying to automate the EnderIO Farming Station, which only ejects Tinkers’ tools once they break.

**Comment by KingLemming** [comment]
Yeah, sorry - that's just a function of Tinker's Construct and how they write their tools.

Unsupportable.
