### ISSUE TITLE
Crash issue with Thermal Dynamics ... I think

### ISSUE THREAD

**Issue by IAmRaptor** [CoFH/Feedback#1385]
So I tried to launch an old modpack, the game crashes.
So I check if everything  is up to date, relaunch the game, it crashes again.
I'm no expert, but after trying to understand the crash report I think the problem comes from Thermal Dynamics, so I post my issue here. But then again I'm no expert.
Also here's the crash report : 

[crash-2018-12-26_19.21.20-client.txt](https://github.com/CoFH/Feedback/files/2710714/crash-2018-12-26_19.21.20-client.txt)

**Comment by KingLemming** [comment]
This can only happen if some other mod is doing something *extremely* stupid and incorrect with entities, or you simply don't have enough RAM allocated.

Either way, it's not a code issue on our end.

**Comment by covers1624** [comment]
This was actually a Forge bug from a little while ago, they completely broke entities with null worlds.
