### ISSUE TITLE
ThermalCultivation usability with AgriCraft

### ISSUE THREAD

**Issue by LemADEC** [CoFH/Feedback#1387]
As of Agricraft-2.12.0-1.12.0-a6 with ThermalCultivation-1.12.2-0.3.1.8, we can't use Watering can directly on Agricraft crops, sneaking or not.
As a workaround, players need to right click the soil or another block nearby to use the watering can.

Consider allowing to use the WateringCan directly on the crops to make players like easier, thanks!

**Comment by KingLemming** [comment]
I'm unfamiliar with the crops but they're poorly designed if they require special logic.

This is likely a hard no, but I'm willing to look into it.

**Comment by LemADEC** [comment]
In Agricraft, right clicking the crop sticks will remove the breeding sticks or collect the drops, when applicable.
Right clicking while holding ExtraUtilities Watering can will behave like an empty hand.
Sneaking and right clicking while holding ExtraUtilities Watering can will grow the crops.

So, it's just about allowing players to use the ThermalCultivation Watering can while sneaking, so they can bypass the effect of the block itself.

You can reproduce the same behavior with vanilla chest for that matter:
- right clicking opens the chest
- right clicking while sneaking actives/uses the item

Hopes it's more clear that way :)

**Comment by KingLemming** [comment]
I've made a change where this should work. The inconsistency issue shouldn't be much of a thing. Calling resolved but no promises it won't change back if it proves strange or confusing.
