### ISSUE TITLE
Flux Capacitors error with 0-size container GUIs whilst in player inventory

### ISSUE THREAD

**Issue by SanAndreasP** [CoFH/Feedback#1395]
Minecraft Forge: 1.12.2-14.23.5.2781
CoFH Core: 4.6.1.22
Thermal Expansion: 5.5.2.39

What happens:
When the flux capacitor is in a players inventory (*not* in the hotbar/offhand) and charges something else a player carries, it'll spam the client log with the following error: https://paste.dimdev.org/anivunuqod.mccrash

I suspect the same issue Psi had with their CAD: https://github.com/Vazkii/Psi/issues/427#issuecomment-450950029

If Baubles is installed and the capacitor is in a baubles slot, it still errors, but only ocassionately.

**Comment by KingLemming** [comment]
Try making this happen with only CoFH mods. I can't. There's something else happening here.

**Comment by SanAndreasP** [comment]
latest.log: https://gist.github.com/SanAndreasP/8f26f84c10bf740e2cc48277507b36b2

You need a mod that has a GUI that extends GuiContainer, but doesn't provide a container for the client (OpenBlocks manual, all their GUIs extend GuiContainer for easier coding I guess!?)
(or Industrial Foregoing, once you configure a machines sides, it'll remove the player inventory slots)

Steps to reproduce:
- Put a filled capacitor (not the creative one) inside the inventory, not the hotbar or offhand slot
- get an empty energy cell so the capacitor charges it
- open the OpenBlocks manual (item is called "World Domination with OpenBlocks")
- The client gets spammed with the above recreated error with ```java.util.concurrent.ExecutionException: java.lang.IndexOutOfBoundsException: Index: 9, Size: 0```

**Comment by KingLemming** [comment]
I think I'm understanding the interaction here but this is probably unfixable without really hacky ASM. If you have an alternate solution, let me know. As it stands though, I don't think I'm addressing this.

**Comment by SanAndreasP** [comment]
yea, well the only solution I have for you is to have the capacitor only charge items when in the hotbar/offhand/baubles slot.

**Comment by KingLemming** [comment]
Yup. Non-starter then I'm afraid. Fundamentally this sounds a lot like a Mojang bug, since those slots still exist in the absence of a GUI normally. Pulling up a new GUI without slots shouldn't screw things up.

I would also suggest that GUIs which do not provide a container shouldn't be extending GuiContainer. :P Maybe report it to them too.

**Comment by SanAndreasP** [comment]
> 
> 
> I would also suggest that GUIs which do not provide a container shouldn't be extending GuiContainer. :P Maybe report it to them too.

Can do. Thanks :)
