### ISSUE TITLE
Flux-Infused Helm Randomly Breaks

### ISSUE THREAD

**Issue by Prang97** [CoFH/Feedback#1396]
I've noticed this issue for quite a while now, my helmet would just disappear. I just observed it happen after receiving 2HP of fall damage, it played the tool breaking sound effect.

**Comment by KingLemming** [comment]
Can't replicate this at all. You probably have another mod doing some weirdness.

**Comment by Prang97** [comment]
I'll see if I can do some testing on which it is. Thanks for responding, mate!

**Comment by slimboyphat** [comment]
I am too having this issue. On a custom pack, with Redstone Arsenal  2.3.1.15
![teamviewer_2019-01-27_04-00-58](https://user-images.githubusercontent.com/47062441/51790364-5abd5e80-21e8-11e9-82cb-307553f8f120.png) are mods (sorry if this isn't the correct way to show)
@Prang97 did you have any luck testing?

**Comment by Prang97** [comment]
@KingLemming @slimboyphat
The issue is caused by Wearable Solars, even without a solar panel being attached to the helmet. Removing that mod resolved my issue.

**Comment by slimboyphat** [comment]
That solved the issue, thanks @Prang97 for the help.
