### ISSUE TITLE
[1.12.2] [Question] Igneous Extruder

### ISSUE THREAD

**Issue by NickelHub** [CoFH/Feedback#1397]
Is there a way to add recipes to the Igneous Extruder? If Chisel is installed, its Basalt appears in the machine. I look for a way to add other stones like them from Undergorund Biomes.  I requested this to Craftweaker but this was denied because @Jaredlll08 said he isn't able to remove stuff. See https://github.com/jaredlll08/ModTweaker/issues/690 .

**Comment by KingLemming** [comment]
This isn't a forum. Please use the Discord for questions.

Answer to this is no, however. And no, there aren't plans to add that functionality in 1.12.
