### ISSUE TITLE
[Bug] Strongbox in-world item is invisible

### ISSUE THREAD

**Issue by WhatThePuckPT** [CoFH/Feedback#1399]
Title says all. When I drop a Strongbox, the in-world item is completely invisible, aside from the shadow.
If logs are needed, tell me the relative path within the folders and/or what log I should be looking for - I'm playing a self-created modpack on Twitch Launcher, mod version is ThermalExpansion-1.12.2-5.5.2.39-universal.

**Comment by KingLemming** [comment]
Caused by something else you have installed.

Feel free to come by the Discord server and ask around, but this absolutely isn't a code issue.
