### ISSUE TITLE
Psi duplicating blocks

### ISSUE THREAD

**Issue by PetersonE1** [CoFH/Feedback#140]
When I break a machine with a Psi break block spell, it drops the block as normal but also drops a redstone furnace.  This occurs both in singleplayer and on a server.

Pack - FTB Beyond 1.2.1
 forge-12.18.3.2254
ThermalExpansion-1.10.2-5.0.3.86-universal
Psi-r1.0-42

**Comment by KingLemming** [comment]
Yes. **PSI** is duplicating blocks. Better let them know so that they can fix it.

Ironically enough, this is *also* a duplicate, of #93.
