### ISSUE TITLE
Flux-infused Armors Incorrect RF usage

### ISSUE THREAD

**Issue by hotarunso31** [CoFH/Feedback#1401]
I am using RedstoneArsenal-1.12.2-2.6.1.15 and other cofh series in latest version.

I found the Flux-Infused Armors consume a lot of RF even I am not taking any damage. Especially when I flight with Angel ring from EU2 in Nether, even I wasn't attacked by ANY entities, it drained the  Flux Capacitor quickly.

Is it the default behavior or a bug?

**Comment by KingLemming** [comment]
The armor only drains if something is telling g it to. This can either be damage or another mod or effect making it happen.

It is not bugged.

**Comment by hotarunso31** [comment]
I cannot see any mod is "telling" it to drain RF. It wastes too many RF so that I can only switch to the Platinum Armors .... 😭
