### ISSUE TITLE
Energized glowstone spread

### ISSUE THREAD

**Issue by raltus** [CoFH/Feedback#1402]
I wanted to do some lighting in Stoneblock 2 like I had done in the past in other packs. I put down a source and it spread only one block in each direction. I remember this spreading like water, and in the item information on the website it still says it does spread like other fluids. Unless there has been a change I can't find information on I am assuming this is a bug with it because I didn't see anything in the config about its spread distance when I checked it in a mod list I had done myself. I've also had it just hang in place with it flowing up but the source staying where it was put. I remember a delay before it will move, but the source will occasionally not update or just sit there after moving one block.

**Comment by Tora-B** [comment]
As far as I remember, it spreads just like water, except upside-down. Does it have a surface to spread out on, or is it following up into a hole? A screenshot may be helpful in illustrating the problem.

**Comment by KingLemming** [comment]
There's no bug here. Spread range was reduced a bit.

**Comment by raltus** [comment]
Ok, I can think of a way to do what I wanted to, it'll just take a bit more. Is the source still supposed to float up or was that changed as well?
