### ISSUE TITLE
[1.12.2] Thermal Foundation/Redstone Arsenal dragon drops

### ISSUE THREAD

**Issue by Column01** [CoFH/Feedback#1403]
A player on our server noticed that when killing the dragon with the Thermal Foundation Diamond Reinforced bow, and the Flux-Infused Quiver. Upon killing using a staff of power from Draconic Evolution or vanilla tools, the drops come out fine, but when using the bow and quiver, it only drops the XP and the heart from Draconic Evolution. Confirmed not working properly in SP and on a MP environment

[Mod List](https://gist.github.com/Column01/6e17277351bc3723791390e5ad459633)

**Screenshot of enchants:**
![img](https://i.imgur.com/9n2aPvY.png)
![img](https://i.imgur.com/8UsYIkJ.png)

**Versions:**
CoFHCore-1.12.2-4.6.1.22
CoFHWorld-1.12.2-1.3.0.6
RedstoneArsenal-1.12.2-2.6.1.15
ThermalFoundation-1.12.2-2.6.1.22
ThermalExpansion-1.12.2-5.5.2.39
ThermalDynamics-1.12.2-2.5.3.16
ThermalCultivation-1.12.2-0.3.1.8
Forge Version: 2796

**Comment by KingLemming** [comment]
Vanilla issue with explosions.
