### ISSUE TITLE
Signalum-Plated Itemducts, Fluiducts carry 4000 RF/tick despite config change

### ISSUE THREAD

**Issue by weedgoku** [CoFH/Feedback#1405]
In .minecraft/config/cofh/thermaldynamics/common.cfg the option I:BaseTransfer=1000 does not affect the signalum-plated fluid and item ducts. To me, this is undesirable behaviour---I tried setting the value to 100 and found that as a result the signalum-plated ducts carried more RF/tick than even resonant fluxducts.

**Comment by KingLemming** [comment]
Yes, correct. I'll put out the fully fixed version when I am able to. Please don't attempt to compile it on your own.
