### ISSUE TITLE
Underground Biome & Igneous Extruder

### ISSUE THREAD

**Issue by bookerthegeek** [CoFH/Feedback#1406]
# Heyo!
Per the discussion on Discord, here is the information for the stone in UB

### Igneous Stone
- ```<undergroundbiomes:igneous_stone:0>```  Red Granite
- ```<undergroundbiomes:igneous_stone:1>```  Black Granite
- ```<undergroundbiomes:igneous_stone:2>```  Rhyolite
- ```<undergroundbiomes:igneous_stone:3>```  Andesite
- ```<undergroundbiomes:igneous_stone:4>```  Gabbro
- ```<undergroundbiomes:igneous_stone:5>```  Basalt
- ```<undergroundbiomes:igneous_stone:6>```  Komatiite
- ```<undergroundbiomes:igneous_stone:7>```  Dacite
### Metamorphic Stone
- ```<undergroundbiomes:metamorphic_stone:0>```  Gneiss
- ```<undergroundbiomes:metamorphic_stone:1>```  Eclogite
- ```<undergroundbiomes:metamorphic_stone:2>```  Marble
- ```<undergroundbiomes:metamorphic_stone:3>```  Quartzite
- ```<undergroundbiomes:metamorphic_stone:4>```  Blue Schist
- ```<undergroundbiomes:metamorphic_stone:5>```  Green Schist
- ```<undergroundbiomes:metamorphic_stone:6>```  Soapstone
- ```<undergroundbiomes:metamorphic_stone:7>```  Migatite
### Sedimentary Stone
- ```<undergroundbiomes:sedimentary_stone:0>```  Limestone
- ```<undergroundbiomes:sedimentary_stone:1>```  Chalk
- ```<undergroundbiomes:sedimentary_stone:2>```  Shale
- ```<undergroundbiomes:sedimentary_stone:3>```  Siltstone
- ```<undergroundbiomes:sedimentary_stone:4>```  Lignite
- ```<undergroundbiomes:sedimentary_stone:5>```  Dolomite
- ```<undergroundbiomes:sedimentary_stone:6>```  Greywacke
- ```<undergroundbiomes:sedimentary_stone:7>```  Chert
## Additional Request
Would it be possible to add each section as its own augment? If not that is understandable. Also thank you for everything. :smile:

**Comment by KingLemming** [comment]
Separate augments won't be happening, sorry.

Working on a plugin to do this in a reasonable fashion - not sure how to handle metamorphic, honestly.

**Comment by KingLemming** [comment]
Calling metamorphic "igneous," gave them a base higher energy/water. It's all configurable though.
