### ISSUE TITLE
Potential issue

### ISSUE THREAD

**Issue by DemonfangArun** [CoFH/Feedback#1408]
I've been getting this upon world load: https://paste.dimdev.org/yagovotuyu.mccrash

My knowledge stops at whether the issue is with this mod or jei, so I'll let someone that knows more figure it out.

**Comment by KingLemming** [comment]
Quite possibly neither of them, I'm afraid. Another mod might be registering a null enchant via the API and breaking it. Only way to test is to start with just Thermal / JEI and add mods til it breaks.

**Comment by DemonfangArun** [comment]
Followup: https://github.com/ShetiPhian/Localizations-and-Issues/issues/201
That seems rather random to me, the mod doesn't even add any enchantment related anything.
