### ISSUE TITLE
Bug Report: Thermal Expansion Hammers and TI Fluxbores Voiding GTCE Machines

### ISSUE THREAD

**Issue by Vyraal1** [CoFH/Feedback#1409]
Thermal Foundation Hammers and Thermal Innovation Fluxbores will void any GregTech machines mined in an AoE effect. Per the video, you can mine all 9 machines with a pickaxe just fine, same goes for using Tinkers Hammers mining a 3x3 wall of machines just fine.

However when using a TF Hammer or a TI Fluxbore, only 1 machine drops, the other 8 in the AoE range were voided. 

Video: https://streamable.com/1ziz5

**Mods in Testing Instance:**
Forge: 2808
Thermal Expansion: 5.5.2.39
Thermal Foundation: 2.6.1.22
Thermal Innovation: 0.3.1.8
GregTech Community Edition: 1.0.142

**Comment by KingLemming** [comment]
As I commented in the other issue, not sure what the "proper" resolution for this is. Leaving this up for a while but my thoughts are that GT needs to sort this out.

**Comment by KingLemming** [comment]
Given that the other issue has been closed, I'll do the same here.
