### ISSUE TITLE
[Feature Request] All-access slot configuration for TE machines

### ISSUE THREAD

**Issue by codewarrior0** [CoFH/Feedback#141]
Thermal Expansion machines have three basic settings for a face's configuration: Blue, which passively waits for items to be inserted; Orange, which actively ejects items in that direction, and a "blank face" which does neither and does not connect to pipes or conduits. 

I am requesting a fourth type of face setting that will play nice with EIO's bidirectional conduits: A setting which allows pipe connection to all of the machine's input and output slots, but does not actively intake or eject items. A "Grey" setting, I'll call it. The setting wouldn't discriminate between the green/purple inputs of a Smelter or the red/yellow outputs of a Pulverizer, but that's a problem EIO's Smelters and Mills have too, and would probably be solved with improvements to item conduits, or simply by using conduit item filters.

This setting might need a config option to enable it, since its purpose isn't immediately obvious to anyone not using EnderIO.

**Comment by KingLemming** [comment]
TE machines actually used to have this back in TE2.

It's worth considering, but not really for EIO's sake alone.

**Comment by codewarrior0** [comment]
It might be relevant for AppliedEnergistics too. I observed this interplay with AE2 and EIO:

An EIO machine whose face is set to "Push" can accept input from an attached ME interface, and then the machine outputs are pushed right back into the ME interface which imports them into the ME network. Thus there is no need for a separate ME Import Bus to collect the outputs.

**Comment by codewarrior0** [comment]
Thanks for implementing this! It plays well with LogisticsPipes: the Crafting Pipe wants to push into and pull from the same face of the machine, and without this face setting, I'd have to use Satellites to make it push into a different face.
