### ISSUE TITLE
[1.10.2] [Thermal Foundation] Basalz not dropping rods when not killed by player

### ISSUE THREAD

**Issue by ShneekeyTheLost** [CoFH/Feedback#141]
Not sure if this is intended or not, but Basalz do not appear to drop their rods when they are not killed by a player. Specifically tested out with Blood Magic's Well of Suffering. Mobs were dying, but no items were being dropped.

Is this a bug, or working as intended?

**Comment by KingLemming** [comment]
This is working as intended. All of the elementals are equivalent to Blazes, which are also not supposed to drop their rods if killed by a non-player.
