### ISSUE TITLE
Two bugs in thermal dynamics

### ISSUE THREAD

**Issue by Alex7896** [CoFH/Feedback#1410]
1. Particles run crookedly displayed on the pipes: https://imgur.com/qRpjU8j
2. Broken pipe connection texture: https://imgur.com/acStnNL

**Comment by KingLemming** [comment]
Can't replicate the particle thing at all, and Long-Range Ducts only support connections in one direction so while the break is confusing, it is correct.

**Comment by Alex7896** [comment]
Then what about their complete removal? Better to remove them completely than to see buggy ones...

**Comment by Tora-B** [comment]
Complete removal of what? The particle issue doesn't seem to happen to anyone else, and the viaducts only look like that when you've attempted to connect them wrong, and they won't work anyway, so it's appropriate that they look like that.

**Comment by Alex7896** [comment]
complete removal of particle ducts
