### ISSUE TITLE
ThermalFoundation-1.12.2-2.6.1.22-universal crashing while minecraft is starting up

### ISSUE THREAD

**Issue by mojangmine** [CoFH/Feedback#1411]
so minecraft keeps crashing because of thermal foundation failing to load, what exactly is happening.

[crash-2019-01-23_17.41.44-client.txt](https://github.com/CoFH/Feedback/files/2789632/crash-2019-01-23_17.41.44-client.txt)

**Comment by KingLemming** [comment]
Dunno, but it's not a code issue. Please come by the Discord for tech support. This is something with your setup.
