### ISSUE TITLE
Morbs not functioning

### ISSUE THREAD

**Issue by Aexoyir** [CoFH/Feedback#1412]
Mod conflict?

Error shows up in log:
[12:33:09] [Server thread/WARN]: Skipping Entity with id minecraft:empty

Entity displays strike animation but takes no damage.

Entities tested, minecraft cow, sheep, villager, iron golem.

[latest.log](https://github.com/CoFH/Feedback/files/2793515/latest.log)

**Comment by KingLemming** [comment]
This is caused by another mod yes. Your log has a LOT of errors and warnings. You probably need to clean up your pack.
