### ISSUE TITLE
Tick Acceleration Crash

### ISSUE THREAD

**Issue by NillerMedDild** [CoFH/Feedback#1416]
Hello o/

Original report: https://github.com/NillerMedDild/Enigmatica2Expert/issues/713

Tick accelerating a Pulverizer with an Itemduct with Servo attached crashes the game, screenshot below.
Time in a Bottle from Random Things was used to tick accelerate.

**Logs**
https://pastebin.com/Ch1p1nQu - Crash Report

**Screenshot**

![2019-01-27_15 16 05](https://user-images.githubusercontent.com/32063145/51808261-853e0480-2246-11e9-9aa5-273f2c08c914.png)

**Comment by KingLemming** [comment]
Yup. Don't do that. Generalized tick acceleration is outside the scope of normal Minecraft operation and is unsafe.

**Comment by NillerMedDild** [comment]
Fair enough.
