### ISSUE TITLE
Induction Smelter recipes being added for Thermal Foundation items that are disabled.

### ISSUE THREAD

**Issue by xt9** [CoFH/Feedback#1417]
### Reproductions steps
1. Grab latest Thermal Foundation / Thermal Expansion versions.
2. Disable some tools in the thermal foundation config. For example Iron excavator
3. ???
4. Sand and air equals iron https://imgur.com/a/cCvYesx

This was produced on a clean install with only the Thermal Suite and JEI.

ThermalExpansion-1.12.2-5.5.2.39-universal
ThermalFoundation-1.12.2-2.6.1.22-universal
CoFHWorld-1.12.2-1.3.0.6-universal
CoFHCore-1.12.2-4.6.1.22-universal

**Comment by KingLemming** [comment]
It's a quirk of how JEI has to be handled. Duplicate issue.
