### ISSUE TITLE
Fluxduct remains RF even the power supply gone

### ISSUE THREAD

**Issue by hotarunso31** [CoFH/Feedback#1418]
Forge: 1.12.2 - 14.23.5.2768
Thermal Dynamics: 2.5.3.16
Modpack: No

I found TE machines can still receive RF from the fluxduct even all the dynamos gone (No fuel and RF left) for a long time. For my Magma Crucible can still use 500RF/t without draw internal buffer.

Is it a bug?

**Comment by KingLemming** [comment]
No. Fluxducts have capacitance.

**Comment by hotarunso31** [comment]
Sorry about that .....
