### ISSUE TITLE
[CoFH] Oregen Chance Question

### ISSUE THREAD

**Issue by Senophoe** [CoFH/Feedback#142]
I'm using the latest version for 1.10.2. On the new syntax for CoFH, is there something like the old _chunkChance_? I've been trying the code below to make diamonds more rare, but it doesn't seem to work.

    "diamond": {
       "distribution": "uniform",
       "generator": {
         "block": "iron_ore",
         "material": "stone",
         "cluster-size": 1
       },
       "chunkChance": 10,
       "cluster-count": 1,
       "min-height": 0,
       "max-height": 64,
       "retrogen": false,
       "biome": "all",
       "dimension": {
         "restriction": "blacklist",
         "value": [
           -1,
           1
         ]
       }
     },

Since it's only 1 ore, I've managed to use a workaround by setting weights between Diamond (10%), and Stone (90%). But it wouldn't work like the _chunkChance_ if there were bigger clusters. Also, I'd like to do it the correct way.

**Comment by KingLemming** [comment]
This is not a forum. It's an issue tracker. The only issue is that you're treating this as a forum.

It's an easy answer, so I'll provide one. But in the future, please don't clog up the tracker with stuff like this. It only makes me want to shut it down.

"chunk-chance" is what you use now - everything that used to be camelCased is now hyphen-cased.

Please use the IRC or Twitch channel for questions.

**Comment by Senophoe** [comment]
@KingLemming I'm sorry for my mistake. I saw people using the issue tracker as a questions answering feature, and thought it was common between mods. I'm new to this. I'll surely not do this again.

Also, thank you for answering the question still.

Sincerely,
Seno

**Comment by KingLemming** [comment]
No worries. It's sort of a slow time on the tracker, so not really a big deal, it's just usually better to ask on another venue. You typically get better answers there anyways. :)
