### ISSUE TITLE
[Feauture Request] Connecting cover textures with blocks

### ISSUE THREAD

**Issue by kimfy** [CoFH/Feedback#142]
I know cover textures connect like ![this](http://i.imgur.com/56AdZ4H.png) but when you then place the block you used to create the covers, the textures don't connect ![image](http://i.imgur.com/2IHCMr6.png). If it's possible then that would be awesome to see.

**Comment by KingLemming** [comment]
Not very feasible I'm afraid. I'll double check with @rwtema but I think this can't really be done.

**Comment by kimfy** [comment]
That's alright, thank you anyways though. Loving Thermal Dynamics so far!

**Comment by miuirussia** [comment]
How you covered pipes? With ForgeMultipart it not working

**Comment by KingLemming** [comment]
We have a cover recipe - Structural duct + any block (almost)

**Comment by rwtema** [comment]
It is possible if the blocks implement the use of the CofhLib interface IBlockAppearance. Extra Utilities will be doing so in the next version and I've spoken to the chisel guys about it.

http://i.imgur.com/lyKOmtc.png

**Comment by kimfy** [comment]
Great news Tema, can't wait!

**Comment by KingLemming** [comment]
Closing this down; it's the best we'll be able to do. :) Pretty good though IMO.
