### ISSUE TITLE
1.12.2 The problem of rendering mechanisms in Compact Machines

### ISSUE THREAD

**Issue by NiceBergovich** [CoFH/Feedback#1421]
![2019-01-31_12 42 16](https://user-images.githubusercontent.com/41009034/52039607-ca1faf00-2556-11e9-8f05-1f5f6bfdbc2e.png)
![2019-01-31_12 41 42](https://user-images.githubusercontent.com/41009034/52039610-ce4bcc80-2556-11e9-9e21-4a8ee079891f.png)

**Comment by KingLemming** [comment]
Sorry, I don't know what they do in their code but clearly they are not doing it right.
