### ISSUE TITLE
Update check for CoFH Core failed.

### ISSUE THREAD

**Issue by MCRakaan** [CoFH/Feedback#1422]
CoFH 1.7.10 3.1.3-327 core and all related modules

YES! I am digging this up!
Supported or not, how hard is it to just remove the updater from the start and upload it?!
There is no need for any server to have these kind of errors!

**Comment by Tora-B** [comment]
Version 1.7.10 is no longer supported, which means there will be no further updates. As disabling, removing, or fixing the updater would require setting up a build environment, digging through old code to become familiar with it again, creating a build, testing it, and uploading it, all of which take a non-trivial amount of time, for which there are better things to spend it on, this is unlikely to occur.
