### ISSUE TITLE
Disable Mobs spawn without removing them

### ISSUE THREAD

**Issue by Insane-96** [CoFH/Feedback#1423]
In the config for each mob (Blizz, Blitz and Basalz) there a Property called "Enabled"
The comment says (_# If TRUE, Blizzes will spawn naturally_), sadly setting this to false will completely remove the mobs instead of just stopping the natural spawn.

**Comment by KingLemming** [comment]
I'll think about this but it used to work that way and then people yelled because they wanted them fully disabled.

I apparently can't win either way.

**Comment by Insane-96** [comment]
Add 2 Properties

```
# If FALSE the mob will be completely disabled
B:Enabled=true

# If FALSE the mob will no longer spawn naturally
B:"Spawn Naturally"=true

```
