### ISSUE TITLE
Minor render issue with energy cells

### ISSUE THREAD

**Issue by 016Nojr** [CoFH/Feedback#1427]
When energy cells (In this case a resonant) is enchanted with holding (Tested with Holding IV(4)), the power stored inside renders as default resonant size (50M or 1/3) of the bar on the outside when entering the world, either logging in or coming from another dim. Rotating or break/replace energy cell fixes it.

Versions:
Forge: 5.2808
CoFHCore: 4.6.2.25
Thermal Foundation: 2.6.2.26
Thermal Expansion: 5.5.3.41

**Comment by KingLemming** [comment]
Known. Not going to touch it in 1.12 though.
