### ISSUE TITLE
servo on thermal dynamics itemduct set to nearest first problem with YABBA antibarrel

### ISSUE THREAD

**Issue by c0mical** [CoFH/Feedback#1428]
Hi

I'm playing PO3 (.35)

ThermalDynamics-1.12.2-2.5.3.16-universal
YABBA-1.1.2.34

https://i.imgur.com/NJrFkSw.png

I created a setup (repeated a few times) of a crate with a reinforced servo set to nearest first with two destination inventories

when both destination inventories are crates then the setup works as expected 

however when I put a YABBA Antibarrel as the first inventory (nearest) then the compatible items do not always go there

If I put the items in the crate with the servo in slowly one by one (eg they are sent a few seconds apart) then everything goes to the right place, but if they all go through normally then the first compatible item goes into the antibarrel and the others don't

It seems that it takes a second or two to identify that the item can go into the antibarrel after one has already been deposited into it

I also replicated the issue with ExU transfer pipes (max speed upgrades), and that behaved as expected with all the items at once although I don't know if it 'moves' items using the same methods

**Comment by KingLemming** [comment]
Working as intended. You need a filter and then mark it for "Enable Oversending"
