### ISSUE TITLE
[ Question / Request ] Dynamo

### ISSUE THREAD

**Issue by HurtsAsHell** [CoFH/Feedback#1429]
is there a way to add a crafting to the Dynamo Enervation? I did not find anything on the web

**Comment by KingLemming** [comment]
Sorry, but I don't understand what you mean. The dynamo is craftable. Please come by the Discord.

**Comment by HurtsAsHell** [comment]
To create rf i Need the redstone for example, i wanted to add a new recipe to generate rf, i can?
