### ISSUE TITLE
Additional Phytogenic Insolator recipes.

### ISSUE THREAD

**Issue by PaperTriangle** [CoFH/Feedback#143]
Are there any IMC Messages to add recipes to the Phytogenic Insolator, as there are for other machines? And if there isn't, do you plan to add them? I had a look around for some documentation / information on them, but I couldn't find anything.

**Comment by KingLemming** [comment]
There aren't just yet, but I'll add them. :)

Have anything specific in mind? If it's a set of crops I've overlooked with the auto-reg, just let me know and I'll do that too.

**Comment by PaperTriangle** [comment]
Awesome, glad to hear! :D

For the most part I wanted to add compatibility for some crops from a mod I maintain for my server, so it's probably not feasible to add entries for them into your mod. :s 
Though, one crop I found a bit odd to be missing an entry was the Vanilla Cocoa Beans.

**Comment by KingLemming** [comment]
If you want an easy way to add them automagically, register the seed as "seedX" and the crop as "cropX" and the machine handles it.

I'm on the fence with the cocoa beans, since they normally require trees, but I might be able to make an exception.

**Comment by PaperTriangle** [comment]
Oh, it automatically does it by Ore Dictionary? That's pretty awesome! I shall just do that then. Thanks for the tip. :)

Yeah, I see where you're coming from and agree! However, on servers like mine with Growthcraft, it must automagically register Hops and Grapes, and they normally require unique cultivation setups of rope and such. So it feels a tad odd that Cocoa Beans wouldn't work with the Phytogenic Insolator in that instance.

So, maybe a normally disabled configuration option for Cocoa? Or maybe an option to disable Hops and Grapes if Growthcraft is installed? (That feels like it would be harder to do though, and Minetweaker will likely be able to accomplish the same thing for OCD server maintainers like myself after a while.)

**Comment by KingLemming** [comment]
Cocoa can be a config option but unfortunately hops and grapes can't be just yet - it picks those up due to the OreDict registration.

I'll look into a whitelist/blacklist but it will take a while
