### ISSUE TITLE
[Enhancement] Make IC2 steam compatible with steam dynamo

### ISSUE THREAD

**Issue by DatGurney** [CoFH/Feedback#143]
due to the lack of railcraft boilers, steam production from 3rd party mods is pretty limited. only found IC2 in beyond which seems to register its own steam separately from normal one. just seeing if its possible for you to make it able to use IC2 steam

**Comment by KingLemming** [comment]
No, sorry. If they're adding it under a different name, then they explicitly do not want crossmod capability and will not go against their wishes.
