### ISSUE TITLE
Dupe bug 

### ISSUE THREAD

**Issue by EthernalVoid** [CoFH/Feedback#1433]
Version ThermalExpansion-1.12.2-5.5.3.41-universal

>the jist of it is that you can pulverise conduits to gain the exact amount of materials invested
>>with a sieve augment that becomes infinite bonus materials
thank you in advance :smile:

**Comment by EthernalVoid** [comment]
namely leadstone fluxducts and * hardened fluxducts with the sieve upgrade
and  pulverising fluiducts (opaque)

**Comment by KingLemming** [comment]
By the time anyone can do this, it's incredibly inefficient to do so, energy-wise. Feel free to crafttweak the recipe out.
