### ISSUE TITLE
CoFH Core Config broken

### ISSUE THREAD

**Issue by 016Nojr** [CoFH/Feedback#1434]
Tried disabling all CoFH Core enchants setting `# If TRUE, CoFH Enchantments will be disabled and NOT REGISTERED. Only do this if you fully understand the consequences. World backup is recommended. [default: false]
    B:DisableAllEnchantments=false` to `true`.

Restarted the game, and even though it says it wont register, enchanted books appear in JEI.

Versions (1.12.2)
Forge: 14.23.5.2815
CoFHCore: 4.6.2.25
CoFHWorld: 1.3.0.6

**Comment by KingLemming** [comment]
This sounds like client and server configs aren't matching. I'm unable to replicate this.

**Comment by 016Nojr** [comment]
I am loading a singleplayer world... so configs mismatching shouldnt be an issue

**Comment by KingLemming** [comment]
I honestly dunno what to tell you. I can't make this happen locally. I toggle the option, try and enter a world, I get a bunch of warnings.

Seems to be working to me.

In any case, all of this is moving to Ensorcellment so even if there is some strange corner case, it's not something I'll be addressing at this point.
