### ISSUE TITLE
Under some conditions items disappear when taken from a cache

### ISSUE THREAD

**Issue by quaixor** [CoFH/Feedback#1435]
When inventory is full and you take a stack of ender pearls (crouch + left click) out of a cache, they disappear.

Also happens with other items that have a stack size smaller than 64, such as a cache of strongboxes.

ThermalExpansion-1.12.2-5.5.3.41-universal.jar

**Comment by KingLemming** [comment]
I'm unable to replicate this but think I have a fix in place anyways. A video would be helpful though.

**Comment by Fatmice** [comment]
https://streamable.com/e2z1q

**Comment by KingLemming** [comment]
Can't make it happen in dev, so guess the fix indeed works. :)
