### ISSUE TITLE
Fluid Dupe

### ISSUE THREAD

**Issue by Mr-Krab** [CoFH/Feedback#1437]
**I am currently running**

- SpongeForge: 1.12.2-2768-7.1.6-RC3587
- Forge version: 14.23.5.2770
- Java version: Oracle 1.8.0_191
- Operating System: Debian 9.6

- Plugins (25): Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge,  FastAsyncWorldEdit, BeanCore, CatClearLag, CommandSync, EconomyLite, GriefPrevention, GuiShopManager, Holograms, HuskyCrates, HuskyUI, LuckPerms, Nucleus, ProjectCore, SkyClaims, StackBan, UltimateChat, UniversalMarket, VirtualTool, Wasted, WorldEdit, spark

- Mods (53): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, Applied Energistics 2, Better Questing, BiblioCraft, Binnie Core, Binnie's Botany, Binnie's Design, Binnie's Extra Bees, Binnie's Extra Trees, Binnie's Genetics, CoFH Core, CoFH World, CodeChicken Lib, Console Filter, Construct's Armory, CraftTweaker JEI Support, CraftTweaker2, CreativeCore, CreativeCoreDummy, CustomNPCs, Ex Nihilo Creatio, Fishing Net Mod, Forestry, HoloInventory, Iron Chest, ItemPhysic, Just Enough Items, LagGoggles, MTLib, Mantle, McJtyLib, Mekanism, Mod Tweaker, Quick Leaf Decay, Redstone Arsenal, Redstone Flux, Shadowfacts' Forgelin, SpongeForge, Standard Expansion, Thermal Dynamics, Thermal Expansion, Thermal Foundation, Thermal Innovation, Tinkers' Construct, Tiquality, Tree Chopper, UniDict, WanionLib

I previously did an issue on Sponge https://github.com/SpongePowered/SpongeForge/issues/2535.

Without your mod(Thermal Foundation), the problem does not appear. 
The essence of the bug. If a player is in a foreign region and is forbidden to interact with the blocks, he can fill his bucket with any liquid in the region. At the same time, the fluid block itself will not go anywhere.

**Comment by KingLemming** [comment]
Nope. We don't use a custom Bucket Handler in Thermal Foundation or affect that logic in any way.

Also, Sponge isn't supported, generally for reasons like this. Too many little quirky things which then get blamed on a random mod.

**Comment by phit** [comment]
> Also, Sponge isn't supported, generally for reasons like this. Too many little quirky things which then get blamed on a random mod.

Just to be clear, we are definitely not blaming issues on a random mod! Usually issues like these are on our end, if they aren't, we make a clear issue on the mods tracker with an explanation. So feel free to send people back to us if they nag you with Sponge issues (like this ticket) and we will investigate it.
