### ISSUE TITLE
No Fluid Transposer recipes not showing up in JEI

### ISSUE THREAD

**Issue by tfox83** [CoFH/Feedback#1438]
In FTB Ultimate Reloaded 1.0.1 no Fluid Transposer recipes show up in JEI, ie the filled ducts and such.

The issue was reported to me here, and I can confirm its an issue with this pack 
https://github.com/FTBTeam/FTB-Ultimate-Reloaded/issues/66

I have not edited any recipes for the fluid transposer or any items that go into the transposer.
Any help looking into this would be helpful, I cannot see anything off hand that would break them with scripting.

**Comment by tfox83** [comment]
Running ThermalExpansion-1.12.2-5.5.3.41-universal

**Comment by KingLemming** [comment]
I don't see this running just our stuff. Maybe you have a mod that removes them?

**Comment by tfox83** [comment]
I have no idea, I just went through all my scripts again and I am not touching the Fluid Transposer.    It may be mod tweaker doing something weird or another mod causing this.  I will try and do some more research.  Thanks for checking your mod.
