### ISSUE TITLE
[1.12.2] unable to remove some TFoundation mod integration recipes with CT

### ISSUE THREAD

**Issue by Yoghurt4C** [CoFH/Feedback#1439]
![image](https://user-images.githubusercontent.com/11313954/52978787-d1aed700-33e3-11e9-888d-654239e4abee.png)
![image](https://user-images.githubusercontent.com/11313954/52978792-d4a9c780-33e3-11e9-86be-85d6fd428b04.png)

**Comment by KingLemming** [comment]
Dunno which mod is adding that tbh. If it's our plugin, then you can disable the plugin. TCon may add that on their end.

I make no guarantees for anything working with Crafttweaker though, sorry.

**Comment by Yoghurt4C** [comment]
this isn't really an issue with ct, it's just that this particular recipe is registering too late, and seems to be coming from thermalfoundation; disabling the whole module turns off a bit too many features for that solution to not be a headache in itself

**Comment by KingLemming** [comment]
Well it sort of is an issue with CT if there is such a thing as "too late"

Thing is, all of our plugins fire at the same time - postInit. And I know that is within the window.

Maybe your CT syntax is wrong?
