### ISSUE TITLE
Thermal Dynamics for 1.10.2 ?

### ISSUE THREAD

**Issue by ToserBan** [CoFH/Feedback#144]
Hi,
I just stepped into the thermal world, wow, really nice mods. My question is, if thermal dynamics gets released for minecraft 1.10.2 some day ? Right now, it seems, only thermal expansion and thermal foundation is ready for 1.10.2, so the nice conduits are missing. I know i could play with 1.7.10, but then some other features would be missing.

**Comment by KingLemming** [comment]
Please don't misuse the issue tracker for this stuff. We're working on Dynamics. It's coming.

We have lives and jobs and other things to do. It'll be out when it's out.
