### ISSUE TITLE
Cells is bugged (GUI)

### ISSUE THREAD

**Issue by Andre-Maartens** [CoFH/Feedback#144]
When I updated my cofh mods this happened:
It says 0 but it is a creative cell?
![1](https://cloud.githubusercontent.com/assets/9878596/6318999/6cf305ee-bab5-11e4-8290-ddf3d5677a92.png)
the charge on the tooltip is also bugged as 0/100000 rf is 0/100kRF and not 0/1.21 gRF (might be wrong on this though)
![2](https://cloud.githubusercontent.com/assets/9878596/6319000/6cfecce4-bab5-11e4-8df9-16f6aa306aeb.png)
Waila states also 0/100000 rf
![3](https://cloud.githubusercontent.com/assets/9878596/6319001/6d07761e-bab5-11e4-99a4-7444650b5890.png)
This is a sub-node of #140

**Comment by KingLemming** [comment]
Okay so first of all, the 1.21 GRF is a joke. It's a reference from Back to the Future. The charge is obviously Infinite. ;)

That will be made a bit more clear though. The charge on the Creative Cell doesn't matter, just use it and it will work fine.
