### ISSUE TITLE
[CoFH World] TreeGrowthChance config setting does not appear to effect tree growth rate

### ISSUE THREAD

**Issue by CelestialPhoenix** [CoFH/Feedback#1443]
Tried setting this to 20%, then 10% (planting a row of saplings each time), and did not notice a significant observable difference to the normal growth rate.
(Then checked this again at 100% and produced a similar result).

I initially assumed it was mod interference, so I've ran this again in a clean instance;
(CofhWorld, CofhCore, RedstoneFlux, and JEI in the mods folder).

`    # This adjusts the % chance that a tree will grow as normal when it is meant to. Reducing this value will mean that trees take longer to grow, on average. [range: 1 ~ 100, default: 100]
    I:TreeGrowthChance=1`

Planted a 15x15 grove of Oak saplings in creative mode. 3 had grown by the time I'd finished, and after 10 minutes 62 had grown.

CofhWorld 1.3.0.6 universal 
Forge 14.23.5.2779

**Comment by KingLemming** [comment]
It does actually work but doesn't work as the comment describes. Will address it at some point.
