### ISSUE TITLE
Infinite Storage Satchel Glitch

### ISSUE THREAD

**Issue by KnightOfWorth** [CoFH/Feedback#1444]
So I was messing with satchel storage in my game and I noticed that you could store satchels inside of shulker boxes. This appears to be a problem because those satchels can also store shulker boxes allowing for infinite storage. Details below.

![1](https://user-images.githubusercontent.com/47932162/53293994-60d13b80-37a4-11e9-8502-b945c238a8e0.PNG)

![2](https://user-images.githubusercontent.com/47932162/53294133-78a9bf00-37a6-11e9-8317-a5ebc281e869.PNG)

**Comment by KingLemming** [comment]
This is known. There are other ways of doing that too, given a modded ecosystem.

Do this at your own risk. It's not infinite; you'll eventually break your world with NBT that is too large.
