### ISSUE TITLE
[Bug] Satchel and all of its contents are deleted

### ISSUE THREAD

**Issue by quaixor** [CoFH/Feedback#1445]
Under certain conditions a satchel and all of its contents are deleted.

You need two satchels to trigger this bug. It helps to have two different kinds (say, basic and hardened) to clearly see what is happening. I will call them Satchel A and Satchel B.

Repro steps:

1. Put Satchel A into slot 1 of your belt. 
2. Put Satchel B into slot 2 of your belt. 
3. Holding Satchel A in your hand, crouch right-click. This will open the filter GUI of the satchel.
4. With the GUI window open, mouse over Satchel B and press the keybind for the first belt slot. (The keybind must be a keyboard key, not a mouse key.) Normally this would swap the two items. However, since we have a GUI of one of the items open, this fails.

Both satchels will now look like Satchel A. Satchel B has been deleted and replaced with a ghost of Satchel A. If you open your inventory and try to pick up the satchel in slot 2, it will disappear.

Bug happens with satchels, void satchels, or a combination of the two. Swapping with a non-satchel item doesn't trigger the bug.

It seems that Satchel B tries to take Satchel A's slot, fails, and gets deleted.

Modlist:

codechickenlib@3.2.2.353
cofhcore@4.6.2.25
cofhworld@1.3.0.6
redstoneflux@2.1.0.6
thermalexpansion@5.5.3.41
thermalfoundation@2.6.2.26
forge@14.23.5.2768

**Comment by KingLemming** [comment]
I've already added custom slots to prevent pickup of the Satchel which is open, but frankly this sounds like a lower level issue and just isn't something I can address.

So, I guess don't do that.
