### ISSUE TITLE
EnableGenericDeathMessage ignores vanilla GameRule

### ISSUE THREAD

**Issue by xElementzx** [CoFH/Feedback#1446]
**Mod:** CoFHCore
**Version:** 1.12.2-4.6.2.25
**ModList:**
**Forge** 2807
**CoFH Core** 4.6.2.25
**RedstoneFlux** 2.1.0.6

**Description:**
Config option (common.cfg)
```
    # If TRUE, death messages are displayed for any named entity. [default: true]
    B:EnableGenericDeathMessage=true
```
ignores the vanilla GameRule ``showDeathMessages``, This is only present when CoFH Core is installed and the config option is set to true. 

For added support with servers using SpongeForge, a check should be added to the EventHandler to check the GameRule for the world the entity died in, as Sponge adds per-world GameRule support to the environment.

**Comment by KingLemming** [comment]
Eh. Okay fine.
