### ISSUE TITLE
Dense itemducts not working as intended

### ISSUE THREAD

**Issue by EthernalVoid** [CoFH/Feedback#1447]
V: ThermalDynamics-1.12.2-2.5.4.18-universal

Dense clear itemduct does not increase path length, it goes to the inventory nearest despite it being a dense itemduct (while other itemducts are opaque) and there being plenty of room on the other side of the network
![2019-02-25_21 01 50](https://user-images.githubusercontent.com/45131452/53365089-9b6fdb00-3940-11e9-801d-379299ac1567.png)

**Comment by EthernalVoid** [comment]
![2019-02-25_21 03 37](https://user-images.githubusercontent.com/45131452/53365209-f6093700-3940-11e9-91ae-311275e14e05.png)
![2019-02-25_21 03 52](https://user-images.githubusercontent.com/45131452/53365210-f6093700-3940-11e9-9e59-319ae35821ab.png)
Caches provide plenty of space

**Comment by EthernalVoid** [comment]
Servo is set to random , works the same when set to round robin, works as intended when set to nearest inventory first

**Comment by EthernalVoid** [comment]
Meaning dense / vacuum itemducts are only useful when setting servos to nearest / furthest first and are completely useless when used in conjunction with random/round robin

**Comment by KingLemming** [comment]
Yes. So they're working as intended. If you're doing random or RR, why in the world would you think path length matters?
