### ISSUE TITLE
Tier 6 Inferium Seeds from Mystical Ag do not work in the Phytogenic Insolator

### ISSUE THREAD

**Issue by seitzcasey** [CoFH/Feedback#1448]
Title.

**Comment by Serifina** [comment]
That's because they're front Mystical Aggraditions, not Mystical Agriculture (the former does not have a compatability plug-in). You can easily add an appropriate recipe CraftTweaker/ModTweaker.

**Comment by KingLemming** [comment]
Yeah, Aggraditions is just a little bit on the OP side and it's a bit limited to warrant a full plugin.
