### ISSUE TITLE
[TE] Problem with private tesseracts

### ISSUE THREAD

**Issue by Mrdlor** [CoFH/Feedback#145]
Greetings dear CoFH team !

First of all thank you very much for the hard work on the new updates and the release of Thermal dynamics :)

Sadly i got a issue going on right now. Every time i upgrade a tesseract with the Signalum lock upgrade so i can use a private frequency and place the tesseract down my game crashes with the following error: http://pastebin.com/P1ASmbKk

After a restart of the game i can access the tesseract gui just fine but when i set a private frequency it throws this error in the console: http://pastebin.com/V4ihTABt

The tesseract seems to work fine after the first initial crash & with the console error but i would hope there is a solution to avoid the crash & console spam all together but im not sure what the problem is :(

All the new release builds are in use:

RedstoneArsenal-[1.7.10]1.1.0RC2-43.jar
ThermalDynamics-[1.7.10]1.0.0RC1-69.jar
ThermalFoundation-[1.7.10]1.0.0RC2-53.jar 
MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar
ThermalExpansion-[1.7.10]4.0.0RC1-119.jar
CoFHLib-[1.7.10]1.0.0B9-112.jar
CoFHCore-[1.7.10]3.0.0RC1-181.jar 

In case it's important we are playing on a server, but only the client crashes not the entire server.

**Comment by KingLemming** [comment]
What are your Forge versions on Server and Client?

Your crashlog is very interesting since is suggests you are running an altered version of Minecraft. And I don't mean modded.

**Comment by Mrdlor** [comment]
Hey Lemming

We are using forge-1.7.10-10.13.2.1291 from http://files.minecraftforge.net/

isn't that the go to version for modded right now? :/

**Comment by KingLemming** [comment]
It sure is. Just that your crashlog doesn't match up with what the file actually *is*. And that's very strange.

**Comment by skyboy** [comment]
Should be fixed in dev at least. Mismatches aside.
