### ISSUE TITLE
Ore dictionary in all machines

### ISSUE THREAD

**Issue by Skillotic0703** [CoFH/Feedback#145]
For example you can't use the compactor in storage mode for all ingots/Blocks.

**Comment by KingLemming** [comment]
This must be an April Fool's issue or something, because I don't know what you're talking about. The compactor is compatible with oredict.

**Comment by Skillotic0703** [comment]
I mean that it doesn't support every material. For example it doesn't support chrome. I know that the pulverizer automatically finds the dusts that correspond to gems or ingots. So I thought that you could add this functionnality to the compactor.

**Comment by KingLemming** [comment]
Ah. Fair enough then. That's already being added for 5.1.
