### ISSUE TITLE
[Thermal Dynamics] Servo's liquid filter doesn't work properly for multi-tank machines.

### ISSUE THREAD

**Issue by Archengius** [CoFH/Feedback#1450]
Expected behavior:
Servo will iterate through each tank in IFluidHandler.getTankProperties() and attempt to extract tank liquid if it's content matches one of it's liquid filters via IFluidHandler.drain(FluidStack, boolean).

Observed behavior:
Servo does dumb extraction of first fluid stack provided via IFluidHandler.drain(int, boolean) and checks extracted liquid to match it's fluid filters, and doesn't perform extraction if it doesn't.

**Comment by KingLemming** [comment]
Yeah, this is kind of a fundamental issue w/ IFluidHandler. It's a massive performance hit to try and do it "properly."

It sucks, but that's just one of the tradeoffs that has to be made for server efficiency.

**Comment by Archengius** [comment]
Not really, iterating few tanks doesn't eat that much performance. Even
taking the fact that tank properties return a copy fluid stack, you will
get a copy as a result of drain(...) call. And most probably such code will
allocate object on a stack after JIT's inclining and escape analysis, so
it's not really a performance-critical.

**Comment by Archengius** [comment]
What's the point of this filter for fluids if it doesn't work properly for the case it is intended to be used in?

**Comment by KingLemming** [comment]
You're welcome to submit a PR.
