### ISSUE TITLE
[Thermal Expansion] Issue with More Planets?

### ISSUE THREAD

**Issue by ErisyaleLancaster** [CoFH/Feedback#1451]
Hello,
I'm playing on a Server that has Thermal Expansion (and all it's required Mods, obviously.) and GalatiCraft and More Planets installed.

I've run into an issue where the Redstone Furnace will randomly start to convert Wood into the 'Infected Charcoal' that More Planets adds instead of regular Charcoal.
This isn't some custom setting by the Server Admin or my error as the same Wood will be turned into normal Charcoal by any other type of Furnace.

I'm not sure if the issue lies within Thermal Expansion or More Planets so i decided to report this to both sides.

Or could it just be the Server itself screwing up? :/

**Comment by KingLemming** [comment]
This sounds to me like they are modifying the original charcoal itemstack which is in the Furnace recipe list. That would be a huge no-no.
