### ISSUE TITLE
Compactor keeps Thermal item as its output despite removing it from OreDict

### ISSUE THREAD

**Issue by MaxNeedsSnacks** [CoFH/Feedback#1453]
**About my instance**
_Forge - 14.23.5.2815_
_CoFH Core - 4.6.2.25_
_Thermal Foundation_ - 2.6.2.26
_Thermal Expansion_ - 5.5.3.41
_Modlist - https://gist.github.com/MaxNeedsSnacks/71e63fb6890f2beab905c93af7ec6f52_

Hi there! I'm currently running into a bit of an issue with using CraftTweaker to unify my metals and metal parts because I can't seem to get thermal to swap out say its Iron Ingot -> Iron Plate Compactor recipe.

Now I'm not sure whether this is an error on my side or a bug in Thermal but I remember that Thermal was supposed to keep the first item that's oredicted under the name "plate<Material>" as its output from playing around with ContentTweaker in the past, so I figured *removing* any other oredict entries should work out just fine.

As you could expect, it didn't. Instead, the Compactor just outputs the default thermal plate which did not have any uses anymore. I also tried fixing this with ModTweaker by forcing it to remove and re-add the plate recipe after unification, but that didn't work either (and I stopped trying to do that now which is why I'm not reporting this to the ModTweaker issue tracker).

Is there anything I'm doing wrong on my side or could this be a minor bug in TE?

**Comment by KingLemming** [comment]
Your assumption is wrong. It does not keep the "first item." If you want to remove the recipe, you need to change it.

**Comment by MaxNeedsSnacks** [comment]
Ah, I just revisited that issue where I took that from and yeah, I totally misunderstood what you said there, sorry for the silly mistake ^^

I'll probably just try using the json system to accomplish what I want to accomplish then (or just stick with UniDict)
