### ISSUE TITLE
[1.12.2]-[Thermal Foundation]-[Potion Fluids]-[Question]: Registries

### ISSUE THREAD

**Issue by Lanse505** [CoFH/Feedback#1454]
Question:
Is there any particular reason why Thermal Foundation is using:
```
PotionType.REGISTRY instead of ForgeRegistries.POTION_TYPES
```

See: https://github.com/CoFH/ThermalFoundation/blob/1.12/src/main/java/cofh/thermalfoundation/init/TFFluids.java#L264

**Comment by KingLemming** [comment]
Questions on Discord please. And I don't remember why offhand. Forge at one point had an issue with handling them correctly, so it was probably done to get around that.

**Comment by Lanse505** [comment]
Sorry :S, and that's a fair enough point.

Was mostly curious as I noticed it while reverse engineering how I'd get what the potion type was from the fluid and saw it in the above-linked part of the code.
