### ISSUE TITLE
[1.12.2]-[Thermal Foundation]-[Potion Fluids]-[Feature Request]: Potion Naming

### ISSUE THREAD

**Issue by Lanse505** [CoFH/Feedback#1455]
Request:
Potion Type Prefix on Names.

Reasoning:
With the current system, you end-up with confusing naming of Potion Liquids with STRONG and LONG type Potion Types from vanilla. Essentially producing recipes that looks like you're inputting and outputting the same liquid at the cost of an item when in actuality you are creating a separate potion type.

So currently looking at the code and what is being generated in-game.
It seems that there is no handling for the "STRONG" and "LONG" vanilla PotionTypes.
Case in Point:
![](https://cdn.discordapp.com/attachments/107517519589339136/553304419869917225/unknown.png)
![](https://cdn.discordapp.com/attachments/107517519589339136/553304443399962638/unknown.png)

So my current suggestion would be for some kind of Prefix system to be added.
"STRONG" type would possibly be "Empowered"
"LONG" type would possibly be "Lasting".

This would generate a result like:
Potion of Swiftness.
Empowered Potion of Swiftness.
Lasting Potion of Swiftness.

Empowered Splash Potion of Swiftness.
Lasting Splash Potion of Swiftness.

Empowered Lingering Potion of Swiftness.
Lasting Lingering Potion of Swiftness.

**Comment by KingLemming** [comment]
I agree with you - there absolutely should be a prefix system.

But vanilla needs to add it. I'm just keeping consistency with their current system.
