### ISSUE TITLE
Game Crash when load world

### ISSUE THREAD

**Issue by loveqmxd** [CoFH/Feedback#1456]
Thermal Dynamics 2.5.4
[mods_list](https://pastebin.com/QRzTuzXS)
[crash_report](https://pastebin.com/pBhw9p3Z)
I installed a retriever on a fluid duct, a fluid duct within a large water net composed by Thermal Dynamics' fluid duct, and some Thermal fluid tank at somewhere. The fluid-receiver block is a Thermal machine which mixes water and lava into obsidian.

**Comment by KingLemming** [comment]
This is a tech support thing. Discord please.
