### ISSUE TITLE
[Request] Dynamic Trees compatibility

### ISSUE THREAD

**Issue by Sweddy** [CoFH/Feedback#1458]
Hello,

Currently, that one machine I have forgotten the name of that drains liquid from trees does not work with dynamic trees from the ‘[Dynamic Trees](https://minecraft.curseforge.com/projects/dynamictrees)’ mod. I was wondering if compatibility could be implemented.
  I don’t know how the machine is coded, but I do know that the dynamic trees can be recognized as trees—because Minecolonies NPCs recognize them as trees—and that even though the trees seem to be made out of many different block types of varying sizes, they appear to in fact be the same kind of block, if any of that information is relevant.

Thanks.

**Comment by KingLemming** [comment]
Sorry, this unfortunately just isn't feasible given the current implementation of the Extractor.

I can look into it for 1.13+, but I won't be rewriting the entire block for 1.12 at this point.
