### ISSUE TITLE
All CoFH ores and ingots are invisible

### ISSUE THREAD

**Issue by wugmump** [CoFH/Feedback#146]
Hello! I posted this in FTB forums but there was no answer at all, and amazingly enough I can't find any other mention of it.

All CoFH ingots, ores and nuggets are *invisible*.  Black holes where ores should be, empty areas in inventory slots where the materials should be.

This is a video demonstration of the problem: https://www.youtube.com/watch?v=pw6j9pPQHUo

Here's the specs of my machine: https://www.dropbox.com/s/sxa0feqrmugjh3d/system.png?dl=0

Using the 1.8.0.21 64b JRE. 5.8GB allocated to MC currently. I'm seeing the problem in FTB Beyond 1.2.1.

Any help you guys can provide will be very much appreciated. Thank you.

**Comment by KingLemming** [comment]
Yeah, this is just sort of generalized texture sheet corruption. Happens infrequently and is apparently the whim of load order, memory allocation, and other arcane things.

Unfortunately, we can't really provide anymore help than that. It's not anything that we're doing specifically, just something that modded MC rarely does.
