### ISSUE TITLE
Small amount of fluid in Magmatic Dynamo

### ISSUE THREAD

**Issue by Kalman11** [CoFH/Feedback#1461]
Hi!
I'm not sure where I read it (maybe issues or changelogs?), I can't find it now, but this issue might have been reported.
In my magmatic dynamos, I've used Lava, but I've switched to Blazing Pyrotheum. The problem is that many of my dynamos (I got tons of them, around 120+) is not working, doesn't accept Pyrotheum. I've checked them and all of them has 10mB of lava inside them. Is there any way to fix this or do I have to pick them up and place again?

**Comment by BlueCreeper160** [comment]
Are there pipes below or conected with the dynamos?

**Comment by KingLemming** [comment]
You need to remove the fluid. Your assumption is correct, or you can pipe the fluid out.

In the future, please use the Discord for questions. This isn't a forum. ;)
