### ISSUE TITLE
Thermal Dynamics: Cryo-Stabilized Fluxduct does not work with Enderio Power Monitor

### ISSUE THREAD

**Issue by Rambut** [CoFH/Feedback#1463]
I use the Cryo-Stabilized Fluxduct so I can use more than 20,000 RF a tick but I would like to see the power monitor get supported with it. 

![22b146424b051f179082103e1c2e25eb](https://user-images.githubusercontent.com/8761115/54470414-74f1d280-477d-11e9-82ca-d017cf25d5c6.png)

**Comment by KingLemming** [comment]
Not possible due to how it works, sorry.
