### ISSUE TITLE
(Suggestion/Thermal Innvation):Tool Upgrades/Rework

### ISSUE THREAD

**Issue by Wotzinator** [CoFH/Feedback#1464]
so i tried out the TI tools,and they are good and all but i felt something is missing;customizebility.i know that you can upgrade and color them but i mean some sort of upgrade system like adding upgrades that allow for new functionality or/and visuals.

a few examples.
cooling:allows for cooling fluids to be insertet into the tool and makes it more energy efficient.
lubricating:basicly the same as cooling but with the difference that instead of making it more energy efficient it makes the tool faster.
heads for the drill and saw:adding new heads for the tools with new effects.

i have a few more ideas on that topic but ill just put those her for now.

**Comment by KingLemming** [comment]
Sorry, but no. They're meant to be simple and effective. I don't want to overcomplicate them with tons of options and micromanagement.

I may consider something like it for another mod, but choices like these almost always end up leading to false choices and pre-optimized paths.
