### ISSUE TITLE
[Request] COFH world compat for Astralsorcery ore.

### ISSUE THREAD

**Issue by Roonas** [CoFH/Feedback#1467]
Utilizing cofh to overwrite ore generation in the overworld causes a conflict with AS' rock crystal ore gen. Due to the fact that AS' rock crystal gen sets the data the resonating wand looks for on world creation, if removed by cofh and re-added thru a generation script it fails to redistribute the gen data to the new ore, thus making it incredibly difficult to locate. [HellFirePvp has suggest that this bit](https://github.com/HellFirePvP/AstralSorcery/blob/master/src/main/java/hellfirepvp/astralsorcery/common/world/attributes/GenAttributeRockCrystals.java#L160-L161)
can be utilized to bypass the effect and make ore generated thru cofh actually be picked up by the resonating wand.

**Comment by KingLemming** [comment]
Sorry, but no. If the generation is that specialized, then it's not something CoFH World should be handling.

Astral Sorcery *could* write their own plugin/generator for CoFH World and then register it at runtime, but it's not appropriate to handle it on our end.
