### ISSUE TITLE
NullPointerException when speeding up Energetic Infuser (Thermal Expansion)

### ISSUE THREAD

**Issue by Rushmead** [CoFH/Feedback#1468]
The Energetic Infuser from ThermalExpansion causes an NPE when sped up using the "Time in a bottle" item. Adding a simple null check on [this line](https://github.com/CoFH/ThermalExpansion/blob/1.12/src/main/java/cofh/thermalexpansion/block/machine/TileCharger.java#L203), would be a easy fix.

Crash Log: https://pastebin.com/rej1AdPe

Originally from FTBTeam/FTB-Sky-Odyssey#101

**Comment by KingLemming** [comment]
No, a null check there would band-aid it. It'd prevent the crash but put the machine in a non-viable state.

There's some weird hacks with the bottle, because calling an update tick shouldn't cause this in any form.

**Comment by Rushmead** [comment]
Understandable, my use of the word "fix" is probably not the best. I have no idea how the bottle works.

**Comment by KingLemming** [comment]
Oh actually. I know the issue. The bottle is calling update on the client side. it's making a HORRIBLE assumption that if a Tile is ITickable then it ticks on both server and client. That is wrong.

https://github.com/lumien231/Random-Things/blob/master/src/main/java/lumien/randomthings/entitys/EntityTimeAccelerator.java#L75

is the culprit line. It needs to be handled by RandomThings, probably by checking to see if the tile is *actually* registered in the chunk tickable list.

**Comment by Rushmead** [comment]
Alright, thank you for putting the time into looking into this. I'll make an issue on the relevant mods page. Again, thank you!

**Comment by LatvianModder** [comment]
Wait how is the the assumption that a tile is ticking on both sides bad? To my understanding, ITickable = ticks on both sides. It doesn't have to handle any logic on client side (e.g. `if(world.isRemote) return`) but how else are you supposed to "unregister" it from client side (or server side) tickable list?

**Comment by KingLemming** [comment]
It's entirely possible and allowed to remove a tile from either side if it doesn't tick on that side.

Witness:
https://github.com/CoFH/CoFHCore/blob/1.12/src/main/java/cofh/core/block/TileCore.java#L74

This is done for efficiency reasons and code decluttering.

**Comment by LatvianModder** [comment]
That's interesting, and I might use that myself, *however* I still think it doesn't hurt for you to add a simple `if(world.isRemote) return;` check. For the tick accelerator, it would be much more performance costly to check if Tile Entity is on the `tickableTileEntities` list for everything than if the tile itself made that check. Perhaps in future, there could be a forge method for this

**Comment by KingLemming** [comment]
It probably would be more performance costly, but it would also be *correct.* And that's more important. The mod doing something should be doing it right. Alternatively, it should only do what it's doing on the server side.

Putting the world remote check in the tile completely defeats the purpose of doing it the way that I am.
