### ISSUE TITLE
Crash with TiCon table

### ISSUE THREAD

**Issue by billybricker** [CoFH/Feedback#147]
Crashed when right clicking on the crafting station with the crescent hammer. Not sure if this is your issue or Tinkers'. I'll open an issue with them if needed.

https://pastebin.com/LSZp5i8a

MC Version: 1.10.2
Tinkers' Construct: 2.6.3
Thermal Expansion: 5.0.4.90
Thermal Foundation: 2.0.5.81
CoFH Core: 4.1.1.156

**Comment by transcondriver** [comment]
From what I can suss out, the Crescent Hammer attempted to rotate the crafting station, but the station did not have a "down" position to rotate to. Does the Hammer have a check to see if a block is valid for rotating?

**Comment by KingLemming** [comment]
The Hammer does not have such a check, because one is not mandated by Forge, nor is it wise to require one.

The block is supposed to override the rotateBlock() with appropriate action, so this is on TiCon to fix.
