### ISSUE TITLE
1.12.2 - Portable Tanks not showing liquid level change in newer Forge versions

### ISSUE THREAD

**Issue by AtomicWaffle14** [CoFH/Feedback#1471]
When updating forge from 14.23.5.2768 (recommended) to 14.23.5.2823 (latest), Portable tanks stopped visually updating their liquid level when placed and interacted with in the world. Functionally, they still would gain or drain the liquid; however, the liquid level in the tank would not rise or fall properly.

Not sure which forge version in between these two where the change occurred, but some mods required a newer forge version so I had to update. For now, gonna roll with the minimum I need which is 2776, since the tanks seem to work fine there.

**Comment by KingLemming** [comment]
Known and already fixed in Dev.

**Comment by AtomicWaffle14** [comment]
Okay, good to know! Shall I close this issue now or once the version is released?

**Comment by Cr33dC0d3r** [comment]
Is there a way to download a version including this fix? Or is there an estimated release date for the fixed version?

**Comment by aaronhowser1** [comment]
bump
