### ISSUE TITLE
Can't apply Multishot to Botania's Bows

### ISSUE THREAD

**Issue by Insane-96** [CoFH/Feedback#1472]
The Multishot enchantment can't be applied via Anvil on Botania bows and doesn't pop out in Enchanting table (Insight and Soulbound work)

**Comment by Tora-B** [comment]
Multishot is opt-in, so it's on Botania to implement the necessary interfaces. I believe IEnchantableItem is required for the enchantment to applicable, and IToolBow is required for Multishot to function.

**Comment by KingLemming** [comment]
Yep. This is something Botânica would have to implement. Sorry.
