### ISSUE TITLE
Crash at world load "Description: Exception while updating neighbours"

### ISSUE THREAD

**Issue by DemonfangArun** [CoFH/Feedback#1473]
https://pastebin.com/ZsQQeps1

All mod version info is contained within. The crash is likely a loading timing issue. I have a large city area near spawn that is all chunkloaded, with fluxducts, itemducts, and fluiducts under every street (think like a real city). I would estimate each network has at least 2-4 thousand ducts in it at this point (I stopped counting at some point). Everything was working perfectly until I restarted the server for a pack update. Upon booting the server, it finished loading fine, then as soon as it went to load all the chunkloaded areas the above happened.

**Comment by KingLemming** [comment]
Yeah, you have something chain forcing an update. Nothing we can do on our end I'm afraid. Feel free to come by our tech support channel and see if anyone has a MultiMC based suggestion.

**Comment by DemonfangArun** [comment]
Could I get a link to this channel?

Also I'm not sure what multimc would do to fix this. It's happening on a dedicated server, and my pack is published on curse and I have no interest in switching platforms.

**Comment by KingLemming** [comment]
Sorry, I meant MCEdit. Brain fart.

Discord here: https://discordapp.com/invite/uRKrnbH

**Comment by DemonfangArun** [comment]
-hands coffee-

**Comment by DemonfangArun** [comment]
Update: after finding out which duct was causing it (resonant fluxducts), and given the elevation, I figured out what area triggered the issue. It turns out that layers of fluxducts (say a 32x33x1 layer of them), and potentially other ducts, triggers this. They will work perfectly fine while the world is loaded, but when you reload the world what I'm assuming is some sort of routing calculation chokes on trying to do everything at once (whereas during creation it was able to do them as it was built out).

Perhaps some throttling could be added to spread the task out over a few seconds, capacitors/energy storage can cover for a small gap in generation.
