### ISSUE TITLE
What about Thaumcraft 6?

### ISSUE THREAD

**Issue by NathanielFreeman** [CoFH/Feedback#1474]
Hi, I am an admirer of your work, I have heard those rumors that TeamCoFH is going to adopt Thaumcraft 6, and I would like to know if this is still Real since I have not seen any news about it for months. I am especially interested in this because I have translated the Mod (Beta 26) into Spanish (my language) and I have the translation es_es.lang in my GitHub repository. For months I have not seen any activity in Azanor's repositories and I do not know where to send the "Pull requests".
Will there be new repositories in the TeamCoFH profile? will continue using the repositories created by Azanor? I like know more about this. Thank you very much for adopting Thaumcraft 6. Thank you all, truly.

**Comment by KingLemming** [comment]
This is not a forum. Please head to our Discord for questions.
