### ISSUE TITLE
[Thermal Innovation 1.12.2] Tools briefly "un-clicking" and disrupting Treecapitator

### ISSUE THREAD

**Issue by AtomicWaffle14** [CoFH/Feedback#1475]
Version: Thermal Innovation 1.12.2 - 0.3.2.11

Mining something with a Thermal Innovation tool (like the fluxbore and fluxsaw) for longer than normal causes them to briefly stop mining for a tick every so often. This normally is fine but not when using them with treecapitator, which hates when you un-click. 

How to reproduce:
-Take a fluxsaw and try to mine stone or obsidian
-Notice that the saw flicks upwards sometimes, but the breaking progress does not reset to zero.
-For mining blocks normally, this has no affect on the progress, but it does for treecapitator due to the way it is coded.

Is there a way to fix this that doesn't involve changing Treecapitator?

**Comment by KingLemming** [comment]
This is unfortunately just engine weirdness. Innovation's tools are coded to *not* do that, but the MC engine sometimes just forces it anyway. It's kind of annoying, but we literally can't do anything about it.
