### ISSUE TITLE
Restoring fluiduct connection in different chunks

### ISSUE THREAD

**Issue by JimusHimus** [CoFH/Feedback#1476]
Fluiducts should not be connected, but sometimes connection is restored. They are in different chunks.
![изображение](https://user-images.githubusercontent.com/39002687/55173953-a3b07580-518d-11e9-9d5c-59679c15b388.png)
![изображение](https://user-images.githubusercontent.com/39002687/55173886-8380b680-518d-11e9-829d-7cd61aaaed17.png)
![изображение](https://user-images.githubusercontent.com/39002687/55174003-bdea5380-518d-11e9-9ee6-f2015cb453eb.png)

**Comment by KingLemming** [comment]
Can't replicate this. You may have a mod that's doing weird stuff with chunk processing.

**Comment by JimusHimus** [comment]
Еxpressly I can't replicate this too.

**Comment by JimusHimus** [comment]
Just this:
![изображение](https://user-images.githubusercontent.com/39002687/55210091-e0fd1d80-51f6-11e9-90e8-ed55abe81e0b.png)

**Comment by KingLemming** [comment]
Yeah sorry, I think you're seeing some odd corner case with chunks themselves. We're getting into engine weirdness territory, and the fact is that Dynamics is being fully rewritten anyway.

Whatever this is, it's likely not something that can or will be addressed with the current codebase.
