### ISSUE TITLE
Maximum energy consumption

### ISSUE THREAD

**Issue by JimusHimus** [CoFH/Feedback#1477]
Magma crucible and maybe something else consumes only 666 RF/t instead of 750.
![изображение](https://user-images.githubusercontent.com/39002687/55287540-e901bc80-53b2-11e9-8a30-4e1ae962aded.png)

**Comment by KingLemming** [comment]
With that configuration, it should only consume 600 RF/t. Not sure where you got your jar, but please only get them from CurseForge. 750 isn't a thing.

**Comment by JimusHimus** [comment]
I got jar from CurseForge!
![изображение](https://user-images.githubusercontent.com/39002687/55297585-5bfd4880-5430-11e9-99c4-632a41fa7e73.png)

**Comment by JimusHimus** [comment]
Without any augments resonant magma crucible consumes 150 RF/t
![изображение](https://user-images.githubusercontent.com/39002687/55297642-ec3b8d80-5430-11e9-8186-3a789d0df49b.png)

**Comment by KingLemming** [comment]
Should be 120. Reset your configs, you've managed to break something.

**Comment by JimusHimus** [comment]
Indeed, reset config helped. I think the config was from early versions of thermal expansion on client side.
