### ISSUE TITLE
Compression Dynamo Additions (V2)

### ISSUE THREAD

**Issue by Fortist** [CoFH/Feedback#1478]
Basically Im trying to add Industrial Foregoing's Biofuel to the Compression Dynamo, but the script doesnt actually do anything. (No Error, no breaking the rest of the changes in the file, etc.)

According to Jared https://github.com/jaredlll08/ModTweaker/issues/717 because it "Just passes to Thermal" I cant add other fuels to the Compression Dynamo because of something on TE's side.

I dont know, it probably doesnt matter at this point.

**Comment by KingLemming** [comment]
160 is too small of a number. That's your issue.

**Comment by Fortist** [comment]
Oh. The documentation is straight garbage then. Thanks.
