### ISSUE TITLE
[Suggestion] Injectors can be fill a milk

### ISSUE THREAD

**Issue by KiBergMK** [CoFH/Feedback#1481]

**Comment by KiBergMK** [comment]
Currently, only a milk bucket should be used to reduce the effect of the potion.

**Comment by AtomicWaffle14** [comment]
Just to be clear, are you asking to make milk a usable liquid in the Hypoinfuser? I think that's a clever idea.

There is currently not liquid for milk in Thermal Foundation. They would have to add one, which can be complicated considering the way milk buckets work in the base game.

**Comment by KiBergMK** [comment]
> Just to be clear, are you asking to make milk a usable liquid in the Hypoinfuser?

yes, it is Hypoinfuser. btw, liquid for milk exists in the forestry:
![2019-04-07_18 40 42](https://user-images.githubusercontent.com/48606321/55686104-fc3dfa80-5965-11e9-97e4-b2a686bb5716.png)

**Comment by KingLemming** [comment]
Sorry, but this is a no. Milk isn't meant to be injected.
