### ISSUE TITLE
[Question] 9 Auxiliary Sieves capped off at 100 percent?

### ISSUE THREAD

**Issue by donqixot** [CoFH/Feedback#1483]
I am using [CustomAugmentScaling=true] in config and allow up to 9 augmentations for resonant level devices. I have resonant pulverizer with 9 Auxiliary Sieves installed. According to documentation https://teamcofh.com/docs/thermal-expansion/augment-auxiliary-sieve/, I should expect chance multiplier x20. For example, for iron ore in pulverizer, there is 10% of nickel dust. I expect that with x20 multiplier to be 200%, which means for every stack of iron ore, I should get 2 stacks of nickel dust on average? In reality, I only stack of nickel dust (plus 3-4 more). Is there some kind of cap around 100%?

![2019-04-06_18 23 11](https://user-images.githubusercontent.com/12219588/55676034-61c4b500-589a-11e9-80da-71881133b9a6.png)

Same question for Fractionating Still. For resin, there is 50% chance of getting rosin. With 9 Auxiliary Sieves augmentation, I should expect 50x20=1000%? In reality I am only getting 150%, as if additional multiplier is capped at 100% (plus 50% base rate).

![2019-04-06_18 23 21](https://user-images.githubusercontent.com/12219588/55676075-30001e00-589b-11e9-90bd-d3893e4800b3.png)

Is there a cap on secondary product chance and if yes, how is it set? Thank you!

**Comment by KingLemming** [comment]
Yes, there is a cap. No you cannot change it. And please use the Discord for questions. The issue tracker is not a forum.
