### ISSUE TITLE
FPS Problem with Thermal Foundation 

### ISSUE THREAD

**Issue by jefferyxu1** [CoFH/Feedback#1484]
After I add the series, the FPS is locked to 40 FPS. Even though I change the fps limit to unlimited, the game is still running at 40 FPS while fps indicator says 200. I found that the problem happens after the thermal foundation was added. Cofh core and Cofh world are fine. I am using Ryzen 2700x and Vega 56. How could I solve this problem?

**Comment by KingLemming** [comment]
We touch absolutely nothing related to FPS. I dunno what you're seeing but it's not us, sorry.
