### ISSUE TITLE
Creature Encaptulator's work area is 9x9x9

### ISSUE THREAD

**Issue by HD97300** [CoFH/Feedback#1485]
**Mod name/version:** ThermalExpansion-1.12.2-5.5.3.41-universal
[List of all mods](https://pastebin.com/46mWQk6R)

From [documentation](https://teamcofh.com/docs/thermal-expansion/creature-encaptulator/):
> it will begin using them to capture mobs in a 11x11x11 area.

But actually it work only in 9x9x9 area (pic related)
![2019-04-08_12 36 21](https://user-images.githubusercontent.com/13046608/55715129-bc762200-59fc-11e9-871e-8182e5984c55.png)

**Comment by KingLemming** [comment]
The issue tracker is for issues with the mod, not the documentation.

**Comment by HD97300** [comment]
So this is the desired behavior (9x9x9)? And it was a problem with the documentation, and not with the mod?

**Comment by Tora-B** [comment]
Uhhh... Pretty sure the **default** work area is now 11x11x11. However, it is configurable, and if you've kept old configs, it would still only operate on the old default of 9x9x9.
