### ISSUE TITLE
Morbs of modded mobs in centrifugal separator don't work

### ISSUE THREAD

**Issue by kreezxil** [CoFH/Feedback#1486]
Thermal Expansion: 1.12.2-2.5.4.18
Forge build 1,12,2-14.23.5.**2825**

Mobs from mods in morbs won't go into the centrifugal separator.

Original issue reported at https://github.com/kreezxil/World-of-Dragons/issues/126

**Comment by KingLemming** [comment]
Yes. Plugins are required to support them.

**Comment by kreezxil** [comment]
What plugins? I have everything that COFH puts out for Thermal
**everything** on 1.12.2.

**Comment by KingLemming** [comment]
What I'm saying is that a plugin hasn't been written to support that mod.
