### ISSUE TITLE
[suggestion] animated fluxducts

### ISSUE THREAD

**Issue by mtjohnson47** [CoFH/Feedback#1487]
Fluxducts should change color from dark to bright red depending on how much rf/t is transfering through them as a percentage of the total capacity.  For cryoducts, instead of max int as the total, it should probably use the highest value that chain has previously transferred.

This suggestion is partly for consistency (itemducts, fluiducts already show their contents), and partly just because it's a cool idea.

**Comment by KingLemming** [comment]
Sorry, no. This would be a large bandwidth burden for minimal visual impact.
