### ISSUE TITLE
Itemduct (base/dense/vacuum) recipes from JEI.

### ISSUE THREAD

**Issue by Slyklaw** [CoFH/Feedback#1488]
When clicking in JEI for any specific type of itemduct, you get the recipes for several types of itemducts. This is confusing.

Repro: Click on Dense Itemduct in JEI.
Expected: Only the Dense Itemduct recipe.
Actual: See recipes for 4 Itemducts, only 1 of which is a Dense Itemduct.

**Comment by KingLemming** [comment]
Yup. Quirk of how JEI works. Will hopefully be addressed in the rewrite.
