### ISSUE TITLE
Request for custom world generation generator types

### ISSUE THREAD

**Issue by bookerthegeek** [CoFH/Feedback#149]
Heyo!
#
So this one is a bit odd.... Have you ever turned off all ore generation except for Railcraft Ore Mines? Personally I find them amazing. Only issue is recreating it with COFH. Just can't seem to do it. So I was wondering if you could implement an ```mine``` generator type that generates ores similar to how Railcraft does theirs.

[I think the code for it is here][1]
[Picture of a vein][2] & [Another Picture][3]
#
Obviously it would also be up to CovertJaguar if he would be acceptable to you also using RailCrafts ore generation code. 

[1]:https://github.com/CovertJaguar/Railcraft/tree/mc-1.10.2/src/main/java/mods/railcraft/common/worldgen
[2]:http://i.imgur.com/zoIUmsc.jpg
[3]:http://i.imgur.com/tQ3bOWT.png

**Comment by KingLemming** [comment]
Technically you can already make your own and register them.

**Comment by bookerthegeek** [comment]
Gotcha. Time to go learn Minecraft mod making. ;)
