### ISSUE TITLE
Tesseract rendering error

### ISSUE THREAD

**Issue by Mcgode** [CoFH/Feedback#149]
Since I've upgraded to the lastest version of CoFH mods with Thermal Dynamics and the lastest forge I have this issue

Before break my last tesseract
![capture d ecran 2015-02-22 a 17 04 47](https://cloud.githubusercontent.com/assets/8111506/6319240/06580d02-bab5-11e4-953a-1d10b59a4b3c.png)

Just broke it:
![capture d ecran 2015-02-22 a 17 05 20](https://cloud.githubusercontent.com/assets/8111506/6319241/0710b60e-bab5-11e4-9504-21684efecf25.png)

Used ThermalExpansion-[1.7.10]4.0.0RC1-119

**Comment by miuirussia** [comment]
Confirm it

**Comment by KingLemming** [comment]
For whatever reason, your particular computer/potato doesn't care for the Shader.

You can disable it in config/cofh/core/client.cfg

with the line

# Set to false to disable shader effects in CoFH Mods.
    B:EnableShaderEffects=false

That'll fix you up, though things won't look as they are meant to.

**Comment by adudney** [comment]
Can confirm on my machine, Mac OS 10.10, Java 8, Intel integrated HD 5000 graphics card, happens with both active tesseracts and active warp-ducts. Brings framerate down to 1-3fps.

**Comment by Mcgode** [comment]
I'm gonna try, but it it is a problem due to the lastest version for sure, the last "B" release was working perfect. Also it was messing up the render of all the other non-block shaped tile entities. I assume that tesseract are breaking the rendering engine of something like that on Mac OSX.

**Comment by KingLemming** [comment]
Basically Macs are potatoes it seems. Disable shaders for now and we'll shoot for a test build that may fix the issue.

**Comment by adudney** [comment]
Fixed on newest ThermalFoundation alpha.

**Comment by ChibiPaw** [comment]
I was going post about this, but found this existing thread.. 
I have the exact same problem with the tesseracts rendering as well. 
The moment one gets turne on, the timing will return on opus from anywhere between 60k to 1+mil µs.  FPS drops down to zero, and I can't interact with anything other than turning my character away from it.  

Configuration is  Thermal Expansion 4.0.0 rc2-129,  OSX 10.10.2 , JDK 1.8.0.31-b13.  AMD Radeon HD 6750M. 

Let me know if you need more info form my config.

**Comment by Pamelloes** [comment]
Can confirm, me and my brother have been experiencing this issue on our macs while our friends (on PCs) have no problem.

**Comment by KingLemming** [comment]
On the latest version?

**Comment by KingLemming** [comment]
This has been fixed.
