### ISSUE TITLE
copper, tin, lead and iron ingot recipe issues

### ISSUE THREAD

**Issue by Genesiz13** [CoFH/Feedback#1490]
In Jei, any crafting recipe that uses copper, tin, lead or iron ingots as an input is having the input amount tripled ( or nonupled in the case of iron ingots) on the display. The actual crafting works fine, i only need to place one of each ingot in order to actually craft, however the recipes are always displayed with these increased amounts, and any other mod where i can save recipes is saving and reading them with these incorrect amounts.  i also noticed that when i set unidict to keep only one entry and hide all other recipes, it still displays two recipes : one by thermal foundation, and one by unidict, which leads me to believe the problem is being caused by one of these two mods, however i can't figure out which one is causing this.  I would appreciate any help figuring out what is the cause, and which mod is responsible for this. if it's not thermal foundation, i apologize for posting this issue here.
![Captura de Tela (1)](https://user-images.githubusercontent.com/40258873/56075912-3d883d00-5da0-11e9-8c0b-995e52a3e254.png)
![Captura de Tela (2)](https://user-images.githubusercontent.com/40258873/56075913-3d883d00-5da0-11e9-949f-95cf79c8768e.png)
![Captura de Tela (3)](https://user-images.githubusercontent.com/40258873/56075914-3e20d380-5da0-11e9-8d45-462b54a36d3c.png)

**Comment by KingLemming** [comment]
Yes this happens when you have a modpack and things screw up crafting. This isn't us.
