### ISSUE TITLE
Induction Smelter Won't Accept Oredict Gems in Recipe

### ISSUE THREAD

**Issue by Graywaren** [CoFH/Feedback#1491]
Hi
My partner and I are working on a kitchen sink modpack and we oredicted "gemPrecious" to include enderpearls, ourium crystals, and gems like diamonds, ruby, sapphire, and block of emerald. This has made the recipe for Pulsating Iron Ingots (originally ender io) in the induction smelter say that it accepts any "gemprecious" and JEI shows it rotating through that whole ore dictionary list. However, when trying to actually make the ingot, the induction smelter refuses to accept any gems aside from the enderpearl (which was the original recipe) and the ourium crystal. No other added gem can be placed in either input slot. I have the flux slot unlocked and I've tested it in creative with it upgraded all the way and with whatever augments and configurations i can manage to try and it still won't let them be input. We can't figure out what can possibly be going on because the recipe shows in JEI, so it should work, and it is accepting one item that was added, but not all. All the items show in JEI as properly added to the ore dictionary list, are showing rotating through in the recipe... I can't find any config that blacklists the smelter from accepting these items...  I'm stumped. Any suggestions on what could be going on?

We've got 1.12.2, forge b2805, CoFHCore-1.12.2-4.6.2.25-universal, CoFHWorld-1.12.2-1.3.0.6-universal, ThermalFoundation-1.12.2-2.6.2.26-universal, ThermalExpansion-1.12.2-5.5.3.41-universal, ThermalDynamics-1.12.2-2.5.4.18-universal

I can add any additional information you think would be useful, just let me know. Thanks!

**Comment by KingLemming** [comment]
OreDict gems aren't something the smelter normally allows for. It's a bit annoying but there's not a way around it with the current design.

I won't be addressing this until the next major release, sorry.
