### ISSUE TITLE
ender io energy conduit incompatibility

### ISSUE THREAD

**Issue by niklas2233** [CoFH/Feedback#1492]
Hey i just wanted to check if this is supposed to be like this or if its possible to make the cables connect. 
Ender IO ver: 5.043
Thermal Dynamics ver: 2.5.4.18
![2019-04-14_21 28 49](https://user-images.githubusercontent.com/33903786/56098076-d764fc80-5efc-11e9-86f6-7b2e127bb1b7.png)

**Comment by KingLemming** [comment]
Not a forum. Please ask questions on Discord.

Also without knowing how their conduits work, no idea. But there's not a good reason to try this anyways.
