### ISSUE TITLE
Resonant Satchel Crash

### ISSUE THREAD

**Issue by NillerMedDild** [CoFH/Feedback#1493]
If the Resonant Satchel is filled, it will cause a crash.
Crash: https://pastebin.com/ZkssnPas

**Comment by KingLemming** [comment]
Can't replicate this.

**Comment by NillerMedDild** [comment]
In that case, I think the Satchel has to contain a Building Gadget.

**Comment by KingLemming** [comment]
It's possible, or it's how Building Gadgets is apparently looking into the Satchel. I'm not sure what's happening based on the stacktrace.

**Comment by NillerMedDild** [comment]
The last two comments in the Building Gadget thread I linked could be helpful: https://github.com/Direwolf20-MC/BuildingGadgets/issues/280#issuecomment-483208283

**Comment by KingLemming** [comment]
Yeah, they're doing something weird.

**Comment by NillerMedDild** [comment]
Thanks :)
