### ISSUE TITLE
[RA] FI Pickaxe voids some blocks when empowered

### ISSUE THREAD

**Issue by Paul17041993** [CoFH/Feedback#1494]
Confirmed an issue with certain Immersive Engineering blocks, an easy example being concrete slabs, but also affects machine blocks. The centre block will be dropped correctly, however the upper and lower blocks will be completely voided.

I'd presume this is a specific case with materials, but regardless, the drop call should still occur for each block...

Forge; 2830
RA; 2.6.2.17
Core; 4.6.2.25
IE; 12-89

**Comment by KingLemming** [comment]
This sounds like something in IE's drop logic. We specifically actually call break the same way Minecraft does.

It's actually FAR more packet intensive than I would like.

Can you make this happen with Fluxbores or TiCon tools?

**Comment by Paul17041993** [comment]
Alright, well, I've mostly confirmed this is an issue with IE, as the same nullification occurs with Industrial Foregoing's and Poject Red's breakers, although not with OpenBlock's breaker...

I don't see anything immediately wrong with the code on either side, although IE on some blocks has getDrops overwritten as an empty function. I don't see why this would matter with silk-touch in use though...

**Comment by KingLemming** [comment]
Oh. Yeah that'll do it. Definitely on IE's end.
