### ISSUE TITLE
Crash with Strongbox

### ISSUE THREAD

**Issue by jk1895** [CoFH/Feedback#1495]
Hello,
I had two crashes with right clicking the Strongbox (Basic). After the crash and a reload of the game the chest can be opened.
[crash-2019-04-12_21.39.02-server.txt](https://github.com/CoFH/Feedback/files/3082021/crash-2019-04-12_21.39.02-server.txt)
[crash-2019-04-15_20.13.45-server.txt](https://github.com/CoFH/Feedback/files/3082022/crash-2019-04-15_20.13.45-server.txt)
Mod version: ThermalExpansion-1.12.2-5.5.3.41-universal
Forge version: 14.23.5.2815
Modpack: FTB Sky Odyssey

**Comment by KingLemming** [comment]
So, this would be caused by an error in your server, and that's what it sounds like happened. Not specific to our code though, sorry.

**Comment by jk1895** [comment]
Alright, but I don't play on a server.
Greetings
