### ISSUE TITLE
Holding-enchanted Portable Tanks filled with gas render incorrectly

### ISSUE THREAD

**Issue by codewarrior0** [CoFH/Feedback#1496]
ThermalExpansion-1.12.2-5.5.3.41-universal

Full tank looks empty. If I had to guess, [the problem is here](https://github.com/CoFH/ThermalExpansion/blob/1.12/src/main/java/cofh/thermalexpansion/render/BakeryTank.java#L114) since it's not calling `TileTank.getMaxCapacity` like it does in the non-gaseous case.

**Comment by KingLemming** [comment]
Eh.
