### ISSUE TITLE
Induction Smelter metal hardened glass doesn't work with fused quartz

### ISSUE THREAD

**Issue by SynexWolf** [CoFH/Feedback#1498]
Minecraft: 1.12.2
Forge: 14.23.5.2824
Thermal Foundation: 2.6.2.26
Thermal Expansion: 5.5.3.41

In jei, it shows that the different types of hardened glass can be crafted with fused quartz, but this is not the case with the induction smelter. You are not able to place fused quartz into the smelter.

**Comment by KingLemming** [comment]
Intentional so that you can't cheat the intended recipe. Fused Quartz sort of just tags along on the the oredict entry due to EnderIO's origins as a copy of Thermal. I wish they wouldn't.
