### ISSUE TITLE
No ability to change hotkeys or create them.

### ISSUE THREAD

**Issue by RoxyLuffer** [CoFH/Feedback#1499]
have the Electrum Watering Can has no hotkey, no way to set one in the game, or in the Config file. (Direwolf20 1.12.2 Pack Mod Version 0.3.1.8)

**Comment by KingLemming** [comment]
Incorrect. It's in the hotkey menu.

**Comment by RoxyLuffer** [comment]
Since you didn't believe me, Here are 3 Screenshots of the controls section of the Menu that shows no hotkeys for any of the Thermal Expansion mods. I checked the Configs, and sent them to a friend who knows java. There is no section for Thermal Cultivation. Could you maybe look into this now?
![2019-04-20_12 37 43](https://user-images.githubusercontent.com/1261310/56461034-70669e00-6369-11e9-82bf-6a5fb2149bb8.png)
![2019-04-20_12 37 53](https://user-images.githubusercontent.com/1261310/56461035-70669e00-6369-11e9-88b9-206a153e4900.png)
![2019-04-20_12 38 14](https://user-images.githubusercontent.com/1261310/56461036-70669e00-6369-11e9-81d1-1c78c9ca72a4.png)

**Comment by RoxyLuffer** [comment]
And if it is there, and I'm simply not seeing it, perhaps change its' name to "Watering Can Mode Select" or something one can search.

**Comment by KingLemming** [comment]
"CoFH Keys" - Cycle Item Mode

It's literally a section in the menu.

**Comment by RoxyLuffer** [comment]
What does CoFH mean even? It's not "Thermal" anything. Thank you for pointing this out for me.

**Comment by KingLemming** [comment]
Notice the github you're on? It's CoFH. That's the team.

**Comment by RoxyLuffer** [comment]
Ah, thank you. While I'm not new to mods, I didn't realise that the team name was used for the hotkey section, didn't know it was the team name and makes a lot of sense, now that the Thermal mods are broken up into multiple mods. Thank you for your time, and sorry for my ignorance.
