### ISSUE TITLE
Underfluid generator does not work

### ISSUE THREAD

**Issue by Tsyklop** [CoFH/Feedback#150]
I try generate `sulfur` from `Railcraft` under lava. My JSON:

https://pastebin.com/N6y0Pr6V

But this does not work. No parsing errors.

I read the documentation. It's old, since version 1.7.10, there are no examples.

EDIT#1: Generator `undewater` works fine.

**Comment by KingLemming** [comment]
Try "gen-fluid" instead of "genFluid" - there is no more camel case in 1.10.

In any case, please take this kind of stuff to the twitch chat since it's almost definitely a matter of configs and not an actual code issue

**Comment by Tsyklop** [comment]
@KingLemming `gen-fluid` not working.

**Comment by Tsyklop** [comment]
@KingLemming https://pastebin.com/vvEv2sig and this also not working.

I tried in many ways but all failed. I wrote in the chat - they do not know themselves what the problem may be. It would be normal wiki there were no questions, no problems. I also asked you to add examples from version 1.7.10. You somehow tested the generation, when they developed it. Why not put it on the wiki, I do not understand.

**Comment by Tsyklop** [comment]
@Tonius 

not working:

```
          "sulfur": {
			"distribution": "underfluid",
			"generator": {
				"fluid": "lava",
				"block": {"name": "railcraft:ore", "metadata": 0},
				"material": "stone",
				"cluster-size": 5
			},
			"cluster-count": 2,
			"min-height": 0,
			"max-height": 255,
			"retrogen": "false",
			"biome": "all",
			"dimension": {
				"restriction": "blacklist",
				"value": [
					-1,
					1
				]
			}
		}
```

**Comment by Tonius** [comment]
Oh, also `fluid` should be outside the `generator` object, on the same level as `distribution`. Didn't spot that one yet.

**Comment by Tsyklop** [comment]
@Tonius i try. not working.

**Comment by Tsyklop** [comment]
@Tonius 
I try this, but also not generated. Diamond block for a testing.
```
"sulfur": {
	"fluid": "lava",
	"distribution": "underfluid",
	"gen-fluid": "lava",
	"generator": {
		"fluid": "lava",
		"gen-fluid": "lava",
		"block": "minecraft:diamond_block",
		"material": [{
			"name": "minecraft:stone",
			"metadata": 0
		}, {
			"name": "minecraft:stone",
			"metadata": 1
		}, {
			"name": "minecraft:stone",
			"metadata": 2
		}, {
			"name": "minecraft:stone",
			"metadata": 3
		}, {
			"name": "minecraft:stone",
			"metadata": 4
		}, {
			"name": "minecraft:dirt"
		}, {
			"name": "minecraft:gravel"
		}, {
			"name": "chisel:basaltextra",
			"metadata": 7
		}],
		"cluster-size": 5
	},
	"cluster-count": 10,
	"min-height": 0,
	"max-height": 255,
	"retrogen": "false",
	"biome": "all",
	"dimension": {
		"restriction": "blacklist",
		"value": [-1,
			1
		]
	}
}
```

**Comment by Tsyklop** [comment]
I found a generation. But it is not so large and rare, although lava is a lot. Why? Diamond block for a testing.
![2017-04-04_14 34 09](https://cloud.githubusercontent.com/assets/6783568/24654796/01ba2dc6-1944-11e7-9a9b-6b58c9f12734.png)
![2017-04-04_14 34 34](https://cloud.githubusercontent.com/assets/6783568/24654802/04532e34-1944-11e7-967f-ce30c76d4d18.png)
JSON:

```
"sulfur": {
	"fluid": "lava",
	"distribution": "underfluid",
	"gen-fluid": "lava",
	"generator": {
		"fluid": "lava",
		"gen-fluid": "lava",
		"block": "minecraft:diamond_block",
		"material": [{
			"name": "minecraft:stone",
			"metadata": 0
		}, {
			"name": "minecraft:stone",
			"metadata": 1
		}, {
			"name": "minecraft:stone",
			"metadata": 2
		}, {
			"name": "minecraft:stone",
			"metadata": 3
		}, {
			"name": "minecraft:stone",
			"metadata": 4
		}, {
			"name": "minecraft:dirt"
		}, {
			"name": "minecraft:gravel"
		}, {
			"name": "chisel:basaltextra",
			"metadata": 7
		}],
		"cluster-size": 50
	},
	"cluster-count": 10,
	"min-height": 0,
	"max-height": 255,
	"retrogen": "false",
	"biome": "all",
	"dimension": {
		"restriction": "blacklist",
		"value": [-1,
			1
		]
	}
}
```
