### ISSUE TITLE
Server (SSP/SMP) crash with latest CoFH mods

### ISSUE THREAD

**Issue by stardustrider** [CoFH/Feedback#150]
When using the latest releases of the CoFH mods (including Thermal Dynamics), I repeatedly recieved the following crash report when I tried to either connect to my server or play locally via SSP. The server would startup and "run" without trouble, until I connected, when it could crash. When connecting to the server or trying to play locally via SSP, it would just kick me from the game, giving a "Server Closed" error.

An example of the error:
http://pastebin.com/9tvTUDFc

If I disabled BoP, those two lines would just disappear, and the rest of the error would remain the same. I spent a few hours trying to find the culprit, and turned out to be the wave of CoFH updates. Though, strangely, if I generated a new world locally, it wouldn't crash at all; it was with pre-existing worlds that I was having issue with.

**Comment by skyboy** [comment]
The actual error is being swallowed, launch the server with the java parameter `-Dcofh.classloadinghack=true` so we can see what's going on (the error will get much larger; this is a stackoverflow)

**Comment by stardustrider** [comment]
Appears to be stuck in some sort of loop:

https://paste.ee/p/BRWN6

**Comment by skyboy** [comment]
There are BoP plants that require a block to remain that are all updating and popping each other. Have you removed any mods? This should only occur when a bunch of blocks have disappeared from the world.

**Comment by stardustrider** [comment]
Nope, just updated the CoFH mods. Though, funnily enough, we have dynmap running, and prior to connecting and causing a crash, it was able to run and update various chunks. It appears as though there was some sort of ID mismatch(?):

http://map1.lychnobi.com/?worldname=Helios&mapname=surface&zoom=6&x=168&y=64&z=181

This area has yet to be re-rendered, and as you can see, a lot of blocks have been replaced with others, etc.

**Comment by skyboy** [comment]
Okay, what happened is that you were using alpha versions of ThermalFoundation and when you updated FML had a fit and corrupted your world. You'll need to restore from a backup (if you have any) downgrade everything CoFH to the last round of releases, load the world, then update it all again in sync.

**Comment by stardustrider** [comment]
Aw yis! Worked a treat. Downgraded the mod versions, restarted, connected, no problems. Updated all of the CoFH mods to the new releases, restarted, connected, no problems.

Swish!

**Comment by KingLemming** [comment]
Awesome.

**Comment by Wolfseverest93** [comment]
Wow, I think I'm one of the handful that avoided this issue when updating. XD thanks for posting it, this helps people like me from eventually posting the same thing when unnecessary.
