### ISSUE TITLE
[Suggestion] More Covers

### ISSUE THREAD

**Issue by CarlderGross** [CoFH/Feedback#1500]
I have been using Thermal Dynamics with some other mods for a while, and I created a building using Quark's Blue Stained Planks and Marble Bricks, but then discovered that there weren't covers for them. The same thing happened for Betweenlands Weedwood Planks
If you guys could make covers for the blocks from Quark and the Betweenlands, that would be really great.
I know how to make mods as well, so if you don't have time or something, I would be willing to make myself an addon mod that adds in the covers I need if you could explain how to do it. I am not very good at picking through other people's mods and figuring out how to make addons that add the features I want.
I have never made an addon before, so please make your explanation fairly detailed if you choose that route.
This 'issue' has been happening in Minecraft 1.12.2 with the "ThermalDynamics-1.12.2-2.5.3.16-universal" file. I assume the 2.5.3.16 is the version number, but I included the whole file in case it means something else.
Thanks for considering this suggestion!

**Comment by KingLemming** [comment]
Covers are autogenerated. If they are not available for a given block, then the block is not compatible. Also, please delete your configs and re run to ensure you did not have a whitelist specified.
