### ISSUE TITLE
[Enhancement] isStackTagEqual() should ignore not available NBT

### ISSUE THREAD

**Issue by Insane-96** [CoFH/Feedback#1503]
I'm using ModTweaker to add Quark's Tomes as obtainable in the Arcane Ensorcellator.
I'm using this line to add e.g. Looting III Book + Gold Ingots = Looting III Tome `Enchanter.addRecipe(<quark:ancient_tome>.withTag({ench: [{lvl: 3 as short, id: 21 as short}]}), <enchantment:minecraft:looting>.makeEnchantment(3).makeBook(), <minecraft:gold_ingot> * 64, 1000000, 5000, false);`.
The problem with this is it only works if you have a newly made book (directly from enchanting table) and not a merged one. So if you try to use a book that has been made by two Looting II books the Arcane Ensorcellator slot will not accept it since the tags are not equal.
The book in the recipe: `{StoredEnchantments: [{lvl: 3, id: 21}]}`
The merged book: `{RepairCost: 1, StoredEnchantments: [{lvl: 3, id: 21}]}`
The coulprit is the "RepairCost" tag that the merged book has. Due to this the Arcane Ensorcellator doesn't accept the merged book.
I think this has something to do with this line: https://github.com/CoFH/CoFHCore/blob/1.12/src/main/java/cofh/core/inventory/ComparableItemStackNBT.java#L50 Since it checks for equality between the two tags and they are not the same as one has 1 more tag.

**Comment by KingLemming** [comment]
No, definitely not, sorry. That would actually create a bug.
