### ISSUE TITLE
[1.12.2] [suggestion] [compat] Mystical Aggradditions Compatibility

### ISSUE THREAD

**Issue by ToMe25** [CoFH/Feedback#1506]
Please add support for the Mystical Aggradditions Crops to the Phytogenic Insolator,
or if you think that would be too op because you wouldn't need the Crux than add only support for the Tier 6 Inferium Seed.

**Comment by KingLemming** [comment]
I do think it's too OP. No, sorry.

**Comment by ToMe25** [comment]
@KingLemming do you think the Tier 6 Inferium Seed is so much Stronger than the supported Tier 5 one?
