### ISSUE TITLE
Game crash about using IC2's ov scanner

### ISSUE THREAD

**Issue by mcBegins2Snow** [CoFH/Feedback#1508]
[crash report](https://gist.github.com/mcBegins2Snow/f4ec1d262b8747dbcf06e682a43966fb)
There are some Thermal Dynamics's pipes near me when using IC2's ov scanner.

**Comment by KingLemming** [comment]
K. Better let IC2 know.

**Comment by mcBegins2Snow** [comment]
This issue has been reported to IC2.
https://bt.industrial-craft.net/view.php?id=2542
