### ISSUE TITLE
Forge Lexicon fails to account for wildcards

### ISSUE THREAD

**Issue by Landmaster** [CoFH/Feedback#1509]
While playing Project Ozone 3, I noticed that when trying to convert TF Hardened Glass to EnderIO Fused Quartz using the Forge Lexicon, the wildcard oredict for TF Hardened Glass is not expanded into its constituent items using `getSubItems`. This causes crashes when such an item attempts to render.
[lexicon_crash_log.txt](https://github.com/CoFH/Feedback/files/3140024/lexicon_crash_log.txt)

**Comment by KingLemming** [comment]
You've got like a million errors in that log.

The Lexicon is actually fine. This is technically an issue with Hardened Glass since I honestly didn't expect EnderIO to copy literally everything from my mods.

Handled in dev. You can certainly blacklist this OreName in the meantime, though.
