### ISSUE TITLE
Crash!

### ISSUE THREAD

**Issue by Ar97x** [CoFH/Feedback#151]
Crash log:
https://www.dropbox.com/s/jtugpwxfr9904i2/crash-2017-04-03_23.07.58-client.txt?dl=0

As you can see, crashed on initialization. Must be some kind of incompatibility with the mods I have.

**Comment by KingLemming** [comment]
Yeah, no idea what issue this is, but it's not on us.

**Comment by Ar97x** [comment]
Ok, but the only error on initialization is with Thermal Foundation and Expansion. Can't you point me at the right direction, at least?

**Comment by KingLemming** [comment]
I really can't. If this crash were in our code, it would happen 100% of the time to literally everyone. It doesn't. It's another mod causing it, but I have no way of knowing which from the crashlog.
