### ISSUE TITLE
extreme fps lag with all versions of Thermal Innovation

### ISSUE THREAD

**Issue by ycxtdxy** [CoFH/Feedback#1512]
Tested with forge 2768 and above. Other mods I use Thermal Foundation,Thermal Expansion, and Thermal Dynamics. Tested in single player mode. When Thermal Innovation is removed everything is fine

**Comment by KingLemming** [comment]
Feel free to swing by tech support in the discord, but Innovation itself literally cannot cause this. It's just items.
