### ISSUE TITLE
[BUG] Dupplicates machines when placed on water

### ISSUE THREAD

**Issue by chouuul** [CoFH/Feedback#1514]
Hello, I need your help, I have a bug on my server with sponge 1.12.2, When i place a redstone furnace, aqueous accumulator or another machine on water, it place a bugged machine without interface, but the machine still in my hand... it's bugged only in the overworld, i think it's a permission, but i didn't know what permission... Somebody can help me please ?

**Comment by KingLemming** [comment]
Tech support belongs on Discord. Please don't use the issue tracker for it.
