### ISSUE TITLE
Prevent servos from extracting and sending into the same inventory

### ISSUE THREAD

**Issue by segabl** [CoFH/Feedback#1515]
Just a simple QoL improvent I'd like to see. If you have multiple ducts connecting to an inventory that are part of the same duct network, placing a servo on one of them will make the servo extract items from that inventory and route them back into the same inventory it extracted them from. I can't think of a reason where this behaviour would be wanted and it would improve situations where I want an inventory to generally collect every item it can by placing a retriever on it but also have instances of where I want to retrieve certain items from that inventory to use them in some other processes.

**Comment by KingLemming** [comment]
There are actually situations where this is desired. They're admittedly kind of rare. And it'd be basically a full rewrite to make this happen, sorry.

**Comment by segabl** [comment]
Understandable. Are there any plans to improve item routing then? What I'm currently trying to do often fails due to duct congestion. I have one big storage inventory where I want all items to go to and a overflow/misc chest that stores excess or not sorted items. I have a vacuum item duct on route to the global storage and a dense on to the excess chest, so in theory, items should only go into the excess chest if they're not contained in the main storage or the main storage is full. However, if I'm not putting a retriever on the main storage things will often end up in the excess chest despite the main storage having enough spce for them (I assume due to transfer limit of pipes, I have a lot of stuff moving all the time). But putting a retriever on the main storage won't let me extract from the main storage anymore because the retriever would start retrieving from its own storage.
