### ISSUE TITLE
[Feature Request] COFH World: Configurable Geode width and height

### ISSUE THREAD

**Issue by Tommsy64** [CoFH/Feedback#1516]
I am using the `geode` feature-type and I would like to change its size; however, currently the size appears to be hard-coded. [WorldGenGeode.java](https://github.com/CoFH/CoFHWorld/blob/5c5590eb8ecac98d1dcf6701798133b512d65f44/src/main/java/cofh/cofhworld/world/generator/WorldGenGeode.java#L30). Is there a reason for doing so?
```java

	public WorldGenGeode(...) {
                ... /* constructor */
		this.setWidth(16);
		this.setHeight(8);
	}
```

If this request is accepted, I am willing to write a PR for it.

**Comment by KingLemming** [comment]
Honestly, I don't know. Come to the Discord and ask Skyboy. I think there was a reason but I'm unsure of it.
