### ISSUE TITLE
About issue #1508

### ISSUE THREAD

**Issue by mcBegins2Snow** [CoFH/Feedback#1518]
The issue #1508 (<b>Game crash about using IC2's ov scanner</b>) that I created has been closed, however this crash has not be resolved two weeks later.
This morning I reported the same issue to IC2, 
https://bt.industrial-craft.net/view.php?id=2542
On this afternoon, I recived this reply:

`This is a problem in Thermal Dynamics, not IC2.`

`They are doing an unchecked downcast from IBlockAccess to World, which is not covered by the APi signature and isn't even in line with Forge's own code ("Random rand = world instanceof World ? ((World)world).rand : RANDOM;" in net.minecraft.block.Block.getDrops(NonNullList<ItemStack>, IBlockAccess, BlockPos, IBlockState, int)).`

This reply means that the crash is irrelevant to IC2. <b>Be relevant to Thermal Dynamics.</b>

**Comment by KingLemming** [comment]
You could have replied to the existing issue. Do not open duplicates like this.
