### ISSUE TITLE
Making hardened glass recipe accept ore dictionary dusts

### ISSUE THREAD

**Issue by yafta98** [CoFH/Feedback#1519]
Currently (v2.6.2.26) it seems the recipes for hardened glass (in the induction smelter) accept only Thermal Foundation dusts (lead and obsidian). I assume this isn't intentional since pulverized materials are in the ore dictionary dust entries. I couldn't find any other recipes that do this but there may be more.

**Comment by KingLemming** [comment]
Cannot replicate. The smelter properly accepts any dust which is correctly oredict'd.

My guess is that you have things that aren't.
