### ISSUE TITLE
Enhancement - TOP Cache Compatibility

### ISSUE THREAD

**Issue by Karmacopper** [CoFH/Feedback#152]
Notices an odd thing with Thermal expansions caches, one the cache is hold 64 items TOP doesn't show the amount correctly. Just 64 until the cache is full, then it shows 128.

Not sure if this is your side or there's, so reporting it on both.

TOP version 1.1.x-1.4.5
TE version 5.0.4.90
CofH Core version 4.1.1.156

https://github.com/McJty/TheOneProbe/issues/157

**Comment by KingLemming** [comment]
Not really an issue so much as lack of integration. I'm unsure how to get TOP to correctly see the value offhand.

**Comment by Karmacopper** [comment]
So, that just leaves this blowing in the wind then?

**Comment by KingLemming** [comment]
Well I'm not sure how this should be handled. I can add IDeepStorage back to it, but if TOP doesn't know how to parse that, it solves nothing.

**Comment by Karmacopper** [comment]
I understand, and I appreciate your candour and effort as always.

**Comment by KingLemming** [comment]
I've asked McJty if there's a custom wrapper I should be using. If I can write one or some such, I'll flag this for enhancement.

**Comment by Karmacopper** [comment]
Thanks, I saw that. 👍

**Comment by KingLemming** [comment]
Marking as enhancement. No idea when this will get done though.

**Comment by Karmacopper** [comment]
Sounds good to me. Cheers

**Comment by KingLemming** [comment]
In dev but we actually uncovered a problem with TOP in the process, so I'll have to wait for that to get fixed, haha.
