### ISSUE TITLE
Crash with newest releases and alpha versions

### ISSUE THREAD

**Issue by TheJulianJES** [CoFH/Feedback#152]
When going to another dimension (Mystcraft) I crash. I had an tesseract im my inventory.. I hope this is what the issue caused. And if I connect now, the server crashes.
Forge: 1.7.10-10.13.2.1300-1.7.10-universal
Crash: http://pastebin.com/95jpibvB
Crash with releases from curse, and alpha versions from curseforge.

**Comment by TheJulianJES** [comment]
It has something to do with the tooltip I think..

**Comment by KingLemming** [comment]
Nope - it has something to do with the fact that you have somehow acquired an illegal itemstack. 12 is not a valid metadata value for machines.

You can't acquire this legitimately through TE gameplay, so it's possible something else you had messed with metadata in your inventory.

There's no fix for this I'm afraid beyond editing your inventory.

**Comment by TheJulianJES** [comment]
Okay, I deleted my playerdata, thanks for your support, I don't know how I got an illegal machine itemstack.. Sorry for this issue...

**Comment by TheJulianJES** [comment]
Also I have to figure out a way to get into my woid age, everytime I crash and I have to delete the playerdata...

**Comment by TheJulianJES** [comment]
I finally fixed it with MCEdit NBT Explorer and all that stuff..

**Comment by KingLemming** [comment]
No need to apologize for it; I'm really wondering how you got that ItemStack too. I'll see if I can't come up with a way to prevent that.

**Comment by TheJulianJES** [comment]
@KingLemming I'm German so I'm not good in English ;) So I apologize for "me"..
