### ISSUE TITLE
Hardened Glass compatibility with ChiseldAndBits

### ISSUE THREAD

**Issue by Fireztonez** [CoFH/Feedback#1520]
Hello,
I want to know if you can add Chisel&Bits compatibility for the Hardened Glass of Thermal Fondation. I really enjoy that block for decoration, but I can't use with chisel and bits right now.

If you need somes information let me know.

Forge: 14.23.5.2831
ThermalFondation: 2.6.2.26
Chisel&Bits: 14.32

Thank's
Fireztonez

**Comment by KingLemming** [comment]
To my knowledge, blocks don't have to do anything for compat, so if it's not working, it's on their end. It might be that "glass" just isn't something the mod supports by default.

**Comment by Fireztonez** [comment]
Ok I will open issue with chisel & bits, in that case, thank's KingLemming
