### ISSUE TITLE
"Operations" number provider and "world-data" not cooperating

### ISSUE THREAD

**Issue by g-rock84** [CoFH/Feedback#1524]
Hello! I really hope I'm not just being an idiot but I can't seem to get the "world-data" and "operations" Number Providers to play nice. It doesn't throw an error in the log file and as far as I can tell my syntax *should* be correct (obviously subjective).

Ultimately, I want to create meteor impact craters using plates from CoFH World. I'm trying to use either the "surface_block" or "lowest_chunk_horizon" world data number providers with the "operations" number provider to adjust the y position of the plates to create layers, but nothing generates when I use it as an operation. Here's the code snippet:
`"y-offset": {
	"value-a": 1,
	"value-b": {
		"world-data": "lowest_chunk_horizon" 
	},
	"operation": "subtract"
},`

However, when I run this:
`"y-offset": {
	"world-data": "lowest_chunk_horizon"
},`

Everything generates just fine. Am I an idiot, is this a bug or was this never intended to work this way? The documentation says that the operation number provider should accept other number providers. I am 100% open to suggestions for different approaches as well as constructive criticism as to why this might be dumb. Thanks!

Here is the full code if you'd like to take a look at my formatting/syntax/method/etc:
[https://github.com/g-rock84/miscellaneous/blob/master/crater_test_2.json](https://github.com/g-rock84/miscellaneous/blob/master/crater_test_2.json)

**Comment by KingLemming** [comment]
Please drop by the Discord for tech support; the github is for code issues.

Thanks.
