### ISSUE TITLE
Bug - Igneous Extruder won't output Basalt when available lava is < 1 bucket

### ISSUE THREAD

**Issue by jamthief** [CoFH/Feedback#1525]
Apologies if this is not a thermal foundation issue, I wasn't sure where to post.

Mod list: https://pastebin.com/rQMr0zp7

**What happens**
The igneous extruder uses up lava and water to create Basalt, until the lava level goes below 1 bucket. After that it stops working, until the lava level is replenished to >= 1 bucket. (the recipe calls for 250mb of lava, yet the extruder stops working even at 750mb of lava and with available water.)

**What should happen**
I _think_ the igneous extruder should continue to work so long as there is at least 250mb of lava and 1 bucket of water available.

**Steps to reproduce**
* Install Chisel `1.12.2-0.2.1.35`
* Install ThermalExpansion `1.12.2-5.5.3.41`
* Drop an igenous extruder, set it to Basalt mode, add power
* Place a bucket of lava and >= 2 buckets of water into it

**Comment by KingLemming** [comment]
Not a bug. Intentional. 1 bucket is always required.
