### ISSUE TITLE
[Feature Suggestion] Ducts for Moving Gas

### ISSUE THREAD

**Issue by MonfGeiger** [CoFH/Feedback#1526]
I'm basing this suggestion for the skyfactory 4 modpack and others that have thermal dynamics installed. This involves the Mekanism mod and its method of making gases

Here's my idea: we got ducts for transferring power, ducts for liquids, ducts for items, so why not cover the final base and do ducts for gas? In sf4, i'm using mekanism for making brine and eventually going for a tier 4 ore processing facility, and while there are tubes for gas and heat already, the mechanical pipes are missing, and I like the versatility of the ducts with how we can filter what goes where. So why not finish the puzzle and add ducts for transferring gases if possible?

**Comment by KingLemming** [comment]
Nope. Absolutely not. Mekanism having their own "gas" API is absurd. They need to use Forge Fluids like literally everyone else - this is exactly why we wrote it as a Fluid API.
