### ISSUE TITLE
ThermalFoundation materials are registered with no default repair item

### ISSUE THREAD

**Issue by LemADEC** [CoFH/Feedback#1529]
As of ThermalFoundation-1.12.2-2.6.2.26, all armors and tools from the mod have no accessible default repair item.
ThermalFoundation registers materials but don't their default repair Item.
Instead, CoFHCore is (re)implementing the repairability check into the tool classes with a protected ore dictionary name as seen for the Swords, here: https://github.com/CoFH/CoFHCore/blob/dbab6db4bfa90dd0a4bb801330620dc34a0392a9/src/main/java/cofh/core/item/tool/ItemSwordCore.java#L11 .

This prevents other mods to directly access the repair material to use.

**Comment by KingLemming** [comment]
Yes - the check is via "isRepairable".

Intended - specific materials are incorrect here as it should be oredict sensitive.
