### ISSUE TITLE
Game not starting.

### ISSUE THREAD

**Issue by SprinkCal** [CoFH/Feedback#153]
Whenever I load my game with the latest CoFH mod updates it won't start. It worked before I updated. 
The original problem was this which appeared to be caused by the blizz. 
Original: http://pastebin.com/6qRmpTJC
Now I have no clue what it could be.
New:   http://pastebin.com/AKRNXGcd

**Comment by KingLemming** [comment]
Your first problem was actually Ex Astris. It's looking for something that is no longer there.

As far as your second problem, you don't have the latest mod updates. Your TE is clearly still on beta 5.

Please be sure you have downloaded them all.
