### ISSUE TITLE
[Suggestion] An augment that reduces the power usage

### ISSUE THREAD

**Issue by PapiDimmi** [CoFH/Feedback#153]
In TE5 for 1.10.2, it would be really nice if there were an augment for machines like the redstone furnace that reduces the RF/t that the machine uses but also slightly reduces the speed at which they operate—essentially the opposite of the auxiliary reception coil.

**Comment by KingLemming** [comment]
Nah, sorry, no plans for this one. This is already accomplished by making dynamos fuel efficient with their augments. If I allow double dipping, it will create a free energy loop.

**Comment by PapiDimmi** [comment]
>This is already accomplished by making dynamos fuel efficient with their augments.

Huh, all right. I don’t use those.

>If I allow double dipping, it will create a free energy loop.

I’ve no idea what that means.

**Comment by KingLemming** [comment]
Efficient Magma Crucible + Efficient Magmatic Dynamos = free energy. I don't want that.
