### ISSUE TITLE
[Suggestion] Fluiducts/Itemducts and their Opaque Counterparts become one

### ISSUE THREAD

**Issue by MonfGeiger** [CoFH/Feedback#1530]
In thermal dynamics, we got itemducts and fluiducts, and opaque versions which are solid pipes that do not render their contents mid-transit like their non-opaque ones. This was fine at first, but after talking with some of my friends on discord and coming to the same conclusion, we think that there should be only one type of fluiduct/itemduct excluding the pressurized ducts (if I got that right), and make an option in the config that when set to true/false, turns the rendering of contents inside the pipes off and makes their textures then like their opaque counterparts

This came to me when I tried searching through mekanism's mod options in minecraft and found they have an option to set their opaque rendering on so nothing in the pipes they got render and they are fully solid. Doing so would eliminate the need for 2 different types of ducts while possibly giving servers the option to disable their internal rendering and fix some compatibility issues or whatever else players complain about nowadays

**Comment by KingLemming** [comment]
No. There are reasons to have different variants. You can mix/match and a lot of people do.
