### ISSUE TITLE
Thermal Dynamics: Dupe Glitch

### ISSUE THREAD

**Issue by Andre-Maartens** [CoFH/Feedback#154]
I placed 3 chests one with a stack of ae 2 logic circuits, another with a stack of printed silicon and lastly one with a stack of redstone dust
i used impulse itemducts to connect the chests to an inscriber, i used resonant retrievers to import the items and whitelisted each for on of the item to their respective sides
i used an impulse itemduct with a reinforced servo to extract the respective processors into a chest
it worked great, until after five min i still had a full stack off all the items, and when i picked it up with my cursor it changed to something like 348. same happens when traversing items between two chests

**Comment by KingLemming** [comment]
Have a screenshot?

**Comment by Andre-Maartens** [comment]
not at the moment but will have one tomorrow. ps nice response time

**Comment by KingLemming** [comment]
Based on the description - I can't make this happen. Not with Strongboxes or vanilla chests anyway.

**Comment by Andre-Maartens** [comment]
It may be one of the other mods interfering, i am running semi stable overkill pack, trying to push mc to its limit, the game is steady on 258 mods so i will add nei and cofh tf te td and onwards test each mod separately with nei and cofh tf te td to determine who is the culprit. Will notify of any other bugs

**Comment by Andre-Maartens** [comment]
updating to the latest alphas of the mods worked to a point:
nice touch:
![4](https://cloud.githubusercontent.com/assets/9878596/6329370/572bd6e6-bb78-11e4-8a15-7438db4108aa.png)
the culprit is applied energistics
i have three chests with:
64 redstone in chest x
64 printed silicon in chest y
64 engineering processors in chest z
![5](https://cloud.githubusercontent.com/assets/9878596/6329371/572c44a0-bb78-11e4-8066-b69c3a632f96.png)
test setup for inscriber
![6](https://cloud.githubusercontent.com/assets/9878596/6329373/5737ac00-bb78-11e4-8c8d-8bd36f898fd7.png)
the td conduits forces any item to any slot which cannot be done manually playerwise (it is like trying to wear oak wood logs for a helmet) notice three printed silicon was drawn from the chests
![7](https://cloud.githubusercontent.com/assets/9878596/6329374/573d75a4-bb78-11e4-8907-0b634354e6f3.png)
but the chest shows 64 silicon
![8](https://cloud.githubusercontent.com/assets/9878596/6329375/5744f63a-bb78-11e4-9541-10a6244df772.png)
when picked up you get a random amount extra
![9](https://cloud.githubusercontent.com/assets/9878596/6329372/5731fca6-bb78-11e4-823a-01ee31c58286.png)
and lose all of it and get 65 back
![99](https://cloud.githubusercontent.com/assets/9878596/6329376/574a34ce-bb78-11e4-8135-6be51a11e799.png)
so for only occurs on ae2 blocks
