### ISSUE TITLE
Rare Machine/Tank Reset Bug

### ISSUE THREAD

**Issue by EZKatnipz** [CoFH/Feedback#154]
Pretty rarely, some of the Thermal Expansion machines and tanks will reset, losing liquids, upgrades and power. Seems to happen on server restarts or world reloads. Hard to replicate, since it seems to be pretty rare/random.

**Comment by KingLemming** [comment]
When you say restart or reload, do you mean after a crash? Because offhand this would only happen if a chunk isn't properly saved.

**Comment by EZKatnipz** [comment]
Nope, no crashing at all. Just general "Save & Quit" out of single player, and normal scheduled server restarts. I've seen it happen myself specifically to the 1st tier portable tank, the lava in it no longer being in it, and some of my players have lost upgrades on other machines. I found a thread on the FTB forums where a couple people were talking about it, but not really any information. 
It seemed to happen after almost every time I got on my server before the newest update, (my tank resetting) until I updated all of the CoFH mods, then it stopped for a couple days, now the issue has returned. One player lost all upgrades, except for his energy cells, and my tank reset again. (i haven't been using much TE stuff out of fear of losing them) my server does have 15 minute auto-saving.

Feel free to ask me any questions for any information you might need, I certainly don't mind helping to resolve awful problems.

**Comment by KingLemming** [comment]
Yeah, I can't seem to make this happen.

**Comment by EZKatnipz** [comment]
I'm going to try out a few things, see if I can either fix it or maybe find the cause or something.
Here is the link for the FTB thread I was talking about:
https://forum.feed-the-beast.com/threads/thermal-expansion-machines-lose-upgrades-and-reset-configuration.222008/

**Comment by KingLemming** [comment]
Yeah, reading over that thread, I'm extremely confident that the issue isn't in our code at all.

And really, there's essentially NOTHING it could be in our code. Tile Entities essentially have save and load functions. We use them. This is something that if we got wrong, we'd be getting it wrong 100% of the time.

There's a lot going on in Beyond, so I'll leave this up for now in the hopes that somebody can figure out what it is. If it takes a while to start happening though, I'm betting another mod is at fault here and their tile entity errors out or some such, which screws up the save operation for everyone else.

**Comment by EZKatnipz** [comment]
Ahh, that makes sense. I figured another mod was causing problems, since there is very little info. Now, the conflicting mods machines and whatnot would also reset? Or should everything reset? Because only thermal expansion stuff currently resets from what we've seen.

**Comment by KingLemming** [comment]
The thread says that Botania does as well, so I was going off of that. Do the machines also lose inventory?

**Comment by EZKatnipz** [comment]
I believe they do, tanks do at least. I know they can sometimes lose stored power and upgrades. I do not currently have Botania in my modpack, although I was planning on adding it eventually. I will continue gathering as much information as I can about this, I do understand how bug fixing and coding can be.

**Comment by EZKatnipz** [comment]
Actually, thinking about it, early on I saw the Applied Energistics grindstone lose inventory and the SkyStone Chest from the mod had reset, losing inventory and faced North.

**Comment by EZKatnipz** [comment]
Do you think it is possible for Mekanism to be contributing to this issue? In my single player testing of this, I have not been using Mekanism machines, and some other issues have been caused by Mekanism.

**Comment by legodude17** [comment]
Based on what they lose, it seems the tile entities are not being saved correctly.

**Comment by EZKatnipz** [comment]
thats what i was thinking, but i would have no idea what would be causing it. My friend can reproduce in single player, but i cannot.

**Comment by legodude17** [comment]
What is different about your setup from their's?

**Comment by KingLemming** [comment]
Just so everyone is clear, I'm 110% positive that we aren't the cause of this. Still leaving this up for discussion so we can figure out who is.

**Comment by legodude17** [comment]
Ok, does this occur consistently?

**Comment by TheBrain0110** [comment]
Quite possibly unrelated, but this does remind me of an issue I ran across back when the FTB Beyond pack was first released, I had random TEs losing data too. My suspicion was WorldEdit was to blame, but there was no real way to tell. So just in case it gives anyone any ideas:

https://forum.feed-the-beast.com/threads/random-tile-entities-losing-data.220863/
http://imgur.com/a/4Uh0R

**Comment by EZKatnipz** [comment]
Do you thing there could be anything that could linger around and cause the issue? Such as using ChunkGen (i have used that on my server)

**Comment by EZKatnipz** [comment]
Alright, so apparently what my friend had replicated in his single player world was an issue with EnderIO conduits draining power from Mekanisms Power Generators. That is easy to reproduce and is a known issue. He apparently never tried to replicate the Thermal Expansion machines reset bug. When I had asked him if he could replicate the reset bug before, he had always said he did.
From the other thread about the reset bug, they said they couldnt reproduce the issue on a fresh server install. I have reset everything except the world file, but the issue still exists. Maybe it is something that is kinda just stuck in the world file? i would really prefer not to have to reset my whole server world lol

**Comment by EZKatnipz** [comment]
I think the issue might be with the chunks themselves. I was able to go to a completely new area, never loaded, and i couldn't get anything to reset. But in the areas that were generated with the Chunkgen mod, everything resets on server restart.

**Comment by k-dueb** [comment]
Just wanted to drop here that I had the same issue with my own (home) server.
I solved it by setting back to default the Forge setting 'dormantchunkcachesize' that was set to 0 after I changed it (thinking it was a good idea) to an other value for both for the client and the server.
Maybe changing both server and client settings caused a desync? I don't know, I didn't tested further tbh.
Hoping this can help, somehow! :)
Minecraft 1.10.2 - Forge 12.18.3.2254

**Comment by EZKatnipz** [comment]
Hmm, while i havent had any issues since i started using a different part of my world, i had changed that. maybe i'll change it back to 0 just in case.

**Comment by EZKatnipz** [comment]
Issue must be either dormantchunkcachesize in Forge configs, or chunk problems possibly caused by pre-generation. Either way, seems to be solved by moving to new parts of the world in the case of chunk problems, or changing dormantchunkcachesize to zero. Havent had any problems at all since.

**Comment by k-dueb** [comment]
Considering I had the same problem on my side without pre-generating chunks, I think instead it's related to Forge's dormantchunkcachesize (https://github.com/MinecraftForge/MinecraftForge/issues/3325).

But with so few information on that bug, we cannot confirm if it's a Forge(/Vanilla?) bug or not.
Maybe it's just a mod not doing something it is supposed to do? I don't know...

**Comment by EZKatnipz** [comment]
Right? This one is tricky to track down it seems. Also doesn't help that it can be inconsistent.

**Comment by k-dueb** [comment]
Yeah, and that's sad because this is a huge perf improvement!

**Comment by bs2609** [comment]
Please see https://github.com/Vazkii/Botania/issues/2263, `TileCore` seems like it would be affected here.

**Comment by KingLemming** [comment]
Hmm...

**Comment by Linkthekiller13** [comment]
I playing with TE and i seem to have the same problem where the tanks, engines, and energy cells reset and rotate towards north. i don't know what is causing it but seems maybe when it loads the chunk it happens. when i go back and forth to a different dimension it happens but not every time.

I'm see if i can get with the server owner and change the config "dormantchunkcachesize" and see if it helps it.

**Comment by KingLemming** [comment]
So basically, this sounds like a Forge issue. And it's unfixable until 1.11 because Forge doesn't backport bugfixes.

I'll have the fix ready for when we go to 1.11, but there's nothing we can do about it right now.

**Comment by KingLemming** [comment]
Calling this resolved now in 1.11.
