### ISSUE TITLE
[CoFHCore-1.10.2-4.1.1.156] Dense ore won't generate

### ISSUE THREAD

**Issue by Slater022** [CoFH/Feedback#155]
Do someone know why denseore from https://mods.curse.com/mc-mods/minecraft/224942-dense-ores won't generate in this script : https://pastebin.com/V7BFPUeD
Only coal ore is generating.

about : "denseores:minecraft_coal_ore_0" -> when i try a give command with that name it's working good.

( mc 1.10.2, CoFHCore-1.10.2-4.1.1.156-universal , denseores-1.11-alpha-1.0.1 )

PS : if it's from the dense mod problem i'm asking the same thing on curse srry in that case

**Comment by KingLemming** [comment]
This is not a forum. Please ask in Twitch chat or IRC.
