### ISSUE TITLE
[1.10.2] Suggestion - Add recycle recipes

### ISSUE THREAD

**Issue by ZorbaHerbalist** [CoFH/Feedback#156]
In 1.7.10 TE registers "recycle" recipes, for example golden sword with sand makes gold ingots and slag. Is there any plans to bring this back to 1.10.2?

**Comment by KingLemming** [comment]
This isn't a forum. It's not for questions.

I'll mark it as a request, but seriously, this is what Twitch chat is for.

**Comment by ZorbaHerbalist** [comment]
I wanted to not be claiming. It was rather a rhetorical question :)

**Comment by PapiDimmi** [comment]
I second this. Bring it back!

**Comment by KingLemming** [comment]
The reason it was removed wasn't really a balance one, but a change that Forge introduced between 1.7 and 1.10. It's not nearly as easy to support anymore.

**Comment by KingLemming** [comment]
So, it's readded in a fashion. I can no longer guarantee that it results in the preferred ingots though. :/
