### ISSUE TITLE
Crashing with Thermal Dynamics + Thermal Expansion

### ISSUE THREAD

**Issue by fewewq** [CoFH/Feedback#156]
http://paste.ee/p/VnmQY I can't open the game because it crashes with those errors

**Comment by Deckee** [comment]
Getting the same crash
http://pastebin.com/kp7Qpf6e

**Comment by fewewq** [comment]
Yeah I was also getting an issue with Thermal Expansion the newest one http://paste.ee/p/iMohd

**Comment by skyboy** [comment]
Update everything.

**Comment by fewewq** [comment]
Update what?

**Comment by fewewq** [comment]
I did.

**Comment by KingLemming** [comment]
No - your crashlog clearly shows that TE is still on B8.
