### ISSUE TITLE
Can't load/create a world when Thermal Expansion is installed

### ISSUE THREAD

**Issue by AegisLesha** [CoFH/Feedback#158]
The title is self explainatory I guess
I tested what happens when I remove TE and everything working just fine

Also, here's an interesting part from the log:
http://pastebin.com/CzpjCTWh
It seems like TE Pulverizer, Metallurgy and maybe AOBD are involved

**Comment by KingLemming** [comment]
Yup. Metallurgy or AOBD is at fault here - they're doing something they absolutely should not be; probably reflecting into the Pulverizer and adding recipes or registering things to the OreDictionary at the wrong time.

Sorry, this one just isn't on us.

**Comment by ganymedes01** [comment]
I can't talk for Metallurgy, but AOBD isn't reflecting into anything.
And it registers items in the dictionary at PreInit. Is that correct? I can easily move it to Init or even PostInit if needed.

**Comment by skyboy** [comment]
Then AOBD isn't involved, the issue is caused by mods using TE-internal classes to register recipes instead of the provided IMC-based API.

**Comment by ganymedes01** [comment]
Definitely not AOBD then. I use the IMC messages to register it's recipes with TE.

**Comment by Glassmaker** [comment]
Well, we don't touch Thermal Expansion's pulveriser or other Thermal Expansion machines at the moment.

I have another user who stated that the crash happened after removing then re-adding the mods in batches. TeamMetallurgy/Metallurgy4#58

So, I don't know how this happens.
