### ISSUE TITLE
Request: Ig. Extruder - Whether to use water for obsidian

### ISSUE THREAD

**Issue by charlesbevans** [CoFH/Feedback#159]
I'd like to request a config to enable/disable the use of water when making obsidian in the igneous extruder. Cobble gen mimics vanilla (no water or lava used up), but obsidian uses up water unlike vanilla.

BTW, great to see you in 1.10

**Comment by KingLemming** [comment]
I won't be adding a config, but I am adding an augment which will work for both Stone and Obsidian.

I realize that strictly speaking, Obsidian doesn't use up water in a classic generator, but this is meant as more of a logistical challenge and a balance thing.

A config would partially negate the usefulness of the augment, so it's not something that I particularly want to do.

**Comment by charlesbevans** [comment]
Fair enough. Thanks for considering it and for all the hard work.
