### ISSUE TITLE
Thermal dynamic...

### ISSUE THREAD

**Issue by Pilad** [CoFH/Feedback#16]
When will the mod Thermal dynamic ?

**Comment by bochen415** [comment]
Now you've done it. They will add another week to the release date..

**Comment by Pilad** [comment]
Thanks ))

**Comment by KingLemming** [comment]
The description of the repo clearly says not for questions. We have an IRC channel for that. It also says to use proper grammar.

So, I refer you to: https://www.youtube.com/watch?v=8Gv0H-vPoDc
