### ISSUE TITLE
Bizzare Compatability Bug with Biomes O' Plenty and other mods.

### ISSUE THREAD

**Issue by C1ffisme** [CoFH/Feedback#160]
For some bizzare reason, when placing an item frame from Quark on the ceiling or floor, or when placing down a bucket of poison or blood from Biomes O' Plenty, a basic, empty tank is placed instead.

I'm using ceramics, and it seems like placing poison or blood with a clay bucket does not result in this behavior.

Mods currently in use:
AdvancedRocketry 1.0.15
AutoRegLib 1.0-2
Biomes O' Plenty 5.0.0.2162
Ceramics 1.1.5
Chameleon 2.2
CodeChickenLib 2.5.7.241
CoFHCore 4.1.1.156
CraftTweaker 3.0.24
foamfix 0.6.1-law
jei 3.14.7.314
journeymap 5.4.6
JustEnoughResources 0.5.8.98
LibVulpes 0.1.17
Mantle 1.1.3
Quark-r1.1-70
SimpleCorn 2.1.6
StorageDrawers 3.5.16
TConstruct 2.6.1
ThermalExpansion 5.0.4.90
ThermalFoundation 2.0.5.81
ThermalSmeltery 2.0.2

**Comment by KingLemming** [comment]
Yeah, we have absolutely nothing to do with this. Somebody has a super hacky bucket handler and they've gone off the range.

**Comment by C1ffisme** [comment]
Welp, Imma try and find out which mod is responsible.

**Comment by KingLemming** [comment]
Sorry I can't be more helpful. That definitely sounds like a cluster of a bug, but we're the victim here. :P

**Comment by C1ffisme** [comment]
And just like that, the bug is... gone?

I put every single mod into a test profile and folder one at a time and tried to reproduce the bug, but to no avail. Then I started up the profile I found this bug with, assuming that this had to do with configs, and could not get it to happen.

Truly bizarre.
