### ISSUE TITLE
Induction Smelter's new "Flux Lock" does not accept Rich Slag

### ISSUE THREAD

**Issue by codewarrior0** [CoFH/Feedback#160]
Using ThermalExpansion-[1.7.10]4.0.0RC1-119. Does accept Sand and Cinnabar, but no Rich Slag.

**Comment by KingLemming** [comment]
Works fine for me. Sure you're trying Rich Slag and not standard?

**Comment by codewarrior0** [comment]
100% sure.

I was able to replicate your screenshot on a new Creative world, but in my existing Survival world a Reinforced level Smelter will not take the Rich Slag.

**Comment by KingLemming** [comment]
Okay, that's quite interesting. And I think I may know the issue.

**Comment by KingLemming** [comment]
I think I've got this one fixed. Tentatively marking it so.
