### ISSUE TITLE
Starfield Shader isn't loaded from resource pack, thus is impossible to override

### ISSUE THREAD

**Issue by adudney** [CoFH/Feedback#163]
I'm trying to debug the shader on my Mac so I can hopefully make it run at non-3fps or so I can report useful info to you so you can fix it to run at non-3fps. This is difficult or impossible when it only loads from the jar.

I understand this is an esoteric use case, but I'd love to help figure out why it's only slow on certain Mac machines (My first guess is M_PI doesn't need to be nearly that precise, and you don't need to do mod(thing, 2*M_PI) every time you use a trig function (As they're cyclic) but I can't test those theories.)

**Comment by KingLemming** [comment]
Well for the moment - you can disable it altogether in CoFHCore's client.cfg.

I'll see what needs to change with that.

**Comment by adudney** [comment]
Cool, no rush.
I hope the issue isn't too hard to find, the starfield is a nice upgrade from the previous animated texture.

**Comment by KingLemming** [comment]
The cynic in me says the issue is that you're using a Mac and it's just poor drivers. A quick google search seemed to turn up as much. :/

Hopefully there's a fix.

**Comment by adudney** [comment]
https://lists.apple.com/archives/mac-opengl/2006/Nov/msg00202.html

Knowing the speed at which Apple updates their OpenGL drivers, this is probably the problem.

**Comment by rwtema** [comment]
http://github.com/CoFH/ThermalFoundation/commit/4ad985a03de28a855078ba820e56a7868a97cd2b

I've removed the noise function in the shader method. Probably won't affect the effect itself (god I hope I got that right).

Rather annoying that card makers choose not to support methods in the GLSL though.

**Comment by adudney** [comment]
Yeah, but evidently it's not just a Mac issue, it's the card vendor's fault. :( And yes, I think the grammar of that sentence is correct.

**Comment by KingLemming** [comment]
I don't think we'll be resource packing it (is that actually possible?) but just wanted to check in - is the new version acceptable on your potato/Mac?

**Comment by adudney** [comment]
Yes, the new version works fine. Although I just want to point out that the bug isn't just a mac specific bug, unfortunately the noise function is really poorly supported, even on windows :P

And I would hardly call my current machine a Potato. :)
