### ISSUE TITLE
Crashing / needing older versions 

### ISSUE THREAD

**Issue by Allensfish** [CoFH/Feedback#164]
Hello.  I am trying to create a modpack with the lates version of bucket for 1.7..10 but the cofhcore and thermal mods are to updated/ new to work with couldron.  Is there a place to get older version of your mods?

**Comment by KingLemming** [comment]
Cauldron isn't supported. Also, I have no idea what you'd need.

And I'd really appreciate it if people would stop using the issue tracker as a forum. Please ask questions in Twitch chat or IRC.

**Comment by Allensfish** [comment]
well all i need i believe is an older version.  were can i find them? or were can i find your twitch chat or IRC?

**Comment by covers1624** [comment]
Cauldron is horribly outdated. Use Thermos, https://cyberdynecc.github.io/Thermos/

**Comment by Allensfish** [comment]
how do i install thermos.   i do what it says but it is very confusing.
