### ISSUE TITLE
Sent to multiplayer menu after updating CoFH and ProjectRed mods

### ISSUE THREAD

**Issue by kimfy** [CoFH/Feedback#165]
When my world(singleplayer) is done loading it sends me to the multiplayer menu with a message "A fatal error has occured, this connection is terminated". Trying to load it a second time works fine. I cleared my log right before trying to launch my world. [Launch game log, does not include world load](http://paste.ee/p/Fl1Ii), [World load log](http://paste.ee/p/7QGFi). This happens 10/10 times. I am playing on a potato at the moment if that helps.

I have absolutely no clue what's going on, at line 547 I get disconnected(second log). Would be great if someone told me out of curiosity where I should look to find out what this issue is so I can fix these issues later and tell me why it's working when I load my world the second time...

Edit: i cleared my log before opening the world a second time to 'compare': [pastee](http://paste.ee/p/jemUZ)
Edit2: I'm sorry if this has nothing to do with CoFH mods

**Comment by KingLemming** [comment]
This seems to be ExtraUtilities.

[11:14:03] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.NullPointerException
[11:14:03] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.rwtema.extrautils.multipart.microblock.ItemMicroBlock.func_150895_a(ItemMicroBlock.java:75)

**Comment by kimfy** [comment]
That's unfortunate... I disabled ExU temporarily and still being sent back to the screen, time to disable one mod at a time! Thanks anyways though King
