### ISSUE TITLE
Docs Update

### ISSUE THREAD

**Issue by legodude17** [CoFH/Feedback#165]
I am really loving all of the CoFH mods and I appreciate all of the hard work you put into it. I just want to request that the docs be updated for the 1.10 version of the mods.

**Comment by KingLemming** [comment]
I promise, you are not the only person to have asked this. You may, however, have been the first to use the issue tracker for it rather than Twitch or IRC.

We're working on it. It takes time.

**Comment by KingLemming** [comment]
I'll go ahead and reopen this just so we don't get copycats. If you *really* want them updated though, you are welcome to PR to the github repo. :)

**Comment by legodude17** [comment]
@KingLemming I actually sent one already. I would love to help out the docs though.

**Comment by legodude17** [comment]
@KingLemming Just sent another one CoFH/cofh.github.io#2. Am I doing this right?

**Comment by KingLemming** [comment]
Not sure yet. I'm not the one in charge of the page, but will take a look. :)

**Comment by legodude17** [comment]
@KingLemming Thanks for being supportive!

**Comment by Dietz8** [comment]
I could be posting this in entirly the wrong spot but I'm having some issues with your mod, mainly the furances not being upgradable. I spent the last few hour trying to figure out the issue and have yet to find the solution. I've uninstall everything thermal related checked for the most recent versions of all the files, reinstalled them and still having the same issue. There are no receips for any of the upgraded machine frames just the basic. Any help would be much appreciated. I'm really new to modded mincraft so I would be surprised if its something so simpl.

**Comment by legodude17** [comment]
You are opening this in the wrong spot, but I can still help you. You want to craft a basic machine and then a upgrade kit and then right click the machine with the upgrade kit. If you need any more help then open a new issue.

**Comment by KingLemming** [comment]
This process is underway and @Tonius is progressing on it pretty steadily. :)

Feel free to PR as you like, but the issue can be safely closed at this point I feel.

**Comment by legodude17** [comment]
Alright then, thanks for this!
