### ISSUE TITLE
My server crashes at start with the latest updates

### ISSUE THREAD

**Issue by Hund** [CoFH/Feedback#166]
I updated all three mods as we were told to.

* CoFHCore-[1.7.10]3.0.0RC1-190.jar
* ThermalExpansion-[1.7.10]4.0.0RC1-126.jar
* ThermalFoundation-[1.7.10]1.0.0RC2-54.jar

I'm running a custom FTB Infinity (1.1.0) server on my server. 

* [crash-2015-02-23_12.21.51-server.txt](http://pastebin.com/weWR8kam)
* [Mods list](http://pastebin.com/K4zLTSfh)

I hope I didnt miss anything. :)

**Comment by KingLemming** [comment]
Update ProjectRed. He's doing something that he really shouldn't be doing. But I think he's fixed it.

**Comment by Hund** [comment]
Thank you! Thats solved the problem.
