### ISSUE TITLE
Thermal Foundation Shovels unable to convert Grass into Path Blocks.

### ISSUE THREAD

**Issue by mallrat208** [CoFH/Feedback#166]
Thermal Foundation version 1.10.2-2.0.5.81
COFH Core version 1.10.2-4.1.1.156

Thermal Foundation shovels are unable to be used to convert Grass blocks into Grass Path blocks. Vanilla handles this logic in ItemSpade itself, and since TF uses the custom COFH Tool classes (or at least did last I saw), this functionality is missing.

**Comment by KingLemming** [comment]
Hrm...this will create a problem with Redstone Arsenal. Unsure how to handle that.

**Comment by Serifina** [comment]
Toggle creating farmland or paths by sneaking?

**Comment by KingLemming** [comment]
reasonable enough I think, sure
