### ISSUE TITLE
Ender IO support

### ISSUE THREAD

**Issue by Skillotic0703** [CoFH/Feedback#168]
Ender IO compat is not yet implemented. I hope you have plans to add it back like in 1.7.10.

**Comment by KingLemming** [comment]
Please elaborate. I do not know what you are referring to.

**Comment by Skillotic0703** [comment]
In 1.7.10 you could make Ender IO alloys in an induction smelter.

**Comment by bookerthegeek** [comment]
@Skillotic0703 that iirc was added by enderio.

Either way simple enough to script it in.

**Comment by bookerthegeek** [comment]
http://wiki.enderio.com/Alloy_Smelter

**Comment by Skillotic0703** [comment]
Thank you!
