### ISSUE TITLE
[1.10.2] Machines not interacting properly with EnderIO item conduits

### ISSUE THREAD

**Issue by ChaoticTabris** [CoFH/Feedback#169]
I have machines connected to a small network of item conduits from EnderIO but for some reason they don't work reliably. Some machines output to the conduits normally and others don't, the conduits set to extract always can't pull from the machines. I'm playing FTB Beyond, except i removed FTBUtils and updated EnderIO to try to fix the issue, with no success.

Here is a small video showing the issue: https://gfycat.com/LightAridBubblefish

**Comment by KingLemming** [comment]
Title of the video sums it up well I think - "conduit bug." Let EIO know about it, but no other mod is having this issue.

The machines properly expose their slots based on side config. Auto-Output isn't required for conduits to extract, but it shouldn't hurt either.
