### ISSUE TITLE
Redstone Armory Fails After Upgrade

### ISSUE THREAD

**Issue by pamiller3** [CoFH/Feedback#169]
After upgrading CoFH Core to 3.0.0RC2-196, Minefactory Reloaded to 2.8.0RC7-71, Thermal Foundation to 1.0.0RC3-56, Thermal Expansion to 4.0.0RC2-129 and Redstone Armory to 1.1.0RC2-43 it shows the following crash errors:

http://paste.ee/p/yhu6x

**Comment by KingLemming** [comment]
Okay. That isn't our mod. Redstone Armory is someone else. We're Redstone Arsenal.

**Comment by pamiller3** [comment]
Good grief....ok I mixed them up, I upgraded Redstone Aresenal and wrote Armory every time...I apologize.  Am I still eligible for assistance even though I have shown signs of dyslexia.

**Comment by pamiller3** [comment]
Alright I see that in my logs it was Armory that was throwing the error not Arsenal.  I am VERY sorry for this, but....it still doesn't load with the upgraded mods.  Here is the new error: http://paste.ee/p/VC52z

**Comment by skyboy** [comment]
Update project red
