### ISSUE TITLE
Itemstacks being saved as ComparableItemStacks do not save NBT

### ISSUE THREAD

**Issue by Drullkus** [CoFH/Feedback#17]
I'm running into this problem while trying to put together the Thermal Smeltery mod. I investigated why all tinker's Tool parts melted into iron despite their original materials. It appears that when you convert the input Itemstacks into the Magma Crucible recipe map, it will convert the IS into the ComparableItemStack which does not store NBT.

What I would love to see is the Magma Crucible being able to handle Itemstacks that have NBT.

**Comment by Drullkus** [comment]
Related: #20

**Comment by KingLemming** [comment]
That's the entire point of ComparableItemStacks...otherwise they'd just be ItemStacks.

There's not really a good fix here TBH. That class exists to make hashing quick.

**Comment by KingLemming** [comment]
Hrm...Java 8 apparently changed hashing, so ComparableItemStack may not need to exist for much longer.

**Comment by KingLemming** [comment]
Okay. I redid the logic on the backend a bit. The Crucible will now support NBT.
