### ISSUE TITLE
[1.10.2] Thermal Expansion - Cache doesn't show storageinfo by mouseover

### ISSUE THREAD

**Issue by Hodel1** [CoFH/Feedback#170]
Hi,

when you use a Cache for example Cobblestone, you will see the levelbar, but you don't see a storageinformation by mouseover.

In 1.7.10 you had seen on mouseover, a storageinformation like "15/10000 Items"

Tested in FTB Beyond 1.5.3, TE 5.0.4.90

**Comment by legodude17** [comment]
Does this occur with only CoFHCore, TF and TE?

**Comment by KingLemming** [comment]
This was never the case. That was WAILA having auto-integration.

**Comment by Hodel1** [comment]
If the display was shown because we had the Waila Mod, then it issnt a Issue! ;)

**Comment by KingLemming** [comment]
I agree, it's not an issue.
