### ISSUE TITLE
server crashing with updated mods

### ISSUE THREAD

**Issue by chanzie** [CoFH/Feedback#171]
have checked to make sure was not on alpha on any of the mods before posting this and all are the release from 7 hours ago.
http://http://pastebin.com/f89kuqMw 
this is the crash I am getting 

am checking project red status right now to make sure its on par since I saw it in the log on error as well

**Comment by Biofusionz** [comment]
Update project red

**Comment by chanzie** [comment]
updating project red to most recent version did fix it
