### ISSUE TITLE
[1.10.2] Thermal Expansion - Cache - Mining Tool Pickaxe

### ISSUE THREAD

**Issue by Hodel1** [CoFH/Feedback#171]
Hi,

the Cache shows that you remove it with a pickaxe, which is the wrong way.
it is possible to show instead an Pickaxe, a Wrench?

You will not be able to break the cache with a pickaxe ;)

Tested in FTB Beyond 1.5.3, TE 5.0.4.90

Greets

**Comment by KingLemming** [comment]
No, the Cache doesn't say that at all. You have a mod which is looking at the material of the Cache (Iron) and making a tremendous assumption.

Also, you can't exactly break it with the Wrench either. You can only dismantle. Either way, I'm not in charge of that, that's on your mouseover mod.
