### ISSUE TITLE
Crash with Basic Filter

### ISSUE THREAD

**Issue by Reyls** [CoFH/Feedback#172]
every cofh mod latest version (from curse)

https://gist.github.com/Reyls/9c65d189ba242fc42b07
while trying to place a basic filter on disconnected duct
see picture http://imgur.com/npHZWq1

**Comment by KingLemming** [comment]
Does the same thing happen with other blocks? I can't seem to replicate this.

**Comment by Reyls** [comment]
ok, the type of block doesnt matter. I tested stirling generator, mana fluxfield, pulverizer and energy cell.
the problem occurs with all types of filters, servos and retrievers
it crash while I place and after reboot of minecraft the filter/servo/etc is succesfully placed on the duct
If I place the filter/etc on the duct at first and after that I disconnect the duct, everything is fine.
it only happens with fluctuating itemduct. normal itemducts and impulse itemducts works correctly.
btw, why connect a itemduct to a energy cell?

**Comment by KingLemming** [comment]
I still can't replicate this at all.

**Comment by Reyls** [comment]
okay, next try
this causes a crash: http://imgur.com/24IwFfO,pjrkPGV#1
this doesnt cause a crash: http://imgur.com/24IwFfO,pjrkPGV#0

**Comment by KingLemming** [comment]
Nice catch.
