### ISSUE TITLE
Fluxduct transition causing measurable ghost current load

### ISSUE THREAD

**Issue by Freekmine** [CoFH/Feedback#173]
When transitioning from a higher tier powered fluxduct to a lower tier fluxduct, a ghost RF/t load is imposed on both ducts. This is measurable with the multimeter.

**Comment by KingLemming** [comment]
It's not a ghost load, the ducts have to transfer power.

**Comment by dallenwilson** [comment]
I've seen this happen as well, when there is no load on the system and nowhere to transfer power to.

Just reproduced in creative single player: a creative energy cell in to a single cyro-stabilized fluxduct in to two sections of resonent fluxduct in to two sections of redstone fluxduct with no machine on the end. The meter displays +8000RF/-8000RF on the redstone and resonent sections, but 0/0 on the cyro.

I tried it again with a full leadstone energy cell and it showed no droppage of power, so there is clearly no transfer taking place, but the multimeter does not reflect that.

**Comment by Freekmine** [comment]
![2017-04-22_13 36 22](https://cloud.githubusercontent.com/assets/27895041/25307591/e209e284-2760-11e7-9a13-1da4c576b2e0.png)

Energy Cell > Redstone Energy Fluxduct > Hardened Fluxduct.

No other ducts or machines connected.
5 Sec. Avg. In/Out: +800RF / -800RF
The Energy Cell level does not diminish
