### ISSUE TITLE
using the latest builds on curse harden glass cannot be crafted

### ISSUE THREAD

**Issue by kurokuno** [CoFH/Feedback#174]
only 1 input slot is working on the alloy smelter the right side the other input slot is ignoring clicking shift clicking hoppers and pipes and yet it allows say sand or slag in there for ores

edit: it only seems to be ones crafted after i updated as someone else on my servers is working just fine but any new ones we craft fail to allow the input

double edit: breaking the one that was working and putting it back down stops it allowing input allso

**Comment by KingLemming** [comment]
Do you have a texture pack?

I'm guessing that you can't see the brand new button on the smelter that locks input. If enabled, it only allows for sand, rich slag, pyrotheum, and cinnabar to be in the left slot.

So either you didn't try it or you didn't see it. But it does still work, I promise you. :)

**Comment by kurokuno** [comment]
sorry king yeah i was using jaded's pack ty for the fast response

**Comment by KingLemming** [comment]
No need to apologize - my guess was just that you literally didn't see it. :)
