### ISSUE TITLE
Multimeter Bug

### ISSUE THREAD

**Issue by Freekmine** [CoFH/Feedback#174]
Multimeter reading an in/out RF load with no load present

![2017-04-22_13 36 22](https://cloud.githubusercontent.com/assets/27895041/25308530/93942444-2773-11e7-9b7d-32fb4f1bc816.png)

Energy Cell > Redstone Energy Fluxduct > Hardened Fluxduct.

No other ducts or machines connected.
5 Sec. Avg. In/Out: +800RF / -800RF
The Energy Cell level does not diminish

**Comment by KingLemming** [comment]
You already added this to the last invalid issue. Please do not do this.
