### ISSUE TITLE
[Thermal Dynamics] Compatibility with Storage Drawers ore dictionary conversions

### ISSUE THREAD

**Issue by jaquadro** [CoFH/Feedback#175]
Thermal dynamics will not recognize a destination slot in my inventory when the exact item/block type does not match the type that it is trying to deliver.

Storage Drawers performs implicit ore dictionary conversion on item input.  When TD calls canInsertItem() on the inventory, the inventory will do the ore dictionary check and return true when the conversion is valid.  I suspect TD is then comparing the stack that gets returned from the subsequent call to getStackInSlot(), seeing they don't match, and not trusting what the inventory just told it.

For the record, this issue also applies to JABBA barrels, as JABBA does the same implicit input conversions.

**Comment by KingLemming** [comment]
You are correct, because for every inventory that does something clever like this, there are about 10 that are poorly coded and we absolutely shouldn't trust them.

I'll see what we can do.

**Comment by KingLemming** [comment]
After looking into it, there's absolutely no reasonable way to do this on our end. Inventories that have this sort of behavior can be coded in such a fashion where it still works.

Honestly, if Jabba doesn't work with it then I need to go talk with Mobius. There's no reason the OreDict conversion can't happen during the balance operation.

**Comment by jaquadro** [comment]
I would be very interested if you do talk to Mobius and what falls out from that.  If JABBA worked, I would go reference his code.  But reading through now, we essentially arrived at the same implementation for that feature.

From my perspective, there is no strong link between a call to canInsertItem and a corresponding call to getStackInSlot. If by balance operation you're referring to re-syncing the inventory with the input or output item stacks we handed out, I don't see how we could be absolutely sure what kind of item stack to give you in the first place.

**Comment by KingLemming** [comment]
There is a strong link though. Here's why:

The duct has to merge the ItemStacks. That's part of insert. If the ItemStacks aren't the same, we *cannot* do it.

Implicit conversions are bad for a lot of reasons. This is one of them. The Minecraft inventory system is handled by slots, and we are limited to that.

Jabba only fails in the corner case where the barrel is within 1 stack from being full. Otherwise it works, as the duct inserts into an empty slot, and the balance operation handles the conversion.

**Comment by jaquadro** [comment]
I see that the null stack return is a key difference.  I would argue that it's even worse to be inconsistent, so I don't see much incentive to make a change that would get it working 80% of the time.

The conversion criticisms are fair, and the third big one is that the ore dictionary itself is not always predictable or correct.  For that and performance, I'm considering making it opt-in via upgrade.  If it wasn't genuinely useful though, I wouldn't have added it in the first place.

I don't think the equivalence checks themselves can be moved to the balance operation.  TD might be well-behaved if an inventory always returns true in a call to canInsertItem, but that's not an assumption I could make for all transport systems.

Thanks for investigating anyhow.  I see some potential creative solutions to this problem.
