### ISSUE TITLE
Redstone Arsenal tool charging

### ISSUE THREAD

**Issue by jubalearly** [CoFH/Feedback#175]
Pickaxe and a few other tools(did not test every item) will not charge in TE Infuser.  They will charge in EIO capacitor bank, actually additions energizer and rftools powercell.

**Comment by KingLemming** [comment]
Cannot replicate this at all, and there is literally absolutely no reason that this would ever be the case. Please provide a modlist and a video.

**Comment by jubalearly** [comment]
I can duplicate error about 50% of time.  Charge RA tool partially in another mod's charger then try and insert it into TE Infuser it tends to skip out of charging slot straight into orange output slot.  Putting it back in to blue slot again works about 90% of the time.  When it happens it goes on for 4-5 tools then does not reoccur for awhile.  It happened most frequently when partially charged item had a charge ending in __800 and ___400

Probably just a glitch with my mods, weird though.

**Comment by KingLemming** [comment]
Hrm...I'm worried this may be an issue with capabilities and how mods are using them. Caps really aren't good for items.

**Comment by KingLemming** [comment]
Still couldn't make this happen. Going to chalk it up to caps and it being entirely out of our control.
