### ISSUE TITLE
[Request] Rubber recipes

### ISSUE THREAD

**Issue by Skillotic0703** [CoFH/Feedback#176]
In 1.7.10 this 
![image](https://cloud.githubusercontent.com/assets/12701912/25315357/076c1756-2854-11e7-98bf-feec178d9e26.png) and this 
![image](https://cloud.githubusercontent.com/assets/12701912/25315363/211b816e-2854-11e7-9178-b204e539943f.png) were possible. Could you add this back in 1.10.2 to support Tech Reborn and IC2 rubber please?

**Comment by KingLemming** [comment]
This probably isn't happening since I'm adding a rubber fluid and alternative ways to get rubber. But I'll think about it.

**Comment by Skillotic0703** [comment]
Is Tar the alternative rubber?

**Comment by KingLemming** [comment]
No, I'm pondering adding Latex to certain trees.

**Comment by Skillotic0703** [comment]
Ok thx!

**Comment by KingLemming** [comment]
Closing this down since the port status of MFR is unknown, and it's kind of irrelevant. Latex may still happen, if I find a use for rubber.
