### ISSUE TITLE
TD - Strange GUI behavior

### ISSUE THREAD

**Issue by kennymoto** [CoFH/Feedback#177]
I can only get this to happen in 1 tall morph, after right clicking on retriever with an empty hand at an angle, if I click on an item or empty slot in the top right four spots in my inventory it will replace the item with a piece of my armor. From left to right helm, chest, leggings, boots. If I click on an item in the bottom row of my inventory all items in slots above it will disappear. Sometimes it will duplicate items and sometimes items will disappear and not come back after closing the GUI. I have see weird behavior with morph while trying to click the correct item. But I have not seen an issue after a GUI opens. Thanks!
![2015-02-24_00 48 43](https://cloud.githubusercontent.com/assets/11152546/6344648/f3ed1286-bbc0-11e4-92da-1499089bd682.png)
![2015-02-24_00 53 08](https://cloud.githubusercontent.com/assets/11152546/6344654/fe5e615c-bbc0-11e4-8132-fefe9b4e152d.png)
![2015-02-24_00 53 12](https://cloud.githubusercontent.com/assets/11152546/6344651/fe5d2634-bbc0-11e4-8270-7adc5552b1c7.png)
![2015-02-24_00 53 23](https://cloud.githubusercontent.com/assets/11152546/6344650/fe5ca696-bbc0-11e4-8d91-3e2d103249b5.png)
![2015-02-24_00 52 58](https://cloud.githubusercontent.com/assets/11152546/6344653/fe5e392a-bbc0-11e4-8cc6-509803a6beab.png)
![2015-02-24_00 53 03](https://cloud.githubusercontent.com/assets/11152546/6344652/fe5e1774-bbc0-11e4-91e4-3cb5cd64a069.png)

**Comment by skyboy** [comment]
This is an issue related to morph and the altered player height.

**Comment by KingLemming** [comment]
This is definitely a Morph issue.
