### ISSUE TITLE
Crash ThermalFoundation-[1.7.10]1.0.0RC3-56

### ISSUE THREAD

**Issue by frank89722** [CoFH/Feedback#178]
When I update it game was crash:
http://pastebin.com/QrfCaudr
After I delete all addon:
http://pastebin.com/HDSEkX6x
It crash too Orz
※I was update all CoFH's mods

**Comment by skyboy** [comment]
The first crash is caused by flora, the second crash is caused by project red.

**Comment by Shielded** [comment]
I also get a crash with TF on newest version etc:

http://pastebin.com/BCxLQt2n

**Comment by KingLemming** [comment]
It's Ex Astris. The vast majority of these startup crashes are easy to determine if you just read the log. ;)
