### ISSUE TITLE
[1.10.2] Redstone Arsenal - Omniwrench - Not compatible with AE2

### ISSUE THREAD

**Issue by Hodel1** [CoFH/Feedback#178]
Hi,

the Omni-Wrench from Redstone Arsenal seems not longer working on Applied Energistics 2.

Tested in FTB Beyond 1.5.3 with RedstoneArsenal 2.0.3.29 and AE2 rv4-alpha-11 and CoFH Core 4.1.1.156

Edit: Works not on a Quantum Storage Unit too.

**Comment by KingLemming** [comment]
That's on them. They no longer support the wrench.
