### ISSUE TITLE
Natural Smite bonus for silver tools

### ISSUE THREAD

**Issue by Adaptivity** [CoFH/Feedback#179]
https://github.com/SlimeKnights/TinkersConstruct/issues/1424

**Comment by KingLemming** [comment]
Looking into this, there's no way we can have a material property go over to Tcon via IMC and keep any sort of bonus like that.

Do you just mean the TF tools?

**Comment by Adaptivity** [comment]
There are Smite modifier exists in Tcon. Are you sure you can't add it to silver tools on creation? I thought it's possible to add it if not, just close it.

**Comment by KingLemming** [comment]
Talked with boni. Isn't possible through IMC. Sorry.

**Comment by KingLemming** [comment]
boni apparently doesn't know the TiCon codebase at all. Reopening for a reminder.

**Comment by KingLemming** [comment]
Nah, turns out TiCon needs a revamp for this to be possible. :(
