### ISSUE TITLE
Autonomous activator not very random

### ISSUE THREAD

**Issue by Zaflis** [CoFH/Feedback#18]
Using autonomous activator in "randomly use items" mode is not very random. Only some of the item slots are used.

Test scenario is all 9 slots filled with ores, and a second autonomous activator with a pickaxe. Entirely depends on the pickaxe's mining speed on which ore-slots will be picked.

Being a programmer i think the current implementation is time-based and has a previously indexed random list to go through. Problem is that the activator doesn't account to failure on placing an item. It propably shouldn't proceed to next random index if it can't place the block. Alternatively use built in random function to get a truly random value. I doubt it would cause any lag for the game since the activation delay is so long.

Also you can get best test result by using all 9 slots of same ores. If the mining speeds differ per ores, it may hop the slots slightly differently each time, but can still miss some of them.

**Comment by KingLemming** [comment]
You are incorrect. It is not time based. We know what Math.random is. ;)

Even so, that doesn't mean that it's reliable. We'll look into it.

**Comment by Entoarox** [comment]
@KingLemming Probably a case of 'real random doesnt feel random', so you'd have to make it somewhat less random to make it feel more random.

**Comment by Zaflis** [comment]
I cut the item feeding conduit for a test, so here's it after digging a few coal ores: http://imgur.com/KxrXBul
Top 3 rows were completely left alone while 1 stack is at 5.

**Comment by Entoarox** [comment]
that is a completely possible situation, real random means that it may randomly choose to skip those stacks completely.

**Comment by Zaflis** [comment]
It's not actually skipping them i believe. It may have a more perfect scatter that goes through all the slots, but the timing given by how many ticks it takes to mine 1 ore away determines if using that (and next few) slot succeeds or fails.

If you mean real random, a human random, it would be more even distribution. Because given time and filling those bottom slots, top row would still NEVER be picked. It's very biased random in action. But whatever, we are possibly meaning the same thing all the time :) I just don't know how you've made it exactly so i don't have much to say on the topic here.

**Comment by KingLemming** [comment]
Could you test this with the new releases please? I think we got it.

**Comment by Zaflis** [comment]
It seems pretty good now for both random and round robin, gj.
