### ISSUE TITLE
[REQUEST] UBC Compatablilty

### ISSUE THREAD

**Issue by bookerthegeek** [CoFH/Feedback#18]
Hello Good sirs! I am requesting compatibility with another mod for 1.10

* Mod Name:
  * [Underground Biome Constructs for 1.10](https://github.com/Zeno410/UndergroundBiomesConstructs1.10)
* Reason:
  * When generating your ores in the world while using UBC, they look out of place and having them match the surrounding strata would be amazingly immersive.
  * Would be wonderful if this also worked while using your World generation Configs.
* [API](https://github.com/Zeno410/UndergroundBiomesConstructs1.10/blob/master/src/main/java/exterminatorjeff/undergroundbiomes/api/common/UBOresRegistry.java) for registering with UBC

My (non-java coding) understanding is that UBC does not generate any ores by itself, just replaces your ores as they generate so that it matches the surrounding strata. This allows you to continue to control your own ore generation, while making the ores match their surroundings.

Thank you for considering my request.

p.s. I do understand their was a [mod](https://github.com/mallrat208/UBC-Ore-Registrar/issues/22) that added all of this compatibility by itself, sadly it is not updated from 1.7.10, although I did post there inquiring about an update.

<details><summary>Snippet from the MCF thread on adding compatibility</summary><p>
There are two ways to request your ores get "UB'd". Both require a simple one-line call, wrapped in a try-catch so it runs if UBC is installed and just gets skipped if it's not there. 

The first method is to actually request the operation. This has to be done during your pre-init and *after* UBC has run its pre-init.
```
try {
 UBAPIHook.ubAPIHook.ubOreTexturizer.
 setupUBOre(<em>oreBlock</em>, <em>overlayTextureName, FMLPreInitializationEvent);
} catch (Exception e) {
 // do nothing; Underground Biomes not installed
}</em>
```

The second method is to send a request to UBC. UBC stores this in a queue and runs it during its own pre-init. This has to be done *before* UBC runs its own pre-init.
```
try {
 UBAPIHook.ubAPIHook.ubOreTexturizer.
 requestUBOreSetup(<em>oreBlock</em>, <em>overlayTextureName);
} catch (Exception e) {
 // log e.toString() somehow so you will know if you called this at the wrong time.
 // UB will throw UBOreTexturizer.BlocksAreAlreadySet (a runtime exception) if you do
}</em>
```
</p></details>

**Comment by Thiana** [comment]
UBC Ore Registrar has been updated to 1.10 now, and supports TF ores.

**Comment by KingLemming** [comment]
So basically, has this been handled?

**Comment by bookerthegeek** [comment]
Yes, it is now being handled as the author of the compatibility mod has decided to update to 1.10

Thank you for the wonderful mod guys. :)
