### ISSUE TITLE
Crashlog: Tesselating block model (RenderDynamo.java:181)

### ISSUE THREAD

**Issue by 7eggert** [CoFH/Feedback#180]
I plaxed a workbench next to a dynamo

A copy of the world and a zip of all my mods would be available on request

PS, removing the offending workbench next to the dynamo using mcedit did help

[crash-2017-04-30_06.06.45-client.txt](https://github.com/CoFH/Feedback/files/966550/crash-2017-04-30_06.06.45-client.txt)

**Comment by KingLemming** [comment]
How about just a modlist for starters?

**Comment by 7eggert** [comment]
There is a modlist in the crashlog, too, but I guess a list of the jar files is better:

1.10-chunkedgeindicator-1.3.jar
Advanced-Inventory-Mod-1.10.2.jar
AutoPackager-Mod-1.10.2.jar
BaseMetals_1.10.2-2.4.0.11.jar
Better HUD by NukeDuck [1.9.4][1.3.8].jar
BetterFoliage-MC1.10.2-2.1.4.jar
BiomesOPlenty-1.10.2-5.0.0.2162-universal.jar
CXLibrary-1.10.2.jar
Chameleon-1.10-2.2.2.jar
CoFHCore-1.10.2-4.1.1.156-universal.jar
CodeChickenCore-1.10.2-2.4.1.102-universal.jar
CodeChickenLib-1.10.2-2.5.8.255-universal.jar
ColossalChests-1.10.2-1.5.0.jar
CraftingCraft_1.10.2-4.1.9.jar
CyclopsCore-1.9.4-0.10.0.jar
DrCyanosLootableBodies_1.10.2-2.2.0.jar
ElectricAdvantage_1.10.2-2.2.0.jar
Ender-Compass-Mod-1.10.2.jar
EnderBags-Mod-1.10.2.jar
EnderCore-1.10.2-0.4.1.65-beta.jar
EnderIO-1.10.2-3.1.183.jar
EnderStorage-1.10.2-2.2.1.106-universal.jar
Flat-Bedrock-Mod-1.10.2.jar
Inventory-Tweaks-Mod-1.10.2.jar-
LLOverlayReloaded-1.1.1-mc[1.9-1.11].jar
Mineralogy_1.10.2-3.2.0.jar
OptiFine_1.10.2_HD_U_D7.jar
OreSpawn_1.10.2-1.1.0.jar
PowerAdvantage_1.10.2-2.3.0.jar
ProgressiveAutomation-1.10.2-1.7.4.jar
QuantumFlux-Mod-1.10.2.jar
Railcraft_1.10.2-10.1.1.jar
RebornCore-1.10.2-2.13.5.136-universal.jar
Redstone-Paste-Mod-1.10.2.jar
SteamAdvantage_1.10.2-2.2.0.jar
StorageDrawers-1.10.2-3.7.1.jar
ThermalExpansion-1.10.2-5.0.4.90-universal.jar
ThermalFoundation-1.10.2-2.0.5.81-universal.jar
VillageInfoSSP-1.9.4-2.1.jar
VoxelMap-Mod-1.10.2.litemod
Waila-1.7.0-B3_1.9.4.jar
Waypoints-Mod-1.9.4.jar
bdlib-1.12.4.24-mc1.10.2.jar
compatlayer-1.10-0.2.5.jar
cyberware-1.9.4-1.10.2-beta-0.2.7.jar
endertanks-1.10.0-1.4.12.jar
fluxducts-mc1.9.4-1.0.4.jar
hopperducts-mc1.9.4-1.4.8.jar
jei_1.10.2-3.14.7.417.jar
mcjtylib-1.1x-2.3.11.jar
mod_worldeditcui_1.10_00_lite_mc1.10.litemod
pressure-1.3.1.20-mc1.10.2.jar
rftools-1.1x-6.00.jar
shetiphiancore-1.10.0-3.3.8.jar
worldedit-forge-mc1.10.2-6.1.4-dist.jar

**Comment by KingLemming** [comment]
After looking over this, it'll only happen if the state is null, in which case something else screwed up and you have other problems. But they aren't caused by this mod, sorry. :/

**Comment by 7eggert** [comment]
That's very possible, but you're the only one who could give diagnostic output and/or prevent the crash. It happened with a vanilla workbench! That is, I didn't look into the code, I just hope you can either skip something or throw a better error message.

**Comment by legodude17** [comment]
My 2-cents: Optifine might have caused this.
