### ISSUE TITLE
Glowstone Illuminator

### ISSUE THREAD

**Issue by evenas98** [CoFH/Feedback#181]
I can't right click with dye to color the glowstone illuminator
using latest versions

**Comment by KingLemming** [comment]
Correct. Sneak-use a multimeter on them instead.

**Comment by evenas98** [comment]
Okay, cool, maybe a tooltip for that?

**Comment by evenas98** [comment]
on the Glowstone Illuminator

**Comment by KingLemming** [comment]
Done. :)

**Comment by evenas98** [comment]
Thanks :)
