### ISSUE TITLE
blitz's play Ambience sound effects instead of normal "wheezing"

### ISSUE THREAD

**Issue by macks2008** [CoFH/Feedback#181]
no idea what's causing it, but for some reason when I'm near a blitz, Minecraft starts playing "ambience" sound effects on the Hostile Mob sound channel. Someone on your IRC at #thermalexpansion on EsperNet said Minecraft is probably being fed a null sound event.

**Comment by KingLemming** [comment]
Just looked at the code. No nulls.

Really not sure what to tell you here.

**Comment by macks2008** [comment]
when I say ambience, I mean vanilla's ambient sounds. Instead of playing the usual wheezing, asthma-like sounds that the elemental makes, blitz's are making these sounds: http://minecraft.gamepedia.com/Ambience

**Comment by KingLemming** [comment]
Yeah that doesn't seem to be the case at all. They wheeze properly for me.

You using a resource pack?

**Comment by macks2008** [comment]
no. I do have a lot of month loaded however, and should probably try updating CoFH mods... I'll give ya the list and let you know if updating helps.

**Comment by macks2008** [comment]
@KingLemming it looks like I'm already using the latest version. You don't seem to be updating much... It's from over a month ago.

**Comment by KingLemming** [comment]
Yeah, there haven't been any major issues, and we're doing a content cycle.

There hasn't been a need for releases, especially when a lot of the issues that get reported are things we straight up can't replicate and don't hear from any of the other couple hundred thousand people playing the mod.

**Comment by macks2008** [comment]
an issue reported by only one person is still an issue, although I understand what you mean. If you can't replicate a bug, it becomes down right near-impossible to determine what's causing it. I'll try to provide any information I can to help you replicate it. Would you like an instance of the server backend and modpack? Maybe that combined with a breakpoint every time a blitz would make a sound can help you track it down.

**Comment by macks2008** [comment]
actually, better yet, let me see if it's reproducible in singleplayer. That'll eliminate the server from the equation

**Comment by macks2008** [comment]
weird. Things work on single player just fine. Makes me wonder if SpongeForge is to blame. Come to think of it, I probably should've mentioned that first. Even though it's a seemingly client-side problem, the server does have some influence on sounds (case in point, /playsound)

**Comment by macks2008** [comment]
@KingLemming

**Comment by KingLemming** [comment]
Yes...yes you should have mentioned that you're not using a supported modding API.

It's handled through resource packs, in the sounds.json file.

The specific sound group is "mob_blizz_ambient"

**Comment by Notawallplan** [comment]
I can actually confirm that this happens to me too. When fighting a blizz/blitz/balaz with the subtitles on, it is definitively ambient noise. This happens in both singleplayer and multiplayer.

**Comment by macks2008** [comment]
@KingLemming well it is technically still Minecraft Forge loading everything, isn't it? Then again, I remember there being something about SpongeForge needing to transform certain classes before Forge gets to loading them... However, it seems I'm not the only one having trouble. Our dear friend @Notawallplan here (if I'm understanding) is having this issue in single player too! as such, it seems SpongeForge is ultimately unnecessary to bring forth the bug. Nota, can you provide game logs, etc.? also, just to be sure, you did mean that the elementals are making the same sounds that you normally here in caves, i.e. ["ambience"/"cave sounds"](http://minecraft.gamepedia.com/Ambience), right?

**Comment by Notawallplan** [comment]
Yep. No logs since I can't trace worth a damn, but I can confirm.

**Comment by macks2008** [comment]
@KingLemming interestingly, while the elemental mobs themselves make the "Eerie noise" (ambience)  sound effect, the corresponding Vengeance Spirits (which are added by EvilCraft and spawn after a mob dies) play the right sound effect, i.e. Blitz Vengeance Spirits still make the wheezing sound effect (albeit slightly lower to make them seem ghostlike)

**Comment by KingLemming** [comment]
Well, I've kept trying, and same deal - I absolutely cannot get this to happen. Sounds are correct and on the correct channels.

**Comment by Notawallplan** [comment]
Try downloading your mods, create a server, and join it. This is a problem
- although a bit wtfy - that actually persists.

**Comment by KingLemming** [comment]
I've already done that. Doesn't happen. :/

**Comment by Notawallplan** [comment]
It may be something to do with Optifine and/or FoamFix.

**Comment by covers1624** [comment]
Probably, try and find the mot minimal mod list that this issue occurs with.

**Comment by macks2008** [comment]
whatever's going on here, it happens with only ThermalFoundation, CoFHcore, and SpongeForge installed. I just tested it with an otherwise completely  clean server. @KingLemming try adding spongeforge. That seems to be the trigger for the weirdness.

**Comment by KingLemming** [comment]
So it's Spongeforge's fault then. Easy enough.

**Comment by macks2008** [comment]
@KingLemming well it's apparently also something you're doing different from other mods that add unique sounds... Vampirism's blood-sucking sound plays fine, for instance. I'm not saying you should fix it, but I am curious what it is you do different that might cause this?

**Comment by KingLemming** [comment]
We're not doing anything different to my knowledge.

**Comment by thiakil** [comment]
@KingLemming I found a similar issue with Mekanism which occurred only on dedi-servers; the cause was that the SoundEvents weren't registered with the GameRegistry. It had no relation to Sponge in that case.

**Comment by KingLemming** [comment]
Well, there is some relation, because I can't make this happen on a vanilla server at all. ;)

It's an extra step that can be taken, but the way MC works - json should be enough - Forge adds the registry system and it's absolutely not required for sounds to function.

**Comment by thiakil** [comment]
It had no relation to Sponge in _Mekanism's_ case.

Standard Minecraft SoundEvents are even registered with the Forge registry in SoundEvent.java.

**Comment by KingLemming** [comment]
Yes - Forge is performing that registration, but there's not a strict need for it.

**Comment by thiakil** [comment]
And how exactly do you expect the client to know about the sound when the server send it?

**Comment by KingLemming** [comment]
The server isn't supposed to send those sounds. They are ambient mob noises and are strictly client only.

I've already added code to register them, but this isn't actually an issue on a Forge server. Sponge is making some assumptions.

**Comment by thiakil** [comment]
It most definitely DOES send from the server. Entities are ticked server side, and via World.playSound it gets sent to clients.

**Comment by thiakil** [comment]
![20170607043609](https://user-images.githubusercontent.com/1788847/26862459-fe617384-4b7d-11e7-9cf4-0f1c1fc6ad78.png)
This is very much plain Forge Server. 12.18.3.2239

**Comment by KingLemming** [comment]
Yes. And that call does not require ANY registration whatsoever. getAmbientSound() does not return a null in the release version of TF.

**Comment by thiakil** [comment]
playSound -> World.playSound -> eventListeners.x->playSoundToAllNearExcept -> this.mcServer.getPlayerList().sendToAllNearExcept ->new SPacketSoundEffect -> writePacketData -> SoundEvent.REGISTRY.getIDForObject(this.sound)

**Comment by KingLemming** [comment]
Fair enough, though that still doesn't actually explain why it works on a standard Forge server without issue.

**Comment by macks2008** [comment]
registering the sound event worked like a charm. Thank you! Now I don't hear eerie noises (or at least not Ambience) when your asthmatic air mobs try to breathe 😛

**Comment by macks2008** [comment]
@KingLemming the above was mainly directed at you and/or whoever made the commit to register the event. Basically, "thanks! It's working now! *insert joke demonstrating my appreciation*"
I'm not even sure if I should be pinging you with the issue resolved, but then again you can never truly get enough "thank you"s can you?
