### ISSUE TITLE
World Generation Docs for CoFH Core

### ISSUE THREAD

**Issue by scottosx** [CoFH/Feedback#182]
In the 1.10.2 version the tree structure and property names have changed somewhat. The old documentation is very thorough but not fully applicable.

I am especially having trouble with the Decoration template and generator for surface features (plants,etc). In lieu of a doc update an example of how to build the json file for this would be very helpful.

**Comment by KingLemming** [comment]
Duplicate of #165.

**Comment by scottosx** [comment]
Sorry for the dup entry. I should have searched. I have spent hours though pouring through the source and trying countless combinations and decoration does not work for me. Maybe a quick example, please?

**Comment by KingLemming** [comment]
Poke around in the Twitch channel and @skyboy can probably help you.
