### ISSUE TITLE
Liquid Transposer & Drums

### ISSUE THREAD

**Issue by Maxcloud** [CoFH/Feedback#183]
1) Insert a bucket of liquid.
2) Insert 64 Drums.
3) Remove the first drum.
4) The machine moves 1 drum over.
5) There is no liquid left in the machine to add to the drum.
6) Crash.

Stacktrace:
http://pastebin.com/4sEg9CEn

Mods:
CoFHCore-[1.7.10]3.0.0RC2-195
extrautilities-1.2.1
ThermalExpansion-[1.7.10]4.0.0RC2-129
ThermalFoundation-[1.7.10]1.0.0RC3-56

**Comment by FirKys** [comment]
Okay. how i can find this BugEnity and delete him?

**Comment by zhs2** [comment]
It seems this same exact crash happens solely with attempting to fill a liquid container from an empty transposer, such as any spare portable tank.
