### ISSUE TITLE
Grinder crashing server

### ISSUE THREAD

**Issue by Overlord1974** [CoFH/Feedback#184]
I've recently updated all of my team cofh mods to the latest versions and each time I load up my single player map it crashes whenever the grinder goes to kill a mob that I have spawned through the auto-spawner in my mob farm.

I have included a pastebin link to the crash report that I get

http://pastebin.com/6Z66gpxs

**Comment by skyboy** [comment]
Don't use alphas. Use the release versions available on [curse](http://curse.com).
