### ISSUE TITLE
[Suggestion] Fluid storing machines

### ISSUE THREAD

**Issue by Skillotic0703** [CoFH/Feedback#185]
Sometimes it is easier for automation to have smaller tanks inside machines so I have an idea. Every fluid storing machine should have an interface (like the one to configure I/O sides) in which you can put a portable tank. The quantity of fluid storage of the machine becomes the one of the tank. And if you put a bucket, the machine stores 1000 mB. That seems more logical to me because when you craft for example a fluid transposer, you use one bucket for the crafting but then you can store more buckets and when you upgrade it, you store even more buckets.

I know that this isn't your priority but I just wanted to share a fun idea.
Thank you for all your work!

**Comment by KingLemming** [comment]
It's something I've wanted to do as an augment, but I don't want to clutter things with another tab and a bunch of special case logic.

**Comment by Skillotic0703** [comment]
If you want to do this the simplest way possible, it would just be an option that allows you to set the exact amount of fluid you want to store as long as the amount is inferior to the base amount of the machine. I think that's a bad idea to do it in an augment form because you already have a bunch of augments and you only have max 4 slots for upgrades.

**Comment by KingLemming** [comment]
After giving this a bit of thought, it's just not something I'm interested in doing, sorry.
