### ISSUE TITLE
[Thermal Dynamics] Round-robin mode behaves strangely when disabled/invalid connections are present

### ISSUE THREAD

**Issue by jaromero** [CoFH/Feedback#185]
I don't know if this behaviour is intended (and if so, how is it supposed to work exactly), but basically, if there's an itemduct line with a servo on round robin mode, at least two valid inventories, and at least one "end" where a) the connection into another valid inventory is disabled with the wrench, or b) the connected block is not an inventory (e.g. TE energy cells), then the servo distributes the items it pulls unevenly across the valid inventories connected.

I apologize for the massive amount of images, but I'm not entirely sure in what way it's behaving. In all these test layouts I tested with 50 mushrooms inside the chest, and the servo in round robin mode (blacklist/whitelist empty) pulling 1 item at a time. My expectation is to have 25 mushrooms in each of the two empty non-locked JABBA barrels connected to the ducts.

This is my first test. The target barrels are the first two, from left to right. The third barrel is locked to sandstone (which, in theory, prevents anything else from being accepted). The fourth barrel accepts anything, but the connection has been disabled with a crescent hammer. Finally a TE Redstone Energy Cell which for some reason plugs into the ducts, but never ever accepts items. The target barrels ended up with 20 and 30 mushrooms, instead of 25 each.
![2015-02-24_17 33 04](https://cloud.githubusercontent.com/assets/794031/6362188/f8a8b034-bc4f-11e4-882a-afd7c5aa227b.png)

Second test. Added a couple more energy cells. Same result; 20 and 30 instead of 25 each.
![2015-02-24_17 34 34](https://cloud.githubusercontent.com/assets/794031/6362244/9bf6b9d4-bc50-11e4-9a2a-1caf9daff30d.png)

Moving the left cell to the right side doesn't affect things.
![2015-02-24_17 36 07](https://cloud.githubusercontent.com/assets/794031/6362249/afce7a5a-bc50-11e4-9c4b-9dcc6fc6244a.png)

The obvious scenario, only two barrels, nothing else along the ducts. 25 each.
![2015-02-24_17 37 50](https://cloud.githubusercontent.com/assets/794031/6362253/c387c7d6-bc50-11e4-8243-5bde6091b5cc.png)

Add an invalid destination, or add a valid one and then unplug it, and round robin breaks. 17 and 33, instead of 25 each.
![2015-02-24_17 39 02](https://cloud.githubusercontent.com/assets/794031/6362259/d8b68b4c-bc50-11e4-9fe5-d6ac4e084a64.png)
![2015-02-24_17 40 43](https://cloud.githubusercontent.com/assets/794031/6362262/de081ade-bc50-11e4-9bfc-3fe75aef24ca.png)

I suspected a weird corner case of having an odd number of connections, but this happens with an even amount as well.
![2015-02-24_17 42 16](https://cloud.githubusercontent.com/assets/794031/6362280/16a5b5cc-bc51-11e4-95a5-6e6f3e9d3788.png)

However, when both barrels are on the same side of the first fork, it works as expected.
![2015-02-24_17 43 46](https://cloud.githubusercontent.com/assets/794031/6362282/204f829c-bc51-11e4-891e-315a57ebb26e.png)

... until a third invalid connection is added at the first fork as well.
![2015-02-24_17 45 10](https://cloud.githubusercontent.com/assets/794031/6362293/352c4d1c-bc51-11e4-9059-a51cd0e9bf3d.png)

Swapping the first barrel and the energy cell somehow makes the other barrel further down the line receive more mushrooms instead.
![2015-02-24_17 46 33](https://cloud.githubusercontent.com/assets/794031/6362307/4fda9ff6-bc51-11e4-8a1b-8e838427a92c.png)

And mirroring the previous test makes the furthest chest receive an even larger fraction. The north-east rule might be influencing things a bit here (in all these screenshots, the player is facing south)
![2015-02-24_17 47 56](https://cloud.githubusercontent.com/assets/794031/6362318/706e42ea-bc51-11e4-817d-52cc1a7c6220.png)

Removing one energy cell makes it very slightly less lopsided.
![2015-02-24_17 49 20](https://cloud.githubusercontent.com/assets/794031/6362348/ce38b81a-bc51-11e4-8929-22e46253516a.png)

But with only two valid destinations, even if the lengths are asymmetrical, it works as expected.
![2015-02-24_17 50 55](https://cloud.githubusercontent.com/assets/794031/6362360/e2090bce-bc51-11e4-91f9-72d5c395efb4.png)

Finally, a much more complicated setup with 5 barrels, 3 energy cells and 2 disabled connections (around the central barrel), results in 6, 20, 12, 6 and 6 mushrooms in the barrels (instead of each barrel having 10 mushrooms).
![2015-02-24_17 54 55](https://cloud.githubusercontent.com/assets/794031/6362364/f2c290a2-bc51-11e4-9758-041fc0d80f40.png)

**Full list of mods: https://gist.github.com/jaromero/d71a62af31d6fd57aed0**

**CoFH mods:**
 
* CoFHCore-[1.7.10]3.0.0RC2-195.jar
* CoFHLib-[1.7.10]1.0.0B9-118.jar
* MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar
* NetherOres-[1.7.10]2.3.0RC4-4.jar
* RedstoneArsenal-[1.7.10]1.1.0RC2-43.jar
* ThermalDynamics-[1.7.10]1.0.0RC2-77.jar
* ThermalExpansion-[1.7.10]4.0.0RC2-129.jar
* ThermalFoundation-[1.7.10]1.0.0RC3-56.jar

**Comment by jaromero** [comment]
Two more tests, this time with all valid inventories:

Symmetrical, 5 barrels, each barrel receives 10 as expected.
![2015-02-24_18 34 49](https://cloud.githubusercontent.com/assets/794031/6362599/5786e5f4-bc54-11e4-8aa7-4a0631c68721.png)

5 barrels again, but not symmetrical. 17, 16, 6, 6 and 5.
![2015-02-24_18 37 58](https://cloud.githubusercontent.com/assets/794031/6362618/926233fe-bc54-11e4-989a-2af2e6b69cec.png)

And a slightly different layout. 17, 8, 8, 8 and 9.
![2015-02-24_18 36 28](https://cloud.githubusercontent.com/assets/794031/6362606/6b6d0864-bc54-11e4-9da5-1c04f549c37b.png)

Finally... 12, 6, 6, 13 and 13.
![2015-02-24_18 41 56](https://cloud.githubusercontent.com/assets/794031/6362628/de6259fa-bc54-11e4-8386-5065ca0a04d5.png)

I have no clue anymore but weird asymmetrical branches seem to confuse the servo a lot.

**Comment by KingLemming** [comment]
Partially fixed. Still a couple of corner cases.
