### ISSUE TITLE
Redstone Arsenal: ClassCastException breaking leaves with Flux-Infused OmniWrench

### ISSUE THREAD

**Issue by mallrat208** [CoFH/Feedback#186]
Forge Version: 12.18.3.2281
COFHCore: 4.1.1.156
Redstone Arsenal: 2.0.3.29 
Mod List: https://gist.github.com/mallrat208/85ad7818cd47139328c58ff08461cd93
Crash Report: https://gist.github.com/mallrat208/7d7446eb30dd05b2926d9e8912141dd1

We had a player harvest leaves using the Flux-Infused OmniWrench earlier which resulted ClassCastException. Luckily said crash won't keep the server down and is easily avoided by not using the wrench as shears for the time being. I don't know if it was being used on vanilla leaves or Forestry leaves as both are possible.

Vaygrim/CoopLife#24

**Comment by KingLemming** [comment]
Forge changed things and didn't even update the Javadoc. Lovely...
