### ISSUE TITLE
TD Enhancement - Firewall with filters?

### ISSUE THREAD

**Issue by kennymoto** [CoFH/Feedback#186]
So I placed a filter on two joining ducts - one side became the filter and the other side turned into a connection. So even though it made the connection - items will not go through - even with an empty black list. Wouldn't it be cool though to place a filter on each side of joining ducts and have a firewall? See images below. Again thanks for the great ducts!!!
![2015-02-24_18 05 31](https://cloud.githubusercontent.com/assets/11152546/6362478/19ae3b98-bc53-11e4-9d0a-5c490ad67d61.png)
![2015-02-24_18 05 50](https://cloud.githubusercontent.com/assets/11152546/6362477/19ae5664-bc53-11e4-947b-441b4a53151c.png)

**Comment by kennymoto** [comment]
If not possible, maybe not allow filters, servos or retrievers to be placed on ducts without a connection to an inventory....

**Comment by KingLemming** [comment]
After thinking about it, we just don't see this as feasible, and limiting attachment placement isn't something we'd like to do either.
