### ISSUE TITLE
[Bug]Steam Dynamos not accepting Steam from an outside source

### ISSUE THREAD

**Issue by rtr468** [CoFH/Feedback#187]
I'm using this modpack: https://mods.curse.com/modpacks/minecraft/253632-ftb-presents-direwolf20-1-10
on version 1.9.1. I am having an issue where if I try to pump railcraft and industrial craft steam into the steam dynamo with and without the Augment: Turbine Conversion installed, and no matter what methods I use, none will go into the input buffer. graphically all pipes I can find in the pack appear to connect but whenever I try to input steam it doesn't actually fill the buffer. it would seem to me that it is trying to put steam into the coolant slot, and as it isn't a valid coolant, it doesn't input at all. If this is true Open Computers may be able to, but I am not experienced in it, so I cannot test it. Feel free to take this down if it isn't your problem. Thank you for your time.

**Comment by KingLemming** [comment]
The issue here is that everyone is creating their own steam. That used to not be a thing.

There's not a great solution here to be honest. I'll see what I can do.

**Comment by rtr468** [comment]
thermal expansion(in this pack) didnt have its own version of steam, and it has an unknown texture like the railcraft steam. It might just have been a pack config but I figured its worth mentioning

**Comment by KingLemming** [comment]
Yeah, that's happening because you have a mod really screwing things up. TE definitely has its own version of Steam.
