### ISSUE TITLE
[Thermal Dynamics] Server freezes completely when a connection is disabled and round-robin servos are being used

### ISSUE THREAD

**Issue by jaromero** [CoFH/Feedback#187]
This might also be related to #185 in that it involves a servo in round-robin mode.

Basically, if there's a servo pulling items out in round robin mode (with a single destination inventory) and that end connection is disabled, the server just freezes completely. The player can walk around but can't open inventories or machines, can't interact with the world, etc. and if on a remote server, it kicks the player with a "Server timed out" error and is unable to reconnect until the server is killed and restarted.

The right servo is set to round-robin mode, pulling 1 item at a time. The thing at the end of the duct is an Extra Utilities trash can, just to serve as an item sink. (The thing just off to the right of the screen is just a vanilla contraption that toggles a piston constantly, just so I can easily tell when the server freezes)

![2015-02-24_23 56 21](https://cloud.githubusercontent.com/assets/794031/6365719/d8747ef6-bc81-11e4-8686-b6c27c31e0c3.png)

The problem happens when disabling the connection into the trash can with a wrench.

No crash log, because the server never actually crashes, it just keeps using CPU time until manually killed.

**Full list of mods: https://gist.github.com/jaromero/d71a62af31d6fd57aed0**

**CoFH mods:**
 
* CoFHCore-[1.7.10]3.0.0RC2-195.jar
* CoFHLib-[1.7.10]1.0.0B9-118.jar
* MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar
* NetherOres-[1.7.10]2.3.0RC4-4.jar
* RedstoneArsenal-[1.7.10]1.1.0RC2-43.jar
* ThermalDynamics-[1.7.10]1.0.0RC2-77.jar
* ThermalExpansion-[1.7.10]4.0.0RC2-129.jar
* ThermalFoundation-[1.7.10]1.0.0RC3-56.jar

**Comment by KingLemming** [comment]
This one is actually fixed. :)

**Comment by AngelRyder93** [comment]
I have also this issue with this configuration, with one itemtube in "round robin" mode and three outputs. Game freezes when items enter the output block (TE Dynamo).

I have also only the @jaromero mods installed.

**Comment by chrissiemcc** [comment]
Yes.. and as he said it is fixed for the next release :)
