### ISSUE TITLE
Blazing Pyrotheum Registering As A Fuel In Tinkers' Construct Smelteries.

### ISSUE THREAD

**Issue by Gamemaster2198** [CoFH/Feedback#188]
So I was messing around in creative with a modpack with a few additional mods I added in myself (Tinkers' Construct already in the pack) and Blazing Pyrotheum got registered as a fuel in smelteries, I reported this to the Tinkers' Construct Form and said it might be your mod problem so yeah. Here are the images:
![2017-05-07_16 00 56](https://cloud.githubusercontent.com/assets/28332429/25838253/11c6625c-3447-11e7-9794-3ee1a2b1d0cd.png)
![2017-05-07_16 00 59](https://cloud.githubusercontent.com/assets/28332429/25838254/13f75c02-3447-11e7-9776-31fb2115f9cb.png)
![capture](https://cloud.githubusercontent.com/assets/28332429/25838453/f50e1fbe-3447-11e7-86a5-207fdbdc4a34.JPG)
![capture1](https://cloud.githubusercontent.com/assets/28332429/25838456/f9d32990-3447-11e7-989c-372c6f4f960d.JPG)

**Comment by Gamemaster2198** [comment]
Also, it does not want to melt down anything, FYI its in 1.10.2

**Comment by KingLemming** [comment]
We don't register it with them. I don't know who does, but it isn't us.

It's possible that Tinker's scans all available fluids and adds "hot" ones automatically, but that would be on them to fix.

**Comment by Gamemaster2198** [comment]
alright, then i shall report this back to the tinkers' form
