### ISSUE TITLE
Crash Report [NullPointerException: Ticking block entity]

### ISSUE THREAD

**Issue by FirKys** [CoFH/Feedback#188]
http://pastebin.com/Ux1UXgjh
version:
ThermalExpansion-[1.7.10]4.0.0RC2-129.jar
ThermalFoundation-[1.7.10]1.0.0RC3-56.jar
CoFHCore-[1.7.10]3.0.0RC2-195.jar

**Comment by MinecraftDevin** [comment]
Other people have been having this issue in irc..wonderful.

**Comment by MinecraftDevin** [comment]
Actually... This might be a cauldron issue..

**Comment by KingLemming** [comment]
Duplicate of #183
