### ISSUE TITLE
Manually filling tanks handles stackable containers incorrectly

### ISSUE THREAD

**Issue by squeek502** [CoFH/Feedback#189]
CoFHLib's FluidHelper.fillHandlerWithContainer/fillContainerFromHandler methods (which TE's BlockTank call in onBlockActivated) don't handle stacked items properly, and therefore will do things like replace a stack of 64 filled containers with a single empty container when manually filling a tank.

Relevant code:
 * https://github.com/CoFH/CoFHLib/blob/master/src/main/java/cofh/lib/util/helpers/FluidHelper.java#L160
 * https://github.com/CoFH/CoFHLib/blob/master/src/main/java/cofh/lib/util/helpers/ItemHelper.java#L175-L185

I also noticed this, which seems to have a similar purpose to the FluidHelper methods, but it looks like it handles this situation better:
 * https://github.com/CoFH/CoFHLib/blob/master/src/main/java/cofh/lib/util/UtilLiquidMover.java

**Comment by KingLemming** [comment]
Part of the problem here is that stackable reusable containers shouldn't exist. Still, we should probably handle this abomination gracefully.

**Comment by squeek502** [comment]
> stackable reusable containers shouldn't exist.

Why would that be? I don't want to fill a players inventory with an inconsequential item just because it has the arbitrary distinction of being filled with a liquid.

**Comment by KingLemming** [comment]
It's not arbitrary. Vanilla doesn't implement them and unless it's been patched by Forge, doesn't handle them correctly.

**Comment by squeek502** [comment]
In which does Forge not handle them correctly? And why wouldn't that be considered a bug in Forge? There are an infinite number of things that Vanilla doesn't implement.

By the way, the fix seems like it'd be as simple as calling `consumeItem(ItemStack, EntityPlayer)` rather than `consumeItem(ItemStack)` in `FluidHelper.fillHandlerWithContainer` (https://github.com/CoFH/CoFHLib/blob/master/src/main/java/cofh/lib/util/helpers/FluidHelper.java#L160)

**Comment by KingLemming** [comment]
By the way, the stackable reusable container thing refers to full containers. Buckets stack to 16. Full buckets do not. Vanilla could not gracefully handle full buckets in crafting if they were stacked. That's what I was referring to.

And yes, this change has been made.
