### ISSUE TITLE
If I installed Residence Plugin,I can put the fluid on the private residence.

### ISSUE THREAD

**Issue by Damnie** [CoFH/Feedback#189]
My Res Plugin issue : https://github.com/Zrips/Residence/issues/46
If I installed RedProtect Plugin, it's OK.
https://www.spigotmc.org/resources/redprotect-for-all-versions-anti-grief-server-protection.15841/

So how to reslove this problem.
Thanks!

**Comment by KingLemming** [comment]
So Residence Plugin does not work, RedProtect does?

...this sounds like you already know what the problem is.

**Comment by Damnie** [comment]
Eh...It's KCauldron or Thermos. They are bukkit.
If you change the rules about the fluid,can you fix it?
It seems that I can only use the RedProtect in my server :)

**Comment by covers1624** [comment]
This entirely boils down to how THEY handle fluids, they are a plugin, not a mod, they don't know how mods work and don't support foges fluid stuff because its a Plugin not a mod. Locking.
