### ISSUE TITLE
[MinefactoryReloaded 2.0.0RC6] and [Thaumcraft 4.2.1.4] Mana Beans Placed in Wrong Position

### ISSUE THREAD

**Issue by Simon-Bitdiddle** [CoFH/Feedback#19]
Thaumcraft 4.2.1 and higher place mana beans under logs as opposed to on the sides, Minefactory Planter attempts to place them on the sides of logs, often causing the beans to disappear.

**Comment by skyboy** [comment]
Duplicates https://github.com/skyboy/MineFactoryReloaded/issues/358
