### ISSUE TITLE
I/O on the front side (thermal expansion)

### ISSUE THREAD

**Issue by LordMZTE** [CoFH/Feedback#190]
I have testet around a bit with computercraft and openperipheral and using the openperipheral command
rotateBlock() and changing the I/O while the block was rotating made the front to an Input:
![2017-05-16_17 39 07](https://cloud.githubusercontent.com/assets/28735087/26114856/aefac604-3a5e-11e7-949e-16685f254d00.png)

i am using thermal expansion 4.1.3-246
modlist: https://pastebin.com/LfTeMvax

**Comment by KingLemming** [comment]
Yeah, you have another mod directly interfacing with our stuff in a way that it isn't meant to. That's on them, not us.

Don't do that.
