### ISSUE TITLE
Sometimes Autonomous Activator can't attack

### ISSUE THREAD

**Issue by caxerx** [CoFH/Feedback#191]
I am using ThermalExpansion 4.0.0RC2-129

![2015-02-25_16 29 01](https://cloud.githubusercontent.com/assets/9213146/6367243/686ac02c-bd0b-11e4-9ab4-e6604fe0d63b.png)

it only kill few mobs and then stop

**Comment by KingLemming** [comment]
Thank you! This is the first actual report we've ever gotten of it. It's normally just been hearsay.

Could you include a screenshot of the Activator GUI please?

**Comment by caxerx** [comment]
![2015-02-25_18 40 54](https://cloud.githubusercontent.com/assets/9213146/6369083/dbbae1da-bd1d-11e4-8b22-e8e2e5e300bb.png)

**Comment by KingLemming** [comment]
What is that sword? I can't replicate it with a Diamond Sword.

**Comment by Andre-Maartens** [comment]
Looks like a sanguinite cleaver from extratic + metallurgy 4 and tcon

**Comment by caxerx** [comment]
![2015-02-25_22 31 12](https://cloud.githubusercontent.com/assets/9213146/6372292/096622e6-bd3e-11e4-839c-5c40e7c86684.png)
![2015-02-25_22 31 24](https://cloud.githubusercontent.com/assets/9213146/6372294/0b5ec378-bd3e-11e4-9683-46a412079ab0.png)

same issue when i change to diamond sword

**Comment by evenas98** [comment]
i can comfirm the issue!
http://imgur.com/f0czmza,qE77sVz

**Comment by evenas98** [comment]
using diamond sword, won't attack me or villager

**Comment by evenas98** [comment]
had that issue for a long time

**Comment by KingLemming** [comment]
Are you *also* using a conveyor?

**Comment by skyboy** [comment]
Fixed. Railcraft heat blocks are in front of the activators.

**Comment by evenas98** [comment]
no i am not, but looks like skyboy fixed it :)
