### ISSUE TITLE
Rosin not registering as a fuel source anymore

### ISSUE THREAD

**Issue by Emerald-Chicken** [CoFH/Feedback#191]
When since I updated my FTB Beyond server from 1.5.3 to 1.6.1, something weird happened. Suddenly, it doesn't see Rosin as a proper fuel source anymore. It no longer works as intended in any mod that allows you to use it as a smelting reagent or convert it to power (including TE's own Steam Dynamo). The same thing seems to have happened with Coke Coal from TE.

What's wrong here?

**Comment by ktole1999** [comment]
did the mod update in the pack?

**Comment by Emerald-Chicken** [comment]
No. Both FTB Beyond 1.5.3 and 1.6.1 use version 2.0.5.81 for Thermal Foundation and 5.0.4.90 for Thermal Expansion. Which is exactly why this is such a weird bug.

Especially since other fuels still seem to work fine: it's just the Thermal Foundation ones.

**Comment by ktole1999** [comment]
then something else changed it. maybe one of the other mods dropped support. you would have to research changelog for mods that updated.

**Comment by Emerald-Chicken** [comment]
I'm fairly certain it does not have to do with any other mod. Once again: I can use solid fuels from other mods just fine, even within TE's very own Steam Dynamo. Doesn't it strike you as odd that TE machines accept fuels from other mods, but not from itself?

**Comment by KingLemming** [comment]
Known. Duplicate. Fixed in dev.

**Comment by ktole1999** [comment]
so the TE is reacting to a change in another mod?

**Comment by KingLemming** [comment]
No, it's a thing with Forge and the underlying item map.
