### ISSUE TITLE
[Suggestion] Deprecated nether ores

### ISSUE THREAD

**Issue by Skillotic0703** [CoFH/Feedback#192]
When you update nether ores for 1.10.2 you should replace some deprecated ores like nikolite ore by their modern counterpart (electrotine from project red in this case).

**Comment by Tahakk** [comment]
As this is not issue you should try to ask on COFH Twitch (Curse) Group chat, you may get answer there 👍

**Comment by KingLemming** [comment]
I imagine that will happen, yes.
