### ISSUE TITLE
Mob Farm Crash

### ISSUE THREAD

**Issue by Raminence** [CoFH/Feedback#192]
http://pastebin.com/0SvvL3c7

The game keeps crashing when I'm close to my blaze farm. I'm suspecting it might be MFR that causes it with the grinder. It started doing it when I updated all the CoFH  mods and the project red ones.
I have a the mod list here: https://docs.google.com/spreadsheets/d/1_4SJex0JAJMZ4W5M4UMUOZvCercpNLSvhnQcow73Ng8/edit?usp=sharing

**Comment by skyboy** [comment]
There's no indication MFR is involved at all; can you provide more details?

**Comment by Raminence** [comment]
I have some screenshots of the farm here:
![2015-02-25_18 52 00](https://cloud.githubusercontent.com/assets/11182468/6376631/6be64136-bd1f-11e4-8811-cfa7dd813837.png)
![2015-02-25_15 59 26](https://cloud.githubusercontent.com/assets/11182468/6376437/0ff94568-bd1e-11e4-93c4-111dd18f5d07.png)
![2015-02-25_16 00 08](https://cloud.githubusercontent.com/assets/11182468/6376438/0ffc05be-bd1e-11e4-8bf5-91d86462996e.png)
![2015-02-25_18 43 20](https://cloud.githubusercontent.com/assets/11182468/6376456/3848217e-bd1e-11e4-93f0-97c8c709bbe8.png)

I can't really think of anything else, it's the conveyor belts but other than that it's just a regular minecraft spawner. I haven't been able to replicate it with either.

**Comment by skyboy** [comment]
The crash references Tcon glass panes, yet I don't see those in your farm anywhere? Is something else crashing?

**Comment by Raminence** [comment]
Ok, I figured it out. The crash happens when a mob gets killed inside a glass pane, I tested with both TC and vanilla ones.

![2015-02-25_19 22 44](https://cloud.githubusercontent.com/assets/11182468/6377347/ccad25e4-bd23-11e4-894f-f887da4f5d5a.png)

**Comment by skyboy** [comment]
Fixed by https://github.com/CoFH/CoFHCore/commit/9c9beb7565351e28a1115e472d7a222bf7af1d73
