### ISSUE TITLE
Water wheels apparently deliver way too much power to Cryo-Stabilized Ducts

### ISSUE THREAD

**Issue by Sailren** [CoFH/Feedback#193]
just look at this pic: http://abload.de/img/2015-02-25_19.05.05l2u3l.png

the water wheels are supposed to deliver 5.000 rf/t xD

**Comment by Wolfseverest93** [comment]
@Sailren what mod are those beautiful rf generating water wheels from?

**Comment by Sailren** [comment]
additional buildcraft objects -> https://github.com/da3dsoul/Additional-Buildcraft-Objects/releases

**Comment by Sailren** [comment]
if these ducts are working perfectly, then i have found a huge alternative solution to big reactors

**Comment by KingLemming** [comment]
1) This isn't super descriptive
2) The ducts have been rewritten, but I'm pretty sure the issue here is actually the water wheels.

Either way we should be good in the next release.

**Comment by Sailren** [comment]
i will see what will happen regarding abo, i posted a report on abo github, lets w8 for a response ;-)

**Comment by Sailren** [comment]
what i also found out, do u know the mod buildcraft utilities? he adds the electric engines from the old bc2ic crossover mod from silentdeth, the industrial engine produces 250 rf/t normally, when i conenct one of those with the cryo duct the ender io cell gets a input of 500 rf/t from one engine, is it intended that the duct doubles the rf/t input

**Comment by KingLemming** [comment]
It's not intended and that doesn't happen with anything coded properly. I've put some stupid-catching code in, however.

**Comment by Sailren** [comment]
hehe, cool :)
