### ISSUE TITLE
Suggestion for better Redstone Arsenal Compat

### ISSUE THREAD

**Issue by Wolfseverest93** [CoFH/Feedback#194]
it seems the person(s) responsible for making Draconic Evolution figured out a really effective method for making the RF powered tools weapons and armor have absolutely full compatibility with every other mod in minecraft without bugs, and with the ability to be used in conjunction with Battlegear2. The tools and armor have no endurance, and instead use RF in place of it. I noticed the Redstone Arsenal tools and armor all still have endurance levels (which i have sometimes encountered bugs with) and also have some compatibility issues with other mods including Battlegear2. So my suggestion is perhaps to request to use some of brandon3055's code from Draconic Evolution to make the Redstone Arsenal stuff more compatible and practically bug-less.

Just in case, this should make it easier. Heres the site link to TolkienCraft (which is why he made the mod): TolkienCraft.com and this is the minecraft forum: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/2093099-draconic-evolution-1-0-0e as well as the curseforge: http://minecraft.curseforge.com/mc-mods/223565-draconic-evolution

I don't know his email though, but I think he wouldn't be too hard to contact through one of those methods. Please and thanks, this would be amazing (no more accidentally breaking my flux equipment by having certain items in my inventory~)

**Comment by KingLemming** [comment]
Okay, so I took a look at his code, and well basically he's copied mine - which is the correct way to handle IEnergyContainerItems. :P

So, please elaborate on the bugs you're experiencing. Because he's doing exactly what I do with one minor change which is display only. If Battlegear2 is NOT treating that change as display only, then the bug is in Battlegear2.

His tools still have endurance levels, he's just not showing the bar when they're full on energy.

**Comment by Wolfseverest93** [comment]
Waila shows that they don't, but on to answer your question, I've had times when flux tools wear down their actual endurance level instead of the rf amount, and eventually break (an issue i brought up before, but since it doesnt post anything to the log, i couldnt do anything more than describe the error and the most common situations it occurred in). Also, his tools can be equipped in battlegear slots whereas only the flux bow and flux crescent hammer can be equipped in battlegear slots (meaning the tools likely dont reach to their respective vanilla tool identification string for some reason). I thought his code was totally different given how much smoother the tools work >.> might be just a few differences, but then again those differences actually save a lot of trouble down the road.
Basically this is a request for smoother compatibility with other mods such as bg2 and quiverbow because this happens to be the only flux tool mod i have an issue with while using those two mods in conjunction, flux trinkets works perfectly, and all of draconic evolution works perfectly (even the bows works while using a quiver instead of tripping up and taking away its endurance if any exists, whereas the flux bow uses endurance if theres a quiver anywhere in my inventory, eventually breaking) the only ones I really care about having the ability to equip in bg2 slots are the sword and battle wrench (i would have the wrench reach the vanilla sword string so bg2 considers it a weapon, or whatever respective string it needs to reach).

also, it's only happened to me once and I've yet to have it happen again, but at some point a flux pickaxe broke while mining, if that happens again i'll make note of what was in the inventory and around my player aside vanilla items because just about anything could have been the object of affection.

as for whether bg2 treats the change as display only, it does, but for some reason as i said, the tools can't be set into bg2 slots.

sorry if i seem jumbled here, been drafting one of my mod requests for a while now...

**Comment by KingLemming** [comment]
Okay so I can put some workarounds in place to address this, but they're actually pretty ugly kludges. BattleGear 2 is doing things that Minecraft really isn't meant to do, so that ain't cool.

As far as whatever slot logic he's doing...he's not relying on instanceof checks, so frankly I don't know what the issue is.

instanceof is the correct way to do it; my *guess* is that he's relying on the HashMap of tags, which is like 38 kinds of wrong. You may want to send this over to BG2 and suggest that he change his slots.

**Comment by KingLemming** [comment]
Just commenting again now since a recent issue cropped up as a result of this. Vanilla *requires* things to have a max damage level to enchant them.

Given the choice between supporting vanilla and supporting a mod that is clearly doing something wrong, I have to choose vanilla, sorry.
