### ISSUE TITLE
SidedInvWrapper used when facing is null

### ISSUE THREAD

**Issue by SquidDev** [CoFH/Feedback#195]
In Thermal Expansion, `TileInventory` wraps the current tile entity in a `SidedInvWrapper` when getting an `IItemHandler` capability ([see here](https://github.com/TheCBProject/ThermalExpansion/blob/master/src/main/java/cofh/thermalexpansion/block/TileInventory.java#L275)). However, when the `facing` parameter is null, the `SidedInvWrapper` is constructed with a null side. Normally this doesn't cause issues, but the hash code implementation expects side to be non-null ([see here](https://github.com/MinecraftForge/MinecraftForge/blob/1.11.x/src/main/java/net/minecraftforge/items/wrapper/SidedInvWrapper.java#L66)).

When `facing` is null, a normal `InvWrapper` should probably be returned instead.

Tested under:
 - CodeChickenLib 2.5.8.255
 - CoFHCore  4.1.1.156
 - Thermal Expansion 5.0.4.90
 - Thermal Foundation 2.0.5.81
 - Forge 12.18.3.2185.

Thanks!

**Comment by covers1624** [comment]
I though i made that change ages ago.. Maybe it got nuked somehow..

**Comment by SquidDev** [comment]
Great. Thanks!
