### ISSUE TITLE
[Request] TechReborn wrench support

### ISSUE THREAD

**Issue by Skillotic0703** [CoFH/Feedback#196]
I don't know why but you can't use the crescent hammer or the omniwrench on TechReborn machines (they have their own wrench so it shouldn't very difficult to add compatibility). Maybe you could collaborate with TechReborn devs to find a solution.

**Comment by KingLemming** [comment]
The Omniwrench *might* get compatibility. Crescent Hammer is a no though - it's a mess supporting APIs which are implemented as poorly as IC2/TechReborn.

Seriously, TechReborn had an excellent opportunity to drop the terrible IC2 wrench API and didn't. Poor design decision on their part.

**Comment by Skillotic0703** [comment]
I think that TechReborn is a very messy mod anyway but I really like the fact that it's a remake of old IC2+gregtech, it really feels like one mod. I feel like it got better over time and I hope that the devs will be able to get a fully functionnal release someday.

**Comment by KingLemming** [comment]
Looked into this as part of 1.10.2 finalization. It's not something I can do unfortunately - Tech Reborn doesn't keep their IWrenchable class in an API package. So basically no other mods can safely support it.

You might want to open an issue up with them. :)

**Comment by Skillotic0703** [comment]
They don't want to add new "features" for versions before 1.10.2 but that's not a problem as you're going to update soon to 1.11.2. I just want you to tell them how they should implement their wrench.
