### ISSUE TITLE
Wrench

### ISSUE THREAD

**Issue by evenas98** [CoFH/Feedback#197]
No Thermal Expansion/Arsenal/Armory wrench can wrench the AE cables, worked before the latest updates

**Comment by evenas98** [comment]
EnderIO's Wrench works.

**Comment by KingLemming** [comment]
No wrench?

Did you try the Crescent Hammer?

This is an issue on AE's end as they support IC2's interface. They're fixing it.

**Comment by evenas98** [comment]
Yes I tried the crescent hammer, well I didn't update ae
