### ISSUE TITLE
Crash on FTB Beyond

### ISSUE THREAD

**Issue by SquirrelWithABanana** [CoFH/Feedback#199]
When trying to launch FTB Beyond on Curse/Twitch, after finishing step 2/7 it crashes, the crash report is attached below
[crash-2017-05-20_14.38.18-client.txt](https://github.com/CoFH/Feedback/files/1016464/crash-2017-05-20_14.38.18-client.txt)
When launching it on the FTB Launcher, it runs perfectly fine, yet I have friends who can launch it on Curse/Twitch. I have tried updating and disabling mods, and found only one solution, disabling COFH Core. There is one problem, COFH Core handles oregen for the pack. I have no idea who else to report this to, so I am reporting it here because COFH Core is stated in the crash report.

The pack is completely unedited as well.
Edit: The Pack version is 1.6.1, had the problem on 1.6.0 as well.

**Comment by KingLemming** [comment]
You'll have to talk to FTB about this. It's not on us, sorry.
