### ISSUE TITLE
[Thermal Dynamics] Itemducts on round-robin skip the 2nd available inventory

### ISSUE THREAD

**Issue by chrissiemcc** [CoFH/Feedback#199]
Check this out:

![image](https://cloud.githubusercontent.com/assets/11199454/6384650/5d9fbff2-bd57-11e4-9b07-c6a1a7aa5a5c.png)

**Comment by chrissiemcc** [comment]
It also sends twice as many to the first inventory in this case, I guess because a second item has left before the first one gets into the first inventory. Perhaps this is connected to the problem?

![image](https://cloud.githubusercontent.com/assets/11199454/6384705/0b04c7e6-bd58-11e4-8275-88cce76a0e51.png)

**Comment by KingLemming** [comment]
Duplicate of #185
