### ISSUE TITLE
Suggestion: Thermal Expansion Flux capacitors as batteries for everything, not just inventory charging.

### ISSUE THREAD

**Issue by mrbaggins** [CoFH/Feedback#2]
As it currently stands, the only use a flux capacitor has is to charge Redstone Arsenal (or a selection of other mods) items in your inventory. Largely, this isn't very necessary, especially when combined with other mods. It's also a crafting ingredient, but that's hardly a "use".

My suggestion is the make it so that there is either a machine or method of using flux capacitors as batteries for networks as well. 

There are two obvious choices. The first would be the energetic infuser being changed to operate like a fluid transposer. It can then either charge the battery, or drain the capacitor, depending on which way it's configured. The other sensible option would be to let energy cells drain capacitors. This way you keep the infuser in use, make it more functional, and I believe it would be straightforward to make energy cells drain from a battery into their own buffer.

The best part of this is that it begins to allow an early game energy transfer mechanic. Currently, a player can manually wrench an energy cell, move it, place it and wait. By opening up flux capacitors, it let's us use ITEMS, not blocks, which makes it much easier to implement and use.

I worked out **I** need this when trying to set up a power station, but without using tesseracts. There is NO way to move power without wireless systems or giant long conduits (which can only be really achieved with 1 or 2 other mods, depending on which versions you're using, Ender IO and maybe Buildcraft). I'd much rather, as a server moderator, see a useful railcart system (or with Railcraft, a train) moving players and power around than a giant pink and grey tube from Ender IO.

Being able to charge a flux capacitor, load it into a cart and ship it off allows for a much more interesting collection of mechanics, with a dedicated "processing" area turning various fuels into RF, then shipping RF back around using either vanilla or mod based methods.

I've tried to make sure I meet the requirements. I hope you feel this would be a beneficial addition. I think it's pretty straightforward, especially as an addition to Energy Cells.

Great mod, great authors, and I hope mentioning Railcraft doesn't stir any hard feelings. :P

Cheers for reading!

**Comment by mrbaggins** [comment]
Huh. I guess I misunderstood the tool tip, as it looked like it was for extracting RF from items, and the wiki on TeamCofh site doesn't list the enervation dynamo either.

Sorry to bother you then. Thanks!

**Comment by KingLemming** [comment]
Yeah the wiki is out of date. Working on that. Capacitors are items, and it's worth revisiting. :) Glad you're getting use out of them!
