### ISSUE TITLE
[Reminder] Update TE security to use UUIDs

### ISSUE THREAD

**Issue by Tonius** [CoFH/Feedback#20]
As far as I know, security is currently based on player usernames. However, Mojang will be enabling name changes in early February, which could cause various problems that are likely self-explanatory.

**Comment by KingLemming** [comment]
Easy fix. We disallow name changes.

**Comment by mechaet** [comment]
That's awesome because I now have a bunch of tesseracts that can't be managed anymore.

**Comment by skyboy** [comment]
This is now implemented.

**Comment by skyboy** [comment]
This is now implemented.
