### ISSUE TITLE
[Suggestion] Re-Add Tesseracts 

### ISSUE THREAD

**Issue by NuclearCreeper** [CoFH/Feedback#200]
I'm sure most of you agree, Tesseracts were probably the most useful block in Thermal Expansion pre 1.10.2 release. Why they were removed is beyond my knowledge. They made everything so much easier.

**Comment by covers1624** [comment]
They are being revamped, this is a topic for the curse or irc channels.

**Comment by KingLemming** [comment]
Tesseracts as they existed were boring. I want to bring them back in a not-boring way.
