### ISSUE TITLE
[Thermal Dynamics] Item dupe glitch

### ISSUE THREAD

**Issue by xirixal** [CoFH/Feedback#201]
I'm currently using FTB Infinity (1.2.0) with TD, TE and COFHCore updated to RC2. I've Found a dupe glitch using Applied Energetics Inscribers and Itemducts/Retrievers

Setup:
1 Chest, 1 AE Inscriber, Impulse Itemduct. Signalum or Resonant Retriever, 2 AE Printed Circuit

Place the chest right the Inscriber and Itemducts on top connecting each other.
Place a Retriever on the itemduct facing the inscriber and set it to disable redstone control.
Place (for example) one "Printed Calculation Circuit" on the inscriber's top slot and one on the chest.
Then, remove the Printed Circuit from the inscriber.
In the chest there should be a full stack of Circuits. If you grab it it may turn into more than 64

**Comment by xirixal** [comment]
![2015-02-26_15 21 18](https://cloud.githubusercontent.com/assets/8078759/6398604/80eadbbc-bdcb-11e4-9403-2ab9b984a6d4.png)
![2015-02-26_15 20 28](https://cloud.githubusercontent.com/assets/8078759/6398608/86fe0eca-bdcb-11e4-95e4-95c4014bbee8.png)

**Comment by Andre-Maartens** [comment]
Copy of #154

**Comment by KingLemming** [comment]
This seems unique to the inscriber. Working on it.

**Comment by rwtema** [comment]
fixed in dev

It's tricky to track down exactly what was happening but it seems to be a side effect of inserting an item into a single accessible slot inventory that has a smaller max stack size than the item being inserted.

Note: Just for clarity, this does not appear to be an AE2 issue.
