### ISSUE TITLE
Suggestion: Custom Recipe Support

### ISSUE THREAD

**Issue by DrDarkfire** [CoFH/Feedback#201]
So. Ender IO has this, They have files that let you make custom recipes for its machines. It doesn't seem that ModTweaker is adding any support for that soon. So if you could possibly do this, or push Jared to make ModTweaker support, Many of us would greatly appreciate it. I know I would love this for the hardcore/hard recipe modpack I am making.

- Dr_Darkfire

**Comment by PanSzelescik** [comment]
Good idea! Especially worth adding support to Compater

**Comment by KingLemming** [comment]
I've already talked with the MT guys, they said this was happening.

**Comment by jaredlll08** [comment]
@KingLemming I assume you didn't get the message I posted in that group?
http://i.blamejared.com/C7jWs.png

**Comment by KingLemming** [comment]
I suppose I did not. Hmm.

**Comment by DrDarkfire** [comment]
Pls change things. I wants the integration :P

**Comment by KingLemming** [comment]
Yeah it's not that simple - the built-in custom recipe parser relies on boolean values being returned.

Yes, there is one, it was active in 1.7.10, removed in 1.10.2 due to new machines and new formats. Not sure how I want to go about it.

**Comment by KingLemming** [comment]
Alright, so I went ahead and did this, but I'll need confirmation from @jaredlll08 that it will work before I close this out.
