### ISSUE TITLE
[enhancement request]Let the machine work faster

### ISSUE THREAD

**Issue by mgdgfbhevdyeh** [CoFH/Feedback#202]
Let's see one example
Exu furnace Fastest speed Processing an item use 0.20s
Processing 64 item use 21s
TE redstone furnace Processing 64 item use 28s(Fastest speed)(add Thermal Mediator
)
ExU than TE furnace furnace RF Province RF

**Comment by KingLemming** [comment]
No, I'm good with it. It's balanced as is.

**Comment by Tahakk** [comment]
Right, if you have problems with speed just build bunch of Furnaces, they are not that expensive.

**Comment by mgdgfbhevdyeh** [comment]
@KingLemming Tesseract canceled at TE5?
Or will it be added in the future?

**Comment by covers1624** [comment]
Tesseract is being revamped. Also this closed issue is no place for that question, That belongs on the Twitch/Curse/IRC chat.
