### ISSUE TITLE
CryoCoil Regulator gives more than advertised

### ISSUE THREAD

**Issue by mconwa01** [CoFH/Feedback#204]
The CryoCoil Regulator (Dynamo Augment, Fuel Efficiency, tier III) gives an 85% boost in base fuel energy, while the tooltip shows 75%. Tested in Steam, Magmatic and Compression Dynamos (though the latter two seem to have an additional inconsistency, which I'll put in another issue.)

Forge 10.13.2.1291
CoFHCore 3.0.0RC2-195
ThermalDynamics 1.0.0RC2-77
ThermalExpansion 4.0.0RC2-129
ThermalFoundation 1.0.0RC3-56

**Comment by KingLemming** [comment]
Fixed in dev. It's a tooltip error. 85% is intended.
