### ISSUE TITLE
Crash on world creation

### ISSUE THREAD

**Issue by vrork** [CoFH/Feedback#206]
https://gist.github.com/vrork/0b84dd26edfffb718e29be8e0c3c127c

**Comment by KingLemming** [comment]
Has absolutely nothing to do with us.

**Comment by vrork** [comment]
How it doesnt? Isnt TE from Cohf? (Its even on the Cohf config folder)

**Comment by KingLemming** [comment]
This is caused by a mod improperly oredicting things. We're simply tripping over the bomb that they are setting.

**Comment by vrork** [comment]
There is one weird thing tough, it was working fine a few hours ago. It stopped working suddenly after i did one change to the copper ore amount and level where it spawn but i alredy reverted (deleted and allowed it  generate the settings again) and no luck
