### ISSUE TITLE
[CoFHCore][World Generation] Replace Vanilla Ores don't work.

### ISSUE THREAD

**Issue by StuardBr** [CoFH/Feedback#206]
Hello!

For some reason the config for "ReplaceVanillaGeneration=true" isn't working. Any number of Cluster size, number of cluster, max and min height made no difference for me. I tried to set all to 0 to test and in the "native" ores (Cooper,Tin, etc.) is working like a charm, but with the vanilla ores no. I have no other mod that replace or change the vanilla ores installed.

I hope you can give me a light about this. Tks anyway :)

Versions:
Minecraft 1.7.10
Forge 10.13.2.1291
CoFHCore 3.0.0RC2-195
ThermalFoundation 1.0.0RC3-56
ThermalExpansion 4.0.0RC2-129
ThermalDynamics 1.0.0RC2-77
MineFactoryReloaded 2.8.0RC7-71

**Comment by KingLemming** [comment]
Just tested. It's working fine.

**Comment by KingLemming** [comment]
Still having this issue? If so, we'll need a full modlist, maybe a savefile, loads of other stuff.

You can test pretty easily on a new world with the /cofh clearblocks command:
https://cofh.github.io/mods/cofh-core/commands.html

**Comment by StuardBr** [comment]
Ok,i will do some tests here and post the results. I'm using the CustonOres now, it's a simple way to control the ores for every world, but i will disable him and test with a fresh minecraft + forge installation and after with all the other mods.

**Comment by KingLemming** [comment]
So, figure anything out? It's working as expected for us.

**Comment by KingLemming** [comment]
Closing this out. We can't make it happen and the feeling is that you may have been using the wrong config.

Be sure you're checking /config/cofh/core/common.cfg to enable replacement.
