### ISSUE TITLE
[1.10] Fluid Transposer clamps output stack min size to 1

### ISSUE THREAD

**Issue by thiakil** [CoFH/Feedback#207]
Extracting from a Consumable FluidHandler in the Transposer does not consume the item, instead giving an item of stackSize 1 (that is technically invalid in some cases).

See `net.minecraftforge.fluids.capability.templates.FluidHandlerItemStack.Consumable` for an example implementation.

**Comment by KingLemming** [comment]
That's not actually what is happening here, no. There's no explicit clamping of any kind.

Not sure how fixable this is.

**Comment by KingLemming** [comment]
I have a mitigation for this, I believe.
