### ISSUE TITLE
Duplicating when breaking with tools

### ISSUE THREAD

**Issue by APolarBaer** [CoFH/Feedback#208]
im not sure if its my pack thats causing it but i cant find anything on it, if it is im sorry for wasting your time but whenever one of my test groups breaks a Thermal Expansion block it duplicates (most notable would be the tanks because those get broken a lot)
i dont really have any errors come up that i can see, if theres a way i can help or you can help me figure out whats causing this i would very much appreciate the help if you can spare the time

**Comment by KingLemming** [comment]
What tools specifically? This isn't something we see with any vanilla, tinkers, or our own. Or really anything at all anywhere.

This is certainly something with your pack, or we'd have heard this one about 10000 times. But I would like to know what mod you have that is causing it.

**Comment by APolarBaer** [comment]
any pickaxe in the pack. >w<

**Comment by APolarBaer** [comment]
might be unrelated but everythings comming up on waila as a redstone furnace
also might help if i specify its 1.10.2

**Comment by APolarBaer** [comment]
i get 1 of the block and the second is a furnace

**Comment by KingLemming** [comment]
Yeah, this isn't on our end. Sorry, dunno what to tell you. That error in the log is caused by ExU2, but shouldn't have anything to do with any sort of pickaxe duplication.

**Comment by covers1624** [comment]
This may be linked to #195

**Comment by KingLemming** [comment]
It is, yes, but in this particular example, ExU2 is firing that with whatever the JEI Radar nonsense is. That shouldn't cause any sort of duping.

**Comment by KingLemming** [comment]
I'm pretty sure this was linked to the other issue, which has now been fixed. Calling this resolved.

**Comment by APolarBaer** [comment]
Why the wtf label also I'll check when I update the pack tomorrow and let you know
