### ISSUE TITLE
Shiftclicking into Autonomous activate = crash

### ISSUE THREAD

**Issue by Darkmega18** [CoFH/Feedback#208]
I've recently come across a crash with the autonomous activator where when I try to shiftclick a stack of blocks into it's inventory to be used in a sifter next to it the game crashes. I can place them in manually just fine, but shiftclick makes everything blow up. If it's worth anything i've set the base and use energy levels to 0 cause screw balance.

two crashlogs are on that same paste for the same issue. first using dusts. second using gravel if that can be of any help either.
http://pastebin.com/PBmgvMFJ

**Comment by skyboy** [comment]
Fixed in dev

**Comment by Darkmega18** [comment]
roger. I look forward to it. Since I keep forgetting cause shiftclick has sorta become automatic for me. >_<
