### ISSUE TITLE
Leadstone Energy Cell

### ISSUE THREAD

**Issue by NerdCat** [CoFH/Feedback#209]
I am currently playing Daemonds Science (1.7.10) from the technic launcher. It is a TE series based modpack. In world that I am LANing on I tried to open the configuration tab on a leadstone energy cell and all that I got was a square that became white when I slid my cursor over it over it. I tried to fix it by restarting three times but nothing changed. If anyone has had this problem I would like some help.

**Comment by KingLemming** [comment]
Yeah, that's entirely something with your rig and modpack. Not a code bug, sorry.

You can try asking in the IRC or twitch channel though.

**Comment by NerdCat** [comment]
Thank You!!
