### ISSUE TITLE
Server hangs when loading some chunks.

### ISSUE THREAD

**Issue by TiranDirth** [CoFH/Feedback#209]
Updated to the latest COFH suite (everything but Netherores) last night, after previously updating the day after Thermal Dynamics came out. Every time certain chunks are loaded, the server hangs indefinitely, timing out all players. Before the update the server was running stable for ~4 months.

Forge: 10.13.2.1291

Modlist:
BiblioCraft[v1.9.2][MC1.7.10].jar
BiblioWoods[BiomesOPlenty][v1.9].jar
BiblioWoods[Natura][v1.5].jar
BigReactors-0.4.1A2.jar
BiomesOPlenty-1.7.10-2.1.0.1004-universal.jar
buildcraft-6.3.7.jar
Carpenter's Blocks v3.3.0.1 - MC 1.7.10.jar
Chisel-1.7.10-1.5.7.jar
CodeChickenCore-1.7.10-1.0.4.29-universal.jar
CoFHCore-[1.7.10]3.0.0RC2-195.jar
EnderStorage-1.7.10-1.4.5.27-universal.jar
ExtraTiC-1.7.10-1.0.3.jar
Galacticraft-Planets-1.7-3.0.8.267.jar
GalacticraftCore-1.7-3.0.8.267.jar
HardcoreEnderExpansion  MC-1.7.10  v1.7.jar
InventoryTweaks-1.59-dev-152.jar
ironchest-1.7.10-6.0.41.729-universal.jar
Java7Checker  MC-1.7.10  v1.1.jar
Mantle-1.7.10-0.3.2.jar
Metallurgy-1.7.10-4.0.6.80.jar
MetallurgyCore-1.7.10-4.0.4.18.jar
MicdoodleCore-1.7-3.0.8.267.jar
MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar
MineTweaker3-1.7.10-3.0.9C.jar
MobiusCore-1.2.3_1.7.10.jar
ModTweaker-1.7.X-0.6-0.jar
natura-1.7.10-2.2.0.1.jar
NotEnoughItems-1.7.10-1.0.3.64-universal.jar
Opis-1.2.3_1.7.10.jar
RedstoneArsenal-[1.7.10]1.1.0RC2-43.jar
SimplyJetpacks-MC1.7.10-1.3.0.jar
TConstruct-1.7.10-1.7.1c.jar
Thaumcraft-1.7.10-4.2.3.5.jar
ThermalDynamics-[1.7.10]1.0.0RC2-77.jar
ThermalExpansion-[1.7.10]4.0.0RC2-129.jar
ThermalFoundation-[1.7.10]1.0.0RC3-56.jar
TMechworks-1.7.10-0.2.10.jar
twilightforest-1.7.10-2.3.2.jar
Waila-1.5.5_1.7.10.jar
CodeChickenLib-1.7.10-1.1.1.99-universal.jar
Baubles-1.7.10-1.0.1.10.jar

I can't provide a crash log as the server hangs indefinitely rather than crashing, but could happily provide the map this happens on and a link to the (custom) modpack if that would help.

**Comment by KingLemming** [comment]
Try the alpha versions currently on CurseForge and let us know if that solves it.

**Comment by TiranDirth** [comment]
First tests seem positive, if you want to leave this open a day or so, I'll push the new version to the rest of the server and update if it goes down. I'm sure my players will let me know within seconds. =-p

**Comment by KingLemming** [comment]
Oh I'll leave this up until we push a new RC, but it'd be fantastic to mark it as fixed in dev it at all possible.

Sorry for the initial inconvenience - ducts are super complicated and have a lot of corner cases. My assumption is that your server is getting caught in one of those infinite loop issues related to round robin.

**Comment by TiranDirth** [comment]
So far so good, seems nice and stable as the rest of the server pulls out all the rednet cable and buildcraft pipes for ducts.

Don't worry about that, we knew what we were getting in to when we installed the mod the second a version was up, we decided it was worth the risk and we'd do it again. You guys do great work, the speed at which you helped us here is just icing on top.
