### ISSUE TITLE
[1.10.2] Charging items causes Server crash

### ISSUE THREAD

**Issue by ColinAndress** [CoFH/Feedback#210]
Hello TeamCoFH,
Recently, one of my servers has been running into crashing issues with your energetic infuser from your 1.10 Thermal Expansion mod v5.0.4.90. When charging any item inside the infuser, it charges for a while absolutely fine until it reaches roughly 50% charge, then the server crashes. I have tested this in single player and on my sponge server, but it only crashed the server and not the client. The crash report shows nothing to point this towards an interaction with sponge as far as I can tell. I have attached the crash report in the pastebin link below. Thanks in advance!
-Colin
Crash Report: https://pastebin.com/CCyXqhhS

Mod list: https://pastebin.com/kaNAcdxL

**Comment by ukdyl94** [comment]
I've had this happen a couple times today as well.

**Comment by KingLemming** [comment]
What have you updated recently? Because this is the first report of anything like this, and TE hasn't changed lately.

We'll need screenshots to see connected machines/blocks/whatever for an idea of what may be causing this.

**Comment by ukdyl94** [comment]
@KingLemming This is what my server had updated.
MultiStorage (1.10.0-1.2.18 -> 1.10.0-1.2.18b)
IC2 (2-2.6.210-ex110 -> 2-2.6.234-ex110)
HarvestCraft (1.10.2 Only)
Ceramics (1.1.5 -> 1.1.6b)
BiblioCraft (2.2.2 -> 2.2.3)
NEID (1.5.3 -> 1.5.3.1)
ImmersivePetroleum (1.0.3 -> 1.0.4)
Natura (4.1.0.63 -> 4.1.0.65)
Acintegration (1.4.7 -> 1.5.0)
TConstruct (2.6.3 -> 2.6.5)

**Comment by KingLemming** [comment]
So looking through the code, this can only happen if another mod is fundamentally violating either the inventory contract (removing items from inaccessible slots) or fundamentally violating the Capability contract (changing capabilities on ItemStacks randomly).

This isn't in our code, but I'd like to know whose fault it is.

**Comment by ColinAndress** [comment]
I have not updated anything on my server, as it is running a fixed version of a modpack. One thing I did have was a creative capacitor bank next to the infuser to give it power. Not sure if that helps at all.

**Comment by ColinAndress** [comment]
It appears that using the "Flux Linkage Concentrator" module prevents this as the item charges fast enough to prevent the server crash, regardless of the connection. 

Here are some examples of energy inputs that I see when checking the area of the crash:
- It crashes when having the creative capacitor bank directly connected to the infuser
http://i.imgur.com/rVUG3x9.png
- It crashes when having the creative capacitor bank connected to an energy conduit from ender IO and then connected to the infuser.
http://i.imgur.com/NL4vfaR.png
- It does not crash when having the Extrautilities2 creative energy source directly connected to the infuser.
http://i.imgur.com/zr83Ujx.png
-It does crash when having the Extrautilities2 creative energy source connected to a energy conduit from ender IO and then connected to the infuser.
http://i.imgur.com/3tuexiZ.png
-It does crash when having the energy cell from Thermal Expansion directly connected to the infuser.
http://i.imgur.com/0FTxkEa.png

Those are just a few of the common setups I have seen that crash the server.

**Comment by KingLemming** [comment]
Yeah, I can't make a crash happen in any of those situations. I'm thinking Sponge may actually be a culprit.

**Comment by KingLemming** [comment]
Could you please attach a FULL crash report please? There's a strange method call that may be the culprit here - something is doing some funky ASM in the WorldServer class.

**Comment by Peace7904** [comment]
I am apart of the same server as Colin, here is a full crash report. I included the one with the least amount of players to make it easier for copy pasting.
https://pastebin.com/7Mdx5tnu

**Comment by KingLemming** [comment]
A full crash report includes a list of all installed mods.

**Comment by covers1624** [comment]
The full report also contains other important debug information, we need said information.

**Comment by Peace7904** [comment]
This is what the crash report is giving us. The list Colin provided in his op is the full list of mods installed.

**Comment by ukdyl94** [comment]
[Pastebin](https://pastebin.com/EjLVQvER)
[Screen Shot](https://images.discordapp.net/.eJwVyDkOwyAQAMC_0BuW5fZnIgQII9kGwbqK8vckxTTzZs882c4OorF2IXJbqc_MF_UZa-G193qWONriqV8iEsV0XOWmJRRKgGC11sY4VAD-X_InGG8wOCvRCwTpNrAb6Bci18ilKrkRH3dlny8bOiU7.6A8OA01G8FwM7fcVtaAliv0LYTc?width=720&height=382)

The red boxes would be where the player played the block.

Relating to my similar issue at least.

**Comment by KingLemming** [comment]
This right here:

at org.spongepowered.common.event.tracking.TrackingUtil.tickTileEntity(TrackingUtil.java:231)
    at net.minecraft.world.WorldServer.updateTileEntity(WorldServer.java:2808)
    at net.minecraft.world.WorldServer.redirect$onUpdateTileEntities$zjp000(WorldServer.java:2795)

This is a problem. You have something doing ASM and you have sponge doing some weird stuff on top of it. Given that we've never seen this reported before, and under standard MC conditions, an NPE isn't actually possible there, this is the fault of Sponge and/or some other mod you have.

Can you make it happen without Sponge?

**Comment by KingLemming** [comment]
k, I've pushed a few fixes to the Charger, so even if this ever was a thing on a normal Forge server, pretty sure it won't be now.
