### ISSUE TITLE
Can't build Machines after upgrade 

### ISSUE THREAD

**Issue by HideAwayDk** [CoFH/Feedback#210]
![recip](https://cloud.githubusercontent.com/assets/7749454/6425738/401e62c4-bf39-11e4-827a-d0009466bc8d.jpg)
Hey, after i tried to upgrade TE and all other mods you have made i can't build Machines, i haven't checked if any other recipes are broken ATM
On the image i'am trying to make the pulverizer

TE 4.0.0RC2-131 & 4.0.0RC2-129

**Comment by miuirussia** [comment]
Not confirm. All working

**Comment by HideAwayDk** [comment]
Do you have any idea that can be wrong with my setup then "miuirussia" ?

**Comment by HideAwayDk** [comment]
Update:
I tried to delete all configs and let it create em again, but that dossent help the problem, and its the same if i play on my server or single player

**Comment by skyboy** [comment]
Mod packs have the ability to change recipes for items, refer to the documentation for the mod pack you are playing.
