### ISSUE TITLE
Induction Smelter item insertion

### ISSUE THREAD

**Issue by krizo96** [CoFH/Feedback#211]
Hey,
I noticed that when I have a basic induction smelter and try piping in (on blue side) for example both cinnabar and ferrous ore, it will start inserting cinnabar in both slots once it runs out of the ore and if I upgrade it to anything higher than the basic level it will keep one slot empty as I would it expect it to. Don't know if it's a bug, but it seemed unusual to me since I didn't find any info on it.

**Comment by KingLemming** [comment]
Why would you expect it to do that?

Have you locked the left slot using the button on the GUI? If you don't see the button, then you need to not use that texture pack for now.

**Comment by krizo96** [comment]
No, the slots are blue and when the induction smelter is basic it just
takes in everything (ore in both slots for example, or cinnabar in both
slots) and when the induction smelter is any higher level it always keeps
one slot for ores and for the other thing. If I piped in only ores on blue
with the basic one, both inputs would get filled and if I piped in only
ores on a higher upgrade level only one of the input slots would get filled
and other left empty. It was weird to me that it acts differently in the
same situation just depending in the upgrade level.

**Comment by KingLemming** [comment]
I understand that the slots are blue, but what you're describing isn't how it actually works.

My guess is that you were using a smelter that was already in the world before you updated the mods, in which case the slot lock was disabled.

**Comment by krizo96** [comment]
Ahh! It seems that your guess was completely correct.
I created a new world to test it and it was working perfectly (also worked
in the original world after removing and replacing it).
Thanks, and sorry for the bother!

**Comment by KingLemming** [comment]
No problem at all!
