### ISSUE TITLE
[1.10.2]I can't make IC2 uranium ore gen in the Moon

### ISSUE THREAD

**Issue by TehporP** [CoFH/Feedback#211]
here the problem  
As the title says   I cant do dat  i have tow json files. One is for certus quartz and another one is for uranium,Certus Quartz works fine，but uranium doesnt(that means I enabled GC support)

here is the mod I have installed
![20170606220205](https://cloud.githubusercontent.com/assets/8299221/26833446/0a06b9b6-4b05-11e7-8b67-3e35bd0f0512.png)

and here is the json
https://pastebin.com/wL8yxp3X

so can anyone tell me how to make it happen or it just a bug?

**Comment by KingLemming** [comment]
Please use Twitch for questions. -_- This isn't a bug in the code.

Maybe try a value under 5000 for the size btw.
