### ISSUE TITLE
Cauldron comaptibility

### ISSUE THREAD

**Issue by Silverseppel** [CoFH/Feedback#212]
Hi,
can you make youre current versions of youre mods compatible to forge 1236 that i can youse it on my cauldron server because cauldron would not be updated anymore. The creator of cauldron is working on sponge.

thx

**Comment by HideAwayDk** [comment]
I wont belive he will make all mods work on that old forge, and i guess alot of the tings the mods use now can't be done in forge 1236.
My best gust is you need to download the old versions of the mod to be able to play it, sorry

**Comment by skyboy** [comment]
Servers can run the mods on 1236, it's only clients that need 1291.
