### ISSUE TITLE
Game crashes when CoFH is present in a modpack (1.10.2)

### ISSUE THREAD

**Issue by pinkcat13** [CoFH/Feedback#213]
Anytime this mod is present in a modpack, sine 1.10.2, the modpack crashes and I can't play it.  I don't know why this is happening and am hoping to get some help to resolve why this is occurring.

**Comment by legodude17** [comment]
Can you please provide your crash report?

**Comment by pinkcat13** [comment]
Here is the message I get when it crashes:

The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from CoFH Core (cofhcore)

[crash-2017-06-07_18.14.26-client.txt](https://github.com/CoFH/Feedback/files/1059465/crash-2017-06-07_18.14.26-client.txt)

**Comment by KingLemming** [comment]
Broken Forge installation. Please reinstall everything.
