### ISSUE TITLE
Crash on load

### ISSUE THREAD

**Issue by Serifina** [CoFH/Feedback#214]
Just updated to the most recent version and tried to load the game, crashed on startup. Crashlog is located [here](https://paste.ee/p/Xe9yo). Looks like something with the Compactor recipes?

**Comment by KingLemming** [comment]
You have a mod adding an invalid recipe to the game. Lovely.

**Comment by Serifina** [comment]
Will do. I tell have to be in the morning but I'll report back as soon as I figure it out.

**Comment by KingLemming** [comment]
Thanks! I imagine I'll head to bed as well and have a "fix" for this and whatever other issues later on.

**Comment by Serifina** [comment]
Right. Thanks for the hard work on all this. :)

**Comment by KingLemming** [comment]
Fixed it. Put in anti-stupidity code. No idea who caused it, but doesn't matter.

FTB Beyond loads up, so it should be good.
