### ISSUE TITLE
[Thermal Dynamics 1.10.2] Servo/Filter Stack Duping

### ISSUE THREAD

**Issue by s0uthw3st** [CoFH/Feedback#215]
It appears that servos and filters can be duplicated when applied to an itemduct - have not tested with other duct types yet, though presumably similar behavior exists.

Mods Installed:
DW20 1.10.2 (v1.11.0) Pack + updated CoFH mods + Thermal Dynamics v2.0.0.32

Steps for replication:
1. Apply servo to itemduct (attached or unattached to an inventory)
2. Interact with an inventory (click/shift-click the stack, open a GUI - including the servo GUI)
3. The number of servos in the stack returns to the previously held amount (e.g. a stack of 2 servos would reduce to 1 as expected when placed, and interacting with the stack in inventory would return it to containing 2 servos again)

Video example: http://recordit.co/bcUtMIEfHG

**Comment by KingLemming** [comment]
Interesting.
