### ISSUE TITLE
Client not detecting Minecraft Forge (sorta)

### ISSUE THREAD

**Issue by Rovio01** [CoFH/Feedback#215]
When loading minecraft with Minecraft Forge 10.13.2.1291, CoFH Core 3.0.0RC2-195, Thermal Foundation 1.0.0RC3-56, and Thermal Expansion 4.0.0RC2-129, the following message is displayed in the minecraft window (without crash):

Forge Mod Loader has found a problem with your minecraft installation
The mods and versions listed below could not be found
Forge : [10.13.2.1291,10.14)
The file 'ForgeModLoader-client-0.log' contains more information

I have used Minecraft Forge before, and in my experience it usually writes this file to the .minecraft folder. However, it was not present. I found a "fml-client-latest" in the "logs" folder, but I am fairly certain this is not the file being referenced. Here it is just in case:
http://pastebin.com/KyjerM1y

Has anyone else had this issue, and if so know of a fix, or is it and issue with one of my copies of the mods, or am I just doing something completely wrong?

**Comment by KingLemming** [comment]
Try actually using Forge 1291 please. You're using 1230.

**Comment by Rovio01** [comment]
Silly me. Selected the wrong one in the launcher. Thanks!
