### ISSUE TITLE
No recipes at all for Redstone Arsenal

### ISSUE THREAD

**Issue by Skillotic0703** [CoFH/Feedback#216]
With the new updates, vanilla recipes are disabled when TE is installed but there aren't any recipes for TE machines. So RA items are uncraftable atm.

**Comment by KingLemming** [comment]
You wanted them disabled with TE installed. You opened that last issue. Please make up your mind.

**Comment by Skillotic0703** [comment]
Yeah I wanted the vanilla recipes disabled not the TE ones!

**Comment by KingLemming** [comment]
It was a joke. :P Something got lost in the shuffle. I'll be hotfixing it.

**Comment by Skillotic0703** [comment]
Thank you!

**Comment by KingLemming** [comment]
Hotfix is up. Go ahead and redownload -32 please. Seems as though the change we made didn't quite get rolled in properly. AT < 1k downloads, I'm not doing a version increment.

**Comment by Skillotic0703** [comment]
Yeah I noticed a few minutes ago that you had pulled off the release from curseforge. Thank you I'm going to test it.

**Comment by Skillotic0703** [comment]
It's working now but recipes aren't showing up in JEI.

**Comment by KingLemming** [comment]
They do for me. Not sure what to tell you on that.

**Comment by KingLemming** [comment]
Made a tweak which should consistently force them to show in JEI. Load order randomness is dumb. Watch for -33 in a minute.

**Comment by Skillotic0703** [comment]
ok thank you!

**Comment by Skillotic0703** [comment]
Recipes are showing in JEI yeah!
