### ISSUE TITLE
Thermal Expansion 1.10.2 crashes game on startup

### ISSUE THREAD

**Issue by ZimsShiz** [CoFH/Feedback#217]
Once added it [crashes the game after the first loading phase.](https://gist.github.com/ZimsShiz/e548636e1c077535052728eb6bddfeee)

**Comment by KingLemming** [comment]
Yeah that's not Thermal Expansion at all.

**Comment by KingLemming** [comment]
Looking at it more, that's literally just your game crashing on the MissingMods screen. And you are missing a mod - CodeChickenLib 2.5.9. So that screen should be coming up, but it's not TE's fault that Minecraft is crashing on it.

**Comment by ZimsShiz** [comment]
oh, huh. Well thank you anyways.
