### ISSUE TITLE
[TE 1.10.2-5.1.0.92] Compactor bug with CraftTweaker

### ISSUE THREAD

**Issue by bortooo** [CoFH/Feedback#218]
If you change the recipe of a item with CraftTweaker using a different material in the crafting, compactor uses the previous material.

**Comment by KingLemming** [comment]
I'll need an example but offhand CraftTweaker isn't something we really support.

**Comment by KingLemming** [comment]
Actually, I get what you're saying and the problem here is that you'll *also* have to change the recipe in the Compactor.

The machine can't magically figure out what you're doing with CraftTweaker, since it's happening WAY WAY too late in the load process.
