### ISSUE TITLE
Conduit Error

### ISSUE THREAD

**Issue by thebongolest1206** [CoFH/Feedback#218]
http://paste.ee/p/umszw

Im using the latest version.

**Comment by KingLemming** [comment]
So...we don't have conduits.

I'm willing to assume you mean ducts. And we need context for that crashlog. Does it just happen on login, randomly, chunk loading - when?

**Comment by thebongolest1206** [comment]
Yeah, ducts , sorry used to calling them conduits. And it happens when I load a certain chunk or chunks that has my Uberminer in it.

**Comment by KingLemming** [comment]
When you loaded your world, did you happen to ignore any errors and just click "yes", suggesting an ID remap?

**Comment by thebongolest1206** [comment]
No. I loaded a back up, and it worked up until I went towards my mining machine and then started to crash when I loaded the world.

**Comment by KingLemming** [comment]
Why did you load a back up?

**Comment by thebongolest1206** [comment]
It crashed when I tried to load the miner. So thats when I used a back up because I have Aromas Back up so it only went back a few minutes.

**Comment by KingLemming** [comment]
We can't find a situation where this happens, unless the IDs on your world have been redone.
