### ISSUE TITLE
[Feature Request] [Thermal Expansion] Ability to comfigure TiC Materials

### ISSUE THREAD

**Issue by Mortvana** [CoFH/Feedback#219]
The ability to modify the mining levels, durability, and mining speed of TF's TiC materials (registered by TE) would be a great addition, for example, say I wanted to make Platinum have a mining speed of 24, or give Electrum 10 extra base durability. This could be achieved already through hacky ASM junk, or Iguana Tinker's Tweaks, although ITT only would work without Metallurgy 4 and Extra TiC (both by @Glassmaker). Theoretically the latter could be solved if Glassy added configs to disable conflicting metals in 1.1.x

**Comment by KingLemming** [comment]
Implemented, although it will be in Thermal Foundation and not Expansion. :)
