### ISSUE TITLE
[ThermalExpansion-1.10.2-5.1.0.92] Induction Smelter only processes shared ore from first mod loaded w/ IE

### ISSUE THREAD

**Issue by zcorcoran** [CoFH/Feedback#219]
This one's a little weird.
With Thermal Foundation, Thermal Expansion (both latest) and Immersive Engineering (latest 1.10 version), the Induction Smelter will only process one mod's version of any ore the two have in common. This appears to be based on load order; without renaming any mods, the Induction Smelter will only process IE's Copper, Tin, Lead, and Silver ores; it won't even accept TF's. However, if I append 10 z's to the IE jar's name, the opposite situation occurs and the Induction Smelter will process and accept TF ores while totally ignoring IE's. I can only conclude this happens because in the first setup, IE loads first, but in the second, TF loads second.
This extends to JEI recipes for the Induction Smelter as well, and applies to both the smelter's recipes by itself and the Pyro-Concentrator's; the're present for one version of the ore but totally absent for the other. 
Oddly enough, the Redstone Furnace and Pulverizer (and their respective augments) are totally unaffected by this and will happily accept both mods' ores regardless of load order from what I can tell.

**Comment by zcorcoran** [comment]
I forgot to mention that this extends to dusts as well, so with IE loading first, only Lead Grit will work to make hardened glass, for example.

**Comment by KingLemming** [comment]
That is extremely weird, yes.

**Comment by KingLemming** [comment]
Yep. Found it.
