### ISSUE TITLE
Caches get stuck when items are sucked out.

### ISSUE THREAD

**Issue by marcin212** [CoFH/Feedback#22]
When you have something that pulls out of a cache (BC pipe or hopper), at random times, the items would stop dropping out. It can be reset by pulling an item or stack from the cache and/or putting it back in.

CoFHCore-[1.7.10]3.0.0B9-73
CoFHCore-[1.7.10]3.0.0B9-73
ThermalExpansion-[1.7.10]4.0.0B8-23
forge: 1.7.10-10.13.2.1286
Modlist(custom pack): http://pastebin.com/5Q88mMKQ

**Comment by bochen415** [comment]
It will take out one stack and stop. I reported the original issue with vanilla hoppers and not long ago this:
https://github.com/rwtema/extrautilities/issues/468
The only pipes working that I tested were EnderIO conduits (they were also doing this in the past).

**Comment by KingLemming** [comment]
This still happening with the latest release?
