### ISSUE TITLE
1.7.10 charcoal dupe bug

### ISSUE THREAD

**Issue by NoX-programer** [CoFH/Feedback#220]
Just try to burn some Witchery wood for charcoal: http://www.youtube.com/watch?v=margPWxxkHM

mods&versions:
forge-1.7.10-10.13.2.1291-universal.jar
CoFHCore-[1.7.10]3.0.0RC2-195.jar
ThermalExpansion-[1.7.10]4.0.0RC2-129.jar
ThermalFoundation-[1.7.10]1.0.0RC3-56.jar
witchery-1.7.10-0.22.0.jar

**Comment by KingLemming** [comment]
Is this unique to Witchery wood? My tests suggest that it is.

**Comment by NoX-programer** [comment]
Yes. Vanilla wood doesn't  have that problem and Thaumcraft wood is OK too. Can you fix that witchery "feature of behavior"?

**Comment by KingLemming** [comment]
Strictly speaking, it's caused by Witchery doing something really incredibly wrong, but vanilla is too stupid to catch it.

And then it's apparently too stupid for the first mistake to matter.

I can probably fix this.
