### ISSUE TITLE
[1.10.2] Missing GUI Crash??

### ISSUE THREAD

**Issue by MokahTGS** [CoFH/Feedback#220]
This crash keeps showing up when I update to the new versions of TE.

https://pastebin.com/riqeDNtK

It's a weird crash and I don't see what's doing it.

**Comment by MokahTGS** [comment]
Got this same crash just adding Thermal Dynamics to the mod pack.

**Comment by KingLemming** [comment]
You're missing CodeChickenLib 2.5.9. Why your MC is choosing to crash rather than telling you that, I have no idea.

**Comment by MokahTGS** [comment]
Updating to 2.5.9 and the TD mods produces the same crash.

**Comment by MokahTGS** [comment]
Forge 12.18.3.2281
CodeChickenLib-1.10.2-2.5.9.267
CoFHCore-1.10.2-4.1.2.157
ThermalExpansion-1.10.2-5.0.4.90
ThermalFoundation-1.10.2-2.0.5.81

= No Crash

Update to ThermalExpansion-1.10.2-5.0.4.92 and ThermalFoundation-1.10.2-2.0.5.82 = https://pastebin.com/cXeK6pn7

Please help.

**Comment by MokahTGS** [comment]
Code Chicken says its not them:

https://github.com/TheCBProject/CodeChickenLib/issues/55
