### ISSUE TITLE
Wrench-Incompatibility

### ISSUE THREAD

**Issue by Reyls** [CoFH/Feedback#221]
all cofh mods latest version from curse

you cannot dismantle TE and MFR machines with certus quartz wrench from AE2.
and you cannot dismantle AE-devices with crescent hammer and sledgehammer.
yeta wrench works with TE but doesnt work with MFR.
is it intended?

**Comment by KingLemming** [comment]
We stopped shipping the BC wrench API - if BC is present, then our wrenches will implement it.

So it's not strictly intended, but rather a side effect. We're talking with the AE guys.

**Comment by KingLemming** [comment]
This should be fixed in dev. :)
