### ISSUE TITLE
[Thermal Dynamics 2.0.0.32] ItemDuct Filter "Mod Owner" non-functional

### ISSUE THREAD

**Issue by Pugsworth** [CoFH/Feedback#221]
The assumption I get from this feature is that it will filter items based on the mod id/domain.
e.g. minecraft:dirt as a filter will include all items from "minecraft:" - minecraft:stone, minecraft:obsidian, etc.

Setup:
An input chest with a Servo to pull items into the network.
Multiple output chests with Filters, all set to different mod items.

Edit: Options used
* Whitelist
* Ignore Meta
* Ignore NBT
* Ignore Ore Dictionary
* Use Mod Owner
* Prevent Over-Sending

[Image of simple setup](http://i.imgur.com/Rtr7XYl.png)

&nbsp;

What happens:
The items that are put into the filters are filtered. All other item stays in the input chest.

Expected behavior:
All items from mods that are in the filters should be filtered into the correct chest.

List of installed mods:
* Chisel-MC1.10.2-0.0.10.22.jar (for testing other "mod owners")
* CodeChickenCore-1.10.2-2.4.1.102-universal.jar
* CodeChickenLib-1.10.2-2.5.9.267-universal.jar
* CoFHCore-1.10.2-4.1.2.157-universal.jar
* ForgeMultipart-1.10.2-2.0.0.31-universal.jar
* ThermalDynamics-1.10.2-2.0.0.32-universal.jar
* ThermalExpansion-1.10.2-5.1.0.92-universal.jar
* ThermalFoundation-1.10.2-2.1.0.82-universal.jar

**Comment by KingLemming** [comment]
...is your filter set to Blacklist, or Whitelist?

**Comment by Pugsworth** [comment]
Oh sorry, forgot to include the options.
I've tested every combination that includes "Use Mod Owner".

Exact options:
Whitelist
Ignore Meta
Ignore NBT
Ignore Ore Dictionary
Use Mod Owner
Prevent Over-Sending

**Comment by KingLemming** [comment]
Was actually an issue in CoFHCore, but is now rewritten to only be in TD.

**Comment by Pugsworth** [comment]
Compiled latest commit and can confirm Filters are now behaving correctly.
Thank you.

**Comment by KingLemming** [comment]
Gonna leave it open til there's a build up on Curseforge. ;) Should be later tonight.
