### ISSUE TITLE
[1.10.2] Missing GUI Crash

### ISSUE THREAD

**Issue by MokahTGS** [CoFH/Feedback#222]
Forge 12.18.3.2281
CodeChickenLib-1.10.2-2.5.9.267
CoFHCore-1.10.2-4.1.2.157
ThermalExpansion-1.10.2-5.0.4.90
ThermalFoundation-1.10.2-2.0.5.81

= No Crash

Update to ThermalExpansion-1.10.2-5.0.4.92 and ThermalFoundation-1.10.2-2.0.5.82 = https://pastebin.com/cXeK6pn7

Please help.

**Comment by KingLemming** [comment]
Update ALL of your CoFH mods. This crash is in a Forge class. We aren't the cause.

**Comment by MokahTGS** [comment]
I'm not sure how you aren't the cause when updating your mods (as you say I should do) causes the crash.

**Comment by KingLemming** [comment]
The entire trace is Forge. The error is that you are missing a mod. That is a problem with your setup, not our mods.

**Comment by MokahTGS** [comment]
The problem is that Redstone Arsenal is required to update if you update any of the others.  Didn't realize that was required.

**Comment by KingLemming** [comment]
"Update ALL of your CoFH mods." :|
