### ISSUE TITLE
Ticking Entity crash (different from the others)

### ISSUE THREAD

**Issue by Fogger** [CoFH/Feedback#223]
Worked fine previously, but after update, turning on my blaze spawner which consists of:
Autonomous Activators placing/removing Mekanism Cardboard Boxes on Blaze Spawners, but it has 2 modes, and the crash occurred when switching from manual target practice to auto mode, which drops the blast shield, turns out the lights and turns on the Grinders using Rednet.
![Visual](http://i.imgur.com/gztNiTv.png)
Crash Log: http://haste.pagefortress.com/oyosidoxof.coffee

May be related: r-clicking an Immiblocks covered rednet cable crashes the client with the following error: http://haste.pagefortress.com/ehevukukab.coffee

**Comment by skyboy** [comment]
The first crash has been fixed in dev, the second crash is entirely on immibis.

**Comment by Fogger** [comment]
Thanks, If only there was a bug tracker for Immiblocks :S
