### ISSUE TITLE
Client crash while trying to display ducts in Refined Storage System

### ISSUE THREAD

**Issue by BluMasc** [CoFH/Feedback#223]
I tried to autocraft the empty player transporting ducts from Thermal dynamics with Refined Storage, but i get this crash either when i'm looking in the system, with the recipe in a crafter or when i hold shift while having an inventory with the pattern open:
[crash-2017-06-11_17.23.31-client.txt](https://github.com/CoFH/Feedback/files/1066568/crash-2017-06-11_17.23.31-client.txt)
this happend on a Server but only crashed the client.

MC 1.10.2
Forge 12.18.3.2281
Modlist:
[latest.txt](https://github.com/CoFH/Feedback/files/1066579/latest.txt)

**Comment by KingLemming** [comment]
Yeah that crash doesn't really make any sense unless Refined Storage is throwing nulls around for no good reason.

**Comment by BluMasc** [comment]
Ok, i will put this over on Refined Storages Issue Tracker

**Comment by KingLemming** [comment]
Well, I'll likely have to mitigate it on this end, I really would like to know what's going on exactly though.

**Comment by TheChaosKing771** [comment]
I have the same issue but with every duct, and I reported it on the Refined Storage issue tracker [here](https://github.com/raoulvdberge/refinedstorage/issues/1296), but raoulvdberge said that it was a COFH issue.

[My crash report](https://pastebin.com/1WsJbabb)

**Comment by KingLemming** [comment]
Yeah, it crashes in our code, but only crashes because it's being handed a null. Normal Minecraft doesn't do that. What is RS doing?

**Comment by BluMasc** [comment]
It only comes up when you autocraft it. So the system has 0 of it, but can craft it. Maybe because of that?

**Comment by KingLemming** [comment]
Resolved in dev. Issue is basically exactly as I stated - it's on RS's end because they are doing some SUPER hacky stuff with their item renderer.

**Comment by raoulvdberge** [comment]
We are using Minecraft's override system, which is not "hacky" stuff.

**Comment by KingLemming** [comment]
From what I can tell, it directly resulted in a null being passed to our renderer, so there was something very strange afoot.
