### ISSUE TITLE
Dynamos do not auto-rotate towards an RF-accepting item.

### ISSUE THREAD

**Issue by ariosos** [CoFH/Feedback#224]
Steps to Reproduce -

1. Place down any item accepting RF (energy cell, duct, IO conduit/capacitor bank, etc.).
2. Place any dynamo next to it.

Expected Result -

The dynamo should rotate to the RF-accepting item.

Observed Result -

The dynamos are placed in their default upright position.

**Comment by KingLemming** [comment]
This was an intentional change, it has already been changed back.

Once again, what version are you on?

**Comment by ariosos** [comment]
(hmm, I thought I put the version in the title, but must've not hit the right save button). I'm using the FTBInfinity Pack.
ThermalDynamics-[1.7.10]1.0.0RC1-69
ThermalExpansion-[1.7.10]4.0.0RC1-119
ThermalFoundation-[1.7.10]1.0.0RC2-53


(I've tried looking for later versions, i.e., on OpenEye, but they don't seem to have download listed when I checked).

**Comment by KingLemming** [comment]
Yeah, you're a version behind. By the end of the day, you'll probably be two versions behind. ;) We need to push some new fixes.
