### ISSUE TITLE
[Feature Request] - Fluctuating Itemducts should have a red glow when RF is applied.

### ISSUE THREAD

**Issue by ariosos** [CoFH/Feedback#225]
(not sure how lag intensive this one could be)
To indicate that RF is actively flowing through the Fluctuating Itemducts, the itemduct should glow red, with a brightness dependent on how much RF is flowing through, as well as the default state for no RF, or being disabled by a redstone signal.

**Comment by KingLemming** [comment]
After looking at it, it's too much lag, sorry.
