### ISSUE TITLE
Crash When Using Search Bar

### ISSUE THREAD

**Issue by HelloIamapersonthatisalive** [CoFH/Feedback#225]
(When I click the creative compass)

Crash Report: https://pastebin.com/eS5gSdGD

Error itself: https://pastebin.com/VSc7WL0S

I saw thermal dynamics in there so I posted it here

**Comment by KingLemming** [comment]
Can you make this happen with only CoFH mods?

**Comment by HelloIamapersonthatisalive** [comment]
Nevermind I fixed it, sorry for the time waste

**Comment by KingLemming** [comment]
Well I'd still like to know the cause.
