### ISSUE TITLE
The Resonant Energy Cell loses its' RF indicator (bright red meter in the GUI)

### ISSUE THREAD

**Issue by ariosos** [CoFH/Feedback#226]
Steps to Reproduce -

1. Fill up a Resonant Energy Cell with RF from any RF source.
2. Watch the RF storage indicator.

Observed Result -

After about 52 million RF, the indicator turns off. 

Expected Result -

The meter should continue as normal.

**Comment by KingLemming** [comment]
This has already been fixed. What version are you on?
