### ISSUE TITLE
Thermal Dynamics - There are texture glitches when looking at Cryo-Stabilized Fluxducts

### ISSUE THREAD

**Issue by ariosos** [CoFH/Feedback#227]
Depending on the view angle, there are texture glitches or artifacts in the middle section of the pipe.

http://s14.postimg.org/5ut0tk7wx/Texture_Glitch1.jpg
http://s14.postimg.org/92xi6lu6p/Texture_Glitch2.jpg

**Comment by skyboy** [comment]
This is generally just a problem in 1.7. We can't do anything to resolve it.

**Comment by chrissiemcc** [comment]
I reckon you are using OptiFine and have 'Fast Render' enabled. Turn that off and it will go away.

**Comment by KingLemming** [comment]
Nah, has nothing to do with that, it's just an artifact of how Mojang implemented render layering

**Comment by chrissiemcc** [comment]
Ah alright then. Was worth a go ;P
