### ISSUE TITLE
Thermal dynamics crash

### ISSUE THREAD

**Issue by Joshwoo69** [CoFH/Feedback#229]
Buildcraft update to latest seems to break this
API update/ recompile?

**Comment by KingLemming** [comment]
Have a crashlog, modlist, anything at all?

**Comment by KingLemming** [comment]
So, nothing then?

**Comment by Joshwoo69** [comment]
Yes I do have a modlist.. crash log will be later when I get home. But it seems to be BC and Thermal dynamics. I updated BC and then thermal dynamics starts crashing.

**Comment by Joshwoo69** [comment]
But it can be other mods that go into play... I also see Somnia entity core though.... in the crash log.

**Comment by Joshwoo69** [comment]
here is the crash log ;)
http://pastebin.com/tsuYpgq6

**Comment by Joshwoo69** [comment]
somnia and Thermal dynamics crashes things...

**Comment by Joshwoo69** [comment]
here is the openeye report
http://openeye.openmods.info/crashes/d076d95db8e1975b540430569547bb81

**Comment by skyboy** [comment]
This is a case somnia will have to handle as vanilla expects this particular behavior.
