### ISSUE TITLE
1.10.2  Camera glitches in Viaducts

### ISSUE THREAD

**Issue by EvilBastard** [CoFH/Feedback#229]
When going through the viaducts, the camera tends to glitch and not be at all smooth.

**Comment by KingLemming** [comment]
Known. Yup. Seems to be related to 1.10.2 entity handling and may well be unfixable. :/

**Comment by KingLemming** [comment]
This is temporarily resolved in dev, albeit in an inelegant manner. Leaving this up as a reminder to fix it "properly."

**Comment by KingLemming** [comment]
Closing this out and replacing with an enhancement issue. :)
