### ISSUE TITLE
[Thermal Foundation] Crash on Launch

### ISSUE THREAD

**Issue by clink87** [CoFH/Feedback#23]
Hello, I'd first off like to say thank you for all the great work that you guys put into these wonderful mods! My issue is with the newest release of Thermal Foundation (RC1). Upon launching Minecraft, I get this error: 
![screen shot 2015-01-14 at 4 00 46 pm](https://cloud.githubusercontent.com/assets/10558822/5773362/b4d89e08-9d2f-11e4-8a81-0e7caa3073f2.png)

I have downloaded and re-downloaded the newest version multiple times, for both TF and CofHCore because I read in the Issues that there was a similar issue that was solved with re-downloading the CofHCore file.

Here is the log file: http://pastebin.com/QWAc97bH
And the Mod list: http://pastebin.com/U4BzkmE0 (I have also had the same problem with only CofHCore, TF, TE, and MFR installed)

I appreciate any help that you can provide.

**Comment by Fortist** [comment]
I had the same issue before, I think.
Make sure you're using Java 7 or whatever its called.

**Comment by clink87** [comment]
That did the trick, thanks Fortist!
