### ISSUE TITLE
Strange cache behavior in creative mode

### ISSUE THREAD

**Issue by mcpecommander** [CoFH/Feedback#23]
you can not destroy the cache in creative mode without sneaking "but I guess this okay" and you can not retrieve any items in creative too , as it only shows the breaking animation and a decrease in items that you do not get back.
there is also a strange render bug for machines and blocks in the cache mainly, where they become darker at a certain angle but since I have optifine installed, I can not confirm if this happens every time without it. 
![2017-03-05_11 58 29](https://cloud.githubusercontent.com/assets/25066107/23586714/18abe0ee-019b-11e7-8123-2f47596dd09c.png)
![2017-03-05_11 51 59](https://cloud.githubusercontent.com/assets/25066107/23586715/18ac3d00-019b-11e7-9bb3-b05690fe1e79.png)

**Comment by KingLemming** [comment]
This was actually intentional, but I suppose it's not construed that way. I'll consider changing it.

**Comment by KingLemming** [comment]
I've adjusted this. Creative mode now extracts 64 items at a time, since a Shift + Click will destroy the block.
