### ISSUE TITLE
Ducts and Actually Additions

### ISSUE THREAD

**Issue by EvilBastard** [CoFH/Feedback#231]
Today I discovered that flux ducts, item ducts, and whatever else ducts will not directly connect to the oil generators of actually additions.  They will connect to the other machines, but for some reason not the oil gens.

**Comment by KingLemming** [comment]
Hrm. That's interesting. Offhand I don't know if that's a limitation on the oil gen or what.

**Comment by KingLemming** [comment]
Are you trying to connect to the bottom of it? Apparently connection rules were changed in 1.11.

**Comment by EvilBastard** [comment]
Tried from bottom, front, side, and back. Top I hadn't tried with either ducts.

**Comment by KingLemming** [comment]
Okay so this report confused me because of the "whatever else ducts."

Fluiducts connected fine, and once I realized that, I figured it out. Fixed in dev.

**Comment by the1upper** [comment]
Will this fix also correct fluxducts not connecting to EnderIO machines? I noticed the Stirling Generator from EnderIO would not connect to a fluxduct. Or is this due to EnderIO dropping the RF API?

**Comment by KingLemming** [comment]
It probably will, yes.
