### ISSUE TITLE
Phytogenic Insolator negative water quantities on server

### ISSUE THREAD

**Issue by ouroboros8** [CoFH/Feedback#231]
I'm having a problem with the Phytogenic Insolator on a 1.7.10 server running Thermal Expansion 4.0.0RC2-129. I can't replicate this bug in single-player, so it may be an issue with how the data is communicated to the client from the server.

When I hook up the insolator to a water supply, the tank begins to fill normally, but once it hits about 32000 mB the value switches sign, so the value jumps to about -32000 mB, but continues to climb. It eventually hits 0 again, and the tank starts to fill again, and gets up to about 14K mB before stopping.

The fact that it stops at about 14K makes me think that the tank still fills up to a total of 80K mB: it fills to 33K, then jumps down to -33K and fills up to 0, then fills the remaining 14K, making 80K.

**Comment by KingLemming** [comment]
Yup. Tried to use vanilla for something. I should know better.
