### ISSUE TITLE
[Suggestion]  Canola Oil and it's improvements

### ISSUE THREAD

**Issue by EvilBastard** [CoFH/Feedback#232]
This more for a cross mod compatibility, but perhaps making it so the canola oil its refined oil and the two improvements from there from Actually Additions can be used in the Compression Dynamo.   Or even let it be used to make a Biodiesel for use in the compression dynamo.

**Comment by KingLemming** [comment]
That's reasonable. I'll look into that. :)

**Comment by s0uthw3st** [comment]
On a similar note, would be nice to see Forestry ethanol as an option in compression dynamos - not many mods use it for anything except Forestry itself and EnderIO. It's fun to make and being able to use it as a power option alongside charcoal, creosote, etc. already made by tree farms would be a neat addition.

**Comment by KingLemming** [comment]
AA oils are in, Forestry isn't yet but it's on the to-do.
