### ISSUE TITLE
Crash with CoFHCore 1.7.10 R2-195

### ISSUE THREAD

**Issue by lhenrique03** [CoFH/Feedback#232]
When I tried to update cofh core on my modpack it crashed, I tried many things and none of them worked, so I decided to report this to see if someone can help me.
Here is the crashlog: http://pastebin.com/esd3xeML and if helps here is the modlist:http://pastebin.com/6bqLfTJC

**Comment by KingLemming** [comment]
You didn't follow directions. Please update ALL of your mods. This includes Thermal Expansion.
