### ISSUE TITLE
When updating CoFH mods to latest any worlds from before updating become unusable

### ISSUE THREAD

**Issue by jss2a98aj** [CoFH/Feedback#234]
I updated all of the CoFH mods I was using. I then tried loading up a world of mine (with over 150 mods) and it had a yes/no option and if I hit yes, it would proceed to start loading the wold and the crash. I looked at the log a bit and tried making a new world with only the CoFH mods). I then updated the mods and opened the new world I had made. (I updated from
CoFHCore 3.0.0B9-102
CoFHLib 1.0.0B9-67
MFR 2.8.0RC6-41
Nether ores 2.3.0RC1-26
Redstone arsenal 1.1.0RCRC1-26
Thermal expansion 4.0.0B8-23
thermal foundation 1.0.0RC1.0.0RC-27
to
CoFHCore 3.0.0RC2-201
CoFHLib 1.0.0RC1-119
MFR 2.8.0RC7-81
Nether ores 2.3.0RC4-10
Redstone arsenal 1.1.0RC2-49
Thermal expansion 4.0.0RC2-131
thermal foundation 1.0.0RC3-57 )
It had the same yes/no prompt. It did not crash though, but it did have item and block ids shifted around randomly. Here's a log if it helps(I think thermal foundation is at fault from looking at the log): http://pastebin.com/dVxuV0i6

**Comment by KingLemming** [comment]
You are at fault. You used alpha versions from CurseForge when we warned you not to.

The fix for this is to backdate TF and TE to the december RELEASES. Load your world, THEN update.

**Comment by jss2a98aj** [comment]
Sorry, I should have realized I was using alpha versions, Its been a while since I had downloaded them.
