### ISSUE TITLE
[1.10.2] Long Range Viaducts do not allow for 2x1 spaces

### ISSUE THREAD

**Issue by JonoColwell** [CoFH/Feedback#234]
Attempting to go through this long range viaduct killed me by putting me in the wall

http://puu.sh/wiqYo/d1eb0568d8.jpg

F5 showed me above the duct but as the duct is on bedrock and there's a one block space above the duct I don't believe this was the case, unless you need 2 blocks above the duct, I think the player might be slightly off to the side.

**Comment by JonoColwell** [comment]
Long range Viaducts require a 2x1 space above them, as though the player was standing on top of the duct.

**Comment by JonoColwell** [comment]
This is how it looks when it's glitching
http://puu.sh/wiuRq/1aff00ba8e.png

**Comment by KingLemming** [comment]
Just checking, did you first travel *down* to the linking duct?

**Comment by JonoColwell** [comment]
Yeah, the linking duct is below the main viaduct system

**Comment by KingLemming** [comment]
This is basically an extension of #229. Resolved for now in a dev build, but it's not truly "fixed" as well as I would like.
