### ISSUE TITLE
Long range viaducts don't remain connected

### ISSUE THREAD

**Issue by JonoColwell** [CoFH/Feedback#235]
Long range viaducts seem to disconnect at random, this is over an 800 block straight line or so
Here it is connected
http://puu.sh/wiuPL/11682604c8.png

Here it is a few seconds later, disconnected
http://puu.sh/wiuRq/1aff00ba8e.png

They can be relinked for a random period of time by shift right clicking the linking viaduct but they'll just disconnect after a while

**Comment by KingLemming** [comment]
Hrm okay. Will look into it.

**Comment by JonoColwell** [comment]
Further information

Attempted to reset server to get more information from a clean log (Old log is 17MB, but here it is http://puu.sh/wiBmM/13dcec4259.log)

Now it's not dropping, I don't know what's going on here.

**Comment by JonoColwell** [comment]
And it's dropped again, but only from some of my viaducts

Showing
http://puu.sh/wiCXq/250be7062b.png

Not showing
https://puu.sh/wiCYP/718332e04f.png
http://puu.sh/wiCZq/5260482931.png

**Comment by KingLemming** [comment]
Just checking - are you chunkloading the endpoints? Because that has always been a requirement.

**Comment by KingLemming** [comment]
Just wanted to follow up - are your endpoints chunkloaded? My guess is that when you can't see a certain one, it's because you're too far away and it's no longer in existence.

**Comment by JonoColwell** [comment]
No it was not, just to clarify only the viaduct end needs to be loaded or the linking viaduct ends?

I've since loaded it and will let you know if it drops.

**Comment by JonoColwell** [comment]
Nevermind, I have kept it loaded with spot loaders and it's sitll vanished, reopening

**Comment by KingLemming** [comment]
I'm fairly sure that the endpoints have to be loaded as well as the long range linking viaducts. @rwtema could probably clarify that a bit more.

**Comment by JonoColwell** [comment]
Everything is chunk loaded and it's still vanishing

**Comment by KingLemming** [comment]
Okay at the moment it's 100% known that long range are bugged. I apparently broke them the other day by cleaning things up. Figuring out a fix for that, but I'm not sure it solves the original issue.

**Comment by KingLemming** [comment]
Closing this down as I've fixed the disconnecting issue in dev, and apparently the suffocation one too. Will have updates out today.

As far as ducts "forgetting," this actually seems to be somewhat intentional behavior - clicking the Linking Duct forces a scan and loads the chunk. I've set up an issue which will serve as discussion for this: #277.
