### ISSUE TITLE
Tick Handler Crash

### ISSUE THREAD

**Issue by Kazekitsune23** [CoFH/Feedback#236]
Every time I try to go to a world after I placed down ducts I crash to desktop. Here's the crash log. http://pastebin.com/2HWRjQk7

**Comment by rwtema** [comment]
It would seem that either some mod is called readFromNBT on a client-side tile (which it shouldn't), or modifying the server world to have it detected as a client world (which it really shouldn't). I suspect the former.

**Comment by KingLemming** [comment]
Yeah, I'm about 99% sure this isn't us in any way. Could we get a modlist please?

**Comment by Kazekitsune23** [comment]
Here's my current modlist http://pastebin.com/Ex6zcc2m

**Comment by mcmz4e** [comment]
I´ve been getting the same problem with the 1710 RC277 version....wanted to report noticed new version came out 2 hours ago.
I´ll test the new version and report for new version if it persists....also you´ll be able to cross reference the 2 modlists to find the offending mod if it´s not thermal dynamics.

**Comment by Kazekitsune23** [comment]
For me the recent updates finally let me back into the worlds where I have ducts placed again. Thanks for the great mods :)

**Comment by KingLemming** [comment]
k, closing this as fixed then.
