### ISSUE TITLE
TD 2.0.2.4 Round Robin issue

### ISSUE THREAD

**Issue by Pihrra** [CoFH/Feedback#236]
I've set up 8 steam dynamos around a vertical fluxduct going into an energy cell and feed them with water on one side and charcoal on the other.
The charcoal is supposed to be distributed in round robin mode however the ones on the west and east of the itemduct don't receive any charcoal until the north and south are full.
![2017-06-13_09 23 12](https://user-images.githubusercontent.com/215052/27071191-2f05f88c-501c-11e7-99c2-fbe303d5c819.png)
![2017-06-13_09 23 22](https://user-images.githubusercontent.com/215052/27071195-312ed03e-501c-11e7-8af1-e78fecd71141.png)

Here is a debug crashlog in case you need more info on my setup : https://gist.github.com/Pihrra/f4ddb9fdf43b64dc6689d7239aab3a44

**Comment by KingLemming** [comment]
Technically they are doing round robin, but on a per-duct basis.

**Comment by KingLemming** [comment]
Found it! The logic was there but the assignment wasn't.
