### ISSUE TITLE
Thermal Expansion not wanting to show up

### ISSUE THREAD

**Issue by kurty1411** [CoFH/Feedback#237]
I downloaded it and put it in my mods folder, but every time I go into the game it doesnt show up. 

Mods folder:
![image](https://user-images.githubusercontent.com/28402879/27093119-6b1d162a-505d-11e7-900b-09c46691d378.png)

**Comment by KingLemming** [comment]
Yeah so you need the 1.7.10 version. You downloaded the 1.10.2 version.

**Comment by kurty1411** [comment]
...
