### ISSUE TITLE
Crash on server startup with Forge Essentials

### ISSUE THREAD

**Issue by zlepper** [CoFH/Feedback#238]
Crashlog: http://paste.ubuntu.com/10515235/
Startup log: http://paste.ubuntu.com/10515787/
I have no idea what is actually causing the issue, expect attempting to start my server. 
Modlist: http://paste.ubuntu.com/10515917/ please ignore any client-side only mods like custom main menu, they are not on the server.

I also reported the issue to the FE devs, but to no avail: https://github.com/ForgeEssentials/ForgeEssentialsMain/issues/1319

**Comment by skyboy** [comment]
A new version will be coming out in a few hours that may resolve this; when it's available report back

**Comment by skyboy** [comment]
Closing as this is reported as resolved in the FE issue.
