### ISSUE TITLE
[CoFHCore][World Generation] Emerald Ore

### ISSUE THREAD

**Issue by tgstyle** [CoFH/Feedback#239]
I have tried everything to control emerald ore generation, is it not possible? I have tried every combination to no avail.

This is what I used in it's own json file. I also tried it in the vanilla json.

{
    "emerald": {
        "template": "uniform",
        "block": "minecraft:emerald_ore",
	"material": "minecraft:stone",
        "clusterSize": 1,
        "numClusters": 1,
        "minHeight": 4,
        "maxHeight": 32,
        "retrogen": "false",
        "biomeRestriction": "whitelist",
        "biomes": [
            {"type": "dictionary", "entry": "MOUNTAIN"}
        ],
        "dimensionRestriction": "blacklist",
        "dimensions": [
            -1,
            1
        ]
    }
}

**Comment by KingLemming** [comment]
What do you mean by "control"? Forge doesn't expose emeralds as something that can be replaced.

You can add new ones, that works. And this is a valid json, so in theory also works. But you're stuck with the vanilla default spawns in addition. It's a Forge issue, sorry.
