### ISSUE TITLE
Thermal crashes every 15-20min.

### ISSUE THREAD

**Issue by MrPinkDrifter** [CoFH/Feedback#24]
Game runs without Thermal.
But when I add thoes 3 files ("CoFHCore, ThermalFundation & ThermalExpansion") it crashes every 15-20min.
And the game can't find the textures for Thermal tools/gear. Gets unknown texture. "Pink/Black checker"
Mod list:
![c2b32076333bff08430c72c97e43120b](https://cloud.githubusercontent.com/assets/10561518/5777374/44057b34-9d92-11e4-9d4f-4fe588280527.png)

**Comment by MrPinkDrifter** [comment]
I will see if I can manage to get a crash report, but the game just stops working and I have to close it through the prosess manager.

And I run Forge 10.13.2.1286.

**Comment by bochen415** [comment]
1. Get the fml log, upload it to http://paste.ubuntu.com or a similar site.
2. Why is there a 1.7.2 directory there? Are you using 1.7.2 mod versions in 1.7.10?
3. IronChest mod original jar name is different. Where did you download this? Unofficial version?
http://files.minecraftforge.net/IronChests2/
4 You have Optifine. Always try without optifine before posting an issue
4a You have PlayerAPI + RenderPlayerAPI + Smart Moving + Smart Render+..... Always check without those before posting an issue.
5. Get the fml log, upload it to http://paste.ubuntu.com or a similar site. (I know it's twice)

**Comment by MrPinkDrifter** [comment]
Aight, gona check without Optifine and Smart moving. But it works as it should with those mods when Im not using Thermal.
The 1.7.2 is an old folder that I had when I used that version for mods. (deleted now)
The IronChest mod i got from dl4.9minecraft.net

**Comment by KingLemming** [comment]
Without a crash log, there's no way to even verify these mods as the direct cause.

Are you using official versions?

**Comment by MrPinkDrifter** [comment]
All the mods should be official now. Still doing some testing atm without Smartmoving.
Just did a test after I deleted the 1.7.2 folder and changed the IronChest mod to the legit one from the provided link. And it still crashed as usual. Though I'll provide the fml file after I'v tested without Smart moving and Optifine.

**Comment by bochen415** [comment]
Crashes or freezes? You mentioned you have to use the task manager.

**Comment by MrPinkDrifter** [comment]
Well, I removed Smart Moving and the crashing stopped.
I started it again to get a log on conflicts or what not.

Yes, its like it gets a memory leak or something, even tho it dosen't, never goes full on memory.
I have given it 6GB to play around on.

**Comment by MrPinkDrifter** [comment]
I manage to make come to "shutting down internal server.." where it completly freezes and dont respond. After that I open my task manager and end its prosess.
It only uses 4GB ram in my manager and alot on my CPU. (Not sure what the numbers under the tab CPU stands for, but its around 60-70 anyway)

here's the log from the Launcher's "log output":
http://paste.ubuntu.com/9762549/

And the "fml-client-latest":
http://paste.ubuntu.com/9762568/

**Comment by bochen415** [comment]
>  java.lang.OutOfMemoryError: PermGen space

You are running out of PermGen space

There are 2 options:
1. Add -XX:MaxPermSize=384m to your startup parameters (java arguments)

or

2. Remove java 1.7.0_60 (recheck if gone) and install the newest 1.8.0_25

**Comment by MrPinkDrifter** [comment]
I did nr2 and it looks like it works properly now.
I did upgrade to that java ver 2 days ago when this started, but i looked and i still had java 7 and another java 8, plus my java 8 x64. Something went mental there. =P

Thanks for the help. Much appreciated!

**Comment by bochen415** [comment]
One more thing

> I have given it 6GB to play around on.

This is too much. 2-3GB in singleplayer should be enough.
