### ISSUE TITLE
Issues deleted without reason

### ISSUE THREAD

**Issue by krakentoa** [CoFH/Feedback#24]
Hi, I had left a issue about viaducts ( #1284 according to the emails I have) and was starting to get some independent verification from @Fabboz , but I noticed today that it was gone, deleted, not closed.
Why? It took me some time to put together the info I had posted, if it was missing information it would be much easier for me to edit than to recreate it.

**Comment by KingLemming** [comment]
The Feedback repo was wiped as nothing on it was relevant any longer. We're working with a completely different codebase now.
