### ISSUE TITLE
Release candidate

### ISSUE THREAD

**Issue by mcmz4e** [CoFH/Feedback#240]
New mods just came out from Team CoFH
All of them are release candidates and i understand that some are RC3 while others RC4 because ...duh ...the fourth version is RC4 but I find that a bit confusing so I would like to suggest the following :
When a new batch of mods comes out they should all have the same suffix (RC x) even if for some that is actually the same mod as last version or nothing changed.
Reason: makes it easier to browse through mod lists and mod folders looking for duplicate mods or older incompatible mods, It wouldn´t be more logical but more practical.

**Comment by KingLemming** [comment]
That's...not actually how versioning works. I'm sorry.
