### ISSUE TITLE
Hardened Flux ducts not transferring power once filled with RF

### ISSUE THREAD

**Issue by EvilBastard** [CoFH/Feedback#242]
I've noticed today, at least with hardened flux ducts is that once saturated with RF they transfer a REALLY low amount. It seems to behave like how dynamos do once they are filled with power.  This is in TD 1.10.2 ver 2.0.2.4

**Comment by KingLemming** [comment]
Gonna need a screenshot.

**Comment by EvilBastard** [comment]
http://i.imgur.com/cLIch5O.png

**Comment by KingLemming** [comment]
Well I was more thinking a screenshot of the setup. That sure is a throttled dynamo, but doesn't tell me a whole lot.

**Comment by KingLemming** [comment]
I think we debugged this one the other night.
