### ISSUE TITLE
Thermal Expansion -- Multiplayer Security Tab Issue -- Username Change

### ISSUE THREAD

**Issue by MadaxTheShadow** [CoFH/Feedback#242]
Hello everyone!

I recently changed my username, and so far I've been loving it and things have been dandy. The security tab doesn't seem to think it's dandy, though. When I place down a securified machine, strongbox in this particular case, it's registered under my old username. Seems reasonable, as servers still know my old name and such. The problem occurs when I go over to edit the settings.

I can't.

I'm not going to pretend to know why it registers it to the old name but won't allow me to edit it afterwards. I'm just glad I didn't upgrade the dang thing until I checked the settings. Hopefully it's not to much of difficult fix. Thanks guys! You guys rock.

== Edit ==
So I relogged into the server, and even though the strongbox still states it as being owned to my old username under the tooltip, the tab itself is now using my new username. I crafted a new strongbox to see if it's the initial crafting but it too seemed to work fine. Little confuzzled about why it didn't like me the first time around, but hey as long as it still works. Singleplayer never had an issue though, so I'm just posting this here since it did have a little trouble finding out who I was at first.

This may or may not be an issue with server recognition, but since I don't know for sure, you guys can just ignore this if it is.

== Using ==
FTB Infinity 1.2.1

Thermal Foundation 1.0.0RC3
Thermal Expansion 4.0.0RC2
CoFH Core 3.0.0RC2

**Comment by KingLemming** [comment]
Update to the latest release please. This has already been fixed.
