### ISSUE TITLE
World doesn't start up anymore

### ISSUE THREAD

**Issue by accessdenied0** [CoFH/Feedback#243]
Hi dear CoFH team,

I'm here to ask you for your help because, I updated to the newest version of TE, TD, RA and CoFH-core. Minecraft is starting up, pretty normal, but I'm unable to load the World up.

My fml_log says: http://puu.sh/glP1e/bafc67f242.log
(at the specific part: http://pastebin.com/LvVUMc4a)

I have to admit, I'm not sure if here is another mod involved, for example ModTweaker2... but the log isn't so clear at this point (my view).

I hope someone can support me a bit and thank you for your time,

access_denied

**Comment by KingLemming** [comment]
Well, you did find a piece of debug code that doesn't need to be there.

However, it's harmless if mods are doing things properly. What's happening there is that you have a mod trying to register a null itemstack as a furnace recipe.

That's all i've got for you. :( It's not us and I can't tell by the log who that's from.

**Comment by accessdenied0** [comment]
Hi KingLemming, 

thank you for your help... this sounds pretty nasty to figure out where it comes from... strangely I didn't get this problem with previous recommend Version...

Is there a better possibility to track the problem down, than disable any mod one by one?

Anyway I thank you very much for your help again,

access_denied

**Comment by Kazekitsune23** [comment]
For what it's worth I have this problem too. Been trying to track it down for seven hours which of my mods might do it. Found going back to the last release of Thermal Expansion stops it though. 

Here's my modlist minus today's updates from COFH if you want to compare them together. http://pastebin.com/Ex6zcc2m

**Comment by KingLemming** [comment]
Offhand there isn't a great way to fix this. I can remove the debug string and that *should* allow your world to load, but honestly that's really just hiding a much deeper issue.

There's an alpha build on CF that does this. I'm not crazy about it, but here ya go:
http://minecraft.curseforge.com/mc-mods/69163-thermalexpansion

**Comment by Kazekitsune23** [comment]
If it's any help, after many hours I figured out what mod in my list made me have this same issue. It was a mod called SmeltToIngots 1.1 1.7.10. Maybe you have something similar to that might be causing the hang up on world load. 

Ironically the dev verison with that mod in couldn't even get me to the main menu. It kept complaining about a wrench.

**Comment by KingLemming** [comment]
Hrm...have that log? I'd like to see that.

**Comment by Kazekitsune23** [comment]
Sure thing here you go. Got a pissed at the time with the same error I just put in only Cofh mods to see if I got this error again. http://pastebin.com/eGyZmRtb

**Comment by KingLemming** [comment]
Okay are you using dev jars in a non-dev environment? Because that looks like what is happening.
