### ISSUE TITLE
[EnderIO / Thermal Expansion] Flux Capacitors not charging held items

### ISSUE THREAD

**Issue by s0uthw3st** [CoFH/Feedback#243]
The Flux Capacitor doesn't seem to charge EnderIO items (have not tested with armor, but if it's a cross-mod interaction I'd guess it's the same fundamental issue). I've tested it with the Ender and with the Staff of Traveling - neither receive RF when the Flux Capacitor (using Hardened to test) on the hotbar is activated and set to Charging Held Items or Charging Armor and Held Items and the items are held.

Mod versions:
EnderIO 3.1.183
Thermal Expansion 5.1.1.93

**Comment by KingLemming** [comment]
Strictly speaking, not a bug. EnderIO no longer supports RF. I'll see what I can do though.

**Comment by s0uthw3st** [comment]
Gotcha, strange seeing as it's still labeled RF on their end - gotta stick to convention, I suppose.

**Comment by KingLemming** [comment]
Yeah. It's a bit annoying. Either way, cross-compat shouldn't be too hard.
