### ISSUE TITLE
[Thermal] Tesseract Low FPS

### ISSUE THREAD

**Issue by lekiller66** [CoFH/Feedback#244]
Hi,

Sorry i'm French and my English isn't good . Hum, so, I would like to know why Tesseract reduce FPS ? Do you have any idea/suggestion ? I don't understand why my FPS is low (10-30FPS) when i want to use a tesseract. I've understand that the Tesseract isn't a BUD and what should we do for solve the problem ?

Thx

**Comment by KingLemming** [comment]
You're playing on a potato.

Check your /config/cofh/core/client.cfg file and change

# Set to false to disable shader effects in CoFH Mods.
    B:EnableShaderEffects=true

to false

**Comment by lekiller66** [comment]
Thx to you Mr Lemming and have a nice day

Solved √
