### ISSUE TITLE
[Bug] Dynamos and Wrench.

### ISSUE THREAD

**Issue by EvilBastard** [CoFH/Feedback#244]
Just came across this on the WAPC Play Pack for dynamos when trying to rotate them.  When I made a new compression dynamo, placed it down and tried wrenching it, it would not rotate.  I then made a reactant dynamo and tried with it and it too would not rotate.  I can use the wrench to pick them up however.  So a normal right click does nothing, but shift+right click works as normal.

**Comment by KingLemming** [comment]
Literally only happens on WAPC server. Nowhere else.

Code isn't broken, but it's possible that another mod is catching the interaction event and force-cancelling it.
