### ISSUE TITLE
Server crash after startup

### ISSUE THREAD

**Issue by xpto2011** [CoFH/Feedback#245]
After updating all cofh mods to the latest version my server crashes a few seconds after starting up. Reverting back to older versions solves the problem. This only happen on multiplayer. 

Crash report: http://pastebin.com/FDkBaf7u

**Comment by KingLemming** [comment]
"Older" versions meaning what?

**Comment by xpto2011** [comment]
CoFHCore-[1.7.10]3.0.0RC2-195.jar
RedstoneArsenal-[1.7.10]1.1.0RC2-43.jar
ThermalDynamics-[1.7.10]1.0.0RC2-77.jar
ThermalExpansion-[1.7.10]4.0.0RC2-129.jar
ThermalFoundation-[1.7.10]1.0.0RC3-56.jar

**Comment by YuRaNnNzZZ** [comment]
Same issue, downgrading to previous version of the mods solve the problem
Server forge version: 10.13.2.1240 (Cauldron)
Crash report with same error: http://pastebin.com/CTyxCG8B

**Comment by nister6000** [comment]
I got the same error, server works for some time then crash.

**Comment by KingLemming** [comment]
And you have Cauldron, right? We may have to drop support at this point, since it's impossible to debug without Cauldron source.

**Comment by xpto2011** [comment]
I'm not using cauldron. I use the vanilla server with forge 10.13.2.1264
wait... do i have to update forge to 1291 right?

**Comment by skyboy** [comment]
Fixed in dev

**Comment by KingLemming** [comment]
He thinks.

**Comment by KingLemming** [comment]
New release out. Give it a test?

**Comment by Sunconure11** [comment]
Hm, it crashes with TickDynamic.

**Comment by Sunconure11** [comment]
The error is probably too long for pastebin. Any other alternatives I can use?

**Comment by Revemohl** [comment]
I thought about reporting this as well, but didn't because I thought it was something to do with my pack. But then again it is, maybe, since my crashes happen in single player, I'm using both Optifine and Fastcraft, and they don't happen when the world is loaded, instead crashing me after I walk away a bit from my base (so most likely after a certain chunk is loaded or tries to load).
Here's my crash log, just in case: http://pastebin.com/wnUGSK6r
Happened both with the versions from yesterday and the ones that came out today.

**Comment by Yolopanther12** [comment]
> Happened both with the versions from yesterday and the ones that came out today.

I am getting an identical error to the one you are getting ( http://pastebin.com/De73ScDr ). My server crashes whenever I disconnect from the game (I am the only player on the server) or when I go to another dimension (Mystcraft, Twilight Forest). This seems to be a problem with the Thermal Dynamics versions 1.0.0RC3-90 and 1.0.0RC4-91. Using version 1.0.0RC2-77 does not cause a crash to happen.

**Comment by Tora-B** [comment]
I'm getting [the same crash](http://pastebin.com/kuUdkQK7) in single player on travelling to the nether, and my server crashes within about a minute of starting it. However, if I immediately log into the server after starting it, it won't crash as long as someone remains connected to the server. This was happening both with ThermalDynamics-[1.7.10]1.0.0RC3-90 and ThermalDynamics-[1.7.10]1.0.0RC4-91.

**Comment by ouroboros8** [comment]
Also having this issue on my server. Here's my [crash log](http://sprunge.us/agdQ). Reverting to the versions mentioned above by xpto "resolves" it.
