### ISSUE TITLE
[Ender IO / Thermal Dynamics] Can't extract from Vacuum Chest

### ISSUE THREAD

**Issue by s0uthw3st** [CoFH/Feedback#245]
More cross-mod weirdness for you - attaching an Itemduct with a Servo and activating it does not extract items out of the Vacuum Chest's inventory. I tested the same network of Itemducts with a chest and a Servo and was able to extract items. 

I suspect it's a specific interaction with the Vacuum Chest because other Ender IO machines seem to work normally in terms of I/O using Itemducts - e.g. an Alloy Smelter can have its output extracted by a Servo even if the block face isn't assigned as an output.

Mod versions:
EnderIO 3.1.183
Thermal Expansion 5.1.1.93

**Comment by KingLemming** [comment]
This just sounds like weirdness on the part of the vacuum chest. As far as the machines go, is that actually standard behavior? Does EnderIO just always allow for extraction regardless of input/outputness?

**Comment by s0uthw3st** [comment]
I think you're right, I'll go bug that team instead. Looks like only their conduits work for extracting from it, just tested ExU2 transfer nodes and they didn't work either. Not entirely sure why that inventory's special.

As for the sidedness, it appears to be the default behavior for a side to act as an input and output for their blocks (just without automatically pulling/pushing from adjacent inventories), so there's nothing wrong there. If a side IS assigned, then that behavior takes priority (e.g. no inserting into a side marked "Push").

**Comment by KingLemming** [comment]
Interesting. Good to know.

Thanks much. :)

**Comment by s0uthw3st** [comment]
https://github.com/SleepyTrousers/EnderIO/issues/4257

Just a follow-up from the Ender IO folks, not sure if it's helpful for you long-term:

"Probably because the vacuum chest doesn't support CapabilityItemHandler.ITEM_HANDLER_CAPABILITY."

**Comment by KingLemming** [comment]
k yeah that's 100% on them then, hah.

**Comment by s0uthw3st** [comment]
Figured as much lol
