### ISSUE TITLE
Atonomous Activater issue

### ISSUE THREAD

**Issue by BuckitHead** [CoFH/Feedback#246]
After updating last night Atonomous Activater no longer works with Pickaxe of any kind.

Running Forge 1307
updated from 
CofhCoreRC2-195
CofhLib RC3-118
RedstoneArsenal RC2-43
ThermalDynamics-RC2-77
ThermalExpansion-RC2-129
ThermalFoundation-RC3-56

Updated to 
CofhCoreRC3-203
CofhLib RC3-120
RedstoneArsenal RC3-50
ThermalDynamics-RC3-90
ThermalExpansion-RC3-132
ThermalFoundation-RC4-58

**Comment by akvgergo** [comment]
Not just pickaxes. They seem to be completely unable to left click on anything.

**Comment by KingLemming** [comment]
It's a skyderp. Should be fixed; I'm going to test and be sure and have a release this evening hopefully.
