### ISSUE TITLE
Cannot assign colors to lumium lamps

### ISSUE THREAD

**Issue by Nagapito** [CoFH/Feedback#247]
Using thermal expansion 4.0.0RC1-119 - 4.0.0RC2-129 on FTB Infinity 1.2.1

After placing a lumium lamp, I cant assign a color to it. I Right click with the lapis lazuli but nothing happens. If then I break them and pick them they show up as black in the inventory and dont stack with the white ones. 
If I try to place it again, it shows as black on my hand and as soon its placed in the world it changes back to white. If I break it, it reverts to black.

**Comment by KingLemming** [comment]
Sneak right click with a multimeter.

**Comment by Nagapito** [comment]
Ok, multimeter, awesome! is there any way of copying one lamp settings and applying it to others? I have hundreds to configure the colour...
