### ISSUE TITLE
Recipe conflict Shiny ingots

### ISSUE THREAD

**Issue by Maokuma** [CoFH/Feedback#248]
Hi, there is a problem were platinum Ingots from metallurgy 4 with ExtraTic gives for example Shiny large plates from TConstruct. In the recipe it sees the shiny ingot as simply platinum for an odd reason.
Shiny ingots still gives shiny large plates. Thanks!

Using:
Forge 1291
ThermalExpansion-[1.7.10]4.0.0RC4-135
ThermalFoundation1.0.0RC4-58
CoFHCore3.0.0RC4-204
TConstruct-1.7.10-1.8.2a
ExtraTiC-1.7.10-1.0.3
Metallurgy-1.7.10-4.0.6.80
MetallurgyCore-1.7.10-4.0.4.18

**Comment by shadowfacts** [comment]
TF Shiny Ingots are "ingotPlatinum" in the OreDictionary, this behavior is intended.

**Comment by KingLemming** [comment]
Shiny is Platinum and vice-versa. The only real issue here is that if Platinum spawns very commonly, you trivialize a lot of Thermal's tech progression.

But it's a sandbox. Have fun.
