### ISSUE TITLE
Render Crash on Redstone Energy Fluxduct crafting pattern(Refined Storage)

### ISSUE THREAD

**Issue by Nicklorion** [CoFH/Feedback#248]
A render crash occurs whilst having a RefinedStorage Crafting pattern for the Redstone Energy Fluxduct
in your inventory.

Issue can be reproduced constantly
MC Version: 1.10.2
ModPack: FoolCraft 1.4.3
Refined Storage Version: refinedstorage-1.2.25
Thermal Dynamics Version: ThermalDynamics-1.10.2-2.0.0.32-universal

The Error message: 
The game crashed whilst rendering item Error: java.lang.NullPointerException: Rendering item

Full Error PasteBin: https://pastebin.com/0d9xUVPG

Kind Regards, Nicklorion

**Comment by KingLemming** [comment]
Outdated. Please update.
