### ISSUE TITLE
Cascading Worldgen

### ISSUE THREAD

**Issue by Serifina** [CoFH/Feedback#249]
I've been trying to create a world in 1.11.2 with the updated CoFH mods, but I keep getting out of control cascading worldgen, followed by the game dropping into a stopped state and refusing to load further. The log is located [here](https://paste.ee/p/ACgBy).

**Comment by KingLemming** [comment]
I dunno what to tell you there. :/ Doesn't happen in testing. Didn't even happen in FTB Beyond. If you have a ton of ridiculous generation already, you may have to tone down the oil gen.

**Comment by Serifina** [comment]
I have tried it without Lost Cities or Recurrent Complex as a precaution, and I set the oil gen back to default, and the clathrates I haven't adjusted. I have bumped the oregen up, but it's the same values I used in 1.10.2 without issue. I'll try adjusting things further and see if I can get better results.

**Comment by Serifina** [comment]
Something's definitely not right. [This log](https://paste.ee/p/etdfe) was created with literally just the CoFH mods loaded, nothing else, in a default world with default oregen configs. Also, there are some weird errors towards the end, including NoClassDefFoundError?

**Comment by KingLemming** [comment]
Hrm...let me see if our bedrock flattening broke somehow. I didn't explicitly test that because there's really no reason for it to ever have an issue.

**Comment by KingLemming** [comment]
Yep. Flat Bedrock is busted right now. Fascinating.

**Comment by Serifina** [comment]
I'm just glad it's found! Thanks.

**Comment by Serifina** [comment]
Just to verify for you - that definitely did it. I put my oregen configs back to where I like them (rather inflated), turned off bedrock flattening, and generated a world without any issue at all with all mods present.

**Comment by KingLemming** [comment]
Good news! I have a fix. :)

**Comment by Serifina** [comment]
Awesome. I'll just retrogen my bedrock in this world when it's out. Thanks for the help, KL.

**Comment by KingLemming** [comment]
npnp. Sorry for the inconvenience!

**Comment by Serifina** [comment]
It happens. That's part of why I update so quick, is to find this stuff and it can get fixed.
