### ISSUE TITLE
Fluxducts not connecting to EnderIO generators

### ISSUE THREAD

**Issue by the1upper** [CoFH/Feedback#250]
Your [fix](https://github.com/CoFH/Feedback/issues/231) corrected issues I noticed with fluxducts and generators for Actually Additions and RFTools generators. However, I'm still seeing issues connecting fluxducts to EnderIO generators. Fluiducts and itemducts connect to EnderIO generators fine. Additionally, fluxducts connect fine to every EnderIO machine I tested.

![eiofluxductex](https://user-images.githubusercontent.com/25512583/27239897-762113d6-5298-11e7-8952-333fedd4bae8.png)

Versions:
ThermalDynamics-1.10.2-2.0.4.6
ThermalFoundation-1.10.2-2.1.1.3
CoFHCore-1.10.2-4.1.4.7
EnderCore-1.10.2-0.4.1.66-beta
EnderIO-1.10.2-3.1.192

**Comment by KingLemming** [comment]
EnderIO is doing some *really* weird stuff with energy - I just took a look at their github.

I'm fairly confident that it's on their end.

**Comment by KingLemming** [comment]
Do other non-EnderIO things connect to them properly?

**Comment by KingLemming** [comment]
Okay, so managed to figure this one out. It's essentially a case of the capability being awful compared to the actual RF API.

With RF, there are two options - are you a receiver, or are you a provider? (You can be both, that's fine).

With the capability, it's, "Do you store energy, can you receive it, can I extract it?" None of those questions answers, "Do you generate it," so the *most* correct assertion (which worked for AA, obviously) is to use the, "can I extract it?" answer.

Well, EnderIO says no to that.

TL, DR: Capabilities suck.
