### ISSUE TITLE
Ticking Block Entity server crash

### ISSUE THREAD

**Issue by ouroboros8** [CoFH/Feedback#251]
Server crashed, and now crashes on start with java.lang.NullPointerException: Ticking block entity. [Full crash report](http://sprunge.us/gQBP). Possibly triggered by placing a resonant retreiver/toggling to whitelist mode a resonant receiver, if that's any help.

Versions:
CoFHCore-[1.7.10]3.0.0RC4-204
RedstoneArsenal-[1.7.10]1.1.0RC3-50
ThermalDynamics-[1.7.10]1.0.0RC4-92
ThermalExpansion-[1.7.10]4.0.0RC4-135
ThermalFoundation-[1.7.10]1.0.0RC4-58

**Comment by KingLemming** [comment]
Check with the new updates and let us know if it happens. I can't repro in dev so far.

**Comment by ouroboros8** [comment]
I'm afraid I restored a backup over the worldfile, so I can't check whether the update fixes it. My apologies: I'd been troubleshooting the server all day, and in my eagerness to get it back up ASAP I didn't stop and think to back up the crashing world. I'll update to the latest version and let you know if it happens again (will try to reporoduce steps leading up to it, too).

**Comment by ouroboros8** [comment]
Issue has re-occurred, definitely triggered by placement/configuration of a resonant retreivers.
http://sprunge.us/bTPN

**Comment by ouroboros8** [comment]
Correction to my original post: the server doesn't crash on start, but briefly after start. There's a 30sec or so period where I can log in.

**Comment by ouroboros8** [comment]
Some more details that may help:
The crash occurs shortly after connecting machines to a large Thermal Dynamics network (1200+ pipes) using a resonant receiver. There are 4 or 5 resonant servos also on the network, along with 3 other resonant receivers.

The Furnace mentioned in the crash report is a redstone furnace connected to the network using a resonant receiver in whitelist and use ore dict mode, but the crash occurs when I place *other* resonant receivers; in the most recent crash, I was connecting an induction smelter to the network. In the older one, it was a cyclic assembler.

I'm now checking whether the crash occurs if I disconnect the furnace from the network.

**Comment by ouroboros8** [comment]
When I remove the furnace, a slightly different crash occurs.
http://sprunge.us/PJWC

**Comment by ouroboros8** [comment]
This issue is re-occurring with the current versions:
http://sprunge.us/eHYB
