### ISSUE TITLE
[1.11.2] thermalfoundation:material doesn't show up in JEI

### ISSUE THREAD

**Issue by Partonetrain** [CoFH/Feedback#251]
Very odd. Tested in an instance with only CoFH Core 4.2.0.4-universal, JEI 4.5.0.287, and Thermal Foundation 2.2.0.2-universal.

In attached screenshot, enderium ingots, dust, and nuggets are missing, even with config option B:ShowDisabledEquipment=true
![2017-06-16_15 15 15](https://user-images.githubusercontent.com/19861808/27243300-d622c05a-52a6-11e7-9fc1-d44719b7cc9e.png)

**Comment by KingLemming** [comment]
Yeah, saw this myself but have literally no idea what the cause could be. Paging @mezz

**Comment by KingLemming** [comment]
This is apparently intentional on JEI's part.

See:
https://github.com/mezz/JustEnoughItems/commit/96b66f6788f464fd77445a38166e6a1ad722d9ff

I'm assuming that there is a config option for this. Either way, nothing I can do on my end except yell at @mezz. Sorry.

**Comment by Serifina** [comment]
There is a config option. In JEI.cfg, the following line:

    # Items with more than this many subtypes will not be displayed in JEI.
    I:maxSubtypes=100

Up that and items under thermalfoundation:material show up again.
