### ISSUE TITLE
Igneous extruder augment glitch

### ISSUE THREAD

**Issue by akvgergo** [CoFH/Feedback#252]
Someone is going to facepalm on this one. Changing the augments of an Igneous exxtruder will change the properties of all igneous extruders in that world.

This basic igneous extruder for example, will create 4 stone without any augmentation, because the other one next to it already has the augments(it shows 32, but the size of the tank is only enough for 4):
![2015-03-06_01 34 47](https://cloud.githubusercontent.com/assets/8812148/6518187/c00b2a1c-c3a3-11e4-9402-a1dc886fe963.png)
After I modify the augments it gets "refreshed" but, once again, this changes the augmentation worldwide. Here's a fully augmented resonant extruder with the settings of a basic one:
![2015-03-06_01 38 58](https://cloud.githubusercontent.com/assets/8812148/6518315/275315a8-c3a5-11e4-8efe-a3c537fda06e.png)
Note that these aren't just visual glitches. These machines will actually try to create as many materials as shown in their GUI.

**Comment by akvgergo** [comment]
Also, I'm using the up-to-date versions that came out a couple hours ago.

**Comment by KingLemming** [comment]
Hah. Awesome. It would appear that some rather basic functionality in Java does not work as advertised.

Fair enough.
