### ISSUE TITLE
[1.10.2+] CoFHLib/Core Suggestions

### ISSUE THREAD

**Issue by hextrace** [CoFH/Feedback#252]
**Suggestion:**  Global dimensional whitelisting/blacklisting for the config/cofh/world/ JSON files.
**Reason:**  Logical organization of custom WorldGen files and a reduction of a few bytes in file size due to repetitious fields being consolidated into one spot.  To be fair, this is a convenience request.

**Suggestion:**  Usage examples for some of the lesser used Generator Types and Distribution models.
**Reason:**  Trial and error is currently the only way to know if the objects are being defined properly.  _For instance, what should a properly defined Geode look like?  If I set the Crust and Filler information, am I still required to have the Block information?  If so, what should it look like if I'm making Applied Engineering Certus Quartz Geodes with Charged Certus Quartz in the center?_

**Comment by KingLemming** [comment]
Yes, documentation would be *wonderful.* I wish somebody would write it. I have enough work with the mod.

**Comment by hextrace** [comment]
I believe I haven't properly thanked you for your hard work.  Seriously, thank you for the hard work you've been putting in.  I realize my suggestions are QoL in nature, just figured I'd share them before I forget to ... again.

**Comment by KingLemming** [comment]
Thanks. :) And yeah, documentation is a sore spot for me. I really want an in-game book at some point. The website is just a pain that I don't want to deal with right now tbh...I'm trying to refactor things up for 1.12 and ensure that 1.10 and 1.11 are as bug-free as possible.

But yeah, at some point we'll have to do a 1.10+ website.

You are more than welcome to PR btw, if you're feeling froggy. It is one of our github repos.

**Comment by KingLemming** [comment]
Templates will be happening with world rewrite. Things will get revisited then, but no ETA.
