### ISSUE TITLE
[1.11.2] Thermal Expansion Causes Crash

### ISSUE THREAD

**Issue by Knighthawker1** [CoFH/Feedback#253]
When starting up Minecraft with CoFHCore and Thermal Foundation, Minecraft boots up as expected. However, Thermal Expansion causes the game to crash before it reaches the title screen. I've attached the text of the crash log to the link below.

https://hastebin.com/terocaduga.sql

**Comment by KingLemming** [comment]
Nope. Caused by another mod, not us. You have something registering a completely invalid recipe.

I've heard that it's Arcane Bags but don't 100% know if that's the only potential culprit.
