### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by Sailren** [CoFH/Feedback#253]
i have a neat request i have to tell ya, but it would be easier for me to talk to a german guy if u have one in your team, english would be ok too. i cant write it down here cuz its hard to explain for me. no idea if painting it would help either. is this possible to get in contact with one of you? later this day ofcourse, im on my way home, so crap internet here.

**Comment by KingLemming** [comment]
Go ahead and try here.

**Comment by Sailren** [comment]
ok then, would it be possible to change the dynamos to a way, that they shut themselves off, when they are not needed? and activate themselves again, when needed? example: i can set my pwm fans to a mode that they shut off, when the cpu is below a specific temperature, when i play a game, they turn on to keep up with the temp and shut down when not needed anymore, of course they start at low rpm and speed up when temp rises. so i dont know, magmatic dynamo starts at 8 rf speed up to maybe 40 rf to keep up with the power demand and shut down when not needed anymore, i feel this could be realistic/similar to a pwm fan for example, i didnt have any success in the last time to make a setup that works like this

**Comment by KingLemming** [comment]
Throttling is the best you're going to get, sorry. There's an augment in the works that may alter the throttle to 0, but there's no auto-shutoff, sorry.

**Comment by Sailren** [comment]
could this throttle to 0 work with the enderio engine control feature? the buildcraft gate feature begins to flicker really bad on the dynamos

**Comment by KingLemming** [comment]
No idea what that feature is. But if it throttles to 0, it never actually needs to shut off.

**Comment by Sailren** [comment]
that feature was "power requested?" give redstone signal, so when it goes to 0, no fuel usage?

**Comment by KingLemming** [comment]
Yeah, no ETA on that augment though and it might not happen.

**Comment by BoboSims** [comment]
I have a setup that does something similar. It's named BC pipes:

I have a Redstone Energy Cell (but it could be any type of Cell) that serves as a battery to power a small network of machines. The power generated by a Magmatic Dynamo (Redstone control set to active/high) is transported TO this cell through an Emerald Kinetic Pipe and a *single* Gold Kinetic Pipe. On the Emerald Pipe, there is a Standard Gate which is set to give a redstone sygnal only if power is flowing through the pipes. When the Cell is full, and thus the power stops flowing, the Gate stops no longer emits the restone sygnal, and therefor the Magmatic Dynamo shuts itself down, thus preserving Lava for when it's needed.

I can imagine this working with *ANY* type of Dynamo.

**Comment by Sailren** [comment]
thats sad, well we will have to live with 8 rf and a very little fuel usage,

**Comment by BoboSims** [comment]
Not necessarily... If you have an energy cell between the dynamo and the energy using devices, you could build a small logic circuit with two gates to toggle the dynamo on and off. On when the reserve in the energy cell is low, and off once the energy cell is fully charged again. That way, the dynamo would not trickle 8 rf continuously, but only provide large boosts to recharge the cell.

Or, provided that you have installed an energy cell, you could simply add a lever to manually switch on the dynamo when the battery is low. But we want it automated, don't we?

**Comment by KingLemming** [comment]
Will ship with 4.1. We didn't get a texture in time, sorry.

**Comment by Sailren** [comment]
really implemented? you are a hero

**Comment by BoboSims** [comment]
So I'm as bit late with my new solution to the issue. I have completely abandoned BC pipes, and set up a little RedNet network with a comparator reporting on the storage level in a buffer Energy Cell. If the comparator signals 9 or less (below 60% storage), the dynamos come on to charge it. As soon as the comparator reports 15 (full charge), the dynamos are immediately switched off. This ensures that no generated RF remains lingering in the dynamos' internal batteries where it would decay. I created this to make sure that not a single mB of *fuel* (any type) is wasted. But it would also completely stop the flickering of gates, because there **are** no gates :sunglasses:

**Comment by Sailren** [comment]
sounds fair

**Comment by BoboSims** [comment]
The circuits for this setup are simple too:

1. Less than or equal, I/O B orange, const 9, Vars 0
2. Greater than or equal, I/O B orange, const 15, Vars 1
3. SR-Latch, Vars 1, Vars 0, I/O B White

**Comment by Sailren** [comment]
i thought about something that shuts off on its own and turns on again, depending on the load, KL talked about the augment that his team implemented, well, lemme try to paint something, so i can show you what i mean

**Comment by BoboSims** [comment]
Doesn't this do that already? Once it's built, it can be totally self-reliant, making sure that the Energy Cell is always charged. From that Energy Cell (which I call a buffer), the energy is ofcourse sent to another (range of) Cell(s) that never get depleted, because the system kicks in well before that. Regardless of load, the system keeps you going.

You merely need to make sure that the number of available Dynamo's fits the average load. If your base constantly pulls 2kRF/t, a single dynamo without augments would never cut it, for example.

**Comment by Sailren** [comment]
im looking for something like this: http://abload.de/img/unbenanntssupt.jpg

**Comment by Sailren** [comment]
a system that turns on the dynamos dynamically depending on the load, a pulse width modulation for dynamos, u know

**Comment by BoboSims** [comment]
You want individual dynamos to be switched on/off based on actual need on-the-fly? Like if you use only 40RF/t, one dynamo is enough, while using 80RF/t causes 2 to run?

**Comment by Sailren** [comment]
You want individual dynamos to be switched on/off based on actual need on-the-fly? this is what im looking for

**Comment by Sailren** [comment]
my case fan can be set to, that he turns of when cpu is maybe under 40 degrees, he turns on at 45 degrees and speeds up to match the temp and shuts down again, when temp falls under 40 degrees again

**Comment by Sailren** [comment]
in theory this should be possible with dynamos and minecraft itself

**Comment by BoboSims** [comment]
Hmmm, yeah, my system could never do that, ofcourse. It works on a larger scale: when power is drained from the main bank, the buffer immediately replenishes it. And when the buffer is low, it will toggle the dynamos to compensate. :sunglasses: 

But I see your point.

**Comment by BoboSims** [comment]
NE-way, my system works *now*, without having to wait for the next release, and without having to build some - probably rather expensive - augment :sunglasses:

**Comment by Sailren** [comment]
yeah, its not very visible from the picture, but i think about something that can detect, is there load, how many dynamos do i need, and how much power should they produce

**Comment by Sailren** [comment]
not like buildcraft that turns on all engines, even just one is needed, and then maybe just 40 rf

**Comment by BoboSims** [comment]
THAT would be tough! A system that measures the current level of power drain and adjusts the number of dynamos working to compensate... I'm not even sure if the tools for that are available in the MC universe.

**Comment by Sailren** [comment]
well, ender io capacitor banks can show you how much power is drained, but then there is something missing that can control the dynamos dynamically

**Comment by Sailren** [comment]
first case: oh i need 500 rf, i have to turn on 7 dynamos, 6 on 80 rf and 1 on 20 rf,
 second case: oh no more load, shut them all down

**Comment by BoboSims** [comment]
Can these banks send a signal based on the load, though? If they can only show it on a meter or in an interface, that won't help much.

**Comment by BoboSims** [comment]
And you would still require an extensive program, maybe something that surpasses RedNet, and requires ComputerCraft instead.

**Comment by Sailren** [comment]
that would be something i could ask tterrag for, but if the would send a signal, how could this be used to control the dynamos, the ender io controller, can only turn them on and off, he cant set the rf to a specific number

**Comment by Sailren** [comment]
a computer could do this, but then he needs a interface so he can interact with the dynamos directly

**Comment by BoboSims** [comment]
Tha't my point exactly... you're asking for a very high level of precision, that is not easy to implement without heavily leaning on system resources.

**Comment by BoboSims** [comment]
What *could* be done, is to layer the RedNet system that I proposed: *not* just switch everything on the 40%/60% mark, but for every point that the Orange signal goes down, more dynamos are activated, each with their own channel-color.

**Comment by Sailren** [comment]
the idea i have now is this: i would look for an expensive TE block, that can manage all dynamos alone and can interact with them directly, a smart controller u know, then my pcture comes into place again

**Comment by BoboSims** [comment]
Should be **insanely** expensive. Not sure if that's ever happening... :smile:

**Comment by Sailren** [comment]
im ok if this would use nether stars and that greenish ingot from TE

**Comment by Sailren** [comment]
one controller to rule them all

**Comment by BoboSims** [comment]
And if it were available, I would probably never use it anyway. I have a sheaper solution, after all? :sunglasses:

**Comment by BoboSims** [comment]
RE: "One controller to rule them all": my system in a layered setup could do that, but it would require several expansions on the PRC to hold the necessary circuits and vars.

**Comment by Sailren** [comment]
hey skyboy, pls make something so PRC can use adhoc to communicate with each other

**Comment by BoboSims** [comment]
Hahahahahahaha!!!

**Comment by Sailren** [comment]
well a computer can do this too, but im a bad programmer, so something like a steves factory manager just for redstone control could be funny, these network PRCs and your system could work in theory together, they just cant set a specific rf value

**Comment by Sailren** [comment]
well, this should work almost like i want it, i will try out what im thinking right now and give you feedback

**Comment by BoboSims** [comment]
Sure they can! Or - more precisely - with the right amount of programming/tinkering, you can make it *mimic* that control very closely.

BTW: I *used to be* a reasonable programmer in several languages/environments, but nowadays I'm a bit rusty. I'm not even *trying* to get into Java/JS/Perl OR that stuff the Computercraft machines work with... I'm done doing that kind of thing.

**Comment by BoboSims** [comment]
I'm happy that you're willing to at least *try* my method. It may come close to what you're looking for, depending on what Energy Cell you use for buffer. Bigger Cells give higher reliability, but also much coarser control. On the other hand, they allow a greater influx, making more dynamos feasible.

At least, my method will not waste the tiniest drop of fuel; you'll get the most really useful energy from each mB of Lava/Oil/Fuel, or from every grain of (char-)coal.

**Comment by Sailren** [comment]
since dynamos are self regulating, we can skip the controller, i just need the 0 rf augment, no matter what lol, the only thing that is missing is the turn on and off thingy, i need to figure that out

**Comment by Sailren** [comment]
well with 0 rf augment and 0 fuel usage, i think this is what i'm looking for see KL message about this:

No idea what that feature is. But if it throttles to 0, it never actually needs to shut off., since they self regulate, i guess this is the thing im looking for,
