### ISSUE TITLE
Energy Cell Request more Triggers

### ISSUE THREAD

**Issue by kremsy** [CoFH/Feedback#254]
It would be amazing if the Redstone Energycell could provide more triggers to interact with buildcraft, for example <50% full, <75% like it is already with chests and other stuff in buildcraft.

**Comment by KingLemming** [comment]
BuildCraft should be providing these by default now I would think. It used to for energy storage.

**Comment by kremsy** [comment]
All I can choose when I place a Gate next to the energy cell are basic things like low energy stored and high energy stoed, but no values for 50% energy stored or something.

**Comment by KingLemming** [comment]
Check with BC and see if they'd be willing to add defaults, now that they use RF.

**Comment by KingLemming** [comment]
k, since asie will be adding it, closing this down.

**Comment by kremsy** [comment]
Still no progress :/.
