### ISSUE TITLE
[1.11.2] Render Item Crash

### ISSUE THREAD

**Issue by EPIICTHUNDERCAT** [CoFH/Feedback#254]
forge is 1.11.2 2315
ThermalDynamics-1.11.2-2.2.0.2-universal
CodeChickenLib-1.11.2-2.7.0.268-universal

https://pastebin.com/Jiaadnyf

**Comment by KingLemming** [comment]
What other mods do you have installed? :/

**Comment by KingLemming** [comment]
Okay, so what's happening here is that you have a mod which is registering blocks but isn't giving them a default state.

That is bad and it's their fault and they should feel bad. Unfortunately, there's no easy way to know exactly who is screwing it up. You could figure that out though by adding and removing groups of mods and narrowing it down.

It's something we can mitigate on our end, but we really shouldn't have to. :/

**Comment by KingLemming** [comment]
We've mitigated it in dev now.

**Comment by EPIICTHUNDERCAT** [comment]
thank you for the quick work Lemming, im still going to try to figure out what mod is causing the issue so it wont cause future errors with other mods.

**Comment by covers1624** [comment]
There wasn't any mod in particular, it was an invalid cover. So a mod was removed and there was a cover from one of those mods blocks.

**Comment by EPIICTHUNDERCAT** [comment]
then i know what mod it is, "Totem Defender" it was causing tons of issues with other mods on startup, all rendering related, once it was removed it fixed most, except Dark Utilities, that one had a rendering issue as well which was reported.
