### ISSUE TITLE
[Thermal Dynamics] Retriver On EnderIO Disabled Side Crashes

### ISSUE THREAD

**Issue by TheJulianJES** [CoFH/Feedback#255]
Crash: http://pastebin.com/B6Lsza0u
Forge: 10.13.2.1307
MC: 1.7.10
Version: Newest stable versions (curse) Newest alpha versions (curseforge)

Story:
I placed a resonant retriver on a impulse itemduct on a machine from EnderIO, the site was disabled so nothing should happen but the server crashed.

**Comment by KingLemming** [comment]
Fixed in dev but it's actually a very bad sign that this happened in the first place. Something is screwing with how ticks process.f

**Comment by TheJulianJES** [comment]
@KingLemming Is there a possibility to get this on CurseForge :D ? Also thank's for the fast fix

**Comment by TheJulianJES** [comment]
Also reproduceable with TE machines :D

**Comment by KingLemming** [comment]
http://minecraft.curseforge.com/mc-mods/227443-thermal-dynamics/files/2229835

**Comment by TheJulianJES** [comment]
Thank's @KingLemming!

**Comment by KingLemming** [comment]
You have a mod changing how ticks process on a pretty fundamental level. I'm not sure we can or should fix that.

**Comment by TheJulianJES** [comment]
@KingLemming Okay, I will try to remove some mods and figure out what mods does this...
