### ISSUE TITLE
[Thermal Dynamics] Fluctuating Itemduct Server Crash

### ISSUE THREAD

**Issue by fabm3n** [CoFH/Feedback#256]
If Items come in Fluctuating Itemducts Server Crashs http://pastebin.com/X7JxQray
Mods: 
CoFHCore-[1.7.10]3.0.0RC5-207
ThermalDynamics-[1.7.10]1.0.0RC5-94
ThermalExpansion-[1.7.10]4.0.0RC6-138
ThermalFoundation-[1.7.10]1.0.0RC4-58
Minecraft 1.7.10
Forge 10.13.2.1291

**Comment by KingLemming** [comment]
Unfortunately, you are incorrect. Fluctuating itemducts correctly accept items.

This is something different. Have a world save?

**Comment by TheJulianJES** [comment]
I also had this issue.

**Comment by nmarshall23** [comment]
I also have this issue. I think it happens when a Jabba barrel is both receiving an item from a TE Machine and has items feed into it from an ItemDuct. Or when sending round robin, items to a group of Botaina's RedString Containers.  I haven't been able to reliably recreate this bug, in a test world.

**Comment by TheJulianJES** [comment]
I had it with just TE machines.

**Comment by nmarshall23** [comment]
I think I know what's happening. This error is caused when two things try to change the same inventory space. I have a  botania Hopperhock picking up a lot of milk 10 buckets, and a servo's exporting those buckets, this setup will crash often.

If you need a world download, I will make one.

**Comment by TheJulianJES** [comment]
@KingLemming Is this the same issue: http://pastebin.com/JTm1AjzE ?

**Comment by KingLemming** [comment]
Jabba was recently updated to change some incorrect logic on their end. Try updating that.

**Comment by TheJulianJES** [comment]
Still not working.. Same crash D:

**Comment by skyboy** [comment]
@nmarshall23 We don't need a world download just yet, but we do need the crashlog you're getting; the one originally reported should be fixed.

**Comment by nmarshall23** [comment]
Interestingly, my game didn't crash when the input chest is connected to both Redstring dispensers and hoppers. But does crash when just Redstring dispensers are connected.

Here is the crash log: http://pastebin.com/S9Q53rPj

**Comment by skyboy** [comment]
Okay, that error appears resolved in dev.
