### ISSUE TITLE
Possible bug Tree Sap, fluid ducts, and tanks.

### ISSUE THREAD

**Issue by EvilBastard** [CoFH/Feedback#256]
I'm having an odd issue. Not sure if it's server side or what. The problem is that Sap does not seem to like flowing evenly into either a tank or fluid transposer.  When piping it into a tank it at times came out as resin. I am making sure to use just oak trees and the pipes do not connect to my resin pipes either.

![image](https://user-images.githubusercontent.com/24449157/27249655-2baa82b8-52e0-11e7-8314-42ae0c644f5b.png)

**Comment by KingLemming** [comment]
"Flowing evenly?"

What's that mean?

**Comment by KingLemming** [comment]
Also, that picture sure looks like Resin to me.

**Comment by KingLemming** [comment]
Ah, never mind. Got it. ;)

**Comment by EvilBastard** [comment]
Ahh okay.  Yeah, I found that when I went back to normal 1 block wide oak trees it fixed as well.  in the WAPC Pack, it allows for making normal oaks in a 2x2.  That might have been confusing the extractors.
