### ISSUE TITLE
Rendering crash viaducts: IndexOutOfBounds

### ISSUE THREAD

**Issue by tobiasvdp** [CoFH/Feedback#257]
e.

Time: 6/17/17 11:12 AM
_Description: Tessellating CCL block in world_

> java.lang.IndexOutOfBoundsException
> 	at java.nio.Buffer.checkIndex(Buffer.java:546)
> 	at java.nio.DirectByteBuffer.putFloat(DirectByteBuffer.java:893)
> 	at net.minecraft.client.renderer.VertexBuffer.func_187315_a(VertexBuffer.java:208)
> 	at codechicken.lib.render.CCRenderState.writeVert(CCRenderState.java:192)
> 	at codechicken.lib.render.CCRenderState.render(CCRenderState.java:172)
> 	at codechicken.lib.render.CCModel.render(CCModel.java:577)
> 	at codechicken.lib.render.CCModel.render(CCModel.java:565)
> 	at codechicken.lib.render.CCModel.render(CCModel.java:557)
> 	at cofh.thermaldynamics.render.RenderDuct.renderBase(RenderDuct.java:220)
> 	at cofh.thermaldynamics.render.RenderDuct.renderBlock(RenderDuct.java:394)
> 	at codechicken.lib.render.block.BlockRenderingRegistry.renderBlock(BlockRenderingRegistry.java:94)
> 	at codechicken.lib.render.block.CCBlockRendererDispatcher.func_175018_a(CCBlockRendererDispatcher.java:53)
> 	at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:199)
> 	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:100)
> 	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:43)
> 	at java.lang.Thread.run(Thread.java:745)

**Comment by KingLemming** [comment]
Is this 1.10 or 1.11?

**Comment by tobiasvdp** [comment]
1.10.2

**Comment by KingLemming** [comment]
Is it consistently happening, or it was just a one-off?

**Comment by tobiasvdp** [comment]
as soon as it loaded. Had to remove dynamics from the server to get past the first rendering frame on the clients.

**Comment by tobiasvdp** [comment]
(didn't happen instantly after placing. Just after a while, or maybe after a server restart.)

**Comment by KingLemming** [comment]
Quite odd. Can I get a full modlist please?

**Comment by tobiasvdp** [comment]
> ActuallyAdditions-1.10.2-r105.jar
> AdvancedRocketry-1.10.2-1.2.2.jar
> AkashicTome-1.0-5.jar
> appliedenergistics2-rv4-alpha-11.jar
> AutoRegLib-1.0-2.jar
> Avaritia-1.10.2-2.1.2.1-universal.jar
> BadWitherNoCookie-1.10.2-0.0.1-5418dde.jar
> Bagginses-1.10.2-3.0.4g.jar
> Baubles-1.10.2-1.3.11.jar
> BetterBuildersWands-1.10.2-0.11.1.220+f8232fe.jar
> BiomesOPlenty-1.10.2-5.0.0.2155-universal.jar
> BloodMagic-1.10.2-2.1.10-79.jar
> Bookshelf-1.10.2-1.4.4.347.jar
> Botania r1.9-341.jar
> BrandonsCore-1.10.2-2.1.7.102-universal.jar
> Chameleon-1.10.2-2.3.0.jar
> Chisel-MC1.10.2-0.0.10.22.jar
> chiselsandbits-12.12.jar
> CodeChickenCore-1.10.2-2.4.1.102-universal.jar
> CodeChickenLib-1.10.2-2.5.9.267-universal.jar
> CoFHCore-1.10.2-4.1.4.7-universal.jar
> CompactSolars-1.10.2-5.0.9.332-universal.jar
> compatlayer-1.10-0.2.9.jar
> CraftTweaker-1.10.2-3.0.25.jar
> creeperhost-1.10.2-1.2.4.jar
> CustomMainMenu-MC1.10.2-2.0.5.jar
> DarkUtilities-1.1.8.finalrc1.jar
> Decocraft-2.4.2_1.10.2.jar
> deepresonance-1.1x-1.4.8.jar
> Draconic-Evolution-1.10.2-2.0.12.222-universal.jar
> ElecCore-1.10.2-1.7.421.jar
> EnderCore-1.10.2-0.4.1.66-beta.jar
> EnderIO-1.10.2-3.1.183.jar
> EnderStorage-1.10.2-2.2.1.106-universal.jar
> extrautils2-1.10.2-1.4.1.jar
> ExtremeReactors-1.10.2-0.4.5.29.jar
> FastLeafDecay-v11.jar
> flatcoloredblocks-mc1.10-v4.4.jar
> foamfix-0.6.1-anarchy.jar
> forestry_1.10.2-5.2.17.376.jar
> FTBLib-1.1x-3.6.5.jar
> FTBUtilities-1.1x-3.6.5.jar
> GraveStone Mod 1.5.12.jar
> Guide-API-1.10.2-2.0.3-46.jar
> ImmersiveEngineering-0.10-58.jar
> immersivepetroleum-1.10.2-1.0.4.jar
> industrialcraft-2-2.6.210-ex110.jar
> inventorysorter-1.10.2-0.11.0+47.jar
> IronBackpacks-1.10.2-2.2.26.jar
> ironchest-1.10.2-7.0.15.804.jar
> IvToolkit-1.3.3-1.10.jar
> jeibees-0.9.0.5-mc1.10.2.jar
> jei_1.10.2-3.14.7.419.jar
> journeymap-1.10.2-5.4.6.jar
> JustEnoughResources-1.10.2-0.5.9.3.jar
> LibVulpes-1.10.2-0.2.5-22-universal.jar
> LLOverlayReloaded-1.1.1-mc[1.9-1.11].jar
> Mantle-1.10.2-1.1.5.jar
> mcjtylib-1.1x-2.3.11.jar
> MCMultiPart-1.4.0-universal.jar
> Mercurius-1.10.2-1.0.4.jar
> Morph-o-Tool-1.0-12.jar
> Morpheus-1.10.2-3.1.13.jar
> NotEnoughItems-1.10.2-2.1.3.220-universal.jar
> notenoughwands-1.1x-1.5.5.jar
> OpenComputers-MC1.10.2-1.6.2.7.jar
> p455w0rdslib-1.10.2-1.0.13.jar
> Pam's HarvestCraft 1.9.4-1.10.2h.jar
> Psi-r1.0-42.jar
> Quark-r1.1-70.jar
> Railcraft_1.10.2-10.1.2.jar
> rangedpumps-0.3.jar
> RedstoneArsenal-1.10.2-2.0.4.31-universal.jar
> refinedstorage-1.2.25.jar
> ResourceLoader-MC1.9.4-1.5.1.jar
> rftools-1.1x-6.01.jar
> rftoolsctrl-1.1x-1.6.8.jar
> rftoolsdim-1.1x-4.55.jar
> StorageDrawers-1.10.2-3.7.7.jar
> SuperCircuitMaker-1.0.4.jar
> TConstruct-1.10.2-2.6.5.jar
> theoneprobe-1.1x-1.4.7.jar
> ThermalDynamics-1.10.2-2.0.4.6-universal.jar
> ThermalExpansion-1.10.2-5.1.3.4-universal.jar
> ThermalFoundation-1.10.2-2.1.1.3-universal.jar
> Waila-1.7.0-B3_1.9.4.jar
> WailaHarvestability-mc1.10.2-1.1.9.jar
> Wawla-1.10.2-2.3.2.215.jar
> WirelessCraftingTerminal-1.10.2-0.1.29.jar
> woot-1.10.2-1.4.0.jar
> xnet-1.3.2.jar
> zerocore-1.10.2-0.1.0.6.jar
> ActuallyAdditions-1.10.2-r105.jar
> AdvancedRocketry-1.10.2-1.2.2.jar
> AkashicTome-1.0-5.jar
> appliedenergistics2-rv4-alpha-11.jar
> AutoRegLib-1.0-2.jar
> Avaritia-1.10.2-2.1.2.1-universal.jar
> BadWitherNoCookie-1.10.2-0.0.1-5418dde.jar
> Bagginses-1.10.2-3.0.4g.jar
> Baubles-1.10.2-1.3.11.jar
> BetterBuildersWands-1.10.2-0.11.1.220+f8232fe.jar
> BiomesOPlenty-1.10.2-5.0.0.2155-universal.jar
> BloodMagic-1.10.2-2.1.10-79.jar
> Bookshelf-1.10.2-1.4.4.347.jar
> Botania r1.9-341.jar
> BrandonsCore-1.10.2-2.1.7.102-universal.jar
> Chameleon-1.10.2-2.3.0.jar
> Chisel-MC1.10.2-0.0.10.22.jar
> chiselsandbits-12.12.jar
> CodeChickenCore-1.10.2-2.4.1.102-universal.jar
> CodeChickenLib-1.10.2-2.5.9.267-universal.jar
> CoFHCore-1.10.2-4.1.4.7-universal.jar
> CompactSolars-1.10.2-5.0.9.332-universal.jar
> compatlayer-1.10-0.2.9.jar
> CraftTweaker-1.10.2-3.0.25.jar
> creeperhost-1.10.2-1.2.4.jar
> CustomMainMenu-MC1.10.2-2.0.5.jar
> DarkUtilities-1.1.8.finalrc1.jar
> Decocraft-2.4.2_1.10.2.jar
> deepresonance-1.1x-1.4.8.jar
> Draconic-Evolution-1.10.2-2.0.12.222-universal.jar
> ElecCore-1.10.2-1.7.421.jar
> EnderCore-1.10.2-0.4.1.66-beta.jar
> EnderIO-1.10.2-3.1.183.jar
> EnderStorage-1.10.2-2.2.1.106-universal.jar
> extrautils2-1.10.2-1.4.1.jar
> ExtremeReactors-1.10.2-0.4.5.29.jar
> FastLeafDecay-v11.jar
> flatcoloredblocks-mc1.10-v4.4.jar
> foamfix-0.6.1-anarchy.jar
> forestry_1.10.2-5.2.17.376.jar
> FTBLib-1.1x-3.6.5.jar
> FTBUtilities-1.1x-3.6.5.jar
> GraveStone Mod 1.5.12.jar
> Guide-API-1.10.2-2.0.3-46.jar
> ImmersiveEngineering-0.10-58.jar
> immersivepetroleum-1.10.2-1.0.4.jar
> industrialcraft-2-2.6.210-ex110.jar
> inventorysorter-1.10.2-0.11.0+47.jar
> IronBackpacks-1.10.2-2.2.26.jar
> ironchest-1.10.2-7.0.15.804.jar
> IvToolkit-1.3.3-1.10.jar
> jeibees-0.9.0.5-mc1.10.2.jar
> jei_1.10.2-3.14.7.419.jar
> journeymap-1.10.2-5.4.6.jar
> JustEnoughResources-1.10.2-0.5.9.3.jar
> LibVulpes-1.10.2-0.2.5-22-universal.jar
> LLOverlayReloaded-1.1.1-mc[1.9-1.11].jar
> Mantle-1.10.2-1.1.5.jar
> mcjtylib-1.1x-2.3.11.jar
> MCMultiPart-1.4.0-universal.jar
> Mercurius-1.10.2-1.0.4.jar
> Morph-o-Tool-1.0-12.jar
> Morpheus-1.10.2-3.1.13.jar
> NotEnoughItems-1.10.2-2.1.3.220-universal.jar
> notenoughwands-1.1x-1.5.5.jar
> OpenComputers-MC1.10.2-1.6.2.7.jar
> p455w0rdslib-1.10.2-1.0.13.jar
> Pam's HarvestCraft 1.9.4-1.10.2h.jar
> Psi-r1.0-42.jar
> Quark-r1.1-70.jar
> Railcraft_1.10.2-10.1.2.jar
> rangedpumps-0.3.jar
> RedstoneArsenal-1.10.2-2.0.4.31-universal.jar
> refinedstorage-1.2.25.jar
> ResourceLoader-MC1.9.4-1.5.1.jar
> rftools-1.1x-6.01.jar
> rftoolsctrl-1.1x-1.6.8.jar
> rftoolsdim-1.1x-4.55.jar
> StorageDrawers-1.10.2-3.7.7.jar
> SuperCircuitMaker-1.0.4.jar
> TConstruct-1.10.2-2.6.5.jar
> theoneprobe-1.1x-1.4.7.jar
> ThermalDynamics-1.10.2-2.0.4.6-universal.jar
> ThermalExpansion-1.10.2-5.1.3.4-universal.jar
> ThermalFoundation-1.10.2-2.1.1.3-universal.jar
> Waila-1.7.0-B3_1.9.4.jar
> WailaHarvestability-mc1.10.2-1.1.9.jar
> Wawla-1.10.2-2.3.2.215.jar
> WirelessCraftingTerminal-1.10.2-0.1.29.jar
> woot-1.10.2-1.4.0.jar
> xnet-1.3.2.jar
> zerocore-1.10.2-0.1.0.6.jar

**Comment by KingLemming** [comment]
Does this happen to every client, or just a couple of them?

**Comment by covers1624** [comment]
Do you have any sort of FPS improvement mods? As this crash is purely related to the VertexBuffer not growing in size when almost out of space, its possible that some mod is breaking the VB in a way that does not cause this to happen. Also, what other blocks are in the chunk? And can we have the FULL FML-latest log file as that provides some other usefull info on the surroundings of the block that was rendering.

**Comment by tobiasvdp** [comment]
It happened to all clients I'm afraid. It was not a singular case. No fps improvers.
I've looked up the location of the specific block for you:
![image](https://user-images.githubusercontent.com/5156314/27261563-e2b300aa-5445-11e7-99d6-02cfac83474d.png)
It was on the edge of a chunk and the chunk also holds some ea2, and some botania stuff.

**Comment by KingLemming** [comment]
Does this happen with a viaduct in *only* that spot, or other ones are crashing on the server?

I'm having absolutely no luck replicating this nor is there anything in our code that indicates it's even a possibility.

**Comment by tobiasvdp** [comment]
Always same one in the crash reports.
It's very odd indeed.
When joining chunks are loaded from the right, so that shouldn't be the cause as well.
Last thing I can think of is that he is trying to render a crossing where only a straight line should be. Can the blocks end up in a bad state or is that impossible? But even that shouldn't cause an out of bounds exception.

**Comment by KingLemming** [comment]
Could you try with the latest builds and let me know what happens? I didn't directly try to fix this, as I have no idea wtf is wrong, but viaducts got a bit of an overhaul and this may have helped it.

**Comment by tobiasvdp** [comment]
Ok, I'll readd it to the pack. If it happens again I'll reopen this issue.
