### ISSUE TITLE
Server Crash - Game in invalid state

### ISSUE THREAD

**Issue by tjsd** [CoFH/Feedback#258]
Forge: 1291
Mod Versions:
CoFHCore-[1.7.10]3.0.0RC5-207.jar
CoFHLib-[1.7.10]1.0.0RC5-123.jar
ThermalDynamics-[1.7.10]1.0.0RC5-94.jar
ThermalExpansion-[1.7.10]4.0.0RC6-138.jar
ThermalFoundation-[1.7.10]1.0.0RC4-58.jar
Jabba-1.2.1_1.7.10.jar
MobiusCore-1.3.0_dev9_1.7.10.jar
StevesFactoryManagerA93.jar

Crash Report: http://pastebin.ubuntu.com/10553263/

What I think causes it:
I made a igneous extruder (using the new augments) outputting cobble to a Jabba barrel, setting up a compressed cobble program in steve's factory manager.

**Comment by KingLemming** [comment]
My guess is that this will only happen with that combination of mods. What is occurring should be literally impossible in the course of normal operation. I'm curious what SFM is doing in particular.

Basically if you look at the function name, it attempts to add to an occupied inventory slot. The error is that either the inventory is null or the ItemStack in the slot is null. Neither of those is actually possible. This is the first and only time we've ever seen this error, as it simply can't actually happen.

Unless SFM and/or JABBA is doing something *very* screwy.

I'll keep looking, but I think this is fundamentally unfixable, as we'd see this crash everywhere constantly all the time if the error were in our code.

**Comment by KingLemming** [comment]
This has been narrowed down. It's a multimod interaction but fundamentally something needs to change in Jabba. The code is paranoid and is firing tile changes at times when it is not appropriate to do so.
