### ISSUE TITLE
[Thermal Dynamics] Feature Request - New Ducts

### ISSUE THREAD

**Issue by Kava-Kal** [CoFH/Feedback#259]
We already have the bases covered for fluid and power, and items and power, but how about items and fluids? It could use the cryotheum-stabilized fluxduct model as a base, with fluids in the outer case. This could be particularly useful considering the reactant dynamo.

Additionally simple, regular fluiducts that render like the outer case of the cryotheum-stabilized fluxduct would be aesthetically appreciated, even if they have no benefit over the regular ones. This comes down to personal choice and the fact that very few mods seem to have "beefy" liquid pipes.

**Comment by KingLemming** [comment]
Yeah we've thought about one and you're not far off.

There are a few logistical issues with it. It's definitely on the todo.

**Comment by Kava-Kal** [comment]
Glad to hear! I'm looking forward to it already. I would say I can't wait but that would be a lie, I'm more than capable of waiting for a polished result! (College life = easy to wait for new stuff since you'll be busy until it's done anyways)
