### ISSUE TITLE
Not working on 1.11.2?

### ISSUE THREAD

**Issue by ELChris414** [CoFH/Feedback#26]
Thermal Expansion and CoFHCore not made for 1.11.2? Why?

**Comment by KingLemming** [comment]
Because they weren't. We're moving things up incrementally.

Also, this is an issue tracker, not a forum. Please don't misuse it for questions.

**Comment by ELChris414** [comment]
Yeah, sorry. This was just the quickest way to communicate with you.

**Comment by KingLemming** [comment]
No worries. Anyways, a 1.11 port is in the cards but it'll be a while. It's not a trivial thing.

**Comment by ELChris414** [comment]
Nice! Gonna test for any bugs now! TE is one of my favorite mods if it is not my favorite. Good luck with whatever you have in your future plans!
