### ISSUE TITLE
request (new ores and alloys)

### ISSUE THREAD

**Issue by Hypsellis** [CoFH/Feedback#260]
I wanted to suggest base metals and interesting alloys to add which would give more combination possibilities of use for the base metals.

- Metals
	- Zinc
	- Chromium
	- Mercury (liquid)
- Alloys
	- Brass (Zinc + Copper)
	- Red Gold (Gold + Copper)
	- White Gold (Gold + Nickel or/and Silver and/or Platetinum)
	- Pink Gold (Gold + Nickel or/and Silver and/or Platetinum + Copper)
	- Sterling Silver (Silver + Copper)
	- Sterling Platinum (Platinum + Copper  + potentially Silver)
	- Monel (Copper + Nickel)
	- Bell Metal (Copper + Tin)
	- Cuproaluminium/Aluminium Brass (Copper + Aluminium)
	- Nichrome (Nickel + Chromium)
	- Gun Metal (Copper + Tin + Zinc)
	- Mailechort (Copper + Nickel + Zinc)
	- Zamak (Copper + Zinc + Aluminium)
	- Amalgam (any metals mixed with Mercury except Iron or Platinum)

**Comment by EvilBastard** [comment]
My question would be, what would be the use of all of those extra alloys that the current ones don't already do?   Also among metals I think you meant Chromium.

**Comment by Hypsellis** [comment]
This is a good question.  I suppose they can be used already for making powerful weapons and armors, and after maybe extra stuff I haven't any ideas what it would be. I don't request to add all of them, I just give a list of the most popular and known ones, after the modders do what they want.

**Comment by KingLemming** [comment]
We've discussed a lot of these internally and ultimately we just don't have a need for them going forward, and we don't want to become another "Metallurgy" style mod.

Some of these might appear at some point in the future, but in general I think we have about all the metal we really need for now.

**Comment by Hypsellis** [comment]
Oh I understand, even if I'm a bit disappointed. I hope at least Zinc and Chromium and some alloys will come at one time.

About Metallurgy it didn't work really in the same way, it dealt with many fantasy metals and alloys, and it didn't add a lot of all the alloys I listed.
