### ISSUE TITLE
Crash when using fluid transposer injection with magma crucible

### ISSUE THREAD

**Issue by fscrivy** [CoFH/Feedback#261]
Detail:  

what i was doing was using the magma crucible to melt redstone then with the transposer full buckets after putting in a stack of buckets and then click the fill direction button the game freezes and crashes and im no longer able to load the world[it loads somewhat then freezes have to do a force shutdown of MC]

Log:

https://paste2.org/W9bCbx16

MC: 1.11.2
Forge: 13.20.0.2315
Pack: WyldBits - Version 2.0.20 [modified-added all the thermal stuff and Rftools dimensions plus updated all the mods in the pack ]

**Comment by KingLemming** [comment]
I can't actually make this happen, but I can confirm that the Fluid Transposer wasn't quite working the way it was supposed to.

**Comment by KingLemming** [comment]
There were a couple of different bugs related to Forge changing things with Fluid Containers, but I think I'm confident enough in saying that this should be resolved following the 5.2.1 patch.
