### ISSUE TITLE
[Usability] Fluid container usage behavior changed

### ISSUE THREAD

**Issue by maruohon** [CoFH/Feedback#262]
The behavior of adding the emptied version of (at least) buckets to the player's inventory has changed some time recently-ish (after mid-december at least...).

At the moment, when you empty, let's say a lava bucket, into for example a Portable Tank or an Igneous Extruder, the empty bucket will not stay in the same hotbar slot where you had the filled bucket. It will ALWAYS be put into another slot (I suspect via player.inventory.addItemStackToInventory()), unless you make sure there is NO other free slot in your inventory. This makes it extremely frustrating trying to manually fill fluid to TE4 machines using a bucket, as the bucket will jump around in the inventory, unless you fill your inventory with junk.

I first thought it might have been due to #189, but at least downgrading CoFHLib alone a couple of weeks back didn't change the behavior back to what it used to be. So unfortunately I'm not sure when the behavior changed exactly, as I haven't really played modded since last december.

**Comment by KingLemming** [comment]
I'll see what we can do. However:

"extremely frustrating"

Hyperbole does not endear people.

**Comment by maruohon** [comment]
I'm sorry if I used inappropriate language. Many of the subtleties of English are not that familiar to me, since it is not my native language. Anyway, that is more or less how I felt when I discovered this change yesterday while filling a Hardened Portable Tank with lava from a pool :D

**Comment by KingLemming** [comment]
It's not inappropriate, just that it's not quite that critical. It is actually a result of #189, but you can't selectively downgrade CoFHLib to change it. That doesn't work. Lib is included in Core.

**Comment by maruohon** [comment]
Oh ok.
I wasn't trying to imply that this is a critical issue, I just described my initial reaction to it when I discovered it. Sorry about the confusion. And thank you for looking into it, whenever you get the chance.

**Comment by KingLemming** [comment]
It's handled in dev now. It's sort of a compromise - it will attempt to stack buckets if you have other empty ones, but it'll stay in the same slot otherwise.
