### ISSUE TITLE
Suggestion: Augments

### ISSUE THREAD

**Issue by Andre-Maartens** [CoFH/Feedback#263]
I was recently testing and messing about TE and thought that for creative testing I can't really see the true potential of the machines without all the augments so my proposal is:
1) what about a creative only augment that acts as all augments of the same level
     e.g. a level 1 creative augment will act like:
     Integrated Servo Mechanism-,
     Integrated Modular Framework-,
     Integrated Redstone Circuit-,
     Transmission Coil Ducting-,
     Secondary Gearbox-,
     Secondary Transmission Coil-,
     Secondary Sieve-,
     Secondary Reception Coil- and
     Accelerated Extrusion Augments
   e.g a level 2 creative only augment will act like:
     Flux Linkage Optimization-,
     Flux Modulation Booster-,
     Stabilized Frame-,
     Overclocked Modular Gearbox-, and
     Igneous Catalyst Augments
  e.g. a level 3 Creative only augment will act like
     CryoCoil Regulator-,
     CryoCoil Flux Amplifier-,
     GyroServo Feedback-,
     Space-time Flux Unifier and
     Pyroclastic Generation Augments
OR
2) Level 1 Creative Only Augment:
    When Shift Right clicked whilst in hand will open a gui which has 9 slots which only accepts Basic and level 1 augments
   Level 2 Creative Only Augment:
  When Shift Right clicked whilst in hand will open a gui which has 5 slots which only accepts level 2 augments
  Level 3 Creative Only Augment:
When Shift Right clicked whilst in hand will open a gui which has 5 Slots which only accepts level 3 augments

Both Methods retain the "I need the previous level augment to work" Concept
although method 2 is customizable,
by adding these augments one could test more easily and design more extensive and intricate factories, plus who doesn't love OP machines?

**Comment by KingLemming** [comment]
Yeah that's not happening, sorry. Augs don't work that way under the hood and I'm not going to rewrite them just to make this possible.

**Comment by Andre-Maartens** [comment]
Okay just wondered if possible
Thanks for the response
