### ISSUE TITLE
Crash when extracting items from strongbox with a hopper

### ISSUE THREAD

**Issue by hottentottententententoonstelling** [CoFH/Feedback#264]
Hi,

I get the following error when placing a strongbox on top of a hopper:

https://pastebin.com/LpJga7Ru

Hopefully you can fix this :)

**Comment by KingLemming** [comment]
This 100% does not happen for me.

**Comment by hottentottententententoonstelling** [comment]
I tested this a little bit more and the problem only happens when I put a strongbox inside a dispenser and the dispenser places it on top of a hopper using vazkii's mod which tweaks the dispenser such that it places blocks or entities. The crash doesn't happen when the dispenser places the stongbox on a non-hopper block

**Comment by hottentottententententoonstelling** [comment]
Also, maybe I should open another issue for this, can you make it possible to dye the strongbox like you can do with shulkerboxes. Strongboxes make a really nice replace for shulkerboxes in 1.10.2 which is the main reason I installed thermal expansion.

**Comment by hottentottententententoonstelling** [comment]
I have tested this a little bit more and it seems to be a problem with the dispenser tweak mod from vazkii. Since this also happens to the hermitron boxes from the hermitron mod. I shall forward this problem to vazkii.

**Comment by KingLemming** [comment]
k, cool.

**Comment by hottentottententententoonstelling** [comment]
Do you plan adding dyable strongboxes to thermal expansion like shulkerboxes in 1.11+? I added thermal expansion mostly because of the strongboxes being a replacement for shulkerboxes.

**Comment by KingLemming** [comment]
I don't know tbh. I'll have to think on it.
