### ISSUE TITLE
Infinite rf power with cryo-stabilized flux ducts

### ISSUE THREAD

**Issue by VindictiveSoul** [CoFH/Feedback#264]
I was playing the latest FTB infinity mod pack and i found that if you completely surround an energy transfer node or hyper energy transfer node from extra utilities with cryo-stabilized flux ducts, then attach any power generating machine to the duct it starts producing infinite RF, you could even remove the generator, it still produces RF as long as the node is there.

**Comment by TheJulianJES** [comment]
Looks like #255

**Comment by KingLemming** [comment]
The latest FTB Infinity pack is ridiculously out of date. This doesn't happen with updated mods.
