### ISSUE TITLE
crash on Minecraft 1.11.2

### ISSUE THREAD

**Issue by Realever** [CoFH/Feedback#265]
hi
my game crash  since i used the newest version from you.here is the crash report: https://pastebin.com/BTjmsHZw

**Comment by thejams13** [comment]
My server and clients are having the same issue . The ic2 jenkins is down atm so now sure if just need new ic2.

Client- https://pastebin.com/ePKgjM33

Server https://pastebin.com/ExP5ws5Z

**Comment by juanmelk** [comment]
I disabled IC2 and had a similar issue but now coming from BuildcraftLib, so I'm pretty sure the problem is on CoFH's side.
https://pastebin.com/YLiCFsHy

**Comment by EmosewaGamer** [comment]
I don't have IC2, nor BC, but whenever I try to reload a previously created world, it gets stuck on "Loading Word". I don't have get a crash log, but in the latest log it says:
"Fatal errors were detected during the transition from AVAILABLE to SERVER_ABOUT_TO_START. Loading cannot continue".

 It only occurs on version 4.2.1.5 and not on 4.2.0.4.

**Comment by Terpo** [comment]
My report is also BC related: https://gist.github.com/Terpo/1bd4db593d9b6bd28f9822c4dd944ab2
Already opened an issue about it: https://github.com/BuildCraft/BuildCraft/issues/3675

**Comment by KingLemming** [comment]
Yeah, the "problem" is indeed here. But not exactly. I'm going to add a mitigation, but they really shouldn't be iterating the registry in that fashion. It's dangerous and irresponsible.

**Comment by AlexIIL** [comment]
@KingLemming are there any other ways of getting all fluid container items other that iterating over the entire item registry? While it would be possible to manually register all of the items from all mods that store fluids, that would be fairly unwieldy.

I'm also not convinced by the assumption that you control all itemstacks created with your items.

I can only speculate, but it looks like ic2 also assumes that they can create itemstacks for any item to test.

**Comment by juanmelk** [comment]
@KingLemming Sorry, It's easy to forget there's real people behind these mods, I didn't mean to imply anything negative towards you or your team. I really appreciate the great work you do and love your mods, and am really excited to be able to add them to the pack I am currently playing with my friends.

**Comment by thejams13** [comment]
just an update . I have updated my server and clients and all seems better less lag and no crashes as of this post. Thanks guys. My server and I really love your mods keep up the good work.
