### ISSUE TITLE
Dynamics 1.10 Viaducts Suffocation and Long Range Viaducts disconnection issues

### ISSUE THREAD

**Issue by JacobMuken** [CoFH/Feedback#268]
I tried the Viaductsout in Creative and everything was great, like really great, so obviously the next thing i did was install some in my lab in my survival world, (made completely of various Laboratory blocks from Chisel) I installed them along the middle of the ceiling, the blocks above the viaducts were clear but on the sides they had more lab blocks, and whenever i travel in them it acts like I'm inside a lab block (taking suffocation damage and a huge block decal in my face) the entire way, i recreated a section from my lab in the same creative world and i get the same result in creative, There are no blocks directly above the Viaducts because thats where my DE wireless power network is, I tried taking out surrounding blocks on all 8 surrounding sides to no effect, i don't understand but i assume this is just a glitch seeing as how the updated mod is only a few days old, so i hope this can be fixed because it kinda ruins the Viaducts for me, and that sucks because i really love them. 

Also whenever i leave and rejoin my creative world, the long range viaduct setup i have disconnects, every long range viaduct between the 2 linkers turns into a sphere, and the connection is broken, i need to fiddle with it every time to get it to work.

**Comment by JacobMuken** [comment]
I just solved my own mystery, the tubes treat you as if your standing on top of the block that the Viaduct occupies, if there is a block where your head would be (in my case there is an empty block directly above, and a laboratory block above that) then you will be treated as if your head is in that block! So i recommend that you offset the player's collision box by -2y so that your head is in the viaduct and then simply treat the viaduct as something that you can breath when your head is colliding inside it, like tall grass or torches (i assume that's whats causing the problem but I'm not familiar with minecraft's BTS)

**Comment by KingLemming** [comment]
Yeah, viaducts are a bit of a mess in general and MC 1.8+ really screwed things up with entities.

The fix is not *nearly* as simple as you think it is, unfortunately. I almost want to remove them entirely. It'd be less of a headache.

**Comment by JacobMuken** [comment]
Trust me when i say that i have complete faith in your abilities. Everybody has there at home mod, the mod they used first, love the most, and feel the most at home with, the one they want to use more than any other, and for me thats the Thermal Trilogy, Almost everything appears so simple and friendly, but its all so powerful and cool. I went through hell and back trying to add Dynamics to my modpack because everything was breaking just as i fixed the thing before it, on 2 computers, for 9 hours, all because i love your work so much that i was more then willing to do that. Imagine my overwhelming joy when i discovered Viaducts, the coolest way to get around minecraft that i have ever seen. I could just get an Enhanced Charm of Dislocation but i much prefer Viaducts... i'm going off on a tangent sorry, my point is, i love you and your work and i have full faith in your abilities, correct me if i'm wrong but you've set the standard in the modding community more than once. You more than got this. I believe in you.

**Comment by KingLemming** [comment]
So the long range duct disconnect is easily fixed, and has been in dev.

The entity collision boxes though? Possibly not fixable. Unsure yet.

**Comment by KingLemming** [comment]
Closing this down as I've fixed the disconnecting issue in dev, and apparently the suffocation one too. Will have updates out today.

As far as ducts "forgetting," this actually seems to be somewhat intentional behavior - clicking the Linking Duct forces a scan and loads the chunk. I've set up an issue which will serve as discussion for this: #277.
