### ISSUE TITLE
RSA Fluxed Electrum and Flux crystal damage

### ISSUE THREAD

**Issue by Biofusionz** [CoFH/Feedback#268]
Walking into the Flux Electrum and Flux Crystal blocks at head height creates suffocation damage.
The config option for these blocks to give damage are off, but they do still give damage at head height
![image](https://cloud.githubusercontent.com/assets/6354132/6543343/f9ba4442-c50f-11e4-872f-ae2bf5dc9242.png)

After a bit more testing, it seems there's an extra pixel layer somewhere. You are able to stand on and walk in midair when on them.
![image](https://cloud.githubusercontent.com/assets/6354132/6543353/58e79fa0-c510-11e4-9ffc-fe2e1aa65714.png)

**Comment by KingLemming** [comment]
To deal damage, the collision for the block has to be larger than the block.

I've toned it down a bit.
