### ISSUE TITLE
Launcher crashes when i add Thermal Expansion

### ISSUE THREAD

**Issue by Dazohan** [CoFH/Feedback#27]
Tried to add Thermal expansion along with CoFH and Thermal foundation to my modpack.

It simply wont work. Tried removing every other mod exept for Thermal Expansion, CoFH, Thermal foundation and the two "CodeChicken" ones. And i get the same crashreport. 

Maybe im doing something wrong? Im really not sure. 

Crashreport: http://pastebin.com/Lhmp3H0S

**Comment by covers1624** [comment]
Update CodeChickenLib from here: https://minecraft.curseforge.com/projects/codechicken-lib-1-8

**Comment by Dazohan** [comment]
That worked :) thanks a lot :)
