### ISSUE TITLE
Thermal Expansion crash on startup

### ISSUE THREAD

**Issue by tristan1301** [CoFH/Feedback#270]
Updated the COFH mods in my client, and it has crashed in this manner consistently since. No other changes made to either configs or mod updates/additions.

Crash Log: https://paste.ee/p/axTcL

**Comment by covers1624** [comment]
Duplicate of https://github.com/CoFH/Feedback/issues/265

**Comment by tristan1301** [comment]
I hate to push this, but if the mitigation was included in the updates from just over an hour ago, this is after those updates.
