### ISSUE TITLE
Any pipe can extract items from Input slot in machines

### ISSUE THREAD

**Issue by PanSzelescik** [CoFH/Feedback#271]
Any pipe (tested with item conduit and transfer node) can extract items from input slot when side is setting on blue, orange/blue or white color. Tested with Pulverizer and Redstone Furnace
Minecraft: 1.10.2
Forge: 2316
CoFH Core: 4.1.5.8
Thermal Expansion: 5.1.5.6
Modpack: SzelestPack Sky 1.13

Sorry for my English, for more Information please answer. Probably the error also occurs in 1.11.2

**Comment by KingLemming** [comment]
Yes, this is 100% correct and working as intended.

The limitation is that output slots cannot be inserted into, but there are valid reasons for wanting to automatically remove items from an input slot.
