### ISSUE TITLE
[Thermal Dynamics] Add config option to disable Facade system

### ISSUE THREAD

**Issue by Vexatos** [CoFH/Feedback#271]
I'd like to have a config option that completely disables facades being added to the game. I know I could disable them by removing the recipe for Structuralducts, but an option to make them not even load (and thus slightly decrease launch time) would be very convenient. Sometimes you just don't want your stuff to be hidden, and you don't want others to hide their things either. I think if you really want it, you should be able to disable facades simply because of this.

**Comment by KingLemming** [comment]
The way that the recipe is done, it literally wouldn't decrease launch time at all. We're talking opcodes.

The rest of that is valid though.

**Comment by KingLemming** [comment]
Alright. It's implemented for the reason of not letting people hide things.

The decrease in load time is exactly 0.0001 ns. Just how it works.

**Comment by Vexatos** [comment]
Well, thank you anyway. :+1:
