### ISSUE TITLE
[CRASH] Potential Mod Conflict - Thermal Expansion & Hammer Microblocks

### ISSUE THREAD

**Issue by hextrace** [CoFH/Feedback#272]
Crash Report:  https://paste.ee/p/6Wn7P
 
Observation:
Forge crashes on Phase 6 when loading mods with linked crash report.
 
Details:
When starting a newly built Curse profile with Thermal Expansion and Hammer Microblocks, Minecraft crashes before getting to the main menu.  Crash log indicates potential conflict between TE and HMB.  Crash is specfically caused by `Cannot set property PropertyEnum{name=variant, clazz=class net.minecraft.block.BlockPlanks$EnumType, values=[acacia, dark_oak]} to oak on block minecraft:log2, it is not an allowed value`.
 
Steps:
1. Create a new Curse profile with latest version of Forge
2. Use default downloads for Thermal Expansion & Hammer Microblocks
3. Launch new instance
4. Pour one out for your homies as the instance crashes out

Versions:
Forge:  13.20.0.2315 (and latest, at the time, version for 1.10.2)
Minecraft:  Both 1.10.2 and 1.11.2
Thermal Expansion:  1.11.2-5.2.2.3
Hammer Microblocks:  1.11.2-2b

Workarounds:
* Unsuccessfully attempted to identify potential solutions in *.cfg files
* Only option was to remove one of the mods (Hammer Microblocks)
* NOTE:  Hammer Core does not have a direct conflict with Thermal Expansion

**Comment by KingLemming** [comment]
Okay. That sure seems to me like they're doing something that they really should not be. Possibly overwriting the vanilla block, and that is bad terrible juju.

**Comment by hextrace** [comment]
I did drop a crash report to their issue tracker as well; included the report here in the event there may have been something overlooked. :)

**Comment by KingLemming** [comment]
Figured it out: #319.

Hammer needs to mitigate this on its end, as there is an explicit call to a deprecated / unsafe function and Mojang has a stupid block.

**Comment by hextrace** [comment]
Thanks for taking a peek at it. :)

**Comment by KingLemming** [comment]
Having said that, I'm also going to try and mitigate it on my end by checking for Mojang's stupid block.
