### ISSUE TITLE
Item duct spilling

### ISSUE THREAD

**Issue by fscan** [CoFH/Feedback#273]
I'm trying to automate AE2 inscribers with item ducts and filters. The inscribers allow only 1 of an item in the slot. The filters are configured to prevent over-sending. Sometimes it seem the servo sends another item before the previous arrives, this item is then dropped to the floor (or AE2 drops the item previously in the slot - i'm not sure). I did the same setup in another world with enderio conduits (same AE2 version) and they worked without problems).
Is this intended behavior? If yes, it would be nice to have something like a "overflow" filter to reroute items that have no destination. Or am i missing a feature/mechanic to avoid this?

ThermalDynamics-1.10.2-2.0.5.7

**Comment by KingLemming** [comment]
If the filters are in place, and oversending is disallowed, then it's on AE2's end. Basically the inventory is lying about how many slots are open, and then when we actually send the item to be inserted, it gets denied.

Take it up with AE2. I'll leave this here for the time being.

**Comment by fscan** [comment]
I had a look at the inscriber code. The ISidedInventory interface returns 1 as the stack limit. 
The problem seems to be that canInsertItem does not check this again. If i change the implementation to return false if any item is in the slot it works, but i dont really know if this is required by the interface. I will submit a PR to AE2 and see what happens.
TBH i'm surprised TD doesn't use capabilities, they should work in any case.

**Comment by KingLemming** [comment]
TD does use capabilities. Not really sure what you mean by that.

**Comment by KingLemming** [comment]
k, honestly I'm unsure why the Item Filter wasn't using caps (ducts do), and even more confused why it worked in the first place.

That's been rectified and tested now, but I still think AE should have proper implementation on their interface.
