### ISSUE TITLE
[SUGGESTION] Thermal Expansion - Caches and waila

### ISSUE THREAD

**Issue by kerts93** [CoFH/Feedback#274]
**Mod name**: Thermal Expansion
**Idea**: Make caches to use Waila to show it's insides like JABBA does. It's a bit annoying to use multimeter all the time.

Picture tells more than thousand words:
![Waila and JABBA](http://i.imgur.com/LABzsNS.png)

**Comment by KingLemming** [comment]
There's a reason for it though. The entire purpose of Caches is to prevent constant packet updates from displaying the number.

Doing it with WAILA means that the packets have to be sent.

**Comment by kerts93** [comment]
Maybe make it optional?

**Comment by KingLemming** [comment]
Yeah, the number isn't going to be optional. That's just packet spam nonsense waiting to happen.

The name is something you've already asked for in a separate request, so I'm closing this one down.
