### ISSUE TITLE
Thermal Foundation Forge Lexicon GUI Crash

### ISSUE THREAD

**Issue by nataliejean2412** [CoFH/Feedback#275]
Attempted to place a copper ingot from the [Embers mod](https://mods.curse.com/mc-mods/minecraft/251918-embers) into the Lexicon GUI and it immediately crashed. Ingot was missing after reload.

[Crash Log of Event](https://paste.ee/p/4foI5)

**Comment by KingLemming** [comment]
This will be awesome to track down I am sure. Thanks. :)

**Comment by KingLemming** [comment]
Yeah unfortunately it seems as though the 1.11 ItemStack change has broken the Lexicon in a completely strange way.

I've fixed the crash bug, but the orelist doesn't seem to sync from server->client anymore. Very odd.

**Comment by KingLemming** [comment]
The other issue has now been fixed in dev. Mojang decided to be stupid. (My shocked face: -_-) 

But it's all good now - the Lexicon items now have a "hover" effect unfortunately, but this is forced upon them by the game engine now. Boo hiss.

**Comment by nataliejean2412** [comment]
That's silly. Thanks for taking a look at this. I have missed the Lexicon for the last few versions, and got kinda sad when it crashed my client.

**Comment by KingLemming** [comment]
Oh well yeah, I wasn't gonna let it linger as an actual problem. :)
