### ISSUE TITLE
[SUGGESTION] Thermal Expansion - Caches

### ISSUE THREAD

**Issue by kerts93** [CoFH/Feedback#275]
**Mod name**: Thermal Expansion
**Idea**: Add option for caches to display item name also (right now you only see image). Maybe make and option to choose between: Item image only; item image + text; text only?
Just and idea.

**Reason**: When there are a lot of mods and a lot of similar items, it's quite hard to distinguish them.

**Comment by KingLemming** [comment]
See - *this* could maybe happen with WAILA, but displaying it on the face itself? No way, it can't fit.

**Comment by kerts93** [comment]
Roger that

**Comment by Revemohl** [comment]
Maybe you could make right clicking on a cache behave almost like using a multimeter on it does, but only telling the name of what's stored inside of it in the chat. The amount of items and lock state could remain as multimeter-only features in order to not make that item pointless.

**Comment by Tora-B** [comment]
Right-clicking on a cache that already has items in it puts any of the appropriate item in your inventory into the cache, even if you're right-clicking with an empty hand. So right-clicking is kind of being used already. Shift-right-click bypasses the interaction with the cache, resulting in the normal "use item" effect of the item, as is normal behavior with interactive blocks.

**Comment by Lordmau5** [comment]
I added this to the recent WAILA sources already. Once ProfMobius get's to fix remaining bugs and co. I assume he will build a new version.
http://puu.sh/guxWG/7e4a00b75b.jpg

**Comment by KingLemming** [comment]
I assume that requires WAILA on the server, correct? Because we don't send the number.

**Comment by Lordmau5** [comment]
![Image](http://puu.sh/guBwg/bd96dbc783.png)
It does, ye, unfortunately.

**Comment by KingLemming** [comment]
Unfortunate nothing. That's a good thing, we aren't going to be responsible for the extra overhead.

I suppose I can close this out now since WAILA is adding it. :)
