### ISSUE TITLE
Energetic Infuser Deleting items when output slot is full

### ISSUE THREAD

**Issue by zedekblue** [CoFH/Feedback#276]
Pack is FTB Beyond 1.8.1 (And tested on 1.9.0)
Images to replicate problem below.
Also tested on a machine with different/no augments whatsoever. Included them to speed up the process.

Mods/items tested with: Thermal Expansion, Simply Jetpacks 2, and Draconic Evolution
![2017-06-18_19 54 58](https://user-images.githubusercontent.com/17040113/27269982-507bd67a-5478-11e7-8c5a-a280b0a7507f.png)
First step is to fill up the output slot
![2017-06-18_19 55 03](https://user-images.githubusercontent.com/17040113/27269986-530b2a80-5478-11e7-9829-c0e3dd23e074.png)
Then throw something else in there without taking it out.
![2017-06-18_19 55 06](https://user-images.githubusercontent.com/17040113/27269987-549ca234-5478-11e7-8129-9068274a5362.png)
Putting a third item in will delete the second.
![2017-06-18_19 55 08](https://user-images.githubusercontent.com/17040113/27269988-55f3b1b8-5478-11e7-929b-0abf6dc39d53.png)
However putting a fourth item in will NOT.
![2017-06-18_19 55 11](https://user-images.githubusercontent.com/17040113/27269989-5723b100-5478-11e7-818e-ecabbe72c60c.png)
However taking the second/third item OUT...
![2017-06-18_19 55 15](https://user-images.githubusercontent.com/17040113/27269990-5910a018-5478-11e7-9055-6af749b5cd00.png)
The deletion can be replicated by putting a fifth item in.
![2017-06-18_19 55 18](https://user-images.githubusercontent.com/17040113/27269991-5ac47772-5478-11e7-8209-468d54b29f5f.png)
Now with TE Cells. Another bug showcased here, however may have been fixed in the newest Beyond release, is sometimes items will skip the charging step entirely.
![2017-06-18_19 55 37](https://user-images.githubusercontent.com/17040113/27269995-5e2edc4a-5478-11e7-9cdf-72df5d7637da.png)
We put a second item in and it proceeds to charge as usual.
![2017-06-18_19 55 42](https://user-images.githubusercontent.com/17040113/27269997-5fce7d9e-5478-11e7-9a85-639883c75232.png)
However, putting a third item in will NOT delete the 2nd until it is fully charged.
![2017-06-18_19 55 49](https://user-images.githubusercontent.com/17040113/27269999-61cc1dd6-5478-11e7-9abb-4f200092edb1.png)
Almost charged...
![2017-06-18_19 56 25](https://user-images.githubusercontent.com/17040113/27270001-636c02d2-5478-11e7-89d2-0f388c6dd4d1.png)
And it's gone.
![2017-06-18_19 56 27](https://user-images.githubusercontent.com/17040113/27270002-6516ecd2-5478-11e7-9a7c-53b1a4df4ec9.png)

If you have issues replicating I can provide detailed info regarding pack, server, and playerdata. Thanks.

**Comment by KingLemming** [comment]
I wasn't able to make this happen exactly as described here, but there were clearly a couple of issues with the Charger, including generally less-than-ideal handling of EnergyHandler objects.

That's been fixed. :)
