### ISSUE TITLE
[Crash] Thermal Dynamics 1.0.0RC5-94

### ISSUE THREAD

**Issue by Carbon-Key** [CoFH/Feedback#276]
Hello,

Had a string of strange issues that are centered around two different crashes.  I am running the mods here:  http://pastebin.com/igU63Sjy.  The first crash report can be found at http://pastebin.com/j8fAPDmK and the second crash, which occurred while trying to re-create the first, is at http://pastebin.com/tvWTJndT.  

The world in which the first crash occurred (the one with simulateInsertItemStackIntoInventory) crashes on load so I was unable to grab a screenshot of the exact setup I had that caused the crash.  Below is as close a re-creation of what I was doing as I could get, however I could not reproduce the first crash in a new world.  
![2015-03-08_16 46 23](https://cloud.githubusercontent.com/assets/10481639/6547752/c322dae0-c5b7-11e4-8c75-12300459818e.png)

The Extra Utilities node is feeding cobblestone into a JABBA barrel with a resonant servo on fluctuating item ducts leading out of it.  The initial crash happened within less than a second of switching the servo to ignore redstone and whitelist, in that order.  The two machines are Resonant Pulverizers.  

While trying to recreate the first crash I encountered the second crash (concurrent modification exception).  This one occurred in the same setup when I switched all faces of the pulverizer to disabled with a shift-click.  It also crashed with the same problem when I swapped the servo for a retriever and toggled white/blacklist.  This second crash, while it was server level, did not cause a crash loop like I am experiencing in my first world.  

Let me know what more info I can give you and I look forward to hearing from you soon.

**Comment by Carbon-Key** [comment]
My apologies for forgetting to mention it in my initial post; I tried replacing the barrel with a vanilla chest in the second world as I was trying to re-create the first crash and I still got the concurrent modification exception.

**Comment by skyboy** [comment]
The first crash can be resolved with an update to jabba.

**Comment by Carbon-Key** [comment]
I am running 1.2.1a, I was under the impression that was the most recent release.  I was speaking with taelnia from JABBA in #ThermalExpansion about that.

**Comment by KingLemming** [comment]
Try http://minecraft.curseforge.com/mc-mods/227443-thermal-dynamics/files/2229835

**Comment by Carbon-Key** [comment]
The concurrent modification crash seems to be resolved in the dev build.  However my first issue seems to still be occurring.  It looks like the same crash, but here is a fresh crash report in case anything has changed now that i'm on the dev build:  http://pastebin.com/MGUrciu7.  This is from the original world where I crash on load; should I be expecting any updates to fix this issue or should I be looking to delete the affected blocks with MCEdit and see if I have issues going forward?  I don't need to have the world back urgently so If you'd like I can keep trying new things on it or even send it to you somehow if you want to test on it yourself.  I can also continue my conversation with the JABBA people now that there is only one error to contend with, if you believe that the issue may be on their end.  Let me know what you'd like me to do, and as always thank you all for you quick responses.
