### ISSUE TITLE
[Thermal Dynamics] Localisation (Brazilian Portuguese)

### ISSUE THREAD

**Issue by LorenzoDCC** [CoFH/Feedback#278]
https://dl.dropboxusercontent.com/u/66533831/pt_BR.lang

I'd love to see it translated, and a bunch of other brazilians would, too :smile: 
I see no reason not to add it (unless you don't want to add it before the mod is a little more polished like Pahimar did with EE3).
Pretty please? :)))

**Comment by KingLemming** [comment]
We have a repo for that. Please submit a PR.
