### ISSUE TITLE
[1.11.2] Filled Thermal Foundation buckets doesnt get used up in crafting recipes 

### ISSUE THREAD

**Issue by 016Nojr** [CoFH/Feedback#279]
When you craft enderium blend with the normal crafting recipe, 1 Resonant Ender bucket, 1 platinum dust, 1 silver dust and 2 tin dust, everything is used up except for the resonant ender bucket, that isnt emptied. The same counts for the signalum recipe with the destabilized redstone bucket.

I am not playing on the latest version of the mod, but I went a few pages back in the GitHub pages and could not find the issue.

I am playing on a server with these mod versions:

Forge: 13.20.0.2315
CoFH Core: 1.11.2-4.2.0.4-universal
Thermal Foundation: 1.11.2-2.2.0.2-universal

**Comment by KingLemming** [comment]
This is a stupid issue caused by Forge + Mojang w/ the transition to 1.11.
