### ISSUE TITLE
[Redstone Arsenal] Armor and some tools are not enchantable in vanilla enchanting table

### ISSUE THREAD

**Issue by jaromero** [CoFH/Feedback#280]
I don't know if this is an intended change, but since at least version 1.0.0RC3, certain items can no longer be enchanted normally, i.e. with a vanilla enchanting table, an Enchanting Plus table, an Osmotic Enchanter from Thaumic Tinkerer, or seemingly anything that lets you pick an enchant, regardless of the RF charge level on these:

* All Flux-infused armor
* Flux-infused OmniWrench
* Flux-infused BattleWrench
* Flux-infused Sword

The vanilla table will not show any options in the UI, and the other two flat out refuse to accept the item in the slot. Machines that apply enchantments at random still work (tested with OpenBlocks' Auto Enchantment Table and MFR's Auto Enchanter). In addition, enchantments can still be applied to these items by using an anvil and an enchanted book, so this is more an inconvenience than anything, really.

Every other Redstone Arsenal tool works just fine (shovel, pick, axe, fishing rod, sickle and bow).

Forge version: 10.13.2.1291
CoFH Mods: (I was able to reproduce with just these and no other mods)

* CoFHCore 3.0.0RC5-207
* CoFHLib 1.0.0RC5-123
* Redstone Arsenal 1.0.0RC4-54
* Thermal Expansion 4.0.0RC6-138
* Thermal Foundation 1.0.0RC4-58

**Comment by KingLemming** [comment]
It's an unexpected side effect from an intentional change.

Vanilla is apparently stupid. I'll see what we can do.
