### ISSUE TITLE
Applying/removing covers causes fluxducts to lose their RF.

### ISSUE THREAD

**Issue by MonaMoonlight** [CoFH/Feedback#281]
I just discovered that covers causes all the fluxducts with residual capacitance to lose all their RF charge when applied or removed.

Was when I saw that the power cell wouldn't go above 12RF, despite none of the connected machines needing RF, that I started to suspect something fishy. So I checked the ducts, and found that they lost their charge when a cover was applied or removed.

Confirmed for the 1.10.2 and 1.11.2 version of Thermal Dynamics

**Comment by KingLemming** [comment]
Confirmed. Although, this really isn't a big deal. Are you relying on ducts for energy storage?

**Comment by MonaMoonlight** [comment]
I am relying on them to distribute power, without an unreasonable amount of loss.

The bigger issues with this relate to troubleshooting your RF duct networks, as well as losing a fair chunk of your ducts' total stored RF because you open the maintenance hatch, as it affects not only the duct that the cover is attached to, but every other duct that is part of the same cluster of ducts.

I mean, if you need to power something you just built, and you just so happen to realize you didn't place any ducts down for it to draw RF from, you're going to empty them all, each and every time you add/remove a cover.

With the Resonant Fluxduct, that amounts to a loss of 125 000 RF over five duct pieces.
If I cover all of them up while they're hooked up to an energy cell, it could go up to a 1 250 000 RF loss, just for covering two sides of each duct.

Even with lower level ducts, those smaller chunk losses add up to real amounts.

Now, I get that the best thing I can do is to reverse the flow of the current, get the RF to flow back into the energy cell before I start tinkering, but that isn't always an option.

I'm just saying, this issue had me running around like Charles McGill, trying to figure out why the power meter was still turning.
I thought it was a power loop I'd inadvertently created, or something.

Anyhow, I don't think I'm the only one who wants to mitigate loss of RF, especially early on when you are limited in what you can generate.
