### ISSUE TITLE
[TD] Retriever set to round-robin does not pull evenly from inventories

### ISSUE THREAD

**Issue by Tora-B** [CoFH/Feedback#282]
Versions:
CoFHCore-[1.7.10]3.0.0RC5-207
CoFHLib-[1.7.10]1.0.0RC5-123
ThermalDynamics-[1.7.10]1.0.0RC5-94
ThermalExpansion-[1.7.10]4.0.0RC5-137
ThermalFoundation-[1.7.10]1.0.0RC4-58

For reference, here's my testing setup:
![2015-03-09_06 19 23](https://cloud.githubusercontent.com/assets/11331588/6554712/456bad80-c624-11e4-8226-855f780c89ad.png)
In between tests, I pulled the retriever off the duct to reset the sequence.

The first cycle pulls one item from each inventory in turn, starting at the inventory closest to the retriever, but on the second and all subsequent cycles, it pulls twice from the first inventory, and once from each of the others. If you disable the connection to the first inventory (such as in #185), it will pull *twice* from the first available inventory (what was originally the second inventory) on the *first* cycle, and *three times* on subsequently cycles, still pulling once from the other inventories. If you disable the connection on the last inventory, it will then pull once from the first inventory on the first cycle, and three times subsequently. Disabling a connection somewhere in the middle will cause it to pull twice from the inventory after the disabled connection on all cycles.

This results in a growing disparity in the number of items pulled from each source. It appears to be counting connection points that are not valid for pulling, and pulling that number of times from the next available inventory. Perhaps it's also counting the connection that the retriever is mounted on, and that's why it pulls an extra time from the first available inventory on subsequent cycles.

**Comment by KingLemming** [comment]
That's exactly the reason. Unsure if it's fixable.
