### ISSUE TITLE
CoFHCore-[1.7.10]3.0.0RC5-207 cofh.command.CommandHandler no longer working

### ISSUE THREAD

**Issue by VenomFrog** [CoFH/Feedback#283]
Hello, decided to test out a 1.7.10 modpack im making and messing with permission, added a single line for cofh.command.CommandHandler and noticed its not working in this version, newest one. either OP'd or not.

**Comment by KingLemming** [comment]
Messing with permissions how?

Commands work. It's a question of how you're restricting/enabling perms.

**Comment by VenomFrog** [comment]
I guess it must be me then. Previous permissionsEX works by enabling - cofh.command.CommandHandler under my default group. :/ anyways my bad then

**Comment by VenomFrog** [comment]
My permissions work, its just this version of cofhcore

**Comment by KingLemming** [comment]
Well I'd still like to get to the bottom of it if you really can't get them to work.

But I do believe it's a matter of whatever mod you have managing them.
