### ISSUE TITLE
Psi Portable Tank Dup

### ISSUE THREAD

**Issue by DefiantZombie** [CoFH/Feedback#283]
When this Psi spell https://gist.github.com/DefiantZombie/6c6fe2a4d69904cd86a531dc47bd199d is used in a normal spell bullet to break a Portable Tank, the tank is duplicated.

Minecraft: 1.10.2
Forge: 12.18.3.2297
Psi: r1.0-42
Thermal Expansion: 5.1.6.8
Thermal Foundation: 2.1.2.4
CoFH Core: 4.1.6.10

Here's a Twitch client pack if it helps test faster: https://drive.google.com/file/d/0B8hEL3a43A9XUk9rTmxaNWkzYjg/view

**Comment by DefiantZombie** [comment]
Apologies for not noticing this before. Minecraft and java are not my forte for testing. One of the dups has 3 NBT tags attached to it.

I also forgot to mention that breaking tanks with fluids in them gives you one tank with and one without fluid.

**Comment by KingLemming** [comment]
Funny enough, this issue is also a duplicate. #140.

This is on Psi's end.
