### ISSUE TITLE
Flux-Infused OmniWrench *and* Crescent Hammer wonky

### ISSUE THREAD

**Issue by BoboSims** [CoFH/Feedback#284]
Yesterday, after updating Forge to version 1291, I updated all the TeamCoFH mods in the latest DW20 FTB modpack (for MC 1.7.10) with the latest releases from your site and installed Thermal Dynamics as well. 

TeamCoFH mod versions:
CoFHCore-[1.7.10]3.0.0RC5-207
CoFHLib-[1.7.10]1.0.0RC5-123
MineFactoryReloaded-[1.7.10]2.8.0RC8-86
RedstoneArsenal-[1.7.10]1.1.0RC4-54
ThermalDynamics-[1.7.10]1.0.0RC5-94
ThermalExpansion-[1.7.10]4.0.0RC6-138
ThermalFoundation-[1.7.10]1.0.0RC4-58

Other mod versions:
appliedenergistics2-rv2-beta-8
industrialcraft-2-2.2.691-experimental

Now I see the following strange behaviors from both RSA's Flux-Infused OmniWrench *and* TE's Crescent Hammer:

1. They can no longer pick up Applied Energistics blocks with a shift-right-click.
2. They *will*, however, pick up MFR's Paved Stone Bricks!
3. IC2's Macerators can even be picked up by a simple right-click *without pressing shift*.

**Comment by KingLemming** [comment]
1) The AE behavior is on their end.
2) Intentional.
3) This may be an IC2 change we don't know about.

**Comment by BoboSims** [comment]
No 1: Before the update, I was already using the latest AE2 version, and *then* those blocks *were* picked up. To me, that *seems* to indicate that it's not an AE2 issue. But if you say so (yes you do, I know :))
No 2: Intentional? Why? Don't we have pickaxes to break those blocks? Why would we need to use hammers/wrenches/screwdrivers to pick them up? They aren't exactly machines that could lose contents, charge or anything if you break them... they're just blocks.
No 3: Yeah, IC2 has always been e bit weird... I'm not a fan.

**Comment by KingLemming** [comment]
1) We did change something on our end and it's meant to be a concurrent change with AE2. It's possible they haven't pushed the corresponding update yet. Basically we don't ship the BC API anymore and they're shipping ours now.

2) Any block that implements a certain interface has this behavior. It works with hardened glass too. :)

3) Yup.

**Comment by TheJulianJES** [comment]
To fix the flux wrench issue on the redstone arsenal side, just add a !player.isSneaking to the check before rotating the block ;)

**Comment by KingLemming** [comment]
What flux wrench issue, Julian?

**Comment by BoboSims** [comment]
@KingLemming - 
1) I see. That makes sense, then. Thank you.
2) Ok. Makes me giggle to think of what interface a piece of pavement might need. But so be it. :)
3) Glad I'm not the only one who thinks so. :)

Anyway, thanks for your quick responses. I can live with these answers.
Oh, and thanks for Hardened Glass. I've built a blast chamber out of this glass, in which to produce compressed iron for pneumaticcraft (to concentrate the blast and prevent collateral damage). This stuff *truly* absorbed the hit without a scratch. Ender IO's Fused Quartz, which is supposed to be blast resistant, was completely destroyed in a similar experiment.

@TheJulianJES - 
What block are we trying to rotate?

**Comment by TheJulianJES** [comment]
@BoboSims Shift+Wrench AE2 blocks.

@KingLemming 
The flux wrench trys to rotate blocks, even while shifting
The AE2 only rotates block when the player is not sneaking, since AE2 blocks can be "wrenched" and rotated at the same time. AE2 wrench example:

https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/rv2/src/main/java/appeng/items/tools/quartz/ToolQuartzWrench.java#L59

In Redstone Arsenal it is probaly something like this:
````
Block localBlock = world.getBlock( x, y, z );
if ( localBlock != null) {
     *rotate code*
}
````
It should be:
````
Block localBlock = world.getBlock( x, y, z );
if ( localBlock != null && !player.isSneaking()) {
     *rotate code*
}
````

**Comment by BoboSims** [comment]
@TheJulianJES - That is what I'm *trying* to do: Shift+Wrench AE2 blocks. The point is that since the update, that no longer works.

Odd, that when we try to *pick up* some block, the code below our tool is trying to *rotate* that block. Must be some weird MC work-around-thingy: to light up the room, we must extinguish all lights. :-)

**Comment by KingLemming** [comment]
You know @TheJulianJES , RSA's code is visible. You can take a look there and not speculate. ;) And just because AE's wrench behaves a specific way doesn't mean we'll change ours to match it. Sneaking and rotating other blocks actually rotates them in the opposite order.

**Comment by BoboSims** [comment]
But how much work would it be to have one of your wrenches (and why not have it be the Flux-Infused one) mimic an AE Wrench's behavior *when applied to an AE block*? I mean, that tool *is* rather expensive to build and on top of that, it expands energy. I think that making it work like a true universal tool would justify all that.

Oh, and let me say that whoever came up with the idea of making that wrench double as shears, should be crowned Emperor of MineCraftia!

**Comment by TheJulianJES** [comment]
@KingLemming 1. Uppsss, I thought it was not ;)
2. I also will take a look into the AE2 code.

**Comment by BoboSims** [comment]
*DOWN*-grading AE2 from version 10 to pre9 seems to fix the wrench issue. Unless the even newer versions of the Team-CoFH mods are resposible. Either way, the wrenches work again!
