### ISSUE TITLE
Unlimited resource using Forestry Worktable

### ISSUE THREAD

**Issue by Renadarain** [CoFH/Feedback#284]
Hi :)

When using the Forestry Worktable to create Lumien Blend you have unlimited resources when shift-clicking - as in it does not remove the ingredients from the table.

MC: 1.11.2
Forge: 1.11.2-13.20.0.2315-installer
Cofh Core: 1.11.2-4.2.2.7-universal
T.E: 1.11.2-5.2.3.6-universal
T.D: 1.11.2-2.2.3.6-universal
T.F: 1.11.2-2.2.2.4-universal

Regards,
Renada

**Comment by KingLemming** [comment]
Cool. Better let Forestry know about that.

**Comment by Renadarain** [comment]
lol me or you?

**Comment by KingLemming** [comment]
You. You found it. :)

**Comment by Renadarain** [comment]
lol ok will do :) And thanks for updating T.E. it's a great mod :)
