### ISSUE TITLE
all the ducts are missing the arrows

### ISSUE THREAD

**Issue by tacoriffic926** [CoFH/Feedback#285]
![2015-03-09_23 06 46](https://cloud.githubusercontent.com/assets/3410249/6568621/117b0a06-c6b1-11e4-8a96-bfa85b7f6674.png)
After I wrench it it just vanishes I have try more the one wrench and all of the ducts.
I am on version [1.7.10]1.0.0RC5-94 and have tried 95 and It didn't fix it

**Comment by KingLemming** [comment]
Awesome. Maybe learn how the mod works please.

https://www.youtube.com/watch?v=75auVES_tKE
