### ISSUE TITLE
[1.11.2]  Errors in log

### ISSUE THREAD

**Issue by Endmateria** [CoFH/Feedback#285]
Getting error messages from your mod in my startup logs.  Doesn't crash server though.

MC 1.11.2
Forge 2315
CoFHCore-1.11.2-4.2.2.7

It's a couple of hits starting at line 1111.  I have about 75 mods installed server side, so if this is not enough info to deduce the problem, then I can remove mods/troubleshoot to isolate the cause/conflict.  Let me know.
 https://gist.github.com/Endmateria/adf8b2a6f6bb64f8190668e6d022c51e#file-fml-client-latest-log

**Comment by KingLemming** [comment]
Yeah that's just Forge complaining about something that isn't actually a problem. @API has been broken for a while and they know about it.

**Comment by Endmateria** [comment]
k, thanks for letting me know.
