### ISSUE TITLE
Suggestion: Viaduct Funnel

### ISSUE THREAD

**Issue by Pinaz9** [CoFH/Feedback#286]
As it stands, viaducts are really neat. However, they are somewhat clunky. You have to right click on the entrance, then find and choose your destination.
A much more immersive solution to the operation of viaducts might be funnels. A funnel goes on the end of the viaduct, and you shift right click to set the destination. Then, whenever you walk into or onto the funnel, you are automatically routed to the chosen destination immediately.

This also opens up the possibility of using viaducts for non-player mobs. You choose the destination, get the mob to the viaduct, and they are transported wherever.

**Comment by KingLemming** [comment]
Yeah, won't work for a variety of technical reasons right now, sorry.
