### ISSUE TITLE
(MC 1.10.2) Server Crash on startup with ThermalFoundation-1.10.2-2.1.3.5 and CodeChickenLib-1.10.2-2.5.9.267(and 255)-universal

### ISSUE THREAD

**Issue by zerisius** [CoFH/Feedback#287]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  SpongeCoremod (Z.spongeforge-1.10.2-2281-5.2.0-BETA-2394.jar)
  BookshelfLoadingPlugin (Bookshelf-1.10.2-1.4.4.347.jar)
  IC2core (industrialcraft-2-2.6.234-ex110.jar)
  CTMCorePlugin (CTM-MC1.10.2-0.1.1.16.jar)
  NEICorePlugin (NotEnoughItems-1.10.2-2.1.3.220-universal.jar)
  MalisisCorePlugin (malisiscore-1.10.2-4.4.0.jar)
  NWRTweak (redstonepaste-mc1.9.4-1.7.4.jar)
  SignPictureCorePlugin (SignPicture-1.10.2-2.7.1-universal.jar)
  CoFH Loading Plugin (CoFHCore-1.10.2-4.1.7.11-universal.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.66-beta.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.5.8.255-universal.jar)
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.7.0-beta1-anarchy.jar)
Contact their authors BEFORE contacting forge

// Shall we play a game?

Time: 23.06.17 14:00
Description: Exception in server tick loop

Missing Mods:
	CodeChickenLib : [2.5.9,)

net.minecraftforge.fml.common.MissingModsException: Mod thermalexpansion (Thermal Expansion) requires [CodeChickenLib@[2.5.9,)]
	at net.minecraftforge.fml.common.Loader.sortModList(Loader.java:285)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:536)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:328)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:121)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraftforge.fml.common.Loader.sortModList(Loader.java:285)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:536)

-- Sponge CauseTracker --
Details:
	Cause Stack: [Empty stack]
Stacktrace:
	at net.minecraft.server.MinecraftServer.handler$onCrashReport$zhn000(MinecraftServer.java:3937)
	at net.minecraft.server.MinecraftServer.func_71230_b(MinecraftServer.java:829)
	at net.minecraft.server.dedicated.DedicatedServer.func_71230_b(DedicatedServer.java:361)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:503)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_131, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2071217120 bytes (1975 MB) / 3099590656 bytes (2956 MB) up to 3099590656 bytes (2956 MB)
	JVM Flags: 2 total; -Xms3G -Xmx3G
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.3.2316 76 mods loaded, 76 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	U	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	U	FML{8.0.99.99} [Forge Mod Loader] (minecraft_server.jar) 
	U	Forge{12.18.3.2316} [Minecraft Forge] (minecraft_server.jar) 
	U	NotEnoughItems{2.1.3.220} [Not Enough Items] (NotEnoughItems-1.10.2-2.1.3.220-universal.jar) 
	U	spongeapi{5.2.0-SNAPSHOT-ab52c0c} [SpongeAPI] (minecraft.jar) 
	U	sponge{1.10.2-2281-5.2.0-BETA-2394} [SpongeForge] (Z.spongeforge-1.10.2-2281-5.2.0-BETA-2394.jar) 
	U	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	U	foamfixcore{7.7.4} [FoamFixCore] (minecraft.jar) 
	U	architecturecraft{1.7.3} [ArchitectureCraft] (ArchitectureCraft-1.7.3-mc1.10.2.jar) 
	U	backpack{3.0.1} [Backpack] (backpack-3.0.1-1.10.2.jar) 
	U	Baubles{1.3.11} [Baubles] (Baubles-1.10.2-1.3.11.jar) 
	U	baublesstuff{3.0.2} [Baubles Stuff] (baublesstuff-3.0.2.jar) 
	U	BiblioCraft{2.2.4} [BiblioCraft] (BiblioCraft[v2.2.4][MC1.10.2].jar) 
	U	BiomesOPlenty{5.0.0.2236} [Biomes O' Plenty] (BiomesOPlenty-1.10.2-5.0.0.2236-universal.jar) 
	U	bookshelf{1.4.4.347} [Bookshelf] (Bookshelf-1.10.2-1.4.4.347.jar) 
	U	Chameleon{1.10.2-2.3.0} [Chameleon] (Chameleon-1.10.2-2.3.0.jar) 
	U	chisel{MC1.10.2-0.0.11.25} [Chisel] (Chisel-MC1.10.2-0.0.11.25.jar) 
	U	chiselsandbits{12.14} [Chisels & Bits] (chiselsandbits-12.14.jar) 
	U	CodeChickenCore{2.4.1.103} [CodeChicken Core] (CodeChickenCore-1.10.2-2.4.1.103-universal.jar) 
	U	CodeChickenLib{2.5.8.255} [CodeChicken Lib] (CodeChickenLib-1.10.2-2.5.8.255-universal.jar) 
	U	ccl-entityhook{1.0} [ccl-entityhook] (CodeChickenLib-1.10.2-2.5.8.255-universal.jar) 
	U	cofhcore{4.1.7} [CoFH Core] (CoFHCore-1.10.2-4.1.7.11-universal.jar) 
	U	customspawner{3.10.1} [DrZhark's CustomSpawner] (CustomMobSpawner 3.10.1.jar) 
	U	customnpcs{1.10.2} [CustomNPCs] (CustomNPCs_1.10.2(25may17).jar) 
	U	PTRModelLib{1.0.0} [PTRModelLib] (Decocraft-2.4.2_1.10.2.jar) 
	U	props{2.4.2} [Decocraft] (Decocraft-2.4.2_1.10.2.jar) 
	U	mocreatures{10.0.6} [DrZhark's Mo'Creatures Mod] (DrZharks MoCreatures Mod-10.0.6.jar) 
	U	eplus{4.1.0.113} [Enchanting Plus] (EnchantingPlus-1.10.2-4.1.0.115.jar) 
	U	endercore{1.10.2-0.4.1.66-beta} [EnderCore] (EnderCore-1.10.2-0.4.1.66-beta.jar) 
	U	EnderIO{1.10.2-3.1.193} [Ender IO] (EnderIO-1.10.2-3.1.193.jar) 
	U	ExtraBitManipulation{1.10.2-2.3.4} [Extra Bit Manipulation] (ExtraBitManipulation-1.10.2-2.3.4.jar) 
	U	extrautils2{1.0} [Extra Utilities 2] (extrautils2-1.10.2-1.4.4.jar) 
	U	flatcoloredblocks{mc1.10-v4.4} [Flat Colored Blocks] (flatcoloredblocks-mc1.10-v4.4.jar) 
	U	foamfix{@VERSION@} [FoamFix] (foamfix-0.7.0-beta1-anarchy.jar) 
	U	hopperducts{1.4.8} [Hopper Ducts] (hopperducts-mc1.9.4-1.4.8.jar) 
	U	IC2{2.6.234-ex110} [IndustrialCraft 2] (industrialcraft-2-2.6.234-ex110.jar) 
	U	ironchest{1.10.2-7.0.15.804} [Iron Chest] (ironchest-1.10.2-7.0.15.804.jar) 
	U	JEI{3.14.7.419} [Just Enough Items] (jei_1.10.2-3.14.7.419.jar) 
	U	malisiscore{1.10.2-4.4.0} [MalisisCore] (malisiscore-1.10.2-4.4.0.jar) 
	U	malisisdoors{1.10.2-5.2.0} [MalisisDoors] (malisisdoors-1.10.2-5.2.0.jar) 
	U	mantle{1.10.2-1.1.5.205} [Mantle] (Mantle-1.10.2-1.1.5.jar) 
	U	Mekanism{9.2.2} [Mekanism] (Mekanism-1.10.2-9.2.2.301.jar) 
	U	MekanismGenerators{9.2.2} [MekanismGenerators] (MekanismGenerators-1.10.2-9.2.2.301.jar) 
	U	MekanismTools{9.2.2} [MekanismTools] (MekanismTools-1.10.2-9.2.2.301.jar) 
	U	multihotbar{2.1.3} [Multi-Hotbar] (multihotbar-1.10.2-2.1.3-build-T49.jar) 
	U	harvestcraft{1.9.4-1.10.2g} [Pam's HarvestCraft] (Pam's HarvestCraft 1.9.4-1.10.2h.jar) 
	U	redstonepaste{1.7.4} [Redstone Paste] (redstonepaste-mc1.9.4-1.7.4.jar) 
	U	xreliquary{1.10.2-1.3.3.664} [Reliquary] (Reliquary-1.10.2-1.3.3.664.jar) 
	U	ruins{16.2} [Ruins Mod] (Ruins-1.10.2.jar) 
	U	signpic{2.7.1} [SignPicture] (SignPicture-1.10.2-2.7.1-universal.jar) 
	U	simpleautoswitch{v1.3} [SimpleAutoSwitch] (simpleautoswitch-v1.3.jar) 
	U	StorageDrawers{1.10.2-3.7.9} [Storage Drawers] (StorageDrawers-1.10.2-3.7.9.jar) 
	U	tconstruct{1.10.2-2.6.5.10} [Tinkers' Construct] (TConstruct-1.10.2-2.6.5.jar) 
	U	thermalexpansion{5.1.6} [Thermal Expansion] (ThermalExpansion-1.10.2-5.1.6.8-universal.jar) 
	U	thermalfoundation{2.1.3} [Thermal Foundation] (ThermalFoundation-1.10.2-2.1.3.5-universal.jar) 
	U	Waila{1.7.0} [Waila] (Waila-1.7.0-B3_1.9.4.jar) 
	U	WorldEditCuiFe{1.0.7} [WorldEdit CUI Forge Edition] (WorldEditCuiFe-v1.0.7-mf-1.10.2-12.18.2.2125.jar) 
	U	changeskin{2.3.2} [ChangeSkin] (Z.ChangeSkin.jar) 
	U	crazyfeetsponge{1.5} [CrazyFeetSponge] (Z.crazyfeet-sponge.jar) 
	U	edisguise{0.5} [EntityDisguise] (Z.EntityDisguise.0.6.jar) 
	U	com.boydti.fawe{3.5.1} [FastAsyncWorldEdit] (Z.FastAsyncWorldEdit-forge110-17.06.09-0f3138e-713-13.0.17 (1).jar) 
	U	helpme{0.2.2} [HelpMe] (Z.helpme-5.0.0-0.2.2.jar) 
	U	holograms{2.2} [Holograms] (Z.holograms-2.2.jar) 
	U	nucleus{1.0.0-PR2-S5.1} [Nucleus] (Z.Nucleus-1.0.0-PR2-1.10.2-S5.1-plugin.jar) 
	U	permissionsex{2.0-SNAPSHOT-b147} [PermissionsEx] (Z.PermissionsEx-Sponge.jar) 
	U	pjc{0.1.0} [Project Core] (Z.project core-5.2.0-0.1.0.jar) 
	U	pjp{0.13.7} [Project Portals] (Z.project.portals-5.2.0-0.13.7.jar) 
	U	pji{0.10.0} [ProjectInventories] (Z.projectinventories-5.1.0-0.10.0.jar) 
	U	pjw{0.11.4} [ProjectWorlds] (Z.projectworlds-5.1.0-0.11.4.jar) 
	U	pvptoggle{1.2.0} [PvpToggle] (Z.PvPToggle-1.2.0.jar) 
	U	sayitem{1.1.0} [SayItem] (Z.SayItem-v1.1.0.jar) 
	U	timewarp{2.2.1-r6.0.0} [TimeWarp] (Z.timewarp-2.2.1-r6.0.0.jar) 
	U	universeguard{1.0} [Universe Guard] (Z.UniverseGuard.jar) 
	U	vigilate{1.0.2} [Vigilate] (Z.Vigilate-1.0.2.jar) 
	U	worldedit{6.1.4-SNAPSHOT} [WorldEdit] (Z.worldedit-forge-mc1.10.2-6.1.4-SNAPSHOT-dist.jar) 
	U	mcmultipart{2.0.0_88} [MCMultiPart] (MCMultiPart-experimental-2.0.0_88-universal.jar) 
	Loaded coremods (and transformers): 
SpongeCoremod (Z.spongeforge-1.10.2-2281-5.2.0-BETA-2394.jar)
  org.spongepowered.common.launch.transformer.SpongeSuperclassTransformer
BookshelfLoadingPlugin (Bookshelf-1.10.2-1.4.4.347.jar)
  net.darkhax.bookshelf.asm.BookshelfTransformerManager
IC2core (industrialcraft-2-2.6.234-ex110.jar)
  
CTMCorePlugin (CTM-MC1.10.2-0.1.1.16.jar)
  team.chisel.ctm.client.asm.CTMTransformer
NEICorePlugin (NotEnoughItems-1.10.2-2.1.3.220-universal.jar)
  codechicken.nei.asm.NEITransformer
MalisisCorePlugin (malisiscore-1.10.2-4.4.0.jar)
  net.malisis.core.util.chunkcollision.ChunkCollisionTransformer
  net.malisis.core.util.chunkblock.ChunkBlockTransformer
  net.malisis.core.renderer.transformer.MalisisRendererTransformer
  net.malisis.core.renderer.icon.asm.TextureMapTransformer
  net.malisis.core.util.clientnotif.ClientNotifTransformer
NWRTweak (redstonepaste-mc1.9.4-1.7.4.jar)
  net.fybertech.nwr.NWRTransformer
SignPictureCorePlugin (SignPicture-1.10.2-2.7.1-universal.jar)
  com.kamesuta.mc.signpic.asm.SignPictureTransformer
CoFH Loading Plugin (CoFHCore-1.10.2-4.1.7.11-universal.jar)
  cofh.asm.CoFHClassTransformer
  cofh.asm.repack.codechicken.lib.asm.ClassHierarchyManager
EnderCorePlugin (EnderCore-1.10.2-0.4.1.66-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
CCLCorePlugin (CodeChickenLib-1.10.2-2.5.8.255-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.CCL_ASMTransformer
Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.7.0-beta1-anarchy.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge,sponge'
	Type: Dedicated Server (map_server.txt)

**Comment by KingLemming** [comment]
...you clearly don't have CodeChickenLib-1.10.2-2.5.9 installed. The log shows 2.5.8.

**Comment by zerisius** [comment]
it happens with the latest available version of CodeChickenLib "CodeChickenLib-1.10.2-2.5.9.267-universal"
