### ISSUE TITLE
[1.11.2] Thermal expansion fishing rod not working

### ISSUE THREAD

**Issue by Ushupiuck** [CoFH/Feedback#288]
As it reads... it can be crafted, yet not used. trying to use it shows no string, nor anything else. Tried with copper fishing rod. It does plays the launching sound if you right click, tho
mod list:
![imagen](https://user-images.githubusercontent.com/12677854/27496724-96dbedfe-582d-11e7-8dfd-fb642f4bba0c.png)

**Comment by KingLemming** [comment]
Can't replicate this at all. Not sure what to tell you.

Just tested with the most recent versions on Curse and it 100% absolutely completely totally works.

**Comment by KingLemming** [comment]
Oh wait, 1.11!

Yeah, known. And this is on Forge's end. I've already submitted a PR, but there's nothing more we can do.

**Comment by Ushupiuck** [comment]
I do wonder what the issue is..? I mean, regular fishing rods don't have this problem.
By the way, are other similar tools affected by this too?

**Comment by KingLemming** [comment]
I know exactly what the issue is - that's why I made the pull request to Forge. ;)

And no, it's just fishing rods.

**Comment by Ushupiuck** [comment]
off topic sidenote, you should make a CoFH discord.

**Comment by Tahakk** [comment]
@Ushupiuck there is Twitch Channel (curse earlier)
