### ISSUE TITLE
Cryotheum is registering as liquid glass in liquid filters

### ISSUE THREAD

**Issue by PsionicArchon** [CoFH/Feedback#289]
I'm experiencing this issue on version: 1.0.0RC5-94

This is making it difficult to extract fluids from my AE network (Extra Cells) as I can no longer select a fluid to be exported. 

Example: http://i.imgur.com/7IOhc2j.png

Edit: Interesting. Only a bucket of gelid cryotheum registers as liquid glass. If I use a portable tank with the item filter it works perfectly.

**Comment by KingLemming** [comment]
We don't crossreference in any way, sorry. This is another mod registering Cryo as glass on our behalf, or it's a quirk with AE2.

Either way, it's not in our code.

Also, I assume tnat's an EnderIO filter? It's not our interface.
