### ISSUE TITLE
Weird UI dead zone

### ISSUE THREAD

**Issue by ELChris414** [CoFH/Feedback#29]
Very minor bug.

In the GUI of any machine the Information and Tutorial tab have a weird dead zone where it doesn't trigger the tab to close. That does not happen with any other tab, including the energy tab.
![2017-03-05_16 46 27](https://cloud.githubusercontent.com/assets/8685248/23588276/ca7908a6-01c3-11e7-83d0-51fa6ff62939.png)
![2017-03-05_16 46 30](https://cloud.githubusercontent.com/assets/8685248/23588277/ca7c48cc-01c3-11e7-9e07-2158d8d180d6.png)

**Comment by KingLemming** [comment]
Intended so that people manually clicking the upper arrow don't accidentally close the tab should they miss.
