### ISSUE TITLE
False Forge version

### ISSUE THREAD

**Issue by NilssMiner99** [CoFH/Feedback#290]
Hallo,

I have installed Forge for the 1.11.2 and CoFH is saying false forge version.
I have searched the forge reason what he need and it was for the forge version 1.12

CoFH Link: https://mods.curse.com/mc-mods/minecraft/cofhcore/2440019

http://prntscr.com/fnj2nc

**Comment by KingLemming** [comment]
....*sigh*. No. You're just straight up wrong.

**Comment by NilssMiner99** [comment]
i have found my mistake 😄.
I have installed 1.11 and not 1.11.2.
sry for this poste

**Comment by NilssMiner99** [comment]
I have insalled the forge version 1.11.2 - 13.20.0.2228 with the COFH version 1.11.2 - 4.2.3.8 
And it not work :/ can you pls help me.

Forge version: http://prntscr.com/fnlzp2
COFH version: https://mods.curse.com/mc-mods/minecraft/cofhcore/2440019
My ModPack: https://mega.nz/#!pF9FGS7R!GMUuPbeMjrtAekumYKaeLh4pc_dcXLrhxkjCXe1xqxU

Logs:
Latest: https://pastebin.com/06RgHTWC
fml client latest: https://pastebin.com/hWjrEvHt

**Comment by KingLemming** [comment]
The error screen is extremely clear - it requires 13.20.0.2315. Go download that version or higher.

**Comment by NilssMiner99** [comment]
Okay thanks it works
