### ISSUE TITLE
[Request] Additional Support for Sapling Infuser Augment

### ISSUE THREAD

**Issue by bookerthegeek** [CoFH/Feedback#291]
## Heyo ##
I do have a small suggestion for an added capability for the Sapling Infuser Augment. Mods this would benefit are listed, but not inclusively;
- [x] Industrial Craft 2
- [x] Natura
- [x] Pam's Harvest Craft
- [x] Rustic
- [x] Tinkers
- [x] Biomes O' Plenty
##### Not Possible due to NBT Data on Saplings. #####
- [ ] Forestry

##### Not Possible due mod not loading in a dev environment. #####
- [ ] Random Things
- [ ] Better with Addons

### What is the suggestion? ###
The ability to use any sapling with the ```Augment: Sapling Infuser```
### Why? ###
It seems that currently you can only use Vanilla Saplings, and one would expect to be able to use any sapling. Makes sense as it is called the Sapling Infuser, and not the Vanilla Sapling Infuser
***
That being said, love the mod and look forward to what you come up with next

As a side note, can I implement those recipes myself? I did see that you support IMC but as of today their is no way for a non modder (i.e. I don't know Java) to send those messages to your mod (That I know of). Did you have a mod in mind for pack makers to use when deciding to use IMC over Minetweaker that you would recommend?

**Comment by KingLemming** [comment]
I agree, and it's something I want to do. Unfortunately since Saplings aren't oredict'd, it's a non-trivial addition.

I'm going to see if I can add support for most, if not all of these.

**Comment by KingLemming** [comment]
BTW, a lot of these probably flat out aren't possible due to the mods using NBT data.

**Comment by bookerthegeek** [comment]
Hm... I noticed in JEI when looking up the recipies for logs that it shows the sapling. Could you use the same list that that information is pulled from?

**Comment by KingLemming** [comment]
Nope, unfortunately not. Certain calls are client-side only, which doesn't help me at all.

**Comment by bookerthegeek** [comment]
And since forestry trees use nbt to specify the sapling, that would not work as the machine can not tell what sapling it is so it cant produce tje correct wood log. Gotcha.

Ok, maybe then the mod authors could switch to something other rhen nbt, or you could add limited nbt support. I'll tag the specified mod authors when i get home and see if they would be willing to make their daplings compatible.

That you for the explanation.

**Comment by KingLemming** [comment]
Just wanted to let you know - I have managed to add support for Natura. Also for the Arboreal Extractor. :D

**Comment by bookerthegeek** [comment]
>Just wanted to let you know - I have managed to add support for Natura. Also for the Arboreal Extractor. :D
>>KingLemming 

Thank you! Thinking about it, how hard would it be to add at least the log to wood to plank recipe in the sawmill at the same time? If you like I can make a new issue for it.

**Comment by KingLemming** [comment]
I assume you mean log -> plank?

The sawmill already auto-adds everything - it has support out of the box. That's possible due to the nature of how the recipes exist. It does a blanket scan on the crafting manager and finds all of the log -> plank recipes.

**Comment by KingLemming** [comment]
Checking them off as I add compat. It's turning into a lot more than just the Insolator though - I'm writing entire plugins in some cases (Rustic / TCon).

**Comment by KingLemming** [comment]
Okay so I added support for HarvestCraft, but there's a catch.

Pam's fruit trees are all vanilla logs and leaves, with a bit of trickery. So instead of them providing wood, they produce fruit instead.

Otherwise it would be a mostly meaningless integration.

I pondered a fruit picker augment but frankly that just makes for a mess of conditionals.

**Comment by KingLemming** [comment]
Random Things is a buggy mess in dev. Can't get it to boot, so there's no real way to do an integration. Looking at the source code though, the tree is non-standard, so I can't really make it work anyways.

**Comment by bookerthegeek** [comment]
Sorry for all the extra work....

**Comment by KingLemming** [comment]
It's not a big deal, it's just very unfortunate that a lot of these mods are either non-standard or buggy.

Honestly, this is about as implemented as is possible at the moment.

**Comment by bookerthegeek** [comment]
Thank you. One more quick question. Both Pam's Harvest Craft & Rustic have drops from their trees. Pam's has fruit and Rustic a secondary leaf drop. Any way to get those in also since you're doing a bunch of tree stuff?

**Comment by KingLemming** [comment]
That's a machine rewrite, I'm afraid. So probably not for < 1.12.

For Pam's, I'm already just providing the fruit and not the logs, since they're fruit trees and the logs are nothing special.

Rustic is tricky.

**Comment by KingLemming** [comment]
Added BOP Support in 1.12 going forward. ;)

**Comment by lumien231** [comment]
RT, TE &  the 7 required dependencies work fine for me in dev. Maybe you could send me your crash report?

If you do add support from the TE side 1x"spectreSapling" -> 4x"spectreLog" + 1x"ingredient"(meta:2) with a secondary chance of 5 would be my suggested recipe. (Used InsolatorManager.addDefaultTreeRecipe to test that so i guess the chance is 5/100/150)

**Comment by KingLemming** [comment]
Sure thing, here you go:

https://pastebin.com/0cffcY26

I can't make heads or tails of it, but I'm just taking your jar and dropping it into /mods.

**Comment by KingLemming** [comment]
So, Better with Mods / Addons also does not load in a dev environment.

Which means at this point, I'm done for now. ;)
