### ISSUE TITLE
Destabilized redstone ore

### ISSUE THREAD

**Issue by Renadarain** [CoFH/Feedback#292]
Hi :)

This is probably a really daft question but you please tell me how to pick up the ore blocks? Hovering over the block TheOneProbe says it needs a pickaxe with power 7.  Do I need to install Redstone Arsenal in order to pick up these blocks? 

Also, is there any way to pick up the liquid running all over the place after breaking a block?

Thanks for your help :)

Regards,
Renada

**Comment by KingLemming** [comment]
TOP is wrong about that, not sure why. Any level pickaxe will break the block, but to pick it up, you need Silk Touch. :)

And no, you can't stop the fluid escaping. That's a visual cue to let you know you're being wasteful.

So, Silk Touch!

**Comment by Renadarain** [comment]
I just tried a diamond pickaxe with silk touch and it broke the block and I floated down the hill in a stream of liquid redstone lol

Does it need to be a Thermal Expansion pickaxe with silk touch?

**Comment by KingLemming** [comment]
The fluid still happens regardless, but the block correctly drops itself and not the Clathrates.

**Comment by Renadarain** [comment]
Oh gosh so it does, blonde moment, or senior moment - or maybe both lol

Thank you :)
