### ISSUE TITLE
Ticking block entity crash Direwolf20 modpack

### ISSUE THREAD

**Issue by idealjo** [CoFH/Feedback#293]
Hello

Since the last update of the Direwol20 modpack, I got a crash instantly after the world loading

crash report
https://pastebin.com/EufBvasz

I tried with all the lastest COFH mod update, still nor working

**Comment by KingLemming** [comment]
That line doesn't correlate to anything in the actual method.

This is basically tech support and not an actual mod issue, sorry.

The only advice I have for you is to use an NBT editor to remove the reactant dynamo from your world, since something apparently gave it an invalid item or fluid.
