### ISSUE TITLE
Cyclic Assemblag

### ISSUE THREAD

**Issue by ShadwDrgn** [CoFH/Feedback#293]
![2015-03-11_23 04 29](https://cloud.githubusercontent.com/assets/2470781/6611558/d9aa89fa-c843-11e4-91e0-2cbb299494cd.png)
Holy god @ chunk updates. :~(. I am being silly by assuming this is the CA's since that's the last thing I added prior to getting this problem. My FPS is also normally over 100 until i added them. I suppose it could be the item nodes from ExU but i assume the CAs are causing it due to the animated texture being linked to the 1 per tick crafting operation. Perhaps loop through the CA's inventory to determine how many operations could be performed given it's contents and do it all in one go up to 20 operations a second once per second only? not sure if this would be possible, but it'd sure help if it is. Alternatively this might not even be your problem. This is a basic cobble compressing assembly with 3 nodes with 64 world interaction upgrades each.

**Comment by KingLemming** [comment]
This isn't on us. Take a look at how the Assemblers actually animate before assuming please.

TE machines do not update their animations any faster than once per 10 seconds. So the 1/tick crafting has literally nothing to do with this.
