### ISSUE TITLE
[DUPE] MineFactory

### ISSUE THREAD

**Issue by sanyashvets** [CoFH/Feedback#294]
https://www.youtube.com/watch?v=Qe0Gn44m77E&feature=youtu.be
CoFHCore-[1.7.10]3.0.0RC5-207
MineFactoryReloaded-[1.7.10]2.8.0RC8-86

**Comment by skyboy** [comment]
Fixed by https://github.com/skyboy/MineFactoryReloaded/commit/b44e84496c2628c8f8129cf9a528bd662d0883e6
