### ISSUE TITLE
Break/Stop the Blizz/Blaze peace

### ISSUE THREAD

**Issue by Ushupiuck** [CoFH/Feedback#295]
Blizzes and blazes are supposed to be hostile against each other... could this come back? They're opposed elementals, after all!
Extract outright from the wiki:
[...] When they see a player or a Blaze, they start flying and attacking. Blizzes attack by shooting several icy bolts that can apply a slowness effect in addition to dealing damage. [...]
Blizzes do more damage to entities that are marked 'immune to fire', like most mobs from the Nether. "

**Comment by KingLemming** [comment]
This was removed due to fundamental changes in Minecraft AI. It's unfortunately computationally irresponsible to bring it back, sorry.

I'm aware of what the wiki says, but it's out of date. I don't have time to handle both the mod and the website.
