### ISSUE TITLE
Issue: MFR Mob Essense not working with Reactant Dynamo

### ISSUE THREAD

**Issue by AnthonyKane5528X** [CoFH/Feedback#296]
FYI:  Reported to MFR first.  Skyboy advised that this should go to CoFH.
CofHcore: 1.10.2-4.1.7.11
Thermal Expansion: 1.10.2-5.1.6.8
Minefactory Reloaded: [1.10.2]2.9.0B1-220

Issue:
-Attempted to pipe "Mob Essense" into a Thermal Expansion Reactant Dynamo.
-Mob Essence FAILS to pipe into dynamo. The block will not accept it.
-Went into the CofH configs for Thermal Expansion.

Tried all the following:

  * mobessence
  * mob_essence
  * essence

Nothing worked to get Thermal Expansions Reactant Dynamo to take Mob Essense fluid.

Please also note: Fluid itself registers as Mob Essence in JEI. Under the "Forge Bucket" it shows as "Essence". The Metadata name is mob_essence.

**Comment by KingLemming** [comment]
Correct. Mob Essence is not a viable fluid in the dynamo.

The reactant dynamo changed. It requires specific reactions now and you cannot add fluids or fuels.

You may want to regen your configs, as adding fuels to dynamos is currently disallowed.
