### ISSUE TITLE
[Thermal Dynamics] Backstuffed servo dupe bug

### ISSUE THREAD

**Issue by qchronod** [CoFH/Feedback#297]
There is a bug where a backstuffed servo is duping the items in it and dropping full stacks of each type when it is wrenched. I've been able to get it to happen using several different methods to cause a backstuff. Simplest method to use is a pipe several blocks long pulling from a hopper and into a chest, then disconnect the chest before the item actually gets there causing it to go back to the servo (but it can't go back into the hopper) so it becomes backstuffed and glows red. Wrench it with the crescent hammer and now you have a stack of whatever item it was trying to send.

Forge-10.13.2.1291
CoFHCore-[1.7.10]3.0.0RC5-207
ThermalDynamics-[1.7.10]1.0.0RC5-94

I'm currently using the EDK Steampunk pack on the Technic Launcher, but since I can cause it with just the itemducts and vanilla blocks, I'm guessing that none of the other mods would be affecting it.

![](http://i.imgur.com/JKPUj6Q.png)
Simple setup, chest on the left has one redstone and all the rest of the slots filled with items. Flip the switch and wait for the redstone to get pulled out.

![](http://i.imgur.com/Zvlbqx1.png)
Put another item in the last slot in the chest and then disconnect to target inventor, then wait for the redstone to bounce off the end of the pipe and return to the servo.

![](http://i.imgur.com/2ebDp4V.png)
Wrenching the servo after it has become backstuffed yields a full stack of redstone. (This works with any stackable item.

**Comment by rwtema** [comment]
Fixed in dev.

The code for dropping stuffed items was, well, just plain wrong. Was possibly drunk or something when I wrote it. My bad.
