### ISSUE TITLE
TD ducts and FluxNetworks plugs

### ISSUE THREAD

**Issue by Bass2style** [CoFH/Feedback#297]
pingback for my report on the FluxNetworks GIT, because IDK if the bug come from TD or from FN. : https://github.com/SonarSonic/Flux-Networks/issues/118

**Comment by KingLemming** [comment]
Frankly, don't know enough about this one, but looking over that Issue tracker, it seems to have issues with other mods too.

**Comment by Bass2style** [comment]
well, it's the "only" alternative for wireless energy transfer actually, like TF Tesseracts, but Tesseracts doesn't exist actually in 1.10.2, and other mods doesn't provide unlimited transfer rates.
yep, it seems a bit buggy with other mods, few weeks ago, the mods create extreme TPS lags, crashing servers/clients, it was fixed in the newt release, but a bit annoying. :D 

i reported the issue to both dev's because i dont know the responsible, between TD and FN. :D

**Comment by KingLemming** [comment]
Given that we work with literally everything else...not us. :)
