### ISSUE TITLE
It causes IC2 things and ExU2 CreativeTab to show incorrectly

### ISSUE THREAD

**Issue by fluid-uu-matter** [CoFH/Feedback#298]
When I updated CoFH Core to CoFHCore-1.10.2-4.1.5.8-universal.jar, All of IC2 items started to show their unlocalized names like this: 
![2017-06-26_18 06 01](https://user-images.githubusercontent.com/17115547/27534763-b42b32ce-5a9a-11e7-98ea-cd1f80fafd43.png)
ExU2 CreativeTab name is also effected.
![2017-06-26_18 11 49](https://user-images.githubusercontent.com/17115547/27534945-44baafd6-5a9b-11e7-984d-a6bdf9238aa7.png)
These happened after I updated CoFH Core to CoFHCore-1.10.2-4.1.5.8-universal.jar,with all the CoFH mods updated.
Now CoFHCore-1.10.2-4.1.7.11-universal.jar still have the problem.

**Comment by fluid-uu-matter** [comment]
Mod list
![image](https://user-images.githubusercontent.com/17115547/27535262-b4bed0b8-5a9c-11e7-8c6d-d0cef252add6.png)
The .disabled files are disabled when updating mods.
Also contains EJML-core-0.26.jar from IC2.

**Comment by KingLemming** [comment]
Is this also when you installed MineFactoryReloaded? I'm betting it is.

**Comment by KingLemming** [comment]
Ah, I think it's already been fixed on his end. You'll just have to wait for an MFR update.
