### ISSUE TITLE
Thermal Dynamics item name displaying incorrectly.

### ISSUE THREAD

**Issue by killerscorpion** [CoFH/Feedback#299]
Forge 1307
Thermal dynamics RC7-97

Currently all blocks and items from Thermal Dynamics is incorrectly displaying the item name and info when browsing in NEI. The picture is explains it. 
![2015-03-13_20 02 36](https://cloud.githubusercontent.com/assets/10732882/6650086/c7039010-c9bc-11e4-8857-889b6c2623f0.png)

**Comment by Carbon-Key** [comment]
Yeah, same issue here.  Looks like they all got un-localized somehow.  I know what they do, but it'd be nice to read them again. :P

**Comment by KingLemming** [comment]
Lovely.

**Comment by KingLemming** [comment]
The Jenkins didn't link localizations in properly. Download the new one.
