### ISSUE TITLE
[Request] MineTweaker Support

### ISSUE THREAD

**Issue by UndeadZeratul** [CoFH/Feedback#3]
I'm aware Modtweaker currently adds support, but @joshiejack has stopped working on it a while ago.  I don't know his policies on giving you the code to integrate it with the various CoFH mods (Mainly Thermal Expansion, since MFR has support natively from Minetweaker itself), but I saw Blood Magic now has the classes from ModTweaker, and they're credited to Josh. [Here's](https://github.com/joshiejack/ModTweaker/tree/master/src/main/java/modtweaker/mods/thermalexpansion) the classes you'd need to implement in order to get Thermal Expansion working, for example.

**Comment by KingLemming** [comment]
Seems like it's already been done. I don't understand the request here.

**Comment by UndeadZeratul** [comment]
Well, MFR has it, do the Thermal Expansion machines also have it?  I just went through ModTweaker's mod support and didn't see if TE had support natively.  If it already does, feel free to close this.

Thanks for the info though!  I thought modtweaker was the only one who had it, and since it's no longer being worked on, I wanted to reach out to mod devs and see if minetweaker support could be added in their respective mods.

**Comment by KingLemming** [comment]
Yeah I think I'm sort of confused here.

Minetweaker actively supports MFR. So why can't they also actively support TE? I'm not sure I understand the reason that we'd have to flip the script and put the code in on our end.

**Comment by UndeadZeratul** [comment]
With MFR support in Minetweaker's code, you can tweak things for machines that are part of MFR.  However, that doesn't work for any TE machine.  ModTweaker has support for these machines, but since it's no longer being worked on, if your APIs change, I'd assume that would end up breaking ModTweaker, and thus no more support for TE machine tweaking.

If CoFH would rather have the TE support exist within Minetweaker's code alongside MFR, that's fine; I've just seen that Josh mention that instead of keeping ModTweaker as the sole mod for bridging MineTweaker and other mods, that instead the support for a mod to be tweaked could/should be placed within the parent mod.

If it makes more sense to add in support for TE to MineTweaker directly, I can talk with Stan H. and see what he thinks.

I do agree though, having one of your mods supported on their side, and one here is a bit odd; It would have to be both on your end or both on theirs.  I'll see what they can do on their end, maybe he can port over Josh's work into Minetweaker directly, and just make TE supported natively.

**Comment by KingLemming** [comment]
The API changing argument is true of all mods, but in general I'd argue that the onus is on MineTweaker to stay up to date on this, otherwise it's yet another compatibility layer that we have to maintain and worry about breaking.

I also don't see the API changing in the foreseeable future.

**Comment by UndeadZeratul** [comment]
Fair enough.  The argument isn't that your API could change, it's more that if it does, then there isn't much of a chance on ModTweaker being updated to match.  Because you MineTweaker has MFR support already in house, I agree that having other CoFH mod support over there would be preferrable, as it's all in one place, and kept up to date by the same team, rather than having multiple people working to update the bridge between you two.

**Comment by Yulife** [comment]
It has already been made in Modtweaker. [Here](https://github.com/joshiejack/ModTweaker/tree/master/src/main/java/modtweaker/mods/thermalexpansion)'s the "documentation" for it. If you cannot read the code, feel free to PM me.

**Comment by UndeadZeratul** [comment]
I'm well aware of ModTweaker having support, as I mentioned that in my original post.  My point is that if/when Josh stops working on it - he might have already, he's mentioned it on twitter, then there won't be any support for Thermal Expansion machines being tweaked.

I was merely curious if CoFH wanted to implement it themselves, as that's what Josh has said he wanted to do, to offload the classes into the parent mods.  However, KL makes a good point that MineTweaker itself has MFR support already, so why put in support in two places?  If MineTweaker already has support for one, why not both?

**Comment by BionicFelps** [comment]
Joshie (the author of ModTweaker), stated in his farewell that he believes this support should be built into the mods themselves, which I think is off-base, I don't think that the average user would ever consider MineTweaking... But that's where this request is coming from...  ModTweaker is of course entirely separate from MineTweaker... Thermal Expansion is such an important mod though that I can't imagine no one picking up at least that portion of ModTweaker, I'm sure stanhebben (the maker of MineTweaker) probably somewhat depended on ModTweaker's existance and isn't going to just throw up his hands and say "well there goes various mod support" when ModTweaker is also open source either...

Joshie doesn't want to support a million different mods, and that's the reason he's quitting, but the truth is nobody does...

**Comment by jaredlll08** [comment]
I am actually taking over modtweaker...I have spoken to joshie and he is fone with me taking it over...

**Comment by skyboy** [comment]
That's a thing then.
