### ISSUE TITLE
Rockwool recipe mixup

### ISSUE THREAD

**Issue by Staegrin** [CoFH/Feedback#30]
There is currently no way to get rockwool and you can smelt Light Gray Rockwool into slag. I think this was meant to be the other way around. Keep up the good work.
![rockwool to slag](https://cloud.githubusercontent.com/assets/8494635/23589038/d2f558a6-01c6-11e7-83fc-b81a033af175.png)

**Comment by KingLemming** [comment]
Haha. Yeah.
