### ISSUE TITLE
Creosote oil from Immersive Engineering won't go into reactant dynamo.

### ISSUE THREAD

**Issue by krokots** [CoFH/Feedback#300]
I am using 1.11.2
ThermalExpansion-1.11.2-5.2.3.6-universal
ImmersiveEngineering-0.11-62
1.11.2-forge1.11.2-13.20.0.2345
and no Railcraft unfortunately.

**Comment by KingLemming** [comment]
Right. That's because it's not part of a valid reaction. Please consult JEI to see what's allowed and what isn't.
