### ISSUE TITLE
Issues with ShaderMod

### ISSUE THREAD

**Issue by ppoozl** [CoFH/Feedback#301]
When I update new CoFH mods on 3-14,Client stay on The line:[Client thread/INFO] [FML]: Holder lookups applied. When I removed my ShaderMod, the client can run normally.
ps. I am not a native English speaker. So I hope you can understand my poor written English.

**Comment by KingLemming** [comment]
What shader mod are you talking about?

Can you please provide a log?

**Comment by KingLemming** [comment]
Okay, thanks for your feedback. Very helpful.
