### ISSUE TITLE
[1.10+] Platinum Chestplate and Leggings have swapped armor values.

### ISSUE THREAD

**Issue by laserlemons** [CoFH/Feedback#301]
I noticed that the platinum armor uses the same armor values as diamond, except the platinum leggings have the same value as the diamond chestplate, while the platinum chestplate has the same value as diamond leggings. Is this intentional? I'm not sure it makes sense for the leggings to have a higher armor value than the chestplate.

**Comment by KingLemming** [comment]
Not really intentional, but not a huge deal either way. Meh.
