### ISSUE TITLE
[TE] Comparator outputs for caches

### ISSUE THREAD

**Issue by Tora-B** [CoFH/Feedback#303]
From my testing, the Thermal Expansion Caches appear to produce comparator outputs using the formula `floor(contents / capacity * 15)`. As a result, the smallest cache doesn't produce a signal until it has 667 items in it, making it impossible to detect when a cache is completely empty. The larger caches only produce outputs at even higher amounts, and the creative cache never produces an output at all, even if it's completely full. The red display meter on the front of the cache doesn't work for creative caches either, though it does work for the others.

Vanilla inventories use roughly `floor(contents / capacity * 14) + (stacks > 0 ? 1 : 0)` This enables the player to distinguish between a completely empty inventory, and one with a single item, as well as between a completely full inventory, and one that only has room for a single additional item, as well as a broad range of values in between.

I don't know exactly how you're storing the contents of caches, but I would guess that you're not storing it in separate stacks, and you're not using the vanilla calcRedstoneFromInventory(). Could the comparator output formula be changed to produce something closer to vanilla behavior? It's when an inventory is completely full or completely empty that a circuit most often needs to take action on, so being able to detect those states is important.

Versions:
CoFHCore-[1.7.10]3.0.0RC7-211
CoFHLib-[1.7.10]1.0.0RC7-127
RedstoneArsenal-[1.7.10]1.1.0RC7-65
ThermalDynamics-[1.7.10]1.0.0RC7-98
ThermalExpansion-[1.7.10]4.0.0RC7-141
ThermalFoundation-[1.7.10]1.0.0RC7-62

**Comment by KingLemming** [comment]
I'll ponder it. The case of completely empty is a corner case with barrel-style inventories.

**Comment by KingLemming** [comment]
k, it's in dev.

**Comment by Tora-B** [comment]
Just checking this on the latest releases, and it seems like comparator outputs for caches now only distinguish between two states: empty and not empty. They produce 0 signal when completely empty, and a signal strength of 1 for all other values, up to and including completely full. Was that the intended resolution?

It's still impossible to distinguish between full and mostly-full, and while completely full and completely empty are the most important states to be able to detect, the rest of the range is still valuable for adjusting rates in a production line. I know that minimal computational impact is a goal of both TE, and caches in particular, but you obviously do some computation for the display on the front of the cache, and have to check for the full and empty cases anyway when adding or removing items.

Versions:
Forge10.13.4.1448-1.7.10
CoFHCore-[1.7.10]3.0.2-262
RedstoneArsenal-[1.7.10]1.1.0-80
ThermalDynamics-[1.7.10]1.0.0-122
ThermalExpansion-[1.7.10]4.0.1-182
ThermalFoundation-[1.7.10]1.0.0-81

I also just tested on the latest alphas, just to make sure this hadn't already been addressed.
Forge10.13.4.1448-1.7.10
CoFHCore-[1.7.10]3.0.2-283
RedstoneArsenal-[1.7.10]1.1.0-83
ThermalDynamics-[1.7.10]1.0.0-130
ThermalExpansion-[1.7.10]4.0.1-182
ThermalFoundation-[1.7.10]1.0.0-88

**Comment by Tora-B** [comment]
@KingLemming I don't know if you were notified by my previous comment, or if I should have opened a new issue. The current behavior definitely isn't what I expected, so I'm not sure if I failed to communicate the problem clearly, or there's a problem with the implementation, or what.
