### ISSUE TITLE
Induction Smelter not working

### ISSUE THREAD

**Issue by rickets007** [CoFH/Feedback#304]
I am having an issue with the Induction Smelter. It will not let me put any item in the left hand input slot. This makes the machine useless as it requires something to be in both of the input slots. This issue was present with the old mod pack before the most recent update and was not resolved after updating. Has anyone else had this issue? Could another mod be causing it? 

New mod packs
CoFHCore-[1.7.10]3.0.0RC7-211
ThermalExpansion-[1.7.10]4.0.0RC7-141
CoFHLib-[1.7.10]1.0.0RC7-127

Old mod pack
CoFHCore-[1.7.10]3.0.0RC5-207
ThermalExpansion-[1.7.10]4.0.0RC6-138
CoFHLib-[1.7.10]1.0.0RC5-123

We are using a lot of various other mods. I can post a list if anyone thinks it would help.

**Comment by KingLemming** [comment]
You're also using a texture pack and it's not showing the slot lock button. You'll need to rectify that.

**Comment by rickets007** [comment]
That was it.

Thank you for the quick response.
