### ISSUE TITLE
[1.11.2] biome generation options not accepting multiple dictionary entries

### ISSUE THREAD

**Issue by Octopork** [CoFH/Feedback#306]
Forge: 1.11.2-13.20.0.2366
COFHCore: 4.2.4.9

Specifying multiple biome dictionary tags doesn't seem to function, log appears to load values correctly but there's no generation in the world.

works fine with a singular entry:
"entry": "FOREST"

but with multiple there's no generation...
"entry": ["FOREST", "PLAINS"]

this is of course assuming dictionary entries can be specified in the same way as id's

Example below

```
{
    "populate": {
    "Marble": {
            "distribution": "uniform",
            "generator": {
                "block": "astralsorcery:blockmarble",
                "material": "stone",
                "cluster-size": 14
            },
            "cluster-count": 16,
            "min-height": 10,
            "max-height": 118,
            "retrogen": false,
            "biome": {
                "restriction": "whitelist",
				"value": [
					{
						"type": "dictionary",
						"entry": ["FOREST", "PLAINS"]
					}
				]
            },
            "dimension": "all"
        }
    }
}
```

**Comment by skyboy** [comment]
For the `dictionary` type values, that operation is an AND; so it's looking for biomes that are forest and plains, rather than forest or plains; you can just separate them out like this:

```
				"value": [
					{
						"type": "dictionary",
						"entry":  "FOREST"
					},
					{
						"type": "dictionary",
						"entry": "PLAINS"
					}
				]
```

**Comment by KingLemming** [comment]
Yeah, confirmed with a local test that skyboy is infact correct. It's an unintuitive form, but this is actually working as intended.

Sorry for the confusion.
