### ISSUE TITLE
[1.11.2] Thermal Dynamics assuming block has meta property error

### ISSUE THREAD

**Issue by Boomflex** [CoFH/Feedback#307]
Hi all at Team CoFH,

Having my server console spam: https://pastebin.com/EYHsUbTU

It seems as if TD is assuming a block has their meta property but it doesn't actually have it.

CoFH Core: 4.2.4.9
TD: 2.2.4.7

**Comment by KingLemming** [comment]
Nope. Psi is assuming that ducts have a property they do not have.

Report it to Psi please.
