### ISSUE TITLE
java.lang.ClassNotFoundException: cofh.core.util.crafting.RecipeUpgradeOverride

### ISSUE THREAD

**Issue by Cryotechnic** [CoFH/Feedback#307]
So here's the deal: I am making a pack for a friend of mine and when I download coFH Core, from teamcofh.com/download of course, I get this error:

[19:36:44] [Client thread/ERROR] [FML]: The following problems were captured during this phase
[19:36:44] [Client thread/ERROR] [FML]: Caught exception from CoFHCore
java.lang.NoClassDefFoundError: cofh/core/util/crafting/RecipeUpgradeOverride

Full init log can be found here: http://pastebin.com/jTbY98t6
Crash log can be found here: http://pastebin.com/mxTA4SyA

**Comment by KingLemming** [comment]
Redownload *all* CoFH mods and be sure you aren't using dev jars.

If this were an issue on our end, everyone would see it 100% of the time as the jars would be fundamentally broken.
