### ISSUE TITLE
WAPC: Two filled resonant tanks stacking and bug when separating.

### ISSUE THREAD

**Issue by EvilBastard** [CoFH/Feedback#308]
I had two resonant tanks filled with resin. Completely filled, not enchanted.  When I went to put them into a vanilla enchanter, by shift clicking them in, only one of course went in. However it went it as a normal tank with no fluid in it.

**Comment by KingLemming** [comment]
The only fix here may be to disallow tank stacking.

**Comment by Techokami** [comment]
So THAT'S why I can't stack my tanks and caches anymore! BOOOO :(
