### ISSUE TITLE
[MFR & Nether Ores] PowerCrystal Core

### ISSUE THREAD

**Issue by Delchon** [CoFH/Feedback#309]
When I try to run the new versions of Nether Ores and MineFactory Reloaded, Forge asks me PowerCrystal Core mod, but I don't really know where I have to search it and I don't know if it maybe a problem with the other cofh mods.
I have updated all your mods, I tried to install CofhLib and of course if I remove these two mods the game starts normally.
Can you help me? Thanks.

**Comment by KingLemming** [comment]
Yeah, that sounds like you aren't actually downloading the new versions.

**Comment by Delchon** [comment]
I thought it too, so I went to http://www.curse.com/mc-mods/minecraft/minefactory-reloaded#t1:other-downloads and I downloaded the first mod in the list, but I gain the same error
