### ISSUE TITLE
[Suggestion] Quark DropOff Support for Strongbox (and maybe Cache)

### ISSUE THREAD

**Issue by Rupertofly** [CoFH/Feedback#309]
Hello Cofh,

Quark as a mechanic allowing easy drop off of items into nearby chests or similar inventories, would it be possible to add support for this mechanic to the Strongbox or even Cache?

A link to the API can be found here https://github.com/Vazkii/Quark/blob/master/modders.md

Thanks for your Time, From Rupertofly.

**Comment by KingLemming** [comment]
Seems reasonable but I need to know a bit more about what I have to do for integration.

**Comment by Rupertofly** [comment]
hmm sorry I don't know much else, i only found that API link from this comment in the description of the dropoff youtube video posted on Vazkii's channel: 

"Notes: The system will only put items in vanilla chests, modded blocks whose name includes chest or modded blocks marked with the interface: [https://github.com/Vazkii/Quark/blob/...](https://github.com/Vazkii/Quark/blob/master/src/main/java/vazkii/quark/base/handler/IDropoffManager.java)"

Sorry, I don't know if I can be much help in that area

**Comment by KingLemming** [comment]
Will happen in 1.12. Talked w/ Vazkii and the API needs to change somewhat.

**Comment by Rupertofly** [comment]
That's great, thank you so much.

**Comment by KingLemming** [comment]
Will be in next TE build. Strongboxes only though, Caches don't really have a GUI. ;)
