### ISSUE TITLE
Only copper armor showing in JEI

### ISSUE THREAD

**Issue by alphacentauri7** [CoFH/Feedback#31]
Only copper armor shows in JEI. This is inconsistent with the tools and weapons where a variant for each metal is shown. They show just fine in the creative menu and also shows the other variants in the recipe interface of the copper ones.

Is that intended to be a way to remove clutter in JEI, as they only differ in durability and have the same protection? Anyway, I find it's not straight-forward and hides the fact there are other variants available. I mean, it made me consider this being a bug in the first place! If you would just show all, it would be quite easy to hide them with JEI, as it's only 4 item ids.

**Comment by KingLemming** [comment]
The fact that it's 4 item IDs is probably why JEI is getting confused. Minecraft armor usually isn't that way. :) Lemme ping @mezz and see how to fix this.

**Comment by mezz** [comment]
If you're using meta values for subtypes on that item, I'm guessing it's not working because the item's `hasSubtypes` is `false`.

**Comment by KingLemming** [comment]
Ehh, I'm doing a full rewrite on armor/tools anyways, so this will either get fixed or need a totally different fix. ;)

**Comment by KingLemming** [comment]
Fixed, by virtue of the fact that armors were completely rewritten.
