### ISSUE TITLE
RA Crashes w/Latest Versions of Mods (Hash Error)

### ISSUE THREAD

**Issue by vintagedon** [CoFH/Feedback#310]
Updated all the Thermal mods, COFH, and Redstone Arsenal tonight, and the world will no longer start unless I remove Redstone Arsenal.  There's a Java hash error.

Versions I'm running:
ThermalDynamics-1.10.2-2.0.8.11-universal.jar
MineFactoryReloaded-[1.10.2]2.9.0B1-224.jar
CoFHCore-1.10.2-4.1.8.12-universal.jar
ThermalFoundation-1.10.2-2.1.3.5-universal.jar
ThermalExpansion-1.10.2-5.1.7.10-universal.jar

You can see the crash report here:
https://pastebin.com/Eipu6aPS

**Comment by KingLemming** [comment]
Not us, sorry.

This is caused by another mod adding OreDictionary names to and object in an inappropriate place. There's no way to know without adding/removing mods in batches until you find the actual reason for the crash.

**Comment by BrisingrAerowing** [comment]
I have successfully implicated Forestry as the culprit after getting this crash. I will report this to them.

**Comment by KingLemming** [comment]
I can't make it happen with Forestry, either.
