### ISSUE TITLE
Augmention Tab unclickable..

### ISSUE THREAD

**Issue by kbcoder** [CoFH/Feedback#311]
Builds: 

Thermal Expansion 1.11.2-5.2.3.6
Thermal Dynamics 1.11.2-2.2.4.7
Thermal Foundation 1.11.2-2.2.3.5

Machine: Redstone Furnace
Issue: Cannot access Augmentation Tab. Clicking on it does nothing.

**Comment by KingLemming** [comment]
PEBKAC. See what the mouseover text does?

**Comment by kbcoder** [comment]
Sorry, I saw 'Upgrade Required', but I thought that meant that there were no augmentations currently installed. Thanks and I apologize for the bother.

**Comment by KingLemming** [comment]
No worries!
