### ISSUE TITLE
Covering up RedNet (Energy) Cables...

### ISSUE THREAD

**Issue by BoboSims** [CoFH/Feedback#312]
How is it done?

I've tried Microblock covers, but it appears that RedNet (Energy) Cables aren't microblock-compatible.
I've tried Thermal Dynamics covers, but to no avail. Perhaps they'll cover the TD conduits, but not RedNet cables.
Whatever other covers and/or Facades I tried, seem not to work either. Did I miss something?

I'm using RedNet cables, because BC Kinesis pipes hardly ever connect to foreign devices (luckily they *will* connect TE Dynamos to TE Energy Cells). Energy cables from most other mods, (unfortunately *including* TD cables) are too expensive in comparison. So that's a yoohoo for RedNet wires.

Please advise. Any help is appreciated.

**Comment by Parker8283** [comment]
There is no current way to use any cover or facade system with RedNet cables. Though skyboy has stated before in IRC that he intends to use TD covers at a later date.

**Comment by BoboSims** [comment]
Ok, thank you, @Parker8283. I can only hope that 'a later date' will be sooner, rather than later :smile:

**Comment by Cbert** [comment]
I need those covers.

**Comment by BoboSims** [comment]
I know the feeling. I want them too. Badly! But as long as that feature is not yet available, we will have to make do without.

**Comment by DrakoAlcarus** [comment]
I hope soon happens...
...soon.

I need them badly.

**Comment by Phebus666** [comment]
I want those covers too...
I really love RedNet for all the awesome stuff you can do with it, yet really hate it for the eyesore :(
