### ISSUE TITLE
TD 2.0.7.10 Server crash : ServoItem.onNeighborChange NullPointerException

### ISSUE THREAD

**Issue by MigukNamja** [CoFH/Feedback#313]
ThermalDynamics-1.10.2-2.0.7.10 server crashed at:

```
java.lang.NullPointerException
        at cofh.thermaldynamics.duct.attachments.servo.ServoItem.onNeighborChange(ServoItem.java:333) ~[ServoItem.class:?]
```
Here's what the player said regarding this 1st crash:

> the offending resonant servo was in signalum-plated impulse itemduct (opaque) which was attached to AA small crate and permanently redstone signal activated with EIO redstone conduit among with few resonant retrievers
> but it didnt crash the server at the placement of it. it crashed first time several minutes after i had placed it.

[Full crash log](https://pastebin.com/raw/R5MzKYFY)

===

It crashed again in the same spot when the same player who placed it broke it in an attempt to clear it up.

> second crash was when i shift right clicked the said item duct with a crescent hammer

[Full crash log](https://pastebin.com/raw/2MhTYGyH)

**Comment by KingLemming** [comment]
Mitigated, although this can only ever happen if the attached tile does something that it shouldn't be doing.

**Comment by MigukNamja** [comment]
Wow !! Many thanks for the super-fast response and fix. The players on the server are loving the new COFH mods :-)
