### ISSUE TITLE
Apparent dependence on Thermal Foundation, but still wont run

### ISSUE THREAD

**Issue by GeneralSpacey** [CoFH/Feedback#314]
It says it is missing mods it depends on . 
It says to get Thermal Foundation between 2.1.2 and 2.2.0.
I installed 2.1.3
Still gives me the same error. The page for RSA doesnt even say that it is dependent on Thermal Foundation.
![4f6be7d4f3abf68414241bf54003e128](https://user-images.githubusercontent.com/29782637/27702865-82589116-5cd3-11e7-9f57-573a4118049d.png)

**Comment by GeneralSpacey** [comment]
Additional Info. Running on 1.10.2
With Forge 12.18.3.2316

**Comment by KingLemming** [comment]
You didn't include a modlist so I can tell you what you're doing wrong.

I just downloaded all of the mods from CurseForge and they work. Please go do that.
