### ISSUE TITLE
Version just released simply doesn't work

### ISSUE THREAD

**Issue by turnerlewis** [CoFH/Feedback#315]
CoFHCore-1.11.2-4.2.5.11-universal.jar - this file is simply broken. It doesn't work with Thermal Expansion, Foundation and Dynamics.

The process:
Start modpack
Forge loader 1/7
When it is about to reach 1.7 it comes up with the attached image.

![image](https://user-images.githubusercontent.com/27859162/27716167-526051e0-5d34-11e7-9b10-830aac257b17.png)

**Comment by KingLemming** [comment]
Yeah this is just outright false, sorry. It works.

Update Forge to latest, and give me a full modlist.
