### ISSUE TITLE
[Thermal Dynamics/Expansion]  Server Crash

### ISSUE THREAD

**Issue by mewhite42** [CoFH/Feedback#317]
I play on a small server with friends and last night it crashed after one of us placed down a tesseract next to a Cryo-stabilized flux duct.  Now the server crashed about a half second after loading.  Here is the crash report.

http://pastebin.com/v7bui4t2

**Comment by KingLemming** [comment]
Please only report issues if you've actually updated to the latest version of the mods. That's been fixed for weeks.

**Comment by mewhite42** [comment]
Sorry did not realize the RR3 had not updated.
