### ISSUE TITLE
[CRASH] 1.11.2 has strict Forge version reqs?

### ISSUE THREAD

**Issue by CanoLathra** [CoFH/Feedback#317]
Crash Report:
[https://pastebin.com/Wy0XbNZJ](https://pastebin.com/Wy0XbNZJ)

I got this error after updating Forge to the latest version of 13.20.x, as indicated by the "Incompatible version of Forge, Please Update" screen I got beforehand. I also got a similar crash report when using 13.21.x, but that wasn't one of the versions of forge listed by the "Update Forge" screen. I have never seen a hash code error in a minecraft crash report, so I have no idea what could be wrong.

If one of the installed mods is known to be incompatible, please tell me which ones or direct me to a list of known incompatible mods.

**Comment by CanoLathra** [comment]
UPDATE: Works with Forge 13.20.0.2315 (which is the oldest version compatible with all of my mods). Still not sure what is wrong with newer versions.

**Comment by KingLemming** [comment]
This is an issue related to BaseMetals. It's either doing oredict registration too late, or another mod is cross-registering and doing it too late.

Sorry, but there's no way to know *exactly* who is at fault here without removing mods in groups til you narrow it down.
