### ISSUE TITLE
Thermal Dynamics crash when loading world

### ISSUE THREAD

**Issue by SilverTab** [CoFH/Feedback#318]
My single player world crashed randomly and now I'm getting a crash with a thermal dynamics-related stack trace when loading my world: http://pastebin.com/9VQzA9FQ

Did some googling around and found at least one other instance of the same crash here: http://www.resonant-rise.com/topic/5331-first-crashes-from-nether-now-crash-on-world-load/

**Comment by KingLemming** [comment]
Mods are out of date. Please only post crashes if you're using updated mods.
