### ISSUE TITLE
Another request.

### ISSUE THREAD

**Issue by bookerthegeek** [CoFH/Feedback#318]
# Heyo # 
Please don't shoot me.

Ok, so configing out my pack, the only real issues I was having were your machines and ic2. Then, I rembered how ic2 easily lets you customize all the machine recipies... You can unzip the jar file, and place the machine configs in a directory in the config directory. Ic2 checks their first before and if the config file exists, it uses that instead of the internal config.

So I was wondering....how hard would that be to implament?  This way you could still support imc, and let people customize the actions inside the machines, all while still avoiding other tweaking methods. (Curous though, Why did you decide that imc was the best way to go?)

### Other ###
If your open to the idea, I'd be willing to create some default files that you could include that woyld have all the vanilla recipes. The nice thing is theinstructions on exactly how to make the modifications could be included in those files along with an address to the COFH wiki.

Another option would be for a config option that would generate those files instead with all the current registered recipes.

Thoughts?

**Comment by KingLemming** [comment]
IMC relies on having access to objects in the environment. JSON parsing doesn't. It's messy and ugly.

Basically, IMC was trivial to implement. This? You're asking a LOT.

**Comment by bookerthegeek** [comment]
hm... It is possible to read those messages from a file instead of them being sent by a mod?

**Comment by KingLemming** [comment]
That is essentially what you are asking. The problem is that those messages aren't really in a form that is human-readable/convenient AT ALL.

Hence, we need a completely separate parser. We actually had one in 1.7.10, and I can probably bring it back and adapt it, but the fact is that the game has moved away from ID/meta somewhat and adding oredict is another layer of nonsense on top of that too.

**Comment by bookerthegeek** [comment]
Understand. And I apologize if I am a becoming a bother, ;) I do not know how how to Java at all, but am pretty good at asking questions once I understand the issue, sometimes it helps. Other times, it's annoying.

As of right now it is a moot point personally as I am adjusting everything else to output COFH items. It will only become an issue once I start messing with the ore processing, as I am using multiple mods for the chain. That can wait till you come up with an elegant solution. 

I would assume that reasonable people will be happy to wait for a polished implantation vs a band aid that is not wanted in the first place.

Once again thank you for the wonderful mod. And that slightly less annoying RF implementation. Have a 💎.

**Comment by 3TUSK** [comment]
@bookerthegeek Sorry for reviving an inactive issue.

I was searching for existed IMC documentation of Thermal Expansion and I noticed this issue.   
I recall that I once wrote a [mod, named "RobustIMC"](https://github.com/Team-AbCiv/RobustIMC) that allows user to write IMC message in a lenient json format and send to other mods. Which would be somehow helpful in this case where Thermal Expansion has IMC support, but other tweak mods, e.g. CraftTweaker/ModTweaker, has no support(s).  
The only issue, as KingLemming said, is:  
> The problem is that those messages aren't really in a form that is human-readable/convenient AT ALL.  

I did tried to use it in my modpack, and [it looks.. not very human-friendly](https://gist.github.com/3TUSK/f3e342e0ef35e00e81d19e2e6202d6ae). It works perfectly tho. 
Furthermore, mods like Thermal Expansion has no public documentation on their IMC message, which creates more challenges for non-modder to use RobustIMC.

Still, it is a possible solution, so I would like to share.

**Comment by bookerthegeek** [comment]
@3TUSK Thank you. This was what I was/am looking for. I'll dig around a bit and hit you up on your Github if I have any questions.

**Comment by KingLemming** [comment]
This is a priority for the next release. :)

**Comment by KingLemming** [comment]
Merging this into #1008.
