### ISSUE TITLE
Itemducts do not connect to Mining Wells

### ISSUE THREAD

**Issue by ariosos** [CoFH/Feedback#319]
Place any itemduct to the top of a BuildCraft mining well and it will not connect. The warp and fluctuating ducts appear to connect, but do not accept items.

**Comment by KingLemming** [comment]
Yes, the impetus is on the Itemduct to be compatible with TD.

**Comment by Parker8283** [comment]
Use BuildCraftCompat. It adds support for anyone using the CoFH Itemduct interface.
