### ISSUE TITLE
[1.10.2 - 5.1.8.11 ] - Crash on launch "block minecraft:log2, it is not an allowed value"

### ISSUE THREAD

**Issue by EPIICTHUNDERCAT** [CoFH/Feedback#319]
Crashes on launch! Thanks

https://pastebin.com/3ApScf5p

**Comment by EPIICTHUNDERCAT** [comment]
Interesting, after this crash happened I decided to downgrade back to where this didn't happen and now it happens in that version as well. Don't really know how to explain that lol

**Comment by EPIICTHUNDERCAT** [comment]
i just now noticed 
" at ru.liahim.mist.init.recipe.RecipesMistDirt.func_77569_a(RecipesMistDirt.java:51)" i have no clue what that is lol hmm ill look into it

**Comment by EPIICTHUNDERCAT** [comment]
Reporting this issue to them as well, now it makes sense why it was broken in every version xD

**Comment by KingLemming** [comment]
Not us, sorry. Their function is trying to so something it shouldn't.

**Comment by Liahim85** [comment]
Hello!
I looked at the error and can not understand what the problem is.
Maybe you can help?
I'm just trying to get BlockState from the ItemStack.

`
if (stack != null) {
	item = stack.getItem();
	if (item instanceof ItemBlock) {
		block = Block.getBlockFromItem(item);
		state = block.getStateFromMeta(stack.getItemDamage()); //line 51 (RecipesMistDirt)
`

**Comment by KingLemming** [comment]
The problem there is that getStateFromMeta is deprecated - in the case of that particular block, there is a meta offset of 4.

So basically you're passing along the metadata and it doesn't match up with the block itself. This is arguably Mojang's fault for a poorly designed block, but if you're going to have a recipe that checks for something like this, you unfortunately have to mitigate it on your end.

**Comment by Liahim85** [comment]
Thanks for the advice )
However, I'm sorry.
I do not know much English.
Can you explain what it means to "mitigate it on your end"

**Comment by Liahim85** [comment]
Thank you!
I'll try to fix it )

**Comment by KingLemming** [comment]
Sure thing. :) I'm sorry that I don't know of a quick fix offhand.

**Comment by KingLemming** [comment]
I will see if it's possible to put in a pre-emptive mitigation on my end and not send that particular block through the pipeline.
