### ISSUE TITLE
Inconsistent behavior with JEI and Phytogenic Insolator Soil Specializations

### ISSUE THREAD

**Issue by alphacentauri7** [CoFH/Feedback#32]
The recipes for Mushrooms, Nether Wart and Chorus, which need one of the 3 soil type specializations upgrades, show up in the main Insolator usage screen. There is no hint to have you know you need these specializations. Furthermore it's inconsistent with various other specializations showing their own usage screen and additionally displaying a tab at the top of the usage screen of the machine they are to be used with.

**Comment by KingLemming** [comment]
Yes. Known. We had a deadline.

**Comment by KingLemming** [comment]
Implemented but won't be in until TE 5.1. Sorry. :)
