### ISSUE TITLE
[Feature Request] [Thermal Foundation] Add aluminum ore and silicon ore worldgen.

### ISSUE THREAD

**Issue by jdinkel** [CoFH/Feedback#320]
I have all ore worldgen for all my mod handled by Thermal Foundation - all other mods have ore worldgen disabled - except for aluminum ore and silicon ore.

Aluminum ore is used by Tinker's Construct and Galacticraft.

Silicon ore is used by Galacticraft.

Thanks for all your work.

**Comment by KingLemming** [comment]
Nope. You can do this yourself. Our world generation allows for it. Offhand, we don't know the IDs or metas that your world may have configured - this is impossible for us.

**Comment by jdinkel** [comment]
Oh nice, I found the instructions here for anyone else that may come across this: http://teamcofh.com/core-mods/cofhcore/ore-generation/
