### ISSUE TITLE
PSI break block spell on Pulverizer spawns in random Redstone furnace.

### ISSUE THREAD

**Issue by skytheraiders** [CoFH/Feedback#320]
I am was the Break Block spell from PSI made by Vaski and I needed to move the Pulverizer so I used my Break Block spell on it and out of nowhere, the Pulverizer dropped with a Redstone Furnace. I picked them up and placed them down and broke them again but this time, another Furnace dropped and didn't stack with the other furnaces. They work just like the regular Redstone Furnaces but they just appear out of nowhere when I use my Break Block spell. You guys have any ideas? If you need my help, just ask. I hope I can be of help.

**Comment by KingLemming** [comment]
That's not the only duplicate, either. This issue is one too. #140 !
It's 100% on Psi.

**Comment by skytheraiders** [comment]
Thanks guys! You're doing great! :-)
