### ISSUE TITLE
[1.11.2] Disabling Satchels in config doesn't seem to do anything.

### ISSUE THREAD

**Issue by laserlemons** [CoFH/Feedback#321]
The config of my client and server have the satchel option set to false and they are still craftable and show up in JEI and the creative tab.

Item {

    Satchel {
        B:Enable=false
    }

}

**Comment by KingLemming** [comment]
You asked for a config option, you didn't say ANYTHING about it working.

**Comment by laserlemons** [comment]
lol that's a good point I guess.
