### ISSUE TITLE
Issue with Extracting ITEMS from Magma Crucible.

### ISSUE THREAD

**Issue by AnthonyKane5528X** [CoFH/Feedback#322]
CoFHcore 1.10.2-4.1.9.13
Thermal Expansion:  1.10.2-5.1.8.11

Xnet: xnet-1.3.2
EnderIO:  1.10.2-3.1.184

Issue:  Can insert Netherrack into Thermal Expansion's Magma Crucible.  CANNOT EXTRACT Netherrack from Magma Crucible.

With Xnet my system is setup with a drum full of lava.  This drum has an Xnet Sensor tell it that when below 255,000 mil buckets to emit RED Color signal.  This tells the system to extract from a drawer frull of Netherrack and insert a stack into the Magama Crucible.  This works fine.

It is also setup to say when greater than or equal to 256,000 mil buckets to switch to White Color.  White Color tells the system to EXTRACT a stack of Netherrack (all items) from the Magma Crucible and insert them back into the storage drawer.  THIS is where it has stopped working.  

I can insert just fine into the Magma crucible.  Its trying to get the item extracted that's causing the issue.

I have tried using Input/Output mode (blue and orange overlay)  This did not work.
I have made sure that auto output is enabled.  This did not work
I have switched to the non-colored mode.  This did not work.

I do not believe this to be an Xnet issue as Xnet is doing exactly what it is suppose to to with regards to extracting Netherrack to be inserted into the Magma crucible.

To further test this I hooked up a small Ender IO conduit system to a Magma Crucible.

With this I told it, extract from the chest WITHOUT Redstone signal and insert into the Magma Crucible.  It did this just fine.  Then I told it to extract from the Magma Crucible WITH a Redstone signal.  Once again the Magma Crucible would not allow the Netherrack to be extracted.  And I ran through all the modes again.

I know this Xnet setup was working previously as I have it powering my base by insert Netherrack to be melted down into lava so that the drum can be refilled once it gets low.  And the drum then feeds the Magmatic Dynamos.

**Comment by KingLemming** [comment]
Yes, this was actually changed recently to prevent extraction from input slots, as there were more use cases this way.

So...it's working as intended, strictly speaking. But I'm open to suggestions.

**Comment by AnthonyKane5528X** [comment]
Would it be possible to set it up so that if the block is in "colorless" mode then the inventory slot would allow extraction?  I don't know.  I don't see why extracting from the input slot would be/cause an issue.

**Comment by KingLemming** [comment]
People were using the blue/orange and then complaining that things were extracting their inputs and not just their output.

The colorless side is a good compromise though, I was actually just implementing that in dev.

**Comment by AnthonyKane5528X** [comment]
Thank god because otherwise that borks my whole automated fuel generation.

With Xnet I finally have the ability to say if fuel is below X, then insert a stack and keep a stack in the Magma Crucible until the fuel tank is full.  Then once full, pull the remainder of the stack out and put it away.

Otherwise I'm forced to do some redstone shenanigans using two fluid monitors to measure the drum's on and off levels, and then figure out some math percentage of what a stack of Netherrack translates into for actual fuel gain.

I did that in 1.7.10 and pretty much with the 3 magmatic dynamos, with 1 power upgrade augment, 2 fuel economy augments, and excitation field limiter, it mean I could refuel the drum fully if it when below 91%.  Because then the system would kick on, and keep putting Netherrack in while the redstone signal was on, and then still have enough left to burn through when the signal kicked off to finish filling the barrel.

So you can see why I don't want to go back to that method.

I can do it.  But... math.  (be kind and don't make me do math on my time off)

**Comment by AnthonyKane5528X** [comment]
For now I reverted to the previous version of TE.  So no worries.

My best suggestion would be to see if you could do the colorless side like we discussed OR you could give the block more colored input/output modes like the Fluid Transposer.

As for people saying that blue/orange mode was extracting their inputs + their outputs, couldn't that just be handled by them disabling the auto-extract mode.  (you know those blue/orange arrows next to the GUI for how the sides actually function)?

**Comment by KingLemming** [comment]
No - auto extract/eject is a machine setting - it doesn't prevent other things from inputting/extracting.

**Comment by AnthonyKane5528X** [comment]
Well then I'm glad I could suggest the colorless side as a compromise :)
