### ISSUE TITLE
[Thermal Dynamics] Filters cause over-sending

### ISSUE THREAD

**Issue by MrLavender** [CoFH/Feedback#322]
CoFHCore-[1.7.10]3.0.0RC7-211.jar
CoFHLib-[1.7.10]1.0.0RC7-127.jar
ThermalDynamics-[1.7.10]1.0.0RC7-98.jar
ThermalExpansion-[1.7.10]4.0.0RC7-141.jar
ThermalFoundation-[1.7.10]1.0.0RC7-62.jar

Steps to reproduce;

- Completely fill 2 chests with cobble and connect them so that one pushes to the other (I used powered warp duct and a resonant servo, didn't test with other types).

- Open the receiving chest and right-click to remove half a stack. Result is that 32 cobble get sent from the other chest, as expected.

- Add a resonant filter to the receiving chest. Now when you remove half a stack 64 cobble gets sent resulting in 32 of them being dumped on the floor.

**Comment by MrLavender** [comment]
Additional Info:

It only happens when there is more than one stack of the same item in the sending chest. In the above example if there is only one stack of cobble in the sending chest then only 32 will be sent even with a filter present. If there is more than one stack then it seems to send 32 items twice because it leaves two half-stacks in the sending chest.

**Comment by rwtema** [comment]
Two separate issues. Resonant servos were over-sending, and Warp ducts without filters weren't bouncing items properly.

Both are fixed in dev.
