### ISSUE TITLE
Interaction with Underground Biomes Constructs

### ISSUE THREAD

**Issue by andrewminer** [CoFH/Feedback#323]
I'm putting together a modpack which uses CoFHCore for ore gen along with Underground Biomes Constructs to liven up the plain stone.  I would *love* to be able to say that certain ores can only spawn in certain kinds of rock (e.g., having diamonds appear in only igneous stone, or tin only appear in sedimentary stone).  Having gone over the code for both mods, I'm about half convinced that it's not possible, but I figured I'd ask the experts here.

As near as I can tell, UBC hooks into the [`PopulateChunkPost`](https://github.com/Zeno410/UndergroundBiomesConstructs1.10/blob/master/src/main/java/exterminatorjeff/undergroundbiomes/world/WorldGenManager.java#L118) event to start its work while CoFHCore uses the [`OreGenEvent`](https://github.com/CoFH/CoFHCore/blob/master/src/main/java/cofh/core/world/WorldHandler.java#L225).  My guess is that the `OreGenEvent` happens before `PopulateChunkPost`, and therefore, no UBC blocks are present in the world at the time the CoFHCore runs its ore generators.  If that's the case, then what I'm asking for isn't possible without one or the other of the two mods changing what events it uses to do its work.

Can you add any further details?  Am I missing something simple?  It would be super awesome if this actually worked, but I'm afraid I just don't know enough about the Minecraft codebase to work it out as yet.  Thanks!

**Comment by KingLemming** [comment]
Technically this is possible with only CoFHCore - you just have provide a generator for the replacement stone as well, and then configure your generation files so that certain ores only spawn in that generation.

**Comment by andrewminer** [comment]
Let me make sure I understand...  I'd need a subclass of `WorldGenerator` which does the work of putting in the right UBC stone (perhaps by hooking into the UBC code).  This would need to be early in the list of CoFH generators so that it runs before those which add the ore.  Then, the ore-generating `FeatureBase` subclasses would be able to run and find the UBC stone in which to attempt to place features.

> As far as UBC goes though, you are correct. And we are unable to change - OreGen must be hooked for us to be able to override vanilla.

This makes me wonder... is there some other event UBC could hook into which would run *before* the CoFH ore generation (e.g., [`OreGenEvent.Pre`](https://takahikokawasaki.github.io/minecraft-resources/javadoc/forge/1.8-11.14.1.1320/net/minecraftforge/event/terraingen/OreGenEvent.Pre.html)?  If they ran their normal processing at that time, then CoFH could just do it's normal thing, and everyone would be happy.  No?

**Comment by andrewminer** [comment]
Of course, then everyone would be forced to recognize UBC stone in their CoFH world-gen configs, and that would be a PITA, so it would definitely have to be a configurable thing.

**Comment by KingLemming** [comment]
You don't need a subclass at all - CoFHCore's generation is completely configurable. You just have to point the json at the UBC stone and figure out how you want to generate it. You don't have to write any mod code at all.

Here's a reference point. It's not 100% up to date, but should be a good place to start:
http://teamcofh.com/docs/cofh-core/features/custom-world-generation-1-10/

If you have further questions, please try the IRC or Twitch channel and ping @skyboy - the worldgen is largely his doing at this point.

**Comment by skyboy** [comment]
`PopulateChunkPost` is fired before forge's oregen occurs, but all oregen is offset by +8 on x and z in 1.10+ so it gens into 3 chunks that may not have populated: this is true of vanilla without forge, too. Any issues occurring from that needs to be handled by Underground Biomes

**Comment by andrewminer** [comment]
> You don't need a subclass at all - CoFHCore's generation is completely configurable. You just have to point the json at the UBC stone and figure out how you want to generate it. You don't have to write any mod code at all.

I've looked over all the generators in CoFH, and I'm guessing you aren't familiar with how UBC works if you're suggesting that one of the current generators could do what it does.  It *completely* replaces absolutely *all* vanilla stone using different strata of sedimentary, igneous, and metamorphic rocks.  It's much more comprehensive than just adding a few blobs of new kinds of stone (e.g., like the placement of diorite in vanilla Minecraft).

I think that's why they hook into the event they do.  When that event is fired, they just walk through every block in the chunk replacing the vanilla stone using their own algorithm to decide which strata a given y-level belongs to as they go along.  They're not doing ore-gen... they're doing wholesale replacement.

> Here's a reference point. It's not 100% up to date, but should be a good place to start...

Thanks!  I've been following that document extensively as I've been developing the custom ore gen already.  I definitely approve of the changes from the 1.7.10 version!

> `PopulateChunkPost` is fired before forge's oregen occurs, but all oregen is offset by +8 on x and z in 1.10+ so it gens into 3 chunks that may not have populated: this is true of vanilla without forge, too. Any issues occurring from that needs to be handled by Underground Biomes.

Sorry, but I don't see how this relates to my question.  My original question was whether I could use the CoFH ore gen to specifically place ores in stone which is added as a post-processing step by UBC.  Based upon the behavior I'm seeing from CoFHCore, it looks like it's specifically looking to place ore in `minecraft:stone` (and doing so successfully), which makes me suspect that it must be running before UBC (otherwise, it would have to have rules for placing ore in `undergroundbiomes:*_stone`).

In any case, I think I understand better how these two mods are interacting.  I'll take any further questions to IRC or Twitch as suggested.  Thanks!

**Comment by KingLemming** [comment]
I'm familiar with how it works, and it is infact completely doable with existing CoFH generation templates. It's just not easy. Writing your own generator and registering it would definitely be simpler.

As far as the other thing, I think skyboy replied to the wrong issue. :)

**Comment by skyboy** [comment]
I was replying to discussion as to what was going on with events and their timings, above.

As for looking for stone and replacing it even though UBC stone exists - that's a feature of the oregen at large, and exists specifically for mods like UBC. They tell ores that their block is ore-gen-equivalent to vanilla stone, and the ores generate in it.

If, however, you wish to restrict ores to specific kinds of UBC stones, UBC should not be doing anything that would prevent you from specifying that in our configs, and if that does not function correctly I'll look into our logic to make sure it's not our bug first.
