### ISSUE TITLE
Hard Server crash have to rollback...

### ISSUE THREAD

**Issue by beefjerkymm** [CoFH/Feedback#323]
So aparently if you put a portable tank inside of a fluid transposer , it auto crash the server and when you reboot the server it auto crash it again , had to do a rollback of a previous save. ( the portable tank in question i tried is the 128000mb one ) using FTB infinity 1.7.10 pack latest version

**Comment by KingLemming** [comment]
So apparently if you use a modpack that's out of date, you don't have any of the bugfixes from weeks ago.
