### ISSUE TITLE
[1.10+] Config option request/suggestion for tanks

### ISSUE THREAD

**Issue by laserlemons** [CoFH/Feedback#324]
Could we get a config option to adjust the amount of buckets tanks can hold like there was in 1.7?

**Comment by KingLemming** [comment]
Ehh.

What value do you want to set it to? I don't want to open up free configs again - it leads to issues.

**Comment by laserlemons** [comment]
I always set mine to 4 buckets at the lowest tier and 32 at the highest tier. I know most people wouldn't like those values, though, which is why I liked being able to change it. In my modpacks, I like to make item and fluid storage a challenge to overcome creatively, which is hard to do when you can fit 1500 buckets in a single movable block.

**Comment by KingLemming** [comment]
Yeah unfortunately narrowing the value range that much means I'd have to do free configs. I'd really much rather provide a base adjustment and leave the proportional scaling in place.

**Comment by KingLemming** [comment]
So I'm guessing you previously did 4/8/16/32 ? But with 5 tiers it'd be 4/8/16/32/64 ?

**Comment by laserlemons** [comment]
Yup, that sounds about right. And that's understandable, I knew there was probably a good reason the option wasn't carried over. What if you allowed the amounts to be changed as a whole using a percentage/fraction type thing?

**Comment by KingLemming** [comment]
Well right now I'm sort of doing a hybrid - you can set the base value, and I can go as low as 4 buckets, that's fine.

But I sort of want to keep that 1/4/9/16/25 scaling factor. So it'd be 4/16/36/64/100 buckets. That too large?

**Comment by laserlemons** [comment]
Sounds good to me! It's your mod so I'll take whatever you think is best.

**Comment by laserlemons** [comment]
Sorry to bug again, but is this in 5.2.5.14? The changelog makes it seem like it is but I don't see it in the configs.

**Comment by KingLemming** [comment]
Yes, the fixes are in 5.2.5.14. And yes, I am absolutely sure they are in. Looking at the config right now.

**Comment by laserlemons** [comment]
I downloaded it from curse via both the launcher and the website directly
and even deleted my existing config to allow it to regenerate. I also tried
a completely brand new profile in MultiMC. Is it in
cofh\thermalexpansion\common? At the bottom of the config it says 5.2.5 but
I don't see any new options. Also the satchels are still showing up after
setting it to false. Here's the config file that I generated new this
version: https://pastebin.com/LucEiaDE. Is it possible there's something
wrong with the download?

**Comment by KingLemming** [comment]
Potentially. I'm going to upload a .15 here in a second. Curse may have derped it on their end, but my local .14 definitely has the configs.

**Comment by laserlemons** [comment]
Still getting the same results with .15. Tried on a different computer in a
different building this time. Only for the 1.11 version, though. The 1.10
version is working.

**Comment by KingLemming** [comment]
Found the issue. The jenkins wasn't pulling from the correct repository.
