### ISSUE TITLE
TE Machine speed upgrades RF use

### ISSUE THREAD

**Issue by Zaflis** [CoFH/Feedback#324]
Machine speed upgrades are using old x3, x8, x20 power use, but tooltip says it only use 50%, 100%, 150% more. Expected hardened pulverizer to go from 40 RF/t to 60 RF use, but it goes to 120 RF, as it did before.

We have ThermalExpansion-[1.7.10]4.0.0RC7-141, and all other cofh mods latest too.

Also wiki page with still old info: http://teamcofh.com/thermal-expansion/machines/augments/

**Comment by KingLemming** [comment]
The tooltips are correct. The total amount of energy used is that.

8x speed, but 20x energy per tick is 150% more energy total.
