### ISSUE TITLE
Creative Energy Cell drops

### ISSUE THREAD

**Issue by hbro** [CoFH/Feedback#325]
Mods: https://feedthebeast.atlassian.net/wiki/display/PML/Direwolf20+%281.7.x%29+1.1.1

Square mining with an Awakened Ichorium Pickaxe with any Energy Cell in range, drops a Creative Energy Cell.
Square mining with an Awakened Ichorium Pickaxe with an Autonomous Activator in range, drops a Machinist's Workbench.

I am not sure where the error comes from, but the pickaxe works fine with all other mods, so my first guess is here.

To reproduce:
- Get an Awakened Ichorium Pickaxe;
- Put it in "Square Mode" by Shift-rightclicking with it;
- Place a block of Cobblestone;
- Place any non-Creative Energy Cell next to the Cobblestone block;
- Mine the Cobblestone block with the Awakened Ichorium Pickaxe in Square Mode;
- A Creative Energy Cell drops.

**Comment by KingLemming** [comment]
Your guess is incorrect. It's the pickaxe.
