### ISSUE TITLE
Incompatiblity with aether 2 (1.10.2)

### ISSUE THREAD

**Issue by jamzam90** [CoFH/Feedback#325]
I've reported it on the aether 2 github as well link [here](https://github.com/gildedgames/aether-issues/issues/696)

Crashes when moving a Thermal expansion tank and energy cell potentially a few others.
[crash-2017-07-01_03.09.22-server.txt](https://github.com/CoFH/Feedback/files/1116981/crash-2017-07-01_03.09.22-server.txt)

**Comment by KingLemming** [comment]
That is entirely on them. I have no idea what they're doing.
