### ISSUE TITLE
Thermal Dynamics: Suggestion Divided Itemduct Delivery

### ISSUE THREAD

**Issue by NullMagic** [CoFH/Feedback#326]
Alright, so, I am extremely happy to have ducts back, and I was super excited to see that the warp itemducts had a travel time of "instant", because I'm big on minimizing movement time in my setups, however I've been working with them, and I've been finding that the 0.5s extraction rate of the resonant servo is actually.. well, fairly slow, to be honest, it probably wouldn't be an issue if I was moving everything in packets of 64, but I wanted to split up the amounts into smaller groups for processing in multiple machines (in this case groups of four) using the Round Robin feature. I found that the movement rate is indeed instant, but then I'm waiting almost as long as it takes the machine to process for it to dispense the next packet (it is a bit faster than having one machine but not by a lot). So, I considered this a bit and came to the conclusion that you probably have 0.5s as the minimum extraction time for a reason, so I was wondering if instead of speeding up the extraction time there might some way to instead divide the blocks after extraction.

So what I'm suggesting is that the amount that the item duct extracts isn't the amount that it sends to the target inventory.

For instance I want 40 quartz to go to 10 machines in packets of four, so my extraction amount would be 40 quartz, but then my division would be 4, it would extract at 40 quartz every 0.5s, but then send 4 quartz to each end point round robin style. I hope that example makes sense.

anyway, I suggest this because I feel it would be a very nice perk for the resonant level servo instead of just faster movement and extraction rate and would make it far more useful on the Warp Itemducts as they do not benefit from the 3x speed boost (already being instant) which is the major difference I can see between the Resonant Servo and the Signalum Servo (aside from the larger number of white/blacklist slots, which isn't a huge pull when setting up ducts to carry exclusively two to three items).

I'm sorry if this comes across as nitpicky or in any other less than friendly way, it's really just something I thought would be useful/beneficial, and I won't be upset if you don't feel it's a good idea, or if there's a good reason not to do so, or if you just decide this is not a direction you want to take this. Anyway, thanks for reading, and for the fantastic mods.

anyway, it's just a suggestion

**Comment by MrLavender** [comment]
I think the resonant servo actually is too slow. It's not fast enough to keep up with cobble production from a speed 3 ender quarry (sending it to a trash can). For comparison an extra utilities transfer node with a stack upgrade and a couple of speed upgrades manages the task easily.

**Comment by KingLemming** [comment]
If the Ender Quarry is getting more than 128 cobblestone per second (6.4 blocks per tick), then that's just straight up dumb.

**Comment by MrLavender** [comment]
It's hard to find exact information on Ender Quarry speed but according to the test below it can mine 64x64 stone in 6 minutes = 182 cobble per second. That sounds about right based on eyeballing a buffer chest being filled with cobble faster than the resonant servo can remove it.

https://www.reddit.com/r/feedthebeast/comments/2yx9zc/ender_quarry_power_usage/cpehzkn

**Comment by KingLemming** [comment]
Use a second Servo + Duct. It's sort of ludicrous to expect something to keep up with that.

**Comment by NullMagic** [comment]
To be fair, you can stick a Tesseract directly on an Ender Quarry, and as far as I've been able to discern tesseracts are instant item transfer so long as the item is being pushed from one side and has a receiving inventory on the other. (it's also the best way to send the power to your quarry as, again, far as I can tell, they have no upper power limit).

**Comment by IdleMuse** [comment]
I don't think it's unreasonable to suggest the use of Tesseracts in this situation, and they handle the load perfectly. I guess the question is, should Warp Ducts plus Resonant Servos/Retrievers be essentially the same throughput as a Tesseract?

**Comment by NullMagic** [comment]
While tesseracts are fantastic (one of my favorite blocks), they don't offer the same level of control as the warp ducts, the ability to send a specific amount in round robin style to each machine in a row allows me to, potentially, break a project that could take 30 minutes to an hour of processing time down into just a few minutes, so far I've not seen another item transfer device that will allow me to determine exactly how many of each item each machine will receive that isn't a packet of 1 or 64. While what I suggest would have essentially the same throughput as tesseracts it does require a good bit of setup time, and over larger projects a very large amount of materials and then the power required to move objects at such speeds, it also does not have the unlimited distance that a tesseract does, it would be completely silly to stretch a duct over a thousand blocks, especially since a duct can be applied to a tesseract and extract from them just fine, although at a much slower rate than the tesseract can manage on it's own.

**Comment by MrLavender** [comment]
I am using tesseracts. The receiving tesseract dumps everything into a buffer chest and I then have three filtered outputs from that which send everything where it needs to go (ore processing, storage, or trash).

Yeah, it's not a major problem, obviously since I have an ender quarry then I also have ExU transfer nodes which can handle it. I just wanted to use TD ducts everywhere because they're prettier :)

**Comment by KingLemming** [comment]
@IdleMuse - It's apples to oranges. Tesseracts are passive - they don't extract. If something inserts directly *into* an Itemduct, it's the same thing, and their throughput will match.

I'll talk to @RWTema about adding direct support. I'm sure he'd be okay with that.

**Comment by IdleMuse** [comment]
Yeah, I understand how it differs in general, but I was referring to it in the context of an ExU Ender Quarry, which does push its output.

Can a solution be achieved with Resonant Retrievers, @NullMagic, until this functionality is added?

**Comment by NullMagic** [comment]
I was actually just thinking about that, I actually am still feeling my way around Thermal Dynamics and just noticed the retrievers and filter attachments, I'm not absolutely sure they can do what I want  (as I'd like even distribution of quartz across all machines in sets of 4) but I'm certainly going to take a look.

**Comment by KingLemming** [comment]
Retrievers will absolutely work.

**Comment by NullMagic** [comment]
Sorry for getting back to this so late, but I got distracted on a larger project. Anyway, retrievers do work, but even better are the filters, as you can set them to only allow a certain amount into an inventory, which lets you instantly transfer via pushing from the tesseract while still limiting the amount that goes to each inventory.

**Comment by KingLemming** [comment]
Pretty sure that is per item. I'll call this one good then. :)
