### ISSUE TITLE
[Thermal Expansion] Crash after putting an empty Portable Tank into an empty Fluid Transposer

### ISSUE THREAD

**Issue by ikkonoishi** [CoFH/Feedback#327]
[Crashlog](https://gist.github.com/ikkonoishi/9617b6b5250a84bb0bac#file-gistfile1-txt)

I had previously stored Pyrotheum in the tank, and set it to output mode to empty it. When I put it in the empty fluid transposer it crashed the server.

**Comment by KingLemming** [comment]
Update your mods. This was fixed forever ago.

**Comment by ikkonoishi** [comment]
Oh. Thanks.
