### ISSUE TITLE
[1.10.2] Error connected texture

### ISSUE THREAD

**Issue by GabrielR52** [CoFH/Feedback#327]
On 1.10.2 sometimes when I go to play on the server online and I go to a place where there are some machines of thermal expansion happens this crash
https://hastebin.com/uxihafabib
The only way to get in later is to disable the connected textures of optifine.

**Comment by KingLemming** [comment]
Yeah, we don't support Optifine for reasons such as this. Sorry.

**Comment by covers1624** [comment]
For reference if OptiFine ever want to fix this on THEIR end, our model is being called without asking for the standard forge extended BlockState , The Extended BlockState stuff is there SPECIFICALLY for rending, so we can append data to the BlockState from a tile. This is on THEM to fix and will probably break the majority of mods using the extended BlockState system.
