### ISSUE TITLE
*Possible* Warpduct/Machine Interaction

### ISSUE THREAD

**Issue by timrockz123** [CoFH/Feedback#328]
The Resonant Machines if you have it fully upgrades with speed will duplicate items. Such as if i put in one gold ingot into a pulverizer i will get 3 pulverized out. So you can make infinite material. Also works with the fluid transposer and buckets so you can get infinite of any liquid

**Comment by KingLemming** [comment]
Okay so, none of that actually happens. Like 0 of it.

Provide screenshots please.

**Comment by timrockz123** [comment]
It only happens when you pull the item out with a warp duct so it might only have to do with that

**Comment by timrockz123** [comment]
![2015-03-18_19 37 26](https://cloud.githubusercontent.com/assets/11545071/6721706/78b66426-cda6-11e4-8a97-bc086fdac7ef.png)
![2015-03-18_19 38 01](https://cloud.githubusercontent.com/assets/11545071/6721707/78ba1c92-cda6-11e4-8d60-162bfb418f29.png)
![2015-03-18_19 38 10](https://cloud.githubusercontent.com/assets/11545071/6721708/78bd4462-cda6-11e4-8eb5-123b238e3e28.png)
Here are some screenshots

**Comment by rwtema** [comment]
Acknowledged, warp ducts + auto-output = dupe.
Swapping two lines around fixed it.

**Comment by pooboy92** [comment]
If this bug is still open I can confirm it as well, as I just ran across it on my server.
