### ISSUE TITLE
[1.10.2] Gelid Cryotheum -> Squid spawn

### ISSUE THREAD

**Issue by TheSnowyChickens** [CoFH/Feedback#328]
Hello
is it possible , that Squids cant spawn in Gelid Cryotheum ?

They spawn in my extreme reactors and it dont looks good xD

Thx

**Comment by KingLemming** [comment]
Not something we can address, sorry.

**Comment by TheSnowyChickens** [comment]
Okay thank you.
I ask the extreme reactors team ,if they can change something , with a protected zone or other things :)
