### ISSUE TITLE
COFH total failure

### ISSUE THREAD

**Issue by Narwhal8** [CoFH/Feedback#329]
i can not get COFHcore to work with any other mods or launchers or have it alone in 1.10 or 1.11

**Comment by KingLemming** [comment]
No. Just no.

**Comment by Narwhal8** [comment]
It's the truth

**Comment by KingLemming** [comment]
As I said, I've told you what to do. This isn't an actual issue. Fix your setup.

**Comment by Narwhal8** [comment]
every set-up (including FTB pre-made pack) wont work
