### ISSUE TITLE
[cofh api][request] Force cofhlib version of API to take priority over bundled API versions

### ISSUE THREAD

**Issue by Entoarox** [CoFH/Feedback#33]
right now each time I update my mods, I need to delete their bunbled cofh/api directories to keep fml from screaming at me about a sorting loop.

I'd really love it if you guys could make it so having cofhlib installed makes it so bundled api versions are not loaded at all, so this annoying loop doesnt keep happening and requiring me to delete the api from every mod that bundles it.

**Comment by KingLemming** [comment]
We'd really love that too. It's a Forge problem. We have it set up so that *should* happen, especially with CoFHCore installed, but Forge doesn't handle it right.

**Comment by Barhandar** [comment]
Speaking of which, is there any way to tell what mod bundles different version of some API other than manually checking through the archives?

**Comment by bochen415** [comment]
All mods that I know off have updated the RF api and apart from the time the update went live I never had any issues with this.
I'm using Funky Locomotion, EnderIO, TE, Mekanism, BC, ExU and other tech mods and I don't have a problem if I stick to the recent versions.

**Comment by KingLemming** [comment]
I'm closing this one out. It's fairly common knowledge at this point, and if you're using mods that aren't updated, well that's bad. :/

**Comment by bochen415** [comment]
I have one thing to add to this.
There was a question here from @Barhandar and it needs an answer: install BdLib to get a nice api report with versions and the mod loading them added to your logs.
http://www.curse.com/mc-mods/minecraft/bdlib
