### ISSUE TITLE
[Thermal Dynmics] Retrievers bug

### ISSUE THREAD

**Issue by SirWilli** [CoFH/Feedback#330]
Version: ThermalDynamics-[1.7.10]1.0.0RC2-77

It seems that you can dupe items with Retrievers (maybe with others too) and an Inscriber from AppliedEnergistics.
Setup:
http://i59.tinypic.com/elcxzr.jpg
Inscriber:
http://i57.tinypic.com/25ho947.jpg
ME Interface:
http://i59.tinypic.com/24boxac.jpg
Me System after a while:
http://i60.tinypic.com/2805xeb.jpg

**Comment by FireBall1725** [comment]
What version of AE2

**Comment by FireBall1725** [comment]
Not able to reproduce http://screenshot.tsr.me/FZf2

**Comment by KingLemming** [comment]
I can't reproduce either. Are you on RC7?

**Comment by SirWilli** [comment]
appliedenergistics2-rv2-beta-8

**Comment by Parker8283** [comment]
Update all your mods. You are using an outdated TD.

**Comment by KingLemming** [comment]
Ah. Indeed. Closing this then. Please update.
