### ISSUE TITLE
Color blind texture for Energy Cell is missing.

### ISSUE THREAD

**Issue by CplPibald** [CoFH/Feedback#330]
Fresh download of ThermalExpansion-1.11.2-5.2.3.6 (EDIT: confirmed in 1.11.2-5.2.5.11 as well)
Enable color blind textures in the config.
See [issue #226](https://github.com/CoFH/Feedback/issues/226) for screenshots.

(would have added data to that issue, but it was already closed)

**Comment by KingLemming** [comment]
Hmm. Not sure the correct way to actually fix this - cells don't really have CB textures nor is strict orange/blue an issue as I understand it, so probably just need to remove that as a thing.

**Comment by KingLemming** [comment]
Eh, just removing it as an option for now. May revisit if there's appropriate iconography.
