### ISSUE TITLE
TF refined fuel can't be used as a fuel

### ISSUE THREAD

**Issue by fluid-uu-matter** [CoFH/Feedback#332]
The refined fuel appears as a pure-purple fluid and doesn't show in JEI.
And refined fuel can't be used for a fuel in TE compression dynamo. If the Ignition plugs augment is installed,the dynamo will be unable to use any fuels including refined fuel.
But JEI says it is able to use refined fuel in compression dynamo.
![14](https://user-images.githubusercontent.com/17115547/27770424-1f41ad4c-5f71-11e7-8cac-bd2b947c178c.png)
![24](https://user-images.githubusercontent.com/17115547/27770425-1f5f5298-5f71-11e7-80f1-dd14a27cb08e.png)

**Comment by KingLemming** [comment]
Yeah, this is the result of another mod breaking it. Not us, sorry.

**Comment by fluid-uu-matter** [comment]
Maybe Galacticraft? GC adds a fluid also named "Fuel".

**Comment by KingLemming** [comment]
That's probably it then, yes.

**Comment by KingLemming** [comment]
I'm going to consider renaming it internally to prevent this from happening, but the question is what exactly they're doing to hijack this. Hrm.

**Comment by fluid-uu-matter** [comment]
Oh,I used MultiMC launcher and refined fuel can be equivalence to GC fuel.
It maybe a GC bug.

**Comment by KingLemming** [comment]
It's not really a bug so much as a quirk of the Forge fluid system. I'm renaming my fuel internally.
