### ISSUE TITLE
[Thermal Expansion] Feature Request - Redprints should have visual/audio feedback.

### ISSUE THREAD

**Issue by Zeronic** [CoFH/Feedback#333]
Similar to the AE2 Memory Card, allowing you to save filter setting to something like a Schematic for quick and easy multi filter setups.

**Comment by KingLemming** [comment]
So...like a Redprint, which already does this? Or you mean something else?

**Comment by Zeronic** [comment]
Yes, I don't now the Redprint could also work with the Thermal Dynamics items. If possible, it would be nice to see some kind of feedback that it saved and loaded the setting.

**Comment by KingLemming** [comment]
The Item name changes when it reads a setting. Just sayin'.
