### ISSUE TITLE
Viaduct crash upon use

### ISSUE THREAD

**Issue by Captainaviator** [CoFH/Feedback#334]
When using a Viaduct, even for a very short distance, the client locks up, screen turns a light blue, then i get an "Unexpected error - java.lang.NullPointerException: Unexpected error"

Looks like it may be related to Stellar Sky renderer

MC version 1.11

[crash-2017-07-02_14.41.17-client.txt](https://github.com/CoFH/Feedback/files/1118048/crash-2017-07-02_14.41.17-client.txt)

**Comment by KingLemming** [comment]
Yup. 100% them. Please report it to their issue tracker.
