### ISSUE TITLE
[Thermal Expansion] Visual and/or audio feedback when interacting with Caches

### ISSUE THREAD

**Issue by Tonius** [CoFH/Feedback#334]
It would be nice to have some kind of feedback when putting things into Caches or getting things out of them. Something like a chat message of how many items were moved, or even just a sound effect, just to let you know that something actually happened.

Seeing the progress bar on the texture change as a result of items being moved manually only happens very rarely.

**Comment by KingLemming** [comment]
You get audio. I don't really want to spam the chat. I'll look into reviving CoFH HUD though.
