### ISSUE TITLE
Issue loading chunks in RfTools Dimension

### ISSUE THREAD

**Issue by ConnorPr** [CoFH/Feedback#335]
Thermal Dynamics - 1.10.2 - 2.0.9.12 - universal

So recently I decided to replace all of my piping underneath my RfTools Void Dimension Base with Cryo-Stabilized Fluxducts. At first they worked great (well at least while I was in the dimension), yet whenever I left the dimension, my connection to my ME System (From Applied Energistics 2) would die due to lack of power. The same thing occurred whenever I tried to leave my Rftools dimension where my power grid is to go to a new one. The chunks powered by the Cryo-Stabilized Fluxducts simply refused to properly load. At one point I got so desperate that I spent almost an hour grinding villagers to get enough chunk loaders to load every single chunk in my dimension, which still did nothing.

**Comment by KingLemming** [comment]
This sounds like an RF tools and/or chunk loading issue. The ducts work when loaded. If they aren't working, they aren't loaded.

Let RF tools know please.

**Comment by ConnorPr** [comment]
So do the ducts need to all be loaded? It's strange because every other form of conduit I use (Namely SolarFlux's Last Cable), works fine. In order for those ones to work while I'm away, I just need to load where the energy comes from and where it needs to go, do the ducts need to be loaded all the way through? And since almost every other conduit I use works fine, could this potentially be a compatibility error between Thermal Dynamics and RfTools?

**Comment by KingLemming** [comment]
I'm going to need screenshots to make any sense of this. But as a general rule, grids have to be loaded to work, and that applies for pretty much any cable/pipe/duct/conduit/whatever.

**Comment by ConnorPr** [comment]
Alright, i'll be sure to get some screenshots

**Comment by KingLemming** [comment]
So....?

**Comment by ConnorPr** [comment]
Oh sorry, I've been out of town and haven't had access to my computer. Went on a camping trip with some friends, anyway, I'll have the screenshots in maybe an hour or so. Still on the way back, thanks for putting up with my complete silence on the matter

**Comment by ConnorPr** [comment]
![2017-07-10_23 53 32](https://user-images.githubusercontent.com/22427246/28055220-e0169616-65cc-11e7-9c9a-f58d5247f73b.png)
![2017-07-10_23 53 38](https://user-images.githubusercontent.com/22427246/28055221-e0342258-65cc-11e7-8d1a-b6f65ec0957a.png)
![2017-07-10_23 58 34](https://user-images.githubusercontent.com/22427246/28055222-e0350826-65cc-11e7-9296-314dfe814726.png)

These 3 images depict my RfTools dimension being powered and chunk loaded by Cryo Stabilized Fluixducts, my Wireless ME Connector isn't powered since despite the chunks being loaded, the dimension still refuses to supply power to my ME system while i'm gone.

![2017-07-11_00 04 58](https://user-images.githubusercontent.com/22427246/28055246-fede23e8-65cc-11e7-82db-1d979703d110.png)
![2017-07-11_00 05 03](https://user-images.githubusercontent.com/22427246/28055247-ff005cec-65cc-11e7-93a3-821ff7f5fc1e.png)
![2017-07-11_00 05 20](https://user-images.githubusercontent.com/22427246/28055249-ff1126d0-65cc-11e7-9a2c-66b001e00aeb.png)

These 3 images depict my dimension being powered by SolarFlux Last Cables, cables which are able to transfer an upwards of 320,000 Rf/tick. As you can see in the 3rd picture, despite me being in the End, my ME Wireless Connector still works since the chunks and power sources are being properly chunk loaded.

**Comment by KingLemming** [comment]
Well, use those cables then.

I really don't know what to tell you - if a grid is loaded, it works. Period. And I've tested this lots now - ducts don't require you to be in that dimension, the chunk just has to be loaded. So you either aren't loading it correctly, or there's a strange interaction specifically with the ME controller.
