### ISSUE TITLE
NPE @ ThermalExpansion SawmillManager

### ISSUE THREAD

**Issue by xAlicatt** [CoFH/Feedback#336]
Just passing along this client crash report. I have rolled back to previous version for my pack for now.

https://gist.github.com/xAlicatt/b4ec5d6145c8400a4d45f8c14a0bec07

**Comment by KingLemming** [comment]
Yeah, that's caused by a mod doing registering a null value to the oredict. They really shouldn't be doing that. It's something I may mitigate, but I'd really like to know who is actually at fault here.

**Comment by xAlicatt** [comment]
Any suggestions for how to narrow it down?

**Comment by KingLemming** [comment]
Start with just CoFH mods, then slowly add mods in batches until you find whoever is doing it.

**Comment by KingLemming** [comment]
I'm pushing a hotfix here shortly which will prevent this from happening, even if people are kind of dumb. :)
