### ISSUE TITLE
Crash bug on dev versions of mods

### ISSUE THREAD

**Issue by jmeyer2k** [CoFH/Feedback#337]
I tried adding dev versions of the mod to my forge/eclipse/mods folder and after a couple of seconds of loading up a new world, it crashes with this stacktrace: http://pastebin.com/wkMn5j5u

I'm using: 

CoFHCore-[1.7.10]3.0.0RC7-216-dev.jar
ThermalDynamics-[1.7.10]1.0.0RC7-99-dev.jar
ThermalExpansion-[1.7.10]4.0.0RC7-146-dev.jar
ThermalFoundation-[1.7.10]1.0.0RC7-63-dev.jar

**Comment by skyboy** [comment]
You need to decompile forge with the CoFH_at.cfg file.
