### ISSUE TITLE
Crash on startup 1.10.2

### ISSUE THREAD

**Issue by Debonairesnake6** [CoFH/Feedback#337]
I've been pondering this over a week or so now but can't seem to fix this crash in my mod pack without removing Thermal expansion. I captured a video of my screen and slowed it down to find out it crashes when the modelloader tries to load the item minecraft:milk_bucket. I've also tried it with different versions of forge and all of the thermal mods with no luck. Sometimes it would load and othertimes it would fail but it seems to start crashing more and more each day. One work around I have got working is to use the old client to launch minecraft rather than the new one in case that helps.

Crash log: https://pastebin.com/ifa14kCQ

**Comment by KingLemming** [comment]
Yeah this is MFR, not us. Post it over on that issue tracker please.
