### ISSUE TITLE
Thermal Dynamics Server Crash

### ISSUE THREAD

**Issue by Brycey92** [CoFH/Feedback#339]
The following two crashes happen repeatedly and in alternating order each time certain chunks are loaded with itemducts in them. Remotely worldediting the area to remove the itemducts caused the crash as well. I have removed Thermal Dynamics from my modpack, which has stopped the crashes until such a time the mod can be fixed.

https://gist.github.com/Brycey92/8796fe3139d2499b7f32
https://gist.github.com/Brycey92/4f71d7aed35db5f2324f

I am running TD 1.0.0RC7-98 recommended, MC 1.7.10, and Forge 1307.

**Comment by KingLemming** [comment]
Well, that's interesting. This is the first and only NPE we have *ever* seen here.

Question for you - what tile was *attached* to the Itemduct? It's returning null in a place where it shouldn't be. That's actually where the bug is.

**Comment by KingLemming** [comment]
Welp. Handled in Mek, or should be. But I'll see about some kind of error logging.

**Comment by KingLemming** [comment]
Actually, @RWTema is a freaking hero and already did some error logging. :)

**Comment by Brycey92** [comment]
Thanks!
