### ISSUE TITLE
Crash 1.11.2 with Latest & Recommended Forge

### ISSUE THREAD

**Issue by Thrimed** [CoFH/Feedback#339]
Crash before server starts.

but works if i remove
ThermalDynamics & ThermalExpansions

[crash-2017-07-04_02.54.54-server.txt](https://github.com/CoFH/Feedback/files/1120793/crash-2017-07-04_02.54.54-server.txt)

https://pastebin.com/Rkz0tN9W

**Comment by covers1624** [comment]
Can we get the full log, this crash is stating that there was mod errors, the full log is needed.

**Comment by Thrimed** [comment]
fml-server-latest.log

[fml-server-latest.txt](https://github.com/CoFH/Feedback/files/1120801/fml-server-latest.txt)

**Comment by Thrimed** [comment]
I can now see that i missed a mod "CodeChickenLib"
