### ISSUE TITLE
Thermal Expansion - Dyes from wool in pulverizer

### ISSUE THREAD

**Issue by ClaytonAstrom** [CoFH/Feedback#34]
Thermal Expansion - 4.0.0B8-23
CoFHCore - 3.0.0B9-40
CoFHLib - 1.0.0B8-34
Forge - 10.13.2.1284
Minecraft 1.7.10

So I'm trying to get the pulverizers to create string and dye from wool, as they used to, but it doesn't seem like dye is a product from the pulverizer anymore?  I see a chance line in the config (ThermalExpansion.cfg:  B:Pulverizer.Wool.Dye.Chance=5).  I've tried changing 5 to 100 just to make sure, but no dice.  The dyes also do not have a recipe involving wool and a pulverizer in NEI either.

Something I'm goofing up in the config or another?  Or was this feature removed?

**Comment by KingLemming** [comment]
We need a full modlist. There could be another mod you have hijacking it.

**Comment by ClaytonAstrom** [comment]
Sorry about that, should have specified that I tested it isolated:
CodeChickenCore (1.0.4.29)
CoFH Core (3.0.0B9)
CoFHLib (1.0.0B8-34)
ThermalExpansion (4.0.0B8-23)
ThermalFoundation (1.0.0RC1-13).  

I'll add NEI in with that build to see if the recipe is also missing.

**Comment by ClaytonAstrom** [comment]
Just tested with NotEnoughItems 1.0.4.83, there's only a recipe with flowers to produce dye in the pulverizer.  Nothing involving wool, however.

Example with rose red:  http://imgur.com/a/ZLo0Z
