### ISSUE TITLE
Problem with Pulverizers.

### ISSUE THREAD

**Issue by Furious1964** [CoFH/Feedback#341]
I'm using version 5.1.6.8 of thermal Expansion in Sky Factory 3 and will be updating it soon, but I noticed that they no longer pulverize cobble into gravel...it's turned into sand. and gravel is turned into flint and not sand. Does this mod have mod compatibility with Ex Compressum?

**Comment by KingLemming** [comment]
They have never done cobble to gravel, it has literally always been sand.

Also, this isn't a problem.
