### ISSUE TITLE
(request) more realistic color for Aluminum ore

### ISSUE THREAD

**Issue by Hypsellis** [CoFH/Feedback#342]
The Aluminum ore color doesn't correspond at all to the Aluminum color, it kinda close from Copper ore color while it should be white. Aluminum is white and is stainless. With the current Aluminum color, the ore is reversed easily with Copper and make it harder to recognize.

**Comment by KingLemming** [comment]
Nope. Use a texture pack if you don't like it. Aluminum ore is absolutely not white though.

**Comment by Hypsellis** [comment]
Yes it's, it's one of the whitest metal which exist, I think you reverse with another ore. https://en.wikipedia.org/wiki/Aluminium

**Comment by KingLemming** [comment]
Aluminum ore does not look like aluminum metal. Google it sometime.

**Comment by bookerthegeek** [comment]
> Aluminum ore does not look like aluminum metal

Did you mean Bauxite? :p

**Comment by KingLemming** [comment]
Yes I did. :)

**Comment by Hypsellis** [comment]
Bauxite isn't Aluminium, it's a mineral rock which mix Oxygen and Aluminum (Al2O3).

**Comment by bookerthegeek** [comment]
@Hypsellis, Bauxite is the main ore used to create aluminum. As there is effectively no such thing in the real world as aluminium ore, I was giving KingLemming a little good natured ribbing about that.

Point being, either use a differant resource pack if you dont like the current texture, or tweak the pack to use a differant mods ores .
