### ISSUE TITLE
[1.7.10] CoFH Core Server Issue

### ISSUE THREAD

**Issue by Diamondspade** [CoFH/Feedback#343]
Hi,
English is not my native language, but I'll try my best.
I created a server 1.7.10 using Spigot, installed the latest Forge version 10.13.4.1614 for 1.7.10. Installed plenty of mods and it worked fine. Did the same for client. But when I installed CoFHCore it crashed and sent out this:
---- Minecraft Crash Report ----
// I just don't know what went wrong :(

Time: 04.07.17 14:03
Description: Exception in server tick loop

Missing Mods:
	Forge : [10.13.4.1448,10.14)

cpw.mods.fml.common.MissingModsException
	at cpw.mods.fml.common.Loader.sortModList(Loader.java:258)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:491)
	at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:87)
	at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:318)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:176)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:620)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_91, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 651757000 bytes (621 MB) / 951058432 bytes (907 MB) up to 1908932608 bytes (1820 MB)
	JVM Flags: 4 total; -Xms1024M -Xmx1024M -Xms512M -Xmx2048M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.114.1388 Minecraft Forge 10.13.3.1403 79 mods loaded, 79 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded
	FML{7.10.114.1388} [Forge Mod Loader] (minecraft_server.1.7.10.jar) Unloaded
	Forge{10.13.3.1403} [Minecraft Forge] (minecraft_server.1.7.10.jar) Unloaded
	appliedenergistics2-core{rv2-stable-10} [AppliedEnergistics2 Core] (minecraft.jar) Unloaded
	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) Unloaded
	NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar) Unloaded
	OpenModsCore{0.6} [OpenModsCore] (minecraft.jar) Unloaded
	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) Unloaded
	Treecapitator{1.7.10} [Treecapitator] ([1.7.10]Treecapitator-universal-2.0.4.jar) Unloaded
	AdvancedMachines{1.1.6} [IC2 Advanced Machines Addon] (AdvancedMachinesAS-1.7.10.jar) Unloaded
	adventurebackpack{1.7.10-0.8b} [Adventure Backpack] (adventurebackpack-1.7.10-0.8c.jar) Unloaded
	appliedenergistics2{rv2-stable-10} [Applied Energistics 2] (appliedenergistics2-rv2-stable-10.jar) Unloaded
	BiblioCraft{1.11.5} [BiblioCraft] (BiblioCraft[v1.11.5][MC1.7.10].jar) Unloaded
	BuildCraft|Core{7.1.22} [BuildCraft] (buildcraft-7.1.22.jar) Unloaded
	BuildCraft|Transport{7.1.22} [BC Transport] (buildcraft-7.1.22.jar) Unloaded
	BuildCraft|Factory{7.1.22} [BC Factory] (buildcraft-7.1.22.jar) Unloaded
	BuildCraft|Silicon{7.1.22} [BC Silicon] (buildcraft-7.1.22.jar) Unloaded
	BuildCraft|Robotics{7.1.22} [BC Robotics] (buildcraft-7.1.22.jar) Unloaded
	BuildCraft|Energy{7.1.22} [BC Energy] (buildcraft-7.1.22.jar) Unloaded
	BuildCraft|Builders{7.1.22} [BC Builders] (buildcraft-7.1.22.jar) Unloaded
	CarpentersBlocks{3.3.7} [Carpenter's Blocks] (Carpenter's Blocks v3.3.7 - MC 1.7.10.jar) Unloaded
	ChickenChunks{1.3.4.19} [ChickenChunks] (ChickenChunks-1.7.10-1.3.4.19-universal.jar) Unloaded
	chisel{2.9.4.10} [Chisel] (Chisel-2.9.4.10.jar) Unloaded
	CoFHCore{1.7.10R3.1.4} [CoFH Core] (CoFHCore-[1.7.10]3.1.4-329.jar) Unloaded
	eplus{3.0.2-d} [Enchanting Plus] (Enchanting-Plus-Mod-1.7.10.jar) Unloaded
	endercore{1.7.10-0.2.0.36_beta} [EnderCore] (EnderCore-1.7.10-0.2.0.36_beta.jar) Unloaded
	EnderStorage{1.4.7.37} [EnderStorage] (EnderStorage-1.7.10-1.4.7.37-universal.jar) Unloaded
	extracells{2.3.10} [Extra Cells 2] (ExtraCells-1.7.10-2.3.10b190.jar) Unloaded
	Forestry{3.6.10.1} [Forestry for Minecraft] (forestry_1.7.10-3.6.10.1.jar) Unloaded
	GraviSuite{1.7.10-2.0.3} [Graviation Suite] (GraviSuite-1.7.10-2.0.3.jar) Unloaded
	IC2CA{1.14.5.06} [IndustrialCraft 2 Combo Armors] (ic2ca-1.7.10-1.14.5.06.jar) Unloaded
	IC2NuclearControl{2.3.3a-Exist} [Nuclear Control 2] (IC2NuclearControl-2.3.3a-Exist.jar) Unloaded
	ImmibisCore{59.0.1} [Immibis Core] (Immibis-Core-1.7.10.jar) Unloaded
	IC2{2.2.824-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.824-experimental.jar) Unloaded
	InGameInfoXML{2.8.1.82} [InGame Info XML] (InGameInfoXML-1.7.10-2.8.1.82-universal.jar) Unloaded
	inpure|core{1.7.10R1.0.0B9} [INpureCore] (INpureCore-[1.7.10]1.0.0B9-62.jar) Unloaded
	inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] (InventoryTweaks-1.59-dev-152.jar) Unloaded
	IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar) Unloaded
	JABBA{1.2.2} [JABBA] (Jabba-1.2.2_1.7.10.jar) Unloaded
	LunatriusCore{1.1.2.21} [LunatriusCore] (LunatriusCore-1.7.10-1.1.2.21-universal.jar) Unloaded
	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) Unloaded
	NEIAddons{1.12.14.40} [NEI Addons] (neiaddons-1.12.14.40-mc1.7.10.jar) Unloaded
	NEIAddons|Developer{1.12.14.40} [NEI Addons: Developer Tools] (neiaddons-1.12.14.40-mc1.7.10.jar) Unloaded
	NEIAddons|AppEng{1.12.14.40} [NEI Addons: Applied Energistics 2] (neiaddons-1.12.14.40-mc1.7.10.jar) Unloaded
	NEIAddons|Botany{1.12.14.40} [NEI Addons: Botany] (neiaddons-1.12.14.40-mc1.7.10.jar) Unloaded
	NEIAddons|Forestry{1.12.14.40} [NEI Addons: Forestry] (neiaddons-1.12.14.40-mc1.7.10.jar) Unloaded
	NEIAddons|CraftingTables{1.12.14.40} [NEI Addons: Crafting Tables] (neiaddons-1.12.14.40-mc1.7.10.jar) Unloaded
	NEIAddons|ExNihilo{1.12.14.40} [NEI Addons: Ex Nihilo] (neiaddons-1.12.14.40-mc1.7.10.jar) Unloaded
	neiintegration{1.1.2} [NEI Integration] (NEIIntegration-MC1.7.10-1.1.2.jar) Unloaded
	numina{0.4.0.100} [Numina] (Numina-Mod-1.7.10.jar) Unloaded
	OpenBlocks{1.3} [OpenBlocks] (OpenBlocks-1.7.10-1.3.jar) Unloaded
	OpenMods{0.6} [OpenMods] (OpenModsLib-1.7.10-0.6.jar) Unloaded
	planetguyLib{1.9} [planetguyLib] (PlanetguyLib-1.9.2.jar) Unloaded
	ProjRed|Compatibility{4.7.0pre12.95} [ProjectRed Compatibility] (ProjectRed-1.7.10-Compat.jar) Unloaded
	ProjRed|Fabrication{4.7.0pre12.95} [ProjectRed Fabrication] (ProjectRed-1.7.10-Fabrication.jar) Unloaded
	ProjRed|Integration{4.7.0pre12.95} [ProjectRed Integration] (ProjectRed-1.7.10-Integration.jar) Unloaded
	ProjRed|Transmission{4.7.0pre12.95} [ProjectRed Transmission] (ProjectRed-1.7.10-Integration.jar) Unloaded
	ProjRed|Illumination{4.7.0pre12.95} [ProjectRed Illumination] (ProjectRed-1.7.10-Lighting.jar) Unloaded
	ProjRed|Expansion{4.7.0pre12.95} [ProjectRed Expansion] (ProjectRed-1.7.10-Mechanical.jar) Unloaded
	ProjRed|Transportation{4.7.0pre12.95} [ProjectRed Transportation] (ProjectRed-1.7.10-Mechanical.jar) Unloaded
	ProjRed|Core{4.7.0pre12.95} [ProjectRed Core] (ProjectRed-Base-1.7.10.jar) Unloaded
	Railcraft{9.12.2.0} [Railcraft] (Railcraft_1.7.10-9.12.2.0.jar) Unloaded
	TConstruct{1.7.10-1.8.5.build957} [Tinkers' Construct] (TConstruct-1.7.10-1.8.5.jar) Unloaded
	UndergroundBiomes{0.7} [Underground Biomes Constructs] (UndergroundBiomesConstructs-1.7.2-test45.jar) Unloaded
	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) Unloaded
	WailaHarvestability{1.1.6} [Waila Harvestability] (WailaHarvestability-mc1.7.10-1.1.6.jar) Unloaded
	wailaplugins{MC1.7.10-0.2.0-23} [WAILA Plugins] (WAILAPlugins-MC1.7.10-0.2.0-23.jar) Unloaded
	weaponmod{v1.14.3} [Balkon's WeaponMod] (weaponmod-1.14.3.jar) Unloaded
	WR-CBE|Core{1.4.1.9} [WR-CBE Core] (WR-CBE-1.7.10-1.4.1.9-universal.jar) Unloaded
	WR-CBE|Addons{1.4.1.9} [WR-CBE Addons] (WR-CBE-1.7.10-1.4.1.9-universal.jar) Unloaded
	WR-CBE|Logic{1.4.1.9} [WR-CBE Logic] (WR-CBE-1.7.10-1.4.1.9-universal.jar) Unloaded
	bspkrsCore{6.16} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.16.jar) Unloaded
	ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) Unloaded
	ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) Unloaded
	McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) Unloaded
	MCFrames{1.0} [MCFrames] (ForgeRelocation-1.7.10-0.0.1.4-universal.jar) Unloaded
	ForgeRelocation{0.0.1.4} [ForgeRelocation] (ForgeRelocation-1.7.10-0.0.1.4-universal.jar) Unloaded
	RelocationFMP{0.0.1.2} [RelocationFMP] (ForgeRelocationFMP-1.7.10-0.0.1.2-universal.jar) Unloaded
	MrTJPCoreMod{1.1.0.33} [MrTJPCore] (MrTJPCore-1.7.10-1.1.0.33-universal.jar) Unloaded
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'cauldron,craftbukkit,mcpc,fml,forge'
	Type: Dedicated Server (map_server.txt)

I used latest version of CoFHCore (1.7.103.1.4-329). Got it from Curse. 
OK, Maybe it's because of another mods. I deleted almost everything and it still wont't work. It requires the version of Forge, which is lower, than my current, but at the same time my Client works fine, and I even managed to install and launch successfully CoFHCore based mods (Thermal Expansion, Minefactory Reloaded).

P.S I know that 1.7.10 is a "bit" outdated, but can you help me anyway?

**Comment by KingLemming** [comment]
Sorry, but there's nothing in that log that actually points to us. Start with CoFH mods only and install things until you get the crash, and then you'll find the actual issue.

Feel free to ask on IRC or Twitch, but the issue tracker is not tech support.

**Comment by Diamondspade** [comment]
But i've already wrote that I have installed only CoFHCore on Clean version of server and it crashed, is there anything I can do?

**Comment by KingLemming** [comment]
Well except you haven't - you're using Spigot. That's not clean.

**Comment by Diamondspade** [comment]
So I must use something else, like MCPS or Bukkit? I'm not trying to accuse you in anything, but that's strange. I've installed more than 50 different mods on the server, it works fine. Adding a CoFHCore to it leads to a crash. Launching a server only with CoFHCore also crashes it.  

What I was trying to do : Tried almost every version of mod starting from the oldes to the latest. Surfed on the internet. Some users also had the same issue, but none of them were solved (not a single respond from the others)

Nobody knows your mod better than you. I tried everything a normal user would do. Can you help please?

**Comment by KingLemming** [comment]
The crash log tells me literally nothing, other than a mod can't find the right Forge version. I think this is maybe a fundamental incompatibility with Spigot, and I don't know what it could be on their end.

I'm sorry, but this is way outdated and unsupported, and there's really nothing I can do about it at this point.

**Comment by covers1624** [comment]
> FML: MCP v9.05 FML v7.10.114.1388 Minecraft Forge 10.13.3.1403 
You clearly do not have the correct forge version.

**Comment by Diamondspade** [comment]
Anyway thanks

**Comment by KingLemming** [comment]
Oh wow - good catch by covers there. You literally don't have the right version.

**Comment by covers1624** [comment]
Use https://cyberdynecc.github.io/Thermos/ For Bukkit 1.7 modded.

**Comment by Diamondspade** [comment]
Thank's alot. Please, Forgive my stupidity
