### ISSUE TITLE
CoFH crash

### ISSUE THREAD

**Issue by Indeoo** [CoFH/Feedback#344]
New CoFH crashing at the start
http://cloud.venherak.com/latest.log
What's the problem? How fo fix?

**Comment by KingLemming** [comment]
This isn't tech support and that is not a full log. Please pay attention to what the readme says. Try again, and use pastebin.

**Comment by Indeoo** [comment]
Which readme? Where is it?

**Comment by KingLemming** [comment]
https://github.com/CoFH/Feedback

**Comment by Indeoo** [comment]
I've launch everything according to readme, crash anyway

**Comment by KingLemming** [comment]
You didn't give us a modlist, and you didn't provide a FULL proper log.

**Comment by Indeoo** [comment]
This is the FULL log.
I've tried to launch CoFH even without any other's mod. Error is the same

**Comment by KingLemming** [comment]
You have Cauldron, don't you?

**Comment by Indeoo** [comment]
Yes, but the error is actual on client also.

**Comment by KingLemming** [comment]
You have a mod that is changing something in WorldServer. Cauldron has a patch specifically for CoFH compatibility, but that mod is breaking it. But you haven't given us a modlist, so can't really narrow it down.

**Comment by Indeoo** [comment]
As i've told I have no mods exept CoFH

**Comment by KingLemming** [comment]
Sorry, we just can't replicate this, even with Cauldron. Make sure everything is up to date, all I can tell you.
