### ISSUE TITLE
fluctuating itemduct freezes server

### ISSUE THREAD

**Issue by thecrazyrai** [CoFH/Feedback#345]
![2015-03-25_14 24 22](https://cloud.githubusercontent.com/assets/9990458/6825429/d5ca7982-d2fa-11e4-938a-a4b8f68844b9.png)
this is my setup. if i configuer the servo to do round robin and only 16 items at a time and put for example two stacks coal dust and one stack iron ingots in the chest, it will freeze the server and restarting won't fix it. I used induction smelters but it will do similar things with other machines.
There is no crash log because it didn't crash.

**Comment by KingLemming** [comment]
This has been fixed already. You're out of date.
