### ISSUE TITLE
[World generation] Crude oil and others Thermal Foundation

### ISSUE THREAD

**Issue by cap1o** [CoFH/Feedback#345]
Hello, 

It's more help than a request.
I don't find out on my world, any crude oil. The map is from the modpack Beyond 1.8.1 with Thermal Foundation [ThermalFoundation-1.10.2-2.1.3.5-universal.jar].
Is it a problem of generation or config file ? 

There is the config file ( I don't so much understand this) :

https://pastebin.com/4WieEShC

Do i miss something ?
I have to restart a new map ? :(
Thanks for help.
Jérémy

**Comment by KingLemming** [comment]
Delete the config and let it regenerate.

But in the future, please don't use this for tech support.
