### ISSUE TITLE
RS control crash Autonomous Activator

### ISSUE THREAD

**Issue by devryb** [CoFH/Feedback#347]
Getting this crash intermittently with autonomous activators being redstone controlled via enderio conduits

http://pastebin.com/jSAT4cj1

RC7-141

**Comment by KingLemming** [comment]
This is *probably* EnderIO's fault, since we never see it with vanilla redstone. They're either doing the calculation client-side, or loading inactive chunks on RS updates. Neither of those is correct.

I'll leave this up for now, but I don't think it's on our end.

**Comment by HenryLoenwind** [comment]
BTW: That codepath is isRemote-protected in vanilla code. My guess would be that your code cannot handle not being the last thing to be cleaned up onChunkUnload().

Also, it is vanilla code that decides which blocks to notify, and it has no check for unladed chunks. The only way to play this safe would be to not notify when being near an unloaded chunk, even if 5 of the blocks that would be notified are loaded.

And what is your TE NPEing on? onNeighborBlockChange() is parameterless...

**Comment by KingLemming** [comment]
The Tile is hitting an NPE on a field that isn't initialized in two cases)

1) on the client
2) when the tile has not yet been loaded

You don't update RS on the client, and you don't update unloaded things. Or at least, vanilla doesn't. EnderIO seems to be trying to.

**Comment by KingLemming** [comment]
Closing this out. There will be a sanity check in the next version of TE to prevent invalid interactions. But fundamentally, this is Ender IO.

**Comment by devryb** [comment]
Thanks!

**Comment by devryb** [comment]
Hey I think the rednet cabled from MFR are causing the same issue fyi

http://pastebin.com/9JbxQcyb

**Comment by BoboSims** [comment]
Mod versions in lines 173-181 show that you're **not** using the latest released versions of *at least* the Team CoFH mods. Maybe you should update all your mods and **then** check if the issue persists.
