### ISSUE TITLE
Missing requirement informations on Core

### ISSUE THREAD

**Issue by fampat** [CoFH/Feedback#347]
Hi, 
i just installed the 1.12 version,
please add a hint on curseforge the you will need the Restone-Flux Mod as well as CoFH World (for foundation) and codechickenlib 3.1.0 fir expansion, its not noted on the core-page (or the others).

Also a note that you will need at least .2388 of the current forge 1.12 would be real a good addition so that ppl can install the stuff with less hassle!

thanks for the mod(s)! ;)

**Comment by SnowShock35** [comment]
@fampat Already Exists. Tada! 
![](https://ss.blamesnow.co.uk/2017/07/1499253490-cdaca3ed.png)

**Comment by covers1624** [comment]
Each file should state their dependencies.

**Comment by KingLemming** [comment]
As noted, this is already a thing. There is a dependencies page.
