### ISSUE TITLE
Add support for fuels from others mods.

### ISSUE THREAD

**Issue by felihenrique** [CoFH/Feedback#348]
Hello.
It would be nice if we had support for fuels from other mods. I mainly missed the ethanol/biofuel from forestry mod in compression dynamo and the biomass in reactant dynamo.

**Comment by KingLemming** [comment]
Biomass in the reactant is not coming back - the Reactant Dynamo now relies on Reactions, not random combinations of ingredients.

Biofuel is a maybe. Eventually I want to add some customizable support for fuel, but not like it used to be, as that was less than ideal.

**Comment by fluid-uu-matter** [comment]
EnderIO fuels, IE diesel, even IC2 biogas!

**Comment by Techokami** [comment]
What about being able to process Crude Oil from other mods? I have two incompatible Crude Oil fluids now: one from Thermal Foundation and one from Immersive Petroleum. I should be able to process both of them in the same way!

**Comment by KingLemming** [comment]
I've added support for a number of new fuels. Possibly not exhaustive, but enough IMO. :)

Marking this as implemented - you are always welcome to drop by the Twitch chat for further requests.
