### ISSUE TITLE
Resonant Cyclic Assemblers only produce one item a tick

### ISSUE THREAD

**Issue by adudney** [CoFH/Feedback#348]
I remember reading that the cyclic assemblers were buffed in a recent version to craft multiple items a tick at higher tiers, but that does not appear to be the case in the most recent version (4.0.0RC7) as the resonant ones only craft one item a tick. The test item was compressed cobblestone from ExtraUtilities.

**Comment by KingLemming** [comment]
They have one operation per tick - whether that crafts 64 things or 1 thing. What changed is that they output 8/16/32/64 items based on level and output after every operation and not every 32 ticks.
