### ISSUE TITLE
Thermal Expansion Crash

### ISSUE THREAD

**Issue by MadToilet** [CoFH/Feedback#35]
Hey CoFH Team!

Beyond excited to see your mods move to 1.10.2! Thanks for all your dedication and hard work for the community.

Ran into a crash when running thermal expansion with my modified Mech & Magic modpack.

http://pastebin.com/8vrgkmhq

**Comment by covers1624** [comment]
Update CodeChickenLib from here: http://minecraft.curseforge.com/projects/codechicken-lib-1-8

**Comment by MadToilet** [comment]
Thanks!
