### ISSUE TITLE
[1.10.2] [TE 5.1.8.16] Many blocks are not rendering in JEI

### ISSUE THREAD

**Issue by 2ndkirbyever** [CoFH/Feedback#350]
After updating to the latest version of Thermal Expansion, I noticed that there are many items that are not rendering in JEI.  A few of those are the frames, machines, and energy cells.
![2017-07-05_22 50 35](https://user-images.githubusercontent.com/16438720/27895061-957c3a48-61d5-11e7-9c0a-8d36385fdd17.png)
Since they are not displaying in JEI, I can't click them to check their recipes. Worst of all, if I try to check the recipe for an item that requires one of the hidden items, the game outright crashes.
[crash-2017-07-05_23.19.51-client.txt](https://github.com/CoFH/Feedback/files/1126740/crash-2017-07-05_23.19.51-client.txt)

**Comment by KingLemming** [comment]
Here's the cause:

at net.darkhax.bookshelf.client.render.item.RenderItemWrapper.func_184393_a(RenderItemWrapper.java:354)

BookShelfLoadingPlugin is doing a thing it shouldn't.

**Comment by 2ndkirbyever** [comment]
I'll let the bookshelf author know.
Thanks for your help.

**Comment by KingLemming** [comment]
No problem. :)
