### ISSUE TITLE
Thermal Dynamics Unloading Chunks Crash

### ISSUE THREAD

**Issue by RedstoneJunkyard** [CoFH/Feedback#351]
Its seems as though if you have a Thermal Dynamics (v1.0.0RC2-77) duct system stretching though 2 or more chunks and you unload the area it crashes the game. This occurred on the FTB infinity pack, version 1.2.1. This occurs when you leave via teleportation (Mystcraft book) or by flying away. The crash report is here: http://pastebin.com/jZUiWJh1

**Comment by KingLemming** [comment]
Mods are outdated. Sorry, this has long been fixed.
