### ISSUE TITLE
Tooltip in wrong place in TE GUI's

### ISSUE THREAD

**Issue by Zetharion** [CoFH/Feedback#351]
Playing Thermal Expansion 1.12 version 5.3.0.4 and while in a GUI for a Thermal Expansion machine like the Pulverizer, when you hover over items in your inventory the tooltip shows up way off to the left of the screen.

Thermal Foundation 1.12 2.3.0.3
CoFH Core 1.12 4.3.0.5
Forge 14.21.1.2396

**Comment by KingLemming** [comment]
Already fixed. Please update.
