### ISSUE TITLE
[Thermal Expansion crossmod] Unconventional materials in Induction Smelter recipes introduced by other mods are not accepted in left hand input slot

### ISSUE THREAD

**Issue by Paksarra** [CoFH/Feedback#352]
I updated to the latest version of the COFH mods, and have reproduced this issue in a clean version of Forge 1307 with only COFHCore, Thermal Expansion, Foundation, and Dynamics, and Simply Jetpacks (to demonstrate the problem.) However, I have also encountered this issue while attempting to use Induction Smelter recipes added with MineTweaker and Ex Nihilo/Ex Astris.

In brief, the Induction Smelter will only allow materials used in the base COFH recipes to go into the left hand input slot, even if a valid recipe using that item is visible using a recipe viewer such as Not Enough Items. As an example, Simply Jetpacks adds an item called "Tinkers' Alloy Armor Plating" created by putting "Iron Armor Plating" in the right hand slot, and ten "Tinkers' Alloy Ingots" in the left hand slot. However, the Induction Smelter doesn't accept Tinkers' Alloy Ingots into the left slot anymore.

I've reproduced the same issue with the assorted Scented Hive recipes introduced in either Ex Nihilo or Ex Astris, which are created by combining a scented artificial hive in the right slot with eight of a specific item in the left (which somehow creates a bee. I'm not going to question the logic here.) Eight sand in the left slot will work to create a Modest (desert) Hive because there are vanilla Thermal Expansion recipes that ask for sand, but eight vines (jungle) or eight sheared leaves (forest) will not go into the left slot. I also attempted to use Minetweaker to create a custom Induction Smelter recipe, and it, too, did not allow the unconventional item to go into the left slot, despite appearing as a valid recipe when viewed in NEI.

However, any item I tried goes into the right slot-- it's only the left that's picky.

I was able to use both the Simply Jetpacks armor plate and Ex Whatever's beehive recipes on the last release of Thermal Expansion before Thermal Dynamics came out, so this is a recent change.

**Comment by KingLemming** [comment]
Do you have a texture pack?

You need to unlock the left slot. There's a button to do that, but I'm guessing you literally don't see it.

**Comment by KingLemming** [comment]
Going to go ahead and close this - I know that's *exactly* the case.

**Comment by Paksarra** [comment]
I do not have a texture pack. I'll look for the button that I did not previously notice.

Thank you, and sorry about that!

**Comment by KingLemming** [comment]
Bottom center of the GUI, just above the Player Inventory. In theory, you can't miss it. ;)

**Comment by Paksarra** [comment]
....

....how the heck did I miss THAT?

Thank you again. Clearly not having a good brain day.
