### ISSUE TITLE
Fractionating Sill accepts nothing at all.

### ISSUE THREAD

**Issue by 63502** [CoFH/Feedback#353]
I am using The Fractionating sill with ThermalExpansion-1.11.2-5.2.5.18-universal. There is no built in input slot, input/auto input via Thermal Dynamics Fluiducts is impossible, I cannot right click with a bucket/tank/etc to input liquid, and there is a broken texture in the gui.
![2017-07-07_00 26 06](https://user-images.githubusercontent.com/15267053/27943184-03df6dae-62ab-11e7-9395-6fb5ea391f9b.png)
Please help?

Also, TUMAT says 0/4000 mb Lava when I hover on the block when it is empty, if that helps.

**Comment by KingLemming** [comment]
The texture is an actual issue, and is now fixed in dev.

The rest of this is just factually incorrect, sorry. Your screenshot doesn't show the side configuration tab, but I'm betting if it did, you aren't trying to input on a "blue" side, are you?

**Comment by 63502** [comment]
UMMMMMM...

Just curious, but since which version did Resin only come from spruce trees?

Cause my arboreal extractors were extracting Sap, not Resin from an oak.

And I was trying to pipe Sap, not Resin.

Sap, not Resin.

*Facepalm*

**Comment by KingLemming** [comment]
Resin comes from most trees. Sap just happens to come from Oak.

Resin is still Spruce, birch, acacia, and jungle.

**Comment by 63502** [comment]
...

*Facepalms again*

**Comment by 63502** [comment]
Will sap ever be useful for anything? Since I now have an extra tank full of it, I may as well ask.

**Comment by KingLemming** [comment]
It's already useful for stuff. Have JEI? Look it up. Rich Phyto-Gro. :)

Which you can then use to make Fluxed Phyto-Gro. And you can use those in Arboreal Extractors to *greatly* boost Resin production.

**Comment by 63502** [comment]
*sigh*

Well thankfully my massive stupid moment wasn't entirely fruitless I guess.

I really need to stop playing minecraft a 2:00 AM.

**Comment by KingLemming** [comment]
In any case, thanks for pointing out the texture issue. I will be hotfixing that.
