### ISSUE TITLE
Thermal Foundation, no ores, at all

### ISSUE THREAD

**Issue by Plurp13** [CoFH/Feedback#353]
I've been having this very strange problem which makes me completely unable to use any CoFH mods, which are some of my favorites. I noticed in the last couple of worlds I made I wasn't seeing any thermal ores and I thought it might just be because I had a lot of other mods that added ores too. So I removed all but the CoFH mods I had and made a new world and went poking around in creative mod, I found plenty of every single vanilla ore but no thermal ores. Then I took out everything except CoFHCore and Thermal Foundation and recreated the world and again went poking around in creative in different places, again I found plenty of everything vanilla but no thermal ores. I have the latest everything, forge too, I've updated since I first noticed the issue but it's still not worldgening. I don't know if this is a really weird bug, or I'm just missing something. Is there a world type or config setting I've missed that will make it start working? I had used it in 1.7.10 before without issue so I'm extremely confused and a bit frustrated. Please help me.

**Comment by KingLemming** [comment]
Try a completely new installation. It sounds like you have a borked config but we can't really know where. But you can try the following:

CoFHCore handles Ore generation. The config for this is in /config/cofh/world, and you should see a ThermalFoundation-Ores.json file. If that isn't there, or it's blank, something has gone horribly wrong and you should wipe out your config folder completely.

This is more of a tech support thing than an issue, so I'm going to close this down and ask you to check our IRC please:

irc.esper.net
Port 6667
#ThermalExpansion

It's really your best shot for getting this resolved.

**Comment by Plurp13** [comment]
Oh, ok, whoops, thank you! Sorry for asking in the wrong place!
