### ISSUE TITLE
[1.10.2] Crash once loaded into world.

### ISSUE THREAD

**Issue by MUSE-iC** [CoFH/Feedback#354]
I wish I could give more info, but all I have is a crash log.

https://pastebin.com/b2z7GtD4

**Comment by KingLemming** [comment]
This is a CCL issue, not us. But I believe it's just been fixed.

**Comment by covers1624** [comment]
Fixed via: https://github.com/TheCBProject/CodeChickenLib/commit/cbadb4d8161b5c125861f4b55bdeebd4209a8e51
