### ISSUE TITLE
Casts in client-side packet handler unsafe due to packet reordering

### ISSUE THREAD

**Issue by planetguy32** [CoFH/Feedback#354]
Mod affected: Thermal Expansion, possibly others

Log: planetguy32/RemainInMotion#128 has the full log in the original post. The top part is most of what's relevant.

All mods: This looks like it might be possible with only CoFH mods, but a block-moving mod like Remain In Motion might make it more easily reproduced since it can replace tile entities en masse. I'm guessing it's caused by the server sending a block description and then a block change in quick succession, but the block change arriving before the description due to quirks of the network.

**Comment by KingLemming** [comment]
Packets are threaded, just how Mojang does it. The fact that this happens at all suggests that RIM moves Tile Entities in an incorrect manner.

Such a thing does not happen with Funky Locomotion, for instance, which can also move Tile Entities.

We have a try/catch block present for exactly this reason. The packet spam lets you know that somebody is doing something wrong. ;)

**Comment by planetguy32** [comment]
We just fixed a bug that caused moving blocks to leave behind copies of their tile entities, so that might have something to do with it.
