### ISSUE TITLE
Crash on World Join

### ISSUE THREAD

**Issue by MnMaxon** [CoFH/Feedback#355]
I'd like to start by saying you have done a great job with these mods, and thank you for creating them.
Include the mod name and version:
I'm using a few of your mods, I think the problem is with ThermalExpansion, but I'm not sure. I have:
CoFH Core 3.0.0RC7-211
ThermalFoundation 1.0.0RC7-62
ThermalExpansion 1.7.10R4.0.0RC7-141
I'm using the DireWolf20 modpack, but I updated your plugins to the latest ones to fix a drum crash recently.

When my game first crashed I wasn't sure why, I wasn't really doing anything, so I didn't read the crash log and I figured I just ran out of memory or something.  I logged back on, and played for about another 2 hours.  This time I noticed something weird, two or three chunks near my house weren't loading.  This happened before in an earlier version of the mod pack, but then it fixed itself, so I didn't pay much attention to it.  I don't think there were any thermal expansion machines in those chunks, there should have only been sugar cane and some sheep, so I don't know if this had anything to do with your mods or the crash.  My game then crashed again, so I thought my computer was just being stupid, and tried to log back on again.  I tried twice, and both times, while trying to join the world, my game crashed,  I eventually looked in the error log (below), so now I'm here.

pastebin: http://pastebin.com/uuW8cU8q - I believe this has all of the mods at the bottom, if you believe something may be missing, please tell me and I'll try to find a better list

Thanks for reading.

**Comment by KingLemming** [comment]
Yeah, this is on EnderIO's end. The RS conduits are very buggy at the moment.
