### ISSUE TITLE
Minor graphical bug.

### ISSUE THREAD

**Issue by 63502** [CoFH/Feedback#355]
The progress bar in the Redstone Furnace for Pyrolytic Converter recipes does not render. All other functionality seems to be fine.

I have not tested other augments to check them for the same issue yet, but I imagine I will get there eventually.

**Comment by 63502** [comment]
Update:

The bar will sometimes render after exiting the nether, but only for the first time opening the interface.

**Comment by KingLemming** [comment]
Got it.
