### ISSUE TITLE
[Thermal Foundation] Suggestion: Remove "TF:" from ToolMaterial names. (Witchery compatibility)

### ISSUE THREAD

**Issue by PaperTriangle** [CoFH/Feedback#356]
The "TF:" in the Material name for tools breaks compatibility with Witchery's Werewolves taking extra damage from Silver equipment. Either removing "TF:" from the Material's name or overriding the getToolMaterialName() method within the Tools themselves to remove such prefixes would amend this.

Obviously isn't a major problem, but is this possible?

**Comment by skyboy** [comment]
The prefix exists explicitly to avoid conflicts with other mod's materials. There can only be one of a given name.

**Comment by PaperTriangle** [comment]
That's cool. I'll bring this issue up with Witchery's dev, then, and ask them to look for TE:SILVER as well.

However I am curious. What kind of conflicts occur when two materials have the same MaterialName?
I ask as when testing this I made a material named TF:SILVER and applied it to a custom sword that would remove the "TF:" on getToolMaterialName(). I ran both that and Thermal Foundation at the same time and didn't run into any visible conflicts due to "TF:SILVER" being used as a name twice.

I had assumed that the EnumHelper returned a new instance ToolMaterial, so it wouldn't interfere. I am still learning Java as a hobby, so I am guessing this is wrong?

**Comment by KingLemming** [comment]
Well, the thing about ToolMaterial is that it's an enum. And you can't have two identical enums.

**Comment by PaperTriangle** [comment]
So, I'm guessing Forge doesn't check for pre-existing enum values that have the same String "key" as the one it is creating, so then it's possible to make multiple enum entries with the same String "key". And when .valueOf("") is called the wrong entry may be returned?
I hope my understanding is somewhat correct. Either way, I'll start prefixing my ToolMaterial entries.

That would be awesome! I'm unsure if there's a more efficient way to do it, but the piece of code I used was:
```java
    @Override
    public String getToolMaterialName()
    {
		return super.getToolMaterialName().contains(":") ? super.getToolMaterialName().split(":", 2)[1] : super.getToolMaterialName();
    }
```
I could set up a pull request based off of this, if the code's acceptable?
However, I'm feeling like this is more of Witchery's problem as they should take into consideration multiple ToolMaterials and check if the String contains "SILVER". So, feel free to close this if you decide no action should be taken! And thanks for the heads up on enum… I should really read more when I encounter unfamiliar Java things. <_<

**Comment by KingLemming** [comment]
Frankly I'm not sure what to do about this. The code there seems reasonable and I could just drop it in. The only place in Minecraft this is used is in the furnace, but I don't know what other mods are doing.

**Comment by skyboy** [comment]
Due to the possibility for bad x-mod interactions, it may be best if witchery checks for the standard namespacing on the material name and ignores it.

**Comment by KingLemming** [comment]
Actually, I went ahead and dropped the code in. We'll see what happens. I consider it sort of like an oreDict in this case.
