### ISSUE TITLE
[Question] Disable energy drain in dynamo

### ISSUE THREAD

**Issue by ExDomino** [CoFH/Feedback#356]
Hello, we are in 1.12 using the version 5.3.1.6 of ThermalExpansion and my players don't cease to ask me if there is a way to disable the slow power drain from dynamo. Because they lost a lot of coal, for example. With 4 compression dynamo, you can lost 4 coals every 10 minutes. I searched in the configs file but I didn't found anything in order to disable this behaviour. Can you tell me how to disable it please?

If it's not possible, can you add a config option to allow us to disable this behaviour please? Thank in advance.

**Comment by KingLemming** [comment]
There is an Augment specifically for this purpose - the Field Excitation Limiter.

So they can either use that, or they can more optimally balance their power generation with their power needs. :)

**Comment by ExDomino** [comment]
So if I add a Field Excitation Limiter, the power drain will be zero?

**Comment by KingLemming** [comment]
What do you mean by drain exactly? Idle dynamos do not lose energy.

**Comment by ExDomino** [comment]
Coals are taken from a Chest to a Pulverizer and pulverized into Pulverized Coal, then are converted into liquid into a Magma Crucible and then injected into the Compression Dynamo that recharges an Energy Cell that is used to power the Pulverizer and the Magma Crucible. They are full of energy, pulverized coal and water and nothing else drains energy from this network, for the moment. But I noticed that the amount of coal diminues from the Chest. I lost 4 coals after 10 minutes. The FTB wiki says « _This power will slowly drain and be lost if it's not removed from the dynamo_ » so I'm wondering if there is a way to disable that power drain and prevent energy lost, of in that case, the coal lost. Thank in advance.

**Comment by KingLemming** [comment]
Yes - what is happening there is that the Dynamos are only scaling down to 8 RF/t, so they are still running and burning through fuel. The Augment will prevent this.

The FTB wiki is wrong. Ignore it.

**Comment by ExDomino** [comment]
So, the Field Excitation Limiter will se this scaling down to 0 RF/t ?

**Comment by KingLemming** [comment]
Yes.

**Comment by ExDomino** [comment]
Thanks. I will craft three of them and upgrade my Compression Dynamos.

**Comment by KingLemming** [comment]
BTW, you should *really* make a Fractionating Still or two and turn that coal into a much better fuel.

If you don't have JEI installed, I highly recommend it.

**Comment by ExDomino** [comment]
A better fuel ? I will check that. Of course I have JEI installed. xD
