### ISSUE TITLE
[Question] Does it exist a lava pump?

### ISSUE THREAD

**Issue by ExDomino** [CoFH/Feedback#357]
Hello, it's a simple question: does it exist a lava pump to pump the lava? For water there is the Aqueous Accumulator, but does it exist something for lava? Thanks in advance!

**Comment by KingLemming** [comment]
Nope. And no immediate plans to add one.

Also, please use Twitch or IRC for questions. This is not a forum.

**Comment by ExDomino** [comment]
What is the address of your IRC ?

**Comment by covers1624** [comment]
Links can be found on http://teamcofh.com
