### ISSUE TITLE
CoFHCore crash in dev environment

### ISSUE THREAD

**Issue by maruohon** [CoFH/Feedback#357]
The game crashes with the following crash log, when launched in a dev environment with CoFHCore installed. I tried 3.0.0RC1-181-dev, RC7-211-dev (the latest stable) and the latest alpha RC7-221-dev, they all crash with the same error. Adding CodeChickenCore*-dev fixes the crash. I was wondering how I was able to use the CoFH mods before, but I have always also had CCC and NEI installed before now.

http://pastebin.com/Jqrf0FfD

**Comment by KingLemming** [comment]
That sounds like an issue where the ATs aren't correctly happening in your dev environment for whatever reason.

**Comment by maruohon** [comment]
Would it be something I could have messed up myself somewhere? Like in Eclipse settings? I can't think of anything else it could be...?

**Comment by KingLemming** [comment]
Possibly yes. It may be a thing as simple as ordering and how FML is dealing with deobf'd data.

**Comment by skyboy** [comment]
This is a problem with FML not including deobf->mcp mappings; as a result the deobf named ATs (required to work in actual installs) don't function in mcp envrionments. You'll need the CoFH_at.cfg file in your resources and setup your workspace with that, until FML changes this behavior.
