### ISSUE TITLE
crash when using thermal dynamics(1.12) not sure if cofh side or SN's side(mod interaction)

### ISSUE THREAD

**Issue by SDUBZ** [CoFH/Feedback#358]
Forge
TD:-1.12-2.3.1.6
TE: -1.12-5.3.1.6-universal
SN:1.12-1.0.10
crash report:
[crash-2017-07-09_23.48.02-server.txt](https://github.com/CoFH/Feedback/files/1133791/crash-2017-07-09_23.48.02-server.txt)

**Comment by KingLemming** [comment]
Not us. They're attempting to query a duct for a value it doesn't have.

**Comment by SDUBZ** [comment]
thanks for your help @KingLemming
