### ISSUE TITLE
Augment: GyroServo Feedback Operational?

### ISSUE THREAD

**Issue by Zang518** [CoFH/Feedback#359]
Hello, I have secondary chance augments in a resonant pulverizer. With all three augments in for the secondary chance says it boosts it to 45%. I pulverized a stack of gold ore thinking I should have about 27 ,28, 29 cinnabar. 64*.45=28.8. I got about 5 cinnabar not the 28 I was expecting. This seems to still equal the 5% chance 64*.05=3.2. Is there something I am doing wrong since it seems to be using the 5% chance instead of 45% or 50% (not sure if it adds to the current secondary chance)? It seems that having the augments in the pulverizer does nothing. Am I not understanding this correctly? Since TE 4 for 1.7.10 is somewhat new, there is not much information on the web to looks up yet. 
Here is the experiment
with all three secondary augments: out of a stack of 64 gold I got 5 cinnabar
Without any secondary augments: out of a stack of 64 gold I got  3 cinnabar

It is a bit less. Am I thinking the something different about the 45% secondary chance?

**Comment by KingLemming** [comment]
First of all, update. You're on an old version.

Secondly, you are interpreting them incorrectly. It's not +% chance; that would be *incredibly* overpowered.

**Comment by Zang518** [comment]
Awesome, thanks for the reply. I have much better understanding now.
