### ISSUE TITLE
[REQUEST] Diorite/Andesite/Granite Ore Support

### ISSUE THREAD

**Issue by SynfulChaot** [CoFH/Feedback#36]
Would it be possible to add the ability for the TF ores to generate directly in the alternate vanilla stone?

**Comment by KingLemming** [comment]
That's already possible with how our worldgen works. We won't add it as a default I'm afraid.

**Comment by KingLemming** [comment]
Reopened because I may have misinterpreted the question. Do you want alternate textures? That's not a thing that can easily be done to my knowledge, due to the metadata limitation.

**Comment by SynfulChaot** [comment]
Yes, alternate textures is what I had meant.

**Comment by Thiana** [comment]
Have a look at https://github.com/SlimeKnights/TinkersConstruct/blob/master/resources/assets/tconstruct/blockstates/ore.json @KingLemming.

**Comment by KingLemming** [comment]
Gave this one a lot of thought and there is absolutely no good way to do this without either using a bunch more block IDs or making the block a tile entity, and neither one of those options is acceptable for what is ultimately purely cosmetic.

Sorry.
