### ISSUE TITLE
Molten Glass in whitelist does not work.

### ISSUE THREAD

**Issue by BoboSims** [CoFH/Feedback#360]
Using ThermalDynamics-[1.7.10]1.0.0RC7-98
with TConstruct-1.7.10-1.8.2a

I installed a Hardened Fluiduct with a Reinforced Servo on the TiC Smeltery, and want it to *only* pour molten glass. So I made a Molten Glass Bucket, and put it in the whitelist. Then I set the servo to ignore Redstone signals. Result: it refuses categorically to pour any molten glass.

As soon as I remove the bucket from the whitelist, glass pours out. But putting the bucket back in effectively stops the drain.

**Comment by BoboSims** [comment]
Never mind... Obviously, the Blacklist/Whitelist button works reversed to what I expected, so I confused one for the other, making it not work.

**Comment by KingLemming** [comment]
Just curious, what was the confusion with the blacklist and whitelist button? Any way we can clarify it?

**Comment by BoboSims** [comment]
Well, the description mentions "Blacklist" as an *option*. So I didn't expect "Blacklist" to be the *default* state the Servo comes in. I imagined that if I were to press that black "Blacklist" button, the Servo would switch to blacklist mode. Therefor, the current state could only be the "whitelist" mode, regardless what the button said. Boy, was I wrong! :blush:

**Comment by KingLemming** [comment]
Right, if whitelist were the default mode it'd be sort of annoying. An empty blacklist is the typical "general" case so that's the default.

**Comment by BoboSims** [comment]
Yup, got that now. But maybe it would be an idea to *mention* that in the information. It would be helpful to idiots like me, to be told that the Blacklist option is the *default*. :stuck_out_tongue_winking_eye:
