### ISSUE TITLE
Fire EnderTeleportEvent with the resonant ender fluid.

### ISSUE THREAD

**Issue by darkhax** [CoFH/Feedback#361]
Hello, 

I noticed earlier that the resonant ender fluid does not fire the [EnderTeleportEvent](https://github.com/MinecraftForge/MinecraftForge/blob/16bfd8cef1d12ee9ca0de1122addaf9916767ae9/src/main/java/net/minecraftforge/event/entity/living/EnderTeleportEvent.java). This event is fired whenever an entity teleports in an ender way. This includes enderman and shulker teleporting, and ender pearls. Several mods such as Dark Utilities make use of this event to redirect ender teleportation, or outright prevent it in a designated area. I would really appreciate it if you could add support for this event for all the ender teleportation in your mods ^^

**Comment by KingLemming** [comment]
So I marked this as "under consideration," because I was pretty sure that we do actually use the event.

And sure enough, after tracing through the code, we do. It's already a thing.

**Comment by darkhax** [comment]
Oh, sorry to waste your time. I had a look through the Thermal Foundation source on GitHub but found no reference to it.

**Comment by KingLemming** [comment]
CoreUtils. We redirect the teleport call there and it handles the event.
