### ISSUE TITLE
Question: Lag of visible content in 1.11.2

### ISSUE THREAD

**Issue by PearlCanopus** [CoFH/Feedback#363]
I play 1.11.2 with a bunch of tech (IE, Mekanism, ...) and GUI mods installed. Usually the last release or beta ones. (WAILA, WAWLA, WAILA Harvestability, NEI 1,8+, JEI...)

When I use JEI to search items i.e. I can see the the Leadstone Energy Cell but no further one. A search for hardened shows up no results from TE.
With all my 85 mods inside I only have 26 item pages without any filters.

Do you know about any issues with one or more of these mods in 1.11.2?
I have'nt tried to use a knwon recipe from 1.7.10 in 1.11.2 yet because several of them have changed. So I cannot build, what I don't know exactly. :)
I'm not quite sure about 1.10.2 behaviour but I could check that tonight.

I would not believe that you have removed any content after 1.7.10.

**Comment by KingLemming** [comment]
So first of all, we did actually remove some content. Tesseracts, Illuminators, Plates, and some other Blocks. We've added new stuff though.

However, what's happening here is just that you're super unfamiliar with how the mod works now. Blocks are now upgraded in world with Upgrade Kits, and by default, the upgraded versions do not show up in the Creative Tab / JEI. You need to change your config files to make them show up.

Also, in the future please use the Twitch channel for questions:
https://app.twitch.tv/invite/SipeCoinsSvalna
