### ISSUE TITLE
[1.11.2] TD - NPE

### ISSUE THREAD

**Issue by Terpo** [CoFH/Feedback#364]
I've got a NPE for you but can't deliver much information as nobody was online while the crash happened:
https://gist.github.com/Terpo/770e7804b8dbeb9694c1786c085710a0

Forge: latest RB, 2386?
ThermalDynamics 1.11.2 2.2.5.10
ThermalExpansion 1.11.2 5.2.5.18
ThermalFoundation 1.11.2 2.2.4.12 

Happened a few minutes after I left the server. Can only think that it was my base as I'm the only one who uses TD currently.

**Comment by covers1624** [comment]
Please verify you are running the latest CoFH mods.

**Comment by Terpo** [comment]
When I find a way to reproduce this error I will try it with the new versions.

**Comment by KingLemming** [comment]
This can only happen if a tile entity lies to the servo. The only way for this code path to occur is if a tile entity claims to have an Item Handler capability and then returns a null upon request for that capability.

**Comment by Terpo** [comment]
Well, as there is no way to find out where it happened exactly I can only speculate at this point which TE could have caused it.

**Comment by Terpo** [comment]
Is the redstone check before the actual handler check or later? So, for checking I would turn of some of the servos that are Item related. So maybe I will find the erroring mod.

**Comment by KingLemming** [comment]
The RS check is before.

**Comment by Terpo** [comment]
ok, currently my new factory is completly offline. If the server stays stable for the next days I will reactivate servos. Can't do much more. This thread gets updated when I find the issue.

**Comment by KingLemming** [comment]
I went ahead and mitigated it on TD's end. There may be a very occasional case where a servo will appear to "not work," but that's because I'm catching the null and returning an empty capability, which will spare you the crash.
