### ISSUE TITLE
Cofh crash with Mekanism V8.0.201

### ISSUE THREAD

**Issue by enterprise12nx** [CoFH/Feedback#365]
Mekanism author says this crash is related to you, so here you go.
http://pastebin.com/ezCmSckL

my players are crashing on join from it

**Comment by KingLemming** [comment]
Yeah, we have no idea what version you're on. That line number makes no sense.

**Comment by KingLemming** [comment]
Also, does this *only* happen with Mekanism installed?

**Comment by enterprise12nx** [comment]
im using Cofh version rc7-211 (same with thermal expansion, etc)
and im not sure if mekanism is actually causing this, i had just reported it to him because players are crashing around the solar evaporation plant, but im not sure if thats actually the cause

**Comment by KingLemming** [comment]
Well, it's going to be really hard to track down unfortunately, as that line number doesn't correspond with anything else. Also, this is only report of this we've ever seen.

**Comment by enterprise12nx** [comment]
at first fastcraft gave the error, but after they removed fastcraft it gave this error.

**Comment by enterprise12nx** [comment]
anybody who enters that area crashes, im not sure what else i can provide /=

**Comment by KingLemming** [comment]
Can you make a copy of your server, remove Mek, and try on that copy? Because it's sounding like Mekanism.

**Comment by enterprise12nx** [comment]
i will see if i can give it a try

**Comment by enterprise12nx** [comment]
removing it crashes the server, enderio doesnt seem to like it being removed

**Comment by enterprise12nx** [comment]
This is the full mod list, all i know is players started crashing today in this one area where someone lives.  Nobody really knows whats causing the crash

Forge/FML by LexManos, cpw
Advanced Machines Immibis by Immibis
Advanced Repulsion Systems by immibis
Advanced Solar Panels by SeNtiMeL
Applied Energistics by AlgorithX2
Baubles by Azanor
Bdlib by bdew
BiblioCraft by Nuchaz
Big Reactors by Erogenous Beef
Binnie's Mods by Binnie
Biomes O' Plenty by TDWP_FTW, Adubbz
bspkrsCore by bspkrs
Buildcraft by CovertJaguar, SirSengir, Krapht, cpw, spacetoad
Carpenter's Blocks by Mineshopper
ChickenChunks by Chickenbones
Chisel by AUTOMATIC_MAIDEN
CodeChickenCore by Chickenbones
CodeChickenLib by Chickenbones
CoFH Core by CoFH team
ComputerCraft by dan200
CookieCore by ephys
CoroUtil by Corosauce
Dimensional Anchors by immibis
Doggy Talents by ProPercivalalb
Enchanting Plus by Freyjadono, mssodin23, GnRSlash, Qizzok, xkyouchoux
EnderIO by CrazyPants
EnderStorage by Chickenbones
Extra Cells by Leonelf
ExtraTiC by Glassmaker
Factorization by neptunepink
FastCraft by Player
Flans mod and official content packs by jamioflan
Forbidden Magic by SpitefulFox
Forestry by SirSengir
Forge Multipart by Chickenbones
Galacticraft by Micdoodle8
Gendustry by bdew
Gravitation Suite by SeNtiMeL
Growthcraft by Gwafu
HarvestCraft by MatrexsVigil, Rhodox
Hat Stand by iChun
Hats by iChun
iChunUtil by iChun
Immibis Core by immibis
Immibis's Microblocks by immibis
IndustrialCraft 2 by IC2 Dev Team
Inventory Tweaks by Kobata
IronChests by cpw
JABBA by ProfMobius
Liquid XP by immibis
Localized Weather & Stormfronts by Corosauce
LogisticsPipes by davboecki, AartBluestoke, ArtForz, GUIpsp, theZorro266
Magic Bees by MysteriousAges
Mantle by mDiyo, progwml6
Matmos by Hurricaaane
Mekanism by aidancbrady
MicdoodleCore by Micdoodle8
Minechem by ljdp
MineFactory Reloaded by skyboy026, powercrystals
Modular Powersuits by MachineMuse
Modular Powersuits Addons by eximius88, Andrew2448
MrCrayfish's Furniture Mod by Mr_Crayfish
Natura by mDiyo
NEI Addons by bdew
NEI Integration by Tonius
NetherOres by skyboy026, powercrystals
Not Enough Items by Chickenbones
NotEnoughCodecs by Mikeemoo
Nuclear Control by shedar
Numina by MachineMuse
OpenBlocks by Mikeemoo
OpenModsLib by Mikeemoo
OpenPeripheral Core by Mikeemoo
PneumaticCraft by MineMaarten
Power Converters by samrg472, powercrystals
Project Red by MrTJP, Chickenbones
QuarryPlus by yogpstop
Railcraft by CovertJaguar
Redstone Arsenal by TeamCoFH
Roguelike Dungeons by Greymerk
Simply Jetpacks by Tonius
Soul Shards Reborn by Moze_Intel
Steve's Carts 2 by Vswe
Thaumcarpentry by zot201
Thaumcraft by Azanor
Thaumic Tinkerer by pixlepix, nekosune, vazkii
ThaumicRevelations by Mortvana, MasterAbdoTGM50
The Mithril Mod by Dawars
Thermal Dynamics by TeamCoFH
Thermal Expansion by CoFH team
Thermal Foundation by TeamCoFH
TiC Tooltips by squeek502
Tinker's Construct by boni, mDiyo
Tinkers Steelworks by Toops, Ephys
TreeCapitator by bspkrs, DaftPVF
ttCore by tterrag
TubeStuff by immibis
Twilight Forest by Benimatic
Voxel Menu Music by The Voxel Box
VoxelLib by The Voxel Box
VoxelMap by The Voxel Box
VoxelMenu by The Voxel Box
Waila by ProfMobius
Waila Harvestability by squeek502
WAILAPlugins by tterrag
Wireless Redstone CBE by Chickenbones

**Comment by KingLemming** [comment]
Do you have the crash log from EnderIO complaining after Mekanism was removed?

**Comment by enterprise12nx** [comment]
http://pastebin.com/cYes9mnJ

**Comment by Yucca86** [comment]
Downgrade EnderIO to 363 build to prevent that Mekanism related crash

**Comment by KingLemming** [comment]
Okay, so looking at the fastcraft error, this is certainly a Mekanism issue. It's messing around with chunk loading in ways that it shouldn't be. That would cause both the Fastcraft and CoFH errors.

Sorry, but this is Mek. :/

**Comment by enterprise12nx** [comment]
@Yucca86 but i updated it because that is the version that fixes compatibility with mekanism V8
check their changelogs here

Also @KingLemming when they remove fastcraft, they get the cofh error. but i will talk to mekanisms author

**Comment by enterprise12nx** [comment]
@Yucca86 but i updated it because that is the version that fixes compatibility with mekanism V8
check their changelogs here

Also @KingLemming when they remove fastcraft, they get the cofh error. but i will talk to mekanisms author

**Comment by enterprise12nx** [comment]
well if its not mek, etc...how can i fix this :(

**Comment by KingLemming** [comment]
I'm willing to bet that removing Mek fixes it, but that's all I got for ya, sorry. :(

**Comment by enterprise12nx** [comment]
https://github.com/aidancbrady/Mekanism/issues/2426#issuecomment-88320208

Evidence shows that its either you or Mekanism, or both having an issue being together.

**Comment by KingLemming** [comment]
As I said before, this is Mek. No other mod seems to have a problem with us. Also, Fastcraft and CoFH don't crash together, but throw Mek in and it does?

Come on, it's Mek.
