### ISSUE TITLE
[1.12] Dupe bug

### ISSUE THREAD

**Issue by EmosewaGamer** [CoFH/Feedback#365]
On the 1.12 version, when you break an Energy Cell you get 2. The weird thing is that if you place one of them, the other one disappears, but if you place the other one, you keep the first one.

**Comment by KingLemming** [comment]
So, this doesn't actually seem to happen. Need more info.

**Comment by KingLemming** [comment]
Seriously, this doesn't seem to happen. Can provide a modlist please?

**Comment by EmosewaGamer** [comment]
I really don't believe that this answer is of any help:
https://minecraft.curseforge.com/projects/modern-skyblock-2/pages/version-112-mods-list

**Comment by KingLemming** [comment]
Hrm...no I'm afraid it isn't. I think the only way we're going to figure this out is to start with only CoFH mods and then add things until we can replicate the bug.

**Comment by EmosewaGamer** [comment]
Well apoarently there's also a bug where breaking any TE machine gives you a Redstone Furnace as well. I'm guessing that that's caused by whatever caused the first issue.

**Comment by KingLemming** [comment]
We already know that happens with PSI. And that's on PSI's end. Not sure what mod is affecting things in general to make this happen with pickaxes though.

**Comment by EmosewaGamer** [comment]
The cause was just the first mod I tested (as it simply made the most sense)
  https://minecraft.curseforge.com/projects/multi-mine

**Comment by covers1624** [comment]
Well its probably on multi-mine then, i see they are a coremod for god knows what reason, who knows what they are doing with their transformer..

**Comment by KingLemming** [comment]
Cool. Good to know.
