### ISSUE TITLE
Flux-Infused OmniWrench in Autonomous Activator doesn't shear sheep

### ISSUE THREAD

**Issue by mconwa01** [CoFH/Feedback#366]
Wrench and AA are charged. Vanilla Shears and the metal shears from TF work as expected when AA is set to Right Click, Not Sneaking, and facing any direction but down. OmniWrench actions on machines work (rotate when not sneaking, dismantle when sneaking).

I can't get either the Shears or the OmniWrench to shear a sheep when the AA is facing down, but that may be due to range and the height of the sheep and may not be a bug. (I tried getting the sheep closer to the AA by having it stand on a slab, but that didn't work either.)

Minecraft Forge 10.13.2.1291
CoFH Core 3.0.0RC7
Thermal Foundation 1.0.0RC7
Thermal Expansion 4.0.0RC7
Redstone Arsenal 1.1.0RC7

**Comment by mconwa01** [comment]
The OmniWrench can shear sheep when used by an OpenComputers (1.5.3.10) robot, if that helps at all.

**Comment by KingLemming** [comment]
Fixed this in dev, but it's actually a bug that it was working with OpenComputers. They should look into that as they are ignoring onUse returns.
