### ISSUE TITLE
Interaction of Fluids between mods and worldsaves

### ISSUE THREAD

**Issue by BluSunrize** [CoFH/Feedback#366]
Hiya!
So, over some time now, people have been reporting an issue with fluids breaking in existing worlds after other mods (IE in my case) get added. I did some investigating today, looking at how Forge handles fluids internally and in regard to world saves and I think I figured out what's causing the respective issues. I compiled a description of the problem and how we could combat this from the mod devs side (since I doubt Forge is gonna fix it).

### Description of the issue:.
A mod registers a fluid with a certain name (let's use the example "creosote"). The player starts a world. Forge automatically remembers that fluid as the "default" for that world.
Another mod is then added that loads *before* the original mod (example, Immersive Engineering loads before TE) and also adds "creosote". This means that during loading, the second mod's fluid is the default one. Forge uses this default to load its textures, register buckets and blocks.
The player loads the world; Forge recognizes the existence of an old default fluid and continues using it. Within the fluid registry, the first mod's fluid becomes the default again (while that world is loaded anyway).

### Now, as a result:
 - The fluid lacks textures (they weren't loaded, because it wasn't the default fluid during stitching)
 - Machines can't fill buckets (bucket registry contains the second mod's fluid, not this active one)
 - TE Florbs crash (they were initialized with the second fluid, which has a block, but the active one doesn't, and they don't nullcheck)
 
### Proposed fixes for this (on the sides of all Mod Developers):
1) Stitch your fluid's textures with the stitch event. That guarantees the fluid's texture to always be present.
2) Register a bucket for your fluid (before grabbing the active one from the Dictionary), basically insert the bucket registration here: https://github.com/CoFH/ThermalFoundation/blob/master/src/main/java/cofh/thermalfoundation/init/TFFluids.java#L57
3) Make Florbs null safe (maybe re-evaluate them at server start, or just add a !=null in their update method and kill them if the fluid has no block)

Thoughts?

**Comment by KingLemming** [comment]
I've actually already done this in the most recent builds, except for the bucket part. I'll add that too.

**Comment by BluSunrize** [comment]
Well a fluid name doesn't necessarily help, I don't think.
Because then you'd do "getFluid", which provides you with the TE fluid (the local default to that world), which doesn't have a bucket associated, because IE registered it first.

**Comment by KingLemming** [comment]
Ah yeah, that's fair. Hmm...that's a bit of a Forge bug IMO. Fluid Blocks should be auto-remapping onto the default fluid.

**Comment by KingLemming** [comment]
On a side note, this is why I initially forced a hard crash when I designed the new Fluid system and required that everyone made their fluids configurable. Maybe a bit of tough love, but stuff like this NEVER HAPPENED.

**Comment by BluSunrize** [comment]
Once again, I don't get why that default thingy is in anyway. Fluids are supposed to be equal, why the heck do worlds need to save a default? If you install a new mod that registers earlier, so what. Guess the texture changes, though luck. Should still not do weird stupid caching things.

**Comment by KingLemming** [comment]
They shouldn't, IMO. And while I know that Lex would probably give me full control over a rewrite...oy vey on actually doing it. Not sure if I can stomach it.

**Comment by KingLemming** [comment]
Just so everybody linking to this knows, builds of TF which address this have already been pushed.

**Comment by KingLemming** [comment]
CurseForge, same with all of our builds.

**Comment by leagris** [comment]
Latest CoFH Core on CurseForge:
https://minecraft.curseforge.com/projects/cofhcore/files?filter-game-version=2020709689%3A6452
CoFHCore-1.11.2-4.2.6.14-universal.jar

Anyway still has issue with breaking Creosote buckets from Immersive Engineering.
Also breaks buckets from Galacticraft Oil

**Comment by BluSunrize** [comment]
Are you also using latest TF and TE, as well as latest IE? >_>

**Comment by KingLemming** [comment]
I've fixed it on my end, I can't speak for everyone else.

**Comment by BluSunrize** [comment]
I register all icons manually and register my buckets before grabbing the updated fluid from the registry. All that I can do, I believe I have.
Would need more info on this apart from "breaking buckets" =P

**Comment by KingLemming** [comment]
Yeah, the buckets w/ Galacticraft Oil is a different interaction entirely - probably Actually Additions or Buildcraft.

**Comment by leagris** [comment]
I use all latest versions for 1.11.2
http://rawgit.com/Beyond-Reality/Beyond-Realty-Farscapes/master/modlist.html?p=Beyond-Reality:%20Farscapes&v=1.1.1-r3

If I remove all Thermal mods, then IE Creosote Bucket works as intended and textures are ok. As soon as I reinstall Thermal And CoFH, Creosote bugs.

**Comment by BluSunrize** [comment]
Oh you're playing 1.11.
Yeah I don't dev for that anymore, it doesn't have my fluid fixes. Nothing Lemming can do about that =P

**Comment by KingLemming** [comment]
Ah. Yeah, I backported it to 1.10 and 1.11 on my end. But I can't fix everyone else's stuff, sorry. :(
