### ISSUE TITLE
[Thermal Expansion] Creative Strongbox config option misisng

### ISSUE THREAD

**Issue by SirWilli** [CoFH/Feedback#367]
hey,

the config option to disable the creative strongbox is missing. I tried to add
```
    Creative {
        B:Enable=true
    }
```
to the strongbox settings but the strongbox is placeable.

**Comment by KingLemming** [comment]
Well first of all, if you tried *enabling* the strongbox, then of course it would be placeable.

Secondly, no - there is no option to prevent placement of the Strongbox. The options prevent recipes from working.

**Comment by SirWilli** [comment]
1. Ups, I have it on false for sure, just typo here.

2. Hm? The creative cell, strongbox, cache and sponge have a option to disable it which will remove the item from the invenetory if someon tries to place it but this option is missing for the strongbox.
> Don't give your players admin. Seems easy enough.
That's not the issue. There are many mods which corrupt the item if it gets broken.
For example Draconic Evoulion or Thaumic Tinkerer Kami which has a pickaxe with a 3x3 radius. If you break a block next to the strongbox/cache/tank... it will drop the creative type of it.

**Comment by KingLemming** [comment]
>creative cell, strongbox, cache and sponge

Again I'm confused, but I assume you mean tank.

Anyways, I hope you've reported the bug to the mods in question then.

The option wasn't properly being saved to the config file. It is now in dev, but it's pretty low priority. It'll be out with the next release.

**Comment by SirWilli** [comment]
I don't think it is only a config save/generation issue. As I added the option like see below and the strongbox doesn't dissappear like the other creative items/blocks.
```
Strongbox {

    Creative {
        B:Enable=false
    }

    Basic {
        B:Recipe.Enable=true
    }

    Hardened {
        B:Recipe.Enable=true
    }

    Reinforced {
        B:Recipe.Enable=true
    }

    Resonant {
        B:Recipe.Enable=true
    }

}
```

**Comment by KingLemming** [comment]
No, it was. Really. It's fixed in dev.

**Comment by SirWilli** [comment]
Okay, will wait for the update then, thanks.
