### ISSUE TITLE
[Unclear Operation] Residual Capacitance Drain+Loss When Connecting/Disconnecting Machines to Fluxducts

### ISSUE THREAD

**Issue by MonaMoonlight** [CoFH/Feedback#367]
I had some issues with unexpected power drains again while playing, and after some testing, I found that: 

- Any given number of fluxducts - for the lowest five tiers - above 1, in a connected line, with no more than one giving cell and a receiving machine, has a residual capacitance of the per-tick transfer rate of its tier, times five. For instance, the lowest tier's rate of transfer is 1 000 RF/t, giving 5 000 RF of residual capacitance. The highest tier with residual capacitance, Resonant Fluxduct at 25 000 RF/t, gets a whopping 125 000 RF of residual capacitance.

- Each time more machines or cells are connected, this capacitance is increased by 100%, and the vacancy this causes is filled, causing a drain of 5k/20k/45k/80k/125k RF each time (depending on tier).

- Each time one is disconnected, it is decreased again by 100%, and what was previously drained to fill the vacancy is - if not used up - simply _lost_, although this loss in charge is gradual and can be seen with use of a multimeter.

- The above two things happen regardless of whether the machines or cells are charged fully or not.

This issue is similar to the one that existed a while back with duct covers #281 , although it does not result in a complete power loss, just a portion of the total RF stored as part of the residual capacitance mechanic.

As such it is less serious, but like the issue with the ducts, the power losses do add up quickly.
I can see how it is more dynamic than how it worked in the past, but it is also a great deal more lossy.

It feels as though it unnecessarily penalizes you for moving machines.

Confirmed for 1.12-2.3.2.9 of Thermal Dynamics

**Comment by KingLemming** [comment]
So what's happening here is that you are removing and re-adding nodes from/to the system. Only nodes store energy. This is 100% intentional, working as intended, and in all likelihood will not change. Also, they have literally always been like this. Nothing new.

**Comment by MonaMoonlight** [comment]
Ah, okay o_o

Now I feel sheepish.

**Comment by KingLemming** [comment]
No worries. I admit, it's not super apparent what's happening, though at the same time if you have enough extra energy to keep your lines fully charged all the time, the losses shouldn't really mean much to you.

Heck, machines don't store their RF, so wrenching a machine is already a loss of up to 600k RF if it was fully charged. I realize that's not ideal either, but people tend to prefer it for the purposes of having the blocks stack.

**Comment by MonaMoonlight** [comment]
Wait... They don't?
Because I just wrenched some machines of the same tier and charge, that stacked, and retained their charge when put down.

**Comment by KingLemming** [comment]
My bad. I added that. Hah!

**Comment by MonaMoonlight** [comment]
Oh, hah xD
