### ISSUE TITLE
[1.10] Client crashes after placing Cryo-Stabilized Fluxduct

### ISSUE THREAD

**Issue by balcas** [CoFH/Feedback#368]
Hey basicly i placed a Cryo-Stabilized Fluxduct and i got a crash now i cant even connect back to the server it instantly crashes the client for me. Can you take a look at this crash log for me?
[crash-2017-07-12_12.txt](https://github.com/CoFH/Feedback/files/1142892/crash-2017-07-12_12.txt)

**Comment by KingLemming** [comment]
Try without Optifine. This is a pretty low level byte-buffer issue and it's way outside the scope of anything we do.
