### ISSUE TITLE
Thermal Dynamics Server Crash

### ISSUE THREAD

**Issue by ako1** [CoFH/Feedback#369]
Happened while either removing an item retriever or removing a me interface off the retriever (not sure which one I clicked first) with a wrench:

http://pastebin.com/zP01fdyw

Using v1.3.4 FTB Infinity: https://feedthebeast.atlassian.net/wiki/display/PML/Infinity+1.7

Server will not restart and produces the same crashlog on restart: http://pastebin.com/WepER87K

**Comment by KingLemming** [comment]
Duplicate of #291.
