### ISSUE TITLE
[RedstoneArsenal] Flux-infused pickaxe disappear blocks

### ISSUE THREAD

**Issue by marcin212** [CoFH/Feedback#37]
https://github.com/CovertJaguar/Railcraft/issues/473
CoFHCore-[1.7.10]3.0.0B9-96
CoFHLib-[1.7.10]1.0.0B9-64
ThermalExpansion-[1.7.10]4.0.0B8-23
ThermalFoundation-[1.7.10]1.0.0RC1-27
RedstoneArsenal-[1.7.10]1.1.0RC1-25
Forge-1.7.10-10.13.2.1286

**Comment by KingLemming** [comment]
Please attach a proper modlist. You obviously have RailCraft installed as well at the very least.

**Comment by marcin212** [comment]
Custom modpack on forge.
My modlist:
http://i.gyazo.com/cc6364cc93c4501692d6c400db635a3f.png
I have problem only with block from railcraft.

**Comment by KingLemming** [comment]
Oh that's interesting. ONLY RailCraft huh?

Obviously, the fault is with RSA.

Here's the code which works with literally every other mod in the game:

if (isEmpowered(stack) && canHarvestBlock(block, stack)) {
				Material bMat = world.getBlock(x, y, z).getMaterial();
				Block adjBlock = world.getBlock(x, y - 1, z);
				if (adjBlock != null && adjBlock.getMaterial() == bMat && adjBlock.getBlockHardness(world, x, y - 1, z) != -1) {
					harvestBlock(world, x, y - 1, z, player);
				}
				adjBlock = world.getBlock(x, y + 1, z);
				if (adjBlock != null && adjBlock.getMaterial() == bMat && adjBlock.getBlockHardness(world, x, y + 1, z) != -1) {
					harvestBlock(world, x, y + 1, z, player);
				}
			}

This is on RailCraft's end.

**Comment by CovertJaguar** [comment]
That code isn't really relevant...canHarvestBlock() and harvestBlock() are where the action happens.

**Comment by KingLemming** [comment]
That's actually fair - for some reason I thought those were world calls. Still, it's curious that it'd only happen with RC stuff. We'll look into it more.

**Comment by skyboy** [comment]
Fixed in dev.
