### ISSUE TITLE
[Thermal Expansion] Crash on server and client

### ISSUE THREAD

**Issue by DJDaemonix** [CoFH/Feedback#370]
Greetings,

I recently updated Thermal Expansion and MineFactory Reloaded to their latest versions, only to find that Thermal expansion crashes on launch on my client AND my server.

They all seem to have the same crash : 
NoClassDefFoundError: thermalexpansion/util/crafting/SmelterManager

Here is the entire modlist of my client (server has client-only mods removed): http://puu.sh/gTOHJ/b35e28da6b.png

Further information needed will be provided if asked.

Thank you,
DJ Daemonix

**Comment by KingLemming** [comment]
The crashlog would have been nice, but the problem is that Project Red is out of date.
