### ISSUE TITLE
[Suggestion] [1.12] Tesseract augment

### ISSUE THREAD

**Issue by Skillotic0703** [CoFH/Feedback#370]
This is an upgrade which adds a tesseract tab to a machine. (When tesseracts come back!)
It allows to directly receive power, I/O fluids and items through a tesseract channel.
That allows to have a clean machine room without cables everywhere.
That allows to save faces on a machine to put thermal mediators for example.
That allows to make a multimachine with only one I/O.
If you want for example a giant pulverizer factory, you connect a lot of pulverizers on the same channel and you input and output items from one tesseract!
That would be the best feature in all the history of TE! (imho)

**Comment by Tahakk** [comment]
Since there is no tell how will new Tesseracts work ( hoping that I haven't missed it), let's say we wait for it and then we shall see. :)

**Comment by KingLemming** [comment]
This won't be happening because Tesseracts won't operate in this fashion, sorry. :)
