### ISSUE TITLE
[Bug] Upgraded Machines do not correctly set ItemStack size upon eject in all cases.

### ISSUE THREAD

**Issue by MonaMoonlight** [CoFH/Feedback#371]
~~I just found out through JEI that Diamond horse armor could be pulverized for 10 diamonds, and did so, but only got 8.~~

~~Testing in creative, I got 10, as I first expected.~~
~~Recreating my setup from survival game yielded the same result.~~

~~Then in survival, I noticed that there were 10 diamonds in the pulverizer just after the horse armor got done being pulverized, but once they had been sucked through a shorter length of impulse itemduct and into a chest, two had somehow gone missing.~~

~~In creative, it seemed as though the diamonds got sucked out in two groups, presumably 8 and 2, and somehow that doesn't happen in survival...~~

The bug has to do with upgraded versions of Pulverizer and Induction Smelter outputting fewer items into ducts than they're supposed to.

Confirmed for 1.12 - 5.3.2.10 of Thermal Expansion, and 1.12-2.3.2.9 of Thermal Dynamics.

**Comment by KingLemming** [comment]
The Pulverizer ejects items in quantities based on its level, starting at 8. So yes, it ejects 8 and then 2.

The 2 don't go missing, you either simply missed where they went to or didn't wait for them to arrive.

Creative/Survival has nothing to do with this and everything is working fine.

**Comment by MonaMoonlight** [comment]
There's only one way for them to go, and they didn't go there, I checked.

And yes, I am aware it doesn't have anything do to with the mode, it's just that in one game it works as intended, and in another it doesn't.

**Comment by KingLemming** [comment]
I actually tested this, just so you know. What you're describing doesn't happen. You get 10 diamonds consistently, and they travel through any length of duct and arrive properly.

**Comment by MonaMoonlight** [comment]
Do you think it could be an issue that has to with the fact that I started that particular game world on a different version?

**Comment by KingLemming** [comment]
Nope. What you're describing as a bug just doesn't make any sense here - the Pulverizer is agnostic about what it ejects to, or what it is ejecting, and the ducts just transfer stuff that has been handed to them.

It's literally impossible to have a bug where transferring items from one particular recipe is wrong in one particular game mode.

**Comment by MonaMoonlight** [comment]
I tested again, and I think I found the problem...
Try pulverizing with a pulverizer upgraded to Hardened.

**Comment by MonaMoonlight** [comment]
I tested pulverizing diamond horse armor on every upgraded tier of pulverizer, and they all send out 8 diamonds into impulse itemducts.
Seems it has to do with the upgrade tiers and how they eject items.

**Comment by KingLemming** [comment]
This doesn't seem to happen in dev, so I'm not sure what may be going on in live. I'll spin up an instance to confirm though.

**Comment by MonaMoonlight** [comment]
It seems this bug is also affecting the yield from the other horse armors, when using the Induction smelter on any tier but basic.

**Comment by KingLemming** [comment]
Okay, found the *actual* bug, which had nothing to with horse armor, pulverizers, smelters, or ducts.

Sorry for thinking you were a crazy person, but your initial post came off as the ramblings of a madman.

**Comment by MonaMoonlight** [comment]
It's alright, you don't know me personally, so that's totally understandable x_x

**Comment by kolhed** [comment]
Is this related to when I'm missing items, and when looking in the furnace the fire "is burning" at as close to 100% as possible, the sound is running, but there is nothing in it... 
same thing with pulverizer
I get this very much using xnet to roundrobin into several machines

same versions as op

**Comment by KingLemming** [comment]
Haven't heard of that issue. Nor have I ever seen it. May be something on XNet's end.
