### ISSUE TITLE
Steam Dynamo doesn't require water to operate

### ISSUE THREAD

**Issue by Zetharion** [CoFH/Feedback#372]
I searched for Dynamo and didn't see this issue.  I have TE version 1.12-5.3.2.10-universal and when my Hardened Steam Dynamo ran out of water, it continued to generate RF even without it.  Its augmented with Auxiliary Transmission Coil

**Comment by Zetharion** [comment]
On the topic of the steam dynamo, is it supposed to burn a block of coal at the same rate as a piece of coal?

**Comment by KingLemming** [comment]
Do you mean same RF/t? Yes.

**Comment by Zetharion** [comment]
Restarted my world and once my energy storage got low enough, it did work as intended.
