### ISSUE TITLE
Thermal Dynamics Flux-Plated/Fluctuating Pass-through?

### ISSUE THREAD

**Issue by ShadowDrakken** [CoFH/Feedback#372]
It appears that while Flux-Plated and Fluctuating ducts can accept power and can run it along to machine, they don't currently allow that power to re-transmit back onto fluxducts at the other end.

Not sure if this is by design or a bug. If it's by design, it'd be nice to have it documented or configurable to where you can offload back onto fluxducts. As it stands, it's either broken or counter-intuitive.

**Comment by KingLemming** [comment]
Just tested. Fluxducts can receive power fine from both Flux-Plated and Fluctuating. It works just like every other tier of Fluxduct - there is a connection made where the two networks join and that is treated just like any other node.

**Comment by ShadowDrakken** [comment]
Except it isn't and doesn't, but whatever.

**Comment by KingLemming** [comment]
Okay, provide screenshots and explain then please.
