### ISSUE TITLE
Suggestion/Question: Warp Itemducts in 1.11

### ISSUE THREAD

**Issue by kaosjr** [CoFH/Feedback#373]
I've been playing around with Thermal Dynamics and Thermal Expansion for ore processing in 1.11, and I've noticed the removal of an entire tier of itemducts: Warp Itemducts.
The counterparts for fluids and energy are there: Super-Laminar Fluiducts and Cryo-Stabilized Fluxducts, so I was wondering what happened to the instant variety of Itemduct. The highest tier currently available is Impulse Itemducts, and those definitely have a speed limit.
I was just confused about why exactly they aren't in 1.11 yet, and if there isn't a particular reason I would like to see their return.
Thanks!
-kaosjr

**Comment by KingLemming** [comment]
They're not coming back for 1.11 because we aren't actively developing 1.11 anymore. In general, they won't be coming back - we have another idea for how we want a higher tier of duct to work, but it's not implemented yet.

When it is implemented, it'll be in 1.12.
