### ISSUE TITLE
MFR [latest build (1.7.102.8.0RC8-86)] requires Ender IO now????

### ISSUE THREAD

**Issue by Ianaver** [CoFH/Feedback#373]
EnderIO is required for some reason and gives the following crash when not installed:

http://pastebin.com/P1HsTSbK

**Comment by Ianaver** [comment]
I did this with only CoFH core and MFR and I still get the same crash but with out all the extra gibberish about the other mods being loaded

**Comment by KingLemming** [comment]
Do you have the EnderIO recipes enabled by chance?

**Comment by skyboy** [comment]
You have EnderIO recipes enabled in the config. You can't enable that if you don't want to play with EIO.

**Comment by Ianaver** [comment]
I did nothing more than let MC create a new config... (I don't know if its enabled by default)

**Comment by KingLemming** [comment]
Try fresh installs of your mods and wipe your MFR config please. This can only happen if TE and EIO are not installed, and EIO recipes are set.

**Comment by Ianaver** [comment]
ok
