### ISSUE TITLE
[1.12] RedPrint not storing Auto-Input/Output

### ISSUE THREAD

**Issue by 016Nojr** [CoFH/Feedback#374]
The Redprint doesnt copy the Auto-Input/Output options on (in this case Pulverizer) TE machines. 

I guess this is on TE's end, so I have not  tried it with an instance with only CoFH mods.

Forge: 14.21.1.2407
CoFH Core: 4.3.2.7
TE: 5.3.2.10

**Comment by KingLemming** [comment]
This was actually an intentional omission, and I don't remember why now. Let me revisit the reason.

**Comment by 016Nojr** [comment]
Interesting, I can probably understand why. Is it too much work to add a toggle option so you can choose if you want to copy the auto-input/output aswell?

**Comment by KingLemming** [comment]
That would be inelegant and inconsistent, so work aside, won't be happening.

I'm still trying to remember the initial reason for not copying it, tbh.

**Comment by KingLemming** [comment]
Found the initial reason and it's largely no longer relevant now. So added a couple of minor checks and this will be a thing going forward.
