### ISSUE TITLE
MFR issues go in here too? Mega rubber tree possibly too huge

### ISSUE THREAD

**Issue by Frontrider** [CoFH/Feedback#375]
https://drive.google.com/file/d/0By-HkGt_YSxeRE9PRGhucmNiY2M/view?usp=sharing

Seems to be the best place to post, i'll put on a log as soon as i can.

i got to know that it was a sacred rubber. This is the intended behaviour for them?

**Comment by Xorifelse** [comment]
Oh, that's nothing. I've seen bigger ones. Intended behavior I presume. You can disable it in the config file. But I do agree its a bit over the top as it crashed my server upon generation.

**Comment by KingLemming** [comment]
I can't really make heads or tails of that screenshot.

skyboy says that this is intended for the blessed sacred rubber trees or whatever they are. They can only spawn in Stronghold chests and there is no way to otherwise acquire them.

They can also be disabled in the config.
