### ISSUE TITLE
[Suggestion] [1.12] Redstone Reception Coil

### ISSUE THREAD

**Issue by llloyd4** [CoFH/Feedback#375]
So, I just started to play MC 1.12, the All The Mods 3 mod pack. I was noticing there are no early game tech mods for RF except Thermal Dynamics. I started to make a Pulverizer when I noticed the Redstone Reception Coil needs gold. That is one of the hardest metals to find in Minecraft, it's super rare. But the basic tier leadstone pipe needs only lead which is a lot more common. Now, agreed, gold is a very good conductor but so is copper. It's in millions of homes as house wiring. Maybe, and this is just my opinion, hence a suggestion (and subject to round filing of course) the coil should use one copper and two redstone instead? It would make it a lot more early game friendly. The upgrades already cost quite a bit so...

**Comment by KingLemming** [comment]
It's been this way for literally years. If you're deep enough to find redstone, you're deep enough to find gold.

You can change it with CraftTweaker, but it won't be changing in the base game, sorry.
