### ISSUE TITLE
[Suggestion] Flux Capacitor : Invert Armor and Held Items icons

### ISSUE THREAD

**Issue by ExDomino** [CoFH/Feedback#376]
Hello. My suggestion is about the Flux Capacitor, all tiers. At this moment, the red dot at the left indicates that items are charged, right dot indicates armor is charged. But the armor is in the left in the inventory window, so I think it would be more user-friendly to set that armor is the left dot and items is the right dot.

**Comment by KingLemming** [comment]
I get what you're saying, but Held is Mode 1, Armor is Mode 2, and things read left to right, at least in most Western languages.

You can always make a texture pack if you'd prefer it the other way personally. :)
