### ISSUE TITLE
Pulverizer Recipe Suggestion

### ISSUE THREAD

**Issue by Flexico** [CoFH/Feedback#377]
I'd like to suggest giving a small chance of getting Iridium Ore (IC2) when pulverizing Sky Stone (AE2) because meteorites are actually the world's main source of iridium in real life. Some might consider this overpowered, as iridium is supposed to be insanely hard to get, but I think Sky Stone is sufficiently rare (and such a beautiful building material if you use the Sphax resource pack) that it would be a significant sacrifice to grind it all up for your iridium.

**Comment by Xee1** [comment]
With Meteorite Compass(AE2) is very easy to get SkyStone.

**Comment by Flexico** [comment]
That thing never worked for me. XD

**Comment by KingLemming** [comment]
This is the kind of thing that ModTweaker is really good for. I'll be adding json recipe support to TE, but I won't make this a default recipe, sorry.
