### ISSUE TITLE
Tier System 1.12

### ISSUE THREAD

**Issue by Buddii** [CoFH/Feedback#377]
Hey,
i installed thermal Expansion and my problem is, that i cant Craft the other Tier Upgrades.
In my JEI are only the Basic recipes. Do i need another Mod ?

Sorry for my bad english skills^^

**Comment by KingLemming** [comment]
Please don't use the tracker for questions, only actual issues. :/

Blocks are upgraded in world now, using Upgrade Kits. Look through the creative tab and you'll see them.
