### ISSUE TITLE
[1.12] Portable Tank seems to always return false for canDrain and canDrainFluidType

### ISSUE THREAD

**Issue by faceofcat** [CoFH/Feedback#379]
this is for when you get the FLUID_HANDLER_ITEM_CAPABILITY from the item.

calling drain(..) works fine and you get the fluid stack.... 

but... drain() and canDrainFluidType() should return true if the right liquid can be drained from the tank.

**Comment by KingLemming** [comment]
canDrainFluidType() isn't a thing. What in the world are you talking about? Also, drain() returns a FluidStack, not a boolean.

Please make sense.

**Comment by KingLemming** [comment]
Oh, I figured it out. You're talking about IFluidTankProperties, which is a completely optional thing and does nothing except waste CPU cycles. It shouldn't be used and is legacy nonsense dating all the way back to BuildCraft.
