### ISSUE TITLE
Add links to http://crafting-guide.com

### ISSUE THREAD

**Issue by andrewminer** [CoFH/Feedback#38]
I've been working on a project to make it easier to deal with complex mods (especially tech mods), and I recently added support for Thermal Expansion.  The gist of the site is that you tell it what item(s) you want to make, and it will figure out all the raw ingredients you need along with step-by-step instructions.  For example, here's how you [make a Tesseract](http://crafting-guide.com/item/tesseract).

The maintainers of mods I've added (e.g., BuildCraft / Applied Energistics) have found it useful to include links to Crafting Guide in their official documentation, and I was hoping you would feel the same.

**Comment by andrewminer** [comment]
@KingLemming Not to be impatient, but any word on this suggestion?  Thanks!

**Comment by KingLemming** [comment]
So basically you want us to link from our website?

**Comment by andrewminer** [comment]
Pretty much!  For mods with public wikis (e.g., [Industrial Craft](http://wiki.industrial-craft.net/index.php?title=Electric_Jetpack)), I've (with permission) added links from each item to the matching page on Crafting Guide.  For others (e.g., [Applied Energistics](http://ae-mod.info/)), there's just a single link on the homepage.  Whatever you think would be most helpful to people using the mod!

**Comment by andrewminer** [comment]
@KingLemming Just checking in on whether you like the idea... thanks!

**Comment by KingLemming** [comment]
I've let the website guys know; they're doing a rewrite of things and we'll find a place for it.

Nice site!

**Comment by andrewminer** [comment]
Thanks!  I'm looking forward to the new site!

**Comment by andrewminer** [comment]
Any update on adding that link?  It would be much appreciated!

**Comment by KingLemming** [comment]
The guys are working on the new site. Ideally we'd actually have dozens of links to the site, but we can probably just put one up for the time being.

**Comment by andrewminer** [comment]
Would it help if I could make Crafting Guide the official home of the detailed information about each item?  I've added features recently which allow you to enter any information you like to each item page as well as stand-alone tutorials for each mod.  What's missing still is most of the content.

It would be great for Crafting Guide to have an opportunity to get some great content like the TeamCoFH mods, and I expect it would speed up the process of revamping the website if you could simply link to Crafting Guide for the item content.

Would that work for you?  If not, I'd love to hear what you think is missing from Crafting Guide so I can keep improving it.  :-)

**Comment by KingLemming** [comment]
Link is now up on the site as part of the main sidebar. We may add links on all the sub-pages. We'll see. The entire website has been pretty low priority due to time constraints.

**Comment by andrewminer** [comment]
Thanks!  Any interested in using Crafting Guide to host some of the documentation?  Might make that project go a lot faster not to have to create pages for each item.  :smile:
