### ISSUE TITLE
No sounds when placing a portable tank on a tank

### ISSUE THREAD

**Issue by 016Nojr** [CoFH/Feedback#38]
The title sums it up. When you right click a portable tank on a portable tank it places it as it should, but the sound when placing the tank isnt played. https://youtu.be/bPFPn0ZxNkU

**Comment by KingLemming** [comment]
This is sort of intentional but I understand the confusion. Since we haven't implemented the Tank GUI yet, I'll see about adding the sound.

**Comment by KingLemming** [comment]
Okay so turns out we were really smart and got it right the first go round. Sorry for the confusion, but this just has to be like it is.
