### ISSUE TITLE
[Thermal Dynamics] Fluiducts destroying fluids when in unloaded dimensions

### ISSUE THREAD

**Issue by Mysteryem** [CoFH/Feedback#381]
This is on a TPPI2 v0.1.1 server.
Thermal Dynamics version: ThermalDynamics-[1.7.10]1.0.0RC7-98
CoFHCore version: CoFHCore-[1.7.10]3.0.0RC7-211
CoFHLib version: CoFHLib-[1.7.10]1.0.0RC7-127
Full mod list here: https://github.com/TPPIDev/TestPackPleaseIgnore2/blob/Development/ModVersions.txt

I kept noticing that the drums in my Spectre Dimension (from Random Things) were emptying despite there being nowhere for their contents to go.

It seems that while dimensions are unloaded, fluiducts lose their contents and will continue to drain from connected tanks if they have a servo set to extract (and is currently enabled).

In the below image, both bottom and top OpenBlocks tanks (it's not a problem with these tanks, I've tested other fluid containers such as ExtraUtilities drums) started with 16B, 1B from each was drained into the fluiducts, leaving 15B in the two top tanks. The left-hand servo was disabled and the dimension was left via MystCraft linking book. Some time later (maybe an hour or two), I re-entered my spectre dimension, the server lagged for quite a bit (timing me out). Once the server had caught up, I saw that both fluiducts were now empty and the right top tank was also empty.

![Tanks with fluiducts](http://imgkk.com/i/789b.png)

Losing 1B seems to occur after waiting a couple of minutes (the fluiduct is empty upon entering the dimension, thus draining 1B). I've not noticed losing 2B or 3B, it seems to be either 1B or the entirety of the attached tank. This bug emptied a drum of just over 250B of lava in much less time than the time it seems to approximately take to lose 1B times 250.

I have been unable to reproduce this in the overworld which leads me to suspect this is an issue with other dimensions. I was able to reproduce the bug in the Nether, a random Mystcraft age and the Random Things Spectre Dimension.

It may be coincidence, but the server seems to lag pretty badly when loading one of the dimensions that was unloaded when there is more than 1B of fluid loss (A whole OpenBlocks tank [16B] being lost in the nether lagged me into the ground), possibly lagging more the greater amount of time the dimension hasn't been loaded, which might be the cause of https://github.com/TPPIDev/TestPackPleaseIgnore2/issues/256 when the dimension hasn't been loaded for most of a day.

Edit: It may not matter, but I've tested this with both Temperate Fluiducts and Opaque Hardened Fluiducts.

**Comment by KingLemming** [comment]
Hrm. I'm a bit confused here because my tests don't show that this actually happens. I tried in the Nether and overworld, it doesn't happen in either case.

Nor does the premise actually make sense. If the dimension is unloaded, the fluiducts are unloaded too. Also, if this were linked to unloading, it would happen with not just dimensions, but chunks as well. There's no special code involved for handling dimensions.

Now it's possible you have a mod which does screw with how dimension loading and unloading is done, and that *could* possibly mess it up. But as it stands, I cannot reproduce this.

**Comment by Mysteryem** [comment]
I think I might've been in spawn chunks still when testing in the overworld (that or forge's chunk 'GC' is still a mess), so I've set up a bunch of tests elsewhere. Though as I write this, my tests in the mystcraft dimension aren't acting up at all, yet the test I have in the nether is frequently losing 1B.

I could understand how the fluiducts could possibly lose their stored fluid, but I would guess that the loss of stored data for the block would involve losing the attached servo too? But there isn't much to explain why the entire tanks are sometimes emptied.

Unless if the fluid is being lost on each successive chunk/dimension reload, then perhaps the whole tanks being emptied and the seemingly corresponding lag is caused by the dimension being continuously loaded and unloaded. 250 reloads in ~7 minutes seems way too low though.

I've successfully reproduced this in single player in the nether, so I can at least take apart the mod pack until the issue is no longer a problem. Though I've still not reproduced it in the overworld even by setting up tests 10,000 blocks away from spawn in singleplayer and a similar distance on the server.

**Comment by KingLemming** [comment]
In theory, if something is forcing the dimension to load/reload constantly, it would explain the lag.

And if it's doing so in a *very* improper manner, the ducts may not be reading from NBT properly, which would cause them to be empty and then forcefully drain the tank.

That's really all I've got, but as I've said - I can't seem to make this happen. :/

**Comment by KingLemming** [comment]
@Mysteryem Can you make this happen with TE portable tanks?

**Comment by Mysteryem** [comment]
In the sense of replacing an openblocks tank with a TE portable tank, yes, the tanks are slowly depleted and sometimes (with great lag) entirely deplete. I got ``[10:16:09] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 392192ms behind, skipping 7843 tick(s)`` earlier today which coincides with the Resonant portable tank I had set up in the nether being emptied, presumably by the fluiduct extracting from it.

However, if you mean losing their contents like the fluiducts, no, the tanks keep their contents when not attached to fluiducts extracting from them.

I've still not found the mod(s) causing this.

**Comment by KingLemming** [comment]
I was wondering if they also drain like the OpenBlocks tanks. I still can't make it happen and wanted to be sure TE tanks were also affected. :/

**Comment by Mysteryem** [comment]
My best guess is that the fluiducts are *somehow* losing their contents when being loaded some of the time. Then for whatever reason they're getting rapidly unloaded and then loaded again until the tank has depleted. I don't think the reloading lag stops once the tank has been emptied seeing as 512B being entirely emptied took less time than ~256B.

The thing I don't understand is why it's just the fluiducts that are losing their contents and that they don't lose any other information, such as the servo they have connected, and on what side and what its settings are.

It may be better to move this issue to the TPPI2 git repo, seeing as with only the CoFH mods installed, I can't reproduce this issue either?

**Comment by KingLemming** [comment]
Sure, send it over that way. There's something x-mod going screwy here.

**Comment by Mysteryem** [comment]
An interesting thing I just found out is that a single fluiduct on its own loses its contents (1B), whereas, two fluiducts together (with 1B between them) only lose 500mB.

I also managed to lag the server and catch a resonant portable tank before it had fully emptied, so the proposed rapidly reloading doesn't seem to be connected to the tanks being emptied.

The portable tank went from 511,000mB to 310,500mB. I'm not sure where the 500mB came from. I know that the portable tanks seem to send their stored amount to the client shortly after the chunk has been loaded, so the connected fluiduct has begun extracting, but usually the amount extracted in this time is 200mB to 100mB, not 500mB. I unfortunately removed the tank while in creative, so can't check how much was actually stored in it.

**Comment by KingLemming** [comment]
Something else that isn't quite making sense about this is that Fluiducts don't hold 1 bucket. The amount they hold depends on the viscosity of the fluid, but it's going to range from 1.5 buckets to 15 buckets.

And you still can't make this happen in the Overworld or only with CoFH mods, right?

**Comment by Mysteryem** [comment]
All the fluiducts hold 1 bucket of any one fluid for me. The extraction/flow speed is dependent on the viscosity of the fluid. Isn't that how it's supposed to be?

**Comment by KingLemming** [comment]
Never could replicate this. Still can't.
