### ISSUE TITLE
[Feature Request] [1.12] JSON recipe system

### ISSUE THREAD

**Issue by PanSzelescik** [CoFH/Feedback#381]
Please add JSON recipe system for all machines from Thermal Expansion. This is easier way to change recipes in modpacks.

**Comment by KingLemming** [comment]
Duplicate of #318. It is not high priority, nor necessarily even possible. Not sure yet.

**Comment by Frontrider** [comment]
Don't even bother, it will probably become the preferred way in 1.13 anyways.
We supposed to get json recipes in the data packs. (whitch should be adobted by forge, I assume it would make updates easier.)
