### ISSUE TITLE
[TE] [NO] ThermalExpansion received an broken IMC from NetherOres!

### ISSUE THREAD

**Issue by Xorifelse** [CoFH/Feedback#382]
Hey there,

I receive this error in the log but the server happily continues loading but I'm not sure what this would cause in the long run. This is the part in the logs: 
http://pastebin.com/stbA0QU0

I however believe that I didn't receive this error when Thermal Dynamics was installed.
I've tried with multiple versions starting from the latest release to alpha versions from Thermal Expansion, Nether Ores and COFH Core.

Mod list:
appliedenergistics2-rv2-beta-22.jar
AsyncWorldEditInjector.jar
ATG-1.7.10-0.12.0.jar
BiblioCraft[v1.10.1][MC1.7.10].jar
BiblioWoods[BiomesOPlenty][v1.9].jar
BiblioWoods[ExtraBiomesXL][v1.4].jar
BiblioWoods[Forestry][v1.7].jar
BiblioWoods[Natura][v1.5].jar
BigReactors-0.4.2A2.jar
binnie-mods-2.0-pre8.jar
BiomesOPlenty-1.7.10-2.1.0.1164-universal.jar
buildcraft-6.4.5.jar
Carpenter's Blocks v3.3.5 - MC 1.7.10.jar
Chisel2-2.3.9.36.jar
ChiselTones-1.7.10-1.0-1.jar
CodeChickenCore-1.7.10-1.0.4.35-universal.jar
CoFHCore-[1.7.10]3.0.0RC7-227.jar
CookieCore-1.7.10-1.3.1-5.jar
CustomMobSpawner 3.3.0.zip
CustomNPCs_1.7.10c.jar
DrZharks MoCreatures Mod v6.3.1.zip
Dynmap-2.1-forge-1.7.10.jar.disabled
Enchiridion-1.7.X-1.2b.jar
Enchiridion 2-1.7.10-2.0e.jar
EnderIO-1.7.10-2.2.8.349.jar
EnderStorage-1.7.10-1.4.5.30-universal.jar
extrabiomesxl_1.7.10-3.16.0.jar
ExtraCells-1.7.10-2.2.63b94.jar
forestry_1.7.10-3.4.0.7.jar
GalacticraftCore-1.7-3.0.11.306.jar
Galacticraft-Planets-1.7-3.0.11.306.jar
ironchest-1.7.10-6.0.62.742-universal.jar
legacyjavafixer-1.0.jar
Mantle-1.7.10-0.3.2.jar
Mariculture-Deluxe-1.7.10-1.2.4.1.jar
MarketCompanion-1.7.10-2.0.1.jar
Mekanism-1.7.10-8.0.3.207.jar
MekanismGenerators-1.7.10-8.0.3.207.jar
MicdoodleCore-1.7-3.0.11.306.jar
Minechem-1.7.10-5.0.5.394.jar
MineFactoryReloaded-[1.7.10]2.8.0RC8-86.jar
MineTweaker3-1.7.10-3.0.9C.jar
MineTweakerRecipeMaker-1.7.10-1.1.0.11.jar
MobiusCore-1.2.4_1.7.10.jar
MrCrayfishFurnitureModv3.4.7(1.7.10).jar
natura-1.7.10-2.2.0.1.jar
NBTEdit_1.7.10.jar
NetherOres-[1.7.10]2.3.0RC4-10.jar
NotEnoughItems-1.7.10-1.0.4.94-universal.jar
OpenBlocks-1.7.10-1.3-snapshot-567.jar
OpenComputers-MC1.7.10-1.5.3.10-universal.jar
OpenModsLib-1.7.10-0.6-snapshot-315.jar
Opis-1.2.4a_1.7.10.jar
Pam's HarvestCraft 1.7.10g.jar
plantmegapack-4.15-1.7.10-1230.jar
ProjectRed-1.7.10-4.5.15.75-Base.jar
ProjectRed-1.7.10-4.5.15.75-Compat.jar
ProjectRed-1.7.10-4.5.15.75-Integration.jar
ProjectRed-1.7.10-4.5.15.75-Lighting.jar
ProjectRed-1.7.10-4.5.15.75-World.jar
Railcraft_1.7.10-9.5.0.0.jar
TabulaRasa-[1.7.10]1.0.1-3.jar
TConstruct-1.7.10-1.8.3b.jar
ThermalExpansion-[1.7.10]4.0.0RC7-151.jar
ThermalFoundation-[1.7.10]1.0.0RC7-62.jar
TMechworks-1.7.10-0.2.14.100.jar
TSteelworks-1.7.10-1.1.0-6.jar
ttCore-MC1.7.10-0.1.0-67.jar
vending-1.2.1b.jar
Waila-1.5.10_1.7.10.jar
worldedit-forge-mc1.7.10-6.0-beta-01.jar
Ztones-1.7.10-2.2.1.jar

**Comment by KingLemming** [comment]
So install Thermal Dynamics. ;) Easy fix.

Seriously though, the error here is one with mod sorting and a mod which is not properly registering to the OreDictionary.

Unfortunately, it's neither TE or NetherOres.
