### ISSUE TITLE
Crash 1.12 : Click on blacklist button on Servos

### ISSUE THREAD

**Issue by ExDomino** [CoFH/Feedback#382]
https://pastebin.com/m4W05c6c

**Comment by KingLemming** [comment]
Yeah, you're not on the latest version. Please update.

**Comment by ExDomino** [comment]
Last update I did : 11 july #9, 4 days ago.
Last update you did : 11 july #10, 4 days ago.

I don't know why, but 4 days ago, when I downloaded the latest version, CurseForge didn't give me the latest version but the one just before. Sorry, I thought I had the latest version. I will upgrade then.
