### ISSUE TITLE
Pulverizer is outputting 8 apatite and keeping 4

### ISSUE THREAD

**Issue by Ricket** [CoFH/Feedback#383]
I put a chest behind a (basic) pulverizer, set the output to auto eject, and then put apatite ore into the pulverizer. For each ore, 8 apatite is going into the chest and 4 is staying in the output box. Why isn't all apatite going to the chest?

ThermalExpansion-1.11.2-5.2.5.20-universal
(All the Mods 2 modpack, v0.73)

**Comment by KingLemming** [comment]
Because the Basic Pulverizer only ejects 8 and apparently a single apatite ore generates a ludicrous amount.

Upgrade your Pulverizer and please use Twitch or IRC for questions in the future.
