### ISSUE TITLE
Crash on World Load

### ISSUE THREAD

**Issue by MnMaxon** [CoFH/Feedback#384]
I had a ton of redstone conduits connected to autonomous activators, and eventually my game just started crashing.  I wasn't sure what was happening, so I suffered through the crashes and kept playing.  Eventually after crashing, my game wouldn't turn back on, so I posted here:  https://github.com/CoFH/Feedback/issues/355
You thought it was a problem with the redstone conduits, so I posted on the Enderio github, but they didn't respond.  Eventually I tried again, and it just worked.  I thought there might have been an update to the pack or something.  Then, after playing for a while, the crashes started happening again.  Last night, I replaced all of the redstone conduits with covered redstone wires (or something like that) and connected them to the activators with redstone repeaters.  Today after joining, I crashed, and I've tried to join a few times, but it hasn't worked, I've been getting the same error each time.  It looks like there's an error with a machine (probably the autonomous activator) and a redstone repeater.
Here's the error: http://pastebin.com/UWTx0BUb
I hope you can help, thanks for reading!

**Comment by MnMaxon** [comment]
I was looking through the crash files, and found they weren't all exactly the same.  The 'Block location:' section is always different.  It might be moving through all of the repeaters.

**Comment by KingLemming** [comment]
Caused by EnderIO's conduits. Vanilla redstone, as distasteful as it is, doesn't do this.

**Comment by MnMaxon** [comment]
I really do not believe this can't happen with redstone repeaters.
When using conduits, I got this in the error:

-- Block being updated --
Details:
	Source block type: ID #1246 (tile.blockConduitBundle // crazypants.enderio.conduit.BlockConduitBundle)


After removing ALL of the conduits, I got:

-- Block being updated --
Details:
	Source block type: ID #94 (tile.diode // net.minecraft.block.BlockRedstoneRepeater)


I do not see how this could be caused by a redstone conduit if there are no conduits.



-----Original Message-----

**Comment by KingLemming** [comment]
I agree, the problem is that in dev, we can't make it happen. Like I said, there's a sanity check in place in the future but we can't actually reproduce the issue.

**Comment by MnMaxon** [comment]
Alright, thanks.
