### ISSUE TITLE
[1.10.2] Crash between CoFH and CodeChicken Libs

### ISSUE THREAD

**Issue by eXtremeJR96** [CoFH/Feedback#384]
Hello,

CoFH and CodeChicken Lib plants in the creative inventory. Here are the crash report:

https://pastebin.com/hkJXdTe4

**Comment by KingLemming** [comment]
Your CCL is out of date. Please only use up to date mods before you report issues, as they have often been fixed.

**Comment by eXtremeJR96** [comment]
Sorry I had written the issue in a hurry ... But I did some testing and the mods that do the most bug is Bookshelf.

**Comment by KingLemming** [comment]
Yes. Also that. :) For whatever reason it ends up throwing nulls to CCL. The newest version of CCL deals with that gracefully, to my knowledge.
