### ISSUE TITLE
[Dynamics] Item/Fluid Transferral Through Covers

### ISSUE THREAD

**Issue by zhs2** [CoFH/Feedback#385]
I realize this is likely not so much a bug as a "feature" (more like yet another corner case with no defined behavior beyond the default),  but I still feel it prudent to report anyway, if only for a solid answer and peace of mind. As the title suggests, items and fluids can be transferred to inventories through covers - this tripped me up the first time I placed a tank where covered fluiducts were located, as I didn't expect the tank to begin filling with water. Is automatic cover anti-connection a planned feature?

**Comment by adudney** [comment]
Use a wrench on the connection between two ducts or between a duct and a block to disconnect.

**Comment by KingLemming** [comment]
No it's not a planned feature. Wrench the duct.

**Comment by zhs2** [comment]
I suppose that's just a little annoying when you can't wrench the duct through the cover, but okay. Fair enough, I will keep my wits about me in the future.

**Comment by KingLemming** [comment]
It's worth looking into but then we'll get complaints the other way. There's not a good solution here.
