### ISSUE TITLE
[1.10] Redstone Mode Bug

### ISSUE THREAD

**Issue by anders0nmat** [CoFH/Feedback#386]
Sry for bad english

If you have a setup, where some TE machines stand right next to each other and try to disable them with redstone (Machines are in low mode) they stop working. So far so good.
But if you turn off the redstone signal some of the machines keep doing nothing. A block update didn't fix the problem so probably the machines didn't update their "redstone tag". The machine takes the RS level of the adjacent blocks and not of itself.

TE v5.1.6(.8)

**Comment by KingLemming** [comment]
This is working as intended. Strong redstone signals propagate through blocks.

**Comment by KingLemming** [comment]
If by chance I haven't understood, please attach a video.

**Comment by anders0nmat** [comment]
Hello KingLemming,

thanks for your reply.
Uhm... well... thats awkward.
The bug only appears when the Redstone signal is given by XNet. With Vanilla Redstone the machines work as they should. But there is no way make it work with XNet which is interesting because XNet should do exactly what the vanilla Redstone does: Simply power the block it is connected to.

If you wish, i can make a little video where i reproduce the bug (or whatever it is)

**Comment by KingLemming** [comment]
That's on XNet then - it's not properly communicating the state change.
