### ISSUE TITLE
CTD on startup

### ISSUE THREAD

**Issue by Moobien** [CoFH/Feedback#387]
Hey guys, I have BC 7.99.6 installed and once all of the Thermal Expansion mods are installed I am getting a CTD, the same happens for Mekanism a couple of other mods that are using an out of date BC API. Is there a way around this?

**Comment by KingLemming** [comment]
We need a crashlog to know what you're doing wrong.

**Comment by Moobien** [comment]
Here is my crashlog.  

https://pastebin.com/rFN6YL0y

No crashes when CoFHCore-.11.2-4.2.6.14-universal, ThermalDynamics-1.11.2-2.2.5.12-universal, ThermalExpansion-1.11.2-5.2.5.20-universal & ThermalFoundation-1.11.2-2.2.4.15-universal are installed.
