### ISSUE TITLE
thermal expansion GUI weirdness (latest version)

### ISSUE THREAD

**Issue by Ianaver** [CoFH/Feedback#387]
some images:
top: recipe GUI (What it should look like)
middle: what it actually looks like
bottom: redstone furnace example

does this mod need advanced graphics rendering just to render a 2D image? XD

BTW this bug applies to all machines in TE that have a progress arrow/bar and only TE machines

The mods:
NEI and its core mods
CoFH Core
Thermal expansion
Thermal foundation

![2015-04-05_15 59 04](https://cloud.githubusercontent.com/assets/8153290/6999077/bc6f29d0-dbae-11e4-8d18-8bd4cad467d9.png)

![2015-04-05_16 00 35](https://cloud.githubusercontent.com/assets/8153290/6999079/c8025236-dbae-11e4-937f-6a6050c3978d.png)

![2015-04-05_16 00 04](https://cloud.githubusercontent.com/assets/8153290/6999080/cc645144-dbae-11e4-8bb2-157671e2195b.png)

**Comment by KingLemming** [comment]
This is unique to your client and is something in your end. Tech support in IRC please.

**Comment by Ianaver** [comment]
@KingLemming tried that and no one gave a good answer

**Comment by KingLemming** [comment]
Redownload and reinstall. It's an issue with the texture not showing up properly. You either have a texture pack overwriting it or your download was corrupted.
