### ISSUE TITLE
[1.12] Magmatic Dynamo

### ISSUE THREAD

**Issue by TheSnowyChickens** [CoFH/Feedback#388]
Hello (at first , my English is not so good)
I found a bug , the Magmatic consume ,for example ,Lava for producing Energie , that normal , BUT it generate Energie during all cells / cables are 100% full.
So it waste a lots of Lava to produce 0 Energie.

I hope it is fixable. :)

Thx

Forge : 2413
TE : 5.3.2.10
TF : 2.3.2.8
TD : 2.3.2.9

![magmatic](https://user-images.githubusercontent.com/29357962/28283756-0f477394-6b2f-11e7-8897-a5b37ce6e43f.png)

**Comment by KingLemming** [comment]
This is not a bug. If you want to prevent this behavior, there is an Augment to do so.

Please learn how dynamos work. -_-

**Comment by TheSnowyChickens** [comment]
Oh sry. ;(
