### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by blueteton** [CoFH/Feedback#39]
I just have thermal expansion and the other required mods for it, i'm almost positive that they are all up to date as well as forge.

Maybe i'm doing something wrong and i'm just missing something. Sorry if this causes any trouble.
Any help would be appreciated.

Crash report: http://pastebin.com/ARmeim66

**Comment by 016Nojr** [comment]
Did you update CCL? (CodeChickenLib)

**Comment by blueteton** [comment]
yes, the latest CodeChicken Lib 1.10.2-2.5.6.233-universal should be anyway.

**Comment by 016Nojr** [comment]
I commented on the wrong post. Did you change any configs?

**Comment by blueteton** [comment]
nope everything should be default

**Comment by KingLemming** [comment]
You seem to be missing a standard library. I don't honestly know what to tell you there. Forge ships that.

**Comment by blueteton** [comment]
I'll try reinstalling minecraft and forge, thanks for the help!

**Comment by blueteton** [comment]
yep got it to work, thanks again!
