### ISSUE TITLE
CTD Take 2

### ISSUE THREAD

**Issue by Moobien** [CoFH/Feedback#390]
King Lemming here is my crash log.

https://pastebin.com/rFN6YL0y

No crashes when CoFHCore-.11.2-4.2.6.14-universal, ThermalDynamics-1.11.2-2.2.5.12-universal, ThermalExpansion-1.11.2-5.2.5.20-universal & ThermalFoundation-1.11.2-2.2.4.15-universal are installed.

The reason I suspect out of date API is because Mekanism and the latest version of IC2 also crash when the latest version of buildcraft is installed. I told the BC guys about the crash and they stated the following "Mekanism crash: There was an api change that broke their integration, should be fixed on the next release, if it still crashes then you'll have to report it to them"

**Comment by KingLemming** [comment]
...I asked you to bring this to Twitch chat.

This is tech support, not an actual issue. That particular error is just Forge erroring on the version check screen because something is screwing up by either being out of date or looking for something that doesn't exist.

In any case, it isn't us.
