### ISSUE TITLE
ambiguous recipe crash with IC2

### ISSUE THREAD

**Issue by Ianaver** [CoFH/Feedback#392]
fixed by removing IC2 expirimental 

crash: http://pastebin.com/0rW6GM4X

mods are all updated to the most recent versions (CoFH mods mainly)

**Comment by KingLemming** [comment]
That's 100% IC2. I have no idea what they're doing. We don't send them recipes.

**Comment by KingLemming** [comment]
If by most recent version you mean "alpha build" then that's the problem. Please don't use that.

**Comment by Ianaver** [comment]
oh.... ok my bad I think I may have missed it if you posted something about incompatability
