### ISSUE TITLE
[1.12] Issues with some changes made to vanilla

### ISSUE THREAD

**Issue by Frontrider** [CoFH/Feedback#392]
Its not exactly a bug. Its mostly from a design choice on your part.
The recipe book groups items with the same id together, whitch means that all the machines are depicted as a single item, and can be hard to navigate it at first.
Just as a moments notice, I think it should be cared about from this version. Its not completly unuseable tough (just check on the item ids).

Also I don't know how advancements are included in forge. I would be really happy if you had some.

**Comment by covers1624** [comment]
Honestly the recipe book is a train wreck with modded.. But anyway, this seems to be an issue with the way we are generating the group for the recipe, not really sure if it is worth fixing and will probably be fixed when / if we move all recipes to json.

**Comment by Frontrider** [comment]
Well, I do see anomalys. But I would think that it might be worth fixing for a single reason: you will have it figured out when you get there.

**Comment by KingLemming** [comment]
We won't be moving all recipes to json, and vanilla *has not done so either.* The simple fact is that json is less flexible and more annoying. Also, I wouldn't count on jsons being used in the Bedrock engine, either.

Also, the vanilla crafting guide is a mess and the official stance is to use JEI, because it's about 1000x better.

**Comment by Frontrider** [comment]
About Bedrock engine.
Behaviour packs are json files describing entity behaviour from the existing patterns. In the example we have a tameable "Skeleton" in a villager skin. Taming done with a bow, fights for you after tamed (aggro towards hostiles).
Altough, it is horrible way to use it.

Its a sure thing that you can not move everything to json. But, non-tile blocks, normal items, simple tools,recipes (you can just give it a recipe type with your own custom values) etc have no reason to not to move, since they are nothing more than data. (and if you load most of the simple items from one source, than you could handle duplicate items better. At least I would think. I do not know why forge is not blocking the second/third steel from being registered, if all of them are referring to the oredict entry anyways)
So, I do see vanilla mc moving whatever possible to json. Will not invalidate forge (not even close to do so) but can provide an aid. (Last post from me on this thread)

By the way, moved to jei.
Waiting for the advancements, I'm sure they gonna have awesome text!
