### ISSUE TITLE
[1.11.2] Crash When Rendering Lockbox in JEI

### ISSUE THREAD

**Issue by Laruae** [CoFH/Feedback#393]
I am getting a crash to desktop when rendering the lockbox in JEI. Not sure what is causing it, but I am posting the issue on the issue page for each mod mentioned in the error log, which is linked below.

[Error Log Gist](https://gist.github.com/Laruae/40f6a1d75d96227b0f6c81f12a59d41f)

Thanks for your time as well as all the hard work on the mod!

**Comment by KingLemming** [comment]
This seems to be a simple case of you not having up-to-date versions. Please update all of your mods.

If that isn't it, then this is something that CodeChickenLib needs to handle.
