### ISSUE TITLE
ThermalFoundation Crash

### ISSUE THREAD

**Issue by a950216t** [CoFH/Feedback#393]
When I upgraded to ThermalFoundation [1.7.10]1.0.0RC7-71
I get crash on startup:
http://pastebin.com/bevkY4Jx
So I downgraded to ThermalFoundation [1.7.10]1.0.0RC7-70
Everything works fine.
I think the problem with DragonAPI and RotaryCraft related.
Please check and fix it.
Thank you.

**Comment by KingLemming** [comment]
You're using an alpha. Don't do that.
