### ISSUE TITLE
Crash when placing Autonomous Activator

### ISSUE THREAD

**Issue by labrat42** [CoFH/Feedback#394]
Hi

I'm playing FTB Infinity 1.3.4. (with Curse Launcher)

I tried placing an Autonomous Activator next to an impulse Itemduct and crashed. The same happened when I tried to enter the world afterwards. [Crash log](http://pastebin.com/1QE3Xh1G)

I then removed the Activator using MCEdit, it worked and I can play again.

But I tested a bit if I could somehow fix it:
- Updated Thermal Dynamics to 1.0.0RC8-105 (All CoFH mod versions should now be the newest releases), didn't fix it
- Tried to place Activator elsewhere (no Itemducts around), worked
- Placed the same Activator to the desired spot, crashed again
- Placing the Activator next to other Itemducts, worked
- Placing stone blocks at the "crash spot", then the activator, crashed again

**Comment by KingLemming** [comment]
You left out the part where you're using Redstone somewhere in there.

**Comment by labrat42** [comment]
Oh right, there was a stone block with a redsone signal from a lever.

It really only crashes if there is already a redstone signal.

**Comment by KingLemming** [comment]
Yeah, this is already fixed in dev then.

**Comment by labrat42** [comment]
Nice! Thanks.

**Comment by Slind14** [comment]
hmm, "fixed in dev". Is that already released? It happens for me with 182 which is the latest version on curseforge.

**Comment by Yselith** [comment]
Is there a way to get the commit or a compiled version of v4.0.0RC7-141 with this fix please ?

**Comment by skyboy** [comment]
You can update. That's what updates are, these come with a change of the version number. 4.0.0RC7-141 is what it is and will never change, you can only not use it and use a newer version.
