### ISSUE TITLE
crash with fluids in thermal dynamics, thermal expansion (forges update to stop incorrect fluid things)

### ISSUE THREAD

**Issue by Nick-77ab2** [CoFH/Feedback#395]
so forge 1355, i believe you already knew about it, are you already making a fix? if not then here's the crash, it happens when i try to join my server, Client crashes AND Server crashes.
Server: http://pastebin.com/40FrPUBe
idk if it ends up being the same crashes so here's both
Client: http://pastebin.com/xRQ4NKn3
weirdly the client shows other mods (either than CofH mods) too. probably couldn't fit it all on the server?

**Comment by KingLemming** [comment]
Not us. It's Biomes of Plenty.

**Comment by Nick-77ab2** [comment]
ok

**Comment by Nick-77ab2** [comment]
but if it happens with this even if biomes of plenty fixes it, I'm coming back here :)

**Comment by Nick-77ab2** [comment]
so nvm forge changed their stuff back xD
