### ISSUE TITLE
[1.12][RSA] New quiver stacks to 64

### ISSUE THREAD

**Issue by billybricker** [CoFH/Feedback#396]
Title. I imagine that it's not intended to stack at all due to its behavior but it's currently stacking to 64. Found out on accident when I forgot to disable cheat mode in JEI.

Forge: 14.21.1.2415
CoFHCore: 1.12-4.3.3.10
Redstone Arsenal: 1.12-2.3.3.9

**Comment by KingLemming** [comment]
Haha. Interesting.

**Comment by KingLemming** [comment]
Fixed. Go download the newest version please. :)
