### ISSUE TITLE
[1.12] Immersive Engineering coal coke isn't usable for steel

### ISSUE THREAD

**Issue by billybricker** [CoFH/Feedback#397]
IE's coke isn't usable to craft steel in the induction smelter. 

I'm not 100% sure if this is on your end or not (or intentional) but IE's coke is oredicted as fuelCoke, same as yours.

Forge: 14.21.1.2415
CoFHCore: 1.12-4.3.3.10
Thermal Expansion: 1.12-5.3.3.13
Immersive Engineering: 0.12-67

**Comment by KingLemming** [comment]
Yeah, this was sort of intentional as I didn't have a good idea of how common/trivial other coal cokes were.

I'll think about it.
