### ISSUE TITLE
Mod Sorting Cycle error.

### ISSUE THREAD

**Issue by Maleia** [CoFH/Feedback#397]
I keep getting this set of errors while I'm trying to update mods.

http://puu.sh/h5BTD/50cc43571d.png

No, the logs are empty of anything relevant, so I'm kinda at a loss.

For the first few, I was changing the name of some of the mods to put them at the end of the loading list, but now that's not enough.  And this is only happening with mods that I'm updating to their latest.  If this isn't an issue with CoFH, if you know where to point me, would be great.

**Comment by KingLemming** [comment]
Update literally every mod in that list. That's it. It's not actually us, but a mod that is including an outdated RF API.
