### ISSUE TITLE
[1.12] Fluxed Electrum Recipe Suggestion

### ISSUE THREAD

**Issue by EvilBastard** [CoFH/Feedback#398]
Currently to make the fluxed electrum, at least in the ATM3 pack, it requires putting electrum into a fluid transposer with 500mb of destabilized redstone.  Which is all well and good, but given that Signalum has a recipe to do it in a crafting table with a bucket or tank of redstone, why not with this as well?  It would be a simple addition of making it one pulverized gold and silver with one bucket of destabilized redstone to get two pieced of fluxed electrum blend.

**Comment by KingLemming** [comment]
Yeah, that's fair.

**Comment by MokahTGS** [comment]
Hey does making it in the Fluid Transposer work in the 1.11.2 version?  We can't seem to make it work.

**Comment by KingLemming** [comment]
It does work, yes. If it doesn't work, then you either have an out of date version or you have another mod which has corrupted the redstone fluid.
