### ISSUE TITLE
[bug/idear] microblocks not working on energyducts

### ISSUE THREAD

**Issue by Goten87** [CoFH/Feedback#399]
i was trying to place microblock covers on my Resonant fluxduct
and its not going in the same block
donno if its a bug or if its not yet implanted but i will love to see this option
so we can hide cables more and more nicely

**Comment by Goten87** [comment]
nvm i found out alrdy what i need to do xD close please got it from IRC still be nice to have the normal microblock covers to use in builds

**Comment by KingLemming** [comment]
"Normal" microblock covers?

FMP is a really overcomplicated system for what people want to do - hide ducts.
