### ISSUE TITLE
[Thermal Expansion 4.0.0B8-23] and [NetherOres 2.3.0RC4-8]

### ISSUE THREAD

**Issue by Morpheusblog** [CoFH/Feedback#4]
List of my mods: [pastebin.com/TsMWx05Z](http://pastebin.com/TsMWx05Z)
Log (Thermal Expansion): [pastebin.com/kjatdwGt](http://pastebin.com/kjatdwGt)
2nd Log (Nether Ores): [pastebin.com/Hqp3gp6J](http://pastebin.com/Hqp3gp6J)

During the launch of the modpack, I get these errors.

**Comment by bochen415** [comment]
Very annoying, especially on the server when you need to find something in the logs but they do not cause a hard crash.

**Comment by KingLemming** [comment]
Those aren't crash logs; simply info about some missing stuff. We need to fix up some of the version checking.

Don't worry though, it's not actually a problem.

**Comment by skyboy** [comment]
Neither error should occur in the next release

**Comment by bochen415** [comment]
What about Redstone Arsenal?
http://paste.ubuntu.com/9697114/
