### ISSUE TITLE
Underfluid Parser iterates through list of DungeonMobs?

### ISSUE THREAD

**Issue by UndeadZeratul** [CoFH/Feedback#40]
I found [this](https://github.com/CoFH/CoFHCore/blob/master/src/main/java/cofh/core/world/feature/UnderfluidParser.java#L45) while looking through the underfluid parser, and it seems off to me.

```
for (DungeonMob str : list) {
				//ints.add(FluidRegistry.getFluidID(str.type));
				// NOPE. this NPEs.
				Fluid fluid = FluidRegistry.getFluid(str.type);
				if (fluid != null)
					ints.add(fluid.getID());
			}
```

Is it supposed to iterate through a list of entities? for the fluid list?

**Comment by skyboy** [comment]
The class `DungeonMob` is poorly named, it's a `WeightedRandomString` implementation, and I use it as such.

**Comment by UndeadZeratul** [comment]
Huh, well that's silly.  The problem I had that drove me to look in the code in the first place, is that I can't get that template to even work.  I set the fluid name in my json to, say, "lava", and the ores I defined aren't showing up underneath any lava pool.

**Comment by skyboy** [comment]
The template may not be finding any lava in its search routine, due to how sparsely they're located in the overworld. Try it in the nether, and if it fails there under lava lakes (use `/cofh clearblocks` to search under them) I'll look over the logic and ensure it will search appropriately; also a copy of the json entry would be useful.

**Comment by UndeadZeratul** [comment]
I was actually using clearblocks to do my searching, as I'm not about to go strip mining to find some lava veins.  I've got some ores set to generate in the nether, so I'll do some testing tonight.  As for the json file, I'll attach it when I get home later.
