### ISSUE TITLE
Crashing upon launch

### ISSUE THREAD

**Issue by Arcnz** [CoFH/Feedback#40]
I installed the latest version of Thermal Expansion (2.0.0.64), Thermal Foundation (2.0.0.64), and CoFH Core (4.0.0.127) with Resonant Rise version 4.1.0.2-b, and it crashed upon launch.

Full log: [Here](http://paste.atlauncher.com/view/325ea023)

**Comment by 016Nojr** [comment]
Update CCL (CodeChickenLib)

**Comment by KingLemming** [comment]
Seriously, it's right on the front page. "If you are crashing on launch...update your mods."
