### ISSUE TITLE
[CoFH ASM@000] IllegalAccessError accessing collidingBoundingBoxes

### ISSUE THREAD

**Issue by Mitchellbrine** [CoFH/Feedback#400]
This occurs in my development environment (which is why the mod BrineTech is loaded). As I load up a world for the first time (or any time for that matter), I get a crash with the IllegalAccessError, which happens less than a second after the world begins loading.

The only mods loaded are:
- CoFHCore (I assume/believe CoFH ASM is packaged with this mod) [version 1.7.10R3.0.0RC7]
- Thermal Foundation [version 1.7.10R1.0.0RC7]
- BrineTech

Now, if this error persists because I do not have CoFHLib, close this swiftly and promptly, but if not, here's the crash log: https://pste.me/#/cP5Za

I hope this helps you to fix the issue.

\- Mitchellbrine

**Comment by KingLemming** [comment]
Issue with FML not properly converting things in a dev environment. Fixed by CCC.
