### ISSUE TITLE
[1.7.10 MineFactory Reloaded]

### ISSUE THREAD

**Issue by JustusBumm** [CoFH/Feedback#401]
I installed MineFactory Reloaded and CoFHCore for 1.7.10 but if i stard Minecraft it Crash i Have installed much other mods and these are:
ForgeMultipart-1.7.10-1.2.0.347-universal
CodeChickenLib-1.7.10-1.1.3.138-universal
ae2stuff-0.5.0.56-mc1.7.10
AgriCraft-1.7.10-1.5.0
AppleCore-mc1.7.10-1.3.9
appliedenergistics2-rv3-beta-1
Backpacks-Mod
bdlib-1.9.4.109-mc1.7.10
BigReactors-0.4.3A
BrandonsCore-1.0.0.12
buildcraft-7.1.22
buildcraft-compat-7.1.6
Carpenter's Blocks v3.3.8.1 - MC 1.7.10
Chisel-2.9.5.11
CodeChickenCore-1.7.10-Latest
CoFHCore-[1.7.10]3.1.4-329
EnderCore-1.7.10-0.2.0.39_beta
EnderIO-1.7.10-2.3.0.429_beta
ExtraCells-1.7.10-2.3.14b197
extrautilities-1.2.12
gilded-games-util
GravityGun-4.0.0-beta
HungerOverhaul-1.7.10-1.0.0.jenkins104
iChunUtil-4.2.2
InventoryTweaks-1.59-dev-152
journeymap-1.7.10-5.1.4p1-unlimited
llibrary-1.5.1-1.7.10

**Comment by KingLemming** [comment]
Outdated and no crash log.
