### ISSUE TITLE
Thermal Dynamics/Expansion - Client Crash

### ISSUE THREAD

**Issue by Tim020** [CoFH/Feedback#402]
When right clicking on the I/O part of the GUI in the Pulveriser to disable the top side as an input, the client crashed with a NPE.
The pulveriser had a pipe connected to the top of it with items flowing through when I disabled the input
Using the 1.7.10 DW20 pack version 1.2.1 (With the addition of Agricraft and Steve's Addons)
Crash log here: http://pastebin.com/tVqbEN40

**Comment by KingLemming** [comment]
This has already been fixed. The DW20 pack is out of date.
