### ISSUE TITLE
Still getting this issue, server crash only, explain how this is biomes o plenty's problem

### ISSUE THREAD

**Issue by Nick-77ab2** [CoFH/Feedback#403]
http://pastebin.com/sghBs1AJ
using the newest forge 1358 which changes the fluid stuff back to what it was, so it should have been fixed but wasnt, the client crash with biomesop has been fixed though.

**Comment by KingLemming** [comment]
BoP was doing some invalid fluid stuff. You may have another mod *also* doing it.

Use a version of Forge sub-1355.

**Comment by Nick-77ab2** [comment]
well they kind of reverted the fluid changes in 1538

**Comment by Nick-77ab2** [comment]
but ok
i can't find any evidence of any mod causing the crash that's the most annoying thing

**Comment by KingLemming** [comment]
No, they didn't. -_-
They made them binary compatible. However, there is some behavior which was never officially supported with the old system and is explicitly disallowed under the new one. It's a corner case but will be fixed in time I am sure.

**Comment by Nick-77ab2** [comment]
ah i thought they reverted them well darn thanks for telling me anyway
