### ISSUE TITLE
[Bug] - Cannot craft basic machines (1.12 fresh install)

### ISSUE THREAD

**Issue by reuhblat** [CoFH/Feedback#403]
Hello,

Fresh install of the proper Forge versions, plus everything on the CoFH download page. Was able to craft a few Thermal Expansion tools, but cannot craft e.g. a steam dynamo. The only mods are CoFH stuff and Forge.

**Comment by KingLemming** [comment]
No, sorry. They're absolutely craftable. Install JEI and look up the recipe.
