### ISSUE TITLE
[1.12] Crash with RedstoneFlux on start

### ISSUE THREAD

**Issue by YOYOK9** [CoFH/Feedback#404]
I am creating a 1.12 modpack and am now crashing with the new redstone flux mod. Any way to get around this? Since if I remove redstone flux it wants me to either remove other mods cores, or cofh core.. 

Picture of screen:
https://puu.sh/wOQqh/ab35d4ba0f.png
Crash
https://pastebin.com/8BqPDBfW

**Comment by KingLemming** [comment]
Yes, remove mininglib and whatever depends on it. They are being incredibly stupid and doing exactly what we told everyone not to do.

That's why we are force-crashing it and that's why we made the log incredibly, absolutely obvious. You probably could have self-diagnosed this. :)

**Comment by YOYOK9** [comment]
Yeah about 10minutes later i got it working. Thanks for the response though and not just yell at me like some authors would XD
