### ISSUE TITLE
[1.12] Portable tank fluidstack recipes reducing too many Mb

### ISSUE THREAD

**Issue by oitsjustjose** [CoFH/Feedback#405]
So, I'm working on further testing (vanilla TE recipes, vanilla TE instance, etc) but in a lightweight mod world with:

* Forge 14.21.1.2415
* CoFH Core 4.3.3.10
* Thermal Expansion 5.3.3.13

Crafting the Treated Wood Planks recipe seems to be draining the portable tank by 2000Mb instead of 1000Mb, and once completely empty (or rather - has less than 2000Mb) the portable tank disappears entirely. [Here's a GIF demonstration](https://puu.sh/wP5Sq/858374282f.gif) - let me know if this needs further testing on my part!

**Comment by oitsjustjose** [comment]
Tested in a controlled environment - seems to be an IE bug.

**Comment by KingLemming** [comment]
I know what's happening here. Oy vey.

**Comment by oitsjustjose** [comment]
Heh, might be able to offer Blu [some help then](https://github.com/BluSunrize/ImmersiveEngineering/issues/2344)? I haven't done too much fluid stack stuff but sounds like he isn't getting the proper "emptyContainer" stack to place in that crafting slot in his IRecipe.

**Comment by KingLemming** [comment]
Yeah, just posted. We actually sort of did what we asked each other to do and this was the result.

Honestly, this should be a consistent recipe style in Forge. I've just been lazy and haven't PR'd it.
