### ISSUE TITLE
[Thermal Dynamics] Server Crash

### ISSUE THREAD

**Issue by Soundtoxin** [CoFH/Feedback#405]
My server is on the most up to date TD (ThermalDynamics-[1.7.10]1.0.0RC8-105.jar as of this writing), but several days passed before any sort of crash resulted from it.

Server Crashlog: http://sprunge.us/HScE
Server Modlist: http://sprunge.us/XXYS
Additional info: Cauldron is being used on this server with a single plugin (prism). Some people have strict policies about ignoring crashes from any server with Cauldron, so I'm just telling you now before you start looking into this.

The version of Forge used by Cauldron on this server is 1307.

Lastly, a player known to use TD pipes in his setup told me on IRC that the crash happened as soon as he logged on. I had a crash like this one from a previous version of TD where I just removed TD and let Forge delete its blocks to stop the crashing. I'm going to avoid this unless the server crashes again.

**Comment by KingLemming** [comment]
Heck of a corner case crash. I think I've found the culprit but can't be sure since we never actually see this happen.

**Comment by Soundtoxin** [comment]
Server hasn't crashed again even with said player logging on and loading the chunks again. Hopefully this was still helpful even though I can't seem to encounter it again so far with normal usage.

**Comment by KingLemming** [comment]
k, either way it *should* be fixed in dev. It's a very strange corner occurrence.
