### ISSUE TITLE
Thermal Dynamics causing server crash in Forge 1355

### ISSUE THREAD

**Issue by Inglonias** [CoFH/Feedback#406]
I read issue #404 and I am having a similar problem. Whenever I place a Fluiduct into the world, there is an error and the game crashes. I tried to revert to Forge 1355, but that doesn't fix the crash. Indeed, that's as far back as I can go with the current versions of my mods.

Here's a pastebin link to my crash-log.
http://pastebin.com/fEvLRgt7

This is my modlist:
AppleCore
Applied Energistics 2
CodeChicken Core
CoFH Core
Ender IO
Extra Utilities
Hunger Overhaul
Inventory Tweaks
Mantle
Not Enough Items
OpenBlocks
OpenMods
Pam's HarvestCraft
Simply Jetpacks
The Spice of Life
Tinkers` Construct
Thermal Dynamics
Thermal Expansion
Thermal Foundation
Waila

**Comment by KingLemming** [comment]
Okay. Forge 1355 contains breaking changes and is not guaranteed to be backwards compatible with all mods. Downgrade for now.
