### ISSUE TITLE
[1.10.2] weird things happens when exit nether

### ISSUE THREAD

**Issue by NerdCraft** [CoFH/Feedback#407]
how it should be:
![2017-07-21_17 37 14](https://user-images.githubusercontent.com/13489837/28481525-b121f3ce-6e3b-11e7-94a5-88d486b58f41.png)

after going to nether and coming back:
![2017-07-21_17 14 20](https://user-images.githubusercontent.com/13489837/28481560-cfc34e9a-6e3b-11e7-8648-36046930bac4.png)
![2017-07-21_17 36 57](https://user-images.githubusercontent.com/13489837/28481558-cf5a20a0-6e3b-11e7-9b36-a4a753f78e49.png)
![2017-07-21_17 37 00](https://user-images.githubusercontent.com/13489837/28481559-cf68399c-6e3b-11e7-8f4a-4f82b56ab60a.png)

To fix it, I have to break pulverizer and the redstone furnace and place it again, and cheat a new energy cell, because it doesn't work anymore.

1.10.2
forge: 12.18.3.2422
cofhcore: 4.1.11.16
thermalexpansion: 5.1.9.20
thermal foundation: 2.1.5.12
thermal dynamics: 2.0.10.16

**Comment by NerdCraft** [comment]
I updated to  5.1.9.21 and it did not happen again

**Comment by KingLemming** [comment]
Yeah well the thing is that we were never the cause of this anyway. So if it does happen again, I'd recommend that you figure out who is actually at fault. :/

**Comment by NerdCraft** [comment]
happened again, after used tp from journeymap
![2017-07-26_19 52 10](https://user-images.githubusercontent.com/13489837/28647339-fc433f02-723c-11e7-8757-6c98760628ca.png)
![2017-07-26_19 52 22](https://user-images.githubusercontent.com/13489837/28647338-fc41a6f6-723c-11e7-8478-b1fac13c80ad.png)
![2017-07-26_19 53 32](https://user-images.githubusercontent.com/13489837/28647337-fc411eb6-723c-11e7-8336-2113ab3c17ae.png)
![2017-07-26_19 53 34](https://user-images.githubusercontent.com/13489837/28647340-fc441d00-723c-11e7-8cc7-e64a062c9107.png)

**Comment by KingLemming** [comment]
Again, this isn't on us. You'll have to do some extensive testing to figure out the actual cause, sorry.

Our tiles correctly load/unload. This can only happen if another mod is screwing that process up.
