### ISSUE TITLE
[Thermal Expansion] Feature request - Augment to automatically pull items from input sides

### ISSUE THREAD

**Issue by HellsMiner** [CoFH/Feedback#407]
How about the possibility for TE Machines to pull from the input slots like Ender IO Machines do? Maybe implementing this as an augment which ads this to a machine when put into it.

**Comment by KingLemming** [comment]
It's on the to-do. It's fairly trivial to do, but the way Minecraft works it's a VERY CPU intensive operation.

**Comment by HellsMiner** [comment]
ok cool :) lookin forward to using this in my world...

**Comment by KingLemming** [comment]
You're aware TD sort of allows this already in the form of Retrievers, right? :)

**Comment by HellsMiner** [comment]
Yes i know this, but i dont have enough space sometimes to bring the cables all around, you know... :D

**Comment by BoboSims** [comment]
Even the simplest retriever requires Eye of Ender to craft, making access to them very tough in peaceful mode (I'm a builder-inventor, not a mob-hunter). So that's my excuse for supporting the requested feature :)
