### ISSUE TITLE
1.11.2 Compatibility Issue with some ores of UndergroundBiomesConstruct mod

### ISSUE THREAD

**Issue by PearlCanopus** [CoFH/Feedback#408]
I have no idea where to start. Therefore I left a comment at the UBC developement side yet.

I use UBC with this setting in 1.11.2:
"# Convert ores to have Underground Biomes stone background textures
    B:UBifyOres=true"
So far all vanilla minecraft ore will encapsulated in UBC stone faces.
The ores appear in my inventory i.e. as:
- undergroundbiomes:metamorphic_stone_redstone_ore
- undergroundbiomes:sedimentary_stone_redstone_ore
- undergroundbiomes:igneous_stone_redstone_ore
When I mine their coal or redstone ore with silktouch I cannot use this in the Pulverizer to create coal/coal dust or redstone/cinnabar.
And the same for coal. These are the only ones I checked yet. This may happen to Lapislazuli ore too.

Is it possible to add compatibility of these ores to TE in any way?

**Comment by KingLemming** [comment]
Sure. Tell UBC to properly oredict their ores. Then TE will automatically have compatibility.
