### ISSUE TITLE
[ThermalExpansion] Server startup exception with Minechem

### ISSUE THREAD

**Issue by RAnders00** [CoFH/Feedback#408]
jakimfett/Minechem#716

**Comment by KingLemming** [comment]
You're using TE alphas and you're on a version of Forge post 1355. Forge 1355 contains breaking changes and you should only be using alphas if you know what you're doing.

**Comment by RAnders00** [comment]
@KingLemming I use alphas because I know what I am doing and because I want to report as many bugs and errors as possible to get a stable release for those who don't know what they are doing as soon as possible. I have no problem with broken and bugged worldsaves, if I can report all bugs and crashes to help to make great software. Ocer at the Minechem
thread I also laid out that a mod I updated now requires a Forge above 1291 and that pretty much is the only mod-combination that is broken. (So far, eventually there will be more exceptions later on)
