### ISSUE TITLE
[Suggestion] Refined Storage recipes integration

### ISSUE THREAD

**Issue by PearlCanopus** [CoFH/Feedback#409]
My example is generating silicon from pulverizing sand. Right now in 1.11.2 it does'nt work.
There might be some other recipes to be implemented I still don't know.

**Comment by covers1624** [comment]
That was an enderio added recipe if immnot mistaken..

**Comment by billybricker** [comment]
Yup, Ednder IO has silicon which can be made by crushing sand.. That was never a part of RS but both silicons were oredicted the same so you could use either one in the recipes.

**Comment by covers1624** [comment]
So this was on enderio's end then.
