### ISSUE TITLE
secondary output augments have no effect on induction smelter

### ISSUE THREAD

**Issue by Paul17041993** [CoFH/Feedback#41]
secondary output augments have no effect on induction smelter, I've had a resonant one with a level III secondary output chance only produce 5% rich slag out of all the ores I've processed ( about 60 at this time ).

**Comment by KingLemming** [comment]
You didn't check the readme, did you?

We need a modlist. Other mods can potentially hijack TE behavior, that's just how Java works.

Screenshots would help too in this case, to make sure that you're actually using the augments properly.

**Comment by Paul17041993** [comment]
https://docs.google.com/spreadsheets/d/1AI69xEfaidLb0VQgqXlLqzKpdFBsM0SUAdEjW6qxHbU/edit#gid=0
http://i.imgur.com/bTrjpsY.png

does it work when you test it?

**Comment by Paul17041993** [comment]
I don't know of the specific maths you use in the chance, but is a lvl 1 secondary boost ( +10% ) supposed to override a lvl 3 speed boost ( -30% ) ? I have a pulverizer with said setup that gets +10% extra secondary chance despite the speeds supposedly reducing it to virtually nothing.

**Comment by skyboy** [comment]
There's confirmation that all augments do correctly work in the machines you've specified, and that the overriding effect you described does not occur with properly installed augments (as described by the tooltip).

**Comment by Paul17041993** [comment]
so what could be causing this behavior then? because I don't know of any mods that could override any TE code...

**Comment by Paul17041993** [comment]
is it 'existing chance + additional chance' (what the augments actually tell you) 
or is it actually 'existing chance * (1 + additional chance)'?
