### ISSUE TITLE
Items dissappearing

### ISSUE THREAD

**Issue by jubalearly** [CoFH/Feedback#41]
When you place a chest above the pulverizer, redstone furnace, etc and upgrade machine to hardened to enable auto input items will disappear if loaded into chest while it is processing items of a different kind.  Sentence might be confusing so try and detail it.

Load input chest with cobblestone, let it empty first top left slot in chest while it is processing cobble.  Click another stack of a different item into slot 1 of chest and those items count down but never load into machine, they essentially disappear.  

Reproducible.  Hope I explained it well enough

**Comment by KingLemming** [comment]
Meant to say btw, nice catch.
