### ISSUE TITLE
Crash when placing Hardened Fluidduct.

### ISSUE THREAD

**Issue by Raizunne** [CoFH/Feedback#410]
I just placed a Hardened Fluidduct in the bottom of a ExtraUtilities Drum with lava and then I crashed.

http://pastebin.com/TT9bSf7v

Forge - 1358
Thermal Dynamics - 1.0.0RC8

If there's any need for extra information please ask.

**Comment by KingLemming** [comment]
That Forge is not supported yet. Sorry.
