### ISSUE TITLE
[1.10.2]Portable tank delete itself while crafting

### ISSUE THREAD

**Issue by mcdodge34** [CoFH/Feedback#411]
Ok, I wanted to do some crafting with the portable tank to avoid filling buckets every single time, I filled it up with creosote oil, then put it in center of crafting table and surrounded it with wooden planks, if you craft the recipe, the portable tank is deleted automatically for some weird reasons, a short video will demonstrate this one, its unlisted so don't worry about this spreading up... Oh yeah, almost forgot Thermal Expansion version is 5.1.8.19 and COFHCore is 4.1.10.15

https://youtu.be/d3jRMJ3NiiQ

**Comment by KingLemming** [comment]
This isn't on us, it's an IE recipe.

**Comment by mcdodge34** [comment]
Oh, ok, the recipe works #1 with the bucket, so I was sure it was related to the tank, forgot to mention this.

**Comment by KingLemming** [comment]
Yeah, the thing is that the recipes are implemented by each mod, so they have to interpret how to handle the tank.
