### ISSUE TITLE
One energy cell

### ISSUE THREAD

**Issue by TheRealSmolt** [CoFH/Feedback#413]
I'm sorry if this is not an issue, I did switch from 1.7.10 to 1.11.2. I saw with thermal expansion(latest version), and all the other thermals and cofh core, that there is one energy cell, a basic one. This might be a new mechanic but I'm unfamiliar with it, so I think that the others are missing, its like this with no other mods.

**Comment by KingLemming** [comment]
You're just unfamiliar with the mod. You use upgrade kits now, but there is a config option to show the other levels in the creative tab as well.

Please spend a little time in the creative tabs beyond just looking at the blocks. The tooltips are quite helpful.

**Comment by TheRealSmolt** [comment]
Sorry for the inconvience, and thanks for the response, I'm just out of style.
