### ISSUE TITLE
[CoFH Lib?] Crash near Mekanism Salination Towers

### ISSUE THREAD

**Issue by Xaethon** [CoFH/Feedback#413]
Posting this here because there is nothing in the stacktrace about Mekanism, although its definitely an intergration issue with Mekanism. This crash happens seemingly randomly when near to Mekanism Salination/Solar Evaporation Towers. The crash sometimes occurs upon them being loaded, but sometimes you can walk around them for a few minutes just fine with no issues. This will ONLY happen near Salination Towers from Mekanism and does not occur with only Mekanism installed.

http://pastebin.com/3v2YBxW0

Possibly related issue:
https://github.com/aidancbrady/Mekanism/issues/2426

This crash happens both with and without the CoFH Lib Mod installed.

Versions: 
Mekanism 8.0.1.214 and 215
CoFH Core 3.0.0RC7-211 
CoFH Lib 1.0.0RC7-127 (happens both with and without CoFH Lib)
Thermal Foundation 1.0.0RC7-62
Thermal Expansion 4.0.0RC7-141
Thermal Dynamics 1.0.0RC8-105
Redstone Arsenal 1.1.0RC7-65
MFR 2.8.0RC8-88

Complete modslist can be seen here http://www.atlauncher.com/pack/Genesis

**Comment by KingLemming** [comment]
Did you read the other issue? This has already been reported, proven invalid, and dismissed. Not us, sorry.
