### ISSUE TITLE
Crash on 1.12 with steves carts fluid manager

### ISSUE THREAD

**Issue by Watchful1** [CoFH/Feedback#414]
Got the following crash when trying to put water into a steves carts fluid manager with a hardened fluiduct.

https://pastebin.com/YpqLPPW3

Thermal dynamics version 2.3.2. I haven't had a chance to try 2.3.3, but it doesn't look like the changes there were related.

**Comment by KingLemming** [comment]
No, but you should probably take that up with Steve's Carts. Ducts don't just randomly try to insert fluid into things - they only try that on things which have SAID that they can do it.

So basically, it's looking a lot like the cart is a liar.

**Comment by Watchful1** [comment]
Thanks, will do.
