### ISSUE TITLE
[1.10.2]Magmatic dynamos don't accept lava or pyrotheum

### ISSUE THREAD

**Issue by fluid-uu-matter** [CoFH/Feedback#415]
When I updated TE to 5.1.9.20, lava dynamo doesn't accpet lavva pr blazing pyrotheum as fuel.
JEI says the magmatic dynamo can use the fuels of compression dynamo and generate no power.

![Uploading 2017-07-23_19.10.49.png…]()

![2017-07-23_19 10 43](https://user-images.githubusercontent.com/17115547/28499020-a7c856e8-6fde-11e7-9d7f-f3bde180f916.png)

**Comment by KingLemming** [comment]
Did you actually try putting lava or pyrotheum in? Because it actually works - I tested. This is just a bug with the JEI handler.

**Comment by fluid-uu-matter** [comment]
I tried to put them in by buckets or by Portable Tanks(already set to output mode) but none works

**Comment by fluid-uu-matter** [comment]
also, in the older versions, there is no this bug.

**Comment by KingLemming** [comment]
I absolutely cannot replicate this.

**Comment by KingLemming** [comment]
Yes, I am doing that. It does not happen.

**Comment by KingLemming** [comment]
Also first of all, at the time of you opening the issue, you didn't have the latest versions.

Secondly, I have uploaded a 5.1.9.23 which fixes the JEI issue. However, I was never able to reproduce the magmatic dynamo issue and as such am calling it invalid. Sorry. Make sure that ALL of your mods are up to date. Seriously, all of them. Redownload fresh ones.

**Comment by fluid-uu-matter** [comment]
Oh, I tried to add lava into a dynamo which has 50mB of pyrotheum left. So that's my fault.
