### ISSUE TITLE
Random Thermal foundation server startup crash

### ISSUE THREAD

**Issue by Nick-77ab2** [CoFH/Feedback#417]
didn't happen when i updated but now i'm getting it
http://pastebin.com/g224n2VU

**Comment by KingLemming** [comment]
It's Fastcraft, sorry. We aren't in that stack trace at all, actually. :/

**Comment by Nick-77ab2** [comment]
it wasnt fastcraft or this mod, it was chromaticraft

**Comment by Nick-77ab2** [comment]
we're still trying to figure out what the heck is happening over at reika's forum
