### ISSUE TITLE
Energy Cells : Conflict with EnderIO

### ISSUE THREAD

**Issue by metrosis0** [CoFH/Feedback#418]
A user on a server I have access to help support with config's and errors, there seems to be one that I cant fix.

The server and modpack is for Minecraft Version 1.10.2

There seems to be an issue with energy cells and enderIO.

Server Crash Report : [Here](https://pastebin.com/PZzMZVcY)

**Comment by KingLemming** [comment]
That crashlog is 110% Mekanism. Neither TE or EnderIO is in it.
