### ISSUE TITLE
fluid crash with newest version.

### ISSUE THREAD

**Issue by Dragunkod** [CoFH/Feedback#419]
just updated my cofh teams mods to newest version and now i get a new crash when nei is open on a page that contains the fluid. sorry i don't know the fluid but here is the crash report.
http://pastebin.com/qfZ2pxmy

**Comment by KingLemming** [comment]
Either all of your mods need to be modified to support Forge 1355+, or you need to downgrade to 1352.

We support 1355+ but do not require it. What's happening here is that a mod is doing something wrong and TE is finding out in an unfortunate manner.

**Comment by Dragunkod** [comment]
thank you very much.

**Comment by bigbantha** [comment]
Also got the same crash with ExtraCells
