### ISSUE TITLE
[Thermal Expansion]Convertion to creative

### ISSUE THREAD

**Issue by nister6000** [CoFH/Feedback#42]
Any energy cell and capicator convert to creative when repaired by tf2 dispenser.

Forge 1240
CoFHCore-[1.7.10]3.0.0B9-96
CoFHLib-[1.7.10]1.0.0B9-64
ThermalExpansion-[1.7.10]4.0.0B8-23
ThermalFoundation-[1.7.10]1.0.0RC1-27

**Comment by skyboy** [comment]
Those items are not only not damageable but also not repairable. This is a bug with whatever TF2 is.

**Comment by nister6000** [comment]
Ah i forgot about config option.

If someone have this problem just change this in config:
   
S:ignoredItems <
	ThermalExpansion:capacitor
	ThermalExpansion:Cell
     >

**Comment by KingLemming** [comment]
You should report it to TF2 though - by default, it shouldn't attempt to repair things explicitly tagged as not repairable.

**Comment by nister6000** [comment]
Will do.

**Comment by Cronosus** [comment]
similar problem when used Unique artifacts mod
repaired items lowering subID and become creative (example battery).
autor of mod say its problem in TE, items are not set as unrepairable
