### ISSUE TITLE
Combining TF tools in crafting table results in corrupt item

### ISSUE THREAD

**Issue by Pihrra** [CoFH/Feedback#42]
While trying to combine two Invar Pickaxes in a crafting table I noticed this : 
![2017-03-05_23 21 31](https://cloud.githubusercontent.com/assets/215052/23592039/1df63b98-01fb-11e7-8748-ebf50c22713a.png)
Repairing in an anvil works as intended.
(Latest CoFH mods and CCL)

**Comment by KingLemming** [comment]
Yeah unfortunately it seems I got a bit too clever for Minecraft. I'm going to have to rewrite all of the tools and armor.
