### ISSUE TITLE
Thermal expansion issue!?!?

### ISSUE THREAD

**Issue by NicosaurusRex99** [CoFH/Feedback#420]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CTMCorePlugin (CTM-MC1.11.2-0.2.0.8.jar)
  SFRCore (SolarFluxReborn_1.11.2-2.21r.jar)
  HammerCoreCore (HammerCore_1.11.2-1.8.9.jar)
  LoadingPlugin (RandomThings-MC1.11.2-4.0.jar)
  CoreMod (Aroma1997Core-1.11.2-1.2.0.0.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.62.jar)
  IC2core (industrialcraft-2-2.7.74-ex111.jar)
  TransformerLoader (OpenComputers-MC1.11.2-1.7.0.40.jar)
  Ar_CorePlugin (additionalresources-1.9.4-0.2.0.28+47cd0bd_signed.jar)
  CoFH Loading Plugin (CoFHCore-1.11.2-4.2.7.15-universal.jar)
  CCLCorePlugin (CodeChickenLib-1.11.2-3.0.0.284-universal.jar)
  RebornCoreASM (RebornCore-1.11.2-2.16.1.115-universal.jar)
Contact their authors BEFORE contacting forge

// Oops.

Time: 7/24/17 5:16 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Thermal Expansion (thermalexpansion)
Caused by: java.lang.IllegalArgumentException: Equal objects must have equal hashcodes. During rehashing, Trove discovered that the following two objects claim to be equal (as in java.lang.Object.equals()) but their hashCodes (or those calculated by your TObjectHashingStrategy) are not equal.This violates the general contract of java.lang.Object.hashCode().  See bullet point two in that method's documentation. object #1 =class cofh.thermalexpansion.util.managers.machine.CompactorManager$ComparableItemStackCompactor id= 1620163371 hashCode= 353763328 toString= cofh.thermalexpansion.util.managers.machine.CompactorManager$ComparableItemStackCompactor@1620163371{m:0, i:com.mcmoddev.lib.item.ItemMMDIngot@1744175562, v:5398}; object #2 =class cofh.thermalexpansion.util.managers.machine.CompactorManager$ComparableItemStackCompactor id= 430784198 hashCode= 679 toString= cofh.thermalexpansion.util.managers.machine.CompactorManager$ComparableItemStackCompactor@430784198{m:0, i:com.mcmoddev.lib.item.ItemMMDIngot@1744175562, v:5398}

	at gnu.trove.impl.hash.TObjectHash.buildObjectContractViolation(TObjectHash.java:464)
	at gnu.trove.impl.hash.TObjectHash.throwObjectContractViolation(TObjectHash.java:448)
	at gnu.trove.map.hash.THashMap.rehash(THashMap.java:403)
	at gnu.trove.impl.hash.THash.postInsertHook(THash.java:388)
	at gnu.trove.map.hash.THashMap.doPut(THashMap.java:178)
	at gnu.trove.map.hash.THashMap.put(THashMap.java:145)
	at cofh.thermalexpansion.util.managers.machine.CompactorManager.addRecipe(CompactorManager.java:344)
	at cofh.thermalexpansion.util.managers.machine.CompactorManager.addDefaultStorageRecipe(CompactorManager.java:386)
	at cofh.thermalexpansion.util.managers.machine.CompactorManager.loadRecipes(CompactorManager.java:238)
	at cofh.thermalexpansion.util.managers.machine.CompactorManager.initialize(CompactorManager.java:192)
	at cofh.thermalexpansion.ThermalExpansion.managerInitialize(ThermalExpansion.java:171)
	at cofh.thermalexpansion.ThermalExpansion.postInit(ThermalExpansion.java:111)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:647)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:253)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:231)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:833)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:357)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:521)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:352)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1611690632 bytes (1537 MB) / 3193962496 bytes (3046 MB) up to 4772593664 bytes (4551 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx5120m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.38 Powered by Forge 13.20.1.2421 135 mods loaded, 135 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJ	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCHIJ	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJ	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.1.2421.jar) 
	UCHIJ	forge{13.20.1.2421} [Minecraft Forge] (forge-1.11.2-13.20.1.2421.jar) 
	UCHIJ	additionalresources{0.1.1} [Additional Resources] (additionalresources-1.9.4-0.2.0.28+47cd0bd_signed.jar) 
	UCHIJ	aroma1997core{${version}} [Aroma1997Core] (Aroma1997Core-1.11.2-1.2.0.0.jar) 
	UCHIJ	opencomputers|core{1.7.0.40} [OpenComputers (Core)] (minecraft.jar) 
	UCHIJ	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJ	ccl-entityhook{1.0} [ccl-entityhook] (CodeChickenLib-1.11.2-3.0.0.284-universal.jar) 
	UCHIJ	achievementbooks{v1.0-MC1.11.2} [Achievement Books] (achievementbooks-v1.0-MC1.11.2.jar) 
	UCHIJ	actuallyadditions{1.11.2-r110} [Actually Additions] (ActuallyAdditions-1.11.2-r110.jar) 
	UCHIJ	aether_legacy{v1.0.1} [Aether Legacy] (aether_legacy-1.11.2-1.0.1.jar) 
	UCHIJ	aquaculture{1.5.1} [Aquaculture] (Aquaculture-1.11.2-1.5.1.2.jar) 
	UCHIJ	aroma1997corehelper{1.0} [Aroma1997Core|Helper] (Aroma1997Core-1.11.2-1.2.0.0.jar) 
	UCHIJ	aromabackup{1.0} [AromaBackup] (AromaBackup-1.11-2.1.0.0.jar) 
	UCHIJ	aromabackuprecovery{1.0} [AromaBackupRecovery] (AromaBackup-1.11-2.1.0.0.jar) 
	UCHIJ	audiodeath{0.6.3_1.9-1311200} [Audio Death] (audiodeath-1.9-0.6.3.47+1311200.jar) 
	UCHIJ	psi{r1.1-47} [Psi] (Psi-r1.1-47.jar) 
	UCHIJ	autoreglib{1.1-4} [AutoRegLib] (AutoRegLib-1.1-4.jar) 
	UCHIJ	jei{4.5.0.291} [Just Enough Items] (jei_1.11.2-4.5.0.291.jar) 
	UCHIJ	base{2.0.0} [B.A.S.E] (base-1.11.2-2.0.0.jar) 
	UCHIJ	veinminer{0.36.0} [Vein Miner] (VeinMiner-1.11-0.36.0.621+8499b73.jar) 
	UCHIJ	basemetals{2.5.0-beta1} [Base Metals] (BaseMetals-1.11.2-2.5.0-beta1.45.jar) 
	UCHIJ	baubles{1.4.5} [Baubles] (Baubles-1.11-1.4.5.jar) 
	UCHIJ	betterbuilderswands{0.11.1} [Better Builder's Wands] (BetterBuildersWands-1.11-0.11.1.239+9162f74.jar) 
	UCHIJ	bettermagnets{1.02} [Better Magnets] (bettermagnets-mc1.11.2-v1.02.jar) 
	UCHIJ	betterthanbunnies{1.11-1.1.0} [BetterThanBunnies] (BetterThanBunnies-1.11-1.1.0.jar) 
	UCHIJ	betterthanllamas{1.11.2-1.0.0} [BetterThanLlamas] (BetterThanLlamas-1.11.2-1.0.0.jar) 
	UCHIJ	guideapi{1.11.2-2.1.1-52} [Guide-API] (Guide-API-1.11.2-2.1.1-52.jar) 
	UCHIJ	bloodmagic{1.11-2.1.11-80} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.11-2.1.11-80.jar) 
	UCHIJ	botania{r1.9-345} [Botania] (Botania r1.9-345.jar) 
	UCHIJ	buildcraftlib{7.99.6} [BuildCraft Lib] (buildcraft-7.99.6.jar) 
	UCHIJ	buildcraftcore{7.99.6} [BuildCraft] (buildcraft-7.99.6.jar) 
	UCHIJ	buildcraftbuilders{7.99.6} [BC Builders] (buildcraft-7.99.6.jar) 
	UCHIJ	buildcraftenergy{7.99.6} [BC Energy] (buildcraft-7.99.6.jar) 
	UCHIJ	buildcraftfactory{7.99.6} [BC Factory] (buildcraft-7.99.6.jar) 
	UCHIJ	buildcraftrobotics{7.99.6} [BC Robotics] (buildcraft-7.99.6.jar) 
	UCHIJ	buildcraftsilicon{7.99.6} [BC Silicon] (buildcraft-7.99.6.jar) 
	UCHIJ	buildcrafttransport{7.99.6} [BC Transport] (buildcraft-7.99.6.jar) 
	UCHIJ	cfm{4.1.2} [MrCrayfish's Furniture Mod] (cfm-4.1.2-mc1.11.2.jar) 
	UCHIJ	chameleon{1.11.2-3.1.0} [Chameleon] (Chameleon-1.11.2-3.1.0.jar) 
	UCHIJ	chesttransporter{2.7.11} [Chest Transporter] (ChestTransporter-1.11.2-2.7.11.jar) 
	UCHIJ	chisel{MC1.11.2-0.0.13.22} [Chisel] (Chisel-MC1.11.2-0.0.13.22.jar) 
	UCHIJ	clumps{2.0.0} [Clumps] (Clumps-2.0.0.jar) 
	UCHIJ	codechickenlib{3.0.0.284} [CodeChicken Lib] (CodeChickenLib-1.11.2-3.0.0.284-universal.jar) 
	UCHIJ	cofhcore{4.2.7} [CoFH Core] (CoFHCore-1.11.2-4.2.7.15-universal.jar) 
	UCHIJ	cookingforblockheads{5.3.21} [Cooking for Blockheads] (CookingForBlockheads_1.11.2-5.3.21.jar) 
	UCHIJ	crafttweakerjei{1.0.2} [CraftTweaker JEI Support] (CraftTweaker-1.11.2-3.0.26.jar) 
	UCHIJ	crafttweaker{3.0.26} [Crafttweaker] (CraftTweaker-1.11.2-3.0.26.jar) 
	UCHIJ	ctgui{1.0.0} [CT-GUI] (CraftTweaker-1.11.2-3.0.26.jar) 
	UCHIJ	ctm{MC1.11.2-0.2.0.8} [CTM] (CTM-MC1.11.2-0.2.0.8.jar) 
	UCHIJ	custommainmenu{2.0.5} [Custom Main Menu] (CustomMainMenu-MC1.11.2-2.0.5.jar) 
	UCHIJ	eleccore{1.7.425} [ElecCore] (ElecCore-1.11-1.7.425.jar) 
	UCHIJ	deepresonance{1.4.8} [DeepResonance] (deepresonance-1.1x-1.4.8.jar) 
	UCHIJ	dldungeonsjdg{1.9.3} [Doomlike Dungeons] (DoomlikeDungeons-1.9.3-MC1.11.2.jar) 
	UCHIJ	elevatorid{1.3.2} [Elevator Mod] (ElevatorMod-1.11.2-1.3.2.jar) 
	UCHIJ	enderstorage{1.0} [EnderStorage] (EnderStorage-1.11.2-2.3.1.116-universal.jar) 
	UCHIJ	endmetals{1.2.0-beta1} [End Metals] (EndMetals-1.11.2-1.2.0-beta1.10.jar) 
	UCHIJ	valkyrielib{1.11.2-0.11.0b} [Valkyrie Lib] (valkyrielib-1.11.2-0.11.0c.jar) 
	UCHIJ	environmentaltech{1.11.2-0.11.0d} [Environmental Tech] (environmentaltech-1.11.2-0.11.0d.jar) 
	UCHIJ	ic2{2.7.74-ex111} [IndustrialCraft 2] (industrialcraft-2-2.7.74-ex111.jar) 
	UCHIJ	mekanism{9.3.3} [Mekanism] (Mekanism-1.11.2-9.3.3.311-fix.jar) 
	UCHIJ	thermalfoundation{2.2.5} [Thermal Foundation] (ThermalFoundation-1.11.2-2.2.5.16-universal.jar) 
	UCHIE	thermalexpansion{5.2.6} [Thermal Expansion] (ThermalExpansion-1.11.2-5.2.6.22-universal.jar) 
	UCHIJ	exchangers{1.11.2-1.3} [Exchangers] (Exchangers-1.11.2-1.3.jar) 
	UCHIJ	extrautils2{1.0} [extrautils2] (extrautils2-1.11.2-1.5.1.jar) 
	UCHIJ	zerocore{1.11.2-0.1.0.6} [Zero CORE] (zerocore-1.11.2-0.1.0.6.jar) 
	UCHIJ	bigreactors{1.11.2-0.4.5.30} [Extreme Reactors] (ExtremeReactors-1.11.2-0.4.5.30.jar) 
	UCHIJ	sonarcore{4.0.0} [SonarCore] (SonarCore-1.11.2-4.0.0.jar) 
	UCHIJ	fluxnetworks{2.0.0} [FluxNetworks] (FluxNetworks-1.11.2-2.0.0.jar) 
	UCHIJ	foamfix{@VERSION@} [FoamFix] (foamfix-0.7.1-law.jar) 
	UCHIJ	ftbl{0.0.0} [FTBLib] (FTBLib-1.1x-3.6.5.jar) 
	UCHIJ	gogskybox{1.0-1} [Garden of Glass Skybox] (GoGSkybox 1.0-1.jar) 
	UCHIJ	gobackpacks{1.1.1} [Good Old Backpacks] (GoodOldBackpacks-1.1.1.jar) 
	UCHIJ	gravestone{1.0.10} [Gravestone] (GraveStone-1.11.2-Graves-1.0.10.jar) 
	UCHIJ	hammercore{1.8.9} [Hammer Core] (HammerCore_1.11.2-1.8.9.jar) 
	UCHIJ	mantle{1.11.2-1.2.0.26} [Mantle] (Mantle-1.11.2-1.2.0.26.jar) 
	UCHIJ	tconstruct{1.11.2-2.7.1.34} [Tinkers' Construct] (TConstruct-1.11.2-2.7.1.34.jar) 
	UCHIJ	theoneprobe{1.4.14} [The One Probe] (theoneprobe-1.1x-1.4.14.jar) 
	UCHIJ	immersiveengineering{0.11-63} [Immersive Engineering] (ImmersiveEngineering-0.11-63.jar) 
	UCHIJ	immersivepetroleum{1.0.7} [Immersive Petroleum] (immersivepetroleum-1.11.2-1.0.7.jar) 
	UCHIJ	mtlib{@VERSION@} [MTLib] (MTLib-2.0.3.jar) 
	UCHIJ	initialinventory{2.0.2} [InitialInventory] (InitialInventory-2.0.2.jar) 
	UCHIJ	inventorypets{1.4.9.7} [Inventory Pets] (inventorypets-1.11.2-1.4.9.7.jar) 
	UCHIJ	inventorytweaks{1.62+release.90.40cf8fc} [Inventory Tweaks] (InventoryTweaks-1.62.jar) 
	UCHIJ	ironchest{1.11.2-7.0.25.815} [Iron Chest] (ironchest-1.11.2-7.0.25.815.jar) 
	UCHIJ	jehc{1.3.0} [Just Enough HarvestCraft] (jehc-1.11.2-1.3.0.jar) 
	UCHIJ	jeiintegration{1.1.0.10} [JEI Integration] (jeiintegration_1.11.2-1.1.0.10.jar) 
	UCHIJ	journeymap{1.11.2-5.4.7} [JourneyMap] (journeymap-1.11.2-5.4.7.jar) 
	UCHIJ	jeresources{0.6.6.12} [Just Enough Resources] (JustEnoughResources-1.11.2-0.6.6.12.jar) 
	UCHIJ	mekanismgenerators{9.3.3} [MekanismGenerators] (MekanismGenerators-1.11.2-9.3.3.311.jar) 
	UCHIJ	mekanismtools{9.3.3} [MekanismTools] (MekanismTools-1.11.2-9.3.3.311.jar) 
	UCHIJ	mob_grinding_utils{0.2.0} [mob_grinding_utils] (MobGrindingUtils-0.2.0.jar) 
	UCHIJ	modnametooltip{1.7.1} [Mod Name Tooltip] (modnametooltip_1.11-1.7.1.jar) 
	UCHIJ	modtweaker{3.0.1} [Mod Tweaker] (modtweaker-3.0.1.jar) 
	UCHIJ	morpheus{1.11.2-3.2.14} [Morpheus] (Morpheus-1.11.2-3.2.14.jar) 
	UCHIJ	mousetweaks{2.8} [Mouse Tweaks] (MouseTweaks-2.8-mc1.11.2.jar) 
	UCHIJ	mysticalagriculture{1.5.8} [Mystical Agriculture] (mysticalagriculture[1.11.2]-1.5.8.jar) 
	UCHIJ	natura{1.11.2-4.2.0.24} [Natura] (natura-1.11.2-4.2.0.24.jar) 
	UCHIJ	neat{1.4-13} [Neat] (Neat 1.4-13.jar) 
	UCHIJ	nethermetals{1.2.0-beta1} [Nether Metals] (NetherMetals-1.11.2-1.2.0-beta1.21.jar) 
	UCHIJ	notenoughwands{1.5.5} [Not Enough Wands] (notenoughwands-1.1x-1.5.5.jar) 
	UCHIJ	omlib{3.0.0-119} [OMLib] (omlib-1.11.2-3.0.0-119.jar) 
	UCHIJ	opencomputers{1.7.0.40} [OpenComputers] (OpenComputers-MC1.11.2-1.7.0.40.jar) 
	UCHIJ	openglider{@VERSION@} [Open Glider] (OpenGlider-1.11.2-1.0.0.jar) 
	UCHIJ	openmodularturrets{3.0.0-196} [Open Modular Turrets] (openmodularturrets-1.10.2-3.0.0-196.jar) 
	UCHIJ	orespawn{3.0.0} [OreSpawn] (OreSpawn-1.11.2-3.0.0.36.jar) 
	UCHIJ	harvestcraft{1.11.2g} [Pam's HarvestCraft] (Pam's HarvestCraft 1.11.2h.jar) 
	UCHIJ	projecte{1.11.2-PE1.0.0B} [ProjectE] (ProjectE-1.11.2-PE1.0.0B.jar) 
	UCHIJ	reborncore{2.16.1.115} [Reborn Core] (RebornCore-1.11.2-2.16.1.115-universal.jar) 
	UCHIJ	quantumstorage{4.2.3} [QuantumStorage] (QuantumStorage-1.11.2-4.2.3.jar) 
	UCHIJ	quickleafdecay{1.2.3} [Quick Leaf Decay] (QuickLeafDecay-MC1.11.2-1.2.3.jar) 
	UCHIJ	randomthings{4.0} [Random Things] (RandomThings-MC1.11.2-4.0.jar) 
	UCHIJ	rangedpumps{0.4} [Ranged Pumps] (rangedpumps-0.4.jar) 
	UCHIJ	reborncore-mcmultipart{2.16.1.115} [reborncore-MCMultiPart] (RebornCore-1.11.2-2.16.1.115-universal.jar) 
	UCHIJ	refinedstorage{1.4.20} [Refined Storage] (refinedstorage-1.4.20.jar) 
	UCHIJ	rftools{6.12} [RFTools] (rftools-1.1x-6.12.jar) 
	UCHIJ	rftoolsdim{5.04} [RFTools Dimensions] (rftoolsdim-1.1x-5.04.jar) 
	UCHIJ	roguelike{1.6.6} [Roguelike Dungeons] (RoguelikeDungeons-1.11.2-1.6.6.jar) 
	UCHIJ	ruins{16.5} [Ruins Mod] (Ruins-1.11.2.jar) 
	UCHIJ	snad{1.11.2-1.7.03.26a} [Snad] (Snad-1.11.2-1.7.03.26a.jar) 
	UCHIJ	solarfluxreborn{2.21r} [Solar Flux Reborn] (SolarFluxReborn_1.11.2-2.21r.jar) 
	UCHIJ	spartanshields{1.3} [Spartan Shields] (SpartanShields-1.11.2-1.3a.jar) 
	UCHIJ	stg{1.11.2-1.1.1} [SwingThroughGrass] (stg-1.11.2-1.1.1.jar) 
	UCHIJ	storagedrawers{1.11.2-4.2.10} [Storage Drawers] (StorageDrawers-1.11.2-4.2.10.jar) 
	UCHIJ	thermaldynamics{2.2.6} [Thermal Dynamics] (ThermalDynamics-1.11.2-2.2.6.13-universal.jar) 
	UCHIJ	tinkertoolleveling{1.11.2-1.0.1.DEV.641b08f} [Tinkers Tool Leveling] (TinkerToolLeveling-1.11.2-1.0.1.jar) 
	UCHIJ	tp{2.2.3} [Tiny Progressions] (tinyprogressions-1.11.2-2.2.3.jar) 
	UCHIJ	topaddons{1.11.2-0.15.0} [TOP Addons] (topaddons-1.11.2-0.15.0.jar) 
	UCHIJ	treechopper{1.1.2} [Tree Chopper] (TreeChopper-1.11.2-1.1.2.jar) 
	UCHIJ	veinminermodsupport{0.36.0} [Mod Support] (VeinMiner-1.11-0.36.0.621+8499b73.jar) 
	UCHIJ	weirdinggadget{1.0} [The Weirding Gadget] (weirdinggadget-1.11.2-1.0.1-universal.jar) 
	UCHIJ	witherskelefix{2.2.2} [Wither Skeleton Tweaks] (Wither Skeleton Tweaks-1.11.2-2.2.2.jar) 
	UCHIJ	xnet{1.3.2} [XNet] (xnet-1.3.2.jar) 
	UCHIJ	yabba{1.11.2-0.5.1} [YABBA] (YABBA-1.11.2-0.5.1.jar) 
	Loaded coremods (and transformers): 
CTMCorePlugin (CTM-MC1.11.2-0.2.0.8.jar)
  team.chisel.ctm.client.asm.CTMTransformer
SFRCore (SolarFluxReborn_1.11.2-2.21r.jar)
  com.pengu.solarfluxreborn.core.SFRSerializedTransformer
HammerCoreCore (HammerCore_1.11.2-1.8.9.jar)
  com.mrdimka.hammercore.asm.HammerCoreTransformer
LoadingPlugin (RandomThings-MC1.11.2-4.0.jar)
  lumien.randomthings.asm.ClassTransformer
CoreMod (Aroma1997Core-1.11.2-1.2.0.0.jar)
  
Inventory Tweaks Coremod (InventoryTweaks-1.62.jar)
  invtweaks.forge.asm.ContainerTransformer
IC2core (industrialcraft-2-2.7.74-ex111.jar)
  
TransformerLoader (OpenComputers-MC1.11.2-1.7.0.40.jar)
  li.cil.oc.common.asm.ClassTransformer
Ar_CorePlugin (additionalresources-1.9.4-0.2.0.28+47cd0bd_signed.jar)
  
CoFH Loading Plugin (CoFHCore-1.11.2-4.2.7.15-universal.jar)
  cofh.asm.CoFHClassTransformer
  cofh.asm.repack.codechicken.lib.asm.ClassHierarchyManager
CCLCorePlugin (CodeChickenLib-1.11.2-3.0.0.284-universal.jar)
  codechicken.lib.asm.ClassHierarchyManager
  codechicken.lib.asm.CCL_ASMTransformer
RebornCoreASM (RebornCore-1.11.2-2.16.1.115-universal.jar)
  reborncore.mixin.transformer.MixinTransformer
	GL info: ' Vendor: 'Intel' Version: '3.3.0 - Build 8.15.10.2712' Renderer: 'Intel(R) HD Graphics 4000'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- theoneprobeIntegration (Enabled/Not Forced)

	Pulsar/natura loaded Pulses: 
		- NaturaCommons (Enabled/Forced)
		- NaturaOverworld (Enabled/Not Forced)
		- NaturaNether (Enabled/Not Forced)
		- NaturaDecorative (Enabled/Not Forced)
		- NaturaTools (Enabled/Not Forced)
		- NaturaEntities (Enabled/Not Forced)
		- NaturaOredict (Enabled/Forced)
		- NaturaWorld (Enabled/Not Forced)

	codechickenlib Invalid Fingerprint Reports: - No invalid fingerprints.: 
	enderstorage Invalid Fingerprint Reports: - No invalid fingerprints.: 
	RebornCore: 
		Plugin Engine: 0
		RebornCore Version: 2.16.1.115
		Mixin Status: 1
		Runtime Debofucsation 1
		RenderEngine: 0

**Comment by NicosaurusRex99** [comment]
Disabling the Compactor did not fix it

**Comment by KingLemming** [comment]
This is the fault of Basic Metals or whatever mcmoddev is. I'm pretty sure that's the mod.

They're oredicting something in postinit which is bad stupid wrong and they shouldn't be doing that.

**Comment by NicosaurusRex99** [comment]
@MinecraftModDevelopmentMods i think this is you
