### ISSUE TITLE
Lava Pump Suggestion.

### ISSUE THREAD

**Issue by Badcholo** [CoFH/Feedback#421]
1). Lava/water/other Pump
2). Lava Cells like ic2 that can be used in the liquid transposter, reusable
3). A Redstone Arsenal Hose tool that can suck up fluids and place them in your inventory Tanks.
4). A Fluid Tank Chestplate backpack of some sort that can be filled by just using a bucket or hose.

fluid transportations seems to be low tech. I use buckets and a tank to gather lava at the moment.
I know how to use the crucible connected to magmatic engines and also the dynamo upgrades for fuel efficiency, but i like to gather lava manually. It's so much faster too. a 512bucket tank can be filled in minutes. plus i like the danger. gets me out of the house too. It would just be nice to have a nice way to farm lava from the nether. I don't have buildcraft nor like it.

**Comment by KingLemming** [comment]
Duplicate of #277

It'll happen.
