### ISSUE TITLE
machine GUI rendering bug?

### ISSUE THREAD

**Issue by SniperHauss89** [CoFH/Feedback#422]
Hello I've been using the release build of CoFH mods and noticed a rendering bug in the machine GUI's having to do with the progress arrow. I'm not quite sure why it would be like this in the release version seems like an odd bug to occur given all the development... anyway here are some pictures: 
![2015-04-13_00 20 47](https://cloud.githubusercontent.com/assets/9005067/7109770/04174f28-e173-11e4-826b-931c22caf096.png)
![2015-04-13_00 20 50](https://cloud.githubusercontent.com/assets/9005067/7109777/33bd371a-e173-11e4-830d-afe0920e66ec.png)

**Comment by KingLemming** [comment]
You have a texture pack which needs to update.

Sorry.

**Comment by KingLemming** [comment]
Reopening this so others see it - if you have any GUI issues, your texture pack is out of date. We tweeted that they're gonna need updates.

These changes made our textures compatible with starch-based platforms.

**Comment by SniperHauss89** [comment]
O ok Thank You that hadn't occurred to me... just like another problem I had awhile ago was related to texture packs. :)
