### ISSUE TITLE
[Question] How does COFH world "retrogen": true actually work?

### ISSUE THREAD

**Issue by cragrim** [CoFH/Feedback#423]
I have been pondering this for a while and searched but can't seem to find any actual documentation on it aside from speculation.

I use custom oregen by configuring **config\cofh\world\thermalfoundation_ores.json** to populate ore in high mountain biomes like Alps from Biomes o Plenty among other things and its working great! Editing the json format is fairly easy and I've set up profiles for custom oregen. Then I use the mod [world stripper](https://mods.curse.com/mc-mods/minecraft/250603-world-stripper) to double check ore distribution which is really handy. Running the command **/cofh reloadworldgen** in game is really useful to find out if any formatting is wrong.

Lately I've been experimenting with the boolean **retrogen** flag but I can't figure out how to initiate or activate retrogen. 

- How does it actually work? 
- Is it working in the current version?
- Is there some official documentation?

I read something about having to visit new chunks in order to initiate retrogen of already visited chunks, is there any truth to this or is it just a rumour?

I appreciate any help or advice you can offer :)
Best Regards and thanks!

For example I've configured the following, how do I repopulate already visited chunks?
```
		"draconic_more": {
			"distribution": "uniform",
			"generator": {
				"block": "draconicevolution:draconium_ore",
				"material": "minecraft:stone",
				"cluster-size": 8
			},
			"cluster-count": 1,
			"min-height": 0,
			"max-height": 16,
			"retrogen": true,
			"biome": "all",
			"dimension": {
				"restriction": "blacklist",
				"value": [
					-1,
					1
				]
			}
		},
```

**Comment by KingLemming** [comment]
So, couple things here. Questions are for Twitch chat, not the issue tracker.

Secondly, it works by setting the retrogen option in config.cfg to "true". It then retrogens all new ore distributions which it had not previously (by name).

That's it. Enable the flag and don't reuse ore names. It clearly logs all of this to the server log. There's nothing confusing or mysterious about this.

**Comment by cragrim** [comment]
Is changing retrogen to true in **thermalfoundation_ores.json** for each ore type enough or do you mean that there is an additional setting?

I can not find **config.cfg** in the cofh folder?
Searching through all the configs the only place where you can set retrogen is in **thermalfoundation_ores.json** 

If it is only **thermalfoundation_ores.json** then retrogen is not working for me and I will have to investigate further and return once I've done some debugging.

Sorry if I'm being slow and not understanding. 
Thank you for taking the time to respond, I really appreciate it.

**Comment by KingLemming** [comment]
Okay so config.cfg is for CoFHWorld in 1.12+.

For earlier versions, the config for retrogen is part of CoFHCore instead. So check those config files. The individual retrogen options on the ores just set whether or not they should be counted as retrogennable.

**Comment by cragrim** [comment]
I've found it now. It's called **RetroactiveGeneration** located in **\config\cofh\core\common.cfg**
It's just me being dumb searching for "retrogen" giving me trouble finding it.

**This needs to be set to true:**
```
    # If TRUE, world generation handled by CoFH Core will be retroactively applied to existing chunks. [default: false]
    B:RetroactiveGeneration=true
```

Thank you for all your help
Best Regards

**Comment by cragrim** [comment]
I've done further testing on a server and I still can't get retrogen to work with the following json edits for draconic ore even though I have enabled it also in **\config\cofh\core\common.cfg**. I set cluster count to silly high 32 for testing purposes and using the mod world stripper I can quickly check if ore has appeared. 

Oregen works perfectly fine for new fresh unvisited chunks. I did /tp 20000 120 20000 

It's understandable if you won't continue further developing 1.11.2 but there appears to be something wrong with current retrogen on the following versions. I also tried changing cluster size to 6 and 7 without any results.

No rush from my part, but I wanted to let you know that something's acting funny :)
Keep up the great work, the cofh and Thermal Expansion mods are some of my favorite must have mods!
Best Regards :D

**Using the most recent versions for 1.11.2**
CoFHCore-1.11.2-4.2.7.15-universal.jar
RedstoneArsenal-1.11.2-2.2.6.10-universal.jar
ThermalDynamics-1.11.2-2.2.6.13-universal.jar
ThermalExpansion-1.11.2-5.2.6.22-universal.jar
ThermalFoundation-1.11.2-2.2.5.16-universal.jar

**\config\cofh\world\thermalfoundation_ores.json**
```
		"draconic_more": {
			"distribution": "uniform",
			"generator": {
				"block": "draconicevolution:draconium_ore",
				"material": "minecraft:stone",
				"cluster-size": 8
			},
			"cluster-count": 32,
			"min-height": 0,
			"max-height": 16,
			"retrogen": true,
			"biome": "all",
			"dimension": {
				"restriction": "blacklist",
				"value": [
					-1,
					1
				]
			}
		},

		"draconic_high": {
			"distribution": "uniform",
			"generator": {
				"block": "draconicevolution:draconium_ore",
				"material": "minecraft:stone",
				"cluster-size": 8
			},
			"cluster-count": 32,
			"min-height": 140,
			"max-height": 250,
			"retrogen": true,
			"biome": "all",
			"dimension": {
				"restriction": "blacklist",
				"value": [
					-1,
					1
				]
			}
		},
```

**Comment by cragrim** [comment]
I think I got where things went wrong now, my server crashed or was interrupted before retrogenning was able to complete.

**Retrogen runs only ONCE on server startup** for the specified ores when set to true in the configs then it remembers if it has already run and will not retrogen that entry again.

IF the server crashes on startup or is unable to complete retrogen it will still remember that it has run before hence if any chunks were missed before the completion of retrogen they will be skipped and not run again even if you restart the server.

In case retrogen is unable to complete for whatever reason one needs to **rename** the oregen identifier in the json file. Changing "**draconic_more**" to "**draconic_more_two**" and restarting the server enabled it to run again. This process may accidentally introduce double retrogen so I would recommend making backups of the world before retrogenning and checking the logs to make sure it has completed.

**The log file should contain retrogenning entries if successful as follows:**
```
[12:56:00] [Server thread/DEBUG] [cofhcore/]: RetroGening [-3, 34].
[12:56:00] [Server thread/DEBUG] [cofhcore/]: RetroGening [-2, 34].
[12:56:00] [Server thread/DEBUG] [cofhcore/]: RetroGening [36, 0].
[12:56:00] [Server thread/DEBUG] [cofhcore/]: RetroGening [37, 1].
[12:56:01] [Server thread/DEBUG] [cofhcore/]: RetroGening [-21, 33].
[12:56:01] [Server thread/DEBUG] [cofhcore/]: Queuing RetroGen for features for the chunk at [-21, 34].
[12:56:01] [Server thread/DEBUG] [cofhcore/]: RetroGening [-18, 33].
[12:56:01] [Server thread/DEBUG] [cofhcore/]: Queuing RetroGen for features for the chunk at [-17, 34].
[12:56:01] [Server thread/DEBUG] [cofhcore/]: Queuing RetroGen for features for the chunk at [-17, 33].
[12:56:01] [Server thread/DEBUG] [cofhcore/]: RetroGening [-19, 34].
[12:56:01] [Server thread/DEBUG] [cofhcore/]: RetroGening [-18, 34].
[12:56:01] [Server thread/DEBUG] [cofhcore/]: RetroGening [-20, 34].
[12:56:01] [Server thread/DEBUG] [cofhcore/]: RetroGening [7, 33].
[12:56:01] [Server thread/INFO] [cofhcore/]: RetroGening [-21, 34].
[12:56:01] [Server thread/INFO] [cofhcore/]: RetroGening [-17, 34].
```

This would probably be self explanatory to most people but for some reason I assumed that retrogenning used the world seed to always retrogen ore at the same location and only when revisiting old chunks. This assumption is wrong!

Sorry for wasting your time, hopefully this clarifies or helps someone else in the future. 
Best Regards

**Comment by Mremenar** [comment]
I apologize if this is a dumb question, but can CoFH retrogen be used for other resources in other mods, like the Ant Nests in Orespawn?
I found a mod that would do this and meet our needs: https://minecraft.curseforge.com/projects/easy-retrogen
but alas it is for 1.12.2, and we need 1.7.10.  I know very little about programming so any help that you can provide is greatly appreciated.
We are trying to populate a pre-made map with Orespawn, Ruins, and Better Dungeons resources.  My six year old is very hopeful for this.
Thanks in advance,
M
