### ISSUE TITLE
[Suggestion] More quark support

### ISSUE THREAD

**Issue by Skillotic0703** [CoFH/Feedback#424]
- [ ] Add the ability to create quark's stones in the igneous extruder (marble/limestone)

- [x] Add some pulverizer recipes:
    - Soul Sandstone = 2 Soul sand + 25% chance for Sulfur
    - Allow quark's sandstone/sandstone stairs versions to replace vanilla ones.
    - Quilted Wool = 4 String
    - Blaze Lantern = 21 Blaze Powder + 50 % chance for 4 sulfur. (8000 RF)
   - Colored Flower Pot = 3 Brick + 5 % chance for corresponding dye
- [ ] Add recipes to other machines:
    - Add the ability to use bark blocks/walls instead of wood in all recipes
    - Add support for bark stairs
    - Add the ability to use carved wood instead of wood planks in all recipes
    - Support for colored beds/item frames

**Comment by KingLemming** [comment]
Satchels can't be used as a dropoff location as they are not a tile entity.

I don't really want to add searching. NEI does this and handles it more elegantly with no work on my part.

Some of the recipes seem alright.

The TF tools thing I think is entirely on Quark's end.

**Comment by KingLemming** [comment]
Marble and Limestone are metamorphic and sedimentary, respectively, so I won't be adding that to the Extruder, sorry.

Pulverizer and Sawmill recipes are added.

Given the nature of 1.12+ and json recipes, I won't be adding a bunch of alternates though, sorry. Vazkii can pretty trivially handle this with the OreDict though. ;)
