### ISSUE TITLE
[MFR] invincible mobs reloaded

### ISSUE THREAD

**Issue by Frontrider** [CoFH/Feedback#425]
Now they always have max hp, not always 0.

**Comment by KingLemming** [comment]
This is not a helpful report. What are you even talking about?

**Comment by Frontrider** [comment]
Okey, sorry.

The fix whitch shows up about the update, says that the bug where grinder made mobs invincible has been fixed. Before the fix they had 0 hp at all time. Now they have maximum hp at all time.

**Comment by Frontrider** [comment]
Some other testing shows different results, the bug might be somewhere else,.

**Comment by KingLemming** [comment]
Okay then.
