### ISSUE TITLE
[Redstone Arsenal] Featherfall on Flux boots not working

### ISSUE THREAD

**Issue by xenoflot** [CoFH/Feedback#426]
A chap reported this problem in IRC tonight and I was able to reproduce it.

My testing... Flux Boots, fully charged (currently wearing the full set, in case that's relevant). Applied the Feather Fall III enchantment then jumped off a ledge about 20 blocks up. I took 6 hearts damage which I feel is excessive if FF3 was doing its job.

He's running Sky Factory 2 (latest per the AT Launcher). I'm playing FTB Infinity 1.3.4. Both of us have RA1.7.10(1.1.0RC7-65).

**Comment by KingLemming** [comment]
What is Feather Fall? If it's not a vanilla enchantment, we can't provide any guarantee of compatibility.

**Comment by adudney** [comment]
Yes, Feather Falling is a vanilla enchant: http://minecraft.gamepedia.com/Feather_Falling#Feather_Falling

**Comment by KingLemming** [comment]
Just tested. Exactly a 20 block height. Here are the results:

No boots - 7.5 hearts.
Boots, no enchant - 7.5 hearts*
Boots, Feather Falling 4 - 3 hearts

It works.

*Falling damage is marked as unblockable. Any armor mod that is bypassing this is either doing so intentionally, and that's fine, OR they're just being sloppy coders. I may add a 25% reduction on Unblockable damage though. I kinda like that idea.

**Comment by xenoflot** [comment]
Re-tested myself in the way you did. I agree. Sorry for wasting your time.

**Comment by KingLemming** [comment]
Not a waste at all. I learned a thing. :)
