### ISSUE TITLE
[Suggestion] Dense fluid ducts

### ISSUE THREAD

**Issue by xenoflot** [CoFH/Feedback#427]
I'm currently producing an excessive amount of liquid XP and mob essence. I'd like to void any excess after my tanks are full. I was able to craft a dense item duct but using a temperate fluid duct in the recipe had no result.

TDyn 1.0.0RC7-98

**Comment by KingLemming** [comment]
Due to how Fluiducts work, this just isn't feasible, sorry. There are ways that you can do it though.
