### ISSUE TITLE
Crash with 1.11.2 Equal objects must have equal hashcodes

### ISSUE THREAD

**Issue by cursinorock** [CoFH/Feedback#428]
[crash-2017-07-27_02.21.57-client.txt](https://github.com/CoFH/Feedback/files/1178899/crash-2017-07-27_02.21.57-client.txt)
Crash on custom modpack.
last version of forge *.2425

**Comment by KingLemming** [comment]
Not us. Whatever cyclopscore is, it is oredicting items in PostInit, which is bad stupid dumb wrong.

**Comment by Tahakk** [comment]
https://github.com/CyclopsMC/CyclopsCore/issues/58

**Comment by rubensworks** [comment]
CyclopsCore actually oredicts during PreInit, as we have done for as long as I can remember, so I would be surprised if that would have something to do with it.
Are there any other potential causes for this?

I'll try to do some debugging later today.

**Comment by KingLemming** [comment]
This is absolutely caused by an oredict in PostInit. It may not be your mod, but it IS one of your Items. It's absolutely possible that another mod is doing cross-dressing though that has been rare in my experience.

**Comment by KingLemming** [comment]
Cross-oredicting. Damn autocorrect.

**Comment by rubensworks** [comment]
I'll have a look at it later today.

@cursinorock In the meantime, could you see if you can reproduce it with just Thermal Expansion and EvilCraft (+ the lib mods) installed?

**Comment by cursinorock** [comment]
I did and it did not happen again, it must be another mod, sorry for the inconvenience
:T
