### ISSUE TITLE
[CoFHCore] java.lang.IllegalAccessError in dev environment

### ISSUE THREAD

**Issue by Shukaro** [CoFH/Feedback#428]
Specifically https://github.com/Shukaro/Artifice
Forge version is 1291, CoFHCore version is 262-dev, IDE is idea

http://pastebin.com/Jmds65qc

**Comment by KingLemming** [comment]
FML bug. Add code chicken core to your Dev environment to fix it

**Comment by Shukaro** [comment]
That fixed it, thanks!
