### ISSUE TITLE
Flat bedrock generation in void world

### ISSUE THREAD

**Issue by Lorexe** [CoFH/Feedback#43]
Hello,
I just test ThermalExpansion and I found that a generation of flat bedrock occurs in my Aether world.
Screen : http://i.imgur.com/G9IrhcJ.png
The problem comes from cofh core [checking for air](https://github.com/CoFH/CoFHCore/blob/master/src/main/java/cofh/core/world/WorldHandler.java#L311) at bedrock layer to know if is it a void world.

Config:
B:FlatBedrockEnable=true

Versions : 
CoFHCore-1.10.2-4.0.0.127

**Comment by KingLemming** [comment]
Okay. Do you have a better solution...?

Is that NOT air?

**Comment by Lorexe** [comment]
I understand the problem :/ 
I don't have a proper solution but maybe add a blacklist for dimension when we don't want a bedrock gen can be a good idea.

**Comment by KingLemming** [comment]
Okay, so I'm marking this fixed. Checking in multiple places for NOT BEDROCK or its associates. Hopefully that will be enough.

Given that this has been a thing for all of 1.7.10 and this is the only time there's ever been an issue reported, I bet it will work.
