### ISSUE TITLE
[MineFactory Reloaded 2.8.0RC6-5] RedNet Cable bugged with forced connection

### ISSUE THREAD

**Issue by Jerdo** [CoFH/Feedback#43]
How I found the bug: Attach a RedNet cable to a daylight detector and on the other end to a solid block (i.e. stone) via forced connection mode. Place a redstone lamp on top of that solid block. 

Expected behaviour: Lamp shines when there is a signal (i.e. the daylight detector detects light). Lamp does not shine when there is no signal (i.e. daylight detector does not detect light).

Behaviour: The Lamp will only shine if placed while there is an active redstone signal. If the signal is 0 and then back to a value larger than 0, nothing happens. If the solid block attached to the cable or the cable itself is replaced, the lamp starts glowing again. A multimeter or historian will show the correct signal, it is just not transfered via the forced connection side. See the following screenshot for further explanation.
![2015-01-22_17 44 38](https://cloud.githubusercontent.com/assets/7532004/5859988/b70c1522-a25e-11e4-9ef3-3293662431a4.png)

My system and specs:
Win 8.1 x64 Pro
Geforce GTX 770
Minecraft 1.7.10
Forge 10.13.2.1286
CoFHCore 3.0.0B9-40
ThermalFoundation 1.0.0RC1-13
Thermal Expansion 4.0.0B8-23
RedstoneArsenal 1.1.0RC1-19

**Comment by skyboy** [comment]
Forced connection mode only emits a weak redstone signal, and will provide power only to the block it is connected to. You need strong connection mode to power nearby blocks.

**Comment by Jerdo** [comment]
Ah makes sense. Well then the bug is, that forced connection mode works once as strong connection mode. Because the lamp is turning on once when switching to forced connection mode.

**Comment by skyboy** [comment]
It will no longer light up incorrectly when switching to forced mode.
