### ISSUE TITLE
Cache Storage. 

### ISSUE THREAD

**Issue by CrossVas** [CoFH/Feedback#430]
Cache don't show the real number of stored items/blocks when this is connected with Storage Bus from AE2. Terminal show only 64 items/blocks. 

![image](https://user-images.githubusercontent.com/25727222/28683445-437740e0-7309-11e7-9bfc-dca88aedb879.png)

![image](https://user-images.githubusercontent.com/25727222/28683453-519b56e8-7309-11e7-87c4-e89c6d076535.png)

With Drawers from SD work fine.  

![image](https://user-images.githubusercontent.com/25727222/28683464-583430ce-7309-11e7-8fe5-0ed4bd510a03.png)

![image](https://user-images.githubusercontent.com/25727222/28683471-6023b50c-7309-11e7-83e2-8ecd506664b7.png)

CoFHCore-1.10.2-4.1.11.16-universal
ThermalExpansion-1.10.2-5.1.9.23-universal

**Comment by KingLemming** [comment]
So AE2 is probably looking for some kind of interface here. I'm not sure how to handle this, tbh.

It's not a bug, strictly speaking.

**Comment by thiakil** [comment]
yeah it's looking for `net.minecraftforge.items.IItemHandler`

I don't care how you implement it internally, but there are no stack size restrictions on ItemHandlers. You could implement a single slot handler that exposes the real contents - that's what I did for Mekanism bins.
