### ISSUE TITLE
[Thermal Expansion] [Bug]

### ISSUE THREAD

**Issue by whitestarx0312** [CoFH/Feedback#430]
I am using the latest recommended versions of all CoFh mods and Forge 1291.

The bug isn't anything huge, but the Translocation Plate does not teleport Endermen. It will teleport any 2 block high, 1 block wide mob. I understand spiders being impossible but Endermen seem to just stand on the plate and do nothing.

**Comment by skyboy** [comment]
I don't actually know why that would be the case, for either spiders or endermen, but I like the concept.

**Comment by KingLemming** [comment]
I actually do as well. And I believe I know why it's the case.

**Comment by whitestarx0312** [comment]
Hmm yeah I was thinking it was on-purpose.
