### ISSUE TITLE
[1.12] Duplicating Energy Cells

### ISSUE THREAD

**Issue by tgstyle** [CoFH/Feedback#431]
When breaking a basic energy cell with a diamond pickaxe (enchantments or not). You get two, one with the state it was when broken and one that is as if it were newly constructed. I will try some further testing.

TE - 5.3.3.15
Forge - 2426
SpongeForge - 2481

**Comment by KingLemming** [comment]
This is absolutely not caused by us. I can tell you that right now.

**Comment by tgstyle** [comment]
It looks to be caused by MultiMine
