### ISSUE TITLE
Crash with Thermal Expansion and EnderIO on Chunk Unload.

### ISSUE THREAD

**Issue by alexanderpas** [CoFH/Feedback#431]
java.lang.NullPointerException: Exception while updating neighbours
        at cofh.thermalexpansion.block.device.TileActivator.onRedstoneUpdate(TileActivator.java:152)

Pastebin of full Crash Report: http://pastebin.com/C5FJSnfX

Mod Versions:

ThermalExpansion: [1.7.10]4.0.1-182
EnderIO: 1.7.10-2.2.8.367

**Comment by skyboy** [comment]
This is a bug with EnderIO. It's loading an unloaded chunk in its onChunkUnload callback.
