### ISSUE TITLE
Obscure boiler dynamo shenanigans...?

### ISSUE THREAD

**Issue by Paul17041993** [CoFH/Feedback#432]
I've noticed some odd behaviour while messing with the boiler augment, for one thing the GUI gets messed up a bit when you add the augment (I'd suggest just moving the steam tab to be below the augments).

The more critical weirdness though comes with resonant tier compression dynamos with the augment, are the efficiency augments supposed to boost the steam/RF production so drastically? (tree oil gets 1kRF per mB standard, 1.8k via boiler>turbine dynamos, but add 3 eff augments to the boiler and you get 2.7kRF per mB...) is there supposed to be a limit to how many eff augments can be used or are these next points just weird bugs?;
- right-clicking augments into dynamos only inserts 2 eff augs at a time, you have to use the GUI for the 3rd one
- when I copy-pasted a compression dynamo with the boiler augment in creative, upgraded it from reinforced to refined, then added eff augments the boiler augment got removed somehow, not sure what happened there...

**Comment by KingLemming** [comment]
I can't replicate either of those bullet points. The tab thing is known and is addressed in dev, however.

**Comment by Paul17041993** [comment]
I realise now that the augments will insert 2 at a time regardless, unless only one is allowed, seems weirdly specific... shouldn't it just insert the max amount possible?

I'm also going to assume the +300RF/mB per eff. aug. is intentional for compression boiler dynamos, and it makes sense with the materials anyway, but I notice we have a funny loop with lead being used a lot at the start, mostly disappears and then comes back in the end-game tier (3 lead per resonant upgrade as well as the eff. aug.'s)...

**Comment by KingLemming** [comment]
I also don't get the two at a time thing. Seriously, are you sure you have an actual version of TE?

**Comment by Paul17041993** [comment]
weird, I have the latest 1.12 version so I'm going to have to assume that's a forge bug...
which version of forge you currently testing with?

**Comment by KingLemming** [comment]
2415 for 1.12.

**Comment by Paul17041993** [comment]
ok well I'm currently running 2424 and I definitely don't have fastcraft or optifine, so I'm going to have to do some extra testing between versions...

**Comment by KingLemming** [comment]
Figured it out. Forge did infact change something on how servers and clients interpret a right click, and that was backported as well.

Also, there have been some pending in dev changes to fuel efficiency for a couple weeks now - a small decrease to how effective fuels are for the compression/magmatic dynamos when they operate as boilers. So I'm calling this resolved. :)
