### ISSUE TITLE
[Suggestion] No-update/"keep running" augment?

### ISSUE THREAD

**Issue by Paul17041993** [CoFH/Feedback#433]
Basically when you set up a production line of machines, or set up fuel processing for dynamos, very often you'll have at least one machine that runs at a different speed to the rest of the setup, often in such a way that they'll change their rendering face every few seconds or so. Currently it's very difficult to tune some of these machines to run close enough to the speed needed so you basically just have to put up with the occasional chunk update (that can cause large stutters with large setups and/or low IPC CPUs).

Basically I'm suggesting an augment that disables face updating for the machine, it'll always render as 'doing an operation' unless the machine is disabled via redstone. You could also make this work with dynamos too (though ideally you'd want them to always have fuel anyway).

Alternatively, or additionally, you could make an augment that makes the machine dynamically adjust its RF usage based on how full its main output buffer is (both for liquids and items). I like the idea of this one too as it can show how much energy it's using on average (give or take some), though there'd probably still be cases where the machine would still trigger updates despite only using 1RF/t.

**Comment by Paul17041993** [comment]
I will note though that rendering the faces of the machines via tile entity rendering would remove the chunk updates entirely, but it would then replace it with GL over-draw when you build a lot of machines (which is already pretty horrendous with the mods that do this, if MC's own chunk rendering was bad enough at long view distances...). Strongly suggest against using TE rendering, unless you want to make your own chunk render layer system that batches all the faces in the chunk to one vertex buffer...

**Comment by KingLemming** [comment]
Machines already have a fairly long update timer on when they change their render.

Frankly if your system is falling outside of that 10 second window already, you have abjectly failed at optimization.

**Comment by Paul17041993** [comment]
Is the 10 second timer supposed to start after the processing has finished? I'm seeing machines that run for more than 10 seconds, stop, update their face after about 1 second, then start and update again after something like 5 seconds...

**Comment by Paul17041993** [comment]
In that regard we kinda need a way to downgrade machines, if a machine was already upgraded to resonant but you need it to use 70RF/t instead of 60, you're basically screwed...

**Comment by KingLemming** [comment]
Gave this some thought and the delay thing has been in place for years and has never been an issue. There's also not a need to downgrade machines, so I won't be addressing this, sorry.

**Comment by Paul17041993** [comment]
I still don't see what the '10 second' timer's supposed to go off, I see machines update their face 3-5 seconds after...

Also, is there a particular reason why fluiducts fire chunk updates as well even when they're either opaque or carry a non-glowing liquid?
