### ISSUE TITLE
Java crash, thermal dynamics showing up in the log

### ISSUE THREAD

**Issue by Frontrider** [CoFH/Feedback#434]
http://pastebin.com/Ajtz4dnj

I cant really put this log anywhere, but thermal dynamics shows up.
Edit:

I think i walked on some ducts.
func_149743_a

**Comment by skyboy** [comment]
You need to report this crash here: http://bugreport.sun.com/bugreport/crash.jsp

As you can see, nothing from minecraft or us even shows up:
```
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
v  ~StubRoutines::call_stub
V  [jvm.dll+0x1cef93]
```
