### ISSUE TITLE
Weird flux network issues with plated ducts

### ISSUE THREAD

**Issue by Paul17041993** [CoFH/Feedback#437]
While messing with dynamo setups I've noticed a strange and very specific connection issue with plated ducts, I'll show an image for clarity;

<img width="1132" alt="screenshot_53" src="https://user-images.githubusercontent.com/3912867/28749556-9fd15d06-750e-11e7-8bdb-3c85935929e2.png">

now, if you break and replace the signalum duct right next to the plated fluid duct, or any of the other plated ducts, they will update their network connection correctly, no problem there.
However, if you break any of the other sinalum flux ducts down the line and replace, the plated ducts then become disconnected from the signalum ducts completely, adding to that simply breaking the connecting ducts and replacing, or adding more ducts over the top will not re-connect them at all.
What _does_ reconnect them however, is placing more plated ducts over the top, making another connection, then breaking the plated duct between the two, forcing it to re-calculate the network.

another image to clarify;
<img width="669" alt="screenshot_54" src="https://user-images.githubusercontent.com/3912867/28749587-83b3cd74-750f-11e7-8366-34c04d0a89ff.png">

You place 1-2, then break 1 again and the ducts are now connected back to normal, you can then remove 2. This can only be done using plated ducts, all the standard fluxducts have no effect, which is what makes it extra weird, like they're actually still connected but not transferring flux between their buffers...?

I will note as well that the plated itemduct is missing the RF/t in the tooltip, the fluid and impulse ducts have it though.

**Comment by KingLemming** [comment]
This is literally another thing that I can't make happen.

**Comment by Paul17041993** [comment]
Ok I seemed to have worked out 2 more things with it;
- 1st is that it seems to only occur when you have a lot of high power dynamos, 8*720RF/t seems to do it reliably + 2*480's attached to a plated duct
- 2nd is that if a dangling plated duct (marked A on the picture below) is present it'll reduce the effect and let the dynamos drain slowly, which means that there's a bandwidth limit, but if you do the trick in the OP the bandwidth limit is removed and they can drain as fast as the plated ducts allow

<img width="586" alt="screenshot_55" src="https://user-images.githubusercontent.com/3912867/28756986-36b17aae-75bd-11e7-818a-dbc15c71fb37.png">

**Comment by Paul17041993** [comment]
Still something weird going on with the plated ducts, I can hammer their faces off and back on and they'll work properly, but reload the world and they'll seem to be logically disconnected from the adjacent cell and fluxducts, so now I'm trying with them isolated from the ducts...

<img width="845" alt="screenshot_2" src="https://user-images.githubusercontent.com/3912867/29739862-ea937166-8a8b-11e7-976d-bbfcab5ad55b.png">

the gap where the cursor is is where I've hammer-isolated for now

**Comment by KingLemming** [comment]
Just adding another comment here to again reiterate that I can reproduce literally none of this, even using your setups. I'll give this another week or so, but the only thing I can verify at all here is that the tooltip was missing for Signalum Plated Itemducts.

**Comment by KingLemming** [comment]
Never could make this happen.
