### ISSUE TITLE
[Thermal Expansion] Suggestion - make advanced augments require previous augments.

### ISSUE THREAD

**Issue by nigraforce** [CoFH/Feedback#438]
To my mind, using previous levels of augments to craft better augments(say, require the use of reinforced speed upgrade to craft resonant speed upgrade) would be cool.
You see, all other Thermal Expansion-based mods, like Redstone Arsenal or Thermal Expansion itself, consume previous tiered items in order to craft more advanced items. You don't get to keep your reinforced jetpack if you want to craft a resonant jetpack. Because of this, the augments stand out quite a lot. 
In order to balance the machines, you can keep the number of augment slots in a machine being 4. It will almost not make a difference. Right now, you can sacrifice all default augments in pulverizer and put all speed and all efficiency upgrades in it. With updated augment system, you would be able to dump 1 of the 3 default augments and max out both the speed an efficiency of a machine.
Also, there is little purpose to keep high tier augments and low tier augments separated, because if, say, 1 highest dynamo efficiency augment enters the game, it will be useless without other, lower-tiered augments, because they are required for the best augment to function.

**Comment by KingLemming** [comment]
Actually no. Thermal Dynamics does not operate in this way and actually Machines do not either.

Scaling the slots is part of flexibility. You're only looking at it from the perspective of higher tier = better so we can drop the slot, but if we did so and kept it at 4 slots, we'd be giving people 8 effective slots.

Sorry, not happening.
