### ISSUE TITLE
creating blaze powder in fluid transposer 

### ISSUE THREAD

**Issue by ForestJones** [CoFH/Feedback#439]
I am working with thermal expansion, dynamics, etc. for minecraft 1.11.2 and everything is working great except when I try to create blaze powder in the fluid transposer. It goes through the motions (the destablized redstone flows to/through the glowstone powder) but then the blaze powder does not appear where it should.

**Comment by KingLemming** [comment]
Can't replicate this at all and it makes no sense. Please provide a video and screenshots of your setup. I can almost guarantee what is happening is that the powder is being auto-ejected to an adjacent inventory.

**Comment by ForestJones** [comment]
KingLemming, you are a genious and I am an idiot. It was being ejected into an adjacent inventory - a chest that was hidden behind the transposer that I forgot I put there. Thank you!

**Comment by covers1624** [comment]
Glad you fixed your issue :D
