### ISSUE TITLE
[1.10.20] Machine Set To False Still Showing In JEI.

### ISSUE THREAD

**Issue by TheBritishBrotherhood** [CoFH/Feedback#44]
I have set the Smelter to false in the config as shown in the image, But the recipe still shows for items using the induction smelter.

I did the same thing with Advanced rocketry and that removed all knowledge of the electric furnace including recipes.

Please fix <3

![e40a443ccc13ba69e039bfd73e126d8c](https://cloud.githubusercontent.com/assets/21251496/23594078/d9dcfcd0-020e-11e7-8d7d-64abc6a8de50.png)

**Comment by KingLemming** [comment]
What exactly is wrong with your players knowing about the glorious machine that you are denying them?

To understand, if only briefly, what could have been.

**Comment by KingLemming** [comment]
Okay, serious response. Here's the deal.

That config option only disables the recipe and hides it from the Creative Tab. It's actually meant as a shortcut for packmakers who want to nix the recipe easily and then maybe add a new one. It doesn't disable it *entirely*, nor is that something I think is wise.

So I may add a separate config for JEI, but I'm not going to link it to that one.

**Comment by TheBritishBrotherhood** [comment]
Hahaha! ;D 

The reason i want this not to show is that my pack has a very strict progression, Steel is only able to be made from immersive engineering (Thats my goal anyway) I dont want there to be any backdoors/Loop holes

**Comment by KingLemming** [comment]
After some consideration, I went ahead and linked it because most pack makers are intelligent. :)

**Comment by TheBritishBrotherhood** [comment]
![divi9yo](https://cloud.githubusercontent.com/assets/21251496/23596927/cf030db4-0226-11e7-82b1-3763931e11bd.png)

**Comment by KingLemming** [comment]
Hey now. I didn't necessarily include you in that. >;)

**Comment by TheBritishBrotherhood** [comment]
May as well have done #OpieOP
