### ISSUE TITLE
Ducting Crash

### ISSUE THREAD

**Issue by Griffin224** [CoFH/Feedback#440]
Keep having issues with Thermal Dynamics. Server will crash (what makes it crash can depend, but most times it is hooking up some sort of duct) when I go to restart the server it immediately shuts down and I have to remove Thermal dynamics, starts the server up without it, then shut it down, re-add thermal dynamics and restart the server.

PLEASE tell me what I can do to fix this!
[crash-2017-07-24_15.00.10-server.txt](https://github.com/CoFH/Feedback/files/1186041/crash-2017-07-24_15.00.10-server.txt)

**Comment by Griffin224** [comment]
Oops, wrong log file...
[crash-2017-07-30_19.01.08-server.txt](https://github.com/CoFH/Feedback/files/1186071/crash-2017-07-30_19.01.08-server.txt)

**Comment by KingLemming** [comment]
Okay so that crash (and probably all your others) is being caused by Storage Networks. You'll have to remove it or take it up with them.
