### ISSUE TITLE
Minefactory Reloaded massive stackoverflow!

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [CoFH/Feedback#440]
Take a look at this... http://hastebin.com/goxajikudo.avrasm the f**k is going on?!

**Comment by KingLemming** [comment]
Looks like a Thaumcraft error, actually.

**Comment by Azanor** [comment]
Yeah, some mod must have recently added some TC compatibility that is breaking my aspect calc algorithm - there is a lot of these errors popping up lately.

**Comment by skyboy** [comment]
This is Witching Gadgets, disable the crucible recipes.

**Comment by Unrepentant-Atheist** [comment]
I checked witching gadgets config file. There's no option for that. Or am I missing something?

**Comment by BluSunrize** [comment]
Yes there is. I wish people would start reading the FAQ, or just one of the many closed issues. This error has been reported a hundred times and the response stays the same: Set "Enable transmutations" in the config to false.
