### ISSUE TITLE
Ghost items?

### ISSUE THREAD

**Issue by decryptedchaos** [CoFH/Feedback#441]
Not sure if this is already been reported i couldn't find anything in the existing issues.  

Don't have a lot of info no errors as far as logs go

Been noticing this issue with items being ghosted inside the redstone furnace 

Thermal Dynamics version is 2.0.9.13  for 1.10.2

https://i.imgur.com/5cWgofy.png

Sorry if this is a dupe,  feel free to close

**Comment by KingLemming** [comment]
Have literally never seen this nor can I seem to make it happen.

**Comment by decryptedchaos** [comment]
yeah,  I've never seen it until now,  I'm not sure whats causing it,  it seams to run through a stack of items and process the last one sometimes this seams to happen. 

If you click the ghost it dispersal and the machine starts working normally again until it happens again.  

You know,  i wonder if this has something to do with chunk-loading?    i usually notice this after coming back to my chunk-loaded base after mining.

**Comment by KingLemming** [comment]
So yeah, I've tested a LOT and can't seem to make this happen. There might be some strange x-mod stuff happening here when chunks load and it's screwing things up somehow.

What I can tell you is that this absolutely can't happen on 1.12. So...start playing that please. ;)

Officially, 1.10 is outdated and unsupported.
