### ISSUE TITLE
[Thermal Expansion] [BUG] Pulverising redstone doesn't output anything

### ISSUE THREAD

**Issue by CriticalRocket** [CoFH/Feedback#441]
Pretty straight forward: Redstone ore in a pulverizer doesn't output redstone dust(should output 6 redstone dust for each ore), nor cinnabar (cinnabar is 25% chance for each pulverised redstone ore, i've done 10 ores and got nothing). Pretty annoying :s

Mod Version: Well, idk. This is the (server) .jar name: **CoFHCore-[1.7.10]3.0.2-262** so I guess it's version 3.0.2-262? :p

MC Version: 1.7.10

List of all mods I'm using: http://www.technicpack.net/modpack/the-1710-pack.453902/mods

**Comment by KingLemming** [comment]
It's on your end, and when you figure out whatever it is, you may feel a little silly. Sure it isn't ejecting to an adjacent inventory? That's my bet.

But if you're sure, let's see some screenshots of your setup.

**Comment by CriticalRocket** [comment]
Hey,

I've been using the pulverizer with other ores, and those didnt output. So the redstone and cinnabar from Redstone Ore shouldnt either. Havent checked, but it's simply impossible :) Otherwise the gold that I pulverised seconds later should have gotten ejected aswell, as well as the cinnabar that gold ore got me. 

It's got nothing to do with my setup, 100% sure. I might be able to post some screenshots later tonight, otherwise tomorrow morning :) 

It could be something with conflicting mods or smthing.. but that seems highly unlikely to me, since all other ores just pulverise normally. I'll keep you updated,

**Comment by CriticalRocket** [comment]
Oke, I tried it again just now and it worked. Don't ask me how/why it didnt work yesterday, I didnt change anything. Wtf :/

**Comment by BoboSims** [comment]
What happens to me on occasion, is that a nearby hopper eats the stuff... After looking all over my base for the missing items, I find them inside that innocent-looking, but oh-so-guilty hopper.

**Comment by CriticalRocket** [comment]
I don't have any hoppers, so thats not an option ;)
