### ISSUE TITLE
[1.12] Crash on "Inserting"

### ISSUE THREAD

**Issue by havelyn325** [CoFH/Feedback#442]
I played at my private server and after I placed reinforced servo in auto pulverizing/melting factory, it started crashes if I comes to itemducts nearby this "factory".

[Mod List](https://pastebin.com/eMf7Ewh6)
[Crash Report](https://pastebin.com/2M8wUJdR)

_Sorry for bad english..._

**Comment by KingLemming** [comment]
Can't replicate this. Need screenshots.

**Comment by havelyn325** [comment]
Hmm.
I made a video and upload savefile.
Is this enough?
[Video](https://youtu.be/XIp9Gwh3Nqk)
[Save and mods](https://www.mediafire.com/?kw0ltxg5x7c59ri)

**Comment by Karolis2011** [comment]
I managed to get this crash too. Sometimes it occurred instantly when chunks with itemducts got loaded or it will crash on delay. 
Seems like crash in my case occurred when lead dust near my strange servo used as filter entered redstone furnace. 
[Video](https://youtu.be/sp0oKzL4h28)
[Crash log](https://pastebin.com/40jRyaTZ)
I had to purposefully reduce powered furnace count to make it crash.

**Comment by KingLemming** [comment]
Okay, so this is apparently a corner case which can only happen in extreme lag/desync. Possibly packet or chunk corruption.

I've added a mitigation for it, but frankly if you are seeing this at all, your world has much much bigger problems.
