### ISSUE TITLE
[1.12-4.3.3] crashes dedicated server Forge 1.12 build 2428

### ISSUE THREAD

**Issue by kreezxil** [CoFH/Feedback#443]
Notes:
     on startup, possibly a fluke, something about command handler

crash report:
https://gist.github.com/4113893033fb1a1489ecf4314b925678

fml server latest:
https://gist.github.com/f3c364365a0e1951b11de36373938976

**Comment by KingLemming** [comment]
This doesn't happen for me. Can you make it happen with *only* CoFH mods?
