### ISSUE TITLE
[Request]Baubles support

### ISSUE THREAD

**Issue by Post-opKen** [CoFH/Feedback#446]
With Baubles now updated to 1.12, it would be nice if we could charge RF accepting baubles with flux capacitors.

**Comment by KingLemming** [comment]
Agreed. Or, have the capacitor as a bauble. ;)

**Comment by KingLemming** [comment]
Capacitors charge baubles now. I don't think I can do capacitor *as* a bauble without a hard dependency, which I'm trying to avoid.
