### ISSUE TITLE
Questions about design decisions for dungeon generator algorithm

### ISSUE THREAD

**Issue by rockobonaparte** [CoFH/Feedback#447]
I was trying to use the dungeon generators for Baby's First Space Race, but I could never get it to generate a dungeon--particularly in The Nether.  I have been toying with the code for that such that it now does generate something in The Nether like I want, but I am wondering if I'm disregarding some design decisions in doing it.  I was planning to submit this code back, but I'd rather not wait until then to find out my implementation goes in a completely different directions.

Both our algorithms roughly have three phases:
1. Check if the dungeon can be validly generated at the given location.
2. Carve out the dungeon and build its walls.
3. Prepare dungeon loot chests.

I was having some issues:
1. I felt the selection criteria was too strict--particularly in handling air.  The generator permits holes, but if there were some in the central body, it looked like it would drop it completely.
2. I was seeing some strange problems with wall generation.  I don't think it was actually generating all the walls completely.
3. The dungeon loots chests would never generate because there was not a wall next to them to trigger their generation.

I did some stuff:
1. Dungeon generation will start if the blocks in the Y-column centered at the given coordinates are valid and not air.
2. I revised dungeon generation so that I was able to get some walls.  I could not follow the ABS checks so I used ternary operators.
3. Beyond the walls missing, it looked like it was trying to generate chests potentially at some bad coordinates, so I just made sure the random number generator was only providing combinations that are along the perimeter where walls would be.

I have to still see if my wither spawner works, and I wanted to see if my nether lakes work now, but I have to augment my testbench to get fluids from Thermal Foundation in there to find out.  I added some extra checks for parameters the web page claims are not mandatory but had NPE's when missing.

Anyways I was wondering if anything I was doing sounds like bad news.  Otherwise, I guess the source code will speak for me.

**Comment by KingLemming** [comment]
Paging @skyboy

**Comment by rockobonaparte** [comment]
I've been hanging around in the IRC channel and we've talked a little bit about this.  I think I've massaged the algorithm to be nether-friendlier, and it looks like it does generate a decent-enough dungeon in vanilla.  I have to verify I am doing the right stuff with the spawners; I don't think I broke that mechanic, but whatever I specify in the JSON is creating empty spawners.

**Comment by skyboy** [comment]
The generator is an exact copy of vanilla dungeons, with more freedom, so its behavior is fairly set in stone. You can make an issue/pr about the parsing errors though.
