### ISSUE TITLE
Underfluid and Geode Ore Generations don't work

### ISSUE THREAD

**Issue by UndeadZeratul** [CoFH/Feedback#45]
I've made sure my configs look correct, I've even looked in the parser files to see what properties I need to set, as well as make sure I use the correct fluid registry name; but still no ores are generating beneath any fluid.

I also have noticed that none of my uniform type, geode generator templates are working.  I've set diamonds and certus quartz to generate in geodes in the overworld, but when I fly around after a "/cofh clearblocks", I can't find any.

[Here](https://imgur.com/a/8kmf8) is an album of a few screenshots I took while flying around.  There's supposed to be sulfur beneath lava and bitumen beneath oil in the overworld, and ignatius and vulcanite beneath lava (vulcanite when in a phantasmagoric inferno biome, otherwise ignatius) in the Nether.

[Here](http://pastebin.com/NS7NsVn7) is the configuration for the blocks in question.

If I'm doing something dumb, I apologize; I just don't know what else is wrong after I've looked at what the parsers want from the JSON.

I'm on the following versions:
Forge v1286
Biomes O' Plenty v2.1.0.1004
CoFHCore v3.0.0B6-32
CoFHLib v1.0.0B6-26
Metallurgy Core v4.0.3.11
Metallurgy v4.0.4.43

**Comment by skyboy** [comment]
In the current release geode generators attempt to place all blocks around 0,0,0 (fixed in the alphas).
I'll look more into the underfluid generator

**Comment by UndeadZeratul** [comment]
Hmm, well I guess that's good to hear about geodes, even though that means I can't use them until CoFH updates.  I will await your findings on the underfluid generator.

**Comment by Maxwelljones** [comment]
I am also having some trouble trying to generate underfluid or underwater with CoFH Core. It seems I can't get any of those working although my JSON seems to be ok. Any news about the underfluid generator ? - would be great to be able to see a working cfg.

**Comment by skyboy** [comment]
Fixed by https://github.com/CoFH/CoFHLib/commit/e082ca55d659ea6ce5788682364de52687bcb6d9
