### ISSUE TITLE
[Request]Add Numismatic Dynamo to fuel.cfg

### ISSUE THREAD

**Issue by TokkenGmr** [CoFH/Feedback#45]
So Happy we have this for 1.10 thank you!!!!

Please consider adding the numismatic dynamo to the fuel config. 
Allow for coins from other mods and set custom RF values for all coins

**Comment by KingLemming** [comment]
It's on the todo list, was an intentional omission for now. Solids are trickier than fluids.

**Comment by KingLemming** [comment]
Due to the rewrite of the Numismatic Dynamo and the eventual hope for a json "recipe" system, this won't be a thing, sorry.
