### ISSUE TITLE
Magma crucible crashes when trying to access

### ISSUE THREAD

**Issue by piedpipr314** [CoFH/Feedback#450]
Crash trying to access crucible GUI.  Was piping out to a freezing pillar via and Ender IO fluid conduit.  Even completely moving the machine away from all conduits and other blocks did not help.
Pastebin included:
http://pastebin.com/QZwkNySN

**Comment by BoboSims** [comment]
Update your mods to the latest versions first, please. At least your Team CoFH mods are not the most recent. From your paste, you seem to have: 

[quote]
AE2 Version: beta rv2-beta-18 for Forge 10.13.2.1291
        CoFHCore: -[1.7.10]3.0.1-254
        MineFactoryReloaded: -[1.7.10]2.8.0-104
        ThermalFoundation: -[1.7.10]1.0.0RC7-62
        ThermalExpansion: -[1.7.10]4.0.0RC7-141
        Mantle Environment: Environment healthy.
        TConstruct Environment: Environment healthy.
        NetherOres: -[1.7.10]2.3.0-12
        ThermalDynamics: -[1.7.10]1.0.0RC8-105
[/quote]

You *should* have:
CoFHCore-[1.7.10]3.0.2-262
CoFHLib-[1.7.10]1.0.1-151
ThermalFoundation-[1.7.10]1.0.0-81
ThermalExpansion-[1.7.10]4.0.1-182
ThermalDynamics-[1.7.10]1.0.0-122

Maybe other mod versions are datet as well?

**Comment by KingLemming** [comment]
Bobo nailed it. You're mixing versions up. Update everything.
