### ISSUE TITLE
[1.12] CoFH World generator types like geode not working?

### ISSUE THREAD

**Issue by cragrim** [CoFH/Feedback#451]
I've been experimenting with worldgen in 1.12 and I can't get some custom generator types to work. 
Maybe they're currently WIP?

When checking the loading console log the Json files appear to load correctly.
```
[00:45:41] [main/INFO] [cofhworld]: Reading world generation info from: cofh\world\02_actuallyadditions_oil.json:
[00:45:41] [main/INFO] [cofhworld]: Finished reading cofh\world\02_actuallyadditions_oil.json
```

**Current mod versions:** 
forge-1.12-14.21.1.2442-installer
CoFHCore-1.12-4.3.3.11-universal.jar
CoFHWorld-1.12-1.0.0.6-universal.jar
Complete mod list: https://paste.ee/p/tqRCR

I've been studying the templates **02_thermalfoundation_oil.json** and **03_thermalfoundation_clathrates.json** in **minecraft\config\cofh\world** in world and they don't appear to function either which made me suspect its WIP.

I'm using the documentation here but it's possible that I've missed something or its out of date.
http://teamcofh.com/docs/cofh-world/guides/world-generator-configuration/
There was no issue tracker for the new world module split in 1.12 so I hope it's allright with me posting here? It appears that the command **/cofh reloadworldgen** has been removed in 1.12? It was really handy to double check if one makes any editing syntax mistakes.

**Keep up the great work :)
Best regards** 

Snip from **02_actuallyadditions_oil.json** that appears to load correctly but doesn't actually create anything in-game:
```
{
	"dependencies": "actuallyadditions",
	"populate": {
		
			"canola_oil": {
			"distribution": "uniform",
			"generator": {
				"type": "geode",
				"block": "actuallyadditions:block_refined_canola_oil",
				"material": [
					"minecraft:dirt",
					"minecraft:gravel",
					"minecraft:stone",
					"minecraft:sand",
					"minecraft:sandstone"
				],
				"hollow": true,
				"filler": "actuallyadditions:block_refined_canola_oil",
				"crust": "quark:basalt",
				"cluster-size": 40
			},
			"cluster-count": 1,
			"chunk-chance": 1,
			"min-height": 10,
			"max-height": 40,
			"biome": "all",
			"in-village": false,
			"retrogen": true,
			"dimension": {
				"restriction": "blacklist",
				"value": [
					-1,
					1
				]
			}
		}
		

	}
}
```

For testing purposes I ran this one as regular oregen and it worked. Thinking it was fluids being weird.
```
{
	"dependencies": "actuallyadditions",
	"populate": {
		
		"oil_testing": {
			"distribution": "uniform",
			"generator": {
				"block": "actuallyadditions:block_refined_canola_oil",
				"material": "minecraft:stone",
				"cluster-size": 42
			},
			"cluster-count": 20,
			"min-height": 0,
			"max-height": 120,
			"retrogen": true,
			"biome": "all",
			"dimension": {
				"restriction": "blacklist",
				"value": [
					-1,
					1
				]
			}
		}
		
		
		
	}
}
```

**Comment by KingLemming** [comment]
They work. Please use the Twitch channel for stuff like this. The issue tracker isn't a forum.

Also, as a general rule, every time you open an issue with a ? at the end of it - you are almost definitely wrong.

**Comment by cragrim** [comment]
I'm only trying to be helpful, not run a discussion. SORRY if my report is not good enough. 
Is this your twitch chat where I should ask if its a bug beforehand? https://www.twitch.tv/kinglemming

I've checked over 50 chunks comparing the following entries named
- **"type": "geode"** with name **geode_doesnt_work** 
- **"type": "lake"**  with name **lake_works** 

With almost the exact same variables the lake type works perfectly fine with about 1 in every chunk but the geodes have NEVER showed up for me. 

```
{
	"dependencies": "actuallyadditions",
	"populate": {
		
		"geode_doesnt_work": {
			"distribution": "uniform",
			"generator": {
				"type": "geode",
				"block": "actuallyadditions:block_refined_canola_oil",
				"material": [
					"minecraft:dirt",
					"minecraft:gravel",
					"minecraft:stone",
					"minecraft:sand",
					"minecraft:sandstone",
					"chisel:marble",
					"chisel:basalt",
					"chisel:limestone"
				],
				"hollow": true,
				"filler": "actuallyadditions:block_refined_canola_oil",
				"crust": "quark:basalt",
				"cluster-size": 40
			},
			"cluster-count": 1,
			"chunk-chance": 1,
			"min-height": 10,
			"max-height": 60,
			"biome": "all",
			"in-village": false,
			"retrogen": true,
			"dimension": {
				"restriction": "blacklist",
				"value": [
					-1,
					1
				]
			}
		},
		
		"lake_works": {
			"distribution": "uniform",
			"generator": {
				"type": "lake",
				"block": "actuallyadditions:block_refined_canola_oil",
				"material": [
					"minecraft:dirt",
					"minecraft:gravel",
					"minecraft:stone",
					"minecraft:sand",
					"minecraft:sandstone",
					"chisel:marble",
					"chisel:basalt",
					"chisel:limestone"
				],
				"outline-block": "quark:basalt",
				"gap-block": "quark:basalt",
				"cluster-size": 40
			},
			"cluster-count": 1,
			"chunk-chance": 1,
			"min-height": 10,
			"max-height": 60,
			"biome": "all",
			"in-village": false,
			"retrogen": true,
			"dimension": {
				"restriction": "blacklist",
				"value": [
					-1,
					1
				]
			}
		}
		
		
		
	}
}
```
