### ISSUE TITLE
tile screen issue

### ISSUE THREAD

**Issue by morkoll** [CoFH/Feedback#451]
ok so the only mods im using are the most current versions of cofh core and lib, minefactory reloaded, nether ores, redstone arsenal, thermal dynamics, thermal expansion, thermal foundation, liteloader and as far as forge is concerned im running on 1291. by the way my minecraft has had a fresh install today and so is running on the most current launcher. everything is for 1.7.10. now the bug that im getting is on the title screen where for the most part the entire screen is white except in the bottom left corner where there is an image none of the buttons are available therefore i cant play the game. now before anyone starts the suggestions understand that everything loads to the title screen correctly without the afore mentioned mods from cofh installed. would like to be able to play with the updated stuff so can anyone help?

**Comment by bochen415** [comment]
This is a Forge issue with crappy Intel gpus.
Read the forge EAQ http://www.minecraftforge.net/forum/index.php/topic,20.msg8027.html#msg8027
Insert -Dforge.forceNoStencil=true to your java args.

External issue. Should be closed.

**Comment by morkoll** [comment]
i understand what you are trying to say here however that is not the case since that doesnt fix the problem and the problem only exist with these updated mods insatlled (cofh core and lib, minefactory reloaded, nether ores, redstone arsenal, thermal dynamics, thermal expansion, thermal foundation)

**Comment by morkoll** [comment]
also when i looked up the issue through the web i found that i wasnt the only one having this issue and the aforementioned argument doesnt fix the problem that the problem only exists when cofh core is installed. if you remove that mod the title screen issue doesnt exist but the world  wont load because that 1 mod is not installed

**Comment by Stefan0209** [comment]
Did that and i got this:
http://prntscr.com/73reln
