### ISSUE TITLE
[Suggestion] Extract some code/textures out into CoFH Core or Lib

### ISSUE THREAD

**Issue by unwrittenfun** [CoFH/Feedback#452]
In the process of writing a mod that adds a new machine in the style of Thermal Expansion, I have found some things that would be useful to be extracted out of Thermal Expansion.

I have found that about 99% of all the things you need to create a Thermal Expansion style machine is in CoFH Core/Lib (Interfaces + GUI). However, there are a couple of things (that I have found so far) that would need me to require Thermal Expansion rather than simply CoFH Core.

The first is the __side config textures__ (the blue/red/orange/etc squares that indicate the sides in/out state). At this point in time I would either need to require Thermal Expansion to be installed or copy-paste these textures into my mod. Obviously it wouldn't be ideal to have to include them and I would also need your permission to do so. I would suggest that this is a feature that any mod implementing machines/blocks that are in the theme of Thermal Expansion would need access to and therefore it would make sense to me to extract them out of Thermal Expansion and into CoFH Core/Lib. I would suggest somewhere else but seeing as most other textures required are already in CoFH Core/Lib this seems fitting.

Another thing to do with sides is the __ElementSlotOverlay__ (the blue/red/orange/etc highlights in the gui). This is currently in Thermal Expansion (package cofh.thermalexpansion.gui.element) and is the only piece of code I currently depend on from it. If the above is moved out, it would only make sense that this should also (along with the texture used).

The last thing is the __textures for the machine top, side, and bottom__. This is the one I am stuck on as to me it only really makes sense to include this with Thermal Expansion. So, unless you disagree, I ask you for permission to include these within my mod.

I appreciate your time in reading this and respect your decision should you agree or disagree with my suggestions.

**Comment by KingLemming** [comment]
The problem is one of image. If the machine is actually appropriate for TE and isn't in TE yet, let us know and we can add it.

If it's not appropriate for TE, then it maybe shouldn't look like one. :/

I'll think on this. If you're really trying to copy TE's style though, what's wrong with actually depending on TE?

**Comment by unwrittenfun** [comment]
I would say it is appropriate to for TE, its a pump. I had thought of the issue of image, but then I thought I can make the gui for a block look exactly like a TE gui with everything from CoFH Core/Lib. 

Of course I could just depend on TE and none of this would matter, however it would be nice to keep the user option to just install my mod rather than also TE if all they wanted was a pump.

I have already basically coded the whole thing using everything in CoFH Core/Lib and these were the only things that meant I would need to require TE.

As for using your textures obviously if you would rather not have other mod's use TE's image then I will just have to make some of my own but I thought it would be nice to make it look like an addon to TE rather than some random pump mod.. and then the argument goes back to why not just depend on TE?

At the very least I think the sides texture + that class would be appropriate for not just TE and wouldn't be much different to the fact the gui stuff is in CoFH Core/Lib

**Comment by KingLemming** [comment]
It's very appropriate for TE, yes. That's why we're adding one. If you want a standalone version, I'd request that you use separate textures to avoid confusing people.

**Comment by unwrittenfun** [comment]
That's good to hear, is it near release or on a list for 'we'll do it at some point'? Just so I can make a decision on whether to develop mine further or not (with different textures ofc).

**Comment by KingLemming** [comment]
The pump is about 50% written at the moment, but I'm fairly busy for the foreseeable future. No ETA.
