### ISSUE TITLE
[1.12] RF API not working with Actually Addition's Crystal Flux on Forge server.

### ISSUE THREAD

**Issue by zzApotheosis** [CoFH/Feedback#452]
# Information
Java Version 8 Update 141 (build 1.8.0_141-b15)
Minecraft 1.12
MCP 9.40
Forge 14.21.1.2443
OptiFine_1.12_HD_U_C5_pre
RedstoneFlux-1.12-2.0.1.2-universal

# Problem
It seems as though standard Redstone Flux (RF) generating machines like dynamos do not play nice with Crystal Flux (CF) consuming machines from Actually Additions. However, this problem only happens on a Forge server, as it works fine on single player.

Here's a 5 minute video demonstration of the problem: https://drive.google.com/open?id=0B_wljXPJi507N3dlTVkxMW5LdVk

**Comment by KingLemming** [comment]
Okay. Better let Actually Additions know. We do everything properly on our end.
