### ISSUE TITLE
Thermal Dynamics (2.0.7.10) (mc 1.10.2) , Retrivers unable to pull Items from Ovens

### ISSUE THREAD

**Issue by DrKilledalot** [CoFH/Feedback#453]
Iam playing on a slightly modified ftb beyond modpack , heres the modlist: http://www.modlister.com/user/Dr_Killedalot

When i attach an itemduct on the bottom of a furnace (if the furnace contains smth smelted) a retriver on a nearby chest can pull the items for a few seconds.
After that evrything newly smelted doesnt get pulled.

**Comment by KingLemming** [comment]
Dunno what you mean by "oven," but no - retrievers are working correctly.
