### ISSUE TITLE
Use plugin messages rather than packets (?)

### ISSUE THREAD

**Issue by Nentify** [CoFH/Feedback#453]
This was discussed last week and was wondering if any further action would be taken upon @dualspiral's feedback and information here: https://github.com/SpigotMC/BungeeCord/issues/1437

**Comment by KingLemming** [comment]
Not sure, honestly.

That solution is very heavy as it creates yet more new objects and a channel.

I'd really like to know why bungee seemingly can't handle packets, as they're used all the time elsewhere.

**Comment by skyboy** [comment]
It's confirmed as a bug that negative ID packets were slipping past the guards on packet id. They should have a release out covering it soon.
