### ISSUE TITLE
[MFR] Server crash: Crashing on conduit TileEntityRedNetEnergy

### ISSUE THREAD

**Issue by kerts93** [CoFH/Feedback#455]
When a player goes to certain location on map, our server crashes with this error message:
```
java.lang.RuntimeException: Crashing on conduit TileEntityRedNetEnergy(x=743,y=59,z=-289)@1980166801
        at powercrystals.minefactoryreloaded.net.GridTickHandler.tickEnd(GridTickHandler.java:160)
        at powercrystals.minefactoryreloaded.net.GridTickHandler.tick(GridTickHandler.java:77)
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_203_GridTickHandler_tick_ServerTickEvent.invoke(.dynamic)
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
        at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:247)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:590)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.NullPointerException
        at powercrystals.minefactoryreloaded.tile.rednet.RedstoneNetwork.mergeGrid(RedstoneNetwork.java:226)
        at powercrystals.minefactoryreloaded.tile.rednet.TileEntityRedNetCable.incorporateTiles(TileEntityRedNetCable.java:162)
        at powercrystals.minefactoryreloaded.tile.rednet.TileEntityRedNetCable.firstTick(TileEntityRedNetCable.java:141)
        at powercrystals.minefactoryreloaded.tile.rednet.TileEntityRedNetEnergy.firstTick(TileEntityRedNetEnergy.java:115)
        at powercrystals.minefactoryreloaded.net.GridTickHandler.tickEnd(GridTickHandler.java:156)
        ... 8 more
```
[Full crash log on pastebin](http://pastebin.com/gb3HTmdf)
[FML logfile](http://thesociety.eu/uploads/logsForBugReports/2015-04-22/fml-server-latest.log)
[Server logfile](http://thesociety.eu/uploads/logsForBugReports/2015-04-22/latest.log)

Forge version:
>1.7.10-10.13.3.1385

List of TeamCofh mods:
>CoFHCore-[1.7.10]3.0.2-262
ThermalExpansion-[1.7.10]4.0.1-182
ThermalFoundation-[1.7.10]1.0.0-81
MineFactoryReloaded-[1.7.10]2.8.0-104

Full list of mods:
>[1.7.10-10.13.0.1198]ArchimedesShipsPlus-universal-1.7.10.B-Plus.jar
AppleCore-mc1.7.10-1.1.0.jar
BiblioCraft[v1.10.3][MC1.7.10].jar
BigReactors-0.4.3A.jar
Carpenter's Blocks v3.3.6 - MC 1.7.10.jar
ChickenChunks-1.7.10-1.3.4.17-universal.jar
Chisel2-2.3.10.37.jar
CodeChickenCore-1.7.10-1.0.5.37-universal.jar
CoFHCore-[1.7.10]3.0.2-262.jar
ComputerCraft1.73.jar
DragonsRadioMod-MC1.7.10-1.6.3.jar
EnderIO-1.7.10-2.2.8.367.jar
extrautilities-1.2.4b.jar
Flans Mod-1.7.10-4.9.0.jar
HungerOverhaul-1.7.10-beta.5.jar
IguanaTinkerTweaks-1.7.10-2.1.4.jar
InventoryTweaks-1.58-147.jar
ironchest-1.7.10-6.0.62.742-universal.jar
JourneyMapServer1.0.3_MC1.7.10.jar
LampsAndTrafficlights-1.11-Minecraft_1.7.2.jar
malisiscore-1.7.10-0.11.4.jar
malisisdoors-1.7.10-1.6.jar
Mantle-1.7.10-0.3.2.jar
MineFactoryReloaded-[1.7.10]2.8.0-104.jar
MineTweaker3-1.7.10-3.0.9C.jar
Morpheus-1.7.10-1.6.4.jar
MrCrayfishFurnitureModv3.4.7(1.7.10).jar
neiaddons-mc1710-1.12.5.17.jar
NotEnoughItems-1.7.10-1.0.4.95-universal.jar
Pam's HarvestCraft 1.7.10h.jar
PlanetguyLib-1.5.jar
plantmegapack-4.16A-1.7.10-1230.jar
ProjectZulu-1.7.10-1.4c2.jar
Railcraft_1.7.10-9.5.0.0.jar
RemainInMotion-2.5.4.jar
RoadWorks-2.01-Minecraft_1.7.2.jar
SpiceOfLife-mc1.7.10-1.2.3.jar
TConstruct-1.7.10-1.8.4.jar
ThermalExpansion-[1.7.10]4.0.1-182.jar
ThermalFoundation-[1.7.10]1.0.0-81.jar
tradebooth.1.7.10.1.jar
Waila-1.5.10_1.7.10.jar
WailaHarvestability-mc1.7.x-1.1.2.jar
worldedit-forge-mc1.7.10-6.0.2-SNAPSHOT-dist.jar

**Comment by Entoarox** [comment]
have you tried using /setblock to replace the issue causing block (its position is in the error log) with air?

**Comment by kerts93** [comment]
I can't even get near the area, but I could try setting the location manually, i think WE had /setpos1 and /setpos 2?

**Comment by Entoarox** [comment]
vanilla 1.7.10 comes with the build in /setblock command, you should be able to enter the exact coordinates (`TileEntityRedNetEnergy(x=743,y=59,z=-289)`) and use minecraft:air as the replacement block.
It may or may not fix the issue, depending on if it is the only block causing the issue, and it is not an interaction problem.
If it is an interaction problem, you might want to consider destroying the whole chunk, if you do not mind the loss of any custom structures inside it. (or spend the time removing each problematic block one by one)

**Comment by kerts93** [comment]
Well this isn't our live server, this is our testserver where we test our pack updates, so I'd like to fiqure out this problem before updating it, maybe it can be fixed etc.

**Comment by kerts93** [comment]
This is the setup that is crashing, I draw the block inside black square (image taken from live server where update hasn't been applied yet)
![Crashing setup](http://i.imgur.com/PkaipCt.png)

**Comment by Entoarox** [comment]
What version of minefactory are you upgrading from?
It might be that the grid system was changed in ways that prevent the update from happening properly

**Comment by BoboSims** [comment]
Could you rebuild the rednet energy cables such that it touches every machine at only one side? Like a ring of cable touching all of them on top (or at the bottom), but nowhere else? I'm sure it's of no concern, but perhaps...

**Comment by kerts93** [comment]
@Entoarox From version is: [1.7.10]2.8.0RC8-86

@BoboSims Currently syncing the 2 maps (live server > testserver) if the problem occurs, I will try. I have no idea why the player has made the system like that.

**Comment by BoboSims** [comment]
Ok, I can live with that. I'm just thinking that in a weird way maybe the odd loopings in the cables might be causing this trouble. It *shouldn't* make much of a difference, but one never knows.

**Comment by Entoarox** [comment]
What you could try is loading the world with  each of the alpha releases between the version you are updating from and the one you are updating to, maybe a slow progression will allow the grid to adjust, at the very least you'd be able to inform skyboy as to what build of MFR the issue starts happening with.

**Comment by kerts93** [comment]
It looks like the problem occurs when we move away from it and maybe chunck tries to unload. It looks like it's on the borders of chunck:
![on the borders](http://i.imgur.com/rYqyHes.png)

@BoboSims Your suggestion did not change anything

@Entoarox I could try that, I had to do similar thing when we used unstable branch and to get onto stable branch, map couldn't convert directly.

**Comment by BoboSims** [comment]
Alright! I expected as much, but thought it was worth a try. Thank you for checking, @kerts93.

But the construction crossing a chunk border might indeed be relevant! As long as a player is present, both chunks are active. But as you move away, I'm guessing the one furthest from you unloads first, causing the issue.

**Comment by kerts93** [comment]
This looks like same issue:
https://github.com/skyboy/MineFactoryReloaded/issues/414

**Comment by kerts93** [comment]
Adding Energy cell to the marked block removes the error:
![Energy cell](http://i.imgur.com/LWCGzFX.png)

**Comment by skyboy** [comment]
Should be fixed in dev
