### ISSUE TITLE
|1.12| issue when (re)connecting cryo stabilized ducts.

### ISSUE THREAD

**Issue by Bass2style** [CoFH/Feedback#457]
when breaking a cryo-stabilized fluxduct, and placing it again, the fresh-placed duct wont connect to the old one.
it seems to append when energy is present in a duct, and we connect an empty duct to the network.
i tryied to reproduce the bug, but when doing it voluntary, it's not working, i dont know why.

using FTB Unstable 1.0.7, but whas already problematic when in 1.0.6.

**Comment by KingLemming** [comment]
Got a video? Because I absolutely can't make this happen. Nor is there literally anything in the code which suggests it could happen.

**Comment by Bass2style** [comment]
i've tryied to reproduce this, but i cannot reproduce it, it appens 4 times, but seems realy random.

**Comment by KingLemming** [comment]
Yeah I still can't make this happen, sorry.

**Comment by Paul17041993** [comment]
do the logs mention anything about skipping ticks or any form of errors?

**Comment by Bass2style** [comment]
not noticed, but i shoul check the console when that appens the next time. very strange issue.

**Comment by KingLemming** [comment]
I've been unable to reproduce this in any way, and I've been doing a LOT of cryoduct testing lately. Likely x-mod or Forge instigated.
