### ISSUE TITLE
[1.12] Crashing with Comparable Items Error

### ISSUE THREAD

**Issue by shadowkeriphin** [CoFH/Feedback#458]
**Information:**
- I do have this Argument enabled:  -Dcofh.rf.crashOnOldAPI=false
- I have not tried with this argument removed or disabled.
- I have tried searching for relevant errors online in both Google and GitHub.
- I verified that the MC Versions for the four Thermal mods and CoFHCore+CoFHWorld match and are the latest versions.
- Everything Loads without Thermal Expansion enabled.

Wondering if this is a mod interaction problem or the argument enabled or something else entirely.

[------>| net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Thermal Expansion (thermalexpansion) |<-------]
[------>| Caused by: java.lang.NoClassDefFoundError: cofh/core/util/ComparableItem |<-------]

https://pastebin.com/ZfbrHu3P

[crash-2017-08-05_16.30.16-client.txt](https://github.com/CoFH/Feedback/files/1202699/crash-2017-08-05_16.30.16-client.txt)

Thank you!
-SK

**Comment by KingLemming** [comment]
Go update all your mods.

**Comment by shadowkeriphin** [comment]
All of my Mods are their latest as I have downloaded them with in the last 24 hours and rechecked.

I will try removing the argument however that still does not help me understand why this error occurred. Do you know why this occurred based on the logs provided?

I don't expect or need you to say "yes this mod" but I am looking for what "comparable item" might be referencing so that I can narrow down my investigation.

**Comment by KingLemming** [comment]
It can't find a CoFH core class, which means your mods don't match somehow.

**Comment by shadowkeriphin** [comment]
So something - possibly a mod that either interacts with CoFH or Overrides CoFH and causes Thermal Expansion to not find what it is expecting - thus when not using TE - no problems. 
I doubt its a problem with TE. 
Ok - Thank you! That helps a lot actually.

**Comment by KingLemming** [comment]
It's definitely not TE, no. Make sure you have the most up-to-date versions, as that is the most likely culprit.

Don't rely on the mod menu - go to Curse and redownload ALL of them.
