### ISSUE TITLE
[1.10.2] Crash when right clicking ducts while in the air.

### ISSUE THREAD

**Issue by MUSE-iC** [CoFH/Feedback#459]
When right clicking a duct(itemduct, fluxduct, fluiduct) while in the air (jumping, creative flying, jetpack flying) the game crashes.

It doesnt matter if you are placing a block, another duct, or just right clicking with an open hand.

I noticed that the crash log also mentioned iron backpacks. So I went ahead and disabled it to see if that fixed the issue and it did. I also tried disabling foamfix and betterfps but just disabling iron backpacks works. 

https://pastebin.com/eHCdXUqb
My iron backpack is a version behind in this log but the issue is still present in the latest version.

**Comment by KingLemming** [comment]
Yep. That's an Iron Backpack issue.
