### ISSUE TITLE
[Thermal Expansion/Extra Utilities] Drum Dupe Bug

### ISSUE THREAD

**Issue by Nentify** [CoFH/Feedback#46]
Putting more than 1 empty drum in a fluid transposer and filling it with a liquid will fill all the drums, and one will be output.

![](http://i.nentify.me/X1feLUPJ.gif)

**Comment by KingLemming** [comment]
Known issue. Sort of a weird implementation problem on a Forge level, since the intention was the IFluidContainerItems would not stack.

**Comment by bochen415** [comment]
https://github.com/rwtema/extrautilities/issues/363

**Comment by KingLemming** [comment]
The transposer has been redone to accommodate this.
