### ISSUE TITLE
[Redstone arsenal] Stop lying about having the IC2 api.

### ISSUE THREAD

**Issue by portablejim** [CoFH/Feedback#460]
Since Redstone Arsenal includes a fraction of the api, but also a package-info.class for the IC2 api, any mod testing for the IC2 api thinks it has the entire api ("Is there an apple in the fruit bowl?" "Yes" '*looks* Its only a stalk!" "Same difference").

All the poor mods that see if the IC2 api is available by testing to see whether the IC2 api is available get caught out.

**Comment by KingLemming** [comment]
This report doesn't meet the 5th requirement for bug reporting. Surefire way to get it closed.

I'll take a look though, but it's pretty super low priority.
