### ISSUE TITLE
Rendering Issue | 1.12

### ISSUE THREAD

**Issue by TheSpicePhantom** [CoFH/Feedback#460]
Hello, i got a problem that seems to happen very rarely, but I got it happening to me.
Since CofH Mods depend on the Mod "CodeChickenLib" and its rendering mechanics, this issue is going to be published here and on the CodeChickenLib Part of TheCBProject.
[This is my CrashReport](https://hastebin.com/raw/adonafunup)

Now to how I got this issue show up.
I placed down a Redstone Furnace and a Pulverizer, left the game to play a different game. I wanted to join back in my Base and the game crashed, i tried it 3 times! (All gave me the same result) I ended up deleting the furnace and pulverizer with MCEdit, which worked fine.

Please Help!

**Comment by KingLemming** [comment]
This is xmod induced, sorry.

Seems to be Harvestcraft, though we aren't sure why.
