### ISSUE TITLE
[1.12] Fluid Transposer overplaying sounds

### ISSUE THREAD

**Issue by OreCruncher** [CoFH/Feedback#461]
Using TE 5.3.3.15 on 1.12.  Noticed that the Fluid Transposer when continuously operating plays a lot of sounds.  In the case I am seeing it is up to 69 instances of "thermalexpansion:blocks/machine/transposer" and is steadily climbing.  I am running the Radon modpack (on CurseForge).

EDIT:  When the transposer went idle all the sounds in the sound engine released and went back to normal.  It peaked at something like 171 instances.

**Comment by KingLemming** [comment]
As a general rule, please don't use a question mark in an issue name. It makes me want to close it outright, because the answer is negative about 150% of the time.

I haven't seen this myself, but I'll look into it.

**Comment by OreCruncher** [comment]
Not sure if it is relevant but I am playing on a server, not single player.

**Comment by Tonius** [comment]
I've noticed this with the Redstone Furnace and Pulverizer as well. It seems to happen when enabling/disabling auto-input or auto-output while a machine is operating.
