### ISSUE TITLE
Feature Request:Redstone Arsenal Liquidpack

### ISSUE THREAD

**Issue by Badcholo** [CoFH/Feedback#462]
I see a liquidpack mod. The idea would be great if used in Redstone Arsenal.
http://www.curse.com/mc-mods/minecraft/224371-liquipacks

**Comment by BoboSims** [comment]
I'm curious: What would be the purpose? I mean, there is obviously already a mod out there that has the functionality you're looking for: the one you linked to! And I'm not certain if this idea fits RSA's scope. It's quite different from everything that RSA already contains.

Also, what's wrong with carrying around one or two Reinforced Portable Tanks? They're not too involved to build, and I don't see the point for much more... after all, how many different liquids do you need to carry with you and how much of each?

If the issue is that tanks take slots in your inventory, so would a backpack. A backpack could possibly be worn in the chestplate slot, but that limits you to only one backpack. So how many different liquids must that backpack store simultaneously?

Believe me, I'm not trying to immediately shoot this idea down. I just want to try and understand why you want something like this in RSA.

**Comment by KingLemming** [comment]
TE has a FluiVac on the way. It doesn't work like this though, and honestly there's no reason to copy a mod that already exists.

**Comment by BoboSims** [comment]
FluiVac, huh? So that's the name of the pump? I can't wait to see it happen. With TE's track record, it's bound to be awesome squared :sunglasses:

**Comment by Badcholo** [comment]
BoboSims,
1). The purpose of a Liquid backpack is so that i don't have to place a tank and keep filling it with buckets. It would be nice to be mobile instead of having to run back and forth.
2). Liquid Backpacks can be Armored! wha? i didn't know you could do that.......
3). The Capacity of Tanks can be changed and i am sure upgrades will come next.
4). I have added the idea here for a Hose as such to scoop up fluids and place the fluid into portable tanks in your inventory. That wouldn't take up a chest space and is very simple.
5). I never said copy someone elses mod!!!
6). I do a lot of work reporting, finding bugs, giving feedback and coming up with ideas. I also create modpacks, run a server and am learning ways of creating textures and mod reviews, so i'm not some spoiled player that just wants everyone to do all the work while he just plays and complains. I don't even get to play anymore cause i'm always updating and finding root causes to crashes, bugs or dupes. Ideas are ment to be heard, then dismissed or used. Take the idea or leave it, but don't ask me to help you understand why it sucks so bad to have to run back and forth filling up a portable tank with buckets.

**Comment by Badcholo** [comment]
Your such a kiss ass

**Comment by BoboSims** [comment]
@Badcholo:

1. You obviously have never heard of the *Pump*? It makes bauckets rather obsolete!
2. Liquipack armor is limited, and can't be enchanted.
3. Tanks can be changed, but as I said, even the largest is still too small for me.
4. It may have a different name, but the hose is already a part of the LiquiPack mod as well, so it doesn't sound like you had an original idea.
5. Maybe not literally, but you *did* point at a specific mod, and suggested that its *functionality* was copied into some RSA object. So if that's not copying someone else's mod, I don't know what is.
6. I have a suggestion: take a bit of time for yourself. In stead of running around trying to be famous, have a life and make some fun. You should find out how a *Pump* works, *before* you start requesting  copies of *someone else*'s original ideas

And in response to your last post, I'd like tyo add: And *you*, sir, are a barbarian with no understanding of a decent conversation. I'm too civilised to put what choice words I have to say to you, out in the open.

**Comment by Badcholo** [comment]
1. duh, everyone has been asking for this. I would prefer a better way of gathering lava manually as my server is hardcore survival. 
2. yes it can. mr knows nothing.
3. 512 bucket tanks are too small for you eh? how about a million? 
4. that mod is new and just barely came out.
5. your an idiot, there are many mods that do the same thing, but in different ways.
6. your an noob if you think there is someone out there that doesn't know how a pump works. Your just a troll that has got me wrapped up in this stupid conversation. 

And polish my c*** i don't care what you think.
rather than having to deal with people like you, i'll stick to buckets and a tank.
Also who is trying to be famous? i make videos to help players on my server understand how things work. Stop being such a civilized Troll. Try adding your own comments instead of bothering others.
