### ISSUE TITLE
[1.10.2] [Request] Pam's harvestcraft support in MFR

### ISSUE THREAD

**Issue by stanedav** [CoFH/Feedback#462]
Hello guys,
 thank you for fantastic work on this mode, which is my favourite of all (I play modded MC since 1.6.4).
I am currently on version 1.10.2 and only thing that I am missing is support of Pams harvestcraft crops and fruits in Planter, Harvester and Fruit picker.
I would be very grateful for consideration of adding this feature.

Have a great day guys and thank you for great work!

**Comment by KingLemming** [comment]
MFR has its own issue tracker. Please put this up there: https://github.com/skyboy/MineFactoryReloaded/issues
