### ISSUE TITLE
Tesseract in send/receive energy mode not powering adjacent items

### ISSUE THREAD

**Issue by taiyoko** [CoFH/Feedback#463]
I just got my first pair of tesseracts built. One (the one in question) is connected directly to my Big Reactor power tap, in send and receive energy mode, items and liquids turned off. I have a channel configured and it correctly sends power to the other tesseract on the channel that powers my fledgling AE network.

However, energy cells and fluxducts directly connected to the reactor-side tesseract are not receiving any power and I'm not sure why.

**Comment by KingLemming** [comment]
This is intended behavior. A Tesseract does not send energy to itself.
