### ISSUE TITLE
I was told to come to you

### ISSUE THREAD

**Issue by archmage94** [CoFH/Feedback#463]
While i'm not having any issues with your mods, in fact I don't have any of them installed, I am having a related issue, see i'm trying to run Draconic Evolution but that requires Brandons Core, which requires CodeChickenlib and, oddly enough, Solar Flux Reborn. No problem right? Well apparently for whatever reason, Solar Flux Reborn is trying to repack the old CoFH API, check the crash report
[crash-2017-08-06_21.43.23-client.txt](https://github.com/CoFH/Feedback/files/1205260/crash-2017-08-06_21.43.23-client.txt)

**Comment by KingLemming** [comment]
Draconic Evolution shouldn't require Solar Flux Reborn. That sounds quite incorrect.

And the issue there is 110% with Solar Flux Reborn.

**Comment by archmage94** [comment]
Draconic Evolution isn't the one requiring Solar Flux Reborn, no for some reason Brandon's Core requires it, but Brandon's Core is required for Draconic Evolution, so if I remove Solar Flux Reborn that means I also have to remove Brandon's Core and therefore Draconic Evolution which defeats the purpose. Look at the crash report

**Comment by KingLemming** [comment]
I did. There is literally no reason for Brandons Core to require Solar Flux Reborn, nor does the crashlog say anything about that at all.

**Comment by archmage94** [comment]
I understand, though I do wonder why Solar Flux Reborn is trying to repack the old CoFH API

**Comment by covers1624** [comment]
No, I told you over at DE's tracker to yell at solar flux reborn, that are being dumb and repacking the old api, brandonscore nor DE require solar flux reborn. Solar flux reborn is in the wrong here, report to them.

**Comment by brandon3055** [comment]
As mentioned by lemming and covers BC does not in any way, shape or form require solar flux reborn.
What it does need though is "Redstone Flux" by CoFH.

**Comment by archmage94** [comment]
Ok I misread something and did something stupid, I got it figured out, thanks anyway
