### ISSUE TITLE
Thermal Tank dupe in ExU2 enchanter

### ISSUE THREAD

**Issue by OrdinatorStouff** [CoFH/Feedback#464]
![image](https://user-images.githubusercontent.com/6283913/29041939-c63e82be-7b69-11e7-9bc3-14ef0d9a1ceb.png)

ATC dev/test server found that putting a Thermal tank in the ExtraUtilities2 enchanter produced an output and left the source tank as input. I'm reporting here first to make sure it's not something related to the tanks before reporting to ExU2.

ThermalFoundation-1.12-2.3.3.10-universal
ThermalExpansion-1.12-5.3.3.15-universal
ThermalDynamics-1.12-2.3.3.10-universal
CoFHCore-1.12-4.3.3.11-universal.jar
extrautils2-1.12-1.5.1.jar

**Comment by KingLemming** [comment]
Nope. Not us. Internally, the Arcane Ensorcellator doesn't do this. Report to ExU2.
