### ISSUE TITLE
[1.12] Machines/Ducts Losing Their Data

### ISSUE THREAD

**Issue by MasterGeneral156** [CoFH/Feedback#465]
Forge 1.12 - 14.21.1.2443  
Thermal Expansion: 5.3.3.15  
Thermal Dynamics:  2.3.3.10
Thermal Foundation:  2.3.3.10
CoFH Core: 4.3.3.11  
CoFH World: 1.0.0.6  
  
What happens is whenever the chunks containing machines are unloaded, upon being reloaded, they lose their upgrade level, and in turn, their augments. The same happens with Thermal Dynamic's cover system. (They get removed from the ducts, never to be seen again)  
  
It's likely FTB Utilities chunk loading causing the issue. As of this moment, I do not have logs. Can try to recreate the issue and fetch logs if they may have important information.

Edit: Modlist incoming. https://pastebin.com/UAwRgzp5

**Comment by KingLemming** [comment]
This isn't on our end. It's been reported but we can't reproduce it with only our stuff. Xmod in nature, also affects Botania from what I've heard.
