### ISSUE TITLE
[1.12] Itemduct loop causes crash (StackOverflowError)

### ISSUE THREAD

**Issue by Karolis2011** [CoFH/Feedback#466]
So this is what I done and got a crash.
[My horrible photoshop of representation on what I constructed](http://i.imgur.com/jkDQ6YB.png)
This crash rendered map useless. I got it fixed only using MCEdit to remove servo from duct (Bottom left) MBT data.
[Crash stack](https://pastebin.com/FeeGQMCJ)
My guess on what happened: Item from pulverizer tried to enter network, but during recursive destiniation finding it entered recursive infinite loop.

Edit: Info on modpack:
Thermal Dynamics (2.3.3.10)
Thermal Foundation (2.3.3.10)
Thermal Expansion (5.3.3.15)
Code Chicken lib (3.1.1.288)

**Comment by KingLemming** [comment]
Well, don't do that then.
