### ISSUE TITLE
Strongbox bug in twlight forest

### ISSUE THREAD

**Issue by renakitsune** [CoFH/Feedback#467]
twlight forest v2.3.4
thermal expansion 141

came across a unusual bug last night while playing, had a resonant strongbox half filled with goodies from looting the ur-ghast tower in the dark forest, came to the section with the anti-builders and ...

I placed down the strongbox in order to fill it up with more drops, when it got broken by the anti-builder. it then popped out as a creative strongbox, and i lost the loot i got. lucky i had a aroma backup half an hour previous, so i restored the save.

Just thought i'd let you know of this bug.

**Comment by KingLemming** [comment]
Okay, so the anti-builder is broken. Gotcha.

This isn't on us - it sounds like the anti-builder does not correctly break blocks and assumes metadata 0.
