### ISSUE TITLE
Upgrading Servos/Retrievers in world

### ISSUE THREAD

**Issue by tgstyle** [CoFH/Feedback#467]
Would it be possible to have it upgrade to higher tiers just by clicking them with the ingot ?

**Comment by tgstyle** [comment]
Also keep the settings, whitelist/blacklist.

**Comment by KingLemming** [comment]
This is a no, sorry. The reason is that recipes can be changed with modpacks, but this behavior would require a LOT of extra code and backend hacks to adjust for that.
