### ISSUE TITLE
The CoFH cores do not work on 1.12.1

### ISSUE THREAD

**Issue by EmosewaGamer** [CoFH/Feedback#468]
Because of the upper forge limit, CoFH mods don't work on 1.12.1. Please just change it.
![image](https://user-images.githubusercontent.com/25333164/29209645-e8960ab6-7e8f-11e7-844b-c86db725fe1f.png)

**Comment by KingLemming** [comment]
I'm on vacation. Going to push a build. If it works, great. If it doesn't, too bad you can wait another 10 days.

**Comment by covers1624** [comment]
Builds are pushed.
