### ISSUE TITLE
[1.10] Astral Sorcery Lightwell (liquid starlight) + Fluiduct crash

### ISSUE THREAD

**Issue by MigukNamja** [CoFH/Feedback#469]
I opened the [Issue against Astral Sorcery](https://github.com/HellFirePvP/AstralSorcery/issues/261). I'm cross-posting here the crash here because eIO doesn't crash when extracting from Lightwells.

`java.lang.IllegalArgumentException: Cannot create a fluidstack from a null fluid
	at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:47)
	at hellfirepvp.astralsorcery.common.util.block.PrecisionSingleFluidCapabilityTank.drain(PrecisionSingleFluidCapabilityTank.java:174)
	at cofh.thermaldynamics.duct.attachments.servo.ServoFluid.tick(ServoFluid.java:91)`

[Full crash report](https://pastebin.com/X8dGK1ji)

**Comment by KingLemming** [comment]
That seems to be entirely in their code offhand. We just call a drain. They are the ones creating a null stack.

**Comment by HellFirePvP** [comment]
On my end. I'll tend to it next version; From what i guess, it exists on 1.10.2, 1.11.2 and 1.12(.1) versions aswell.

**Comment by MigukNamja** [comment]
Many thanks for the very quick responses :-)
