### ISSUE TITLE
[1.10.2] Game crashing with OptiFine

### ISSUE THREAD

**Issue by SlimF** [CoFH/Feedback#47]
I know, I know, OptiFine causes lots of unwanted bugs but here it goes. Yesterday, I installed CoFHCore, TE and TF and had absolutely no problems with the game. Today, when I placed a few Induction Smelters the game ran fine for a few minutes and crashed, I tried launching it again a few times but it just crashed again, so here is the crashlog:

[crash-2017-03-06_14.21.29-client.txt](https://github.com/CoFH/Feedback/files/821113/crash-2017-03-06_14.21.29-client.txt)

I tried disabling some of OptiFine's options but without success, removed it from the mods folder and the game is working fine again. 
I apologize for reporting a bug caused because of OF. And thank you for your work, for me FTB isn't FTB without your mods <3 <3 <3

**Comment by covers1624** [comment]
Seems optifine is being silly and passing us a null blockstate for our blocks. Suitable checks have been added. https://github.com/TheCBProject/CodeChickenLib/commit/6045d5096853445d740f59ec927a7b191af8f8d7

**Comment by covers1624** [comment]
Please verify the issue is fixed with this version: http://chickenbones.net/maven/codechicken/CodeChickenLib/1.10.2-2.5.6.237/CodeChickenLib-1.10.2-2.5.6.237-universal.jar

**Comment by SlimF** [comment]
Now the game hangs at part 6/7, LoadComplete - Just Enough Items.

**Comment by covers1624** [comment]
Can i have your FML-client-latest log please?

**Comment by SlimF** [comment]
Sure, here you are

[fml-client-latest.txt](https://github.com/CoFH/Feedback/files/821243/fml-client-latest.txt)

**Comment by covers1624** [comment]
Did, your client ever launch. seems to just be JEI loading..

**Comment by SlimF** [comment]
![image](https://cloud.githubusercontent.com/assets/6482572/23613000/3a91a360-0286-11e7-9d3d-340155337d57.png)
It just stays like this, I left it for 10 minutes.

**Comment by covers1624** [comment]
Pinging @mez, Its possible something weird is happening with JEI.

**Comment by bs2609** [comment]
Most likely this: https://github.com/mezz/JustEnoughItems/issues/746

**Comment by SlimF** [comment]
Yup, disabled Vsync and everything is working now, thank you @covers1624 and @bs2609 :)
