### ISSUE TITLE
[Compatibility] Better BuildCraft integration

### ISSUE THREAD

**Issue by asiekierka** [CoFH/Feedback#47]
Here are my personal proposals for improving BuildCraft <-> Thermal Expansion compatibility, in order from most to least important:

* **Implement IHasWork**. It's a single function and it serves the highly important role of letting BuildCraft gates know that a machine has work to do (that means it has work it could do and/or is doing - such as a pulverizer having an ore in its input slot). (It's also supported by OpenComputers via the Computronics addon, and possibly in the future ComputerCraft via OpenPeripheral) -> see https://github.com/BuildCraft/BuildCraft/blob/6.3.x/api/buildcraft/api/tiles/IHasWork.java
* Implement IControllable. This one is three functions and lets BC (and other mods providing the API) control machines, via gates or etc. Personally, I would do this as either a separate Control augment ("BuildCraft Gates") or a Tier 2 Augment you need to add on top of redstone - the former idea sounds more sound to me. -> see https://github.com/BuildCraft/BuildCraft/blob/6.3.x/api/buildcraft/api/tiles/IControllable.java
* Possibly look into adding custom gate triggers/actions. The new API is at https://github.com/BuildCraft/BuildCraft/tree/6.3.x/api/buildcraft/api/statements and is, in my opinion, reasonably improved from the previous one (it actually lets non-BC mods define gate triggers/actions in a sane way, it's also self-contained, fully independent from BC and doesn't do silly ID things anymore)

There are other things, such as builder schematic compatibility and robot request system integration, but in the case of (a) I don't think it's worth the effort, and for (b) the API is going to change soon anyway and right now it's really really bad, so... that's about it.

**Comment by KingLemming** [comment]
So asie, you still around these days?

**Comment by KingLemming** [comment]
Okay, so IHasWork has been added. I'm not certain about the other ones because I no longer know the future of BC.

Any comments on that, @asiekierka ?

**Comment by asiekierka** [comment]
Development has slowed down, but I do help out a bit.

BC is not dead, we are making new releases, whether you add the other ones is up to you and how much you like the ol' kinesis piping.

Also, I am wondering how http://m.imgur.com/oqLanCO happened.

**Comment by KingLemming** [comment]
Given the current transitional state of BC, I'm shutting this down for now until we know more about BC7 and what we can do. Feel free to open up a new Issue then so we can see if there's any additional integration we can add.

**Comment by asiekierka** [comment]
Old BC6 APIs are not going away, neither is the functionality.

The new APIs which are coming and might be useful for CoFH mods are:

* the Library API (already in 7.0.0), which lets you add custom import and export data types to the Electronic Library (previously the Blueprint Library),
* the IList API - adds support for the BuildCraft List item, which is essentially an item filter with its own GUI; it exports a function called "matches" to check if an ItemStack matches the List - and you can also implement it yourself to have support of your item-based filter in BuildCraft pipes, robots and machines.

**Comment by asiekierka** [comment]
Here's a good API to look into - the BuildCraft Facade API. https://github.com/BuildCraft/BuildCraft/tree/6.5.x/api/buildcraft/api/facades (Everything but FacadeAPI.java providing a way to access BuildCraft's own ItemFacade item is in there).

My recommendation would be to allow IFacadeItems to be placed on TD ducts and use get(Blocks|MetaValues)ForFacade (using only the first value of the array - the other ones are unimportant for non-BC users) to get the information about the block to be displayed - also, store the ItemStack used to place the facade to return that on dropping.
