### ISSUE TITLE
[1.7.10]IllegalAccesError on placing Tesseract with enderIO installed

### ISSUE THREAD

**Issue by picatrix1899** [CoFH/Feedback#470]
Hello,
when I place a tesseract in the world the game crashes with an IllegalAccessError.
If you join a world where you placed a tesseract and destroy it it will crash too. but the rightclick works correctly.
the issue was found in my modpack but could be tracked down to EnderCore, EnderIO, CoFHCore, Thermal Foundation and Thermal Expansion. This crash only happens when enderIO is installed without it works fine.
I used in my modpack another vesion of enderIO but could reproduce the issue with the latest beta and stable build of enderIO for 1.7.10.

Is this a known bug with a fix? I've searched a bit but didn't found this problem. I also already created an issue at enderIO issue tracker but they redirected me to here.

Steps to reproduce:

1. generate new world

2. place Tesseract from TE.

3. crash

1. load a world with a tesseract in it

2. destroy the teseract

3. crash

installed Versions:

EnderIO: 1.7.10-2.2.8.381
EnderIO: 1.7.10-2.3.0-429_beta
EnderCore: 1.7.10-0.2.0.39_beta
CoFHCore: [1.7.10]3.1.4-329
Thermal Foundation: [1.7.10]1.2.6-118
Thermal Expansion: [1.7.10]4.1.5-248
Minecraft: 1.7.10
Forge: 10.13.4.1614

Crashlog:
https://pastebin.com/M8k56afM

**Comment by KingLemming** [comment]
Caused by a mod including an invalid version of the CoFH API. Quite possibly EnderIO. You'll have to perform jar surgery.
