### ISSUE TITLE
Agrarian Skies 2 white Screen

### ISSUE THREAD

**Issue by thegamehunter09** [CoFH/Feedback#471]
In this modpack that is made by Jadedcat I have come across and issue that she can't solve and I believe it has something to do with your mod cofh core because I can't get the pack to start up without the white screen. The pack currently uses forge 10.13.3.1387 but I have tested the most up to date forge 1395 and I get to the mojang splash screen and then it gets to the pre initialization bit and java stops working when it gets to the cofh core.

The cofh core version is: 3.0.2-273
latest log: http://pastebin.com/DB712DmB
Early start up log:http://pastebin.com/ysBvZef2

**Comment by KingLemming** [comment]
I don't understand. Did you choose CoFHCore out of a hat?

There's literally nothing in that log that points to us.

**Comment by thegamehunter09** [comment]
No I used the newest one. The curse launcher is where I downloaded. I'm not really sure if it is entirely cofhcores fault but when I remove it everything shows up fine till it tells me I need to put back the cofhcore . When I put it back the white screen issue comes back. If it isn't your mod what does the log say to you. I know a little programming but my current knowledge is too limited at the moment to fully understand the problem

**Comment by KingLemming** [comment]
The log says to me that you have something causing an invalid GL operation. If it were CoFHCore, this would happen with every installation of it and this would not be unique to you. It's entirely possible (and likely) that it's something else depending on CoFHCore.

**Comment by thegamehunter09** [comment]
Could you name all the mods that depend on the cofhcore? I wanna see what happens if I remove them. I know thermal expansion, dynamics and foundation do but are there any others.

**Comment by KingLemming** [comment]
No, I actually can't. Our mods do, yes. But other mods in the pack might as well. They probably shouldn't, but people rarely do what they are supposed to.

**Comment by Velken** [comment]
This is a old bug, only happens with bad GPU (as far as I tested)
Before it would be simply solved with the  JVM Arguments: -Dforge.forceNoStencil=true
With some computers it stills happens.
But the easiest solution (also the one that I took), is to save some money and get a better GPU.
