### ISSUE TITLE
[1.12] TE Configurable Machine Power

### ISSUE THREAD

**Issue by NillerMedDild** [CoFH/Feedback#471]
Hey!

This request is for Thermal Expansion:
I'd really like a config option to configure base power of machinery, like there was in 1.7.10 Thermal Expansion. I'm making a modpack with pretty heavy changes to some tech mods, and I'd like to make Thermal Expansion a bit stronger, but at higher energy costs, and I'm currently not aware of a way to do it.

And of course, thank you for a great mod, I've enjoyed it since I started playing modded :)

**Comment by KingLemming** [comment]
Maybe.

**Comment by KingLemming** [comment]
Added this. The range is 25% to 400%, same as dynamos. I still want to contain the power window somewhat.

**Comment by NillerMedDild** [comment]
Thank you!

**Comment by KingLemming** [comment]
Edited it again and it's 10 to 200 for both Machines and Dynamos now. >:)

**Comment by NillerMedDild** [comment]
That'll do aswell :D

Just curious, is the higher possible RF requirement messing with the scale/look of the power window?

**Comment by KingLemming** [comment]
Not sure what you mean.

**Comment by KingLemming** [comment]
I mean the acceptable range. Basically I don't want machines being too fast.
