### ISSUE TITLE
TD 2.3.3.10 Items vanish from Itemducts(Furnace Fuel)

### ISSUE THREAD

**Issue by zeromic** [CoFH/Feedback#472]
Fuel Items vanishes after the first stack is consumed in the Furnace

You can see the Items(non opaque Itemducts) moving into the furnace but wont show up in the fuelslot and the furnace will not start working.

First occured with round robin setup: the first furnace in line will work but on all others the fuel will vanish.
Back or Frontside doesnt matter.

It seems after the first "round robin cycle" all items vanish even if you change the mode. Breaking and replacing all itemducs + servo and it works for one "cycle".

modpack: https://minecraft.curseforge.com/projects/modern-skyblock-2

JaR:ThermalDynamics-1.12-2.3.3.10-universal.jar

**Comment by KingLemming** [comment]
Can't replicate this. Need a video.

**Comment by zeromic** [comment]
I dont know how to capture a video..i can make some screenshots if it helps

**Comment by KingLemming** [comment]
It's better than nothing I suppose, but this doesn't seem to actually happen in any test setup that I've made.

**Comment by KingLemming** [comment]
Still need those screenshots. I can't make this happen.

**Comment by zeromic** [comment]
sorry had to rebuild the setup after i used other item transportation

I used normal servo without round robin and the fuel vanishes with them too:

http://imgur.com/a/7aXkg

and my world download

https://drive.google.com/file/d/0B8OYE0NcoHGBT2RyOHBPMDZTc2s/view

**Comment by KingLemming** [comment]
Servo logic got a bit of a rewrite, so even if we could replicate this before (we couldn't), it's not really valid anymore anyways.

In any case, this was definitely unique to you and the pack. An issue like this where items disappear randomly? We'd have heard about it, in droves.

**Comment by Paril** [comment]
This issue definitely still happens in Modern Skyblock 2. It's extremely odd. Servos kind of stop working, get clogged up randomly and don't seem to interact properly. Vanilla furnaces especially seem to like doing this.

**Comment by jhebert121** [comment]
I am getting the same issues in Modern Skyblock 2.  Not sure if it is related to the pack but itemducts seem to be very buggy in Modern Skyblock 2.  I get random items now showing up inside of inventories, and tons of random clogged servos.  I have used itemducts rather extensively in Direwolf's 1.12 pack, and have not had these issues.

**Comment by KingLemming** [comment]
Cool, so it's definitely another mod then. Something in Modern Skyblock 2 and NOT in DW's pack.

**Comment by Paril** [comment]
Yep, just wish we knew what mods edited the ducts like this. The weird thing is it seems to happen the most with furnaces; for instance I have a setup with storage drawers, mechanical crafter, freezer, and they all extract/insert fine, but furnaces cause disappearing items. The only thing I can think of that modifies vanilla furnaces is the mod that makes the UI smoother (like the burning bar is more "accurate"/subpixel if that makes sense).

**Comment by KingLemming** [comment]
I didn't think anything is necessarily editing the ducts, but actually...you might be right. Capabilities can be attached to (read: forced on, like assault) anything at runtime (part of why it's a terrible system).
