### ISSUE TITLE
Automating the auto-disenchanter

### ISSUE THREAD

**Issue by scifibob** [CoFH/Feedback#472]
I'm unable to insert items into this machine via automation.
Currently I've tried EnderIO conduits and Steve's Factory Manager in my test setup.
Books loads fine, but the items to disenchant is not loading, like swords, etc.
When testing, there has been occasional inserts, but these seem random, and it's not happening very often.
I get no errors in the logs. At least none I can see relates to this bug report.

My current test setup is a single player world, with the following plugins:

CoFHCore-1.7.10-3.0.2-262.jar
EnderIO-1.7.10-2.2.8.367.jar
MineFactoryReloaded-1.7.10-2.8.0-104.jar
StevesAddons-1.7.10-0.10.2.jar
StevesFactoryManagerA93.jar

I have the same problem on my SMP server - so I thought I could test it on single player without all the other mods I have on the server.

Log dump: http://pastebin.com/ZGvNDTkf

**Comment by skyboy** [comment]
I can't reproduce this. Screenshots of your attempts?

**Comment by KingLemming** [comment]
Yeah, we need screenshots. Lots of them.
