### ISSUE TITLE
[Thermal Expansion] [Mod compatibility bug] Galacticraft canister issues.

### ISSUE THREAD

**Issue by nigraforce** [CoFH/Feedback#473]
Putting a galacticraft's filled canister in the fluid transposer in fill mode does not drain the canister, but the inner tank does fill up. This results in fluid(fuel, oil, oxygen, w\e galacticraft liquid) dupe. 
redfast says that this is TE's bug. https://github.com/micdoodle8/Galacticraft/issues/1618

**Comment by KingLemming** [comment]
The issue here is in the canisters. The Transposer works with literally every other IFluidHandler in the game.
