### ISSUE TITLE
[1.12] Thermal Expansion - Missing Smelting Recipes for TE Aluminum & TE Iridium ore/dust

### ISSUE THREAD

**Issue by llloyd4** [CoFH/Feedback#474]
So, I was talking to the Mekanism team as their Smelter doesn't accept TE Aluminum and TE Iridium dusts / ores (along with a bunch of other mod ores / dusts) and they pointed out there is no smelting recipe for either of these. And, sure as **** there isn't, JEI only shows the Redstone Furnace and Induction Smelter and no other, vanilla or otherwise, smelting recipes. O.o

**Comment by KingLemming** [comment]
Working as intended.

**Comment by llloyd4** [comment]
So you don't want no vanilla furnace and/or other mod smelting Iridium and
Aluminum? O.o ​Ok...

**Comment by covers1624** [comment]
Those ores were added for pack devs that wanted to unify ores, fairly certain we have no intensions of adding any recipes for them as they are meant to be added via craft tweaker.

**Comment by llloyd4** [comment]
Ok. Then I'll go poke at the Unstable team as those are enabled for world
gen in Unstable 1.12. >.<

**Comment by KingLemming** [comment]
That isn't it. It's that aluminum and iridium aren't simple to smelt. Hence, the basic furnace shouldn't be able to do it.

Mods which add those metals typically have special ways to smelt them. If we added them to the basic furnace, that would be a balance issue.

**Comment by llloyd4** [comment]
Except TC which just uses the smeltry powered by lava?
