### ISSUE TITLE
Minefactory Reloaded error

### ISSUE THREAD

**Issue by 31trainman** [CoFH/Feedback#474]
I'm getting this strange error printed in my console when starting up a custom modpack im building.
Here's the link to a paste bin of the error: http://pastebin.com/UPHNyPVn
I'm using Multimc to test it.

Minefactory Reloaded version 2.8.0.104   All mods are up to date unless a new version comes out etc.
[
COFH Core v3.0.2-262
CoFHLib v1.0.1-151
ThermalDynamics v1.0.0-122
ThermalExpansion v4.0.1-182
ThermalFoundation v1.0.0-81
[
Forge 1391
Java 8 update 45 64bit
win 7 64 bit

Other mods used
AdvancedSolarPanels 3.5.1
appliedenergistics 2 rv2-beta-8
BetterFoliage 10
BiomesOPlenty 1237
Bloodmagic 1.3.2.1
Botania r1.6-183
CodechickenCore-1.0.4.29
DynamicTransport-0.1.2.0
Enchiridon-1.2b
ExtraCells 69bNIGHTLY
Farseek-1.0.5
Fastcraft-1.21
ForbiddenMagic-0.562
Highlands v 2.2.3
Industrialcraft2 v718
IntelligentEnergistics v2.1.4.553
MaricultureDeluxe-1.2.4.2a
NotenoughItems-1.0.3.74
Planetguylib-1.5
RemainInmotion-2.5.4
RWG-alpha-1.3.2
SlimevoidLibrary-2.0.4.7
Streams-0.1.4
Thaumcraft-4.2.3.5
thaumicenergistics-0.8.9.1b-rv2
ThaumicInfusion-3.966
ThaumicTinkerer-2.5
ZoranoDenshav0.7

**Comment by KingLemming** [comment]
Highlands is causing that, not MFR.

**Comment by 31trainman** [comment]
ah ok, il get this over to the highlands dev then, Thanks for the input KingLemming.
