### ISSUE TITLE
[1.12] Inconsistency between ThermalExpansionHelper and IMCHandler

### ISSUE THREAD

**Issue by DarkMorford** [CoFH/Feedback#475]
I would like to add a Fluid in a mod I'm developing as a fuel for Thermal Expansion's Compression Dynamo. I've tried using `cofh.api.util.ThermalExpansionHelper#addCompressionFuel` to do so, but I wind up getting a warning message about an invalid IMC.

It appears that `addCompressionFuel` sends an IMC with the key string "CompressionFuel". On the other end of the exchange, `cofh.thermalexpansion.util.IMCHandler#handleIMC` is checking for the string "addcompressionfuel". This mismatch causes `handleIMC` to fall through to the warning statement, and the fuel addition fails.

A similar mismatch between these two classes will cause `ThermalExpansionHelper#addMagmaticFuel` to fail, as `handleIMC` is expecting to receive "addmagmaticfuel" but will instead get "MagmaticFuel". I'll also note that `handleIMC` does not appear to have support for adding coolants or Reactant Dynamo reactions at all, and the handler for "addcentrifugerecipe" seems to be a no-op.

**Comment by KingLemming** [comment]
Honestly that helper isn't super high priority, nor is IMC in general.

If you're writing your own mod though, you can always just write your own IMC and not rely on that helper class.

**Comment by KingLemming** [comment]
Fixed in dev, although more of "resolved," honestly.

Centrifuge recipes can be removed, but not added. I've trimmed the list of valid IMCs a bit as well. I'd like to add a more proper json based system, but will see about supporting this.

You are welcome of course to PR adjustments. ;)
