### ISSUE TITLE
Phytogenic Insolator + Thermal Dynamics itemducts crash

### ISSUE THREAD

**Issue by Cherry** [CoFH/Feedback#475]
> "This is what happened when I was changing the input for the seeds and Phyto-Gro to the side input of the Phytogenic Insolator configuration tab. This happens with any Item Ducts from Thermal Dynamics attached to the side of this particular machine and happens also right after passing the filter color purple. ~GeekTechMedia"

Quick steps to reproduce:

1. Place pyhtogenic insolator
2. Place any TD Itemduct on the left
3. Open machine config UI and cycle through the left side config until crash. Crash generally happens after "purple" colour.

Crash report: http://pastebin.com/C2TgQL8g (happens continuously until removing the duct from the world via something like MCEdit)

Other observations:

* Buildcraft pipes don't crash, however don't really appear to function, either.
* ExU transfer nodes/pipes also cause a similar crash: http://pastebin.com/5JG33i5T
* As do EnderIO item conduits: http://pastebin.com/A22WKdzF

CoFH mod versions (latest stable releases):

* CoFHCore: 3.0.2-262
* ThermalFoundation: 1.0.0-81
* ThermalExpansion: 4.0.1-182
* ThermalDynamics: 1.0.0-122

**Comment by KingLemming** [comment]
I figured I'd miss one of them. :)

**Comment by thelonster** [comment]
How does one edit the world file using mcedit?
