### ISSUE TITLE
[1.12] Glass Panes connect to Ducts and Dynamos

### ISSUE THREAD

**Issue by Tonius** [CoFH/Feedback#476]
As seen here: ![](http://i.imgur.com/2ImuFNC.png)

Other non-opaque blocks in the mods might do this as well.

**Comment by KingLemming** [comment]
Hmm. Is this not actually a bug in panes then?

**Comment by Tonius** [comment]
As of 1.12, fences, walls, panes and bars connect to the backs or 'solid sides' of stairs. I heard somewhere that a new method was introduced for blocks to tell which sides are to be considered 'solid' for this. I haven't looked at the code myself though.

**Comment by KingLemming** [comment]
Fixed in dev, but frankly this should be a Forge-level fix. Kind of annoying.
