### ISSUE TITLE
[1.12.x] Redstone Furnace ignoring CraftTweaker 2 Furnace Recipes

### ISSUE THREAD

**Issue by oitsjustjose** [CoFH/Feedback#478]
So, this is a pretty minor issue, but I'm sure someone else would've found it if I hadn't. In essence, the Redstone Furnace seems to be grabbing from the vanilla Furnace recipelist before CraftTweaker has had a chance to modify it.

The code handling your recipe registration looks a little complex (understandably so), so I don't know how easy it'd be to just "put it off til later in Game Registration", so I'm not sure if it would *actually* be easier for Jared to tap into the TE API to update the changes in recipes itself (if there is an API plugin for the Redstone Furnace in the first place, since it's usually a "typical smelter").

### Versions:

Minecraft: 1.12.x (experienced on 1.12 and 1.12.1)
CoFH Core: 4.3.4.12
Thermal Expansion 5.3.4.16

### Details:

Here's an instance where I removed this recipe from smelting, and added another one using the same item. This image is what's supposed to work (and does in all other furnaces):

![2017-08-16_08 44 59](https://user-images.githubusercontent.com/3887324/29363924-c1765598-825f-11e7-8d40-aaa192822da1.png)

However Actually Additions' original recipe (removed by CraftTweaker 2) still persists in the Redstone Furnace:

![2017-08-16_08 45 02](https://user-images.githubusercontent.com/3887324/29363939-d25451b2-825f-11e7-99af-22b123bdeab2.png)

Lastly, this recipe was removed altogether but still persists as well:

![2017-08-16_08 45 18](https://user-images.githubusercontent.com/3887324/29363946-db75afe8-825f-11e7-8eb4-d851ceb17b04.png)

Let me know if there is anything else I can do / any more info I can provide!

**Comment by KingLemming** [comment]
That's just how it works. We literally can't put it off until later, sorry. It's something I can hash out with CraftTweaker when I get back from vacation, but it's not something we can address on our end.
