### ISSUE TITLE
CoFH Core/CodeChickenLib crash

### ISSUE THREAD

**Issue by WJ44** [CoFH/Feedback#48]
modlist: http://pastebin.com/irxy7709
using forge 10.13.2.1291
crash log: http://pastebin.com/TsgRfGRF

After starting the game, when the main menu pops up, it crashes after about half a second.
It does not crash with only CoFHCore and CodeChickenCore installed.

EDIT:
It seems to happen as long as CodeChickenCore, CoFHCore and WirelessRedstone-CBE are installed

**Comment by skyboy** [comment]
This is an issue unrelated to CoFHCore, report it to WR-CBE.
