### ISSUE TITLE
[1.12 v5.3.4.16] Compression Dynamo graphical bug

### ISSUE THREAD

**Issue by VallenFrostweaver** [CoFH/Feedback#480]
As seen below the little flames do not render on this machine for people to find and click the recipe like others do.
![18-08-17 10-16-56 am](https://user-images.githubusercontent.com/13642054/29452586-c3519846-83fe-11e7-97b7-7269ed2f94db.png)

If you need more information like my mod list let me know.

**Comment by KingLemming** [comment]
On vacation so haven't confirmed yet, but wouldn't surprise me. :) Should be an easy fix.

**Comment by VallenFrostweaver** [comment]
Enjoy your vacation! :D

**Comment by KingLemming** [comment]
Hrm. Actually not so simple since the flames aren't actually intended to be rendered on the fluid-using dynamos.

So it'll be a redesign somehow.

**Comment by VallenFrostweaver** [comment]
Just realized the Magmatic Dynamo has the same thing going on. FYI

**Comment by KingLemming** [comment]
Yeah, handled that too. ;)
