### ISSUE TITLE
[1.12] TE Buff Ingition Plugs

### ISSUE THREAD

**Issue by KaseiFR** [CoFH/Feedback#481]
Hi,

As far as I understand, the Ignition Plugs augments have been made obsolete by the new boiler augments: even with the latest rebalance change the steam way has a final efficiency of 180%, compared to 150% for the Ignition Plugs.  
On the plus side, it takes one dynamos less (and that many upgrades) and it easier to control/throttle than steam. It remains a little harder to get than the boiler augments, since it requires signalum and pyrotheum.  
I would propose to buff the Ignition Plugs so they stay relevant (at least on par with steam, including the efficiency augments which get doubled).

**Comment by KingLemming** [comment]
I'll double check your math, but all things considered you just pointed out a whole lot of reasons that plugs still offer a viable path.

**Comment by KingLemming** [comment]
I've adjusted some numbers. I haven't mathed it out to ensure that plugs are "better" now, but frankly the initial premise that something is "obsolete" just because it's not absolutely optimal or perfect is a false equivalency which is one of the worst things about modded Minecraft.
