### ISSUE TITLE
[1.12.x] Binnie's mods compatibility

### ISSUE THREAD

**Issue by Skillotic0703** [CoFH/Feedback#482]
- [x] Comb Processing in Centrifuge

- [x] Squeezer Recipes

- [x] Juice compatibility because Binnie's mods actually has a fluid for each fruit juice instead of a random 'fruit juice' fluid. I thought that you could maybe add a way to get these juices with Thermal Expansion machines.

- [ ] Maybe sapling compatibility in the phytogenic insolator if it's possible

**Comment by KingLemming** [comment]
Binnie's mods are still sort of buggy on 1.12, so this is more of a roadmap thing. I have skeleton files ready to go, but I won't be adding serious support until a lot of the basic bugs are worked out.

**Comment by KingLemming** [comment]
Comb Processing is done, except for the double-x-mod ones.

I'm admittedly a little iffy on the various fruit juices though. Really not sure if I want to do those.

Saplings aren't possible at the moment and there's a fair chance they will not be.

**Comment by KingLemming** [comment]
Juice extraction is handled in the Centrifuge - the Transposer emulates the Squeezer instead.

Distillation is handled in the Fractionating Still, but it's considerably more expensive. Also, there's no way to create Wine in Binnie's at this time so that's sort of a dead end for now. :)

**Comment by Skillotic0703** [comment]
Thank you a lot. It's so bad for wine ;)
