### ISSUE TITLE
[1.12] All the Mods pack and Steam turbine augment

### ISSUE THREAD

**Issue by EvilBastard** [CoFH/Feedback#483]
Today I've been trying to get steam to go into my steam turbines with the turbine augment in them. I am producing steam, from both a boiler augment and even from an extreme reactor.  The problem I'm having is getting the steam to go into the steam dynamo with the turbine augment. 

I am using hardened fluid ducts to connect it all together.   I've already tried wrenching them around, removing and replacing them as well.

![image](https://user-images.githubusercontent.com/24449157/29489596-5f0061b4-84ea-11e7-80d9-8076f4f5aded.png)

![image](https://user-images.githubusercontent.com/24449157/29489605-9f59096e-84ea-11e7-9381-cbbb13ef74f0.png)

**Comment by KaseiFR** [comment]
Weird. I'm playing ATM 3 v2.8 (TE 5.3.3.15) and I have no issue:
![v3](https://i.imgur.com/LMW9GRx.png)
Given your turbine icon, you play the v3.0 release, but I have no problem either:
![v3.0](https://i.imgur.com/5AVxnKA.png)

Could you show your whole setup ?

**Comment by EvilBastard** [comment]
My whole setup was an AC putting water into the steam boiler, and then hardened ducts into the steam turbine.  I seem to have found the problem. My world file itself.  I started a new world to test in, cheated things in and it worked perfectly fine.   Seems I'm just going to have to start up a whole new world file.

**Comment by benstreb** [comment]
Wait, wait, wait. Your steam dynamos don't accept steam, even with the augment. My steam dynamos don't accept steam either. This is still an open bug, even if you can work around it by restarting the world.

**Comment by KingLemming** [comment]
Check and make sure that the right Steam is being registered in the "bugged" worlds. I'm betting it isn't, and this is fundamentally an xmod issue, with the other mod not handling things right. (TF does handle things properly, but the nature of the Forge fluid issues means that ALL mods have to)

**Comment by KingLemming** [comment]
Sorry guys, but this isn't on us. I looked over the code - we are properly reassigning fluid registrations on world load. If it doesn't work after that, it's the fault of another mod doing things incorrectly.

Worlds can be fixed using NBT editing, but this is ultimately the result of Forge's fluid system.

**Comment by benstreb** [comment]
I did have another source of steam taking precedence. I disabled the other steam source and it worked in a fresh world, but that alone wasn't enough to fix the issue on the server I'm on. Is there something else I'd need to do to make it work, or will it take a server reset to fix?

**Comment by benstreb** [comment]
At the very least, since this isn't your issue, is there a place we can get some assistance on a fix?
