### ISSUE TITLE
CoFHTweaks 0.1.0B1-23 [Client and Server] Chunks flat-out refused to load

### ISSUE THREAD

**Issue by EnigmaticaGH** [CoFH/Feedback#485]
So I just installed this on my client as well as my server for testing. I went far away to unexplored lands to test server load during fast chunk demands. This worked fine although my TPS did tank, it wasn't nearly as bad as before.

Well I'm on my way back, using a slightly different path to get home, and as I'm flying in my top tier jetpack (i.e. moving really really fast), new unexplored chunks can't load fast enough to keep up with me but I keep flying. I figure I'll test the server load again. Well I get back home and the chunks just refused to load. Server TPS isn't impacted according to CoFHCore, although my server did spam some "Can't keep up!" messages, presumably when I was flying back.

Screenshot of chunks not loading (oddly enough, some tileEntities did manage to render): https://dl.dropboxusercontent.com/u/10679993/Photos/Minecraft/2015-05-01_10.55.47.png

Also, during this, I was not able to interact with any items on me. Examples like turning on/off hover mode on my Jetpack, changing teleport locations on my Charm of Dislocation, etc but I can open my Backpacks and move items around and such.

**Comment by skyboy** [comment]
I think what happened to you was that you flew into a tree or building on your way back, but that structure hadn't been loaded yet (a danger of flying faster than chunks load), and so the server never sent those chunks to you - it thought you were several hundred blocks elsewhere. If this is what happened to you, it had nothing to do with tweaks, this is just an issue with moving really fast in minecraft.

**Comment by skyboy** [comment]
Anything further to report?

**Comment by EnigmaticaGH** [comment]
On v24, chunks and stuff would stop loading after a short while, and the only solution was to completely restart the client. Not sure if it's fixed in the newer versions. I'll give them a try after my finals.

**Comment by skyboy** [comment]
Assuming this is fixed, or otherwise the vanilla bug was encountered.
