### ISSUE TITLE
Client crashing to desktop servo/

### ISSUE THREAD

**Issue by Renadarain** [CoFH/Feedback#485]
Hi :)

Something is going pear shaped when connecting the pipes to either the Furnus or the Pulvus - not sure if its a problem here or with the Furnus mod.  Just thought I'd check here first.

MC: 1.12.1
Forge: forge-1.12.1-14.22.0.2456
CoFH Core: 1.12-4.3.4.12-universal
CoFH World: 1.12-1.0.1.8-universal
Redstone Flux: 1.12-2.0.1.2-universal
Thermal Expansion:  1.12-5.3.4.16-universal
Thermal Foundation: 1.12-2.3.4.13-universal
Thermal Dynamics: 1.12-2.3.4.11-universal
Thermal Cultivation: 1.12-0.1.0.5-universal

https://pastebin.com/n3ZvZqaL

Regards,
Renada

**Comment by KingLemming** [comment]
Seems to be on the Furnus from what I can tell.

**Comment by Renadarain** [comment]
@KingLemming  Thanks for looking, I'll toddle off to them :)

Regards,
Renada
