### ISSUE TITLE
[1.12] Items Copy Bug for Thermal Foundation with Forestry mod

### ISSUE THREAD

**Issue by Flithor** [CoFH/Feedback#486]
If you craft advanced materials with canned liquid of Forestry mod, the rest of items will be copied.
Specific operation:
1. Prepare multiple canned liquid and stack them.
2. Put other materials(multiple each) in craft GUI.
3. Put one canned liquid in craft GUI.
![ScreenShot](http://imgur.com/ZoYdYKB.png)
(All similar recipes will trigger this bug)
4. Stack the rest canned liquid in craft GUI.
![ScreenShot](http://imgur.com/8BtlOEe.png)
5. Craft!!
6. The rest of materials doubled!
![ScreenShot](http://imgur.com/IJrgxSH.png)
![ScreenShot](http://imgur.com/dFZdUr8.png)

Pls fix it soon!
========================================
(Due to this bug, I almost want to delete this world archive.)

And in these recipes, the can will be consumed (not return empty can). But these recipes should only consume liquid.
(Maybe a bug?)

Orignal:[https://github.com/ForestryMC/ForestryMC/issues/1820](https://github.com/ForestryMC/ForestryMC/issues/1820)
The Forestry mod developer said it's CoFH Core's bug.

**Comment by KingLemming** [comment]
Go ahead and delete your world then. I have no evidence of this happening and frankly I don't know if it's actually on our end or not.

Dupe bugs by nature are kind of low priority, like it or not. They aren't game critical.

**Comment by Flithor** [comment]
I tried IC2 mod liquid container, also trigger this bug... so...
![ScreenSort](http://imgur.com/wNbiFPp.png)

**Comment by KingLemming** [comment]
Provide a video please. Screenshots of this aren't clear and offhand there's literally nothing in the code that suggests this can happen - it's almost exactly like the underlying Forge code.

**Comment by Flithor** [comment]
![Bug](http://imgur.com/a/U0qhZ)
@KingLemming

**Comment by KingLemming** [comment]
This is actually a much deeper issue. You'll notice that if you try putting a stack of cans directly in, there is no output (that's because the stack of cans doesn't know how to process itself as holding fluids).

The recipe correctly checks for a valid fluid holder - a *single* can. And it processes that single can accordingly.

The problem is that when the stacksize of the can is updated, the game doesn't properly update the recipe. This is a much more fundamental issue.

**Comment by KingLemming** [comment]
Talked with @mezz and we figured out a resolution for this. There is still some really weird stuff going on at a much lower level though.
