### ISSUE TITLE
Strange Crash with COFH Tweaks B1-24

### ISSUE THREAD

**Issue by SJ1133** [CoFH/Feedback#486]
The game refuses to load and crashes. No fastcraft or optifine

http://pastebin.com/Mkr2wXHb

**Comment by skyboy** [comment]
This crash isn't caused by tweaks - the class generating the error isn't even touched. I have no idea which of your other mods may be causing it, either.

**Comment by SJ1133** [comment]
Thats intresting cause when i remove COFH Tweaks everything works as normal?

**Comment by KingLemming** [comment]
That doesn't mean it's the cause though. Hypothetically, somebody could have a mod that looks for another mod and crashes if it sees it.

That isn't happening here directly, but something along those lines is. Tweaks might do something another mod doesn't like, and *that* mod is crashing.

**Comment by SJ1133** [comment]
Ah i see. Will try and test to see what mod it is
