### ISSUE TITLE
[TD] Issues rendering cover version of some blocks.

### ISSUE THREAD

**Issue by JonasCiss** [CoFH/Feedback#487]
~I got this error several times and the game crashed.~

~java.lang.NullPointerException: Tessellating CCL block in world
	at net.minecraftforge.client.model.pipeline.BlockInfo.updateLightMatrix(BlockInfo.java:124)~
	~at net.minecraftforge.client.model.pipeline.VertexLighterSmoothAo.updateBlockInfo(VertexLighterSmoothAo.java:186)~
	~at cofh.thermaldynamics.duct.attachments.cover.CoverRenderer.renderBlockQuads(CoverRenderer.java:69)~
	~at cofh.thermaldynamics.duct.attachments.cover.CoverRenderer.renderBlockCover(CoverRenderer.java:140)~
	~at cofh.thermaldynamics.duct.attachments.cover.Cover.render(Cover.java:119)~
	~at cofh.thermaldynamics.render.RenderDuct.renderBlock(RenderDuct.java:387)~
	~at codechicken.lib.render.block.BlockRenderingRegistry.renderBlock(BlockRenderingRegistry.java:94)~
	~at codechicken.lib.render.block.CCBlockRendererDispatcher.func_175018_a(CCBlockRendererDispatcher.java:53)~
	~at mods.betterfoliage.client.Hooks.renderWorldBlock(Hooks.kt:95)~
	~at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:293)~
	~at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(ChunkRenderWorker.java:119)~
	~at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(ChunkRenderWorker.java:47)~
	~at java.lang.Thread.run(Unknown Source)~

[crash-2017-08-22_09.13.04-client.txt](https://github.com/TheCBProject/NotEnoughItems/files/1241915/crash-2017-08-22_09.13.04-client.txt)

**Comment by KingLemming** [comment]
CCL error. Please report on that repo.

**Comment by JonasCiss** [comment]
Where can I found that page? If I click on the issues button at curseforge I will redirected to this page.?

**Comment by covers1624** [comment]
This is actually a valid issue, seems the cover renderer doesn't like some blocks, Reopening, this will be fixed with the model rewrite to TD.
