### ISSUE TITLE
[1.12.1]  Crash after world load with Thermal Expansion (forge 2459)

### ISSUE THREAD

**Issue by Littlebugg** [CoFH/Feedback#488]
Game crashes after world load. removing TE fixes it.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  Inventory Tweaks Coremod (InventoryTweaks-1.63+beta.108.jar)
  ForgelinPlugin (Forgelin-1.5.1.jar)
  AppleCore (AppleCore-mc1.12.1-2.2.2.jar)
  TransformerLoader (OpenComputers-MC1.12.1-1.7.0.4.jar)
  CoreMod (Aroma1997Core-1.12-1.3.0.0.b103.jar)
  IELoadingPlugin (ImmersiveEngineering-0.12-70.jar)
  CTMCorePlugin (CTM-MC1.12-0.2.2.7.jar)
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
  LoadingPlugin (RandomThings-MC1.12.1-4.0.5.jar)
Contact their authors BEFORE contacting forge

// Ooh. Shiny.

Time: 8/22/17 11:24 AM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:94)
	at codechicken.lib.render.block.CCBlockRendererDispatcher.func_175018_a(CCBlockRendererDispatcher.java:60)
	at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:200)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:100)
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.func_178505_b(ChunkRenderDispatcher.java:172)
	at net.minecraft.client.renderer.RenderGlobal.func_174970_a(RenderGlobal.java:976)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1311)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1254)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1057)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:94)
	at codechicken.lib.render.block.CCBlockRendererDispatcher.func_175018_a(CCBlockRendererDispatcher.java:60)
	at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:200)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:100)
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.func_178505_b(ChunkRenderDispatcher.java:172)
	at net.minecraft.client.renderer.RenderGlobal.func_174970_a(RenderGlobal.java:976)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1311)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1254)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['zeta70'/189, l='MpServer', x=297.44, y=80.00, z=-444.29]]
	Chunk stats: MultiplayerChunkCache: 169, 169
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (243,64,314), Chunk: (at 3,4,10 in 15,19; contains blocks 240,0,304 to 255,255,319), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 779258 game time, 926449 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 60 total; [EntityBat['Bat'/258, l='MpServer', x=280.82, y=16.10, z=-409.36], EntityBat['Bat'/259, l='MpServer', x=272.71, y=12.35, z=-397.88], EntitySquid['Squid'/260, l='MpServer', x=283.40, y=62.54, z=-387.06], EntityPig['Pig'/265, l='MpServer', x=292.55, y=80.00, z=-504.49], EntityPig['Pig'/266, l='MpServer', x=291.87, y=74.32, z=-486.87], EntityPig['Pig'/267, l='MpServer', x=299.05, y=75.00, z=-490.60], EntityBat['Bat'/272, l='MpServer', x=314.53, y=21.17, z=-485.32], EntityPig['Pig'/273, l='MpServer', x=317.78, y=109.00, z=-411.51], EntityPig['Pig'/282, l='MpServer', x=328.63, y=94.00, z=-499.75], EntityPig['Pig'/283, l='MpServer', x=327.48, y=95.00, z=-500.25], EntityPig['Pig'/284, l='MpServer', x=327.05, y=90.00, z=-494.54], EntityPig['Pig'/285, l='MpServer', x=327.55, y=88.00, z=-493.09], EntityPig['Pig'/286, l='MpServer', x=332.08, y=107.00, z=-408.06], EntityPig['Pig'/287, l='MpServer', x=328.78, y=107.00, z=-406.51], EntityLlama['Llama'/300, l='MpServer', x=347.50, y=117.00, z=-511.50], EntityPig['Pig'/301, l='MpServer', x=339.18, y=108.00, z=-412.74], EntityPig['Pig'/302, l='MpServer', x=342.51, y=87.00, z=-394.22], EntityCow['Cow'/303, l='MpServer', x=348.47, y=79.00, z=-369.19], EntityCow['Cow'/306, l='MpServer', x=346.38, y=71.00, z=-366.82], EntityCow['Cow'/307, l='MpServer', x=346.55, y=72.00, z=-367.92], EntityPig['Pig'/309, l='MpServer', x=362.69, y=88.00, z=-400.66], EntityPig['Pig'/310, l='MpServer', x=364.33, y=86.00, z=-394.26], EntityPig['Pig'/311, l='MpServer', x=353.88, y=89.00, z=-394.55], EntityPig['Pig'/312, l='MpServer', x=355.68, y=82.00, z=-379.23], EntityCow['Cow'/313, l='MpServer', x=362.17, y=80.00, z=-374.61], EntityBat['Bat'/314, l='MpServer', x=362.31, y=48.20, z=-367.04], EntityItem['item.item.death_info'/187, l='MpServer', x=300.08, y=79.00, z=-449.32], EntityCow['Cow'/315, l='MpServer', x=364.15, y=90.00, z=-367.46], EntityPig['Pig'/188, l='MpServer', x=280.50, y=79.00, z=-479.72], EntityPlayerSP['zeta70'/189, l='MpServer', x=297.44, y=80.00, z=-444.29], EntityBat['Bat'/321, l='MpServer', x=373.21, y=35.08, z=-420.59], EntityBat['Bat'/322, l='MpServer', x=371.16, y=33.19, z=-417.97], EntityCow['Cow'/323, l='MpServer', x=373.15, y=81.00, z=-391.43], EntityCow['Cow'/324, l='MpServer', x=373.64, y=83.00, z=-370.18], EntityPig['Pig'/325, l='MpServer', x=372.75, y=81.00, z=-373.82], EntityCow['Cow'/326, l='MpServer', x=368.51, y=85.00, z=-370.60], EntityPig['Pig'/327, l='MpServer', x=368.49, y=86.00, z=-369.45], EntityPig['Pig'/328, l='MpServer', x=370.88, y=80.00, z=-378.81], EntityCow['Cow'/329, l='MpServer', x=375.69, y=83.00, z=-366.46], EntityPig['Pig'/227, l='MpServer', x=238.70, y=77.00, z=-517.57], EntityPig['Pig'/228, l='MpServer', x=230.46, y=91.00, z=-449.79], EntityChicken['Chicken'/229, l='MpServer', x=237.50, y=93.00, z=-450.18], EntityPig['Pig'/230, l='MpServer', x=231.46, y=90.00, z=-452.97], EntityItem['item.item.egg'/231, l='MpServer', x=239.17, y=92.00, z=-451.37], EntityPig['Pig'/232, l='MpServer', x=239.73, y=91.00, z=-454.45], EntityPig['Pig'/233, l='MpServer', x=233.32, y=91.00, z=-444.84], EntityChicken['Chicken'/234, l='MpServer', x=234.91, y=92.00, z=-446.80], EntityItem['item.item.egg'/235, l='MpServer', x=235.17, y=92.00, z=-446.88], EntityPig['Pig'/241, l='MpServer', x=242.20, y=92.00, z=-450.60], EntityPig['Pig'/242, l='MpServer', x=241.75, y=92.00, z=-448.51], EntitySquid['Squid'/243, l='MpServer', x=246.66, y=62.51, z=-418.65], EntityBat['Bat'/244, l='MpServer', x=252.83, y=34.54, z=-412.41], EntitySquid['Squid'/245, l='MpServer', x=249.40, y=59.00, z=-414.40], EntityPig['Pig'/249, l='MpServer', x=261.75, y=80.00, z=-461.70], EntityBat['Bat'/250, l='MpServer', x=270.83, y=19.28, z=-403.54], EntitySquid['Squid'/251, l='MpServer', x=261.50, y=61.83, z=-412.97], EntitySquid['Squid'/252, l='MpServer', x=267.40, y=59.69, z=-409.40], EntityBat['Bat'/253, l='MpServer', x=266.51, y=12.72, z=-388.70], EntityBat['Bat'/254, l='MpServer', x=268.56, y=12.00, z=-389.29], EntityPig['Pig'/255, l='MpServer', x=271.71, y=64.00, z=-375.63]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:415)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2748)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:426)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.1
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1865537312 bytes (1779 MB) / 4221042688 bytes (4025 MB) up to 5726797824 bytes (5461 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6144m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 7, allocated: 20, tallocated: 86
	FML: MCP 9.41 Powered by Forge 14.22.0.2458 85 mods loaded, 85 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	minecraft{1.12.1} [Minecraft] (minecraft.jar) 
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.12.1-14.22.0.2458.jar) 
	UCHIJAAAA	forge{14.22.0.2458} [Minecraft Forge] (forge-1.12.1-14.22.0.2458.jar) 
	UCHIJAAAA	aroma1997core{1.3.0.0.b103} [Aroma1997Core] (Aroma1997Core-1.12-1.3.0.0.b103.jar) 
	UCHIJAAAA	ivtoolkit{1.3.3-1.12} [IvToolkit] (minecraft.jar) 
	UCHIJAAAA	opencomputers|core{1.7.0.4} [OpenComputers (Core)] (minecraft.jar) 
	UCHIJAAAA	actuallyadditions{1.12-r118} [Actually Additions] (ActuallyAdditions-1.12-r118.jar) 
	UCHIJAAAA	applecore{2.2.2} [AppleCore] (AppleCore-mc1.12.1-2.2.2.jar) 
	UCHIJAAAA	jei{4.7.5.88} [Just Enough Items] (jei_1.12.1-4.7.5.88.jar) 
	UCHIJAAAA	appleskin{1.0.7} [AppleSkin] (AppleSkin-mc1.12-1.0.7.jar) 
	UCHIJAAAA	aroma1997corehelper{1.3.0.0.b103} [Aroma1997Core|Helper] (Aroma1997Core-1.12-1.3.0.0.b103.jar) 
	UCHIJAAAA	aroma1997sdimension{1.3.0.0.b37} [Aroma1997's Dimensional World] (Aroma1997s-Dimensional-World-1.12-1.3.0.0.b37.jar) 
	UCHIJAAAA	bdlib{1.14.1.6} [BD Lib] (bdlib-1.14.1.6-mc1.12.jar) 
	UCHIJAAAA	bedbugs{@VERSION@} [Bed Bugs] (BedBugs-1.12-1.0.1.jar) 
	UCHIJAAAA	bookshelf{2.0.424} [Bookshelf] (Bookshelf-1.12.1-2.0.0.424.jar) 
	UCHIJAAAA	codechickenlib{3.1.1.288} [CodeChicken Lib] (CodeChickenLib-1.12-3.1.1.288-universal.jar) 
	UCHIJAAAA	redstoneflux{2.0.1} [Redstone Flux] (RedstoneFlux-1.12-2.0.1.2-universal.jar) 
	UCHIJAAAA	brandonscore{2.3.2} [Brandon's Core] (BrandonsCore-1.12-2.3.2.129-universal.jar) 
	UCHIJAAAA	chisel{MC1.12-0.0.13.16} [Chisel] (Chisel-MC1.12-0.0.13.16.jar) 
	UCHIJAAAA	mantle{1.12-1.3.1.18} [Mantle] (Mantle-1.12-1.3.1.18.jar) 
	UCHIJAAAA	tconstruct{1.12-2.7.2.19} [Tinkers' Construct] (TConstruct-1.12-2.7.2.19.jar) 
	UCHIJAAAA	ceramics{1.12-1.3.2} [Ceramics] (Ceramics-1.12-1.3.2.jar) 
	UCHIJAAAA	chameleon{1.12-4.1.3} [Chameleon] (Chameleon-1.12-4.1.3.jar) 
	UCHIJAAAA	chiselsandbits{14.6} [Chisels & Bits] (chiselsandbits-14.6.jar) 
	UCHIJAAAA	cofhcore{4.3.4} [CoFH Core] (CoFHCore-1.12-4.3.4.12-universal.jar) 
	UCHIJAAAA	cofhworld{1.0.1} [CoFH World] (CoFHWorld-1.12-1.0.1.8-universal.jar) 
	UCHIJAAAA	cyclopscore{0.10.13} [Cyclops Core] (CyclopsCore-1.12-0.10.13.jar) 
	UCHIJAAAA	commoncapabilities{1.4.0} [CommonCapabilities] (CommonCapabilities-1.12-1.4.0.jar) 
	UCHIJAAAA	cookingforblockheads{6.3.6} [Cooking for Blockheads] (CookingForBlockheads_1.12.1-6.3.6.jar) 
	UCHIJAAAA	crafttweaker{4.0.4} [CraftTweaker2] (CraftTweaker2-1.12-4.0.4.jar) 
	UCHIJAAAA	ctgui{1.0.0} [CT-GUI] (CraftTweaker2-1.12-4.0.4.jar) 
	UCHIJAAAA	crafttweakerjei{2.0.0} [CraftTweaker JEI Support] (CraftTweaker2-1.12-4.0.4.jar) 
	UCHIJAAAA	ctm{MC1.12-0.2.2.7} [CTM] (CTM-MC1.12-0.2.2.7.jar) 
	UCHIJAAAA	draconicevolution{2.3.3} [Draconic Evolution] (Draconic-Evolution-1.12-2.3.3.261-universal.jar) 
	UCHIJAAAA	embers{0.221} [Embers] (embers-0.221.jar) 
	UCHIJAAAA	valkyrielib{1.12-2.0.1a} [Valkyrie Lib] (valkyrielib-1.12-2.0.1a.jar) 
	UCHIJAAAA	environmentaltech{1.12-2.0.1a} [Environmental Tech] (environmentaltech-1.12-2.0.1a.jar) 
	UCHIJAAAA	forestry{5.5.0.171} [Forestry] (forestry_1.12.1-5.5.0.171.jar) 
	UCHIJAAAA	farmingforblockheads{3.1.3} [Farming for Blockheads] (FarmingForBlockheads_1.12-3.1.3.jar) 
	UCHIJAAAA	fastleafdecay{v14} [Fast Leaf Decay] (FastLeafDecay-v14.jar) 
	UCHIJAAAA	forgelin{1.5.1} [Shadowfacts' Forgelin] (Forgelin-1.5.1.jar) 
	UCHIJAAAA	ftbl{0.0.0} [FTBLib] (FTBLib-4.0.5.jar) 
	UCHIJAAAA	ftbu{0.0.0} [FTBUtilities] (FTBUtilities-4.0.3.jar) 
	UCHIJAAAA	gendustry{1.6.5.4} [GenDustry] (gendustry-1.6.5.4-mc1.12.jar) 
	UCHIJAAAA	thermalfoundation{2.3.4} [Thermal Foundation] (ThermalFoundation-1.12-2.3.4.13-universal.jar) 
	UCHIJAAAA	thermalexpansion{5.3.4} [Thermal Expansion] (ThermalExpansion-1.12-5.3.4.16-universal.jar) 
	UCHIJAAAA	advgenerators{0.9.20.4} [Advanced Generators] (generators-0.9.20.4-mc1.12.jar) 
	UCHIJAAAA	gravestone{1.9.0} [Gravestone Mod] (gravestone-1.9.0.jar) 
	UCHIJAAAA	hammercore{1.9.4.0} [Hammer Core] (HammerCore-1.12-1.9.4.0.jar) 
	UCHIJAAAA	waila{1.8.20} [Waila] (Hwyla-1.8.20-B35_1.12.jar) 
	UCHIJAAAA	immersiveengineering{0.12-70} [Immersive Engineering] (ImmersiveEngineering-0.12-70.jar) 
	UCHIJAAAA	immersivepetroleum{1.1.3} [Immersive Petroleum] (immersivepetroleum-1.12-1.1.3.jar) 
	UCHIJAAAA	teslacorelib{1.0.7} [Tesla Core Lib] (tesla-core-lib-1.12-1.0.7.jar) 
	UCHIJAAAA	industrialforegoing{1.2-1.1.1} [Industrial Foregoing] (industrialforegoing-1.12-1.1.1-33.jar) 
	UCHIJAAAA	integrateddynamics{0.8.5} [Integrated Dynamics] (IntegratedDynamics-1.12-0.8.5.jar) 
	UCHIJAAAA	integrateddynamicscompat{1.0.0} [IntegratedDynamics-Compat] (IntegratedDynamics-1.12-0.8.5.jar) 
	UCHIJAAAA	integratedtunnels{1.3.0} [Integrated Tunnels] (IntegratedTunnels-1.12-1.3.0.jar) 
	UCHIJAAAA	inventorypets{1.4.9.8} [Inventory Pets] (inventorypets-1.12-1.4.9.8.jar) 
	UCHIJAAAA	inventorytweaks{1.63+beta.108.6ff67c4} [Inventory Tweaks] (InventoryTweaks-1.63+beta.108.jar) 
	UCHIJAAAA	journeymap{1.12.1-5.5.0b2} [JourneyMap] (journeymap-1.12.1-5.5.0b2.jar) 
	UCHIJAAAA	jeresources{0.8.4.24} [Just Enough Resources] (JustEnoughResources-1.12.1-0.8.4.24.jar) 
	UCHIJAAAA	minecolonies{1.12.1-0.8.3530} [MineColonies] (minecolonies-universal-1.12.1-0.8.3530.jar) 
	UCHIJAAAA	notenoughwands{1.5.9} [Not Enough Wands] (notenoughwands-1.12-1.5.9.jar) 
	UCHIJAAAA	opencomputers{1.7.0.4} [OpenComputers] (OpenComputers-MC1.12.1-1.7.0.4.jar) 
	UCHIJAAAA	openglider{@VERSION@} [Open Glider] (OpenGlider-1.12.1-1.1.0.jar) 
	UCHIJAAAA	harvestcraft{1.12.1a} [Pam's HarvestCraft] (Pam's HarvestCraft 1.12.1a.jar) 
	UCHIJAAAA	randomthings{4.0.5} [Random Things] (RandomThings-MC1.12.1-4.0.5.jar) 
	UCHIJAAAA	reborncore{3.2.6.91} [Reborn Core] (RebornCore-1.12.1-3.2.6.91-universal.jar) 
	UCHIJAAAA	reccomplex{1.4.5} [Recurrent Complex] (RecurrentComplex-1.4.5.jar) 
	UCHIJAAAA	storagedrawers{1.12-5.2.5} [Storage Drawers] (StorageDrawers-1.12-5.2.9.jar) 
	UCHIJAAAA	refinedstorage{1.5.17} [Refined Storage] (refinedstorage-1.5.17.jar) 
	UCHIJAAAA	xreliquary{1.12-1.3.4.706} [Reliquary] (Reliquary-1.12-1.3.4.706.jar) 
	UCHIJAAAA	rftools{6.13} [RFTools] (rftools-1.12-6.13.jar) 
	UCHIJAAAA	rftoolscontrol{1.6.8} [RFTools Control] (rftoolsctrl-1.12-1.6.8.jar) 
	UCHIJAAAA	rftoolsdim{5.04} [RFTools Dimensions] (rftoolsdim-1.12-5.04.jar) 
	UCHIJAAAA	roots{0.025} [Roots 2] (roots-2-0.025.jar) 
	UCHIJAAAA	spiceoflife{1.3.10} [The Spice of Life] (SpiceOfLife-mc1.12-1.3.10.jar) 
	UCHIJAAAA	techreborn{2.6.11.177} [Tech Reborn] (TechReborn-1.12.1-2.6.11.177-universal.jar) 
	UCHIJAAAA	thermalcultivation{0.1.0} [Thermal Cultivation] (ThermalCultivation-1.12-0.1.0.5-universal.jar) 
	UCHIJAAAA	thermaldynamics{2.3.4} [Thermal Dynamics] (ThermalDynamics-1.12-2.3.4.11-universal.jar) 
	UCHIJAAAA	usefulnullifiers{1.4.1} [Useful Nullifiers] (usefulnullifiers-1.4.1.jar) 
	UCHIJAAAA	wailaharvestability{1.1.11} [Waila Harvestability] (WailaHarvestability-mc1.12-1.1.11.jar) 
	UCHIJAAAA	xnet{1.4.0} [XNet] (xnet-1.12-1.4.0.jar) 
	UCHIJAAAA	teslacorelib_registries{1.0.7} [Tesla Core Lib Registries] (tesla-core-lib-1.12-1.0.7.jar) 
	Loaded coremods (and transformers): 
Inventory Tweaks Coremod (InventoryTweaks-1.63+beta.108.jar)
  invtweaks.forge.asm.ContainerTransformer
ForgelinPlugin (Forgelin-1.5.1.jar)
  
AppleCore (AppleCore-mc1.12.1-2.2.2.jar)
  squeek.applecore.asm.TransformerModuleHandler
TransformerLoader (OpenComputers-MC1.12.1-1.7.0.4.jar)
  li.cil.oc.common.asm.ClassTransformer
CoreMod (Aroma1997Core-1.12-1.3.0.0.b103.jar)
  
IELoadingPlugin (ImmersiveEngineering-0.12-70.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
CTMCorePlugin (CTM-MC1.12-0.2.2.7.jar)
  team.chisel.ctm.client.asm.CTMTransformer
IvToolkit (IvToolkit-1.3.3-1.12.jar)
  
LoadingPlugin (RandomThings-MC1.12.1-4.0.5.jar)
  lumien.randomthings.asm.ClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 384.94' Renderer: 'GeForce GTX 1060 6GB/PCIe/SSE2'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- wailaIntegration (Enabled/Not Forced)

	List of loaded APIs: 
		* actuallyadditionsapi (33) from ActuallyAdditions-1.12-r118.jar
		* AppleCoreAPI (2.4.0) from AppleCore-mc1.12.1-2.2.2.jar
		* Baubles|API (1.1.1.0) from inventorypets-1.12-1.4.9.8.jar
		* BetterWithModsAPI (Beta 0.6) from AppleSkin-mc1.12-1.0.7.jar
		* Chisel-API (0.0.1) from Chisel-MC1.12-0.0.13.16.jar
		* ChiselAPI|Carving (0.0.1) from Chisel-MC1.12-0.0.13.16.jar
		* ChiselsAndBitsAPI (13.8.0) from chiselsandbits-14.6.jar
		* cofhapi (2.0.0) from CoFHCore-1.12-4.3.4.12-universal.jar
		* cofhapi|block (2.0.0) from CoFHCore-1.12-4.3.4.12-universal.jar
		* cofhapi|core (2.0.0) from CoFHCore-1.12-4.3.4.12-universal.jar
		* cofhapi|item (2.0.0) from CoFHCore-1.12-4.3.4.12-universal.jar
		* cofhapi|tileentity (2.0.0) from CoFHCore-1.12-4.3.4.12-universal.jar
		* cofhapi|util (2.0.0) from CoFHCore-1.12-4.3.4.12-universal.jar
		* commoncapabilities|api (0.0.1) from CommonCapabilities-1.12-1.4.0.jar
		* ctm-api (0.1.0) from CTM-MC1.12-0.2.2.7.jar
		* ctm-api-events (0.1.0) from CTM-MC1.12-0.2.2.7.jar
		* ctm-api-models (0.1.0) from CTM-MC1.12-0.2.2.7.jar
		* ctm-api-textures (0.1.0) from CTM-MC1.12-0.2.2.7.jar
		* ctm-api-utils (0.1.0) from CTM-MC1.12-0.2.2.7.jar
		* DraconicEvolution|API (1.3) from Draconic-Evolution-1.12-2.3.3.261-universal.jar
		* farmingforblockheads|api (1.0) from FarmingForBlockheads_1.12-3.1.3.jar
		* ForestryAPI|apiculture (5.0.0) from forestry_1.12.1-5.5.0.171.jar
		* ForestryAPI|arboriculture (4.2.1) from forestry_1.12.1-5.5.0.171.jar
		* ForestryAPI|circuits (3.1.0) from forestry_1.12.1-5.5.0.171.jar
		* ForestryAPI|climate (2.1.0) from forestry_1.12.1-5.5.0.171.jar
		* ForestryAPI|core (5.1.0) from forestry_1.12.1-5.5.0.171.jar
		* ForestryAPI|farming (2.2.0) from forestry_1.12.1-5.5.0.171.jar
		* ForestryAPI|food (1.1.0) from forestry_1.12.1-5.5.0.171.jar
		* ForestryAPI|fuels (3.0.0) from forestry_1.12.1-5.5.0.171.jar
		* ForestryAPI|genetics (4.7.1) from forestry_1.12.1-5.5.0.171.jar
		* ForestryAPI|greenhouse (5.2.0) from forestry_1.12.1-5.5.0.171.jar
		* ForestryAPI|hives (4.1.0) from forestry_1.12.1-5.5.0.171.jar
		* ForestryAPI|lepidopterology (1.4.0) from forestry_1.12.1-5.5.0.171.jar
		* ForestryAPI|mail (3.1.0) from forestry_1.12.1-5.5.0.171.jar
		* ForestryAPI|multiblock (3.0.0) from forestry_1.12.1-5.5.0.171.jar
		* ForestryAPI|recipes (5.4.0) from forestry_1.12.1-5.5.0.171.jar
		* ForestryAPI|storage (5.0.0) from forestry_1.12.1-5.5.0.171.jar
		* ForestryAPI|world (2.1.0) from forestry_1.12.1-5.5.0.171.jar
		* gendustryAPI (2.3.0) from gendustry-1.6.5.4-mc1.12.jar
		* ImmersiveEngineering|API (1.0) from ImmersiveEngineering-0.12-70.jar
		* ImmersiveEngineering|ImmersiveFluxAPI (1.0) from ImmersiveEngineering-0.12-70.jar
		* integrateddynamics|api (0.2.0) from IntegratedDynamics-1.12-0.8.5.jar
		* jeresources|API (0.8.4.24) from JustEnoughResources-1.12.1-0.8.4.24.jar
		* journeymap|client-api (1.4-SNAPSHOT) from journeymap-1.12.1-5.5.0b2.jar
		* journeymap|client-api-display (1.4-SNAPSHOT) from journeymap-1.12.1-5.5.0b2.jar
		* journeymap|client-api-event (1.4-SNAPSHOT) from journeymap-1.12.1-5.5.0b2.jar
		* journeymap|client-api-model (1.4-SNAPSHOT) from journeymap-1.12.1-5.5.0b2.jar
		* journeymap|client-api-util (1.4-SNAPSHOT) from journeymap-1.12.1-5.5.0b2.jar
		* JustEnoughItemsAPI (4.13.0) from jei_1.12.1-4.7.5.88.jar
		* mcjtylib_ng (2.4.4) from mcjtylib-1.12-2.4.4.jar
		* Open Glider|API (0.1) from OpenGlider-1.12.1-1.1.0.jar
		* opencomputersapi|component (7.0.0-alpha) from OpenComputers-MC1.12.1-1.7.0.4.jar
		* opencomputersapi|core (7.0.0-alpha) from OpenComputers-MC1.12.1-1.7.0.4.jar
		* opencomputersapi|driver (7.0.0-alpha) from OpenComputers-MC1.12.1-1.7.0.4.jar
		* opencomputersapi|driver|item (7.0.0-alpha) from OpenComputers-MC1.12.1-1.7.0.4.jar
		* opencomputersapi|event (7.0.0-alpha) from OpenComputers-MC1.12.1-1.7.0.4.jar
		* opencomputersapi|filesystem (7.0.0-alpha) from OpenComputers-MC1.12.1-1.7.0.4.jar
		* opencomputersapi|internal (7.0.0-alpha) from OpenComputers-MC1.12.1-1.7.0.4.jar
		* opencomputersapi|machine (7.0.0-alpha) from OpenComputers-MC1.12.1-1.7.0.4.jar
		* opencomputersapi|manual (7.0.0-alpha) from OpenComputers-MC1.12.1-1.7.0.4.jar
		* opencomputersapi|network (7.0.0-alpha) from OpenComputers-MC1.12.1-1.7.0.4.jar
		* opencomputersapi|prefab (7.0.0-alpha) from OpenComputers-MC1.12.1-1.7.0.4.jar
		* reborncoreAPI (3.2.6.91) from RebornCore-1.12.1-3.2.6.91-universal.jar
		* reborncoreAPI|Power (3.2.6.91) from RebornCore-1.12.1-3.2.6.91-universal.jar
		* reborncoreAPI|Recipe (3.2.6.91) from RebornCore-1.12.1-3.2.6.91-universal.jar
		* reborncoreAPI|Tile (3.2.6.91) from RebornCore-1.12.1-3.2.6.91-universal.jar
		* StorageDrawersAPI (2.1.0) from StorageDrawers-1.12-5.2.9.jar
		* StorageDrawersAPI|event (2.1.0) from StorageDrawers-1.12-5.2.9.jar
		* StorageDrawersAPI|registry (2.1.0) from StorageDrawers-1.12-5.2.9.jar
		* StorageDrawersAPI|render (2.1.0) from StorageDrawers-1.12-5.2.9.jar
		* StorageDrawersAPI|storage (2.1.0) from StorageDrawers-1.12-5.2.9.jar
		* StorageDrawersAPI|storage-attribute (2.1.0) from StorageDrawers-1.12-5.2.9.jar
		* techrebornAPI (2.6.11.177) from TechReborn-1.12.1-2.6.11.177-universal.jar
		* valkyrielib.api (1.12-2.0.1a) from valkyrielib-1.12-2.0.1a.jar
		* WailaAPI (1.3) from Hwyla-1.8.20-B35_1.12.jar
	RebornCore: 
		Plugin Engine: 0
		RebornCore Version: 3.2.6.91
		Runtime Debofucsation 1
		RenderEngine: 0
	Launched Version: forge-14.22.0.2458
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1060 6GB/PCIe/SSE2 GL version 4.5.0 NVIDIA 384.94, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz

**Comment by KingLemming** [comment]
CCL Error. Please report on that repo.

**Comment by KingLemming** [comment]
Turned out to actually be HarvestCraft. covers put in a PR to fix it.
