### ISSUE TITLE
Chest going transparent

### ISSUE THREAD

**Issue by Thistlebalm** [CoFH/Feedback#488]
So this is really a tough one for me. I was using fastcraft & optifine, then uninstalled those to try COFHTweaks. I've never seen this before now. It appears really randomly, but usually after playing for ~20-30 minutes. 
They only go transparent when looking at a certain angle/area. 
Not all placed chests turn transparent, usually only recently placed ones. 
Quiting & restarting/changing textures fixes it until the 20-30 minute mark again. 
Just about all modded chests have the same problem;Iron Chests, Chisel 2(Presents), Thaumcraft(and other addon chests), AE2(Skystone chests), but not Enderchests. 
It doesn't change in hand, only placed chests.
The most recent time I noticed a slight flicker while I was placing the chests, that's when it started for the pictured group.

If there's any other info I can provide let me know.

![2015-05-01_15 42 42](https://cloud.githubusercontent.com/assets/8571660/7436240/8b2af00a-f019-11e4-86f7-06010b75ce3b.png)

**Comment by esotericist** [comment]
For what it's worth, this problem predates both CofHTweaks and Fastcraft. I've been dealing with it off and on for like a year now, and I have no idea what causes it. Nobody else can experience it with my configs. (multiple packs have displayed this to me) It is a mystery.

**Comment by Thistlebalm** [comment]
Oh man, that sucks. It's just so weird though. I don't think it's a huge issue, but this has been the hardest bug for me to recreate and try to understand.

**Comment by eruantien-hiraear** [comment]
I've seen this several times before, but it only seems to happen when I have Modular Powersuits installed. Are you using this mod?

**Comment by esotericist** [comment]
In my case, I haven't used MPS since 1.6.x

**Comment by Thistlebalm** [comment]
I'm not using Modular Powersuits either. Here's the dump of loaded mods from NEI http://pastebin.com/EcGBUApw

**Comment by skyboy** [comment]
Well, I'll close this then since it's not related to tweaks.
