### ISSUE TITLE
[1.12.1]TE 5.3.4.16 Dynamo orientation

### ISSUE THREAD

**Issue by TANDEROID** [CoFH/Feedback#489]
Sometimes, dynamo change orientation to default value

**Comment by KingLemming** [comment]
I'm only going to bother responding to this one. In the future, do not spam the tracker multiple times with what is OBVIOUSLY the same issue.

This is either a packet issue or chunk loading issue. It isn't caused by us and isn't our bug. You have another mod doing this.
