### ISSUE TITLE
Cofh worldgen no ores generating in certain areas in straight lines?

### ISSUE THREAD

**Issue by dahjin** [CoFH/Feedback#489]
im using only cofh to handle all of my oregen and i tend to get these lines with no ores on every test world i do im not sure if its only related to just the spawn or what?
http://i.imgur.com/BHOZXKj.jpg

**Comment by KingLemming** [comment]
We're looking into this. Conceivably, we see how this *can* happen, but we actually haven't been able to reproduce it. It's sort of a race condition.
