### ISSUE TITLE
Dupe bug found

### ISSUE THREAD

**Issue by runescapejon** [CoFH/Feedback#49]
These are the version i have installed and here a video on how to dupe it any item
https://youtu.be/Wqz4gPz7ZEM
CoFHCore-[1.7.10]3.1.4-329
ThermalDynamics-[1.7.10]1.2.1-172
ThermalExpansion-[1.7.10]4.1.5-248
ThermalFoundation-[1.7.10]1.2.6-118

**Comment by KingLemming** [comment]
Right, this is 1.7.10. No longer supported, sorry.
