### ISSUE TITLE
Stopped rendering after about an hour.

### ISSUE THREAD

**Issue by Euphoreich** [CoFH/Feedback#490]
Tried it on tppi2 after removing fastcraft, and it's fantastic. About a 25% increase in fps, but after about an hour all blocks stopped rendering, and I had to restart to get them to start again.

Great work guys, this looks extremely promising.

I should note I only had it client side, and not server side, the server was running cauldron and not fastcraft.

**Comment by Euphoreich** [comment]
Oh did i submit this to cofh issues instead of cofh tweaks issues?

**Comment by KingLemming** [comment]
This is the correct place.

**Comment by skyboy** [comment]
Closing due to duplicating #498: refer there for updates.
