### ISSUE TITLE
[COFH Tweaks] Bug with The Aether II: No blocks load except the ones in the player's current chunk

### ISSUE THREAD

**Issue by bubbyboytoo** [CoFH/Feedback#491]
Changing the render distance a few times seems to fix it for the rest of the game session.

![2015-05-01_22 40 58](https://cloud.githubusercontent.com/assets/12205185/7439464/3a6a52a2-f053-11e4-8f90-9ceec41e6baa.png)

**Comment by VapourDrive** [comment]
I believe this may have to do with the threaded lighting in guilded games core.

**Comment by skyboy** [comment]
I may close this if no further information can be found - I have no particular way of finding or fixing the issue.

**Comment by skyboy** [comment]
This appears to not be an issue anymore.
