### ISSUE TITLE
[1.12.1] Steam Boiler Augments Slightly Too Efficient.  Breaks Laws of Thermodynamics.

### ISSUE THREAD

**Issue by VT-14** [CoFH/Feedback#493]
![2017-08-22_17 19 17](https://user-images.githubusercontent.com/12564251/29588447-8e00a560-875f-11e7-8a0e-b78bd8a460a0.png)

Currently, the above setup generates ~ 100 RF/t from an RF -> Magma Crucible -> RF loop.

The Igneous Extruder creates one piece of cobblestone using 400 RF.  The Magma Crucible creates 1 bucket of lava from that piece of cobblestone using 300,000 RF.  The Pyroconvective Loop augment allows this process to take as few as 200 ticks without sacrificing efficiency.  1 bucket of lava is produced from 300,400 RF.

A Magmatic Dynamo with the Boiler augment and 3 Fuel Catalyzer Augments can feed steam into a Steam Dynamo with the turbine augment.  This generates 324,000 RF from every bucket of lava, which is greater than the lava creation cost.

This loop generates 23,600 RF, and can theoretically be done every 200 ticks.  That creates a theoretical limit of 118 RF/t per Magma Crucible.  The above setup settles for 100 RF/t using 3 Magmatic Dynamos and 2 Steam Dynamos (each Steam with 2 Auxiliary Transmission Coil augments), and is slowly producing a slight excess of RF.  All Machines and Dynamos are upgraded to the Resonant Tier.

Minecraft 1.12.1
Forge: 14.22.0.2460
Thermal Expansion: 1.12-5.3.4.16
Manual Debug Crash: https://gist.github.com/VT-14/05416a04f7df4a38ec98a1851d585cd1

**Comment by KingLemming** [comment]
It's already been adjusted.
