### ISSUE TITLE
[CoFH Tweaks] Crash on Direwolf20 1.3.0 and weird block rendering

### ISSUE THREAD

**Issue by Mcniiby** [CoFH/Feedback#493]
http://pastebin.com/pTErN7x5

Another crash 

http://pastebin.com/65wBVJLy

This one was when opening a door and the other now that I think of it was when I was opening a tesseract or the GUI of the tanks from railcraft

Also I'm getting weird looking blocks and textures(Appears this isn't from you guys and just something wrong with the new version of direwolf20)

Lines between blocks 
![2015-05-01_22 53 32](https://cloud.githubusercontent.com/assets/12205417/7440195/899cc07a-f059-11e4-9033-54228158dd0c.png)
![2015-05-01_20 03 51](https://cloud.githubusercontent.com/assets/12205417/7440196/8c1f1ae6-f059-11e4-8b0f-4666ebb92364.png)
![2015-05-01_20 03 57](https://cloud.githubusercontent.com/assets/12205417/7440198/8de50ed0-f059-11e4-882a-42636ad72fbe.png)

**Comment by skyboy** [comment]
Crashes are solved, the seams are not caused by tweaks.
