### ISSUE TITLE
[CoFH Tweaks]Oddities with Golems & Agricraft Crops

### ISSUE THREAD

**Issue by TraXza** [CoFH/Feedback#494]
No actual crash with this one, but adding CoFH Tweaks to Regrowth 0.7.4 (latest) causes golems to stop harvesting crops - only tested with crops planted on agricraft crop sticks.

The pack has an older version of CooFH Core (CoFHCore-[1.7.10]3.0.0B9-99.jar), updating to '3.0.2-273' & the problem persists.  Not sure if this is due to the custom nature of the modpack, either way hopefully it highlights something that could better CoFH Tweaks which aside for that issue gives a big increase in FPS for me.

Regrowth - COFHCore3.0.0B9-99_NO_COFHTweaks (busy golems)
![regrowth - cofhcore3 0 0b9-99_no_cofhtweaks](https://cloud.githubusercontent.com/assets/12209368/7440991/cfd5a096-f0d3-11e4-9f79-8b1bd27ba35d.png)

Regrowth - COFHCore3.0.0B9-99_COFHTweaks0.1.0B1-24 (lazy golems)
![regrowth - cofhcore3 0 0b9-99_cofhtweaks0 1 0b1-24](https://cloud.githubusercontent.com/assets/12209368/7440996/ff13f8c6-f0d3-11e4-880d-1449c346981e.png)

Regrowth - COFHCore3.0.2-273_COFHTweaks0.1.0B1-24 (lazy golems)
![regrowth - cofhcore3 0 2-273_cofhtweaks0 1 0b1-24](https://cloud.githubusercontent.com/assets/12209368/7441003/1ceae1a2-f0d4-11e4-9f52-a4ce5c38b120.png)

**Comment by esotericist** [comment]
I just testing with a minimal install, and cofhtweaks did in fact cause thaumcraft harvest golems to stop harvesting with the combination of Forge 1291, thaumcraft 4.2.3.5 (which implies baubles 1.0.1.10), cofhtweaks 0.1.0B1-24.

cofhtweaks 0.2.0B1-25 fixes it, so this can probably be closed as fixed.

**Comment by TraXza** [comment]
Thanks for the feedback, CoFHTweaks 0.1.0B1-28 is working for me as well.
