### ISSUE TITLE
[CoFHTweaks] Feature or bug?

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [CoFH/Feedback#495]
I'm not sure if that's a feature or indeed a bug... No idea how to describe it either. Take a look at this short video: https://mega.nz/#!9twnEJjQ!_U_UqVFhPa28a6YVTwcBxITNquXICRJN_JQGn52OJ1s

**Comment by KingLemming** [comment]
Something wrong with youtube? We need a decryption key for that nonsense.

**Comment by Unrepentant-Atheist** [comment]
Ooops, my bad.

**Comment by skyboy** [comment]
That's a big part of how it improves framerate. It's normal, I'll see if I can make it less obvious, but there's limits.

**Comment by KingLemming** [comment]
To be fair skyboy, it NEEDS to be less obvious.
