### ISSUE TITLE
[Suggestion] Sandstone recipe for Compactor

### ISSUE THREAD

**Issue by VallenFrostweaver** [CoFH/Feedback#496]
There seems to be a missing link in the chain of _automation_ for making any variant of phyto grow: The ability to make Niter. Currently you can make it from variations of sandstone. This is fine but the sandstone does require manual crafting or mining. I would like to recommend that sandstone be a recipe in the compactor. 4 sand would be a simple solution. This will allow the autocrafting of sandstone that the chain is missing.

Therefore the autocrafting chain would look something like this (I didn't include quantities):
Igneous Extruder + lava/water = cobblestone + Pulverizer = sand (and gravel) + Compactor = sandstone + pulverizer = sand (and chance of niter)

As a side note, this would also allow for the autocrafting of endstone as sandstone is used for that process as well.

**Comment by KingLemming** [comment]
This actually used to be a thing prior to 1.12. The issue is that the new recipe system prevents me from easily scanning the recipe list and automatically adding it. I'm trying to come up with a more elegant solution than just adding things manually.

**Comment by KingLemming** [comment]
Turned out to be easier than I thought. :)
