### ISSUE TITLE
MFR ThaumcraftCompat crash issue with latest Thaumcraft

### ISSUE THREAD

**Issue by NEXUS2345** [CoFH/Feedback#496]
Pasted from MFR issues section: MFR is trying to register a non existable aspect "Tempus".
That one is Added by Magic Bees, not Thaumcraft, and it wants to add it even if you don't have Magic Bees installed.

What's more, after installing it, it keeps telling "Thaumcraft" that one of it's items uses this aspect, and thaumcraft doesn't have anything to do with it, so, it crashes.

Crashlog for the same issue: http://pastebin.com/mKWbv7VX

**Comment by skyboy** [comment]
The crash log is Thaumcraft crashing because of a stackoverflow, caused by an item loop in its lookup of aspects on an item. This has nothing to do with MFR, nor with the missing aspect.

**Comment by AnodyneEntity** [comment]
Had this same issue, removed MFR, my single player worlds loaded up fine, so there is a compatibility issue between MFR and Thaumcraft at the moment.

**Comment by NEXUS2345** [comment]
I am sorry, but this issue is definitely MFR. Line 2 states that the exception was flagged by the ThaumcraftCompat section of MFR. Removing MFR stops the crash from occurring completely. I will attach a forge.log and a crashreport from a single player below. I am also tagging @Azanor so that he can take a look. This is occurring with several different Forge versions also.

Forge log before removing MFR: https://raw.githubusercontent.com/NEXUS2345/Crashes/master/before%20removing%20MFR%20fml-client-latest.log
Forge log after removing MFR: https://raw.githubusercontent.com/NEXUS2345/Crashes/master/after%20removing%20MFR%20fml-client-latest.log
Single player crash: http://pastebin.com/pnnf4PJS

**Comment by NEXUS2345** [comment]
Also, this appears to be the same as skyboy/MineFactoryReloaded#446
