### ISSUE TITLE
[Thermal Dynamics] Dimension corruption when moving duct with FunkyLocomotion

### ISSUE THREAD

**Issue by Zoryn4163** [CoFH/Feedback#497]
See: https://github.com/McJty/RFTools/issues/166
Mod list: http://pastebin.com/kXqMpqQ6

**Comment by KingLemming** [comment]
Posted in the other one, but there's a good chance this isn't really fixable. I've checked the code and we are already checking for the proper class, so this is a deeper corruption issue caused by Minecraft just not doing things right.

**Comment by Zoryn4163** [comment]
That was expected. Thank you for looking into it.
