### ISSUE TITLE
|1.12| Cryo-stabilized and draconic

### ISSUE THREAD

**Issue by Bass2style** [CoFH/Feedback#497]
Cryo-Stabilized Fluxducts wont connect to Draconic Evolutions Energy Pylons, but lower tier of cables does.

MC Version : 1.12
Modpack : RagnaMod IV
Forge : 14.21.1.2443
Draconic Evolution : 2.3.3.261
Thermal Dynamics : 2.3.4.11

**Comment by KingLemming** [comment]
The Cryoducts literally extend the base ducts, so the root of this issue is on Draconic's end.

**Comment by Bass2style** [comment]
okay, submiting the issue to Brandon's GIT then.
