### ISSUE TITLE
[CoFHTweaks] Rendering weirdness

### ISSUE THREAD

**Issue by Evolution0** [CoFH/Feedback#498]
I believe this is similar to issue #490 due to the fact that after a few blocks were placed subsequent blocks would not render and breaking previously placed blocks (that did render) did not remove their model.

That and after I switch graphics from fast to fancy to get everything to reload nothing but mobs and my character model would display (and switching back did nothing to fix it).

Before making it reload:
![Before switching](http://a.pomf.se/xadpkm.png)

After:
![After switching](http://a.pomf.se/xwvbvm.png)

Restarting MC fixed it.

It seems pretty inconsistent and I can't reliably reproduce it, sometimes it will happen in 30 seconds of me placing/breaking blocks and sometimes it will happen after a few minutes and fix itself.

CoFHTweaks-[1.7.10]0.1.0B1-24

**Comment by Unrepentant-Atheist** [comment]
Yea, I get that sometimes to. Have to restart MC completely for it to go away. Just quit and reloading world doesn't work.

**Comment by skyboy** [comment]
This should now be corrected. Fun with parallelism.

**Comment by Evolution0** [comment]
Yeah I don't get this with the latest (CoFHTweaks-[1.7.10]0.1.0B1-30) Though I do get this strange effect where it will unrender/hide all chunks outside of a 3x3 + shape (5 chunks) around me randomly.
