### ISSUE TITLE
Itemduct Servos Incorrectly Filter Potions [1.11.x]

### ISSUE THREAD

**Issue by Xirema** [CoFH/Feedback#499]
Using Thermal Dynamics 2.2.6.13 in Minecraft 1.11.2 with Forge 2386, with Java 8 64-bit on Windows 10, on a Standalone Server running locally.

Itemduct Servos set to Whitelist mode, using Metadata, using NBT data, ignoring Forge Dictionary, ignoring Mod Owners, are only allowing the first listed Potion through the filter. If, for example, I set the filter to allow [Extended Night Vision Potion], [Extended Fire Resistance Potion], only the first listed potion is allowed to pass through. In this case, the Night Vision Potions get through. If I reverse the order, the Night Vision Potions get blocked, and the Fire Resistance Potions get through.

I tried to replicate this using Stone, Diorite, and Dirt, and did not have the same issue.

[Splashing Instant Health II] did not interfere with [Extended Fire Resistance], but did interfere with [Splashing Poison II].

Something to do with the filters is not taking the (somewhat overlapping) nature of Potion Metadata into account, making automated potion systems difficult.

Let me know if you need screenshots or more details about the setup I'm using.

EDIT: Blacklist appears to have a few related inconsistencies/discrepancies, but I haven't tested it under conditions as rigorous.

**Comment by KingLemming** [comment]
Fixed in 1.12. Unsure if I'll backport it TBH.
