### ISSUE TITLE
Strange rendering bug on title screen

### ISSUE THREAD

**Issue by Samario1** [CoFH/Feedback#499]
With the latest version of CoFH Core, and only CoFH Core, installed, I get this weird effect where the title screen (and ingame) fails to render properly, producing an effect similar to that below.
![image](https://cloud.githubusercontent.com/assets/11773646/7445975/e6ef62fc-f1bf-11e4-9c9d-0a63d58c8f10.png)
If CoFH Core is disabled, the screen returns to normal and I can play the game properly.
Running Java 8 u45
Minecraft 1.7.10
Forge 1291
Windows 7 (32-Bit)
Intel(R) HD Graphics (Core i5)

**Comment by KingLemming** [comment]
Duplicate of #451
