### ISSUE TITLE
Waila shows the wrong names for some blocks 

### ISSUE THREAD

**Issue by itsCobaltRogue** [CoFH/Feedback#5]
Example 1: http://prntscr.com/eg4l1q
Example 2: http://prntscr.com/eg4l8v

**Comment by Rocky28447** [comment]
To clarify: WAILA shows all normal machines as "Redstone Furnace", all Dynamos as "Steam Dynamo", and all passive machines as "Aqueous Accumulator".

**Comment by KingLemming** [comment]
Is this not a WAILA issue then?

**Comment by SPMoo66** [comment]
HWYLA does not have this problem, so you can probably blame WAILA for being so outdated for this issue.

**Comment by cylek56** [comment]
There are other options the items: Hwyla by Tehnut or The One Probe by McJty,  ProfMobius has not updated Waila for a while
