### ISSUE TITLE
Void dimension log in issue

### ISSUE THREAD

**Issue by ryuben** [CoFH/Feedback#500]
4.1 infinity server

made a void dimension with RFTools

put in 10 turbines ( big reactors)

and a mek reactor with 21 salination towers etc etc

annnd i crash when ever i try to load the world 

http://www.pastebin.com/HjXr4wUH

http://pastebin.com/NiZyCLLp

help please

**Comment by KingLemming** [comment]
This isn't a void dim issue, it's something with Mek's salination plants and how they make chunks behave. We can't do anything about it on our end.
