### ISSUE TITLE
[Feedback/Suggestion] Dynamo Coolant mechanics

### ISSUE THREAD

**Issue by ShneekeyTheLost** [CoFH/Feedback#500]
This isn't a bug report so much as feedback based on my playing around with Dynamos in preparation for making a Mod Spotlight and inclusion in my mod pack that I am developing for MC 1.12.1. Specifically, how coolant currently works.

Right now, it seems that the only advantage to using a more 'advanced' coolant (i.e. Gelled Cryotheum) is that it is consumed at a slower pace than water, giving no further mechanical advantages. However, Gelled Cryotheum is decidedly non-trivial to mass produce, while water is easily available through an Aqueous Accumulator, giving absolutely zero reason or cause for any player to want to upgrade their coolant at any point, which seems a shame to me and a place that could be improved upon at some future point when you aren't busy with everything else your amazing team is doing. 

Where that balance point is to be put, however, is something of a sticky question. Simply increasing the RF/t output seems like a poor design choice, seeing as how this leads to a mudflation effect as other mods adapt to this and put in their version of 'a better coolant'. 

A better idea might be something like increasing fuel efficiency. Say you have four dynamos able to run from your current production of whatever fuel source you are using. A better coolant increasing fuel efficiency by 25% means being able to put a fifth dynamo on the same fuel line, for an effective increase in RF production, but without mudflation of RF/t numbers per engine, and requires crafting and hooking up said dynamo to both fuel and coolant lines. The net result is still 25% more energy produced per time iteration, but less brute-force number-spam. This is already somewhat seen in Reactant Dynamos, if one considers it an engine which burns solid fuel A with 'coolant' B also required, with the best efficiency using the elemental reactions that are the most expensive to produce the materials for. 

I don't want to distract anyone from the Thermal Cultivation mod in progress, or all of the other things being worked on at the moment, but I also saw a place where the mod could develop a new and interesting dynamic and so thought to share with the class.

**Comment by KingLemming** [comment]
It's been on the todo actually. Although if look at the Thermal Mediator, there's an extremely good reason to use Cryotheum.

I've been considering taking the new % values and applying them to possibly Efficiency in the Compression Dynamo and Output in the Magmatic Dynamo (Efficiency in the Magmatic would lead to a thermodynamic break).

**Comment by ShneekeyTheLost** [comment]
While I can understand, this may cause a perceived imbalance by a large percentage of the player base. The Magmatic Dynamo already has a reputation of being 'practically passive generation' due to prevalence of means of pumping lava from the nether and transporting it to the overworld, and popularity of skyblock type maps that have lava as an early-game resource. Increasing RF/t to this using Gelled Cryotheum may give a perception of 'an inherently superior option' due to higher RF/t generation. 

As a result, you may need to give a more substantial efficiency bonus to the Compression Dynamo than you give an energy production bonus to the Magmatic Dynamo. 

Other than that, sounds great to me. You may even rename the upgrade for the Magmatic Dynamo to 'Stirling Upgrade', and posit that the increase in RF production comes from the thermal differential, so of course colder coolant makes it do more work in the same period of time.

**Comment by KingLemming** [comment]
Well the RF production increase *would* be from the differential, yes. That's just basic thermodynamics.

I think you're way overstating any perceived imbalance there, however. Cryotheum is as you mentioned, non-trivial to make. So it becomes higher power production at a higher cost. Also, I would obviously adjust the numbers such that either water has no boosting effect, or alter the Isentropic Reservoir to not provide a boost at the augment level and rely only on coolant.

Really, I thought you had more faith in me.
