### ISSUE TITLE
Error crashing my server with ae2 - extrea utils

### ISSUE THREAD

**Issue by xanderc2** [CoFH/Feedback#501]
Hi, i got this error on my server, it's something that happen only when the chunk is loaded, luckyfully i dont have a chunk loader and my world is safe, 
for now...

forge-cauldron: 1370
thermalexpansion: 4.0.1 -182
ae2: rv2-33

this is the error: http://pastebin.com/J3nPpbxy
this error occour also with extrautilities, so ae2 is not the cause...

**Comment by skyboy** [comment]
This appears to be either a bug in cauldron, or a misbehaving mod. Reproduce it without cauldron, otherwise open the report that they have `UNKNOWN` listed in `VALID_DIRECTIONS`

**Comment by xanderc2** [comment]
i dont know how works closed issues, but please check this:
https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/1457

**Comment by Prototik** [comment]
Even if some add UNKNOWN to valid list, it will has index 6.  
  
`getAccessibleSlotsFromSide` looks like this:
```java
public int[] getAccessibleSlotsFromSide(int side) {
    return sideConfig.slotGroups[sideCache[side]];
}
```
Possible issue not that side == 7, but sideCache[side] == 7 ?

**Comment by KingLemming** [comment]
I'm pretty sure it's actually #475, which is fixed in dev. No ETA on a release though.

**Comment by MySt1k** [comment]
please update
