### ISSUE TITLE
Servo over-sending when multiple items on route

### ISSUE THREAD

**Issue by fscan** [CoFH/Feedback#502]
I have a servo on a chest sending items to filtered (different items) 1 size inventories on the same TE. The filters are set to prevent over-sending. As long as only one of the inventories empties and is ready to accept a new item it work. But when 2 inventories are ready to accept simultaneously the servo continues sending items until the slots are filled. The over-sent items are spilled.
As far as i can see, it somehow depends on the order it sends the items, as if its somehow confused by the sided nature. If the items are in the "correct" order in the source chest it works.
The TE in question is the AE2 inscriber, which exposes 3 distinct IItemHandlers, one for top, one for botton and one for the remaining sides.

Forge: 14.21.1.2443
TD: 1.12-2.3.4.11

**Comment by KingLemming** [comment]
Frankly the AE2 inscriber has always been a mess. I'm not sure if this is worth addressing.

**Comment by fscan** [comment]
The inventory system has been completely rewritten (actually by me)

If you can point me to another TE which has similar sideness/restrictions i will gladly test an try to reproduce it.

**Comment by KingLemming** [comment]
Offhand I can't think of any other tile like that. And that's part of the problem - the Inscriber historically has been a really annoying special snowflake. At one point it actually required a Forge patch to make interaction with it work properly.

Can you get me a video of this happening?

**Comment by fscan** [comment]
https://drive.google.com/open?id=0B26GWD6V2JIGVUN0bFdCV0tMVVU

**Comment by KingLemming** [comment]
Okay so I did some testing. The Inscriber is still a snowflake.

![Cache Test](http://i.imgur.com/NmD4iI8.png)

On the left, the Caches first pull the bottom, then top, then side. So 2 silicon, and THEN the redstone. One at a time, very slowly.

On the right, the vanilla furnace, one of the most poorly coded blocks in the history of anything. Both items pull simultaneously, go to their correct slots, and the furnace starts.

**Comment by fscan** [comment]
>On the left, the Inscriber fills the bottom, then top, then side. So 2 silicon, and THEN the redstone. One at a time, very slowly.

i noticed that - what is the cause for this?

> So I'm still not super likely to address this, given that it's a heck of a corner case and could be fixed very easily on your end by redoing your item handlers a bit

I don't really know what you mean. What part of our item handlers are the problem? Because they are 3 distinct instances depending on the connected face? Or because they limit the stack size to 1? Other then that they should behave like the StackItemHandler they are derived from.

I'm not saying there are definitely no bugs on our end, but i would like to know what part of the TE's behaviour is causing problems.

**Comment by KingLemming** [comment]
To be honest, I don't know what the issue is. And this almost hurts to write, but basically your block should maybe work more like the vanilla furnace. It also has 3 IItemHandlers. It's also a sided inventory, which is probably still appropriate.

Thermal Expansion's machines can be reconfigured at will and we don't see any behavior like this, so maybe try doing what the vanilla furnace does. Write it as ISidedInventory, keep the IItemHandlers, and use net.minecraftforge.items.wrapper.SidedInvWrapper to create them.

**Comment by fscan** [comment]
I had a quick look over your code. Maybe i'm missing something, as i didn't look at all the possible codepaths but it seems to me that SimulatedInv ignores the stack size limit of the original slot. It always tests the insertion on a maxStackSize'ed slot. So while you can correctly insert just 1 at a time, you can do it up to 64 times for a item that stacks to 64.

**Comment by KingLemming** [comment]
https://github.com/CoFH/ThermalDynamics/blob/49c44764b5897f0936f37ae2e96f5641415dbc54/src/main/java/cofh/thermaldynamics/duct/item/SimulatedInv.java#L126

...what?

**Comment by fscan** [comment]
yes, but insertItem allows inserting a 1 sized stack multiple times as getSlotLimit is not used in the class itself.
I'll have a closer look in an hour or so ..

**Comment by fscan** [comment]
ok... https://pastebin.com/5evhS1pS would fix the issue

**Comment by KingLemming** [comment]
That does handle it, although the extraction delay remains. Interesting.

**Comment by fscan** [comment]
in my case the delay was also gone, but i didn't do any extensive testing.
