### ISSUE TITLE
[1.12.1-5.3.5.18] Hard dependency on The One Probe?

### ISSUE THREAD

**Issue by Leo40Git** [CoFH/Feedback#503]
**Log:** https://pastebin.com/DAv0KBDF
I mean, I was going to add The One Probe anyway...

**Comment by KingLemming** [comment]
Unless the version that somehow got posted to Curse is incorrect, then the answer is no. Lemme check.

**Comment by KingLemming** [comment]
Yep. It apparently was. Go Curse.
