### ISSUE TITLE
Clay Bucket from ITT doesn't get destroyed

### ISSUE THREAD

**Issue by Adaptivity** [CoFH/Feedback#504]
[Just gonna bring this to there](https://github.com/SlimeKnights/IguanaTweaksTConstruct/issues/117).

**Comment by KingLemming** [comment]
I have absolutely no idea what is supposed to happen here.

**Comment by KingLemming** [comment]
Sorry, have to close this one down. Fundamentally, that bucket isn't coded right. The callback chain is interrupted by the normal operation of Minecraft, as I've explained in the other issue.
