### ISSUE TITLE
[1.11.2 Question] What am I doing wrong? Mobs from TF not spawning 

### ISSUE THREAD

**Issue by Flyrija** [CoFH/Feedback#505]
I don't know what's wrong, but basalz, blizz and blitz don't spawn no matter where I look. In which biomes do I need to look for them (tested snowy areas, mountains and desert/plains)? I upped the lightlevel to 12 in the config, tried changing the spawnrate from 10 to 20 and nothing =(. Spawneggs work, but they don't spawn in survival. 

I'm using: 
forge 1.11.2-13.20.1.2386 
ThermalFoundation-1.11.2-2.2.5.16
ThermalExpansion-1.11.2-5.2.6.22
ThermalDynamics-1.11.2-2.2.6.13
CoFHCore-1.11.2-4.2.7.15

**Comment by KingLemming** [comment]
Just tested. They are correctly spawning. Make sure all of your mods are up to date, only advice I have for you.
