### ISSUE TITLE
All modpacks crash with cofhcore installed, regardless of version.

### ISSUE THREAD

**Issue by jaidens111** [CoFH/Feedback#505]
I honestly have no idea whats going on.
pastebin to where the error first is shown : http://pastebin.com/PU3PGzgW
full start log : http://paste.atlauncher.com/view/ee765103

**Comment by KingLemming** [comment]
You have some other mod either breaking your Minecraft installation or simply a corrupted MC installation.

If this were on our end, literally nobody would be able to play the mod.

**Comment by jaidens111** [comment]
When I said all modpacks I literally meant EVERY modpack, not one, every last modpack i use with cofh core tosses an error nearly identical to that one. I've tried a fresh install, I've tried updating/downgrading/sidegrading mods, I've tried java reinstallations. I have literally gone through everything I have learned from modding clients sense fricking beta!

**Comment by KingLemming** [comment]
Well, that error is basically, "Part of Minecraft isn't there anymore."

So, it's on your end. Sorry. :/

**Comment by skyboy** [comment]
Don't use dev versions if you're not a developer. You've been repeatedly downloading a version you shouldn't be using.

**Comment by KingLemming** [comment]
Good call skyboy - I didn't check the 2nd log for whatever reason.
