### ISSUE TITLE
Fluctuating itemduct doesnt receive power from fluxduct

### ISSUE THREAD

**Issue by valveo** [CoFH/Feedback#506]
I made test setup based on reddit post.
Energycell -> redstone fluxduct -> fluctuating itemduct -> energycell
http://imgur.com/pqrKqJm

Power is not moving between fluxduct and itemduct. If I remove fluxduct and place it back same position, power starts flowing. I could reproduce this.
ThermalDynamics version: 1.0.0-122

**Comment by KingLemming** [comment]
Would love to fix this one, but it just doesn't actually happen. :/ We'll need a modlist to see if anything is screwing with our mods.

**Comment by valveo** [comment]
Modlist from server:
https://gist.github.com/valveo/e88ccc2cb9ab2fc8944e

**Comment by McJty** [comment]
I have the same issue with another modpack (I was the one who originally reported this on reddit). I don't have my modlist here at this computer however.

**Comment by KingLemming** [comment]
I really don't know what to tell you. I've tested it a lot of different ways and it just doesn't happen. Energy flows.

**Comment by McJty** [comment]
Here is my setup that I had at first. It worked in the beginning and then it stopped working at some point (I think when it got unloaded and loaded again, that part is not chunkloaded):

http://i.imgur.com/LMdVqCL.png

**Comment by whitestarx0312** [comment]
I have the same issue on Agrarian Skies 2 1.0.39. I will upload screenshots later.

**Comment by KingLemming** [comment]
Still waiting for screenshots, since this doesn't seem to actually happen...

**Comment by whitestarx0312** [comment]
Okay I have almost the same setup but with a final fluxduct instead of cell.
 I have a Energy cell -> redstone fluxduct -> fluctuating itemduct -> back to redstone fluxduct.

http://imgur.com/syPTlSN
http://imgur.com/DcwPJp8

**Comment by jforr** [comment]
I'm having the same issue.  With my setup I'm alternating between Fluctuating itemducts and regular fluxducts a few times.  The first transition works, but the latter ones seem to be receiving a fraction of the power that they should be.

**Comment by hron84** [comment]
@kinglemming it has a little chance but I guess the problem can be the connection between fluxduct and fluctuating itemduct falls into a chunk border an when the fluxduct unloads and loads back it doesn't revalidate its connections. But it's just a wild idea.

**Comment by KingLemming** [comment]
Nothing to do with borders here, no. I still can't actually get it to happen, so it's either a complete x-mod or already fixed in dev.

**Comment by KingLemming** [comment]
Is this still a thing for anyone?

**Comment by DarkDaskin** [comment]
I just had the same problem now with `ThermalDynamics-[1.7.10]1.1.0-161` (within FTB Infinity 2.1.3). A *fluctuating itemduct* did not accept power from a *leadstone fluxduct*. I tried reconnecting ducts with a wrench, replacing the fluxduct and even connecting them indirectly via Immersive Engineering wires. But it only started to work when I detached a *servo* from the *fluctuating itemduct* and reattached it back.

**Comment by whitestarx0312** [comment]
I know this is a hard thing to prove/find, but I can also still say this problem persists. Furthermore, it happens on all bi-purpose ducts such as the fluctuating itemduct, and fluctuating fluiduct. It only happens when you attempt to power a bi-purpose duct with a regular fluxduct (all types).

**Comment by Mobliz640** [comment]
Still a problem in FTB Infinity Evolved 1.7 v 2.6.0. Fluctuating Itemduct not receiving power from adjacent redstone energy fluxduct.  Problem can be fixed by breaking the connection and replacing, but breaks again shortly after. 
![2016-09-05_07 18 12](https://cloud.githubusercontent.com/assets/5910701/18246344/06dce53e-7339-11e6-8157-45b00d2a621f.png)

**Comment by hron84** [comment]
@Mobliz640 temporary solution: add a leadstone cell between the fluxduct and the fluctuatng itemduct.

**Comment by whitestarx0312** [comment]
lol 1.7 guys

**Comment by hron84** [comment]
@whitestarx0312 still popular, 1.8-1.10 is still too frequently changes.
