### ISSUE TITLE
[Feedback/Suggestion] Satchel Improvements

### ISSUE THREAD

**Issue by Boolyman** [CoFH/Feedback#506]
I really love your recent incorporation of Cultivation tools, and even backpacks under the Thermal umbrella. I cant wait to see how Thermal Cultivation develops.  Hopefully I can fully ditch waiting on MFR to update to 1.12.1.

Anyways, I wanted to recommend adding some Augment Upgrades for the backpack.  Mostly for mining purposes... a Mining Upgrade that automatically places ore items into the backpack, instead of player inventory. Things that enable automatically condensing ores like redstone, lapis, glowstone, etc... into block form to save space.  Voiding cobblestone, stone, granite, etc...

This will make your Satchels self sufficient, and negate the need for us to download any separate Backpack mods.

**Comment by Skillotic0703** [comment]
KingLemming already plans on improving the satchels, adding filters for auto-picking and auto-destroying items.

**Comment by KingLemming** [comment]
Self-sufficient is a loaded term. While I have plans for satchels, I don't think I'll be adding any sort of auto-compressing/smelting/whatever feature.

**Comment by KingLemming** [comment]
Satchels in the next release will have a lot more functionality. No auto-compressing or Smelting though, that's a bit further than I want to take them as it would start to eclipse other parts of Thermal Expansion.

In 1.13, I may juggle which blocks/items are where and break them out into their own mod, who knows.
