### ISSUE TITLE
[ThermalExpansion] Phytogenic Insolator + AE2 import bus crashing

### ISSUE THREAD

**Issue by Astarael** [CoFH/Feedback#507]
> Attaching an AE2 Import Bus to the right side of a Phytogenic Insolator (AE2 Interface (left) and ExtraCells Fluid Export Bus (Back) already attached) causes a crash.

Versions:
COFHCORE-[1.7.10]3.0.2-262
THERMALEXPANSION-[1.7.10]4.0.1-182

This may be related to Issue #475 

Crashlog:

http://pastebin.com/WdMtp7PG

**Comment by KingLemming** [comment]
Yup. Duplicate of #475.
