### ISSUE TITLE
Suggestion for new Thermal Dynamics item

### ISSUE THREAD

**Issue by andrewrula** [CoFH/Feedback#508]
A friend and I were discussing Thermal Dynamics and things we wished that we could see, and one idea came up a couple of times. I figured that it was good enough to share with you all and see what you thought.

The idea is a kind of spraypaint for pipes. Specifically, we've noticed that having opaque pipes is extremely helpful for reducing the lag on some lower end servers, while the transparent pipes are very nice for troubleshooting a build (and seeing the actual flow of items). However, switching from transparent to opaque is tedious at the moment, and often causes things in the build to break.

My suggestion is a paintbrush/applicator - where you can spray a pipe to turn them from transparent to opaque (and potentially another item to reverse the process, which my friend is referring to as turpentine).

Hope you find the idea helpful. Thanks for the mod!

**Comment by KingLemming** [comment]
Can't be done, sorry. Just how Minecraft works.

**Comment by andrewrula** [comment]
No worries. Thought it would be a cool idea, but if it's outside the possibilities of the code, then there's nothing to do about it.

Thanks for the consideration! ^_^
