### ISSUE TITLE
Tectonic Initiator Item loss

### ISSUE THREAD

**Issue by Sonic2423** [CoFH/Feedback#508]
When using the tectonic initiator augment in a pulverizer it just checks how many items it requires on the output slot for the basic recipe. So when processing lapis with the augment it produces 13x lapis and and the automtic export just exports 8 at once so the output slot contains more and more items. when it reaches exactly 52 the machine is still processing and not exporting some of the output slot so you get only 12 lapis even with tectonic petrotheum used. same applies for everything else: eg. diamond -> 62 diamonds on output slot -> processing with the augment should give 3 diamonds but it just adds 2 till max stack size.

This also affects all recipes with augments like pyro concentrator from the induction smelter its the same:
pyro concentrator and cinnabar gives 4 ingots from eg copper but when the output slot contains 61 ingots it processes the ore giving just 3 ingots to fill the stack and also consuming 100mB blazing pyrotheum. so this seems to be a general thing.

Minecraft log doesnt give any errors neither on servor nor on client.

 Running on client as well as on dedicated server:
  forge-1.12.1-14.22.0.2444-universal
  ThermalDynamics-1.12-2.3.5.12-universal
  ThermalExpansion-1.12-5.3.5.19-universal
  ThermalFoundation-1.12-2.3.5.14-universal
  RedstoneFlux-1.12-2.0.1.2-universal
  CoFHCore-1.12-4.3.5.13-universal
  CoFHWorld-1.12-1.0.1.8-universal

**Comment by KingLemming** [comment]
Yep. Working as intended and I don't plan on special casing it.

**Comment by Sonic2423** [comment]
It consumes the liquid and gives less than it should output. if this is intended... ok.

**Comment by KingLemming** [comment]
It's intended because of how Augments work - you can slap one in mid-process. It's intended that people are supposed to use auto-output, which by the way, outputs a minimum of 16 if the machine actually has an augment.

**Comment by Sonic2423** [comment]
ok understood. but the pulverizer really outputs just 8 right after an operation. so after processing 1 ore block of lapis with tectonic initiator 5 remain in the pulverizer and 8 go to a standard itemduct which lead to a strongbox.
maybe the duct is limiting?
https://youtu.be/38XU9fIDGjw

**Comment by KingLemming** [comment]
Duct is indeed limiting. That can be changed.
