### ISSUE TITLE
[1.12 - 5.3.5 Thermal Expansion] Augment: Mycelium Substrate - Says good for Slime but isn't

### ISSUE THREAD

**Issue by VallenFrostweaver** [CoFH/Feedback#509]
You can put both spotted and brown mushrooms in as JEI states but the description of the augment states it can also be used for slime and slime cannot be inserted into the Photogenic Insolator with or without this augment.

**Comment by KingLemming** [comment]
By "slime"...what are you trying to do exactly?

**Comment by VallenFrostweaver** [comment]
Ah! I'll just slowly walk away then... I was vanilla thinking when I read slime.

**Comment by KingLemming** [comment]
Well, I should maybe clarify the tooltip somehow. Lemme think on that. BTW, JEI shows everything that the machines/augments can do. :)

**Comment by VallenFrostweaver** [comment]
I had seen the JEI options. I just thought it was a tool tip description that hadn't been fuflfilled yet and was still a wip. I didn't think about other mods.
