### ISSUE TITLE
Itemducts Fluiducts and Energy Conduits missing from 2 modpacks

### ISSUE THREAD

**Issue by Ghordath** [CoFH/Feedback#51]
I've been playing "Tekkify" and "The Kat Factory" , both of which have your mod installed but the Itemducts,Fluiducts and Energy conduits are missing from the recipe list. Makes it impossible to use your wonderful machines. Can you tell if its an error on the Modders side or did something get dropped by accident? Both are using 4.0.0B8-23

**Comment by skyboy** [comment]
The ducts are yet to be released.

**Comment by Ghordath** [comment]
Thank you for the quick reply


- Nageswarao Kilaru

"Remember, it isn't that you're paranoid; it's just they are all out to get you." 



-----Original Message-----

**Comment by bochen415** [comment]
Tekkify has EnderIO for conduits, ExtraUtilities for tranport pipes, MFR for conveyor belts and other. There's plenty of ways to transport items to/out of the wonderful machines.
