### ISSUE TITLE
Isentropic Reservoir seems too tame

### ISSUE THREAD

**Issue by jubalearly** [CoFH/Feedback#51]
I am not clear if the fuel efficiency is just amazing as its not noted but you only get a 160 boost in RF output versus 100 for a Auxiliary Transmission Coil.

**Comment by KingLemming** [comment]
It has 2x the effect of an Auxiliary Coil, so I think your comparison was done on dynamos of different levels.

Augments scale based on the level of the thing that they're going into. If the Aux Coil adds 100, the Isentropic will add 200.

So for dynamos it's 40/60/80/100/120 for "base power" - Aux Coils add "base power", Isentropic adds 2x "base power" as well as 50% efficiency. 

It's quite substantial, honestly.
