### ISSUE TITLE
[Suggestion] Phyto Grow auto-creation limitation lifted/created? Sapling output increase?

### ISSUE THREAD

**Issue by VallenFrostweaver** [CoFH/Feedback#510]
I was messing around with a build and I've tried setting up a completely automatable set up to make phyto grow and with the recent addition (thank you!) from item #496 this has made it all possible BUT I forgot to mention one other thing. I can't make the basic Phyto grow itself as there is no way of autocrafting it (just manual crafting)? Not sure if you want to go that far. It is a very complex set up and has the potential to be self sustaining but I really like where it's going. I'm currently using 10 machines to set all this up but still need a way of making the phyto grow itself from 3 different ingredients (otherwise I would suggest a compactor again which requires a maximum of 1 ingredient type).  

I do see a flaw in this though and that is the production of tree saplings being limited to 50% with the basic phyto grow and no way to increase that without processing ores for rich phyto grow or adding in your own saplings. Even if there is no change made to the creation of Phyto Grow, perhaps then instead a way of increasing the sapling output without the need for further outside sources (since it would require phyto grow be manually made or auto-crafted with another mod)? Only reason I suggest this then is that I hate in-world lag-inducing tree farms and your method seems very nice and smooth.

Just some thoughts.

**Comment by Tonius** [comment]
There is actually a way to create rich phyto-gro without processing ores. In the fluid transposer, you can infuse regular phyto-gro with 500mb of sap (obtained from oak trees) to turn it into rich phyto-gro.

**Comment by VallenFrostweaver** [comment]
Oooh. I missed that. Nice to know.

**Comment by KingLemming** [comment]
As Tonius mentioned, there is a way to make the higher Phyto-Gro. And the Cyclic Assembler is eventually coming back.
