### ISSUE TITLE
[Minefactory Reloaded] Syringe Fluids placeable in world!°

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [CoFH/Feedback#511]
I'd like to place the syringe fluids in the world or tanks. So I can quickly access them when needed and not have 10000000 syringes in my inventory.

**Comment by skyboy** [comment]
The syringes crafted with items do not have any fluid associated with them. If you need multiple, keep the raw ingredients on you to re-use the syringes instead of filling your inventory.
