### ISSUE TITLE
[1.12] [TD 2.3.5.12] Missing/incorrect duct recipes

### ISSUE THREAD

**Issue by Tonius** [CoFH/Feedback#512]
Some duct recipes are incorrect or missing completely.

Missing recipes:
- Signalum-Plated Fluiduct opaque <-> transparent
- Super-Laminar Fluiduct opaque <-> transparent
- Signalum-Plated Impulse Itemduct opaque <-> transparent
- Impulse Itemduct to Signalum-Plated Impulse Itemduct using ingots (only a recipe with nuggets is registered)
- Ditto for the opaque version

Incorrect recipes:
- Signalum-Plated Itemduct (using ingots): registered twice, one of which uses Fluiducts instead of Itemducts
- Ditto for the opaque version

**Comment by KingLemming** [comment]
I'm not sure if these are worth fixing. If it's gone on this long without being reported, clearly nobody is actually playing the mod. :/

**Comment by Tonius** [comment]
I think most of these recipes are rarely used anyway. If you need opaque/transparent ducts, it's usually easier to just craft new ones. Still, it's nice to have consistent recipes.
