### ISSUE TITLE
[1.12 Thermal Expansion 5.3.5.19] Multi-meter chat spam error

### ISSUE THREAD

**Issue by VallenFrostweaver** [CoFH/Feedback#513]
See image below when clicking on a fluiduct with a multi-meter.
![multimeter](https://user-images.githubusercontent.com/13642054/29918737-744e981c-8e3e-11e7-8361-885548200b85.png)

**Comment by KingLemming** [comment]
That's not actually an error. It's debug information. But I can see the confusion. I'll add a config option.
