### ISSUE TITLE
Thermal Dynamics + Skyfactory Crash

### ISSUE THREAD

**Issue by JakeCWolf** [CoFH/Feedback#514]
This is a persistent bug I keep getting in Skyfactory, and before you ask, yes I read to try and use only CoFH mods to see if it's a mod conflict, but what little I can gleam from the crash report says it's something to solely do with Thermal Dynamics and nothing else.

The crash happens after about 20 seconds in my world, the game closes without warning, it has something to do Thermal Dynamics servos, which in my world are currently being used in both a crucible lava farm and an automated soul sand sieve, the later of which is disabled at the moment so I think it's to do with the former.

Here's the crash report itself, before I yammer on to long and forget to put it up in the first place; http://pastebin.com/CDW7Kvr7

EDIT: Forgot to add I manually updated all Cofh mods used in Sky Factory 2 to the latest versions to see if that would solve the problem, sadly it did not, so the versions you see are not the ones used in the current version of Sky Factory 2.

**Comment by KingLemming** [comment]
It's in the Crucibles from Ex Nihilo, nothing to do with us. They know about it.
