### ISSUE TITLE
[ThermalExpansion] Inventory Crashes

### ISSUE THREAD

**Issue by rikrobots** [CoFH/Feedback#516]
Hello CoFH Team, i've made a modpack but it crashes when i open a ThermalExpansion block.
I have removed allmods and tested it with thermalExpansion, but still it crashes.
(Mod Versions: CoFHCore-[1.7.10]3.0.2-262, MineFactoryReloaded-[1.7.10]2.8.0-104, ThermalExpansion-[1.7.10]4.0.0RC7-141 and ThermalFoundation-[1.7.10]1.0.0-81)
This is the crash log:
http://pastebin.com/HE1D2zfh
I hope you see whats wrong (I tryd other versions but those didnt work at all with the modpack these vesions did work)

**Comment by KingLemming** [comment]
Version mismatches. Please make sure all your mods are on the latest versions.

**Comment by rikrobots** [comment]
Thank you! i didnt know what went wrong last time but thanks!
