### ISSUE TITLE
Using the multimeter freezes the client

### ISSUE THREAD

**Issue by wanderingmage** [CoFH/Feedback#516]
Launcher 2.0.934
Minecraft 1.12
Forge 14.21.1.2443
JDK 1.8_72
JVM Switches -Xmx4G -Xms4G -Xmn1024m -XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+UseNUMA -XX:+CMSParallelRemarkEnabled -XX:MaxTenuringThreshold=15 -XX:MaxGCPauseMillis=30 -XX:GCPauseIntervalMillis=150 -XX:+UseAdaptiveGCBoundary -XX:-UseGCOverheadLimit -XX:+UseBiasedLocking -XX:SurvivorRatio=8 -XX:TargetSurvivorRatio=90 -XX:MaxTenuringThreshold=15 -Dfml.ignorePatchDiscrepancies=true -Dfml.ignoreInvalidMinecraftCertificates=true -XX:+UseFastAccessorMethods -XX:+UseCompressedOops -XX:+OptimizeStringConcat -XX:+AggressiveOpts -XX:ReservedCodeCacheSize=2048m -XX:+UseCodeCacheFlushing -XX:SoftRefLRUPolicyMSPerMB=10000 -XX:ParallelGCThreads=10

Windows 7 ultimate SP1 x64
AMD FX 4130 Quad Core 3.8 GHz
RAM 16 GB

NVIDIA GeForce GTX 960 

Codechickenlib 3.1.2.297
CoFHCore 4.3.5.13
CoFHWorld 1.0.1.8
ThermalDynamics 2.3.5.12
ThermalExpansion 5.3.5.19
ThermalFoundation 2.3.5.14

No Crash report Client freezes when using the multimeter on fluidduct.

**Comment by KingLemming** [comment]
Yeah this doesn't actually seem to happen.

**Comment by Tahakk** [comment]
Try to replicate this only with TE and its dependencies + minimal number mods required to make that happen

**Comment by covers1624** [comment]
A log would be nice too.
