### ISSUE TITLE
[Question/Request] Rotatable Thermal Dynamics Covers

### ISSUE THREAD

**Issue by VT-14** [CoFH/Feedback#517]
![2017-09-02_10 54 48](https://user-images.githubusercontent.com/12564251/29996501-c07e2aaa-8fcd-11e7-8804-ec946940b7df.png)

On a recent 1.12.1 world I built a house with a lot of wood beams.  When I tried to hide various ducts in them I found that I could only get the covers to show with the wood logs in the vertical orientation.

Is there a way for the covers on the above picture be 'rotated' to match the vanilla logs on the left?  If there isn't one, can one please be added?

Last tried with Thermal Dynamics 1.12-2.3.5.12

**Comment by KingLemming** [comment]
Not super likely, but I'll leave it up to @covers1624 for a final verdict.

**Comment by covers1624** [comment]
Something I have been considering supporting on the backend of the new cover renderer, not entirely sure how we would implement it to the user. If it's through a new item, or sub hit boxes on the cover, or when you place them. Input on this would be nice.
