### ISSUE TITLE
[CoFHCore 3.0.2-262] Generating a geode crashes game

### ISSUE THREAD

**Issue by DaRasch** [CoFH/Feedback#518]
While working on custom ore generation I found out, that useing **"geode"** as the generator crashes the game upon world generation. This only happens if a geode is actually being created and not when the oregen is unable to find a place for generating a geode.

Code example:  
```json
{
    "gold_dense": { // Crashes world gen
        "template": {
            "type": "uniform",
            "generator": "geode",
            "crust": {"name": "Railcraft:ore", "metadata": 8} // poor gold ore
        },
        "block": "minecraft:gold_ore",
        "material": "minecraft:stone",
        "clusterSize": 32,
        "numClusters": 5,
        "chunkChance": 1,
        "minHeight": 40,
        "maxHeight": 64,
        "biomeRestriction": "none",
        "biomes": [],
        "dimensionRestriction": "blacklist",
        "dimensions": [-1, 1],
        "retrogen": false,
        "enabled": true
    }
}
```

[Pastebin of a crash report](http://pastebin.com/0CU4XdjM)

[Pastebin of mods](http://pastebin.com/6VJMEpPk)

**Comment by KingLemming** [comment]
Pretty sure this isn't actually the mod but a config issue on your end. @skyboy can probably narrow it down.

**Comment by skyboy** [comment]
You're generating 5 8x8x4 lumps of ore in every chunk and they don't align to chunk boundaries. chunkChance should not be 1, it should be 5 or 6.

No, lakes and geodes aren't currently configurable in size. Yes, they are planned to be.
