### ISSUE TITLE
Augment/upgrade loss changing dimensions [TD-1.12-2.3.5-12]

### ISSUE THREAD

**Issue by ProthosMP** [CoFH/Feedback#518]
When changing dimensions from Aroma1997s Dimensional World-1.12.1-2.0.0.0.b56 back to the overworld, machines/dynamos/duct connections/machine connections are messed up. All thermal dynamics in the Aroma Dimension are not affected. 

Examples: Dynamo losses upgrades and augments. Signalum upgrade seems not affected. Connection between energy ducts are broken. Energy cell looses upgrades and energy. All machines lose energy buffers.

**Comment by KingLemming** [comment]
This isn't caused by us. You have a mod which is wrecking NBT loads and breaking everything. Possibly Harvestcraft, as that was only just recently fixed.

Update all your mods, but I can tell you definitively this is not caused by us.
