### ISSUE TITLE
[MFR] planter not able to plant ExtrabiomesXL saplings

### ISSUE THREAD

**Issue by Paul17041993** [CoFH/Feedback#519]
Likely related to the auto-plant feature said mod has, the planter doesn't seem to recognise them as valid saplings. Haven't yet tested each one or with saplingreplanting for each set to zero but I definitely know it's present with Acacia.

**Comment by skyboy** [comment]
I'm going to have to leave this entirely to EBXL to implement on their side. I have no reliable way to auto-recognize things to plant.

**Comment by Armigus** [comment]
Actually, skyboy, you do.  The ore dictionary has an entry called treeSapling.  I can add sapling types from Witchery, ExtraBiomesXL, Extra Trees, etc. using MineTweaker.  I can also add wood types using the logWood entry and leaves using the treeLeaves entry.  All you have to do is read the entry.

This goes for the harvesters also,  If they recognized the logWood entry for logs and the treeLeaves entry for leaves to harvest then I can add log and leaf types at will.  Even unusual trees like greatwood from Thaumcraft could be supported this way.

The only thing to watch is the script timing event so you search it when all potential additions have occurred.

**Comment by skyboy** [comment]
Minetweaker doesn't work correctly, and so does not register the entries early enough for MFR to catch them.
Greatwoods are already supported.

It is ill advised for you to decide you know how minecraft works better than the people who have been working with it for several years.

**Comment by Paul17041993** [comment]
Would my assumption be correct that EBXL uses it's own class for the saplings that isn't directly compatible with how the vanilla ones work? I know they use a custom entity to auto-plant but I haven't been bothered to screw with their code to really know specifics...

**Comment by skyboy** [comment]
Auto-recognition of planting is far more complicated than is viable to implement. Harvesting is doable for a limited amount of things and has been implemented, Fertilization is hit-and-miss depending on mods using the correct interfaces, etc.

**Comment by Paul17041993** [comment]
Certainly sounds like something that needs work, may look at that with my overhawl mod assuming it sees enough development. (currently have many other things that should be done first)

**Comment by Armigus** [comment]
Then that's something I will have to bring up with Minetweaker. I wondered if the entry timing was an issue and you just revealed it as one.

**Comment by Armigus** [comment]
Are you using a custom in-house database to tell the machines what saplings, logs, leaves, and other materials are accepted by the machines?  If you were using the ore dictionary entries directly then it should not matter when changes were made.
