### ISSUE TITLE
Compressed Planks?

### ISSUE THREAD

**Issue by jubalearly** [CoFH/Feedback#52]
Trying to scale steam dynamos using the sawmill (also using tree oil for a few compression dynamos) the amount of planks being burned is pretty crazy.  A reinforced steam dynamo with two coils is going through a plank in less than a second.  

Is it possible to add some recipe to compress planks something like extra utilities and get 9x the burn time on planks?  Yes a crafter would have to be utilized but I think the overall tick rate might drop.   Not sure if its capable but maybe the new compactor block could even condense a stack of 64 planks to a single compressed plank with a burn time of 64x.

**Comment by KingLemming** [comment]
This seems reasonable although I'd want it to be a generic thing and not have to do multiple versions for the myriad of planks.

**Comment by KingLemming** [comment]
So funny thing with Steam Dynamos - you're better off using Charcoal as they have a substantial boost to it and Coal.

We can probably come up with something though.

**Comment by jubalearly** [comment]
It seems that the sawmill producing 6x planks combined with the resin refined to Tree oil and converting sawdust to charcoal , **should** produce more overall energy than simply smelting logs to charcoal.  Certainly less complex just to go with charcoal.

**Comment by KingLemming** [comment]
Oh no, it's certainly better for energy overall. Just not purely for the steam dynamo.

Also, charcoal is 32000 RF in a Steam Dynamo - that dynamo just pays a small penalty generating the initial 3/4 tank of steam, so net 30k assuming the thing constantly runs. ;)

**Comment by KingLemming** [comment]
I've decided to resolve this in an alternate manner - Planks can be Pulverized into 2 Sawdust.

So Sawmill + Pulverizer will provide 13 Sawdust per log, at the cost of 2800 RF. So if you use a Compactor (another 400 RF), then you get a total of 13 Charcoal per 9 logs, with just under a 1 Charcoal penalty. So basically +30% overall, with a tiny bit of complexity.

Factoring in fuel efficiency though, you can do a *lot* with that.
