### ISSUE TITLE
[MFR][Severe] Harvester nullptr on harvesting trees

### ISSUE THREAD

**Issue by Paul17041993** [CoFH/Feedback#520]
Spruce sapling planted by planter, harvester in usual setup, BC gold pipe placed underneath for output (actual output face left open), gave a couple bonemeal to a spruce sapling to kickstart the cycle and the server crashed.

http://pastebin.com/P6FNZZhv

edit; ok this seems to only occur when the BC gold pipe is below the harvester, and not when its behind it or no pipe attached at all.
edit 2; only seems to occur with BC pipes too, but any other system that uses inject-into-world vs inject-into-inventory (eg; chests, itemducs?) would likely be affected too. BC pipes themselves have been tested via a quarry and work fine on all directions.

extra note; there's also the extra bug in that it always extracts one or two items out the back into the air during the start of a harvest, even though itemducts or other inventories are connected elsewhere. These items will almost always be a single log and rubber if using rubber trees. I'm mentioning it here instead of making a new issue as it's likely a part of the original bug at hand.

**Comment by skyboy** [comment]
Using itemducts or chests as a buffer to buildcraft pipes will resolve the issue.

**Comment by Paul17041993** [comment]
Pretty obvious considering I already worked out it only occurs with BC pipes placed anywhere but the back hole.
