### ISSUE TITLE
ProjectRed Block Breaker is coded incorrectly

### ISSUE THREAD

**Issue by MySt1k** [CoFH/Feedback#521]
https://youtu.be/52mJVixR5mE

ProjectRed v4.6.0
ThermalExpansion-[1.7.10]4.0.1-182
forge 1.7.10-10.13.3.1388

https://github.com/MrTJP/ProjectRed/issues/786

**Comment by KingLemming** [comment]
This is 100% on ProjectRed's side.

Try TE's Terrain Smasher. You'll notice it's coded properly.

**Comment by MrTJP** [comment]
It is my understanding that the getDrops method is the only way to check for what a block drops besides actually breaking it and checking after the fact.  Should it not be implemented anyway? I'm sure this is used for other purposes too.  It only requires a few lines of code in the base block class.

**Comment by KingLemming** [comment]
getDrops is what you are supposed to use, but you have to tell it which metadata.

https://github.com/CoFH/CoFHLib/blob/master/src/main/java/cofh/lib/util/helpers/BlockHelper.java#L508

is the code that we use and there's absolutely no issue. We do use getDrops.

**Comment by MrTJP** [comment]
My mistake, I was calling setBlockToAir *before* getDrops. Sorry :P

**Comment by KingLemming** [comment]
No worries. It's a pretty common thing.
