### ISSUE TITLE
CoFHWorld does not work with "Recommended" Minecraft Forge version 2387

### ISSUE THREAD

**Issue by embik** [CoFH/Feedback#521]
I'm new to modding Minecraft in general so please bear with me, I might be doing something wrong. Your work here is greatly appreciated.

That being said it looks like CoFHWorld does not run with the "Recommended" version of Minecraft Forge (as of writing, that is `14.21.1.2387`). As - at least some - CoFHCore versions (such as `4.3.3.11`) seem to run with that version I wonder if the (hard?) requirement on Minecraft Forge `2388` is intended. If I understand correctly it is currently not possible to run Thermal Expansion with the recommended Minecraft Forge version hence.

The three crash reports for all available versions of CoFHWorld:
* CoFHWorld-1.12-1.0.0.5: [crash-2017-09-03_11.08.52-server.txt](https://github.com/CoFH/Feedback/files/1272876/crash-2017-09-03_11.08.52-server.txt)
* CoFHWorld-1.12-1.0.0.6: [crash-2017-09-03_11.05.37-server.txt](https://github.com/CoFH/Feedback/files/1272872/crash-2017-09-03_11.05.37-server.txt)
* CoFHWorld-1.12-1.0.1.8: [crash-2017-09-03_11.07.42-server.txt](https://github.com/CoFH/Feedback/files/1272875/crash-2017-09-03_11.07.42-server.txt)

Any way to get around that other than using the "latest" Forge version? Is it possible for me/you to fix this issue?

**Comment by KingLemming** [comment]
This isn't an issue at all. It doesn't require fixing. Just use a newer Forge. Forge's recommended version is extremely old and is missing LOTS of bugfixes.

**Comment by embik** [comment]
Alright, these are good reasons. Thank you for your quick answer!
