### ISSUE TITLE
[MK1.12. TD: Feature request] Integration with WAILA/HWYLA

### ISSUE THREAD

**Issue by Kilmatar** [CoFH/Feedback#522]
Is it possible to add integration with WAILA/WHYLA for TD's fluiducts/fluxducts?
In MK 1.7.10 WAILA was able to show actual ducts filling (how many RF stored in fluxducts or how many fluid is in fluiducts). Is it possible to return this back for MK 1.12?

**Comment by KingLemming** [comment]
That integration was done entirely on WAILA's end. You'll have to ask them, sorry.

**Comment by Kilmatar** [comment]
I was open ticket for HWYLA: https://github.com/TehNut/HWYLA/issues/87
TehNut close ticket with remark "Their end".
I open ticket here and you close with remark about "WAILA's end"!

C'mon guys. Please - talk with each other and resolve this problem. Please!

**Comment by KingLemming** [comment]
It's not a "problem." It's literally a feature that WAILA added in 1.7.10. And apparently the new one didn't.

**Comment by Kilmatar** [comment]
So it's really on WAILA's end?
And whowing items count in cache also?

**Comment by KingLemming** [comment]
That was also something that WAILA had on their end in 1.7.10, yes. We didn't add any special integration. You can look at the codebase - we never used a WAILA API or anything at all - it was handled entirely on WAILA's end.

They may not wish to do that going forward, and that's fine. We do support TOP, however. And TOP supports ducts out of the box, to my knowledge.

**Comment by Kilmatar** [comment]
Can you point me to TOP? Not a very good name for googling =)

**Comment by KingLemming** [comment]
The One Probe.

**Comment by Kilmatar** [comment]
The McJty mod? Wow. Thank you!

**Comment by Xiaminou** [comment]
I have to ask again, is there no chance of adding WAILA integration on your end?
