### ISSUE TITLE
[TE] Crash when shooting lamps with QuiverBow guns

### ISSUE THREAD

**Issue by Nova001Sol** [CoFH/Feedback#522]
Alright, so far I have tried this with the regular lumium lamp and the glowstone illuminator, using the sunray from QuiverBow to shoot 'em. I have posted the log here: http://pastebin.com/2tqi6byp

Domochevsky (author of QuiverBow) has also been informed of the crash, and told me this:
"As for that crash log… that ain’t my code.

cofh.thermalexpansion.block.light.BlockLight.getItemStackTag(BlockLight.java:271) <- this is where the NPE occurs, so you’ll have to hit up the maker of cofh to add an additional null check. :)
(I don’t even know what it’s trying to do there.)"

There is no permanent damage caused to the world, and reloading it works fine. The lamps in the line of fire are gone though.

**Comment by KingLemming** [comment]
Yeah we're gonna need more details as we don't know what that sunray is supposed to do.

If it's meant to destroy the block, then it's in his code and he is destroying the block and collecting the drops in the wrong order.

**Comment by Nova001Sol** [comment]
Right, should've explained that. Sorry. All weapons from QuiverBow break glass-type blocks as soon as their projectiles hit those blocks, which include, but are not limited to: vanilla glass, Extra Utilities variants and hardened glass from TE. And, as it turns out, lamps. Not redstone lamps, however, nor any other type of lamp from any of the installed mods. And I'm not sure if it helps, but various types of light-emitting glass break and drop without a crash. Would a copy of my console log help?

**Comment by KingLemming** [comment]
Yeah well, however he's doing it, he's doing it wrong. There is a correct way to break a block and about 12 incorrect ways.
