### ISSUE TITLE
Suggestion; locking button for increased ore yield

### ISSUE THREAD

**Issue by Paul17041993** [CoFH/Feedback#523]
The pulveriser and induction smelter have an augment each that allows them to use a catalyst fluid to increase their yields with ores, however the presence of the augment doesn't specifically lock them into this requirement and thus they can process ores with the basic yields. This can be problematic when the system cannot supply enough fluid at the time and you end up 'wasting' ore.

I'm suggesting a locking button, much like the ismelter's flux slot lock, that enforces the machine to only process ore when it has enough fluid present, reducing the need of somehow detecting stored fluid level and sending redstone to machines, something that's already problematic due to the amount of faces often needed (two in two out etc)...

**Comment by KingLemming** [comment]
I've decided to just change the base behavior on the machines. The fluid will be required, end of story. The lock is ultimately inelegant in the GUI, and the toggle option necessitates player interaction anyways, so the system should just default to requiring the extra resources.
