### ISSUE TITLE
[1.12] Induction smelter lacking fluid input?

### ISSUE THREAD

**Issue by Paul17041993** [CoFH/Feedback#524]
<img width="291" alt="screenshot_6" src="https://user-images.githubusercontent.com/3912867/30041993-a811a9b8-9231-11e7-850b-9decd19a64be.png">

Usually the fluid input goes through blue, but doesn't seem to in the ismelter, but neither does it with anything else, even the blank slot, so it's missing?

**Comment by KingLemming** [comment]
Any side works. Same as the Insolator.

**Comment by Paul17041993** [comment]
suddenly, my ismelter accepts the fluid, something screwy here...

**Comment by Paul17041993** [comment]
I suspect fluiducts don't connect properly simply by placing the augment into the machine, you have to wrench and re-place the machine for it to work, is the machine not sending a block update upon installation?

**Comment by JFMillerUSA** [comment]
I'm having same issue, cannot get it to work using ThermalExpansion-1.12.2-5.5.2.39-universal
