### ISSUE TITLE
[1.10.2 +] Server Lag due to Igneous Extruder

### ISSUE THREAD

**Issue by SamDaywalker** [CoFH/Feedback#525]
On our server we experienced quite some performance issues due to Igneous Extruders.

We built a small number of Resonant Igneous Extruders with 4 Auxiliary Reception Coil augments per machine. This boosted the power consumption (i.e. the speed) of the machine quite a lot (300 RF / tick per machine), however, it did not increase the production as expected due to enormous tile entity lagging which caused the server cpu load to rise drastically. The progressbar was just flickering like crazy. In fact, with only one augment the achieved output was comparable to 4 augments.

Therefore we suggest that for the Igneous Extruder the Auxiliary Reception Coil augment should be working in a comparable way as the old Batch Size augment did when inserted in an Igenous extruder, i.e. outputting more items per batch instead of increasing the working speed. The increased energy consumption may stay as it is now for balancing reasons.

We suggest a multiplicative factor of 2 for every augment, resulting in 16 items per batch for a cost of 300 RF / tick at the speed of a "plain" 60 RF/tick Resonant Igneous extruder. We feel this would be a balanced and reasonable output for such a machine.

We know, this may result in a lot of recoding, however, at the moment the current mechanic is no good use in case of an Igneous Extruder.

**Comment by KingLemming** [comment]
What's a "small number?" You better not tell me anything > 100.

Which btw, I've tested with 512 of them and there isn't any lag so what's your setup exactly?

**Comment by SamDaywalker** [comment]
There were only exactly 2 of them, directly connected (via pushing to the respective side) to an ME Matter Condenser from AE2. Might this be an issue?

**Comment by KingLemming** [comment]
AE2 may have some optimization issues. I wouldn't rule that out. You're normally running at 60% though? Hrm. :/

**Comment by SamDaywalker** [comment]
Our hoster is somehow secretive about the CPU specs. It might be a shitty CPU, that's correct. However, it shouldn't impact performance that heavily. In SSP there doesn't seem to be a problem like you explained before. 

Maybe it's just the hoster and you're not to blame. Anyway, regarding server load generally less operations per time unit should always be preferred. If it's just our server, I don't want to send you into reprogramming all that stuff, maybe we just have to switch the hoster. But considering that there are a lot of much larger servers, they might profit from less calculations in the long run.

**Comment by KingLemming** [comment]
In general, you're correct - doing everything in batches is "better," but there's a a balance between being truly optimal and having consistent gameplay. I'll look into a separate augment for mass cobblestone production, but I don't want to special case the Extruder as it stands right now.

**Comment by SamDaywalker** [comment]
Yes, you are absolutely right. I feel this would be the best way to go. If you do so, you might want to consider not allowing the auxiliary reception coil augment in the extruder. 

Thanks for your fast support :)

**Comment by KingLemming** [comment]
There's no reason to expressly disallow it, really - people may want a faster obsidian maker, for example. And it's consistent.

**Comment by SamDaywalker** [comment]
Oh, of course. I didn't remember obsidian production being not that fast. My bad.

**Comment by KingLemming** [comment]
Gonna close this for now but I have a TODO for a new augment on the backend. :)

**Comment by SamDaywalker** [comment]
BTW: We moved to a new server. Runnig much more smoothly now also with the auxiliary recepion coil upgrades ;)
