### ISSUE TITLE
[Thermal Dynamics] [Agrarian Skies 2]

### ISSUE THREAD

**Issue by whitestarx0312** [CoFH/Feedback#525]
Getting a crash when attempting to start up my server on Agrarian Skies 2.

Agrarian Skies 2: 1.0.41
Forge: forge-10.13.3.1401
CoFH Core: CoFHCore-[1.7.10]3.0.2-262
CoFH Lib: CoFHLib-[1.7.10]1.0.1-151
Thermal Dynamics: ThermalDynamics-[1.7.10]1.0.0-122
Thermal Expansion: ThermalExpansion-[1.7.10]4.0.1-182
Thermal Foundation: ThermalFoundation-[1.7.10]1.0.0-81

Log: http://pastebin.com/j5UsAL5d
*I am using FastCraft.

**Comment by KingLemming** [comment]
Looking into this. Did you just update AS2 or remove any mods?

**Comment by whitestarx0312** [comment]
Both. I updated AS2 to 1.0.41 from 1.0.39. Due to my first TD error, I had to remove the mod, let the world delete all TD items, and then I readded the mod. This fixed my first TD error, but caused this one.

**Comment by KingLemming** [comment]
Better explained in #529 

This is a result of recklessly removing mods from the install. Not saying you did, but the pack may have.
