### ISSUE TITLE
Crash with Embers Item Vacuums

### ISSUE THREAD

**Issue by EmosewaGamer** [CoFH/Feedback#526]
When an Itemduct with a servo is connected to an Item Vacuum from Embers and something is collected by it, a server crash occurs: https://pastebin.com/pppNfa8R

**Comment by KingLemming** [comment]
k. Well don't do that.

Unfortunately this may well be unresolvable, since there's a good chance that it's on Embers' end, and Embers is no longer updated, to my knowledge.

**Comment by KingLemming** [comment]
Looked over the code. This is on Embers' end - they are not correctly isolating their client and server code and are trying to do item transfer on the client, which is incorrect.
