### ISSUE TITLE
[TE] Nullifiers only accept one type at a time

### ISSUE THREAD

**Issue by Paul17041993** [CoFH/Feedback#527]
While this is normally not an issue for most setups, if one were to have a multi-tree harvesting setup with rubber trees or similar, and both the logs and rubber caches in the line of itemducts are full, the harvester can then only send either logs or rubber through the line and will have to wait for either to clear before continuing. The end result is a massive slowdown of the harvesting process and even a complete failure or mass item dump into the world, multiple nullifiers isn't ideal and logically shouldn't be necessary.

**Comment by KingLemming** [comment]
Untrue. You're using itemducts. Add a filter. Allow over sending.

**Comment by Paul17041993** [comment]
why should a filter be necessary to allow multiple simultaneous types? makes even less sense...

**Comment by KingLemming** [comment]
Because you're using Itemducts. It has nothing to do with the Nullifier.

**Comment by Paul17041993** [comment]
that doesn't answer the question, and yes I was referring to itemducts, not the nullifier...

**Comment by KingLemming** [comment]
Your issue title refers to the Nullifier; that's sort of confusing.

And the filter is required to force over-sending, as I stated. Otherwise, when an item is on the way, the slot is considered "full." That's just how it goes.

**Comment by Paul17041993** [comment]
updated then, to match the conversation context, but I still need an explanation of some sort. Otherwise it's a kinda silly idea, like adding a valve to a pipeline to let more fluid through...?

From what I can tell its a part of design optimisation to prevent excessive amounts of item rebounds and flooding in massive multi-destination setups, but there should be a better option really, especially if said kind of setups required the filters on each destination anyway. I know old redpower tubes would check and update item paths when they entered an intersection or corner and returned to the nearest source if required, though it also had a problem with flooding at one point...

**Comment by KingLemming** [comment]
Correct. It's for optimization and server protection. No, there literally isn't a better option here, sorry.

The servo is completely reasonable.

**Comment by Paul17041993** [comment]
Filters forcing items into a destination and spilling the excess into the world is a bad design idea IMO, what ever happened to back-logging to the source...? (to also prevent further excess) it makes them dodgy to use for automation systems...
![itemduct spillage](https://cloud.githubusercontent.com/assets/3912867/7717968/1908ebe8-feed-11e4-87b3-7a443e9e8ae4.png)
