### ISSUE TITLE
Steam Dynamos Question

### ISSUE THREAD

**Issue by IceBleu** [CoFH/Feedback#528]
ThermalExpansion-1.10.2-5.1.10.25
Forge-1.10.2-12.18.3.2316

Let me start off by asking a few questions just in case I don't know what I'm talking about.

Aren't steam dynamos supposed to produce RF as long as they have steam and a coolant in them? or Do they need steam/solid/coolant all at once? I thought steam dynamos were supposed to create steam from a solid fuel and turn that steam into RF right?

My steam dynamos will only create RF if there is a solid fuel in it and the fire symbol is burning but it won't produce any RF when there is just steam and water in it. Is it supposed to be this way or is this a bug? Is the steam there for a reason if it is supposed to work that way? I'm heavily confused.

**Comment by KingLemming** [comment]
Intentional. Fuel needs to be actively burning in a Steam Dynamo to produce RF. 1.12 changes up how it works a bit. You should update to the latest and greatest version. :)
