### ISSUE TITLE
Steel Blend not working in regular furnaces

### ISSUE THREAD

**Issue by Lukas45** [CoFH/Feedback#53]
Currently Steel Blend (no matter where it's made from) can only be smelted in a Tinkers Construct smeltery, TE Induction Smelter and IE Arc Furnace.
I don't hope that's intended, as it would leave a lot of other furnaces out (Vanilla, Ender IO, Mekanism mainly)

ThermalExpansion 1.10.2-2.0.0.64-universal
ThermalFoundation-1.10.2-2.0.0.64-universal
CoFHCore-1.10.2-4.0.0.127-universal

**Comment by KingLemming** [comment]
That is absolutely intended. Traditionally, Steel has always been treated as a "blast furnace" ore.

**Comment by Lukas45** [comment]
Just creates a bad interaction with Mekanism, which makes Steel by enriching Iron twice, then smelting it (normally) :)
But we'll find a way around it (CraftTweaker most likely)!

**Comment by KingLemming** [comment]
If Mekanism adds normal smelting recipes then I don't see what the problem is. It should work.

**Comment by Lukas45** [comment]
The problem is that Mekanism outputs Steel Blend from TE, which acts as TE intends it.
Of course that could be an error on our part, as we set all our ingots+dusts to default to TE, from IE.

So far, it's just TE that doesn't allow Steel Dust not to be smelted in a normal furnace - all other steel creation methods creates the ingots directly in a Blast Furnace (apart from Mekanism that is), where you then can Dust the ingot, and back again through normal crushers/smelters. And as far as I can see, TEs method of creating steel is by mixing the dusts together, THEN Blast Furnace it (hard to tell with our many steel variants)
Our other Steel Dust variants (although not used now) are: Base Metals, Mekanism, libVulpes, Extreme Reactors and Immersive Engineering

**Comment by KingLemming** [comment]
Hrm...if that's the case I'm willing to change it up. I don't use steel at all, so that's kind of whatever. Consider it addressed. :)

**Comment by Lukas45** [comment]
The workaround for TEs case would probably be to use the Induction Smelter to require the Ingots + Coal (Dust perhaps?) directly, instead of just the dust (and then removing the Steel Dust recipes), to keep the Blast Furnace element of it.
Just a thought :)

**Comment by KingLemming** [comment]
That's exactly what I'm doing.
