### ISSUE TITLE
CoFHCore Build 279 crashes!

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [CoFH/Feedback#530]
Crashes with latest core: http://hastebin.com/idahowojiy.1c

**Comment by KingLemming** [comment]
This is a Forge change. They're enforcing a specific versioning scheme and probably shouldn't be.

**Comment by Unrepentant-Atheist** [comment]
Because I like using bleeding edge builds? Anything wrong with it?

**Comment by KingLemming** [comment]
Just the nature of how those builds are made - things get committed, it auto-builds and pumps out an alpha.

If you're going to use them, be aware they may or may not work at all, and if they don't, please don't report it.

**Comment by Unrepentant-Atheist** [comment]
'kay. Got it. Won't report then on alpha builds :P. Beta builds fine? Or just release builds? :D
