### ISSUE TITLE
[1.12 Thermal Expansion v5.3.5.19] Sawdust to Compressed Sawdust missing in Compactor - Storage

### ISSUE THREAD

**Issue by VallenFrostweaver** [CoFH/Feedback#530]
Currently, I cannot place sawdust into a compactor to make compressed sawdust. Thought this was an obvious thing to be able to do but it is not. Not sure if as intended, a bug/feature, or my facepalm.

**Comment by KingLemming** [comment]
It's a peculiarity due to 1.12.

**Comment by Leowbattle** [comment]
It is probably because compressed sawdust only uses 8 sawdust instead of 9, which is what the compacter checks for.
