### ISSUE TITLE
[Thermal Dynamics][Suggestion] Duct Upgrader

### ISSUE THREAD

**Issue by calebmennen** [CoFH/Feedback#531]
So you've built a large system and you have a large amount of ducts connecting everything. Unfortunately, you need better ducts for your needed throughput, but don't want to replace them all by hand, instead, you use the Duct Upgrader. 

What this block would do at it's most core level would be:
- have the block physically connect to a point in the network
- specify within the interface the duct to be replaced, and the duct to replace with

This is probably to unbalanced to leave it at that, so my suggestions would be:
- an energy cost for each upgrade
- that cost could be variable depending on the upgrade you are making, i.e. leadstone to hardened fluxduct costs less than hardened to redstone, which is less than leadstone to redstone fluxduct.
- maybe the trade off of automating the upgrade is you don't get your old ducts back.

Some additional functionality could be:
- configuring the order in which the ducts are upgraded i.e. upgrade the ducts that are furthest, closest or random
- for duct upgrades that are purely-crafting (i.e. adding glass to make non-opaque) you could just supply the materials and it would apply the upgrade in-place. 
  - this could be balanced by having this feature work with the cyclic assembler

**Comment by KingLemming** [comment]
Sorry, no.

There's simply too much going on under the hood to make this really feasible and due to the nature of Minecraft, there are too many places this could go horribly wrong, even if our code were *perfect.*
