### ISSUE TITLE
[1.12 Thermal Dynamics v2.3.5.12] Item/Fluid transport not working for Fluxducts. Removed?

### ISSUE THREAD

**Issue by VallenFrostweaver** [CoFH/Feedback#531]
According to your wiki (and I swear I saw this on a previous version tool-tip but it's gone now):

"Fluxducts are blocks added by Thermal Dynamics. They transport Redstone Flux between blocks that can store, generate or use RF. **_There are several types of Fluxducts, they can double as an Itemduct, or a Fluiduct._**"

Fluxducts behave normally for all power applications. Are the Fluxducts supposed to double as item/fluid ducts anymore or is this removed? I cannot get them to connect to inventories/tanks and they don't transport between machines or accept item/fluid servos/retrievers/etc. I also did not find any notes in the updates to call this change out so I thought I'd post here.

**Comment by Tonius** [comment]
The information on the wiki is the wrong way around. There are itemducts and fluiducts that can double as fluxducts (the signalum-plated ones).

The wiki for TD is a bit outdated anyway, it'll hopefully get updated sometime soon.

**Comment by VallenFrostweaver** [comment]
Ah! Thank you so much for that.
