### ISSUE TITLE
Steam dynamo not passing power to machine

### ISSUE THREAD

**Issue by jimmyh77** [CoFH/Feedback#532]
Using a steam dynamo connected to a pulverizer will stop passing power unless the dynamo is burning fuel.

CoFHCore-[1.7.10]3.0.2-262
CoFHLib-[1.7.10]1.0.2-160
ThermalExpansion-[1.7.10]4.0.1-182
ThermalDynamics-[1.7.10]1.0.0-122

http://imgur.com/kDT0tSI

http://imgur.com/1THqNIF

http://imgur.com/JOtdNpb

P.S Using it without the lead fluxduct doesn't make a difference.

**Comment by KingLemming** [comment]
Yup. This is how dynamos work. The buffer is there for feedback purposes. It's not free energy storage.
