### ISSUE TITLE
game crashes after installing railcraft

### ISSUE THREAD

**Issue by pcking99** [CoFH/Feedback#532]
Hello. My game crashes in loading mods after installation of Railcraft. It crashes on step 3 of 7 when loading minecraft engine. It crashes at modelling. the crash is random on forge loading.
MC: 1.10.2
Railcraft: 10.2.0
CoFH core: 4.1.11.16 Universal
Log: https://www.dropbox.com/s/60ebwnv6l58s2mm/crash-2017-09-07_14.44.25-client.txt?dl=0

**Comment by KingLemming** [comment]
Okay. Better let Railcraft know. We literally aren't in that log.

**Comment by pcking99** [comment]
I found out its Thermal Expansion that is messing with railcraft.

**Comment by covers1624** [comment]
No, this is the MFR phantom milk bucket issue. check their tracker for updates.

**Comment by pcking99** [comment]
Looks like updating Thermal Expansion worked.
Went from ThermalExpansion-1.10.2-5.1.9.23-universal to ThermalExpansion-1.10.2-5.1.10.25-universal
Now the game will start with Railcraft installed.
