### ISSUE TITLE
auto output for tesseracts feature request

### ISSUE THREAD

**Issue by Sailren** [CoFH/Feedback#533]
hello team cofh,

is it possible to make tesseracts auto output to adjacent inventories? this idea came to me this morning and i wrote it in my calender so i dont forget it to ask. 

it could be something like this: http://abload.de/img/tesseractqir4u.jpg

**Comment by KingLemming** [comment]
They already do. I don't understand what you're asking.

**Comment by Sailren** [comment]
they do? could i connect them to a fermenter for example w/o using any cables and such and this thing would work?

**Comment by KingLemming** [comment]
...yes. The Tesseract can't tell the difference between a duct/pipe/whatever or a machine. It just sees something that accepts energy, fluid, or items.
