### ISSUE TITLE
Redstone Flux API Mod causes tile entities to stop working

### ISSUE THREAD

**Issue by darkphan** [CoFH/Feedback#534]
When a chunk that has tile entities (such as a vanilla furnace) gets unloaded (can be done by going to the nether and waiting a bit then coming back) vanilla furnaces will not function until you break them and replace them. This goes for any machine/duct from thermal expansion and many other TE's from other mods.

(Not sure if this was the right place to report this but RedstoneFlux didn't have an issues page to report it at)

**Comment by KingLemming** [comment]
No. It doesn't. It literally can't cause this. What you're seeing is 100% the fault of something else.

**Comment by darkphan** [comment]
I create a new instance, with only RedstoneFlux. I move away from spawn, place a furnace down, make a nether portal, go into the nether and wait a bit, then go back to the overworld and the furnace does not work. I remove RedstoneFlux and the issue goes away. Put redstone flux in and it is repeatable 100% of the time.

**Comment by KingLemming** [comment]
And I'm telling you that it absolutely cannot be caused by the Redstone Flux API. It straight up can't.

**Comment by darkphan** [comment]
Ok, well I will get you video proof then.

**Comment by KingLemming** [comment]
Video "proof" or not, this literally isn't a thing that can possibly happen as a result of having the Redstone Flux API installed. The API is only an API, nothing more. It doesn't inject code into any tile entities or anything else. Mods have to actively choose to integrate with it.

**Comment by darkphan** [comment]
Yeah, after some more testing by some folks it does seem to be related to forge after build 2450 of forge. It was strange that I was not able to reproduce it without anything for many attempts, I must not have been waiting long enough for the chunk to unload. Hope you can see why it appeared at first to be the Redstone Flux API at first (it baffled me too).
