### ISSUE TITLE
Machine&Pipe Settings reset by reconnect or reentering the dimension

### ISSUE THREAD

**Issue by Petrisis** [CoFH/Feedback#535]
I got simple setup of Leadstone Fluxducts, a basic energy cell, pulverizer and redstone furnace. After leaving the Nether, all ducts where unconnected to each other, the energy cell has basic settings (Input/Output = 0 RF/t) and my hardened portable Tank full of lava is now empty. This error occurs every time i relog now or i leave nether.

If you need any logs, ... pls comment this. Maybe its a known bug or i forgot to add some mods

**Comment by KingLemming** [comment]
This is caused by another mod which shreds NBT and corrupts your world. It's not us. HarvestCraft used to do this but has been patched.

Update everything, only advice I have for you. But I 100% know it isn't us.
