### ISSUE TITLE
phytogenetic Insolator configuring sides with AE attatched to side crashes server.

### ISSUE THREAD

**Issue by Virezz** [CoFH/Feedback#535]
Hi,
I got a server crash when toggling the configurations of a phytogenetic Insolator
http://pastebin.com/RQWXrP50

Crashed when i have a config like this:
https://imgur.com/a/FwMcT
and changed the export bus side in the configuration "tab" in the interface.

**Comment by KingLemming** [comment]
Duplicate of #475.
