### ISSUE TITLE
Suggestion: CoFH World - Ore Generation Exclusion Zone

### ISSUE THREAD

**Issue by trabpukcip** [CoFH/Feedback#536]
An idea that I have floating around in my head is to have an ore generation exclusion zone.
It would centered on either the dimensions spawn or an XY coordinate in combination with a circular or square block radius, perhaps rounded off to chunks for performance.

This could have a couple of applications:
• Allow ores to spawn in "The End", but they are only accessible once players get to the outer islands, preventing the main island from being mined to death, potentially screwing up dragon respawns.
• Have no ores in starting areas, encouraging players to explore beyond spawn to get ores.

**Comment by Dulciphi** [comment]
Distance from origin? Have blacklist/whitelist. Good entity spawners and structure generators have this setting. It may have extra complications for ore gen that I'm oblivious to, but the option works very well for structures and entity spawns.
