### ISSUE TITLE
[1.12] CoFH world - World Generation crash involving custom fractal ore generation (java.lang.NoClassDefFoundError: net/minecraft/world/World$2)

### ISSUE THREAD

**Issue by BBoldt** [CoFH/Feedback#537]
Description:
I'm attempting to create a huge amount of different fractal ore veins for a custom modpack. It was going well at first, but I think I may have hit some sort of limit somewhere, and it started crashing during initial world generation. I've tried to provide as much information as possible, if there is anything else I can do, let me know.

* Forge 2474
* CoFHCore-1.12-4.3.5.13-universal
* CoFHWorld-1.12-1.0.1.8-universal
Full modlist: https://gist.github.com/e882429954be4a667974c47c205f8cba

Crash Report: https://gist.github.com/5272d60064506de9ee6f83f8416025c8
Full log: https://gist.github.com/56d768cf78abd1b6139d289a168c6831

Custom world config.
04_ores_overworld.json: https://gist.github.com/187d36a8f5ce98ae83e791de0ac0d083

**Comment by KingLemming** [comment]
You're out of memory. You'll have to adjust your parameters to values where this doesn't happen.

No, I don't have those numbers offhand as every machine is different and modpacks make this a giant headache to debug.

But basically, you're trying to generate things which are way too enormously large.

**Comment by BBoldt** [comment]
Okay, thank you.

**Comment by BBoldt** [comment]
Anybody finding this issue in the future, here is my updated config file with reduced values resulting in a game that doesn't crash:

https://gist.github.com/8f6f5069af693b67a8245d5496ae6556
