### ISSUE TITLE
Glowstone Illuminator max/max/max is read by client as Yellow / default colour on login

### ISSUE THREAD

**Issue by m0rgs** [CoFH/Feedback#538]
Minor bug

If you set max colour on each slider, until the client logs out they will appear white. 

Client relogs, they will appear yellow (default colour).

If you set, say 256 / 256 / 255, the client will retain the colour as white.

Was wondering why my white Illuminators kept turning yellow.

Cheers

n.b. I don't know if the max setting is actually numerically 256, replace 256 for whatever the max setting is, the numbers do not appear in my UI anymore.

Versions:

ThermalDynamics-[1.7.10]1.0.0-122
ThermalExpansion-[1.7.10]4.0.1-182
ThermalFoundation-[1.7.10]1.0.0-81
CoFHCore-[1.7.10]3.0.2-262
CoFHLib-[1.7.10]1.0.2-160
Forge 10.13.2.1352

**Comment by KingLemming** [comment]
...why do the numbers not appear in your UI?

**Comment by m0rgs** [comment]
Ha, I don't know. They used to. I just figured it was something I had done to my installation. I often change mods and don't recall what I did at the time they disappeared.

Here's a screenshot. http://imgur.com/U4uxsxN

Here's a list of mods: http://pastebin.com/Sjnw5FZV
