### ISSUE TITLE
Suggestion: Blazes should not die from Blazing Pyrotheum

### ISSUE THREAD

**Issue by mankra** [CoFH/Feedback#538]
I built a Pyrotheum trap with a Blaze spawner in the center, but the Blazes get hurt from the Pyrotheum and die. This should not happen to fire elementals, or is it intended?

**Comment by KingLemming** [comment]
I agree. They shouldn't. This seems to be the result of a change Forge made to the fluid system. Basically, they're treating ALL fluids as water in addition to what they actually are, which is...probably incorrect.

I've adjusted the pyrotheum block to get around their incorrect assumptions. :)

**Comment by Leowbattle** [comment]
I think that the elementals should get hurt by every other elemental liquid but their own one.
e.g.
Basalz: Aerotheum, Pyrotheum, Cryotheum
Blitz: Pyrotheum, Petrotheum, Cryotheum
