### ISSUE TITLE
Thermal Dynamics + Inventory tweaks dupe glitch 1.10.2

### ISSUE THREAD

**Issue by thedarkcolour** [CoFH/Feedback#539]
I put a stack of eight empty cryo flux ducts in my inventory, and placed all my filled ones (without opening inventory) and it autorefilled with the empty ones. But when I go back into my inventory, there is the stack of filled ones on my cursor. I can place them and break them, so they are not ghost copies.

**Comment by KingLemming** [comment]
I'm going to need a video of this...there are just too many variables. I need to know what you're interacting with, modlist, etc.

**Comment by thedarkcolour** [comment]
Modlist: UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2422.jar) 
	UCHIJAAAA	Forge{12.18.3.2422} [Minecraft Forge] (forge-1.10.2-12.18.3.2422.jar) 
	UCHIJAAAA	Aroma1997Core{${version}} [Aroma1997Core] (Aroma1997Core-1.9.4-1.1.1.2.jar) 
	UCHIJAAAA	NotEnoughItems{2.1.3.220} [Not Enough Items] (NotEnoughItems-1.10.2-2.1.3.220-universal.jar) 
	UCHIJAAAA	OpenEye{0.8} [OpenEye] (OpenEye-1.10.2-0.8.jar) 
	UCHIJAAAA	openmodscore{0.11.2} [OpenModsLib Core] (minecraft.jar) 
	UCHIJAAAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJAAAA	foamfixcore{7.7.4} [FoamFixCore] (minecraft.jar) 
	UCHIJAAAA	ccl-entityhook{1.0} [ccl-entityhook] (CodeChickenLib-1.10.2-2.5.9.283-universal.jar) 
	UCHIJAAAA	cofhcore{4.1.12} [CoFH Core] (CoFHCore-1.10.2-4.1.12.17-universal.jar) 
	UCHIJAAAA	actuallyadditions{1.10.2-r105} [Actually Additions] (ActuallyAdditions-1.10.2-r105.jar) 
	UCHIJAAAA	JEI{3.14.7.420} [Just Enough Items] (jei_1.10.2-3.14.7.420.jar) 
	UCHIJAAAA	AppleCore{2.2.2} [AppleCore] (AppleCore-mc1.10.2-2.2.2.jar) 
	UCHIJAAAA	appleskin{1.0.8} [AppleSkin] (AppleSkin-mc1.10.2-1.0.8.jar) 
	UCHIJAAAA	Aroma1997CoreHelper{1.1.1.2} [Aroma1997Core|Helper] (Aroma1997Core-1.9.4-1.1.1.2.jar) 
	UCHIJAAAA	AromaBackup{1.0.1.1} [AromaBackup] (AromaBackup-1.9.4-1.0.1.1.jar) 
	UCHIJAAAA	AromaBackupRecovery{1.0} [AromaBackup Recovery] (AromaBackup-1.9.4-1.0.1.1.jar) 
	UCHIJAAAA	Quark{r1.1-70} [Quark] (Quark-r1.1-70.jar) 
	UCHIJAAAA	AutoRegLib{1.0-2} [AutoRegLib] (AutoRegLib-1.0-2.jar) 
	UCHIJAAAA	CodeChickenLib{2.5.9.283} [CodeChicken Lib] (CodeChickenLib-1.10.2-2.5.9.283-universal.jar) 
	UCHIJAAAA	avaritia{${mod_version}} [Avaritia] (Avaritia-1.10.2-2.2.7-universal.jar) 
	UCHIJAAAA	Baubles{1.3.11} [Baubles] (Baubles-1.10.2-1.3.11.jar) 
	UCHIJAAAA	bdlib{1.12.4.24} [BD Lib] (bdlib-1.12.4.24-mc1.10.2.jar) 
	UCHIJAAAA	BetterAchievements{0.3.3.10} [Better Achievements] (BetterAchievements-1.10.2-0.3.3.10.jar) 
	UCHIJAAAA	betterbuilderswands{0.11.1} [Better Builder's Wands] (BetterBuildersWands-1.10.2-0.11.1.220+f8232fe.jar) 
	UCHIJAAAA	biometweaker{2.3.239} [BiomeTweaker] (BiomeTweaker-1.10.2-2.3.239.jar) 
	UCHIJAAAA	guideapi{@VERSION@} [Guide-API] (Guide-API-1.10.2-2.0.3-46.jar) 
	UCHIJAAAA	BloodMagic{1.10.2-2.1.11-80} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.10.2-2.1.11-80.jar) 
	UCHIJAAAA	bookshelf{1.4.4.347} [Bookshelf] (Bookshelf-1.10.2-1.4.4.347.jar) 
	UCHIJAAAA	Botania{r1.9-341} [Botania] (Botania r1.9-341.jar) 
	UCHIJAAAA	BotaniaVisualizer{1.10.2-1.0} [BotaniaVisualizer] (BotaniaVisualizer-1.10.2-1.0.jar) 
	UCHIJAAAA	brandonscore{2.1.12} [Brandon's Core] (BrandonsCore-1.10.2-2.1.12.130-universal.jar) 
	UCHIJAAAA	mantle{1.10.2-1.1.5.205} [Mantle] (Mantle-1.10.2-1.1.5.jar) 
	UCHIJAAAA	tconstruct{1.10.2-2.6.5.10} [Tinkers' Construct] (TConstruct-1.10.2-2.6.5.jar) 
	UCHIJAAAA	ceramics{1.10.2-1.1.6b} [Ceramics] (Ceramics-1.10.2-1.1.6b.jar) 
	UCHIJAAAA	Chameleon{1.10.2-2.3.0} [Chameleon] (Chameleon-1.10.2-2.3.0.jar) 
	UCHIJAAAA	chancecubes{1.10.2-3.0.1.204} [Chance Cubes] (ChanceCubes-1.10.2-3.0.1.204.jar) 
	UCHIJAAAA	ChestTransporter{2.5.18} [Chest Transporter] (ChestTransporter-1.10.2-2.5.18.jar) 
	UCHIJAAAA	CodeChickenCore{2.4.1.102} [CodeChicken Core] (CodeChickenCore-1.10.2-2.4.1.102-universal.jar) 
	UCHIJAAAA	ChickenChunks{2.2.0.52} [ChickenChunks] (ChickenChunks-1.10.2-2.2.0.52-universal.jar) 
	UCHIJAAAA	chickens{4.3.2} [Chickens] (chickens-4.3.2.jar) 
	UCHIJAAAA	chisel{MC1.10.2-0.0.14.32} [Chisel] (Chisel-MC1.10.2-0.0.14.32.jar) 
	UCHIJAAAA	cyclopscore{0.10.9} [Cyclops Core] (xCyclopsCore-1.9.4-0.10.9.jar) 
	UCHIJAAAA	colossalchests{1.6.0} [Colossal Chests] (ColossalChests-1.10.2-1.6.0.jar) 
	UCHIJAAAA	commoncapabilities{1.3.3} [CommonCapabilities] (CommonCapabilities-1.9.4-1.3.3.jar) 
	UCHIJAAAA	cookingforblockheads{4.2.45} [Cooking for Blockheads] (CookingForBlockheads_1.10.2-4.2.45.jar) 
	UCHIJAAAA	crafttweakerjei{1.0.1} [CraftTweaker JEI Support] (CraftTweaker-1.10.2-3.0.26.jar) 
	UCHIJAAAA	MineTweaker3{3.0.26} [MineTweaker 3] (CraftTweaker-1.10.2-3.0.26.jar) 
	UCHIJAAAA	ctgui{1.0.0} [CT-GUI] (CraftTweaker-1.10.2-3.0.26.jar) 
	UCHIJAAAA	creeperconfetti{1.3} [Creeper Confetti] (creeperconfetti-1.2.1.jar) 
	UCHIJAAAA	ctm{MC1.10.2-0.2.2.24} [CTM] (CTM-MC1.10.2-0.2.2.24.jar) 
	UCHIJAAAA	cxlibrary{1.2.4} [CXLibrary] (cxlibrary-1.10.2-1.2.4.jar) 
	UCHIJAAAA	darkutils{1.1.8.finalrc2} [Dark Utilities] (DarkUtilities-1.1.8.finalrc2.jar) 
	UCHIJAAAA	dimensionalcake{0.0.1} [Dimensional Cake] (dimensionalcake-1.9.4-0.0.1.jar) 
	UCHIJAAAA	draconicevolution{2.1.6} [Draconic Evolution] (Draconic-Evolution-1.10.2-2.1.6.263-universal.jar) 
	UCHIJAAAA	EnderBags{2.0.1} [EnderBags] (EnderBags-1.9.4-2.0.0.jar) 
	UCHIJAAAA	endercore{1.10.2-0.4.1.66-beta} [EnderCore] (EnderCore-1.10.2-0.4.1.66-beta.jar) 
	UCHIJAAAA	EnderIO{1.10.2-3.1.193} [Ender IO] (EnderIO-1.10.2-3.1.193.jar) 
	UCHIJAAAA	EnderStorage{2.2.1.106} [EnderStorage] (EnderStorage-1.10.2-2.2.1.106-universal.jar) 
	UCHIJAAAA	valkyrielib{1.10.2-0.10.6} [Valkyrie Lib] (valkyrielib-1.10.2-0.10.6.jar) 
	UCHIJAAAA	environmentaltech{1.10.2-0.10.6b} [Environmental Tech] (environmentaltech-1.10.2-0.10.6b.jar) 
	UCHIJAAAA	exnihiloadscensio{0.1.5} [Ex Nihilo Adscensio] (exnihiloadscensio-1.10.2-0.1.20.jar) 
	UCHIJAAAA	excompressum{2.0.97} [Ex Compressum] (ExCompressum_1.10.2-2.0.97.jar) 
	UCHIJAAAA	extrautils2{1.0} [Extra Utilities 2] (extrautils2-1.10.2-1.6.1.jar) 
	UCHIJAAAA	zerocore{1.10.2-0.1.0.6} [Zero CORE] (zerocore-1.10.2-0.1.0.6.jar) 
	UCHIJAAAA	bigreactors{1.10.2-0.4.5.30} [Extreme Reactors] (ExtremeReactors-1.10.2-0.4.5.30.jar) 
	UCHIJAAAA	farmingforblockheads{1.1.16} [Farming for Blockheads] (FarmingForBlockheads_1.10.2-1.1.16.jar) 
	UCHIJAAAA	foamfix{@VERSION@} [FoamFix] (foamfix-0.7.1-anarchy.jar) 
	UCHIJAAAA	forgemultipartcbe{2.0.0.38} [Forge Multipart CBE] (ForgeMultipart-1.10.2-2.0.0.38-universal.jar) 
	UCHIJAAAA	microblockcbe{2.0.0.38} [Forge Microblocks] (ForgeMultipart-1.10.2-2.0.0.38-universal.jar) 
	UCHIJAAAA	minecraftmultipartcbe{2.0.0.38} [Minecraft Multipart Plugin] (ForgeMultipart-1.10.2-2.0.0.38-universal.jar) 
	UCHIJAAAA	mcmultipart{1.4.0} [MCMultiPart] (MCMultiPart-1.4.0-universal.jar) 
	UCHIJAAAA	ftbl{0.0.0} [FTBLib] (FTBLib-1.1x-3.6.5.jar) 
	UCHIJAAAA	ftbu{0.0.0} [FTBUtilities] (FTBUtilities-1.1x-3.6.5.jar) 
	UCHIJAAAA	GardenOfGlass{sqrt(-1)} [Garden of Glass] (GardenOfGlass.jar) 
	UCHIJAAAA	advgenerators{0.9.20.23} [Advanced Generators] (generators-0.9.20.23-mc1.10.2.jar) 
	UCHIJAAAA	grue{1.3.5} [Grue] (Grue-1.9.4-1.3.5.jar) 
	UCHIJAAAA	hammercore{1.9.4.3} [Hammer Core] (HammerCore-1.10.2-1.9.4.3.jar) 
	UCHIJAAAA	hatchery{0.3.20} [Hatchery] (hatchery-1.10.2-0.3.20.jar) 
	UCHIJAAAA	theoneprobe{1.4.18} [The One Probe] (theoneprobe-1.1x-1.4.18.jar) 
	UCHIJAAAA	immersiveengineering{0.10-61} [Immersive Engineering] (ImmersiveEngineering-0.10-61.jar) 
	UCHIJAAAA	immersivepetroleum{1.1.3} [Immersive Petroleum] (immersivepetroleum-1.10.2-1.1.3.jar) 
	UCHIJAAAA	LunatriusCore{1.1.2.38} [LunatriusCore] (LunatriusCore-1.10.2-1.1.2.38-universal.jar) 
	UCHIJAAAA	InGameInfoXML{2.8.1.89} [InGame Info XML] (InGameInfoXML-1.10.2-2.8.1.89-universal.jar) 
	UCHIJAAAA	mtlib{@VERSION@} [MTLib] (MTLib-1.0.3.jar) 
	UCHIJAAAA	initialinventory{1.0.1} [InitialInventory] (InitialInventory-1.0.1.jar) 
	UCHIJAAAA	integrateddynamics{0.7.12} [Integrated Dynamics] (IntegratedDynamics-1.10.2-0.7.12.jar) 
	UCHIJAAAA	integratedtunnels{1.2.5} [Integrated Tunnels] (IntegratedTunnels-1.10.2-1.2.5.jar) 
	UCHIJAAAA	InventoryPets{1.4.9.6} [Inventory Pets] (inventorypets-1.10-1.4.9.6.jar) 
	UCHIJAAAA	inventorytweaks{1.61-58-a1fd884} [Inventory Tweaks] (InventoryTweaks-1.61-58.jar) 
	UCHIJAAAA	ironbackpacks{1.10.2-2.2.31} [Iron Backpacks] (IronBackpacks-1.10.2-2.2.31.jar) 
	UCHIJAAAA	ironchest{1.10.2-7.0.15.804} [Iron Chest] (ironchest-1.10.2-7.0.15.804.jar) 
	UCHIJAAAA	ItsRainingFood{1.0.2} [It's Raining Food] (itsrainingfood-1.10.2-0.1.0.jar) 
	UCHIJAAAA	journeymap{1.10.2-5.4.6} [JourneyMap] (journeymap-1.10.2-5.4.6.jar) 
	UCHIJAAAA	je_calculation{1.10.2-2.6.4} [Just Enough Calculation] (JustEnoughCalculation-1.10.2-2.6.4.jar) 
	UCHIJAAAA	jeresources{0.5.8.98} [Just Enough Resources] (JustEnoughResources-1.10.2-0.5.8.98.jar) 
	UCHIJAAAA	kleeslabs{3.3.5} [KleeSlabs] (KleeSlabs_1.10.2-3.3.5.jar) 
	UCHIJAAAA	levels{3.0.2} [Levels 3] (Levels 3-1.10.2-3.0.2-beta.jar) 
	UCHIJAAAA	lootbags{2.3.9} [Loot Bags] (LootBags-1.10.2-2.3.9.jar) 
	UCHIJAAAA	minefactoryreloaded{2.9.0B1} [MineFactory Reloaded] (MineFactoryReloaded-[1.10.2]2.9.0B1-226.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatVanilla{2.9.0B1} [MFR Compat: Vanilla] (MineFactoryReloaded-[1.10.2]2.9.0B1-226.jar) 
	UCHIJAAAA	mob_properties{1.0.3} [Mob Properties] (mob_properties-1.10.2-1.0.3.jar) 
	UCHIJAAAA	mob_grinding_utils{0.1.8.22} [mob_grinding_utils] (MobGrindingUtils-0.1.8.22.jar) 
	UCHIJAAAA	modtweaker{2.0.13} [Mod Tweaker] (ModTweaker2-2.0.13.jar) 
	UCHIJAAAA	thermalfoundation{2.1.5} [Thermal Foundation] (ThermalFoundation-1.10.2-2.1.5.12-universal.jar) 
	UCHIJAAAA	morechickens{1.1.6} [More Chickens] (MoreChickens-1.10.2-1.1.6.jar) 
	UCHIJAAAA	MoreFurnaces{1.8.6} [More Furnaces] (MoreFurnaces-1.10.2-1.8.6.jar) 
	UCHIJAAAA	mousetweaks{2.8} [Mouse Tweaks] (MouseTweaks-2.8-mc1.10.2.jar) 
	UCHIJAAAA	MrTJPCoreMod{2.0.1.20} [MrTJPCore] (MrTJPCore-1.10.2-2.0.1.20-universal.jar) 
	UCHIJAAAA	mysticalagriculture{1.5.8} [Mystical Agriculture] (mysticalagriculture[1.10.2]-1.5.8.jar) 
	UCHIJAAAA	mysticalagradditions{1.0.3} [Mystical Agradditions] (mysticalagradditions[1.10.2]-1.0.3.jar) 
	UCHIJAAAA	mysticalmfrcompat{1.0.0} [Mystical MFR Compat] (mysticalmfrcompat[1.10.2]-1.0.0a.jar) 
	UCHIJAAAA	natura{1.10.2-4.1.0.80} [Natura] (natura-1.10.2-4.1.0.80.jar) 
	UCHIJAAAA	Neat{1.3-12} [Neat] (Neat 1.3-12.jar) 
	UCHIJAAAA	nethercore{1.10.2-2.0.3} [Nether Core] (nethercore-1.10.2-2.0.3.jar) 
	UCHIJAAAA	netherportalfix{1.0} [NetherPortalFix] (NetherPortalFix_1.10.2-3.3.6.jar) 
	UCHIJAAAA	notenoughwands{1.5.5} [Not Enough Wands] (notenoughwands-1.1x-1.5.5.jar) 
	UCHIJAAAA	openmods{0.11.2} [OpenModsLib] (OpenModsLib-1.10.2-0.11.2.jar) 
	UCHIJAAAA	openblocks{1.7.2} [OpenBlocks] (OpenBlocks-1.10.2-1.7.2.jar) 
	UCHIJAAAA	oreexcavation{1.2.102} [OreExcavation] (OreExcavation-1.2.102.jar) 
	UCHIJAAAA	p455w0rdslib{1.0.13} [p455w0rd's Library] (p455w0rdslib-1.10.2-1.0.13.jar) 
	UCHIJAAAA	harvestcraft{1.10.2j} [Pam's HarvestCraft] (Pam's HarvestCraft 1.10.2j.jar) 
	UCHIJAAAA	progressiveautomation{1.7.4} [Progressive Automation] (ProgressiveAutomation-1.10.2-1.7.4.jar) 
	UCHIJAAAA	projectred-core{4.8.4.49} [ProjectRed Core] (ProjectRed-1.10.2-4.8.4.49-Base.jar) 
	UCHIJAAAA	projectred-integration{4.8.4.49} [ProjectRed integration] (ProjectRed-1.10.2-4.8.4.49-integration.jar) 
	UCHIJAAAA	projectred-transmission{4.8.4.49} [ProjectRed Transmission] (ProjectRed-1.10.2-4.8.4.49-integration.jar) 
	UCHIJAAAA	projectred-illumination{4.8.4.49} [ProjectRed Illumination] (ProjectRed-1.10.2-4.8.4.49-lighting.jar) 
	UCHIJAAAA	rainboaks{1.0.2} [Rainbow Oak Trees] (RainbowOaks-1.10-1.0.2.jar) 
	UCHIJAAAA	thermalexpansion{5.1.10} [Thermal Expansion] (ThermalExpansion-1.10.2-5.1.10.25-universal.jar) 
	UCHIJAAAA	redstonearsenal{2.1.3} [Redstone Arsenal] (RedstoneArsenal-1.10.2-2.1.3.8-universal.jar) 
	UCHIJAAAA	StorageDrawers{1.10.2-3.7.10} [Storage Drawers] (StorageDrawers-1.10.2-3.7.10.jar) 
	UCHIJAAAA	refinedstorage{1.2.26} [Refined Storage] (refinedstorage-1.2.26.jar) 
	UCHIJAAAA	refined_avaritia{1.0} [Avaritita and Refined Storage] (refined_avaritia-1.10.2-1.0.jar) 
	UCHIJAAAA	xreliquary{1.10.2-1.3.3.664} [Reliquary] (Reliquary-1.10.2-1.3.3.664.jar) 
	UCHIJAAAA	rftools{6.13} [RFTools] (rftools-1.1x-6.13.jar) 
	UCHIJAAAA	rftoolsdim{5.05} [RFTools Dimensions] (rftoolsdim-1.1x-5.05.jar) 
	UCHIJAAAA	roots{0.208} [Roots] (roots-0.208.jar) 
	UCHIJAAAA	SimpleAchievements{MC1.9.4-1.2.2-28} [Simple Achievements] (SimpleAchievements-MC1.9.4-1.2.2-28.jar) 
	UCHIJAAAA	simplegenerators{1.10.2-0.10.6a} [Simple Generators] (simplegenerators-1.10.2-0.10.6a.jar) 
	UCHIJAAAA	simplyjetpacks{2.1.3.55} [Simply Jetpacks 2] (SimplyJetpacks2-1.10.2-2.1.3.55.jar) 
	UCHIJAAAA	SkyLandsForge{1.10.2_0.0.1pre} [SkyLandsForge] (SkyLandsForge-1.10.2_0.0.2pre.jar.jar) 
	UCHIJAAAA	snad{1.10.2-1.6.09.20a} [Snad] (Snad-1.10.2-1.6.09.20a.jar) 
	UCHIJAAAA	solarfluxreborn{2.17r} [Solar Flux Reborn] (SolarFluxReborn_1.10.2-2.17r.jar) 
	UCHIJAAAA	rscircuits{1.0.4} [Super Circuit Maker] (SuperCircuitMaker-1.0.4.jar) 
	UCHIJAAAA	beneath{1.2.0} [The Beneath] (The Beneath-1.10.2-1.2.0.jar) 
	UCHIJAAAA	augmentedvoid{1.0} [Augment of the Void] (TheAugmentedVoid-1.0  MC1.10.2.jar) 
	UCHIJAAAA	thermaldynamics{2.0.11} [Thermal Dynamics] (ThermalDynamics-1.10.2-2.0.11.17-universal.jar) 
	UCHIJAAAA	TickProfiler{1.10.2-jenkins.59} [TickProfiler] (TickProfiler-1.10.2-jenkins.59.jar) 
	UCHIJAAAA	tinkertoolleveling{1.10.2-1.0.1.DEV.f5def58} [Tinkers Tool Leveling] (TinkerToolLeveling-1.10.2-1.0.1.jar) 
	UCHIJAAAA	tp{1.2.3} [Tiny Progressions] (tinyprogressions-1.10.2-1.2.3a.jar) 
	UCHIJAAAA	ts2k16{1.0.3} [Twerk-Sim 2K16] (TS2K16-1.0.3.jar) 
	UCHIJAAAA	voidislandcontrol{1.1.7} [Void Island Control] (voidislandcontrol-1.1.7.jar) 
	UCHIJAAAA	waterstrainer{1.4.2} [Water Strainer] (WaterStrainer-1.9.4-1.4.2.jar) 
	UCHIJAAAA	wcg{1.0.0} [Wireless Crafting Grid] (WirelessCraftingGrid-1.10.2-1.0.0.jar) 
	UCHIJAAAA	Woot{1.10.2-1.4.1} [Woot] (woot-1.10.2-1.4.1.jar) 
	UCHIJAAAA	wrcbe{2.0.0} [WirelessRedstone-CBE] (WR-CBE-1.10.2-2.0.0.18-universal.jar) 
	UD	BiomeTweakerCore{2.3.239} [BiomeTweaker Core] (minecraft.jar)

**Comment by thedarkcolour** [comment]
Ooops, the update fixed it nvm :(
