### ISSUE TITLE
Energy Cells charge when in your Inventory in Survival mode

### ISSUE THREAD

**Issue by itanshi** [CoFH/Feedback#539]
COFH Core: 3.0.2
TE: 4.0.1
Forge: 10.13.3.1395
Survival, no other inventory, anywhere (no wireless chargers), multiplayer (Sky Factory 2)

I mean to provide a video when I have time. Thank you.

**Comment by KingLemming** [comment]
Okay so I'm quite sure this doesn't actually happen, but please, let's see the video.

**Comment by itanshi** [comment]
http://youtu.be/dSBwXohsgqo Here you go :)

**Comment by KingLemming** [comment]
Sounds like something with your setup that you simpjy aren't aware of. Cells have no code that fires on tick in inventory.

Something is charging them.

**Comment by skyboy** [comment]
This is a result of one of the other mods that has some manner of charger freaking out and charging things regardless. Best of luck finding it, I guess? At least there shouldn't be too many mods that do such a thing.
