### ISSUE TITLE
Misgendered Hammers

### ISSUE THREAD

**Issue by bookerthegeek** [CoFH/Feedback#54]
http://i.imgur.com/dcoYZrv.png

Seems that the Hammers have the Sickle texture

CoFHCore-1.10.2-4.0.1.137-universal
ThermalExpansion-1.10.2-5.0.1.73-universal
ThermalFoundation-1.10.2-2.0.1.68-universal

**Comment by KingLemming** [comment]
Hah. Wrong textures. Sorry bout that.

**Comment by bookerthegeek** [comment]
Thank you for the quick fix.
