### ISSUE TITLE
Enderio item conduit / Tesseract crash

### ISSUE THREAD

**Issue by Wykks** [CoFH/Feedback#54]
crash log : http://pastebin.com/tdZL1YnT

Unfortunately I don't know exactly how it happened
May be related to :
https://github.com/CrazyPants/EnderIO/commit/e3e707bd0a8ecf15baa171f7d8c24372dbec96d4

**Comment by skyboy** [comment]
This crash can only occur as a result of another mod having illicitly altered the Tesseract's internal state. It probably wasn't EIO, but I can do nothing to help find what mod did it.
