### ISSUE TITLE
[Thermal Dynamics] [Feature Request] Make ore dependency optional

### ISSUE THREAD

**Issue by vanceza** [CoFH/Feedback#540]
I'd love to use Thermal Dynamics in my modpack, but I'm currently unwilling to because it pulls in non-standard ores. (I also have no interest in any power mechanics, just looking for a good item transport system.) Is there a way to make non-standard ores optional, and use vanilla-only recipes? Maybe it's even possible to have graceful fallback in the case that Thermal Foundation is absent?

Would be willing to write a patch to get this done if that helps.

**Comment by KingLemming** [comment]
You can already do this. Thermal Foundation is required, but you can disable the ore gen.

You can then use another mod to add recipes that you want for the ducts.

Given that this is possible, there's no pressing need to build it into the mod, as the new recipes would still generate complaints.

**Comment by vanceza** [comment]
I'm not suggesting the new recipes be enabled by default. I'm suggesting a
"useVanillaRecipes=false" in the config which can be switch to 'true'. I can use something like Minetweaker as a workaround, agree it's not urgent. (Minetweaker causes horrible crashes in conjunction with NEI in a lot of cases in conjunction with CoFH mods, unfortunately.)

**Comment by KingLemming** [comment]
I understand what you're asking. People will still complain, and it's way easier said than done of course.

**Comment by vanceza** [comment]
The minecraft community is silly that way. Feel free to close if it shouldn't be done. If you do want it done, like I said if you grant me code access and I'll submit a patch so you don't have to do any work.

**Comment by KingLemming** [comment]
We've gone back and forth on this and ultimately there are too many variables for us to get it "right" in such a way that it'd satisfy everyone.

So in this case, I'll just recommend Minetweaker. If you use it correctly (NEVER reload configs), then there shouldn't be any crashing.
