### ISSUE TITLE
[Thermal Foundation] Forge Lexicon destroys items in the GUI when closing it

### ISSUE THREAD

**Issue by N-kay** [CoFH/Feedback#540]
### Info
Minecraft version: 1.12.1
Mod version: ThermalFoundation-1.12-2.3.5.14
Modpack: ATM3 v3.2b

### Actual Behavior:
The Lexicon, in transmutation mode, destroys items left in either slot when closing the GUI.

### Expected Behavior:
Leave the items in the slots or put them in your inventroy.

**Comment by KingLemming** [comment]
This doesn't actually happen, I just tested.

The items do correctly go back into your inventory. If there is no room in your inventory, they are dropped on the ground.

If you are in Creative Mode, then picking up the dropped items with a full inventory will automatically destroy them. This is vanilla Minecraft behavior and has nothing to do with our mod.

**Comment by N-kay** [comment]
Thanks for investigating, must be some mod interaction then.
