### ISSUE TITLE
[1.12] [Thermal Dynamics] Fluxducts break across chunk boundaries.

### ISSUE THREAD

**Issue by JaSpr** [CoFH/Feedback#541]
I have had to repeatedly break and replace a specific flux duct multiple times.  Once even after I was just AFK and standing next to it.

### VERSIONS
Thermal Dynamics: 2.3.5.12
Minecraft: 1.12.1
Forge: 14.22.1.2478
PACK: All The Mods 3, v3.2b
CofH Core: 4.3.5.13, CofH World: 1.0.1.8
Thermal Foundation: 2.3.5.14, Thermal Expansion: 5.3.5.19

[screenshots](https://imgur.com/a/aFicT)

**Comment by KingLemming** [comment]
No, they don't. This is caused by a mod you have smashing the NBT stack on save/load and generally screwing things up. Unfortunately, I can't tell you which one it is, sorry. :(

**Comment by JaSpr** [comment]
Thanks!
