### ISSUE TITLE
cannot craft Augment: Stabilized Frame

### ISSUE THREAD

**Issue by NoX-programer** [CoFH/Feedback#541]
I don't have Magical Crops mod in my custom modpack so Rockwool is uncraftable so that augment is uncraftable. When I hit R on the rockwool NEI only shows re-color recipe from rockwool of other colors, but not how to craft rockwool itself.

Versions:
CoFHCore-[1.7.10]3.0.2-262
ThermalDynamics-[1.7.10]1.0.0-122
ThermalExpansion-[1.7.10]4.0.1-182
ThermalFoundation-[1.7.10]1.0.0-81

**Comment by Entoarox** [comment]
Put slag in a furnace, slag is gained from smelting things in the induction smelter.

**Comment by NoX-programer** [comment]
Thanks for advice. I hope, mod developers will add such tooltip to rockwool.

**Comment by Entoarox** [comment]
If you check light gray or gray rookwool it should show the furnace recipe in NEI, although I agree that the COFH team should look into making it so the smelting recipe shows up no matter what color rookwool you click in NEI, to make it easier to find out.

**Comment by KingLemming** [comment]
No can do. That's entirely on NEI.

**Comment by Entoarox** [comment]
@KingLemming Isnt there a way to trick NEI for this exact purpose? I could swear there are mods out there that do so...

**Comment by NoX-programer** [comment]
Entoarox, if he say than it is. What he can do is tooltip on rockwool... if he deems it necessary.

**Comment by KingLemming** [comment]
There's no way to trick NEI, but a tooltip is fair. :)
