### ISSUE TITLE
A problem when using servos in round-robin mode

### ISSUE THREAD

**Issue by unikmhz** [CoFH/Feedback#543]
After upgrade to thermal dynamics 2.3.5.12 I noticed that some machines became idle. After poking around I managed to reduce everything to a somewhat minimal test setup. The problem seems to be related to servos operating in round-robin mode.

Consider the following setup:
![resized-setup-overview](https://user-images.githubusercontent.com/4131711/30524982-9b7b800a-9c06-11e7-9935-868004249384.png)

Configuration of pulverizer:
![resized-pulverizer](https://user-images.githubusercontent.com/4131711/30524986-b42ba936-9c06-11e7-84ea-787b115e193b.png)

Configuration of pulverizer servo:
![resized-pulverizer-servo](https://user-images.githubusercontent.com/4131711/30524998-e42676ca-9c06-11e7-971c-7016a14466a1.png)

Configuration of smelter:
![resized-smelter](https://user-images.githubusercontent.com/4131711/30525002-f15965aa-9c06-11e7-8900-7ec5b060217d.png)

Servo attached to creative cache:
![resized-chache-servo](https://user-images.githubusercontent.com/4131711/30525004-05f821b8-9c07-11e7-8da5-4b11f8ae873b.png)

Filter attached to smelter:
![resized-smelter-filter](https://user-images.githubusercontent.com/4131711/30525022-471d19dc-9c07-11e7-9c75-a34351218ebd.png)

Servo attached to smelter:
![resized-smelter-servo](https://user-images.githubusercontent.com/4131711/30525029-55823e80-9c07-11e7-9f9e-17b51b3a6e83.png)

Filter attached to output cache:
![resized-output-filter](https://user-images.githubusercontent.com/4131711/30525056-cd4c0504-9c07-11e7-8871-73c41082cf49.png)

After enabling everything and telling servos to ignore redstone, the servos on the left grabbed one stack of iron from the creative cache, and a bit of pulverized coal. After that, everything halted.

If I switch the mode of the servos to nearest-first, for example, they work just fine. But sometimes round-robin is what one wants ;)

No processing was running when these screenshots were taken. Original problem didn't involve induction smelters, but I wanted to not involve fluids in the mix, so as to minimize the test setup. Similar setup worked fine in 2.3.4.

Version info: MC 1.12.1.
Pack: FTB Unstable (2.0.1 with TD 2.3.4.11 works fine, 2.0.4 with TD 2.3.5.12 exhibits this problem).
Forge: 2478.
Platform: Linux 64-bit, Oracle JDK 1.8.0_144.
Mode tested under: single-player (survival and creative).

Can provide further info, logs and/or world file.

**Comment by KingLemming** [comment]
Round-robin was actually *fixed* in that update, so I'm going to need a video of this to actually understand what's going on.

**Comment by unikmhz** [comment]
Figuring out OBS is tough, but I managed it.
Video is here: https://drive.google.com/open?id=0B9UsRYhOquevcFRJalQ5aXV3RVU
Sorry for aspect ratio and lack of sound, never recorded anything before.

**Comment by KingLemming** [comment]
Yeah, can replicate this now. Easiest fix is probably just going to be removing round robin altogether. It's a largely worthless mode and the corner cases involved here mean that it's probably not worth fixing.

I recommend you not rely on it, honestly.
