### ISSUE TITLE
MineTweaker/ModTweaker support no longer functional

### ISSUE THREAD

**Issue by Timeslice42** [CoFH/Feedback#543]
MineTweaker/ModTweaker support no longer works on thermal expansion machines (such as the transposer/crucible/etc.) AllowRecipeOverwrite is set to true in the Thermal Expansion common.cfg, the minetweaker scripts are correct, and there are no errors in the minetweaker logfile (in fact, no message at all is printed for operations such as Transposer.removeFillRecipe). I was told that TE recipe changes won't work with MineTweaker because TE needs the changes before postInit and MineTweaker does its thing in postInit. Is this a fixable issue?

This problem has existed and been reported since february, and has been bounced around/slipped through the cracks all this time. Can someone work with @jaredlll08 and/or @stanhebben so we can get some traction on this?

**Comment by KingLemming** [comment]
We're adding json recipe handling so that Minetweaker won't be necessary. The way that it does things isn't ideal and we'd really prefer people didn't use it.

**Comment by jaredlll08** [comment]
ModTweaker is forced to do what it does because of minetweaker, I would love to just use IMC, but minetweaker reads scripts too late

**Comment by Timeslice42** [comment]
Good enough. Thanks guys!

Are we talking weeks or months for json recipes?

**Comment by KingLemming** [comment]
Weeks probably. The code is actually in place, just have to test it.

However, I'm swamped with important stuff and Minecraft is basically on the bottom of the list for the next month.
