### ISSUE TITLE
[CoFHCore] will not load

### ISSUE THREAD

**Issue by Dracon27** [CoFH/Feedback#544]
Whenever I try to add CoFH core to my mods, I get an error saying I need an older version of Forge.  However, when I downgrade forge, forge retaliates and says I need a newer version.  I really want to use the CoFH mods but they're the only ones making a fuss :(

![mod list](https://cloud.githubusercontent.com/assets/12582621/7787333/51066a4a-01d4-11e5-919d-f27f233930c9.JPG)

![launcher](https://cloud.githubusercontent.com/assets/12582621/7787334/54bdfd4c-01d4-11e5-96a9-7dbbf879adab.JPG)

![error](https://cloud.githubusercontent.com/assets/12582621/7787335/58faef82-01d4-11e5-9e2c-c682925d3c9d.JPG)

![launcher2](https://cloud.githubusercontent.com/assets/12582621/7787336/5c73def8-01d4-11e5-8612-1f06be2c0af0.JPG)

![error 2](https://cloud.githubusercontent.com/assets/12582621/7787337/5dce58a0-01d4-11e5-8313-71aa55916861.JPG)

**Comment by KingLemming** [comment]
This is something specific to your combination of mods. Unfortunately, too many things use parts of CoFH and can cause this if improperly coded.

So essentially, you have to debug your modpack. Possibly check our IRC for help, but this isn't a code problem.

**Comment by Dracon27** [comment]
Okay, I'll test some combinations.

**Comment by Dracon27** [comment]
My apologies, I found the problem mods!  I didn't realized the inconsistencies :(
