### ISSUE TITLE
Vivecraft Crash issue

### ISSUE THREAD

**Issue by XiloTheOdd** [CoFH/Feedback#544]
so after getting bored with some of my other VR games, decided to try VR minecraft, wanted to go back and use some of my favorite mods and if they didn't work to help in anyway!

The Issue: i've been able to use the latest version of almost all the thermal mods save for 2 using vivecraft, Expansion, and Dynamics. as for the cause: https://pastebin.com/Vfmb4VeM  there is a crash log but a basic explanation it fails to tessellate blocks from either Expansion or Dynamics individually. i've dropped out any other mods that were working to ensure these 2 were the cause. as for what blocks are causing it i dont have a clue, forge barely gets out of phase 1 before it crashes back to launcher.

if any more info is needed i'll happily supply it.

**Comment by KingLemming** [comment]
Sorry, but we just aren't in that crash log trace at all. It's on Vivecraft's end.

**Comment by XiloTheOdd** [comment]
thought i'd mention when i asked them this problem is fixed in an unreleased build

**Comment by KingLemming** [comment]
Of Vivecraft? Excellent.
