### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by greatblitz982** [CoFH/Feedback#545]
I'm using the dev versions of the following mods, to test my mod alongside your mods.

ThermalFoundation-[1.7.10]1.0.0-85-dev
ThermalExpansion-[1.7.10]4.0.0-176-dev
CoFHCore-[1.7.10]3.0.2-282-dev

So when I hit the run/debug button, it starts MC up just fine, but when I try to create/load a world, this crash pops up.

Googling said error only brings up more pastebins of the same error:
http://tinyurl.com/l2qelo2

**Comment by greatblitz982** [comment]
I also use this as an api: https://github.com/CoFH/RedstoneFlux-API

**Comment by KingLemming** [comment]
You need to properly set up your environment with access transformers. Forge modding 101. Please check the Forge forums for how to do that.

**Comment by Mitchellbrine** [comment]
(This is a duplicate of #400)

I know it's too late, but CCC will fix it, @greatblitz982
