### ISSUE TITLE
Silicon in pulveriser

### ISSUE THREAD

**Issue by Carbon-Ghost** [CoFH/Feedback#546]
We need a config for that, as this is really annoying with other mods that adds more complex ways to make silicon, and modtweaker can't disable it :c 

Sorry if it's already here and I missed it ;P

**Comment by KingLemming** [comment]
Modtweaker can't do a lot of things. I wish people would stop trying, it just breaks the mod.

I'll consider it.

**Comment by Carbon-Ghost** [comment]
I know it break the mod, as it adds hacky ways to support other mods, anyway thanks, will close this.

**Comment by Carbon-Ghost** [comment]
Nice King ;)
