### ISSUE TITLE
Retrievers with "total items in inventory" limits ignore items already en-route

### ISSUE THREAD

**Issue by AffableLemon** [CoFH/Feedback#546]
Reinforced, Signalum and Resonant retrievers can be configured with a limit on "total items in inventory", which is great.

Unfortunately, they continue pulling items until the target inventory reaches the limit, regardless of how many items are already on the way. This often results in bouncing many excess items back in the itemducts, depending on the time it takes for the items to reach the target inventory. 

It would be great if these retrievers could prevent "over-pulling", similar to the way filters and servos can prevent "over-sending".

Demo video illustrating the problem:
[Thermal_Dynamics_Retriever.zip](https://github.com/CoFH/Feedback/files/1311951/Thermal_Dynamics_Retriever.zip)

Noticed using:
* Minecraft 1.10.2
* Thermal Dynamics 2.0.1.10 (2.0.7)
* (in pack FTB Beyond v1.11.0, if that matters)

Thanks for reading, and thanks for all your great mods. :)

**Comment by KingLemming** [comment]
I'll see if this can be mitigated somehow, but it's not very likely, to be honest.

And it absolutely won't be addressed for any version prior to 1.12.
