### ISSUE TITLE
Rendering issue (aesthetic)

### ISSUE THREAD

**Issue by sefldron** [CoFH/Feedback#547]
I raised this issue with tic as well.
 Constantan fluid does not render properly in the world at all. Cannot pour from a bucket into the world also does not render during casting with tic. Item is still produced but it just looks funny. (Does not effect any gameplay as far as I can see so far)

**Comment by KingLemming** [comment]
Just checked on this. It renders properly in Fluiducts and Tanks, so the rendering error is not on our end. This is a TiC problem.
