### ISSUE TITLE
TD covers cannot be created using MFR blocks

### ISSUE THREAD

**Issue by Towdium** [CoFH/Feedback#547]
It seems most of MFR constructing blocks cannot be accepted to creat Thermal Dynamic covers.
I tried other blocks in different mods, they all works well, except MFR.
Using Agrarian Skies 2, version 1.1.1
CoFH mods are all up-to-date
I also tried alpha version of TD, it still doesn't work
Sorry for my bad English :)

**Comment by KingLemming** [comment]
Correct. Just how Minecraft works, it's a rendering limitation.
