### ISSUE TITLE
Suggestion 

### ISSUE THREAD

**Issue by sefldron** [CoFH/Feedback#548]
Add either a way to drain the fluid transposer or a smaller container for the leftovers. I always seem to be ending up with something leftover in my transposers unless it is filled completely or with even 1000 mb increments. Small container could be applied for minting coins or anything else. 
 Breaking the machine empties them upon replacement though.

**Comment by KingLemming** [comment]
I'm pondering something for this, but honestly I just can't think of many situations where this happens in any meaningful way.

Basically any use of the Transposer is now in 1000 mB increments. Where are you encountering this?

**Comment by sefldron** [comment]
I have my magma crucibles connected to transposers. I'm thinking that it is happening during transport from one machine to the other? Straight to a tank I don't believe this ever happens..I need to double check and make sure nothing is modifying my output amounts from solid items.

**Comment by sefldron** [comment]
A block of nickel just gave me 1296 mb of fluid... something seems funny.

**Comment by KingLemming** [comment]
That is the correct TiC amount.

**Comment by sefldron** [comment]
With large quantities of fluid and with automation I am always getting this. 296 leftover in the machine every time. I'll mess around with a large amount and see just to make sure. I guess this is more of an ocd thing for those who don't want to waste a single drop. I get that way sometimes. Not really an issue or anything since I cannot play without cofh in my game. I just feel so sad for those 4 or 5 nuggets I could have.

**Comment by sefldron** [comment]
Just a thought but could always add detection for the transposer or magma crucibles to know if they are connected to a smeltery drain for complete emptying?

**Comment by KingLemming** [comment]
...they will push any amount of fluid out of the machine automatically, not just 1000 mB amounts.

**Comment by sefldron** [comment]
Didn't know that was already there. Have not tried it yet sorry and thank you.

**Comment by KingLemming** [comment]
Oh no worries. The initial point about the Fluid Transposer is still something I need to address. Propably a pipette item or something.

**Comment by sefldron** [comment]
It's all a matter of math for the last 296 left. I can get it manually by adding 44 nuggets into it (facepalm)

**Comment by KingLemming** [comment]
But...you understand that the Transposer can eject into adjacent Tanks or Ducts, right? It just needs to be set to Extract mode and it'll push Fluid out.

**Comment by sefldron** [comment]
I know. I just don't have a lot of space where everything is and I don't want to move the chests next to it right now.. gotta build a new room but there is a lava pool next to the room so I gotta solidify it first.
