### ISSUE TITLE
[Minefactory Reloaded] Unifier not working?

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [CoFH/Feedback#548]
Not sure if it's intended or not. But a while ago, I used to be able to convert mob essence (MFR) and liquid XP (Ender IO) back and forth with the Unifier.

Now I can't. On top of that Mariculture's "Molten Experience" can't be converted either in mob essence or liquid XP with the unifier.

**Comment by KingLemming** [comment]
So for things like this - just questions - it's really better that you use IRC.

**Comment by Unrepentant-Atheist** [comment]
Cheers! Will do.

**Comment by skyboy** [comment]
EIO XP and MFR XP have never been compatible within MFR.
