### ISSUE TITLE
[Thermal Foundation] Swim on fire

### ISSUE THREAD

**Issue by Exy-mat** [CoFH/Feedback#549]
I recently observed that swimming in Blazing Pyrotheum and after in Cryotheum do not cause the fire extinction.
This is probably nothing, I would like see this bug fixed
Thanks

**Comment by KingLemming** [comment]
It's not necessarily a bug. Cryotheum is COLD, it isn't WET. ;)

Fire can burn in cold environments.

**Comment by Exy-mat** [comment]
But it's a cold fluid no ? Why dive into a cold fluid could not we turn off when we are on fire?

**Comment by KingLemming** [comment]
Air is a fluid. Is it wet? :)

Also, the nature of Cryotheum means that you absolutely should not EVER want to jump into it. If you're seriously in a situation where that's a good idea, I should probably up the damage. It's supposed to be extremely lethal.

**Comment by Carbon-Ghost** [comment]
But cryotheum is composed of 25% of water, right ? ( I have seen the recipe ) ^.^

**Comment by Exy-mat** [comment]
So swimming in a frozen *liquid* based with water will never extinguish you ?
Le 26 mai 2015 9:26 PM, KingLemming <notifications@github.com> a écrit :Air is a fluid. Is it wet? :)

Also, the nature of Cryotheum means that you absolutely should not EVER want to jump into it. If you're seriously in a situation where that's a good idea, I should probably up the damage. It's supposed to be extremely lethal.

**Comment by KingLemming** [comment]
Humans are 70% water and they catch on fire just fine.

**Comment by Exy-mat** [comment]
No, you can't burn thé flesh when you are alive

**Comment by Exy-mat** [comment]
Try to set yourself on fire, only your skin will burn

**Comment by Carbon-Ghost** [comment]
*Don't try to set yourself on fire

*When someone is on fire, only his skin burn 

;) xD

Another argument is that if we follow your logic, cryotheum is near absolute zero cold, now a fire needs energy, combustible and a comburant  ? Dunno how it's in english, use google translate it's french, basically "Comburant" = oxygen to burn, now logically, when you are in cryotheum, only your skin burns, there is 2x less comburant if you are standing in one block of cryo, and the heat of the fire very quickly goes to the cryo if we follow the second thermodynamic law, extinguishing fire as there is more energy loss than gain, not being able to sustain the heat level required to light up fire. 

Logically speaking ofc ;)

**Comment by Exy-mat** [comment]
Does this means you're for the cryotheum extinguishes fire ?

**Comment by Carbon-Ghost** [comment]
Yes, because it's logic ^.^

**Comment by KingLemming** [comment]
Closing this down. I'm not sure which way I'm going to go on it yet, but I don't consider it an actual issue.

Most probably is that Cryotheum will extinguish you in the future by instantly killing you.

**Comment by Carbon-Ghost** [comment]
Configurable like always ? :D
