### ISSUE TITLE
[REQUEST] Steel Dust Config

### ISSUE THREAD

**Issue by SynfulChaot** [CoFH/Feedback#55]
For those that are running packs with more restricted ways of making Steel Ingots, such as IE's Blast Furnaces, would it be possible to get a config to disable the Steel Dust recipe?  I recall that the 1.7.10 versions had that feature.

**Comment by KingLemming** [comment]
So, just to point something out - at the moment, Steel Dust can't be utilized in most furnaces, as explained in issue #53 so it's probably not as big of an issue as you might think.

I've already come up with how I'm going to handle this - I'm not going to start doing configs for everything under the sun. That isn't happening and it saps my will to live.

What I am going to do is remove the dust-making recipe entirely, although the Induction Smelter will still have Ingot Creation as something it can do using Iron and Charcoal/Coal. If you don't want that, them you can MineTweaker it away.

Eventually, TE machines will have crafting jsons (it's pretty close, tbh) and will handle their recipes using those.

**Comment by HenryRichard** [comment]
You could also use CraftTweaker to edit recipes.

**Comment by SynfulChaot** [comment]
I know, but it's always worthwhile to inquire regarding official support before jumping to alternate solutions.
