### ISSUE TITLE
Request for Thermal Expansion!

### ISSUE THREAD

**Issue by Wolfseverest93** [CoFH/Feedback#55]
Lately I've found myself not only having too much energy to really EVER run out of, while playing survival mode without any cheats, as well as really wishing i could have block based weaponry of some sort, even if it has to be a multi-block structure. So my request today is for you guys to at least eventually add block weapons like lasers, railguns, thrusters (I say thruster because I want it to be a giant block that shoots a huge amount of fire much like a thruster and has to use liquid fuels such as railcraft's creosote oil, buildcraft's oil, BC fuel, TE's liquid pyrotheum, and the fuel type should reflect in damage as best as possible), but mostly if not all of it I would to be guns that use RF proportionately as they should be more on the tech side of weaponry. Another type of block based weapon I'd like would be trap like structures, hidden blades that shoot in and out of blocks to damage victims, trap vortexes that teleport players to a random location in any random dimension that already exists in the world save, implosion devices, why didn't i mention explosives? tnt covers that despite being too messy for my liking. Autonomous as well as manned guns, if not having them capable of both under a reasonable balance. Please and thank you! If you guys want the one who made the request to come up with the block images, it might take me some time since I'm often busy, but I can do it. I'm sure you can understand the functionality I requested of them being as they are well...cannons and traps... I really hope to hear back on this some time. And I will have patience.

**Comment by skyboy** [comment]
Can you separate that out into paragraphs? It's somewhat difficult to read it all.

**Comment by Wolfseverest93** [comment]
Sorry about that, last time I posted a request to anyone was well over a year ago so I lost my knack for keeping it neat.

In a nutshell, my request is for block weapons and traps, there are so many player held weapons as is, it's ridiculous. And I've been dying to have a world that's like a tower defense of sort. But I haven't found any mods with what I'm looking for weapon wise, they're all "TNT this" "Bigger TNT that" or else they are player held weapons.

I want the good stuff, autonomous weapons that can be mounted by their owners (the player that placed them, like how if players lock their strongboxes only they can use them or break them), hidden blades inside of blocks that can be modeled to copy the texture of a corresponding block crafted with the original trap block so it can actually be hidden.

Energy based gun structures, "frying chamber" trap structures, vortex traps that warp the victim to a random location in any dimension that is in the world save at the time of the trap springing, multi-block weapons that have variant effects based on the size and shapes and where the gap/gaps face (whether its diagonal, horizontal, vertical, or it lacks a gap),

I hope this is easier to understand.

**Comment by JakeJeremy** [comment]
There is a mod for that: http://www.curse.com/mc-mods/minecraft/224663-openmodularturrets

**Comment by Wolfseverest93** [comment]
JAKE YOURE A LIFE SAVER MAN I WAS LOOKING FOR THAT KIND OF MOD EVER SINCE 1.6.4 CAME OUT WITH NO AVAIL THEN YOU CAME ALONG!!! THANK YOU SO MUCH!!!

**Comment by bochen415** [comment]
@Skyboy um... reopened? What are your plans with this? I like it.
*dreams about weaponry in Thermal Expansion*

**Comment by Wolfseverest93** [comment]
@skyboy oh boy, sounds like skyboy realized just as i did, the modular turrets mod and my request are two different things. modular turrets are simple singleblock craftable objects. whereas my request here is of a multiblock reliant weaponry. meaning the shape you build the weaponry into greatly affects their weapon attack type and damage. should i give this more detail skyboy?

**Comment by KingLemming** [comment]
Won't be doing this one, at least not in TE.
