### ISSUE TITLE
[TE4] Transporation Plane and Endermen

### ISSUE THREAD

**Issue by Yusunoha** [CoFH/Feedback#550]
I've come across this little problem while playing the 1.1.1 version of Agrarian Skies 2.
the transporation place seems to refure teleporting endermen downwards, but it only happens with downwards.

if I use the impulse plate the endermen can be moved, and the other modes of the transporation place also seem to work fine on endermen, it's only downwards that the transporation place seems to refuse to work.

and it only happens with endermen, or from what I've noticed so far, because I'm using the transportation place in a mobfarm

here's some screenshots showing the mobfarm I have build
http://i.imgur.com/AA03ydG.png http://i.imgur.com/WMCtYf6.png http://i.imgur.com/DgwSgTn.png

do note the transporation place still refuses to teleport endermen without the impulse plates.

**Comment by KingLemming** [comment]
The plate shouldn't actually teleport them at all.

They're Endermen; they have control over that sort of thing.

**Comment by Yusunoha** [comment]
that's a real shame, as it'd be a really efficient way of moving entities around, if it worked on all entities including endermen
