### ISSUE TITLE
[1.12 ThermalExpansion 5.3.4.16] Unable to handle CoFH packet!

### ISSUE THREAD

**Issue by Unikron** [CoFH/Feedback#550]
When I leave my Base and come back after a while or from the Nether (chunk was Unloaded). Most of the Machines / Ducts ... are not connected any more, Tanks are empty, and so on. (Meta information lost?)
I'm playing in a havy modded game. The modpack is FTB Unstable 1.12 v2.0.1 112 files in /mods/
https://www.feed-the-beast.com/projects/ftb-unstable-1-12/relations/dependencies
Minecraft game output is 4 times (number of chunks with TE stuff):
`
14:35:56 | FML | main | error | Unable to handle CoFH packet!
-- | -- | -- | -- | --

14:35:56 | STDERR | main | info | [cofh.core.network.PacketHandler:handleNBTPacket:177]: java.lang.ArrayIndexOutOfBoundsException: 0

14:35:56 | STDERR | main | info | [cofh.core.network.PacketHandler:handleNBTPacket:177]: 	at cofh.thermalexpansion.block.TileAugmentableSecure.setLevel(TileAugmentableSecure.java:101)

14:35:56 | STDERR | main | info | [cofh.core.network.PacketHandler:handleNBTPacket:177]: 	at cofh.thermalexpansion.block.machine.TileMachineBase.setLevel(TileMachineBase.java:94)

14:35:56 | STDERR | main | info | [cofh.core.network.PacketHandler:handleNBTPacket:177]: 	at cofh.thermalexpansion.block.TileAugmentableSecure.handleTilePacket(TileAugmentableSecure.java:328)

14:35:56 | STDERR | main | info | [cofh.core.network.PacketHandler:handleNBTPacket:177]: 	at cofh.thermalexpansion.block.TileReconfigurable.handleTilePacket(TileReconfigurable.java:177)

14:35:56 | STDERR | main | info | [cofh.core.network.PacketHandler:handleNBTPacket:177]: 	at cofh.thermalexpansion.block.TilePowered.handleTilePacket(TilePowered.java:126)

14:35:56 | STDERR | main | info | [cofh.core.network.PacketHandler:handleNBTPacket:177]: 	at cofh.core.network.PacketTile.handlePacket(PacketTile.java:33)

14:35:56 | STDERR | main | info | [cofh.core.network.PacketHandler:handleNBTPacket:177]: 	at cofh.core.network.PacketCoFHBase.handleClientSide(PacketCoFHBase.java:399)

14:35:56 | STDERR | main | info | [cofh.core.network.PacketHandler:handleNBTPacket:177]: 	at cofh.core.network.PacketHandler.handlePacketClient(PacketHandler.java:124)

14:35:56 | STDERR | main | info | [cofh.core.network.PacketHandler:handleNBTPacket:177]: 	at cofh.core.network.PacketHandler.injectPacket(PacketHandler.java:152)

14:35:56 | STDERR | main | info | [cofh.core.network.PacketHandler:handleNBTPacket:177]: 	at cofh.core.network.PacketHandler.handleNBTPacket(PacketHandler.java:174)

14:35:56 | STDERR | main | info | [cofh.core.network.PacketHandler:handleNBTPacket:177]: 	at cofh.core.block.TileCore.handleUpdateTag(TileCore.java:191)

14:35:56 | STDERR | main | info | [cofh.core.network.PacketHandler:handleNBTPacket:177]: 	at net.minecraft.client.network.NetHandlerPlayClient.func_147263_a(NetHandlerPlayClient.java:760)

14:35:56 | STDERR | main | info | [cofh.core.network.PacketHandler:handleNBTPacket:177]: 	at net.minecraft.network.play.server.SPacketChunkData.func_148833_a(SourceFile:96)

14:35:56 | STDERR | main | info | [cofh.core.network.PacketHandler:handleNBTPacket:177]: 	at net.minecraft.network.play.server.SPacketChunkData.func_148833_a(SourceFile:18)

14:35:56 | STDERR | main | info | [cofh.core.network.PacketHandler:handleNBTPacket:177]: 	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)

14:35:56 | STDERR | main | info | [cofh.core.network.PacketHandler:handleNBTPacket:177]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)

14:35:56 | STDERR | main | info | [cofh.core.network.PacketHandler:handleNBTPacket:177]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)

14:35:56 | STDERR | main | info | [cofh.core.network.PacketHandler:handleNBTPacket:177]: 	at net.minecraft.util.Util.func_181617_a(SourceFile:46)

14:35:56 | STDERR | main | info | [cofh.core.network.PacketHandler:handleNBTPacket:177]: 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1086)

14:35:56 | STDERR | main | info | [cofh.core.network.PacketHandler:handleNBTPacket:177]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)

14:35:56 | STDERR | main | info | [cofh.core.network.PacketHandler:handleNBTPacket:177]: 	at net.minecraft.client.main.Main.main(SourceFile:123)

14:35:56 | STDERR | main | info | [cofh.core.network.PacketHandler:handleNBTPacket:177]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

14:35:56 | STDERR | main | info | [cofh.core.network.PacketHandler:handleNBTPacket:177]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

14:35:56 | STDERR | main | info | [cofh.core.network.PacketHandler:handleNBTPacket:177]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

14:35:56 | STDERR | main | info | [cofh.core.network.PacketHandler:handleNBTPacket:177]: 	at java.lang.reflect.Method.invoke(Method.java:483)

14:35:56 | STDERR | main | info | [cofh.core.network.PacketHandler:handleNBTPacket:177]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)

14:35:56 | STDERR | main | info | [cofh.core.network.PacketHandler:handleNBTPacket:177]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

`
In NBTExplorer it looks like this
![mc errr1](https://user-images.githubusercontent.com/32132434/30648122-95c92734-9e1d-11e7-86c6-4232137e2809.png)

Is there a tweak or comes this from other mods?

**Comment by KingLemming** [comment]
This is the fault of another mod, probably something smashing NBT on load. We just have that diagnostic info so that we know something is breaking.
