### ISSUE TITLE
Update Source Code

### ISSUE THREAD

**Issue by harmdhast** [CoFH/Feedback#551]
Can you please update the github CoFH Core Source code.

Thanks

**Comment by KingLemming** [comment]
It is up to date. We keep literally the most up-to-date code here.

Please stop being crazy and ask questions like this on IRC.

**Comment by harmdhast** [comment]
Dude the curse version says 3.0.2 and the github one says 3.0.0RC1.
I'm not crazy

**Comment by Parker8283** [comment]
Uhh...

Did you even look? cofh/core/CoFHProps.java says 1.7.10R3.0.2

**Comment by skyboy** [comment]
Not to mention the modification dates: many of them are more recent than the most recent release.
