### ISSUE TITLE
Last item stacked pulled from Basic Drawer (StorageDrawers) is lost.

### ISSUE THREAD

**Issue by Ardagan** [CoFH/Feedback#551]
[modlist.txt](https://github.com/CoFH/Feedback/files/1319425/modlist.txt)
I'm using following setup:

1. Basic drawer connected to regular chest with itemduct
2. Servo inserted into itemduct connected to BasicDrawer

Last item/stack of items pulled is lost.

Tried with regular, hardened and reinforced servos. See item attached for setup image.

ThermalDynamics-1.12-2.3.5.12-universal.jar 
ThermalExpansion-1.12-5.3.5.19-universal.jar 
ThermalFoundation-1.12-2.3.5.14-universal.jar 
CoFHCore-1.12-4.3.5.13-universal.jar 
CoFHWorld-1.12-1.0.1.8-universal.jar 
StorageDrawers-1.12.1-5.3.1.jar 

Overall, I'm using Radon modpack v1.2.2

MC 1.12.1
Forge 14.22.0.2464

![image](https://user-images.githubusercontent.com/12602502/30670549-8fdfad1c-9e17-11e7-9667-ad61a9f35542.png)

**Comment by KingLemming** [comment]
This is actually a Storage Drawers issue and has been fixed. See here:
https://minecraft.curseforge.com/projects/storage-drawers/files/2476749
