### ISSUE TITLE
Extra Utilities 2 [Red Orchid, Ender Lily] Phytogenic Insolator support

### ISSUE THREAD

**Issue by Thiana** [CoFH/Feedback#552]
Could you consider adding support for growing the ExU2 plants in the PI? Thank you.

**Comment by Leowbattle** [comment]
(I'm not a member of TeamCoFH), but it wouldn't make sense because both of those plants have special growth requirements. So then it would need new Augments, although they don't add augments for other mods. And it would be OP anyway.

**Comment by covers1624** [comment]
Hmm, i'm not sure myself if this is a good idea, as stated that would be quite overpowered. But at the end of the day its KL's call.

**Comment by Thiana** [comment]
Yes it is overpowered, but it's also standard these days. IE's Cloche's and MFR's harvesters both support it. Also, it's trivial to automate the with ExU2's own blocks. The important difference is a PI method wont spawn entities or require a magnet block/water stream.
