### ISSUE TITLE
crash after hard reset

### ISSUE THREAD

**Issue by ray10k** [CoFH/Feedback#553]
Recently, my computer crashed while I was playing, and now minecraft crashes to desktop whenever I try to load my level.

Crash log and fml-client-latest log:
https://gist.github.com/ray10k/52eae3d6d979acb3bbea

**Comment by KingLemming** [comment]
Sorry, but this is a vanilla error due to your corrupted world. We just happen to be accessing vanilla code before anyone else.

You'll have to load a backup of your world, it's been destroyed.
