### ISSUE TITLE
[Question] 1.10.2 Thermal (Foundation/Dynamics) / COFH World, no platinum spawn.

### ISSUE THREAD

**Issue by llloyd4** [CoFH/Feedback#553]
So, the pack I am playing, the Direwolf20 1.10.2 LP pack, started off with out COFH World / Thermal Dynamics / Thermal Foundation, etc as it wasn't available when the pack was released and this was added later. So there are no .json files under config/cofh/world except vanilla.json. So I 'borrowed' the 01_thermalfoundation_ores.json from a 1.12.1 pack and did some Googling, couldn't find any examples that even remotely looked like what was in the 01_thermalfoundation_ores.json and had to take a wild guess. So my question is, is this correct?

"dependencies": "thermalfoundation",
	"populate": {
		
"platinum": {
			"distribution": "uniform",
			"generator": {
				"block": {
					"name": "thermalfoundation:ore",
					"metadata": 6
				},
				"material": "minecraft:stone",
				"cluster-size": 8
			},
			"cluster-count": 7,
			"min-height": 20,
			"max-height": 55,
			"retrogen": "true",
			"biome": "all",
			"dimension": {
				"restriction": "blacklist",
				"value": [
					-1,
					1
				]
			}
		},
}

I know, the numbers need tweaking, drop cluster size to 1, not entirely sure what cluster-count is, but tweak it to make it a bit more rare than the figures read I am thinking. But is that essentially right except for a few tweaks to the numbers?

**Comment by KingLemming** [comment]
Please don't use the issue tracker for tech support. We have a twitch chat for stuff like this.

But yeah, sure, that's basically right.

**Comment by llloyd4** [comment]
Oh! Apologies.>.< And thank you.
