### ISSUE TITLE
[Dynamics] [1.10.2 Latest] Crash with exnihilo crucible

### ISSUE THREAD

**Issue by CallMeFoxie** [CoFH/Feedback#554]
Hi,

I've managed to trigger this stacktrace:

https://pastebin.com/iuBbSegj

I am unsure whether it is your or EN Crucible issue, however it seems that somehow you're sending some odd data. There's itemduct pipe feeding from block breaker cobblestone into a crucible. It worked fine for an hour, now it crashes upon loading the world.

Also created EN Crucible issue at https://github.com/Jozufozu/ExNihiloOmnia/issues/160 

Thanks
Ashley

**Comment by KingLemming** [comment]
That's on Ex Nihilo's end.
