### ISSUE TITLE
[Question / Suggestion] CoFH World - Metadata for Material?

### ISSUE THREAD

**Issue by D3nnis3n** [CoFH/Feedback#555]
Hello,
my Goal is to only replace Stone (metadata 0) with ores, as i'm using retroactive Generation. I don't know if or how i can achieve this. Metadata like in the block Parameter seems to not work. As of now, many Buildings and streets on my Server got newly generated ores, as we switched the Provider mod of our ores. That's not a really big Problem, thanks to worldedit, but it would be pretty comfortable to be able to specifiy that only minecraft:stone with metadata 0 should be replaced.

**Comment by KingLemming** [comment]
Please use Twitch chat for questions. This is not a forum.

And yes, this is already possible.

**Comment by D3nnis3n** [comment]
Would you mind to tell me where i can find this Twitch Chat?

**Comment by Tonius** [comment]
Here's an invite: https://app.twitch.tv/invite/SipeCoinsSvalna
