### ISSUE TITLE
[Thermal Expansion]Augment for Pulverizer that disables secondary chances

### ISSUE THREAD

**Issue by UntouchedWagons** [CoFH/Feedback#555]
In my cobbleworks setup I like to use a Pulverizer to turn gravel into flint, but it sometimes produces sand as a by-product. It's not difficult to void but having an adjacent trash can kinda detracts from the setup. So I'd like to recommend an augment that simply disables secondary chances.

**Comment by KingLemming** [comment]
Hrm.

I like it. Okay!

**Comment by UntouchedWagons** [comment]
Yay!

**Comment by Vritra22189** [comment]
agree with adding an augment to disable secondary products.
i think this will be useful when we have an unmonitored chained production line with different inputs, 
where secondary products can halt the production queue.
example usage might be combined with hopper inputs, or AE2 crafting etc.

**Comment by KingLemming** [comment]
In 4.0.3. Except it's for all machines. ;)
