### ISSUE TITLE
[Thermal Dynamics] Upgrade Retrievers

### ISSUE THREAD

**Issue by target-san** [CoFH/Feedback#556]
Servos and filters aren't that much costly, but Retrievers require Eye of Ender and 2 Enderium nuggets. Would be nice to upgrade Retriever to upper tier, without the need to craft new one.
Existing Retriever + 1 tier ingot would up Retriever to that tier.
Example: basic retriever + 1 electrum ingot = redstone retriever (tier 3 one, not sure on precise name).

EDIT: I thought about this playing AgSkies 2 where you need to craft basic retriever for one of quests. And if you want to use better one, you need to spend Eye of Ender again.

**Comment by KingLemming** [comment]
Um...do you use NEI? Because this is already the case.
