### ISSUE TITLE
[1.12.1] Client Crash

### ISSUE THREAD

**Issue by VermillionX** [CoFH/Feedback#556]
Occuring on the server i'm on. Upon removing a dirt block from behind my pulverizer it's put me in an infinite crash loop. Removed Optifine, crash persists. So it's not that.

https://pastebin.com/yAbVwwXU

**Comment by covers1624** [comment]
Either optifine wasn't removed or you need to remove what ever mod is doing connected textures.

**Comment by KingLemming** [comment]
This is caused by CTM, not us.
