### ISSUE TITLE
Strange bug with autonomous activators

### ISSUE THREAD

**Issue by zed-hex** [CoFH/Feedback#557]
I have noticed a strange bug with autonomous activators where they randomly stop functioning correctly in a chunk. I have not fully worked out the cause of this but I first found this bug a long time ago when hitting mobs with a sword with the activator (this would work at first then would randomly sometimes stop working in a chunk. (braking or placing a new activator anywhere in a chunk would not work)

 but more recently I have encounter a similar bug with activators where they randomly stop function in a chunk when they are meant to be interacting with a block (this strangely happened at 2 places at around the same time) http://prntscr.com/79zjb5 this is meant to click a bucket of lava in the tank next to the activator but it does work now but in a different chunk it works fine (this was working fine be for and I have not modified the set up) this is the configuration of the activator http://prntscr.com/79zm0w also it is still able to pick up the lave below the tank with the activator and I tested if it could still hit people / mobs and that is fine.
 
This is the other place that the activator randomly stopped working http://prntscr.com/79zntx it was clinking items into the inventory of the block and clicking it with a wand. This was also working fine be for it randomly stopped working.

 I have not seen this issue reported yet and I have only experienced this bug on servers so far (normal forge servers) it may have something to do with a server restarting but I’m not 100% sure. This bug was found with thermal expansion 4.0.1-182, COFH core 3.0.2-262 and forge 1408 but I think this bug may have been around for a long time since the bug I mentioned with hitting mobs with the activator (I noticed this in earlier 1.7.10 build of the mod) here is a list of all mods present when this bug accorded: http://pastebin.com/NciU5W9x (this is a client side list since it is a pain to get the server side list)

**Comment by KingLemming** [comment]
OH MY GOD.

Paragraphs please. Seriously.

**Comment by zed-hex** [comment]
Sorry I was in a rush

**Comment by KingLemming** [comment]
Okay so we need you to actually read the readme for this repo and provide a proper report please. For all I know, you're using out of date mods, since the issue with Activators and swords has long been fixed.

**Comment by zed-hex** [comment]
I was unaware that the bug with the sword was fix but I can guarantee that this bug is with the latest stable builds of the mods I would not have reported it if it was not. I only mentioned the sword bug because that was also to do with chunks and this seems to also be chunk specific. Sorry for the confusion.

Just to summaries the issue randomly started happening in a few chunks in on server, autonomous activators just randomly stop functioning correctly and they still all had power and did not get reconfigured.  
After I noticed these issues I done lots of testing in and out of the effected chunks and I came to the conclusion that right clicking blocks with the activator was the only thing not working correctly by this I mean clicking anything like a tank with a bucket will not work but all other stuff works like killing mobs milking cow etc. 

Here is a list of all mods and there versions that where present when found this bug: http://pastebin.com/Z7QkfA1N

**Comment by KingLemming** [comment]
The problem with that is that it doesn't really make any sense at all. Either the activators work, or do not.

Check and make sure it isn't something else in your system. It's extremely unlikely that this is actually on the Activator.

**Comment by zed-hex** [comment]
I know what you mean by it does not make sense at all but I have tested for about 3 hours with re making the builds that where effected by the problem and testing random scenarios with activators with versus different things. Here is a quick video to demonstrate the issue: https://youtu.be/TI0IKFLVdpo

**Comment by KingLemming** [comment]
Is that a spawn chunk, and do you have mods which affect spawn protections?

I just can't make this happen.

**Comment by zed-hex** [comment]
That chunk is not a spawn chunk (it is thousands of blocks away) and there are some mods on the server that do change spawn protection / permissions but they have not been modified since the issues happened. The only thing I can think it may be is pneumatic craft with the security part of the mod but I’m not sure if that could affect autonomous activator But I’m looking into if that is the cause of the problem.

**Comment by KingLemming** [comment]
It absolutely could. The AA is a player.

**Comment by zed-hex** [comment]
I just took down the security system and the issues is still happening so it might just be I need to restart the server to fix it or it is not the cause or Something strange is happening on pneumatic crafts side

**Comment by zed-hex** [comment]
I can confirm that it was pneumatic craft that was causing the problem, thank you for the assistances.

**Comment by KingLemming** [comment]
Ah ha, awesome. :) Thanks!
