### ISSUE TITLE
CoFH core 1.10.2

### ISSUE THREAD

**Issue by Sir-hundred** [CoFH/Feedback#559]

**Comment by Sir-hundred** [comment]
Oops! accidentally added with no description
modlist : https://pastebin.com/6frmdkhy
minecraft log : https://paste.ee/p/2RwGG
So I launch and everything works fine till last moment where it crashes ... reading the log makes me think it has something to do with CoFH core....
I have no idea EXACTLY whats wrong and how to fix it so i thought i would ask here for help
The launcher i am using to launch this is MultiMC

**Comment by KingLemming** [comment]
We have absolutely nothing to do with that crash. You have TONS and TONS of errors from other mods though.
