### ISSUE TITLE
[NOT AN ISSUE BUT RATHER A QUESTION] Pump ?

### ISSUE THREAD

**Issue by Carbon-Ghost** [CoFH/Feedback#559]
Tinkering around with TE,  I found out a block named "pump" it does nothing and crashes your game, will it be a future addition ?

**Comment by KingLemming** [comment]
I swear I've said this a hundred times now. The tracker is not for questions. Use IRC.

Also, if you'd bothered to actually check the open issues/suggestions, you'd already know the answer to this.

**Comment by Carbon-Ghost** [comment]
Ok, sorry King, forgot to read the COFH user rules, didn't saw it :/

I will know for next time ;)
