### ISSUE TITLE
TF fluids missing from JEI

### ISSUE THREAD

**Issue by SynfulChaot** [CoFH/Feedback#56]
Since the most recent update, the following fluids are no longer showing up in JEI:

Liquefacted Coal
Naphtha
Refined Fuel
Resin
Tree Oil
Steam

**Comment by KingLemming** [comment]
I have literally no idea what you're talking about. They show up fine for me.

**Comment by SynfulChaot** [comment]
![JEI Pane](http://i.imgur.com/9MRv6rx.png)

![Mods in use](https://i.imgur.com/06dcssW.png)

**Comment by SynfulChaot** [comment]
[Here's the errors that come up in the console.](http://pastebin.com/y4YEL36N)

**Comment by KingLemming** [comment]
Used your modlist. Cannot reproduce at all.

**Comment by SynfulChaot** [comment]
Strange.  I could reproduce it until I cleared out all the old configs.  Not seeing it anymore.
