### ISSUE TITLE
Cascading worldgen lag with oregen

### ISSUE THREAD

**Issue by cosmicdan** [CoFH/Feedback#560]
Large veins causing chunks to be loaded before they should be, causing a runaway-effect with loading. It does add a noticeable lag.

You guys probably already know about this. Mezz, CovertJaguar, and many others were talking about how best to fix this back in May - https://github.com/Vazkii/Quark/issues/412

**Comment by KingLemming** [comment]
This only happens if YOU have added a vein which is too large. We could limit people from doing that, but frankly it's up to them.

We're just giving you enough rope to hang yourself. It's not really our fault when you're swaying in the breeze.

**Comment by KingLemming** [comment]
To expand on this - the nature of the oregen means that we can't stop this from happening if the end user screws it up. Because you have such fine control over the ore generation, this can't be moved to a noise-map solution.

And none of the generation that we provide out of the box causes this.

**Comment by cosmicdan** [comment]
Ok so CoFH will never support generating a single vein that covers a larger area than 3x3 chunks.... little disappointing but reasonable.

On 30 Sep 2017, KingLemming <notifications@github.com> wrote:
>To expand on this - the nature of the oregen means that we can't stop
>this from happening if the end user screws it up. Because you have such
>fine control over the ore generation, this can't be moved to a
>noise-map solution.
>
>And none of the generation that we provide out of the box causes this.

-- 
Sent with <a href="https://play.google.com/store/apps/details?id=com.onegravity.k10.pro2"><b>K-@ Mail</b></a> - the evolution of emailing.

**Comment by KingLemming** [comment]
Well the existing methods won't support it, no. As I said, it would need to be noise-mapped, which would be a separate generation option.

I'll chat with Vazkii and see if it's feasible to add such an option.

**Comment by cosmicdan** [comment]
Would be good, just something for the “would be nice if possible” pile.
 
I considered developing some kind of decoration “delegator” that partitions the workload but I think it’s a bit beyond me. Maybe you veterans could instead work out something re-usable to make this a worthwhile endeavour.

I think everyone is used to worldgen lag from 1.7.10 modpacks anyway 😊 Our server where the performance really matters is irrelevant since we just pregen chunks anyway.

Cheers!
