### ISSUE TITLE
[Thermal Dynamics] Custom Attachments

### ISSUE THREAD

**Issue by ImbaKnugel** [CoFH/Feedback#561]
Currently it isn't possible for addon mods to easily add more Attachments to ducts.
This is because when reading the attachments from NBT ```AttachmentRegistry#createAttachment``` throws a RuntimeException if the id does not match any of the static fields. Could you consider adding a way for mods to register their own attachments.

**Comment by KingLemming** [comment]
Could you please provide a usecase?

**Comment by ImbaKnugel** [comment]
I'm trying to create an addon for Thermal Dynamics which would provide functionality similar to Logistics Pipes. Instead of creating completly new ducts/pipes I wanted to create custom Attachments because they would fit in better with the already existing way of doing things (Servos, Retrievers, ...).

I didn't know that allowing for custom attachments would require such big code changes. If it isn't feasible to implement I'm just going to have to search for a better alternative.

**Comment by covers1624** [comment]
Honestly i like the idea of having other mods being able to register attachments. I'm a little fuzzy on the back end but i was sure that the attachments themselves handled most of the things.

**Comment by KingLemming** [comment]
Attachments do handle most things, but at minimum we still have to recompartmentalize them, provide an interface, standardize that, expose through an API, etc.

I don't think it's a bad idea necessarily, although I think that Logistics Pipes style functionality should probably be part of TD in general.

You are of course welcome to make a PR, as well.

**Comment by KingLemming** [comment]
Also, we'll have to come up with graceful failures and conflict resolution in the event that a mod adding an attachment is removed, or somehow fails to register the attachment when loading an existing world, etc.

**Comment by KingLemming** [comment]
This *may* happen with the TD 3.0 rewrite, but it won't be happening in 2.x.
