### ISSUE TITLE
[Suggestion] Config for the insolator

### ISSUE THREAD

**Issue by Carbon-Ghost** [CoFH/Feedback#562]
Can we have a config for the insolator please ? So we can control phytogrowth usage ( 0-64 ), water, energy for said seed ( so if using magicrops, you can set the power usage to ridiculous ) and time ?

**Comment by KingLemming** [comment]
JSON configs are cominge and will allow for this, although they won't be *nearly* as simple as you'd like I'm guessing.

But sorry, that's the best we can reasonably do.

**Comment by Carbon-Ghost** [comment]
It's ok, JSON configs are fine for me :)

the main part I want is water, phytogrowth and energy consumption.

**Comment by KingLemming** [comment]
Water isn't configurable - it'd be too easy for somebody to screw it up. Water is a function of energy.

**Comment by Carbon-Ghost** [comment]
Ok, at least phytogrowth and energy consumption ? xD
