### ISSUE TITLE
Request - Port to MC-1.12.2 Forge 93

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [CoFH/Feedback#562]
Love this mod; can it get a quick push ;)

**Comment by KingLemming** [comment]
What are you even talking about? Please provide a screenshot or logfile that shows any sort of incompatibility. The existing jars seem to work fine.

**Comment by P3rf3ctXZer0** [comment]
Okay good my bad XD

**Comment by KingLemming** [comment]
...so you didn't even try?
