### ISSUE TITLE
[Thermal Dynamics] Not Working with Forge Multipart

### ISSUE THREAD

**Issue by florian96** [CoFH/Feedback#563]
Hey. I Try to connect a pipe from Thermal Dynamics with a Cover from Microblocks and it not connecting. It was working on thermal Expansion 1.6.4 but not on Thermal Dynamics 1.7.10.

**Comment by KingLemming** [comment]
Correct. We don't support FMP.

Use TD's covers instead. (Structuralduct + Block)
