### ISSUE TITLE
[1.12.2 issue] Cryo-stabilized fluxduct not showing charge

### ISSUE THREAD

**Issue by danikk14g** [CoFH/Feedback#563]
Hello, i was doing some testing for my base on creative and i noticed the cryo-stabilized fluxduct is not showing the charge, whereas other fluxducts do, but it is actually transferring power.
https://imgur.com/a/7G0cD
I am using the latest version of all Thermal mods, The One Probe and Forge.

Thanks.

**Comment by KingLemming** [comment]
This is correct. They do not hold any charge. I'm pretty sure the tooltip even states that.
