### ISSUE TITLE
(Minecraft 1.10.2) 5.1.10.25 - Cache will not accept any more items from an itemduct even if an upgrade kit is used.

### ISSUE THREAD

**Issue by ariosos** [CoFH/Feedback#564]
1. Fill a basic cache with 20,000 items (like cobblestone) via itemducts.
2. Upgrade the cache.
3. From a chest, place an itemduct and a servo to extract items from the chest into the hardened cache.

- The cache will not accept anything over 20,000 items, despite it saying it can accept 80,000.

In multiplayer, it seems like it will push the items through when the player relogs, but then stop pushing if more items are added. This doesn't happen in single player and no items are moved to the cache.

World-around - It seems that if you manually put more items into the cache, then items will start flowing through the itemduct. (At least, I assume, until it hits the next limit, then the cache has to be updated).

**Comment by KingLemming** [comment]
Has nothing to do with Itemducts it turns out, entirely the Cache. Bit of a corner case.
