### ISSUE TITLE
[Suggestion] Wild cards for Servos, Filters and Retrievers 

### ISSUE THREAD

**Issue by duncanwebb** [CoFH/Feedback#564]
Would it be possible to add wild cards to the servos, filters and retrievers? So for example if the ore dictionary name has ingot in then it would be selected for extraction or insertion. So one implementation could select contains a word, starts with a word or ends with a word. I reckon this would work best with ore dictionary names.

So a sorting system could select all ores into a intermediate chest and then send iron one way and gold another. I was also going to suggest daisy chaining filters together but an intermediate chest would work well.

Great mod, a big thank you.

**Comment by KingLemming** [comment]
It's possible, but it'd be utterly server destroying. Just not something I'm willing to add, sorry.

**Comment by duncanwebb** [comment]
Would it not be possible to use a list or a hash table that would be built at creation of the filter? Apologies I don't know anything about minecraft data structures. I guess that an item has an unique id (32 bits) and a binary search on list of id's would be quite fast.
