### ISSUE TITLE
Null Pointer exception repeatedly.

### ISSUE THREAD

**Issue by TerabyteTim** [CoFH/Feedback#566]
So I'm running my server with Forge 10.13.3.1408 on Minecraft 1.7.10 and CoFH core 3.0.2-262.

The server runs pretty well, and hasn't crashed yet. But I'm getting this weird error repeatedly, and it appears to be coming from CoFH core.

This error is popping up every 30 seconds or so: http://pastebin.com/gwwut9TW

Any ideas what may be going wrong? Is it a bug, or something I've done wrong? If you need any other information, just ask.

**Comment by KingLemming** [comment]
This isn't us. If you look at the log, ALL of the WorldHandlers are complaining.

Something busted your world, sorry. :(
