### ISSUE TITLE
Fractionating still keeps stopping?

### ISSUE THREAD

**Issue by MythicArcher** [CoFH/Feedback#566]
I am using the fractionating still to pull resin from 4 arboreal extractors attached to a spruce tree. It sends the rosin down some item ducts to be used else where. I also am using a compression dynamo to power the system and save extra energy to cells for infinite energy. The fractionating still keeps stopping though. I have not been able to figure out why. I have found that emptying the fractionating still completely and replacing it restarts the system properly for a time. Is there some intended feature that I am missing or is this a bug? I am leaving a copy of my setup in a 1.12.2 creative test world if you would like pictures.

**Comment by KingLemming** [comment]
Yeah, please post some pictures of your setup. This isn't something I've ever heard of.

**Comment by tritechnik** [comment]
Also have a similar setup. The fractionating still has stopped accepting resin completely, even after breaking. It does have power.

**Comment by MythicArcher** [comment]
I have been testing this in my games (Creative test world and Survival) and have found that the problem for me seems to be that, basically, I am not using enough RF. 
What I mean is, the system produces infinite power. Once my energy cells are full RF builds in the dynamos. Once they are full on RF they stop running. Once they stop running they slowly fill with tree sap. Once they are full of tree sap the fractionating still fills with tree sap. And once the fractionating still is full of tree sap it stops working. When I was removing the fractionating still it empties out the tree sap and allows it to start up again.

At least, I think that is right.

I am including a pic from my test world.
The below url is to a video by Mischief of Mice that I used to make my setup.

https://www.youtube.com/watch?v=hdZTBwWoVfA&list=PLQzDSnrhrcyxuhcG-ay37CqNBjSb_axnl&index=3

And sorry for the late reply, life got in the way.

**Comment by MythicArcher** [comment]
... Now I am really adding the pic, promise...
![2017-10-04_15 48 04](https://user-images.githubusercontent.com/32442489/31198834-37a88dd0-a91b-11e7-9e6f-0bfd2430d6aa.png)

**Comment by KingLemming** [comment]
Yes...the issue you are having is that you've filled up your system. Nothing is broken - the machine won't start if the tanks are full and it's unable to output.
