### ISSUE TITLE
[Thermal Dynamics] Itemduct on BC Quarry w/Servo installed not working

### ISSUE THREAD

**Issue by Hazmatik** [CoFH/Feedback#567]
When I attach an Itemduct to a Buildcraft Quarry it works fine, but if I attach a servo onto it (to set it to round robin mode) it just starts shooting items into the air as if there was no duct attached to the quarry. I'm playing on the FTB Infinity pack. This is with Thermal Dynamics version 1.0.0 and BuildCraft version 6.4.14 

P.S. - Sorry about the closing and re-opening I accidentally hit (shift+enter) and it posted before I had finished.

**Comment by KingLemming** [comment]
Yup. This sure is on BC.

Unless the quarry is coded to understand ducts, you'll have to use a buffer chest, sorry.

**Comment by Parker8283** [comment]
BCCompat has support for you to do this.

**Comment by Hazmatik** [comment]
The pack includes BCCompat version 6.4.2 it seems that it understands the duct but not when a servo is attached at least that's what I gathered from my attempt to decipher the code on the BCCompat github (I'm not very good at reading and understanding code) and my in game experience.

**Comment by Parker8283** [comment]
You shouldn't need to have a servo on it; items will automatically be injected into the duct system.

**Comment by KingLemming** [comment]
Correct. Servos are for forced extraction. They prevent things from auto-injecting into the system and bypassing the controls.

**Comment by Hazmatik** [comment]
Yeah I just wanted it to evenly distributed between the multiple chests instead of filling up the closest first. I solved the problem of chests filling up quickly by adding some caches for things like dirt and cobble and using filters on the chests to not allow them in the chests.
