### ISSUE TITLE
1.12 Cryo-Stabilised Fluxducts, weird power transfer issues

### ISSUE THREAD

**Issue by Guybrush0** [CoFH/Feedback#568]
Thermal Dynamics Version: 2.3.5.12
So i have a calculator conductor mast setup: https://i.imgur.com/magGozq.png

It produces ~100k rf/t and it should be capable of outputting at that rate(i've seen it work with solar flux last cables in other packs). but when i use cryo-stabilised fluxducts it will not accept it(may be an issue with the no buffer)

I have this setup to accept the power: https://i.imgur.com/hls2zbx.png
But it's not accepting it, if i use  just fluxducts it causes my systems to toggle off and on(rs storage), also keeping in mind that because this pack has no wireless power i have this setup ~300 blocks away from my main base(all chunk loaded)

So to wrap up, cables not accepting/outputting infinite, may or may not be related to having 0 buffer, may be an issue with calculator

**Comment by KingLemming** [comment]
So, what exactly are you trying to store the energy in? The cables themselves are infinite, but it is of course limited by the receiver. You say 100k RF/t, but does Calculator try to send that all at once? And do you have storage which can receive that all at once?

It sounds to me like you've just mismatched your setup a bit. There's also no good explanation for Fluxducts causing things to "toggle on and off" other than again, the system not being designed in a workable manner.

**Comment by Guybrush0** [comment]
If you notice in the second screenshot I have 4 resonant cells acting as buffers, after that it leads to multiple machines including a refined storage controller and a tier 5 void miner from environmental tech (which uses more than 25k RF/t, my reason for using Cryo in the first place)

**Comment by Guybrush0** [comment]
After further testing I found that using Cryo ducts was actually slower than resonant as the output was barely 4k RF/t, so the calculator might output in bursts and having no buffer might be the issue

**Comment by KingLemming** [comment]
This is definitely sounding like an issue on Calculator's end, yes.
