### ISSUE TITLE
[Thermal Dynamics] Retriever feature request

### ISSUE THREAD

**Issue by ghost** [CoFH/Feedback#569]
When a retriever is set to only pull fluid with a Redstone signal, it still seems to currently accept fluid without one. Is this intended, or could it be possible to have it not allow fluids through when its signal requirement isn't met?

**Comment by Leonyx1175** [comment]
If not, maybe a redstone signal to toggle whitelist/blacklist for filters, or something similar?  That might be easier to implement since it's less of a change and more an addition.

**Comment by Leonyx1175** [comment]
Not sure how to edit via mobile, apologies, but to elaborate, I'm thinking redstone control enabled, high or low, and disabled, like the other similar items. Also, if enabled, a redstone control mode to block all or invert the white/blacklist might look better but I'm just trying to think along the lines of feasibility without really knowing how to do much scripting for mods.
