### ISSUE TITLE
Crash while loading world

### ISSUE THREAD

**Issue by xlicer** [CoFH/Feedback#57]
I installed the latest version of Thermal Expansion , Thermal Foundation , CoFH Core, the 2 Codechickencode and JEI. In a new instance and while loading a new world, I got this [crash](http://pastebin.com/Q2LRwNNN). Full log [here](http://pastebin.com/j9g6uZjw).

And yes if you ask, my laptop is trash.

**Comment by KingLemming** [comment]
We're not really featured in that stacktrace at all. You seem to simply be out of RAM. And no, we don't use much at all.

**Comment by xlicer** [comment]
I've made it work in a new instance, still I don't know what happening before.

**Comment by KingLemming** [comment]
Well, we don't show up anywhere in that crash log, so I'm going to call this one good.
