### ISSUE TITLE
cofh.thermalfoundation.block.BlockOre.getLightValue crashes

### ISSUE THREAD

**Issue by ProsperCraft** [CoFH/Feedback#570]
We are having multiple players in different locations on our FTB Infinity server having this client crash.

http://pastebin.com/6PULCQ3v

The player was in the overworld not in mystcraft as this user was-

https://github.com/CoFH/Feedback/issues/62

**Comment by KingLemming** [comment]
ID mismatch. This is on your world.

**Comment by BlackAce21** [comment]
If this is an ID mismatch it is the strangest one I have ever seen. I can teleport to those locations using the same modpack, same version, same everything, downloaded from the same source and I have no issues or crashes. Correct me if I am wrong, but shouldn't an ID mismatch issue cause crashes for everyone?

**Comment by KingLemming** [comment]
Well here's what's happening. There is a block with metadata 11. For some reason, the clients which are crashing believe that block to be a TF Ore.

It isn't. It literally can't be one. The block is mismatched on their clients. I don't know why, I don't know what FML has done here, but that IS the case.

**Comment by BlackAce21** [comment]
Installing optifine version 1.7.10 B7 HD Standard fixes this crash =\ we had one player on our server who literally reinstalled java and his client both without success. Installed that version of optifine, runs perfectly fine now.

**Comment by KingLemming** [comment]
That makes even less sense.

**Comment by BlackAce21** [comment]
See that was my theory as well. When I get time to get with the guy having the issue we can try and see if this is the case. I will keep you informed so other people know.
