### ISSUE TITLE
[Thermal Foundation] Incompatability with Pixelmon 3.4

### ISSUE THREAD

**Issue by enenra** [CoFH/Feedback#571]
I'm having a crash on loading of the main menu (after displaying the Mojang logo).

http://pastebin.com/0zAmkBz1

It only appears if I have Pixelmon and the latest Thermal Foundation installed at the same time. In the past I've used the two mods together (but different versions each). From what I can tell it seems to have to do with the tools newly implemented in Thermal Foundation but I don't actually know if the problem lies with Pixelmon or TF originally. 

I have tried avoiding the bug by disabling all armors and tools in the TF config - no effect. I made sure that it is TF and Pixelmon by installing and uninstalling the mods one after the other. The other mods seem to not make a difference.

I wanted to try it with an older version of Thermal Expansion but that would mean no Thermal dynamics afaik and having that is one of the main reasons why I'd like to use all of these mods. I'll try with an older version of Pixelmon next but I'm not confident that will fix the issue.

EDIT: Older version of Pixelmon did not change anything.

**Comment by KingLemming** [comment]
This is on Pixelmon.

**Comment by enenra** [comment]
Ok, thanks. Will ask them about it.

**Comment by clienthax** [comment]
@KingLemming can you elaborate?, it seems you are setting a tool or armour material that isnt registered?
	public static void init() {
		for (Object anItemRegistry : Item.itemRegistry) {
			Item item = (Item) anItemRegistry;
			if (item == null) {
			} else if (item instanceof ItemTool) {
				ItemTool tool = (ItemTool) item;
				TOOLS.put(Item.ToolMaterial.valueOf(tool.getToolMaterialName()), tool);//line 25
			} else if (item instanceof ItemArmor) {
				ItemArmor armor = (ItemArmor) item;
				ARMOR.put(armor.getArmorMaterial(), armor);
			}
		}
	}

**Comment by Ivorforce** [comment]
@clienthax, 

Item.ToolMaterial.valueOf(tool.getToolMaterialName()) == tool.func_150913_i 

You're unnecessarily parsing the name. Enums objects are not necessarily in the constant enum map.

**Comment by clienthax** [comment]
@Ivorforce thanks, this is ancient code that hasnt been touched for a few mc versions

**Comment by enenra** [comment]
@clienthax So is there a chance for this to be fixed for a 1.7.10 version or only 1.8+ ? I'd love to be able to play these two mods together but TE is 1.7.10 only so far.

**Comment by clienthax** [comment]
@enenra nope, were working on 1.8 now

**Comment by KingLemming** [comment]
Most mods aren't going to 1.8. We're part of that group, it just isn't worth it.

But for 1.8, you should know that the material's returned name is not guaranteed to be identical to the enum. That's some rather reckless code.

**Comment by Unrepentant-Atheist** [comment]
Most mods aren't going to 1.8? Because? So they're skipping to 1.9?

**Comment by clienthax** [comment]
@Unrepentant-Atheist because they are waiting for forge to sort out the shitstorm that is the new rendering system, mods like thermal foundation don;t want to update because of the millions of json files they would need..
