### ISSUE TITLE
Cache Becomes Unmovable and Cannot be Destroyed

### ISSUE THREAD

**Issue by Boolyman** [CoFH/Feedback#572]
This doesn't crash the server, so I don't have a log.  But players using my Craft Of The Titans 1.10.2 modpack are experiencing issues with the Thermal Expansion Caches.  Once they are placed down, they can not be moved again.  This is also happening in 1.12.2 in a new modpack I am making.  Even when switching over to creative, I can not break the Cache out of position.

**Comment by KingLemming** [comment]
None of your players have ever used TE before apparently?

Crescent Hammer.
