### ISSUE TITLE
Cofh core version 3.0.1 & 3.0.2 not working for me

### ISSUE THREAD

**Issue by scottmando2000** [CoFH/Feedback#573]
when ever I launch any modpack or just cofh ver 3.0.1 or 3.0.2 it makes my client sop responding when it loads cofh core
Sky Factory 2.4 pastebin --> http://paste.atlauncher.com/view/ee5a0bd2

**Comment by KingLemming** [comment]
Nothing in that log points to us. Try a different Forge version.

**Comment by scottmando2000** [comment]
ive probally tried 1/8 versions of forge every output is the same... It's stops responding

**Comment by KingLemming** [comment]
Ah, sorry. Looked again:
[20/5/2015 20:53:56 PM] java.lang.ClassNotFoundException: dmillerw.remoteio.asm.RemoteIOCorePlugin

Line 52. Your error is RemoteIO, has nothing to do with us.

**Comment by scottmando2000** [comment]
So how would I fix? Because it all ways stops responding on cofh no matter what pack/launcher

**Comment by KingLemming** [comment]
Find whatever is including RemoteIO stuff and remove that.
