### ISSUE TITLE
Transposer Recipes

### ISSUE THREAD

**Issue by Boolyman** [CoFH/Feedback#573]
I know Thermal Expansion used to be Mine Tweaker compatible, but some of the verbage has changed recently.  Are the TE machines still able to have recipes added and deleted?  I am trying to figure out the appropriate syntax for the Fluid Transposer.

Thanks for your time!

**Comment by KingLemming** [comment]
In 1.12, MineTweaker is supported. Beyond that, got nothin for ya, sorry.

**Comment by Boolyman** [comment]
Ah ok.  I wasn't aware Twitch Chat was a forum either.  ¯\(°_o)/¯

**Comment by covers1624** [comment]
https://app.twitch.tv/invite/SipeCoinsSvalna
