### ISSUE TITLE
Reactant dynamo not accepting Biomass (forestry)

### ISSUE THREAD

**Issue by iJordi** [CoFH/Feedback#574]
Playing FTB Beyond (v1.11.0) with Thermal Expansion (1.10.2-5.1.9.23).

It's not possible to put biomass in the Reactant Dynamo, with buckets or pipes/conduits.
Not sure where the issue lies.

**Comment by KingLemming** [comment]
The issue is that you didn't look at valid fuels for the Reactant Dynamo. Biomass isn't one of them.

JEI is your friend.
