### ISSUE TITLE
render bug (optifine and or fastcraft) MFR alpha 113

### ISSUE THREAD

**Issue by Ianaver** [CoFH/Feedback#575]
I know that this is an alpha but this one was really annoying. when either fastcraft, optifine or both were installed and MFR is ran, cables don't VISUALLY connect. I realize that optifine may not be fully supported if at all but fastcraft however doesn't screw with rendering quite as much as optifine yet the issue persists so can the issue be fixed? it didn't happen before is all I know.. 

Edit: version 104 is proven to work, not sure what version started this madness though
Edit 2: 110 works, past that it doesn't

screenshots:
![2015-06-01_20 52 20](https://cloud.githubusercontent.com/assets/8153290/7928393/2e41f570-08a4-11e5-818a-c23558245ddf.png)
![2015-06-01_20 50 33](https://cloud.githubusercontent.com/assets/8153290/7928394/324f12ce-08a4-11e5-9d99-efe6cc171613.png)

log (if helpful but unlikely): http://pastebin.com/rEd3H0ky

**Comment by Ianaver** [comment]
close this if you want....

**Comment by TheJulianJES** [comment]
@lanaver Is this fixed now?
You can also close it by yourself.

**Comment by Ianaver** [comment]
I was using an alpha (113) and using either fastcraft or optifine or both broke the rendering so it probably won't get fixed.... atleast not at this moment
