### ISSUE TITLE
cofh set to replace vanilla ore gen causes crash

### ISSUE THREAD

**Issue by 321nick** [CoFH/Feedback#576]
hey, i have a problem where, if i set ReplaceVanillaGeneration=true , then the game crashes after i move around my spawn a bit. i got a crash report: https://gist.github.com/6c02cc50a9d3cd163ad6d8e3913f18b9 , do you know what mod conflict might be causing this? ic an post mod list if need be .

**Comment by KingLemming** [comment]
That log shows entirely Thaumcraft as the cause.

Also, 1.7.10 is completely unsupported at this point, sorry.
