### ISSUE TITLE
[Thermal Dynamics] 2.3.5 Ducts breaks

### ISSUE THREAD

**Issue by Tupilak** [CoFH/Feedback#578]
Playing on a server and when ever I get 8 - 9 chunck away from the ducts I have connected to a crate the ducts breaks.  It's both power and item ducts.

![2017-10-08_00 28 17](https://user-images.githubusercontent.com/20927492/31312341-a03c3a84-abc0-11e7-88ae-5d771e7eb606.png)

**Comment by KingLemming** [comment]
That specifically seems to be an issue with the crate which is causing adjacent tiles to break. Possibly NBT corruption.

But if it were in the duct code, they would ALL break. ;)
