### ISSUE TITLE
Mekanism Dupe Bug

### ISSUE THREAD

**Issue by palaster** [CoFH/Feedback#579]
Thermal Expansion - 4.0.1-182
Mekanism - 8.1.3.231
Mod Pack - Resonant Rise 3.2.6.4 RC

If you place any TE Cache on the output face of a digital miner from mekanism, it is possible to dupe the contents of the cache. First, place the desired item (such as diamonds) into the cache, then place any useless item (such as stacks and stacks of cobble) into the inventory of the digital miner. The miner will auto output and increase the number in the cache.

**Comment by KingLemming** [comment]
That is *entirely* on Mekanism.

**Comment by palaster** [comment]
Alright I will go let him know, but it weird that it works with everything, but your caches, like barrels.

**Comment by KingLemming** [comment]
It's definitely strange, but every other mod works correctly with Caches.

**Comment by KingLemming** [comment]
https://github.com/aidancbrady/Mekanism/blob/master/src/main/java/mekanism/common/util/InventoryUtils.java#L146

The && should be ||

The error is in Mekanism. ;)

**Comment by palaster** [comment]
Thank you very much for the help.

**Comment by aidancbrady** [comment]
You're the best @KingLemming, fixed.

**Comment by KingLemming** [comment]
Any time. :)
