### ISSUE TITLE
Tinkers Construct Plugin Issues [1.12.2]

### ISSUE THREAD

**Issue by ReverseStateMonad** [CoFH/Feedback#579]
Forge Version 1.12.2 14.23.0.2491

Mod List:
CodeChickenLib 1.12 3.1.3.313
CoFHCore 1.12 4.3.5.13
CoFHWorld 1.12 1.0.1.8
Mantle 1.12 1.3.1.21
RedstoneFlux 1.12 2.0.1.2
TConstruct 1.12 2.7.3.30
ThermalDynamics 1.12 2.3.5.12
ThermalExpansion 1.12 5.3.5.19
ThermalFoundation 1.12 2.3.5.14

Additional Mods:
CraftTweaker2 1.12 4.0.8
MTLib 3.0.0
ModTweaker 4.0.3

There seem to be some issues with the Tinkers Construct plugins for Thermal Foundation/Expansion and the liquid alloys registered therein.

Reproducible with the mods in the first list:
- Although the liquids for these alloys (Invar, Constantan, etc.) are present in the game and can be produced in the Magma Crucible, they cannot be produced in the Smeltery, either by melting (e.g. invar blend gives the "Item cannot be molten" message) or by alloying (e.g. molten iron and molten nickel do not combine into molten invar).

- There are no casting recipes for these alloys.  Once you have acquired them (via creative mode or the Magma Crucible), they can only be stored or destroyed, not used.

With the addition of the mods in the second list:
- Attempting to add a recipe using Craft Tweaker that involves one of these liquid alloys (either as an ingredient or as a product) fails, with an error such as `Could not resolve <liquid : invar>`.  Using the `/ct liquids` command to generate a list of registered liquids does show the liquid alloys in the list.  Replacing the alloy with another liquid such as `<liquid:water>`, or even a liquid added by Thermal Foundation outside of the Tinkers Construct plugin such as `<liquid:redstone>` succeeds.

**Comment by KingLemming** [comment]
Hrm...the problem is that I'm using TiCon's IMC exactly as prescribed.

Perhaps the issue is on their end?

**Comment by ReverseStateMonad** [comment]
OK, I reposted the issue over there.

**Comment by KingLemming** [comment]
So, after actually trying this...it works. So at the moment, you appear to be a crazy person. :)

**Comment by KingLemming** [comment]
Also just completed a cast. I think what you're seeing is a graphical bug, and this is entirely on TiCon's end.

Currently, they don't seem to render fluids if there is no block form of the fluid. This is 100% improper behavior and there's no reason for that restriction. I'll comment on the other issue.

**Comment by ReverseStateMonad** [comment]
I'm not crazy.  I do notice that you appear to be using an earlier build of Forge than I am (1.12 vs 1.12.2).

Screenshot:
![2017-10-08_22 52 42](https://user-images.githubusercontent.com/23009720/31323969-b7e5a0d8-ac7b-11e7-9f0c-ec40676a68cb.png)

**Comment by ReverseStateMonad** [comment]
I think I've found the cause of the problem.  It appears that the TC Plugins are firing during the initialization stage.  From the [TC Wiki page on IMC](https://github.com/SlimeKnights/TinkersConstruct/wiki/IMC) :

> ALL IMCs HAVE TO BE SENT DURING PREINIT

So, the IMCs are being sent after TC stops accepting them.  I don't know why it still works for you.

**Comment by KingLemming** [comment]
Because that's not actually a thing that should matter. Order is PreInit -> Init -> IMC -> PostInit.

That's just how Forge works.

**Comment by ReverseStateMonad** [comment]
And yet, something _is_ going wrong.  What version of Forge are you testing this with?  I could make a profile with that version and see if it still happens to me there.

**Comment by KingLemming** [comment]
I'm pulling down off the github. I'm on 1.12.2. I don't know why you think that I'm not.

**Comment by ReverseStateMonad** [comment]
The screenshot you posted says "Minecraft 1.12" on the title bar.  My screenshot doesn't show the title bar, but my title bar says "Minecraft 1.12.2".

**Comment by ReverseStateMonad** [comment]
I tried updating from the recommended Forge version to the latest (2512)... no change.  Can you think of anything else to try?

**Comment by KingLemming** [comment]
I'm actually wondering if somehow ModTweaker or CraftTweaker is messing with it.

**Comment by ReverseStateMonad** [comment]
Can't be.  I set up a profile with just TC, the CoFH mods, and the relevant prerequisites (so no CT, MT, minimap, JEI, etc.) and it still happened.

**Comment by laz2727** [comment]
For the record, TiC processes its IMC during init.

**Comment by ReverseStateMonad** [comment]
I figured it out, for certain this time.  And the implications are disturbing.  It's a mod loading order problem.  If TC loads first, the bug happens.  If TF/TE load first, the plugins work.  To test it, I added this:
`[
    {
        "modId":"tconstruct",
        "deps":[
            {
                "type":"after",
                "target":"thermalexpansion"
            }
        ]
    }
]` as injectedDependencies.json in my config folder (I'm honestly surprised I got this to work first try, there was basically no documentation on this anywhere), and the bug just went away.  Here's the disturbing part: default mod load order appears to be OS-dependent.  If your OS is case-sensitive, the 'C' in "TConstruct" and the 'h' in "ThermalExpansion" are alphabetized (and therefore loaded) in one order, while if it isn't case-sensitive they are loaded in the other order.  So you couldn't reproduce the bug because we were using different OSes.

**Comment by KingLemming** [comment]
Those aren't really "disturbing implications." Russia undermining democracy in the western world is "disturbing implications."

Mod load order being OS dependent has plagued Forge for years. I'll still argue that TCon is being stupid though by forcefully processing IMC in init as there is absolutely literally no reason to do so.

**Comment by ReverseStateMonad** [comment]
*shrug* They're "disturbing implications" the same way that TCon is being "incredibly stupid".  It's a very minor bit of hyperbole.  Also, I would argue that the Russia thing is significantly worse than just disturbing implications.

Regardless, I'm glad this is finally actually resolved.
