### ISSUE TITLE
Energetic Infuser max power too low?

### ISSUE THREAD

**Issue by jubalearly** [CoFH/Feedback#58]
Upgraded Infuser to max, added specialization and 3 coils.  600RF/tick is max charge rate.  That seems too low compared to V4 and trying to charge Redstone Arsenal gear takes too long...in my opinion.  Please advise if I am doing something wrong. 

![2017-03-06_19 57 33](https://cloud.githubusercontent.com/assets/7937235/23639914/719f2e7e-02a7-11e7-955f-e2dcea244af4.png)

**Comment by jubalearly** [comment]
It's just a display error, the charge rate goes to 25k with these augments when you actually charge something.  BTW, enderio items and a few other mods will not charge in the Infuser guessing they need to update to new TE RF API

**Comment by KingLemming** [comment]
It's not a display error - the 600 RF/t is for standard recipes. You have the correct augment in to "unlock" the higher charge rate for rechargable items, but it's *only* higher for those items.

Also, even at 600 RF/t, Redstone Arsenal gear would charge in about 13 seconds. That's not exactly *slow*.

The Infuser also supports Forge Energy, so those should work.
