### ISSUE TITLE
UBC integration

### ISSUE THREAD

**Issue by Adaptivity** [CoFH/Feedback#58]
Integration with UBC changes textures of ores. Instruction how to add it located here: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1293503-underground-biomes-constructs under spoiler: "For modders: How to set up UB textures for your ores". This is really easy to add it.
Some examples of integration code:
1) Forestry: https://github.com/ForestryMC/ForestryMC/commit/b3b1a6a415cf2309d65bd700dcfcdc1c5cf36ae8
2) Tinkers Construct: https://github.com/SlimeKnights/TinkersConstruct/commit/0972d78077d4290f578c54b99b24e98d6e2cf011

**Comment by KingLemming** [comment]
This has been handled by mallrat208 in a far better fashion than we EVER could:
http://minecraft.curseforge.com/mc-mods/227992-ubc-ore-registrar

:)
