### ISSUE TITLE
Feature Request: Automated Augment Assignment

### ISSUE THREAD

**Issue by jforr** [CoFH/Feedback#580]
I just went through and assigned augments to 48 dynamos and it was a fairly tedious process as I was changing out 4x augments on each machine.

I'd like to have a new "augment assignment" machine where you can insert a stack of newly built machines of the same type and frame, pick an augment pattern you'd like, then this machine will automatically change out the augments on your inserted stack to match the pattern.

**Comment by KingLemming** [comment]
No, sorry. Not building a specific machine for this. It's too meta.
