### ISSUE TITLE
[Thermal Expansion] Balancing Tectonic Initiator recipes

### ISSUE THREAD

**Issue by OneEyeMaker** [CoFH/Feedback#581]
Hello.
Found one feature of recipes of Pulverizer with Tectonic Initiator augment,
It outputs the same amount as regular Pulverizer + 1.
For most recipes it is logical behavior, because most recipes in regular Pulverizer output 2 items (so in Tectonic Initiator - 3).
But for recipes, which process gem/dust ores (i. e. Redstone ore/Lapis ore) it isn't. For example, Lapis Ore produces **13** Lapis Lazuli (in augmented pulverizer) compared with **12** (in non-augmented one). For such materials it doesn't make much sense to create Tectonic Initiator augment and Tectonic Petroteum for processing and getting just one more item.

So I suggest for Tectonic Initiator to change output amount to: ```Math.round(pulverizerOutputAmount * 1.5F)```.
It won't break recipes for regular ores (ones still will output 3 dusts), but it will make this augment much useful for more materials.

**Comment by KingLemming** [comment]
Found a semi-clever way to do it. I'm still a bit worried about there being odd cases, but it should be okay for the most part.
