### ISSUE TITLE
Bronze replacment [Issue]

### ISSUE THREAD

**Issue by Saizetsu** [CoFH/Feedback#582]
Tinkers alloy is overwriting all the bronze recipes from mekanism. All but paxels, i have tried to disable foundations bronze and all the armors but it turns it back on with a reset that is forced when changing settings. Before i had hit reset defaults it did not even show tinkers alloy now i cannot undo said settings or in anyway keep tinkers alloy out of the game.

**Comment by KingLemming** [comment]
Tinker's Alloy IS Bronze.
