### ISSUE TITLE
Crash with TD 2.0.11.18

### ISSUE THREAD

**Issue by BrisingrAerowing** [CoFH/Feedback#582]
[Crash Log](https://gist.github.com/BrisingrAerowing/9ee9f880e5f47c863004dd5a610333a6)

Got this after updating TD and TE to the latest.

**Comment by KingLemming** [comment]
This right here is why we don't usually backport. Stuff breaks which really has no reason to.

Please stop playing on 1.10 and play on the *actual* latest version.

**Comment by BrisingrAerowing** [comment]
I am on 1.10 for a few mods that don't have 1.12 versions yet: Galacticraft, Railcraft, and Exotic Birds. Railcraft I can live without, but GC and EB are two of my core mods. I do have a 1.12.2 instance set up for testing, but it crashes with another mod I use (Biome Tweaker, which I use to remove BOP Wastelands), and there has been no progress on that issue.

**Comment by BrisingrAerowing** [comment]
I am on 1.10 for a few mods that don't have 1.12 versions yet: Galacticraft, Railcraft, and Exotic Birds. Railcraft I can live without, but GC and EB are two of my core mods. I do have a 1.12.2 instance set up for testing, but it crashes with another mod I use (Biome Tweaker, which I use to remove BOP Wastelands), and there has been no progress on that issue.
