### ISSUE TITLE
Tinkers alloy [Issue]

### ISSUE THREAD

**Issue by Saizetsu** [CoFH/Feedback#583]
The tinkers alloy is replacing the bronze equipment from mekanism. This is unwanted but i cannot disable the bronze part of thermal expansion it sets itself back on. How do i fix this?

**Comment by KingLemming** [comment]
You already opened this. I answered it and closed it. Stop.

Tinker's Alloy is Bronze. That's how the ore dictionary works. You cannot disable it.

**Comment by Saizetsu** [comment]
Tinkers equipment is overriding the equipment from mekanism. That was not answered. Yes it is bronze it is also weaker than mekanisms and for some reason i cannot make any piece of mekanisms bronze items without it replacing it with tinkers equipment. If that cant be changed then i guess i cant use thermal any longer. I apologize however.

**Comment by KingLemming** [comment]
There are plenty of ways to disable recipes. The config files work, and Minetweaker also works.

**Comment by Saizetsu** [comment]
There is no config file in the config folder for thermal. Dont know why it does it but if i change anything it makes minecraft restart then reverts what was changed. Not so much tech support as what appears to be a bug.

**Comment by KingLemming** [comment]
config/cofh/thermalfoundation/common.cfg

It is most certainly there. If it isn't, then you should download official CoFH mods because you have a version different from literally everyone else on the planet. Modpacks use this config all the time. There is no bug.

**Comment by Saizetsu** [comment]
The issue still persists with tinkers alloy equipment replacing mekanism equipment. It uses the bronze but its crafting makes it impossible to make mekanism bronze items as crafting them they become tinkers equipment. This is the issue. The recipe for tinkers replaces mekanisms bronze recipe.

**Comment by KingLemming** [comment]
That's on Mekanism or another mod then and however it's doing things. If the equipment is flagged as disabled, then the recipes do not register, period.

**Comment by Saizetsu** [comment]
If it would remain disabled. But when restarting minecraft as it says to it reenables the recipes on its own as though it had never been disabled to begin with.

**Comment by KingLemming** [comment]
Be sure you have proper write access in that directory and that you're actually saving the file.

I just tested with the release versions. It works.

**Comment by Saizetsu** [comment]
Still an issue i changed it to be writable. Next i could do is use n++ to edit it manually. Can i actually attach the config file here?

**Comment by KingLemming** [comment]
It's all OreDictionary sensitive.

However, if you're properly disabling TF's armor, it doesn't register recipes.

Pastebin your config and I'll take a look. Also, are you on the current release version?
