### ISSUE TITLE
[Thermal Dynamics 1.7.10 1.0.0-122] RecipeSorter assert failure...

### ISSUE THREAD

**Issue by OreCruncher** [CoFH/Feedback#584]
http://pastebin.com/LGtVTZQ5

Trying to run with asserts enabled to debug my mod and encountered the above "error".

EDIT: Removed Dynamics and came across the same issue with Thermal Expansion: http://pastebin.com/hChuhuJc.  Gonna be a fun day debugging. :)

**Comment by KingLemming** [comment]
That's on Forge/FML. What we're doing is valid.
