### ISSUE TITLE
[1.12 (and below?)] Disconnect between machine GUIs and JEI_Handler GUIs progress icons

### ISSUE THREAD

**Issue by HanFox** [CoFH/Feedback#584]
Something appears to have been missed when doing the jei_handler. All the on/off animations for progress are there, but the off variant isn't used in JEI. Instead you rely on the off icon being on the actual GUI image.

However, you use the off part of the scale_* icons on the actual GUIs.

I've only come across this because I decided to remove the off icons from the actual GUIs when doing PureBD due to the available scale_* icons, but I thought I'd bring it up so you can maybe bring some harmony to the way you handle these icons :)

Also, this is obvious with vanilla textures when you look at the Centrifuge recipes in JEI, because the jei_handler progress icon doesn't line up with the actual GUI progress image.

**Comment by KingLemming** [comment]
Well, the off icon is in the actual GUI image, so...I didn't see an issue. I'll look into changing up the JEI handler, though that's really not something I want to backport to 1.10 and 1.11.

The centrifuge icon is a thing though, yeah. I'll ponder that.

**Comment by KingLemming** [comment]
Alright, so this is handled in 1.12 now. Unfortunately, I can't really backport it as JEI changed a bit and it'd be a rather large rewrite for a really minor thing.
