### ISSUE TITLE
Cyclic Assembler consuming Piston

### ISSUE THREAD

**Issue by olDirdey** [CoFH/Feedback#585]
Hi there, I set up a Cyclic Assembler containing a shematic (1 Piston + 1 Wheat) to craft Wheat Flour (Vegan Option Recipe). The Output is connected to a normal chest via Ender IO Item Conduit. If I put wheat into the cyclic assembler with a piston in it´s inventory the crafting only works once. I got 1 wheat flour as a result in my chest, but the piston dissapears. 

Does anyone know about the problem and has a workaround for it?

I am using Minecraft 1.7.10 with forge 1614 and ThermalExpansion-[1.7.10]4.1.5-248

**Comment by KingLemming** [comment]
Sorry, 1.7.10 is unsupported, and strictly speaking there is no problem.

The piston isn't coded to remain in inventory, so it is correctly consumed.
