### ISSUE TITLE
[Thermal Dynamics] Crash when placing fluiduct

### ISSUE THREAD

**Issue by athelred** [CoFH/Feedback#588]
I am encountering a crash when placing a fluiduct in the world.  Once the crash occurs it repeats every time the world is loaded.  If I remove the errant duct with MCEdit, the world will load, however the error reoccurs if I try to place the fluiducts again.  

The location it is being placed is a fairly complex array of already active fluiducts.  There are two ducts that seem to cause the issue.  Which ever of them is placed second causes the crash.  They are both connected to the complex array of ducts.

The mod pack is All the mods 3.  I have updated the related mods to the most recent version to see if that resolved the issue.

Thermal Dynamics version 2.3.6.12

The following should include the error report and a full list of all mods

https://pastebin.com/6sYJ1B8q

As the error is repeatable and in a publicly available mod pack, if desired I can provide the save files with exact instructions on creating the error.

**Comment by covers1624** [comment]
Duplicate: https://github.com/CoFH/Feedback/issues/410
