### ISSUE TITLE
[Thermal Dynamics 1.12.2] NoClassDefFoundError: GuiDuctConnection

### ISSUE THREAD

**Issue by OscarXcore** [CoFH/Feedback#589]
Just recently updated from 1.12.1 (Forge 2485) to 1.12.2 (Forge 2512) with the same world being transferred over, and suddenly, Servos of any type on any pipe, do not have a GUI show up when right clicking the servo. In the MC Client log I am getting the following [error](https://gist.githubusercontent.com/OscarXcore/24491a2024a0b91540290787e1941d2d/raw/443a32bbd79615b5454e2933f32e1fb0ee69477d/Snippet%2520of%2520latest.log). 

[latest.log](https://gist.githubusercontent.com/OscarXcore/24491a2024a0b91540290787e1941d2d/raw/443a32bbd79615b5454e2933f32e1fb0ee69477d/Entirety%2520of%2520latest.log)
[modlist](https://gist.githubusercontent.com/OscarXcore/24491a2024a0b91540290787e1941d2d/raw/443a32bbd79615b5454e2933f32e1fb0ee69477d/Modlist%2520via%2520Debug%2520Crash)

**Comment by covers1624** [comment]
You likely have a corrupt TD jar, re-download it along with fresh versions of ALL CoFH mods and CCL. If the issue persists, strip mods from your pack and find the minimal set of mods required to reproduce this.

**Comment by KingLemming** [comment]
Yeah, just checked. This doesn't happen with the latest jars on Curse, so please redownload.
