### ISSUE TITLE
[Thermal Foundation] Suggestion: Recolouring Aluminum Ore

### ISSUE THREAD

**Issue by starg09** [CoFH/Feedback#59]
Asked @KingLemming about this in private about a month ago, but there were more important stuff to do. Noticed there's no report here about this, so I thought about adding it 😛 

Anyway, here's what I sent back then: Current texture for Aluminum Ore looks quite a bit similar to Iron Ore, which doesn't look very nice (at least as a personal opinion). A possible solution brought up at that time was making the ore texture have a color closer to red and/or orange (a middle point, as for not confusing it with either redstone or copper), similar to how aluminum shows up in nature, in the real world. As a note, this would only be about the ore, processed aluminum does look ok in its current white-y palette.

Anyway, that would mostly be it. Hopefully it can be looked up eventually!

**Comment by KingLemming** [comment]
Yeah, this is something I had wanted to do but it just kinda fell off the stack, sorry.
