### ISSUE TITLE
[1.10.2 TE] No Redstone Furnace recipes for MFR items.

### ISSUE THREAD

**Issue by bochen415** [CoFH/Feedback#591]
As title
Example: can't place raw rubber in a Redstone Furnace.

ThermalExpansion-1.10.2-5.1.10.28-universal.jar
ThermalFoundation-1.10.2-2.1.5.12-universal.jar
CoFHCore-1.10.2-4.1.11.16-universal.jar
MineFactoryReloaded-[1.10.2]2.9.0B1-229.jar
Forge 12.18.3.2488

**Comment by KingLemming** [comment]
If that's a normal furnace recipe, then the issue is on MFR's end. They are failing to add the recipe in a timely manner.
