### ISSUE TITLE
[1.12.2] Thermal suite Refined Storage interaction Server Crash?

### ISSUE THREAD

**Issue by VallenFrostweaver** [CoFH/Feedback#592]
#### Issue description:
Server crashing on startup

#### Steps to reproduce:
Unsure. Crash report is all I have to go on as this is a server. I asked players to log out for a reboot so I could check entity count and loaded chunks count after a reboot then it crashed out.

#### Version (make sure you are on the latest version before reporting):
- Minecraft: 1.12.2
- Forge: 14.23.0.2491
- Modpack: Radon 1.3.0
Related Mods in Crash report:
- Refined Storage: 1.5.18
- Thermal Dynamics 1.12.2 - 3.5.12
- Thermal Foundation 1.12.2 - 2.3.5.14
- Thermal Expansion 1.12 - 5.3.5.19

Does this issue occur on a server? [yes]

#### If a (crash)log is relevant for this issue, link it here:
https://pastebin.com/k52h48nH

EDIT: Removing the blocks being ticked resulted using NBT Editor results in another crash and more +1 more block effected and 1 less: https://pastebin.com/8r96F0qG

EDIT Update: Removing these blocks lead to world corruption and many blocks being exchanged for others. Had to revert to previous backup.

**Comment by KingLemming** [comment]
That's 100% on Refined Storage.

What's happening there is that the grid is forming, and the blocks have to call updates to let adjacent blocks know what is going on.

Refined Storage is apparently trying to cast one of its own blocks as a different block, and it's freaking out.

**Comment by VallenFrostweaver** [comment]
Thanks. I was occupied and couldn't follow up until now. For any that get this issue here is the link to the report on RS github: https://github.com/raoulvdberge/refinedstorage/issues/1490

Thanks again KL :)
