### ISSUE TITLE
[Thermal Dynamics] Crash upon switching dimensions

### ISSUE THREAD

**Issue by whitestarx0312** [CoFH/Feedback#593]
I received this crash when teleporting from one dimension (RFTools) back to my base in the overworld.

http://pastebin.com/KyyCcmtk
*I am using Optifine and Fastcraft.

CoFH Core: CoFHCore-[1.7.10]3.0.2-262
CoFH Lib: CoFHLib-[1.7.10]1.0.2-160
Thermal Dynamics: ThermalDynamics-[1.7.10]1.0.0-122
Thermal Expansion: ThermalExpansion-[1.7.10]4.0.1-182
Thermal Foundation: ThermalFoundation-[1.7.10]1.0.0-81

**Comment by KingLemming** [comment]
Does it happen consistently and can you load into your world?

**Comment by whitestarx0312** [comment]
Hmm makes sense. 

I can load into my world and only get the crash every so often. Is there anything I can do to try and find the culprit?

**Comment by KingLemming** [comment]
Take an inventory of everything in the chunk that you crash loading into.

Even that, who knows. And, Optifine and Fastcraft could easily cause this as well just by their nature of taking shortcuts...

Either way, I have to call this one closed I'm afraid. If it were a bug in our code, it would be consistent and we'd just be leaking GL calls everywhere. We wouldn't even make it past initial testing if we were leaving the tessellator out in the wild like that.
