### ISSUE TITLE
Missing texture

### ISSUE THREAD

**Issue by RanzeJini** [CoFH/Feedback#593]
Mod: Thermal Foundation 2.3.5.14
Issue: Missing in-world molten/smelter gui molten texture for iridium. Not tested on platinum, mana infused, steel, invar, signalum, lumium, or enderium metals. all other TF molten metals show textures. Otherwise, iridium functions properly and ingot textures work.
Other: Playing FTB Unstable 1.12 - 2.0.3

**Comment by KingLemming** [comment]
That would be on TCon's end. We use their textures and IMC.

My guess is that you have another mod also doing registration and is doing it incorrectly.
