### ISSUE TITLE
[1.12][Cofh World] Stalactite + Cave crash

### ISSUE THREAD

**Issue by Lyl4c** [CoFH/Feedback#594]
forge: 1.12.2-14.23.0.2512
CoFHWorld 1.12-1.0.1.8

[crash report](https://pastebin.com/gRbZGpKM)
[json file](https://pastebin.com/72DppvmB) (quartz-stalactite)

Upon entering the nether; the game crashes while trying to generate stalactites on the cave ceiling of the nether.

I'm not sure what I'm doing wrong with the quartz-stalactite generation entry. If this problem is even related to the entry that is. I doubled checked it and it looks right.

**Comment by KingLemming** [comment]
It's not right. you have both a gen-size and size-variance of 0. One of those needs to be positive.
