### ISSUE TITLE
Request - Cache sizes

### ISSUE THREAD

**Issue by NosajDraw** [CoFH/Feedback#596]
Thermal Expansion Cache Inventory size

Add a GUI element, or other means of dynamically (doesn't need to be automatable) reducing the size of the inventory.

So allow upgrades to work in exactly the way they already do, but allow the player to select a lower number.

This could be achieved either by some selectable option, or more interesting by say stuffing the excess space with cobblestone (or some other low value, easy to get item), if the "stuffing" method was used, this stuff inventory would not be exposed or interactable with by automation.

The reason for wanting this, is to allow me to fine tune stock levels of whatever item I have stored in the cache, where even the smallest cache is too big, but a chest is too small.

**Comment by KingLemming** [comment]
Spoke too soon. This creates some usability issues for Caches in general, and this is a really strange application to be honest.

Can you provide an example where limiting the amount of total items in the system is really necessary?

**Comment by NosajDraw** [comment]
Need?  I can tell you what I want it, and what I will use it for, but need?

Well, it comes down to how I build bases and the size of base I build, I build mega bases, I like to automated every task in more or less every mod, which means ultimately being able to ask my ME/RS system to autocraft say 10x top tier Draconic Solar panels (I don't know the numbers but imagine needing 1 million sand etc for a single crafting job).

To enable this to happen, without killing the server (since I tend to play on servers) I stockpile components, so for instance right now I have many of the gears needed by your mods already crafted and stock piled.  One of the methods I use the stock piling is to use cache's (or other mods) and fill these up with the item to be stockpiled and have a storage bus from the RS/ME connected to it.

But, whilst I often would like say 256 or 512 gears to be pre-crafted and ready to go, I'm less likely, at least till later in the game to want say 4000, that level may even use up all my base resources (I want enderium gears, but, until late on in the game 4000 of them is likely to be a strain on resources).

So, I don't need this functionality, but it would help me make efficient designs that I can scale overtime.  If it can't be done, or isn't worth the effort then so be it, I will be sad, but no great shakes.

**Comment by KingLemming** [comment]
That seems reasonable, sure. Let me see how I can add a GUI to caches without totally altering the mechanics of them in an inelegant way.

**Comment by KingLemming** [comment]
I'm going to try and push updates today, so this didn't quite make the cut for this round, but it will be happening.

**Comment by KingLemming** [comment]
Ultimately, this just didn't end up working out for a variety of reasons. Just felt awkward and cumbersome. Sorry.

Caches as they exist are being removed in 1.13. I'll keep this in mind for the unified Storage Cell mechanics though.
