### ISSUE TITLE
[1.12] [1.10] [Enhancement] Energy storage capacities can be much bigger than Integer.MAX_VALUE; please use Longs

### ISSUE THREAD

**Issue by Robijnvogel** [CoFH/Feedback#597]
Tracing the source of [this modpack issue](https://forum.feed-the-beast.com/threads/259793) on the FTB forums, I found that the CoFH energy API uses getter methods of the `int` type to fetch the maximum capacity and the actual level of an energy storage. See [here](https://github.com/CoFH/CoFHLib/blob/master/src/main/java/cofh/api/energy/IEnergyHandler.java#L19-L24).

In this particular case, and probably a few other cases (not including DE) as well, an energy storage can exceed the maximum value for an integer and cause the mod using your API to malfunction. I can't quite predict how bad this malfunction might be.

Would you consider changing the return type of these functions to `long` instead of `int`? Or maybe you have another way of making sure that the cap gets increased dynamically, a List of booleans or something? :P
Or should Flux-Networks not be using your API, but a different one entirely?

[Flux-Networks reference](https://github.com/SonarSonic/Flux-Networks/blob/1.10.2/src/main/java/sonar/flux/common/tileentity/TileEntityStorage.java#L90) that propagates down to your API.

I am aware that this is an API, and a popular one at than, so changing this might break a lot of mods.
Also, the original issue is Minecraft 1.10.2, so... could you consider fixing it for that version as well?

**Comment by KingLemming** [comment]
No. Int was chosen over long for performance reasons. There is absolutely no reason to ever need more than INT_MAX energy stored or power transferred. That's just bigger numbers for the sake of bigger numbers.

What you're asking basically just damages the performance of the game with no actual upsides whatsoever.

**Comment by covers1624** [comment]
DE already handles this properly and works fine with literally every power transfer system except FluxNetworks. This is an issue on their end. Also a rewrite for DE's energy system is planned, don't expect easy conversion to RF / FE.

**Comment by Robijnvogel** [comment]
@covers1624 with other words. FluxNetworks should not be using CoFH's API, or at least not for everything. Thank you. :)

**Comment by covers1624** [comment]
No in other words they should be using the RF api PROPERLY like every thing else. You ask it to take energy and it tells you whats left. Thats it. They do cacluations based on Int.MAX_VALUE and they shouldn't there is no need.

**Comment by brandon3055** [comment]
I have to agree with covers on this one. This is in no way an issue with the RF API. Sure i am going beyond its intended limits but thats not a problem as long as i handle things properly on my end it does not cause any issues other than machines not being able to read the actual capacity in my blocks. This is why i have OC integration so computers can get around this and in the future i will be re writing my entire energy network to work within the intended limits of the RF API. But regardless. This is an issue with Flux-Networks not implementing the API properly.
