### ISSUE TITLE
[TE]Want to support somehow to output the remaining items / fluid in the input field of the machine

### ISSUE THREAD

**Issue by Flithor** [CoFH/Feedback#598]
After the machine has finished processing, some material may be left, they do not support the output, which hinders automation.

**Comment by KingLemming** [comment]
There's not a good way to handle this. It used to be that input sides would allow for extraction as well, but then people complained, so now they don't. Basically different people want it different ways and I'm happy with how it is now, sorry.

**Comment by covers1624** [comment]
If you are implementing a complex system for pulling out items from a machine when its done, you can just not over send items in the first place.

**Comment by Flithor** [comment]
@KingLemming @covers1624 
It seems really hard to handle the automatic output of the remaining raw materials.
But at least allow the player can use container manually take the remaining fluid from the Pulverizer and Induction Smelter.

**Comment by KingLemming** [comment]
What do you mean remaining raw materials? You should only input things that you want to process. Outputs are ejected, and you can even send them different ways. But there's no way to know what "extra" input is.

**Comment by Flithor** [comment]
Oh? I'll try it.

**Comment by KingLemming** [comment]
Well I mean that I'll add that. In the next patch, you can bucket fluid OUT of a smelter/pulverizer, if it's off.
