### ISSUE TITLE
Pixelmon crash

### ISSUE THREAD

**Issue by Badcholo** [CoFH/Feedback#599]
Using the latest Pixelmon and thermal expansion causes a crash. Using much older versions works but causes a crash when looking into the energy cell. I'm making a pixelmon modpack and would love to use CoFH mods.

Logs and crash report with minimum mods installed.
https://www.dropbox.com/sh/cnoqfyrijctkfkf/AAAUHff0bMDWeHaq3KR6d68Ia?dl=1

**Comment by KingLemming** [comment]
Duplicate of #571. This is 100% on Pixelmon but I don't think they're willing to fix it. Sorry. :(

**Comment by Badcholo** [comment]
crud, thanks
