### ISSUE TITLE
Fluid Duct Compatability

### ISSUE THREAD

**Issue by Daihok41** [CoFH/Feedback#599]
I noticed today in 1.12.2 the fluid ducts will not pull water from pressure pipes mod infinite water source and insert into like a forestry carpenter. Dont know if this is intended or just a compatability issue.

**Comment by KingLemming** [comment]
Without a screenshot, I can't know what might be wrong with your setup, but ducts use the standard and proper Forge fluid system, so if there's an incompatibility, it's the fault of one of the other mods.

Strictly speaking, this is a tech support issue. Please feel free to join the Twitch chat and elaborate.
https://app.twitch.tv/invite/SipeCoinsSvalna
