### ISSUE TITLE
Missing item textures

### ISSUE THREAD

**Issue by minecraftuser1243** [CoFH/Feedback#6]
Certain items in nei not there at all. Playing 1.10.2 dns techpack. 
<img width="1440" alt="screen shot 2017-03-04 at 5 55 48 pm" src="https://cloud.githubusercontent.com/assets/26193542/23583841/1a3c32e8-0104-11e7-8846-7d1285e5cc8a.png">
<img width="1440" alt="screen shot 2017-03-04 at 5 55 46 pm" src="https://cloud.githubusercontent.com/assets/26193542/23583842/1b7adcea-0104-11e7-9418-2bc789454107.png">

**Comment by KingLemming** [comment]
This is an issue with your modpack or texture pack.

**Comment by minecraftuser1243** [comment]
Ok thank you! Just wanted to make sure:)

**Comment by minecraftuser1243** [comment]
Unfortunately, I have tried a few different modpacks and none of them seem to work, the same textures are missing. its only around the ore stuff like tin, invar, nickel and what not

**Comment by KingLemming** [comment]
Try just the mods on their own. We seriously aren't seeing this.

**Comment by minecraftuser1243** [comment]
ok i will

**Comment by minecraftuser1243** [comment]
Yeah it works! Must be a mod texture issue. Thank you though!

**Comment by KingLemming** [comment]
Sorry, wish I had better news for you on that. :( If you figure out the conflict, could you please let me know?

**Comment by minecraftuser1243** [comment]
Yes ofcourse im working on it right now

**Comment by HenryLoenwind** [comment]
The conflict is OSX, btw. I have this happen with a number of textures from different mods, too.

**Comment by KingLemming** [comment]
Any idea why OSX does this?

**Comment by HenryLoenwind** [comment]
No, I haven't been able to find that out. I see no pattern behind it, e.g. For TiC the shovel-head textures are all missing, other tool parts work fine. I looked at the png, and it looks exactly the same as the other tool part pngs. The mod that brings that cobblegen in SF3 is missing all its textures, except for the vanilla textures it uses in its models.
