### ISSUE TITLE
Duplication glitch with Thermal Expansion and Botania

### ISSUE THREAD

**Issue by IBeRamen** [CoFH/Feedback#6]
If you use a Terra Pick (From Botania) in hammer mode and break a block next to any type of TE Strongbox/Tank it will drop a creative tank and a creative strongbox.

**Comment by IBeRamen** [comment]
Thermal Expansion Version: 1.7.10 4.0.0 B8-23
CoFHCore Version: 3.0.0B9-40
CoFHLib Version: 1.0.0B8-34
RedstoneArsenal Version: 1.1.0RC1-19
Botania Version: r1.3-145

**Comment by IBeRamen** [comment]
I have also reported this bug to Botania.

**Comment by Vazkii** [comment]
https://github.com/Vazkii/Botania/issues/470 - Issue in question.
