### ISSUE TITLE
Redstone Arsenal Pickaxe, Shovel

### ISSUE THREAD

**Issue by Sasikaa** [CoFH/Feedback#60]
My mincraft is crashing when press "v" (empowered)
The Flux-Infused shovel, and Pickaxe either crashing my game, when use this items.
The non powered this items is working PERFECT!

The pickaxe crash report:
http://pastebin.com/i96Y5QzU

The shovel crash report:
http://pastebin.com/T8GG2UAX

**Comment by KingLemming** [comment]
Congratulations. You are using alpha versions. Those versions are not on Curse. You should not be using them. I'll still forward this to @skyboy, but I'm pretty sure that's the issue.

**Comment by skyboy** [comment]
This is a result of using alpha releases of CoFHCore with beta releases of RSA. Don't do that. If you're using a mod pack, tell the mod pack creator not to do that.
Alphas are not stable and may corrupt worlds, or may corrupt worlds when a beta release is made. Support is not offered, use at your own risk.

**Comment by Sasikaa** [comment]
Thanks your answer. BUT! If i not send you this crash report, not solved them... Thanks!
