### ISSUE TITLE
[REQUEST] Ore Generation Template builder

### ISSUE THREAD

**Issue by bookerthegeek** [CoFH/Feedback#60]
Heyo!

So this is an odd request, and I don't know how easy/hard it would be. But here goes.

Similar to [HERE](http://minecraft.tools/en/custom.php), would it be possible for to have a setup where we go and select the options, and the output is a properly formatted config snipet  that we can then use to build out the reset of the ore generation config files? This way we know that they are formatted correctly, and do not have to try and figure out the correct everything.

You can leave `PLACEHOLDERS` for the actual values, just parse the snippet correctly with all the optional and required objects for the select generation types.

Thank you for taking the time to consider this request.

**Comment by KingLemming** [comment]
This would be a pretty large amount of work. I...dunno, but it's worth investigating.

If the formatting is all you're concerned about, the wiki will eventually get more info on it, and combined with http://jsonlint.com/ it should be fairly straightforward.

**Comment by bookerthegeek** [comment]
Not so much the formating, more so the optional and required arguments. 

Mainly it was so that I could figure out why my config setting are not working. Everything says it is right, just it is not working.

**Comment by KingLemming** [comment]
We won't be doing a template builder, but when the World rewrite happens, we'll have templates up on the website which will allow for copy/paste.
