### ISSUE TITLE
ModTweaker unable to modify Pulverizer recipies

### ISSUE THREAD

**Issue by MattJohns** [CoFH/Feedback#601]
I'm trying to add a recipe to the Pulverizer using ModTweaker but it's failing with "No such member: thermalexpansion".  The code I am using is from the ModTweaker examples:

`mods.thermalexpansion.Pulverizer.addRecipe(3000, <minecraft:flint_and_steel>, <minecraft:flint>, <minecraft:iron_ingot>, 80);`

http://minetweaker3.powerofbytes.com/wiki/ModTweaker:Thermal_Expansion_Support

Using the latest of both mods, no other mods installed on Minecraft 1.10.2 .  Thermal expansion version 5.1.10.25 and ModTweaker2-2.0.13 .

**Comment by OneEyeMaker** [comment]
This wiki is outdated.

Use this wiki:
http://crafttweaker.readthedocs.io/en/latest/

**Comment by KingLemming** [comment]
Any issues that ModTweaker has are ModTweaker issues.

**Comment by MattJohns** [comment]
And there policy is to contact the mod authors for any issues specific to that mod.  Doesn't matter I found a workaround.
