### ISSUE TITLE
Thermal Expansion Cannot open security tab

### ISSUE THREAD

**Issue by zzzzzx** [CoFH/Feedback#602]
When i play with my friend lan offline mode, my friend cannot open the security tab but other tabs work just fine. But whoever open the lan (through the menu) can open it.

Mod list : CoFHCore-[1.7.10]3.0.2-262, ThermalDynamics-[1.7.10]1.0.0-122.jar, ThermalExpansion-[1.7.10]4.0.1-182.jar, ThermalFoundation-[1.7.10]1.0.0-81.jar, CodeChickenCore-1.7.10-1.0.7.46-universal.jar, NotEnoughItems-1.7.10-1.0.5.110-universal.jar

**Comment by KingLemming** [comment]
We fixed this one a while back, but due to how Minecraft works, it may be fundamentally unavoidable on LAN games.

Try using a server and see what happens. We'll look into it though.

**Comment by eraser0010** [comment]
got the same problem, still.. 
i setup a server on my pc, ftb infinity 1.6.2    
its running on offlinemode and cant enter the security tab.

**Comment by KingLemming** [comment]
Why are you running it in offline mode? Just curious.

**Comment by zzzzzx** [comment]
Here internet not available everywhere

**Comment by KingLemming** [comment]
Sorry, but this is inevitable due to how Mojang has coded Minecraft. You have to either use a dedicated server or do single player. LAN mode is a hack and I'm afraid we just can't support it.
