### ISSUE TITLE
[1.12.1 Thermal Dynamics] Itemducts voiding items?

### ISSUE THREAD

**Issue by XxZajoZzO** [CoFH/Feedback#602]
I am playing a custom modpack in 1.12.1. I set up an ender chest at home and connected it to a storage crate from actually additions with itemducts to put away items when I am mining. I was mining in the deep dark (ExU2) but I noticed that my items were disappearing much faster than they should be (10 stacks of cobblestone in a second pulled from an ender chest altough I am using reinforced servo which is pulling 32 items at the time). When I came back from the deep dark the storage crate was empty, all my ores that I mined for an hour disappeared. I actually don't know what is causing that, but I suspect the itemducts are doing it. I am using storage crates to store all my items and they are all working fine.

Screenshot: https://i.imgur.com/dNut2gn.png
latest.log: http://paste.feed-the-beast.com/view/cda53568
Forge version: 14.22.1.2485
CoFH core: CoFHCore-1.12-4.3.6.14-universal
Thermal dynamics: ThermalDynamics-1.12-2.3.6.13-universal

Edit: Setup is in the overworld and the chunks were not loaded when I was in the deep dark so I just assumed that it would not pull items at all.

I am not sure which mod is using this so I apologize if this not a bug in thermal dynamics and sorry for the long post.

**Comment by KingLemming** [comment]
No, they don't void items. This isn't us.

There was a bug at one point where Storage Crates were doing it, however. I'm unsure if that's been fixed or not.

And just as a general rule, please try to avoid posting issues (on any tracker, not just this one) with a ? at the end. It generally follows the same rules as clickbait articles - if there's a question mark on the end, the answer is almost always negative.
