### ISSUE TITLE
[1.12][Thermal Dynamics] covers not working with Tinkerers Construct Seared Brick

### ISSUE THREAD

**Issue by The-Scout** [CoFH/Feedback#603]
Issue:I cannot make TC seared brick blocks of any kind to make covers

Steps to replicate:craft a structueduct and any TC seared brick together

**Comment by covers1624** [comment]
Alright, their block is either not specifying that it is solid or it is a tile entity, nothing we can do.

**Comment by KingLemming** [comment]
It's a tile entity, yes.
