### ISSUE TITLE
[Crash]Fluxduct inventory item render

### ISSUE THREAD

**Issue by Frontrider** [CoFH/Feedback#603]
http://pastebin.com/0UpuSLk1

From what I see, The crash was caused by the 3 pieces of redstone energy fluxduct on my hotbar.

**Comment by KingLemming** [comment]
Sort of, yes.

The issue is that this is something where another mod botched the render context. Basically they set up a land mine and we stepped on it.

If it were in the duct code, this would happen every time and obviously we wouldn't have released it.

Does this happen consistently?
