### ISSUE TITLE
Crash in 1.10 custom modpack

### ISSUE THREAD

**Issue by Trinsdar** [CoFH/Feedback#604]
When loaded together in my modpack Thermal expansion and libvulpes cause a crash. It does not happen when just thermal expansion and libvulpes are loaded however.

Crash report: https://pastebin.com/HezZexP5

Here is a pic of the mods I'm using: https://imgur.com/a/Ukc0L
minecraft 1.10.2
forge1.10.2-12.18.3.2511

**Comment by KingLemming** [comment]
So you have a mod which is handling OreDict registration improperly. It might be LibVulpes, might not. Unfortunately, there's not a good way to know. But it *is* ultimately a LibVulpes ore.
