### ISSUE TITLE
SlotEnergy not accepting items with Forge Energy Capability

### ISSUE THREAD

**Issue by rubensworks** [CoFH/Feedback#605]
`SlotEnergy` only seems to accept items that implement the `IEnergyContainerItem` interface, and not items that have the Forge Energy capability.

This means that items that only have this Forge capability can not be inserted into Thermal Expansion machines for transferring energy into the machine's internal buffer.

**Comment by KingLemming** [comment]
Yep. This is true. Capabilities are pretty inefficient for this slot so I'm unsure if they should be supported.

**Comment by KingLemming** [comment]
I'm not a fan, but it probably won't be game breaking.
