### ISSUE TITLE
[1.10.2-5.1.10.28] Dynamos randomly refuse to rotate via Crescent Hammer

### ISSUE THREAD

**Issue by SephirothWS** [CoFH/Feedback#606]
I've done a bit of research, and I've noticed this issue has cropped up before, but closed as an invalid issue. Unfortunately this is indeed a problem as I am pulling my hair out with trying to rotate my dynamos and just watching them stare back at me with a blank face. Shift-Rclick works to pick them up instantly, but the standard right-click doesn't seem to do anything. However sometime later on when NOTHING has changed, no config changes, no mod changes, nothing, and all of a sudden they're rotatable as they should be. Therefore it has nothing to do with other mods blocking the event, as it works sometimes and not all the times as it should. (Modpack: Foolcraft v2.4)

On a side note: I wouldn't be having this issue if when placed, dynamos wouldn't face in to another dynamo and would instead prioritize facing into the ender IO conduit above them. When using Fluxducts from Thermal Dynamics the dynamos won't even auto-orientate themselves to the fluxducts and instead always place facing up or facing into a nearby dynamo that's already in the world.

**Comment by KingLemming** [comment]
Well, I can't replicate it and never have been able to. The auto-rotate is something I may end up removing. We'll see.

I'll give you a week to actually provide some sort of actual evidence for this, but as far as I can tell, it's still an invalid issue.

**Comment by KingLemming** [comment]
Actually, let me guess..you're standing on them, aren't you? Or there's some other entity touching them?

**Comment by SephirothWS** [comment]
No other entity touching them. Not standing on them either. https://youtu.be/u7M6837WXb0

**Comment by KingLemming** [comment]
Hrm. Couple of things there - FTBUtils is known to screw things up with its chunk loading, and EnderIO conduit may also mess it up. Do you have evidence of a dynamo getting stuck by itself?

**Comment by SephirothWS** [comment]
Here's the thing, the EnderIO conduits actually cause the auto-orientation to work (90% of the time) ... whereas dynamics' own ducts don't even trigger it so they face straight up unless another dynamo is near it when placed. https://youtu.be/r40azf3yavs ... Also you can see I've placed a lone one on its lonesome and it refuses to rotate.

**Comment by KingLemming** [comment]
Yes - the reason for that is that dynamos auto-rotate to valid acceptors. Ducts are not considered valid until the dynamo is there, because they're optimized. It's counter-intuitive I know, but that's just how it works.

**Comment by KingLemming** [comment]
Also, I've traced the codepath for the Wrench action (again), and here's what it boils down to. Wrench will fail under the following conditions:

- The PlayerInteract event is cancelled.
- The TileEntity is null or invalid.
- There is an entity inside the collision box of the object.

The first one is caused by another mod. Period. That's the only thing that can make that happen.
The second one means that your game has decided to force-unload the entity, which puts the game in a bugged state. If I were to allow the wrench action to go through here, it would crash outright. Perhaps I should log an error to console. And the video safely rules the third one out here, which is fine.

However, in neither of the first two cases is this actually the fault of TE. There's literally nowhere in the code where it can "randomly" fail - code doesn't work that way.

**Comment by SephirothWS** [comment]
Hmm, then I wonder how we can trace where the PlayerInteract event is cancelled at. Like I edited in to the original post, I'm running the Foolcraft modpack on v. 2.4 ... There's quite the listing of mods. I'm no guru on this one so I'm unsure which one can do this.

**Comment by KingLemming** [comment]
Unfortunately, there's not a great way to do that. Forge doesn't have a way of dumping everything that catches events, as as you said yourself it's a bit sporadic. My *guess* is that this is FTB Utils and some sort of claiming/ownership interaction.

In any case, I'm absolutely certain it's nothing specific to TE's code. I will, however, remove default rotation from dynamos to provide consistency in placement.

**Comment by janagyjr** [comment]
I am having the same issue, FoolCraft 1.4.8, I have done several tests in creative single-player (I'm running a server right now and would invite you to it to demonstrate) and in SMP (same world). Not having this issue in a creative test world or in my SSP world. I believe one of my recent VODs on Twitch will demonstrate this ( https://www.twitch.tv/tcgjoe ). I'm unsure of the cause and - if as OP said - it resumes normal operation I'll try not to be bothered by it.
