### ISSUE TITLE
Warp itemducts cause massive drop in FPS when powered.

### ISSUE THREAD

**Issue by NolanSyKinsley** [CoFH/Feedback#607]
Warp itemducts, when powered, cut FPS in half at least. If you move right up to one it can cut your fps by 75% or more, got me down to ~14 fps from my 50-60 normal.

I am using Agrarian skies 2 modpack version 1.1.6

**Comment by KingLemming** [comment]
You're on a potato that can't handle shaders. There's a config option to disable them.

**Comment by NolanSyKinsley** [comment]
That is a negative, only option there is for tesseract starfield, and enabling it does not change the warp itemduct situation.

**Comment by KingLemming** [comment]
CoFH Core's client.cfg has an option to disable shaders. It's there.

Also, what kind of potato are you running on?
