### ISSUE TITLE
Unable to preinitialize cofh core in FTB modpack.

### ISSUE THREAD

**Issue by Johnny1023** [CoFH/Feedback#608]
![bug](https://cloud.githubusercontent.com/assets/11202831/8151618/54bf3c9c-12ce-11e5-9073-b45f2f0eabc0.PNG)

 This issue somehow makes cofh unlaunchable.

Computer Info: 32-Bit Java, Java 8.45.

The path to the Java file directed correctly, so I don't know what is wrong.

**Comment by KingLemming** [comment]
Not on us. It happens to show us, but it could be any number of mods that interact with us incorrectly.

We know that ours work, sorry. :/

Try reinstalling the modpack and take it over to FTB. It clearly works for most people; this is a configuration thing on your end. As such, this is a tech support question and not an issue.
