### ISSUE TITLE
Flux Anodizer augment issue

### ISSUE THREAD

**Issue by Gorden211** [CoFH/Feedback#609]
When using the Flux Anodizers Augment in a Redstone Furnace for fast ore doubling the Redstone Furnace does not accept Thermal Foundation Aluminum Ore, maybe because it is not recognized as ore.
Immersive Engineering Bauxite Ore and Mekanism Osmium Ore aren't accepted as well.  

The issue occured in All The Mods 3 version 4.3. I posted the issue on their github as well, but they asked me to post it here, since it seems to be a mod issue.

**Comment by KingLemming** [comment]
Those Ores are not smeltable in a normal furnace. Hence they are also not smeltable in a Redstone Furnace. There is no issue here.

**Comment by Gorden211** [comment]
I thought they were smeltable in a Redstone Furnace by default, since without the Anodizer Augment I could smelt them in the very same Redstone Furnace, but the recipe was probably added by the pack devs.  
Sorry for the confusion.

**Comment by KingLemming** [comment]
Okay, now THAT is interesting. I'll see if that can be remedied. It may be a quirk of ModTweaker.
