### ISSUE TITLE
1.7.10 coFH core crashes when preintializing

### ISSUE THREAD

**Issue by W1CKED-Toaster** [CoFH/Feedback#611]
I know that  1.7.10 is kind of outdated, but i like the older versions of minecraft. i don't know what's messing up. it also says something about it not having an MCV Version annotation. I'm not really sure how the crash report works on the new layout, so here is my game output, i think they're the same thing

07:33:10 | launcher | main | info | Preparing to launch minecraft client for 1.7.10-Forge10.13.4.1614-1.7.10
-- | -- | -- | -- | --
07:33:12 | launcher | main | warn | Couldn't get hash for net/minecraftforge/forge/1.7.10-10.13.4.1614-1.7.10/forge-1.7.10-10.13.4.1614-1.7.10.jar from http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.7.10-10.13.4.1614-1.7.10/forge-1.7.10-10.13.4.1614-1.7.10.jar.sha1: HTTP 404: Not Found
07:33:12 | launcher | main | warn | Have local file C:/Users\Alyssa\AppData\Roaming\.minecraft\libraries\net/minecraftforge/forge/1.7.10-10.13.4.1614-1.7.10/forge-1.7.10-10.13.4.1614-1.7.10.jar but don't know what size or hash it should be. Have to assume it's good.
07:33:12 | launcher | main | warn | Couldn't get hash for com/typesafe/config/1.2.1/config-1.2.1.jar from http://files.minecraftforge.net/maven/com/typesafe/config/1.2.1/config-1.2.1.jar.sha1: HTTP 404: Not Found
07:33:12 | launcher | main | warn | Couldn't get hash for org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar from http://files.minecraftforge.net/maven/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar.sha1: HTTP 404: Not Found
07:33:12 | launcher | main | warn | Couldn't get hash for org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar from http://files.minecraftforge.net/maven/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar.sha1: HTTP 404: Not Found
07:33:12 | launcher | main | warn | Couldn't get hash for com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar from http://files.minecraftforge.net/maven/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar.sha1: HTTP 404: Not Found
07:33:12 | launcher | main | warn | Couldn't get hash for org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar from http://files.minecraftforge.net/maven/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar.sha1: HTTP 404: Not Found
07:33:12 | launcher | main | warn | Couldn't get hash for 1.7.10 jar from https://s3.amazonaws.com/Minecraft.Download/versions/1.7.10/1.7.10.jar.sha1: HTTP 403: Forbidden
07:33:12 | launcher | main | warn | Have local file C:/Users\Alyssa\AppData\Roaming\.minecraft\versions\1.7.10/1.7.10.jar but don't know what size or hash it should be. Have to assume it's good.
07:33:12 | launcher | main | warn | Couldn't get hash for org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar from http://files.minecraftforge.net/maven/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar.sha1: HTTP 404: Not Found
07:33:12 | launcher | main | warn | Couldn't get hash for org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar from http://files.minecraftforge.net/maven/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar.sha1: HTTP 404: Not Found
07:33:12 | launcher | main | warn | Couldn't get hash for org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar from http://files.minecraftforge.net/maven/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar.sha1: HTTP 404: Not Found
07:33:13 | launcher | main | warn | Couldn't get hash for org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar from http://files.minecraftforge.net/maven/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar.sha1: HTTP 404: Not Found
07:33:13 | launcher | main | warn | Couldn't get hash for org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar from http://files.minecraftforge.net/maven/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar.sha1: HTTP 404: Not Found
07:33:13 | launcher | main | warn | Couldn't get hash for org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar from http://files.minecraftforge.net/maven/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar.sha1: HTTP 404: Not Found
07:33:13 | launcher | main | warn | Have local file C:/Users\Alyssa\AppData\Roaming\.minecraft\libraries\com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar but don't know what size or hash it should be. Have to assume it's good.
07:33:13 | launcher | main | warn | Have local file C:/Users\Alyssa\AppData\Roaming\.minecraft\libraries\org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar but don't know what size or hash it should be. Have to assume it's good.
07:33:13 | launcher | main | warn | Have local file C:/Users\Alyssa\AppData\Roaming\.minecraft\libraries\com/typesafe/config/1.2.1/config-1.2.1.jar but don't know what size or hash it should be. Have to assume it's good.
07:33:13 | launcher | main | warn | Have local file C:/Users\Alyssa\AppData\Roaming\.minecraft\libraries\org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar but don't know what size or hash it should be. Have to assume it's good.
07:33:13 | launcher | main | warn | Have local file C:/Users\Alyssa\AppData\Roaming\.minecraft\libraries\org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar but don't know what size or hash it should be. Have to assume it's good.
07:33:13 | launcher | main | warn | Have local file C:/Users\Alyssa\AppData\Roaming\.minecraft\libraries\org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar but don't know what size or hash it should be. Have to assume it's good.
07:33:13 | launcher | main | warn | Have local file C:/Users\Alyssa\AppData\Roaming\.minecraft\libraries\org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar but don't know what size or hash it should be. Have to assume it's good.
07:33:13 | launcher | main | warn | Have local file C:/Users\Alyssa\AppData\Roaming\.minecraft\libraries\org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar but don't know what size or hash it should be. Have to assume it's good.
07:33:13 | launcher | main | warn | Have local file C:/Users\Alyssa\AppData\Roaming\.minecraft\libraries\org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar but don't know what size or hash it should be. Have to assume it's good.
07:33:13 | launcher | main | warn | Have local file C:/Users\Alyssa\AppData\Roaming\.minecraft\libraries\org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar but don't know what size or hash it should be. Have to assume it's good.
07:33:13 | launcher | main | warn | Have local file C:/Users\Alyssa\AppData\Roaming\.minecraft\libraries\org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar but don't know what size or hash it should be. Have to assume it's good.
07:33:15 | launcher | main | info | Checking installations.
07:33:15 | launcher | main | info | Minecraft client 1.7.10-Forge10.13.4.1614-1.7.10 is ready to start.
07:33:15 | launcher | main | info | Starting!
07:33:20 | launcher | main | info | Using default game log configuration client-1.7.xml (outputs XML)
07:33:34 | LaunchWrapper | main | info | Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
07:33:36 | LaunchWrapper | main | info | Using primary tweak class name cpw.mods.fml.common.launcher.FMLTweaker
07:33:36 | LaunchWrapper | main | info | Calling tweak class cpw.mods.fml.common.launcher.FMLTweaker
07:33:36 | FML | main | info | Forge Mod Loader version 7.99.40.1614 for Minecraft 1.7.10 loading
07:33:36 | FML | main | info | Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_25, running on Windows 7:amd64:6.1, installed at C:\Program Files (x86)\Minecraft\runtime\jre-x64\1.8.0_25
07:33:39 | FML | main | warn | The coremod cofh.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
07:33:39 | LaunchWrapper | main | info | Loading tweak class name cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
07:33:39 | LaunchWrapper | main | info | Loading tweak class name cpw.mods.fml.common.launcher.FMLDeobfTweaker
07:33:39 | LaunchWrapper | main | info | Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
07:33:39 | LaunchWrapper | main | info | Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
07:33:39 | LaunchWrapper | main | info | Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
07:33:54 | FML | main | info | Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
07:33:54 | FML | main | info | Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
07:33:54 | LaunchWrapper | main | info | Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
07:33:54 | LaunchWrapper | main | info | Calling tweak class cpw.mods.fml.common.launcher.FMLDeobfTweaker
07:34:02 | LaunchWrapper | main | info | Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
07:34:07 | LaunchWrapper | main | info | Loading tweak class name cpw.mods.fml.common.launcher.TerminalTweaker
07:34:07 | LaunchWrapper | main | info | Calling tweak class cpw.mods.fml.common.launcher.TerminalTweaker
07:34:07 | LaunchWrapper | main | info | Launching wrapped minecraft {net.minecraft.client.main.Main}
07:34:22 | net.minecraft.client.Minecraft | main | info | Setting user: W1CKED_Toaster
07:34:38 | net.minecraft.client.Minecraft | Client thread | info | LWJGL Version: 2.9.1
07:34:45 | STDOUT | Client thread | info | [tv.twitch.StandardCoreAPI:<init>:16]: If on Windows, make sure to provide all of the necessary dll's as specified in the twitchsdk README. Also, make sure to set the PATH environment variable to point to the directory containing the dll's.
07:34:45 | net.minecraft.client.Minecraft | Client thread | error | Couldn't initialize twitch stream
07:34:48 | STDOUT | Client thread | info | [cpw.mods.fml.client.SplashProgress:start:188]: ---- Minecraft Crash Report ---- // You should try our sister game, Minceraft!  Time: 11/1/17 7:34 AM Description: Loading screen debug info  This is just a prompt for computer specs to be printed. THIS IS NOT A ERROR   A detailed walkthrough of the error, its code path and all known details is as follows: ---------------------------------------------------------------------------------------  -- System Details -- Details: 	Minecraft Version: 1.7.10 	Operating System: Windows 7 (amd64) version 6.1 	Java Version: 1.8.0_25, Oracle Corporation 	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation 	Memory: 211888064 bytes (202 MB) / 268435456 bytes (256 MB) up to 1073741824 bytes (1024 MB) 	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M 	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used 	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0 	FML:  	GL info: ' Vendor: 'Intel' Version: '2.1.0 - Build 8.15.10.2202' Renderer: 'Intel(R) HD Graphics'
07:34:49 | MinecraftForge | Client thread | info | Attempting early MinecraftForge initialization
07:34:49 | FML | Client thread | info | MinecraftForge v10.13.4.1614 Initialized
07:34:51 | FML | Client thread | info | Replaced 183 ore recipies
07:34:51 | MinecraftForge | Client thread | info | Completed early MinecraftForge initialization
07:34:52 | FML | Client thread | info | Found 0 mods from the command line. Injecting into mod discoverer
07:34:52 | FML | Client thread | info | Searching C:\Users\Alyssa\AppData\Roaming\.minecraft\mods for mods
07:34:52 | FML | Client thread | info | Also searching C:\Users\Alyssa\AppData\Roaming\.minecraft\mods\1.7.10 for mods
07:36:42 | FML | Client thread | info | Forge Mod Loader has identified 6 mods to load
07:36:43 | FML | Client thread | info | FML has found a non-mod file CodeChickenLib-1.7.10-1.1.3.138-universal.jar in your mods directory. It will now be injected into your classpath. This could severe stability issues, it should be removed if possible.
07:36:43 | FML | Client thread | info | Attempting connection with missing mods [mcp, FML, Forge, <CoFH ASM>, CoFHCore, Baubles] at CLIENT
07:36:43 | FML | Client thread | info | Attempting connection with missing mods [mcp, FML, Forge, <CoFH ASM>, CoFHCore, Baubles] at SERVER
07:36:47 | net.minecraft.client.resources.SimpleReloadableResourceManager | Client thread | info | Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:CoFH Core, FMLFileResourcePack:Baubles
07:36:47 | FML | Client thread | info | Processing ObjectHolder annotations
07:36:47 | FML | Client thread | info | Found 337 ObjectHolder annotations
07:36:47 | FML | Client thread | info | Identifying ItemStackHolder annotations
07:36:47 | FML | Client thread | info | Found 0 ItemStackHolder annotations
07:36:47 | FML | Client thread | info | Configured a dormant chunk cache size of 0

**Comment by W1CKED-Toaster** [comment]
NOTE: i ran this without any mods, but it also happens with mods being there

**Comment by covers1624** [comment]
Err, i have no idea what that log file is doing here on git, it appears to be formatted as a table, at any rate, please edit your post and remove it and provide your crash over a paste service such as pastebin. Even them i don't think there is anything we can do, 1.7 is finalized and we wont be making any changes.
