### ISSUE TITLE
ReplaceVanillaGeneration is set to true and it doesn't seem to work

### ISSUE THREAD

**Issue by BakermanLP** [CoFH/Feedback#612]
Hello,
you already had an similar issue, but here are some more information we got. First of all the version numbers and configs can be found here:

https://github.com/combak/ShatteredWorld

This will be a world somehow similar to skyblock. The spawned island have ores spawned, but in this config https://github.com/combak/ShatteredWorld/blob/master/config/cofh/world/Vanilla.json there are only gravel and dirt.

The config value to replace Vanilla Generation is set:
https://github.com/combak/ShatteredWorld/blob/master/config/cofh/core/common.cfg#L43

Reloading the config via "/cofh reloadworldgen" seems to work and the settings are also correct:
[15:37:33] [Server thread/INFO] [CoFHWorld]: CoFH Core found 2 World Generation files present in /home/minecraft/config/cofh/world/.
[15:37:33] [Server thread/INFO] [CoFHWorld]: Reading world generation info from: /home/minecraft/config/cofh/world/ThermalFoundation-Ores.json:
[15:37:33] [Server thread/INFO] [CoFHWorld]: Reading world generation info from: /home/minecraft/config/cofh/world/Vanilla.json:

Can you see anything, what's going wrong here.

Thanks a lot

Michael (aka BakermanLP)

**Comment by KingLemming** [comment]
Literally just tested it. It works. You may have another mod adding some vanilla generation outside of CoFHCore.

**Comment by BakermanLP** [comment]
You are right, just found in the source code of FunWorldGeneration, that he doesn't use vanilla ore distribution. He uses instead his own code. 

Thanks for looking at this issue.

I close it.
