### ISSUE TITLE
[1.7.10] Sends to frozen state and Crashes

### ISSUE THREAD

**Issue by Xaikii** [CoFH/Feedback#613]
when trying to get into my world I get this issue, it doesn't happen every time, but at the last 10 startups, it crashed 7 times... so often enough that it's worth it to report.

https://pastebin.com/LFndZznm

If somehow helpful here is my modlist:
https://pastebin.com/WBaZL3wb

**Comment by KingLemming** [comment]
This is caused by a mod you have registering a null to the OreDictionary. They're setting up a land mine, we're just stepping on it.

Sorry.

**Comment by Xaikii** [comment]
Ok thanks, now I know what to do. :)
