### ISSUE TITLE
[MFR][Feature] Enchantment Router

### ISSUE THREAD

**Issue by Timeslice42** [CoFH/Feedback#614]
Can the enchantment router be changed so that it will send unenchanted items to a color which has an unenchanted item in the filter? This would allow the router to seperate enchanted items from unenchanted items without having to set "Unmapped" to true and have every enchantment specified in the other colors.

**Comment by knoeki** [comment]
In addition, maybe a way to seperate all enchanted items from all non-enchanted items, without having to specify each different item. There seems to be absolutely nothing that does this.

**Comment by Timeslice42** [comment]
Agreed, since that's technically what I'm trying to do.

**Comment by skyboy** [comment]
Placing a book in a slot will route unrouted enchantments that way.

**Comment by Timeslice42** [comment]
Nice. Thanks for this.
