### ISSUE TITLE
ItemStack null crash with other mod 

### ISSUE THREAD

**Issue by Wugand** [CoFH/Feedback#614]
In preperation for BTM we get following crash:
https://github.com/mcenderdragon/Futurepack-API/issues/296
https://gist.github.com/copygirl/3c51f10a1fc8bdb5d47a1ae1916c1cac
Thermal Dynamics version : "ThermalDynamics-1.12-2.3.6.13-universal"

It seems that the Thermal Dynamics pass "null" ItemStacks to "insertItem" functions. This will cause crashs at every mod written (only) on Minecraft 1.12 rules (ItemStacks should never be null,  instead ItemStack.Empty).

**Comment by KingLemming** [comment]
Nope. We do not. We absolutely do not pass nulls. Millions of downloads and this is literally the only time this has happened?

This is 110% on Futurepack.

**Comment by Wugand** [comment]
Sorry for that. We added null checks our self. And see no reseaon, so we asked the next mod appearing in the log.
If you don't pass null, ok. Thanks for the information. We search at other places, which can cause the probelm. 
(Maybe I should mark such issues as questions next time)

We definitly don't want to blame, we simple search for the reason.
