### ISSUE TITLE
Aluminum exclutivity

### ISSUE THREAD

**Issue by thyratron97** [CoFH/Feedback#615]
I am trying to play with Immersive Engineering and Thermal Foundation at the same time, and i'm experiencing trouble. The Immersive Engineering mod requires Bauxite ore to produce aluminium (aluminum), but so far the only aluminum yielding ore found so far is the aluminum ore from Thermal foundation which requires the use of a redstone furnace. Is there a way to modify TF to allow Aluminum to be smelted by a vanilla furnace, or at the very least an advanced EI furnace?

**Comment by KingLemming** [comment]
This is a modpack specific problem, sorry. And it's tech support, not an actual issue.

Feel free to try the Twitch chat and somebody more knowledgable with ModTweaker or some such may be able to help: https://app.twitch.tv/invite/SipeCoinsSvalna
