### ISSUE TITLE
Tesseracts security tab not working.

### ISSUE THREAD

**Issue by NervouS447** [CoFH/Feedback#616]
So, i've looked at issues for this and is states it is fixed.
I am playong on a server which is using the Agrarian skies 2, 1.1.6
The problem started when the previous Head-Admin had a hissy fit and decided to try and kill the server deleting files etc.
I'm wondering if the issue has to be with the players data.

**Comment by KingLemming** [comment]
Yup, sounds like your admin borked it. You can't just delete data like that and have it work.
