### ISSUE TITLE
Feature Request: Augment to allow RF pass-through on machines

### ISSUE THREAD

**Issue by dallenwilson** [CoFH/Feedback#616]
If this has been proposed and declined before then I apologize, I made only a cursory search of the closed issues on this tracker.

I propose a machine augment that will allow a machine to pass RF to an adjacent machine, at a reduced transfer rate (say, half what a leadstone fluxduct can handle, or less).

**Comment by covers1624** [comment]
I suggested this ages ago to lemming and basically it boils down to, a machine is optimized to do machine things, a duct is optimized to transfer stuff. It would be an insane amout of work and essentially mean mergring 2 massive mods together, just to allow an augment to transfer power between machines. Its gonna be a no sorry.
