### ISSUE TITLE
[Redstone Arsenal] Fallback recipe for obsidian rods missing

### ISSUE THREAD

**Issue by AllieWade** [CoFH/Feedback#617]
When installed without Thermal Expansion or obsidian-dust-providing mods, the fallback recipe for obsidian rods (2 obsidian+blaze powder) is missing, preventing them from being crafted.

Test modpack:

Minecraft 1.12.2
Forge 14.23.0.2529

CoFH Core 1.12-4.3.6.14-universal
Just Enough Items 1.12.2-4.8.0.111
Redstone Arsenal 1.12-2.3.6.16
Redstone Flux 1.12-2.0.1.2-universal

**Comment by KingLemming** [comment]
Well, don't play without Thermal Expansion. :(
