### ISSUE TITLE
[Thermal Expansion] [Feature Request] Fuels.cfg Explanation

### ISSUE THREAD

**Issue by Kalbintion** [CoFH/Feedback#618]
I am working on a modpack and wanted to add additional fuels for the various dynamos, after having discovered the fuels.cfg file for this purpose, I have zero understanding of what it is expecting for the names and with no comments in this file for the settings, I do not see how others would be able to understand what is going on in this file that would allow them to customize additional fuels.

So this feature request is simple: Add a few lines on what the file wants in regards to fuels.

is it the ore dictionary name? Item name? ID number? How does the Enervation dynamo know by "redstone" that it is to accept the redstone block as well? Does this automatically work for additional fuels that may have a block counterpart? None of these questions are answered with the currently available config file and the (lack of) notes explaining the file.

**Comment by KingLemming** [comment]
Did you see the readme? This repo isn't for questions. Take them to IRC please.

**Comment by Kalbintion** [comment]
I did, and are file comments not a valid suggestion considering some of the other files have comments explaining the options?

**Comment by KingLemming** [comment]
I'll see what can be done. That file format is somewhat limiting.

**Comment by Kalbintion** [comment]
Saw your post edit explaining it. Not asking for a help block, giant or otherwise, and since it isn't possible for custom fuels to be added, then a suggestion to add a comment in there on one of the values to indicate as such for those that are coming around that may want to do the same saying that isn't possible.

Thanks for the responses.
