### ISSUE TITLE
Client Crash, ArrayIndexOutOfBoundsException on BlockOre.getLightValue

### ISSUE THREAD

**Issue by Skid-Inc** [CoFH/Feedback#62]
I'm getting crashes whenever a jump to a Mystcraft age that was working prior to one of the last updates. The world loads for 5-10 seconds then just crashes the client with an ArrayIndexOutOfBoundsException, on thermalfoundation.block.BlockOre.getLightValue(BlockOre.java:52) ~[BlockOre.class:?] the server remains unaffected by this error. Again the age was working fine up until an update, somewhere around version 1.0.0RC1-20, sorry I can't be more exact, should of reported it sooner.

Here is the full crash log: http://pastebin.com/ei8caV25

**Comment by skyboy** [comment]
Something has generated invalid blocks in the world. There are only 7 valid metadata values for ThermalFoundation ore (0 - 6). You must fix whatever is generating the bad blocks (verify jsons for CoFHWorldgen, and configs any other mod that can generate blocks in the world) and remove the invalid blocks via something like mcedit.
