### ISSUE TITLE
Crash when manually breaking Portable Tank

### ISSUE THREAD

**Issue by RhinoKneel** [CoFH/Feedback#62]
I had just built my first tank in a save and after figuring I'd take it with me to get lava (it was empty at the time), I figured my pick may do fine at the time. At about half-way progress the game froze and crashed.

I did later try and see the effects of using a pick on machines but those were fine. Portable Tank was the only thing causing the issue for me.

Crash log: [http://pastebin.com/wxM9gLsr](url)

**Comment by KingLemming** [comment]
I can't replicate this. Just broke one, no issues.

**Comment by RhinoKneel** [comment]
Issue caused by Fancy Block Particles. Will pass along the issue.

**Comment by KingLemming** [comment]
Ah ha! Thank you. :)
