### ISSUE TITLE
[Thermal Cultivation] Client Crash using Resonant Watering Can

### ISSUE THREAD

**Issue by Gorden211** [CoFH/Feedback#620]
I was using the TC highest tier Watering Can on a large patch of Mystical Agriculture Inferium crops. 
For quite a while it worked without problems, but all of a sudden I am getting a crash, just using the can. I tried it three times now and it always crashes just using the can on about the same spot. Not sure why and what's happening honestly, I'm not good at reading crash logs. On another spot the can works without issues again.
I have the world on a local server and the server still runs without issue, just the client crashes and the server log shows nothing related to the crash. 
I have the crashlog in a pastebin for you here: https://pastebin.com/jaanryay.
The pack is All The Mods 3. 

Hope this helps.

**Comment by KingLemming** [comment]
I need to know specifically what is in that spot. Screenshot please.

**Comment by KingLemming** [comment]
Is it anywhere on that y-level or just literally that single block? This isn't really making sense to me.

**Comment by Gorden211** [comment]
I just checked and crashed again, it seems to be anywhere on that y-level, not only that exact spot.

**Comment by KingLemming** [comment]
I can't make this happen in any way whatsoever I'm afraid. Can you make it happen with wheat, or only that particular modded crop?

**Comment by Gorden211** [comment]
I tried it and I indeed could replicate it with wheat.
Here's that crashlog if you need it: https://pastebin.com/wfEWgW4h

**Comment by KingLemming** [comment]
Okay well apparently this is already fixed in dev then, somehow. Because it just doesn't seem to happen for me.

**Comment by Gorden211** [comment]
Fine for me, I'm glad it's fixed, however it happened :D
