### ISSUE TITLE
Thermal expansion assumes 1 dusts equals 1 ingot

### ISSUE THREAD

**Issue by MrTJP** [CoFH/Feedback#620]
Im assuming TE looks at ore names and dynamically maps together "oreXXX" with "dustXXX" and "ingotXXX".  The smelter adds recipes that go from 1 dust to 1 ingot, a pulverizer recipe for 1 ore to 2 dusts, and a pulverizer recipe for 1 ingot to 1 dust, as well as a few others such as the pyro-dust and ore to ingot, and not to forget the doubling/tripling recipes with slag, cinnabar, etc.

There needs to be an api call to disable all of this, as its not always a correct assumption. (For example, my mod has an ore that drops a variable amount of dust when broken, and several pieces of dust are required to form 1 ingot.)

**Comment by KingLemming** [comment]
This can already be accomplished with IMC, but I'll see what we can do.

**Comment by MrTJP** [comment]
Maybe its a mod load order issue, but I tried removing the recipes manually, but they were being added anyway.

**Comment by KingLemming** [comment]
Were you adding alternatives as well? TE otherwise assumes outright removal of recipes to be a hostile action.

**Comment by KingLemming** [comment]
After triple-checking the code path, the issue is that you didn't provide an alternative. Do that, and it'll work out.
