### ISSUE TITLE
No Thermal Dynamics Fluid Transposer Recipes

### ISSUE THREAD

**Issue by RoloEdits** [CoFH/Feedback#621]
I Have None Of the Fluid Transposer Recipes For The Ducts, Only The Crafting Recipes With Buckets.

Using Version "ThermalDynamics-[1.7.10]1.0.0-122"

**Comment by KingLemming** [comment]
You have a mod or modpack removing them. It's not us.

**Comment by RoloEdits** [comment]
ok thanks for your help
