### ISSUE TITLE
[Thermal Dynamic]/[Thermal Expansion] Duct/tesseract interaction

### ISSUE THREAD

**Issue by jsrfuture** [CoFH/Feedback#622]
Hi, I've encounter what I believe is a bug with the filter, I've got a retriever connected to a tesseract, this retriever is pulling 6 different item, this tesseract is sending item to an other tesseract connected to a chest with a filter on it, in the filter is set to whitelist and allow half a stack of each of the 6 item, but only one item with go to this chest, ignoring that there is still room for the 5 other item.

Not sure if it is a bug or a limitation of how the filter is working.

**Comment by KingLemming** [comment]
Probably a limitation, but we really need screenshots for this as I'm not quite understanding your setup.

**Comment by jsrfuture** [comment]
Chest A(with item : dirt, stone,grass and other thing in it) -> retriever connected to a tesseract ---- tesseract -> chest b with a filter on it(filter option : whitelist dirt, stone and grass; max total item 32; rest is default) 

After some more testing, it's filling the B chest with 32 dirt block, droping some dirt block because I've set the filter to 32 and won't allow more then 32 in the chest because of that, and some other dirt block are on "hold" in the tesseract( i know it is in the tesseract because they won't come out if I break the duct) it won't send anything else because of those item in hold. I've notice when i've removed the dirt from the chest, the stone where coming in. I think that the issue is with the interaction between the tesseract and the duct,  the tesseract do not "understand" that there enough item on the way so it keep sending them, 8 block get stuck in the tesseract, 16 are droping on the ground. At first I though that turning "allow oversending" on would allow all the block on there way in the chest but It change nothing, again probably because the tesseract doesnt understand the duct/filter system. The only way I could think of to fix this would be to send ,via the tesseract, the pipe information too, but I doubt it's possibility, maybe with a new item/option to sync/lock 2 tesseract together.

I'm not sure it is fixable and if it is it's mostly have to do with the duct/tesseract interaction not the filter.If needed I could make a small video instead of screenshot, it would be way easier to show/understand all this in a 30 sec vid then with a dozen screenshot.

**Comment by KingLemming** [comment]
Yeah, this is just how Tesseracts work. A pretty solid won't fix for us I'm afraid. Coordinating data on that level would make them computationally ugly.
