### ISSUE TITLE
Eyy, Schematic Issue.

### ISSUE THREAD

**Issue by HardInk** [CoFH/Feedback#623]
The Machinist's Workbench has this silly issue where it likes to turn any kind of sandstone into default sandstone, which presents an issue if you have a mod that needs certain blocks to be made out of chiseled sandstone or smooth sandstone. (e.g. SGCraft's stargate blocks) Just a tiny thing, but throws a wrench in my plans for building a stargate factory until it's fixed. Thank you.

**Comment by KingLemming** [comment]
Won't get fixed, sorry. It uses OreDict and the Stargate should too.

**Comment by KingLemming** [comment]
Okay, after a bit of testing, I actually have no idea what you're talking about at all. The workbench conversions present for sandstone are correct. They are vanilla recipes.
