### ISSUE TITLE
Texture glitches :/

### ISSUE THREAD

**Issue by Adc808** [CoFH/Feedback#624]
If anyone has time I have a problem with the textures. They get glitchy when I put the mods in. Here is the list of mods http://paste.ubuntu.com/11794917/. Here is a video showing what is happening https://www.dropbox.com/s/vqptg8j0chm0j5n/Mod%20Problem%20recording.mov?dl=0

**Comment by KingLemming** [comment]
So are you using Optifine? If so, that's probably the cause.

**Comment by KingLemming** [comment]
Closing, since you said it was fixed in IRC.

**Comment by gcewing** [comment]
Can you tell me how you resolved this? I'm experiencing something very similar:
https://github.com/CoFH/Feedback/issues/1078

**Comment by Adc808** [comment]
I am pretty sure that I had to update my java.
