### ISSUE TITLE
[Thermal Dynamics] Dependency on CodeChickenLib

### ISSUE THREAD

**Issue by beckyh2112** [CoFH/Feedback#625]
Noticed this when I was starting a new 1.12.2 world, then took Thermal Dynamics and its listed dependencies (Thermal Foundation, COFH World, COFH Core, Redstone Flux API) off to a test instance where it was just those mods. Same error both times.

> Thermal Dynamics is missing mods it depends on. Include the following mods or remove Thermal Dynamics.
> - codechickenlib 3.1.3 or above

Thermal Dynamics 1.12-2.3.6.13
Thermal Foundation 1.12-2.3.6.16
COFH World 1.12-1.0.1.8
COFH Core 1.12-4.3.6.14
RedstoneFlux 1.12-2.0.1.2

Forge 2500 for regular instance and 2491 for test instance.

**Comment by KingLemming** [comment]
https://minecraft.curseforge.com/projects/thermal-dynamics/relations/dependencies
