### ISSUE TITLE
Reproducible crash

### ISSUE THREAD

**Issue by Kane122** [CoFH/Feedback#626]
I have found a reproducible crash which seems to be related to an interaction between EnderIO and Thermal Expansion. Placing an EnderIO Item Conduit on top of a Thermal Expansion Phytogenic Insolator and setting the machine's output slot to "open but colourless" (whatever is it's actual name) causes a crash and corrupts the world. Here is the crashlog I get when I try to load the corrupted world.

http://pastebin.com/5AwLcMZi

Note that this was a test world, with only the latest versions of Cofhcore, Thermal Foundation, Thermal Expansion and EnderIO installed.

**Comment by KingLemming** [comment]
Duplicet of #475.
