### ISSUE TITLE
[Thermal Expansion] Glowstone Illuminators set to "Always On" don't block mob spawns

### ISSUE THREAD

**Issue by tellowkrinkle** [CoFH/Feedback#627]
If you use glowstone illuminators set to always on (or another mode that allows them to be on without a redstone signal), mobs will still spawn, even though everything is bright and NEI's F7 indicator says they won't.

Tested with Agrarian Skies 2 version 1.1.6 as well as a custom pack using Thermal Expansion 4.0.1-182, Thermal Foundation 1.0.0-81, COFH Core 3.0.2-262, Extra Utilities 1.2.5, and Ex Nihilo 1.38-41.

![2015-07-01_23 44 15](https://cloud.githubusercontent.com/assets/3315070/8470189/be6a56fa-204c-11e5-84f9-ff6548a62f88.png)

**Comment by KingLemming** [comment]
I can't replicate this. You sure that there isn't something just overriding it on a pack level? Some sort of new spawn logic?

**Comment by tellowkrinkle** [comment]
I don't think so, unless ex nihilo or extra utilities changes something (I added them for void worlds and angel blocks respectively).  I did notice that turning on and off a redstone signal fixes the issue.  I guess I should also mention that I'm running Forge 10.13.4.1448.
Does it work with [this save](https://drive.google.com/file/d/0B2pegUqXIP2KTms0eGdSdGthUnc/view?usp=sharing)?

**Comment by KingLemming** [comment]
Yeah, this doesn't happen in dev, so it's either fixed in dev or is completely x-mod.

**Comment by KingLemming** [comment]
Just put out a new release. As I couldn't make it happen, I'm calling this fixed.
