### ISSUE TITLE
[Thermal Dynamics] mob spawning prevented

### ISSUE THREAD

**Issue by blocky-mcsquare** [CoFH/Feedback#628]
I built a mob spawning chamber in Agrarian Skies 1.1.6 utilizing a portable tank with energized glowstone connected to fluiducts to control the light level in the spawn chamber.  Mobs were spawning nicely in the dark spawn chamber with all the empty fluiducts in place, and the energized glowstone in the fluiducts worked well as a light source to stop the spawning.  When I drained the energized glowstone out of the fluiducts back into the portable tank, the light level (according to NEI & F3) dropped back down to 0, but mobs did not begin spawning again.  

I created a custom pack on the curse launcher using only CoFH Core 3.0.2-262, CoFHLib 1.0.2-160, Thermal Foundation 1.0.0-81, Thermal Expansion 4.0.1-182, and Thermal Dynamics  1.0.0-122.  I created a similar spawn chamber with lighting controlled by energized glowstone in fluiducts, and had similar results.

It seems that once the fluiducts have had energized glowstone in them, even though the light level is reported as 0, visually the fluiducts are empty, and all of the enregized glowstone (in mB) has returned to the portable tank, the fluiducts prevent mob spawning as if they still contained energized glowstone.  Covering the fluiducts with a block or  removing and replacing the fluiduct network will allow normal mob spawning again.  Inserting water into the ducts, placing and removing a different light source, and relogging do not affect the condition.

**Comment by KingLemming** [comment]
I can't replicate this. I'm starting to wonder if something has gone wrong in a Forge build.

**Comment by blocky-mcsquare** [comment]
I appreciate your taking the time to look into this, but I am disappointed you couldn't replicate my issue.  I have attached some screenshots from my test pack.

I deleted the custom curse pack I made and recreated it.  The forge version is forge-10.13.4.1481.  The other mods and versions are the same as stated above.

I continued to play around with my setup, and if I relog after running the glowstone in the ducts, I'm finding block light in the locations shown by the redstone blocks.  I destroyed the block light, but still no spawns.  I covered the ducts, spawns.  Uncovered the ducts, spawns.  Run glowstone in the ducts, no spawns. Take the glowstone out of the ducts, no spawns.  Relog, find block light in a similar position.  Rinse and repeat.  Hope this helps track things down.

![2015-07-02_16 24 34](https://cloud.githubusercontent.com/assets/13146448/8487372/aab2281c-20d9-11e5-9c50-53f650b2f550.png)
![2015-07-02_16 25 23](https://cloud.githubusercontent.com/assets/13146448/8487374/aab3e698-20d9-11e5-8c1b-aec6b455f2b7.png)
![2015-07-02_16 25 54](https://cloud.githubusercontent.com/assets/13146448/8487373/aab3c348-20d9-11e5-8c5b-c6b8a4075558.png)
![2015-07-02_17 15 08](https://cloud.githubusercontent.com/assets/13146448/8488148/a1fa2864-20de-11e5-9317-0fcac44e1e70.png)

**Comment by KingLemming** [comment]
Tried with your exact setup and it works fine for me. It's not that I don't believe you, I'm just not sure what's up. It may be fixed in dev already, if it is actually an issue.

**Comment by blocky-mcsquare** [comment]
Thanks again for looking, I suppose that's good news/bad news. I tried blowing out all my minecraft files and re-installing with the same results.  Is there a way for me to download the indev versions to see if it gone for me as well?

**Comment by KingLemming** [comment]
There isn't, but we'll have a release out soon hopefully.

**Comment by KingLemming** [comment]
New releases are out. This shouldn't be a problem.

**Comment by blocky-mcsquare** [comment]
Thanks for the update on the release. I'm out of town until tomorrow night, but I'll be sure to take a look then and let you know. 

Many thanks to you and everyone else who makes these mods and provides them to the community. You have given me many hours of entertainment, and your effort and generosity are much appreciated.

**Comment by blocky-mcsquare** [comment]
The updates have resolved my issue.  No more problems.  Thanks again.
