### ISSUE TITLE
Steam Dynamo does not accept Thermal Expansion

### ISSUE THREAD

**Issue by Xiaminou** [CoFH/Feedback#628]
I realise it can be similar to past issue but I can't be sure unless I ask.
I'm creating steam with Immersive Tech's Solar Tower and piping it into Steam Dynamo with the Turbine Augment. However those dynamos will not accept Steam.
The only Steam I can see in JEI is Thermal Expansion and when using a bucket on the steam produced by the Solar Tower it gives me TE's Steam.

![2017-11-11_23 31 41](https://user-images.githubusercontent.com/8670392/32694187-bd7eb204-c739-11e7-977f-ad7dda911cbd.png)

Minecraft: 1.12.2
Forge: 2537
Mods: [list.txt](https://github.com/CoFH/Feedback/files/1464177/list.txt)

**Comment by KingLemming** [comment]
What's happening here is that the solar tower isn't producing the correct steam. Forge is auto-converting it to TE steam based on bucket interactions. But it's just wrong, sorry.

**Comment by Xiaminou** [comment]
@KingLemming could you message @FerroO2000 and explain to him the steam problem? he doesn't seem to be listening to me.

**Comment by Xiaminou** [comment]
So I've just tried producing steam with a Steam Dynamo + Turbine Conversion and pumping it into a Steam Dynamo + Turbine Conversion and it's not going in. I never tested producing Steam from another source when I first reported this bug, it's starting to look like Steam in my modpack is bugged somehow;

I tried just Immersive Tech + Thermal Expansion and as it turns out it works just fine which means something else is causing Steam to go haywire and I can't figure out what.
