### ISSUE TITLE
Blaze -> Blizz

### ISSUE THREAD

**Issue by Allen24** [CoFH/Feedback#629]
Blizz are a rare type of mob. My suggestion is when a Blaze stay for 5 or more seconds in Gelid Cryotheum it will turn in a Blizz, something like freezing. This a small suggestion, it make any sense?

**Comment by Entoarox** [comment]
Whatever makes you think blizzes are rare? they show up in abundance in the relevant biomes, You just gotta make sure there are no wolves around to murder them immediately.

**Comment by KingLemming** [comment]
We don't want Blizzes to be super common things. However, the wolf problem is interesting. Will definitely look into that. :)

**Comment by Entoarox** [comment]
@KingLemming Oh, I actually thought that the wolves attacking blizzes was intended! Had I know that was a bug I'd have reported it ages ago!

**Comment by KingLemming** [comment]
Well, it's not actually a bug. The Blizz starts the fight. It's not intended that the wolves win frequently enough that it makes Blizzes super rare.

**Comment by Allen24** [comment]
It would be just a small feature.Gelid Cryotheum is a mid-game fluid (it require a magma crucible and/or a liquid transposer for the snowball-redstone method), snowballs are obtained from cold/snow biomes so there will be basically no problem with finding Blizzes.Just a side- feature, whatever.

**Comment by KingLemming** [comment]
Sorry, but there's already a way of obtaining Blizz Powder without a Blizz mid-game. Cryotheum would just kill a Blaze outright, as it should.

I'll see about adding some alternative way of spawning a Blizz though.
