### ISSUE TITLE
Pulverizer Stone to Cobblestone recipe

### ISSUE THREAD

**Issue by Xiaminou** [CoFH/Feedback#629]
I know with the Igneous Extruder being able to produce cobblestone it's not really necessary but why not add a recipe to convert Stone to Cobblestone with the Pulverizer?

**Comment by KingLemming** [comment]
Stone converts to gravel, that's why. ;)

**Comment by Xiaminou** [comment]
Sorry, I wasn't very clear. I meant re-work the Stone line to be, well, similar to Mekanism's.

**Comment by KingLemming** [comment]
Nah, I got that, just don't have any real interest in doing it.

**Comment by Xiaminou** [comment]
Fair enough.
