### ISSUE TITLE
Error message - Minimum version required 1.7.10R1.0.0RC1

### ISSUE THREAD

**Issue by simon-itch** [CoFH/Feedback#63]
Dear COFH team,

Unfortunately can't update beyond these versions -
THERMALFOUNDATION 1.7.10 1.0.B3-8
COFHLIB 1.7.10 1.0.0B7-29
COFHCORE 1.7.10 3.0.0B8-36
THERMALEXPANSION 1.7.10 4.0.0B6-16

I get the above error message when i try to add the recommended versions from COFH site 
i.e. -
THERMALFOUNDATION 1.7.10 1.0.RC1-13
COFHLIB 1.7.10 1.0.0B8-34
COFHCORE 1.7.10 3.0.0B9-40
THERMALEXPANSION 1.7.10 4.0.0B8-23

See screen shot - all other mods cleared out - config files deleted - Java running 8-31
![screen shot 2015-01-29 at 20 02 33](https://cloud.githubusercontent.com/assets/5850119/5964257/07959ee8-a7f3-11e4-8ce0-fb14228ae32a.png)

Forge running 10.13.2.1277

Suggestions of what to do?

Sorry to be a pain

**Comment by bochen415** [comment]
Upload the ForgeModLoader-client-0.log file to paste.ubuntu.com. Post the link

**Comment by KingLemming** [comment]
Oh yay, the Mac issue again. Update to Java 7 please. Paging @skyboy

**Comment by simon-itch** [comment]
The exciting thing is that there is no file named - ForgeModLoader-client-0.log
I took this from latest.log
http://paste.ubuntu.com/9942543/

Hope helps

**Comment by bochen415** [comment]
The King is always right. Mac + java 1.6. The mods aren't loading. 
@KingLemming isn't there a way to update java on those machines? I could sworn I read an article about it on Oracle's website.

**Comment by KingLemming** [comment]
@bochen415 I'm sure there is, but I don't know how.

@simon-itch Update Java. That's your issue. You aren't actually using 8-31, as your log clearly shows.

**Comment by bochen415** [comment]
> Update Java. That's your issue. You aren't actually using 8-31, as your log clearly shows.
...and remember do uninstall (if it's possible) the old java 1.6 or change the path to the java directory to point to the one with 1.8_31

**Comment by adudney** [comment]
1. You need to install Java 8 latest. Mac downloads are on the same page as all the other OS's.
2. Really really use MultiMC. Mojang's Java-app wrapper is horribly out of date and forces Java 6 unless you explicitly tell every single profile to use a newer version. With MultiMC it's just a few button presses and it works great.

**Comment by simon-itch** [comment]
Thanks for the help - i tried to get MultiMC running - but just couldn't get it set up with liteloader in 1.7.10...

On the other hand - using MultiMC gave me the exact path to Java 1.8 so I was able to copy that over into the path 'executable' in the regular Mac Minecraft launcher - i don't mind configuring every profile

So - all good - Thermal working lovely

Thanks
