### ISSUE TITLE
Tessellating CCL block in world

### ISSUE THREAD

**Issue by Xiaminou** [CoFH/Feedback#630]
Crashed while AFK in my base.
As always I'm not sure if it's CCL or TD's responsibility.

Crash Report: [crash-2017-11-12_02.33.13-client.txt](https://github.com/CoFH/Feedback/files/1464299/crash-2017-11-12_02.33.13-client.txt)

**Comment by covers1624** [comment]
TD is probably trying to render an invalid cover, ill investigate when im back at my main PC.

**Comment by X1machinemaker1X** [comment]
I had the same issue. Here is the crash report.

[crash-2017-11-20_21.55.07-client.txt](https://github.com/CoFH/Feedback/files/1490090/crash-2017-11-20_21.55.07-client.txt)

**Comment by covers1624** [comment]
Gonna need some steps to reproduce this one, I initially though that you had removed a mod and had covers made out of those blocks, but that doesn't seem to be the case..

**Comment by X1machinemaker1X** [comment]
I had the issue with covers I placed underneath tinkers construct casting basins on the itemduct pulling out of the basins. Other than that, I can't think of anything I did that caused it. I removed the covers and havent crashed since. It wasnt an immediate crash either, after some time, I would just crash

**Comment by Xiaminou** [comment]
If I knew the steps to reproduce I would have posted them. Unfortunately it seems to happen at random times while I'm in my base, and since I have lots of covers everywhere I can't exactly tell you which one is responsible.

**Comment by X1machinemaker1X** [comment]
@Xiaminou if you look in the crash report, there should be a location (x, y, z) somewhere near the beginning. Check there.

**Comment by Xiaminou** [comment]
Oh right I forgot they do that.

**Comment by Xiaminou** [comment]
![2017-11-27_16 17 36](https://user-images.githubusercontent.com/8670392/33273862-cf00e8f6-d38e-11e7-97f2-7b83ae252fac.png)
![2017-11-27_16 17 42](https://user-images.githubusercontent.com/8670392/33273864-cf18c6ec-d38e-11e7-93ca-e66f06014a54.png)
![2017-11-27_16 17 47](https://user-images.githubusercontent.com/8670392/33273865-cf2bdb1a-d38e-11e7-8d77-624607d60ac5.png)
![2017-11-27_16 18 44](https://user-images.githubusercontent.com/8670392/33273866-cf3e7d06-d38e-11e7-87d0-0bb8ce2a708b.png)

**Comment by Xiaminou** [comment]
![2017-11-28_17 38 18](https://user-images.githubusercontent.com/8670392/33331916-30355ede-d463-11e7-9ed7-8809976c7083.png)
![2017-11-28_17 38 30](https://user-images.githubusercontent.com/8670392/33331918-304c1b6a-d463-11e7-8d54-5c5c9c23bf5e.png)
![2017-11-28_17 38 33](https://user-images.githubusercontent.com/8670392/33331919-3063e9de-d463-11e7-8e32-2603158b2747.png)
![2017-11-28_17 38 42](https://user-images.githubusercontent.com/8670392/33331920-30784280-d463-11e7-942c-1e6ec10bf3bf.png)

**Comment by covers1624** [comment]
Just to confirm this is still happening like #712 after the latest update (2.3.7.14)?

**Comment by Xiaminou** [comment]
No crash so far, but I haven't played that much recently. I'm going to leave my game idle in my base tomorrow so we'll see.

**Comment by Xiaminou** [comment]
Still no crash, I'd say we're good.

**Comment by KingLemming** [comment]
Excellent.
