### ISSUE TITLE
Very serious Duping Problem with Thermal Expansion

### ISSUE THREAD

**Issue by SirTwsted** [CoFH/Feedback#631]
When you use a tinkers construct pick on any thermal expansion machine, or anything from thermal expansion for that matter, or its affiliated mods 
I get an extra of that same item I picked.
Here is the video: -->>  https://www.youtube.com/watch?v=t0pQaPHbUhY

Minecraft:  v1.12.2
Forge: 14.23.0.2529
JRE: 1.8.0.121

CoFHCore-1.12-4.3.6.14-universal.jar
CoFHWorld-1.12-1.0.1.8-universal.jar
ThermalCultivation-1.12-0.1.1.6-universal.jar
ThermalDynamics-1.12-2.3.6.13-universal.jar
ThermalExpansion-1.12-5.3.6.20-universal.jar
ThermalFoundation-1.12-2.3.6.16-universal.jar

**Comment by KingLemming** [comment]
This is a problem with Tinker's, not TE.

**Comment by SirTwsted** [comment]
Well, sorry KingLemming.... I guess you where wrong.
Sorry, I dont know why people dont believe me, so here is a video showing a vanilla pickaxe doing the same thing. :(
https://www.youtube.com/watch?v=_4739c-4QSk

**Comment by KingLemming** [comment]
I was partially wrong. I shouldn't have blamed TiCon, because they know what they're doing. As I mentioned in your duplicate issue which you should not have opened, it's another mod entirely.
