### ISSUE TITLE
Thermal Dynamics world corrupting crash with Calculator

### ISSUE THREAD

**Issue by SonarSonic** [CoFH/Feedback#632]
I'm getting this crash when using Impulse Item Ducts. I know the problem is inputting/outputting with the Storage Chamber (from my mod 'Calculator' which is partly an add-on for TE) but it works perfectly with every other mod I've tested with (AE2, Ender IO, Mekanism, Extra Utilities). However, with Thermal Dynamics it produces a world corrupting crash. This crash doesn't happen straight away but after a little while of operating properly. I doubt the problem is your end though.
The storage chamber allows you to store Circuits beyond their normal stack size, which is done by giving different slots depending on if it is a inputting or outputting which is where TD has the problem compared to other mods which handle it correctly.

Crash:
http://pastebin.com/1CuzUvax

Storage Chamber:
https://github.com/SonarSonic/Calculator/blob/master/sonar/calculator/mod/common/tileentity/machines/TileEntityStorageChamber.java

**Comment by KingLemming** [comment]
Sorry, but no. This isn't on us. There's nothing wrong with how TD attempts to do things; it obeys Minecraft conventions.

What *you* are doing however goes against the fabric of the game. You don't get to arbitrarily juggle slots, there is no mechanism for that.

All you are allowed to do is expose slots and say what can or can't go in them. Caches and other barrel-like things handle this properly.

**Comment by SonarSonic** [comment]
Haha, I already knew it was my end, I was just surprised I didn't get the problem with other mods, is there a better solution to my storage system?

**Comment by KingLemming** [comment]
This is basically caused by you not following slot numbering convention.

Slots must be numbered 0 through N. You're basically using arbitrary numbers.

**Comment by SonarSonic** [comment]
Thanks! I'll make some changes :)
