### ISSUE TITLE
Crescent Hammer causes Silent's Gems Material Grader to lose contents

### ISSUE THREAD

**Issue by kmadstarh** [CoFH/Feedback#632]
Versions

Minecraft Version: 1.12.2
Silent's Gems Version: 2.5.10-247
Silent Lib Version: 2.2.12-93
Thermal Expansion: 5.3.6.20

Expected behavior

- Thermal Expansion's Crescent Hammer rotates machines/blocks without changing contents.

Actual behaviour

- Using Crescent Hammer causes Material Grader to lose Chaos/Item Contents when rotating machine.

Steps to reproduce the problem

1. Place Items / Chaos inside Material Grader
2. Use TE Crescent Hammer to rotate Material Grader
3. Observe loss of items/chaos

**Comment by KingLemming** [comment]
Yep. That's bad. You better let them know.
