### ISSUE TITLE
Vanilla Pickaxe proving that it does Duplicate Thermal Expansion items VIDEO

### ISSUE THREAD

**Issue by SirTwsted** [CoFH/Feedback#633]
Sorry KingLemming.... I guess you were wrong.
Sorry, I dont know why people dont believe me, so here is a video showing a vanilla pickaxe doing the same thing. :(
https://www.youtube.com/watch?v=_4739c-4QSk

I really love your mod, I just don't like that you immediately shut me down & closed my issue.  :(

**Comment by KingLemming** [comment]
No. This is caused by another mod. Vanilla pickaxes DO NOT DO THIS NORMALLY.

You didn't provide a modlist for me to actually determine the real cause. Try with ONLY CoFH mods. This will not happen.
