### ISSUE TITLE
[Thermal Expansion] Strongbox In Item Form Uses Numeric IDs

### ISSUE THREAD

**Issue by airbreather** [CoFH/Feedback#633]
Sorry about not having detailed repro steps here.

Working on HQM modpack development, we have a reward that's a Strongbox filled with items.  Every time we change the mods in the pack (due to conflicts, or just updates because the world doesn't stop for us), the contents of the strongbox change.

Digging in, it looks like this is because the strongbox's NBT has a tag that looks like this:
```
TAG_List("Inventory"): 18 entries {
  TAG_Compound: 4 entries {
    TAG_Int("Slot"): 0
    TAG_Short("id"): 289
    TAG_Byte("Count"): 4
    TAG_Short("Damage"): 0
  }
  TAG_Compound: 4 entries {
    TAG_Int("Slot"): 1
    TAG_Short("id"): 4608
    TAG_Byte("Count"): 4
    TAG_Short("Damage"): 7
  }
  TAG_Compound: 4 entries {
    TAG_Int("Slot"): 2
    TAG_Short("id"): 377
    TAG_Byte("Count"): 3
    TAG_Short("Damage"): 0
  }
  ...
```

The way HQM stores its rewards is it serializes the ItemStack as ItemID (ThermalExpansion:Strongbox), Damage (1), Size (1), NBT (a Compound, including the above tag).

Relevant version numbers (there are other mods installed, this is just the CoFH stuff I could find in the list):
Forge 10.13.4.1448-1.7.10
CoFHCore-[1.7.10]3.0.2-262.jar (MD5: 97048ff79d08ad7b66ce71a6c1574e7a)
CoFHLib-[1.7.10]1.0.2-160.jar (MD5: 364a958227eb70a1cff6422d7ebf57b4)
ThermalFoundation-[1.7.10]1.0.0-81.jar (MD5: 1442f906d4b9adb1d8540533da6b1b5f)
ThermalExpansion-[1.7.10]4.0.1-182.jar (MD5: d8ad94bc7743ad87e7a384f22de283ed)
ThermalDynamics-[1.7.10]1.0.0-122.jar (MD5: 338c1c9100ea1e296dd0ef759a816afa)

**Comment by KingLemming** [comment]
Yup. Welcome to how literally *every* Inventory in Minecraft works. That is how ItemStacks are stored; it's part of the vanilla code to do that.

I'd like to help, but the issue here is that you're changing ItemIDs for some reason. That is basically due to FML and should only happen if you actually remove mods. All I can tell you is not to do that, sorry. :(

**Comment by airbreather** [comment]
I did some digging... it seems *hypothetically* possible to fix this on the ThermalExpansion side (at least for new strongboxes) by changing TileInventory.readInventoryFromNBT / TileInventory.writeInventoryToNBT to reimplement ItemStack.loadItemStackFromNBT / ItemStack.writeToNBT instead of calling the same, just using string instead of numeric item IDs, but the backwards compatibility concerns make it complicated, this use case isn't particularly strong, and it generally feels "icky", so I'm OK with this response.  Thanks.

**Comment by KingLemming** [comment]
Well, part of the issue there is also max NBT size, which is a big issue.

Every tile entity, basically everything else in the game uses ID/meta. It's not something we can easily or safely move away from.
