### ISSUE TITLE
Thermal Foundation Plugins for Tinkers' Construct error

### ISSUE THREAD

**Issue by royalcw** [CoFH/Feedback#636]
Thermal Foundation common.cfg file has a line for B:"Tinkers' Construct"=false/true.  If set to true then nothing from Thermal Expansion actually integrates with Tinkers' Construct but it DOES prevent Immersive Engineering from interfacing with Tinkers' Construct.  When I set to false, all issues go away.  

Minecraft: 1.12.2
Forge: 14.23.0.2522 (can't use higher or get Extra Utils 2 crashes and this is a known issue for EU2)
Thermal Foundation: 1.12.2-2.3.6.16-universal.jar
Tinkers' Construct: 1.12-2.7.4.24

Error line in the log if Thermal Foundation common.cfg plugin line is set to true:
"Server thread/ERROR [immersiveengineering]: Compat module for tconstruct could not be preInitialized. Report this!"

No Errors and no compat issues between Immersive Engineering and TConstruct if Thermal Foundation Integration is set to false.

The error prevents any Immersive Engineering materials from becoming TConstruct materials.

**Comment by Gulduka** [comment]
"Forge: 14.23.0.2522 (can't use higher or get Extra Utils 2 crashes and this is a known issue for EU2)" 

For this issue you can use the new EU2 Version 1.6.5

i do this last week and can update my Forge Version. Hope it helps @royalcw :)

**Comment by royalcw** [comment]
updated the forge...but you still have to disable the Tinkers' Construct plugin option in the Thermal Foundation to stop the Immersive Engineering/TConstruct issue

**Comment by KingLemming** [comment]
Okay, so TF support doesn't involve TE at all. So that part doesn't make sense.

Also, take this up with IE because there is literally nothing in the code where TF would be at fault for causing this.

Feel free too look over it yourself:
https://github.com/CoFH/ThermalFoundation/blob/1.12/src/main/java/cofh/thermalfoundation/plugins/PluginTConstruct.java
