### ISSUE TITLE
Request: Add/Remove Magmatic Dynamo Fluids via config option

### ISSUE THREAD

**Issue by royalcw** [CoFH/Feedback#638]
I wish to prevent Lava from being a Magmatic Dynamo fuel which would leave the two IC2 fuel types and blazing pyrotheum as the three fuel types.  This is for a progression option since lava is too easy to manufacture in modded progression mod packs.

A simple config option would be nice.  

I see the location in the util/managers/dynamo/magmaticmanger.class file. I tried to edit the class file as an option since I couldn't find a config setting but alas I don't know how to edit class files or make a class file from the github files.

**Comment by KingLemming** [comment]
I'm pondering some generalized configs, will see. :)

**Comment by KingLemming** [comment]
BTW, you can already do this with ModTweaker.

**Comment by KingLemming** [comment]
Merging this into #1008.
