### ISSUE TITLE
Ticking Pulverizer

### ISSUE THREAD

**Issue by Aircl0wn** [CoFH/Feedback#639]
Time: 7/5/15 9:17 PM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at cofh.thermalexpansion.block.machine.TilePulverizer.processFinish(TilePulverizer.java:117)
	at cofh.thermalexpansion.block.machine.TileMachineBase.func_145845_h(TileMachineBase.java:105)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at cofh.thermalexpansion.block.machine.TilePulverizer.processFinish(TilePulverizer.java:117)
	at cofh.thermalexpansion.block.machine.TileMachineBase.func_145845_h(TileMachineBase.java:105)

-- Block entity being ticked --
Details:
	Name: thermalexpansion.Pulverizer // cofh.thermalexpansion.block.machine.TilePulverizer
	Block type: ID #1418 (tile.thermalexpansion.machine // cofh.thermalexpansion.block.machine.BlockMachine)
	Block data value: 1 / 0x1 / 0b0001
	Block location: World: (-845,63,986), Chunk: (at 3,3,10 in -53,61; contains blocks -848,0,976 to -833,255,991), Region: (-2,1; contains chunks -64,32 to -33,63, blocks -1024,0,512 to -513,255,1023)
	Actual block type: ID #1418 (tile.thermalexpansion.machine // cofh.thermalexpansion.block.machine.BlockMachine)
	Actual block data value: 1 / 0x1 / 0b0001
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

-- Affected level --
Details:
	Level name: Morvy Cottage-Normal
	All players: 1 total; [EntityPlayerMP['<PROFILE NAME>'/62, l='Morvy Cottage-Normal', x=-844.32, y=61.00, z=988.96]]
	Chunk stats: ServerChunkCache: 466 Drop: 0
	Level seed: 2239003194312966991
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-877,58,1002), Chunk: (at 3,3,10 in -55,62; contains blocks -880,0,992 to -865,255,1007), Region: (-2,1; contains chunks -64,32 to -33,63, blocks -1024,0,512 to -513,255,1023)
	Level time: 6493268 game time, 7286652 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 7068 (now: false), thunder time: 10476 (now: true)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

running AS2 with latest versions of all mods
happend after updated the cofh mods released today, been using the alpha's before that.
world loads normal. crashes when opening any GUI (inventory, pulvirizer gui, crafting table)
full crashlog : http://pastebin.com/bxpgUrxE
same type of crash, different pulverizer: http://pastebin.com/m4AtxFRT

**Comment by KingLemming** [comment]
We've said it a lot, but you shouldn't be using Alphas.

What happened here is that IDs got remapped and a formerly valid item became invalid. This is sort of on FML, as that shouldn't happen with such reckless abandon.

This will be handled with a safeguard in the future, but for now all you can do is downgrade to the previous version, remove all items from all machines, and THEN upgrade.

**Comment by SkinHeadBaby** [comment]
to which version to downgrade exactly because i downgraded  1 version back and it still happens for me
and which items to remove? the ores that are beeing processed or the augments or maybe both

**Comment by Aircl0wn** [comment]
no clue tbh. i've reverted back to the previous beta/stable releases, went creative mode and deleted them all and making new ones with new augment and it's still crashing my world

**Comment by SkinHeadBaby** [comment]
well the question was for KingLemming but i guess i will avoid using my quarry until an update since thats what causes my pulverizers to kick in and cause a crash in a few minutes

**Comment by KingLemming** [comment]
If you guys are still seeing this, then I'll need to know which ore specifically is causing it. This isn't a TE issue specifically; something else is triggering an invalid state.

**Comment by SkinHeadBaby** [comment]
well i am not pulverizing a lot so i will have an answer in a few minutes

**Comment by cabralRodrigo** [comment]
Here we go:

Tin ore from IC2: [Crash log](http://paste.ee/p/2SKUH)
Coal ore: [Crash log](http://paste.ee/p/u4Uev)
Sulfur ore from Railcraft: [Crash log](http://paste.ee/p/9k2lQ)
Cooper ore from IC2: [Crash log](http://paste.ee/p/isXUt)
Lead ore from IC2: [Crash log](http://paste.ee/p/bmKGY)

All the 'what version' stuff: http://postimg.org/image/x3ngaen7h/

**Comment by Aircl0wn** [comment]
http://pastebin.com/ifSBq5ri

pulverizer in the above crashlog is processing gravel to sand (and ex nihilo dust as by-product)
it's the middle on a line from cobble (ig extruder) > pulverizer (gravel)  > pulverizer (sand) > pulverizer (dust). i replaced all pulverizers and everything ran fine, crash happend when i tried opening another new pulverizer gui (which wasn't processing anything at the time)

after reloading the client it then instantly crashed when i opened my normal inventory 

one of the other crashes reports i posted earlier is the bottom one in this same line (sand > ex nihilo dust). i have another pulverizer processing the various ore sands dusts and gravels from ex nihilo

above crashlogs shows fastcraft but the same thing happens without it installed (see prev crashlog)

**Comment by SkinHeadBaby** [comment]
i guess it wasnt a few minutes but i can say after some that i get this crash when process any ore doenst matter if modded or vanilla and the issue is some problem with opening any gui exept the player inventory even opening ender pouch energy cell vibrant capacitor big reactor/turbine
i left my ore procecing go for almost an our without a crash while i was afk
i dont understand coding or anything about the crash log that i get
these are the 2 crashes i get which are almost the same
http://paste.ee/p/pG5RU
http://paste.ee/p/iSsTX

**Comment by SkinHeadBaby** [comment]
the latest update fixed this for me thank you KingLemming or who ever fixed it (hug)
