### ISSUE TITLE
[1.10.2] Crash involving Bibliocraft Shelves.

### ISSUE THREAD

**Issue by b0bst3r** [CoFH/Feedback#64]
Crashlog - https://gist.github.com/b0bst3r/1e76530fd9189ae9ba0ef2a2f288afe0

CoFHCore-1.10.2-4.0.2.150-universal
ThermalExpansion-1.10.2-5.0.2.83-universal
ThermalFoundation-1.10.2-2.0.2.76-universal
Forge 2221
Bibliocraft 2.2.1

To repeat:
 - Place down Energetic infuser.
 - Place down 2 Bibliocraft shelves (the ones which have 4 slots and the type you hang on a wall) one each side of the infuser.
 - Upgrade the infuser to hardened
 - Set left side as input and right side as output on the infuser
 - Enable auto input on Infuser GUI and crash occurs

World will not load from that point on unless the infuser is world edited out (or the input side shelf).

Pics
Setup like this - http://i.imgur.com/1JHSu1e.png
As soon as this is enabled - http://i.imgur.com/vmyAvfr.png crash occurs

**Comment by KingLemming** [comment]
Cool. But let's maybe not use hyperbole in the title.

**Comment by KingLemming** [comment]
So offhand, I'm not entirely sure this is on our end, simply because Auto-Input works just fine with basically every other inventory.

I'll look into it, but you probably want to let Bibliocraft know too.

**Comment by b0bst3r** [comment]
Gimme a min I noticed a major glaring mistake on my end, re-testing

**Comment by KingLemming** [comment]
Actually after just having looked at the code, this is only going to happen if Bibliocraft is in the wrong.

We're getting the capability after confirming that one exists. This crash will only occur if the Shelf hands back a null instead of a capability, so it's lying.

**Comment by b0bst3r** [comment]
I don't know if you want to close this or not.

Also don't know if you did this or it was just a side effect, I enable Forge removal of erroring tile/entities and it fixed the issue by removing the hardened upgrade from the infuser and not by deleteing the machine or the shelves.

Nice one :)

**Comment by KingLemming** [comment]
I'm going to leave it open for now. I may add in a sanity check to prevent such things in the future, but this is the kind of thing that starts to lag servers. No check should ever be required, since I am in theory already executing the correct check for the capability.

**Comment by KingLemming** [comment]
I'm stupid-proofing this on my end but as I've mentioned it shouldn't be required. >:(

**Comment by Kumomo** [comment]
> I'm stupid-proofing this on my end but as I've mentioned it shouldn't be required. >:(

Might I ask what version this was added to if it has been added yet?
We've had the same issue with the server crashing from Bibliocraft Framed Chests as well as EnderIO Capacitors when placed against TE machines with Auto-Input on.
