### ISSUE TITLE
[Redstone Arsenal][Documentation] Referenced files License - Art.txt and License - Code.txt not in repository

### ISSUE THREAD

**Issue by rallias** [CoFH/Feedback#64]
The readme.md file for the Redstone Arsenal repository references License - Art.txt and License - Code.txt files at the very bottom, but those items are not in the Redstone Arsenal repository.

**Comment by KingLemming** [comment]
Re-added them.

**Comment by rallias** [comment]
Yo! 

This is what I've just  read and  it's something really new and interesting, you  can read more  at <http://thing.nicktuckermusic.com/e4cgobs>

All the best, the
