### ISSUE TITLE
[1.12.2] Unable to make colored rockwool in a multiplayer server

### ISSUE THREAD

**Issue by Xerasin** [CoFH/Feedback#640]
Trying to craft any sort of colored rockwool in a multiplayer server fails to show the recipe and fails to craft it.
I tried it in a world with the following mods 

![image](https://user-images.githubusercontent.com/1499878/32978882-9cef6a72-cbff-11e7-83b2-ed3ec0e4e02f.png)

![image](https://user-images.githubusercontent.com/1499878/32978888-bc7b112a-cbff-11e7-8e2e-5fcfe883741e.png)

![image](https://user-images.githubusercontent.com/1499878/32978890-c69a167e-cbff-11e7-8d75-051e052e8d13.png)

I was running forge 2544 on the server and 2545 on the client.

(Singleplayer shows and crafts it without any issues)

Seems to have randomly stopped doing it, even after testing it twice?

**Comment by KingLemming** [comment]
Forge issue. They've managed to screw up crafting.
