### ISSUE TITLE
BlockModelRenderer error when placing pulverizer.  Minecraft 1.12.2

### ISSUE THREAD

**Issue by Davinjapan** [CoFH/Feedback#641]
When I try and place the pulverizer it shuts the game down and corrupts the save, I can reclaim the save by removing Thermal Expansion from my mods folder and restarting my world and having blocks removed. Would love to use Thermal Expansion in my world. Will attach a copy of the crash report.

[crash-2017-11-19_12.22.44-client.txt](https://github.com/CoFH/Feedback/files/1485260/crash-2017-11-19_12.22.44-client.txt)

**Comment by covers1624** [comment]
Ok, Uninstall optifine, is unsupported.
