### ISSUE TITLE
Flat Bedrock Retrogen

### ISSUE THREAD

**Issue by MrSapient** [CoFH/Feedback#643]
I turned retro gen on and made flat bedrock to 1 and nothing happens .. bedrock is still up to level 3-5
Forge 10.13.4.1481
CoFHCore-[1.7.10]3.0.3B2-294.jar

**Comment by KingLemming** [comment]
Right, because it's already flattened the bedrock there...

**Comment by MrSapient** [comment]
how when its up to level 3-5 and i have it set to 1 ?

**Comment by KingLemming** [comment]
Because you're doing it wrong. I literally just tested - I set the configs after generating a world, it worked properly.

**Comment by KingLemming** [comment]
# This will flatten the bedrock layer.
    B:FlatBedrock=true

and

  # If FlatBedrock is enabled, this will enforce it in previously generated chunks.
    B:RetroactiveFlatBedrock=true

are the relevant config options. I am 100% sure it is working as intended.

**Comment by MrSapient** [comment]
http://pastebin.com/8anTTM8p
http://i.imgur.com/8VHofQ0.png
i went to creative mode and block some...

**Comment by MrSapient** [comment]
well i updated to the last release that broke or changed some of how it worked and then updated to this latest version .. iv always had flat on and its worked most place ..

**Comment by KingLemming** [comment]
Do you have other mods affecting bedrock somehow?
