### ISSUE TITLE
Cryo-stabalized fluxducts not connecting on world load

### ISSUE THREAD

**Issue by ouroborus** [CoFH/Feedback#643]
Due to how this bug presented itself, I thought it was a problem with Mekanism. After discussing it with @thiakal [here](https://github.com/aidancbrady/Mekanism/issues/4805) it seems more like it might be a problem with cryo-stabilized fluxducts.

During world load, but not chunk load, Mekanism cables don't always connect to cryo-stabilized fluxducts. This is most repeatable when the fluxduct is receiving power, pushing it to the cables, and the cables are connected on two non-adjacent faces of the fluxduct. This does not seem to happen with other types of fluxduct.

Thermal Dynamics 1.12-2.3.6.13

The various pipes were connected without issue. The screenshots show the results after reloading the world.

![2017-11-19_04 00 13](https://user-images.githubusercontent.com/392047/32990438-34004b8c-ccde-11e7-8f12-d5d387af3daa.png)
![2017-11-19_04 00 18](https://user-images.githubusercontent.com/392047/32990439-3415b512-ccde-11e7-880f-48e6a869b697.png)

**Comment by KingLemming** [comment]
Actually, the cryoducts ARE connecting. The mek cables are failing to.

**Comment by thiakil** [comment]
@KingLemming they ARE capable of showing as connected. It only happens in a specific combination of your ducts. I believe it was narrowed down to a cable being on either side, as you can see in the screenshot; when on just one side in the above setup it works fine.

The cables are simply not able to find a valid "acceptor" at the point when the update is sent. It checks the various energy caps/interfaces & their `canReceive`/`canConnectEnergy` functions. 

Placing any other block to trigger a neighbour update on the Mek cable causes normal connection rendering.

**Comment by KingLemming** [comment]
The cryoducts aren't really fundamentally different from any other duct. I dunno what to tell you there, but I'm extremely sure that it's not really in our code.

**Comment by thiakil** [comment]
I've just set a breakpoint on the neighbour changed functions of our block. You are most definitely *not* calling them in the case of a cable on either side of the duct. The duct that only had a cable on one side *did* call it correctly. In my test world the Mek cables are on East/West, in case that matters.

Power is likely flowing because the Mekanism cables do expose the capabilities and your cable is able to push power through. Your assumption that it's a client sync issue is incorrect.

I personally have not tested *all* of your cables, but I do not need to to know that this one isn't calling the functions it should be.

**Comment by KingLemming** [comment]
Your cables shouldn't be exposing the capabilities on disconnected sides, that's a bit strange.

I'll look into this, but just on the surface of it, you do realize that you sound like a crazy person. There's no logical reason that we'd call an update with one, but not multiple.

**Comment by thiakil** [comment]
> Your cables shouldn't be exposing the capabilities on disconnected sides, that's a bit strange.

I suggest you rethink that. If both cables did that they would forever be locked in a stalemate *and would never connect*

> but just on the surface of it, you do realize that you sound like a crazy person

* Edge cases are not crazy or silly
* Please think *before* you hit that post button. Even with the edit you sound like an arrogant prick who thinks their code can never have bugs.
* I presented you the evidence that your code has a potential logic flaw, nothing more.

> There's no logical reason that we'd call an update with one, but not multiple, adjacent blocks.

Hence this being a bug report.

> Also, Mekanism is definitely the only case we've seen of anything like this.

How many other cases have you seen of people combining other cables with yours in this arrangement? Or even just other neighbour update sensitive blocks? Alone that is a flawed data point.
