### ISSUE TITLE
Thermal Expansion crashing on game startup

### ISSUE THREAD

**Issue by anthonii** [CoFH/Feedback#644]
Every time i try to run this mod, it crashes during the forge loading of the mods.

The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Thermal Expansion (thermalexpansion

**Comment by covers1624** [comment]
Please provide your crash report, that one line literally tells us nothing.

**Comment by anthonii** [comment]
Couldn't get hash for 1.12.2 jar from https://s3.amazonaws.com/Minecraft.Download/versions/1.12.2/1.12.2.jar.sha1: HTTP 403: Forbidden
--
23:04:43 | launcher | Have local file C:/Users\novus\AppData\Roaming\.minecraft\versions\1.12.2/1.12.2.jar but don't know what size or hash it should be. Have to assume it's good.
23:04:43 | launcher | Couldn't get hash for net/minecraftforge/forge/1.12.2-14.23.0.2549/forge-1.12.2-14.23.0.2549.jar from http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12.2-14.23.0.2549/forge-1.12.2-14.23.0.2549.jar.sha1: HTTP 404: Not Found
23:04:43 | launcher | Have local file C:/Users\novus\AppData\Roaming\.minecraft\libraries\net/minecraftforge/forge/1.12.2-14.23.0.2549/forge-1.12.2-14.23.0.2549.jar but don't know what size or hash it should be. Have to assume it's good.
23:04:43 | launcher | Couldn't get hash for jline/jline/2.13/jline-2.13.jar from http://files.minecraftforge.net/maven/jline/jline/2.13/jline-2.13.jar.sha1: HTTP 404: Not Found
23:04:43 | launcher | Have local file C:/Users\novus\AppData\Roaming\.minecraft\libraries\jline/jline/2.13/jline-2.13.jar but don't know what size or hash it should be. Have to assume it's good.
23:04:43 | launcher | Couldn't get hash for com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar from http://files.minecraftforge.net/maven/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar.sha1: HTTP 404: Not Found
23:04:43 | launcher | Have local file C:/Users\novus\AppData\Roaming\.minecraft\libraries\com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar but don't know what size or hash it should be. Have to assume it's good.
23:04:43 | launcher | Couldn't get hash for org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar from http://files.minecraftforge.net/maven/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar.sha1: HTTP 404: Not Found
23:04:43 | launcher | Have local file C:/Users\novus\AppData\Roaming\.minecraft\libraries\org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar but don't know what size or hash it should be. Have to assume it's good.
23:04:43 | launcher | Couldn't get hash for com/typesafe/config/1.2.1/config-1.2.1.jar from http://files.minecraftforge.net/maven/com/typesafe/config/1.2.1/config-1.2.1.jar.sha1: HTTP 404: Not Found
23:04:43 | launcher | Have local file C:/Users\novus\AppData\Roaming\.minecraft\libraries\com/typesafe/config/1.2.1/config-1.2.1.jar but don't know what size or hash it should be. Have to assume it's good.
23:04:43 | launcher | Couldn't get hash for org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar from http://files.minecraftforge.net/maven/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar.sha1: HTTP 404: Not Found
23:04:43 | launcher | Have local file C:/Users\novus\AppData\Roaming\.minecraft\libraries\org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar but don't know what size or hash it should be. Have to assume it's good.
23:04:43 | launcher | Couldn't get hash for org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar from http://files.minecraftforge.net/maven/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar.sha1: HTTP 404: Not Found
23:04:43 | launcher | Have local file C:/Users\novus\AppData\Roaming\.minecraft\libraries\org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar but don't know what size or hash it should be. Have to assume it's good.
23:04:43 | launcher | Couldn't get hash for org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar from http://files.minecraftforge.net/maven/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar.sha1: HTTP 404: Not Found
23:04:43 | launcher | Have local file C:/Users\novus\AppData\Roaming\.minecraft\libraries\org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar but don't know what size or hash it should be. Have to assume it's good.
23:04:43 | launcher | Couldn't get hash for org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar from http://files.minecraftforge.net/maven/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar.sha1: HTTP 404: Not Found
23:04:43 | launcher | Have local file C:/Users\novus\AppData\Roaming\.minecraft\libraries\org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar but don't know what size or hash it should be. Have to assume it's good.
23:04:43 | launcher | Couldn't get hash for org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar from http://files.minecraftforge.net/maven/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar.sha1: HTTP 404: Not Found
23:04:43 | launcher | Have local file C:/Users\novus\AppData\Roaming\.minecraft\libraries\org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar but don't know what size or hash it should be. Have to assume it's good.
23:04:43 | launcher | Couldn't get hash for org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar from http://files.minecraftforge.net/maven/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar.sha1: HTTP 404: Not Found
23:04:43 | launcher | Have local file C:/Users\novus\AppData\Roaming\.minecraft\libraries\org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar but don't know what size or hash it should be. Have to assume it's good.
23:04:43 | launcher | Couldn't get hash for org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar from http://files.minecraftforge.net/maven/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar.sha1: HTTP 404: Not Found
23:04:43 | launcher | Have local file C:/Users\novus\AppData\Roaming\.minecraft\libraries\org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar but don't know what size or hash it should be. Have to assume it's good.
23:04:43 | launcher | Couldn't get hash for org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar from http://files.minecraftforge.net/maven/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar.sha1: HTTP 404: Not Found
23:04:43 | launcher | Have local file C:/Users\novus\AppData\Roaming\.minecraft\libraries\org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar but don't know what size or hash it should be. Have to assume it's good.

**Comment by covers1624** [comment]
That is your launchers log, not the minecraft crash report..

**Comment by KingLemming** [comment]
This absolutely isn't in our code. 100% on your end and a tech support issue. I'll leave it up for a few, so you can provide a proper log. Barring that, you'll have to join Twitch chat.

**Comment by anthonii** [comment]
having some sort of issue that isnt letting me see the log, was trying to use that as a work around, where is the twitch chat?

**Comment by KingLemming** [comment]
https://www.curse.com/invite/SipeCoinsSvalna

**Comment by anthonii** [comment]
also, finally got the log to work

11/19/17 11:19 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Thermal Expansion (thermalexpansion)
Caused by: java.lang.NoClassDefFoundError: cofh/thermalexpansion/item/ItemSatchel
	at cofh.thermalexpansion.ThermalExpansion.<clinit>(ThermalExpansion.java:57)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:344)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:522)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:253)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:231)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:568)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:231)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: cofh.thermalexpansion.item.ItemSatchel
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 39 more
Caused by: java.lang.NoClassDefFoundError: cofh/api/item/INBTCopyIngredient
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 41 more
Caused by: java.lang.ClassNotFoundException: cofh.api.item.INBTCopyIngredient
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 45 more
Caused by: java.lang.SecurityException: class "cofh.api.item.INBTCopyIngredient"'s signer information does not match signer information of other classes in the same package
	at java.lang.ClassLoader.checkCerts(ClassLoader.java:895)
	at java.lang.ClassLoader.preDefineClass(ClassLoader.java:665)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:758)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 47 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 65014336 bytes (62 MB) / 486539264 bytes (464 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.0.2549 74 mods loaded, 74 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                   | Version        | Source                                        | Signature                                |
	|:----- |:-------------------- |:-------------- |:--------------------------------------------- |:---------------------------------------- |
	| UC    | minecraft            | 1.12.2         | minecraft.jar                                 | None                                     |
	| UC    | mcp                  | 9.42           | minecraft.jar                                 | None                                     |
	| UC    | FML                  | 8.0.99.99      | forge-1.12.2-14.23.0.2549.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UC    | forge                | 14.23.0.2549   | forge-1.12.2-14.23.0.2549.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UC    | mercurius_updater    | 1.0            | MercuriusUpdater-1.12.2.jar                   | None                                     |
	| UC    | jei                  | 4.8.0.114      | jei_1.12.2-4.8.0.114.jar                      | None                                     |
	| UC    | abyssalcraft         | 1.9.4.2        | AbyssalCraft-1.12.2-1.9.4.2.jar               | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
	| UC    | actuallyadditions    | 1.12.2-r124    | ActuallyAdditions-1.12.2-r124.jar             | None                                     |
	| UC    | forgeendertech       | 1.12.1-4.2.0.1 | ForgeEndertech-1.12.1-4.2.0.1-build.0035.jar  | None                                     |
	| UC    | adhooks              | 1.12.1-3.1.1.0 | AdHooks-1.12.1-3.1.1.0-build.0034.jar         | None                                     |
	| UC    | appliedenergistics2  | rv5-stable-2   | appliedenergistics2-rv5-stable-2.jar          | None                                     |
	| UC    | crafttweaker         | 4.0.10         | CraftTweaker2-1.12-4.0.10.jar                 | None                                     |
	| UC    | astralsorcery        | 1.8.2          | astralsorcery-1.12.2-1.8.2.jar                | a0f0b759d895c15ceb3e3bcb5f3c2db7c582edf0 |
	| UC    | psi                  | r1.1-59        | Psi-r1.1-59.jar                               | None                                     |
	| UC    | autoreglib           | 1.3-15         | AutoRegLib-1.3-15.jar                         | None                                     |
	| UC    | biomesoplenty        | 7.0.1.2302     | BiomesOPlenty-1.12.2-7.0.1.2302-universal.jar | None                                     |
	| UC    | bookshelf            | 2.2.498        | Bookshelf-1.12.2-2.2.498.jar                  | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UC    | baubles              | 1.5.1          | Baubles-1.12-1.5.1.jar                        | None                                     |
	| UC    | botania              | r1.10-350      | Botania r1.10-350.jar                         | None                                     |
	| UC    | codechickenlib       | 3.1.3.313      | CodeChickenLib-1.12-3.1.3.313-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UC    | redstoneflux         | 2.0.1          | RedstoneFlux-1.12-2.0.1.2-universal.jar       | d4f1503fbacd9b9fb767720420c5395104239ec9 |
	| UC    | brandonscore         | 2.3.4          | BrandonsCore-1.12-2.3.4.134-universal.jar     | None                                     |
	| UC    | cfm                  | 4.1.5          | cfm-4.1.5-mc1.12.jar                          | None                                     |
	| UC    | chameleon            | 1.12-4.1.3     | Chameleon-1.12-4.1.3.jar                      | None                                     |
	| UC    | chiselsandbits       | 14.9           | chiselsandbits-14.9.jar                       | None                                     |
	| UC    | cofhcore             | 4.3.6          | CoFHCore-1.12-4.3.6.14-universal.jar          | None                                     |
	| UC    | cofhworld            | 1.0.1          | CoFHWorld-1.12-1.0.1.8-universal.jar          | None                                     |
	| UC    | extendedrenderer     | v1.0           | coroutil-1.12.1-1.1.22-a.jar                  | None                                     |
	| UC    | coroutil             | 1.12.1-1.1.20  | coroutil-1.12.1-1.1.22-a.jar                  | None                                     |
	| UC    | configmod            | v1.0           | coroutil-1.12.1-1.1.22-a.jar                  | None                                     |
	| UC    | ctgui                | 1.0.0          | CraftTweaker2-1.12-4.0.10.jar                 | None                                     |
	| UC    | crafttweakerjei      | 2.0.0          | CraftTweaker2-1.12-4.0.10.jar                 | None                                     |
	| UC    | cucumber             | 1.0.3          | cucumber-1.12-1.0.3.jar                       | None                                     |
	| UC    | darkutils            | 1.7.181        | DarkUtils-1.12.2-1.7.181.jar                  | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UC    | ic2                  | 2.8.16-ex112   | industrialcraft-2-2.8.16-ex112.jar            | de041f9f6187debbc77034a344134053277aa3b0 |
	| UC    | forestry             | 5.6.0.201      | forestry_1.12.2-5.6.0.201.jar                 | None                                     |
	| UC    | eleccore             | 1.8.433        | ElecCore-1.12.2-1.8.433.jar                   | None                                     |
	| UC    | deepresonance        | 1.4.9          | deepresonance-1.12-1.4.9.jar                  | None                                     |
	| UC    | mantle               | 1.12-1.3.1.21  | Mantle-1.12-1.3.1.21.jar                      | None                                     |
	| UC    | tconstruct           | 1.12-2.7.4.34  | TConstruct-1.12-2.7.4.34.jar                  | None                                     |
	| UC    | extrautils2          | 1.0            | extrautils2-1.12-1.6.7.jar                    | None                                     |
	| UC    | zerocore             | 1.12-0.1.1.0   | zerocore-1.12-0.1.1.0.jar                     | None                                     |
	| UC    | bigreactors          | 1.12-0.4.5.44  | ExtremeReactors-1.12-0.4.5.44.jar             | None                                     |
	| UC    | fastleafdecay        | v14            | FastLeafDecay-v14.jar                         | None                                     |
	| UC    | sonarcore            | 5.0.2          | sonarcore-1.12.2-5.0.2.jar                    | None                                     |
	| UC    | fluxnetworks         | 3.0.1          | fluxnetworks-1.12.2-3.0.1.jar                 | None                                     |
	| UC    | ftbl                 | 4.2.4          | FTBLib-4.2.4.jar                              | None                                     |
	| UC    | ftbu                 | 4.2.3          | FTBUtilities-4.2.3.jar                        | None                                     |
	| UC    | gravestone           | 1.10.0         | gravestone-1.10.0.jar                         | None                                     |
	| UC    | immersiveengineering | 0.12-74        | ImmersiveEngineering-0.12-74.jar              | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| UC    | jeibees              | 0.9.0.5        | jeibees-0.9.0.5-mc1.12.2.jar                  | None                                     |
	| UC    | journeymap           | 1.12.2-5.5.2   | journeymap-1.12.2-5.5.2.jar                   | None                                     |
	| UC    | jeresources          | 0.8.5.27       | JustEnoughResources-1.12.2-0.8.5.27.jar       | None                                     |
	| UC    | llibrary             | 1.7.8          | llibrary-1.7.8-1.12.2.jar                     | None                                     |
	| UC    | llor                 | 1.1.4-mc1.12   | LLOverlayReloaded-1.1.4-mc1.12.jar            | None                                     |
	| UC    | magma_monsters       | 0.3.0          | MagmaMonsters-0.3.0.jar                       | None                                     |
	| UC    | morpheus             | 1.12-3.3.2     | Morpheus-1.12-3.3.2.jar                       | None                                     |
	| UC    | mysticalagriculture  | 1.6.6          | mysticalagriculture-1.12-1.6.6.jar            | None                                     |
	| UC    | notenoughwands       | 1.5.9          | notenoughwands-1.12-1.5.9.jar                 | None                                     |
	| UC    | harvestcraft         | 1.12.2a        | Pam's HarvestCraft 1.12.2a.jar                | None                                     |
	| UC    | rangedpumps          | 0.5            | rangedpumps-0.5.jar                           | None                                     |
	| UC    | thermalfoundation    | 2.3.6          | ThermalFoundation-1.12-2.3.6.16-universal.jar | None                                     |
	| UE    | thermalexpansion     | 5.3.6          | ThermalExpansion-1.12-5.3.6.20-universal.jar  | None                                     |
	| UC    | redstonearsenal      | 2.3.6          | RedstoneArsenal-1.12-2.3.6.16-universal.jar   | None                                     |
	| UC    | storagedrawers       | 1.12-5.2.5     | StorageDrawers-1.12.1-5.3.3.jar               | None                                     |
	| UC    | refinedstorage       | 1.5.23         | refinedstorage-1.5.23.jar                     | 57893d5b90a7336e8c63fe1c1e1ce472c3d59578 |
	| UC    | rftools              | 7.14           | rftools-1.12-7.14.jar                         | None                                     |
	| UC    | rftoolscontrol       | 1.6.9          | rftoolsctrl-1.12-1.6.9.jar                    | None                                     |
	| UC    | rftoolsdim           | 5.05           | rftoolsdim-1.12-5.05.jar                      | None                                     |
	| UC    | ropebridge           | 2.0.5          | ropebridge-1.12-2.0.7.jar                     | None                                     |
	| UC    | beneath              | 1.3.0          | The Beneath-1.12.2-1.3.0.jar                  | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
	| UC    | twilightforest       | 3.3.202        | twilightforest-1.12.2-3.3.202-universal.jar   | None                                     |
	| UC    | xnet                 | 1.4.1          | xnet-1.12-1.4.1.jar                           | None                                     |
	| UC    | zombieawareness      | 1.12.1-1.11.10 | zombieawareness-1.12.1-1.11.10.jar            | None                                     |

	Loaded coremods (and transformers): 
ThaumcraftLoader (Thaumcraft-1.8.9-5.2.4.jar)
  
IELoadingPlugin (ImmersiveEngineering-0.12-74-core.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
AstralCore (astralsorcery-1.12.2-1.8.2.jar)
  
llibrary (llibrary-1.7.8-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
DummyPlugin (ForgeEndertech-1.12.1-4.2.0.1-build.0035.jar)
  
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 385.69' Renderer: 'GeForce GTX 965M/PCIe/SSE2'
	AE2 Version: stable rv5-stable-2 for Forge 14.23.0.2491
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)

**Comment by covers1624** [comment]
Caused by: java.lang.SecurityException: class "cofh.api.item.INBTCopyIngredient"'s signer information does not match signer information of other classes in the same package Someone is signing a jar with cofh classes inside, Remove your mods 1 by 1 until you find the cause.

**Comment by anthonii** [comment]
thank you!
