### ISSUE TITLE
Classic Crafting isn't available for everything.

### ISSUE THREAD

**Issue by Zer0Lyfe** [CoFH/Feedback#645]
![2](https://user-images.githubusercontent.com/28994351/33163719-b963cc9c-d06a-11e7-9ed7-eb4a3e3b42b6.PNG)
![1](https://user-images.githubusercontent.com/28994351/33163720-b99aef7e-d06a-11e7-9a15-b67ce31b4e21.PNG)
![image](https://user-images.githubusercontent.com/28994351/33164415-af7c3c5c-d06d-11e7-9396-8c7afd67074a.png)
The image above is to show that there were no crafting recipes for the later tiers

As you can see that they do say "If Classic Crafting is enabled, only the Creative Conversion Kit may be used in this fashion." for both of them but they do not have an option to have the classic crafting enabled.

**Comment by KingLemming** [comment]
Yeah, it's a copy/paste. And those images don't really show anything since those would be the USES and not the RECIPES.

I've added Classic Crafting for the next release though.

**Comment by Zer0Lyfe** [comment]
thank you KL. sorry for the images :P

**Comment by Zer0Lyfe** [comment]
It was to say there was no crafting table tab 👍

**Comment by KingLemming** [comment]
That makes way more sense, haha.
