### ISSUE TITLE
Suggestion about liquids(Thermal Expansion)

### ISSUE THREAD

**Issue by Da-Technomancer** [CoFH/Feedback#645]
The liquids in thermal expansion have a variety of effects. If you could blend liquids to combine specific properties, you could have all sorts of new uses. The suggestion is for a new machine where you put in 2 different liquids, then from drops down menus pick the desired properties of each. After some time and power, the 2 liquids turn into a new custom liquid with the selected properties. For example, I could  combine lava and liquid ender, I could select the desired properties, and make the resulting liquid hot like lava, teleport you like resonant ender, but not cause fires like liquid ender, glow like lava, and have the shorter flow distance of lava. The sort of traits there would be would be tempature, flow distance, special properties (like go upwards, emit redstone, glow, teleport, etc.), how fast it flows, and so on. I would also like to mention that when combing a liquid with liquid glowstone, if you choose that it flows upward, you can also choose separately whether the source blocks itself flows upward. This machine, for balance reasons, should have to be made with a resonant machine frame and should be difficult to craft in other ways.

**Comment by KingLemming** [comment]
Not really possible, sorry.

That would require a tile entity based fluid with all sorts of property weirdness and it's not something I want to support in any way, it would be murder on servers.
