### ISSUE TITLE
Fluiduct retreivers with empty whitelists will void liquids rather than simply not accepting

### ISSUE THREAD

**Issue by utoc** [CoFH/Feedback#646]
This may be intentional behavior.  Using both temperate and hardened fluiducts with a single retreiever pulling from a bedrockium drum of lava, the lava drum was effectively being voided while the container being filled received nothing (as intended since the whitelist was empty).

Here are a couple screenshots in case my description was as helpful as a congressman teaching an ethics class.

[Here is a list of mods](https://www.reddit.com/r/BBQSauce/wiki/modlist) and I am running FML 1448

Thermal Dynamics - 1.1.0B2-149
Thermal Expansion - 4.0.2B2-210
ThermalFoundation - 1.2.0B1-95.jar
CoFHCore - 3.0.3B2-294

The whitelist, empty:  https://i.imgur.com/2uP1Xwb.png

Using temperate: https://i.imgur.com/CdBOX6q.png

Using hardened:  https://i.imgur.com/rofEqsq.png

**Comment by RoloEdits** [comment]
can confirm this is also happening to me
