### ISSUE TITLE
cofhtweaks lighting update calls getLightOpacity with incorrect coordinates

### ISSUE THREAD

**Issue by Baughn** [CoFH/Feedback#646]
Specifically, in https://github.com/CoFH/CoFHTweaks/blob/master/src/cofh/tweak/asmhooks/HooksCore.java#L282

When this path is used, getLightOpacity will be called with what appears to be chunk-local coordinates. Since most blocks don't use the coordinates, this doesn't generally cause trouble, but it conflicts with Electrical Age where the latter wants to look up the tile entity at the given coordinates.

Example crash: https://madoka.brage.info/crash-reports/crash-2017-11-22_19.31.59-server.txt

I confirmed the coordinate problem by adding print statements to the Eln-side code. In this particular case, the coordinates provided were off by precisely five chunks; the cofhtweaks code is too complex to easily parse, but it certainly looks as if they'd been mod-16'd.

EIO has nothing to do with the crash; the block at those coordinates just happened to be an EIO conduit bundle.

**Comment by KingLemming** [comment]
CoFHTweaks is for 1.7.10. Sorry, but this is just unsupported.

**Comment by Baughn** [comment]
Okay. In that case, would you allow me to redistribute a fixed version of the mod to users on my private server?

**Comment by KingLemming** [comment]
Feel free to submit a PR and I'm willing to push an update.

**Comment by Baughn** [comment]
We ended up deciding to remove cofhtweaks. I could submit a PR anyway, but it won't have seen any testing beyond compilation; your choice.
