### ISSUE TITLE
Multiple Oil Fluid Stack Entries EE3

### ISSUE THREAD

**Issue by RoloEdits** [CoFH/Feedback#647]
Ill first start off asking if you guys added ee3 support and if you did and you added oil then im getting an error http://pastebin.com/cs4SKzby 

and if you didn't add ee3 support than i am sorry for wasting your time

either way thank you for your help

i should note that it is not crashing the game this is part of the fml-client-latest log and the error stops ee3 from calculating values after a certain point so only a few things have emc

**Comment by KingLemming** [comment]
We do add EE3 support, yes. However, this particular issue is something that should be resolved on EE3's end I'm afraid, as this is inevitable with a large enough group of mods.

**Comment by RoloEdits** [comment]
ok thank you very much for your help i have made and error report there already so we will wait and see until it is fixed.

and also thanks for adding ee3 support its very much appreciated

**Comment by KingLemming** [comment]
I'll see about a workaround for now, but I'm not actually sure how it can be done.

**Comment by RoloEdits** [comment]
OK, if nothing can be done then ill be patient util its fixed,I appreciate you trying.

**Comment by RoloEdits** [comment]
i think the problem was between pneumatic craft and thermal expansion after removing pneumatic craft it worked fine or i should say it works how ee3 does right now. i got an error for oil but i think theres an error for fuel as well

**Comment by KingLemming** [comment]
Well you can disable the EE3 plugin in the config file. That may be the best option here if it prevents the game from loading.

**Comment by RoloEdits** [comment]
its not affecting the game itself in any way as far as i can tell its just emc value calculation is getting stuck part way through and only a few things end up with emc, ill just remove pneumatic craft for now until it is solved or i figure out a better work around 

thanks again for you help
