### ISSUE TITLE
Unable to set keypress for empowering tools/weapons

### ISSUE THREAD

**Issue by CrokdStogie** [CoFH/Feedback#647]
When I hold shift and hover over the tools/weapons it shows that I do not have a default key set to empower them and I cannot set a key in the control tab. the tools/weapons have the ability to be empowered, I just have no way to activate them.

**Comment by KingLemming** [comment]
This is a configuration issue on your end and/or is the fault of the modpack. By default, the mods provide such a key AND a mapping can be set in the menu.
