### ISSUE TITLE
(Suggestion) add a way to make terrain smasher not work on fluids, or add an item collector

### ISSUE THREAD

**Issue by jkenyonc** [CoFH/Feedback#648]
I tried to use terrain smashers to collect Mon drops, (because i prefer to avoid the tps disaster that is hoppers)but they keep sucking up the cryptheum I use to kill mobs. Could you add away to prevent this, or add a block to collect items in a server- friendly manner?

**Comment by KingLemming** [comment]
Just thinking about it, you could set your mob trap up differently to avoid this issue. But it's a fair request.

**Comment by jkenyonc** [comment]
I know i could set up my mob farm with hoppers or just use a drop trap (way
more efficient than my crazy cryotheum setup), but i thought this was still
a reasonable request. Do you plan to ever separate the liquid functionality
into a separate block? (whenever you implement that reversible pump/ flood
gate block you've been planning)

**Comment by isochronous** [comment]
No idea what other mods you're using, but you could use a vacuum chest if you have Ender IO. Agreed that this is a reasonable request though, along with the ability to specify what things to pick up (items, fluids, both).

**Comment by Tora-B** [comment]
The latest version of TE (ThermalExpansion-[1.7.10]4.1.1-237)adds an "Acquisition Apparatus", which appears to collect items like a Terrain Smasher, but without the block breaking. Simple, but effective.
