### ISSUE TITLE
Steam Dynamo Bug (Thermal Series)

### ISSUE THREAD

**Issue by FoxBotGames** [CoFH/Feedback#648]
**Info regarding versions and modlist**
This bug involves the thermal series: Thermal Expansion 5.3.6.20. Thermal Dynamics 2.3.6.13, Thermal Foundation 2.3.6.16, and Thermal Cultivation 0.1.1.6. 

All mods in this modpack can be found at https://github.com/Vaygrim/grimco-rd1 under v0.9. This providing a modlist under the configs post.

I am noting this from a basic steam dynamo and have yet to test any higher a tier of the steam dynamo.

**Main Bug**
Steam Dynamo (Basic) will not transfer power when not producing power. (redstone control set to ignore)

When redstone control is set to ignore the Steam Dynamo (Basic) will continue to consume fuel of both solid and liquid fuel when the energy buffer is maxed.
      This issue is resolved when a redstone signal is applied to the Steam Dynamo (Basic), with redstone control enabled, however the dynamo will finish its burn it was on when signal was received. The dynamo will prevent/stop burning fuel until the redstone signal is disabled. (Is this continued burning w/ redstone control a mod setting or a bug?)

**Comment by KingLemming** [comment]
This is 100% intentional. Dynamos only transfer power when generating it.

The continued burn is also intentional.
