### ISSUE TITLE
[Thermal dynamics] 1.12-2.3.6.13 causing huge tps 

### ISSUE THREAD

**Issue by TheMrCaveman** [CoFH/Feedback#649]
Minecraft version 1.12.2
Forge version 14.23.0.2531

Modpack all the mods 3

See report https://timings.aikar.co/?id=5c6d96cee7c6485fbeac43f7efd3e717

This happens as soon as we start using leadstone fluxduct!

**Comment by KingLemming** [comment]
You've got way too much going on there for this to be a useful report. Can you replicate it with *only* our stuff?

Also, given the way that ducts operate, if you have things on the network which are slow, they get blamed. Just how it goes.
