### ISSUE TITLE
Suggestion: Could You Guys Handel EE3 Values For Ore Dict?

### ISSUE THREAD

**Issue by RoloEdits** [CoFH/Feedback#649]
I believe right now you guys currently add values for only cofh stuff but would you consider adding them for the whole ordictionary  like ingotTin,ingotCopper,ect. it would make thing very easier to deal with and i believe, thought im not speaking for anybody, most will go with the values you set anyways 

and maybe add one for enderium? i know there's a reason you don't want one im sure but again it would make things easier to deal with 

and i don't mean easier when i say easier to deal with i mean as in compatibility and integration of other mods

Edit: please disregard the part about enderium.....im an idiot. but its also a good example of you guys handling the ore dictionary.

**Comment by RoloEdits** [comment]
an just because i dont think i was clear enough i also mean stuff like sulfur and niter and obsidian dust

and all of the pulverized dust's

**Comment by KingLemming** [comment]
We're already doing this with all of the things that TF adds, or at least we're trying to. We don't explicitly assign value to the ingots and nuggets because that has to be dynamically determined by EE3, but we do provide reference points on the ores.

**Comment by RoloEdits** [comment]
oh ok but i don't think it handles ingots and other pulverized dust from other mods its just the TE mod items its handling. at least from what i had to do to get some things working i just used your guys's values for the whole or dictionary and values started appearing like for the gears and enderium.
i also had to add the values for dustSulfur and dustSaltpeter  to make the cryo and pyro dusts's have values.

**Comment by KingLemming** [comment]
EE3 should really be handling oreDict equivalencies, I'll mention it to pahimar.

With that in mind, I'll close this out since adding EMC info for our items *should* automatically do that.

**Comment by RoloEdits** [comment]
Ok Thank You For Your Time
