### ISSUE TITLE
Null Pointer Exceptions when mousing over machines

### ISSUE THREAD

**Issue by Cherrii951** [CoFH/Feedback#65]
I'm working on a custom modpack with the MultiMC launcher, and I tend to keep the log window open while I'm playing. I've noticed when I mouse over the new TE machines, the log fills up with NPE errors, though the game doesn't crash. It doesn't happen when mousing over/using the dynamos or the various energy storage containers; only the other machines, such as the Pulverizer, Redstone Furnace, etc. 

I created a new test world and placed down one of each of the basic tier machines, and got a rush of NPE errors from every one. I saved the full game log for that session, which was too long for pastebin. I did put the first of the NPE logs on a pastebin, and put the rest of the log in a text file on my personal website, which I'm linking here with the pastebin, but is also at the bottom of the pastebin file. 

http://pastebin.com/pewZ1nrz
https://cherrii.000webhostapp.com/TE5_NPE_LOG.txt

It appears to be something with the reconfigurable sides, but I'm not a programmer at all, so I'm not sure if that's actually what I'm reading or not. Just thought I'd bring the error vomit in the logs to someone's attention.

**Comment by KingLemming** [comment]
That's being caused by WAILA. However, I might be able to add something that keeps it from being stupid.

**Comment by KingLemming** [comment]
Er...so I have to ask, what WAILA are you using? I can't find one for 1.10.2.

**Comment by Cherrii951** [comment]
It's Hwyla-1.8.8-B22_1.10.2.jar and Wawla-1.10.2-2.3.1.214.jar, both of which I got through the Curse launcher. 

I was using The One Probe, but I have Chickens/Hatchery, and TOP doesn't give the Chickens' stats - only WAILA.

**Comment by KingLemming** [comment]
I can mitigate it on this end, but HWYLA should really consider ISidedInventories >.>

**Comment by KingLemming** [comment]
Mitigated in dev.

**Comment by Cherrii951** [comment]
Thanks. :)
