### ISSUE TITLE
Minecfactory crash - rednet cable

### ISSUE THREAD

**Issue by Cronosus** [CoFH/Feedback#65]
When i use sledgehammer on rednet cable, game crash

crash report: http://pastebin.com/nNb6UByr

i use wrench and crash too :(
http://pastebin.com/82j2KXAh

**Comment by skyboy** [comment]
Fixed by https://github.com/skyboy/MineFactoryReloaded/commit/e4a8fc06c41df507ad0dbefb1ca4648741aafbdc
