### ISSUE TITLE
I can not craft iron gear

### ISSUE THREAD

**Issue by crimso** [CoFH/Feedback#650]
Hello,

I can not craft iron gear, the reciepe is OK in JEI but as zou can se on the picture its not crafting it.

I am using direwols 1.12 mod pack with some extra mods.

Thank zou

https://imgur.com/WhUXnwO
https://imgur.com/LHrxqk3

EDIT: I found the problem, UniDict mod made the conflict now is OK. :)

**Comment by GrimPanda** [comment]
Can you clarify how this was resolved? I was making tin gears just fine, but then suddenly they stopped crafting.  All other gears are ok still, but tin will not craft any longer.

**Comment by KingLemming** [comment]
Possibly by removing UniDict.

**Comment by GrimPanda** [comment]
Hmm I see, I'll give that a shot. I'm in the direwolf 1.12 pack as well. Interesting that this is occurring.
