### ISSUE TITLE
Client crash in SMP after clicking recipe book in inventory on 1.12.2

### ISSUE THREAD

**Issue by Guardian9978** [CoFH/Feedback#651]
After connecting to a SMP server I set up. When I click the Recipe book in the inventory screen I get the following crash on the client no errors on the server.
Error: https://pastebin.com/wzeX9vFQ

Server and Client have the same mods. (Listed below).
Testing in Singleplayer does not cause any crash.

Minecraft: 1.12.2
Forge: 4.23.0.2552

All mods are latest available from curseforge.com (as of 11/25/2017)
Code Chicken Lib: 3.1.3.313
Redstone Flux: 2.0.1
COFH Core: 4.3.6
COFH World: 1.0.1
Thermal Foundation: 2.3.6
Thermal Dynamics: 2.3.6
Thermal Expansion: 5.3.6

**Comment by KingLemming** [comment]
Your configs are different. Delete and regenerate them.
