### ISSUE TITLE
[CoFHTweaks] Erroring out on start

### ISSUE THREAD

**Issue by edenprojectde** [CoFH/Feedback#652]
I tried Forge 1481 and 1448, removed Optifine and Fastcraft, and tried Dev Builds 32 and 30, just to try out the Cofh Tweaks mod but ah well still getting an Error. If already reported or just stupid im sorry :< (didnt found this bug postet as of yet)

Getting this:
http://pastebin.com/W9YWJiwB

**Comment by skyboy** [comment]
Do not use jars marked -dev.
