### ISSUE TITLE
[Thermal Expansion] Failed to register mod plugin in JEI

### ISSUE THREAD

**Issue by mankra** [CoFH/Feedback#653]
Failed to register mod plugin: class cofh.thermalexpansion.plugins.jei.JEIPluginTE

https://pastebin.com/swycAumw

Minecraft: 1.12.2
Forge: 14.23.1.2554
JEI: 4.8.4.129
Thermal Expansion: 5.3.6.20

**Comment by mankra** [comment]
https://github.com/Chisel-Team/Chisel/issues/584

**Comment by KingLemming** [comment]
Gonna need a modlist for this, as I can't make it happen.

**Comment by mankra** [comment]
I'm confused. I tried to track down which mod it is by removing all other mods and readding them step by step. Now I have all 80 mods back in, but the error is still gone.

> [12:11:18] [main/DEBUG] [jei/jei]: Registering plugin: cofh.thermalexpansion.plugins.jei.JEIPluginTE ...
[12:11:18] [main/DEBUG] [jei/jei]: Registered  plugin: cofh.thermalexpansion.plugins.jei.JEIPluginTE in 107 ms

I like explanations, but I can live without. ;-)

**Comment by KingLemming** [comment]
So in theory, that'll happen when there's an invalid fuel registered to Minecraft's base fuel list. Unsure exactly how that could have happened, but that's why.

**Comment by KingLemming** [comment]
There's another possibility for this, and that's if something registered a fuel with a fuel value around 1. The new TE contains a mitigation for this, as unlikely as it may be.

Either way, calling it good.
