### ISSUE TITLE
Stuck: Adding Pulverizer Recipe using Diamond

### ISSUE THREAD

**Issue by RoloEdits** [CoFH/Feedback#653]
when i start up my world the minetweaker log came up saying modifications stuck
so i checked it out and in the minetweaker.log file i see this 

"INFO: Stuck: Adding Pulverizer Recipe using Diamond"

its not anything im adding, i haven't used minetweaker to change recipes for any machines

**Comment by KingLemming** [comment]
You might not have, but your modpack apparently is. Sorry, but this is Minetweaker.

**Comment by RoloEdits** [comment]
Thanks for Your Help
