### ISSUE TITLE
[Bug report] [Thermal Expansion] [1.12-5.3.6.20-universal] Overlapping textures on steam dynamo with upgrades installed.

### ISSUE THREAD

**Issue by Veggetossj** [CoFH/Feedback#654]
Playing a small custom pack with TE and some other mods installed, no fancy texturepacks or visual mods that enhance the game play.

After applying an upgrade to the dynamo (hardened), the corners texture that indicate that an upgrade is installed (light grey in this case) are on the same plane as the dynamo texture.

So when viewing the dynamo from a small distance (4+ blocks away) and moving the camera around, the corners flicker from the overlapping textures: https://imgur.com/a/qceT4

Someone already suggested turning mipmapping off in the options, as it might have been the issue, but it still persisted when having it turned off.

Modlist: https://imgur.com/a/NYjRa

**Comment by KingLemming** [comment]
Sorry, but this is just your setup taking visual shortcuts. We don't see any z-fighting and this is basically configuration on your end - it's not explicitly in the code.

**Comment by KingLemming** [comment]
Well, actually, what hardware are you running? I'm willing to entertain this.

**Comment by Veggetossj** [comment]
My computer has the following hardware:

Motherboard: Asus Prime Z270-A
Processor: Intel® Core™ i3-7350K Processor; 4M Cache, 4.20 GHz
RAM: Ballistix 16 GB DDR4-2400 (4GB allocated)
Graphics: MSI 4GB D5 X R9 290 Gaming R

**Comment by KingLemming** [comment]
I'm going to try relaxing a couple of things and we'll see how it goes. Grr AMD cards.

**Comment by KingLemming** [comment]
Take a look with the new builds and let me know. I can't get them to flicker at any angle, but I don't have an AMD card. :/

**Comment by Veggetossj** [comment]
I'll let you know if anything has changed in the new builds, once the modpack gets updated.

**Comment by Tahakk** [comment]
Since I guess you are playing DW20 modpack you can actually do it yourself if you are using TwitchApp.

If you go to **Mods** -> **_"Chose your pack"_** -> **Installed Mods** -> **find TE** and update to newer version

btw. if you cannot update your mods make sure that you don't have it **Locked** in **Profile Options**

**Comment by KingLemming** [comment]
So?

**Comment by Veggetossj** [comment]
It's fixed, havent seen any Z-fighting anymore. Thank you for that :)

**Comment by KingLemming** [comment]
Cool.
