### ISSUE TITLE
Redstone relay bug.and new fluiducts

### ISSUE THREAD

**Issue by kenaj12** [CoFH/Feedback#655]
Thermal dynamics: version 1.1.0B2-149
COFH core: version 3.03B2-294
MineFactoryReloaded: version 2.8.0-104

Hi,
i've been messing around with redstone relays for ducts and found a bug (atleast I think its a bug). I was trying to fill the auto-spawner, from MFR, using Flux-Plated fluiduct, from Thermal Dynamics, with mob essence and RF. The ducts themselves work nicely but if I add a Redstone relay inbetween the autospawner and the duct (in the servo slot) the auto-spawner stops recieving both liquid and RF. Same problem occurs with other machinery like pulverizer and magma crucible, both from Thermal expansion.

Is this intended, not being able to move items, energy, fluids if the relay is inbetween the destanation and the duct?

Now, the only issue with new fluiducts, flux-plated fluiduct and super-laminar fluiduct, is only that they connect to machines (for example magma crucible) even if there is no input or output port.

That's it for now.

EDIT: forgot to tell about the luxducts which supposedly glow when they recieve a redstone signal. The issue with them is that they won't stop glowing unless you destroy them.

**Comment by KingLemming** [comment]
The relay thing is working as intended but after a little discussion, it should probably work the way you think it works, so we'll change it.

Fluiduct thing actually seems to be happening with all of them and we aren't sure why yet.

I can't reproduce the Luxduct thing at all, multiple chunks, multiple redstone sources, nothing. It always works correctly.

**Comment by KingLemming** [comment]
Actually, we know why it happens with all Fluiducts - it's actually supposed to. There's sort of an issue with how IFluidHandler tends to be used and if we rely on getTankInfo to properly use handlers, people tend to screw it up.

So unfortunately, I think that has to stay for now.

**Comment by kenaj12** [comment]
Okay, Thank you!
