### ISSUE TITLE
[1.12.2] [Thermal Expansion] Crash w/ Forestry (NetworkDispatcher Exception)

### ISSUE THREAD

**Issue by SnowShock35** [CoFH/Feedback#655]
#### Issue Spec

- Minecraft 1.12.2
- Minecraft Forge 14.23.1.2555
- CoFH Core 1.12-4.3.6.14
- Redstone Flux 1.12-2.0.1.2
- Thermal Foundation 1.12-2.3.6.16
- Thermal Expansion 1.12-5.3.6.20
- Other Mods
  - Forestry 1.12.2-5.7.0.213

#### Issue Description

Crash when placing an Apiarist backpack (with a certain amount of contents) into a Strongbox of some description.

Likely caused by overly large amount of NBT data stored on the bees/backpack.

#### Issue Media

- [Latest Log (Exception towards the bottom)](https://paste.ee/p/NqjlT)

**Comment by KingLemming** [comment]
Yup. You're into fundamental Minecraft issue territory here. Not sure if it's really fixable.

**Comment by KingLemming** [comment]
Having said that, I can't actually get this to happen. So please elaborate.

**Comment by SnowShock35** [comment]
It appears it might be another mod. Ugh this is going to be a pain to track down. Apologies KL. Should've tested more throughly

**Comment by KingLemming** [comment]
Yeah, I'm starting to come to the same conclusion but wanted to be sure first. The 32k packet limit is from client to server, and the Strongbox doesn't actually SEND a packet from client to server.

**Comment by KingLemming** [comment]
This isn't the best picture, but I think it does show that it's likely not on the Strongbox:

![2017-11-27 14_51_39-minecraft 1 12 2](https://user-images.githubusercontent.com/2118598/33286140-958b97f8-d382-11e7-9983-24478b57aa0f.png)

I'll leave this up for a bit just incase you trace down a strange interaction, but I think we're probably good.
