### ISSUE TITLE
Itemducts skipping non full storage drawers.

### ISSUE THREAD

**Issue by Logoth** [CoFH/Feedback#656]
Thermal Dynamics version: 2.3.6.13
Storage Drawers version: 1.12.1-5.3.3

Unsure if this is a thermal dynamics issue, or a storage drawers one.

If I place a row of 1x2 storage drawers with itemducts along the line, and a chest at the end, and a set of items to go into them, items being piped through the ducts will skip non-full drawers with the same item already in it and go to the next drawer or the end (if the next one has something else in it).

1x1 drawers, caches, chests etc all seem to work fine. If I pre-set and lock every drawer to a different material type, if it skips, it will go to the end of the line to the final chest.

Her'es a quick video of it happening: http://webmshare.com/play/ZjjGK

**Comment by KingLemming** [comment]
Offhand, this is probably on the drawer. What's happening is that the duct is querying it for the next item type (gold) and it's responding in the negative, so it moves on to the next valid destination.

Why this is happening, I don't know. Will leave this up for now while I investigate on my end. Please crosspost this to Storage Drawers though.

**Comment by Logoth** [comment]
Here's the storage drawers post: https://github.com/jaquadro/StorageDrawers/issues/590
