### ISSUE TITLE
No permission nodes cofh core 1.12

### ISSUE THREAD

**Issue by unstablecraft** [CoFH/Feedback#658]
please make it possible for server owner's to disable cofh compleetly through permmision nodes 
since you guys use permission levels but no actual nodes that let me switch stuff off.
 like the tps command wich is wierd that players have acces to on servers

**Comment by KingLemming** [comment]
Why is it weird that players are able to know about server performance?

**Comment by unstablecraft** [comment]
command logger and the spam is real and cofh has for me no use and for the players on the server has it no use 

so it would be nice if you gave atleast the people that run servers the option to turn it off or disable the cofh commands compleetly
 but atm there is no such option at all

**Comment by KingLemming** [comment]
If it has no use, tell people to stop using it. ;)

Also, I'm looking at the Forge Permission API and it seems like even if I were to add a node (which would only be less flexible), you still couldn't disable it, as there's nothing in there about that.

So I'm not really sure what you're talking about when you say permission node.

**Comment by unstablecraft** [comment]
so adding  a permission node per cofh command (like a normal plugin) makes things less flexible ?

**Comment by unstablecraft** [comment]
or let op's change the permission level per command

**Comment by unstablecraft** [comment]
so that only admins or higher have acces to cofh

**Comment by KingLemming** [comment]
Ah, you said plugin. You want bukkit support. Answer to that is no.

I'll consider config options, but nothing changable mid-gameplay or per-player.

**Comment by unstablecraft** [comment]
that was where i was aiming for  just the config option  is more then  enough

**Comment by KingLemming** [comment]
I still don't see the issue with players being able to know their TPS. What kind of shadiness are you hiding exactly?

**Comment by unstablecraft** [comment]
haha im not hiding any thing its just my ocd that players in this have acces to things i cant change
 and shady ?? all my discord bridges show current tps as shown here http://prntscr.com/hgfplj
