### ISSUE TITLE
Crash when holding shift and hovering over capacitor

### ISSUE THREAD

**Issue by Lilylicious** [CoFH/Feedback#659]
Minecraft version: 1.12.2
Forge version: forge-14.23.0.2531
Modpack: FTB Presents Direwolf20 1.12 (with ProjectE added)
Modpack version: 1.1.0

Mod: Thermal Expansion 1.12-5.3.6.20-universal
Item: Flux Capacitor (Resonant)

When holding shift over the flux capacitor, the game crashes. I have definitely held shift over it before without issue. The problem appeared soon after upgrading it to resonant. The first time it happened, I tried shift clicking it into the Energetic Infuser. I believe the capacitor had 5 million RF in it, due to charging an item from another mod (exchanger tier 5) with 20 million. After the issue started, all capacitors (regardless of charge) also crash with holding shift over them.

I have tested in a test pack containing just thermal mods + exchangers/JEI a number of combinations of actions with the infuser, different capacitors, and the exchanger mod, without being able to reproduce the bug.

Crash log/Mod list: https://pastebin.com/0BYqYv29

**Comment by KingLemming** [comment]
Your keyboard got stuck somehow and was sending invalid input.

**Comment by Lilylicious** [comment]
Any reason this is exclusively happening with the capacitors? Shift clicking over machines works as normal, expanding the tooltip.

**Comment by KingLemming** [comment]
In that case, you have another mod attempting to hijack the capacitor tooltip and somehow adding a value to the shift.

CoFH shift tooltip code is universal, if the issue were on our end, you'd get the crash on everything.

**Comment by Lilylicious** [comment]
After hours of hunting, I've found the issue. Deleting options.txt resolved it, which made me think of keybinds, since that is shown in the tooltip.

Turns out, binding the COFH "Cycle Item Mode" to "<" caused the issue.

**Comment by KingLemming** [comment]
Ah. Now that's interesting.

**Comment by Lilylicious** [comment]
I'm not familiar with exactly how your code is structured, or whether or not this is doable, but removing the keybind from the tooltip (preferably only in the cases where it would cause a crash) would cause minimal loss of information to the player while preventing a crash.

**Comment by KingLemming** [comment]
I've added a line which will just modulo the key by 256. It's not ideal and will probably end up displaying an incorrect key for you, but it won't crash.

**Comment by Lilylicious** [comment]
This is a typical edge case. From what I can tell, the only situation where this happens is when you use a keyboard layout where you can access a character that exists in the LWJGL layout with modifier keys directly without the use of modifier keys (i.e. < on a Swedish keyboard, which is shift + , on a US keyboard). The letter Å doesn't exist on that layout, and is interpreted as semicolon.

It's a shitty fix, but considering the rarity of encountering the issue, I think it's good enough. Just don't forget about it and get confused when someone eventually asks why the tooltip is showing the wrong character!

**Comment by KingLemming** [comment]
I may end up having to go with Mojang's "solution," which is to basically just mark it as invalid:
https://bugs.mojang.com/browse/MC-30704

**Comment by Lilylicious** [comment]
I'd certainly say that (NONE) or (INVALID) is better than displaying a valid key that is incorrect.

**Comment by KingLemming** [comment]
Yep, and I have now done that. 4.3.7.24. :)
