### ISSUE TITLE
MC Crashed after placing fluidducts

### ISSUE THREAD

**Issue by FurryScout** [CoFH/Feedback#659]
Hey there. Me and my friend were playing our own custom modpack and we both encountered an issue after I placed down a hardened fluid duct. Our whole client crashed and we cannot entered our world again. Please do help out, thanks!

MC version: 1.7.10
CoFH core: 3.0.2-262
ThermalDynamics: 1.0.0RC2-77
ThermalExpansion: 4.0.1-182
ThermalFoundation: 1.0.0-81

**Comment by KingLemming** [comment]
Yeah...we can't help without the crash log.
