### ISSUE TITLE
Tabula Rasa - Idees

### ISSUE THREAD

**Issue by Cronosus** [CoFH/Feedback#66]
Tabula rasa is now you mod, i dont know if i can post it here, if not, ignore it..

add:
- hardeness, durability
- type (glass,block,door,stair,slab, model..) - model is own object, but its maybe not possible, i dont know
- sounds for placing/destroing or idle (placed block) (examle: dig.glass)
- multi side textures (for blocks).. maybe animated type too.
- glowing
- tool/weapon/armor types
- oredict names

**Comment by Gambigobilla** [comment]
I would love to have a chargeable item, but unlike capacitors it wouldn't transfer its charge to other items. So i would have a crafting material which requires to be fully charged.

**Comment by KingLemming** [comment]
Some of these are happening, most aren't. Best I can tell you.
