### ISSUE TITLE
[1.12] [Thermal Foundation] Cannot smelt Aluminium Ore

### ISSUE THREAD

**Issue by SnowShock35** [CoFH/Feedback#660]
#### Issue Details

- Minecraft 1.12.2
- Minecraft Forge 14.23.1.2556
- Dependencies:
  - CodeChicken Lib 1.8+ 3.1.3.313
  - Redstone Flux 2.0.1.2
  - CoFH Core 4.3.6.16
  - CoFH World 1.0.1.8
- Thermal Foundation 5.3.6.20

#### Issue Description

Unable to smelt Aluminium Ore. Missing recipe or broken recipe perhaps?

To reproduce:

1. Install the above mods.
2. Load up the instance
3. Create a new world
4. Find some aluminium ore
5. Attempt to smelt it

#### Issue Media

Attempting to smelt Aluminium Ore in a Minecraft Furnace
![Issue Media #1](https://ss.blamesnow.co.uk/2017/11/1511896705-2b038f23.png)

**Comment by SnowShock35** [comment]
The mods above (with the exception of JEI and Thermal Expansion) are all the mods in the pack. I believe this issue is actually legitimate. 😛

**Comment by SnowShock35** [comment]
It seems Iridium Ore is the same. Also, Silver and Platinum don't give XP. Not sure if intentional or not

**Comment by KingLemming** [comment]
The smelting is intentional - traditionally mods have treated some ores as requiring blast furnaces.

I'll investigate the xp though.

**Comment by KingLemming** [comment]
Times change. I'll adjust the ores.

And XP figured out too.
