### ISSUE TITLE
Rubber Sappling not in oredict!

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [CoFH/Feedback#660]
Rubber sappling seems to be missing the ore dictionary registry. Would be nice to have, so I can get rid of the excess for "stuff" ;)

**Comment by KingLemming** [comment]
Why should it have an DreDict entry exactly? The purpose of the OreDict is crafting equivalency.

**Comment by Unrepentant-Atheist** [comment]
In this case, I want to get rid of the gazillions of sapplings from mega rubber trees in Mariculture's sifter for bait for fishing.

**Comment by KingLemming** [comment]
Can't you Minetweak this?

**Comment by Unrepentant-Atheist** [comment]
I guess I could, sure. I haven't used Minetweak, because there was no need so far. Also because 170 loaded mods is more than enouhg for now :P.

**Comment by KingLemming** [comment]
People usually have it installed already, so just figured it'd be easiest.

**Comment by skyboy** [comment]
Implemented by https://github.com/skyboy/MineFactoryReloaded/commit/ef540542352514fe9ca5decba1ca319b9f50224b
