### ISSUE TITLE
[1.12.2] [Thermal Expansion] Crash with florbs

### ISSUE THREAD

**Issue by UnRealDinnerbone** [CoFH/Feedback#661]
Forge: 1.12.2 - 14.23.1.2556
Minecraft: 1.12.2\
CrashReport: https://pastebin.com/ysQ5g87R
The Server crashes when a florb is right clicked, it happened with a water florb, the weird thing is though when i tired to reproduce the crash in singe player it did not crash, the crash seems to only happen it multiplayer

**Comment by KingLemming** [comment]
Interesting. I wonder what Forge managed to break.
