### ISSUE TITLE
Pulverizer Crash/Ticking block entity

### ISSUE THREAD

**Issue by goalie1248** [CoFH/Feedback#661]
It had been going for a few minutes at this point, just grinding up cobble and dumping it into an induction smelter.

Crash: http://pastebin.com/a861b0dz

**Comment by KingLemming** [comment]
Duplicate of #658. It's like people don't search. :/

Caused by Extra Utilities 1.2.7+.

**Comment by goalie1248** [comment]
Whoops sorry about that.. Shouldn't be doing anything of importance before coffee in the morning

**Comment by KingLemming** [comment]
Meh. No worries. :)
