### ISSUE TITLE
[Suggestion]Gear mode for the compacter

### ISSUE THREAD

**Issue by X1machinemaker1X** [CoFH/Feedback#662]
Making gears is, well, it happens all the time. I think the compacter should have another mode for gears.

**Comment by KingLemming** [comment]
For now, gears require Iron + another Ingot, so that's a multiple input kind of thing.

Which the Compactor isn't, so that won't be happening, sorry.

I'll eventually get the Cyclic Assembler back up though, no worries.

**Comment by KingLemming** [comment]
Ya know what, I gave this some more thought, and I have no problem making it an augment. :)

**Comment by X1machinemaker1X** [comment]
Awesome! Thanks.

**Comment by AcidKat** [comment]
This actually happens to be the way Immersive Engineering handles automated gear processing. The Metal Press has a mold for gears that requires 4 ingots of the desired gear material and this process saves you an iron ingot, (I guess this is a trade for the power cost). I like the idea of having this work in the compactor too ^^
