### ISSUE TITLE
[1.12.2] CoFH Core breaks modded bows (Twilight Forest/Better With Mods/Addons)

### ISSUE THREAD

**Issue by Kevun1** [CoFH/Feedback#663]
Forge v5245
CoFH Core 4.3.6.14

With CoFH Core installed, some modded bows lose their special effects. So far, I've found Twilight Forest and Better With Mods/Addons bows affected.

Specifically, the Twilight Forest Tri-Bow/Seeker Bow/Ice Bow no longer have their special abilities when CoFH is installed, they act like regular bows, the Composite Bow from BWM doesn't do extra damage with broadhead arrows and the Greatbow and Yumi from Better With Addons can't fire their special arrows.

I suspect the issue is with the ArrowLooseEvent handler in the EventHandler class in CoFH core.

**Comment by KingLemming** [comment]
Okay seriously, people need to stop reporting things the day I'm trying to push new builds. I swear there's a goddamn conspiracy going on.

The tracker has been relatively quiet for like a month and now everybody, their brother, and their dog comes up reporting random crap.

**Comment by KingLemming** [comment]
Offhand, I'm not sure how this should be handled. The problem is that their bows are firing the events - which means that by design, they want their behaviors to be overridden by event handlers.

**Comment by KingLemming** [comment]
Okay so for now, I'm dealing with it by doing some rather strict comparisons. :)

**Comment by Kevun1** [comment]
From a cursory glance at the code, maybe you can make it so that the ArrowLooseEvent handler only shoots the *extra* arrows from the multishot enchant, and the original behavior of the bow is otherwise unchanged? So tasks like removing an arrow from the player's inventory, playing the firing sound, and any other custom behavior would be deferred to whatever bow that triggered the event. 

The only problem I see with that is that the multishot arrows from CoFH core may not match some custom arrow behavior of a modded bow, but I think that's a better than simply overriding the functionality modded bows that call the ArrowLooseEvent. Also, if modded bows didn't call the event, their mods will be incompatible with other mods that use the event. For example, Survival Tweaks makes arrows fly faster when the player has strength.

I looked at the code for like 30 seconds so I might not know what I'm talking about either.

**Comment by KingLemming** [comment]
Yeah, that's not the only thing it does though. It also allows for the use of quivers, marking them as valid and handling them properly.

I suspect I'll end up making an API and other mods will need to opt-in.

**Comment by Kevun1** [comment]
And maybe a simple blacklist config option to prevent specific bows from being affected? Since some mods are bound to not add compatibility (or be really slow to) and that'll drive pack makers nuts.

**Comment by DaedalusGame** [comment]
I know this is already fixed (thank you for that), but the fact that we fire the event doesn't mean that we want our bows to fire vanilla arrows only, it means that you (other people) can add extra functionality when we fire our bows. Truth be told, I wish the event was more useful and included the projectile entity and ammo stack we use when fired.
