### ISSUE TITLE
World generation crash when using COFH dungeon generation in combination with Plant Mega Pack

### ISSUE THREAD

**Issue by Skyqula** [CoFH/Feedback#663]
Hello,

Ive been playing around with COFH core world generation, or more specifically, dungeon generation.

This is my current file dungeons.json. My goal is to make themed dungeons for the 4 elementals, starting of with a pig just to see if I can get it working.

    {
       "BlizzDungeon": {
         "template": {
           "type": "uniform",
           "generator": "dungeon",
           "spawnEntity": "Pig",		
           "spawnerFloor": "minecraft:packed_ice",
           "lootTable": "dungeonChest",
           "minHoles": 1,
           "maxHoles": 5,
           "maxChests": 5,
           "minHeight": 3,
           "maxHeight": 5,
           "minWidthX": 5,
           "maxWidthX": 9,
           "minWidthZ": 5,
           "maxWidthZ": 9
         },
         "block": "minecraft:packed_ice",
         "material": "minecraft:stone",
         "numClusters": 3,
         "minHeight": 0,
         "maxHeight": 128,
         "retrogen": "false",
         "chunkchance": 1,
         "biomeRestriction": "none"
       }
    }

That exact config with a clean install and just COFH core works. Doing a /cofh blockcount 500 100 500 minecraft:packed_ice returns values of 20 - 50 between different worlds. Great!

Additionally, the log reads:

    [23:43:09] [Client thread/INFO] [CoFHWorld]: CoFH Core found 3 World Generation files present in C:\Users\Skyqula\AppData\Roaming\Minecraft 1.7.10\config\cofh\world/.
    [23:43:09] [Client thread/INFO] [CoFHWorld]: Reading world generation info from: C:\Users\Skyqula\AppData\Roaming\Minecraft 1.7.10\config\cofh\world\dungeons.json:
    [23:43:09] [Client thread/INFO] [CoFHWorld]: Reading world generation info from: C:\Users\Skyqula\AppData\Roaming\Minecraft 1.7.10\config\cofh\world\ThermalFoundation-Ores.json:
    [23:43:09] [Client thread/INFO] [CoFHWorld]: Reading world generation info from: C:\Users\Skyqula\AppData\Roaming\Minecraft 1.7.10\config\cofh\world\Vanilla.json:

Now, adding in the mod Plant Mega Pack causes a massive slowdown in world generation. I am talking about 1 chunk per second if not (way) less. Its not my computer, I can generate modded worlds (130 mods) on amplified quickly.

Now this is not very clear as to whats the problem. My current mod setup:
![currentmodlist](https://cloud.githubusercontent.com/assets/6379067/8600625/0adc1a44-2667-11e5-9c7a-a5d3cb28630c.jpg)
As far as I am aware all mods are updated to there latest stable releases.

This modlist without the dungeons.json and with Plant Mega Pack generates amplified worlds in seconds.

This modlist without plant mega pack and with dungeons.json generates amplified worlds in seconds aswell.

This modlist with both the dungeons.json and Plant Mega Pack generates the following crash report: http://pastebin.com/bttwhwc9

Unfortunatly Plant Mega Pack seems to have some drama going on on curseforge so I connot find the proper place to report it to the PMP dev, I have however send him a PM on minecraftforum.net directing him to this issue.

Just ask away if anny further information is needed.

**Comment by KingLemming** [comment]
Just by the log, you have Fastcraft, so god only knows what's happening there.

But if we assume that Fastcraft isn't causing this, then it's likely PMP generating multi-chunk things and the world generation running rampant.

**Comment by KingLemming** [comment]
Looking a bit more closely,

at net.minecraft.world.World.markAndNotifyBlock(World.java:488)

shows up in the log whenever there is PMP generation. That means they're doing it very wrong. Block updating is not supposed to happen during generation.

**Comment by Skyqula** [comment]
Lets not trash talk alternatives while COFH Tweaks never loads #574 ;)

Eitherway, minecraft cant even crashreport without fastcraft in this instance: http://pastebin.com/y5y8FdRP

**Comment by KingLemming** [comment]
We can't actually reproduce #574. Can you?

And yeah, we're welcome to trash talk it because it's completely closed and obfuscated like it's NSA code or something. It's suuuper sketchy.

**Comment by Skyqula** [comment]
Unfortunatly I can reproduce #574 , clean install, just cofh tweaks, same result as already reported. Love to help if you need anny more info.

**Comment by Skyqula** [comment]
And the plot thickens. No plant mega pack, yet a crash: http://pastebin.com/31ph1ERB
And without fastcraft: http://pastebin.com/BCzqju7Q
Just COFH Core : http://pastebin.com/0dp1am9y

New dungeons.json (for the COFH Core only: all railcraft entries have been replaced with "minecraft:packed_ice"):

     {
    	"BlizzDungeon": {
    		"template": {
    			"type": "uniform", 
    			"generator": "dungeon",
    			"spawnEntity": "Blizz",		
    			"spawnerFloor": {
    				"name": "Railcraft:brick.frostbound", 
    				"metadata": 5
    			},
    			"lootTable": "dungeonChest",
    			"minHoles": 1, 
    			"maxHoles": 5,
    			"maxChests": 4,
    			"minHeight": 5,
    			"maxHeight": 7,
    			"minWidthX": 5,
    			"maxWidthX": 11,
    			"minWidthZ": 5,
    			"maxWidthZ": 11
    		},
    		"block": "minecraft:packed_ice",
    		"material": "minecraft:stone",
    		"numClusters": 5,
    		"minHeight": 0,
    		"maxHeight": 128,
    		"retrogen": "false",
    		"biomeRestriction": "none"
    	},
    	"BlazeDungeon": {
    		"template": {
    			"type": "uniform", 
    			"generator": "dungeon",
    			"spawnEntity": "Blaze",		
    			"spawnerFloor": {
    				"name": "Railcraft:brick.infernal", 
    				"metadata": 5
    			},
    			"lootTable": "dungeonChest",
    			"minHoles": 1, 
    			"maxHoles": 5,
    			"maxChests": 4,
    			"minHeight": 5,
    			"maxHeight": 7,
    			"minWidthX": 5,
    			"maxWidthX": 11,
    			"minWidthZ": 5,
    			"maxWidthZ": 11
    		},
    		"block": "minecraft:nether_brick",
    		"material": "minecraft:stone",
    		"numClusters": 5,
    		"minHeight": 0,
    		"maxHeight": 128,
    		"retrogen": "false",
    		"biomeRestriction": "none"
    	},
    	"BlitzDungeon": {
    		"template": {
    			"type": "uniform", 
    			"generator": "dungeon",
    			"spawnEntity": "Blitz",		
    			"spawnerFloor": "minecraft:sandstone",
    			"lootTable": "dungeonChest",
    			"minHoles": 1, 
    			"maxHoles": 5,
    			"maxChests": 4,
    			"minHeight": 5,
    			"maxHeight": 7,
    			"minWidthX": 5,
    			"maxWidthX": 11,
    			"minWidthZ": 5,
    			"maxWidthZ": 11
    		},
    		"block": {
    			"name": "minecraft:sandstone",
    			"metadata": 1
    		},
    		"material": "minecraft:stone",
    		"numClusters": 5,
    		"minHeight": 0,
    		"maxHeight": 128,
    		"retrogen": "false",
    		"biomeRestriction": "none"
    	},
    	"BasalzDungeon": {
    		"template": {
    			"type": "uniform", 
    			"generator": "dungeon",
    			"spawnEntity": "Basalz",		
    			"spawnerFloor": {
    				"name": "Railcraft:brick.sandy", 
    				"metadata": 5
    			},
    			"lootTable": "dungeonChest",
    			"minHoles": 1, 
    			"maxHoles": 5,
    			"maxChests": 4,
    			"minHeight": 5,
    			"maxHeight": 7,
    			"minWidthX": 5,
    			"maxWidthX": 11,
    			"minWidthZ": 5,
    			"maxWidthZ": 11
    		},
    		"block": "minecraft:hardened_clay",
    		"material": "minecraft:stone",
    		"numClusters": 5,
    		"minHeight": 0,
    		"maxHeight": 128,
    		"retrogen": "false",
    		"biomeRestriction": "none"
    	}
    }

And the console output:

    [00:41:36] [Client thread/INFO] [CoFHWorld]: CoFH Core found 3 World Generation files present in C:\Users\Skyqula\AppData\Roaming\Minecraft 1.7.10\config\cofh\world/.
    [00:41:36] [Client thread/INFO] [CoFHWorld]: Reading world generation info from: C:\Users\Skyqula\AppData\Roaming\Minecraft 1.7.10\config\cofh\world\dungeons.json:
    [00:41:36] [Client thread/INFO] [CoFHWorld]: Reading world generation info from: C:\Users\Skyqula\AppData\Roaming\Minecraft 1.7.10\config\cofh\world\ThermalFoundation-Ores.json:
    [00:41:36] [Client thread/INFO] [CoFHWorld]: Reading world generation info from: C:\Users\Skyqula\AppData\Roaming\Minecraft 1.7.10\config\cofh\world\Vanilla.json:

**Comment by KingLemming** [comment]
Honestly just looks like you're generating things that are too large.

**Comment by skyboy** [comment]
Yeah, you're trying to generate 5 dungeons in every chunk. That's ridiculously excessive.

**Comment by KingLemming** [comment]
Yeah, unfortunately the issue here is just one of pure configuration. It'd be nice if we had a way to gracefully alert people of this, but this isn't a bug so much as a statistical inevitability when you're trying to gen that many large objects in each chunk.

**Comment by Skyqula** [comment]
Well, I was asking for an example over on reddit ;)

I guess what I find missing in the documentation is what setting to use for dungeon rarity. As I would expect it trying to generate every chunk, but only able if it finds a cave?

**Comment by KingLemming** [comment]
It's not that 2 is a problem necessarily, or even 5, in a given chunk. The problem is that in *every* chunk.

Don't worry, if you dropped the odds to 1/10, you wouldn't have that 1/100 crash issue. This is sort of a trial and error thing unfortunately. It's not something I've tinkered with personally, although if you can come up with a good example for how to use the generator, we can put it on the website.

**Comment by Skyqula** [comment]
Ok, so ive been trying for abit more. Got a new config file that is succesfully generating all 4 dungeons. Even when Plant Mega Pack is included. I used a "chunk chance" of 20 (should arguably be abit higher, but for testing it works). I also set the "minHoles" to 0. After all, with only a 1/20 chance of spawning and there also needing to be a cave it would get realy rare to get one to spawn.

I also tried removing the size paramaters and just use the defaults. I could then set chunkchance to 1 and it would still generate the world, including with Plant Mega Pack. So the problem seemed to be that I set the size to high.

So in that regard, the problem is fixed. But:
![2015-07-15_16 13 44](https://cloud.githubusercontent.com/assets/6379067/8701422/fb129d86-2b11-11e5-92ab-311678482d0f.png)
What we see here is one of the multiple dungeons I located. Both with mineholes of 0 aswell as those with a minholes of 1. I think the problem is obvious but ill sum them up:
* No walls are generated, only 4 pillars.
* No floor is generated, only 1 block below the pillars.
* No chests are generated (no floor to generate them on?).

It does this with just cofh core and thermal foundation aswell.

Dungeon settings used:

    	"BasalzDungeon": {
    		"template": {
    			"type": "uniform", 
    			"generator": "dungeon",
    			"spawnEntity": "Basalz",		
    			"spawnerFloor": {
    				"name": "Railcraft:brick.sandy", 
    				"metadata": 5
    			},
    			"lootTable": "dungeonChest",
    			"minHoles": 0, 
    			"maxChests": 4
    		},
    		"block": "minecraft:hardened_clay",
    		"material": "minecraft:stone",
    		"numClusters": 1,
    		"minHeight": 0,
    		"maxHeight": 128,
    		"retrogen": "false",
    		"biomeRestriction": "none",
    		"chunkChance": 1
    	}

**Comment by KingLemming** [comment]
Paging @skyboy

**Comment by Skyqula** [comment]
Had a chance to look at the no walls/floor issue? @skyboy

**Comment by skyboy** [comment]
Been largely focusing on getting NetherOres, MFR, and CoFHTweaks ready for a release; they've gone too long. Though I can probably start addressing this now, get it out with the next core.

**Comment by Skyqula** [comment]
No rush, just wondering ;)

**Comment by Skyqula** [comment]
With  CoFHCore-[1.7.10]3.0.4B1-308.jar the floor is there! :) http://i.imgur.com/g9QAePA.png

**Comment by skyboy** [comment]
The missing walls are an issue, though. were there blocks above?

**Comment by Skyqula** [comment]
Nope, shoudnt be? No chests either, btw.

**Comment by skyboy** [comment]
I want to add the fixed in dev label again. Walls and chests form now.

**Comment by Skyqula** [comment]
Confirming that the dungeon generation is working with CoFHCore-[1.7.10]3.0.4B1-309.

![2015-07-31_13 56 09](https://cloud.githubusercontent.com/assets/6379067/9006839/04c52ad4-378c-11e5-877a-e5f048457b35.png)

![2015-07-31_13 59 21](https://cloud.githubusercontent.com/assets/6379067/9006884/5f727180-378c-11e5-9667-5fc48c29c4a7.png)

![2015-07-31_14 02 05](https://cloud.githubusercontent.com/assets/6379067/9006922/c3563d80-378c-11e5-899d-9311831f2719.png)

![2015-07-31_14 08 06](https://cloud.githubusercontent.com/assets/6379067/9007013/9ee194ee-378d-11e5-9945-e91ca2d278d6.png)

**Comment by jermangarc** [comment]
which pack is this, looks cool!

**Comment by Skyqula** [comment]
This is not in a modpack (well my private one), more info on how to make those can be found here: https://www.reddit.com/r/feedthebeast/comments/3fzgtt/dungeons_generated_using_cofh_core/
