### ISSUE TITLE
[CoFHCore][1.12.2-4.3.7.21] Flux-Infused Quiver unuseable

### ISSUE THREAD

**Issue by bill96012** [CoFH/Feedback#665]
tried change Redstone Arsenal version, but the problem still exists.
so I Try change CoFHCore's ver to 1.12-4.3.6.14, then the problem is solved.
so.. I guess...

and sorry for my grammar

**Comment by Unrepentant-Atheist** [comment]
Can confirm! Latest version makes it unuseable. Have to use arrows.

**Comment by The-PurpleOrange** [comment]
Third'd, Glad to know I'm not the only one.

**Comment by KingLemming** [comment]
.22 fixes it.
