### ISSUE TITLE
[1.12.2] Issue with Immersive Engineering Garden Cloches

### ISSUE THREAD

**Issue by AnZaNaMa** [CoFH/Feedback#666]
I've been having issues with my server crashing whenever I have a fluiduct connected to a Garden Cloche. I'm not 100% sure if it's an issue with thermal dynamics or with immersive engineering, but it only seems to be happening with fluiducts.

Here's a crash report: https://pastebin.com/GN9FhG0V

Also, If it's relevant, I'm playing on the Direwolf20 1.12.2 pack

**Comment by Serifina** [comment]
It's an Immersive Engineering bug with the cloches. The latest version of IE fixes it, which for whatever reason, the DW20 pack does not have yet.

**Comment by AnZaNaMa** [comment]
Oh okay thank you. Will be looking forward to an update from FTB
