### ISSUE TITLE
Retrievers with max total items set can get stuck

### ISSUE THREAD

**Issue by Tora-B** [CoFH/Feedback#667]
Retrievers set to limit max total items in inventory can get stuck on one item, and won't attempt to satisfy the rest of their list. For example, let's say you have three items whitelisted, but only two of them are currently available to pull -- you're out of the third item. The retriever will continue to pull until it satisfies all available items, but if the third item becomes available after it's satisfied the other two, the retriever won't pull it, presumably because it's stopped its cycle on one of the items that has already been satisfied. Reduce that item below the threshold, and it will start cycling again, suddenly realize that the third item is available and unsatisfied, and will start pulling it.

Versions:
forge-1.7.10-10.13.4.1448
CoFHCore-[1.7.10]3.0.3B2-294
RedstoneArsenal-[1.7.10]1.1.1B1-85
ThermalDynamics-[1.7.10]1.1.0B2-149
ThermalExpansion-[1.7.10]4.0.2B2-210
ThermalFoundation-[1.7.10]1.2.0B1-95

**Comment by KingLemming** [comment]
Hrm...not seeing this. It's possible that we accidently fixed it in dev already.

**Comment by Tora-B** [comment]
Yep, as we determined, it's all fixed on the new releases, and other weirdnesses were just due to misunderstanding ductlogic. Thanks!
