### ISSUE TITLE
Fractionating Still isn't accepting potions. 

### ISSUE THREAD

**Issue by Akitori** [CoFH/Feedback#667]
Perhaps I'm doing this wrong, but my current setup doesn't seem to be working at producing any potions. Below are some screenshots i took of me trying to set up a refinery `test` to see if it works.

![2017-11-29_14 49 59](https://user-images.githubusercontent.com/24502131/33398531-eefb5c72-d514-11e7-9c4f-3b2692fe4a13.png)

Here I took proof of the recipe in game to prove it is in fact registered.

![2017-11-29_14 50 45](https://user-images.githubusercontent.com/24502131/33398553-fda6f10a-d514-11e7-9caa-4700552fe3ea.png)

Here's a nearby alchemical imburer filled with potion i want to refine.

![2017-11-29_14 50 53](https://user-images.githubusercontent.com/24502131/33398614-2c537d02-d515-11e7-81cc-b7392eeb58b1.png)

finally, here's the still despite all my output/input changes, where nothing has occured.

![2017-11-29_14 51 02](https://user-images.githubusercontent.com/24502131/33398628-3df90b4e-d515-11e7-8211-40fb941088fe.png)

Forge Version: 2555, Latest releases on all COFH items.

**Comment by Serifina** [comment]
I was just testing this with potions of instant healing, and can also report that the Fractionating Still is refusing to accept potion fluid at all. The Alchemical Retort augment is installed.

**Comment by KingLemming** [comment]
Yeah, I've figured out why but I'm unsure when, because I definitely had it working. Either way, won't be long to patch.

**Comment by KingLemming** [comment]
Fixed. New file is up on CurseForge. 5.3.7.25.
