### ISSUE TITLE
Charged Redstone Flux Armor doubles default armor. 

### ISSUE THREAD

**Issue by Akitori** [CoFH/Feedback#668]
So here's the weird thing with fluxed armor. Uncharged, it gives default armor of 20, like diamond would. However, the second you put any form of Charge into any piece, that piece gets DOUBLE its armor put on.

ex: Helmet has +3 armor uncharged. With some charge, that becomes +6 armor (shown by the armor visuals.)

Course this is hard to show, so instead I made a video to show off this bug. 

https://youtu.be/-5EB7dhDFDE

**Comment by KingLemming** [comment]
It's a display bug, doesn't actually change real armor. It's sort of on Forge's end, which I'm annoyed by, but I think I can handle this quickly enough.

**Comment by KingLemming** [comment]
2.3.7.18. On CurseForge.
