### ISSUE TITLE
Crash with pulverizer

### ISSUE THREAD

**Issue by Kris6699** [CoFH/Feedback#668]
Sorry about the long crash report.
The only thing that i see causing it is on occasion the me export bus or interface forcibly tries to insert a extra item into the pulverizer. So I'm unsure if this is on your side or applied energistics.

Crash Log:
http://pastebin.com/nA9BmsWm

**Comment by KingLemming** [comment]
It's caused by x-mod with ExU > 1.2.7. It's a duplicate of #658.

**Comment by Kris6699** [comment]
Any estimates on when the update fixing this will be released?

On Fri, Jul 10, 2015 at 5:33 PM, KingLemming <notifications@github.com>
wrote:

> Closed #668 <https://github.com/CoFH/Feedback/issues/668>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CoFH/Feedback/issues/668#event-353347156>.
>



-- 
Kristian Jones

**Comment by Kris6699** [comment]
By the way sorry about not searching before posting this.
