### ISSUE TITLE
Crash with Fractionating Still

### ISSUE THREAD

**Issue by billybricker** [CoFH/Feedback#67]
http://pastebin.com/VKk9nT2t

I have Ender IO conduits on top of the still inputting power and outputting rosin. It wouldn't output the rosin into the drawer so i was changing the i/o for the top of the still and it crashed when I got to the orange setting. It doesn't crash when it's empty,

Also the conduits won't extract rosin out of the top of the still. The will do input and output on the top of the sawmill just fine though..

**Comment by KingLemming** [comment]
Have a screenshot of your setup? Looking through the code, I'm unsure where exactly that "4" is originating...

**Comment by billybricker** [comment]
http://imgur.com/a/VGtxT
