### ISSUE TITLE
Reloaded clear fluiducts causing chest render/lighting errors

### ISSUE THREAD

**Issue by dzdod1** [CoFH/Feedback#670]
I first noticed this bug in Agrarian Skies 2. I went through all the blocks in the world and found that it was the fluiducts full of lava that were causing this render error with chests and a couple of other blocks.

I made a test setup that only had the CoFH mods (freshly downloaded) that AS2 had (CoFH Lib, Core, Nether Ores, MFR, and all three of the Thermal Expansion mods). What I have gotten from my tests is that any time a reloaded pipe is full of any liquid, it will make some chests render this way. (A reloaded pipe is any pipe that has gone through a world save or a chunk unload & load.) Moving around and/or turning will sometimes stop a chest from rendering "bright" or cause it to (possibly due to the order of rendering changing). If I destroy the pipe or empty the pipe, this weird rendering disappears. This only occurs with clear pipes (opaque do not have this problem). I have also tried this out with just CoFH Core, and all three of the Thermal Expansion mods and got the same result.

Bright chests:
![bright chests](https://cloud.githubusercontent.com/assets/13282120/8631437/43e48bc4-2733-11e5-872c-ce8262b80a8d.png)

Facing away:
![facing away](https://cloud.githubusercontent.com/assets/13282120/8631438/43e7a174-2733-11e5-957c-6057369e487e.png)

If you wish to see a video of this I have one here: https://www.dropbox.com/s/2lvmtw9gzy1r0gw/Testing.mp4?dl=0

**Comment by KingLemming** [comment]
Pipes do have a call where they disable lighting to render fluids, however - this call is correctly surrounded by GL push and pop.

Are you using Optifine and/or FastCraft?

**Comment by dzdod1** [comment]
I am using neither in the testbed or in AS2.

**Comment by dzdod1** [comment]
I have done further testing on my laptop (that's Windows, not Ubuntu). The same bug still appears on my Windows laptop.

The mods I have installed on my testbed are:
* CoFHCore-[1.7.10]3.0.3B2-294
* ThermalFoundation-[1.7.10]1.2.0B1-95
* ThermalExpansion[1.7.10]4.0.2B2-210
* ThermalDynamics-[1.7.10]1.1.0B2-149

**Comment by KingLemming** [comment]
Found the issue. It's actually a vanilla MC problem, but I've implemented a workaround.
