### ISSUE TITLE
Autonomous activator crash need help 1.7.10

### ISSUE THREAD

**Issue by DeathRules** [CoFH/Feedback#671]
-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows XP (x86) version 5.1
	Java Version: 1.8.0_31, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 104713992 bytes (99 MB) / 523501568 bytes (499 MB) up to 523501568 bytes (499 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx512M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1472 45 mods loaded, 45 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAAAAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAAAAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1472-1.7.10.jar) 
	UCHIJAAAAAAAAA	Forge{10.13.4.1472} [Minecraft Forge] (forge-1.7.10-10.13.4.1472-1.7.10.jar) 
	UCHIJAAAAAAAAA	appliedenergistics2-core{rv2-stable-10} [AppliedEnergistics2 Core] (minecraft.jar) 
	UCHIJAAAAAAAAA	CodeChickenCore{1.0.4.29} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAAAAAAA	NotEnoughItems{1.0.3.74} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.3.74-universal.jar) 
	UCHIJAAAAAAAAA	OpenModsCore{0.7.3} [OpenModsCore] (minecraft.jar) 
	UCHIJAAAAAAAAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJAAAAAAAAA	battlegear2{1.7.10} [Mine & Blade Battlegear 2 - Bullseye] (1.7.10-MB_Battlegear2-Bullseye-1.0.8.0.jar) 
	UCHIJAAAAAAAAA	appliedenergistics2{rv2-stable-10} [Applied Energistics 2] (appliedenergistics2-rv2-stable-10.jar) 
	UCHIJAAAAAAAAA	AWWayofTime{v1.0.1g} [Blood Magic: Alchemical Wizardry] (Blood-Magic-Mod-1.7.10.jar) 
	UCHIJAAAAAAAAA	chisel{1.5.7} [Chisel] (Chisel-1.7.10-1.5.7.jar) 
	UCHIJAAAAAAAAA	clonecraft{3.0} [CloneCraft] (Clone-Craft-Mod-1.7.10.jar) 
	UCHIJAAAAAAAAA	CoFHCore{1.7.10R3.0.2} [CoFH Core] (CoFH-Core-1.7.10.jar) 
	UCHIJAAAAAAAAA	colorfularmor{1.7.10-2.6} [Colorful Armor] (Colorful-Armor-Mod-1.7.10.jar) 
	UCHIJAAAAAAAAA	cookiecore{1.3.1} [Cookie Core] (CookieCore-1.7.10-1.3.1-7.jar) 
	UCHIJAAAAAAAAA	customnpcs{1.7.10} [CustomNpcs] (CustomNPCs_1.7.10.jar) 
	UCHIJAAAAAAAAA	customrecipes{4.72} [Custom Recipes] (customrecipes-1.7.10-4.7.jar) 
	UCHIJAAAAAAAAA	EnderIO{1.7.10-2.2.8.381} [Ender IO] (EnderIO-1.7.10-2.2.8.381.jar) 
	UCHIJAAAAAAAAA	exnihilo{1.34} [Ex Nihilo] (Ex-Nihilo-Mod-1.7.10.jar) 
	UCHIJAAAAAAAAA	extracells{2.2.73} [Extra Cells 2] (ExtraCells-1.7.10-2.2.73b129.jar) 
	UCHIJAAAAAAAAA	ThermalFoundation{1.7.10R1.0.0RC3} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.0.0RC3-56.jar) 
	UCHIJAAAAAAAAA	ExtraUtilities{1.1.0k} [Extra Utilities] (extrautilities-1.1.0k.jar) 
	UCHIJAAAAAAAAA	iChunUtil{4.0.0} [iChunUtil] (iChunUtil-4.0.0.jar) 
	UCHIJAAAAAAAAA	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) 
	UCHIJAAAAAAAAA	MoreFurnaces{1.3.9} [More Furnaces] (More-Furnaces-Mod-1.7.10.jar) 
	UCHIJAAAAAAAAA	Morph{0.9.0} [Morph] (Morphing-Mod-1.7.10.jar) 
	UCHIJAAAAAAAAA	OpenMods{0.7.3} [OpenMods] (OpenModsLib-1.7.10-0.7.3.jar) 
	UCHIJAAAAAAAAA	OpenBlocks{1.4.3} [OpenBlocks] (OpenBlocks-1.7.10-1.4.3.jar) 
	UCHIJAAAAAAAAA	secretroomsmod{@VERSION@} [The SecretRoomsMod] (Secret-Rooms-Mod-1.7.10.jar) 
	UCHIJAAAAAAAAA	wow{2.0} [Special Forces Mod] (Special-Forces-Mod-1.7.10.jar) 
	UCHIJAAAAAAAAA	stefinusguns{0.5.2} [New Stefinus Guns] (Stefinus Guns-0.5.2.jar) 
	UCHIJAAAAAAAAA	SteveMod{0.1.3} [SteveMod] (Steve-Mod-by-SuperYoshiGold-1.7.10.jar) 
	UCHIJAAAAAAAAA	Sync{4.0.0} [Sync] (Sync-Mod-1.7.10.jar) 
	UCHIJAAAAAAAAA	ThermalExpansion{1.7.10R4.0.0RC2} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.0.0RC2-129.jar) 
	UCHIJAAAAAAAAA	TConstruct{1.7.10-1.8.5.build957} [Tinkers' Construct] (TConstruct-1.7.10-1.8.5.jar) 
	UCHIJAAAAAAAAA	fallout{[1.8] v0.1.6} [The Fallout Mod] (The-Fallout-Mod-1.7.10.jar) 
	UCHIJAAAAAAAAA	TMechworks{0.2.14.100} [Tinkers' Mechworks] (TMechworks-1.7.10-0.2.14.100.jar) 
	UCHIJAAAAAAAAA	Translocator{1.1.1.6} [Translocator] (Translocator-Mod-1.7.10.jar) 
	UCHIJAAAAAAAAA	universalcoins{1.7.10-1.5.4} [Universal Coins] (Universal-Coins-Mod-1.7.10.jar) 
	UCHIJAAAAAAAAA	vrm{1.7.10=0.0.1} [Vulcan's Revenge] (Vulcans-revenge-mod-by-hoopawolf-1.7.10.jar) 
	UCHIJAAAAAAAAA	warpbook{2.0.null} [Warp Book] (warpbook-1.7.10_2.0.36.jar) 
	UCHIJAAAAAAAAA	YoutubeBlocksMod{6.5} [Youtuber Blocks Mod] (Youtuber-Blocks-Mod-1.7.10.jar) 
	UCHIJAAAAAAAAA	IguanaTweaksTConstruct{1.7.10-2.1.5.140} [Iguana Tinker Tweaks] (IguanaTinkerTweaks-1.7.10-2.1.5.jar) 
	UCHIJAAAAAAAAA	xan_personalizedRecipes{beta_1.7.10-2.1.0} [Personalized Recipes] (Personalized-Recipes-1.7.10_beta-2.3.0.jar) 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	OpenModsLib class transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[map_gen_fix:FINISHED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
	Class transformer null safety: all safe
	AE2 Version: stable rv2-stable-10 for Forge 10.13.2.1291
	CoFHCore: -[1.7.10]3.0.2-262
	ThermalFoundation: -[1.7.10]1.0.0RC3-56
	Mantle Environment: Environment healthy.
	ThermalExpansion: -[1.7.10]4.0.0RC2-129
	TConstruct Environment: Environment healthy.
	Stencil buffer state: Function set: GL30, pool: forge, bits: 8
	AE2 Integration: IC2:OFF, RotaryCraft:OFF, RC:OFF, BC:OFF, RF:ON, RFItem:ON, MFR:OFF, DSU:ON, FZ:OFF, FMP:OFF, RB:OFF, CLApi:OFF, Waila:OFF, InvTweaks:OFF, NEI:ON, CraftGuide:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 8; [EntityPlayerMP['DeathRules'/167900, l='Crash Landing', x=11.43, y=77.00, z=16.92]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by KingLemming** [comment]
This tells us *literally* nothing. It's not a crash log.
