### ISSUE TITLE
Redstone Furnace thaumium dup

### ISSUE THREAD

**Issue by seebs** [CoFH/Feedback#672]
Thaumium boots require 4 ingots to make. Redstone furnace smelts them into 5. I admit that this is immersive and fits my expectation for what happens when I start mixing magic and technology, which is that nothing makes sense anymore, but it might be considered a balance issue?

**Comment by KingLemming** [comment]
We aren't adding that recipe. Please report it to whoever is.

**Comment by KingLemming** [comment]
If you post a mod list, I may be able to help you figure out which mod it is.

**Comment by seebs** [comment]
I can post the whole mod list if needed, but I do note: If I don't have Thermal Recycling installed, the recipe is gone. If I add Thermal Recycling back, the recipe shows up.

**Comment by seebs** [comment]
Ahh, nevermind, ThermalRecycling isn't yours. Sorry to bug you!

**Comment by KingLemming** [comment]
Yeah, this is the problem with things being named "Thermal" - sorry I didn't suggest that outright, but glad we found the culprit!
