### ISSUE TITLE
[Suggestion] Tome of Knowledge should be able to be emptied in any kind of tanks

### ISSUE THREAD

**Issue by mcdodge34** [CoFH/Feedback#672]
Its just a suggestion here, I loved the experience rod from EnderIO and when I discovered this tome this morning I was in heaven, alas, the limited quantity of XP it can contains could be an issue, for now, its ok, but once I begin to play with mob spawners and a lot of stuff, I'll have so much XP that I won't know what to do with it, so if I find a way to convert it to mob essence for Industrial Foregoing, that could be interesting to be able to dump it into a tank to turn it into something more useful.

**Comment by KingLemming** [comment]
Just curious, did you actually try clicking on a tank with it? ;)

**Comment by mcdodge34** [comment]
Hum, I'm loaded in my world smelting some pulverized obsidian and lead right now, will try to see if I can do this quickly and report back.

**Comment by mcdodge34** [comment]
It does deposit 1 bucket into a stone drum, but not more, but on your portable tank, I got 20 buckets (its a basic one right now)

**Comment by KingLemming** [comment]
I'd argue that the Stone Drum maybe needs some better handling there. In 1.10+ it's quite doable to fill/drain an entire container (or as much as possible) in a single go.

Strictly speaking, this is how buckets work, it's just limited to a single bucket of fluid, obviously.

So given that, I'd argue that TE tanks have correct behavior and apparently not everything else does.

**Comment by mcdodge34** [comment]
Hum, I'm not in RWThema shoes there, but I love the top tier drum with the demon ingots, I'll figure something out with the fluiducts to drop the XP in one from out of your portable tank to store my xp for now. Should work fine, now I need to test if I can convert this liquid to mob essence or not, but I guess its on Industrial Foregoing side to decide of this.

**Comment by KingLemming** [comment]
BTW, you might want to look into the Insightful Collector. It'll automatically collect XP and output it in fluid form.

**Comment by mcdodge34** [comment]
Will surely take a look at it, but if I can't convert it to mob essence, (I need to test in creative with all the usual, I remember the time of MFR, if I stepped on a sewer my xp would convert in mob essence so its something I need to try in IF) I'm setting up my first spawner with cursed earth to gather mob essence at the moment. Will also do other types of spawners eventually, my goal is to try most of the available methods to kill the mobs automatically in this pack, will need an xp collector eventually, apart from the one in Mob Grinding Utilities that also has its own experience fluid system and collector in a 7x7x7 radius.

**Comment by KingLemming** [comment]
Gonna close this out since I think it's basically already in, but I'll remember to poke Tema about his drum handling.

**Comment by mcdodge34** [comment]
Thanks, this works fine already with your own tanks, and dumping your tank in a drum works fine. I prefer to never keep my xp on myself whenever I can, just had problems before by loosing 217 levels because of a bug so I learned to dump it off in whatever system I could.
