### ISSUE TITLE
Fluiducts white/black list not working right

### ISSUE THREAD

**Issue by mokey95** [CoFH/Feedback#673]
I'm playing in the AG2 instance and, as the title says, the white/black list isn't working
Screens below:
![2015-07-09_20 06 44](https://cloud.githubusercontent.com/assets/5108974/8633807/d2c8bb34-27d4-11e5-8c6b-1dd9ea6e6f08.png)
![2015-07-09_20 07 13](https://cloud.githubusercontent.com/assets/5108974/8633808/d2c98e4c-27d4-11e5-8840-fb221747a3f5.png)
![2015-07-09_20 07 52](https://cloud.githubusercontent.com/assets/5108974/8633809/d2ccacda-27d4-11e5-8eaf-6cf39b733ad4.png)

**Comment by KingLemming** [comment]
Can't replicate this I'm afraid. They're working correctly for me.

**Comment by mokey95** [comment]
it's the latest with the Extra utilities rolled back to 1.2.6

**Comment by silverwind** [comment]
Also seeing this, here are the versions in the pack:

````
CoFHCore-[1.7.10]3.0.3B2-294
CoFHLib-[1.7.10]1.0.3B2-169
ThermalDynamics-[1.7.10]1.1.0B2-149
ThermalExpansion-[1.7.10]4.0.2B2-210
ThermalFoundation-[1.7.10]1.2.0B1-95
````

It looks to be ignoring the filter completely on a smeltery, pouring out everything.

**Comment by KingLemming** [comment]
This may be something with the Smeltery, though I don't really understand it.

Seriously, it doesn't happen for me:

![](https://puu.sh/iVlzW/a93f6dcab9.png)


![](https://puu.sh/iVlzB/9f09eb679c.png)

**Comment by KingLemming** [comment]
Can either of you make it happen with things other than the Smeltery?

**Comment by mokey95** [comment]
i'm trying right know, just waiting to load the instance

**Comment by mokey95** [comment]
Confirmed that the same setup ignores the white-list
Screens below
![2015-07-11_17 29 46](https://cloud.githubusercontent.com/assets/5108974/8634492/aa47ac2e-27f2-11e5-8a73-ea13f90397a8.png)
![2015-07-11_17 30 01](https://cloud.githubusercontent.com/assets/5108974/8634493/aa4a21de-27f2-11e5-8ccb-27fb4ac8e88b.png)
![2015-07-11_17 30 11](https://cloud.githubusercontent.com/assets/5108974/8634494/aa4d81c6-27f2-11e5-9125-743fe4f03f4c.png)

**Comment by silverwind** [comment]
Take:

- 1 bucket Molten Copper (4812:2)
- 1 bucket Molten Tin (4812:3)

Put tin into one tank, add a servo and pipe to another empty tank. Set servo to whitelist on copper. When activating the servo, it still drains the tin. It looks like it is ignoring the Sub-ID (:2 vs. :3). This did work correctly before in the 1.0.0 version of TD.

**Comment by KingLemming** [comment]
I just did literally that.


![](https://puu.sh/iVmRp/5013e2090a.png)


![](https://puu.sh/iVmRI/98c6823800.png)


Sorry, but it's working correctly.

**Comment by mokey95** [comment]
could the buckets from tinkers or iguana be the culprits?

**Comment by silverwind** [comment]
Really strange. I was using using regular TC buckets. Maybe some other mod is interfering?

**Comment by mokey95** [comment]
Extra utilities was having an issue with the pulverizers but rolling back should have fixed any problems

**Comment by dzdod1** [comment]
I am able to replicate this in AS2 and with just all the thermal mods installed (meaning this isn't a mod conflict). I tested with water, lava, and resonant ender.

**Comment by KingLemming** [comment]
Check with the new versions and let me know. I definitely couldn't make this happen.

**Comment by mokey95** [comment]
do we update the core too?

**Comment by dzdod1** [comment]
It's been fixed in the new version to my tests.

**Comment by mokey95** [comment]
dzdod, did you try with the new Extra utils?

**Comment by dzdod1** [comment]
I manually updated AS2's mods. I updated CoFH Core, Lib, and all three of the thermal mods. I also switched back to Extrautils 1.2.8 since that has been reported as being fixed in this version. The filters on the servo are working.

**Comment by mokey95** [comment]
ok, then i guess this can be closed
