### ISSUE TITLE
[Suggestion] Special logic for /cofh killall item

### ISSUE THREAD

**Issue by OrdinatorStouff** [CoFH/Feedback#674]
I have found that some of my fellow server administrators are using the cofh killall command to clear dropped item entities. I have tried to spread the word that `/cofh killall item` is not just killing items but any other entites with "item" in it's name (notably vanilla item frames, possibly other modded entities).

Would it be possible to hardcode a special case for `/cofh killall item` to only kill minecraft item entites? The same thing as `/kill @e[type=item]` ? I have seen `cofh killall item` mentioned in other places as well when someone asks about how to kill dropped items so I fear it's become a bit of 'tribal knowledge' that is missing awareness of the fact that it kills more than just *items*

**Comment by KingLemming** [comment]
I'm not a fan of special casing, but I'm willing to consider it.

**Comment by KingLemming** [comment]
Eh, why not.
