### ISSUE TITLE
Crash when starting Minecraft with CoFH Core

### ISSUE THREAD

**Issue by ThePuzzlemaker** [CoFH/Feedback#674]
Minecraft keeps crashing (not responding and closing) whenever I start Modded Minecraft with CoFH Core installed.

Log: http://pastebin.com/Ndh5JztS

**Comment by KingLemming** [comment]
Yeah, this doesn't tell us anything, and if you read the README for this issue tracker, it's *definitely* on your end. Go through the steps as stated and then if you can get an actual crash log, take it to IRC please and we'll try and help you.

As is, this is tech support and not an actual issue I'm afraid.
