### ISSUE TITLE
Suggestions for Thermal Expansion

### ISSUE THREAD

**Issue by DrakoAlcarus** [CoFH/Feedback#675]
I'm a little stupid on the info of the location in which I place suggestions for this amazing mod, so hopefully placing it here won't be much of an annoyance. Sorry in advance!

Now, there are a bunch of things I have been wanting in this mod, so I'll list them.
- A pump for lava. Plain and simple, I want an Rf powered device that draws lava up to be used by my machines and other purposes.
- A mining drill block that drills Vertically, or horizontally based on configuration and 1 x 1 to 5 x 5 based on drill tip (Also, a drill head that does 1 x 3, like the flux infused pickaxe). At max, stops at 100 blocks, and requires 1000mb of tectonic petrotheuim to run for the max distance. Also, mining speed varies on certain augments, and can add a silk touch augment and fortune, both of which cannot be used with each other.
- A device that goes on item pipes that counts how many of that certain item passes through, and displays them on a monitor. Same with energy and fluid.
- A disassembler that can take apart certain items, like tools and machines.
- An elevator block, crafted using energized glowstone or zephyrean aerotheum in it's crafting. I honestly don't really know if that will even be helpful.

Let me know what you think. I hope these might get implemented, so I thank you for reading.

Also, another important thing I would like to recommend: and inventory lock option in the satchels. With the click of a button, satchels become undroppable, saving them from being accidentally thrown into lava.

**Comment by RoloEdits** [comment]
I can get behind these ideas.

**Comment by DrakoAlcarus** [comment]
What do you mean?

**Comment by RoloEdits** [comment]
as in I support the ideas you listed :)

**Comment by Tora-B** [comment]
It's a colloquialism meaning that they like your ideas, and would support them.

* Your first suggestion is already covered by #277.
* An efficient mining device would be nice, and Tectonic Petrotheum does seem like an obvious choice, but I don't think the details you've suggested feel very TE.
 * That's an awfully specific dynamo, requiring a lot of slots or inputs. The existing dynamos are quite flexible, and support a variety of fuels. Uses for the new elemental substances would be nice though.
* Counting things that pass through ducts has been suggested before, though I don't think there's an issue here on GitHub for it. The multimeter in past versions of TE would give you some information about ducts, and I don't know if there's a specific reason that wasn't reimplemented.
* Also #277. KL said that the future pump would be 2-way [in a comment there](https://github.com/CoFH/Feedback/issues/277#issuecomment-98068412).
* Pulverizers can reclaim some of the materials from the low-tier cells and ducts. It would be the obvious place to add more recycling, if they wanted to do it.
* I would love an elevator system. I've looked at a bunch of mods that add elevators, and didn't like any of them -- either too flaky and unreliable, or too bulky and complicated. I just want a faster way to go up and down safely than ladders. Impulse and Translocation Plates have a lot of potential to be used that way, but Zephyrean Aerotheum seems like it could be applied to such a purpose.
* As for satchels, I imagine cancelling the drop event probably isn't too hard (unless Minecraft weirdness), and that deciding on a good interface for the behavior would be the tough part.

**Comment by DrakoAlcarus** [comment]
Thank you for the feedback.

For the interface, it could be simple. Just like the security buttons, it should be a tab the secures the item into your inventory. I lost a resonant loot bad to lava, because I tried to dump cobble out of my inventory. It had so much valuables...

**Comment by DrakoAlcarus** [comment]
@KingLemming What do you think?

**Comment by aking4125** [comment]
I support the pump idea to pump any liquid from any mod and extract it somewhere. Idk about everything else but they seem cool.

**Comment by KingLemming** [comment]
Pump is happening, yeah. It will be reversible.

Mining drill is something I've considered, but no specifics.

Dynamo is a no.

More stuff for ducts is a maybe. Fluid and energy monitors are probably not possible.

Disassembler won't be, sorry. Too much potential for broken stuff there. The pulverizer and the sawmill already support this in a limited capacity.

Elevator is a maybe. I don't really see a super pressing need for it.

The satchel thing..ehh. If your satchel is secured, it's already lava proof.

**Comment by RoloEdits** [comment]
What do you mean secured?

**Comment by KingLemming** [comment]
Like most things in TE, you can add a Signalum Security Lock to it.

**Comment by RoloEdits** [comment]
And that will stop it from being destroyed in lava?
I wish I knew that 2 days ago.
Thanks for that Information it's definitely something ill be doing from now on.

**Comment by KingLemming** [comment]
Yup. Anything which is secured becomes invulnerable as an item. :)

**Comment by DrakoAlcarus** [comment]
WHAT! I seriously wish I knew. Does it despawn?

Anyway, I thought my dynamo idea was stupid, anyway. I just wanted a use for all the elements.

For the ducts,I want to be able to easily count all the items my machines produce.

For the disassembler idea, can I get an example of what would be broken? Imagine I came back from the nether with a buttload of golden swords. Why not break them down?Of course, if they are damaged, I'd get a net loss... only tools and certain items can be broken down. Not everything.

**Comment by KingLemming** [comment]
Machines can have augments inside them; but there's no great way to scan the inventory when it's being destroyed. So either you return too many things or not enough.

**Comment by DrakoAlcarus** [comment]
No no no... I mean, as the item passes through a duct with a device on it, the device with count how many of the white listed item is passing.

**Comment by DrakoAlcarus** [comment]
Sorry, got confused.

**Comment by DrakoAlcarus** [comment]
I see what you mean...Perhaps the disassembler won't except machines, unless they are empty? I don't too many gold swords...

**Comment by KingLemming** [comment]
There's already a mod for this:
http://www.curse.com/mc-mods/minecraft/229666-thermal-recycling

**Comment by DrakoAlcarus** [comment]
I had installed that mod before, but deleted it, thinking it was causing my game problems. I forgot about it.

I'll test it out, then.

**Comment by DrakoAlcarus** [comment]
It's definitely not what I am looking for. Unlike the screenshots, everything is broken down into scrap piles instead. I checked the config if I can find a way to change this, but no. I can't, unfortunately.

I did, however, find the Deconstruction mod. Unfortunately, the recipes don't always work. Especially for the covers.

**Comment by Oxosorrel** [comment]
If you feel adventuresome, creative use of minetweaker can get the effect you want. http://minetweaker3.powerofbytes.com/wiki/ModTweaker:Thermal_Expansion_Support Make whatever reciepes you like. Pulverize leadstone conduit, get 2 lead powder and a chance for redstone. Sawmill a redstone furnace, get bricks and chance for a gear. Magma crucible melt a tesseract down into resonent ender. The limit is your creativity and what fits your theme.

Additionally not every pack has the same reiepes. So not everyong breaks down into the same stuff.  I heavily tweaked my personal server using minetweaker, so my TE machines incorporate metallurgy4's crazy number of metals in its manufacture, and I wouldn't expect this team to know how to deconstruct my crazy ideas. Nor would I think they would code a way to deconstruct my Eximite metal reciepe for tesseracts (ore only found in The End, gating tesseracts behind the end, cuz I'm mean)

**Comment by DrakoAlcarus** [comment]
I could adjust it for tools and covers.

**Comment by Oxosorrel** [comment]
Yup and you have options in how you come up with your mine tweaking. Toss a multimeter in a saw mill, get a gear and a chance of a coil, pulverizer it and get copper dust and maybe redstone, melt it in a crucible and get lead. Go as nuts as you want with scripting minetweak recipes.

**Comment by DrakoAlcarus** [comment]
I'll see.

**Comment by DrakoAlcarus** [comment]
Honestly, I'd rather it be built in. I believe the genius that created this fantastic mod can somehow implement this idea.

**Comment by DrakoAlcarus** [comment]
Never mind... the thermal recycling recipes use other machines. Sorry for the inconvenience.

**Comment by DrakoAlcarus** [comment]
So, let me know if you are adding a pump block, so I know when the update is coming out. I want to record a game play of my mod pack, and take Buildcraft out.

**Comment by DrakoAlcarus** [comment]
Alright... I am an idiot. I never noticed the Composition Core in Thermal Recycling... now I use the mod all the time. Next time, I should not rush mod exploration.
