### ISSUE TITLE
Really minor cosmetic issue between Mek induction matrix and CoFH Fluxducts

### ISSUE THREAD

**Issue by utoc** [CoFH/Feedback#676]
As the title says, this is a painfully minor cosmetic issue.  Mekanism has a multiblock induction matrix which has an input and output port for sending/receieving power.  Connecting a fluxduct to this block, even with a chunkloader on duty at the ready, will cause the fluxduct to appear disconnect after you leave the area/dimension and then return.  The connection appears to be severed but, in fact, it rf has no issue travelling along it.  I probably did a horrible job explaining this so here is a pretty picture to do what my words cannot:

Cryo-Fluxduct: https://i.imgur.com/dUdXcOb.png

Redstone Fluxduct: https://i.imgur.com/yhNAdRB.png

Running CoFH 3.0.3B2-294, Thermal Dynamics 1.1.0B2-149 and Thermal Foundation 1.2.0B1-95
FML 1448.  [Full modlist here](https://www.reddit.com/r/BBQSauce/wiki/modlist)

I have tested this with and without FastCraft with no difference.

Thank you so much for being awesome!

**Comment by KingLemming** [comment]
Unfortunately, I'm pretty sure this will have to be resolved on Mekanism's end. No other multiblock structure has this issue. I'll investigate though.

**Comment by utoc** [comment]
Let me know when you're done looking and I'll post a ticket on Mek's tracker.  Thanks for taking a moment.

**Comment by RoloEdits** [comment]
I Have The Same Problem As Well.

I Think This Is Caused By The Multi Block Capacitor Being Reformed Every Time. If You Try Logging In When Your Looking At The Matrix You Might See Red Particles Form A Little After Everything Else Seems To Load. This Also Make Working With Computer Craft More Tedious Because The Structure Is Not Formed At Startup Fast Enough And Can Uniform During Use Causing Errors. But I Don't Really Know Just Speaking Off Experience Of Working With It.

**Comment by KingLemming** [comment]
What's up with the capitalization? I mean seriously.

But yes, I believe you are correct, and the capacitor does not correctly inform adjacent blocks once it has fully reformed.

**Comment by RoloEdits** [comment]
I apologize, it's just I don't like the way lowercase letters look.

I'll be more considerate of other people and type normally :)

Is there any other fix besides either leaving it there and just have it look funny or having to cause a block update each time?

**Comment by KingLemming** [comment]
The fix is telling Mek about it. Sorry, we can't do anything on our end that really makes sense.

**Comment by RoloEdits** [comment]
Thank you for your help
