### ISSUE TITLE
Satchels dupe bug

### ISSUE THREAD

**Issue by skydark** [CoFH/Feedback#677]
Mod list:
* CoFHCore-[1.7.10]3.0.3B3-301.jar
* ThermalExpansion-[1.7.10]4.0.2B3-215.jar
* ThermalFoundation-[1.7.10]1.2.0B2-100.jar

How to reproduce:
1. fill your inventory with stones or anything, but only leave two slots empty;
2. put one diamond in your inventory, and a satchel in another slot;
3. put a full stack of diamonds in your satchel(any tier);
4. open your satchel, shift-left click the diamonds in your satchel;
5. now you have one stack of diamonds in your satchel, but also another stack of diamonds in your inventory.

**Comment by KingLemming** [comment]
Can't reproduce this at all. Please provide a video.

**Comment by skydark** [comment]
https://youtu.be/nGnEEtbedfQ
shift-left click
