### ISSUE TITLE
Console Spam

### ISSUE THREAD

**Issue by BuckitHead** [CoFH/Feedback#678]
After updating to latest updates today, The server console once startup is complete is getting spammed with: [Server] info 100.

Removed the updates and everything is normal again.
Updated to files below 
CoFHCore-[1.7.10]3.0.3B3-301
CoFHLib-[1.7.10]1.0.3B3-173
ThermalDynamics-[1.7.10]1.1.0B3-156 
ThermalExpansion-[1.7.10]4.0.2B3-215
ThermalFoundation-[1.7.10]1.2.0B2-100

**Comment by KingLemming** [comment]
It doesn't hurt anything. You can leave it.

**Comment by KingLemming** [comment]
Redownload please. :)

**Comment by BuckitHead** [comment]
Redownload all 5?

**Comment by KingLemming** [comment]
TE and TF, once they're approved. Curse is slow. -_-

**Comment by BuckitHead** [comment]
Ok, Thank you very much..

**Comment by BuckitHead** [comment]
Problem Fixed... Thanks again for the fast fix on this..
