### ISSUE TITLE
[Suggestion] Config option to disable side modularity

### ISSUE THREAD

**Issue by racer290** [CoFH/Feedback#679]
So, I am currently creating an expert pack for Minecraft 1.12.2. I have looked for a config option to disable the machines' and devices' side modularity in Thermal Expansion to make automating them more interesting, but i didn't find one. It would be nice to see have such a config option, preferably alongside an option do disable automatic input and output aswell.

Thermal Expansion version: 5.3.7.27

**Comment by KingLemming** [comment]
I'm willing to consider that, but I feel like the "proper" side access in such a case would instead be open and not the defaults that machines typically have.

**Comment by racer290** [comment]
Yes, that's a good idea. Can't you change it via the stored NBT anyways
when crafting the machine?

Am 04.12.2017 01:40 schrieb "KingLemming" <notifications@github.com>:

**Comment by KingLemming** [comment]
Not exactly, no.

**Comment by KingLemming** [comment]
Marking as under consideration, but might be moved into "unpossible" based on if it'd break existing worlds. And it *could* maybe possibly do that. So have to see.

**Comment by racer290** [comment]
Is this still under consideration? Nothing seems to have happened in the last two weeks. I'm also willing to test things myself, but I feel that I'm not really into the necessary parts of the code. Would be nice if you could point me to the most important classes here if you stopped work on this yourself.

**Comment by KingLemming** [comment]
Yes. I'm on vacation.

**Comment by racer290** [comment]
Okay, nothing has happened in the last month. According to the label, this is still under consideration, but I'm not really sure whether this is the case. If this issue should be closed due to a problem of time, I am still willing to do things myself, but I would really appreciate some kind of status info here.

**Comment by KingLemming** [comment]
It's very much a non trivial thing. I've actually tried an implementation but was unhappy with it.

Doing this properly involves essentially rewriting machines entirely.

**Comment by KingLemming** [comment]
Okay, so I've revisited this and frankly there's not a way to do it that doesn't feel like a giant kludge. It's just inelegant - the blocks were designed to be reconfigurable and without that, they feel terrible.

What I have done is provide options to disable auto-input and auto-output.
