### ISSUE TITLE
Crash when breaking portable tank with a tool

### ISSUE THREAD

**Issue by SubsterNL** [CoFH/Feedback#68]
Crash.. In this case when I killed it with a AIO tool. Running the SKyfactory 3 pack with a few updated mods.

`---- Minecraft Crash Report ----

WARNING: coremods are present:
  literalascension (literalascension-1.10.2-1.0.0.4.jar)
  Brandon's Core (BrandonsCore-1.10.2-2.1.4.92-universal.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.5.6.224-universal.jar)
  ForgelinPlugin (Forgelin-1.2.0.jar)
  LoadingPlugin (RandomThings-MC1.10.2-3.7.7.jar)
  LoadingPlugin (ResourceLoader-MC1.9.4-1.5.1.jar)
  AppleCore (AppleCore-mc1.10.2-2.1.0.jar)
  NWRTweak (redstonepaste-mc1.9.4-1.7.4.jar)
  BookshelfLoadingPlugin (Bookshelf-1.10.2-1.4.3.338.jar)
  ChiselCorePlugin (Chisel-MC1.10.2-0.0.7.7.jar)
  RebornCoreASM (RebornCore-1.10.2-2.13.1.104-universal.jar)
  SurgeLoadingPlugin (Surge-1.10.2-1.1.0.66.jar)
  CoFH Loading Plugin (CoFHCore-1.10.2-4.0.2.150-universal.jar)
  NEICorePlugin (NotEnoughItems-1.10.2-2.1.3.201-universal.jar)
  SFRCore (SolarFluxReborn_1.10.2-2.4r.jar)
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.5.3-anarchy.jar)
  CoreMod (Aroma1997Core-1.9.4-1.1.1.1.jar)
  Default Options (DefaultOptions_1.10.2-6.1.5.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.65-beta.jar)
  ShetiPhian-ASM (shetiphiancore-1.10.0-3.3.6.jar)
  llibrary (llibrary-1.7.4-1.10.2.jar)
  AppEngCore (appliedenergistics2-rv4-alpha-11.jar)
  TransformerLoader (OpenComputers-MC1.10.2-1.6.1.6.jar)
  BiomeTweakerCore (BiomeTweaker-1.10.2-2.1.230.jar)
Contact their authors BEFORE contacting forge

// I just don't know what went wrong :(

Time: 3/9/17 12:02 PM
Description: Tesselating block in world

java.lang.NullPointerException: Tesselating block in world
	at cofh.thermalexpansion.render.RenderTank.handleState(RenderTank.java:114)
	at codechicken.lib.model.blockbakery.BlockBakery.handleExtendedState(BlockBakery.java:131)
	at cofh.thermalexpansion.block.storage.BlockTank.getExtendedState(BlockTank.java:196)
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:80)
	at codechicken.lib.render.block.CCExtendedBlockRendererDispatcher.func_175018_a(CCExtendedBlockRendererDispatcher.java:54)
	at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:290)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(ChunkRenderWorker.java:119)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(ChunkRenderWorker.java:47)
	at java.lang.Thread.run(Unknown Source)

`

**Comment by covers1624** [comment]
Can i get your full crash log please?

**Comment by KingLemming** [comment]
Yeah this isn't a thing that seems to happen - just tested with a pickaxe. We're going to need more details.

**Comment by KingLemming** [comment]
I've put in something that should catch for this but frankly this doesn't seem to even happen in a properly functioning Minecraft environment.

**Comment by SubsterNL** [comment]
Ok. Thanks guys.. So I assume you don't need my log now.

Awesome job on bringing back TE from the dead :)
