### ISSUE TITLE
Serverside error in ThermalExpansion with OpenPeripherals

### ISSUE THREAD

**Issue by evan1026** [CoFH/Feedback#68]
Using version [1.7.10]4.0.0B8-23, trying to wrap energy cells using openperipherals causes an error only on a mulitplayer server. By downgrading to [1.7.10]4.0.0B7-21, I was able to get the server to print out [the stacktrace](http://pastebin.com/WfbtCYyk). This bug has been submitted multiple times to the open peripherals repo ([here](https://github.com/OpenMods/OpenPeripheral/issues/210) and [here](https://github.com/OpenMods/OpenPeripheral/issues/215)), but I haven't seen it here, and, since the error is on the thermal expansion side, I figured I should report it.

**Comment by KingLemming** [comment]
We use methods that properly get around this. The fact that OpenPeripherals is actively hacking our classes to try and do things...well that's bad.

I don't foresee us changing this, since it's not actually a bug.

**Comment by skyboy** [comment]
Fixed in dev a while ago.

**Comment by evan1026** [comment]
@skyboy Any idea when that might get released? Not trying to rush you, just curious.

**Comment by ZeldoKavira** [comment]
@evan1026 All dev builds are pushed to curseforge instantly. These sometimes break things to make sure to backup. There is no set time for a full release however.

**Comment by skyboy** [comment]
@evan1026 no ETA for a release of TE
