### ISSUE TITLE
Suggestion: Configurable Baubles Slot For Lexicon

### ISSUE THREAD

**Issue by RoloEdits** [CoFH/Feedback#681]
It would be very nice if we could choose which baubles slot to use such as the amulet slot because I always have my botania sash equipped in my belt slot.

**Comment by KingLemming** [comment]
Ehh, I dunno. Honestly, you should just leave it in an inventory slot. It works fine there, and there are far better Baubles to use.

**Comment by RoloEdits** [comment]
Yeah that is what i'm doing now and when you say there are far better baubles to use what do you mean.like better then the sash?

And thank you for you help as always :)

**Comment by KingLemming** [comment]
No, I mean for other slots. It doesn't matter which slot the Lexicon goes into because it works in the Inventory just fine. There are baubles that have to be equipped and those are better to use as baubles.

**Comment by RoloEdits** [comment]
Oh OK, and your right the more I think about it the more it makes sense just to keep it in your inventory.

**Comment by KingLemming** [comment]
I'm just gonna leave it as belt. Ideally I'll provide far more interesting things to go into Bauble slots anyways.
