### ISSUE TITLE
Blizz powder is not craftable

### ISSUE THREAD

**Issue by Kazzamkablam** [CoFH/Feedback#682]
I found out that with latest version despite NEI saying it's craftable trying to place snowball in fluid transposer results it rejecting the item and you being unable to craft blizz powder with snowball + redstone method.

Versions:
forge-1.7.10-10.13.4.1490
CoFHCore-[1.7.10]3.0.3B3-301
RedstoneArsenal-[1.7.10]1.1.1B1-85
ThermalDynamics-[1.7.10]1.1.0B3-156
ThermalExpansion-[1.7.10]4.0.2B3-216
ThermalFoundation-[1.7.10]1.2.0B2-101

**Comment by Tora-B** [comment]
Are you sure you're putting the snowball the right slot? I just tested it on the versions you list (except the forge version), and it works fine.

**Comment by Kazzamkablam** [comment]
tested with all possible configurations still does it

**Comment by Tora-B** [comment]
![2015-07-12_03 48 17](https://cloud.githubusercontent.com/assets/11331588/8637320/df0781f4-2848-11e5-8934-5dadd0f81fac.png)

**Comment by KingLemming** [comment]
Sorry, but you're just incorrect on this one. You *may* have a modpack removing it, however.

**Comment by Kazzamkablam** [comment]
I'm going to do more testing, definitely not modpack removing it as it's custom pack, if it's not TE then it has to be something interfering with TE.

**Comment by ate0ate** [comment]
Agricraft has no intention of fixing this since all it does is add an ore dict tag for snowballs. Any ideas?

**Comment by Tora-B** [comment]
Yeah. Update to the latest release of TE on Curse (4.0.3B1-218). The changelog says that this should be fixed.
