### ISSUE TITLE
Crash when right clicked Lexicon

### ISSUE THREAD

**Issue by KristjanKr** [CoFH/Feedback#683]
http://paste.ee/p/bnxGU , as soon as i tried to open it ( it showed the lexicon gui for a sec ) and then just crashed.

**Comment by KingLemming** [comment]
This isn't us, sorry. It's a misconfig of some sort with your pack or world.

**Comment by KingLemming** [comment]
Turns out it's vanilla. Empower the Lexicon once first and this won't happen. I have a silly hack to prevent this stupidity from happening in the future.

**Comment by codewarrior0** [comment]
Just now got this crash with these versions (as seen in Project Ozone 2):

```
CoFHCore-[1.7.10]3.1.3-327
CoFHLib-[1.7.10]1.1.2-182
ThermalFoundation-[1.7.10]1.2.5-115
ThermalExpansion-[1.7.10]4.1.3-246
Forge Mod Loader version 7.99.40.1614
```

Crashed the game in single-player upon right-clicking air with a newly crafted Forge Lexicon. After restarting the game, the Lexicon works normally.

[Full crash log](https://gist.github.com/codewarrior0/d53d84e41e0fc1d3ca1d7478bb867f50)
