### ISSUE TITLE
Incompatability with Agricraft

### ISSUE THREAD

**Issue by Kazzamkablam** [CoFH/Feedback#684]
https://github.com/InfinityRaider/AgriCraft/issues/276

#682

Posting this here again since they told to report issue here instead of their github as they are not fixing it.

Basically thermal expansion fluid transposer refuses to accept snowballs with latest version of agricraft installed (1.4.1)

**Comment by KingLemming** [comment]
You could have commented in the prior issue and I would have reopened it. Suffice it to say, this isn't super high priority but I'll get around to figuring out what's going wrong.
