### ISSUE TITLE
[Suggestion] Phytogenic Insolator Recipe for EvilCraft

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [CoFH/Feedback#684]
Would be nice to be able to use the blood sapling from https://github.com/CyclopsMC/EvilCraft in the Phytogenic Insolator, however, for balance purposes the fluid should be Evilcraft's blood.

**Comment by KingLemming** [comment]
The fluid is limited to water only and I won't be changing that. What do blood saplings do, exactly?

**Comment by KingLemming** [comment]
BTW I'm not averse to it, I'd just like to know the properties of the tree, since they apparently do something special if you feel that they need balancing.

**Comment by Unrepentant-Atheist** [comment]
The wood logs can be squeezed in the Forestry sqeezer for blood.

The tree itself doesn't drop saplings. For that you gotta infuse it with blood to get a blood sappling, which is why I had blood as fluid in mind. But if it's too much then water is fine too.

Blood saplings grow blood trees, which drop blood logs, which can be squeezed in Forestry's squeezer for blood.

**Comment by Unrepentant-Atheist** [comment]
Yes, exactly.

**Comment by Unrepentant-Atheist** [comment]
Damn, nice. Already implemented. But I haven't been using the Arboreal Extractor when I posted this, now that I have, the extractor makes much more sense. Just place it near an undead tree and allow it slowly to extract blood, just like Sap and Resin.

**Comment by KingLemming** [comment]
Yeah, already did that.

**Comment by Unrepentant-Atheist** [comment]
You're the best, Dr. Lemming! Much obliged!

**Comment by tyler489** [comment]
Blood saplings drop dead bushes dont they. Instead of itself. If so would it be possible to do so in the infuser to?

**Comment by KingLemming** [comment]
Yes, and that's what happens.

**Comment by tyler489** [comment]
Wow fast response will it take water or blood. I know you said you didnt want to allow other liquids.
