### ISSUE TITLE
Laminar Ducts Flickering

### ISSUE THREAD

**Issue by RoloEdits** [CoFH/Feedback#685]
I first noticed it with life essence but its even more noticeable with water.

![2015-07-12_05 36 21_2](https://cloud.githubusercontent.com/assets/12489689/8637776/25fb7408-2858-11e5-80ec-af92f35e9c7a.png)

![2015-07-12_05 36 22](https://cloud.githubusercontent.com/assets/12489689/8637777/2d0ac820-2858-11e5-95cb-d5fe48955ff0.png)

![2015-07-12_05 36 23](https://cloud.githubusercontent.com/assets/12489689/8637778/344927a8-2858-11e5-9fa9-da2fe156d39c.png)

**Comment by KingLemming** [comment]
Those screenshots don't really show much.

If you mean that the textures are z-fighting, then there are config options for that. :)

**Comment by RoloEdits** [comment]
Yeah your right the screen shots looked a lot better on my end when you can flip back and fourth.

Oh OK i didn't know that's what the config option was for. 

Thank you very much i appreciate it greatly :)

**Comment by KingLemming** [comment]
So this is resolved or you had a different issue other than z-fighting?

**Comment by RoloEdits** [comment]
I'm so sorry I couldn't get back to you till now. Unfortunately its still flickering after turning both values in the Thermal Dynamics Client.cfg from .99 to .5 the water rendering in this case got smaller but still flickers. 

I attempted to take a screen shot but that failed miserably.The flickering happens so fast but, if you saw it you would say "wow, that is flickering".

ill try do a video of it if you would like me to.

**Comment by RoloEdits** [comment]
http://youtu.be/EFcKAx91LRs

**Comment by RoloEdits** [comment]
and also checked it out with other fluiducts and its the same.

**Comment by KingLemming** [comment]
That video is private. You also seem to be the only one reporting this. :/

**Comment by RoloEdits** [comment]
I'm sorry i must have hit the scroll wheel on accident after i put it on unlisted.
It's strange because it happened after I updated to the most recent version yesterday and i don't think it was happening before because this is very noticeable.

if you want to try the video again i changed the settings to unlisted.

**Comment by KingLemming** [comment]
I did change some lighting code on the Fluiducts. *However* - I actually *fixed* a lighting issue, so what I'm wondering now is if you have another tile in your world that messes things up.

Can you make this happen in a world with only Fluiducts placed?

**Comment by RoloEdits** [comment]
You were right it's not the ducts it something else causing it.How would I go about figuring out what is causing it?

**Comment by RoloEdits** [comment]
When trying to figure out what is causing it iv'e been placing blocks and iv'e found that when placing other ducts from TD it cause the same flickering but only after its just placed. May i ask what type of update is going on when placing a duct?

**Comment by KingLemming** [comment]
place things til you find the culprit :/ What other tiles are in the same world?

I'll see if I can prevent it on our end by forcing certain render calls.

**Comment by RoloEdits** [comment]
iv'e found it its the harvester from MFR every time it harvests something the ducts flicker and since I have a torcherino its harvesting a lot quicker and causing a lot of flickering.

**Comment by KingLemming** [comment]
Interesting.

**Comment by RoloEdits** [comment]
that's interesting i was getting it and then tested just the torcherino to see if it was that and after it didnt flicker I placed back the XP bush from tinkers because that's what i have in my normal world it didn't do it any more. still testing more.

**Comment by RoloEdits** [comment]
and after that placing ducts didn't cause the flickering either....maybe it fixed itself??

**Comment by RoloEdits** [comment]
actually i think it might the the essence berry bush when I pick them manually it flickers as well.

**Comment by RoloEdits** [comment]
iv'e just tried with the copper bush and its the same flickering when harvesting

**Comment by RoloEdits** [comment]
its also doing it when wheat is growing

**Comment by RoloEdits** [comment]
i hope i was helpful. sorry for all the random info :/

**Comment by KingLemming** [comment]
Let me know if you still get this with the update please.

**Comment by RoloEdits** [comment]
Yes, that seems to have fixed it :)
Thank you very much for fixing it so fast.
