### ISSUE TITLE
[Suggestion] Covers working with other mods.

### ISSUE THREAD

**Issue by EvilBastard** [CoFH/Feedback#686]
Covers are awesome. I love them. What I would like to see is if the Thermal covers could work with mods such as AE2, Refined Storage,  or other mods that use some sort of pipe, conduit, wire, or what not that doesn't use up the entire block space.

**Comment by Tahakk** [comment]
Most of the the mods have their own version of covers. AE2 have their own and RS is working with that _miniblock_ mod that I cannot remember name of.

**Comment by KingLemming** [comment]
This is pretty unlikely and borderline impossible.
