### ISSUE TITLE
[Thermal Foundatation] Blitz Projectiles (Graphics) Don't Despawn

### ISSUE THREAD

**Issue by roomon1** [CoFH/Feedback#686]
While running a server with the below mods/versions, the projectiles shot by Blitz' do not despawn after reaching maximum range.  Instead, they travel until their maximum range and then stop in mid-air.  Once stopped, they appear to simply sit there forever.

Disconnecting the client and reconnecting does not clear the issue, so I infer the issue is on the server.  Stopping the server (saving the world) and restarting it does not clear the issue either, so I infer it is an issue with the projectiles not despawning instead of some caching-like issue.  Running into the stopped projectiles (e.g. by building a tower up to them) does not trigger the projectile damage or nausea effects, so I infer the issue is related to the graphics of the projectile rather then the "physical" projectile itself.

The server is running Minecraft 1.7.10, along with these CoFH mods/versions:
CoFHCore 3.0.3B2-294
Thermal Foundation 1.2.0B1-95
Thermal Expansion 4.0.2B2-210

It also uses these non-CoFH mods/versions:
Another One Bites the Dust 2.7.1
BDLib 1.9.0.94
Buildcraft 7.0.13
CodeChickenCore 1.0.4.29
ExtraTiC 1.4.5
Forestry 3.6.2.19
Fossils & Archaeology Revival 7.2.1
Gendustry 1.5.2.107
IndustrialCraft 2 Experimental 2.2.742
MagicBees 2.1.22
Mantle 0.3.2
NEIIntegration 1.0.11
Not Enough Items 1.0.3.74
Railcraft 9.6.1.0
Tinkers Construct 1.8.5
Thaumcraft 4.2.3.5
TiCTooltips 1.2.4

My client is running the same mods, plus OptiFine 1.7.10 HD U C1.

**Comment by KingLemming** [comment]
Update.
