### ISSUE TITLE
Thermal Expansion Pulverizer Crash!

### ISSUE THREAD

**Issue by MJRLegends** [CoFH/Feedback#687]
I have a pulverizer setup which is hooked up with my me system, it has a export bus feeding in ore's such as gold and iron in to the import on the pulverizer and it has a import bus in the export of the pulverizer. 

here is the crash log http://pastebin.com/q3dpLjYP

its crashed me 5 times within 24hr and its a random crash

**Comment by KingLemming** [comment]
It's not a random crash at all. it's caused by not updating. This is already fixed.

**Comment by MJRLegends** [comment]
So what version of the mod will this fix be included?

**Comment by KingLemming** [comment]
The one that's already released. Please go download it.
