### ISSUE TITLE
[1.12.2] Minor Recipe Book Issue (Thermal Dynamics Covers)

### ISSUE THREAD

**Issue by AcidKat** [CoFH/Feedback#688]
After first crafting any cover type, from that point on the recipe book permanently has a new invalid recipe showing (even with "Showing Craftable" enabled). See Screenshot Below.

It's really a minor problem as it has very little impact on game-play, but it's probably worth addressing if it's not too much trouble ^^.

**Versions:**

**Minecraft**: 1.12.2
**Forge**: 14.23.1.2559
**Thermal Expansion**: 5.3.7.31
**Thermal Dynamics**: 2.3.7.14

![2017-12-05_02 03 28](https://user-images.githubusercontent.com/15000462/33586351-ea5e6fe2-d960-11e7-89aa-02487612795e.png)

**Comment by KingLemming** [comment]
I don't know if this is "fixable" tbh. It might be entirely vanilla logic.

**Comment by AcidKat** [comment]
Fair enough if it's not caused by the mod, its hardly a game breaking problem, just an annoyance really.. I just like to keep the UIs as clean as possible. Its a shame though, other than this the TE - Vanilla Recipe book functionallity is actually really nice, especially after the changes in one of the recent updates that separated some of the items into their own groups. 

Besides the occasional bug (that you fix at a dizzying speed btw) I can't get enough CoFH right now, loving everything about your mods ^^

**Comment by KingLemming** [comment]
I'll see if there's a way to hide things from the vanilla recipe book.

**Comment by KingLemming** [comment]
Indeed there is. Thank @mezz. :)
