### ISSUE TITLE
[1.12.2] Minor Dropped Item Visual Bug

### ISSUE THREAD

**Issue by AcidKat** [CoFH/Feedback#689]
Items dropped from Thermal Expansion appear much larger than normal items (see screenshot). They also appear oversized in the player's hand (second screenshot). No other impact on game-play that I've found with this bug, it's just a weird visual error.

**Edit**: I double checked this with a fresh install to make sure it wasn't a bug caused by another mod (it isn't).

**Versions**:

**Minecraft**: 1.12.2
**Forge**: 14.23.1.2559
**Thermal Expansion**: 5.3.7.31

![2017-12-05_02 10 03](https://user-images.githubusercontent.com/15000462/33586533-b0525f38-d961-11e7-8df7-d9be5fa6058b.png)

![2017-12-05_02 13 44](https://user-images.githubusercontent.com/15000462/33586593-f4e59462-d961-11e7-807f-591dc0746144.png)

**Comment by KingLemming** [comment]
This isn't actually a bug, it's a result of setting the "isFull3D" flag which was done intentionally. Tools also use it.

But since it seems to be a point of confusion, I'll consider changing it to prevent further issue reports.

**Comment by AcidKat** [comment]
If theres a benefit to the items staying like this dont change it for the sake of idiots like me ;)

**Comment by KingLemming** [comment]
There's no benefit, I had just opted to treat them as tools. If you drop a pickaxe, you'll also notice that it's larger.

But honestly, I think it looks better small after seeing it, so I made the change. :)
