### ISSUE TITLE
[1.12.2/Direwolf20] NoClassDef: ...World$2

### ISSUE THREAD

**Issue by Ikkerens** [CoFH/Feedback#690]
Hey there!

First and foremost I'd like to state that I'm not sure if this issue is immediately caused by your mods, but right now I'm at a loss so I'm looking for any pointers.

I'm running a FTB Direwolf20 for 1.12 server, version 1.1.0 which I'm trying to upgrade to the latest release version 1.2.0.
Without the existing world, this server runs just fine. But as soon as I import my existing world I'm getting this crash after server startup:
https://gist.github.com/Ikkerens/c0a9ac81e99ba309fd1614b814a726ad

Sadly the crash report doesn't give me any kind of coordinates to any offending blocks, so I'm really not sure where to start looking.

Thanks in advance!

**Comment by KingLemming** [comment]
I think you may be running out of RAM, actually. But since it works with a new world, I'm fairly certain it's not caused by our code.

**Comment by Ikkerens** [comment]
RAM is doubtful, Xmx is at 32G. I saw a similar response from you pointing at RAM so I already tried that.

And yeah, I agree, pretty sure it's not. But I'm at a loss.

**Comment by KingLemming** [comment]
Yeah at this point we're basically into just tech support. Can you make a backup of the existing world and try removing a bunch of mods to see how it behaves?

**Comment by OracleofWuffing** [comment]
"Memory: 382329400 bytes (364 MB) / 1320218624 bytes (1259 MB) up to 4151836672 bytes (3959 MB)"
Are you sure the crash report is the same for when you set it to use 32GB of RAM?  The report you posted seems like Minecraft doesn't even have 4GB to work with, that's what FTB suggests as minimum.

**Comment by Ikkerens** [comment]
@OracleofWuffing It's not the same crash report as when I set it to 32G, I never said it was. But apart from that one setting the crash reports are all identical. The server usually runs in my managed environment, but this particular instance was started from commandline.
@KingLemming When disabling both Thermal Dynamics and Applied Energistics, the error no longer occurs. If I enable either of them I get the error. 

I'm well aware we're delving into the tech support part right now, and honestly my main hope here is that your extended knowledge of Minecraft behaviour would be of any assistance at this point :P

**Comment by KingLemming** [comment]
What's the report look like with only AE enabled?

**Comment by Ikkerens** [comment]
This is the crash report when running on 32G and having Thermal Dynamics disabled:
https://gist.github.com/Ikkerens/dec5ed337abbcfb18170e8d742678185

**Comment by KingLemming** [comment]
There's not, no. And after tracing through World, that log makes absolutely no sense. It's crashing on a completely nonsensical line in a catch block. There's no inner world class, which is what the error is complaining about.

So at this point, it could even be a coremod injecting code into world and somehow doing it incorrectly. Wish I had more for you. :/

**Comment by KingLemming** [comment]
Hrm...a google search gives me this:

http://www.minecraftforge.net/forum/topic/23262-1710solved-javalangnoclassdeffounderror-netminecraftworldworld2/

Which suggests that some mod you updated has incorrectly changed their code to create an infinite loop.

**Comment by Ikkerens** [comment]
I'll keep experimenting a bit, see if I can attach a debugger to the java process and set a breakpoint on the offending lines. Perhaps that'll give some clarity.

Thank you for your assistance anyway, it's very much appreciated.

**Comment by KingLemming** [comment]
I'd suggest trying to remove other mods one at a time (or a handful) until you don't get the crash. The idea that it's something physically connected to a duct or AE cable makes a ton of sense.

**Comment by Ikkerens** [comment]
It does, but the best idea I've got right now is find out where in the gameworld this crash is triggered so I can perhaps detach a cable (or remove it through NBT), perform the update and then replace it.
