### ISSUE TITLE
title screen glitch

### ISSUE THREAD

**Issue by TheChronomancer** [CoFH/Feedback#690]
i get this:
![image](https://cloud.githubusercontent.com/assets/8211402/8640659/b36ed15c-28b4-11e5-9d5a-8bad75e83238.png)
whenever i have a mod from teamcofh
and this is my log:
http://pastebin.com/pL44cgz2

**Comment by KingLemming** [comment]
So...I don't see a modlist.

**Comment by TheChronomancer** [comment]
![image](https://cloud.githubusercontent.com/assets/8211402/8640743/6b090abe-28b8-11e5-81f5-c6898ce327fe.png)

**Comment by KingLemming** [comment]
There is literally not a single CoFH mod in that list.

**Comment by TheChronomancer** [comment]
cofhcore,thermal expansion,thermaldynamics and thermal foundation were cut off

**Comment by KingLemming** [comment]
Use

-Dforge.forceNoStencil=true

as a JVM argument.

**Comment by KingLemming** [comment]
So, did that fix your issue?

**Comment by TheChronomancer** [comment]
yes
