### ISSUE TITLE
"Tessellating CCL block in world" caused by TD itemduct

### ISSUE THREAD

**Issue by Frenzaih** [CoFH/Feedback#691]
The pipe had been working on an automated induction smelter for a while. Suddenly, when it had been idle for maybe hours, it crashed my game. The pipe that caused the problem was directly above the induction smelter, if that makes any difference. 
We removed it with mcedit since it would crash anyone near it. I tried reinstalling the pipe but the same problem occurred. I was also unable to recreate the problem in singleplayer. 

**Crashlog:** https://pastebin.com/6uSwWH7A
minecraft 1.12.2, ATM3 pack

**Comment by covers1624** [comment]
Please update your mods before posting issues, this has been fixed with an updated forge & mod version.  
Duplicate https://github.com/CoFH/Feedback/issues/410
