### ISSUE TITLE
[Suggestion] Use Potions of Fire Resistance as Coolant

### ISSUE THREAD

**Issue by OracleofWuffing** [CoFH/Feedback#692]
Minecraft 12.2
CodeChickenLib-1.12-3.1.3.313
CoFHCore-1.12.2-4.3.7.25
CoFHWorld-1.12.2-1.0.2.10
RedstoneFlux-1.12-2.0.1.2
Thermal Expansion 1.12.2-5.3.7.31
Thermal Foundation-1.12.2-2.3.7.18

Please consider adding coolant properties to Potions of Fire Resistance since we have them as fluids now.  There aren't too many coolant options provided by Thermal Expansion on its own, and even with cross-mod usage, the options don't cover a lot of middle ground, jumping from "plentiful and easy" to "best of show" in very few steps.

Powered up a Fluid Transposer to empty a Potion of Fire Resistance and placed it on top of a Thermal Mediator, the Fire Resistance was stuck in the Fluid Transposer's tank.  Broke the Transposer repeatedly and tried other variants of Fire Resistance potions, still couldn't get it into the Mediator.  Tried with a bucket of Gelid Cryotheum, and the Cryotheum moved over to the Mediator.  So I'm guessing they're not currently considered a coolant.

I know Potion stuff was just now added, so I'm guessing there's still up and coming stuff in the pipes as to what kind of content can be played with so chances are I'm asking something that's already on the spindle, but to me it makes sense that a liquid that you drink to prevent yourself from burning to death could be used to prevent a machine from overheating.  When I first read Thermal Expansion was going to do something with potions, the two things that came to mind were Coolants and Compression Dynamos.  Granted, that's on me, nobody in CoFH promised anything, and you all make a good set of mods regardless.

Looking at the available coolants in the Documentation, I would imagine it fitting in the gap between Distilled Water and Crushed Ice in terms of Thermal Capacity.  Maybe somewhere 500,000-ish, 40% Coolant Factor?  Possibly 750,000-1,000,000 TC for the extended version?  Would make a solid-looking 20-40-60% coolant factor progression for Thermal Expansion-alone gameplay, but still be inferior to IC2 Coolant and Crushed Ice for folks that prefer to use those mods.

Thanks for your time reading all this and any consideration on the matter.  Gonna go play with machines some more.

**Comment by KingLemming** [comment]
The thing is that coolants actually are extremely good at conducting heat, not resisting it. When it comes right down to it, potions of fire resistance would make for terrible coolants as they impede heat transfer.

I'm sort of approximating dynamo operation on the Carnot cycle, which depends on absolute temperature difference, and if heat can't flow, the temperature difference is actually removed, making it not work. And even in Minecraft itself, the potion is made with a Magma Cream, suggesting that really what is happening is that the internal temperature of the player is being magically raised to prevent fire from harming them.

So from a raw physics point of view, this probably shouldn't be a thing. And internally from a code perspective, it's a bit more rewriting than you think. Potion is a complicated fluid as it has NBT data. The others aren't.

I don't think I'll rule it out as a fuel though. ;)
