### ISSUE TITLE
[Suggestion] TE: Modified dynamo fuel recipes in JEI based on augments

### ISSUE THREAD

**Issue by AnZaNaMa** [CoFH/Feedback#695]
I'm not sure if this is possible to do with JEI because I have no idea how it works,  but I was thinking that it'd be nice to have the numbers that the recipes in JEI for dynamos change based on the augments that are installed in the machine and the tier of machine that it is.

For example, if you install an auxiliary transmission coil it would show you how long each cycle of fuel will last now compared to before. On this note, it would also be nice if JEI displayed the time it takes a cycle of fuel to burn at maximum output.

Maybe there's a way to see this already and I'm just missing it, but it's hard to figure out exactly how long each set of fuel is going to burn, especially since the numbers for the augments change from time to time.

**Comment by KingLemming** [comment]
It's not possible I'm afraid, JEI looks at categories and not specific tiles. There's no way for me to specify that X dynamo has Y augments when creating the category.
