### ISSUE TITLE
[Suggestion] Thermal Expansion: Satchels right-click empty into Chests and other valid containers.

### ISSUE THREAD

**Issue by angrycloud** [CoFH/Feedback#696]
A machine to extract the contents of a satchel or cache and emit the items to a port. The emptied container would then be emitted out another port.

Say I'm mining and using several satchels to store all my ore and loot. I could dump all my full satchels into this machine (via a hopper or chest). The machine would empty the satchel to one port, eject the empty satchel and get the next one.

There could even be a possible bonus based on how full the satchel was. Sort of like finding loose change when you clean out your backpack. Maybe a bonus of string or wool or maybe a coin.

I could see this working with item containers from other mods (crates, backpacks, etc.)

I suppose it could be reversible. Pack vs. unpack

**Comment by KingLemming** [comment]
I had already considered this at one point - a Transcapsulator. Honestly though, it just didn't seem that useful. It's not technically challenging necessarily, but seemed incredibly limited in its applications.

What I am planning on doing is buffing satchels a fair bit, giving them auto-pickup and filter slots.

Also right now I do run into the minor issue that I'm limited to having 16 machines in the mod, and there are 15 already, plus the Auto Crafter which isn't released which makes the metadata full. In 1.13, the rewrite will necessarily mean that the 16 limit goes away, so maybe then, if it's even really all that necessary?

**Comment by bookerthegeek** [comment]
While nice, I would prefer to be able to click on a chest and empty into the chest. Similar to how the forestry bags work.

**Comment by KingLemming** [comment]
That also came to mind and is entirely reasonable.

**Comment by angrycloud** [comment]
I'd forgotten about behavior of the Forestry bags. That would work.
I do grant that as a machine, it's a little limited in application. Especially considering your machine limit.

**Comment by KingLemming** [comment]
k, let's go with that then. :)
