### ISSUE TITLE
Invisible Cover

### ISSUE THREAD

**Issue by drakray** [CoFH/Feedback#697]
As the title say:
![2017-12-06_19 09 32](https://user-images.githubusercontent.com/4303126/33692056-7be0bf3e-dab9-11e7-80f4-cbb5400dbaaa.png)
![2017-12-06_19 09 36](https://user-images.githubusercontent.com/4303126/33692057-7bfcb02c-dab9-11e7-954c-afb859aa6f0a.png)
![2017-12-06_19 09 55](https://user-images.githubusercontent.com/4303126/33692058-7c0eea58-dab9-11e7-99d9-9ea67d4d3e5a.png)

Is there a reason/workaround for that? 
NO Optifine

MC 1.12.2
Forge 2258
[ModList](https://pastebin.com/6Q5TFJnE)

**Comment by KingLemming** [comment]
Can you make it happen with only our mods installed and nothing else?

If yes, then @covers1624 can take a look. If not, well then it's not our mod.

**Comment by drakray** [comment]
Covers show texture with just TeamCOFH mods(and dependencies) in pack, I'm testing to find which one is breaking thing

**Comment by drakray** [comment]
Found the culprit: [LazeModder](https://minecraft.curseforge.com/projects/lazymodder)

Tested with:
Minecraft 1.12.2
Forge 2558
CodeChickenLib-1.12-3.1.3.313-universal
CoFHCore-1.12.2-4.3.7.25-universal
CoFHWorld-1.12.2-1.0.2.10-universal
LazyModder-0.74
RedstoneArsenal-1.12.2-2.3.7.18-universal
RedstoneFlux-1.12-2.0.1.2-universal
ThermalCultivation-1.12.2-0.1.2.8-universal
ThermalDynamics-1.12.2-2.3.7.14-universal
ThermalExpansion-1.12.2-5.3.7.31-universal
ThermalFoundation-1.12.2-2.3.7.18-universal
...
Without LazyModder, the covers show normally

**Comment by covers1624** [comment]
Do you happen to have a texture pack installed?

**Comment by drakray** [comment]
Yes, but got fix by removing LazyModder mod, sorry, forgot to write here

**Comment by covers1624** [comment]
Try keeping LazyModder installed and removing your texture pack. If the issue persists, im gonna call this a LazyModder issue, they are breaking vanilla's models somehow, TD may have a non standard rendering pipe but it uses vanilla's standard for grabbing models and it is that, that is broken.

**Comment by drakray** [comment]
Tried, didnt work

**Comment by covers1624** [comment]
Ok, This is a LazyModder issue, I'll leave this open until their issue is resolved.

**Comment by KingLemming** [comment]
House cleaning.
