### ISSUE TITLE
Title Screen Graphical Glitch

### ISSUE THREAD

**Issue by thehotdogman93** [CoFH/Feedback#697]
Ive been getting this graphical glitch on the title screen when I play on the AT Launcher, Specificlly when I startup Sky Factory 2.4. White screen and the bottom left corner has the background. I know your gonna tell me to use -Dforge.forceNoStencil=true and Ive tried using that. Ive been doing some research on it and stencils which is a graphical feature that forge provides, my opengl cant use stencils. I read up somewhere that CoFH has to use stencils to work and my thought is that forge ignores to disable stencils for CoFH causing the graphics to fail. Im not sure if this is true or why forge has to use stencils for Sky Factory 2.4.

I think its also very important to say that I replaced forge on SF 2.4 because the splash screen crashes my java and there wasnt a slash properties with the forge that came with SF 2.4 so I spliced in Forge 10.13.3.1384. Im on mobile but I will take screen captures on my computer of what the options look like in the AT Launcher and a copy of the At Console when I run SF2.4. The mod list is just every mod in SF 2.4 including all of the the optional ones and spliced in Forge.

I was just wondering if CoFH had anything to do with stencils. Im also going to ask on the at forums and the forge forums. Maybe there could be lite versions of CoFH. The only thing that worries me is the compatability with the majority of 2.4 servers. I could be wrong about all of this though and was looking for some pointers. 
Thank you guys in advance.

**Comment by KingLemming** [comment]
-Dforge.forceNoStencil=true works with updated mods. 1384 is too outdated, you'll need 1448 and the newest mods.

And then it'll be fixed.
