### ISSUE TITLE
Axes unable to get sharpness?

### ISSUE THREAD

**Issue by Akitori** [CoFH/Feedback#698]
Dunno if this is a bug, but axes from thermal foundation are unable to get sharpness? I know its a vanilla applicable enchantment on vanilla axes (smite, bane, sharp) but why can't thermal foundation axes get this feature?

**Comment by KingLemming** [comment]
Not a bug, just how vanilla is coded. I'll see if there's a good workaround, but I kind of doubt it.

**Comment by KingLemming** [comment]
Actually, seems like Forge did add a semi-convoluted way to address this.
