### ISSUE TITLE
Thermal Dynamics Redstone Transmission attachments

### ISSUE THREAD

**Issue by Xiaminou** [CoFH/Feedback#699]
I remember a version of Thermal Dynamics not so long ago that had a way of transmitting redstone through its pipes using an attachment at both ends. What happened to that? is it coming back? Are there plans for some redstone pipes for Thermal Dynamics or is that out of the question?
I read a post talking about addons for Thermal Dynamics, I think redstone transmission and logic would be an interesting addon for sure.

**Comment by KingLemming** [comment]
I don't know if they're coming back or not tbh. The code is mostly there but I'm not sure the exact state of it.

Honestly, I don't really like TD a whole lot - it just doesn't interest me, so I don't have a whole lot of incentive to re-add stuff.

**Comment by Xiaminou** [comment]
I had a case earlier where I wanted to have Itemducts send items in priority to a certain container, but when I looked for the dense/vaccum functions for itemducts they were no where to be found. Is this another feature that hasn't been ported yet?

**Comment by KingLemming** [comment]
Yes.

**Comment by KingLemming** [comment]
This will be happening next patch. Not today, but sometime after Christmas. ;)
