### ISSUE TITLE
Cross-mod conflict : Thermal Expansion, Thaumcraft, Big Reactors

### ISSUE THREAD

**Issue by elan-morin** [CoFH/Feedback#7]
I've been tracking a bug in Thaumcraft and discovered that it leads through Big Reactors to Thermal Expansion. Here is the issue: https://github.com/Azanor/thaumcraft/issues/1499 It has all the relevant information and links.

**Comment by KingLemming** [comment]
Check explicity with just TE, BR, and TC. Let us know what you find.

**Comment by elan-morin** [comment]
I did, these were the only mods I had that were necessary for the problem to occur:
TE, BR, TC (+Baubles), CoFHcore, Thermal Foundation

When I removed either TE or BR, leaving the others, the problem disappeared. I posted an issue on BR, but they say it's not their fault, so I came here. Also interesting is the fact that the problem doesn't occur with TE version 4.0.0 B6, but it does with versions B7 and B8. Different versions of TC or BR that I tested didn't have any effect on it.

We should have someone else test it either way to eliminate any mistake on my part. I'll copy what I wrote elsewhere about how to test it:

> The problem can be tested by scanning oak wood with the Thaumcraft scanning thingy. If it's broken, it will say "nothing can be learned from this", indicating that oak wood is not correctly registered in TC. If it's ok, it will show the tree essence, as per usual (or say that you have to scan other stuff first).

**Comment by KingLemming** [comment]
Does it happen with *only* TE and TC installed?

**Comment by elan-morin** [comment]
No, it needs BR. I'll write it even more explicitly then:

* TE v4.0.0 B7 or B8, BR, TC (+Baubles), CoFHcore, Thermal Foundation -> problem
* BR, TC (+Baubles), CoFHcore, Thermal Foundation -> ok
* TE v4.0.0 B7 or B8, TC (+Baubles), CoFHcore, Thermal Foundation -> ok
* TE v4.0.0 B6, BR, TC (+Baubles), CoFHcore, Thermal Foundation -> ok

**Comment by skyboy** [comment]
https://gist.github.com/skyboy/5a5c1c49eda525b2d645
https://github.com/CoFH/CoFHLib/blob/master/src/main/java/cofh/api/modhelpers/ThaumcraftHelper.java

The first link is TE's aspect registration, second is how it registers aspects. If there are any problems with either of these that's leading to the misapplied/corrupted aspects then I'll fix it, but as far as I know there are none.

**Comment by skyboy** [comment]
@Azanor Would the thaumcraft helper linked above be causing the problem? These are the constructors/methods invoked (via reflection):

```java
registerItem = ThaumcraftApi.getDeclaredMethod("registerObjectTag", ItemStack.class, AspectList);
Class<?> EntityTagsNBT = Class.forName("[Lthaumcraft.api.ThaumcraftApi$EntityTagsNBT;");
registerEntity = ThaumcraftApi.getDeclaredMethod("registerEntityTag", String.class, AspectList, EntityTagsNBT);
addAspect = AspectList.getDeclaredMethod("add", Aspect, int.class);
newAspectList = AspectList.getDeclaredConstructor(ItemStack.class);
```

**Comment by skyboy** [comment]
@Azanor It appears that the aspects we're adding to items are interfering with the recipe-aspect-applicator thingy, causing it to generate frankly weird results.

**Comment by Azanor** [comment]
It looks like something in BR is triggering my aspect generation code to run before I actually assign base aspects to core items like wood and so forth - which I do in FMLPostInitializationEvent. Basically since BR causes TE to load before TC you try to assign aspects to items using registerObjectTag which probably involves some vanilla items - this in turn triggers a whole cascade of aspects being assigned to stuff which shouldn't have them assigned yet.
In theory if I move my basic aspect assignments to FMLInitializationEvent and TE does it's aspect stuff in FMLPostInitializationEvent everything should be fine. In theory

**Comment by Azanor** [comment]
I tried to fix this on my end, but the "fix" unfortunately makes my mod not work with anything that adds copper or silver ore. Looks like this is not something I can fix on my end. It will have to be fixed on the TE side. The simplest solution might be to have TE load after Thaumcraft, but it is up to you guys if you want to do that.

**Comment by skyboy** [comment]
I'll move integration to LoadComplete instead of PostInit, as I suspect moving Thaumcraft even higher in the load order is going to make the problem even worse.

**Comment by Azanor** [comment]
Hehe, that is quite possible. Thanks :)

**Comment by dredhorse** [comment]
Hi, which version of TE has this fix?
