### ISSUE TITLE
Fluid Transposer clogging up

### ISSUE THREAD

**Issue by 016Nojr** [CoFH/Feedback#70]
If you fill two (In my case) buckets with glowstone in the Fluid Transposer and dont remove the first filled bucket from the output slot, it will move the other bucket to the "processing slot" and fill it, but when the first bucket in the output slot is removed the other bucket is stuck in the "processing slot" and wont get moved to the output slot. I was able to manually grab it out.

Modpack used: FTB Beyond

Forge: 12.18.3.2254
TE: 5.0.1.73
TF: 2.0.1.68
CoFHCore: 4.0.1.137

**Comment by KingLemming** [comment]
#2 - make up your mind.

**Comment by 016Nojr** [comment]
It is? I didnt think it was because a filled bucket was getting stuck, not a bucket that was waiting to be filled.

**Comment by KingLemming** [comment]
Two sides of the same coin. The point being the old code handled this because I was worried about the system getting plugged and this issue is a direct result of me changing it.
