### ISSUE TITLE
Suggestion: Per Tick Power Output/Usage Stats In Machines And Energy Cells

### ISSUE THREAD

**Issue by RoloEdits** [CoFH/Feedback#700]
Would it be possible to have a text display when hovering over the energy buffer of machines and the energy cells to display the input and output or usage of energy kinda like how Ender IO has it but better?

**Comment by RoloEdits** [comment]
I totally forgot about the machines already have it im a derp :p 
please forgive my stupidity.

**Comment by KingLemming** [comment]
After looking into it, this would unfortunately add a lot of overhead to cells that 99.99% of the time would serve no real purpose. Maybe something with the multimeter in the future, so it's an on-demand type of thing, but nothing that'll just happen in the GUI, sorry.

**Comment by RoloEdits** [comment]
Ok thanks for for looking in to it. it means a lot that you take your time to do it.
