### ISSUE TITLE
Portable Tank + Multimeter

### ISSUE THREAD

**Issue by Xiaminou** [CoFH/Feedback#700]
![2017-12-07_02 18 08](https://user-images.githubusercontent.com/8670392/33694294-a3243ede-daf7-11e7-9e59-cb4ba3492ce3.png)
Note: the Portable Tank has Holding IV.

![2017-12-07_02 18 15](https://user-images.githubusercontent.com/8670392/33694295-a33e3244-daf7-11e7-99d4-3aa89b096605.png)

Minecraft: 1.12.2
Forge: 2556
Mods: [list.txt](https://github.com/CoFH/Feedback/files/1537493/list.txt)

**Comment by KingLemming** [comment]
Easy enough.
