### ISSUE TITLE
Suggestion: VersionChecker Integration

### ISSUE THREAD

**Issue by ishitatsuyuki** [CoFH/Feedback#701]
I know CoFH includes a good version checker feature, but VersionChecker does more than it. It will auto download and update it.
So, how about integrating like how Logistics Pipes does?
The LP way:
1. If VersionChecker not installed use own updater.
2. If installed register the update information and shut up in game chat.
BTW, a complain about the version, is that the new homepage doesn't show latest update date and confuses me:)
Reference: 
1. [Version Checker](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2091981-version-checker-auto-update-mods-and-clean)
2. [Logistics Pipes Code](https://github.com/RS485/LogisticsPipes/blob/dev/common/logisticspipes/ticks/VersionChecker.java)

**Comment by KingLemming** [comment]
Yeah, I don't agree with auto downloading at all, that's a really good way to break a pack. I'll look into what all it does, but if that's just a thing that happens, it'll be a solid no.

**Comment by Entoarox** [comment]
You need to manually choose to get the download still, the game will just do the downloading for you once you choose that option.
