### ISSUE TITLE
The Copper hammer (thermal Foundation) only does one craft.

### ISSUE THREAD

**Issue by JamRobLam** [CoFH/Feedback#701]
I'm playing the Direwlf20 mod pack and decided I needed some gravel and saw the hammer and cobblestone make gravel so I crafted up a copper hammer and crafted the recipe, and to my surprise, after one craft the hammer disappeared. Not sure if intended behavior and doing so takes up a lot of durability, but thought I'd note it and send it through.

**Comment by KingLemming** [comment]
Intended. That isn't a recipe that I've added, so take it up with the pack makers.

The issue is basically this: if I code the hammers such that they can be used as crafting items, then there's a problem when you use two hammers to craft a repaired hammer, and you end up just duping hammers.
