### ISSUE TITLE
1.12.2 Pulverizer

### ISSUE THREAD

**Issue by HeKontrolls** [CoFH/Feedback#702]
Hi, when I place the Pulverizer in 1.12.2 and goto access it, I can not. No GUI shows up. I went into creative mode and none of the machines have GUI's

I have the mods Thermal Expansion: Items, Thermal Foundation and Thermal Foundation: Tools, Thermal Foundation: Armor and Thermal Foundation: Florbs

Cache Machine is unbreakable

**Comment by HeKontrolls** [comment]
Another note, the Cache machine it left a horrible screeching sound in my world

**Comment by KingLemming** [comment]
Yeah, this is entirely localized to your setup and install - it's absolutely not in our code. You've done something wrong, and without a complete modlist and logs, we can't possibly know what's going on.

And the Cache must be dismantled with a wrench. It's been this way for years.

**Comment by HeKontrolls** [comment]
Ahh ok, I'm working on a custom mod pack for myself to play this is the list of mods I have installed. I have not had any crashes. 

    Just Enough Items (JEI) (by mezz)
    Buildcraft (by CovertJaguar)
    Extreme Reactors (by ZeroNoRyouki)
    CodeChicken Lib 1.8.+ (by covers1624)
    Inventory Tweaks (by Kobata)
    RFTools (by McJty)
    McJtyLib (by McJty)
    Tinkers Construct (by mDiyo)
    Mekanism (by aidancbrady)
    ZeroCore (by ZeroNoRyouki)
    Mekanism Tools (by aidancbrady)
    Not Enough Items 1.8.+ (by covers1624)
    Mantle (by mDiyo)
    Botania (by Vazkii)
    Baubles (by azanor)
    Advanced Rocketry (by zmaster587)
    LibVulpes (by zmaster587)
    Biomes O' Plenty (by Glitchfiend)
    Draconic Evolution (by brandon3055)
    Redstone Flux (by TeamCoFH)
    Brandon's Core (by brandon3055)
    Actually Additions (by Ellpeck)
    Applied Energistics 2 (by AlgorithmX2)
    Dynamic Trees (by ferreusveritas)
    Mo' Bends (by iwoplaza)
    Ender Storage 1.8.+ (by covers1624)
    ComputerCraft (by dantwohundred)
    Forestry (by SirSengir)
    AE2 Stuff (by bdew)
    BdLib (by bdew)
    Aroma1997s Dimensional World (by Aroma1997)
    Aroma1997Core (by Aroma1997)
    Hardcore Questing Mode (by lorddusk)
    Extra Utilities (by RWTema)
    Pam's HarvestCraft (by MatrexsVigil)
    Pam's Cookables - Pam's Harvestcraft Addon (by BloodWorkXGaming)
    iChunUtil (by iChun)
    Portal Gun (by iChun)
    Thermal Expansion (by TeamCoFH)
    Thermal Foundation (by TeamCoFH)
    CoFH Core (by TeamCoFH)
    CoFH World (by TeamCoFH)
    Hwyla (by TehNut)
    RFTools Dimensions (by McJty)

**Comment by KingLemming** [comment]
Can you please provide a log dump? Mod versions matter, not just the mods.

**Comment by HeKontrolls** [comment]
https://paste.ee/p/vUfxG <-- Latest Log File. I made sure to delete all the other ones that were zipped and restart the game. I placed the pulverizer and tried to access it before I uploaded

**Comment by KingLemming** [comment]
Go download the most recent version of all CoFH mods.

**Comment by HeKontrolls** [comment]
Thanks worked :D
