### ISSUE TITLE
[Thermal Dynamcis] Inconsistent fluiduct connection 

### ISSUE THREAD

**Issue by SuperSandro2000** [CoFH/Feedback#702]
After the last update of thermal Dynamics the hardened fluiducts at my ender thermic pumps sometimes stop transfering lava. After breaking and placing them back it works for a while but it is breaking after a while again.

**Comment by KingLemming** [comment]
We're going to need screenshots at a bare minimum, because nobody has reported anything like this.

**Comment by SuperSandro2000** [comment]
http://i.imgur.com/23ZL6tQ.png
I moved the Ender Thermic Pump and now it seems to work.
I don't know if it is relevant but I switched from Project Red to Blue Power yesterday.

**Comment by KingLemming** [comment]
Chunk border perhaps? Was the dynamo in a different chunk?

**Comment by SuperSandro2000** [comment]
Nope, I checked it before I build it because I only wanted to use a mini chunkloader from chicken chunks.

**Comment by KingLemming** [comment]
Not to our knowledge, no. I'm curious why you actually need a duct in that particular situation though. Can the pump not directly eject to the tank? And is this maybe on the tank?

**Comment by SuperSandro2000** [comment]
Can it directly ouutput? I didn't know that but I like it to see if lava flows.
