### ISSUE TITLE
Crash with latest Forge: "Item$ToolMaterial.getDamageVsEntity()" and other methods no longer exist.

### ISSUE THREAD

**Issue by turbodiesel4598** [CoFH/Feedback#703]
I believe some methods in ItemTool and Item$ToolMaterial have recently had their names changed, leading to the crash. The mods I have installed are [these](https://pastebin.com/Nj3cThz2) - all of the CoFH mods are the latest as of this evening. The crash report [here](https://pastebin.com/3q0P1hdz). Using Forge version 14.23.1.2559 for MC 1.12.2 (not quite the latest anymore but was a few days ago).

**Comment by KingLemming** [comment]
Just tested this with a completely fresh install, doesn't happen. You have messed something up somewhere on your end.

**Comment by turbodiesel4598** [comment]
Yep, my bad - was running the game in a dev environment and forgot to change the source for some folder to the latest version of Forge, leading to a mismatch.
