### ISSUE TITLE
Pulverizer crash

### ISSUE THREAD

**Issue by 2000jf** [CoFH/Feedback#703]
I have a pulverizer that is automatically pulverizing cobble into gravel / gravel into sand, automated with AE. It already crashed my game multiple times at pretty random moments
It happens in Agrarian skies 2 version 1.1.7, crash report included as screenshots

![screenshot 2015-07-16 21 47 22](https://cloud.githubusercontent.com/assets/13354331/8733526/826ed586-2c04-11e5-873f-9a53b82faed3.png)
![screenshot 2015-07-16 21 47 28](https://cloud.githubusercontent.com/assets/13354331/8733527/82758b6a-2c04-11e5-9c82-828c8b6b84f9.png)
![screenshot 2015-07-16 21 47 39](https://cloud.githubusercontent.com/assets/13354331/8733528/827d304a-2c04-11e5-84c5-76b102cc6f9c.png)
![screenshot 2015-07-16 21 47 51](https://cloud.githubusercontent.com/assets/13354331/8733529/8282b236-2c04-11e5-987f-d41af7f8f0ed.png)
![screenshot 2015-07-16 21 48 02](https://cloud.githubusercontent.com/assets/13354331/8733530/828bdea6-2c04-11e5-85a4-70ceed194ef2.png)
![screenshot 2015-07-16 21 48 16](https://cloud.githubusercontent.com/assets/13354331/8733531/8294c44e-2c04-11e5-9a4f-9ecbf010d833.png)
![screenshot 2015-07-16 21 48 27](https://cloud.githubusercontent.com/assets/13354331/8733532/8298c7a6-2c04-11e5-9f46-9b7147e55064.png)
![screenshot 2015-07-16 21 48 37](https://cloud.githubusercontent.com/assets/13354331/8733533/82a31224-2c04-11e5-80a4-82a82f67d534.png)
![screenshot 2015-07-16 21 48 44](https://cloud.githubusercontent.com/assets/13354331/8733534/82a75e38-2c04-11e5-8555-7b8990a05d06.png)
![screenshot 2015-07-16 21 48 54](https://cloud.githubusercontent.com/assets/13354331/8733535/82af3f5e-2c04-11e5-8097-502c2398c7bb.png)

**Comment by KingLemming** [comment]
AG2 is out of date. This has been fixed already.
