### ISSUE TITLE
[Suggestion] Make Fluid Transposers able to imbue Arrows?

### ISSUE THREAD

**Issue by Akitori** [CoFH/Feedback#704]
I realize saying this kinda seems silly, but as these imposers are already able to make potions/splash/lingering already, would it be a stretch to have this same effect on arrows, turning them to tipped variants? (idk how difficult coding this would be, so I understand if its not feasible at this time).

**Comment by KingLemming** [comment]
Hmm...not infeasible, actually.

**Comment by KingLemming** [comment]
Well that was easy.

**Comment by Akitori** [comment]
will the tipped arrows in transposers cost 1/8 the cost of a normal potion or one normal potion? (just asking out of curiosity sake)

**Comment by KingLemming** [comment]
You have to imbue them 8 at a time ;)

**Comment by Akitori** [comment]
Makes sense to me. Thanks!

**Comment by KingLemming** [comment]
Actually I can do 4 at a time, that's maybe more reasonable. Alternatively, I could actually make the transposer *more* efficient at imbuing them, and that's something worth considering.

**Comment by Akitori** [comment]
Personally i would think making arrows in a machine would be more efficient than a crafting table (cause liquid spilling everywhere and all). Dunno, that's my own opinion personally.

**Comment by KingLemming** [comment]
I'm inclined to agree, and there is the added RF cost. So given that it requires the potion in fluid form *and* RF, I'll do 1 arrow per 25 mB, or 10 arrows / bottle.
