### ISSUE TITLE
Certain Ore's Not Affected By Pulverizers Config Multiplier 

### ISSUE THREAD

**Issue by RoloEdits** [CoFH/Feedback#704]
Standard ore's like iron and gold are affected by it but not things like nether quartz and diamonds aren't, is this intended or a bug or maybe neither? 

I set my multiplier to 64 times (OMG :O) to test and it still didn't change.

Thank you for your help.

**Comment by KingLemming** [comment]
Intended. Those aren't ores.

**Comment by RoloEdits** [comment]
OK thanks for your help
