### ISSUE TITLE
Interaction with Refined Storage

### ISSUE THREAD

**Issue by skeough** [CoFH/Feedback#705]
Currently, when a machine is set to auto pull from an empty Interface from Refined Storage, it can pull any item from the network that it can process.  This is a great function.

However, when you apply a specialization, for example the Flux Anodizers Specialization in the Redstone Furnace, it will pull items into itself that the UN-specialized Redstone Furnace could process, but of course fail to do so.  If you pick the item up, you cannot place it back in the machine, as expected.

Not sure if this is a bug, or a feature that was ultimately never planned.

**Comment by KingLemming** [comment]
The code on the Furnace's end suggests that it shouldn't work that way - it won't auto-extract anything that it can't process. And if you try with a normal inventory, it doesn't.

You may need to bring this up with Refined Storage.

**Comment by skeough** [comment]
Fair enough.  I will say that if I use the interface in export mode (put specific items into the interface to keep in stock), it ceases this odd behavior, and only pulls what is in the 'inventory' of the interface.

I will also report this to Refined Storage as well.

**Comment by skeough** [comment]
I don't think that they are going to handle this issue.  So I am unsure where to proceed.  I'd love to be able to pull from the 'inventory' of Refined Storage to auto-process ores.

**Comment by KingLemming** [comment]
Can you please provide a video of this happening? As I mentioned, I can't make it happen with a standard inventory.

**Comment by skeough** [comment]
Absolutely, I will upload one later tonight!

**Comment by skeough** [comment]
[Here we go](https://www.dropbox.com/s/br5g312m888wqw1/Minecraft%201.12.2%2012_8_2017%205_37_19%20PM.mp4?dl=0)

minor correction to the report, it is pulling in items that it cannot process at all as well.  In this instance, I was using Certus Quartz Ore, which came from a Void Ore Minor in the legit playthrough, but this was done in a creative flat world.

**Comment by KingLemming** [comment]
Okay, I know what's happening here, and it makes more sense now. This is a result of Certus quartz specifically not having a recipe but otherwise being oredicted. Has everything to do with an optimization I made and nothing to do with RS.

**Comment by skeough** [comment]
Awesome! I was just about to post that it does it with Certus Quartz Ore in a normal chest too.

Glad you found the issue.

**Comment by KingLemming** [comment]
Yeah. Videos are worth lots.

**Comment by raoulvdberge** [comment]
@skeough If it was an issue I was going to handle it, I don't ignore reports.

I was just making initial observations.

**Comment by skeough** [comment]
@raoulvdberge My apologies, rereading that it did sound a little mean.  I had not intention of it sounding that way.
