### ISSUE TITLE
Fluid based crash.

### ISSUE THREAD

**Issue by Divineaspect** [CoFH/Feedback#705]
http://pastebin.com/T2zkqPCA
The crash only occurs with Chromaticraft installed, but seems to point at Thermal Foundation.

**Comment by KingLemming** [comment]
This is either caused by Chromaticraft improperly registering Ender fluid, or the Fluid Registry not properly reporting that there are multiple registrations. Either way, nothing that we can fix.

**Comment by ReikaKalseki** [comment]
For me, getFluid() consists of `FluidRegistry.getFluid(fluidID);`, which could only NPE if FluidRegistry *itself* is null. I do nothing that could do this...
