### ISSUE TITLE
[Suggestion] Mixing/Combining potion 

### ISSUE THREAD

**Issue by Akitori** [CoFH/Feedback#706]
Alright, i know how overpowered this might seem. how powerful/unstable this might be (not to mention the amount of coding it might take) idk, this is my reasoning/logic for it.

One of the irritating things about potions is that you need to carry stacks of em on you. Instant healing, arrow types in pvp, etc. While you can carry various potion effects, it would not only save space, but also time used to swap between potions and whatnot.

Same logic applies to arrows really. You wanna shoot a target with say, wither/poison, you slow em, get your next shot ready but they're already gone. (i'm using very niche examples, sorry!)

Potions in times of crisis can mean life or death, and i understand if such a potent/powerful feature can't be put in easily, or even if its plain flat out unbalanced. Just suggesting is all.

**Comment by KingLemming** [comment]
Truth be told, the biggest problem with this is how vanilla Minecraft handles potion naming.

I might be able to come up with something though. :)

**Comment by KingLemming** [comment]
Oh I may have an interesting idea for this.

**Comment by Akitori** [comment]
What's up?

**Comment by abculatter2** [comment]
It'd also be nice to have stackable potions, in some form. Just sayin'.

**Comment by KingLemming** [comment]
See #758. Opening a "thread," if you will.
