### ISSUE TITLE
Pulverizer Crash (Null pointer exception)

### ISSUE THREAD

**Issue by M4thG33k** [CoFH/Feedback#706]
Mod Name: Thermal Expansion ([1.7.10]4.0.2B2-210)
List of mods in the pack: http://pastebin.com/2yYrJdqc
Crash Log: http://pastebin.com/mKWcg0Uz

Description of bug: There have been several occasions where the game crashes with a similar crash as this (at least four occasions so far). In each case, the gui is not open. The setup is as follows: the Pulverizer is made with a basic machine frame with the default augments and is set to allow input from the top and export to the right when facing the block (it doesn't seem to be affected by whether or not the block is placed facing N/S/E/W). A vanilla chest is placed to receive exports and a hopper is being used to input ores (vanilla and Metallurgy; the most recent crash happened while pulverizing promethium and iron ores). It is being powered via a Furnace Generator from Extra Utilites on its left.

**Comment by KingLemming** [comment]
What's that? It's already fixed? Please use up to date mods before you report things, just like the README tells you to. ;)

BTW, this is actually caused by ExU > 1.2.6, but we put in compat code on our end anyways.

**Comment by M4thG33k** [comment]
I apologize; I didn't realized it wasn't the most recent version. The Curse client didn't show that it needed an update. Thanks!

**Comment by KingLemming** [comment]
No worries! We've had this a lot from AS2 and I'm starting to wonder if it's something on their end.
