### ISSUE TITLE
[Thermal Foundation] Can't disable Silver Ore generation

### ISSUE THREAD

**Issue by r05ty** [CoFH/Feedback#707]
Hello,
I'm setting up my private modpack, and I ran into a problem. I want Metallurgy to handle most of ore generation, so I began to disable ore generation in configs of various mods. But It seems it's impossible to disable silver ore generation in Thermal Foundation config - http://pastebin.com/zg18VmgJ (my config right now)

As you see, I tried putting overworld dimension into blacklist and even disabling generation in all biomes, yet I can't disable silver, but other ores (like Copper, Tin...) works fine.

List of my mods - http://pastebin.com/nqGF9c9z

**Comment by KingLemming** [comment]
PEBKAC. Silver generates with lead, as the file clearly shows. Remove it from there as well.

**Comment by r05ty** [comment]
Oh thanks, derp on my side.
