### ISSUE TITLE
Super-Laminar Fluiducts don't connect with other fluiducts

### ISSUE THREAD

**Issue by Xiaminou** [CoFH/Feedback#707]
![2017-12-08_17 44 48](https://user-images.githubusercontent.com/8670392/33775783-baf037ea-dc3f-11e7-8aa4-6e805bb2244d.png)

Minecraft: 1.12.2
Forge: 2556
Mods: [list.txt](https://github.com/CoFH/Feedback/files/1543286/list.txt)

**Comment by KingLemming** [comment]
Correct.
