### ISSUE TITLE
1.12.2 item dup bug with tanks

### ISSUE THREAD

**Issue by croftyraider** [CoFH/Feedback#709]
I made a basic tank and then the hardened upgrade thingy and received the original tank plus an upgrade tank as the crafting result.

**Comment by KingLemming** [comment]
Ah. Yeah I can see why that would happen.

**Comment by KingLemming** [comment]
Fixing in dev, though may result in non-ideal behavior with some fluid recipes. Oh well. Can't win this one.

**Comment by croftyraider** [comment]
Personally, getting rid of the crafting recipe works for me though I of course don't know the ramifications. That was the approach I was using in 1.11.2 and was comfortable with. I only stumbled upon this issue because I was using JEI to find the crafting recipe by using the 'u' key on the tank I had just made :) being lazy in other words :)
