### ISSUE TITLE
[Thermal Expansion] Multiple Recipe Bugs

### ISSUE THREAD

**Issue by GenuineSounds** [CoFH/Feedback#71]
Some Thermal Expansion items (like Crescent Hammer and Igniter) are using the static reference to the vanilla items (like Items.iron_ingot) instead of the OreDictionary value (like "ingotIron").

This is a pretty lame bug :/

I've not checked any of the other recipes but I assume there are some others that reference the static vanilla items instead of the oredict name please replace these in all places that apply.

**Comment by GenuineSounds** [comment]
Thermal Expansion: 3.0.0B9-40

**Comment by KingLemming** [comment]
Already fixed in dev. We discussed why this was. It's not really a lame bug, since you are probably literally the only person on the planet to have ever added a new iron ingot.
