### ISSUE TITLE
Integrated Hopper Augment can pull from opposite side it's connected to

### ISSUE THREAD

**Issue by adudney** [CoFH/Feedback#710]
Thus allowing it to pull out of the input when theoretically it should only be able to access the output.

Minecraft 1.7.10
CoFH mods newest Curse version as of July 19th (I'll put in the actual versions later, I'm about to head to bed)

Initially, no issue, input works, and output works.
![2015-07-19_00 02 48](https://cloud.githubusercontent.com/assets/246232/8764931/b30033ba-2da9-11e5-9a16-941b393e4dad.png)
![2015-07-19_00 02 54](https://cloud.githubusercontent.com/assets/246232/8764936/b31cfbd0-2da9-11e5-9763-41152d5c219f.png)
![2015-07-19_00 02 55](https://cloud.githubusercontent.com/assets/246232/8764933/b31c3d12-2da9-11e5-85b7-fbd030fa7f86.png)
![2015-07-19_00 02 57](https://cloud.githubusercontent.com/assets/246232/8764934/b31c7764-2da9-11e5-8170-d1b55cf3824b.png)

But, change the opposite side from the furnace to an input, and the furnace starts pulling from said side.
![2015-07-19_00 03 03](https://cloud.githubusercontent.com/assets/246232/8764932/b31b17b6-2da9-11e5-901e-011fb1398022.png)
![2015-07-19_00 03 05](https://cloud.githubusercontent.com/assets/246232/8764935/b31c9622-2da9-11e5-8db7-6d1da685a0eb.png)

**Comment by KingLemming** [comment]
Took people long enough to find that one. An unfortunate experiment. :/

**Comment by adudney** [comment]
:-/ I was actually very surprised it hadn't been reported yet. But, to be fair, it works great on things like caches or strongboxes, because all sides work the same. On machines it's a completely different case, with a lot of different factors that could go into the bug. After I discovered it was pulling from the input it took me a good 10 minutes of extra tinkering just to figure out that it was the opposite side that was being pulled.
