### ISSUE TITLE
[Thermal Dynamics] Last fluiduct placed does not connect properly, visually

### ISSUE THREAD

**Issue by Zsashas** [CoFH/Feedback#711]
EDIT: Forgot to add, 1.12.2

![2017-12-08_23 01 44](https://user-images.githubusercontent.com/6917535/33793372-decd17c4-dc6b-11e7-9748-aa728a3b828d.png)
![2017-12-08_23 01 47](https://user-images.githubusercontent.com/6917535/33793373-dee3fb88-dc6b-11e7-81fb-b80af4c6a4c9.png)
![2017-12-08_23 02 14](https://user-images.githubusercontent.com/6917535/33793374-def925e4-dc6b-11e7-8c2b-f58994395aae.png)
![2017-12-08_23 02 18](https://user-images.githubusercontent.com/6917535/33793375-df0e74b2-dc6b-11e7-94a2-b000ef0268bf.png)

**Comment by KingLemming** [comment]
Yeah we've had scattered reports of this but it's always been x-mod interference - something on the server or in the pack screws up normal block placement and updates.

If you can make it happen with only our stuff, then please let us know.

**Comment by Zsashas** [comment]
What mods have caused this previously?

**Comment by KingLemming** [comment]
We don't know, but it's only ever happened in modpacks and in conditions where the server was stressed. 

We've tested with literally tens of thousands of ducts with a relatively small modlist and can't make it happen.

**Comment by TheSnowyChickens** [comment]
Hello, I have the same bug. 
This happends after every relog, I have a chunk-based Base and it occurs on 2 points above Pulverizer and between a connection from Redstone Energy Fluxducts to Signalum-Plated Itemducts.

(MC 1.12.2 and all mods up to date (21.1.18))
