### ISSUE TITLE
[CoFHcore] Mod sorting issue stops Forge loading

### ISSUE THREAD

**Issue by craft90** [CoFH/Feedback#712]
There seems to be an issue for me when it comes to cross mod compatibility. I got quite a few mods, about 70 of them, but as I try to start MineCraft it crashes while loading. It runs fine without any other mods than CoFH but as soon as I add more mods it starts to behave bad. I need to restart Minecraft several times before it launches properly. The issue seems to steam from CoFHAPI:power. I don't have the log atm but I'd got this screenshot. Also no crash report was generated either. Only a Forge log which do reset each time you reload Minecraft. I'll try to snatch the log next time the error happens but for now I only got this:
<a href="http://s151.photobucket.com/user/Nick_Jason/media/COFHcoreError_zpskbhhfx95.png.html" target="_blank"><img src="http://i151.photobucket.com/albums/s146/Nick_Jason/COFHcoreError_zpskbhhfx95.png" border="0" alt=" photo COFHcoreError_zpskbhhfx95.png"/></a>

**Comment by KingLemming** [comment]
That's not on us, but the other mods in there being stupid. Sorry. :/

**Comment by craft90** [comment]
OK, thanks. What do you suggest I do then? I don't want to remove CoFH completely.

**Comment by KingLemming** [comment]
All you can really do is sort of trial and error and figure out what the culprit is. Definitely update ALL of your mods.

Ultimately, you either have to live with the sorting nonsense or remove the one actually causing it. Try the jar surgery too - that really might help.

**Comment by craft90** [comment]
OK. I assume the culprit is one of the mentioned mods. I'm going through them atm, updating any outdated ones.

JAR surgery?

**Comment by KingLemming** [comment]
Open up the jars, find the "cofh" folder, delete it. Except from CoFH Core.

**Comment by craft90** [comment]
Thanks. I'd update all the mods I thought might cause the issue. It worked fine for a bit but after a Minecraft crash the issue popped up again. I grabbed all the logs but couldn't find the referenced one.

I guess I could try the JAR surgery then

**Comment by craft90** [comment]
After surgery I got yet another error.

![cofherror2](https://cloud.githubusercontent.com/assets/12762624/8766266/890456ee-2e31-11e5-9120-a3cf7b8357de.PNG)

So I continued on with JAR surgery of those files... and got another error, probably because I removed the cofh folder from ThermalExpansion...

http://pastebin.com/9j4difw4

I guess I can't make this private modpack work with these mods. :/

**Comment by KingLemming** [comment]
What is redgear_core?

**Comment by craft90** [comment]
I have no idea. It's a mod which automatically got downloaded by some other mod. If you're unfamiliar with it, I reckon it isn't Red Stone Arsenal then?

**Comment by craft90** [comment]
EDIT: OK found it. This is the mod which automatically gets downloaded: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1289075-red-gear-core-2-1-0

Also here's the fml-log-latest which may detail the error:
http://pastebin.com/YnSsPeqY

**Comment by bangbang93** [comment]
i got the same error and also has red gear core

**Comment by craft90** [comment]
Try updating all your mods. In my case it was cos Binnie Core was of an older version. It seems to be an RedstoneFlux API mismatch.

**Comment by bangbang93** [comment]
i remove red gear core and snowfall :)
