### ISSUE TITLE
MFR Planter incompatible with Pam's Harvescraft crops and Random Things' Fertilized dirt

### ISSUE THREAD

**Issue by Nostras** [CoFH/Feedback#713]
It appears the MFR planter works fine with standard seed and fertilized dirt, also works fine with vanilla seeds and fertilized dirt, but not both.

Very easy to reproduce, the planter flat out doesn't work.

Edit: It does work with untilled fertilized dirt but does not with tilled fertilized dirt. Exactly the opposite of right clicking.

I'm getting the feeling the fault lies with random things and not MFR.

**Comment by skyboy** [comment]
This issue is not on MFR's side.
