### ISSUE TITLE
download

### ISSUE THREAD

**Issue by fuefrhagbagfberaogyhb** [CoFH/Feedback#714]
im trying to download the version for 1.7.10 but instated it's downloading 1.12.2!
why???????

**Comment by fuefrhagbagfberaogyhb** [comment]
ps I just spammed my keyboard for a name...

**Comment by covers1624** [comment]
![](http://ss.covers1624.net/5pnign6.gif)

**Comment by covers1624** [comment]
You probably pressed the big green download button, that button downloads the latest, not the file you are looking at.
