### ISSUE TITLE
Redstone Energy Conduits loose connection to Mekanism Windturbine

### ISSUE THREAD

**Issue by leglerm** [CoFH/Feedback#714]
As title described
the chunkloader in the image is an additional one that i placed down later. It should normally loaded by the main chunkloader or even the player.
Also Waila is wrong its not set on freq. 0 it is set on our own freq. 1

![2015-07-19_23 56 42](https://cloud.githubusercontent.com/assets/13408657/8768038/e3521538-2e71-11e5-812c-d3d8cad74210.png)

**Comment by KingLemming** [comment]
Yeah, Mekanism does this.
