### ISSUE TITLE
Fluid Transposer not accepting anything

### ISSUE THREAD

**Issue by DenizUgur** [CoFH/Feedback#715]
Okay I was trying to make Flux Crystal's from Redstone Arsenal. Basically I need to put Destabilized Redstone and Diamond to make that Crystal. So I tried putting Fluid Destabilized Redstone and it was successful but when I try to put Diamond it won't accept and the GUI and NEI's Recipe GUI doesn't match.
Mod is in the latest version
<img width="1552" alt="screen shot 2015-07-20 at 01 09 15" src="https://cloud.githubusercontent.com/assets/7467169/8768087/0b777dc8-2e7c-11e5-92a0-e60d54ff29cc.png">
<img width="1552" alt="screen shot 2015-07-20 at 01 09 25" src="https://cloud.githubusercontent.com/assets/7467169/8768088/0b78e4ec-2e7c-11e5-98f3-915d62d4bc58.png">

**Comment by KingLemming** [comment]
"Mod is in the latest version"

No it isn't.

**Comment by DenizUgur** [comment]
Well I'm sorry, you're right but I downloaded the latest version just yesterday

**Comment by KingLemming** [comment]
From where? The fix has been out for like a week. :/
