### ISSUE TITLE
[BUG] Energy Cell can't connect to BuildCraft

### ISSUE THREAD

**Issue by Mxater** [CoFH/Feedback#715]
Mod: Thermal Expansion 5.3.7.31
Mod List: https://pastebin.com/PCxsWGHL
No crash log.

I try to connect a Energy Cell to a Mining Well (BuildCraft 7.99.12), but the energy is not transmitted from one block to another, putting them together or through cable.

![image](https://user-images.githubusercontent.com/4630666/33801846-0118b2e4-dd47-11e7-9e0d-d79672503b68.png)

thank you very much.

**Comment by KingLemming** [comment]
That is 100% on BuildCraft. They use their own new incompatible power system.

**Comment by grydian** [comment]
In the past when RF was first implemented the conduits would convert to MJs on the fly.  Is that planned on being reimplemented?

**Comment by KingLemming** [comment]
Nope. BC wants a totally different power system. It'd be wrong to subvert that.

**Comment by grydian** [comment]
Ah I see no worries I was uninformed thanks.
