### ISSUE TITLE
Machine crash.

### ISSUE THREAD

**Issue by Allescrafter** [CoFH/Feedback#716]
When I trying to place a Pulveriser my Game is going to crash.
I opend the World in MCEdit. The Pulveriser is placed but I can't open the world in Minecraft.
So I removed the Pulveriser in MCEdit. And now I can open the World.

This is the crash Report:
https://pastebin.com/KhfmF13j

Mods:130
RAM:10GB
System:Windows
CPU:Intel i2 Duo
GPU:Nvidia GT 610

**Comment by covers1624** [comment]
Disable optifine's connected textures, they are not supported.
