### ISSUE TITLE
[TD] Machines/Terrain Smasher cannot eject items through duct connections bearing a redstone relay

### ISSUE THREAD

**Issue by Tora-B** [CoFH/Feedback#717]
Fluids and RF can pass through redstone relays, and so can items, except if the machine is configured to eject through a connection bearing a redstone relay. Redstone relays do not appear to block duct transfer in all other cases:
Ducts will export through connections that have a relay on them.
Retrievers can import from a distant connection that has a relay on it.
Machines and terrain smashers can eject fluids through connections bearing a relay.

Test setup:
![2015-07-19_23 19 46](https://cloud.githubusercontent.com/assets/11331588/8770332/b2e3f6be-2e6c-11e5-8bc2-dcf82f19159a.png)

The terrain smasher will break one block, then ignore subsequent blocks, presumably because it's still got something stuck in its craw. Remove the redstone relay, and the block will appear in the duct, and the terrain smasher will begin working again. Same thing happens with a pulverizer ejecting through a duct with a relay on the connection.

Versions:
CoFHCore-[1.7.10]3.0.3-303
RedstoneArsenal-[1.7.10]1.1.1-89
ThermalDynamics-[1.7.10]1.1.0-161
ThermalExpansion-[1.7.10]4.0.3B1-218
ThermalFoundation-[1.7.10]1.2.0-102

**Comment by Tora-B** [comment]
Paging @rwtema? I'm told that this _might_ be fixed in dev already, and that you'd be the one to know.

**Comment by KingLemming** [comment]
I'm not sure it was ever a "bug" to be honest, but the requested behavior is now present in dev.

**Comment by Tora-B** [comment]
I'm just going off your comment in #655 where you said that you were changing the behavior, and that the current behavior is different (partially "fixed") than what was reported in #655.
