### ISSUE TITLE
[Thermal Foundation] Forge Lexicon function crash

### ISSUE THREAD

**Issue by CastielAngelow** [CoFH/Feedback#718]
Crash Log below
[crash-2017-12-11_15.15.03-server.txt](https://github.com/CoFH/Feedback/files/1548089/crash-2017-12-11_15.15.03-server.txt)

Issue with Thermal Foundation Forge Lexicon item.
I set preferences for oreCopper to be Thermal Foundation one. When I held Forge Lexicon and used "V" to get visdom, game was fine. Then I "Q'ed" items on ground (Copper Ore from Mekanism) and while trying to pick up, game crashed. Log provided. Used mods in crash log. Thanks for help.

**Comment by KingLemming** [comment]
Yes, this is caused by a Forge change. Your Forge is too new. The next release will accommodate this, but right now you just need to downgrade to the recommended build and not cutting edge.
