### ISSUE TITLE
Crash in 1.7.10

### ISSUE THREAD

**Issue by Igorwars** [CoFH/Feedback#719]
I did not got a crash report or anything else.
When I used the Mods (CoreFH, Thermal Dynamics, Thermal Expansion, Thermal Foundation) added to the "Tekkit Legends" Pack it crashes and i dont know why. The Only thing I believe it could be is, that CoreFH in an older version was already given in the Modpack and the new and old version wont work together or alone.

Sorry for my English

**Comment by KingLemming** [comment]
Sorry, but 1.7.10 is unsupported.
