### ISSUE TITLE
FileNotFoundException: Missing armour and tools (Thermal Foundation)

### ISSUE THREAD

**Issue by CSOmini** [CoFH/Feedback#72]
Hello,

my problem is: in Thermal Foundation 1.7.10 (1.0.0RC1-35) I'm missing EVERY texture of tools and armour, besides invar. Every other thing is missing -  in the folder where the armour and the tools are  there's no folder for silver or any other ore. In any other version I downloaded I didn't find the files too. What can I do? Thanks for help! If you need more information, tell me.

**Comment by KingLemming** [comment]
You are using an alpha version. Don't do that. Download only from Curse, NOT CurseForge.

We're still working on the textures.
