### ISSUE TITLE
[Request] Hide disabled items

### ISSUE THREAD

**Issue by MasterFee** [CoFH/Feedback#72]
Would be pretty cool if your mods hide all disabled items (from JEI at least). Only disabling the recipe but still having the items in game doesn't seem logical...

**Comment by KingLemming** [comment]
That's done intentionally to provide pack makers with a way to easily disable default recipes and then use whatever method they would like to add their own.

**Comment by MasterFee** [comment]
Oh I get it. Thanks for the fast response ;)

**Comment by bookerthegeek** [comment]
@masterfee you can hide them with craft tweaker.
