### ISSUE TITLE
Fluid transposer issue: Previous functionality not found. 

### ISSUE THREAD

**Issue by fallenhunter1** [CoFH/Feedback#720]
Ok, forgive the paste from your instruction page, want to make sure I follow them.

    Include the mod name and version.
Thermal Expansion: 5.3.7.31

    Include a pastebin (or equivalent) link to a list of all your mods.
https://pastebin.com/8C7TJFBL

    Include the crash log
Not reporting a crash. So not included.

    Be descriptive.

I did do a quick search, there are no similar open issues on your github, there may be an older one that's closed.. if so, forgive an old man.

In previous versions of this mod, you were able to fill Thermal (or other), tank/drum, in whole or part, with 'leftover' melted liquids in the Fluid Transposer. Allowing you, esp in early game to use one machine for multiple liquids. This version does not seem to allow this (tested using the Thermal basic tank, no other tanks from other mods will even go into the machine). I am unsure if this is a bug, or intended. If intended please mark this complete and otherwise ignore it. 
I solved this by breaking the machine and losing the 150mb of glowstone (not a big  loss, but hey, I was just surprised it did not work). However, if this is not intended, figured I should let someone know. 

    Be respectful. Always, us old folks were taught that from early age.
    Use proper grammar and spelling. No promises, but I tried.

Thanks for your time, effort and talents for creating such a wonderful set of mods,

Fallenhunter

**Comment by KingLemming** [comment]
This is intended due to a fairly radical change in how Forge deals with fluids and fluid containers. However, I'll see if there's a way to address this.

As an alternative, you can actually place the tank next to the Transposer, set the mode to "Empty" and it will pump the fluid out into the tank, if the side is configured for it.

**Comment by KingLemming** [comment]
I've readded "support" for this and it'll *probably* be okay, lol.
