### ISSUE TITLE
[Suggestion] Make ItemShieldCore override isShield

### ISSUE THREAD

**Issue by mallrat208** [CoFH/Feedback#721]
Currently Shields derived from CoFHCore's ItemShieldCore function exactly as expected. They block damage, may or may not look spiffy, and generally do shield like things. 

What they cannot do is be checked if they are shields for the purposes of other mods. Overriding isShield  would allow other mods to verify a held item of ItemShieldCore is actually shield instead of a pretty paper weight.

**Comment by covers1624** [comment]
Ahh, Yes this is a newly added method from forge, not sure when it was added (1.12.2 cycle maybe). This is something we definitely want to do.

**Comment by KingLemming** [comment]
Yeah, isShield actually came along after I made shields. :P
