### ISSUE TITLE
Minecraft refuses to run with CoFH-Core

### ISSUE THREAD

**Issue by KKomical** [CoFH/Feedback#721]
Whenever I try to start the game with CoFH core installed it crashes at startup (not responding). I don't know if it's because my computer is trash or if it is the mod's fault (it is the only one I have other than Forge). I have tried a clean install of forge and Minecraft, I've updated java (32-Bit) but nothing has worked. What do I do?
Mod Name: CoFH Core
Version: [1.7.10] 3.0.3-303 (I have also replaced it with [1.7.10] 3.0.3-305)
Mods:
>Forge [Version 10.13.4.1492-1.7.10]
>CoFH Core
I Can't find the crash report
Pls Help ;-;

**Comment by KingLemming** [comment]
This is a tech support request, as the mod clearly works, or we'd have thousands of these reports.

It's something with your computer and/or Forge. Possibly disable the splash screen, there's an option to do that. If that doesn't work, try the IRC channel.

**Comment by KKomical** [comment]
Uhhh
![error2](https://cloud.githubusercontent.com/assets/13441222/8814349/64212b50-2fd9-11e5-9790-9c51b51bfc03.png)

**Comment by KingLemming** [comment]
That one there's already an answer for. It's pretty clearly in the closed issues. ;)

Use -Dforge.forceNoStencil=true as a JVM argument.

**Comment by KKomical** [comment]
It worked thank you so much kind sir. I would donate if I had a Paypal (or money for that matter)
