### ISSUE TITLE
Suggestion/Help: XP Juice from Reliquary vs Essence of Knowledge

### ISSUE THREAD

**Issue by Akitori** [CoFH/Feedback#722]
So i use Reliquary in my modpack, and i usually rely on the hero's medallion to store all my levels. One of the things i wanted to ask/request is the ability for XP juice to be used in machines, or at the least some method to use the two together. Currently, Hero's Medallion only outputs XP juice to any tank, rather than essence of knowledge. Maybe its me being lazy, but i get annoyed at switching from my medallion, back to levels, then put them in my tome, and turn that into essence of knowledge that way.

The main reason i ask this is due to the fact that in the video shown below, they are exactly the same in all regards, down to the amount of Experience given back. 

I ask for perhaps some augment in the future? or something to allow compatibility if possible. Thank you for your time. (also perhaps this is already in and i haven't seen it, though jei says that's a no...)

https://youtu.be/-EGRhXZhdQs

**Comment by KingLemming** [comment]
I realize it's the "same," but under the hood it isn't, they're two different fluids and not unified. I actually did this intentionally because I simply can't be sure of what the various power levels were on the other experience fluids.

I'll think about it, but I'm not promising anything.

**Comment by KingLemming** [comment]
Okay, I had already rewritten the tome slightly before you asked. It now just does all xp/levels at once. It's just easier that way.

What I've now also added is that the Tome will recognize a tank full of xpjuice and also be able to drain that. But I'm afraid that's all the compatibility I can reasonably add.

**Comment by Akitori** [comment]
that's fair, thanks man!
