### ISSUE TITLE
[MFR] [Suggestion] Add meat ingots as Pam's Harvestcraft OreDict AllMeat

### ISSUE THREAD

**Issue by abculatter2** [CoFH/Feedback#723]
So that it can be used in all recipes that use meat in a similar vein to tofu, because it just makes sense and I don't think it really breaks any balance. (That isn't already broken by harvesters pooping out soybeans, anyway)

**Comment by skyboy** [comment]
https://github.com/skyboy/MineFactoryReloaded/blob/master/src/powercrystals/minefactoryreloaded/setup/recipe/Vanilla.java#L102
