### ISSUE TITLE
Weird Fractionating Still Refined Storage interaction

### ISSUE THREAD

**Issue by Gorden211** [CoFH/Feedback#724]
![2017-12-12_21 34 47](https://user-images.githubusercontent.com/25781557/33907244-ccf9623e-df84-11e7-8a00-b3c6e553c982.png)
I use an importer on the back of a Fractionating Still
![2017-12-12_21 34 55](https://user-images.githubusercontent.com/25781557/33907247-d005b55e-df84-11e7-903c-b30a0c2ea7a8.png)
The importer is set to an empty blacklist (although it seems RS handles empty whitelist and empty blacklist both as if they were empty blacklists)
![2017-12-12_21 35 04](https://user-images.githubusercontent.com/25781557/33907248-d10fa400-df84-11e7-8f78-c79d9fb987e0.png)
Here you can see that even though the output for the secondary slot is selected to output to the back the Tar stays in. This also happens with the Sulphur in the Still next to it.
![2017-12-12_21 35 14](https://user-images.githubusercontent.com/25781557/33907252-d317dd76-df84-11e7-8248-adf24b4f21f8.png)
Changing the output to the back to the fluid inventory makes the Tar (and respectively the Sulphur) disappear in the Still, as they get imported into the RS system.
![2017-12-12_21 35 30](https://user-images.githubusercontent.com/25781557/33907256-d4d10d22-df84-11e7-9265-9cb01310975c.png)
Here just so you can see the orientation of the machine so it is correctly configured.
When I set the back to not do anything, so blank it does not import. Outputting into a chest works as intended however.
No idea if this is an RS issue or on your end. However I do want to state, that the pulverizer seen in the last image is configured to output the secondary product into the back also into an importer and this works fine.

I'm using the latest version of all the Thermal mods and there are Reflux Column Specializations in both Fractionating Stills, but testing without the specialization didn't change anything.

**Comment by KingLemming** [comment]
Fixed, kind of. The red side was revealing a slot it shouldn't have, and the yellow side wasn't revealing a slot it should have.

However, auto-eject still should have worked, so what seems to be the case is that RS doesn't allow things to eject into it - it MUST extract. Or at least the importer has to.

**Comment by Gorden211** [comment]
I thought it might have been something along these lines. 
Glad it was this easy to fix. Thanks!
