### ISSUE TITLE
Minor Ore json annoyance/bug

### ISSUE THREAD

**Issue by the-creamster** [CoFH/Feedback#725]
Forge: build 1481
Mod Versions: latest
Curse client instance: beta release

I'm an admin for a small aussie community and was given the task by the head admin to tweak the oregen which thanks to the "config/cofh/world/xxx.json; xxx=filename" files makes it really simple to achieve the said task but for two days now i have been "mentally hitting my head against a wall" because all but 3 ores aren't generating (forestry apatite, railcraft sulfur, railcraft saltpeter) regardless of what the numbers are in the .json file.

"apatite": {
        "template": "normal",
        "block": {"name": "Forestry:resources"},
        "material": "minecraft:stone",
        "clusterSize": 64,
        "numClusters": 16,
        "meanHeight": 96,
        "maxVariance": 16,
        "retrogen": "true",
        "biomeRestriction": "none",
        "biomes": [
        ],
        "dimensionRestriction": "blacklist",
        "dimensions": [
            -1
            1
        ]
    },

I spent an hour yesterday changing the "numclusters" and "clustersize" to values that were semi-redicilous and yet it still wasn't generating so i just gave up in frustration. Incase you ask the question "are the parameters correct?"; they are as every mods ore generation is disabled in there own config, even disabled vanilla oregen in the thermal foundation "common.cfg" and using the "vanilla.json" instead and i see vanilla oregen. So its not the json files themself as they pass in a json checker and all ores are generating except the 3 previously mentioned.

My question is "why is forestry apatite not generating?"

Thanks, The_Creamster.

**Comment by skyboy** [comment]
Need the startup log.

**Comment by the-creamster** [comment]
Here you go: https://www.dropbox.com/s/cap4k86hv2nhb0v/fml-client-latest.log?dl=0

**Comment by skyboy** [comment]
https://paste.kde.org/podg1lmvv

Your files are not valid. Pay attention to the errors in your startup log.
