### ISSUE TITLE
[Thermal Expansion] Allow custom machine recipes

### ISSUE THREAD

**Issue by ImbaKnugel** [CoFH/Feedback#725]
At the moment machine recipes are very restrictive. For example it is impossible to add a recipe that changes dependening on NBT data. Could you consider adding interfaces similar to `IRecipe`. This would allow addons to provide their own recipe logic.

**Comment by KingLemming** [comment]
Do you have any use cases for this?

Offhand, this has the potential to completely circumvent Augment logic and restrictions and I just can't think of any cases where adding a bunch of recipe complexity (and computational overhead) will provide substantial benefit.

I'm willing to consider it, but the balance and CPU implications worry me.

**Comment by ImbaKnugel** [comment]
I was trying to add a recipe where the output depends on an NBT tag from the input.

I'm not sure how the change would impact balance? Wouldn't this require another mod that deliberately registers recipes to circumvent augments?

**Comment by KingLemming** [comment]
What specific NBT tag? Is this filling a known quantity, like energy/fluid? I'd really like more context here.

NBT sensitivity also changes the underlying hashing logic, which while doable...isn't ideal in every machine.

And you're correct, it would still require other mods to abuse it.

**Comment by ImbaKnugel** [comment]
So, my specific use case is:
* I basically have a mob version of the Florb. So my itemstack contains the entities nbt data.
* I now want to add a Magma Crucible recipe that turns specific mobs into different fluids. (So for example Blaze -> Pyrotheum, Basalz -> Petrotheum)

**Comment by KingLemming** [comment]
Oh. Hah, yeah that's something that's already planned - mob capture and "processing." Look at one of the commented out augments in ItemAugment (Enstabulation Chamber).

Great minds and all.

The Magma Crucible is already NBT-sensitive so this is already possible, though I'm better understanding what you mean with the IRecipe now.

Let me think on this. :)

**Comment by ImbaKnugel** [comment]
Is this already possible? I'm not sure how I would make the recipe only compare specific nbt tags. 

The Thermal mods could really use a ToDo list so I don't work on things that are already planned :D (are magnets going to be a thing?).

**Comment by KingLemming** [comment]
Yep. Magnet is happening as part of Thermal Innovation. (Along with Drills, Chainsaws, Jetpacks, and Elytra.)

**Comment by ImbaKnugel** [comment]
I should really ask that before I start working on an addon mod. Just got done implementing the "Monster Orbs" and [Magnets](https://github.com/ImbaKnugel/Gadgetron). Ah well, time to think of new stuff.

**Comment by KingLemming** [comment]
Well as I've mentioned before, I don't get a monopoly on ideas. So it's not fair for me to deny you a mod just because something is planned for Thermal down the road. 

As a general rule though, you should probably just know that I want the Thermal Series to be developed to the point where it could exist alone as a modpack and it would feel complete. So there's a LOT I'd like to add. I just need the time to do it.

**Comment by KingLemming** [comment]
BTW, if you're curious, it is *uncanny* how similar your ideas are. It's almost like you were reading off this document:

![2017-12-13 17_03_16-d__dropbox_cofhdev_design_roadmap txt - sublime text](https://user-images.githubusercontent.com/2118598/33964762-8af445d6-e027-11e7-957c-5c7b444566fa.png)

And yes I know that says 5.3, roadmap was altered but that list was written months ago.

**Comment by Gorden211** [comment]
I don't know how feasible it would be, but wouldn't it be a good idea for both of you to work together, if you are working on basically the same things anyway.
I mean ImbaKnugel's mod is really cool, I like it a lot and he seems to know his way around COFH Core and things related to Thermal mods.

Don't want to overstep any boundaries, but I thought I might state the obvious hanging in the air.
Of course I don't know if that's something both of you might even consider, but I thought it might be worth asking.

**Comment by KingLemming** [comment]
We just had that chat actually. :)

**Comment by Gorden211** [comment]
Awesome. Always nice to see collaborations happening.
I hope it works out.

**Comment by KingLemming** [comment]
Calling this one resolved. It's something that currently I don't see a true need for as it could potentially overcomplexify the machines.
