### ISSUE TITLE
TiC Slime saplings not working in Phytogenic Insolator

### ISSUE THREAD

**Issue by Phytoboi** [CoFH/Feedback#726]
I hope no one has yet reported this, though I found nothing on this. But yeah Tested with Mycelium Substrate and Sapling Infuser, none of which worked.

**Comment by KingLemming** [comment]
What's your mod version? It sounds like you're out of date.

If the Mycelium Substrate still exists in your version, you need BOTH that and the Sapling Infuser to grow them.

**Comment by Phytoboi** [comment]
My bad, sorry should have tried that

**Comment by KingLemming** [comment]
Heh, no problem.
