### ISSUE TITLE
Error in server logs

### ISSUE THREAD

**Issue by QORTEC** [CoFH/Feedback#726]
The following error is spaming my servers log files:
https://gist.github.com/QORTEC/c189bcc36bc2920854e0

I can give you the whole log file if you want it but be warned its large.
[The log file it use to be ~10MiB before the bug, now its at 525MiB!!]

**Comment by KingLemming** [comment]
Please report that to Carpenter's Blocks, that is the mod causing it.

**Comment by QORTEC** [comment]
Thank you!!
