### ISSUE TITLE
New idea for an add-on, +Shaders bug

### ISSUE THREAD

**Issue by DrakoAlcarus** [CoFH/Feedback#727]
I was thinking about another module to Thermal Expansion. It adds exploration, and adventure, as well as new mobs. Worldgen could be abandoned factories, abandoned quarries, wastelands, and Large, complex dungeons. New tools, too. Flux War Hammer, Flux Wand (to use the mana metal and primal mana), Flux Hookshots (Leadstone: basic, Hardened: Longshot, Redstone/Reinforced: Manual), and a Flux Crossbow. The new mobs, I'm not sure. The dungeon loot can consist of metals, coils, rare upgrades, and a few other randoms. Maybe it can add a bunch of flux baubles, that have passive effects as long as they are charged.

Now... into the bug. Even with out having an actual shader pack running, the bug occurs. The covers... do things. And when the star field of the tesseract is activated, a strange shadow appears to cover the land wherever I go. In the examples, I am still using a shader pack, because no matter what, the bug occurs with the covers. The shader is: ShadersModCore-v2.3.28-mc1.7.10-f, and the shader pack is: Sildurs Vibrant shaders v1.06 Medium, but the bug happens if the shader mod is even _installed_.

![2015-07-23_09 59 42](https://cloud.githubusercontent.com/assets/12781728/8857077/f5381c20-3123-11e5-8252-95b1ab078190.png)

*Before:*
![2015-07-23_10 01 17](https://cloud.githubusercontent.com/assets/12781728/8858369/ea3f065a-312b-11e5-8bd1-692fdd40f392.png)

*After:*
![2015-07-23_10 01 26](https://cloud.githubusercontent.com/assets/12781728/8858385/00953816-312c-11e5-9461-b25195538c14.png)

**Comment by KingLemming** [comment]
Yeah, Shader mods do things that are out of our control. Sorry.

**Comment by DrakoAlcarus** [comment]
What about the add-on?

**Comment by DrakoAlcarus** [comment]
That was the whole reason I made this.

**Comment by ZeldoKavira** [comment]
Posting a feature request and a bug in the same issue is not the best idea.

**Comment by DrakoAlcarus** [comment]
I'll remake the suggestion.
