### ISSUE TITLE
Bug?: Fluxed Arrows affected by vorpal/count as melee?

### ISSUE THREAD

**Issue by Akitori** [CoFH/Feedback#727]
Hiya! So I was running my modpack today when i decided to spam normal flux arrows at mobs, with my looting and vorpal in my mainhand (for fun). I noticed that my arrow spam would result in some zombies getting killed instantly. Curious, i used another mod (dynamic sword skills) as a damage indicator (though normally it only works via melee...). While locked on to mobs, i spammed a few of the flux arrows, and some of them got boosted by Vorpal.

Is this intended behavior? Why do flux arrows count as melee?

**Comment by KingLemming** [comment]
They do not count as melee. This may be an artifact of how Vorpal is determined, however. There may not be a good way around that.

**Comment by KingLemming** [comment]
I've resolved this in dev in a somewhat generic way. It probably won't catch everything but should prevent arrows from checking the player's held items.

**Comment by Akitori** [comment]
Would that prevent the arrows from working with looting?
