### ISSUE TITLE
Suggestion: Thermal Exploration (Re-do)

### ISSUE THREAD

**Issue by DrakoAlcarus** [CoFH/Feedback#728]
I was thinking about another module to Thermal Expansion. It adds exploration, and adventure, as well as new mobs. Worldgen could be abandoned factories, abandoned quarries, wastelands, and Large, complex dungeons. New tools, too. Flux War Hammer, Flux Wand (to use the mana metal and primal mana), Flux Hookshots (Leadstone: basic, Hardened: Longshot, Redstone/Reinforced: Manual), and a Flux Crossbow. The new mobs, I'm not sure. The dungeon loot can consist of metals, coils, rare upgrades, and a few other randoms. Maybe it can add a bunch of flux baubles, that have passive effects as long as they are charged. I just thought that this will add plenty of neat features that people might love, as well as places to explore.

**Comment by KingLemming** [comment]
Some of this may come to pass, we'll see. The tools are pretty unlikely.

We'll have flux baubles in a sense, although they'll be spread out among various mods.

It's all really low on the list though, sorry. Too many other things to do first.
