### ISSUE TITLE
[1.12.2] Recipes not not using oredict names rather than specific localised name

### ISSUE THREAD

**Issue by Morpheus1101** [CoFH/Feedback#728]
In the pack im developing i have worldgen in terms of stone done via a different mod that overrides the default minecraft stone, so the only stone types from default Minecraft are Andesitre, Diorite & Granite, the diff stone type varients i have do have some of the ore dict'd as cobblestone, however various recipes to make Gravel for example using the hammer from TF requires minecraft:cobblestone rather than oreCobblestone

**Comment by KingLemming** [comment]
The only bug there is that a testing recipe got left in. Hammers are not intended to be used in that manner nor am I supporting it.

Sorry for the confusion.

**Comment by Morpheus1101** [comment]
ok, thanks for the info.

**Comment by Morpheus1101** [comment]
Same issue occurs when trying to use the Pulverizer, despite the block i have being ore dictd as cobblestone, the pulverizer dosent accept it

**Comment by KingLemming** [comment]
Yes, that's intentional. Only certain orenames are whitelisted - cobblestone isn't one of them.

**Comment by Morpheus1101** [comment]
okies, thats an easy work around, thanks again.

**Comment by KingLemming** [comment]
I can consider adding cobblestone to that list, but the general reason for it was that mods might add different types which would maybe grind to different types of gravel, etc. Maybe a bit out there I know, but stones are one of those less-standardized types of things.

For reference, the OreName paid attention to if it begins with "ore", "ingot", "block", "nugget", "gem", "log", or "plank"
