### ISSUE TITLE
[Suggestion] Thermal Cultivation's Watering Can Rebalance

### ISSUE THREAD

**Issue by Xiaminou** [CoFH/Feedback#729]
I can't help but think that just pouring water on plants should not make them grow that fast. But what if it were another liquid?
I suggest that Water Can be allowed to pour different liquids, water of course could help irrigate the crops and speed up a tiny little bit. But the main purpose would be changed to using Watering Cans to pour a Phyto-Gro liquid, higher tiers of Phyto-Gro would make plants grow faster.

**Comment by KingLemming** [comment]
Unfortunately this would be a breaking change given how the can is coded. It probably wouldn't ruin worlds, but it would mess up existing cans.

That aside, this sort of overcomplicates the can itself and I can't see an actual benefit for the players. Like, it's a direct nerf to the functionality and will require a significant industrial backend to get started. And part of the issue there is that Thermal Cultivation is ultimately meant to be playable without Thermal Expansion.

It changes the can from an early-game farming assist to a mid/late game tool.

Given all that, I'm *unlikely* to move forward with this, but I'll think on it first.

**Comment by Xiaminou** [comment]
It does complicate the Watering Can a little bit, and I had a few more thoughts regarding this suggestion.
The main point remains to add some kind of interaction between Phyto-Gro and Water Cans, now instead of it being a change to the Watering Can, maybe it could be a change to the Phyto-Gro, in my initial design I forgot that you could actually apply Phyto-Gro directly to plants to grow them.
My new proposition would be that when both Thermal Expansion and Thermal Cultivation are present there is an option to change the behavior of Phyto-Gro so it is applied through Watering Cans instead of directly by right-clicking. Or simply make Phyto-Gro more efficient when used via Watering Cans
This would allow the Watering Cans to be used early game and keep being useful in mid-to-late game.

All that being said I consider the automation of Phyto-Gro early-to-mid game, but that's probably because I play tech heavy kitchen sinks.

**Comment by KingLemming** [comment]
Ehh...I really dislike the idea of completely altering the behavior of an item based on what is loaded and what isn't. It harms thematic consistency and confuses players.

Honestly, I just don't even see the watering can as being all that powerful. Heck, compared to literally every other watering-can style tool out there, it isn't. I think it's the only one that actually requires WATER.

**Comment by tyler489** [comment]
Extra utils  2 cost water. Maybe you could make liquid phytogrow grow crops even faster. Or make it use water slowly. Is there a way to currently auto fill watering cans? That would be nice

**Comment by Xiaminou** [comment]
That was my "3rd" suggestion (if we were to number them).
You can refill the Watering Can in a Fluid Transposer so it's pretty much automated.

**Comment by covers1624** [comment]
You can also fill it from a tank, or shift right-click on water in world.

**Comment by KingLemming** [comment]
Sorry, just after giving this thought, it's more complexity than I feel is warranted for what is ultimately kind of a simple tool.
