### ISSUE TITLE
Out of Bounds exception during rendering

### ISSUE THREAD

**Issue by rinesi** [CoFH/Feedback#73]
Happens as soon as I join the server.

http://pastebin.com/uv60mSmU

**Comment by KingLemming** [comment]
I can mitigate this, but apparently you have a mod which somehow violating the contract with the energy cell and is setting its internal energy to a large negative number.

**Comment by rinesi** [comment]
Does the log list which mod? I can go file a report with them as well if needed.

**Comment by KingLemming** [comment]
It does not. I just know that the "scale" being reported back is -96, and TE's code makes that impossible unless something directly hijacks the cell.

**Comment by rinesi** [comment]
Weird. I'll ask around the server and see who is attaching what to the cell. Thanks.

**Comment by KingLemming** [comment]
Either way, I'll call this one mitigated.

**Comment by KingLemming** [comment]
Haven't pushed yet. ;)

**Comment by rinesi** [comment]
Pftt. Good enough for me. haha

**Comment by KingLemming** [comment]
Huh...but it's not crashing him? I'm wondering if MC tiself is kind of derpy on some syncing here...

Either way, fix will go live in a few hours.

**Comment by rinesi** [comment]
It was crashing him as well. Well, everyone. We found out what happened. His player data got deleted by mistake. When we restored the player data, the issue was resolved.

**Comment by KingLemming** [comment]
Interesting! So my working theory is that that somehow corrupted the underlying NBT for the world and it was just putting the wrong values into places.

That...makes sense, but yeesh. Either way, I'll leave the mitigation in place, doesn't cost anything. :)
