### ISSUE TITLE
[TE] Terrain Smasher doesn't connect to pipes

### ISSUE THREAD

**Issue by J15t98J** [CoFH/Feedback#73]
Unlike the other machines, the Terrain Smasher doesn't output to any form of piping on its output face. This was mentioned in #32, but I felt that this specific issue was overlooked, and it would be nice to have it automatically output to all piping systems, not just itemducts as the last comment suggested.

**Comment by KingLemming** [comment]
Took a look at this. It'd require a rather fundamental rewrite on our end or *incredibly* simple integration on BuildCraft's end.

We're not going to do the rewrite, sorry.
