### ISSUE TITLE
AnotherOreBitesTheDust:BerryBushes' oreberries not smeltable in TE Redstone furnace

### ISSUE THREAD

**Issue by SmokeyTheBandicoot** [CoFH/Feedback#731]
After collecting some oreberries from the mod AOBD:BB by ganymedes01, I tried to smelt them up into a fully powered basic redstone furnace from Thermal Expansion. The recipe is there, it is shown up in NEI, I just can't insert them into the smelting slot, neither by shift-clicking or mouse clicking. I even tried adding a recipe for one of the oreberry via minetweaker, it seems that the furnace just refuses to do its job. All the other TE Redstone Furnace recipes work fine. The furnace is powered. I had to smelt oreberries into vanilla furnace. I already reported the issue to ganymedes01, but it has said that ha didn't code anything that interacts with TE, so it is not anything on his side. It is a really boring thing because makes automation really complex and space-consuming (had to use hoppers and vanilla furnace). Thank you for your time.

**Comment by KingLemming** [comment]
Looked into this. The issue is actually on AOBD's end, but it's non-obvious unless you're pretty familiar with the OreDictionary.

I'll probably be able to add some sort of workaround, since from AOBD's perspective, vanilla furnace compatibility is all that's required.
