### ISSUE TITLE
[Suggestion] Coal Coke Block

### ISSUE THREAD

**Issue by Xiaminou** [CoFH/Feedback#731]
Basically the same thing Immersive Engineering has, a Coal Coke Block which is 10 Coal Coke worth of power.

**Comment by KingLemming** [comment]
This is reasonable, though I'm not sure if I'd want to do it now in 1.12 or just wait til 1.13.

**Comment by Xiaminou** [comment]
How close are we to 1.13?

**Comment by KingLemming** [comment]
Not sure. Maybe as early as January.
