### ISSUE TITLE
Make Quiver compatible with Baubles

### ISSUE THREAD

**Issue by Dragnier** [CoFH/Feedback#732]
As the title states, perhaps the quiver could be usable in one of the baubles slots?

**Comment by KingLemming** [comment]
I won't rule it out, but I don't want to add Baubles as a hard dependency.

**Comment by Dragnier** [comment]
Well, Silent's Gems and The One Probe both contain Baubles compatibility without needing it as a dependency. Maybe there are some hints in their code?

**Comment by covers1624** [comment]
It is possible, just an interface on the item with an Optional annotation should do fine.

**Comment by KingLemming** [comment]
So I've given this more thought and I honestly don't see a reason for it. It works in inventory. There's no reason for it to take up a useful bauble slot.
