### ISSUE TITLE
Nether Ores Requiring Core Version 1.7.10R3.0.4.B1 - Not on Curse for Download

### ISSUE THREAD

**Issue by chloeprince** [CoFH/Feedback#732]
This version of CoFHCore is not available for download on Curse.

The mod causing this issue is: NetherOres-[1.7.10]2.3.1RC1-19.jar
Its asking for a version of the core file 1.7.10R3.0.4.B1 which isn't available for download.

Latest on Curse is CoFHCore-[1.7.10]3.0.3-305.jar

**Comment by KingLemming** [comment]
Are you trying to download a Nether Ores alpha?

**Comment by TripOptic** [comment]
Indeed, That is what was put up on CurseForge 17 hours ago.

**Comment by KingLemming** [comment]
In the future, please let us know about this on IRC. The way that the Jenkins works and auto-uploads happen, this is a tech support request for builds that really we aren't supporting.

Alpha builds risk wrecking your world. If you can't use them immediately, it's not necessarily an issue. ;)
