### ISSUE TITLE
[Suggestion] Set Monoculture Cycle to allow Bonemeal

### ISSUE THREAD

**Issue by Dragnier** [CoFH/Feedback#734]
I would like to suggest that the Monoculture Cycle augment allow the Phytogenic Insolator to also use Bonemeal instead of PhytoGrow but with a limitation of occasionally not producing anything, never producing more than one product per operation, and no chance of extra seeds. This would allow the machine to be at least usable, especially in the early game, prior to the ability to produce a decent amount of PhytoGrow automatically.

**Comment by Gorden211** [comment]
I'm not fond of this idea honestly. It removes the necessity entirely to make Phyto-Grow if you make the machine fast enough or make a huge bunch of them.
Tbh automating the production of Phyto-Grow in early game is not even that difficult.
I'm doing it right now in my world and it just takes some resources but it's definitely managable.

**Comment by KingLemming** [comment]
I don't like this because it's inconsistent - either allow Bonemeal or don't, not only with an aug and then a chance on the primary output?

No, this requires a much larger rewrite than you're imagining it will. Sorry.
