### ISSUE TITLE
suggestion for cache

### ISSUE THREAD

**Issue by wackoamd1** [CoFH/Feedback#735]
i love TE4 ( version 4.0.3B1-218 at the moment).
the cache are awesome but atm i prefer factorization barrels because i can see the amount thats inside without a extra item.
since im used to build walls of barrels and can see in a blink of an eye how much i have.
 i would like to make the following suggestion.

since there already is a "displaybar" ( the one below the item ) on the cache , would it be possible to turn that into a digital display with item name and amount of items.

i thi nk that would look awesome , black display with red or blue numbers and letters on it.

**Comment by Tora-B** [comment]
KL made it pretty clear in #274 that updating the display every time the number changes isn't going to happen. The display is intentionally coarse to reduce the frequency that packets have to be sent to the client to inform it of the cache's contents. If you want a barrel that provides more features without regard to the performance impact, I'd suggest you look elsewhere.

**Comment by KingLemming** [comment]
The entire point of caches is to be server-friendly. This is a hard no, sorry.
