### ISSUE TITLE
Bilocation Upgrade for Activator

### ISSUE THREAD

**Issue by TinkerWorX** [CoFH/Feedback#736]
This upgrade would allow a Thermal Expansion Activator to do it's thing like it was the player who the upgrade is configured for. This is useful for situations where the player is a required component, like Thaumcraft wand usage, Hardcore Questing Mode killing quests, etc.

Functionality wise, the player would craft the upgrade, which should be in the expensive end, similar to a Resonant-level upgrade. Once crafted a player can right-click with the upgrade in hand, and it'll bind to the player. Shift-right-click will clear the upgrade. Once it has been bound to a player, it can be inserted into an Activator, and whenever the Activator performs a task, the bound player will functionality be the "source".

A limitation would be that it'll only work when the player is online, and the Activator will function like a regular Activator when the player is offline.

I could see an issue with the player position being different for activating things that rely on the player position. I don't know if it's possible to activate as the player but with the position of the Activator, but that's the point of the suggestion, to either get something started, or determine if it's not feasible.

**Comment by KingLemming** [comment]
Sorry, this is in no way feasible due to how players and fake players work.
