### ISSUE TITLE
Dynamic Sword skills and RF Shield in main hand make a interesting...Crash.

### ISSUE THREAD

**Issue by Akitori** [CoFH/Feedback#736]
So i was using another mod, dynamic sword skills with this rf shield....

Yeah idk what i was expecting but i know better now at least. 

[crash-2017-12-16_20.39.01-server.txt](https://github.com/CoFH/Feedback/files/1565241/crash-2017-12-16_20.39.01-server.txt)

**Comment by KingLemming** [comment]
Yeah, guess you can't do that. I don't think there's gonna be a fix here, sorry, it'll just be a straight incompatibility.

Although, I'd argue that this is basically how shields *have* to work with Forge, so the onus is going to be on the other mod to fix it.

**Comment by Akitori** [comment]
eh i was using the shield and the other mod in a way not put on the tin. Still, thanks at least for looking at it!

(i basically tried to use a shield as a melee weapon, whoops)

anyhow feel free to close this if you want!

**Comment by KingLemming** [comment]
Well strictly speaking you can. But I'm guessing that this is something that dynamic sword skills needs to handle.
