### ISSUE TITLE
[Suggestion] Separate channels for tesseracts 

### ISSUE THREAD

**Issue by permdaddy** [CoFH/Feedback#737]
A separate channel for items, fluids and energy would be awesome. 

For example, say I have a quarry. This quarry needs to accept power and send items. Currently, I would need a matching tesseract to send power and receive items. It would be nicer to have a tesseract dedicated to sending power, and one dedicated to receiving items and be allowed to interact with both of them from the tesseract attached to the quarry.

**Comment by KingLemming** [comment]
Okay, so do that. There's nothing preventing you under the current system.

**Comment by permdaddy** [comment]
Uhh you can only set a tesseract to 1 channel. If you do that under the current system, you need a channel for power/items for each instance that you want to use it. 

It doesn't scale up.

So in the quarry situation, I would have 3 tesseracts. One sending power, one receiving items and one at the quarry receiving power and sending items.

To send items and power somewhere else, that's 3 more tesseracts. You can't use 1 to just send power to all tesseracts and not tie it to a particular item/fluid line.

That's my suggestion, sorry if I didn't explain it clearly.

**Comment by KingLemming** [comment]
Well, your initial scenario suggested that it wasn't possible with 3.

I see what you're asking now, but it's a firm no, sorry. Tesseracts are already crazy powerful. If you're in a position to have multiple quarries running remotely, then the extra Tesseract per quarry shouldn't really be a big issue.

**Comment by Tora-B** [comment]
If you have a tesseract that's dedicated to sending power, why does it matter if the channel is shared with tesseracts that are sending items? Why do you need 3 more tesseracts to send items and power somewhere else? As long as you're routing items appropriately, there shouldn't be a problem.
