### ISSUE TITLE
Redstone Arsenal Quiver Mod Integration Broken

### ISSUE THREAD

**Issue by RacerDelux** [CoFH/Feedback#737]
MC Version: 1.12.2
Modpack: ATM3: v5.5
Redstone Arsenal: 2.3.76.18
CoFH Core: 4.3.7.25 

It seems like the quiver no longer works with any bow but vanilla Minecraft. Tried it with mystical crops, botania, twilight forest.

Can confirm that it used to work with twilight forest bows - as that is what I used.

**Comment by KingLemming** [comment]
Intentional. See #663 for why.

**Comment by RacerDelux** [comment]
I see, unfortunate. I will hold hope for an API =).
