### ISSUE TITLE
Thermal Dynamics Suggestion: Servo Upgrade To Allow Spiting Item Out In the World

### ISSUE THREAD

**Issue by RoloEdits** [CoFH/Feedback#738]
Could you add a setting to allow items spiting in the world like buildcraft pipes?

Thank you  :)

**Comment by ZeldoKavira** [comment]
Why the heck would you want this? This is so bad for servers

**Comment by KingLemming** [comment]
Ehh...technically I can see a use for it I guess, but there are blocks that do it already.

**Comment by RoloEdits** [comment]
it would be only an option like prevent over sending but for allowing items to be spit in the world (Off by default) and I don't like the way dispenser and open crates block what i can see sense there full blocks. and it would be easier for feeding a hungry node in stead of having a buffer chest to connect to BC Pipes.

**Comment by Tora-B** [comment]
Do you expect to recover the items that have been ejected from the network? If yes, then you should handle the situation better, either with an overflow system or by stopping production. If not, then perhaps route overflow to a nullifier?

**Comment by RoloEdits** [comment]
I'm sorry, I must not have explained my example clearly enough, I only meant that the option to send items in the world would be an option just like how on the filters there's a "Prevent Over Sending" option that can be toggled and this "Send Item In The World" option i was thinking would not be for sending items in the world if there's no room in a chest, i was thinking if there was only an open end of a duct not connected to anything then i want to have the option to spit the items in the world.

So for example lets say there's a chest with an impulse item duct attached, then i have that duct leading to lets say over lava for a trash can, the duct is not connected to anything its just positioned over the lava so that any items that would come out would land in there.

I do not want this to be an option if the end of the duct is connected to an inventory ,i would just want it to back-stuff like normal even if it was enabled

**Comment by Tora-B** [comment]
And how would you specify the exit point? The ducts may look like something to you, but I'm guessing that to the code, it's just a list of inventories and path information.

What is wrong with dispensers, droppers, and open crates? I've read and re-read your previous comment, but can't figure out what you're saying. Also, if you're just dumping things into a lava pit... I'm pretty sure that's exactly what the nullifier was created to replace. Creating unnecessary item entities just to burn them up in lava is a needless performance hit.

**Comment by RoloEdits** [comment]
The lava was just used as an example to show the duct not being attached to an inventory and I think the duct's know if there connected to an inventory that's how that form the end where you put servos retriever's or filters at. I'm not a modder so i actually have no clue, but i think this is how it works. so if the item traveling in the duct reaches a duct that is connected to an inventory then it will try that one and then the next just like normal and if there is no open end then it will go back just like normal and be back stuffed.My uses for this are not being use for sorting but to be used to perform action that would normal require an intermediate inventory like an open crate or dispenser.I guess a better example would be having the duct lead into an advanced academical furnace which requires items to be dropped in, so instead of having an open crate blocking from seeing inside it will drop them in there for you.

**Comment by Tora-B** [comment]
The entire path an item is going to follow, and where it's going to end up, is determined before it enters the network. It can change if the network changes before the item arrives, but it doesn't just wander randomly like BuildCraft pipes. Yes, the ducts know if they're connected to a valid inventory. What they have no way of knowing is what dead end you'd like things to drop out of. That's what something like an open crate is for. If you don't want the open crate to visually block the device you're dropping items onto, then leave some vertical space between them.

**Comment by KingLemming** [comment]
After giving this a bit of thought, you should be using any number of methods that already exist.

This includes MFR's Conveyor Belts (best option really) and Vanilla Dispensers and Droppers.

There's not really a good reason to add this to ducts.

**Comment by RoloEdits** [comment]
Thank you for your time :)
