### ISSUE TITLE
Energetic Infuser stops processing items.

### ISSUE THREAD

**Issue by Xiaminou** [CoFH/Feedback#739]
I am using an Energetic Infuser to turn Rich Phyto-Gro into Fluxed Phyto-Gro, and it got stuck processing a Rich Phyto Gro.
It's happened to me twice now, first while setting it up, it stopped processing items while one was in the central slot and I had to take it out manually to get it going again. And now a second time after I rebooted my server.

Minecraft: 1.12.2
Forge: 2562
Mods: [list.txt](https://github.com/CoFH/Feedback/files/1566258/list.txt)

**Comment by KingLemming** [comment]
Can you provide a video? I can't make this happen.

**Comment by Xiaminou** [comment]
I didn't think to record it last time and it's just random so I don't have a video yet, but there isn't much to look at anyway, just a Rich Phyto-Gro in the central slot and the progress bar not moving.

**Comment by KingLemming** [comment]
It can't be "just random," because I can't just randomly make it happen. ;) There's more to it.

**Comment by Xiaminou** [comment]
Oh I know, nothing is ever random, it's just a shorter way of saying "I don't know what caused it".

**Comment by Gorden211** [comment]
Yep I had this happen as well. It happened when the Rich Phyto-Gro is put into the processing slot, but the energy barely is not enough to process it into Fluxed Phyto-Gro. Then it stays in the processing slot and doesn't restart the process once more energy is provided to the Energetic Infuser.

**Comment by KingLemming** [comment]
Yup. This is correct. Unfortunately, I'll probably have to rewrite the machine to handle this.

**Comment by KingLemming** [comment]
Wasn't as large of a rewrite as I feared.
