### ISSUE TITLE
Fractionating Still accepts all fluids

### ISSUE THREAD

**Issue by Ar4093** [CoFH/Feedback#74]
Not sure if this is intended, but the Fractionating Still will accept any fluids, even ones that don't have a recipe (e.g. Lava). The only way to free up the machine again is to break it, losing the contents.

Modpack: FTB Beyond: Thermal Expansion 5.0.1.73 and ThermalFoundation 2.0.1.68

**Comment by KingLemming** [comment]
Definitely not intended. :)
