### ISSUE TITLE
Grinders do not produce essence if placed in peaceful mode.

### ISSUE THREAD

**Issue by killerscorpion** [CoFH/Feedback#74]
This is for MineFactory Reloaded ver. 2.8.0RC6 with Forge 10.13.2.1286. I have all the latest CoFH mods installed. The issue is that MFR grinders are not producing mob essence if the grinder was placed down in peaceful mode. After you place the grinder and switch to Normal mode, it still does not produce mob essence. Now if you place the grinder while in Normal it starts to produce mob essence. And if you switch to peaceful and then back to normal it still works. Long story short, grinder will not produce mob essence at all if it was placed while in peaceful mode.

**Comment by skyboy** [comment]
Fixed by https://github.com/skyboy/MineFactoryReloaded/commit/2664f6ae4d3ace6ec6acc03e74afd094f8f4588c

**Comment by killerscorpion** [comment]
so can i get some feedback? is it going to be fixed in the next version or is it fixed in the current version?

**Comment by bochen415** [comment]
@killerscorpion http://minecraft.curseforge.com/mc-mods/66672-minefactory-reloaded/files
Check the newest version. 
Disclaimer: alpha versions can make you save go poof. Better stay on the version you have.
