### ISSUE TITLE
Weird Flux Duct textures when Optifine's Anisotropic Filtering is set to ON

### ISSUE THREAD

**Issue by bryanlim50** [CoFH/Feedback#740]
Happens regardless of AF setting(1-16x), so long as it's on.

Minecraft ver. : 1.12.2
Forge ver. : 14.23.1.2555
Modlist : [list.txt](https://github.com/CoFH/Feedback/files/1567665/list.txt)

![Screenshot](https://user-images.githubusercontent.com/19260916/34103537-ff12e522-e427-11e7-9727-116cac3a8ab5.png)

The flux ducts are the grey/weirdly coloured tubes

**Comment by KingLemming** [comment]
Yeah Optifine is just outright unsupported, sorry. There are too many rendering hacks that just mess things up, and since they are closed source, any sort of compatibility is impossible.
