### ISSUE TITLE
Portable tank upgrade duping

### ISSUE THREAD

**Issue by thenextelement** [CoFH/Feedback#741]
this is happening on the latest version of thermal expansion
https://imgur.com/a/erT0J

**Comment by ImbaKnugel** [comment]
Duplicate of #709. Seems to already be fixed.

**Comment by KingLemming** [comment]
In Dev, yes. I'm on vacation but will see about an update.

**Comment by thenextelement** [comment]
i only scrolled through a few issues, i kind of figured this was noticed.
