### ISSUE TITLE
[COFH Core] Unable to Disable Enchantments in the Configuration file.

### ISSUE THREAD

**Issue by TeetoKaziim** [CoFH/Feedback#742]
Minecraft Version: 1.12.2
COFHcore Version: 4.3.7.25
Forge Version: 14.23.1.2577
```
Enchantment {
    # If TRUE, the Holding Enchantment is available for various Storage Items. [default: true]
    B:EnableHoldingEnchant=false

    # If TRUE, the Insight Enchantment is available for various Tools and Weapons. [default: true]
    B:EnableInsightEnchant=false

    # If TRUE, the Leech Enchantment is available for various Weapons. [default: true]
    B:EnableLeechEnchant=false

    # If TRUE, the Multishot Enchantment is available for various Bows. [default: true]
    B:EnableMultishotEnchant=false

    # If TRUE, the Smelting Enchantment is available for various Tools. [default: true]
    B:EnableSmeltingEnchant=false

    # If TRUE, the Vorpal Enchantment is available for various Weapons. [default: true]
    B:EnableVorpalEnchant=false
}
```
Still results in the disabled enchantments showing up in the game on enchanted books. I'd specifically like to be able to disable the Leech and Holding enchantments for my modpack, as:
- I am only using COFH world and Thermal Foundation, and don't have any items the holding enchant works on.
- I am creating a pack with no natural regeneration, and am making other forms of healing less available, and the Leech enchant is a bit stronger than I'd like, in that context.

**Comment by KingLemming** [comment]
The enchantments are disabled in that they cannot be applied to anything. It doesn't remove them completely, though. That'd be reckless and potentially screw up existing worlds.

This is working as intended - I can't prevent the books from showing up as that's vanilla logic. But the enchants themselves can't successfully be applied to anything, except in Creative Mode (again, vanilla logic).

**Comment by TeetoKaziim** [comment]
Okay, I can see why doing that could be potentially problematic.

It appears the problem maybe lies with the 2 dungeon mods I'm using: Roguelike Dungeons and Doomlike dungeons.

Both populate their dungeons with loot chests, that include, among other things, enchanted books with random enchantments on them. And that's where I'm still getting holding books and leeching books. I'm not sure what kind of programming they're doing (I have next to no knowledge myself) to pick the enchantments for the books in their chests, but perhaps there is some better way they could be doing it.

Thankyou for the clarification, and your time and patience.
