### ISSUE TITLE
Redstone duping when crafting Ender Pearls

### ISSUE THREAD

**Issue by notacompletemoron** [CoFH/Feedback#743]
![redstonefromenderpearls](https://user-images.githubusercontent.com/12620139/34139396-d5e6ce2a-e431-11e7-80d3-2e557c3aeafb.JPG)
![redstonefromenderpearlsdupe](https://user-images.githubusercontent.com/12620139/34139397-d5fb3504-e431-11e7-8be1-da2d8efb759d.JPG)

When crafting inside the AE2 pattern terminal, no items are used. However, it still dupes redstone. When using a player crafting grid (2x2) the items are consumed.

Using All the Mods 3 v5.5 with ThermalFoundation-1.12.2-2.3.7.18-universal

**Comment by Nexus35** [comment]
When a bucket of resonant ender is crafted with cryothium in the 2x2 crafting grid it produces 10 redstone, not the 4 enderpearls that is expected.

**Comment by KingLemming** [comment]
This is something broken in some versions (unsure which exactly) of Forge. I do know that it doesn't happen in dev though.

**Comment by notacompletemoron** [comment]
Odd. ATM3 v5.5 uses Forge 2570, FYI.

**Comment by KingLemming** [comment]
I can't entirely rule out another mod doing really stupid things with the OreDictionary or even ATM3 itself.

But I absolutely know that it's not in my code.
