### ISSUE TITLE
Portable tank not working as a bucket when u're crafting Signalum Blend

### ISSUE THREAD

**Issue by damaskinos** [CoFH/Feedback#745]
Last Version of Direwolf20, tried with a Portable Tank "standard" and a "hardened"

**Comment by KingLemming** [comment]
I haven't confirmed it yet, but if that's the case, either another mod has somehow broken it or Forge has.

**Comment by Xiaminou** [comment]
I didn't even know you could do that, and it doesn't seem to work in my pack either.

![2017-12-20_17 15 00](https://user-images.githubusercontent.com/8670392/34216752-8824c4c0-e5a9-11e7-8fae-c503d8603216.png)

**Comment by KingLemming** [comment]
Yep. Way to go Forge.

**Comment by KingLemming** [comment]
Unsure if this is actually fixable. I need to poke @LexManos and/or @mezz and see what they say.

**Comment by KingLemming** [comment]
Seems that it is. Just odd that I have to override a method and have the actual value be private. :P
