### ISSUE TITLE
CoFH Missing mod when connecting to no mod server

### ISSUE THREAD

**Issue by Tencao** [CoFH/Feedback#746]
I know the title is a big vague, but it's kinda hard to fully describe the issue there. Basically, I have two modpacks, both fully backwards compatible. One server and pack has Thermal Expansion etc installed, and the other doesn't, but still have CoFHCore and Netherores. The problem is, when connecting to that server, I get mod rejections for Thermal Expansion, despite that server not even having Thermal expansion. If I remove Thermal expansion and the other two Thermal mods, it connects perfectly fine.

Edit - Also like to clarify I'm using the latest of all three Thermal mods, and have personally directly copied the exact mod files from client to server, to ensure their version numbers are exactly the same

**Comment by KingLemming** [comment]
I'm pretty sure this is intentional, actually.

**Comment by Tencao** [comment]
Is there anyway to disable this, or at least not force a kick if those mods aren't detected on the server? As this is preventing me from adding those mods to the modpack

**Comment by KingLemming** [comment]
There is not.

I'm looking into changing it for future versions, but the simple fact is that it is a fantastically bad idea to have content mods installed on the client and not the server.

**Comment by KingLemming** [comment]
Yeah, a quick test of this just reminded me how bad of an idea it is. It creates tons of potential x-mod crashes and NEI absolutely flips out.

Sorry, this is absolutely a safety measure and needs to remain.
