### ISSUE TITLE
Update BoP Plugin

### ISSUE THREAD

**Issue by Xiaminou** [CoFH/Feedback#746]
It's one of those cases where I don't know if the compatibility should be added on your side or their side, so I apologize if it's supposed to be on their side.
I would like to be able use the Pulverizer and Phytogenic Insulator to "grow" some Biomes'o'plenty's flowers and extract their dyes, similar to what you can do with Vanilla's flowers.
Biomes'o'plenty is just an example, there are other mods that add flowers which can be crafted into dyes. I suppose one could argue to add Botania's flower too however I wouldn't do it without Vazkii's approval.

**Comment by bookerthegeek** [comment]
Personally, I feel this should be on the other mods ends to use the API as that way CoFH does not have to keep a massive updated list of plants.

**Comment by KingLemming** [comment]
Just curious, have you actually tried? I've added compatibility for a TON of mods already.

Do you have a specific one that I have missed?

**Comment by Xiaminou** [comment]
I haven't I just assumed the recpie would be in JEI if it were integrated.

**Comment by Xiaminou** [comment]
Okay I tested it, I was right it's not implemented.
To be specific, the flowers and mushrooms of Biomes'o'plenty is what I am talking about.
![2017-12-20_17 15 00](https://user-images.githubusercontent.com/8670392/34237010-a49e8ca2-e5fa-11e7-9ac3-4b497ebf055f.png)

**Comment by Xiaminou** [comment]
Found 3 flowers that don't have a pulverizer recipe:
![2017-12-27_18 40 10](https://user-images.githubusercontent.com/8670392/34388712-8f9b615a-eb35-11e7-8c2f-ca67cf208033.png)
![2017-12-27_18 40 23](https://user-images.githubusercontent.com/8670392/34388713-8fb32c4a-eb35-11e7-8b3b-2251c777f4df.png)
![2017-12-27_18 40 40](https://user-images.githubusercontent.com/8670392/34388714-8fc93e7c-eb35-11e7-9bdd-c9ad0892d858.png)

**Comment by KingLemming** [comment]
Fair enough. Only looked for "dye" in JEI before.
