### ISSUE TITLE
[suggestion][cofh core] Veinminer enchant

### ISSUE THREAD

**Issue by EnderiumSmith** [CoFH/Feedback#747]
Remember the axe of the flowing stream from thaumcraft? I propose an enchant that allows tools to work like that. Instead of breaking the block you broke it would break the farthest connected block of that type. It would only affect certain blocks. For pickaxes it would only work on ores and obsidian. For axes it would only affect logs. Shovels would not have any block by default. Shears should work with it too. It counts as a treasure enchant so it cannot be obtained in the enchanting table.
To go with it i also propose a magnetic enchant. When you mine a block with this enchant the drops get teleported to you so there is no risk of it falling in lava. This can be obtained in the table but is quite rare.

**Comment by KingLemming** [comment]
This gets a bit complicated as certain tools already have complex behavior on their own and would result in a lot of special casing.

I'll think about it, but I don't think it's super likely.

**Comment by OneEyeMaker** [comment]
@EnderiumSmith 
Why are you need this feature in CoFHCore?
There are mods, which created *only* for this specific feature.
https://minecraft.curseforge.com/projects/ore-excavation
https://minecraft.curseforge.com/projects/oreexcavation-integration

**Comment by EnderiumSmith** [comment]
Those are completely different. It mines the whole vein at once for the time it takes to mine 1.
The one im talking about is the axe of the flowing stream where it mines then one at a time but instead of the one you broke it breaks the farthest one.

As for the special cases, what would those be? And cant you limit it to normal tools like pickaxes, axes, shovels and shears?

**Comment by KingLemming** [comment]
Drills, chainsaws, hammers, the flux-infused tools, etc.

Basically anything with AOE breaking. For vanilla enchant reasons, they have to also "look" like a pickaxe, axe, or whatever.

So after thinking about it, sorry but no.
