### ISSUE TITLE
[COFH Core] World: Decoration template/generator not working?

### ISSUE THREAD

**Issue by thephoenixlodge** [CoFH/Feedback#747]
From what I can tell, this world script should be working, but just outright isn't: http://pastebin.com/3MkMpYmp

As such I tested the function numerous different ways to try and figure out if I was doing something wrong, including testing a script written by someone else that they had had working, specifically Gideon's example of a decoration from this thread: http://forum.feed-the-beast.com/threads/cofh-core-ores-and-more.87151/ though I turned up the numClusters to make testing easier.
However, this also refused to work at all for me.
As such, I am hesitantly saying the function is broken, though if it isn't and I'm simply doing something wrong feel free to correct me.
This is for the in development 0.8 version of my Regrowth pack, and if necessary I can provide a download of this version of the pack in case it is something specifically to do with the mod ecosystem of the pack.

Version: COFH Core 3.0.3-303

**Comment by skyboy** [comment]
A quirk of maintaining compatibility with the original json format (from the early betas) requires that this template and generate have an empty material array: `"material": [],`

```json
    "deadgrass": {
        "template": {
            "type": "decoration",
            "generator": "decoration",
            "genSurface": "grass",
            "genSky": "true",
            "checkStay": "false",
            "stackHeight": 1,
            "xVariance": 8,
            "zVariance": 8,
            "yVariance": 4
        },
        "block": [
            "deadbush"
        ],
        "material": [],
        "clusterSize": 12,
        "numClusters": 30,
        "retrogen": "true",
        "biomeRestriction": "whitelist",
        "biomes": [
            {
                "type": "name",
                "entry": [
                    "Ocean",
                    "Beach",
                    "Plains",
                    "Mountainous Wasteland",
                    "Hilly Wasteland"
                ]
            }
        ],
        "dimensionRestriction": "blacklist",
        "dimensions": [
            -1,
            1
        ]
    }
```

**Comment by thephoenixlodge** [comment]
Thanks, this is working flawlessly now.
Just a note though, I'm not seeing any mention of this on the documentation, might be worth adding there?
