### ISSUE TITLE
savegame destruction by Fluiduct

### ISSUE THREAD

**Issue by Soyaro666** [CoFH/Feedback#748]
The topic said a lot I guess. Fortunately I had a backup of my savegame so I was able to fix my world and to reproduce the problem.

Crash 1 when placing a Fluiduct:
Server log: http://pastebin.com/xPjNbmJE
Client log: http://pastebin.com/qDQFTfyw

Crash 2 when loading the savegame:
Client log: http://pastebin.com/ucBuftzy

Crash 3 when reproducing by placing a Fluiduct:
Server log: http://pastebin.com/emzxVQyL
Client log: http://pastebin.com/Gru9V7Xz

The first time I tried to place a Fluiduct below a Tank from Extra Utilities. The second time I tried to place a Fluiduct beside a seared blicks block (which was part of a working smeltery) from Tinkers Construct. It's been the opaque version of Hardened Fluiducts (crafted by 2 invar and 1 lead).

I hope these informations are enough to analyze the problem...

**Comment by KingLemming** [comment]
Yup. Easy fix. Please read the README for this repo, especially this line:

Update your mods! Use mods ONLY from http://teamcofh.com/downloads.

So yeah, please go do that. -_-

**Comment by Soyaro666** [comment]
So the bug report belongs to version checker which gave me the wrong download. That's an important discovery. Thanks for your quick help!

**Comment by KingLemming** [comment]
CoFH includes a version checker. Definitely pay attention to the in-game notification.

**Comment by XFactHD** [comment]
@Soyaro666 you have to update forge to .1448 or higher.

**Comment by Soyaro666** [comment]
@KingLemming It's very motivating to have 15 to 20 mods that spam about updates in ingame chat right after I updated 30 mods... instead of one central list of updateable mods (which I was hoping to have after installing version checker) there are 3 to 4 ways updates are published...

@XFactHD that's exactly the version I'm currently using...

nevermind, another update for my mod collection is going to happen this weekend...
