### ISSUE TITLE
Leadstone fluxduct doesn't connect to cryo-stabilized fluxduct

### ISSUE THREAD

**Issue by ouroborus** [CoFH/Feedback#749]
Other ducts seem to connect normally.

Thermal Dynamics 2.3.7.14

![2017-12-21_23 04 15](https://user-images.githubusercontent.com/392047/34288721-bd7d41d8-e6a3-11e7-87ef-7f645130ad1a.png)
![2017-12-21_23 04 34](https://user-images.githubusercontent.com/392047/34288722-bd8ee280-e6a3-11e7-9a0f-7c20d27a4fb4.png)

**Comment by KingLemming** [comment]
Tema knows what's up.
