### ISSUE TITLE
Severe lag After Updating To CoFHCore-[1.7.10]3.0.4B1-309

### ISSUE THREAD

**Issue by RoloEdits** [CoFH/Feedback#749]
After updating to CoFHCore-[1.7.10]3.0.4B1-309 I've been experiencing extreme tps lag aswell as getting this error message in the fml client latest

http://pastebin.com/DzHUrwqv

it doesn't lag when I start the game in peaceful.

I'm reporting this to you guys because it started happening to me after updating COFH but it might not have anything to do with you but I don't no were else to go for help so if you could offer some form of guidance to go from here to fix it,it would be very much appreciated.

Thanks

**Comment by skyboy** [comment]
This has nothing to do with us, just above the start of that you'll see a line starting with `Wrong location!`. You have a bunch of entities from some mod which are at the wrong x/z location when loading from disk.

**Comment by RoloEdits** [comment]
OK thank you, is the world corrupt and irrecoverable? Or do i just have to delete some files in the world save?

**Comment by RoloEdits** [comment]
and would this also cause a no clip like effect when entering a world and start falling down through blocks?

**Comment by RoloEdits** [comment]
[14:11:21] [Server thread/WARN]: Wrong location! EntityPainting['Painting'/7895345, l='Capitan Planet', x=-1909.06, y=79.50, z=2560.00] (at -120, 160 instead of -120, 159) 

Is this what your taking about?

**Comment by KingLemming** [comment]
Yeah, basically that's it. Entities are being loaded wrong. Unfortunately, we can't really tell you much more than that. We can pretty confidently say that it isn't us, however.

Try loading it up on peaceful, going to all existing chunks, and then reloading.

**Comment by RoloEdits** [comment]
OK thank you very much
