### ISSUE TITLE
Crash when initializing

### ISSUE THREAD

**Issue by q4800** [CoFH/Feedback#75]
-Mod: Thermal Expansion
-Version: 1.7.10
(i used this installer: www.skydaz.com/thermal-expansion-mod-installer-for-minecraft-1-7-10/)
-Pastebin of all my other mods: http://pastebin.com/L69BmiUy

-CrashLog: http://pastebin.com/Tvd3nn2w

 At first i tried to install the mod .jar by .jar. you kwon, first the CoFHcore, then ThermalExpansion and ThermalFoundation. But there are so many bugs and problems with all this new versions, so i tried with the installer. Before the installation my minecraft worked fine with all the other mods, but after the installation i got that CrashLog. I don't think i can give more details. Also, im sorry if my english is not the best... 
I would really like to use this mod, so, any help is apreciated :)

**Comment by KingLemming** [comment]
First of all, absolutely do not use that installer or website. They aren't authorized and god knows what viruses you just downloaded.

Only use downloads from this site: http://teamcofh.com/downloads/

Use those versions and it should work. Do not download ANY of your mods from skydaz.

**Comment by bochen415** [comment]
....or from any website from this list
http://stopmodreposts.org/faq/illegal-sites/
