### ISSUE TITLE
Infinite wooden planks from the saw mill

### ISSUE THREAD

**Issue by TinkeringGnome** [CoFH/Feedback#75]
Since the vanilla wooden door recipe gives three of each door type
![2017-03-09_18 54 02](https://cloud.githubusercontent.com/assets/24947054/23776097/228322a0-04fa-11e7-9bb1-7974800cb18f.png)
and the saw mill offering six planks per door doesn't that result in infinite wooden planks?
![2017-03-09_18 54 26](https://cloud.githubusercontent.com/assets/24947054/23776149/64802040-04fa-11e7-8ee3-07a6c4a8bc7c.png)

Just curious if this was intended or a simple oversight?

Mods:
CodeChickenLib 2.5.6.238
CoFH Core 4.0.2.150
Thermal Expansion 5.0.2.83
Thermal Foundation 2.0.2.76

**Comment by KingLemming** [comment]
Oversight. Crafting recipe changed in 1.8 to give 3 doors and not 1.
