### ISSUE TITLE
Can't set the input for Essence of Knowledge into an Energetic Infuser with the Flux Reconstruction augment.

### ISSUE THREAD

**Issue by paul-soporan** [CoFH/Feedback#750]
Can't set the input for Essence of Knowledge into an Energetic Infuser with the Flux Reconstruction augment. I don't know if it's intended or not. I wanna automate the repairing of items.
More info: The Energetic Infuser is Resonant Tier and has 1 Flux Reconstruction Augment and three Auxiliary Reception Coil Augments.
Please let me know about this!
Have a nice day!

**Comment by KingLemming** [comment]
This is consistent with machines that have a single fluid input - any valid input side works and you don't need to set it.

Did you actually even try?
