### ISSUE TITLE
Disabling Fluxed Electrum damage disables charging

### ISSUE THREAD

**Issue by pjfranke** [CoFH/Feedback#751]
Fluxed Electrum charging and damage behavior configs aren't functioning correctly.  That is:

Both function correctly as configured--
Charge.Enable=true
Damage.Enable=true

Both function correctly as configured--
Charge.Enable=false
Damage.Enable=true

Both function correctly as configured (nothing happens)--
Charge.Enable=false
Damage.Enable=false

Charging does not work, damage is correctly not being dealt--
Charge.Enable=true
Damage.Enable=false

Similar if not the same to issue #170 

Mods present:

forge-1.7.10-10.13.4.1492-1.7.10.jar
Aroma1997Core-1.7.10-1.0.2.14.jar
AromaBackup-1.7.10-0.0.0.5.jar
CodeChickenCore-1.7.10-1.0.6.43-universal.jar
CodeChickenLib-1.7.10-1.1.3.136-universal.jar
CoFHCore-[1.7.10]3.0.4B1-309.jar
journeymap-1.7.10-5.1.0-unlimited.jar
NotEnoughItems-1.7.10-1.0.4.107-universal.jar
RedstoneArsenal-[1.7.10]1.1.1-89.jar
Waila-1.5.10_1.7.10.jar

**Comment by KingLemming** [comment]
Intended. Read the comments.
