### ISSUE TITLE
Translocation Plate not working in The End

### ISSUE THREAD

**Issue by EoD** [CoFH/Feedback#753]
ThermalExpansion-[1.7.10]4.0.3B1-218.jar

I tried several places and several options (up, down, forward, ...) and I could not get the translocation plate to work in the end. Unfortunately I only got a single one to test.

![2015-08-02_20 23 23](https://cloud.githubusercontent.com/assets/293499/9027416/cafc56ea-3954-11e5-8cef-b530a51de71f.png)

![2015-08-02_20 23 26](https://cloud.githubusercontent.com/assets/293499/9027417/ce30f1f4-3954-11e5-8720-386d948f72ee.png)

**Comment by KingLemming** [comment]
Can't replicate this at all, and there's nothing in the code that would prohibit it from working in the End. Possible that it's xmod interference, or you're consistently placing it in areas where it's attempting to teleport to invalid locations.

**Comment by EoD** [comment]
I can give you a complete list of mods we have installed, it's not very long. I tried several locations with different settings as I described above, and I am pretty sure (as seen in the screenshots) that the destination is empty. We also disabled railcrafts heat blocks.

**Comment by skyboy** [comment]
Another mod may cancel the teleport action.
