### ISSUE TITLE
Nullpointer Crash

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [CoFH/Feedback#753]
https://hastebin.com/loqogugozi.cs

**Comment by KingLemming** [comment]
I need context for this.

**Comment by Unrepentant-Atheist** [comment]
I had a chest with ducts and augments and retrievers and stuff like that. Broke the chest because I wanted to move it to a larger chest, in this case RF Tools Modular Storage. Apparently one of the augments is kaput I guess. Because when I broke the chest there was a cube with missing textures, pink cube. I guess that was an augment.

Looking INTO the chest, caused the same crash.

**Comment by KingLemming** [comment]
Yes. A couple of augments have been removed. However, that crash should only happen if you're looking directly at the augment and holding Shift. From the crash log though, it seems like McJtyLib is being "helpful."

Sorry for the inconvenience. I might push a hotfix for this, we'll see.

**Comment by Unrepentant-Atheist** [comment]
That's what was causing the crash: https://i.imgur.com/9dVA1oh.jpg

**Comment by KingLemming** [comment]
Oh yeah, I know what the issue is. The problem is just that it seemed McJtyLib was auto-holding shift or something like that. There shouldn't be any crash unless you hold shift on the item.

I'll push a hotfix, but this is pretty minor in the grand scheme.
