### ISSUE TITLE
Thermal Dynamics Creative Search Menu Crash

### ISSUE THREAD

**Issue by Robijnvogel** [CoFH/Feedback#754]
I have no idea if this is the correct place to post this, but here I go:

I have built a custom modpack with +- 180 mods.
After I start a game in creative mode and go to the creative search tab, my client crashes with this report:
http://pastebin.com/HJHStJ7R
OpenEye does not shed a lot of light on the matter other than that I am the only one having this issue:
http://openeye.openmods.info/crashes/e70e3c403ac835d553119ca0ddf9e7b1

The Creative TD covers page does not cause a crash and neither does NEI.

I suspect an incompatibility with another mod. Any Ideas which mod?

**Comment by KingLemming** [comment]
You are correct in that it's not caused by either mod. Disable the TD Creative Tab in the config options. You have some other mod creating the derp.

**Comment by Robijnvogel** [comment]
For people who have the same issue: This particular crash is caused by the Highlands mod.

**Comment by jakimfett** [comment]
@Robijnvogel you're not the only one having this issue.

To anyone else who needs the fix, set
  `B:Covers.Enable=false`
in the file ".minecraft/config/cofh/thermaldynamics/client.cfg"

**Comment by Robijnvogel** [comment]
Thank you, but disabling functionality to prevent a crash is not a fix. Those covers are neat!
I'll refrain from using Highlands altogether until they fix their code and/or cooperate with Team CoFH to fix the issue.

**Comment by skyboy** [comment]
That config option only disables the creative tab, it does not disable covers.

**Comment by Robijnvogel** [comment]
In that case this does nothing in the direction of fixing my issue, because it is, like I explicitly stated, the creative _search_ tab that leads to a crash. The creative _TD Covers_ tab works just fine.

**Comment by skyboy** [comment]
The covers would not exist at all in the creative menu, which should stop any crashes pertaining to the covers.

**Comment by jakimfett** [comment]
@Robijnvogel setting the config option from my [comment above](https://github.com/CoFH/Feedback/issues/754#issuecomment-147224097) **does** fix the creative search tab crash. I've edited my comment to make that more clear.
