### ISSUE TITLE
[Suggestion] Drink Potions from Reservoirs?

### ISSUE THREAD

**Issue by Akitori** [CoFH/Feedback#755]
Maybe have a fun option to drink potions from the reservoir directly? (maybe with other fluids, heh) I understand that maybe this is too broken to implement.

**Comment by KingLemming** [comment]
I've considered this. I will probably instead do a multi-potion bottle specifically for potions.

**Comment by Akitori** [comment]
Ah, righto. Still, awesome to hear! Thanks!

**Comment by KingLemming** [comment]
Alternatively, a potion injector of sorts which a reservoir could top off. I think that would be smoother in terms of gameplay, but *clearly* more OP.

**Comment by Akitori** [comment]
I would rather the multiuse bottle tbh x3

**Comment by KingLemming** [comment]
See #758. Opening a "thread," if you will.
