### ISSUE TITLE
Right Clicking on Tesseract Causes client to disconnect with Internal Server Error

### ISSUE THREAD

**Issue by AssassinStingray** [CoFH/Feedback#755]
Every time we right click on tesseract on our server it causes the client to disconnect with an internal server error. We had to recreate this in single player to get a crash report since it was not showing anything server side or client side when getting disconnected from the server. Here is the pastebin of the crash report from single player.  

http://pastebin.com/C62iShrB

**Comment by KingLemming** [comment]
You're using an alpha version of CoFH Core. We tell people over and over to only do that if they know what they're doing.

Given that your first course of action was not to immediately try the stable, recommended version of CoFH Core, I suggest that you do not use alphas anymore.

Please revert to the proper release version of the mod.

**Comment by AssassinStingray** [comment]
I thought the purpose of people running alpha builds was so that you could find the errors and fix them. If you don't want feedback on issues with your code maybe you shouldn't release alpha builds.

**Comment by KingLemming** [comment]
I apologize, my phone replies can be a bit blunt. In general, if you have an issue with an alpha, please *confirm* it's caused by the alpha, and let us know in IRC. This isn't a code issue so much a version mismatch.
