### ISSUE TITLE
[1.12.2][Issue] CoFH error loop in world load-up

### ISSUE THREAD

**Issue by accessdenied0** [CoFH/Feedback#756]
Greetings CoFH-team,

I wish a happy holidays! Sadly I still have to report something in this times.

I updated all CoFH mods in my own private pack and after updating Forge to 1.12.2-14.23.1.2571, 
I could load up Minecraft just fine. The main problem starts if I try to load-up my world I used before.
It loops in a crash trying to load the world and yes it loops my console get spammed with the same error again and again.

[Here is a cut of the console output.](https://pastebin.com/S32WUtR0)

The forge log isn't unusual (means no real error) and there is no crash-report, too.

I apologise if I done something wrong with the updates or maybe made a dupe report. (The time I write this, I found nothing similar)

Thank you for your effort!

access_denied

**Comment by KingLemming** [comment]
Nothing changed in that part of the code, so I really don't know what to tell you. Unfortunately, the log doesn't really show what the actual problem is, so the best I can do is tech support.

Downgrade to the previous versions, wrench up your Energy Cells, then upgrade and replace them. Something seems to be messing with them, but that log doesn't explain what.

**Comment by accessdenied0** [comment]
But something did change. I have a SINGLE Creative Cell and if I do like you said:
1) Downgrade
2) Load World remove SINGLE Cell
3) Upgrade
4) World works. Replace Cell
5) Save & Quit
6) Reload World -> Crashloop
7) Repeat

This is a nuisance....

**Comment by accessdenied0** [comment]
Tested it without Foamfix. I got a different crash. Was not able to figure out the issue here. Fact is: This error only accrues if I update all CofH mods. Nothing else except forge has changed. I have to wait for the FoamFix - update it seems but I would post all logs you need here if requested. 

Tested older TE versions with 1.12.2-14.23.1.2571. Working.

This issue as long it is persists and no real solution/reason is found, far from solved or resolved. I'm sorry.

**Comment by KingLemming** [comment]
Post a screenshot of your cell. I need to see what it's connected to - that may provide some clue as to what mod may be screwing this up.

**Comment by KingLemming** [comment]
I'm putting up a new version of CoFH Core and I've added something which will detect this possible situation and mitigate it. No promises, since I'm only working off your incomplete log, but let's give it a shot.

**Comment by accessdenied0** [comment]
Fair enough. I thank you for the effort and support!
http://puu.sh/yNNk1/ccf4b50606.png and
http://puu.sh/yNOsb/a105cc2146.png

where the positions I tried. But what is really strange is, since I use the CoFH Core you pushed, it seem to work and load flawlessly. 

I don't know what kind of magic this was. But with the previous version I tried the steps above more than 14 times. Now it just works.

If you still need any log, I post it here. But it seems solved by now.

I thank you VERY much and hopefully still have a merry Christmas.

**Comment by KingLemming** [comment]
No problem. Sorry if I seemed short there - debugging on Christmas isn't something I really enjoy doing, but I don't want people to have issues with their worlds either.

Merry Christmas. :)

**Comment by kragnoth** [comment]
Do you happen to use energysynergy mod accessdenied0, I use that and got the exact same crash on a creative energy cell.

**Comment by accessdenied0** [comment]
Nope. Sorry maybe disappoint you but I do not use this mod. @kragnoth
