### ISSUE TITLE
Enabling Portable tanks with the same metadata to stack

### ISSUE THREAD

**Issue by border999** [CoFH/Feedback#756]
I am asking this seeing as I've have been massively annoyed by the fact that Portable tanks don't stack, I can't see a reason why this can't occur.

**Comment by KingLemming** [comment]
Basically it's a consistency thing. If the tanks can stack, people get annoyed when the FluiVac won't fill them. Or empty, if full and stacked.

Also, not every mod properly handles stacked fluid containers. And we get yelled at when other mods screw it up. There was a patch cycle where these did stack and the complaints poured in.

Basically somebody will always complain no matter what we choose. Given that fact, we choose consistency.

**Comment by border999** [comment]
Sadly, this logic is pretty sound. Though I could suggest some form of intergration with some other mod for an even bigger container, having a dozen portable tanks filling your inventory is annoying.

**Comment by KingLemming** [comment]
512 buckets is A. Lot. Of. Fluid.

And if this is really "massively" annoying for you, then your threshold for annoyance is maybe a bit on the low end.

Why exactly do you need to carry so many of them?

**Comment by border999** [comment]
buildcraft oil geyser, it took 8 resonant portable tanks to hold the contents of 80% of ONE. And yes, annoyance toleration low, patience high.

**Comment by KingLemming** [comment]
Well, you can change how much each tank holds in the config options.

You can also use a Satchel to hold quite a few tanks.

I also feel obligated to point out that the geyser had a ludicrous amount of oil. :P
