### ISSUE TITLE
After Updating to the newest versions of COFHcore and Thermal Mods, I continuously Crash With a Ticking block entity Crash./

### ISSUE THREAD

**Issue by aplanetsabc** [CoFH/Feedback#757]
Ever Since I updated to the versions released on 12/25/17, I get a ticking block entity crash for any block that is hooked up to fluxducts or is related to /touching any COFH blocks that handle power.

**Comment by KingLemming** [comment]
Without a crash log, I absolutely can't help you.

**Comment by aplanetsabc** [comment]
Incoming

**Comment by aplanetsabc** [comment]
Here are the three crash logs
[crash-2017-12-24_21.47.13-server.txt](https://github.com/CoFH/Feedback/files/1585269/crash-2017-12-24_21.47.13-server.txt)
[crash-2017-12-24_22.18.23-server.txt](https://github.com/CoFH/Feedback/files/1585270/crash-2017-12-24_22.18.23-server.txt)
[crash-2017-12-24_21.57.26-server.txt](https://github.com/CoFH/Feedback/files/1585271/crash-2017-12-24_21.57.26-server.txt)

**Comment by KingLemming** [comment]
Yeah 2/3 of those point to SonarFlux. The one that doesn't point to SonarFlux suggests that you are running out of RAM.

Not our code, sorry.

**Comment by aplanetsabc** [comment]
Ok! I actually removed sonarFLUX and am testing it just to see :). also,  out of curiosity, what line is pointing to me running out of RAM? I'm getting back into MC after a while, and would like to  better understand crash logs so I don't continue to misreport issues, Like this. Happy Holidays!

**Comment by KingLemming** [comment]
Basically whenever you see:

java.lang.NoClassDefFoundError:

then that either means that you have a bad jar (which is not super likely), mismatched mods, or you've run out of RAM.

I know that our jars are good, and I checked your modlist - you are correctly up to date. So the final option is basically RAM. What also points to it being a lack of RAM is that in one crashlog you had this:

java.lang.NoClassDefFoundError: cofh/core/util/helpers/BlockHelper
	at cofh.thermaldynamics.duct.tiles.TileGrid.onNeighborTileChange(TileGrid.java:223)
	at cofh.core.block.BlockCoreTile.onNeighborChange(BlockCoreTile.java:163)
	at net.minecraft.world.World.func_175666_e(World.java:3791)
	at net.minecraft.tileentity.TileEntity.func_70296_d(TileEntity.java:163)
	at sonar.core.common.tileentity.TileEntitySonar.markBlockForUpdate(TileEntitySonar.java:153)

but then in another one you had this:

java.lang.NoClassDefFoundError: com/rwtema/extrautils2/power/energy/PublicEnergyWrapper$Receive
	at com.rwtema.extrautils2.power.energy.BlockPowerBattery.createTileEntity(BlockPowerBattery.java:41)
	at net.minecraft.world.chunk.Chunk.func_177422_i(Chunk.java:780)
	at net.minecraft.world.chunk.Chunk.func_177424_a(Chunk.java:798)
	at net.minecraft.world.World.func_175625_s(World.java:2379)
	at cofh.core.util.helpers.BlockHelper.getAdjacentTileEntity(BlockHelper.java:184)
	at cofh.core.util.helpers.BlockHelper.getAdjacentTileEntity(BlockHelper.java:194)
	at cofh.core.util.helpers.EnergyHelper.insertEnergyIntoAdjacentEnergyReceiver(EnergyHelper.java:119)
	at cofh.thermalexpansion.block.storage.TileCell.transferEnergy(TileCell.java:261)
	at cofh.thermalexpansion.block.storage.TileCell.func_73660_a(TileCell.java:236)

and the issue there is that the first one says that BlockHelper doesn't exist at all, while the second one is a crash that happened AFTER something in BlockHelper processed. That can't possibly be true.

**Comment by aplanetsabc** [comment]
Ok Thanks! Do you have any tips for continuing to troubleshoot this?

**Comment by KingLemming** [comment]
I'm afraid not, other than making sure that you actually are allocating enough RAM to Minecraft. Somewhere on the Minecraft Forge forums I think you can find some recommended java params to use.

**Comment by aplanetsabc** [comment]
Ok! It just seems weird to me that My ram is running out, as I have 7 GB allocated through the twitch launcher's recommended Java Params, which seem to be the same as those that I'd found on curse

**Comment by KingLemming** [comment]
That does seem weird to me, and I can't say 100% that it's the case, but memory errors *tend* to look like what you're reporting.

**Comment by aplanetsabc** [comment]
After Testing, It is definitely updating the COFH suite which causes this issue. It's quite strange.

**Comment by KingLemming** [comment]
So if you make a new world with JUST CoFH mods, you get this? Because you'd be the only one.

**Comment by aplanetsabc** [comment]
Ok. AFter Wiping My Configs, and reinstalling minecraft, I can get everything to load a new world.  I still can't seem to get my existing world to load though.

**Comment by aplanetsabc** [comment]
So. I ended up fixing it. It seems that my blocks that contained power were causing the crash. removing them before upgrading and replacing afterwards fixed it.
