### ISSUE TITLE
More Potion Stuff

### ISSUE THREAD

**Issue by KingLemming** [CoFH/Feedback#758]
Placeholder issue for suggestions related to Potions, such as:

New potions.
Potion combining.
New alchemical processes.
New ways to provide potion effects to players.

**Comment by Akitori** [comment]
Right so i had this dumb idea. Kinda a multiuse bottle like you mentioned, except it can be upgraded with holding to hold 10 potions? (idk, balance isn't my thing tbh). I kinda want its default to be three potions if that makes sense.

**Comment by KingLemming** [comment]
Not dumb at all. I had actually planned on doing it in standard Thermal style - 5 levels + Creative.

**Comment by Akitori** [comment]
Sounds awesome! Also you mentioned a injector earlier i believe..How would that work?

**Comment by KingLemming** [comment]
Kind of like a capacitor or reservoir, you activate it and it just gives you a potion effect, and it would drain a bit of potion every tick (or few ticks, or whatever)

**Comment by Akitori** [comment]
Kinda like a rf powered potion gem

**Comment by Akitori** [comment]
I feel like that isn't too absurdly broken, all things considered. Feels that would belong more in redstone arsenal myself, but that's my two cents. 

Heh, would be interesting to use the injector as a weapon against other players/mobs. Smack em with it and deliver a dose of potion.

**Comment by KingLemming** [comment]
At this point, I'm calling it good enough for now, given how potions work. Might revisit at some point in the future, but I'm pretty alright with this. :)
