### ISSUE TITLE
[CoFH Machines] NEI doesn't fill in gap when extra machine tabs are removed.

### ISSUE THREAD

**Issue by GenuineSounds** [CoFH/Feedback#76]
Example of the issue.

https://dl.dropboxusercontent.com/u/79514/Screenshots/Minecraft/2015-02-03_19.56.53.png

Not sure if this is NEI or the mod associated with the machine GUIs.

**Comment by KingLemming** [comment]
Fixed by https://github.com/CoFH/CoFHLib/commit/85eeb4f5dd3f0c8b704fb2187f8015e53ab8f679
