### ISSUE TITLE
Z-fighting on dynamos

### ISSUE THREAD

**Issue by Ar4093** [CoFH/Feedback#76]
The texture on all dynamo coils and corners is z-fighting when upgraded:
![image](https://cloud.githubusercontent.com/assets/10649509/23795209/9645c19e-0594-11e7-95a6-a04b13176506.png)

Version 5.0.1.73

**Comment by KingLemming** [comment]
Okay. So which graphics mod do you have installed? Optifine?

**Comment by Ar4093** [comment]
Nothing as far as I know. No Optifine, no Fastcraft, just the standard FTB Beyond modpack.

Contents of the mods folder: https://gist.github.com/Ar4093/70f187684ab301161b787caa69337878

**Comment by KingLemming** [comment]
Interesting. This doesn't seem to happen for anyone else, so maybe it's just an artifact of your video card. I've bumped the "spacing" for the overlay up a bit in the latest build. Let me know if that works.

**Comment by Ar4093** [comment]
Yep, looks completely fine now. Thanks!
