### ISSUE TITLE
CoFH World: Cluster generation ignoring defined material and just generating in stone.

### ISSUE THREAD

**Issue by TeetoKaziim** [CoFH/Feedback#760]
Minecraft 1.12.2
Forge 14.23.1.2581
CoFH World 1.12.2-1.1.0.11-universal
Hwyla 1.8.23-B38_1.12
InventoryTweaks 1.63
JEI 1.12.2-4.8.5.138

Steps to reproduce:
In config/cofh/world/00_minecraft.json:
https://pastebin.com/raw/izm6iaTG
In config/cofh/world/config.cfg:
https://pastebin.com/raw/5ix2Kkwy

Summary of config changes: 
-Set the "quartz" entry biome and dimension values to "all" in /world/00_minecraft.json
-In the config.cfg set B:ReplaceStandardGeneration=true

Result:
https://i.imgur.com/4bvpRXp.png
Nether Quartz ore generating in stone in the overworld, and no Nether Quartz ore generating in the netherrack in the nether.

I haven't had occasion to test if this is affecting the material entry for other generator types besides cluster, but it's happening for that one at least.

The best to you.

**Comment by KingLemming** [comment]
Technically, I think the issue is that the format changed and we forgot to update those files.

**Comment by KingLemming** [comment]
Go download 1.1.1. It's technically a reversion since that's the easiest way to handle this right now.

**Comment by TeetoKaziim** [comment]
Thanks a bunch! :D
