### ISSUE TITLE
Weird flux-infused bow bug

### ISSUE THREAD

**Issue by the-creamster** [CoFH/Feedback#761]
As the title suggests it's the weirdest bug i've ever seen; basically when a flux-infused bow has the enchant "Mutlishot(max level 4)" the numbers of arrows that 'bounces' back towards the firing point is equal to the enchant level;

The main issue i see here is that said player could kill themself with there own bow unintentionally or someone else they are assisting(of which i've already done once on multiplayer).

**Comment by KingLemming** [comment]
That's not a bug, that's MC physics at close range. ;)
