### ISSUE TITLE
[Thermal expansion]  Milkbucket -> glassflask [Bugreport]

### ISSUE THREAD

**Issue by zeitenheld** [CoFH/Feedback#762]
This bug currently appears in the ftb infinity modpack Version 1.8.2
If you give a (vanilla so it is not changed) milk bucket  into the liquid transposer (any Version hard ,resonant ect) and it empy`s it out the liquid transposer outputs a glass flask.
I already tried this in singleplayer and multiplayer and also in differnet enviroments like with differnet cables and with no cables on it is always the same result a glass flask.

**Comment by KingLemming** [comment]
The bug is with whichever mod is registering the recipe. It isn't TE.
