### ISSUE TITLE
[1.12.2] Facade Crafting with TiC2 does not work

### ISSUE THREAD

**Issue by JonasCiss** [CoFH/Feedback#762]
It is not possible to craft facedes made of TiC's seared bricks and other seared stuff. 

I also reported that to  TiC.
https://github.com/SlimeKnights/TinkersConstruct/issues/3303

**Comment by JonasCiss** [comment]
Forge: 14.23.1.2562
AE2: appliedenergistics2-rv5-stable-3
TiC: TConstruct-1.12-2.8.1.49

**Comment by KingLemming** [comment]
Yes, that's because Seared Bricks are Tile Entities. This is intentional.

**Comment by JonasCiss** [comment]
So there is no way to get seared stuff as facades?

**Comment by KingLemming** [comment]
I'll mention it to @covers1624 but atm no there is not.

**Comment by KnightMiner** [comment]
Chisel and bits gives us an IMC we can send to say seared bricks are still valid for chisel and bits despite being tile entites, possibly add the same sort of option here?

**Comment by KingLemming** [comment]
That'll entirely be up to covers. I can't look at TD without the urge to throw it all away and start over.

**Comment by covers1624** [comment]
It depends on how much interaction with the world is needed, its possible and im willing to look in to supporting it, would also be opt in over IMC, but it'd have to be after the new year before i even start to look in to it. Gonna open this again and mark it as a feature.

**Comment by KnightMiner** [comment]
In our case, none. When use decoratively seared bricks are as any other block model.

**Comment by covers1624** [comment]
Ok, should be fairly simple then, Ill whip something up after new years.

**Comment by Xiaminou** [comment]
If it's possible for TiCon's Seared Bricks, would it also be possible for Binnie's Mods' Wooden Tiles, Stained Glass and Ceramics blocks?

**Comment by covers1624** [comment]
This will be a thing in the TD rewrite, but won't be happening in the 2.X branch.
