### ISSUE TITLE
[Suggestion] Nullifier Satchel

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [CoFH/Feedback#763]
I think it's self explanatory.

**Comment by OneEyeMaker** [comment]
Just for your information: https://minecraft.curseforge.com/projects/dank-null

**Comment by KingLemming** [comment]
Not sure how I'd want to handle this honestly. A separate satchel feels clunky, and just a copy of /dev/null is ehh...

**Comment by laz2727** [comment]
A cache satchel? With an overflow regulator upgrade or something :P

**Comment by Unrepentant-Atheist** [comment]
I just need a satchel that picks up all the junk I don't need and sends it into...nirvana.

**Comment by KingLemming** [comment]
So *just* something that voids items? Not store 8000000000 of something and void the spares?

**Comment by Unrepentant-Atheist** [comment]
yes, I thought, that what the dev/null machine does? No? Which is why I wrote dev/null satchel.

**Comment by Tonius** [comment]
This may be causing a bit of confusion. What @Unrepentant-Atheist means is the nullifier, the device that voids items/fluids by 'sending them to /dev/null'.

However, the mod OpenBlocks adds an item which is specifically called the /dev/null. This item collects picked up items of a certain type until it is full, after which it voids any more picked up items of that type.

**Comment by Unrepentant-Atheist** [comment]
Ah yes, I read the description of the nullifier, it said something dev/null. Sorry, yes, I meant the nullifier.

**Comment by KingLemming** [comment]
No frills, no storage. Just voids. It does not have higher or lower priority than other satchels, so inventory order *will* matter.
