### ISSUE TITLE
COFH Friend Gui (COFH Core)

### ISSUE THREAD

**Issue by benlop24** [CoFH/Feedback#764]
Hey!

Basically, I've noticed there's only one permission node for COFH Core, the commandhandler. Whilst the commands have separate permission levels, Say I'd like to only give members access to "/cofh friend gui", I can't - They also gain access to COFH TPS, COFH Version and COFH help. Whilst these aren't an issue, it'd be nice to only give the players the one command they need. 

Thanks

Sparky

**Comment by skyboy** [comment]
The players require access to help.

**Comment by untamemadman** [comment]
Why do players require access to help. What benefit does it give to them?

**Comment by skyboy** [comment]
Help.
