### ISSUE TITLE
Tome of knowledge returns incorrect amount of levels

### ISSUE THREAD

**Issue by loudwhitenoise** [CoFH/Feedback#764]
Had 25 levels. Used Tome of Knowledge, poured out some Essence of Knowledge to my machines. Reclaimed the rest of the xp and gained 28 levels instead of (the expected) less than 25.

Edit: Forge .2575, MC 1.12.2

**Comment by KingLemming** [comment]
Gonna need a video of this. I literally can't make it happen.

**Comment by loudwhitenoise** [comment]
I tried and didn't get the same result as I did yesterday. I guess I must have pulled some stuff from the redstone furnace and got xp from that, can't figure out what else could have done it. User error - could not reproduce? Sorry to bother ya.

**Comment by KingLemming** [comment]
No worries! Thanks for looking into it. :)

Changes will be coming to the Tome. I realize the behavior of it isn't ideal at the moment, but I definitely want it to be accurate.
