### ISSUE TITLE
Unfortunate crossmod interaction: vanishing Satchel items

### ISSUE THREAD

**Issue by loudwhitenoise** [CoFH/Feedback#765]
1.12.2

I have a Hardened Satchel that I've been using to collect my Astral Sorcery rock crystals, it had about 8 or 9 items in it. When I rightclicked on my AsS starlight crafting altar, the satchel attempted to deposit its contents into the altar, which has 13 slots. I had already filled 8 of these with random stuff. The satchel deposited the first 5 items in its inventory, and caused the rest to just... vanish. I don't know if this is a general bug in that Satchels will overflow a target inventory and void the excess items, or if it is specific to this block from AsS.

**Comment by covers1624** [comment]
Can you test if the satchels void items when attempting to deposit items to a standard vanilla chest and also a TE strongbox please.

**Comment by KingLemming** [comment]
That is unfortunate, yes. But it's not crossmod, I just tested. It's 100% on their end. Please let them know.
