### ISSUE TITLE
[Feature Request] Opposite to Energetic Infuser... Energetic Defuser?

### ISSUE THREAD

**Issue by shadow7412** [CoFH/Feedback#766]
I made a BigReactor with a train line from my base to it. The plan was to fill up a flux capacitor at the reactor, then take it back to my base.

So the Energetic Infuser side of things was easy - take item out of cart, put it in infuser, infuser had the hopper upgrade and thus would send the filled capacitor back into the cart, causing it to take off again.

But I had no real way to unload the power from the flux capacitor. The Enervation Dynamo was close - but nowhere near fast enough (according to a wiki I read somewhere, 640RF/t). I'm hoping for an item dedicated to discharging equipment.

What are your thoughts?

**Comment by KingLemming** [comment]
Nope, sorry. That would make the dynamo completely worthless.

**Comment by shadow7412** [comment]
Then could the dynamo be enhanced to work similar to the infuser - with the ability to input charged equipment and output uncharged equipment? That way I could actually use it...
