### ISSUE TITLE
[Development Help Wanted]Dev environment version for CoFH mods?

### ISSUE THREAD

**Issue by WeAthFoLD** [CoFH/Feedback#767]
Hi CoFH! I'm a member of team Lambda Innovation. Currently we want to add RF energy support into our mod([AcademyCraft](https://github.com/LambdaInnovation/AcademyCraft))'s custom energy system. 

However I didn't see any deobufscated version of your mods. I have looked up your website and your developement versions don't seem to work (Actually better called nighty builds?).  Though I have the API but it would be struggle to build and test every time.

And the repositories don't have tags or branches so I can't make sure which commit I should pull to get the correct version. So, is there any developer support? Thanks >)

If this is in the wrong place, sorry about that.

**Comment by Entoarox** [comment]
http://minecraft.curseforge.com/mc-mods/69163-thermalexpansion/files/2246924

Check at the very bottom for the dev version of the same release build.

**Comment by WeAthFoLD** [comment]
Got it, thanks.
