### ISSUE TITLE
[Thermal Expansion] Redstone Furnace recipe broken

### ISSUE THREAD

**Issue by Mentlegen** [CoFH/Feedback#768]
Hello team CoFH,
When I look at the redstone furnace recipe in NEI for the malachite ingot I made, I see this:
![2015-08-08_13 01 58](https://cloud.githubusercontent.com/assets/13709632/9151379/c845ba26-3dce-11e5-9c5e-b491b0ae8814.png)
But when I actually try to put the malachite powder into the furnace, it will not go in. Is there a quick fix to this, or is this a problem that either team CoFH or I have to fix?
EDIT: Updated to the latest version. Same thing happens.
EDIT: Further testing reveals that some of my (newly added) dusts will smelt into their respective ingots, but older dusts will not.
EDIT (again): Looks like the one dust that isn't registered on the OreDictionary will smelt.

**Comment by KingLemming** [comment]
Ah. This is a custom mod? You're probably doing something wrong on your end.

Are you registering all of your OreDictionary things correctly AND at the correct time? (ASAP)

**Comment by WesCook** [comment]
Does it have a Trivection Chamber augment?  I found installing that broke my furnace for many non-food items.

Might be worth adding to the tooltip, as it took me a while to figure out what was wrong.  I just threw it in there as I had an extra slot and thought it sounded fun.

**Comment by KingLemming** [comment]
@WesCook - it's already part of the tooltip. "Can only cook food." in red text.

**Comment by WesCook** [comment]
Huh, so it does.  I guess I interpreted that to mean, "will only double food".  It didn't occur to me it would prevent other items from smelting when I first came across it.

My mistake.

**Comment by Mentlegen** [comment]
Sorry for typing this so late. All my ore dictionary things are registered in init, with the same code "OreDictionary.registerOre("dustName", nameOfItem)", and the Pulverizer can crush all of my ores and ingots, so I'm pretty sure they are registered correctly.

**Comment by skyboy** [comment]
The pulverizer and furnace use the same code to detect ore-dict equivalency for auto-adding recipes. So long as your entries are added during pre or init, and on both server and client then detection will work fine.
