### ISSUE TITLE
[1.12.2] Thermal Cultivation Watering Can Crash

### ISSUE THREAD

**Issue by APengu** [CoFH/Feedback#768]
So I was watering my sugar cane farm with signalum watering can and got this crash (I was playing on dedicated server, only client crashed)

Here's full crash report: https://pastebin.com/AtP8dYVp

**Comment by KingLemming** [comment]
Please update to 0.1.3. That probably won't fix it, but you should at least be on the latest version.

Thing is, you have Optifine installed and it's part of the stack trace. Also, I can't seem to make this happen.

So, could you try without Optifine ant let me know if you can make it happen? Thanks.

**Comment by APengu** [comment]
hmm.. It just happened, even with OF installed, I can't get this crash again, yet...

**Comment by KingLemming** [comment]
Even *with* OF installed?

**Comment by KingLemming** [comment]
Pretty sure I've stupid-proofed this now.
