### ISSUE TITLE
Unable to Smelt Tech Reborn Dust in a Redstone Furnace

### ISSUE THREAD

**Issue by HorizonsMC** [CoFH/Feedback#769]
Hello, using the latest version of TE and tech reborn and it appears the integration is broken as you can't smelt any of the dust. It does show the recipies in JEI.

**Comment by KingLemming** [comment]
Yeah, gonna need more info. If you're playing a modpack, there's a chance that the pack and/or server has broken it via ModTweaker or Unidict or some such.

Please try using ONLY CoFH mods + Tech Reborn and let me know if this happens. If the recipe is showing in JEI, I'm betting that something else is afoot.

**Comment by temp1011** [comment]
Not OP, but I looked at this to try and get some progress and it seems to work fine with just COFH mods and Tech Reborn. Using TE 5.3.8.38 and Tech Reborn 2.10.4.394.
![brasssmelt1](https://user-images.githubusercontent.com/34900092/34462792-3b89abec-ee43-11e7-8f5e-4b0a725fd047.png)
![brasssmelt2](https://user-images.githubusercontent.com/34900092/34462794-3f45c2fc-ee43-11e7-8c23-6c1199063733.png)
Some dusts require further processing so won't smelt eg-bauxite but that's what you would expect.
So, with base mods there doesn't seem to be a problem.

**Comment by KingLemming** [comment]
Good enough for me. Thanks for looking into this.
