### ISSUE TITLE
Somewhere between Thermal Expansion and Carpenter's blocks

### ISSUE THREAD

**Issue by thetrin777** [CoFH/Feedback#769]
Hello!
I haven't been able to get anywhere in solving this issue on my own. Everytime I try to install Carpenter's Blocks, I get a crash. And in the crash, the only mod I see listed as a problem is TE. It works fine without CB, but I'd love to use it. Here's some more details:

Minecraft version: 1.7.10

Thermal Expansion: 4.0.3 b1-218

CoFHCore: 3.0.3 303

Carpenter's Blocks: 3.3.6

If I need to provide more info, please let me know. If the actual error report is needed, I uploaded it to pastebin: http://pastebin.com/fRbwMcsB

Thanks in advance! BTW, Thermal Expansion rocks. \m/ 

EDIT: This exact same error occurred when I tried to put in Flat Signs. Either I am the unluckiest person ever, or I'm dong something wrong.

**Comment by KingLemming** [comment]
Your mods are out of date. -_- Please check the readme and notice that you're supposed to run the latest versions before reporting any crashes.

**Comment by thetrin777** [comment]
I went back and double checked all of my CoFH mods, and they are all the latest version from the Curse page.
