### ISSUE TITLE
[CofhCore not found: any]

### ISSUE THREAD

**Issue by JoTyler** [CoFH/Feedback#77]
Latest Version of all the required COFH mods.
Mod list is that of Material Energy 4

Error Log
http://pastebin.com/U6xt8sRr 

In game post mojang screen is says that it can not find any cofhcore mods installed.
Thanks for your help

**Comment by bochen415** [comment]
Open the FTB launcher, go to the options tab and push the big 'Advanced Options' button.
Resize the window (if you can) so everything will be visible and amke a screenshot. Upload it to imgur, post the link.

**Comment by KingLemming** [comment]
You're on a Mac. I see that you have Java 8, but you also have Java 6. Uninstall Java 6.

**Comment by skyboy** [comment]
The next update will fix this: uninstalling java 6 will also correct it, since you already have java 8.
