### ISSUE TITLE
Server crash: java.lang.ArrayIndexOutOfBoundsException: 4

### ISSUE THREAD

**Issue by Xiaminou** [CoFH/Feedback#77]
Server crashed when someone was exporting items into a barrel.

Crash Report: [crash-2017-03-08_19.51.10-server.txt](https://github.com/CoFH/Feedback/files/834762/crash-2017-03-08_19.51.10-server.txt)

**Comment by KingLemming** [comment]
This has been fixed already. Please keep your mods up to date.

**Comment by Xiaminou** [comment]
I would if this were my modpack, but this is FTB Beyond.
