### ISSUE TITLE
[Thermal Dynamics 1.12.2-2.3.8.16] Crash on world load

### ISSUE THREAD

**Issue by AsmodeiXIII** [CoFH/Feedback#770]
[https://pastebin.com/zF9TTgU1](url) Modlist
Forge Version: 14.23.1.2572 
[https://pastebin.com/sJiePGHX](url) Crash Report

This happens in a world that has Leadstone Ducts and Copper Fluiducts (Opaque)
Doesn't happen in one with only itemducts (my testworld)
Happens only on worldload, doesn't seem to crash while playing with the mod.
Removing the mod and changing the blocks (by placing other blocks where the ducts were) fixes the issue.

Happens with and without Foamfix and Optifine.

If you need any other info to track the bug, let me know.

**Comment by KingLemming** [comment]
Update CoFHCore. And please check for updates in the future before you post a crash, just as the readme says.

**Comment by KingLemming** [comment]
While I remember, also be sure and update CoFHWorld. Like, absolutely do that. Just make sure you're on the latest version of everything.

**Comment by AsmodeiXIII** [comment]
Its always the most obvious thing to miss, my b.
