### ISSUE TITLE
NEI Furnace recipe crash

### ISSUE THREAD

**Issue by Gyroscopickitty** [CoFH/Feedback#770]
I honestly have no idea what's going on, so here's a crash report.
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 05/06/15 4:21 PM
Description: Updating screen events

java.lang.ArithmeticException: / by zero
	at codechicken.nei.recipe.FurnaceRecipeHandler$SmeltingPair.getOtherStack(FurnaceRecipeHandler.java:41)
	at codechicken.nei.recipe.TemplateRecipeHandler$CachedRecipe.getOtherStacks(TemplateRecipeHandler.java:77)
	at codechicken.nei.recipe.TemplateRecipeHandler.getOtherStacks(TemplateRecipeHandler.java:501)
	at codechicken.nei.recipe.GuiRecipe.refreshSlots(GuiRecipe.java:228)
	at codechicken.nei.recipe.GuiRecipe.refreshPage(GuiRecipe.java:201)
	at codechicken.nei.recipe.GuiRecipe.func_73866_w_(GuiRecipe.java:70)
	at net.minecraft.client.gui.GuiScreen.func_146280_a(GuiScreen.java:255)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146280_a(GuiContainer.java)
	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:808)
	at codechicken.nei.recipe.GuiCraftingRecipe.openRecipeGui(GuiCraftingRecipe.java:28)
	at codechicken.nei.recipe.RecipeItemInputHandler.lastKeyTyped(RecipeItemInputHandler.java:23)
	at codechicken.nei.guihook.GuiContainerManager.lastKeyTyped(GuiContainerManager.java:307)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73869_a(GuiContainer.java)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73869_a(GuiContainerCreative.java:301)
	at net.minecraft.client.gui.inventory.GuiContainer.public_func_73869_a(GuiContainer.java)
	at codechicken.nei.guihook.GuiContainerManager.callKeyTyped(GuiContainerManager.java)
	at codechicken.nei.guihook.GuiContainerManager.keyTyped(GuiContainerManager.java:475)
	at codechicken.nei.guihook.GuiContainerManager.handleKeyboardInput(GuiContainerManager.java:465)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146282_l(GuiContainer.java)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:276)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1640)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at codechicken.nei.recipe.FurnaceRecipeHandler$SmeltingPair.getOtherStack(FurnaceRecipeHandler.java:41)
	at codechicken.nei.recipe.TemplateRecipeHandler$CachedRecipe.getOtherStacks(TemplateRecipeHandler.java:77)
	at codechicken.nei.recipe.TemplateRecipeHandler.getOtherStacks(TemplateRecipeHandler.java:501)
	at codechicken.nei.recipe.GuiRecipe.refreshSlots(GuiRecipe.java:228)
	at codechicken.nei.recipe.GuiRecipe.refreshPage(GuiRecipe.java:201)
	at codechicken.nei.recipe.GuiRecipe.func_73866_w_(GuiRecipe.java:70)
	at net.minecraft.client.gui.GuiScreen.func_146280_a(GuiScreen.java:255)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146280_a(GuiContainer.java)
	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:808)
	at codechicken.nei.recipe.GuiCraftingRecipe.openRecipeGui(GuiCraftingRecipe.java:28)
	at codechicken.nei.recipe.RecipeItemInputHandler.lastKeyTyped(RecipeItemInputHandler.java:23)
	at codechicken.nei.guihook.GuiContainerManager.lastKeyTyped(GuiContainerManager.java:307)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73869_a(GuiContainer.java)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73869_a(GuiContainerCreative.java:301)
	at net.minecraft.client.gui.inventory.GuiContainer.public_func_73869_a(GuiContainer.java)
	at codechicken.nei.guihook.GuiContainerManager.callKeyTyped(GuiContainerManager.java)
	at codechicken.nei.guihook.GuiContainerManager.keyTyped(GuiContainerManager.java:475)
	at codechicken.nei.guihook.GuiContainerManager.handleKeyboardInput(GuiContainerManager.java:465)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146282_l(GuiContainer.java)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:276)

-- Affected screen --
Details:
	Screen name: codechicken.nei.recipe.GuiCraftingRecipe

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [GCEntityClientPlayerMP['Sora103'/742, l='MpServer', x=329.85, y=68.29, z=-17.92]]
	Chunk stats: MultiplayerChunkCache: 76, 316
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (264,64,236), Chunk: (at 8,4,12 in 16,14; contains blocks 256,0,224 to 271,255,239), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 767693 game time, 767693 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 54 total; [EntityCaveSpider['Cave Spider'/104052, l='MpServer', x=8.29, y=-16.07, z=10.50], EntityBat['Bat'/117569, l='MpServer', x=257.50, y=52.00, z=5.50], EntityBat['Bat'/123147, l='MpServer', x=256.50, y=47.00, z=-14.50], EntityCreeper['Creeper'/123141, l='MpServer', x=275.50, y=36.00, z=-38.50], EntitySkeleton['Skeleton'/119369, l='MpServer', x=317.50, y=44.00, z=-52.50], EntityGiantBrainyZombie['Furious Zombie'/117709, l='MpServer', x=346.22, y=62.00, z=-34.22], EntitySkeleton['Skeleton'/117306, l='MpServer', x=333.00, y=42.00, z=-11.28], EntityZombie['Zombie'/117305, l='MpServer', x=334.63, y=41.00, z=-10.47], EntityCaveSpider['Cave Spider'/103209, l='MpServer', x=2.67, y=-10.84, z=13.34], EntityHorse['Horse'/117274, l='MpServer', x=311.88, y=67.00, z=-24.66], EntityHorse['Horse'/117275, l='MpServer', x=315.91, y=63.00, z=-20.22], EntityHorse['Horse'/117276, l='MpServer', x=323.78, y=65.00, z=-28.19], EntityPig['Pig'/117267, l='MpServer', x=368.88, y=63.00, z=-1.28], EntityPig['Pig'/117268, l='MpServer', x=363.13, y=63.00, z=-11.88], EntityPig['Pig'/117269, l='MpServer', x=366.41, y=63.00, z=-1.88], EntityPig['Pig'/117270, l='MpServer', x=349.34, y=63.00, z=-18.75], EntityItem['item.tile.mfr.rubberwood.log'/117366, l='MpServer', x=318.13, y=61.13, z=26.41], EntityItem['item.tile.flower2.poppy'/117367, l='MpServer', x=304.78, y=55.13, z=35.47], EntityPig['Pig'/117364, l='MpServer', x=378.50, y=63.00, z=-54.53], EntityCreeper['Creeper'/117365, l='MpServer', x=304.50, y=17.00, z=16.50], EntityPig['Pig'/117362, l='MpServer', x=383.41, y=63.00, z=-50.50], EntityPig['Pig'/117363, l='MpServer', x=380.06, y=63.00, z=-53.06], EntityCreeper['Creeper'/122972, l='MpServer', x=280.50, y=36.00, z=-35.50], EntityPig['Pig'/117378, l='MpServer', x=392.88, y=63.00, z=-42.91], EntityPig['Pig'/117393, l='MpServer', x=348.44, y=64.00, z=44.97], EntityPig['Pig'/117395, l='MpServer', x=318.81, y=63.00, z=-13.94], EntitySkeleton['Skeleton'/117405, l='MpServer', x=320.50, y=48.00, z=-8.19], EntitySkeleton['Skeleton'/117404, l='MpServer', x=320.50, y=48.00, z=-7.34], EntityZombie['Zombie'/117406, l='MpServer', x=311.50, y=43.00, z=-64.50], EntityItem['item.tile.dirt.default'/117494, l='MpServer', x=303.72, y=68.13, z=-43.81], EntityGiantBrainyZombie['Furious Zombie'/118450, l='MpServer', x=332.78, y=63.00, z=-21.13], EntityZombie['Zombie'/122800, l='MpServer', x=302.50, y=40.00, z=-52.50], EntityCreeper['Creeper'/122801, l='MpServer', x=307.50, y=40.00, z=-53.50], EntityCreeper['Creeper'/122802, l='MpServer', x=306.50, y=40.00, z=-54.50], EntityWitch['Witch'/122806, l='MpServer', x=282.50, y=41.00, z=19.50], EntityPig['Pig'/117044, l='MpServer', x=307.66, y=63.00, z=-13.22], EntityPig['Pig'/117045, l='MpServer', x=292.50, y=63.00, z=-23.50], EntityPig['Pig'/117046, l='MpServer', x=291.81, y=63.00, z=-21.19], EntityPig['Pig'/117047, l='MpServer', x=294.97, y=66.00, z=-33.09], EntityHorse['Horse'/117043, l='MpServer', x=306.09, y=68.00, z=-39.28], EntitySpider['Spider'/117068, l='MpServer', x=295.25, y=63.00, z=38.59], EntityZombie['Zombie'/99832, l='MpServer', x=15.83, y=-53.14, z=-20.83], EntitySkeleton['Skeleton'/118175, l='MpServer', x=-29.32, y=-8.54, z=53.30], EntityItem['item.tile.flower1.dandelion'/117236, l='MpServer', x=355.03, y=63.13, z=-21.72], EntityZombie['Zombie'/117217, l='MpServer', x=319.03, y=58.00, z=-2.50], EntityZombie['Zombie'/117218, l='MpServer', x=332.66, y=42.00, z=-13.47], EntityCaveSpider['Cave Spider'/94936, l='MpServer', x=18.44, y=-9.17, z=23.56], EntityCaveSpider['Cave Spider'/95935, l='MpServer', x=31.07, y=-10.84, z=-17.04], GCEntityClientPlayerMP['Sora103'/742, l='MpServer', x=329.85, y=68.29, z=-17.92], EntityCaveSpider['Cave Spider'/116929, l='MpServer', x=-18.40, y=-17.63, z=23.33], EntityPig['Pig'/116942, l='MpServer', x=271.97, y=63.00, z=-44.03], EntityPig['Pig'/116947, l='MpServer', x=284.63, y=64.00, z=-61.88], EntityPig['Pig'/116946, l='MpServer', x=278.78, y=63.00, z=-55.94], EntitySquid['Squid'/116950, l='MpServer', x=350.34, y=59.38, z=-66.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:919)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows Vista (x86) version 6.0
	Java Version: 1.7.0_67, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 113422800 bytes (108 MB) / 523501568 bytes (499 MB) up to 523501568 bytes (499 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx512M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.3.1420 Optifine OptiFine_1.7.10_HD_U_B7 59 mods loaded, 59 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.3.1420-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Forge{10.13.3.1420} [Minecraft Forge] (forge-1.7.10-10.13.3.1420-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CodeChickenCore{1.0.7.46} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	NotEnoughItems{1.0.5.110} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.110-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	OpenModsCore{0.7.3} [OpenModsCore] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	DamageIndicatorsMod{3.2.3} [Damage Indicators] ([1.7.10]DamageIndicatorsMod-3.2.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	bspkrsCore{6.16} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.16.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	StatusEffectHUD{1.27} [StatusEffectHUD] ([1.7.10]StatusEffectHUD-client-1.27.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CoFHCore{1.7.10R3.0.2} [CoFH Core] (CoFHCore-[1.7.10]3.0.2-262.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	advancedgenetics{1.5.9} [Advanced Genetics] (advancedgenetics-1.7.10-1.5.9.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	AppleCore{1.1.0} [AppleCore] (AppleCore-mc1.7.10-1.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Backpack{2.0.0} [Backpack] (backpack-2.0.0-1.7.x.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CarpentersBlocks{3.3.6} [Carpenter's Blocks] (Carpenter's Blocks v3.3.6 - MC 1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	enviromine{1.3.117} [EnviroMine] (EnviroMine-1.3.117.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	exnihilo{1.38-40} [Ex Nihilo] (Ex-Nihilo-1.38-40.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	F2L{1.7.10b} [Flesh2Leather] (Flesh2Lether [1.7.10b].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	GalacticraftCore{3.0.11} [Galacticraft Core] (GalacticraftCore-1.7-3.0.11.333.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	GalacticraftMars{3.0.11} [Galacticraft Planets] (Galacticraft-Planets-1.7-3.0.11.333.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	InfernalMobs{1.6.0} [Infernal Mobs] (InfernalMobs-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MineFactoryReloaded{1.7.10R2.8.0} [MineFactory Reloaded] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.0} [MFR Compat: Applied Energistics] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MineFactoryReloaded|CompatAtum{1.7.10R2.8.0} [MFR Compat: Atum] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MineFactoryReloaded|CompatBackTools{1.7.10R2.8.0} [MFR Compat: BackTools] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.0} [MFR Compat: BuildCraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MineFactoryReloaded|CompatChococraft{1.7.10R2.8.0} [MFR Compat: Chococraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.0} [MFR Compat: ExtraBiomes] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MineFactoryReloaded|CompatForestry{1.7.10R2.8.0} [MFR Compat: Forestry] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.0} [MFR Compat: ForgeMicroblock] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MineFactoryReloaded|CompatIC2{1.7.10R2.8.0} [MFR Compat: IC2] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MineFactoryReloaded|CompatMystcraft{1.7.10R2.8.0} [MFR Compat: Mystcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MineFactoryReloaded|CompatProjRed{1.7.10R2.8.0} [MFR Compat ProjectRed] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.0} [MFR Compat: Railcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.0} [MFR Compat: Sufficient Biomes] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.0} [MFR Compat: Thaumcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ThermalFoundation{1.7.10R1.0.0} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.0.0-81.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ThermalExpansion{1.7.10R4.0.1} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.0.1-182.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.0} [MFR Compat: Thermal Expansion] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	TConstruct{1.7.10-1.8.5.build957} [Tinkers' Construct] (TConstruct-1.7.10-1.8.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.0} [MFR Compat: Tinkers' Construct] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.0} [MFR Compat: TwilightForest] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MineFactoryReloaded|CompatVanilla{1.7.10R2.8.0} [MFR Compat: Vanilla] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	NetherOres{1.7.10R2.3.0} [Nether Ores] (NetherOres-[1.7.10]2.3.0-12.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	OpenMods{0.7.3} [OpenMods] (OpenModsLib-1.7.10-0.7.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	OpenBlocks{1.4.3} [OpenBlocks] (OpenBlocks-1.7.10-1.4.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	harvestcraft{1.7.10g} [Pam's HarvestCraft] (Pam's HarvestCraft 1.7.10h.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	RedstoneArsenal{1.7.10R1.1.0} [Redstone Arsenal] (RedstoneArsenal-[1.7.10]1.1.0-80.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	rouletteores{1.0.7} [RouletteOres] (RouletteOres-1.0.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	TallDoors{0.5.1} [Tall Doors Mod] (TallDoors-1.7.10-0.5.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ThermalDynamics{1.7.10R1.0.0} [Thermal Dynamics] (ThermalDynamics-[1.7.10]1.0.0-122.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	witchery{0.20.0} [Witchery] (witchery-1.7.10-0.20.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	HungerOverhaul{1.7.10-1.0.0.jenkins75} [Hunger Overhaul] (HungerOverhaul-1.7.10-1.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	IguanaTweaksTConstruct{1.7.10-2.0.0.DEV.99f9dfd} [Iguana Tweaks for Tinkers Construct] (IguanaTinkerTweaks-1.7.10-2.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	OpenModsLib class transformers: [gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED],[map_gen_fix:FINISHED],[movement_callback:FINISHED],[stencil_patches:FINISHED]
	Class transformer null safety: all safe
	CoFHCore: -[1.7.10]3.0.2-262
	Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: optifine
	MineFactoryReloaded: -[1.7.10]2.8.0-104
	ThermalFoundation: -[1.7.10]1.0.0-81
	ThermalExpansion: -[1.7.10]4.0.1-182
	TConstruct Environment: Environment healthy.
	NetherOres: -[1.7.10]2.3.0-12
	RedstoneArsenal: -[1.7.10]1.1.0-80
	ThermalDynamics: -[1.7.10]1.0.0-122
	Stencil buffer state: Function set: EXT (packed), pool: forge, bits: 8
	Launched Version: 1.7.10-Forge10.13.3.1420-1.7.10
	LWJGL: 2.9.1
	OpenGL: GeForce 6150SE nForce 430/PCI/SSE2/3DNOW! GL version 2.1.2, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because EXT_framebuffer_object is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (UK)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by Gyroscopickitty** [comment]
If a more recent crash report is required, I can re-create the crash easily.

**Comment by KingLemming** [comment]
Mods are out of date. -_- Please check the readme and notice that you should have them all updated for any crash reports.

Also, this is 100% in NEI.
