### ISSUE TITLE
[Thermal Expansion 2.3.8.22]Enchanted books problem

### ISSUE THREAD

**Issue by Manuepolis23** [CoFH/Feedback#771]
I want to search for the holding book ,this appear
![untitled](https://user-images.githubusercontent.com/8598020/34382125-7e0d83b6-eb15-11e7-80c7-9e8d6b7809da.png)

log : https://pastebin.com/izkGPJBe

modlist:
BiblioCraft[v2.4.3][MC1.12.0].jar
ChickenChunks-1.12.2-2.4.1.71-universal.jar
CodeChickenLib-1.12.2-3.1.5.331-universal.jar
CoFHCore-1.12.2-4.3.8.29-universal.jar
CoFHWorld-1.12.2-1.1.1.12-universal.jar
jei_1.12.2-4.8.5.138.jar
NotEnoughItems-1.12.2-2.4.1.233-universal.jar
OpenBlocks-1.12.2-1.7.3.jar
OpenModsLib-1.12.2-0.11.3.jar
RedstoneFlux-1.12-2.0.1.2-universal.jar
ThermalCultivation-1.12.2-0.1.3.11-universal.jar
ThermalDynamics-1.12.2-2.3.8.16-universal.jar
ThermalExpansion-1.12.2-5.3.8.38-universal.jar
ThermalFoundation-1.12.2-2.3.8.22-universal.jar

**Comment by Tonius** [comment]
Do you also actually get Leech when using a chest in the machine? This may just be a bug in the JEI handler.

**Comment by Manuepolis23** [comment]
yes, i get Leech

**Comment by Manuepolis23** [comment]
If I start a new world everything is ok. What may be the issue?

**Comment by Manuepolis23** [comment]
So this is happening: I start a world with only cofh mods, everything is ok. Then i add some mods that add enchantments to the game, the issue is happening only in the worlds that were created before adding the mods (that add enchantments).

**Comment by KingLemming** [comment]
Interesting. It's either one of the other mods, or Forge. Forge may be mishandling the registry somehow, or one of the other mods is shredding it.

**Comment by Manuepolis23** [comment]
Is there any way to save my world? like reseting the id for the  enchantments?

**Comment by KingLemming** [comment]
I don't know offhand. I don't have enough information about what is really going on here.

What mods are you adding?

**Comment by Manuepolis23** [comment]
open mods and bibliocraft

**Comment by KingLemming** [comment]
Can you install NBT tooltip and take a screenshot while moused over the book please?

**Comment by KingLemming** [comment]
Hmm actually I think I've figured this out and it's just fundamentally due to Forge's registry mechanics. It might fixable, but I don't have an ETA for you, sorry.

**Comment by Manuepolis23** [comment]
![untitled](https://user-images.githubusercontent.com/8598020/34383417-b621c566-eb1d-11e7-9f20-8feda7fac986.png)

**Comment by KingLemming** [comment]
Yeah, I was right. Heh.

**Comment by Manuepolis23** [comment]
For now I will put on hold my in-game projects with enchantments.
Thanks a lot and hope you had a good Christmas

**Comment by Akitori** [comment]
Same issue, only fix is having a new world created.

However as this world is one of the most vital worlds, its rather difficult....I doubt there's a way to clear the enchantment registries and fix it as such.

**Comment by KingLemming** [comment]
The problem is that ultimately, modded Minecraft isn't meant to be played with mods added and removed over the course of a given world. Forge accommodates it, but doesn't do so in an ideal fashion.

I have a partial fix in mind but absolutely no idea when I'll be deploying it. Need to check a few things with @mezz first.

**Comment by KingLemming** [comment]
This is a vanilla bug, apparently. I can work around it but then JEI would not match up. We're gonna look into a Forge-based fix for 1.12 and bugging Mojang for 1.13+.

**Comment by KingLemming** [comment]
We have a resolution for this. No ETA though.
