### ISSUE TITLE
Pyrotheum-Bug

### ISSUE THREAD

**Issue by ReneMuetti** [CoFH/Feedback#771]
Hello

I MooFluids installed. Now the following I noticed.
If I kicke with a bucket on a cow with flaming Pyrotheum, I get a bucket full of flaming Pyrotheum. When I click on a fluid Transposer or Autonomous Activator to open the GUI of the bucket is suddenly empty.
So I can not empty the bucket to fill the liquid in a tank.

Thanks for the great mod :)

**Comment by KingLemming** [comment]
Um...offhand that sounds like it's 100% in MooFluids.

**Comment by ReneMuetti** [comment]
Okay ...
Thanks for the answer

**Comment by KingLemming** [comment]
Basically, there isn't anything wrong with the Bucket of Pyrotheum.

What's happening is that when you use the bucket on the cow, it's only working on the *client* side. When something happens to force the inventory to synchronize, the server changes the item back to what it actually is. You should probably report this to MooFluids.
