### ISSUE TITLE
Suggestion: Arcane Escellerator custom recipes

### ISSUE THREAD

**Issue by Akitori** [CoFH/Feedback#772]
I want to be able to add custom recipes to the Arcane Escellerator in case issues occur, as well as remove existing recipes in case i don't like their cost. (Ex: mending for me is rather cheap due to our ability to destroy withers in seconds)

**Comment by KingLemming** [comment]
That's already a thing with IMC. If you mean not IMC, then get in line.

It'll come with the rest of the machines getting some sort of json recipe version and it's been discussed quite a few times here already. ;)
