### ISSUE TITLE
[Suggestion] Revert Tome of Knowledge functionality

### ISSUE THREAD

**Issue by tjsd** [CoFH/Feedback#773]
In the latest update to Thermal Foundation you upgraded the Tome of Knowledge to take and give all experience on use. 

This results in people not being able to be efficient with levels when enchanting manually. I would prefer if you could take out 1 level at the time, could this maybe switch functionality when empowered or not?

So if not empowered (to pick up xp) shift right click extracts 1 level at the time and gives back to the player, but when empowered it takes all experience.

For me this would be a highly QOL change :)

**Comment by KingLemming** [comment]
The change was to get around a Mojang bug. Eventually it'll have a GUI and hopefully a way to mitigate vanilla stupidity.

So no, I won't be reverting it back in the meantime as that introduces the bug again, sorry.
