### ISSUE TITLE
[1.12.2] Crash with a Tech Reborn block a Cresent Hammer

### ISSUE THREAD

**Issue by JonasCiss** [CoFH/Feedback#775]
I clicked with a Cresent Hammer of Thermal Expansion on a auto crafting table of Tech Reborn  and the game crashed. 
[crash-2017-12-28_10.16.29-client.txt](https://github.com/CoFH/Feedback/files/1591290/crash-2017-12-28_10.16.29-client.txt)

It was also mentioned here: https://github.com/TechReborn/TechReborn/issues/1387

**Comment by covers1624** [comment]
Not our issue, modmuss has stated that a RebornCore update is required.

**Comment by JonasCiss** [comment]
I have seen it and updated Tech Reborn. I missed the last update.
