### ISSUE TITLE
[CofHCore] Game crashes when trying to generate ReactorCraft ores

### ISSUE THREAD

**Issue by ax1m** [CoFH/Feedback#776]
I'm currently putting together a personal modpack for SSP, and I aim to tweak the oregen to be similar to Gregtech (large veins, few and far between). All went well for vanilla and Thermal Foundation ores, however when I tried adding ReactorCraft ores to the config, now it crashes when generating a new world.
Oddly enough the crash report doesn't mention ReactorCraft, but it does mention ChromatiCraft which I haven't touched. However when I disable that mod, it still crashes and now it only references CofH and vanilla in the crashlog.

Here's my logs:
[With ChC](http://pastebin.com/4EZGQtRk)
[Without ChC](http://pastebin.com/J5R4RKeW)
[And here's the config I wrote](http://pastebin.com/wcUcWfBS)

Thanks for your time and I hope we can get this issue resolved.

**Comment by skyboy** [comment]
You're generating very large structures too frequently, causing the game to attempt to generate every chunk in the world at the same time. Make them more rare, or smaller.
