### ISSUE TITLE
Weirdness with Mystical Agriculture in 1.10 with Thermal Dynamics(2.0.11.19)

### ISSUE THREAD

**Issue by jamzam90** [CoFH/Feedback#776]
When an item is sent to the top of one of the furnaces it is some times not put into the inventory.
Heres a little video clip of whats going on, even though im pretty sure it not your bug. 
https://youtu.be/jo3P4d9vRgU
and heres a link to the other bug report i made for it
https://github.com/BlakeBr0/MysticalAgriculture/issues/130

**Comment by KingLemming** [comment]
Usually, I hate capabilities. They're inefficient and awkward.

But in this case, I like them, because everything is standardized and I can pretty confidently say...yeah, this isn't us at all.

**Comment by jamzam90** [comment]
It happens with vanilla furnaces as well.
