### ISSUE TITLE
Question/Suggestion

### ISSUE THREAD

**Issue by paul-soporan** [CoFH/Feedback#777]
First, I would like if the thermal machines and the tome could be filled with the Industrial Foregoing Essence, Mob grinding utils liquid xp and when Ender IO and MFR will be ported, their liquid xp should be compatible too.
Second, I would like to know what happened to the 1.7.10 features that didn't get ported:
-Autonomous Activator
-Terrain Smasher
-Warp/Dense/Vacuum Itemducts
-Cyclic Assembler
-Machinist's Workbench
-Schematics
-Acquisition Apparatus
-Plates
-Flux transfuser/igniter/chiller
-Sponges
-FluiVac
-Glowstone illuminator/Lumium Lamp
They were some really nice features. I would like to know if they are on your to do list, or they are just abandoned.
I didn't include Tesserracts because I know it is are already on your list.
I care the most about Dense/Vacuum Itemducts because right now there's no way to set the priority.

**Comment by KingLemming** [comment]
The tome is probably a no. I've specifically balanced it a certain way and I have no guarantees that other liquid experience is actually "correct" at 20 mB / xp. I've allowed "xpjuice" as it *seems* to also follow that convention. IF as a general rule tends to massively trivialize everything it touches, however, so I'm not inclined to add support for it to undermine my own balance.

Secondly, those features...didn't get ported. That's what happened to them. Some of them might come back, but they might not. It's just a question of theme and consistency and what I actually feel like coding.
