### ISSUE TITLE
[Thermal Expansion] [Suggestion] Show that energy is retained

### ISSUE THREAD

**Issue by Mitchellbrine** [CoFH/Feedback#777]
Essentially, it would be an event to be fired on the dismantleBlock method being called.  
It WOULD be cancelable, so someone can cancel and put execute code. Parameters/Fields in the event would be the parameters of the abstract method. The event would be fired before the abstract method of dismantleBlock and if not canceled, it would proceed to use the abstract method.

It would be handy for a lot of mods, as I'm having trouble with it as well at the moment with a mod that allows RF generation to be portable.

**Comment by KingLemming** [comment]
Can you provide a concrete use case please? Otherwise this is just an avenue for somebody to completely screw over one of our mechanics.

**Comment by Mitchellbrine** [comment]
In the mod I'm creating, I am going to be making it so dynamos (maybe machines, though I still haven't figured that out) will retain power (and augmentations) on dismantle with a wrench. The only problem is that dismantleBlock is called onBlockActivated with a wrench AND in getHarvestDrops.

A dismantleBlock event would allow me to make sure it wouldn't remove the power (and augmentations) on creation of the ItemBlock, without the need of any weird hackery.

``` java

@SubscribeEvent
public void dismantleBlock(DismantleBlockEvent event) {
    if (event.block instanceof BlockDynamo) {
        TileEntityDynamo dynamo = (TileEntityDynamo) event.world.getTileEntity(event.x, event.y, event.z);
        ItemStack stack = new ItemStack(TEBlocks.dynamo,1,dynamo.blockMetadata);
        NBTTagCompound nbt = event.block.getItemStackTag(event.world,event.x,event.y,event.z);
        dynamo.writeToNBT(nbt);
        stack.setTagCompound(nbt);
        event.world.setBlockToAir(event.x,event.y,event.z);
        dynamo.blockDismantled();
        event.items.add(stack);
        event.setCanceled(true);
    }
}

```

**Comment by KingLemming** [comment]
That's interesting. So you're basically doing exactly what you shouldn't be with TE.

Don't refer to our source code in any way. Use the API.

Also, have you actually dismantled anything? Machines and dynamos keep their energy and augments already. Dismantle is working exactly how we want it to, and apparently how you want them to as well. This is exactly why there isn't an event - your use case is literally, "I want to change your mod."

**Comment by Mitchellbrine** [comment]
Okay, if you're going to hold energy in the ItemBlocks, at least show it. It gives no reference to the fact that energy is stored in there. Not a damage value, nothing. At least show stuff is retained.

**Comment by KingLemming** [comment]
There's only so big that we want a tooltip to be. Consider the amount of potential states, augments, and everything else. That gets really annoying.

**Comment by Mitchellbrine** [comment]
Use visual damage values for the energy. (I get the whole augment issue with tooltip)

**Comment by KingLemming** [comment]
That would imply that the item could be used in some meaningful way in the inventory, so no, sorry.

**Comment by Mitchellbrine** [comment]
You don't have to show the augments, but show the energy within the tooltip. This whole issue was started because I couldn't tell the energy was stored. And to the end user, it'll be just as confusing.

**Comment by KingLemming** [comment]
It doesn't seem to be very confusing. People seem to understand that blocks retain their state and internal quantities.

**Comment by sci4me** [comment]
Add a config option for the tooltip? Then people can choose if it's annoying for themselves.

**Comment by Mitchellbrine** [comment]
Also: Energy Cells seem to have a "change" shown on tooltip and have a damage values.

So either ADD the visuals for the machines and dynamos or REMOVE them for the cells. Consistency, much?

**Comment by KingLemming** [comment]
Cells can have their energy extracted from and can be filled. They are IEnergyContainerItems, just like Flux Capacitors. Refer to my "meaningful way in the inventory" comment.

It's completely consistent and since you're getting snippy, I'm closing this.
