### ISSUE TITLE
[Suggestion] Watering Can - Reservoir Integration

### ISSUE THREAD

**Issue by EmosewaGamer** [CoFH/Feedback#778]
I suggest making it so Thermal Cultivation Watering Cans can be filled up when a Reservoir filled with Water is active.

**Comment by KingLemming** [comment]
This would be a great suggestion if it didn't already work that way. But it does.

Please try things out before suggesting them. :/

**Comment by EmosewaGamer** [comment]
Weird, it didn't work when I tried it earlier.
