### ISSUE TITLE
Localization improvements

### ISSUE THREAD

**Issue by Adaptivity** [CoFH/Feedback#778]
So, there are few things I want to change in localization system. This is minor issue since it's all about localization.

Thermal Dynamics localization:
1) [Cover string](https://github.com/CoFH/ThermalDynamics-Localization/blob/master/en_US.lang#L45) should have %s tag to swap *Cover* word with *material name*.
2) Every pipe name should be localized individually *if* needed.
So, only if .lang file contains for example *tile.thermaldynamics.duct.itemDense.name=Dense Itemduct* it should be used instead of *tile.thermaldynamics.duct.dense.name* + *tile.thermaldynamics.duct.itemBasic.name*. [An example](https://github.com/aidancbrady/Mekanism/issues/2626) how to do this (check referenced commit).

Thermal Foundation:
Forge Lexicon GUI contains hardcoded localization (Only one entry, search and etc).

Thermal Expansion:
1) Machine localization should be changed in a way like pipe localization. Since even now Russian localization for machines looks rough. It only can be improved by allowing translating machine names individually.
2) Sponge localization should be changed in the same way.

**Comment by KingLemming** [comment]
Okay so...

I don't understand the issue with Covers. What material name are you talking about?

Also, the Lexicon does not appear to have *any* hardcoding. So again, I'm confused there.

The rest of it, I sort of understand. The sponge complaint makes more sense than the machines though. Are parentheses not a thing in Russian?

**Comment by Adaptivity** [comment]
1) About covers: For example "Stone Cover" (where "Stone" can be as adjective or noun in English) but in Russian it's only can be as noun (for adjective there are another form of word exists). So, to workaround this I need to change localization to Cover (%s) (where %s is Stone, Lava etc). Simple thing to do.

2) About Lexicon: Well, I've just missed that Lexicon localization was added... but [this string](https://github.com/CoFH/ThermalFoundation/blob/f2882b14de48b01e74dce2d7224f5d683890f0f0/src/main/java/cofh/thermalfoundation/gui/client/GuiLexiconStudy.java#L29) still hardcoded. Not sure if it possible to easily localize it, may require a code change.

3) Parentheses only help to *workaround* issues such as I've mentioned above about Covers.
For the machines and sponges they will not help. Since machine tier names have different endings in Russian.
For example: Resonant Redstone Furnace (in Russian Resonant will have ending "-ая") while Resonant tier name for Pulverizer will have ending "-ий". I hope you understand what I mean now.

**Comment by KingLemming** [comment]
1) Makes sense but wouldn't that break localization everywhere else?
2) Doable but will get annoying since there's no easy way to center the text.
3) There is no place in TE where the adjectives appear before the machine names. It's always Redstone Furnace (Resonant) and those tiering names are already separately localized.

**Comment by Adaptivity** [comment]
1) No, it shouldn't break anything. A lot of mods using these tags. Buildcraft, Buildcraft Additions and a lots more.
2) I knew it.
3) Yeah, I've mistaken here but still there are no differences at all. As I said, parentheses will *not* help there. You can just [check ru_RU.lang](https://github.com/CoFH/ThermalExpansion-Localization/blob/master/ru_RU.lang#L125) tier localization and you'll see that they're shortened. So, that still need to be done. I hope I've explained everything correctly now. This need to be done for proper localization. There are no other way.

**Comment by KingLemming** [comment]
k, Lexicon is done. :) Will figure out the rest.

**Comment by skyboy** [comment]
Covers can be localized in the format of: `item.thermaldynamics.cover.<unlocalized name of other item>.name` `item.thermaldynamics.cover.tile.log.oak.name` 

Ducts can be localized in the format of `tile.thermaldynamics.duct.<type>[.opaque][.dense|.vacuum].name` where bracketed options are optional. for instance: `tile.thermaldynamics.duct.fluidBasic.opaque.dense.name` `tile.thermaldynamics.duct.fluidBasic.dense.name` `tile.thermaldynamics.duct.fluidBasic.opaque.name` While `.dense.vacuum` is invalid

Machines can be localized as: `tile.thermalexpansion.machine.furnace.<type>.name` `tile.thermalexpansion.machine.furnace.resonant.name`

Sponges can be localized as `tile.thermalexpansion.sponge.<type>[.wet|.dry].name`

**Comment by Adaptivity** [comment]
That should be good. Covers just should have %s tag for name swapping. I don't think that anyone will translate all covers through manual strings. But if you already implemented this, just make sure you have added %s tag. And thank you.

**Comment by Adaptivity** [comment]
@skyboy ok so new localization improvements looking good. Can you also add %s tag to [Augment tooltips](http://i.imgur.com/DvHy04G.jpg)? So, I will be able to change localization to something like: "Energy Produced: x2"
