### ISSUE TITLE
Thermal dynamics 2.0.11.19 losing items

### ISSUE THREAD

**Issue by jamzam90** [CoFH/Feedback#779]
When attached to vanilla furnaces itemducts dont place items into the inventory. I can see them going into the furnace from the attached duct but they dont go in to the inventory.
Heres a video about it.
https://youtu.be/BUy8XDW6yPU

**Comment by jamzam90** [comment]
Also occurs in 1.12.2 with 2.3.8.16

**Comment by KingLemming** [comment]
Dunno what to tell you. I absolutely can't make this happen.

**Comment by jamzam90** [comment]
It only happens with itemducts hoppers dont do it nor do enderio conduits.

**Comment by jamzam90** [comment]
I've reproduced this issue on three computers and two different minecraft accounts doing the following.

Set up a furnace array use at least 3. (Its seen with multiple furnaces reliably)
Then put regular item ducts on the top, bottom and back sides of the furnaces.
Have the items ducts on the top and backs of the furnace plugged into the same chest.
Use any of the servos which can round robin, so reinforced on up, I use signallum because its faster.
Plug the output ducts into a chest and set a retriever to always pull.
Add a servo to the input chest filtered to blacklist coal (furnace top ducts)
set to round-robin
reduce the stack size extracted to 1.
Set to ignore redstone.
Add another servo to the input chest for the back side of the furnaces.
Add a servo to the input chest filtered to whitelist coal (furnace back ducts)
set to round-robin
reduce the stack size extracted to 1.
Put nine stacks of cobble and coal into the input chest.
Watch the ducts and furnaces to see if they are doing anything

**Comment by Old-Wise-One** [comment]
Well i can attest to the fact that it does indeed occur fairly regularly.
I Tested 
1.12 - Both With most updated versions of Cofh Mods
Forge 14.23.1.2582
Forge 14.23.1.2555
1.10
Forge 12.18.3.2511 w/most updated versions of Cofh Mods
Forge 12.18.3.2511 w/oldest available versions of Cofh Mods
Forge 12.18.3.2316 w/oldest available versions of Cofh Mods
Forge 12.18.3.2202 w/oldest available versions of Cofh Mods
1.7.10
Bug Not Present

Items that I found to be voided when put through this situation
Any fuel in the fuel slot
Cobble,Sand,Gravel,Raw Foods ie Chicken Beef Pork, Smelt able Ores, Smelt able ,Sea Lanterns, Dusts,Bedrock,Wood,Stone Bricks, Cactus, Slime Blocks, Redstone Reception Coils,
Other items may be affected but these where what I found

Some items that weren't Voided
Wool, Dirt, Smooth Stones, Grass, Metal Blocks, Glass, Quartz Block, Packed Ice, Hay Bales, Saplings, Leaves, Flowers, Crafting Tables, Dyes, Carpet, Fences(in the upper slot only Voided in fuel),Redstone Transmission Coils, Redstone Conductance Coils

While this could point to the bug being introduced with the rewrite of dynamics or the updates of forge it is evidence that the code that causes this bug has been unaltered for a prolonged period of time.

Further testing of Buildcraft, Extra utilities, Immersive engineering, and Vanilla's item transports do not have this same issue of voiding items once the furnace has been activated after their being hooked up. 

The export instance from twitch of my testing environment in 1.12 limited to only Thermal dynamics its libraries and JEI. This way you should be able to view this on your own computer.
[Test-1.0.zip](https://github.com/CoFH/Feedback/files/1594289/Test-1.0.zip)

Please realism that this work that we have put in has been to help you improve a well loved mod. We are not trying to be adversarial or to demean any of the work you have put in. That and its irritating having our items eaten in early game survival.

**Comment by KingLemming** [comment]
Okay so after having tried many many MANY times...

I still can't make this happen.

Guys, I dunno what to tell you here. It literally just doesn't happen.
