### ISSUE TITLE
Crash when trying to setupDecompWorkspace.

### ISSUE THREAD

**Issue by goldenapple3** [CoFH/Feedback#780]
I'm trying to make an addon to ThermalExpansion, but I can't setup a dev environment properly.

I added the CoFH_at.cfg file to my resources folder, but whenever I run `gradlew setupDecompWorkspace`, it crashes (here's the log: http://pastebin.com/jLLrPhwb).

I assume the AccessTransformer also needs to override canTriggerWalking() in all Entity subclasses?

**Comment by KingLemming** [comment]
So basically this is a tech support request. Use IRC for this stuff please.

If nobody answers, try back later. But that's not why this repo is here.

Offhand, it sounds like you're using a beta CoFHCore. Don't do that either.
