### ISSUE TITLE
[Suggestions]About thermal expansion's details.

### ISSUE THREAD

**Issue by LittleboyHarry** [CoFH/Feedback#781]
1.Can 'Flux Transfuser' translator more rf per tick,it's too slow to transfus some big rf energy cells;
2.The(Redstone/Impulse/Translocation)plates are quite interesting.But I just want to let it make a difference to player,item,animal or monster;
3.Can provide some textures on upgraded machine,I can hardlly know the machines in wich level if i didn't install waila or looked it at a distance.

**Comment by KingLemming** [comment]
1) No, it can't. It's based entirely on the things that it is transferring into and out of.
2) I don't understand what you mean here at all.
3) I've considered it. Not really a fan to be honest.

**Comment by XFactHD** [comment]
I think that 3) could be very useful even if it is only a one pixel wide outline on the block.

**Comment by BoyHarry** [comment]
mmu... i want to step on redstone plates provide power to open my house door only by me not by monster like the Mod ObsidiPlates.
