### ISSUE TITLE
[Suggestion] Instant item transfer duct

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [CoFH/Feedback#781]
There's instant fluid, instant redstone flux, but no instant item transfer? What gives? If implemnted, make it expensive :P

**Comment by paul-soporan** [comment]
There was a warp itemduct in 1.7.10. I asked yesterday about porting some old features. #777

**Comment by KingLemming** [comment]
What gives?

What gives is that I'm on vacation and I don't really like demands. I also don't want to touch TD at this point because I'll end up rewriting it.

**Comment by Unrepentant-Atheist** [comment]
Yo, I wasn't making a demand but wondering why there was no instant item pipe when every other had. Chill.

**Comment by KingLemming** [comment]
Sorry, but I've been getting a lot of sass and demands lately from a lot of different channels, and "what gives," comes across as, "I am *owed* an explanation for this."

Fact is, I don't want to invest any time/effort into TD when I simply want to rewrite it entirely at some point.

**Comment by Unrepentant-Atheist** [comment]
That's fine. I'm not owed anything. I was just wondering. When the rewrite happens, then it happens, and I hope you'll include the idea. If not, fine too. It's your mod after all.
