### ISSUE TITLE
Cannot use creative conversion kit on Compacter (and possibly other machines)

### ISSUE THREAD

**Issue by BrisingrAerowing** [CoFH/Feedback#782]
I tried using a creative conversion kit on a Compacter, and the GUI would open each time I clicked, even if shift was held. A resonant conversion kit worked fine.

And yes, I am in creative.

CoFH Core: 4.3.8.29
TF: 2.3.8.22
TE: 5.3.8.38

**Comment by paul-soporan** [comment]
U cannot upgrade machines to the creative tier.
Only energy cells, strongboxes etc.
Even if u could, what would you expect from a creative machine?

**Comment by KingLemming** [comment]
This is correct. Creative machines are no different from resonant at this time, so I've disallowed the kit working on them.

**Comment by paul-soporan** [comment]
As a suggestion,  if possible, I think that the creative machines could have infinite rf in them and they could be instant.

**Comment by KingLemming** [comment]
That will not be happening.
