### ISSUE TITLE
Invalid framebuffer operation with CoFHCore

### ISSUE THREAD

**Issue by curiosity-a** [CoFH/Feedback#783]
I'm running Minecraft 1.7.10 with Forge build 1469. The only mod I have installed is CoFHCore 3.0.3-303. Once during loading I get this error:
[16:59:22] [Client thread/ERROR]: ########## GL ERROR ##########
[16:59:22] [Client thread/ERROR]: @ Pre startup
[16:59:22] [Client thread/ERROR]: 1280: Invalid enum
Then when the title screen comes out, I get following error a a rate of what I assume to be my framerate:
[16:59:25] [Client thread/ERROR]: ########## GL ERROR ##########
[16:59:25] [Client thread/ERROR]: @ Post render
[16:59:25] [Client thread/ERROR]: 1286: Invalid framebuffer operation
I haven't found any way to disable this behaviour through config. My graphics card is Intel 965 Express and OpenGL version is 2.0. I can post specifications of my graphics card (including supported extensions) if necessary.

Edit: Forgot to mention, all I see in the title screen is a miniature background animation in the bottom left corner. I can click on buttons, but this does not affect the screen. I haven't tried to guess click into loading a world, I assume nothing would change if I did.

**Comment by KingLemming** [comment]
Search function is your friend.

Use

-Dforge.forceNoStencil=true

as a JVM argument.

**Comment by curiosity-a** [comment]
It helped, thank you.

In my defense, I used search, but found only advice about disabling splash screen, which was already disabled for me.
