### ISSUE TITLE
[CoFH World] "surface" generator can not replace/see modded top blocks?

### ISSUE THREAD

**Issue by Robijnvogel** [CoFH/Feedback#783]
**Mod(s) and versions:**
This issue happens with the latest version(s) of CoFH World. 1.1.1.12 and 1.0.2.10.
I have not tested if it happens with pre-1.12.2 versions of CoFHCore as well, but I would assume so.

**Issue description:**
Using `surface` or `decoration` as the distribution type, at first glance it seems like features do not get generated at all, when the top block of an area, a biome if you will, is a modded block.

**Story:**
I first noticed this issue, when I used BiomeTweaker to drain the ocean of all of its water and changed the ocean floor into Biomes O' Plenty `mud` blocks after which I wanted to use CoFH World to generate liquid poison lakes on this new "surface".
[This did not work](https://i.imgur.com/wSpvada.png). Instead, it seems like poison was only generated [one layer below the top layer](https://i.imgur.com/XSJmj0P.png). Before you remark this, no, the `follow terrain` boolean option did not seem to change this behaviour.
I tried both the `plate` and `lake` format, both of which behaved this way. The only places where the poison did reach the surface, was [where the ocean floor steeply declined](https://i.imgur.com/yrC01fY.png), resulting in such an shallowly underground ground being "opened up" at its side.

Later, I tried to generate some poison lakes on the surface, which[ did work in deserts](https://i.imgur.com/sVtsb3v.png), but I found that this [didn't work in BoP's Wasteland biome](https://i.imgur.com/vBmKkrq.png), where the top layer is a BoP block, which gave me the idea, that the problem might be BoP blocks. So I tried to leave the ocean floor Vanilla Minecraft Gravel and not turn it into BoP Mud and suddenly the `surface` distribution [started to work correctly](https://i.imgur.com/SR49sUb.png).

To make sure that it wasn't BoP blocks specifically I replaced the top block of all biomes with Thermal Expansion's Copper Ore, which, again, [resulted in no lakes being generated whatsoever](https://i.imgur.com/pd6DJZw.png) as long as `surface` generation was used.

No, this has nothing to do with falling vs. non-falling blocks. [The lakes generate fine in plains/forest](https://i.imgur.com/p0Bdfpd.png).

Something I found as well, about the `surface` distribution type, is that it only seems to place features on edges; [where the height differs slightly and not in the middle of flat stretches of terrain](https://i.imgur.com/SR49sUb.png). Again, `follow terrain` does make a slight difference, but very clearly [does not affect this specific observation](https://i.imgur.com/bdVwffO.png).

**Summary:**

- [x] Surface generator not working correctly with modded blocks.

- [ ] Surface generator only placing features along edges of "plateaus".

**Comment by KingLemming** [comment]
We need to see your json file.

**Comment by Robijnvogel** [comment]
Which json file? While testing this, I have edited the json file dozens of times. 
In [the current version](https://pastebin.com/iNMMTqv8) of the file, there is a `surface` `lake` generator (L602) that works for all biomes except the ones covered in a BoP soil. 
Even if you remove the biome blacklisting (L616) for those that I added later, after I already thoroughly investigated the issue.

Note:

- With the `lake` generation type, the `material` (I used minecraft:air as a dummy) does not get checked by default, but whether I did specify it to check or not didn't make a difference in my tests.

- All of the other `uniform` distribution generators are purely as a workaround, because I didn't get `surface` distribution to work, specifically when biomes have modded blocks as their top blocks.

**Comment by KingLemming** [comment]
This may actually a be quirk with BoP specifically. It may be generating mud AFTER CoFHWorld does a pass.

Also, you really should not edit 00_minecraft.json. You should make your own json instead.

**Comment by Robijnvogel** [comment]
As I stated in my original message (and I added the pictures now), this does not happen with just BoP or just BiomeTweaker, but with other modded top blocks or top blocks that haven't been substituted as well. I used Thermal Expansion to test that and also added a screenshot of that by now.

The Thermal Expansion example is one without Biomes O' Plenty.
The Wasteland example is one without BiomeTweaker.

Editing `00_minecraft.json` should not have anything to do with the issue, but your objection is noted.

At the moment, it seems to be that CoFH World (directly or indirectly) makes its check for the top block against a hardcoded list of Vanilla Blocks or something. Especially since other distribution types work seem to work fine with modded blocks.

Please don't remove the option, because `surface` still works for Vanilla top blocks.

**Note:**
All BiomeTweaker replacement takes place in a generation step way before the Oregen step.

**Comment by KingLemming** [comment]
I agree that the file has nothing to do with the issue, but 00_minecraft.json is only used if vanilla override is enabled. It's not great practice to tie your generation to that option.

I've traced through the code, and lake uses literally the same logic as everything else. There's no hidden list of vanilla-only blocks that it checks against, so I really dunno what to tell you. I guess just don't expect it to work.

**Comment by KingLemming** [comment]
Looking at the Surface Parser, there actually *is* a reasonable list of defaults and it seems that you do need to explicitly specify every material that you want it to generate in. Otherwise it's going to end up using the default list.

What isn't clear I suppose is if "material" needs to be in the distribution or the generator entry.

**Comment by Robijnvogel** [comment]
**Modded Blocks**
Okay, that completely explains my first observation and my initial issue.
Note that I never meant to say that the `lake` generator type was the problem here, though.

Looking at the CoFH World guide, I can see that 

> This is checked before generating an entire feature, unlike generator materials, which are checked for every block while already generating a feature.

implies that it's a separate `material` entry outside the `generator` entry's scope, however I don't think this is made very clear.
I would call it something like `distributionMaterial` myself, however changing it might not be a good idea for _other reasons_.

**Edges**
About my second observation, though. I took a few more screenshots of using the `surface` distribution with the `plate` generator type and it is very visible, that these features are [only placed on the edges/where the height differs](https://i.imgur.com/22ZMCVM.png) for some reason.
I made a screenshot [with](https://i.imgur.com/QYyu1ZZ.png) and [without](https://i.imgur.com/eEz99Pd.png) `follow-terrain` enabled.

Json [here](https://pastebin.com/zF1FYdKs).

**Comment by KingLemming** [comment]
CoFH World will probably get a full rewrite anyways. We tried with 1.1.0, it failed, hence 1.1.1 which was really just a reversion.

As far as plate goes, I *think* the intention was only to use it for underfluid. I'm not sure - I didn't write it. :/ So unfortunately I don't know if that's just a side effect of using it in a non-intended way or not.

**Comment by Robijnvogel** [comment]
I'll try it with something else than plate, then.
I used `plate` because `cluster` with a `cluster-size` of 1 didn't seem to generate anything.

**Comment by Robijnvogel** [comment]
It seems like the issue is that the plate seems to want to generate [**on top** of the surface](https://i.imgur.com/GkJKR39.png) when using the `surface` distribution and `plate` generator. 
This explains why it only showed up on edges, before, since the **generator** was set to only replace _mud_ and no _air_.

Would it be a good idea to keep this issue open as a reminder for when the generation system is really getting overhauled?
