### ISSUE TITLE
Thermal dynamics 2.2.8.16 losing items (Extremely weird behavior involving furnaces), with steps to reproduce

### ISSUE THREAD

**Issue by jamzam90** [CoFH/Feedback#786]
First, sorry for posting about this bug again. I've been determined to figure out whats causing it and how to trigger it to happen.
I've reproduced this issue on three computers and two different minecraft accounts doing the following.
1)  Set up a furnace array with at least 3 vanilla furnaces. (Its seen with multiple furnaces reliably)
2) Then put regular item ducts on the top, bottom and back sides of the furnaces.
3) Have the items ducts on the top and backs of the furnace plugged into the same chest.
4) Use any of the servos which can round robin, so reinforced on up, I use signallum because its faster.
5) Plug the output ducts into a chest and set a retriever to always pull.
6) Add a servo to the input chest filtered to blacklist coal (furnace top ducts)
7) set to round-robin
8) reduce the stack size extracted to 1.
9) Set to ignore redstone.
10) Add another servo to the input chest for the back side of the furnaces.
11) Add a servo to the input chest filtered to whitelist coal (furnace back ducts)
12) set to round-robin 
13) reduce the stack size extracted to 1.
14) Put nine stacks of cobble and coal into the input chest.
15) Watch the ducts and furnaces to see if they are doing anything
Mods
Code Chicken Lib 1.8+ (3.1.5.331)
Cofh core (4.3.8.29)
Cofh world (1.1.1.12)
Jei (4.8.5.138)
Thermal Dynamics (2.2.8.16)
Thermal foundation (2.3.8.22)

**Comment by KingLemming** [comment]
Do not open duplicate issues.
