### ISSUE TITLE
Clathrate ores spill fluid even when mined with silk touch.

### ISSUE THREAD

**Issue by EnderiumSmith** [CoFH/Feedback#787]
Silk touch drops the original block so there is no reason to spill fluid. While not a problem for redstone, glowstone causes extreme lag and i imagine having to search for where your ender ore teleported to is very annoying.

Also i have a question: why do liquid versions of those ore spawn naturally? Shouldn't all of the destabilized redstone be compacted into the solid form by now? And what does resonant ender even do in the ground? I do like them but i'm curious if their existence has any explanation apart from "they're cool"

**Comment by KingLemming** [comment]
In principle, I agree with you. Minecraft, however, does not.

The order of harvest operations means that fluid is always going to spill, sorry.

And they're in the world because they're cool.

**Comment by KingLemming** [comment]
Actually, I'm going to try and hack it. We'll see. I'm sure some mod somewhere will have a corner case with this, but whatever.
