### ISSUE TITLE
Oil sands/gravels behave like stone instead of sand/gravel

### ISSUE THREAD

**Issue by EnderiumSmith** [CoFH/Feedback#788]
The oils are mined with a pickaxe and are not affected by gravity. Since they have the texture of sand/gravel they should fall and be mined with a shovel. Also oil sands should not spawn in stone as it looks weird.

Also the fossil fuel family of clathrates is missing the methane ice. It may not be oil and the crucible would need a bigger tank but methane ices would make ocean more interesting.

**Comment by KingLemming** [comment]
I'm not really fond of entertaining pedantry, but I'm willing to change harvest type to shovels for those two.

Gravity is probably a hard no, since those blocks receive update ticks and therefore cause lag.

**Comment by EnderiumSmith** [comment]
No they don't. you can make sand float using double flowers and its going to stay that way until a block changes. The only blocks that tick are plants, fire, ice, farmland, fluids, lit redstone ore and nether portals. There is no block that ticks to check placement.

**Comment by EnderiumSmith** [comment]
And dont forget the sound. Also Sand and gravel have different sounds

**Comment by KingLemming** [comment]
Okay, now you're getting demanding.

**Comment by covers1624** [comment]
@EnderiumSmith Your assessment of ticking blocks is invalid, BlockFalling (The super class of Sand, Gravel, Concrete and anvils) receives update ticks. It is used for spawning particles, but regardless it ticks. Also imo your comments come across as demanding, a few emoji's here and there wouldn't hurt and would make it sound more friendly :D

**Comment by EnderiumSmith** [comment]
well a few more blocks are not going to make a difference when there is whole dessert of them. Grass is more laggy since it interacts with the surrounding blocks but most biomes are covered in it.
And yes, expecting the sound to match the texture is very demanding ;P I know from experience that setting the sound type of a block is 3 times harder than rewriting how blocks blocks are stored in chunks so you can add stairs, slabs and walls to every block in the game. And yet i managed to do it for my block :D

**Comment by KingLemming** [comment]
It's not the feature which is demanding, it's the way you said it. "And don't forget..." like you are *owed* something. Doesn't work that way.
