### ISSUE TITLE
Rednet cables wont connect

### ISSUE THREAD

**Issue by Saereth** [CoFH/Feedback#788]
Rednet cables dont seem to want to connect to transmit redstone
We're running forge 1448 and MineFactoryReloaded [1.7.10] v2.8.1B1-113

attached a screenshot to make sure its not something wrong with the setup
http://i.imgur.com/MHDaR9D.png

**Comment by spannerman79** [comment]
Not sure what your doing - I'm not going to check if thats the latest version or not but..

http://i.imgur.com/sGJsbcC.png

No issues

**Comment by skyboy** [comment]
Beta/alpha versions have a tendency to intermittently break things. B1-113 is one such version.
