### ISSUE TITLE
[CoFHCore] HarderUnderground and CoFHCore are incompatible. 

### ISSUE THREAD

**Issue by drago87** [CoFH/Feedback#789]
The autor is aware of the problem but are not quite sure why its happening.

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2451299-reasonable-realism-its-a-pack-its-a-mod-it-makes?page=17#c321

the last post on the page before is the error report and OpenEye if interested.

**Comment by skyboy** [comment]
This is not related to CoFHCore. The problem is flowing water doing as flowing water does and flowing, causing block updates.

Relevant methods:
```
net.minecraft.block.BlockDynamicLiquid.func_149813_h(World, int, int, int, int)
net.minecraft.block.BlockDynamicLiquid.updateTick(World, int, int, int, Random)
```
and physics blocks being set to update instantly, as is standard during worldgen.
