### ISSUE TITLE
Pyrolytic Conversion Bug

### ISSUE THREAD

**Issue by SuperHostile** [CoFH/Feedback#789]
The pyrolytic coversion augment is cooking other things that don't produces creosote oil
![2017-12-31_13 23 32](https://user-images.githubusercontent.com/33268599/34461612-c0953ac8-ee2e-11e7-8fcc-f4fb8fcd4fe8.png)

**Comment by KingLemming** [comment]
Need more info than that. What dust is that and which mod adds it?

**Comment by KingLemming** [comment]
Figured it out. IC2 dust. They're doing something dumb, but I should still be catching it.
