### ISSUE TITLE
NoClassDefFoundError

### ISSUE THREAD

**Issue by qchronod** [CoFH/Feedback#79]
Forever Stranded modpack crashing during load.
Crash report: http://pastebin.com/V1cUfcyV

**Comment by KingLemming** [comment]
Please reinstall Forge.

**Comment by KingLemming** [comment]
Removing Forge label since it may not be entirely on them, but this is a standard library that everyone seems to have.

**Comment by qchronod** [comment]
Thank you for mentioning how to fix it. I've forwarded that info to a few other places that reference the same/similar errors.
