### ISSUE TITLE
[Thermal Expansion] Resonant Strongbox is not localized when you have it locked.

### ISSUE THREAD

**Issue by Lovemaxwell** [CoFH/Feedback#79]
I was messing around earlier today, and I saw this when ever I tried to open up a locked strong box. http://puu.sh/ftgED/250ee2eef9.jpg I assume that it is an not localized, it might be something else entirely since I don't mod. I do not know whether or not it exists in all the other ones too. My version of the mod is ThermalExpansion-[1.7.10]4.0.0B8-23 . Thanks, and sorry if I did this wrong first bug report.

**Comment by KingLemming** [comment]
Fixed in dev.

**Comment by TheJulianJES** [comment]
@KingLemming Probaly a stupid question but can you get the dev builds, they both not on Curse and also not on CurseForge. Thank's for the answer!

**Comment by KamranMackey** [comment]
@KingLemming Yeah, what @TheJulianJES said. Is there a way that we can get those dev builds?
