### ISSUE TITLE
[1.12.2-CRASH] Crash when locking fluid in a Fluid Allocator

### ISSUE THREAD

**Issue by Leosky** [CoFH/Feedback#791]
Crashlog : https://gist.github.com/Leosky/91ee719c364dabe61a46bce32e8d06c8

**Comment by KingLemming** [comment]
That's interesting. This can only happen if you have a null fluid. Which isn't actually possible.

I'm gonna need more info. Modlist and video, ideally.

**Comment by KingLemming** [comment]
Ah, found it.

**Comment by Leosky** [comment]
wow, faster than light :p
