### ISSUE TITLE
Tank Render Crash

### ISSUE THREAD

**Issue by RoloEdits** [CoFH/Feedback#791]
http://pastebin.com/uJNsMWnH

I got this crash and still get this crash every time I log in a world after putting canola seeds from rotarycraft in the magma crucible and exporting the lubricant directly to a tank on top.

**Comment by KingLemming** [comment]
Something jacked with the NBT data and put the tank into an invalid state in your world. NBTedit it out.

This isn't a code error, it's something wrong with your save.

**Comment by RoloEdits** [comment]
It worked.Thank You very much.

**Comment by RoloEdits** [comment]
Iv'e figured out the problem, if you change the setting for the tank size in the config to high it crashes once it reach a certain capacity. Default settings work with no crash. Is this supposed to happen?

**Comment by RoloEdits** [comment]
Iv'e figured out the problem, if you change the setting for the tank size in the config to high it crashes once it reach a certain capacity. Default settings work with no crash. Is this supposed to happen?
