### ISSUE TITLE
[Suggestion] Reservoir 'bucket mode'

### ISSUE THREAD

**Issue by Leosky** [CoFH/Feedback#792]
The way the Reservoir actually only grab liquid if you target a block next to it made it tedious to use in some situation like lava collection and energized glowstone. Another thing is to be able to switch to 'all' and 'bucket' mode next of empty / fill mode to be able to interact with tank more precisely.

**Comment by KingLemming** [comment]
I can change up the hit detection a bit, but I don't plan on adding any more modes to the reservoir.

**Comment by Leosky** [comment]
detection change is already a good change :)

**Comment by KingLemming** [comment]
The problem with more modes is that the controls get unwieldy. It already effectively has 4 modes and 2 degrees of freedom.

And yeah, having tested it, I agree - the detection change is good.
