### ISSUE TITLE
[Thermal Dynamics] Cover Rendering bug

### ISSUE THREAD

**Issue by SuperSandro2000** [CoFH/Feedback#792]
![](http://i.imgur.com/wx7BqyI.png)
I used at the left stone bricks and in the middle Laboratory blocks from Chisel.

**Comment by KingLemming** [comment]
This isn't very descriptive.

**Comment by SuperSandro2000** [comment]
I think that somehow meta data is a bit shacked around. It is not always the same block that is visivle. For example stone brick shows as mossy or cracked stone bricks and laboratory blocks as the chisel variants in bright light with different textures. but when I wrench them they are still the original item.

**Comment by KingLemming** [comment]
It sounds like this is actually caused by Chisel and how it's attempting to do connected textures with TD's covers.

**Comment by SuperSandro2000** [comment]
I'm not running the latest version of chisel because because CTM always crashes me. Maybe I try to update. Any other idea? (I can't remove chisel because almost everything is mad eiwth chisel.)

**Comment by KingLemming** [comment]
Just to be clear, this only happens when adjacent to Chisel blocks?

**Comment by SuperSandro2000** [comment]
No, the cracked stone  above the igneus extruder is actually stone brick and all covers are messes up regardless where they are.

**Comment by KingLemming** [comment]
I'll have @RWTema take a look, but this sounds like your world has been borked somehow. There's nothing in our code where the metadata would randomly change or be incorrect.

**Comment by SuperSandro2000** [comment]
The block below the igneus extruder I newer saw before. The walls, the floor and the ceiling should look the same in the entire room.

**Comment by SuperSandro2000** [comment]
And you could say tema that he should fix the bug above 1.2.5 with random playing sounds when playing with gregtech.

**Comment by SuperSandro2000** [comment]
I did some testing and found some weird behavior. Some ducts are afectat and some not.
![](http://i.imgur.com/9RqsQV0.png)
