### ISSUE TITLE
Coal Coke and Steam Dynamos

### ISSUE THREAD

**Issue by DrakoAlcarus** [CoFH/Feedback#793]
The RailCraft Coal Coke doesn't seem to have an extended burn time like it should when used in the Steam Dynamos. I'm not sure if this was intended,though.

**Comment by KingLemming** [comment]
It's higher than normal, but it's not artificially inflated to moon math numbers, no. Intended.

**Comment by DrakoAlcarus** [comment]
How is it higher than normal? I did a speed check with the dynamos, and both ended burning at the same exact time. I also checked the energy production amount, and both ended at 44,000 Rf. I had no upgrades.
