### ISSUE TITLE
[1.12.2] Experience duplication with Tome of Knowledge

### ISSUE THREAD

**Issue by Leosky** [CoFH/Feedback#793]
It its not really a duplication but more a 'ignore change' bug. It's pretty simple to reproduce. Empty the tome, repair/enchant/etc to spend experience, refill the tome then empty it again. The experience is back to its initial value.

**Comment by Leosky** [comment]
i forgot to say i have a Holding IV on the tome but i think this was already bugged before the enchantment.

**Comment by paul-soporan** [comment]
@785

**Comment by Leosky** [comment]
crap, closing this.
