### ISSUE TITLE
[CoFHTweaks] Chunkloading issue

### ISSUE THREAD

**Issue by Skillotic0703** [CoFH/Feedback#796]
Sometimes, when I'm in caves, I can see through blocks depending on my position (where I look and where I am).

I'm using forge 10.13.4.1448 and CoFHTweaks-[1.7.10]1.0.0RC1-35.
I have some other mods but they just modify the gameplay (I don't have Fastcraft, Optifine etc...)

Forge log : http://pastebin.com/CGezgetb

**Comment by skyboy** [comment]
Fixed in the release version
