### ISSUE TITLE
Crafting a tesseract should clear its settings

### ISSUE THREAD

**Issue by UntouchedWagons** [CoFH/Feedback#798]
This would be simply a convenience thing but putting a configured tesseract into a crafting window should clear its settings.

**Comment by KingLemming** [comment]
Ehh...not security, no.

**Comment by UntouchedWagons** [comment]
It could be a owner specific recipe, I wouldn't be able to reset your tesseracts but I could reset mine.

**Comment by KingLemming** [comment]
Unfortunately, there's no way to do that. Minecraft doesn't pass in the owner when it comes to doing crafting recipes. So this is actually a very difficult idea.

**Comment by UntouchedWagons** [comment]
I had [found](http://www.minecraftforge.net/forum/index.php/topic,23133.0.html) tutorial on the MinecraftForge forum about player specific recipes. It may be useful.

**Comment by SHIuSH** [comment]
how about crafting 2 tesseracts gives you tesseract with duplicated settings?

**Comment by isochronous** [comment]
I'd reeeaaaally like this to happen, at least for non-secure tesseracts. I've run into a bug a couple of times where a tesseract's config got corrupted and any further attempts to access its GUI crashed my client, and I basically had to throw those tesseracts away. It's a rare issue that I've never been able to reproduce on purpose, but when it happens it's rather infuriating.
