### ISSUE TITLE
Thermal Foundation is not marked as a Curse Dependency for Thermal Expansion

### ISSUE THREAD

**Issue by mezz** [CoFH/Feedback#8]
When installing Thermal Expansion with Curse, it sees CoFHCore and CodeChickenLib1.8 as "Required Library" and downloads them. It is missing the dependency on Thermal Foundation.
https://minecraft.curseforge.com/projects/thermalexpansion/files/2388879

**Comment by KingLemming** [comment]
Ah ha. Fixing that now.
