### ISSUE TITLE
[Bug] Redstone Plate is not functioning

### ISSUE THREAD

**Issue by Yulife** [CoFH/Feedback#8]
**Mod name:** Thermal Expansion

**Mod list**: [Link](http://paste.ee/p/5E8C4)

**Description:**
Basically when I was testing the new plates that got introduced to Thermal Expansion recently I noticed that all plates worked but the Redstone type.
Asking through reddit and IRC I heard that it is supposed to transmit redstone "wirelessly" over a certain amount of blocks. However, I cannot reproduce this functionality.
[Proof](https://i.imgur.com/W2KJzVt.png)

**Comment by KingLemming** [comment]
The plate works fine, but it only works 15 blocks away. They aren't finalized - there will be a config GUI. The intention is not to activate every block in an area or along a line; that'd be extremely laggy.

**Comment by Yulife** [comment]
I see! Cheers ~
