### ISSUE TITLE
Pulverizer texture disappeared suddenly, had to restart client

### ISSUE THREAD

**Issue by TheChance** [CoFH/Feedback#80]
See screenshot. I wanted to test whether the TE sawdust was oredicted to match wood pulp and TR sawdust for making paper (it's not, bummer, but that's life.)

So I placed that carpenter, put water in it, turned right to pulverize some wood, and that was the state of my pulverizer. Picking up and replacing the pulverizer didn't help; the texture was missing in JEI and my inventory as well. Mouse over an empty square, see a basic pulverizer tooltip =P

Quitting to the menu and reloading the world did not fix it, but restarting the client did. Unsure if those steps to repro will work.

FTB Beyond 1.0.1, TE 5.0.1.73
![2017-03-10_17 17 54](https://cloud.githubusercontent.com/assets/2975131/23819162/571474ca-05b7-11e7-84b2-a689a1d00f65.png)

The only possibly-relevant thing in the log is the following, which TOP has thrown a few times, but according to IRC timestamps, it threw it about 10 minutes before and again 5 minutes after this happened, not right when it happened. I'm just gonna toss it in a gist.

https://gist.github.com/TheChance/2edbf013b6cefd7e575df3a1f1e20059

**Comment by KingLemming** [comment]
Gotta update. Already handled that.
