### ISSUE TITLE
crash on server start

### ISSUE THREAD

**Issue by SirWindfield** [CoFH/Feedback#800]
https://pastebin.com/1GsTX4Bb

Looks like it is another method that isnt found, not the ÌtemMob` error message that others get.

**Comment by KingLemming** [comment]
Okay, so you don't have the right version of TE for this. There will be a new one coming shortly.

**Comment by SirWindfield** [comment]
ah ok :smile: sorry to have bothered you :D

**Comment by KingLemming** [comment]
npnp. New one is up on CurseForge now.
