### ISSUE TITLE
Thermal Dynamics Cover Creative Tab

### ISSUE THREAD

**Issue by Beanius** [CoFH/Feedback#801]
http://pastebin.com/149HHfPJ
Met upon this bug when i clicked the creative cover tab.
I do have about 130 other mods isntalled as well + Fastcraft/Optifine.

**Comment by KingLemming** [comment]
So basically you didn't search existing issues. Got it.

This is not caused by us, but you can disable the tab.

**Comment by Beanius** [comment]
Ohhhh!!!! Yeah I was in a hurry so totally forgot to do that * -*! Wooops. Thanks a lot :D
