### ISSUE TITLE
Redstone Relays cannot signal cross-grid - is there a workaround?

### ISSUE THREAD

**Issue by Xiaminou** [CoFH/Feedback#801]
If you want a redstone signal to go across two different Thermal Dynamics pipes you have to place two redstone relays in between those pipes. However when you turn off the source of the redstone signal it does not transmit it properly to other pipes until you update the redstone relays.
Video: https://youtu.be/0AfgGhl-t84

I would also like to take this opportunity to ask, is it intended that redstone signals do no travel through connected pipes if they're different?

Minecraft: 1.12.2
Forge: 2583
Thermal Dynamics: 2.3.9.2
Mods: [list.txt](https://github.com/CoFH/Feedback/files/1598386/list.txt)

**Comment by KingLemming** [comment]
I seem to remember this being an intentional limitation to prevent redstone update loop crashes. I'll see if the logic can be adjusted.

As far as your question, yes - that's intentional, signals are grid-wide.

**Comment by KingLemming** [comment]
I'm not sure if this will end up addressed or not, simply because a full TD rewrite is in the cards and this probably won't be relevant to the new paradigm.

**Comment by ImbaKnugel** [comment]
Structure ducts transmit their redstone signal to other duct grids even without relays in between. This seems to create the redstone loop seen in the video. You can avoid this bug by not using two relays between a structuralduct grid and another duct grid.

**Comment by Xiaminou** [comment]
Good call, it works.
![2018-01-03_16 06 18](https://user-images.githubusercontent.com/8670392/34525675-14c96e52-f0a0-11e7-9a12-f439f03d6815.png)

**Comment by EnderiumSmith** [comment]
cant you put a structure duct between the power and item one instead of 2 relays?

**Comment by Xiaminou** [comment]
Not if you want to transfer power between them. This is just an example but the idea is to have Fluxduct transfer power to Signalum Plated ducts.
But yes, if you wanted to only transfer a redstone signal it would be easier, if there is room, to put a Structuralduct.
