### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by alevys25** [CoFH/Feedback#802]
Game Crashed on version 1.12.2

The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Thermal Expansion (thermalexpansion)

**Comment by fallennewyork** [comment]
Same problem as me...

**Comment by KingLemming** [comment]
This is not helpful AT ALL. We need a crashlog.

**Comment by fallennewyork** [comment]
Do you mean the "fml-client-latest"? There are much more of crash files...

**Comment by fallennewyork** [comment]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  ForgelinPlugin (Forgelin-1.6.0.jar)
  TransformerLoader (OpenComputers-MC1.12.1-1.7.1.43.jar)
  CTMCorePlugin (CTM-MC1.12-0.2.3.9.jar)
  FarseekCoreMod (Farseek-1.12-2.2.2.jar)
  BetterFoliageLoader (BetterFoliage-MC1.12-2.1.10.jar)
Contact their authors BEFORE contacting forge

// There are four lights!

Time: 1/2/18 8:48 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Thermal Expansion (thermalexpansion)
Caused by: java.lang.NoSuchMethodError: cofh.core.block.BlockCoreTile: method <init>(Lnet/minecraft/block/material/Material;)V not found
	at cofh.thermalexpansion.block.BlockTEBase.<init>(BlockTEBase.java:49)
	at cofh.thermalexpansion.block.machine.BlockMachine.<init>(BlockMachine.java:70)
	at cofh.thermalexpansion.init.TEBlocks.preInit(TEBlocks.java:29)
	at cofh.thermalexpansion.ThermalExpansion.preInit(ThermalExpansion.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:606)
	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:253)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:231)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:602)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:270)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1831487952 bytes (1746 MB) / 2620391424 bytes (2499 MB) up to 7635730432 bytes (7282 MB)
	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8G
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.1.2582 Optifine OptiFine_1.12.2_HD_U_C7 66 mods loaded, 66 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                      | Version           | Source                                          | Signature                                |
	|:----- |:----------------------- |:----------------- |:----------------------------------------------- |:---------------------------------------- |
	| UCH   | minecraft               | 1.12.2            | minecraft.jar                                   | None                                     |
	| UCH   | mcp                     | 9.42              | minecraft.jar                                   | None                                     |
	| UCH   | FML                     | 8.0.99.99         | forge-1.12.2-14.23.1.2582.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge                   | 14.23.1.2582      | forge-1.12.2-14.23.1.2582.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | opencomputers|core      | 1.7.1.43          | minecraft.jar                                   | None                                     |
	| UCH   | mercurius_updater       | 1.0               | MercuriusUpdater-1.12.2.jar                     | None                                     |
	| UCH   | appliedenergistics2     | rv5-stable-3      | appliedenergistics2-rv5-stable-3.jar            | None                                     |
	| UCH   | architecturecraft       | @VERSION@         | architecturecraft-1.12-1.20.jar                 | None                                     |
	| UCH   | baubles                 | 1.5.0             | Baubles-1.12-1.5.0.jar                          | None                                     |
	| UCH   | betterfoliage           | 2.1.10            | BetterFoliage-MC1.12-2.1.10.jar                 | None                                     |
	| UCH   | bibliocraft             | 2.4.3             | BiblioCraft-Mod-1.12.jar                        | None                                     |
	| UCH   | biomesoplenty           | 7.0.1.2302        | BiomesOPlenty-1.12.2-7.0.1.2302-universal.jar   | None                                     |
	| UCH   | botania                 | r1.10-351         | Botania r1.10-351.jar                           | None                                     |
	| UCH   | codechickenlib          | 3.1.3.313         | CodeChickenLib-1.12-3.1.3.313-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCH   | redstoneflux            | 2.0.1             | RedstoneFlux-1.12-2.0.1.2-universal.jar         | d4f1503fbacd9b9fb767720420c5395104239ec9 |
	| UCH   | brandonscore            | 2.3.7             | BrandonsCore-1.12-2.3.7.140-universal.jar       | None                                     |
	| UCH   | buildcraftlib           | 7.99.12           | BuildCraft-Mod-1.12.2.jar                       | None                                     |
	| UCH   | buildcraftcore          | 7.99.12           | BuildCraft-Mod-1.12.2.jar                       | None                                     |
	| UCH   | buildcraftbuilders      | 7.99.12           | BuildCraft-Mod-1.12.2.jar                       | None                                     |
	| UCH   | buildcraftenergy        | 7.99.12           | BuildCraft-Mod-1.12.2.jar                       | None                                     |
	| UCH   | buildcraftfactory       | 7.99.12           | BuildCraft-Mod-1.12.2.jar                       | None                                     |
	| UCH   | buildcraftrobotics      | 7.99.12           | BuildCraft-Mod-1.12.2.jar                       | None                                     |
	| UCH   | buildcraftsilicon       | 7.99.12           | BuildCraft-Mod-1.12.2.jar                       | None                                     |
	| UCH   | buildcrafttransport     | 7.99.12           | BuildCraft-Mod-1.12.2.jar                       | None                                     |
	| UCH   | ctm                     | MC1.12-0.2.3.9    | CTM-MC1.12-0.2.3.9.jar                          | None                                     |
	| UCH   | chisel                  | MC1.12-0.1.1.24   | Chisel-Mod-1.12.1.jar                           | None                                     |
	| UCH   | cloneland               | 1.6               | CloneLand-1.6.jar                               | None                                     |
	| UCH   | cofhcore                | 4.3.9             | CoFHCore-1.12.2-4.3.9.2-universal.jar           | None                                     |
	| UCH   | cofhworld               | 1.1.1             | CoFHWorld-1.12.2-1.1.1.12-universal.jar         | None                                     |
	| UCH   | thermalfoundation       | 2.3.9             | ThermalFoundation-1.12.2-2.3.9.2-universal.jar  | None                                     |
	| UCH   | draconicevolution       | 2.3.7             | Draconic-Evolution-1.12-2.3.7.278-universal.jar | None                                     |
	| UCH   | extracells              | 2.5.9             | ExtraCells-1.12.2-2.5.9a45.jar                  | None                                     |
	| UCH   | farseek                 | 2.2.2             | Farseek-1.12-2.2.2.jar                          | None                                     |
	| UCH   | ftfloocraft             | 1.8               | Floocraft-Mod-1.12.2.jar                        | None                                     |
	| UCH   | ic2                     | 2.8.16-ex112      | Industrial-Craft-2-Mod-Experimental-1.12.1.jar  | de041f9f6187debbc77034a344134053277aa3b0 |
	| UCH   | jei                     | 4.7.8.95          | Just-Enough-Items-Mod-1.12.1.jar                | None                                     |
	| UCH   | forestry                | 5.7.0.219         | forestry_1.12.2-5.7.0.219.jar                   | None                                     |
	| UCH   | forgelin                | 1.6.0             | Forgelin-1.6.0.jar                              | None                                     |
	| UCH   | ichunutil               | 7.1.4             | iChunUtil-1.12.2-7.1.4.jar                      | None                                     |
	| UCH   | mekanism                | 9.4.0             | Mekanism-1.12-9.4.0.314.jar                     | None                                     |
	| UCH   | teslacorelib            | 1.0.12            | tesla-core-lib-1.12-1.0.12.jar                  | None                                     |
	| UCH   | industrialforegoing     | 1.12.2-1.12.1     | Industrial-Foregoing-Mod-1.12.2.jar             | None                                     |
	| UCH   | ironchest               | 1.12.2-7.0.34.820 | ironchest-1.12.2-7.0.34.820.jar                 | None                                     |
	| UCH   | mantle                  | 1.12-1.3.1.21     | Mantle-Mod-1.12.1.jar                           | None                                     |
	| UCH   | mekanismgenerators      | 9.4.0             | MekanismGenerators-1.12-9.4.0.314.jar           | None                                     |
	| UCH   | mekanismtools           | 9.4.0             | MekanismTools-1.12-9.4.0.314.jar                | None                                     |
	| UCH   | metamorph               | 1.1.4             | Metamorph-1.12.2.jar                            | None                                     |
	| UCH   | radixcore               | 1.12.x-2.2.1      | RadixCore-1.12.x-2.2.1-universal.jar            | None                                     |
	| UCH   | mca                     | 1.12.2-5.3.1      | Minecraft-Comes-Alive-Mod-1.12.2.jar            | None                                     |
	| UCH   | mtrm                    | 1.2.2.30          | MineTweaker-RecipeMaker-Mod-1.12.2.jar          | None                                     |
	| UCH   | morph                   | 7.1.2             | Morphing-Mod-1.12.2.jar                         | None                                     |
	| UCH   | nei                     | ${mod_version}    | NotEnoughItems-1.12-2.4.0.231-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCH   | opencomputers           | 1.7.1.43          | OpenComputers-MC1.12.1-1.7.1.43.jar             | None                                     |
	| UCE   | thermalexpansion        | 5.3.7             | ThermalExpansion-1.12.2-5.3.7.31-universal.jar  | None                                     |
	| UCH   | redstonearsenal         | 2.3.9             | RedstoneArsenal-1.12.2-2.3.9.2-universal.jar    | None                                     |
	| UCH   | rftools                 | 7.22              | rftools-1.12-7.22.jar                           | None                                     |
	| UCH   | spectrite               | 1.6.1             | Spectrite-Mod-1.12.jar                          | 00119cfc089819bbcd2f9166a50c7f3df88ded78 |
	| UCH   | streams                 | 0.4.1             | Streams-Mod-1.12.1.jar                          | None                                     |
	| UCH   | tconstruct              | 1.12-2.8.1.49     | Tinkers-Construct-Mod-1.12.1.jar                | None                                     |
	| UCH   | bspkrscore              | at_0.9            | TreeCapitator-Mod-1.12.jar                      | None                                     |
	| UCH   | treecapitator           | at_0.9            | TreeCapitator-Mod-1.12.jar                      | None                                     |
	| UCH   | twilightforest          | 3.5.263           | twilightforest-1.12.2-3.5.263-universal.jar     | None                                     |
	| UCH   | wailaharvestability     | 1.1.11            | Waila-Harvestability-Mod-1.12.jar               | None                                     |
	| UCH   | waterfreefarming        | 2.0.2             | waterfreefarming-1.12.2-2.0.4.jar               | None                                     |
	| UCH   | xaerominimap            | 1.13.9            | Xaeros-Minimap-Mod-1.12.jar                     | None                                     |
	| UCH   | teslacorelib_registries | 1.0.12            | tesla-core-lib-1.12-1.0.12.jar                  | None                                     |

	Loaded coremods (and transformers): 
ForgelinPlugin (Forgelin-1.6.0.jar)
  
TransformerLoader (OpenComputers-MC1.12.1-1.7.1.43.jar)
  li.cil.oc.common.asm.ClassTransformer
CTMCorePlugin (CTM-MC1.12-0.2.3.9.jar)
  team.chisel.ctm.client.asm.CTMTransformer
FarseekCoreMod (Farseek-1.12-2.2.2.jar)
  farseek.core.FarseekClassTransformer
BetterFoliageLoader (BetterFoliage-MC1.12-2.1.10.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 388.13' Renderer: 'GeForce GTX 1060 6GB/PCIe/SSE2'
	AE2 Version: stable rv5-stable-3 for Forge 14.23.1.2554
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)

	OptiFine Version: OptiFine_1.12.2_HD_U_C7
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 388.13
	OpenGlRenderer: GeForce GTX 1060 6GB/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

**Comment by KingLemming** [comment]
Please go download the latest version of Thermal Expansion. :( That's literally the problem - you have not updated all your CoFH mods.

It's literally on the readme - go get latest versions of everything.
