### ISSUE TITLE
Warp Ducts crash..

### ISSUE THREAD

**Issue by MrSapient** [CoFH/Feedback#803]
http://pastebin.com/RHqnx92F

Also getting wicked dropped FPS when looking at these ducts.. or removing them .. ( FPS is always 200+ then drops to 40s )

Forge - 10.13.4.1492
Thermal - 1.1.0-161

**Comment by XFactHD** [comment]
Remove Optifine!

**Comment by MrSapient** [comment]
Still dose it with out optifine .. i tried installing with to fix FPS drop..

**Comment by XFactHD** [comment]
That's weird. Normally, Optifine is the cause of this crash.

**Comment by MrSapient** [comment]
No sorry the crash dose not happen with out it .. the FPS drop dose!

**Comment by KingLemming** [comment]
Crash isn't us, sorry. Another mod is setting up a trap and we're falling into it, at best/worst.

As far as FPS dropping, your computer apparently can't handle shaders very well. Disable them in the config options.

**Comment by MrSapient** [comment]
Not using shaders .. and using a high end pc..

GTX 770 
i7 4790k 
16gb of ram ..

**Comment by MrSapient** [comment]
http://pastebin.com/hSTbjMEL

Crash again.
