### ISSUE TITLE
[Thermal Expansion/Foundation] Custom Compatibility with EnderIO

### ISSUE THREAD

**Issue by DrakoAlcarus** [CoFH/Feedback#804]
I was wondering if the following metal compounds could be added, and with their recipes to become EnderIO metals:

1 Soul Sand + 1 Gold =Induction Furnace=> 1 Solarium Ingot

1 Coal/Charcoal Powder + Silicon =Crafting=> 1 Electrical Mixture
1 Electrical Mixture + 1 Iron Ingot =Induction Furnace=> 1 Electrical Steel

1 Redstone + 1 Gold Ingot =Crafting=> Energized Compound
1 Energized Compound + 1 Glowstone Dust =Induction Furnace=> 1 Energetic Alloy
1 Energetic Alloy + 1 Ender Pearl =Induction Furnace=> 1 Vibrant Alloy

1 Redstone + 1 Silicon =Induction Furnace=> 1 Redstone Alloy

1 Redstone + 1 Iron Ingot =Induction Furnace=> 1 Conductive Iron

1 Ender Pearl + 1 Iron Ingot =Induction Furnace=> 1 Pulsating Iron

4 Pulverized Obsidian + 1 Coal Dust =Induction Furnace=> 1 Hardened Carbon
1 Hardened Carbon + 1 Iron Ingot =Induction Furnace=> 1 Dark Iron

1 Sand + 1 Glass =Induction Furnace=> 2 Quite Clear Glass
1 Quite Clear Glass + 4 Glowstone Dust =Induction Furnace=> Enlightened Clear Glass

1 Block of Quartz =Redstone Furnace=> Fused Quartz
1 Fused Quartz + 4 Glowstone Dust =Induction Furnace=> Enlightened Quartz Glass

The reason is due to the fact I favor your Induction Furnace, because it has the necessary functions I require to advance, and having both an Alloy Smelter plus an Induction furnace feels more redundant. I like the Induction Furnaces textures, function (alloys and slag), and smoothness. EnderIO is fine, but I would like to have one alloy maker, and save room for another Pulverizer.

Also, can you add Ender IO Anvil upgrades to the Flux armor for Redstone Arsenal? It would be fun to have a full set of flux armor, and have triple jump or night vision.

_P.S. Any plans on changing the texture for the Sawmill?_

**Comment by XFactHD** [comment]
I made an add-on for EnderIO and TE that adds the alloy recipes to the TE Induction Smelter. If you want other recipes to be added, you are welcome to make an issue here: https://github.com/XFactHD/EIORecipesTEInductionSmelter.
PS: I think that sort of cross-mod compatibility doesn't have to be included in the main mod. Are you OK with that @KingLemming?

**Comment by DrakoAlcarus** [comment]
Where would I put this mod so it could function?

**Comment by XFactHD** [comment]
Just put it in your mods folder.

**Comment by DrakoAlcarus** [comment]
Doesn't seem to work.

**Comment by XFactHD** [comment]
Which Minecraft version are you using and what are you trying to produce?

**Comment by DrakoAlcarus** [comment]
It's 1.7.10, but... I eventually took out EnderIO.

**Comment by XFactHD** [comment]
I could perhaps make the mod crash if the required mods are not installed.
