### ISSUE TITLE
CoFH World breaks my game.

### ISSUE THREAD

**Issue by DrEvilAybolit** [CoFH/Feedback#804]
Hi, I have a problem. When I installed Thermal Foundation and Thermal Expansion, I haven't installed CoFh World, but the world generated correctly, with custom ores. When I restarted the game, it showed me the error screen, because i haven't installed CoFH World. I installed it, but now the game straight up won't launch! It does the Forge loading screen, butmain menu won't come up. Please help.

p.s.: sorry for engrish, im russian

**Comment by covers1624** [comment]
Without screenshots or a log file we have no way of helping you, please verify you are on the LATEST of ALL cofh mods, some builds were broken last night and bad jars got released.

**Comment by DrEvilAybolit** [comment]
It seems like I got a broken build you're talking about, because it seems to work now. Thanks for your help!

**Comment by covers1624** [comment]
No worries.
