### ISSUE TITLE
[1.12.2] Thermal Cultivation Crash

### ISSUE THREAD

**Issue by GWSheridan** [CoFH/Feedback#805]
crash when watering crops with watering can

Crash Log: https://pastebin.com/3HrXFgD9

MC: 1.12.2
Forge: 14.23.1.2582
Thermal Cultivation: 0.1.3.11

**Comment by ImbaKnugel** [comment]
Updating Thermal Cultivation to 0.1.4 should fix this.

**Comment by covers1624** [comment]
Update your mods before submitting issues. It's even in the repo readme..  
Verify that the issue is fixed by 0.1.4 as @ImbaKnugel recommended please.

**Comment by KingLemming** [comment]
I already know the update will fix it.
