### ISSUE TITLE
[Thermal Expansion]Fluid Transposer Bug

### ISSUE THREAD

**Issue by Benjamin1433** [CoFH/Feedback#805]
This is a Fluid Transposer bug I have found while playing in my survival world.

If you take a filled water glass bottle, set the transposer mode to fill, and put the bottle in, it takes the water out of it, and puts it into the transposer - but gives you a bucket back.

I originally found this bug in my custom modpack with 150+ mods, and I thought one mod would have caused this. I was wrong, I loaded the mod up all by itself, nothing else. (except COFH Core, of course.) and I still got the same results.
I will compile a list of mods later today, I don't have the time right now. But because this bug occurs even with no other mods installed, I don't think a mod list will be needed.

This is with the latest version,
1.7.10 4.0.3B1-218

**Comment by psusi** [comment]
I was just going to report the reverse of this bug: I put in a water bucket, and got back an empty bottle, and only 333 mb of water in the machine.

**Comment by Benjamin1433** [comment]
That's odd, I just tried that, and it gave me the bucket like it was supposed to. What version are you using?

**Comment by psusi** [comment]
4.03.B1-218.

My full list of mods is:

appliedenergistics2-rv2-stable-10.jar
backpack-2.0.0-1.7.x.jar
CodeChickenCore-1.7.10-1.0.4.29-universal.jar
CoFHCore-[1.7.10]3.0.3-303.jar
Enchiridion-1.7.X-1.2b.jar
forestry_1.7.10-3.6.3.20.jar
Mantle_mc1.7.10_0.3.0.jar
MapWriter-1.7.10-2.1.2.jar
MineFactoryReloaded-[1.7.10]2.8.0-104.jar
NEIIntegration-MC1.7.10-1.0.11.jar
NotEnoughItems-1.7.10-1.0.4.94-universal.jar
Railcraft_1.7.10-9.6.1.0.jar
RedstoneArsenal-[1.7.10]1.1.1-89.jar
ThermalDynamics-[1.7.10]1.1.0-161.jar
ThermalExpansion-[1.7.10]4.0.3B1-218.jar
ThermalFoundation-[1.7.10]1.2.0-102.jar
Waila-1.5.10_1.7.10.jar

**Comment by ErdrickXLII** [comment]
This seems to be a recipe bug on MFR's end.  Version 2.8.0-104 turns buckets of water and milk into bottles, and version 2.8.1B1-131 does the opposite.

The "only 333mB of water" part is a different mod overwriting the water bottle's fluid capacity, but I haven't tracked down which mod it is.
