### ISSUE TITLE
COFH Core crash?

### ISSUE THREAD

**Issue by e30Birdy** [CoFH/Feedback#806]
Sorry I don't know but it looks like to me thats what was causing it. Just updated a lot of mods in my pack to newest version to hopefully fix some of the issues and updates especially for TE2 and now getting this.

https://pastebin.com/viFpgZiT

**Comment by KingLemming** [comment]
Nope. Please update Whoosh.

**Comment by e30Birdy** [comment]
Thanks, yeah I just read it myself and was going to close the ticket.
