### ISSUE TITLE
[Thermal Expansion] Resonant Energy Cell - Max charge RF/t

### ISSUE THREAD

**Issue by ExDomino** [CoFH/Feedback#808]
The Resonant Energy Cell on my server can only charge at 32000 RF/t. But if I connect it next to a Nether Star Generator (that produces 40960 RF/t according to the wiki) the Resonant Energy Cell can handle all of the energy and the internal buffer of the Nether Star Generator will never reach 100% until the Resonant Energy Cell will be full. Same thing with a BigReactor that produce up to 145000 RF/t connected to a Resonant Energy Cell with Cryotheum Cables (unlimited RF/t), the internal buffer of the reactor reach 100% only when the Resonant Energy Cell is full.

I don't know if this is a bug or not, but if you could explain me something about that, thank in adavance! ^^

**Comment by KingLemming** [comment]
Without knowing your exact setup, I can't tell you why exactly this is happening.

However, what I can tell you is that the cell limits are per side and per transaction. So if something is happening to violate either of those conditions (multiple side connections or multiple transfers per tick), then this will happen.

TL,DR: There's nothing wrong with cells. Just a quirk of how things may send energy to them.
