### ISSUE TITLE
Thermal Expansion Update issues

### ISSUE THREAD

**Issue by thetrin777** [CoFH/Feedback#809]
Hello, everyone.

http://pastebin.com/zaN63B8X

The pastebin above is the error report I am getting. Everything that I can find on this problem is updating mods. I am guessing this is the case. So, could someone maybe tell me which non-updated mods are causing the problem? And, if by some chance I have an incompatible version of any CoFH mods, which release version I need to use?

thanks in advance!

**Comment by KingLemming** [comment]
Can't reproduce this at all, sorry. We've also never heard of this.
