### ISSUE TITLE
[Suggestion] Mystical Ag Duplicate Seeds & Phytogenic Insolator

### ISSUE THREAD

**Issue by Mohron** [CoFH/Feedback#809]
Using current 1.12.2 version of Mystical Agriculture (MA) and the COFH Suite, the Phytogenic Insolator allows players to "duplicate" MA seeds regardless of the MA config setting for extra seed drops.  When seed drops are set to 0% chance in MA's config, it would be preferable if there was an easy way to remove the extra seed production from all MA Phytogenic Insolator recipes without needing to rewrite every recipe using CraftTweaker/ModTweaker.

Thank you for your consideration!

**Comment by KingLemming** [comment]
This can't really be easily done since the augments will still work to increase the effective amount to over 100.

If you mean just changing the default recipe, then sure, no problem.

**Comment by Mohron** [comment]
If removing the default duplication chance for MA's seeds without changing each recipe individually was possible, I would certainly use it. The augments are much more easily addressed then all the individual recipes for one mod.

**Comment by KingLemming** [comment]
How are they more easily addressed? There's no way to remove them from just one machine.

**Comment by Mohron** [comment]
From a modpack maker perspective, the specific augments that make the secondary output chance higher can easily be removed or _rebalanced_.  I know my players are only using Phytogenic Insolators with MA specifically to bypass having to craft more than one seed (the purpose of disabling the additional drop chance) and otherwise use IE's garden cloches for actually farming essences. My goal is to find a sane way to address overly simplified seed duplication.  I welcome any thoughts you have on solving this matter.

**Comment by EnderiumSmith** [comment]
if they use the cloche to farm them why not remove the recipe for the insolator?

**Comment by Mohron** [comment]
That would be my least prefered fix because I don't want to lessen the usefulness of the Phytogenic Insolator. But unless there's already a config to disable all the recipes for MA, it would require a large amount of scripting to do (making it much easier to handle with a mod).

**Comment by KingLemming** [comment]
There is actually exactly that config. Check common.cfg and "Plugins"

**Comment by Mohron** [comment]
I can and will use that if that's considered the best course of action for handling plants where seed duplication is unwanted.

**Comment by KingLemming** [comment]
Okay, here's what I've done.

The Plugin has been modified to provide additional config options - you can set the % chance of a seed output for each variant of Phyto-Gro. It's now 100/105/110 by default. So that's up to you to balance. :)

All normal MA seeds use 2x energy and water; Inferium seeds now have a scaling energy cost per tier, and use 4x as much water.

**Comment by Mohron** [comment]
Sounds like a great capability and I look forward to being able to use it!
