### ISSUE TITLE
Every version of thermal expansion crashes with 1.7.10 please help me!!!!

### ISSUE THREAD

**Issue by logan3mclean** [CoFH/Feedback#81]
My minecraft keeps crashing with this report I CANT TAKE IT ANY MORE HELP AS SOON AS POSSIBLE!!!!!!!
Even with thermal expansion alone it crashes
plz fix it Its crashes with every thermal expansion version that is for download on 1.7.10
Hope this crash report helps
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 2/4/15 6:27 PM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoSuchMethodError: thermalexpansion.item.tool.ItemWrench.setMaxStackSize(I)Lnet/minecraft/item/Item;
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:162)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:515)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:239)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoSuchMethodError: thermalexpansion.item.tool.ItemWrench.setMaxStackSize(I)Lnet/minecraft/item/Item;
	at thermalexpansion.item.tool.ItemWrench.<init>(ItemWrench.java:31)
	at thermalexpansion.item.TEItems.preInit(TEItems.java:30)
	at thermalexpansion.ThermalExpansion.preInit(ThermalExpansion.java:122)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:513)
	... 10 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 126253480 bytes (120 MB) / 531259392 bytes (506 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.85.1236 Minecraft Forge 10.13.2.1236 89 mods loaded, 89 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	FML{7.10.85.1236} [Forge Mod Loader] (forge-1.7.10-10.13.2.1236.jar) Unloaded->Constructed->Pre-initialized
	Forge{10.13.2.1236} [Minecraft Forge] (forge-1.7.10-10.13.2.1236.jar) Unloaded->Constructed->Pre-initialized
	appliedenergistics2-core{rv2-beta-8} [AppliedEnergistics2 Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	CodeChickenCore{1.0.4.35} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	<CoFH ASM>{000} [CoFH ASM Data Initialization] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	ivtoolkit{1.0} [IvToolkit] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	NotEnoughItems{1.0.4.83} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.4.83-universal.jar) Unloaded->Constructed->Pre-initialized
	modJ_StarMinerCore{0.9.8} [StarMinerCore] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	BuildCraft|Core{6.0.18} [BuildCraft] (buildcraft-6.0.18.jar) Unloaded->Constructed->Pre-initialized
	BuildCraft|Energy{6.0.18} [BC Energy] (buildcraft-6.0.18.jar) Unloaded->Constructed->Pre-initialized
	IC2{2.2.657-experimental} [IndustrialCraft 2] (Industrial-Craft-2-Mod-Experimental-1.7.10.jar) Unloaded->Constructed->Pre-initialized
	GalacticraftCore{3.0.1} [Galacticraft Core] (GalacticraftCore-BETA-1.7-3.0.1.170.jar) Unloaded->Constructed->Pre-initialized
	SpaceCore{4.1.1} [4Space Core] (4Space-1.7-4.1.1.jar) Unloaded->Constructed->Pre-initialized
	SpaceEuropa{4.1.1} [4Space Europa] (4Space-1.7-4.1.1.jar) Unloaded->Constructed->Pre-initialized
	SpaceHole{4.1.1} [4Space Worm Hole] (4Space-1.7-4.1.1.jar) Unloaded->Constructed->Pre-initialized
	SpaceIo{4.1.1} [4Space Io] (4Space-1.7-4.1.1.jar) Unloaded->Constructed->Pre-initialized
	SpaceMercury{4.1.1} [4Space Mercury] (4Space-1.7-4.1.1.jar) Unloaded->Constructed->Pre-initialized
	SpacePluto{4.1.1} [4Space Pluto] (4Space-1.7-4.1.1.jar) Unloaded->Constructed->Pre-initialized
	SpaceVenus{4.1.1} [4Space Venus] (4Space-1.7-4.1.1.jar) Unloaded->Constructed->Pre-initialized
	lucky{5.1.0} [Lucky Block] ([1-7-10]_Lucky_Block_v5-1-0.jar) Unloaded->Constructed->Pre-initialized
	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) Unloaded->Constructed->Pre-initialized
	adventurebackpack{1.7.10-0.8b} [Adventure Backpack] (adventurebackpack-1.7.10-0.8b.jar) Unloaded->Constructed->Pre-initialized
	appliedenergistics2{rv2-beta-8} [Applied Energistics 2] (appliedenergistics2-rv2-beta-8.jar) Unloaded->Constructed->Pre-initialized
	BiblioCraft{1.7.5} [BiblioCraft] (BiblioCraft[v1.7.5][MC1.7.10].jar) Unloaded->Constructed->Pre-initialized
	CoFHCore{1.7.10R3.0.0B9} [CoFH Core] (CoFHCore-[1.7.10]3.0.0B9-40.jar) Unloaded->Constructed->Pre-initialized
	ThermalFoundation{1.7.10R1.0.0RC1} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.0.0RC1-13.jar) Unloaded->Constructed->Pre-initialized
	ThermalExpansion{1.7.10R4.0.0B3} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.0.0B3-dev-11.jar) Unloaded->Constructed->Errored
	BigReactors{0.4.1A2} [Big Reactors] (BigReactors-0.4.1A2.jar) Unloaded->Constructed->Pre-initialized
	BuildCraft|Builders{6.0.18} [BC Builders] (buildcraft-6.0.18.jar) Unloaded->Constructed->Pre-initialized
	BuildCraft|Factory{6.0.18} [BC Factory] (buildcraft-6.0.18.jar) Unloaded->Constructed->Pre-initialized
	BuildCraft|Transport{6.0.18} [BC Transport] (buildcraft-6.0.18.jar) Unloaded->Constructed->Pre-initialized
	BuildCraft|Silicon{6.0.18} [BC Silicon] (buildcraft-6.0.18.jar) Unloaded->Constructed->Pre-initialized
	CameraStudio{2.1710} [Camera Studio] (CameraStudioV2.1710(mc1.7.10).zip) Unloaded->Constructed->Pre-initialized
	hoelib{1.0} [HOEnvironment] (ChemLab-1.7.10-pr-2.03i4.jar) Unloaded->Constructed->Pre-initialized
	chemlab{2.x} [ChemLab] (ChemLab-1.7.10-pr-2.03i4.jar) Unloaded->Constructed->Pre-initialized
	ChickenChunks{1.3.4.17} [ChickenChunks] (ChickenChunks-1.7.10-1.3.4.17-universal.jar) Unloaded->Constructed->Pre-initialized
	MiscUtils{@VERSION@} [MiscUtils] (MiscUtils-universal-1.7.10-1.0.6.jar) Unloaded->Constructed->Pre-initialized
	Circuit{1.0.1} [DataCircuits] (DataCircuits-universal-1.7.10-1.0.1.jar) Unloaded->Constructed->Pre-initialized
	props{1.10} [Decocraft] (Decocraft-1.10_1.7.2and1.7.10.jar.zip) Unloaded->Constructed->Pre-initialized
	DraconicEvolution{1.0.0e} [Draconic Evolution] (Draconic-Evolution-1.7.10-v1.0.0e.jar) Unloaded->Constructed->Pre-initialized
	Eln{43} [Electrical Age] (ElectricalAge_BETA-1.9_r43.jar) Unloaded->Constructed->Pre-initialized
	EnderIO{1.7.10-2.1.7.254} [Ender IO] (EnderIO-1.7.10-2.1.7.254.jar) Unloaded->Constructed->Pre-initialized
	extracells{2.2.49} [ExtraCells] (ExtraCells-1.7.10-2.2.49b75.jar) Unloaded->Constructed->Pre-initialized
	ForgeMultipart{1.1.0.314} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.0.314-universal.jar) Unloaded->Constructed->Pre-initialized
	ExtraUtilities{1.2.1} [Extra Utilities] (extrautilities-1.2.1.jar) Unloaded->Constructed->Pre-initialized
	eyemod{EyeOS4.1-1.7.10} [EyeMod] (eyemod-EyeOS4.2-1.7.10.jar) Unloaded->Constructed->Pre-initialized
	Steamcraft{0.26.0} [Flaxbeard's Steam Power] (FlaxbeardsSteamPower-1.7.10-0.26.0.jar) Unloaded->Constructed->Pre-initialized
	GalacticraftMars{3.0.1} [Galacticraft Planets] (Galacticraft-Planets-BETA-1.7-3.0.1.170.jar) Unloaded->Constructed->Pre-initialized
	gcphobians{0.1.1} [Galacticraft Phobians] (GalacticraftPhobians-ALPHA-1.7-0.1.1.41.jar) Unloaded->Constructed->Pre-initialized
	IGWMod{1.1.1-17} [In-Game wiki Mod] (IGW-Mod.jar) Unloaded->Constructed->Pre-initialized
	labstuff{2.4} [LabStuff] (labstuff-2.4.jar) Unloaded->Constructed->Pre-initialized
	MCEF{0.4} [Minecraft Chromium Embedded Framework] (MCEF-1.7.10-0.4.jar) Unloaded->Constructed->Pre-initialized
	Mekanism{7.1.1} [Mekanism] (Mekanism-1.7.10-7.1.1.127.jar) Unloaded->Constructed->Pre-initialized
	MekanismTools{7.1.1} [MekanismTools] (MekanismTools-1.7.10-7.1.1.127.jar) Unloaded->Constructed->Pre-initialized
	mm{1.0} [Minecraft Money] (MinecraftMoney-1.7.10-1.0.jar) Unloaded->Constructed->Pre-initialized
	modularsystemsapi{0.0.1} [Modular Systems API] (Modular Systems-1.7.10-1.7.1.jar) Unloaded->Constructed->Pre-initialized
	modularsystems{1.7.1} [Modular Systems] (Modular Systems-1.7.10-1.7.1.jar) Unloaded->Constructed->Pre-initialized
	Monoblocks{1.9.11} [§1M§2o§3n§4o§5b§6l§7o§8c§9k§as] (Monoblocks-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized
	MonoblocksMultipart{1.9.11} [MonoblocksMultipart] (Monoblocks-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized
	moreplayermodels{1.7.10b} [MorePlayerModels] (MorePlayerModels_1.7.10b.jar) Unloaded->Constructed->Pre-initialized
	cfm{3.4.7} [§9MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.4.7(1.7.10).jar) Unloaded->Constructed->Pre-initialized
	NGTLib{1.7.10.3} [NGTLib] (NGTLib1.7.10.3_Forge10.13.0.1180.zip) Unloaded->Constructed->Pre-initialized
	ProjRed|Core{4.4.5.44} [ProjectRed] (ProjectRed-Base-1.7.10-4.4.5.44.jar) Unloaded->Constructed->Pre-initialized
	ProjRed|Transmission{4.4.5.44} [ProjectRed-Transmission] (ProjectRed-Integration-1.7.10-4.4.5.44.jar) Unloaded->Constructed->Pre-initialized
	OpenComputers|Core{1.0.0} [OpenComputers (Core)] (OpenComputers-MC1.7.10-1.3.3.54-universal.jar) Unloaded->Constructed->Pre-initialized
	OpenComputers{1.3.3.54} [OpenComputers] (OpenComputers-MC1.7.10-1.3.3.54-universal.jar) Unloaded->Constructed->Pre-initialized
	PneumaticCraft{1.5.3 - err} [PneumaticCraft] (PneumaticCraft-1.7.10-1.5.3-universal.jar) Unloaded->Constructed->Pre-initialized
	ProjRed|Transportation{4.4.5.44} [ProjectRed-Transportation] (ProjectRed-Mechanical-1.7.10-4.4.5.44.jar) Unloaded->Constructed->Pre-initialized
	ProjRed|Exploration{4.4.5.44} [ProjectRed-Exploration] (ProjectRed-World-1.7.10-4.4.5.44.jar) Unloaded->Constructed->Pre-initialized
	ProjRed|Compatibility{4.4.5.44} [ProjectRed-Compatibility] (ProjectRed-Compat-1.7.10-4.4.5.44.jar) Unloaded->Constructed->Pre-initialized
	ProjRed|Integration{4.4.5.44} [ProjectRed-Integration] (ProjectRed-Integration-1.7.10-4.4.5.44.jar) Unloaded->Constructed->Pre-initialized
	ProjRed|Illumination{4.4.5.44} [ProjectRed-Illumination] (ProjectRed-Lighting-1.7.10-4.4.5.44.jar) Unloaded->Constructed->Pre-initialized
	ProjRed|Expansion{4.4.5.44} [ProjectRed-Expansion] (ProjectRed-Mechanical-1.7.10-4.4.5.44.jar) Unloaded->Constructed->Pre-initialized
	RCSM{1.7.10} [RCSM] (RCSMMod1710.zip.zip) Unloaded->Constructed->Pre-initialized
	rftools{2.21} [RFTools] (rftools-2.21.jar) Unloaded->Constructed->Pre-initialized
	RTM{1.7.10.5} [Real Train Mod] (RTM1.7.10.5_Forge10.13.0.1180.zip) Unloaded->Constructed->Pre-initialized
	securitycraft{v1.6.1} [SecurityCraft] (SecurityCraft v1.6.1 for 1.7.10.jar) Unloaded->Constructed->Pre-initialized
	modJ_StarMiner{0.9.8bf1} [Starminer Mod] (Starminer1710-0.9.8bf1.jar) Unloaded->Constructed->Pre-initialized
	superMassiveTech{0.2.0-alpha} [Super Massive Tech] (SuperMassiveTech-MC1.7.10-0.2.0-alpha-86.jar) Unloaded->Constructed->Pre-initialized
	kitchen{1.2.2} [The Kitchen Mod] (TheKitchenMod-1.7.2-1.2.2.jar) Unloaded->Constructed->Pre-initialized
	tlhpoeCore{1.7} [TLHPoE Core] (tlhpoecore-1.7-1.7.10.jar) Unloaded->Constructed->Pre-initialized
	transportterminal{1.0c} [Transport Terminals] (Transport-Terminals-1.0c.jar) Unloaded->Constructed->Pre-initialized
	UltraTech{1.7.10-0.9.6.1} [UltraTech] (Ultratech-1.7.10-0.9.6.1.jar) Unloaded->Constructed->Pre-initialized
	zeronpowercraft{1.7.10-1.0} [§2Zeron§aPowerCraft] (ZeronPowerCraft_1.7.10-1.0-Stable.jar) Unloaded->Constructed->Pre-initialized
	Ztones{1.7.10} [Ztones] (Ztones-1.7.10-2.2.1.jar) Unloaded->Constructed->Pre-initialized
	McMultipart{1.1.0.314} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.0.314-universal.jar) Unloaded->Constructed->Pre-initialized
	ForgeMicroblock{1.1.0.314} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.0.314-universal.jar) Unloaded->Constructed->Pre-initialized
	AE2 Version: beta rv2-beta-8 for Forge 10.13.2.1230

**Comment by logan3mclean** [comment]
PLZ post this everywere in Github Plz
it will help alot

**Comment by KingLemming** [comment]
http://teamcofh.com/downloads/

Download your mods from there, only from there, and then try again.

**Comment by bochen415** [comment]
@KingLemming you should have a PEBKAC label for this.

**Comment by KingLemming** [comment]
I considered it.

**Comment by logan3mclean** [comment]
thank you, now i can stop using IC2 power for my things

**Comment by logan3mclean** [comment]
i think it was my java or minecraft messing it up

**Comment by logan3mclean** [comment]
i got a new version of java
