### ISSUE TITLE
(request) steel and constantan tools and armors

### ISSUE THREAD

**Issue by Hypsellis** [CoFH/Feedback#81]
I just wanted to suggest the adding of steels tools and armors since all the other metals have their own tools and armors.

**Comment by Hypsellis** [comment]
I suggest too the Constantan tools and armors. ;)

**Comment by KingLemming** [comment]
Ehh. Maybe. Not all the others do actually.

**Comment by laserlemons** [comment]
There should be steel tools at least. It's kind of weird that there are lead pickaxes and armor but not steel.

**Comment by KingLemming** [comment]
Working on it. I just uh...sort of forgot how exactly I made those textures initially. ;)
