### ISSUE TITLE
Cyclic Assembler/ Opaque itemducts

### ISSUE THREAD

**Issue by Jacencaedus** [CoFH/Feedback#810]
I was using the Cyclic Assembler from Thermal Expansion [1.7.10]4.0.3B1-218 to repair a Mattock from Tinker's construct for my farm, I was using Opaque Itemducts from Thermal Dynamics [1.7.10]1.1.0-161 to transport it.  It seems that after completing the crafting and ejecting into the itemducts, the mattock disappears, I have looked all along the ducts to check that it didn't go where it wasn't supposed to, but if it is there I cannot find it. The duct that the assembler is ejecting into has no servo.  I am playing on Agrarian Skies 2, and the mod list can be found here http://www.curse.com/modpacks/minecraft/225550-agrarian-skies-2

**Comment by KingLemming** [comment]
Can't replicate this at all, sorry. At best, this is a tech support thing and it's quite probable that you simply lost track of the item.
