### ISSUE TITLE
[Request] Lock installed by default

### ISSUE THREAD

**Issue by Mohron** [CoFH/Feedback#810]
Would it be possible to have a config that makes all CoFH's securable machines have the lock feature installed automatically when crafted/first placed.

Thank you for your consideration!

**Comment by KingLemming** [comment]
This opens up some corner cases that get annoying and/or ugly to deal with, so I'm afraid not. And I'm probably not even thinking of all of them.

**Comment by Mohron** [comment]
Is the way EnderTanks/Multistorage made something similar possible instead? Basically if global "unsecured" chest or tanks were disabled, you had to use a diamond or emerald on them before they became usable.

**Comment by KingLemming** [comment]
I'm not quite following, sorry. You want to require that machines be claimed for them to be used at all?
