### ISSUE TITLE
Allow ore dict for Fluid Transposer

### ISSUE THREAD

**Issue by jkroepke** [CoFH/Feedback#811]
Related: https://github.com/WanionCane/UniDict/issues/67#issuecomment-355400922

Obsidian Dust is registered as ore dict. 

Can you allow the usage of the ore dict on the Fluid Transposer for example here: https://github.com/CoFH/ThermalExpansion/blob/ec03c7180d73caa15c3b9a78feb6b58b97a02c51/src/main/java/cofh/thermalexpansion/util/managers/machine/TransposerManager.java#L137

**Comment by KingLemming** [comment]
It already allows OreDict for dusts, so frankly I don't know why it isn't working. I'm not sure that your other dust is properly registered.

**Comment by jkroepke** [comment]
Hum. Okay.

Can you explan the line 
https://github.com/CoFH/ThermalExpansion/blob/1.12/src/main/java/cofh/thermalexpansion/util/managers/machine/SmelterManager.java#L116

compared to the line linked above?

Because the Induction Smelter accept the Mekanism Dust, but the Fluid Transposer does only accept the Pulverized Obsidian from TE.

**Comment by KingLemming** [comment]
That's simply how I'm adding the recipe, but that shouldn't actually affect anything.

Here's the important part: https://github.com/CoFH/ThermalExpansion/blob/ec03c7180d73caa15c3b9a78feb6b58b97a02c51/src/main/java/cofh/thermalexpansion/util/managers/machine/TransposerManager.java#L486

**Comment by KingLemming** [comment]
I just tested this by adding a new Obsidian Dust and it works fine. This isn't on the Transposer. Did you actually try, or you just looked at JEI?

**Comment by jkroepke** [comment]
I have test it Fluid Transposer. 200mb Redstone. But the Fluid Transposer does not allow to put the Obsidian in it.

I maybe its related to UniDict.
