### ISSUE TITLE
[CoFH Tweaks 1.0.0-36] Optifine crash / incompatible

### ISSUE THREAD

**Issue by Tomson124** [CoFH/Feedback#812]
Minecraft crashes with Optifine and CoFH Tweaks at startup, if I remove Optifine ist starts up just fine.

Crashlog: http://pastebin.com/LDqmeEnj

EDIT: Is it a client only mod? I'm not seeing any info about server usage or dependence on Curse.

**Comment by skyboy** [comment]
Duplicate of https://github.com/CoFH/Feedback/issues/482
