### ISSUE TITLE
Add config to hide Florbs/Morbs from JEI.

### ISSUE THREAD

**Issue by darkphan** [CoFH/Feedback#813]
I would assume that disabling flobs and morbs would (should) cause them to not show up at all in JEI, yet they do.

**Comment by KingLemming** [comment]
Read the comment. ;) It disables the *recipes* making them uncraftable. It doesn't disable the item completely.

I can add a separate config for that on the client side though.

**Comment by darkphan** [comment]
That would be helpful.

**Comment by KingLemming** [comment]
So the config is separate and has nothing to do with the actual recipes, just a heads up. It has to specifically be set on the client side.
