### ISSUE TITLE
CoFH fake player seems to be "null" instead of "[cofh]"

### ISSUE THREAD

**Issue by Robijnvogel** [CoFH/Feedback#815]
My modded server is running almost all CoFH mods and Forge Essentials. Autonomous Activators could not place or break any blocks or use items. Adding the [cofh] user to the _FakePlayer_ group did not help.
However adding the null user to the _FakePlayer_ group immediately caused the autonomous activators to start placing blocks.
This leads me to believe that the CoFH fake player is called null (or is unnamed) for some reason. And it shouldn't be, right?

**Comment by KingLemming** [comment]
The user is [CoFH], so I'm not sure what should work. Null working is possibly a bug in ForgeEssentials, however. Or it may be intentional.

The FakePlayer is properly named on our end, however.
