### ISSUE TITLE
Crash on clicking the search option in creative crashes mc

### ISSUE THREAD

**Issue by bushbaby1234** [CoFH/Feedback#816]
http://pastebin.com/yMjrjDkZ

as the title says if i click on the search button in creative it crashes with the above.

im using v.0.0.1 of my modpack, BatSink, on curse.
http://www.curse.com/modpacks/Minecraft/230499-batsink

the modlist is pretty much yes.... 
but more accurate list is in the changelog here http://minecraft.curseforge.com/modpacks/230499-batsink/files/2255200

**Comment by KingLemming** [comment]
Welp. You didn't search old issues.

This isn't on us. Another mod is screwing it up. You can disable the TD Creative Tab, however, and it will avoid the conflict that way.

**Comment by bushbaby1234** [comment]
whoops i forgot the issues tab defaults to open issues. sorry. and thanks for the fix anyway!
