### ISSUE TITLE
Thermal Expansion Broke

### ISSUE THREAD

**Issue by KeetaKitty** [CoFH/Feedback#817]
I added this mod, and i hope all the mods it needs to run. the game loaded just fine, but now as I am trying to access the menu for the aqueous accumulator, or any item except florbs i cant right click on and interact with the machines and satchels. What is causing this bug?

**Comment by KingLemming** [comment]
No idea. We need logs to help you. In the meantime, please try redownloading the latest versions of all mods and then set up an instance with *only* those mods.

If you're still getting the issue, please go here: discord.gg/uRKrnbH 

This isn't really a code issue, it's tech support, but we're happy to help.
