### ISSUE TITLE
[Suggestion] Compactor + Blaze/Blitz/Basalz/Blizz

### ISSUE THREAD

**Issue by KirbyQK** [CoFH/Feedback#818]
Pretty self explanatory, I was compacting 5 Blaze powder into a rod via IC2 today and thought to myself that it would be really cool if I could use TE to do that, as I've never really gotten into IC2 at all (no where near as pretty, fun or well engineered ;) ).

IMO 4 powder into a rod might be too powerful with the secondary outputs from pulverizing, meaning 5 could also be well balanced for TE. If you've ever thought about using the other rods for any recipes, I think it would be super handy to be able to make them this way.

---

Completely separate suggestion, but following on from that idea, I'd also LOVE it if there could be blocks of the rods, so 9 rods into a block like a Blaze lantern. I think it would be great for decoration, maybe even have them emit light. Alternatively, I'd also suggest that you could even bring back the Glowstone Illuminator, with various TE fluids enabling different colours and the rods enabling different coloured frames! If you wanted to add some steps for balance or to increase the cost of entry, I'd suggest transposing Energised Glowstone into various solids (Enderium blend, Redstone, Blizz powder etc.) to generate glowing variants of items, to then put into rod frames to create the lantern. That's a whole completely different suggestion in-of-itself though, lmk if I should put it through as a separate thread if that's easier.

---

Thanks for reading, and for all of your hard work, I couldn't bring myself to get into 1.12 until TE was all updated!

**Comment by KingLemming** [comment]
This is reasonable and I don't see a duplication loop offhand. The compactor may be getting a bit of a rewrite here shortly, but I can go ahead and add it.

Not sure about the lanterns since that's sort of a Quark thing, but will look into it. The Illuminators will probably come back, it's just a matter of re-adding them and cleaning them up a bit.

**Comment by KirbyQK** [comment]
Awesome! There really aren't enough attractive lighting options IMO; all the chisel glowstones are (IMO) kinda ugly, and I don't want to just torch everything up. The Blaze Lantern is cool, but isn't very ornate/techy. I loved the illuminator, so I'll look forward to seeing it again sometime in the future:)
