### ISSUE TITLE
Placing Energy Cell Crashes Game

### ISSUE THREAD

**Issue by JDuskey** [CoFH/Feedback#818]
Crash Log: http://pastebin.com/6y6cFC2L

It happens every time I place any type of Energy Cell

**Comment by JDuskey** [comment]
Update: It only occurs on a server, not on single player. Server has all same mods

**Comment by KingLemming** [comment]
This is entirely something with your setup. For whatever reason, corrupt items are being created on the server, or something is messing with our placement code.

We can't reproduce this nor has anyone else reported it. If it were in our code, it would happen 100% every time. Sorry, but there's nothing we can do here.

**Comment by Kvasyr** [comment]
i have the same issue 
this is the log in case you guys want to look at it:
http://pastebin.com/QaJWmTwx
