### ISSUE TITLE
Cofh Killall Command

### ISSUE THREAD

**Issue by TheLoyalOne** [CoFH/Feedback#819]
Hello there.

I have a bit of a request. I am running multiple modpacks (FTB Direwolf20, Infinity). And I would like to give /cofh killall to my server admins (the ones that are not OP'd). The reason being is because entities are a problem sometimes and they cannot kill them without being OP'd. I would give them the worldedit /butcher command, but that kills golems. So, I am wondering if perhaps you can add a permission for the command /cofh killall so I (and others) can give their server mods/admins access to /cofh kilall without being OP'd.

Thanks,
~ Loyal

**Comment by skyboy** [comment]
You can use Forge Essentials to do this, if the bukkit plugin cannot manage it I would suggest opening an issue with them.
