### ISSUE TITLE
[Suggestion] Allow for IF Essence to become Essence of Knowledge

### ISSUE THREAD

**Issue by N1ch0l2s** [CoFH/Feedback#819]
From what I can tell, Essence is essentially XP for Industrial Foregoing. However, there's currently no way of converting it into experience orbs. (unless I haven't looked hard enough) This gave me the idea of why not let IF Essence be allowed into the Tome of Knowledge? It'd be really convenient and would make enchanting with liquids much easier.

**Comment by KingLemming** [comment]
Yes, integrating IF would in general make everything much *much* easier. That's what IF tends to do.

I'm not strictly averse to it, but let me make sure that the amount of essence generated is reasonable and that the mB / xp ratio is correct - 20 mB / xp.

**Comment by KingLemming** [comment]
Seems that they are using 20 mB / xp, so sure.

The tome can now convert from Essence to stored xp and the Fluid Transposer recipe can use Essence to make XP bottles.

**Comment by N1ch0l2s** [comment]
Thank you!
