### ISSUE TITLE
Thermal Expansion Dupe Bug with Twilight Forest Uncrafting Table.

### ISSUE THREAD

**Issue by Eavonrepus** [CoFH/Feedback#82]
I know it's a dupe bug, but it needs to be known. The two mods have a type of 'conflicting recipe' allowing any TE machine that is a regular/upgraded machine to be able to dupe the signalum lock/nuggets when put in an Twilight Forest Uncrafting table. We have the uncrafting table on the server I staff on(the DW20 1.0.3 (1.7.1)) disabled. - But the recipe is still the same on the most recent Thermal Expansion which is why I'm reporting the issue. The reason for this, I'm sure you know is because the way the uncrafting table works, is it takes the first recipe from NEI, and uses that certain recipe. I'm suggesting that you guys rearrange your recipes, which wouldn't be a hard task, so that this recipe conflict can be resolved. 

http://i.imgur.com/uycwZdr.png <-- This is a picture of the recipe, that should be at the end, I think. Plus; I also hate scrolling through 2 pages just to see how to craft the machine, quite annoying.

Thanks!

**Comment by KingLemming** [comment]
Yeah so basically you're filing 2 issues and neither one of them are really ours:

1) NEI is derpy.
2) The crafting table is also super derpy and is not a true uncrafting table.

We'll look into it, but realize that we don't necessarily control how NEI sorts things, and if the crafting table were *properly* coded, it'd get the recipe right.

**Comment by Eavonrepus** [comment]
Alright, I'm sorry to have blamed you. It just seemed like a Thermal Expansion issue, due how the recipes were placed. I didn't quite think that through well. Either way, thank you for taking a look at the issue at-least. most people would ignore it. :) Good luck! I love your CofH's mods by the way. :)

**Comment by KingLemming** [comment]
The underlying issue is that neither NEI nor the Uncrafting Table really handle NBT-based recipes correctly. It's a sort of fundamental failing of MC; NBT isn't dealt with very well. As far as NEI goes, we can hack around it to introduce a custom category (which we've done in an upcoming build). However, the table would still see the recipes in whatever order it chooses to.

If I find time, I might code up an Uncrafting table to see if it's even *possible* to handle NBT-recipes. If so, I'll see about passing it on to Benimatic.

**Comment by Eavonrepus** [comment]
Well, I'll study up on this stuff a little bit, and maybe I will be able to offer a more helpful suggestion next time I have one. If I had of known, I would of went directly to Benimatic instead of coming straight here.  I appreciate the information. :+1:
