### ISSUE TITLE
Request:add augment for energy cell

### ISSUE THREAD

**Issue by MadRatSRP** [CoFH/Feedback#821]
Magic Influence- machine, which powered by energy cell, can power other machines in 1 block radius
For example 1
                     1
                     x, where x- energy cell, 1 - machine. With that upgrade u dont need to put fluxducts for the machines, which placed on top or bottom of the machine connected to the energy cell.

**Comment by KingLemming** [comment]
Sorry, no plans to add augments to energy cells. Also, this would potentially add a *lot* of lag.
