### ISSUE TITLE
[1.12.2][TE 5.3.8.38] Phytogenic Insulator - Melon Seeds produce Beetroot & Beetroot Seeds.

### ISSUE THREAD

**Issue by lrwerewolf** [CoFH/Feedback#823]
While playing Modern Skyblock 2, I had need to produce some melon slices quickly.  I attempted throwing some melon seeds in my pythogenic insolator and got back beetroots and beetroot seeds.  I searched the crafttweaker scripts and found no mods to that recipe, and the modpack creator denied making any changes to those recipes.

**Comment by KingLemming** [comment]
This is caused by some other mod (or the pack) doing incredibly dumb things with the OreDictionary. I unfortunately cannot fix their lunacy.

Sorry for the inconvenience, but it's not on my end.
