### ISSUE TITLE
Extra utilities speed upgrade in a TE servo crashes the server

### ISSUE THREAD

**Issue by scalda** [CoFH/Feedback#823]
Hi i am a admin for iskall85's fan server, 

One of our players put a extra utilities speed up grade in a TE servo and it crashes the server when every a player is near by it. I had to mcedit the block to delete it for the area to be playable again.

please find the attached crash log.

regards

Scalda

http://pastebin.com/mVeNxRpD

**Comment by KingLemming** [comment]
There's literally nothing in that stacktrace that points to TD. Please post this on the ExU tracker.
