### ISSUE TITLE
Portable tank duplication when upgrading via crafting grid

### ISSUE THREAD

**Issue by ogurets** [CoFH/Feedback#824]
Well, it's all in the title. Steps to reproduce:
1. Craft Portable Tank [Basic]
2. Craft Hardened Upgrade.
3. Open the inventory and put the tank and the upgrade into the inventory crafting grid (2x2).

Expected: Hardened Portable Tank taken from the result slot, source items disappear.
Observed: Hardened Tank taken from the result slot, upgrade item disappears, Basic Tank remains in the crafting grid.

Tested on ThermalExpansion-1.12.2-5.3.7.31-universal, SMP.

**Comment by KingLemming** [comment]
Yeah so you're out of date. This has been fixed.

Please be sure you're on the latest before coming to report issues.
