### ISSUE TITLE
allow paper recipe to use tanks of water instead of just buckets

### ISSUE THREAD

**Issue by SHIuSH** [CoFH/Feedback#825]
I mean it works with creosote, why shouldn't water work too?

**Comment by KingLemming** [comment]
You didn't actually try doing it, did you? This has been a thing for a long time.

**Comment by SHIuSH** [comment]
![oopps, I guess I had old version of TE](https://user-images.githubusercontent.com/10953814/34679906-ff573ee0-f4c9-11e7-88d1-44c9e3ea4b44.png)

**Comment by KingLemming** [comment]
Literally just double checked in dev. It works fine.
