### ISSUE TITLE
Translocation plates spawn endermites

### ISSUE THREAD

**Issue by iMekX** [CoFH/Feedback#825]
Using a custom pack with Forge 1472 and TE version 218.

I've got a chain of three '+' translocation plates set up to create an 'express' elevator to the top of a 6 floor base we've created.  Unfortunately (and I've been searching config and googling to see if this was intended),  I just checked and since endermites are a 1.8 thing, it probably is a code response with Et Futurum.

**Comment by skyboy** [comment]
We have no way to prevent other mods from generating side effects as a result of a teleport via Translocation plates. It's up to other mods to ensure their code works correctly.

**Comment by iMekX** [comment]
The problem, and why I noted it here is I think ganymede replicated the 1.8
code for that action.  If that's the case, this bug will be showing up with
the translocation plates when/if TE is brought to 1.8.  That may well be
out of scope 'until then', but was trying to note this is an interaction to
watch for.

**Comment by skyboy** [comment]
Checked 1.8 and confirmed this is a bug in the mod you're using.
