### ISSUE TITLE
MC 1.12.2 w/ latest Forge build - Redstone Flux

### ISSUE THREAD

**Issue by koalateatimes** [CoFH/Feedback#826]
Keeping in line with the prerequisites on issue reporting, I will do my best to explain this issue with Redstone Flux.

Having quite the time getting MC to run with all the necessary CoFH mods installed to run ThermalExpansion and such. I have gone through all the recommended troubleshooting as explained on the TeamCoFH homepage. However, I am receiving the same exact error every single time. I am running the latest and greatest MC version and the latest Forge version (fresh install moments ago). I figured updating Forge would fix the error. Please refer to uploaded picture file and crash log. Again, same error I was getting before updating the Forge version. If the Forge version is the latest, how is it unsupported? Will this require a reinstalled on MC as a whole? Are there any settings I can tweak in the Launcher Settings section in the MC launcher?

![mcissue](https://user-images.githubusercontent.com/35242268/34699377-ef9ee972-f4aa-11e7-9b2d-31633e73760e.PNG)

![mcmodslist](https://user-images.githubusercontent.com/35242268/34699569-10901218-f4ac-11e7-868c-5e1a2e3579f4.PNG)
Link to the error log: https://pastebin.com/n2CzKjaY

Refer to the mod list. Again, I have tried just using the CoFH mods by themselves and I was still getting the same error. What am I missing?

**Comment by KingLemming** [comment]
The error log very clearly shows the error - Buildcraft is repackaging API classes that it should not be. Redstone Flux forces a crash because this is wrong. Either perform jar surgery on Buildcraft or remove it altogether.

**Comment by covers1624** [comment]
You actually have Buildcraft for 1.7 installed for 1.12
