### ISSUE TITLE
Redstone Arsenal: Tweak?

### ISSUE THREAD

**Issue by Lodugh** [CoFH/Feedback#826]
Hi Team CoFH,

I really like the mod but I think it could need some tweaking and improving. The bow for example is in my opinion a bit overpowered. It even onehits most of the mobs when it is not activated. If it's activated and enchanted it deals around 50 damage, which is more than 2 times of what a normal bow can. Furthermore it does not really cost anything. Just some worthless obsidian, gold, silver and redstone and the power it drains is almost nothing too.  Maybe it would be enough just to make the recipe more expensive(let it cost an Infused Obsidian Rod) and let it drain some more power but let it carry more too.
Another thing I find a bit annoying is the thunder. I mean you just activate a tool, its not magical right?
Thats my opinions though I'm really interested what you say to these things.

Greetings, 
Lodugh

**Comment by KingLemming** [comment]
Thanks for the feedback!

Damage values are something we may offer some configuration for in the future, but for the moment the bow is actually incredibly underpowered compared to the rest of the modded environment, so I don't see a need to change where it sits.

In terms of vanilla, the normal bow will one-shot most things. And 2x the damage for a considerable resource investment, in comparison, is acceptable given that this damage is wasted on the majority of mobs.

I'll consider changing the rod, that's an acceptable request.

Increasing the power drain? Possibly. We'll see.

As far as the sound? Sure, it's just a tool, but the thunder is fun. :) It's meant to convey a feeling of power, and hopefully it does so.

I can't promise that I'll implement or change any of this necessarily, but I'll look into it.

**Comment by Lodugh** [comment]
And thank you for the great answer! :D

Yeah, maybe you are right with the damage values..

Would be a great change with the Infuse Obsidian Rod I think because it would feel much more rewarding if you actually have to put some worthy materials into the crafting of the bow.

Regarding the sound I like on it the least that it is just like the normal thunder and because of that I cant really identify it with the tools. An a little bit more electricity inspired sound might be better for it.
