### ISSUE TITLE
[BUG/MISFEATURE] TE4 Energy cells, strongboxes, and portable tanks unplaceable if recipe disabled

### ISSUE THREAD

**Issue by keenerb** [CoFH/Feedback#827]
Yes, this is a resubmitted bug report that was closed as "unreproduceable" but I've also received independent confirmation of the issue and can provide a functional config that duplicates the issue.

http://modpacks.roleplayga.org/modpacks/cofh.zip

Those configs are my attempt to disable crafting of virtually all TE items for a specialized survival server.

With that set of configs, in single player, only the creative energy cell is placeable in the world, although existing energy cells seem to work fine. This also seems to affect portable tanks and strongboxes.

Placing any non-creative energy cell silenty fails, although it will remove tall grass and take the item from me (if in survival mode) as if it WANTS to place the block.

Other machines/blocks with disabled recipes are placeable with no issues, such as redstone furnace and pulverizer.

Someone in IRC took a look and had the following observation:

```
The class populates a boolean array by seeing if creative is enabled then checking the others if each recipes are enabled.  On block placement, it checks if that array has that specific one enabled and if not, it clears the block in-world and returns.
```

I'm not at all certain why this sort of placement behavior would be relegated to just the strongboxes/etc.

**Comment by KingLemming** [comment]
K. So here's how this works. We watch the old thread. We figure it out and handle it.

Here's how it doesn't work: you open the issue again.

Basically, we're on it, and there may be something already changed in dev that means we don't see it. However, you can direct commentary to the existing report. Do not open a duplicate.

**Comment by keenerb** [comment]
I had no idea whether you monitor old closed issues or not, especially when there's no update or status change on said issue.  Plenty of devs never follow up once an issue is "closed."
