### ISSUE TITLE
Request:An addon or mod about thermal expansion mobs/drops

### ISSUE THREAD

**Issue by MadRatSRP** [CoFH/Feedback#828]
Thermal Expansion and its addons are awesome, especially its KIT and Augment upgrade system. But what about new mobs/drops for other mods. I wrote to the Lycanites creator and he said, that he dont want to add addon for drops. What about u? Would you like to add some kind of addon for Thermal Expansion mobs drops?

**Comment by KingLemming** [comment]
I also have no interest in doing this, sorry.
