### ISSUE TITLE
Thermal Dynamics Facade client crash when close to Ender IO Travel Anchor

### ISSUE THREAD

**Issue by GuntherDW** [CoFH/Feedback#828]
( Crossreference from https://github.com/SleepyTrousers/EnderIO/issues/2794 )

I wasn't really sure where exactly to post this one, so I'm posting it on both EIO and CoFH.

We updated EnderIO 2.2 to 2.3 beta, and were experiencing client crashes in some people's bases on our server.
When trying to locate the issue that was causing it,  it seemed to be caused by a mod interaction of some kind between EIO and TD.

TD wasn't updated, let alone any CoFH mod in this pack update, just Ender IO (and a couple other mods).

When a facade gets placed near a EIO travel anchor or already is near one the client crashes and doesn't mention any EIO exception in the log. Because of this the EIO devs told me to also put it on this issue tracker.
It seems to be the block next to the block touching the translocator though, not the block touching it.
Other blocks don't seem to crash it as far as we can tell, just the EIO translocator.

Crashlog : http://pastebin.com/nCRLsuWH
Screenshot of setup whilst frozen (blocks do not matter, a vanilla block facade also crashes the client) : http://puu.sh/k4k0d/2e8d2f7915.jpg

Ender IO : 1.7.10-2.3.0.413_beta
Ender Core : 1.7.10-0.1.0.23_beta
Forge : 10.13.4.1490-1.7.10
Thermal Dynamics : [1.7.10]1.1.0-161

The real question of course is what is causing this, is it EIO or TD? We were leaning towards EIO because that was the mod that got updated, TD didn't get touched in any way.

**Comment by KingLemming** [comment]
I'm pretty confident this isn't TD. I'll leave it up for now, but the trace suggests that it's Chisel.

**Comment by GuntherDW** [comment]
We thought that at first too, as well as tterag. However the block used for the facade or the blocks arround it doesn't matter. I tested it out with a grass patch, cryo fluxducts and vanilla glass facades and it still crashed the same way.
http://pastebin.com/w1fGGMaC

Testing setup : http://wrongplace.be/files/2015-09-08_22.10.14.png (place it, and almost instantly after that the client crashed)

**Comment by skyboy** [comment]
Reported resolved: https://github.com/CoFH/Feedback/issues/853#issuecomment-147974597
