### ISSUE TITLE
resonant energy cells showing wrong rf level indicator when enchanted 1.12.2

### ISSUE THREAD

**Issue by wakkytabbaky** [CoFH/Feedback#829]
the resonant energy cells when enchanted with holding 4 will show the red bars full when only at 50million rf and it will still have 100 million left to fill up. unsure if your aware or if its already been posted.

ThermalExpansion-1.12.2-5.3.9.6-universal

**Comment by KingLemming** [comment]
This has already been fixed. Please be sure you have the latest versions of mods before you report issues. Thanks.

**Comment by bochen415** [comment]
I can confirm this happening in `ThermalExpansion-1.12.2-5.3.10.15`.
Any block update will make the glitch go away but after returning to the area or restarting it happens again.
![2018-01-28_17 07 10](https://user-images.githubusercontent.com/8314356/35484259-f387c060-044d-11e8-8b7c-e12c3a4347fd.png)

Before restarting:
![2018-01-28_17 09 26](https://user-images.githubusercontent.com/8314356/35484278-244683c6-044e-11e8-93ac-579c6a9818de.png)

Afer restarting:
![2018-01-28_17 10 06](https://user-images.githubusercontent.com/8314356/35484283-35bffa42-044e-11e8-806a-593b333dceca.png)

**Comment by danikk14g** [comment]
i can also confirm it on ThermalExpansion-1.12.2-5.3.10.15-universal.jar
i noticed this today while testing some changes on the capacity of Energy Cells, the visual display is 1/3 the actual stored energy on the cell.
