### ISSUE TITLE
Dupe Bug: Solar Flux Solar Panel

### ISSUE THREAD

**Issue by eslachance** [CoFH/Feedback#83]
#### Issue description:
Duplicating the Solar Flux Reborn: Solar Panel by shift+right-clicking with the Crescent Hammer

#### What happens:
Shift+right-clicking on a Solar Panel makes 2 of the panels drop. Placing them again and picking them up duplicates again, eternally

#### What you expected to happen:
Shift+right-clicking on a solar panels makes one drop, not 2

#### Steps to reproduce:
1. Place a Solar Flux Solar Panel on the ground
2. Shift+Right-Click with the Crescent Hammer

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2254
- Thermal Foundation: 2.0.1.68
- Solar Flux Reborn: 2.6r

Does this issue occur on a server? Yes. 
Modpack Used: FTB Beyond (1.0.1)

**Comment by KingLemming** [comment]
This is absolutely on Solar Flux Reborn to fix.

**Comment by 016Nojr** [comment]
@eslachance This was fixed in Solar Flux Reborn: 1.10.2-2.13r

**Comment by eslachance** [comment]
Sorry @KingLemming I wasn't sure what mod caused it. I had to start somewhere ;)
