### ISSUE TITLE
CoFHCore-[1.7.10]3.0.0B9-110+ causes IC2 localization string problems

### ISSUE THREAD

**Issue by Maxital** [CoFH/Feedback#83]
Unsure if you guys seen the report @ https://github.com/skyboy/MineFactoryReloaded/issues/370
But this seems more related to CoFHCore but same issue.

I did some tests with as little mods as possible and found out IC2 starts showing their localization string name instead of the actual localized string with CoFHCore-[1.7.10]3.0.0B9-110
tested with IC2 build 648->671 and it only happens with CoFHCore-[1.7.10]3.0.0B9-110+

Works fine with CoFHCore-[1.7.10]3.0.0B9-109

The commit for the 3.0.0B9-110 build maybe caused by https://github.com/CoFH/CoFHCore/commit/72fa8fbd9a9487523959b7b02df98fb4d280629e
or something around that same timeline.

Mods i tested with:
forge-1.7.10-10.13.2.1291
1.7.10\CodeChickenLib-1.7.10-1.1.1.110-universal.jar
1.7.10\ForgeMultipart-1.7.10-1.1.1.320-universal.jar
ic2\ejml-0.23.jar
CodeChickenCore-1.7.10-1.0.4.35-universal.jar
CoFHCore-[1.7.10]3.0.0B9-109.jar
CoFHLib-[1.7.10]1.0.0B9-85.jar
industrialcraft-2-2.2.671-experimental.jar
MineFactoryReloaded-[1.7.10]2.8.0RC6-47.jar
NotEnoughItems-1.7.10-1.0.4.83-universal.jar
RedstoneArsenal-[1.7.10]1.1.0RC1-33.jar
ThermalExpansion-[1.7.10]4.0.0B8-23.jar
ThermalFoundation-[1.7.10]1.0.0RC1-35.jar

Java: jdk-8u31

/Max

**Comment by KingLemming** [comment]
We've discussed it with IC2 and FML. Fundamentally, there's a larger issue that needs to be addressed. Basically IC2 does some hackery, CoFHCore does some hackery, and it all needs to go away.

**Comment by Maxital** [comment]
I see, well atlest all are aware of it :)

**Comment by KingLemming** [comment]
Handled on IC2's end.
