### ISSUE TITLE
Chisel blocks, EIO painted blocks and TD covers

### ISSUE THREAD

**Issue by XFactHD** [CoFH/Feedback#830]
If you place some TD covers next to the chisel blocks the covers were made out of, the covers have connected textures between each other but not between themselves and the chisel blocks. If you place a painted block from EIO (For me it happened with a Travel Anchor) the cover tries to make a connected texture with the painted EIO block but the EIO block doesn't react on that.

**Comment by Entoarox** [comment]
That is due to use of different CTM designs and is not really solvable untill everyone manages to agree to a single design of declaring CTM for such things.

**Comment by XFactHD** [comment]
That's true but why are the covers connecting to EIO blocks that are using the exact same system for the painted blocks as chisel is using for their blocks.

**Comment by Entoarox** [comment]
EIO facades may implement the interface that TD covers use for connected textures, but chisel uses its own interface to determine CTM, hence that the connection doesnt form properly, chisel facades mimic the properties of the painted block, but that painted block doesnt recognise TD covers.

**Comment by XFactHD** [comment]
If EIO facades and TD covers are implementing the same interface, why are EIO facades connecting with chisel blocks seamlessly then and TD covers not? And why is TD trying to do a connected texture to the EIO facade, but the EIO facade is not reacting to it? Also, if TD covers are not using the same CTM design that Chisel uses, how is it then able to determin that the block it is made out of has a connected texture (the TD covers have connected textures if you build everything out of the covers and not just a single block)?
(By the way EIO has special code for Chisel)

**Comment by Entoarox** [comment]
The chisel blocks & facade blocks connect because as far as chisel can detect, the facade block IS a chisel block, that is how enderIO handles painted facades, but the TD cover isnt checking for the block, its checking if a certain interface is being implemented and responding to that.

But since chisel blocks dont implement or use this interface, the chisel block being mimicked by the facade doesnt recogise the TD facade as valid, just as TD facades dont see chisel blocks as valid.

**Comment by XFactHD** [comment]
That makes sense. This would mean that either Chisel would have to implement this specific interface or TD has to get compatibility code for Chisel (which I doubt will happen).

**Comment by Entoarox** [comment]
What is needed is a universal system to say "side X of block has texture Y, so if block Z has texture Y on that side also, then make it connected", since right now there are 3 or 4 different methods of doing pretty much exactly that in use.

**Comment by XFactHD** [comment]
I think this would need to go into forge itself because otherwise there would still be some people making their own implementation.

**Comment by KingLemming** [comment]
k well glad this got sorted then.
