### ISSUE TITLE
Crash When Wrenching Items

### ISSUE THREAD

**Issue by RoloEdits** [CoFH/Feedback#831]
http://pastebin.com/qwW0YNq7

I'm getting this crash when using the crescent hammer wrenching things.I first go this crash when trying to dissemble and ender tank from ender tech and now i'm getting it when wrenching a logistics chassis from logistics pipes.

**Comment by KingLemming** [comment]
Your world is broken. Your block IDs have gone beyond 4096. That shouldn't be possible in any way.

**Comment by RoloEdits** [comment]
Im using a mod called not enough id's that makes the id limit larger. Would this also effect NBT data like with tanks that would cause a crash? like with #791?

**Comment by KingLemming** [comment]
It's entirely possible. The ID limit is 4096 for a reason. It's deeply tied into basic game logic and world saves.

**Comment by RoloEdits** [comment]
I put it in my mod pack because I have to many mods that added to many blocks, but I wanted to keep them but now it sounds like I should remove the mod because it breaking things. What would you recommend I should do?

**Comment by KingLemming** [comment]
If you're going over the 4096 limit, you probably have a couple of mods that are just outright wasteful with Block IDs. Remove those, and don't use any hackery to try and increase the limit. Best advice I've got for you.

**Comment by RoloEdits** [comment]
Thanks a lot, I appreciate your advice and I will follow it. I think I have around 325 mods so I think it's just the case of to many mods.
