### ISSUE TITLE
[1.12.2] Crash with new versions

### ISSUE THREAD

**Issue by drinfernoo** [CoFH/Feedback#831]
I'm receiving what I believe to be a TE-related crash, relating to the .equals() and .hashCode() methods.

[Crash Report Here](https://hastebin.com/zoxifayobi)

Let me know what I can do to help.

**Comment by KingLemming** [comment]
Oh neat, we haven't seen this one in a while.

You have a mod which is registering OreDictionary items improperly. It's 100% their fault. In this case, it seems involve "dustObsidian," so it may be some sort of OreDict unifier or another mod adding Obsidian Dust.

**Comment by drinfernoo** [comment]
Thanks for the input. Did I miss that in the crash report somehow? How can you tell which item is having the problem?

Either way, it's probably UniDict, if you say it's possibly an unification mod.

**Comment by KingLemming** [comment]
Nah, you didn't really miss that. I just know what to look for in these since I've seen a few.

It's been a while since this has been submitted though. And mods/packs were doing so well. :/
