### ISSUE TITLE
Crescent Wrench, Not Working?

### ISSUE THREAD

**Issue by Thornpaw** [CoFH/Feedback#833]
When I right click on a fluiduct or itemduct with the Crescent wrench, all is does is make the connector vanish.  Shift+right Click knocks the duct loose.  I am playing on my own Realm of Mianite server with ThermalDynamics [1.7.10]1.1.0.161, TheremalExpansion [1.7.10] 4.0.3B1-218 and ThermalFoundation [1.7.10] 1.2.0-102 installed.

Mods using: http://www.technicpack.net/modpack/realm-of-mianite.579505/mods although I have updated the mods as they have come out.

**Comment by KingLemming** [comment]
So basically...you didn't learn the mod. Things have changed.

The wrench works and the ducts work. Please learn how the mod works.
