### ISSUE TITLE
[1.12.2] Redstone Furnace with Pyrolitic Conversion incorrect put out fluid

### ISSUE THREAD

**Issue by KorDum** [CoFH/Feedback#834]
Redstone Furnace with Augment Pyrolitic Conversion gives a liquid to the tank (or pipes) only once when recipe is done.

For example 500 mb put into Portable Tank and 50 mb put into IE pipe every time coal is ready.
![image](https://user-images.githubusercontent.com/1331559/34772210-5679fe3e-f618-11e7-9c7d-c0b363d6c00f.png)

![image](https://user-images.githubusercontent.com/1331559/34772219-5ea16a16-f618-11e7-85f2-2a6a199bda6c.png)

**Comment by KingLemming** [comment]
Yes, this was an intentional change I made, as attempting to transfer fluid every tick is less than optimal. The larger issue here is just that the pipe accepts so little fluid.

**Comment by KorDum** [comment]
Thanks for answer!
Maybe once an second, not every tick?

**Comment by KorDum** [comment]
2500 mb of creosote from one coal block. Basic Portable Tank takes 500 mb (if I'm not mistaken). 5 tanks are required for pumping out liquid at one time... This is uncomfortable =)

**Comment by KingLemming** [comment]
Tanks accept any amount at once. I can't replicate the 500 that you're apparently seeing.

**Comment by KorDum** [comment]
Yes, my mistake. Bu, how can I put out liquid from machine if the machine cann't drain liquid without own work?

> Maybe once a second, not every tick? Or random tick.

?

**Comment by KingLemming** [comment]
A servo will extract just fine. I'm also pondering changes in dev for output. We'll see.

**Comment by KingLemming** [comment]
I've altered the behavior somewhat to compensate for...pipes like that.
