### ISSUE TITLE
Server on hopper gets stuck

### ISSUE THREAD

**Issue by psusi** [CoFH/Feedback#834]
I have a hopper underneath a harvester to collect the wheat and seeds.  Attached to the hopper I have an itemduct with a servo to pull them out and feed the seeds to the planter and the wheat to a breeder.  When the breeder is full of wheat, the servo can no longer remove the wheat from the hopper, but that also stops it from removing the seeds.

In other words, any item in the hopper that the servo can not remove prevents it from removing the other items that it *can*.

**Comment by KingLemming** [comment]
Correct. That's how they work.

**Comment by psusi** [comment]
Umm... no?  When connected to a chest or AE2 interface or a machine, they will pull any and all items they can, and leave whatever they can't.

**Comment by KingLemming** [comment]
How Hoppers work. They're coded by Mojang and are terrible.

**Comment by psusi** [comment]
Ohh... I would think that wouldn't matter when using the servo to *pull* the items instead of relying on the hopper to *push* them..

**Comment by KingLemming** [comment]
After doing a bit of testing, I can't even replicate this AT ALL. The servo behaves correctly.
