### ISSUE TITLE
[Suggestion] Tome of Knowledge should convert ActuallyAdditions Solidified XP into TF XP

### ISSUE THREAD

**Issue by SadChimera** [CoFH/Feedback#837]
As the title states, you current have to pick up the solidified essence and right click, or smelt it down. When it would be much more user-friendly to have it convert into experience automatically. Or at the very least, give a config option for it.

**Comment by KingLemming** [comment]
Fluid support is a lot easier than item support, just by the nature of it. Offhand I'm not particularly inclined to do this, but I'll think on it.

**Comment by SadChimera** [comment]
Since you mentioned fluid support, TechReborn oil pits are prioritized in every pack that I've played thus far(so Thermal pits aren't generated), and the oil is incompatible with TF Fluid Transposers and fractioning stills unless this was fixed in the latest update.   
  
Side-note: TechReborn actually screws things constantly. Tinkers smeltery pours thermal metal blocks. TechReborn's bronze block is the only block that doesn't have an oredict entry. Ironically, you MUST convert TF to TR Bronze blocks in order to get bronze ingots... but wait, TR doesn't have an oredict entry, remember? So no converter works for their block.. to add salt to the wound, TR Bronze cant be converted to ingots. You have to cheat out your thermal bronze blocks and just cheat bronze ingots lmao

**Comment by Nightcaste** [comment]
This technically already works.  You can change the item mode of the Tome of Knowledge to automatically absorb XP that would normally go you your player.  The Solidified Experience item requiring you to use it first isn't a function of the Tome.  Using Solidified Experience as an item (aka Eating it) actually releases XP orbs that are immediately collected by the player, unless the book is set to intercept them.

**Comment by KingLemming** [comment]
Yeah, that was kind of my thought on it. Given all the special casing, I'm going to mark this one down as a no, sorry.
