### ISSUE TITLE
[Suggestions][ThermalFoundation] Add wildcard support for Machines

### ISSUE THREAD

**Issue by Tsyklop** [CoFH/Feedback#838]
Please add support for single wildcard ("*") for machines.

I use ModTweaker2.

I would add crushing damaged items. But added separately it long and hard. I thought I'd add this:
`mods.thermalexpansion.Pulverizer.addRecipe (5000, <minecraft: iron_helmet:*>, <minecraft: iron_ingot> * 2, <ThermalFoundation: material>, 10);`

But damaged helmets are not crushed.

https://github.com/jaredlll08/ModTweaker2/issues/243

**Comment by KingLemming** [comment]
While this might be a thing, we in no way support or approve of ModTweaker. There are just too many situations where it screws things up.

We'll have our own custom recipes via json in the next release, however.

I'll look into the feasibility of this, but I can't promise anything.

**Comment by Tsyklop** [comment]
@KingLemming How soon will the new release?

**Comment by KingLemming** [comment]
It'll be at least another week now since you asked. We don't like ETA requests.

**Comment by Tsyklop** [comment]
@KingLemming ETA?

**Comment by Parker8283** [comment]
Estimated time of Arrival (or Availability)

**Comment by Tsyklop** [comment]
@Parker8283 Ou...I understand. Thx.

**Comment by jaredlll08** [comment]
I am sorry about this, we told him it was our issue but he insisted he create it here.
Also if you would like us to remove support when you release your version, please just tell me :)

**Comment by KingLemming** [comment]
Nah, no worries. Honestly, the only real problem I have with MineTweaker/ModTweaker is the idea of a "reload" simply because that isn't actually possible.

People try to reload and things don't work right, because a lot of mods do things on startup and only startup. :/

**Comment by jaredlll08** [comment]
Yea, I am actually going to writ something that wil llet me define if a mod
can be reloaded, or just write a custom script file for thi gs that
shouldn't be reloaded.

**Comment by Tsyklop** [comment]
@KingLemming Any news?

**Comment by bookerthegeek** [comment]
@Tsyklop Yes their is, now that you asked it will be at least another week before they release an update. Please do not pester people who make mods for when they are going to update. Because the only answer you are going to get is "When I feel it is done"

("I" as in whoever makes the mod and not myself personally)

**Comment by Tsyklop** [comment]
@bookerthegeek I do not stick - I am interested .. How do I know the author could stop doing this and I'm waiting for?

**Comment by jaredlll08** [comment]
Did we not come to the comclusion that this was a modtweaker issue?

**Comment by Tsyklop** [comment]
@jaredlll08 I'm about the recipes in the json file.

**Comment by KingLemming** [comment]
It'll be in the next release. No, we don't know when that will be.
