### ISSUE TITLE
[Suggestion] "stand" cover, "plug" or "support", alternative to covered structuralducts

### ISSUE THREAD

**Issue by Paul17041993** [CoFH/Feedback#838]
Basically this;
<img width="556" alt="screenshot_103" src="https://user-images.githubusercontent.com/3912867/34823771-f5fa050a-f71f-11e7-95e4-7c8b89101d7d.png">

but for non-solid conditions like this;
<img width="695" alt="screenshot_104" src="https://user-images.githubusercontent.com/3912867/34823790-0932b07c-f720-11e7-97fe-3ad94ab971bc.png">

and also just a slightly better way to improve aesthetics (ie; make ducts look like they're actually mounted), without needlessly increasing the render complexity with covered structuralducts...

**Comment by KingLemming** [comment]
so you want an entirely different attachment which will needlessly increase render complexity?

**Comment by covers1624** [comment]
I think he is referring to a purely visual thing, like a stand that's automatically added to the duct and what ever it is next to every x number of blocks.

Could be an interesting concept.

**Comment by KingLemming** [comment]
I know what he wants, I'm just pointing out that in a strict sense, this is a request to needlessly increase render complexity.

**Comment by KingLemming** [comment]
Also, this is for TD, so it gets a big yellow label now which is essentially a caveat for "we'll see, it's all up in the air."

**Comment by Paul17041993** [comment]
nono, not an *automatic* one, just an alternate to the structuralduct covers that you can attach like a standard cover, but instead of being a flat cover it's just the structuralduct connection. This would be way less graphically intensive than using all 6 covers on a duct to make it a full block that doesn't hover...

**Comment by Paul17041993** [comment]
without a custom texture, but I guess you could register them as a secondary set of covers if you want...

**Comment by covers1624** [comment]
Well ill put both on the table, its a maybe at this point, i could justify some form of "anchor" that visibly holds the duct like a "U" or for other orientations a ring, imo having a any form of duct connection be it structual or not would just create confusion and having it be a "cover" that is just a structual connection for visuals is also confusing, imo the anchor idea is better, obviously as an attachment.

**Comment by Paul17041993** [comment]
ah yes, "anchor" would be the correct name for it, all it really needs to do at this point is manually render the structuralduct connection that already exists, I'm not disagreeing about a U or ring though.

**Comment by TheBrain0110** [comment]
I'm picturing basically what AE2's cable anchors do - you stick them on the side of a duct, and they connect to the next block.

Honestly, I thought that was how structuralducts on their own were supposed to work already. But they just float, unconnected to adjacent blocks like all the other ducts do. Unless you make them into covers.

**Comment by covers1624** [comment]
Even the cover "floats", I'm picturing something more than AE's cable anchors, as this is a duct opposed to a data cable, as i mentioned a U and Ring like structure around the duct somehow. Maybe the cover will get more of a visual connection to the duct, unsure how still. I'll likely fiddle with both in the rewrite, nothing will be added to the current version of TD in this regard.
