### ISSUE TITLE
weird crash when opening induction smelter gui

### ISSUE THREAD

**Issue by Sailren** [CoFH/Feedback#84]
http://paste.ubuntu.com/10080952/

http://openeye.openmods.info/crashes/0016a333bbb9c63d7dd4a9febaca3342

**Comment by KingLemming** [comment]
If you want to report a bug:

Include the mod name and version.
Include a pastebin (or equivalent) link to a list of all your mods.
Include the crash log
Be descriptive.
Use proper grammar and spelling.
If you can't do the above, please do not report any bugs.

**Comment by Sailren** [comment]
updated my comment with openeye info

**Comment by KingLemming** [comment]
Welp. Found your issue. Your CoFHCore is an alpha. Do not do that.

Download only from Curse. Not CurseForge.

**Comment by Sailren** [comment]
oki doki , thx man
