### ISSUE TITLE
Redstone Relays in Comparator mode not always updating

### ISSUE THREAD

**Issue by TheBrain0110** [CoFH/Feedback#840]
I was excited when I discovered that relays have a comparator mode, especially the Inverted Threshold mode, that was perfect for setting up some very compact automation of my dynamos. 

But then I noticed sometimes they weren't turning on or off when they were supposed to. And as far as I can tell, the relays simply aren't updating themselves reliably when the state of the block they're reading crosses the threshold.

If I see that it hasn't updated, I can open the GUI for the relay and watch it immediately go from output 0 to 15, so interacting with it forces an update.
And then sometimes they'll keep working & turning on & off properly, until sometimes they don't. It's one of those inconsistently reproducible bugs.

Examples: 

![2018-01-12_00 16 18](https://user-images.githubusercontent.com/3927226/34860829-2c59af3e-f72e-11e7-8a76-09320f9a2249.png)

![2018-01-12_00 20 02](https://user-images.githubusercontent.com/3927226/34860870-7b7d070a-f72e-11e7-84bd-0589dc99ec21.png)

There's two separate circuits here, one turns on the steam boiler when the drum gets below ~2/3 full, and the other turns on the servos pumping from the drum to the turbines when they have ~< 2/3 power buffer. (The fact that dynamos don't output stored power when they're not running was slightly annoying, as they'd never contribute or run like that, but I worked around it by adding another relay on the compression dynamo with the same condition)

The relays on the dynamos are usually reliable, although there have been a couple occasions where they stopped responding. The steam drum however rarely seems to update correctly, with the boiler never shutting off when it's full, although it does generally turn on when empty.

And the conditions are set correctly, as again, opening the relay's GUI will force it to update and behave.

![2018-01-12_00 16 38](https://user-images.githubusercontent.com/3927226/34860967-47289252-f72f-11e7-9164-f03707f0fc5d.png)

My last set is a power cell switch, with the bottom cell only outputting on a signal when the left one gets low.
I've only tested it a couple times since setting it up just now, but the relay has never responded to the left cell filling up to turn the bottom one off until I poke it.

**Comment by KingLemming** [comment]
Yes. Known. Probably won't be fixed.

**Comment by xannor** [comment]
I just wanted to note, the other modes seem to work without a problem and using a vanilla comparator does not display/cause this issue with them, so it is workaround-able, if less convenient.
