### ISSUE TITLE
Basic strongbox slot not working

### ISSUE THREAD

**Issue by Fabboz** [CoFH/Feedback#840]
HI,
yesterday, after installing some enderio item conduits, i found that the two first slot of my basic strongboxes are not working; i can place item in it but they don't interact with servo and item conduit(thermaldynamic).They see items only on the third slot.
Also when insert intem inside them they not appear in the first slot but in the third.
I have connected to the ender  io system a resinforced strongbox and them broke that box too with more unworking slot like 5. Then i delete the cofh config directory and created a complete ender io system with a servo that extract item from an item buffer and all come back to normal.
now the problem is that after a day the basic strongboxes first two slot not working again and deleting the config do nothing.

what you think about?

thx for the help bye

**Comment by KingLemming** [comment]
Sorry, no. Can't replicate this at all, and there is absolutely no basis in the code for anything like this. Also, deleting the config wouldn't do anything, period.

It sounds like EnderIO breaks Strongboxes. It has nothing to do with the Strongbox itself. TD Ducts and Servos work 100% properly with them.

Keep in mind that things can't insert/extract from the box if it's set to Restricted or Private.

**Comment by Fabboz** [comment]
i have found the problem. i can recreate it every time.
so it comes placing a basic strongbox next to an ic2 recycler that extract
item in the chest by using the extracting augment (ic2) and putting item of
the same kind in the strongbox by shift + click on the object in the
inventory.
that what i tested:
-  the machine was extracting on the first slot
- i had shift + click on a stack of 64 + one of 32
- after doing that the first two slot of the other chest in the world don't
work nomore

100% sure of that

pls say me if i can save my world thax



2015-09-14 17:45 GMT+02:00 KingLemming <notifications@github.com>:
