### ISSUE TITLE
CoFH Core isn't "crashing" but something is broken.

### ISSUE THREAD

**Issue by panic25** [CoFH/Feedback#841]
After pressing the play button and Forge finishes loading, the minecraft main-screen looks like this. 
I've tried both CoFHCore-[1.7.10]3.0.3-303 and CoFHCore-[1.7.10]3.0.4B1-308.
It's located in: C:\Users\[name]\AppData\Roaming\.minecraft\mods
I've already updated Java.
I'm using forge-1.7.10-10.13.4.1448-1.7.10 which I believe is the recommended one.
![minecraft broken](https://cloud.githubusercontent.com/assets/14280664/9858332/b9916492-5ae5-11e5-91d2-4b81ecde9887.png)

**Comment by KingLemming** [comment]
There are two issues here:

1) Your computer is a potato.
2) You didn't even TRY searching old issues or asking on IRC.

Use -Dforge.forceNoStencil=true as a JVM argument and please don't post tech support issues on here. Thanks.
