### ISSUE TITLE
Satchel doesn't dump into refinedstorage grid

### ISSUE THREAD

**Issue by SadChimera** [CoFH/Feedback#841]
The satchel doesn't recognize anything except the basic 'grid' from refinedstorage as a storage space. The basic grid is the only one that you can shift+rightclick with the satchel but even then, the contents aren't removed. Possibly on RefinedStorage's side, not sure if you can force items into it without knowing what it has the space to take. Also wouldn't want extra items getting nulled or crashing. Lots of devs don't know what `@nonnull`, `@nullable`, or `@override` are. So hopefully RS isn't one of them..

**Comment by KingLemming** [comment]
Entirely on RS's side.
