### ISSUE TITLE
[Suggestion] Upgrade-able Tools?

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [CoFH/Feedback#843]
I like the idea of empowered tools a lot. The pick-axe particularly. But as time moves on, and I acquire a lot of stuff, I'd like to be able to dige more than just 3x1 swatches of land. Maybe 3x3 or even 4x4. Of course it should cost a lot more RF to do so.

Same things with other tools as well, like sickle, shovel, etc.

**Comment by skyboy** [comment]
Beyond the scope of current mods.
