### ISSUE TITLE
Use Forge's Permissionsystem for (Sub)Commands

### ISSUE THREAD

**Issue by TechnicianLP** [CoFH/Feedback#843]
For reference please look at the `PermissionAPI` class provided by Forge.
Checking the Permissionsystem instead of the raw Op-Level has the benefit of a Server being able to grant access to specific subcommands without having to hand out Op - The Permission system checks for Op-Level by default so no problems with compatibility if the respective server does no make use of the system. (just a few calls boilerplate (1 for each permissionnode) and changed if-statements)

**Comment by KingLemming** [comment]
You're welcome to PR it. :)

**Comment by TechnicianLP** [comment]
You're welcome to write it yourself. ;) (sry)

**Comment by KingLemming** [comment]
If it's so simple to do but PRing it is out of the question, then how reasonable is this request actually? :/

**Comment by KingLemming** [comment]
Looked into this and conferred with Lex. The Forge API is less granular than the system we currently have and can be outright sabotaged by any given mod.

Sorry, but this is a no.
