### ISSUE TITLE
Dark oak replaces dirt and itemducts

### ISSUE THREAD

**Issue by psusi** [CoFH/Feedback#844]
This very well may be caused by non cofh code, but I set up a planter underneath a layer of dirt to place dark oak saplings.  On the surface pointed at the field, I placed a harvester and fertilizer.  Underneath the dirt I placed some itemducts to feed the saplings from the harvester back into the planter.  As the trees are grown, they sometimes replace the dirt on which they are grown with dark oak wood, even sometimes two layers deep, and even sometimes replacing ( and destroying ) the itemduct feeding the saplings back to the planter, breaking the loop and shutting down the system.  This is taking place in a Fen biome from biomes o' plenty.

Modules and versions are:

appliedenergistics2-rv2-stable-10.jar
BiomesOPlenty-1.7.10-2.1.0.1394-universal.jar
Chisel2-2.5.1.44.jar
CodeChickenCore-1.7.10-1.0.4.29-universal.jar
CoFHCore-[1.7.10]3.0.3-303.jar
Enchiridion-1.7.X-1.2b.jar
Mantle_mc1.7.10_0.3.0.jar
MapWriter-1.7.10-2.1.2.jar
MineFactoryReloaded-[1.7.10]2.8.0-104.jar
NEIIntegration-MC1.7.10-1.0.11.jar
NotEnoughItems-1.7.10-1.0.4.94-universal.jar
Railcraft_1.7.10-9.6.1.0.jar
RedstoneArsenal-[1.7.10]1.1.1-89.jar
ThermalDynamics-[1.7.10]1.1.0-161.jar
ThermalExpansion-[1.7.10]4.0.3B1-218.jar
ThermalFoundation-[1.7.10]1.2.0-102.jar
Waila-1.5.10_1.7.10.jar

**Comment by Tora-B** [comment]
Vanilla bug, I believe: https://bugs.mojang.com/browse/MC-10176. Was fixed for 1.8.2, but that doesn't help when you're on 1.7.10.

**Comment by skyboy** [comment]
It is a vanilla bug. Dark Oak destroys everything, including bedrock.

**Comment by psusi** [comment]
That is the one I was thinking about but once I found it and read it again, it is only about replacing blocks ABOVE and around where the tree grows, not below it.  I have been trying to reproduce the replacement of blocks below the tree on vanilla 1.7.10 with no success so far.

**Comment by psusi** [comment]
It is also worth noting that I have never had this problem growing Oak trees on a forestry multifarm, so I don't think this is really a mojang bug.  Will continue testing to lock it down.

**Comment by psusi** [comment]
Ok, so I was finally able to reproduce it in vanilla 1.7.10. It seems to only happen with the Dark Oak, not normal, and only when you plant them all very close and bone meal them. It seems the wider trunk trees trying to grow up right between two other wider trunk trees decide they can't unless they burrow down a block or two into the ground first.
