### ISSUE TITLE
Crash with Sequential Fabricator 

### ISSUE THREAD

**Issue by PessimisticBastard** [CoFH/Feedback#844]
Thermal Expansion Version: 1.12.2-5.3.10.14

Crashlog:

https://pastebin.com/BxaC112s

Mods:

https://pastebin.com/Z4VxiTXi

I was trying to use the Fabricator to create signalium blend. The moment it tried to craft the first blend... it crashed. 

If it matters any, the fabricator had the pattern validation augment.

**Comment by KingLemming** [comment]
Happened because you didn't actually have a recipe set in the Fabricator. I've mitigated it in dev now, but this doesn't seem to be able to happen if a recipe is correctly set.

**Comment by PessimisticBastard** [comment]
Will do. They are lovely little crafting machines, I must say.

**Comment by KingLemming** [comment]
Thanks, glad you like 'em!
