### ISSUE TITLE
Minor request - Signalum Servo coloration

### ISSUE THREAD

**Issue by Nightcaste** [CoFH/Feedback#845]
As they are now, Signalum servos have red borders whether they are stuffed or not.  The difference in the color between stuffed and not stuffed is not easy to tell (on all other servos it is VERY obvious).  I suggest changing the not-stuffed color of these borders to the same color used for Thermal's Electrum ingots.

**Comment by KingLemming** [comment]
Yeah. Honestly the textures need redone in general.
