### ISSUE TITLE
Cant get it to work at all D: Please Read!

### ISSUE THREAD

**Issue by harry-mccormack** [CoFH/Feedback#846]
Hello CoFH Team I hope you will read this,
         So i am trying to play some modded survival making my own private mod pack and i cant get Mine Factory or Thermal Expansion to work i have got Thermal Foundation and CoFH Core all at the latest versions and my Forge version is 10.13.4.1448.
https://cloud.githubusercontent.com/assets/14370347/9980742/9a9f29ba-5f9b-11e5-9711-a07d3f6157af.png
         There is the list of mods i am using for my pack, but with or without them none of the CoFH mods will work.
http://pastebin.com/3AvkPkCr
         There is a link to my Log when i tried to run the 4 mods at the top with fml (didn't work)

**Comment by harry-mccormack** [comment]
Get back to me as soon as possible :smiley:

**Comment by KingLemming** [comment]
It's like you didn't read the readme at all. This is a tech support request. Those go to IRC.
