### ISSUE TITLE
Energetic Infuser + Flux Reconstruction Augment no longer repairing

### ISSUE THREAD

**Issue by gradytrain** [CoFH/Feedback#846]
Here is my mod list to check for conflicts: http://modlister.com/user/gradytrain 

I am having an issue where items that used to be repaired by the Energetic Infuser no longer are being repaired. I put them in the machine and nothing happens. I noticed this happening a couple days ago, I did update to the new versions of all the CoFH mods.

If you guys need any other information let me know.

**Comment by KingLemming** [comment]
I'm going to need a video of this, because after testing basically one of everything...it works fine.

**Comment by gradytrain** [comment]
First time making one of these videos so let me know if you need a more specific action

https://youtu.be/WrfuHIfHNZM

**Comment by KingLemming** [comment]
I just went and recreated those exact items and they ran through just fine.

Are you sure you didn't have a redstone signalling issue?

**Comment by gradytrain** [comment]
It is set to ignore, I also just moved the machine and reattached it to my grid. It worked for like 90% of one item but then stopped and would not continue...

I will try to replicate it and capture a video.

**Comment by gradytrain** [comment]
Actually upon moving it back to the original position it seems to be working again...I have no clue what caused the original issue or the issue after it was moved.

I can close this issue, I will see if I can capture it more thoroughly if it happens again.
