### ISSUE TITLE
Minefactory Reloaded Crash with Thaumcraft Compatability

### ISSUE THREAD

**Issue by Happy4077** [CoFH/Feedback#847]
I repeatedly get this crash when trying to start a new world with these two mods downloaded. I do not know why this issue arises, as there are many packs that have these two mods included. I do not have Optifine or fastcraft, but I do have BetterFPS. Here is the startup log for creating a new world: 
http://pastebin.com/hmseMuna
Mod List: http://pastebin.com/y75AE1dw
I noticed that people have reported crashes similar to this, but I am not aware of this issue ever getting fixed. I will post this on Azanor's Github as well.

**Comment by KingLemming** [comment]
So you saw the old issues, realized they were closed with the comment, "Remove X mod," and then you posted this? ;)

It's a multi-mod interaction. MFR isn't the culprit. You'll have to pare down what is. It's a TC addon.
