### ISSUE TITLE
NuclearCraft Steam incompatible with ThermalFoundation Steam

### ISSUE THREAD

**Issue by kythorn** [CoFH/Feedback#847]
With NuclearCraft 2.8d installed, steam produced from a Thermal Expansion dynamo cannot be consumed by another Thermal Expansion Dynamo. Downgrading to 2.7a (the version in FTB Revelation) seems to resolve the issue.

Tested against TE 5.3.10.14 and TF 2.3.10.6.

I don't know if it's relevant, but after removing NuclearCraft completely, I needed to purge the default fluid list from level.dat to get Thermal Expansion working properly again.

Also opened at https://github.com/turbodiesel4598/NuclearCraft/issues/216 because I'm not sure which side the issue is on.

**Comment by kythorn** [comment]
Copying my comment from the other issue:

I just went to recreate my test case to package it up for you, and I was unable to reproduce it a second time. I thought I was completely losing my mind, so I went to my other test case and I verified can still reproduce it there.

I apologize for opening up a misinformed case - what I now suspect is actually happening is the following:

Start a new world with Thermal Expansion + Thermal Foundation installed
Add NuclearCraft
Start the game up again
The NuclearCraft steam wins (gets registered first), but some other part of the game (perhaps the fluid registry / default list in the save) is still clinging onto the Thermal Steam instead and this is the actual root of the problem.

The thing I I cannot explain is why downgrading the mod changed anything, perhaps it simple shook things up enough it forced a re-evaluation of which steam in the cache was valid.

I don't think this is either of your fault at this point - you're both registering steam the right way, it feels more like an internal forge fluid issue when mods get added to an existing world.

**Comment by KingLemming** [comment]
There's code in place to catch and update fluid references on my end, but it does rely on things happening in a normal way.

So you either have a 3rd party messing things up or something is causing the IdMapping event to not fire. Neither of those is ideal. But I do know that the code I have in place works.

**Comment by roboderpy** [comment]
Same issue here, after i upgraded all the CoFH stuff, im unable to push steam into steam dynamos in ANY way.

This is what happens BEFORE upgrading to https://github.com/CoFH/ThermalExpansion/commit/b9a2325c7e9e26b30524fd37ca826fd9166614ab
![video](https://i.dbot.serealia.ca/2018/01/3a427bfe65_%25pn_-2018-01-21_13-02-55.webm)
After upgrade im not even able to right-click bucket with steam
![steam](https://i.dbot.serealia.ca/2018/01/5e42f11e04_javaw_2018-01-21_13-03-53.png)

**Comment by roboderpy** [comment]
Unable to reproduce issue in singleplayer, but able to do so in multiplayer
