### ISSUE TITLE
[1.12.2] Energy Infuser stops working

### ISSUE THREAD

**Issue by AfterRebelion** [CoFH/Feedback#848]
Forge Version: 14.23.1.2589
CoFHCore Version: 4.3.10.5
Thermal Foundation: 2.3.10.6
Thermal Expansion: 5.3.10.14

When I use the Energy Infuser to recharge a Flux Capacitor, it stops working.
![imagen](https://user-images.githubusercontent.com/559819/34910249-585be5a0-f8b1-11e7-8dda-b527b93a155a.png)

The only things I did was:
1 Place a Energy Infuser on the world, and upgrade it.
2 Place a Energy Cell, and upgrade it to creative to supply power
3 Place a Flux Capacitor on the Energy Infuser and start recharging it.
4 Take the Flux Capacitor out of the machine, and put it again.
5 The Energy Infuser no longer works.

**Comment by KingLemming** [comment]
I need a video. I can't make this happen.

**Comment by KingLemming** [comment]
This sounds like a similar issue to #846, and I'm thinking that it may be crossmod in nature. Because it just...absolutely doesn't break with only CoFH stuff installed.

**Comment by AfterRebelion** [comment]
It may be crossmod, I will try to disable them one by one until I get it down.

**Comment by KingLemming** [comment]
Well, maybe start from the other end of the spectrum if it's not a problem. I can't seem to make it happen, but if you can take *just* CoFH stuff and do it, then clearly I'm missing a step in my testing.

I did follow your 5-step procedure though, thanks for the outline. :)

**Comment by AfterRebelion** [comment]
Nah, got it with only COFH mods installed
https://gist.github.com/AfterRebelion/24d9a3a8a0ccbddc90ee9e3faa540ea0

And got the procedure even simpler, you only got to take out the Flux Capacitor of the Enrgy Infuser, put it on again, and it doesn't work.
Will work on getting a video of it soon.

**Comment by KingLemming** [comment]
That's exactly what I did though. Put capacitor in, remove, put back in. Machine works fine.

**Comment by AfterRebelion** [comment]
Got it https://streamable.com/x2nz9
You can go to 1:05 to see the bug itself.

**Comment by KingLemming** [comment]
Wait, how are you removing it and why are you getting a duplicate? That doesn't happen for me.

**Comment by AfterRebelion** [comment]
Shift clicking. The Dupe only happens sometimes, and it is completily incosistent.

**Comment by KingLemming** [comment]
Ah geez. This is a bug with container code, not the Infuser. I copied MC's code so the root cause is gonna be Mojang. :/

Don't shift-click. :P I'll see what I can do on my end to prevent this.

**Comment by KingLemming** [comment]
Right. Root container code.

**Comment by KingLemming** [comment]
Got a mitigation.
