### ISSUE TITLE
[Suggestion] Remove limits for config values

### ISSUE THREAD

**Issue by Kevun1** [CoFH/Feedback#849]
In the TE config, there's a limited range on various configurable values like the base power of dynamos, the base capacity of energy cells, etc. Unless there is a good reason for having these seemingly arbitrary limits, I think they should be done away with. 

I'm trying to make a modpack with limited battery capacity as an important balancing mechanic, and removing the lower limit on base energy cell capacity would help immensely.

Thanks for you hard work btw.

**Comment by KingLemming** [comment]
There are reasons yes. It keeps things in a range where I can anticipate scaling behaviors. Otherwise somebody is going to set it to 1 RF/t max and then come crying to me that I didn't special case it right when they did something crazy like that where it wasn't designed to handle it.

**Comment by KingLemming** [comment]
The basic cell now has a range of 50k-20M RF. That's the best I can do though to keep odd config combinations from potentially creating a lot of lag, as well as keep the cell not completely useless.

Yes, I realize that would be the fault of the pack creator, but I'd still hear about it so it's not something I really want to allow

**Comment by Kevun1** [comment]
Thanks, that's perfect!
