### ISSUE TITLE
Sounds don't turn off

### ISSUE THREAD

**Issue by awweaver** [CoFH/Feedback#85]
Changed all the options to "false" in ThermalExpansion.cfg for sounds and the sounds still play.

Forge version: 10.13.2.1286
TE Version: S:Version=1.7.10R4.0.0B8

I'm running Wanderlust Reloaded with a few extra mods.

**Comment by awweaver** [comment]
![ss 2015-02-05 at 11 30 27](https://cloud.githubusercontent.com/assets/1010230/6074967/3edca29c-ad8f-11e4-9e7f-983638d631c5.png)

Here's the screenshot of the config file.

**Comment by skyboy** [comment]
There are presently red-herring entries for sound in TE's config file; the actual config values are in Client.cfg
