### ISSUE TITLE
[1.12.2] All machines with a liquid tank freezes from time to time

### ISSUE THREAD

**Issue by KorDum** [CoFH/Feedback#850]
ThermalExpansion 5.3.10.13 (from repo source, since I have made the repairing of items more balanced (more experience and energy requires))

The problem is floating. Steps couldn't be identified, but all machines with a liquid tank freezes from time to time. Visually the machine is displayed in process, but energy not consumed, liquid in tank not put out into pipe/reservoir/some.

**Comment by KingLemming** [comment]
You modified the mod and then came here saying it broke?

No. Just no.

**Comment by KorDum** [comment]
Sorry, but I only change XP amount of charger. No more.
Ok, I get version from CurseForge and I (with players of my server) will check it again.
