### ISSUE TITLE
[1.12.2] [Suggestion] Augment Flux Reconsctruction config

### ISSUE THREAD

**Issue by KorDum** [CoFH/Feedback#851]
Can you add config for
https://github.com/CoFH/ThermalExpansion/blob/1.12/src/main/java/cofh/thermalexpansion/block/machine/TileCharger.java#L46
and
https://github.com/CoFH/ThermalExpansion/blob/1.12/src/main/java/cofh/thermalexpansion/block/machine/TileCharger.java#L47
?
Repairing items is very unballanced now.

**Comment by KingLemming** [comment]
I'll consider it, but frankly it is not actually unbalanced. That's quite a bit more expensive than Mending.

**Comment by KorDum** [comment]
The fact is that players make **mob farms**, accumulate XP to Tome of Knowledge and used it for rare tools without Mending enchantment and vanilla random repair logic. This is recognized by the players themselves. The price of liquid XP doesn't compensate for ease of use.
That's why I raised the cost of XP *4, in order to somehow complicate repair.

**Comment by KorDum** [comment]
"implemented in dev" — big thanks for this feature! Now I can not get into the code mod.

**Comment by KorDum** [comment]
Oh, thank you very much!
