### ISSUE TITLE
[1.12.2] All CoFH enchantements can be use on pickaxe and hummers

### ISSUE THREAD

**Issue by KorDum** [CoFH/Feedback#852]
For example: Multishot can be use on pickaxe. Time from time pickaxe publishes the sound of a shot!
Or Holding enchantement.

**Comment by KingLemming** [comment]
This just isn't true. The only way this can happen is if you are forcing it somehow and there's no way for anybody to prevent that. (Anvil in Creative Mode or something else like that.)

**Comment by KorDum** [comment]
Hm. No, players don't have creative, only survivor.
Ok, I get version from CurseForge and I (with players of my server) will check it again.

JEI show me this enchantment is possible anyway.
