### ISSUE TITLE
When loading a world in single player tesseracts wont receive power

### ISSUE THREAD

**Issue by oster200** [CoFH/Feedback#852]
I have three tesseracts all chunkloaded and when I start my world none of the receiving ones work right away. I have to go to all of them and just click set frequency for them to work.

I am playing with a modded pack called Hermitcraft Modsauce 2. 
I have also used tesseracts many times before and they always worked. I dont know if it is something to do with another mod or not.

Pretty much my setup is I have one tesseract linked up to two others that are receiving power. When I load world I have to click set frequency on the ones receiving power.

**Comment by KingLemming** [comment]
It's either x-mod, or you aren't fully exiting Minecraft before you reload/swap worlds.

The latter issue is known and fixed in dev. As far as x-mod, though, out of our department unfortunately, and nobody else reports anything like this beyond the non-exit issue. :/

**Comment by oster200** [comment]
Well I just made a server with the same modpack and it doesnt do it their only on single player. 

thanks for the help though. If no one has any suggestions other than talking on the forums of that modpack (which i already did before coming here) than I will close the issue in two days.

**Comment by oster200** [comment]
So I dont know if it is another mod interfering because I made a modpack with just Forge 10.13.4.1448-1.7.10 and used CoFH Core 3.0.4B1-308, Thermal Expansion 4.0.3B1-218, thermal Dynamics 1.1.0-161 and Thermal Foundation 1.2.0-102

These were the only mods I put into the pack and I can still replicate the bug. When I load a single player world I have to reset the frequency to the receiving tesseract. If you need more info just let me know.

**Comment by KingLemming** [comment]
Using your exact test case, I cannot replicate this at all. It's either fixed in dev or is unique to something in your setup. Probably the former.

**Comment by dvo75** [comment]
This is an old thread but im very excited to see someone else had the same problem.  I am having the exact same problem as described by Oster200, also using Modsauce 2 modpack. All energy receiving tesseracts stop receiving upon login/out and the channel needs to be reset, as demonstrated in Oster200's youtube video. I see this was marked as Fixed but there is no solution posted??

**Comment by XFactHD** [comment]
Why should there be a solution posted if the solution is to simple update ThermalExpansion? If you carefully look at the tags (also the ones that got removed), one of them says "fixed in dev". What do you think that means?
