### ISSUE TITLE
[1.12.2] CoFHWorld doesn't seem to recognize biome restriction entries with an array

### ISSUE THREAD

**Issue by Vyraal1** [CoFH/Feedback#853]
Couldn't get Apatite and Bauxite to spawn with a generation entry of type dictionary and multiple biomes in an array, which should be possible according to this: 
https://teamcofh.com/docs/world-generator-configuration/#biome-entry.

Instead, a tester of my modpack managed to get it working by just having multiple biome entries like shown: https://github.com/Vyraal1/Interaction/pull/19/commits/4b01081e42873af1fcfeda1d0455f0aae040d4bf

Low priority, it was easy fix, or maybe documentation wasn't up to date but wanted to give a heads up.

**Comment by KingLemming** [comment]
Have that json handy? I'm thinking we need to clarify something in the documentation.

**Comment by Vyraal1** [comment]
Yep, right here. 

https://github.com/Vyraal1/Interaction/blob/master/config/cofh/world/04_SurfaceWorld.json

**Comment by KingLemming** [comment]
The one you linked should work fine. I was referring to the previous one which didn't work.

Though going back and looking at the git, I understand why. So the way you were doing it before was looking for a biome with ALL of those tags, not a biome with ANY of those tags. The default parsing is to AND things, not OR them. :)

I'll make a note for it to be clarified in our documentation. If you take a look at Thermal Foundation's oil gen, this is already how we handle it. Sorry for the confusion.
