### ISSUE TITLE
Minimum version of CofhCore not found...

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [CoFH/Feedback#854]
Nowhere to download it... Latest I can find is CoFHCore-[1.7.10]3.0.4B1-308.jar

https://i.imgur.com/XBfLWdG.png

**Comment by KingLemming** [comment]
Tech support. Please don't use the tracker for this.

That version isn't released and you shouldn't be downloading any jars that require it.

**Comment by Unrepentant-Atheist** [comment]
Tech support as in...?

**Comment by KingLemming** [comment]
Tech support as in this is not an issue and absolutely does not belong on the tracker. The mod is not broken, you simply don't have what the jar requires. Use IRC for things like this.
