### ISSUE TITLE
[Suggestion] energy cells to balance with an input/output option like machines do

### ISSUE THREAD

**Issue by coolgaza16** [CoFH/Feedback#854]
like the machines in thermal expantion that can input and output from one side at the same time could it be possible top do this with the power cells so that they can balance out each other if in a row so they dont drain one battery at a time improving power outputs as at the moment my cells at the end of my rows drain out one at a time for example if i have 8 in a row all outputting i get 8000rf output but as each cell drains im going down 1000 rf per cell that is drained while the others are still full.

**Comment by KingLemming** [comment]
No, sorry. That's not how it would work.
