### ISSUE TITLE
mods initializing phase freezing on CoFH tweaks, using latest 36

### ISSUE THREAD

**Issue by Nick-77ab2** [CoFH/Feedback#855]
So i know CoFH Tweaks probably isn't to blame here but im stuck, after a second day of reading the logs over and over again, i can't find what is causing the issue
http://pastebin.com/WeuSYgNJ
here's the log, no crash and i cant do ctrl+break cus the pause button on my keyboard doesn't have one. This isn't the complete log as the complete log would take an hour to scroll through.
any help would be appreciated.
edit: also this doesn't happen on my server, just the client, and this also happened with version 35.

**Comment by Nick-77ab2** [comment]
Fixed by removing optifine, but i still need to figure out if optifine causes it or CoFH Tweaks, it's probably optifine but still, need to know why so either the creator of optifine can fix it or you (the CoFH team) can fix it

**Comment by skyboy** [comment]
Optifine is known to be incompatible with tweaks. https://github.com/CoFH/Feedback/issues/482

**Comment by Nick-77ab2** [comment]
ok thanks for the info.
