### ISSUE TITLE
[1.10.2] TD - Locking viaducts

### ISSUE THREAD

**Issue by Jason505** [CoFH/Feedback#855]
Hi there!
On our server modpack, we're planning to build something like a transport system across the map via viaducts. Unfortunately, there is no way to avoid editing name of the entry. It could be stupid, if players could edit the names, everyone knows typical player of MineCraft. So, any idea/solution for this problem?
It would be best, if the entry could be edited only by player, who created it.

Thanks for response,
Jason505

**Comment by KingLemming** [comment]
Sorry, but 1.10.2 isn't getting any changes. No longer supported. This may be a thing in the upcoming TD rewrite though.
