### ISSUE TITLE
(Suggestion): Make Multishot COFH Bows only?

### ISSUE THREAD

**Issue by Akitori** [CoFH/Feedback#856]
Howdy! So I kinda wanted to suggest making the multishot enchantment cofh exclusive to its bows. The main reason being that in my modpack with a few other bows, we typically get the enchantment on the non-vanilla bows, get excited, and it doesn't work. 

Yeah a bit disheartening there. I understand why you did it, fixes and conflicts and stuff, but it makes most if not all multishot bows (outside of vanilla and cofh) not work at all. 

I understand this is a thing being worked on with some api probably being looked at, but its still disheartening to make a silent's gem bow for example, and only have one arrow fly out. So, i'd rather remove multishot from everything if possible. (Unless this is already possible with the configs, then i shall use the configs to do it)

**Comment by KingLemming** [comment]
No, sorry. I originally supported everything and then people came complaining that it broke other bows. So now I've gone the other way with it - bows need to opt-in. This won't be changing.

Feel free to submit a PR to Silent's Gems.

**Comment by Akitori** [comment]
So i just inform the modmaker of it? How would they go about adding it in exactly? (Is there a link or something i can send to em directly?).

Still thanks for the surprisingly rapid response!

**Comment by KingLemming** [comment]
I may have to provide an API - I think atm it's an internal-only class but I'll see what I can do.

Essentially the handler looks for instanceof IBowImproved and then processes multishot and the aftereffects.

I'll need to move that file from core files into the api but will look into doing so for next release.

**Comment by Akitori** [comment]
Ah alright. For now I'll just reference him this issue and maybe something can be done from there. Thanks!
