### ISSUE TITLE
[1.12.2] [Suggestion]: Add a config option for configuring the Item Transfer behavior of the satchel.

### ISSUE THREAD

**Issue by Tyrant0x1** [CoFH/Feedback#857]
It would be nice if I could configure the Satchel so instead of emptying into a target inventory on right click, it would empty into the target inventory on sneak+right click, or via some sort of keybinding (as sneak+right click is currently used for configuring the satchel's filters). Such an option might prevent me from, say, accidentally emptying my satchel full of tools into an extra utilities 2 trashcan.

Related, I noticed the documentation for the Satchel might need updated, as it indicates the Item Transfer requires a sneak+right click, when it currently only requires a right click: https://teamcofh.com/docs/satchel/

**Comment by KingLemming** [comment]
So, what outdated version are you playing on exactly?

It is indeed Sneak-Click to empty into an inventory. Just tested and confirmed. Sounds like you need to update.

I addressed this a while back, it's been changed, at this point I'm going on inertia, and no configuration will be provided, sorry. Simple fact is I can't seem to please everyone, and configs just don't end up doing it either, so unless there's actually a bug of some sort, the current behavior in the deployed versions is what it will stay as.

**Comment by Tyrant0x1** [comment]
Oh, I was on 5.3.8.38. It looks like I downloaded mods a few days before you released 5.3.9. I just hadn't been checking for updates, since a lot of authors don't update so frequently. It works great in 5.3.10! Sorry for the erroneous report.
