### ISSUE TITLE
Bug with Extra Alchemy Vials.

### ISSUE THREAD

**Issue by Akitori** [CoFH/Feedback#859]
linked here originally https://github.com/zabi94/ExtraAlchemyIssues/issues/31

I am having a strange bug with cofh potions, particulary instant variants when used in a vial.

https://youtu.be/1Mt2zZYNOe0

Main thing i want to point out is that i do get the effect, that's obvious from the flicker near the top. Yet, for some reason it isn't working? This is only for instant variations from cofh (so damage and instant harming)

**Comment by KingLemming** [comment]
Well I just tested with the normal potions, and those seem to work fine. So...dunno what to tell you. We use the normal potion system.

**Comment by zabi94** [comment]
Fixed it in extra alchemy 0.3.6.2.
It was not CoFH's fault, it was a bug with all instant potions with a duration of 0 ticks (so most of them).

**Comment by covers1624** [comment]
Thanks for the follow up.
