### ISSUE TITLE
Crash on placing any energy cell client side

### ISSUE THREAD

**Issue by Kvasyr** [CoFH/Feedback#859]
Crash log: http://pastebin.com/QaJWmTwx

The server is still running but client crashes
I dont really know what's going on, I would really appreciate if you guys could lend a hand 
thanks!

**Comment by KingLemming** [comment]
Duplicate of #818. Caused by client-server item mismatch, as far as we can tell. Can you make it happen with *only* CoFH mods? I'm about 99% sure this is entirely x-mod and/or the fault of a script.
