### ISSUE TITLE
Fractioning Still: no output to pipes

### ISSUE THREAD

**Issue by KaseiFR** [CoFH/Feedback#86]
Hi,

First of all, I'm very happy that Thermal Expansion has come to 1.10. Can't wait for the Strongboxes and the ducts!

I noticed that the fractioning still cannot be emptied by pipes, but can only auto-output its fluid. I tested both EnderIO and ExU2. The bug appeared in FTB Beyond, but I reproduced it in isolation (with the 2 previous mods and JEI). Despite any face config, the block does not seem to allow the output to be piped out. I tested both tree oil and naphta.

![2017-03-12_23 32 03](https://cloud.githubusercontent.com/assets/6408124/23836676/4c7228ca-077c-11e7-840a-e0971f1b2f24.png)

Note that the auto output works fine (see the basic tank), and that pipe interaction for the input slot too (see the second resin tank).

**Comment by KingLemming** [comment]
Please only report bugs if you're using the latest version of the mods, as the readme for this repo states. This has been fixed for nearly a week.
