### ISSUE TITLE
[Bug Report] Shear Coppers in Multiplayer

### ISSUE THREAD

**Issue by 231joe33** [CoFH/Feedback#860]
Minecraft Version: 1.12.2
Mod Name: ThermalFoundation-1.12.2-2.3.10.6-universal
Mod List: ![mod list](https://user-images.githubusercontent.com/30916890/35031236-f6192548-fb16-11e7-9425-ffde86a0aabe.png)
Crash log: [crash-2018-01-16_20.48.53-client.txt](https://github.com/CoFH/Feedback/files/1638046/crash-2018-01-16_20.48.53-client.txt)
Description: When playing in multiplayer mode, if you die in any way (through players, mobs, kill command) the game will crash upon respawning; however, when re-logging into the server the game continues as normal. This problem does not happen in Singleplayer mode.

**Comment by KingLemming** [comment]
Your client and server configurations are mismatched.
