### ISSUE TITLE
Crashing when Removing Machines

### ISSUE THREAD

**Issue by WiduX** [CoFH/Feedback#860]
When I attempt to mine a TE machine, such as the Pulverizer, with a pickaxe, or shift-right click with a Crescent Hammer, The game crashes and produces the following report: http://pastebin.com/1AKkZ2nH

**Comment by WiduX** [comment]
I have determined that this crash occurs only when Peripherals++ is installed. I have filed a report over on austinv11's GitHub, here: https://github.com/austinv11/PeripheralsPlusPlus/issues/122

**Comment by skyboy** [comment]
Closing as we can do nothing to avoid this crash, see my comment in the other issue.
