### ISSUE TITLE
Crash when a Thermal Dynamics Filter should filter for worldinteraction upgrades

### ISSUE THREAD

**Issue by megalous** [CoFH/Feedback#861]
I have added a world interaction upgrade to the empty whitelist of an ThermalDynamics filter.
When the ThermalExpansion Sawmill starts to output items into the duct the game crashes and as soon as i enter the chunk it will crash again. 

The filter works without problems if only a chest is added to the whitelist of the filter in the middle of the duct network.

I have tested it with a pulverizer using cobblestone, too. The picture and log are from the test with Rubber wood from MFR.
![Setup with a sawmill](https://cloud.githubusercontent.com/assets/9299795/10116398/6ff54ab2-6434-11e5-9fdb-be5a02ac8ea8.png)

![Filter GUI](https://cloud.githubusercontent.com/assets/9299795/10117460/e3eb0c2c-6457-11e5-8734-252ba1654085.png)

[Crashlog](http://s000.tinyupload.com/index.php?file_id=04396132354546587132)

[Crashlog with pulverizer and cobblestone](http://s000.tinyupload.com/index.php?file_id=89327880809770027098)

[Crashlog with only the necessary and up to date mods ](http://s000.tinyupload.com/index.php?file_id=03765928984225217579)

[Crashlog without NEI and codechickencore](http://s000.tinyupload.com/index.php?file_id=06460415441361525562)

**Comment by megalous** [comment]
https://github.com/rwtema/extrautilities/issues/742

**Comment by KingLemming** [comment]
Wow. No. Use Pastebin for crashlogs. Also, this has been reported already. Please search in the future. It's on ExU's end.
