### ISSUE TITLE
[Bug] Machines randomly stop working

### ISSUE THREAD

**Issue by a20eac1d** [CoFH/Feedback#862]
I am using the latest version of all COFH mods and the bug happens with Thermal Expansion machines. They randomly stop accepting items. They keep using power (for nothing), but nothing actually happens inside them and all slots are empty. This is only fixed by breaking and replacing the machine.

**Comment by KingLemming** [comment]
What versions exactly are you using?

**Comment by KingLemming** [comment]
Actually, I already know the answer. It's not the latest, because I hotfixed a corner case where this could happen a couple of days ago.

Please go download the latest.
