### ISSUE TITLE
Thermal Expansion Satchel (Void) Crash

### ISSUE THREAD

**Issue by Armitige** [CoFH/Feedback#863]
I equipped a void satchel on my hotbar and my client crashed. Now unable to reconnect to server.
https://pastebin.com/Yem5LU7N

**Comment by Yusixs** [comment]
Doesn't happen to me, do I need to follow specific steps?

Direwolf 1.12 Modpack v1.5.0
TE version 5.3.9.9
Forge version 14.23.1.2585
CoFH Core 4.3.9.2

**Comment by KingLemming** [comment]
Please update. This has been fixed. :(
