### ISSUE TITLE
[TE] Cache Dupe 

### ISSUE THREAD

**Issue by MySt1k** [CoFH/Feedback#863]
https://youtu.be/xUGbq7IuMDw

Last versions mods

**Comment by KingLemming** [comment]
I don't really understand what's going on there. It seems like your inventory didn't properly sync between server and client. If this was the fault of the cache, this would happen with everything, and not just a specific chisel block.

Have you let chisel know?

**Comment by MySt1k** [comment]
yes
https://github.com/Chisel-2/Chisel-2/issues/418

**Comment by TheCricket** [comment]
I think when he is opening the chisel the second time it is actually a "ghost item". There looks to be a complete de-sync of everything I don't understand what is actually happening other than that.

**Comment by TheCricket** [comment]
So after google fu we have determined this is on a server, can you replicate this in singleplayer?

**Comment by skyboy** [comment]
Fixed in chisel's code.
