### ISSUE TITLE
When loading a world in single player Redstone Energy Fluxduct not send power to  Fluctuating Itemduct

### ISSUE THREAD

**Issue by VladimirMangos** [CoFH/Feedback#864]
I use Fluctuating Itemducts for transfer power to some machines.
Fluctuating Itemducts connected and transfer power from Redstone Energy Fluxducts.
All work fine until world reload or chunk reload. After this power not transfered to Fluctuating Itemducts  and machines. Redstone Energy Fluxducts show as connected with Fluctuating Itemducts.
If I use Crescent Hammer for disconnected its and reconnect then power start transfered in proper way.

[added]Recently find that sometime just disable and reconnect  Redstone Energy Fluxduct with Fluctuating Itemduct not always restore power transfer. Possible this more close to real problem. And world/chunk load just trigger problem.

**Comment by VladimirMangos** [comment]
More careful look at events happen at reconnecting  Redstone Energy Fluxduct with Fluctuating Itemduct when power transfer failed. I see at reconnecting:
1) Itemduct get power (contain max amount for itemduct)
2) then it start lost power (transfer it to connected machine) without continues recharging from Fluxduct.

**Comment by KingLemming** [comment]
So, looked into this. The ducts are working properly, but perhaps unintuitively. You are expecting that the Fluctuating ducts will not backfeed into the higher tier energy ducts. This is not the case. Use Energy Cells to force energy flow in a specific direction.

I may add a block for this purpose, but ultimately this is just the nature of how ducts work. Thankfully, there's no actual bug here.

**Comment by VladimirMangos** [comment]
Sorry, maybe my description has been not clear possible.
In my case Fluxduct allways have max power. So not any backfeed from fluiduck back to fluxduck.
Problem in absent feed from connected fluxduck to fluiduck with some chance after world reload or disconnect/reconnect fluxduck to fluiduck.
