### ISSUE TITLE
Cryo-stablised fluxduct recipe

### ISSUE THREAD

**Issue by HanFox** [CoFH/Feedback#867]
I'm sure there's a good explanation, but I'm curious and the wiki is incomplete (and I see no other issues about it).

I wonder why the Cryo-stablised Fluxduct requires a Redstone Fluxduct in the recipe instead of a Resonant Fluxduct?

Surely just as a basic tiering system a tier 4 item would be needed for tier 5, not the tier 3 item?

**Comment by KingLemming** [comment]
No, this is actually intended. The cryo-cooling negates the need for Enderium's magical-ish properties. Also, they're really quite expensive given that you make one at a time. :)
