### ISSUE TITLE
Suggestions: Skeletons able to use Cofh Bows, along with multishot interaction (plus more)

### ISSUE THREAD

**Issue by Akitori** [CoFH/Feedback#867]
So basically i was testing with replaceitem command to see if i can equip thermal foundation items to skeletons. It worked! I was able to give them bows, but uh...

They treat them like melee weapons. I mean maybe for the average user, that's enough. Me, i like having death delivered to me in high speed!

Also that leads to multishot..It doesn't work on skeletons wielding the bows. I think that's intentional, but i kinda want mobs to use their enchantments on me as the player. Just my two cents.

Demonstration of both:

https://youtu.be/SR64NmrAwaU

**Comment by KingLemming** [comment]
Skeletons are hardcoded to look for the vanilla bow only. So that's a vanilla limitation. Also, Multishot by design has to use the event system, and Forge only fires events for players, so that's a Forge limitation.

Sorry, neither is possible.
