### ISSUE TITLE
Thermal Exp. missing recipe

### ISSUE THREAD

**Issue by jusjudge** [CoFH/Feedback#869]
Forge Version: 14.23.1.2600
Minecraft Version: 1.12.2
Thermal Exp. Version: 5.3.10.15
Thermal Foun. Version: 2.3.10.6
CoFH Core Version: 4.3.10.5

Not sure if you needed all that information but in case you did it's there. Any machine I try to build, regardless of the mod, that requires a machine frame can't be done because the recipe for the machine frame is missing.

**Comment by KingLemming** [comment]
So yeah, gonna need more info, because we do add the recipe and it does exist.

Are you sure you have the right recipe? Have you checked JEI?
Are you playing a modpack? If so, what is it?
Can you recreate this with an older Forge?

**Comment by jusjudge** [comment]
I checked JEI again and actually none of the recipes to create a frame/cell work besides the device frame. Also, some of the augment recipes aren't there. I didn't know forge could have an effect on recipes. I will try to push back to an older forge. I am playing a modpack but it's a private pack that I created.

**Comment by KingLemming** [comment]
I can't say that it necessarily is the cause, but Forge has screwed a few things up with recipes in the 1.12 era, so I don't want to rule it out.

It sounds a lot like you have some issues with your pack, though. If the mods were just missing recipes, I promise you that you wouldn't be the first (and only) report of it.

**Comment by jusjudge** [comment]
@KingLemming SO with going through all the mods I have updated earlier today one by one, checking forge and updating java, I found the culprit. The **platforms** mod new update that came out today was what was stopping the recipes in TE from showing. I apologize for the inconvenience.

**Comment by covers1624** [comment]
Thanks for the follow up.
