### ISSUE TITLE
After update can't open energy cell UI

### ISSUE THREAD

**Issue by Staegrin** [CoFH/Feedback#87]
Just updated to CoFHCore-[1.7.10]3.0.0B9-132 and CoFHLib-[1.7.10]1.0.0B9-87
from CoFHCore-[1.7.10]3.0.0B9-127 and CoFHLib-[1.7.10]1.0.0B9-85 now when I try to open the user interface for any of the energy cells I crash to desktop. They can still receive/output energy.

crash logs:
http://pastebin.com/xQ5zFCLD
http://pastebin.com/hjNMedcY
http://pastebin.com/Wg3bLwTk

After further testing it has become clear this problem extends to all thermal expansion machines.
crash log:
http://pastebin.com/cxYp8g8C

**Comment by grydian** [comment]
Also getting the same crash.

http://pastebin.com/3yPqp7GB

**Comment by KingLemming** [comment]
Oh hey, more people using ALPHA builds from CurseForge. Don't do that. Release versions are on curse.com.
