### ISSUE TITLE
Add an option to force fluxed shield discharge at "damage dealed" rates?

### ISSUE THREAD

**Issue by roboderpy** [CoFH/Feedback#870]
As title says. Player can basically cover him behind a shield, and don't give a fuk about incoming melee attack which should deal at least *40 hearts* damage. And do this endlessy times.

Also i think Fluxed shield shouldn't cooldown after reflecting an attack made by mob/player with axe.

*first i thought this is a scaling health issue, when player in full set of adamantine armor getting hit by an average mob he lose 5 - 10 hearts, but when he uses Fluxed shield - he is invincible in both meanings (no damage taken and shield 😝 at mob), but vanilla shield and other modded shields take full damage*

**Comment by KingLemming** [comment]
This isn't making sense. The shield *does* discharge. You're claiming that it doesn't.

**Comment by roboderpy** [comment]
They *do*. But **only** per-use, not per *damage point*.

**Comment by KingLemming** [comment]
Yeah, that was essentially required to fix a specific behavior. Sorry, this won't be changing.

**Comment by roboderpy** [comment]
So this shield is overpowered for a reason

**Comment by KingLemming** [comment]
In your opinion.

**Comment by roboderpy** [comment]
I request config option because shield differs from vanilla shield. 

And why don't you think that shield is overpowered? In request i mentioned about durability and i will repeat myself - in case where fully repaired vanilla shield would break after three hits and fluxed shield can even stay without holding, unbreaking and flux capacitor for ages.
