### ISSUE TITLE
[Question] CoFH Core WorldGen parametrs

### ISSUE THREAD

**Issue by Tsyklop** [CoFH/Feedback#870]
I do not understand the two parametrs ... on the wiki says it is not understand .. I did not understand what they are doing.
this:
"chunkChance" - for which he is responsible and how to operate it matter? The lower the value the greater the chance of generation?
"horizontalDensity" - for which he is responsible and how to operate it matter?

**Comment by KingLemming** [comment]
Right at the top of this repo - "Bugs and suggestions. Take questions and complaints elsewhere."

That means take questions to the IRC.

"chunkChance" is pretty clearly described as a 1/N chance of the feature being in the chunk. Horizontal density applies to fractal generation, and the name is self-explanatory.
