### ISSUE TITLE
Crash: Sequential Fabricator with Augment: Pattern Validation crash without set recipe through input

### ISSUE THREAD

**Issue by Dinerell** [CoFH/Feedback#871]
How i got that:

1. Place a (any Tier above Hardened) Sequential Fabricator with an Augment: Pattern Validation
2. Do not set a recipe (or erase all recipes)!
3. Transfer items through Itemduct (as well any type)
4. Get a NullPointerException

It is totally functional without the augment!

through Machine Input:
[crash-2018-01-21_14.14.19-server.txt](https://github.com/CoFH/Feedback/files/1649778/crash-2018-01-21_14.14.19-server.txt)

through Itemduct input:
[crash-2018-01-21_14.28.05-server.txt](https://github.com/CoFH/Feedback/files/1649780/crash-2018-01-21_14.28.05-server.txt)

**Comment by KingLemming** [comment]
This has been fixed for over a week. Please go update.
