### ISSUE TITLE
Mod Sorting Error (crash during startup)

### ISSUE THREAD

**Issue by WolfAmaril** [CoFH/Feedback#872]
I just had [this error] (http://pastebin.com/vhnU2g0S) while starting up an admittedly heavily modded instance. The weird part is, I have not changed any mods or config settings for this instance between the last time I played on it (and it worked) and now.

This has also happened once before and simply restarting Minecraft fixed it.
EDIT: The issue isn't fixing itself any more.

**Comment by KingLemming** [comment]
This isn't our fault, sorry. It's simply a combination of mods where the deps weren't properly coded.

**Comment by WolfAmaril** [comment]
Fair enough, just put it here first cause yours was at the top of the list.
