### ISSUE TITLE
Tamed animal duplication with morb

### ISSUE THREAD

**Issue by AlexandrePavy** [CoFH/Feedback#873]
Hello 
- Forge 14.23.1.2555
- CoFHCore 1.12.2-4.3.10.5
- CoFHWorld 1.12.2-1.1.1.12
- Thermal foundation 1.12.2-2.3.10.6
- DrZharks MoCreatures 12.0.3

I found a bug with the new morbs item, i can duplicate tamed animals (i check with horses and wyverns)

![2018-01-21_14 20 36](https://user-images.githubusercontent.com/6603411/35194651-cbaa0e96-feb6-11e7-875d-7fc2eaf2ddda.png)
![2018-01-21_14 20 52](https://user-images.githubusercontent.com/6603411/35194653-cbf69040-feb6-11e7-948c-510d650fbf2b.png)

Thanks

**Comment by KingLemming** [comment]
Please explain or provide a video.

**Comment by AlexandrePavy** [comment]
Hello,

sorry for the lack of precision, there is a video here 
- https://1drv.ms/v/s!AjQ5mOwIi99K-yGmDEfz2M32IRpA (no need account, and cut the sound I forgot I was on discord we hear someone at the beginning)

**Comment by P3rf3ctXZer0** [comment]
I can also duplicate any Thermal Item broken with Tinker Tools from Tinkers Construct. (Cheap way to make many Dynamos)

**Comment by KingLemming** [comment]
So, this doesn't actually seem to happen. Single player or server, just doesn't actually happen.

So I'm thinking this is caused by another mod.

**Comment by AlexandrePavy** [comment]
indeed it may be Mo'creature, should we have a config to disable morbs to prevent duplication ?

Thank you.

**Comment by KingLemming** [comment]
There's already a config for that. You may wish to report this to Zhark though, and see if CustomMobSpawn can be fixed to prevent this.
