### ISSUE TITLE
Forge Multi Part Support for Thermal Dynamics

### ISSUE THREAD

**Issue by DrakoAlcarus** [CoFH/Feedback#874]
Is this a possible feature soon? I think it would make some space to crate neat designs, like cover strips running along the ducts themselves, or have the duct pop through a hollow block. I noticed when a transparent duct passes through a cover of any type, it appears to block of the tube, making it aesthetically displeasing. Basically a minor detail, but I also think it's a good alternative to TD covers. 

The side of the ducts have room for covers and panels, and the Super-Laminar Fluiduct fits precisely into the hollow microblocks. Now the Cryo-Stablized Fluxduct is a block thick, so that is out of the question.

Also, any future plans to change the Sawmill face texture?

**Comment by KingLemming** [comment]
No, we won't support FMP ever. But the covers are more improved in how they render in dev.

I'll see about the sawmill.

**Comment by DrakoAlcarus** [comment]
Why not?

Applied Energistics and ProjectRed offer support. Is it the way the ducts are coded?

**Comment by KingLemming** [comment]
We supported FMP before and got burned badly for it. There's absolutely no incentive for us to take that risk. Zero.

**Comment by DrakoAlcarus** [comment]
Hmm... by burned you mean it caused lots of issues in game, or the owner of FMP disproved of it?

or did it just anger people?

**Comment by KingLemming** [comment]
Basically every single issue we had with ducts in 1.6.4 were due to FMP. Never again.

**Comment by DrakoAlcarus** [comment]
Darn. Well, thanks for the explanation!

i'm super hyped for the upcoming update. Is it going to be for 1.9 when it comes out?
