### ISSUE TITLE
Flux Chiller bug

### ISSUE THREAD

**Issue by DrakoAlcarus** [CoFH/Feedback#876]
I found a bug involving certain blocks and Flux Chiller. The Flux Chiller snow patches replace many hollow blocks like floor buttons, levers, ducts, signs, and any block that lets me reach the block the target block is resting on.

![2015-10-15_02 34 58](https://cloud.githubusercontent.com/assets/12781728/10510063/824b3090-72e5-11e5-8ab6-97d633edcb19.png)

**Comment by KingLemming** [comment]
This is hilariously Mojang's fault, but I can put a check in for it.

**Comment by DrakoAlcarus** [comment]
Thanks!
