### ISSUE TITLE
[Thermal Dynamics] Crash loop when pushing item duct with piston.

### ISSUE THREAD

**Issue by Flanks255** [CoFH/Feedback#876]
So, a player on the server i run, decided to push a item duct with a piston(don't ask), and a crash-loop ensued.

apparently, the rest of the duct work thinks the duct is still there, and tries to cast the piston as a duct.

with the following server side [Log](https://pastebin.com/508V0v3Q)
MC 1.12.2
Forge 14.23.1.2556
TD 2.3.10.4

**Comment by KingLemming** [comment]
Ducts cannot be moved by pistons. If you have a piston which is able to move a duct, then you have a mod enabling that and it's the fault of that mod, because it is clearly doing it wrong.
