### ISSUE TITLE
[Compatability][Redstone Arsenal] Issues with DragonAPI in Console

### ISSUE THREAD

**Issue by ranger135xp** [CoFH/Feedback#877]
I don't know if this is causing any bugs for sure, but DragonAPI is complaining in console upon initial load. It instructs to contact the mod author. If you can't read the image, let me know.
![screenshot 3](https://cloud.githubusercontent.com/assets/15115164/10533265/dc587b7e-7394-11e5-9d00-fb9cde1de912.png)

**Comment by skyboy** [comment]
This is not an issue with RedstoneArsenal. None of our mods interface with DragonAPI.
