### ISSUE TITLE
Blitz Spawn in an unexpected biome

### ISSUE THREAD

**Issue by VT-14** [CoFH/Feedback#878]
As the title says, I'm having Blitz spawn in Mushroom Island biomes in a Mystcraft age.  Specifically the MushroomIslandShore biome.

COFH Core: [1.7.10] 3.0.3-303
Thermal Foundation: [1.7.10] 1.2.0-102
(Expansion and Dynamics similarly up to date via Curse)
Mystcraft: 0.12.3.00

**Comment by KingLemming** [comment]
Have screenshots? Are you 100% sure that it's a Mushroom Island Shore biome?

Basically here's the thing - there's literally no way this is our code at all. Blizzes spawn in cold and snowy. That's it, no exceptions. However, it's entirely possible for something to screw with vanilla biomes and change their tags.

**Comment by VT-14** [comment]
It's a Blitz, not a Bliss.  It also turns out I was wrong about the biome; It's actually a "Pocket Plane" (Thaumcraft 4?) biome (tiled biome distribution).  I think something is still up as only Blitzes are spawning in those areas.  Thaumcraft: 4.2.3.5

The confusion was caused by the 'nothing' blocks not having any texture until a block update, forming an x-ray machine (see picture).  I initially didn't see any caves underneath, but turns out there are some.

![2015-10-16_16 47 48](https://cloud.githubusercontent.com/assets/12564251/10553084/53d10d38-7426-11e5-9d14-deb925977e54.png)

**Comment by KingLemming** [comment]
k, well that's solved then. Clearly, the pocket plane biome is either PLAINS or SANDY.

There's no code issue here.
