### ISSUE TITLE
Duplicate Any Thermal Block Broken With Tinkers Construct Tools

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [CoFH/Feedback#879]
I can duplicate any Thermal block broken with Tinker Tools from Tinkers Construct. (Cheap way to make many Dynamos)

Thermal Things

https://minecraft.curseforge.com/projects/cofhcore/files/2519297
https://minecraft.curseforge.com/projects/cofh-world/files/2513671
https://minecraft.curseforge.com/projects/codechicken-lib-1-8/files/2509819
https://minecraft.curseforge.com/projects/thermalexpansion/files/2520117
https://minecraft.curseforge.com/projects/thermal-dynamics/files/2518224
https://minecraft.curseforge.com/projects/thermal-cultivation/files/2518223
https://minecraft.curseforge.com/projects/thermal-foundation/files/2518222

Tinker Things

https://minecraft.curseforge.com/projects/tinkers-construct/files/2518400
https://minecraft.curseforge.com/projects/mantle/files/2474052
https://minecraft.curseforge.com/projects/tinkers-complement/files/2508767
https://minecraft.curseforge.com/projects/plustic/files/2508052
https://minecraft.curseforge.com/projects/tinkers-tool-leveling/files/2507887

You know what copying a block is - You break a single block but get 2 instead of one. One last thing block saves NBT status. So keeps fluid and fuel etc.

**Comment by KingLemming** [comment]
Not caused by us and I'm pretty sure also not caused by TiCon. We had a report of this previously and it was a third party interfering.

**Comment by P3rf3ctXZer0** [comment]
Do recall which third party @KingLemming
