### ISSUE TITLE
Client crash - Placing a resonant servo in the picture below crashed to desktop.

### ISSUE THREAD

**Issue by ProsperCraft** [CoFH/Feedback#879]
http://pastebin.com/drM2QeYE

![image](https://cloud.githubusercontent.com/assets/4427684/10556438/c7262e62-743f-11e5-88d5-0b0b4fa55f81.png)

**Comment by KingLemming** [comment]
1) What's that block it's attached to?
2) What are you talking about? If you're able to take a screenshot, it didn't crash.

**Comment by XFactHD** [comment]
That's a vacuum chest from EnderIO.

**Comment by ProsperCraft** [comment]
The user crashed then was able to log back in, I teleported to him and took the shot.

**Comment by ProsperCraft** [comment]
This was on a server ;)

**Comment by KingLemming** [comment]
Does it happen consistently?

**Comment by KingLemming** [comment]
Can't replicate this and TD isn't in the original log at all anyways. Probably an existing Forge bug w/ player inventories. Unlikely to be fixed in Forge.
