### ISSUE TITLE
TE Crash When Placing Items in Cache

### ISSUE THREAD

**Issue by SJ1133** [CoFH/Feedback#88]
Game crashes as soon as you put an item in the basic Cache. ( I put in seeds)
CoFHCore-[1.7.10]3.0.0B9-132
CoFHLib-[1.7.10]1.0.0B9-87
ThermalExpansion-[1.7.10]4.0.0B8-23.jar
ThermalFoundation-[1.7.10]1.0.0RC1-34

EDIT: Log: http://pastebin.com/CYyaxa7j
Also this game is singleplayer.

**Comment by KingLemming** [comment]
You are using alpha versions from CurseForge. Why? :( Release builds are on Curse, not CurseForge.

**Comment by Revemohl** [comment]
I just got a crash while trying to open the GUI of an autonomous activator after updating to CoFHCore 132, so I assume it's because the UUID work isn't complete yet. If you insist on using test builds, just go back to the previous CoFHCore.

**Comment by SJ1133** [comment]
I thought I was helping to test out the builds :( . also switching to previous cofhcore does not fix this
