### ISSUE TITLE
[Redstone Arsenal] Possible Flux-Infused Pickaxe Bug

### ISSUE THREAD

**Issue by Raidriar0899** [CoFH/Feedback#88]
Currently, as of version 2.0.2.217 and beyond,  the empowered Flux-Infused Pickaxe mines a 2x1 area instead of its previous 3x1 area. If this is a balance change, it is undocumented, but if not then it is a bug. I have CoFH Core updated to 4.1.0.155. I am playing on the 1.10.2 All The Mods modpack, in case it is an inter-mod conflict. [Mod List](https://github.com/CoFH/Feedback/files/839903/listmyfolder.txt)

**Comment by Raidriar0899** [comment]
[Mod List](https://github.com/CoFH/Feedback/files/839903/listmyfolder.txt)

**Comment by KingLemming** [comment]
Change *seemed* to be intentional, but I don't agree with it. So it's been undone. :)
