### ISSUE TITLE
[Suggestion] [TE] CraftTweaker options.

### ISSUE THREAD

**Issue by Notawallplan** [CoFH/Feedback#881]
I'm just going to leave some minetweaker enhancements that can be implemented into Thermal Expansion for more creative recipie creation. I am absolutely not sure if any of these are implemented, and nicely point out those already implemented.

- Ability to limit processing recipies by machine tier.
- Custom fuel and fuel burn time (regardless of furnace burn time)
- A general specialization-type augment that adds a byproduct slot to most machines that can be used for recipe creation.

And I'll accrete more ideas for CraftTweaker over time on this post.

**Comment by KingLemming** [comment]
Well, if you have any others, go ahead and put them up, because none of these will be happening, sorry.
