### ISSUE TITLE
Game & Server crashing after placing 2 machines next to eachother

### ISSUE THREAD

**Issue by Antonwinther99** [CoFH/Feedback#882]
Here are the 2 crashlogs from the server:

**Comment by Antonwinther99** [comment]
http://pastebin.com/KL713BXj

**Comment by Antonwinther99** [comment]
http://pastebin.com/urb3yz1S

**Comment by Antonwinther99** [comment]
Version of Thermal Expansion is: ThermalExpansion-[1.7.10]4.0.3B1-218
Thermal Foundation version: ThermalFoundation-[1.7.10]1.2.0-102
Thermal dynamics version: ThermalDynamics-[1.7.10]1.0.0RC7-98

**Comment by Antonwinther99** [comment]
Forge version: forge-1.7.10-10.13.4.1517-1.7.10-universal

**Comment by KingLemming** [comment]
Something is attempting to create a FluidStack from a null fluid. This can happen when the modlists aren't the same on server and client, or when a mod has messed something up.

In either case, we enforce that CoFH mods are installed on both, and we also do our fluids properly, so it's not us.
