### ISSUE TITLE
COFH Missing

### ISSUE THREAD

**Issue by DeckadeNemo** [CoFH/Feedback#883]
I have tried every version of COFH on Curse to get this error to stop, but I can not seem to get it to see that the mod is there can you please assist?

http://pastebin.com/Knzhnbtp

**Comment by blockbreaker1361** [comment]
I was just getting ready to post the same thing. I'm having the same problem and cannot find a version of COFHCore higher than 3.0.4.

**Comment by KingLemming** [comment]
3.1.0 isn't released yet. You're either using an ALPHA of Minefactory Reloaded (which you should not), or another mod is improperly depending on CoFHCore based on the github.
