### ISSUE TITLE
Suggestion: A way to manufacture Cinnabar

### ISSUE THREAD

**Issue by KirbyQK** [CoFH/Feedback#884]
Really simple suggestion; maybe fluid transpose 1b or 2b of Destabilized Redstone into rich slag?

**Comment by KingLemming** [comment]
Ehh...I'm not particularly fond of the idea, but I'll think about it.

**Comment by Tahakk** [comment]
Isn't there like 50% chance to get it from pulverizing redstone ore? Not counting that there is augment for more chance of secondary output if I remember correctly.

**Comment by KirbyQK** [comment]
Yep, but that's not a particularly reliable way to get a constant amount. Destabilized Redstone, Redstone and Gold ores are the only way to get it, and it's quite handy for processing, for example, Nickel as you get 3 ingots, plus a 100% chance of a Platinum ingot. I'd be willing to trade 10 - 20 redstone, or 4 - 8 Destabilized Clatharite to get a reliable supply.

**Comment by Akitori** [comment]
Personally i would like keeping it as a rare drop myself. Sure i lose redstone ore (and not even if using the right augments) but i gain almost 3 (or 4) times more ores from a single source block. I usually use it on valuable blocks (nickel for example). I understand wanting more of it, but i feel it should keep its partial rarity (redstone isn't uncommon anyway, and by the time you get to the augments you would more than likely have a silk touch pickaxe).

Just my two cents

**Comment by KirbyQK** [comment]
That's exactly the problem for me - I want to process copper, nickel, platinum, iridium and mana infused. At the rate that I obtain cinnabar the normal way (redstone and destabilised redstone with silk touch or void miner) it isn't nearly enough to keep up.

If you make it 2b + rich slag per cinnabar, it wouldn't be possible to get a net gain in redstone (you get 18 redstone dust if you pyro-concentrate redstone ore). Maybe create it by fluid transposing destabilised clatharite with one of the TE fluids, energised glowstone, resonant ender, aerotheum, petrotheum, maybe even primal mana depending on the 'flavour' of cinnabar?

It really comes down to what the intended flavour of the item is, and whether it can be reasonably balanced IMO.

**Comment by bochen415** [comment]
There are mods out there (Mekanism) that can transform Redstone + Cobblestone into Redstone Ore.

**Comment by KingLemming** [comment]
Yeah, and that's problematic enough on its own.

**Comment by KingLemming** [comment]
Yeah, after giving this some thought...if this is something you really want, you can add it with ModTweaker. It's just not something I want to add to the base balance of things, though.
