### ISSUE TITLE
Magnet Causing Lag

### ISSUE THREAD

**Issue by Badcholo** [CoFH/Feedback#885]
I use the magnet on my baubles neck slot. When i go mining with a Atomic Disassembler from mekanism i get massive lag. The Server actually freezes up and sometimes times me out.
I am able to mine really fast with the atomic Disassembler and i'm looking for a mod that adds max mining speed to stone and dirt. I have 16gb of ram on the server and it's separate from my computer. It's connected directly to the internet with a commercial line. 
I have only noticed this lag when i use the Magnet. I have also experienced gaining a lot of levels quickly from this. I have actually been doing some testing and it seems i get much more extra xp. specially when i have a full inventory and i let all the ores just swarm around me.
I don't really know how to diagnose this issue.

**Comment by XFactHD** [comment]
Which magnet are you using?

**Comment by Badcholo** [comment]
whoops... Ender IO
