### ISSUE TITLE
Suggestion: Fluxed Phyto-grow rebalance

### ISSUE THREAD

**Issue by Bigmanvegas** [CoFH/Feedback#886]
I was going over the numbers in the phytogenic insolator and was wondering if you could add a config to change the output scales for the phytogrow as I see the scale goes x1, x3, x4 from the base crop. The efficiency power wise based on wheat goes 1200rf per crop, then 500rf with rich phyto, and then skyrockets to 1450 per crop with fluxed when you slap the energy "tax" to make it. The sapling augment is also in the same boat, but it's arguably different as you can make charcoal and feed dynamos for more power. As it stands there is no reason besides crafting components and/or fuel for extractors(haven't tested) to use fluxed phyto over rich.

**Comment by KingLemming** [comment]
Yeah, your math is great, if you completely ignore every other cost that isn't RF. Sawdust and pulverized charcoal aren't free. Niter isn't free. Slag isn't free either. And Rich Phyto-Gro takes Sap. Or Rich Slag.

Fluxed *only* takes RF. There's no "tax," it's quite intentionally balanced.
