### ISSUE TITLE
COFH World JSON

### ISSUE THREAD

**Issue by Aknotsdeath** [CoFH/Feedback#888]
I am trying to use COFH to clear ores out of the over world and every dimension but its not working as I had intended. http://i.imgur.com/gHtJxXR.jpg this is the world and this is the config for AE2 as an example http://i.imgur.com/J8UgaWD.png It will be easier for me to include a screen shot of all the mods. http://i.imgur.com/DKcn298.png http://i.imgur.com/EvuGHWW.png http://i.imgur.com/MvfgjkI.png http://i.imgur.com/yAU1pjG.png http://i.imgur.com/VhyxMOa.png If I missed some information I am sorry but if you need anything let me know and I will get it for you. Thank you :)

**Comment by Aknotsdeath** [comment]
Also I have this set to true as you can see. http://i.imgur.com/vMvP1a5.png

**Comment by KingLemming** [comment]
So, this is a tech support issue. -_-

That means take it to IRC. There's no bug here, you simply don't understand something.

CoFHCore can't *clear* ores. That's not a thing it can do. It can override vanilla generation, but that means Minecraft ores. It has no control over what other mods generate.

**Comment by Aknotsdeath** [comment]
Sorry about that thank you for your time.

**Comment by KingLemming** [comment]
No worries!
