### ISSUE TITLE
Sawmill not accepting IC2 rubberwood in 1.12.2?

### ISSUE THREAD

**Issue by ServantGirl** [CoFH/Feedback#888]
Hello. So the sawmill is not accepting the IC2 rubber wood. This, IMO was the most useful function of the mill. 

Is there like a config I can alter or something to restore the 4 planks with the chance at resin?

**Comment by KingLemming** [comment]
There is not. You could write your own mod or use ModTweaker, but that's it.

I'm guessing you just recently started playing TE 5. Maybe try the mod out for a bit and see what's changed rather than disliking the things that are gone.

**Comment by ServantGirl** [comment]
Thank you~ This sent me on a learning adventure and I was able to restore my favorite function of the block<3 

I've dabbled a bit in the new stuff. The block upgrades are a really cool idea, I like that so far a lot.
