### ISSUE TITLE
[Thermal Expansion] Wrong fluid texture on Fluid Transposer

### ISSUE THREAD

**Issue by XFactHD** [CoFH/Feedback#89]
When the fluid transposer is crafting with Energized Glowstone, the window in the front shows the texture of Resonant Ender instead of Energized Glowstone.
I am not using any graphics enhancing mods in my modpack.

Forge: 12.18.3.2254
CoFH Core: 4.1.0.155
TF: 2.0.3.77
TE: 5.0.3.86

**Comment by covers1624** [comment]
Ah, whops, forgot about that..
