### ISSUE TITLE
[Thermal Expansion] NBT Tag weird on morbs item

### ISSUE THREAD

**Issue by temp1011** [CoFH/Feedback#890]
Using 'dev' branch of Thermal Expansion. As far as I'm aware the code is exactly the same in the current released version.

I've been using `stack.serializeNBT().getString("id")` in some code I've been writing using morbs. It seems that this returns the Item id/name of the morb (ie - `thermalexpansion:morb`) rather than the id of the entity contained in the morb. 

The RawNBT I got off the a filled morb that made me suspect this is [here](https://gist.github.com/temp1011/11b8059eb2e4c981dd8ac313dde7e722). I used the command `/entitydata @e[type=Item,r=3] {}` for a dropped morb in the world.

Hopefully this should just be a rename. I'm sorry if this is bad code on my end or I've messed up in some other way.

**Comment by ImbaKnugel** [comment]
To get the NBTTag of an ItemStack you use `ItemStack#getTagCompound`. So this returns the id of the contained mob: `stack.getTagCompound().getString("id").`

**Comment by temp1011** [comment]
Ah that makes more sense. Thank you!

**Comment by KingLemming** [comment]
What exactly are you trying to do....? Just curious.

**Comment by temp1011** [comment]
I'm the annoying guy yesterday on discord asking about devices ;). I tried to see if I could maybe help by coding one myself. As you might have guessed it hasn't gone too well so far..

**Comment by KingLemming** [comment]
The Morb class has code to trivially auto-morb a mob. That's how I'll be doing it. ;)

**Comment by temp1011** [comment]
I'm not sure at the moment whether to return generic morbs or not since if I catch the actual entities in the world the morbs won't stack. At the moment I'm capturing real world entities (with all 17 nbt tags...) However, the greater problem for me seems to be things like getting a device to work lol. I'm happy to share code/create a pr/whatever but I don't know if it would be useful compared to just starting from scratch. Most of the code is adapted from other devices anyway.

**Comment by temp1011** [comment]
You're right. I think it's beneficial to have morbs stack and it's only a small disadvantage/balance tweak to have players not get special items/armour.

**Comment by KingLemming** [comment]
Honestly, while I appreciate your initiative on this, I will almost certainly be going with my own version of it. :)

It's actually a pretty large balance concern, so I need to think it through.
