### ISSUE TITLE
Disabled tools still showup on NEI even when said to not show them

### ISSUE THREAD

**Issue by Nagapito** [CoFH/Feedback#891]
When I disable armor and tools from COFH Foundation and also disable showing the tools on NEI, they still appear. Even worst, they now appear with multiple damage values

https://imgur.com/a/Xrs1x

**Comment by KingLemming** [comment]
Have you tried with ONLY CoFH mods?

**Comment by KingLemming** [comment]
Seems to be something in NEI. Will look into a workaround.
