### ISSUE TITLE
Crash with Redstone Arsenal (AbstractMethodError)

### ISSUE THREAD

**Issue by mastershivam** [CoFH/Feedback#892]
[Crash Report1](https://gist.github.com/mastershivam/51d9d6fcd08914d5626c10906e423acbl)
 [Crash Report 2](https://gist.github.com/mastershivam/543dce8cb37971cc236860a32f1d164d)

When loading with Redstone Arsenal on a modified FTB Revelations, this crash occurred. (Crash Report1) All mods are up to date and forge is up to date. When removing Redstone Arsenal, the game crashes with Thermal Foundation. (Crash Report2)

**Comment by KingLemming** [comment]
Modified, huh?

You caused this, somehow. You probably have a mod including things it should not be, and jar surgery will be required.

**Comment by Mattsingen** [comment]
@mastershivam I had this issue also on my own pack and found the culprit to be COFH Lib that is no longer needed for the COFH mods. It might cause issues with other mods, but I haven't come that far in testing. 
Try removing that from your pack and see if it works.
