### ISSUE TITLE
[Bug] Gany's Nether Flour not placeable in Redstone Furnace

### ISSUE THREAD

**Issue by p75369** [CoFH/Feedback#893]
Include the mod name and version
   Gany's Nether   1.8.1 / Thermal Expansion       1.7.10R4.0.3B1

Include a pastebin (or equivalent) link to a list of all your mods.
   http://pastebin.com/VgtQSP6T

Include the crash log
   N/A

Be descriptive.
   As above. Flour->Bread is listed in NEI and via clicking on the recipe button in the furnace as a valid recipe but the flour cannot be placed in the furnace.

Be respectful.
   Many thanks for an otherwise excellent collection of mods.

Use proper grammar and spelling.
   Please note that whilst every care has been taken to ensure this report is free of errors, it has been prepared in an environment that contains typos and poor grammer and, as such, trace elements may be present.

**Comment by KingLemming** [comment]
Does the flour have an OreDictionary name?

**Comment by p75369** [comment]
dustWheat	1xitem.ganysnether.flour@0	ganysnether:flour

**Comment by KingLemming** [comment]
Technically, this is an issue w/ Gany's mod.

The furnace recipe is being registered using the ITEM. That means that a Wildcard value is being passed.

The OreDictionary registration, on the other hand, does NOT use the metadata. So this is inconsistent.

It needs to be handled on TE's end, but ultimately the is the result of inconsistent coding...which can sort of be blamed on Mojang.
