### ISSUE TITLE
Ic2 cables won't connect to Mfr Machines

### ISSUE THREAD

**Issue by Rickiedrash** [CoFH/Feedback#895]
Running latest version of Ic2 Exp, Mfr, and CofhCore
Ic2 cables won't connect not sure if this is a bug or simply no longer a feature can't find any documentation on Mfr post 1.6.4

**Comment by KingLemming** [comment]
This is a question. -_-

These go to IRC. Please read the README in the future.

But I'll answer - IC2 Exp changed tons, and MFR doesn't support it.
