### ISSUE TITLE
Crash when clicking duct with CTRL + middle click

### ISSUE THREAD

**Issue by MrRiegel** [CoFH/Feedback#896]
https://pastebin.com/QbrC6k4s

**Comment by KingLemming** [comment]
Yeah, given the amount of bugs that Forge has had lately with that, I'm not sure if we're going to support the behavior at all.

**Comment by MrRiegel** [comment]
ok

**Comment by KingLemming** [comment]
Okay so I can prevent the crash. I will not promise that there won't be any weirdness though. Not entirely sure what Forge is doing/trying to do anymore.
