### ISSUE TITLE
Bug Found!

### ISSUE THREAD

**Issue by coolhuh24** [CoFH/Feedback#897]
Dear COFH TEAM,
The problem with your mods is that they are 99%incompatible with Forge's new loading screen.I hope you will fix this incompatibility with forge so we can play with your mod again.
Links:-
1.http://www.minecraftforum.net/forums/support/modded-client-support/2507387-cofh-core-crash

If i try to disable forge loading screen incompatible with cofhcore it glitches my game!

**Comment by KingLemming** [comment]
You submitted a Pull Request with this too. Also, disabling the Forge loading screen does work.

And lastly, you *only* have to do that if you're playing on a potato. So 99.999999% of all people don't experience any sort of conflict at all.
