### ISSUE TITLE
Thermal Dynamics Facade crash

### ISSUE THREAD

**Issue by lightlike** [CoFH/Feedback#897]
MC-Version: 1.12.2
Forge: 14.23.1.2601
Thermal Dynamics: 2.3.10.4-universal
Thermal Foundation: 2.3.10.6-universal

Game Crashing completely, after a few minutes in a World with Facades on Fluiduct.
Only Facades: Grass Block
(Might be connected to Chisel ?! Chisel: 0.1.1.26)

Error does not occure when placing Facade in running world. Only after restarting.

> [17:21:43] [JM-task-4/WARN]: Unable to get any texture to use as color for thermaldynamics:duct_16[meta=3]  
> [17:21:43] [main/WARN]: Unable to locate team.chisel.api.IFacade.getFacade()  
> [17:21:43] [JM-task-4/WARN]: Unable to get any texture to use as color for thermaldynamics:duct_16[meta=2]
> [17:22:18] [Badge_e8b69ebec0f74c4393ccadaf5feeadcc/WARN]: Main Badge API errored, using fallback: java.net.ConnectException: Connection timed out: connect

**Comment by covers1624** [comment]
This literally tells us nothing, provide your full crash report.

**Comment by lightlike** [comment]
There is no crash report. This is all I found in the log. I will try to reproduce it and find more information.

**Comment by KingLemming** [comment]
If that's all you've got, then it probably wasn't us.

**Comment by lightlike** [comment]
Seems to be right. I can't reproduce it. Probably just because "Minecraft".

**Comment by covers1624** [comment]
Its likely just warnings from journey map or the like then, complaining that it cant grab colors from the textures for some reason. Just ignore them.
