### ISSUE TITLE
Crash with bronze pickaxe... 

### ISSUE THREAD

**Issue by RepoDraghon** [CoFH/Feedback#898]
When trying to break a Red Crystal Cluster from Actually Additions with a Bronze Pickaxe the game crashed repeatedly...
When I tried the same pickaxe on a Vanilla Minecraft Sea Lantern, the same crash happened...
[crash-2018-02-01_13.43.41-client.txt](https://github.com/CoFH/Feedback/files/1688327/crash-2018-02-01_13.43.41-client.txt)
[crash-2018-02-01_21.23.56-client.txt](https://github.com/CoFH/Feedback/files/1688328/crash-2018-02-01_21.23.56-client.txt)

**Comment by KingLemming** [comment]
"at ljfa.glassshards.handlers.BreakSpeedHandler.onBreakSpeed(BreakSpeedHandler.java:22)"

There's your problem. It's not us.

**Comment by RepoDraghon** [comment]
Thanks, I know the mod now just found it weird that it was only your bronze pick causing it, cause it wasn't crashing when I used a Tinkers pickaxe

**Comment by KingLemming** [comment]
Yeah, it seems to be making some poor assumptions on the backend.
