### ISSUE TITLE
DragonAPI claims to not find class redstonearsenal.RedstoneArsenal

### ISSUE THREAD

**Issue by piedpipr314** [CoFH/Feedback#898]
Exact line: "[FML/DragonAPI]: DRAGONAPI ERROR: RedstoneArsenal class not found! redstonearsenal.RedstoneArsenal"

This is with DragonAPI V9b and Redstone Aresenal 1.1.1-89
This one stumps me.  Should you guys need more lines from my log that DragonAPI gives, I can put it in a pastebin.

**Comment by bookerthegeek** [comment]
Did you have the api installed and then remove it?

**Comment by Calenria** [comment]
should be fixed: https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/316

**Comment by KingLemming** [comment]
Okay. Let DragonAPI know about it. This has nothing to do with us.
