### ISSUE TITLE
[Enhancement] Allow Warp Itemducts to Recieve Power from Logistic Pipes Network

### ISSUE THREAD

**Issue by mikeloeven** [CoFH/Feedback#899]
Considering how the logistics network has such a poorly implemented and asinine RF transmission capabilities and Warp Itemducts are useful for straight through links between distant networks I think it would be wonderful if the warp item ducts could natively convert logistic power into RF allowing them to be powered directly from the logistics power junction. There is not much of a ballance issue here as there is a known conversion ratio of 10RF to 5LP and the power draw for the system would remain the same regardless of wether or not the itemducts are drawing power from the logi network or a seperate RF conduit. the only benefit would simply be less cabling which is the major problem with integrating Warp Ducts and Logi pipes especially in tight spaces

**Comment by KingLemming** [comment]
Sorry, not doing this. RF is the universal standard and there's really not a great reason for them to be using their own internal power, especially if the conversion is a very trivial 2:1.

**Comment by bookerthegeek** [comment]
IIRC the LP power system is in theory a laser that is created at the rf/ic2 power block, and beamed down the middle of the pipes and converted by magic baking into the original energy form at the destination.

This would also have the unintended effect of seamlessly converting IC2 energy into rf.

Internal power is LP as it can be powered by either RF or EU.
