### ISSUE TITLE
[Suggestion] [Thermal Dynamics] Upgrade Filters/Servers by Shift-Right-Clicking

### ISSUE THREAD

**Issue by DigitalSketch** [CoFH/Feedback#899]
I didn't see this suggestion in the issues list, so not sure if it's been recommended yet, if so, I apologize.

Was wondering if you could setup the servos and filters to be upgraded by shift-right-clicking on them with the appropriate ingot.  Have the settings be saved that were currently on the items when you do this.  Would be really cool to do this!

Thanks.

**Comment by covers1624** [comment]
So, this already exists, RedPrint's, can save and load basically any thermal machine's settings, including attachments, There is however is a suggestion here https://github.com/CoFH/Feedback/issues/889 for the ability to inworld upgrade / replace the attachments on ducts.
