### ISSUE TITLE
Invisible texture for hardened Magmatic Dynamo's

### ISSUE THREAD

**Issue by killerscorpion** [CoFH/Feedback#90]
This is what i did:
1) I made 3 magmatic dynamo's.
2) I placed all three on the ground.
3) I right clicked on each one with a Hardened Upgrade Kit.
4) I right clicked each one with a Crescent Hammer.
5) I picked them back up.
6) Invisible item texture on my player inventory.

Note: When I mouse over on the item stack of 3 dynamos in my inventory, it still shows the tooltip like it should. its literally just the item texture is gone. 

Setup specs:
Forge 12.18.3.2239 for 1.10.2
Thermal Expansion 5.0.3.86
Thermal Foundation 2.0.3.77
CofhCore 4.1.0.155

**Comment by KingLemming** [comment]
That can't be your entire modlist, because that just doesn't seem to happen.

**Comment by killerscorpion** [comment]
I have seen on Reddit that some people are having similiar issues when Project Red is present. Not sure if thats related. But nonetheless here is my modlist:

Agricraft
Animania
AE2
Aroma1997core
AromaBackup
Autoreglib
Bibiocraft
Biomes o plenty
Bullseye
Chameleon
Chicken chunks
Chisel
Chisels and bits
Chunk animator
Codechicken core
Codechicken lib
Cofh core
Compat layer
Dramatic skys
Dynamic surroundings
Ender io
Ender storage
Ender core
Extra utilities
Extreme reactors
Fast leaf decay
Foam fix
Forestry
Fore multipart CBE
Fullscreen Windowed (borderless)
ichunutil
Immersive engineering
Infinity lib
Inventory tweaks
Iron backpacks
Jei bees
Journeymap
JEI
Just enough resources
Mantle
Mcjty lib
Mo' bends
Mob dismemberment
Mrtjpcore
Open glider
Pams harvestcraft
Platforms
Project red- base, integration, lighting, mechanical
Quark
Railcraft
Redstone arsenal
Reliquary
Rftools
Shetiphian core
Simple quarry
Simply jetpacks 2
Storage drawers
Thermal expansion
Thermal foundation
Tinkers construct
Unity
Zerocore

**Comment by killerscorpion** [comment]
I will try removing PR and get back to you on the results

**Comment by killerscorpion** [comment]
Well i cant seem to reproduce this problem at all anymore, so i dont know whats going on, i just relogged into my game. i guess were good for now lol.
