### ISSUE TITLE
Ducts sending ghost items (stacks with 0 size?) to drawers, which corrupts them

### ISSUE THREAD

**Issue by Paril** [CoFH/Feedback#900]
This one is a bit hard to describe, but, I have narrowed it down to itemducts and the way servos seem to work.

Servos seem to try to send every item in an inventory out, even if the connected face can't output certain things. For instance, in a Farmer from Actually Additions (but this happens with any block that supports items in inventories that don't get output), place items in the left-hand side; this side is the seed side, and can't be piped out from. Connect that via itemduct + servo to a Storage Drawer or Storage Drawer Controller. The result is that the servo will send the ghost of the left-hand side items to the drawers, as if it sent a stack of 0 of the items over to it. This ends up being a problem with a separate bug in drawers that makes locking/removing empty items impossible.

Version: ThermalDynamics-1.12.2-2.3.10.4-universal.jar
Video of issue: https://streamable.com/ivcvc

Originally I thought this was a Storage Drawer-only issue, but it seems that the issue in Storage Drawer with empty stacks is just easily reproducible from ducts.

**Comment by KingLemming** [comment]
Okay so the duct knows nothing about the inventory. It just extracts. The issue here is that you have inventories which are not correctly "sanitizing" their ghost items and just hand them over.

So while this is kind of annoying...it's not really on the duct.

**Comment by Paril** [comment]
I thought so too, but it's weird because no other transfer mechanism (conduit, ExU pipes or Logistical Pipes from Mekanism) have this problem, so it can't solely be limited to StorageDrawers. I know StorageDrawers does have a separate bug with ghost items, but it seems two-fold here that this mod's transfer mechanism is able to do this. Why does it tell the other inventory about the items it has if it can't even extract it to begin with? Shouldn't it test for valid extraction before actually doing it?
