### ISSUE TITLE
Tome of knowledge (and maybe other items) method onItemRightClick always returns EnumActionResult.PASS on clientside

### ISSUE THREAD

**Issue by rafradek** [CoFH/Feedback#901]
It's a bad behavior, it causes off-hand items to be accidentally activated. If it is not possible to tell if using an item will do something on clientside, use EnumActionResult.SUCCESS instead.

**Comment by KingLemming** [comment]
No, that would break other behaviors and is incorrect.

**Comment by rapus95** [comment]
Just out of curiosity, what are the interactions with the tome that need the pass enum here? (I'm one of those who always accidentally place an offhand torch per stored level of exp) and do you have any tip besides not having anything in offhand?

**Comment by rafradek** [comment]
Are you sure about that? See ItemMonsterPlacer for example
