### ISSUE TITLE
Log the mismatching IDs during "Packet payload failure"

### ISSUE THREAD

**Issue by Baughn** [CoFH/Feedback#901]
Please?

I'm staring at the ID map for my server, and I don't see anything wrong. Not to mention, it's only happening for one player. The error is getting rather obnoxious, and I want to debug it.

**Comment by KingLemming** [comment]
That player needs a copy of a working client then.

**Comment by Baughn** [comment]
Actually, I was mistaken; it's happening for ~everyone, it's just that most players' computers are fast enough to process the NPEs faster than they can pile up.

I'm wondering if it might be some sort of conflict between the Electrical Age and TE packet handling, as it gets much worse if EA is sending lots of packets. I thought ID conflicts of that sort were a thing of the past... but I just had a look at the EA network code, and it's a mess which certainly doesn't comply with 1.7 coding standards. Can't confirm it without taking a look at the TE code, though.

**Comment by KingLemming** [comment]
There's not really a way to do this unfortunately. :/ The "check the ID map" is sort of a holdover from 1.6 when players could change such things.

Now Forge automates it and sometimes it gets screwed up.
