### ISSUE TITLE
Precision Sledgehammer functionality on Other Wrenches

### ISSUE THREAD

**Issue by DrakoAlcarus** [CoFH/Feedback#902]
Is it possible to add sledgehammer functionality to the other wrenches of Redstone Arsenal and Thermal Expansion? I.E. the area highlight with the area of effect machines. I don't want to have two of the same wrenches that serve the same function.

**Comment by skyboy** [comment]
It's tied specifically to the precision sledgehammer to avoid being really annoying while working with any other wrench.

**Comment by DrakoAlcarus** [comment]
I understand the Battlewrenches, but what about the normal wrenches?
