### ISSUE TITLE
Crash on rendering screen with cofh core

### ISSUE THREAD

**Issue by Memoirs00** [CoFH/Feedback#903]
Minecraft crashes on startup with CoFHCore-1.10.2-4.1.12.17-universal. It says that it crashes on rendering screen, and here is the crash report:
[crash-2018-02-03_17.42.15-client.txt](https://github.com/CoFH/Feedback/files/1692321/crash-2018-02-03_17.42.15-client.txt)
List of mods I have:
<img width="479" alt="asas" src="https://user-images.githubusercontent.com/34219961/35772820-7b3e9568-090a-11e8-97f7-f432112a09ae.PNG">
Any help would be appreciated! Thanks!

**Comment by KingLemming** [comment]
You are apparently missing mods. No idea what or why Forge is screwing up the error screen, but there you go.

**Comment by Memoirs00** [comment]
Any idea what mods I could be missing?

**Comment by KingLemming** [comment]
Nope. Try installing things in groups, best advice I have for you.
