### ISSUE TITLE
crashes Server

### ISSUE THREAD

**Issue by GBGBGB13** [CoFH/Feedback#904]
Server log:
04.02 02:09:58 [Server] INFO Wrong Minecraft Versions!
04.02 02:09:58 [Server] INFO Mod: codechickenlib
04.02 02:09:58 [Server] INFO Location: /mods/CodeChickenLib-1.12.2-3.1.5.331-universal.jar
04.02 02:09:58 [Server] INFO Expected: [1.12,1.12]
04.02 02:09:58 [Server] INFO Current: Minecraft 1.10.2
04.02 02:09:58 [Server] INFO at net.minecraftforge.fml.common.Loader.sortModList(Loader.java:251) ~[Loader.class:?]
04.02 02:09:58 [Server] INFO at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:536) ~[Loader.class:?]
04.02 02:09:58 [Server] INFO at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98) ~[FMLServerHandler.class:?]
04.02 02:09:58 [Server] INFO at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:328) ~[FMLCommonHandler.class:?]
04.02 02:09:58 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:121) ~[ld.class:?]
04.02 02:09:59 [Multicraft] Server shut down (starting)
04.02 02:09:59 [Multicraft] Restarting crashed server in 3600 seconds
04.02 02:09:59 [Multicraft] Server stopped

**Comment by KingLemming** [comment]
Good job. You installed the wrong version of the mod.
