### ISSUE TITLE
[Question] CoFH Core WorldGen parametrs - Geode

### ISSUE THREAD

**Issue by Tsyklop** [CoFH/Feedback#904]
I do like this:
`    "Iron": {`
        `"enabled": true,`
        `"template": {"type": "uniform", "generator": "geode"},`
        `"block": [{"name": "iron_ore", "metadata": 0}],`
        `"crust": [{"name": "stone", "metadata": 0}],`
        `"minHeight": 0,`
        `"maxHeight": 60,`
        `"clusterSize": 10,`
        `"numClusters": 40,`
        `"hollow": false,`
        `"filler": null,`
        `"retrogen": "false",`
        `"biomeRestriction": "none",`
        `"biomes": [],`
        `"dimensionRestriction": "blacklist",`
        `"dimensions": [`
         `   -1,`
          `  1`
        `]`
    `}`
but the creation of the world - crash. what's wrong?

Please create examples of all types and all generators.

**Comment by KingLemming** [comment]
IRC is for questions. This is not.
