### ISSUE TITLE
Dynamics - Crash on serverstart

### ISSUE THREAD

**Issue by Komoden** [CoFH/Feedback#905]
List of mods installed: http://ibkicraft.dk/index.php/mod-liste/

Just checked.. running Java 8, and latest versions of all CoFH mods...
The error log: http://pastebin.com/4p6D2qaR

It doesn't look like it's related to anything but Thermal Dynamics as far as i can see?
This started happening this morning after the nightly restart of our server...

Edit:
After finding an old backup that worked it seems that the issue might be fluiduct related..
This backup we could start and get ingame and it would crash after a few minutes... so ran around removing random pipes that we thought might be causing the issue... The crashes stopped happening when we removed Hardened Fluiduct that we had piping lava into Smelteries (Tinker's Construct).
Could this be caused by the small amounts of lava that smelteries use at a time?

Edit 2: nvm the Smeltery suspicion.... it just crashed again.... further investigation needed :S

Edit 3:
Think i found the issue now... piping items into an Item Router from Immersive Engineering...
This block only has 1 inventory slot, but Dynamics attempts to insert multiple items... is this a Dynamics bug, or an IE bug? (the stack trace is purely Dynamics, so i'm not sure, and your code is not viewable anywhere, so can't check myself)
PS: a vanilla Hopper works fine inputting into this block....

**Comment by KingLemming** [comment]
The block may only has 1 inventory slot, but it's clearly claiming to have 4. Report it to IE. This is possible when the Sided code is slightly off. The hopper does things in a very odd way and shouldn't be used as a benchmark in any way.

We'll look into it though.

**Comment by Komoden** [comment]
The block only has 1 inventory slot, so i'll report this to IE

**Comment by BluSunrize** [comment]
Question: Why does TD use that simulated inventory in the first place? I'm using slotnumbers to store which side was input from (I can easily fix this by upping inv size, obviously), but I'd still love to know what that simulated Inventory is even for.

**Comment by KingLemming** [comment]
The simulated inventory is used for overflow prevention. It does in fact rely on things conforming to vanilla standards. But frankly, everything should.

Good to know it's fixed though.
