### ISSUE TITLE
Thaumcraft & thermal expansion texture bug

### ISSUE THREAD

**Issue by gravestristen** [CoFH/Feedback#906]
Ive been trying to get these two to work together for the past few days but every try ends up with something like this:
![screen shot 2015-11-01 at 10 40 28 am](https://cloud.githubusercontent.com/assets/7584667/10869709/1f95c8d6-8085-11e5-8c72-e0a7cc2e8654.png)
![screen shot 2015-11-01 at 10 40 46 am](https://cloud.githubusercontent.com/assets/7584667/10869710/24e5dc9a-8085-11e5-8799-15785d1f6db8.png)

**Comment by KingLemming** [comment]
Remote Fastcraft and FPSPlus. Does it still happen?

**Comment by gravestristen** [comment]
I added those in in an attempt to fix the texture glitch but yes it still happens without them, removing disrupts a new set of files:
![screen shot 2015-11-01 at 5 43 23 pm](https://cloud.githubusercontent.com/assets/7584667/10871815/5cbe5652-80c0-11e5-82ca-8f7483060767.png)
![screen shot 2015-11-01 at 5 43 29 pm](https://cloud.githubusercontent.com/assets/7584667/10871818/7feef546-80c0-11e5-915a-4f528113085f.png)
![screen shot 2015-11-01 at 5 43 57 pm](https://cloud.githubusercontent.com/assets/7584667/10871819/8569690c-80c0-11e5-8aca-282ca2e9f354.png)
![screen shot 2015-11-01 at 5 44 17 pm](https://cloud.githubusercontent.com/assets/7584667/10871820/8ad13adc-80c0-11e5-90cf-d75d9b7762d3.png)
![screen shot 2015-11-01 at 5 44 22 pm](https://cloud.githubusercontent.com/assets/7584667/10871822/91039bc0-80c0-11e5-8c9e-b553c563cde8.png)
![screen shot 2015-11-01 at 5 44 30 pm](https://cloud.githubusercontent.com/assets/7584667/10871824/977b9bce-80c0-11e5-8927-819726657657.png)
![screen shot 2015-11-01 at 5 45 05 pm](https://cloud.githubusercontent.com/assets/7584667/10871826/ab9a21f2-80c0-11e5-8bf9-97402c53a555.png)

And a log in case you need it: http://pastebin.com/hRTLseur

**Comment by KingLemming** [comment]
Okay so I should have mentioned it earlier but your mods are WAY out of date. Please correct that first.

**Comment by gravestristen** [comment]
Alright ill do that and get back to you but i thought i had downloaded the recommended versions for 1.7.10

**Comment by KingLemming** [comment]
No, you're months out of date. The startup log shows that. :(

**Comment by gravestristen** [comment]
here you go i downloaded the most recent uploads from curse:
![screen shot 2015-11-02 at 12 26 09 pm](https://cloud.githubusercontent.com/assets/7584667/10888971/1c089ec2-815d-11e5-8186-ff7e10f938b6.png)
![screen shot 2015-11-02 at 12 25 54 pm](https://cloud.githubusercontent.com/assets/7584667/10888975/1c2282ce-815d-11e5-813d-f2cdfdbc5083.png)
![screen shot 2015-11-02 at 12 25 48 pm](https://cloud.githubusercontent.com/assets/7584667/10888973/1c1974ae-815d-11e5-9b85-a3865cd17eea.png)
![screen shot 2015-11-02 at 12 25 46 pm 2](https://cloud.githubusercontent.com/assets/7584667/10888978/1c293f10-815d-11e5-8954-402ec937300b.png)
![screen shot 2015-11-02 at 12 25 46 pm](https://cloud.githubusercontent.com/assets/7584667/10888974/1c1bf8dc-815d-11e5-9119-29960a50efab.png)
![screen shot 2015-11-02 at 12 25 41 pm](https://cloud.githubusercontent.com/assets/7584667/10888981/1c587d52-815d-11e5-9170-1852eeb846d9.png)
![screen shot 2015-11-02 at 12 25 27 pm](https://cloud.githubusercontent.com/assets/7584667/10888972/1c16bdea-815d-11e5-8cbc-692212532757.png)
![screen shot 2015-11-02 at 12 25 10 pm](https://cloud.githubusercontent.com/assets/7584667/10888976/1c274002-815d-11e5-9f2c-cd96ff48f004.png)
![screen shot 2015-11-02 at 12 25 07 pm](https://cloud.githubusercontent.com/assets/7584667/10888977/1c2943e8-815d-11e5-9b59-120c4c0ee657.png)
![screen shot 2015-11-02 at 12 25 04 pm](https://cloud.githubusercontent.com/assets/7584667/10888979/1c2f1d9a-815d-11e5-880e-d092f22b2290.png)
![screen shot 2015-11-02 at 12 24 58 pm](https://cloud.githubusercontent.com/assets/7584667/10888980/1c30d39c-815d-11e5-9c0c-4faf14d01ca8.png)

**Comment by KingLemming** [comment]
I'm afraid I don't know what to tell you. Nobody else sees this and we certainly don't either. :/

**Comment by gravestristen** [comment]
I've tried 10 different versions of minecraft forge 1.7.10 and tried it on ftb launcher minecraft launcher at launcher and technic launcher and i always get the same results

**Comment by gravestristen** [comment]
but when i use other peoples modpacks like magic farm 2 or etho's lp pack the textures are completely fine

**Comment by gravestristen** [comment]
Im going to try to lay a texture pack over it and see what happens

**Comment by gravestristen** [comment]
overlaying a texture pack loads the texture pack files correctly, could the default files have gotten corrupted somehow?:
![screen shot 2015-11-02 at 1 02 33 pm](https://cloud.githubusercontent.com/assets/7584667/10889838/53d86ada-8162-11e5-8415-a07bd8e5edd2.png)

**Comment by KingLemming** [comment]
The files aren't corrupted, or everyone would see this. It's unique to your computer. Maybe check Thaumcraft, but if a texture pack is working, then I'd advise you use that.

**Comment by gravestristen** [comment]
I would check thaumcraft but they closed the thaumcraft 4 github and replaced it with thaumcraft 5 github

**Comment by KingLemming** [comment]
Guess you'll have to use a texture pack then, sorry. No idea what it is, but literally nobody else experiences this. It's unique to your hardware.

**Comment by skyboy** [comment]
It's entirely possible your assets cache in .minecraft is corrupted, you could delete it and let it redownload

**Comment by gravestristen** [comment]
Alright heres another strange pice of information for you guys, the textures broke again when i loaded mc with the texture pack but the default textures were completely fine when i turned it off and when i turned my texture pack back on they were 100% fine i think something is happening during the loading process maybe forge isn't loading right or stitching them right?

**Comment by XFactHD** [comment]
Right after you loaded up MC and opened your world, try pressing F3 + T and see if this also fixes it.

**Comment by gravestristen** [comment]
what does that reload?

**Comment by XFactHD** [comment]
F3 + T reloads the textures, F3 + S reloads the sounds, F3 + R reloads the sounds and the textures.
