### ISSUE TITLE
Compatibility with Inventory Tweaks

### ISSUE THREAD

**Issue by pinter-gabor-at** [CoFH/Feedback#907]
**Minecraft Version: 1.12.2**
**Inventory Tweaks Version: 1.63+release.109.220f184 or 1.64-dev+release.110.b4fac73**
**Thermal Expansion Version: 5.3.10.14**
It does not sort items in Satchels. No buttons, no shortcut keys, no support.
![inventory tweeks - satchel](https://user-images.githubusercontent.com/6544011/35849130-d5d75a92-0b20-11e8-8189-d3efdbec1936.jpg)

**Comment by PanSzelescik** [comment]
https://github.com/CoFH/ThermalExpansion/commit/96934ae9405c1b676ea259dafa2908fa9c2ef6de
Inventory Tweaks support is removed

**Comment by KingLemming** [comment]
Intentional. Inventory tweaks has something not compatible. Unsure what exactly but it causes crashes.
