### ISSUE TITLE
Disabling Satchels does not disable all variants of Satchels

### ISSUE THREAD

**Issue by pinter-gabor-at** [CoFH/Feedback#908]
I wanted to disable Satchels, because they are not compatible with Inventory Tweaks. I wanted to test other Backpack mods. I found that Improved Backpacks is compatible with Inventory Tweaks and has very similar funtionality and difficulty as Satchels.
I modified the config file ...\config\cofh\thermalexpansion\common.cfg
```
    Satchel {
        B:Enable=false
    }
```
After this the recipe for Basic Satchel is disabled, as I wanted it. But existing Satchels remained in the world (which is a small bug), and the recipies for all higher tier Satchels were still enabled. They are not craftable, of course, because they all based on the Basic Satchel, but they all appear in JEI.
![satchels](https://user-images.githubusercontent.com/6544011/35851567-af805e18-0b28-11e8-84c5-8e925b2744d8.jpg)

**Comment by KingLemming** [comment]
Working as restricted by Mojang. Welcome to the era of json recipes.
