### ISSUE TITLE
Crash on World join (RedNetCable+Tesseract=Crash?)

### ISSUE THREAD

**Issue by Haxxeris** [CoFH/Feedback#909]
So i was playing around with ThaumCraft while my automatic Ex-Nihlio x Buildcraft machine which gets me unlimited ores. It gets its energy from 2 Tesseracts. When i searched for materials the game suddenly crashed.

Description: Exception in server tick loop

java.lang.RuntimeException: Crashing on conduit TileEntityRedNetEnergy(x=-365,y=195,z=255)@797496580
	at powercrystals.minefactoryreloaded.net.GridTickHandler.tickEnd(GridTickHandler.java:160)
	at powercrystals.minefactoryreloaded.net.GridTickHandler.tick(GridTickHandler.java:77)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_346_GridTickHandler_tick_ServerTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:247)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:590)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: net.minecraft.util.ReportedException: Exception while updating neighbours
	at net.minecraft.world.World.func_147460_e(World.java:730)
	at powercrystals.minefactoryreloaded.core.MFRUtil.notifyNearbyBlocksExcept(MFRUtil.java:314)
	at powercrystals.minefactoryreloaded.tile.rednet.RedstoneNetwork.notifySingleNode(RedstoneNetwork.java:499)
	at powercrystals.minefactoryreloaded.tile.rednet.RedstoneNetwork.addOrUpdateNode(RedstoneNetwork.java:356)
	at powercrystals.minefactoryreloaded.tile.rednet.TileEntityRedNetCable.updateNearbyNode(TileEntityRedNetCable.java:233)
	at powercrystals.minefactoryreloaded.tile.rednet.TileEntityRedNetCable.updateNearbyNode(TileEntityRedNetCable.java:216)
	at powercrystals.minefactoryreloaded.tile.rednet.TileEntityRedNetCable.updateNearbyNode(TileEntityRedNetCable.java:209)
	at powercrystals.minefactoryreloaded.tile.rednet.TileEntityRedNetCable.updateInternalTypes(TileEntityRedNetCable.java:192)
	at powercrystals.minefactoryreloaded.tile.rednet.TileEntityRedNetEnergy.updateInternalTypes(TileEntityRedNetEnergy.java:534)
	at powercrystals.minefactoryreloaded.tile.rednet.TileEntityRedNetCable.firstTick(TileEntityRedNetCable.java:147)
	at powercrystals.minefactoryreloaded.tile.rednet.TileEntityRedNetEnergy.firstTick(TileEntityRedNetEnergy.java:115)
	at powercrystals.minefactoryreloaded.net.GridTickHandler.tickEnd(GridTickHandler.java:156)
	... 9 more
Caused by: java.lang.ClassCastException: cofh.thermalexpansion.block.ender.TileTesseract cannot be cast to flaxbeard.thaumicexploration.tile.TileEntityBoundChest
	at flaxbeard.thaumicexploration.block.BlockBoundChest.func_149695_a(BlockBoundChest.java:175)
	at net.minecraft.world.World.func_147460_e(World.java:697)
	... 20 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 502391008 bytes (479 MB) / 1344376832 bytes (1282 MB) up to 4281597952 bytes (4083 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 96
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1456 Optifine OptiFine_1.7.10_HD_C1 112 mods loaded, 112 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAAAAAAAAAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAAAAAAAAAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1456-1.7.10.jar) 
	UCHIJAAAAAAAAAAAAAA	Forge{10.13.4.1456} [Minecraft Forge] (forge-1.7.10-10.13.4.1456-1.7.10.jar) 
	UCHIJAAAAAAAAAAAAAA	appliedenergistics2-core{rv2-stable-10} [AppliedEnergistics2 Core] (minecraft.jar) 
	UCHIJAAAAAAAAAAAAAA	Aroma1997Core{1.0.2.14} [Aroma1997Core] (Aroma1997Core-1.7.10-1.0.2.14.jar) 
	UCHIJAAAAAAAAAAAAAA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAAAAAAAAAAAA	NotEnoughItems{1.0.5.111} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.111-universal.jar) 
	UCHIJAAAAAAAAAAAAAA	SomniaCore{1.3.1.1} [SomniaCore] (minecraft.jar) 
	UCHIJAAAAAAAAAAAAAA	ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core] (minecraft.jar) 
	UCHIJAAAAAAAAAAAAAA	VeinMiner_coremod{0.27.1_build.unknown} [Core mod] (minecraft.jar) 
	UCHIJAAAAAAAAAAAAAA	OpenModsCore{0.8} [OpenModsCore] (minecraft.jar) 
	UCHIJAAAAAAAAAAAAAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJAAAAAAAAAAAAAA	enhancermod{1.8.6} [Vanilla Enhancer Mod] ([1.7.10] Vanilla Enhancer Mod v1.8.6.jar) 
	UCHIJAAAAAAAAAAAAAA	CraftableAnimals{2.4.3.0} [Craftable Animals] ([1.7.10]CraftableAnimals v2.4.3.0.jar) 
	UCHIJAAAAAAAAAAAAAA	bspkrsCore{6.15} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.15.jar) 
	UCHIJAAAAAAAAAAAAAA	CrystalWing{1.7.10.r02} [CrystalWing] ([1.7.10]CrystalWing-universal-1.7.10.r02.jar) 
	UCHIJAAAAAAAAAAAAAA	appliedenergistics2{rv2-stable-10} [Applied Energistics 2] (appliedenergistics2-rv2-stable-10.jar) 
	UCHIJAAAAAAAAAAAAAA	Aroma1997CoreHelper{1.0.2.14} [Aroma1997Core|Helper] (Aroma1997Core-1.7.10-1.0.2.14.jar) 
	UCHIJAAAAAAAAAAAAAA	CoFHCore{1.7.10R3.0.3} [CoFH Core] (CoFHCore-[1.7.10]3.0.3-303.jar) 
	UCHIJAAAAAAAAAAAAAA	MineFactoryReloaded{1.7.10R2.8.0} [MineFactory Reloaded] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAAAAAAAAAAAA	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UCHIJAAAAAAAAAAAAAA	Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar) 
	UCHIJAAAAAAAAAAAAAA	MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.0} [MFR Compat: Thaumcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAAAAAAAAAAAA	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCHIJAAAAAAAAAAAAAA	Automagy{0.24.1} [Automagy] (Automagy-1.7.10-0.24.1.jar) 
	UCHIJAAAAAAAAAAAAAA	BetterChests{1.1.1.9} [BetterChests] (BetterChests-1.7.10-1.1.1.9.jar) 
	UCHIJAAAAAAAAAAAAAA	ThermalFoundation{1.7.10R1.2.0} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.2.0-102.jar) 
	UCHIJAAAAAAAAAAAAAA	ThermalExpansion{1.7.10R4.0.3B1} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.0.3B1-218.jar) 
	UCHIJAAAAAAAAAAAAAA	BigReactors{0.4.1A2} [Big Reactors] (BigReactors-0.4.1A2.jar) 
	UCHIJAAAAAAAAAAAAAA	BuildCraft|Core{7.0.22} [BuildCraft] (buildcraft-7.0.22.jar) 
	UCHIJAAAAAAAAAAAAAA	BuildCraft|Silicon{7.0.22} [BC Silicon] (buildcraft-7.0.22.jar) 
	UCHIJAAAAAAAAAAAAAA	BuildCraft|Transport{7.0.22} [BC Transport] (buildcraft-7.0.22.jar) 
	UCHIJAAAAAAAAAAAAAA	BuildCraft|Builders{7.0.22} [BC Builders] (buildcraft-7.0.22.jar) 
	UCHIJAAAAAAAAAAAAAA	BuildCraft|Robotics{7.0.22} [BC Robotics] (buildcraft-7.0.22.jar) 
	UCHIJAAAAAAAAAAAAAA	BuildCraft|Energy{7.0.22} [BC Energy] (buildcraft-7.0.22.jar) 
	UCHIJAAAAAAAAAAAAAA	BuildCraft|Factory{7.0.22} [BC Factory] (buildcraft-7.0.22.jar) 
	UCHIJAAAAAAAAAAAAAA	CarpentersBlocks{3.3.5} [Carpenter's Blocks] (Carpenter's Blocks v3.3.5 - MC 1.7.10.jar) 
	UCHIJAAAAAAAAAAAAAA	ChickenChunks{1.3.4.19} [ChickenChunks] (ChickenChunks-1.7.10-1.3.4.19-universal.jar) 
	UCHIJAAAAAAAAAAAAAA	chisel{2.5.1.44} [Chisel 2] (Chisel2-2.5.1.44.jar) 
	UCHIJAAAAAAAAAAAAAA	craft++{1.0} [Craft++] (Craft++-1.0.jar) 
	UCHIJAAAAAAAAAAAAAA	Ding{MC1.7.10} [Ding] (Ding-Mod-1.7.10.jar) 
	UCHIJAAAAAAAAAAAAAA	dualhotbar{1.6} [Dual Hotbar] (dualhotbar-1.7.10-1.6.jar) 
	UCHIJAAAAAAAAAAAAAA	eplus{1.7.10-3.0.1} [Enchanting Plus] (EnchantingPlus-1.7.10-3.0.1.jar) 
	UCHIJAAAAAAAAAAAAAA	EnderIO{1.7.10-2.2.7.326} [Ender IO] (EnderIO-1.7.10-2.2.7.326.jar) 
	UCHIJAAAAAAAAAAAAAA	exnihilo{1.38-48} [Ex Nihilo] (Ex-Nihilo-1.38-48.jar) 
	UCHIJAAAAAAAAAAAAAA	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) 
	UCHIJAAAAAAAAAAAAAA	TConstruct{1.7.10-1.8.5.build957} [Tinkers' Construct] (TConstruct-1.7.10-1.8.5.jar) 
	UCHIJAAAAAAAAAAAAAA	exastris{MC1.7.10-1.16-36} [Ex Astris] (Ex-Astris-MC1.7.10-1.16-36.jar) 
	UCHIJAAAAAAAAAAAAAA	ExtraUtilities{1.2.10} [Extra Utilities] (extrautilities-1.2.10.jar) 
	UCHIJAAAAAAAAAAAAAA	FastCraft{1.21} [FastCraft] (fastcraft-1.21.jar) 
	UCHIJAAAAAAAAAAAAAA	iChunUtil{4.1.0} [iChunUtil] (iChunUtil-4.1.0.jar) 
	UCHIJAAAAAAAAAAAAAA	ImmibisCore{59.1.2} [Immibis Core] (immibis-core-59.1.2.jar) 
	UCHIJAAAAAAAAAAAAAA	infiniteinvo{1.0.44} [InfiniteInvo] (InfiniteInvo-1.0.44.jar) 
	UCHIJAAAAAAAAAAAAAA	LunatriusCore{1.1.2.21} [LunatriusCore] (LunatriusCore-1.7.10-1.1.2.21-universal.jar) 
	UCHIJAAAAAAAAAAAAAA	InGameInfoXML{2.8.1.67} [InGame Info XML] (InGameInfoXML-1.7.10-2.8.1.67-universal.jar) 
	UCHIJAAAAAAAAAAAAAA	InGameInfoXML|simplyjetpacksIntegration{2.8.1.67} [InGame Info XML - Simply Jetpacks Integration] (InGameInfoXML-1.7.10-2.8.1.67-universal.jar) 
	UCHIJAAAAAAAAAAAAAA	InGameInfoXML|ThaumcraftIntegration{2.8.1.67} [InGame Info XML - Thaumcraft Integration] (InGameInfoXML-1.7.10-2.8.1.67-universal.jar) 
	UCHIJAAAAAAAAAAAAAA	instantblocks{1.5.4} [Instant Blocks] (InstantBlocks_v1.5.4.jar) 
	UCHIJAAAAAAAAAAAAAA	JABBA{1.2.1} [JABBA] (Jabba-1.2.1a_1.7.10.jar) 
	UCHIJAAAAAAAAAAAAAA	lootbags{1.4.1a} [Loot Bags] (LootBags-1.7.10-1.4.1a.jar) 
	UCHIJAAAAAAAAAAAAAA	magicalcrops{4.0.0_BETA_13a} [Magical Crops] (magicalcrops-4.0.0_BETA_13a.jar) 
	UCHIJAAAAAAAAAAAAAA	mfrmagiccropscompat{1.1} [MinefactoryReloaded & MagicalCrops extra compatibility] (minefactory-magicalcrops-compatibility-1.1.jar) 
	UCHIJAAAAAAAAAAAAAA	MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.0} [MFR Compat: Applied Energistics] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAAAAAAAAAAAA	MineFactoryReloaded|CompatAtum{1.7.10R2.8.0} [MFR Compat: Atum] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAAAAAAAAAAAA	MineFactoryReloaded|CompatBackTools{1.7.10R2.8.0} [MFR Compat: BackTools] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAAAAAAAAAAAA	MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.0} [MFR Compat: BuildCraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAAAAAAAAAAAA	MineFactoryReloaded|CompatChococraft{1.7.10R2.8.0} [MFR Compat: Chococraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAAAAAAAAAAAA	MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.0} [MFR Compat: ExtraBiomes] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAAAAAAAAAAAA	MineFactoryReloaded|CompatForestry{1.7.10R2.8.0} [MFR Compat: Forestry] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAAAAAAAAAAAA	MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.0} [MFR Compat: ForgeMicroblock] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAAAAAAAAAAAA	MineFactoryReloaded|CompatIC2{1.7.10R2.8.0} [MFR Compat: IC2] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAAAAAAAAAAAA	MineFactoryReloaded|CompatMystcraft{1.7.10R2.8.0} [MFR Compat: Mystcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAAAAAAAAAAAA	MineFactoryReloaded|CompatProjRed{1.7.10R2.8.0} [MFR Compat ProjectRed] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAAAAAAAAAAAA	MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.0} [MFR Compat: Railcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAAAAAAAAAAAA	MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.0} [MFR Compat: Sufficient Biomes] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAAAAAAAAAAAA	MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.0} [MFR Compat: Thermal Expansion] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAAAAAAAAAAAA	MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.0} [MFR Compat: Tinkers' Construct] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAAAAAAAAAAAA	MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.0} [MFR Compat: TwilightForest] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAAAAAAAAAAAA	MineFactoryReloaded|CompatVanilla{1.7.10R2.8.0} [MFR Compat: Vanilla] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAAAAAAAAAAAA	numina{0.4.0.100} [Numina] (Numina-Mod-1.7.10.jar) 
	UCHIJAAAAAAAAAAAAAA	powersuits{0.11.0.176} [MachineMuse's Modular Powersuits] (Modular-Powersuits-Mod-1.7.10.jar) 
	UCHIJAAAAAAAAAAAAAA	me{1.3.2.1} [More Enchantments] (MoreEnchantments-1.7.10-1.3.2.1.jar) 
	UCHIJAAAAAAAAAAAAAA	AencEx{0.0.1} [AencEx] (MoreEnchantments-1.7.10-1.3.2.1.jar) 
	UCHIJAAAAAAAAAAAAAA	NEIAddons{1.12.3.11} [NEI Addons] (neiaddons-mc1710-1.12.3.11.jar) 
	UCHIJAAAAAAAAAAAAAA	NEIAddons|Botany{1.12.3.11} [NEI Addons: Botany] (neiaddons-mc1710-1.12.3.11.jar) 
	UCHIJAAAAAAAAAAAAAA	NEIAddons|Forestry{1.12.3.11} [NEI Addons: Forestry] (neiaddons-mc1710-1.12.3.11.jar) 
	UCHIJAAAAAAAAAAAAAA	NEIAddons|CraftingTables{1.12.3.11} [NEI Addons: Crafting Tables] (neiaddons-mc1710-1.12.3.11.jar) 
	UCHIJAAAAAAAAAAAAAA	NEIAddons|ExNihilo{1.12.3.11} [NEI Addons: Ex Nihilo] (neiaddons-mc1710-1.12.3.11.jar) 
	UCHIJAAAAAAAAAAAAAA	neiintegration{1.0.1} [NEI Integration] (NEIIntegration-MC1.7.10-1.0.1.jar) 
	UCHIJAAAAAAAAAAAAAA	OpenMods{0.8} [OpenMods] (OpenModsLib-1.7.10-0.8.jar) 
	UCHIJAAAAAAAAAAAAAA	OpenBlocks{1.4.4} [OpenBlocks] (OpenBlocks-1.7.10-1.4.4.jar) 
	UCHIJAAAAAAAAAAAAAA	harvestcraft{1.7.10g} [Pam's HarvestCraft] (Pam's HarvestCraft 1.7.10h.jar) 
	UCHIJAAAAAAAAAAAAAA	mobdropcrops{1.7.2a} [Pam's Mob Drop Crops] (Pam's Mob Drop Crops 1.7.2b.zip) 
	UCHIJAAAAAAAAAAAAAA	Scenter{1.7.10-3.2.1} [Scenter] (scenter-1.7.10-3.2.1.jar.zip) 
	UCHIJAAAAAAAAAAAAAA	SmartCursor{1.1.6} [SmartCursor] (SmartCursor-1.1.6_1.7.10.jar) 
	UCHIJAAAAAAAAAAAAAA	SolarFlux{1.7.10-0.4c} [Solar Flux] (SolarFlux-1.7.10-0.4c.jar) 
	UCHIJAAAAAAAAAAAAAA	examplemod{1.0} [examplemod] (Somnia-1.4.3.1.jar) 
	UCHIJAAAAAAAAAAAAAA	Somnia{-au} [Somnia] (Somnia-1.4.3.1.jar) 
	UCHIJAAAAAAAAAAAAAA	ThaumicTinkerer{unspecified} [Thaumic Tinkerer] (ThaumicTinkerer-2.5-1.7.10-471.jar) 
	UCHIJAAAAAAAAAAAAAA	TaintedMagic{1.1.5.7} [Tainted Magic] (TaintedMagic-1.1.5.7.jar) 
	UCHIJAAAAAAAAAAAAAA	telepads{1.6.4 v5} [Teleportation Pads] (TelePads-Mod-1.7.10.jar) 
	UCHIJAAAAAAAAAAAAAA	thaumcraftneiplugin{1.7.10-1.7} [Thaumcraft NEI Plugin] (thaumcraftneiplugin-1.7.10-1.7.jar) 
	UCHIJAAAAAAAAAAAAAA	thaumicenergistics{0.8.10.10} [Thaumic Energistics] (thaumicenergistics-0.8.10.10.jar) 
	UCHIJAAAAAAAAAAAAAA	ThaumicExploration{0.6.0} [Thaumic Exploration] (ThaumicExploration-1.7.10-1.1-53.jar) 
	UCHIJAAAAAAAAAAAAAA	ThaumicHorizons{1.1.5} [Thaumic Horizons] (thaumichorizons-1.7.10-1.1.6.jar) 
	UCHIJAAAAAAAAAAAAAA	TwoGraves{1710.1.0} [Graves] (TwoGraves-Mod-1.7.10.jar) 
	UCHIJAAAAAAAAAAAAAA	jordy141minecraftmagicwrench{0.5 Alpha} [Magic Wrench] (Uncrafting-Table-Mod-1.7.10.jar) 
	UCHIJAAAAAAAAAAAAAA	uncraftingTable{1.7.10 Alpha 1} [Uncrafting Table] (Uncrafting-Table-Mod-1.7.10.jar) 
	UCHIJAAAAAAAAAAAAAA	VeinMiner{0.27.1_build.unknown} [Vein Miner] (VeinMiner-1.7.10_0.27.1.unknown.jar) 
	UCHIJAAAAAAAAAAAAAA	VeinMinerModSupport{0.27.1_build.unknown} [Mod Support] (VeinMiner-1.7.10_0.27.1.unknown.jar) 
	UCHIJAAAAAAAAAAAAAA	wawla{1.3.1} [What Are We Looking At] (Wawla-1.3.1-1.7.10.jar) 
	UCHIJAAAAAAAAAAAAAA	IguanaTweaksTConstruct{1.7.10-2.1.5.140} [Iguana Tinker Tweaks] (IguanaTinkerTweaks-1.7.10-2.1.5.jar) 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	OpenModsLib class transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[map_gen_fix:FINISHED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
	Class transformer null safety: all safe
	AE2 Version: stable rv2-stable-10 for Forge 10.13.2.1291
	CoFHCore: -[1.7.10]3.0.3-303
	MineFactoryReloaded: -[1.7.10]2.8.0-104
	ThermalFoundation: -[1.7.10]1.2.0-102
	ThermalExpansion: -[1.7.10]4.0.3B1-218
	Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: optifine
	TConstruct Environment: Environment healthy.
	Stencil buffer state: Function set: GL30, pool: forge, bits: 8
	AE2 Integration: IC2:OFF, RotaryCraft:OFF, RC:OFF, BC:ON, RF:ON, RFItem:ON, MFR:ON, DSU:ON, FZ:OFF, FMP:OFF, RB:OFF, CLApi:OFF, Waila:ON, InvTweaks:OFF, NEI:ON, CraftGuide:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 8; [EntityPlayerMP['Haxxeris'/171884, l='Recover', x=-393,50, y=69,01, z=309,50]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

This is the crash log.

I also found this here: https://github.com/CoFH/Feedback/issues/455#issuecomment-95206831

**Comment by skyboy** [comment]
```
Caused by: java.lang.ClassCastException: cofh.thermalexpansion.block.ender.TileTesseract cannot be cast to flaxbeard.thaumicexploration.tile.TileEntityBoundChest
```

Your world appears to have been corrupted in some fashion. Rednet interacting with the world just happens to be finding this corruption.
