### ISSUE TITLE
Fluiducts, Tanks and some other stuff are producing chunk updates

### ISSUE THREAD

**Issue by roboderpy** [CoFH/Feedback#909]
And thus, triggering chunk model recompute (the 16x16x16 model), producing massive lags if chunk contains *a lot* fluiducts and/or TE tanks or complex models from other mods (example - Chiesel & Bits or LittleTiles; Garden Cloche, ...).

For example, Mekanism and BuildCraft (on older versions) are not producing chunk updates (and not causing any chunk model recompution) when content of it's pipes or tank changes.

**Comment by covers1624** [comment]
Yes they do, because their models need to change. Fluiducts, sure, those will be changed in TD3, machines however will not, Tanks, its a possibility but super low priority and would likely happen after TD3.

**Comment by KingLemming** [comment]
Right. This is a design choice rather than using TESRs. It's something we may revisit if it actually proves to be a problem. Our testing has not shown it to be so.
