### ISSUE TITLE
Thermal foundation crash

### ISSUE THREAD

**Issue by FrostySigh** [CoFH/Feedback#91]
Well, I have tried to only use the CoFH mods and it is causing this crash everytime I use the latest 2 versions of Thermal Foundation.

http://pastebin.com/22sLceKs

Any idea why?

**Comment by KingLemming** [comment]
Yup. You didn't actually read the readme. CurseForge is full of alphas. They are going to crash you.

**Comment by bochen415** [comment]
@KingLemming Maybe a fake 'I downloaded from CurseForge and it crashes' issue left open with a READ THIS label?

**Comment by FrostySigh** [comment]
I didn't see a readme on the curseforge site, and yes I know it can crash because it is a alpha, but all of the earlier ones worked, so I thought maybe this one would aswell, evedntly not... Reverting to 1.0.0RC1-35 since that one works...
