### ISSUE TITLE
[Thermal Expansion] Machinist's Workbench crash

### ISSUE THREAD

**Issue by Techtronik** [CoFH/Feedback#911]
Thermal Expansion 1.7.10 v4.0.3B1-218
Mods: http://pastebin.com/YuWYEAGU
Crash Log:
http://pastebin.com/e82Sn5Xz (in the end)
http://pastebin.com/ubFDc0LW (in the overworld, if theres a difference)

I crash when i try to interact with the Machinist's Workbench. Right-clicking the block seems to cause an overload and crashes me to the launcher after a few seconds. Left-clicking and/or breaking the block yield no abnormal reactions.

**Comment by KingLemming** [comment]
Try an instance with ONLY CoFH mods. I'm betting it won't crash. The error as reported in the log has nothing to do with our mods.

The crashlog suggests that something is ASMing in a way that it shouldn't be, or you are using dev mods in an environment where you should not be. (InventoryTweaks maybe?)

**Comment by Techtronik** [comment]
it does work properly with just cofh mods but adding inventory tweaks didn't seem to allow the same crash. no clues in the crash report saying which mod it might be? also what is "asming"?

**Comment by Techtronik** [comment]
removed all the mods i added and it still crashed so it must be one or more of the mods included in the modpack

**Comment by KingLemming** [comment]
Yep. It's a mod, but it's not one of ours, sorry.

ASM is basically when a mod hacks a basic function of the game or otherwise alters core code. In your crash log, we're looking for a function that is no longer there (it's a core game function), but another mod has removed it.
