### ISSUE TITLE
[Suggestion] [Thermal Cultivation] Liquid Phyto-Gro

### ISSUE THREAD

**Issue by Saklad5** [CoFH/Feedback#912]
Immersive Engineering seems to have added the potential for fluid-based Fertilizers in the Garden Cloche, but I don’t know of any mods that add such a thing. Liquid Phyto-Gro could be an interesting addition, and not just for that cross-mod interaction.

It could be used in Watering Cans as an even more powerful aid to plant growth, or used in the Decoctive Diffuser as a sort of sprinkler to the same effect.

It could also be used as the basis of a Specialization in the Phytogenic Insolator: you’d no longer have to supply water or Phyto-Gro, but it would require liquid Phyto-Gro to operate.

As for how it would be produced, there are plenty of possibilities: Fluid Transposer (possibly into Water), Magma Crucible, perhaps even playing off the potion mechanic as an alternative source. I’m a big fan of interesting automation options like the Sap-based Rich Phyto-Gro recipe, and this could open up more possibilities like that.

**Comment by KingLemming** [comment]
This has been suggested before, but there are a couple of pretty big problems with it.

As it stands this would require basically full rewrites to the Insolator and Watering Cans. Both of them are fast enough and operate in a reasonable enough manner, and this doesn't seem to really add any gameplay depth.

So I'm sorry, but this won't be happening.

**Comment by CTH999** [comment]
Maybe, but what about not in cans, just the diffuser and garden clouch! I think that would be nice.
