### ISSUE TITLE
[Suggestion] [Thermal Expansion] Add ability to convert Essence of Knowledge into XP Orbs using Decoctive Diffuser

### ISSUE THREAD

**Issue by Saklad5** [CoFH/Feedback#913]
Fluid-based experience is notoriously unstandardized across mods, and that means it is often necessary to somehow convert one liquid to the other. This often means converting back to XP Orbs as a medium of exchange, but the Thermal mods don’t have any way of doing this beyond making Bottles o’ Enchanting, which are terribly random and inefficient.

I feel it would be very fitting to allow the Decoctive Diffuser to produce XP Orbs in this manner. As is, it is probably one of the least useful machines in Thermal Expansion, so it could benefit from a few interesting features like this.

**Comment by KingLemming** [comment]
The inefficiency is intended, otherwise it results in a free xp loop as you could just condense/diffuse forever and the catalyst bonus would increase the overall xp received.

So I'm sorry, but this won't be happening.

**Comment by Saklad5** [comment]
As an alternative solution to the XP conversion issue, could you add configurable fluid support to the Lexical Transmuter? I realize I should probably open another issue for this, but that feels like spamming considering the issue would read almost identically.

**Comment by Saklad5** [comment]
Also, I’d actually be fine with a wildly inefficient Decoctive Diffuser mechanic. Essence of Knowledge is practically infinite with a single mob farm; my main concern is having to automate Glass Bottles, dispensing Bottles o’ Enchanting, etcetera.

**Comment by CTH999** [comment]
Also, you would get infinite xp, but wouldn't it be at the cost of items? Some where, you need something. The items are being used.

**Comment by Saklad5** [comment]
I rarely need Essence, and if I can automate the production of an item from nothing, I effectively have an infinite amount of that item.

**Comment by CTH999** [comment]
good point, but the thermal series+ maybe DE wouldn't. But, I see your pint. Maybe a way to transfer it into that book thing? And then transfer it back from the book into the machine?

**Comment by Saklad5** [comment]
You can currently transfer Industrial Foregoing Essence into the Tome of Knowledge, but that’s not reversible. And I can’t think of any reasonable way to automate the conversion if it was.

Ideally, Forge would adopt a universal XP standard like they did for Forge Energy. This is exactly the sort of nonsense that everyone used to deal with before Redstone Flux was adopted everywhere.

**Comment by CTH999** [comment]
Ok, what about a fluid lexicon? Just a suggestion! Or, a visa-versa thing! Just an idea.
