### ISSUE TITLE
Question: How does the Alchemical Imbuer register recipes?

### ISSUE THREAD

**Issue by Akitori** [CoFH/Feedback#915]
I'm curious how it registers recipes, due to using Extra Alchemy (a different mod) to add in recipes via json. 

Main reason i ask is to verify if its possible to add recipes to the alchemical imbuer. 
![2018-02-10_15 09 56](https://user-images.githubusercontent.com/24502131/36066811-78b582b8-0e76-11e8-970e-a83d3cf7eefa.png)

As you see here i added the recipe easily, it works, but it didn't add a alchemical imbuer variant. Idk, perhaps this is just me barking at the shadows or something.

**Comment by KingLemming** [comment]
Recipes are manually added right now. Just the way vanilla works, it's trivial to add a recipe but it's a tremendous annoyance to read from the list due to how they store it.

Also, please use Discord for questions. This isn't a forum.
