### ISSUE TITLE
Add config option to disable Thermal Expansion machine lighting

### ISSUE THREAD

**Issue by briman0094** [CoFH/Feedback#916]
I'm running a pack based on Direwolf20, which means I have all CoFH mods as well as Environmental Tech. I am currently processing my Environmental Tech ore intake using TE machines, and I needed to set up a large amount of machines to handle the speed at which my T5 miner pulls in resources (and to handle when I upgrade it to T6).

I have 32 pulverizers and 32 furnaces set up in one chunk, which seems to be causing a huge amount of client lag due to lighting updates. If I pull the AE2 devices offline which are feeding the machines, I get about 200 frames/sec in this chunk. When I restore the AE2 devices so that the machines start processing resources again, my FPS drops to about 20 because machines are turning on and off so fast. Each machine that turns on/off triggers a lighting update (behavior seen in TileMachineBase.java).

I am proposing a config option for Thermal Expansion to disable machine lighting. The machines would still change textures to indicate being active or inactive, but a machine activating would not produce light. I believe this would need to be a common config option, as lighting is calculated on both the server and client.

**Comment by briman0094** [comment]
Note that I'm not 100% certain that the lag is solely from lighting updates, as it could also simply be from the blocks updating their textures (I don't recall if machines use TESRs or not).

**Comment by KingLemming** [comment]
So a given machine will only ever do a client update (this includes texture and lights) every 8 seconds, no matter how quickly they turn on/off. So I'm highly skeptical that your diagnosis is correct.

I'm still willing to entertain the config option, but I question how necessary it actually is.

**Comment by briman0094** [comment]
I'm aware they only update every few seconds, but is that tracked per machine or is it global (e.g. `worldTicks % 160 == 0`)? If only a couple machines are processing, I register somewhere between 150 and 200 FPS, but if I for instance set the servos feeding into the machines to Round Robin instead of Nearest First, the FPS drops to around 20 because machines start turning on and off rapidly (the input servo leads to 32 machines for both pulverizer processing and furnace processing).

**Comment by briman0094** [comment]
I just went to observe how the updates are handled and it is indeed tracked per-machine. I set one servo (half the machines) to Round Robin and this is the result: https://puu.sh/zlx95.mp4

The 8-second delay seems to be tracked by each machine individually. If you look at the animated glowstone texture ore the Astral Sorcery light particle to the right, you can see the stuttering when a lot of machines are activating or deactivating.

I suppose an alternate fix would be for the machines to all update on the same 8-second interval, using the ticks % 160 method I listed above, so that there's only one massive lighting update at most every 8 seconds. This would drastically reduce the lag when there are copious amounts of machines in a small space.

I can write a PR for this if that's an acceptable solution and preferred over the config file setting

**Comment by KingLemming** [comment]
I really don't think it's the lighting calc. I think it's simply the redraw call, so the only real "option" would be to just...not have different textures for active/inactive and that feels wrong.

**Comment by briman0094** [comment]
Well, the same optimization would hold true to just have them all update on the same 8-second interval instead of tracking that interval per-machine from whatever reference point it has (whenever the block was placed?)

Perhaps even both; track them all globally, and have a config option to disable visual state changes?

**Comment by KingLemming** [comment]
The interval is from when the machine is no longer active.

Honestly, a quick/easy fix for you is just to reduce the number of machines you have. That will seriously help.

**Comment by briman0094** [comment]
The problem is that I actually need this many machines to handle the rate at which resources come in from my T5 and T6 ore miner. They mine every type of ore registered in the game, and I'm getting one of each every few seconds. If EnderIO were updated I'd use that for mass-processing and use TE for my crafting recipes but it doesn't seem like EIO will be ready soon.

I suppose I could potentially use a compact machine, but I've never used them before so I'm not sure if it would work. I can do some local tests and see if synchronizing all machine updates to the same tick would help...

**Comment by KingLemming** [comment]
>If EnderIO were updated I'd use that for mass-processing and use TE for my crafting recipes but it doesn't seem like EIO will be ready soon.

Gee thanks.

Seriously though, the fact that you have machines turning on and off in such a fashion means that you do NOT actually need that many. An optimal setup would manage to keep a smaller amount of machines going constantly.
