### ISSUE TITLE
Alchemical Imbuer Input Fluid Tank accessible through Output

### ISSUE THREAD

**Issue by Xirema** [CoFH/Feedback#917]
My steps to reproduce are to set up an Alchemical Imbuer with Input (blue) on the left, Output (Orange) on the right, and have auto-output turned off. Then, I put a Fluiduct on the output side and add a basic servo to extract fluid, and turn the servo on. Then, any liquid I pump into the Alchemical Imbuer, regardless of its type, gets pulled out of the input tank into the fluiduct.

I get the sense that this might have been intentional: offering a way to pull potion fluid out of the Imbuer if the wrong type was accidentally pumped in. But I feel like there should be a better mechanism to handle that situation, since I'm fond of using redstone to customize my Potion Brewing pipeline (redstone on→pass to next imbuer, redstone off→pass to fluid transposer to put in bottles), and as it is right now, the only way to make sure I don't accidentally pull the intended potion fluid out of my Imbuer is to blacklist/whitelist the servos, which gets tedious and difficult to maintain.

**Comment by KingLemming** [comment]
This actually was intentional, yes, but I can see why it's annoying. Unfortunately, adjusting this behavior is a slightly larger rewrite than you may be thinking.

I'll look into it, but technically it's working as intended.

**Comment by KingLemming** [comment]
Messed with this in dev a bit. :)
