### ISSUE TITLE
Basic Pulverizer to Max tier recipe not working

### ISSUE THREAD

**Issue by MrDrummer** [CoFH/Feedback#917]
NEI indicates that you can upgrade the pulverizer from basic tier to enderium tier by crafting with the enderium gear, 4 silver and the pulverizer. This does not work in both a modded crafting table and a regular table.

Screenshot of the pulverizers in question:
http://img.ctrlv.in/img/15/11/07/563e44fd198ad.png

Overall recipe:
http://img.ctrlv.in/img/15/11/07/563e45477d981.png

NEI:
http://img.ctrlv.in/img/15/11/07/563e457eb2965.png

In NEI, the pulverizer is basic, and the result is resonant. When i look under recipes for the enderium pulverizer, it does not say this is a recipe. So i am not sure if it is an intended recipe or not.

EDIT: It seems to not work for furnaces either. Have not tried any other machines.

**Comment by KingLemming** [comment]
Are you actually looking at the machine on the left? It should require a Reinforced. Rather, it DOES, and the recipe properly shows this.

If it's not showing that for you, please update your mods. I just tested in a 1.7.10 release and it does work properly.

**Comment by MrDrummer** [comment]
Yes i did read. It says that the basic machine can be upgraded via NEI.

To replicate the issue you press the uses key on the basic machine, and on the second sub-page for upgrade crafting, it shows the standard resonant machine recipe, but the basic machine in the center.

Recipe shown with the basic machine in the middle:
http://img.ctrlv.in/img/15/11/08/563f307c30bde.png

Extra info:
I updated a few days ago, i shall try this again when i have a better internet speed.

**Comment by KingLemming** [comment]
Ah. That'd be an NEI bug then.
