### ISSUE TITLE
can't empty reservoir in drums from extra utilities 2 

### ISSUE THREAD

**Issue by Bircko** [CoFH/Feedback#918]
the reservoir isn't working on drums it just empty one bucket and when i want to empty the next bucket it just takes the bucket out that it justed filled in the drum

**Comment by KingLemming** [comment]
Yep. That behavior needs to be handled on ExU2's end.

**Comment by Bircko** [comment]
why it should be extra utilities fault i could also be a mistake on your mod

**Comment by KingLemming** [comment]
It's not.
