### ISSUE TITLE
[CoFHTweaks] java.lang.IllegalAccessError: tried to access field net.minecraft.world.World.collidingBoundingBoxes from class cofh.tweak.asmhooks.HooksCore

### ISSUE THREAD

**Issue by OreCruncher** [CoFH/Feedback#918]
CoFHTweaks-[1.7.10]1.0.1-37-dev.jar

Dropped the dev jar into my Eclipse environment and tried debugging my mod.  Got the following exception `java.lang.IllegalAccessError: tried to access field net.minecraft.world.World.collidingBoundingBoxes from class cofh.tweak.asmhooks.HooksCore`.

I have encountered similar issues to this with my transformed classes when I tried replacing Minecraft classes *entirely* with implementations from my packages.  It was not possible to refer to classes in my package from those transformed classes - something to with different class loaders.  *Shrugs* I am not an expert with this, so I could be totally wrong.

EDIT:  Forgot to add this bit.  Forge 1448; only mods I have are mine and CoFHTweaks.  My mod doesn't touch anything with rendering or code that Tweaks modifies.

**Comment by skyboy** [comment]
Should be fixed with 1.0.1-38-dev.

**Comment by OreCruncher** [comment]
Confirmed, thanks!  With my mod this is the fastest I have ever seen Minecraft load.
