### ISSUE TITLE
Viaducts not registering destination w/LRV inserted

### ISSUE THREAD

**Issue by Lethann** [CoFH/Feedback#919]
Running FTB Revelations 1.4 w/thermal dynamics 2.3.10.4 (manually updated)

Ok, if I use regular Viaducts it works fine. Toss down some and use the wrench on the ends, label them and use them as intended.

Tried tossing some Long Range Viaducts in the middle, using the Linking ones to get it all connected. Go to the ends and open them up fine. Go into the config and can give them names, but they don't register the other destinations. I've even chunk loaded the areas and it all looks connected fine. Not sure if I"m doing something wrong or not.

**Comment by KingLemming** [comment]
I haven't seen this in any testing (nor has this been reported) and there are just a lot of variables. It's almost definitely something on your end.

Please come by the Discord channel and see if anyone has ideas. This is basically tech support, which isn't the purpose of the issue tracker.

**Comment by Lethann** [comment]
Where is the link to the discord? All I'm seeing is a reference to an IRC channel.
