### ISSUE TITLE
Replace vanilla oregen is not respecting dimensional blacklists

### ISSUE THREAD

**Issue by Saereth** [CoFH/Feedback#92]
CoFHCore-1.10.2-4.1.0.155-universal.jar

Im using the replace vanilla oregen option, using the standard vanilla ore file with a few y level tweaks. Ores, dirt, andesite, diorite etc are generating in the end.

vanilla.json file: https://hastebin.com/hafaxeyexi.json

Image of issue: http://imgur.com/a/Fx8zi

The issue is not present in the nether however, only the end

**Comment by KingLemming** [comment]
I've tried multiple times and I cannot make this happen under any circumstances. We're going to need more info.

**Comment by Saereth** [comment]
np I'll do some thorough testing with just cofh mods and add things back in until I can pin something down, thanks for looking into this!

**Comment by Saereth** [comment]
ok Did some testing and got it pinned down to the nether metals mod, it now adds MMD orespawn as a dependency and with mmd orespawn (even everything removed from its configs generation wise) along side cofh core it causes this issue to happen.

Downgrading nethermetals to a version not reliant on mmd orespawn and removing mmd orespawn resolves this issue so I will report it to them.

**Comment by knoxhack** [comment]
I'll probably add a config to disable OreSpawn requirements so you can use other world gen mods with Nether Metals.
