### ISSUE TITLE
[Thermal Foundation] Sulfur Config Option

### ISSUE THREAD

**Issue by mamgar** [CoFH/Feedback#920]
As far as i can tell Thermal Foundation is the mod that makes lava immune mobs drop sulfur. This is all fine and well. But i really would like to have the ability to disable this feature. as far as i could tell there isn't any way to disable this feature.

**Comment by KingLemming** [comment]
You would be incorrect. Thermal Foundation does not do this.

**Comment by mamgar** [comment]
http://teamcofh.com/docs/thermal-foundation/materials/sulfur/ 
It says right on the webdoc that sulfur drops from lava immune mobs. You can load a world with only Thermal Foundation and CoFH Core and Blazes will drop sulfur.
Is this functionality added by COFHcore?

**Comment by KingLemming** [comment]
You didn't say Blazes. You said "lava-immune," which would include Magma Cubes.

And yes, that is added for consistency with the other elementals. No, there's no config.

**Comment by KingLemming** [comment]
I was misinformed. @skyboy sabotaged me. I'll add a config.

**Comment by mamgar** [comment]
Thanks!
