### ISSUE TITLE
Reservoir will try to fill empty buckets, voiding fluid

### ISSUE THREAD

**Issue by superfluke** [CoFH/Feedback#920]
It seems like reservoirs will attempt to fill buckets in the players inventory. This results in the fluid being voided. This can be replicated by filling a reservoir with water then repeatedly collecting/placing water with a bucket, losing 1b of fluid from the reservoir each time the bucket is emptied. 
https://gfycat.com/PitifulChubbyGraywolf

ThermalExpansion-1.12.2-5.3.10.15-universal
CoFHCore-1.12.2-4.3.10.5-universal
Forge 14.23.1.2604

**Comment by KingLemming** [comment]
Duplicate of #842. The bug is with the bucket.

**Comment by superfluke** [comment]
Looking at the forge github, I'm not seeing any related issues open. I'd try and open one myself, but I doubt I know enough about what's going on with the code to provide a helpful report.
