### ISSUE TITLE
bug occured in 1.7.10 4.1.5-248

### ISSUE THREAD

**Issue by Cobracrystal** [CoFH/Feedback#921]
Played with a bunch of Mods Singleplayer 1.7.10; no Modpack. Placing an Autonomous Activator on Top of  a Draconic Chest, facing it, as soon as it started clicking aka got Energy, caused minecraft to crash instantly. Restarting just caused another crash as soon as the world loaded in. Placing it at the side didnt cause a crash. If you want a crash report, just tell me. I fixed it eventually just through mcedit.
Draconic Evolution version: 1.0.2h
Thermal Expansion version: 4.1.5-248
cofhcore version 3.1.4-329

**Comment by KingLemming** [comment]
1.7.10 is no longer supported.
