### ISSUE TITLE
Adding removal methods for  Precipitator & Extruder 

### ISSUE THREAD

**Issue by superfluke** [CoFH/Feedback#922]
Looks like you've added the ability to add new recipes to the  Precipitator & Extruder, but the Mod Tweaker dev wants to hold off on implementing them until the removal function is also possible. Any chance you could add these methods?

https://github.com/jaredlll08/ModTweaker/issues/576

**Comment by KingLemming** [comment]
I already saw that as I was tagged in it. There wasn't a need to open this. ;)

I'm a bit on the fence due to certain functionality reworking, so it's a tentative "yes, when I'm reasonable able to."
