### ISSUE TITLE
Cannot Appear to set "size-variance" to 0 in CoFH World for Stalactite / Stalagmite generators

### ISSUE THREAD

**Issue by damnsquidpeople** [CoFH/Feedback#923]
I've been making a very customized mod pack and currently I've been using the cave / surface generators in combination with the stalactite / stalagmite types, however the biggest issue I'm having is despite trying everything and reading the documentation, I cannot make them have a base width of 1. My goal is to make 1 block wide "nerd pole" structures full of ore, but I don't appear to be able to in the current versions. Not sure if an oversight or intentional, but I figured I'd report it here.

I do have gen-size set to 1, as well as size-variance at 0, and I've tried one as well, with no difference in results. I've also tried setting fat to false, nothing seems to make any difference in the results on my end.

**Comment by KingLemming** [comment]
To my knowledge, this is intended and "nerd poles" aren't a thing the generation allows for, sorry.

World is getting a rewrite at some point though, so we'll look into it then.

**Comment by damnsquidpeople** [comment]
Alright sweet! It's nice to hear that since World has come the closest to what I want to do, but I'm going to have to compromise and settle until then. It's good to hear it will get looked at though
