### ISSUE TITLE
Witchery "Mog's Quiver" and Flux-Infused Bow bug

### ISSUE THREAD

**Issue by PokeMaserJ** [CoFH/Feedback#924]
When wearing a "Mog's Quiver" from Witchery, the Flux-Infused Bow if charged up to the minimum to shoot, it takes no RF to shoot. So once you have 200 RF in the bow, if wearing the Quiver, you can shoot infinite amount of times.

**Comment by KingLemming** [comment]
Just reading up on the quiver, that seems to be 100% intended on the part of Witchery.

https://sites.google.com/site/witcherymod/mogs-quiver
