### ISSUE TITLE
Cache Rendering Contents Far Infront of Cache

### ISSUE THREAD

**Issue by ElvenChaos** [CoFH/Feedback#924]
When items are in caches, they are rendered not-quite half a block infront of the cache instead of on the cache's face. See Image below.

<details/>
  <summary>Image Spoiler</summary>

![2018-02-15_18 41 51](https://user-images.githubusercontent.com/8423636/36288437-345e3da4-1280-11e8-90d0-39e1d22a8239.png)
</details>
<br>

MC 1.12.2
CoFHCore-1.12.2-4.3.10.5-universal
ThermalFoundation-1.12.2-2.3.10.6-universal
ThermalExpansion-1.12.2-5.3.10.15-universal
Forge 2611

**Comment by KingLemming** [comment]
Nope. This is something in your settings. You have a mod interfering somewhere.
