### ISSUE TITLE
Thermal Dynamics Pipes Suggestions (2)

### ISSUE THREAD

**Issue by mysticdreamer76** [CoFH/Feedback#925]
Hello, 

1) Would you consider the ability to have multiple (different) pipes in the same space? Kind of like EnderIO? So we can have 1 energy, 1 item, and 1 fluid pipe all connect to one side of a block? 
example: https://ftb.gamepedia.com/Item_Conduit

This is a lot more aesthetically pleasing, and efficient than trying to fit multiple pipes on multiple sides of things. (Especially since you can only have 1 servo attached to a single pipe) Why can't they be used as multi-directional pipes? In and out of the same side?

2) Would you consider an upgrade for priority, so we can prioritize specifically which input/output goes 1st, 2nd, 3rd etc? I thought there was something, but I can't seem to find it in the mod. This would just makes it easier to control the flow of things.

Thank you for your consideration.

**Comment by KingLemming** [comment]
1) No, I'm sorry. What EnderIO does is bad for server TPS as well as player agency. Logistical triviality is not a good thing for gameplay.

2) We're probably going to add vacuum and dense itemducts back, but specific priority upgrades? No, sorry.

Thermal Dynamics is intended to be simple and intuitive as well as server-friendly. I'm aware that there are many things we could add to make it far more "powerful" but the core purposes would be harmed in the process.
