### ISSUE TITLE
Feature Request- Fundamental design issue causing players to get creative items.

### ISSUE THREAD

**Issue by ProsperCraft** [CoFH/Feedback#926]
It seems that creative is the default for all items, such as satchels, energy cells, and such.

This was a problem in 1.7 because players could break a block in a way that it removed its extended information, which gave them the default which was creative.

Fast forward to 1.12.2 and I am seeing the same issue.

Can you please give creative items their own item id - name so it's not possible to trick the server into giving them the creative item?

I suppose this might have to wait until 1.13 which is fine.

**Comment by KingLemming** [comment]
This isn't the case in 1.12, no. The "default" or metadata 0 version is the Basic version.

I know of absolutely no way in 1.12 to trick the server into providing a Creative version of any item.

**Comment by ProsperCraft** [comment]
The impossible happened - 

![creativecapacitor](https://user-images.githubusercontent.com/4427684/37420465-7a201c98-277c-11e8-9c5f-43e25684e174.png)

When a player was mining randomite that gives random items, it has a blacklist which we have added 14k items to, but this slipped through.

Here is our blacklist.
[general.zip](https://github.com/CoFH/Feedback/files/1812296/general.zip)

I currently have a request in to the dev to make it a whitelist instead of a blacklist.

**Comment by ProsperCraft** [comment]
Blacklist aside, the server should never drop a creative capacitor, which speaks to the design issue I brought up.

**Comment by covers1624** [comment]
What? You are complaining about a design issue in OUR mod because ANOTHER decides tondrop a creative capacitor? No that's not how this works. It's the OTHER mods fault for not having the infestructure in place to whitelist instead of blacklist, it is the OTHER mods fault for not supporting nbt sensitive blacklist. This is absolutely not an issue with TE.

**Comment by covers1624** [comment]
Furthermore, you believe TE has any sort of controll here, that is invalid, the only way to obtain creative anything in TE is through creative mode. Again it is IMPOSSIBLE to obtain creative items from TE unless another mod is doing it, as lemming stated before.
