### ISSUE TITLE
sawmill

### ISSUE THREAD

**Issue by Flashwar** [CoFH/Feedback#928]
Thermal Expansion 5.3.10.15

When using the Nullification Chamber Augment, the secondary output, in this case sawdust, will not get destroyed. 
![2018-02-16_09 28 44](https://user-images.githubusercontent.com/13320784/36299230-65eaad54-12fc-11e8-8d0b-8b2302e864bb.png)

**Comment by KingLemming** [comment]
Yeah, you didn't read the augment fully. *Excess* outputs. It'll still fill up the slot.
