### ISSUE TITLE
Setting frequency on tesseract crashes my game

### ISSUE THREAD

**Issue by Borre91** [CoFH/Feedback#929]
Hi

So i made two tesseracts. After i put one of them down and try to change the frequency it just closes my game immediately. This happens every time i try to do that. Even if i dont have the tesseract connected to anything. 

I am using FTB Lite 3. 

Heres the error log my FTB Launcher Consol is linking to: http://pastebin.com/ytrs26Ew
Heres what the FTB Launcher Console says: http://pastebin.com/XhuuzGuP

I have tried to google it but cant find any answers. 

If you need any more information please tell me and i will provide it.

**Comment by KingLemming** [comment]
Looks like you're playing on a potato.

Go through your config files and disable shaders. Also try and enable the alternate Tesseract graphic.

**Comment by Borre91** [comment]
I know my computer is a potato. It sucks. 

But thank you for your time. Changing the alternate Tesseract graphic worked. Didnt know i could do that. 

Thanks again!

**Comment by S0LD13Rjo** [comment]
How do u change the tesseract graphics

**Comment by Caasin** [comment]
Im With s0ld13. Idk anything about config files and crap.

**Comment by Caasin** [comment]
I found out how, but when i changed the texture to true, it still crashed. I use no shaders and my computer is a sun-burned computer. here is the report. --- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 28/03/16 8:27 PM
Description: Unexpected error

java.lang.NoClassDefFoundError: com/mumfrey/liteloader/core/event/EventProxy$2
	at net.minecraft.world.chunk.Chunk.func_76607_a(Chunk.java:1280)
	at net.minecraft.client.network.NetHandlerPlayClient.func_147269_a(NetHandlerPlayClient.java:1194)
	at net.minecraft.network.play.server.S26PacketMapChunkBulk.func_148833_a(S26PacketMapChunkBulk.java:184)
	at net.minecraft.network.play.server.S26PacketMapChunkBulk.func_148833_a(S26PacketMapChunkBulk.java:242)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2061)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: com.mumfrey.liteloader.core.event.EventProxy$2
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 15 more
Caused by: java.lang.ArrayIndexOutOfBoundsException


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.world.chunk.Chunk.func_76607_a(Chunk.java:1280)
	at net.minecraft.client.network.NetHandlerPlayClient.func_147269_a(NetHandlerPlayClient.java:1194)
	at net.minecraft.network.play.server.S26PacketMapChunkBulk.func_148833_a(S26PacketMapChunkBulk.java:184)
	at net.minecraft.network.play.server.S26PacketMapChunkBulk.func_148833_a(S26PacketMapChunkBulk.java:242)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['manmanguy98806'/236, l='MpServer', x=-136.50, y=63.62, z=263.50]]
	Chunk stats: MultiplayerChunkCache: 1, 1
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-136,64,256), Chunk: (at 8,4,0 in -9,16; contains blocks -144,0,256 to -129,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 2 game time, 2 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 1 total; [EntityClientPlayerMP['manmanguy98806'/236, l='MpServer', x=-136.50, y=63.62, z=263.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:927)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2825220304 bytes (2694 MB) / 3207856128 bytes (3059 MB) up to 3207856128 bytes (3059 MB)
	Mod Pack: Unknown / None
	LiteLoader Mods: 1 loaded mod(s)
          - VoxelMap version 1.5.20
	LaunchWrapper: 46 active transformer(s)
          - Transformer: cpw.mods.fml.common.asm.transformers.PatchingTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.MarkerTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.SideTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.EventSubscriptionTransformer
          - Transformer: net.minecraftforge.classloading.FluidIdTransformer
          - Transformer: appeng.transformer.asm.ASMIntegration
          - Transformer: com.github.parker8283.bif.Transformer
          - Transformer: codechicken.lib.asm.ClassHeirachyManager
          - Transformer: codechicken.core.asm.InterfaceDependancyTransformer
          - Transformer: codechicken.core.asm.TweakTransformer
          - Transformer: codechicken.core.asm.DelegatedTransformer
          - Transformer: codechicken.core.asm.DefaultImplementationTransformer
          - Transformer: invtweaks.forge.asm.ContainerTransformer
          - Transformer: codechicken.nei.asm.NEITransformer
          - Transformer: com.mumfrey.liteloader.launch.LiteLoaderTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.CrashReportTransformer
          - Transformer: me.guichaguri.betterfps.transformers.MathTransformer
          - Transformer: me.guichaguri.betterfps.transformers.EventTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.DeobfuscationTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.AccessTransformer
          - Transformer: net.minecraftforge.transformers.ForgeAccessTransformer
          - Transformer: appeng.transformer.asm.ASMTweaker
          - Transformer: codechicken.core.asm.CodeChickenAccessTransformer
          - Transformer: cofh.asm.CoFHAccessTransformer
          - Transformer: invtweaks.forge.asm.ITAccessTransformer
          - Transformer: net.malisis.core.asm.MalisisCoreAccessTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ModAccessTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ItemStackTransformer
          - Transformer: cofh.asm.CoFHClassTransformer
          - Transformer: com.olafski.fastleafdecay.FldTransformer
          - Transformer: net.malisis.core.util.chunkcollision.ChunkCollisionTransformer
          - Transformer: net.malisis.core.util.chunkblock.ChunkBlockTransformer
          - Transformer: com.enderio.core.common.transform.EnderCoreTransformer
          - Transformer: com.enderio.core.common.transform.EnderCoreTransformerClient
          - Transformer: cpw.mods.fml.common.asm.transformers.TerminalTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.JoinGamePacketTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.ServerChatPacketTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.LiteLoaderEventInjectionTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.LiteLoaderCallbackInjectionTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.MinecraftOverlayTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.LoginSuccessPacketTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.CustomPayloadPacketTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.ServerCustomPayloadPacketTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.ChatPacketTransformer
          - Transformer: com.thevoxelbox.voxelmap.litemod.VoxelMapTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ModAPITransformer
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M -Xmx3G -Xms3G
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 15, tallocated: 95
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 53 mods loaded, 53 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	appliedenergistics2-core{rv2-stable-10} [AppliedEnergistics2 Core] (minecraft.jar) 
	UCHIJAAAA	bowinfinityfix{rv0} [Bow Infinity Fix] (minecraft.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.5.118} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.118-universal.jar) 
	UCHIJAAAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJAAAA	FLabsBF{4.3} [Better Furnaces] ([1.7.10]Better_Furnaces_V4.3.jar) 
	UCHIJAAAA	animatedplayer{1.5.1} [Animated Player Mod] (AnimatedPlayer-1.7.10-1.5.1.jar) 
	UCHIJAAAA	AnimationAPI{1.2.4} [AnimationAPI] (AnimationAPI-1.7.10-1.2.4.jar) 
	UCHIJAAAA	appliedenergistics2{rv2-stable-10} [Applied Energistics 2] (appliedenergistics2-rv2-stable-10.jar) 
	UCHIJAAAA	Backpack{2.0.1} [Backpack] (Backpacks-Mod.jar) 
	UCHIJAAAA	CoFHCore{1.7.10R3.1.2} [CoFH Core] (CoFHCore-[1.7.10]3.1.2-325.jar) 
	UCHIJAAAA	ThermalFoundation{1.7.10R1.2.3} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.2.3-112.jar) 
	UCHIJAAAA	ThermalExpansion{1.7.10R4.0.3B1} [Thermal Expansion] (Thermal-Expansion-Mod-1.7.10(1).jar) 
	UCHIJAAAA	BigReactors{0.4.3A} [Big Reactors] (BigReactors-0.4.3A.jar) 
	UCHIJAAAA	BuildCraft|Core{6.1.8} [BuildCraft] (buildcraft-6.1.8.jar) 
	UCHIJAAAA	BuildCraft|Builders{6.1.8} [BC Builders] (buildcraft-6.1.8.jar) 
	UCHIJAAAA	BuildCraft|Energy{6.1.8} [BC Energy] (buildcraft-6.1.8.jar) 
	UCHIJAAAA	BuildCraft|Factory{6.1.8} [BC Factory] (buildcraft-6.1.8.jar) 
	UCHIJAAAA	BuildCraft|Transport{6.1.8} [BC Transport] (buildcraft-6.1.8.jar) 
	UCHIJAAAA	BuildCraft|Silicon{6.1.8} [BC Silicon] (buildcraft-6.1.8.jar) 
	UCHIJAAAA	chameleoncreepers{1.2} [Chameleon Creepers] (Chameleon-Creepers-Mod-1.7.10.jar) 
	UCHIJAAAA	ChickenChunks{1.3.4.13} [ChickenChunks] (ChickenChunks-Mod-1.7.10.jar) 
	UCHIJAAAA	chocolateQuest{1.0} [Chocolate Quest] (chocolateQuest-1.7.10-1.0.jar) 
	UCHIJAAAA	cosmeticarmorreworked{1.7.10-v5b} [CosmeticArmorReworked] (Cosmetic-Armor-Reworked-Mod-1.7.10.jar) 
	UCHIJAAAA	DamageIndicatorsMod{3.2.0} [Damage Indicators] (Damage-Indicators-Mod-1.7.10.jar) 
	UCHIJAAAA	endercore{1.7.10-0.2.0.31_beta} [EnderCore] (EnderCore-1.7.10-0.2.0.31_beta.jar) 
	UCHIJAAAA	Waila{1.5.10} [Waila] (Waila-Mod-1.7.10.jar) 
	UCHIJAAAA	EnderIO{1.7.10-2.3.0.417_beta} [Ender IO] (EnderIO-1.7.10-2.3.0.417_beta.jar) 
	UCHIJAAAA	EnderStorage{1.4.7.32} [EnderStorage] (EnderStorage-1.7.10-1.4.7.32-universal.jar) 
	UCHIJAAAA	ExtraUtilities{1.1.0k} [Extra Utilities] (Extra-Utilities-Mod-1.7.10(1).jar) 
	UCHIJAAAA	fastleafdecay{1.3} [Fast Leaf Decay] (FastLeafDecay-Mod-1.7.10.jar) 
	UCHIJAAAA	iChunUtil{4.1.3} [iChunUtil] (iChun-Util-Mod-1.7.10.jar) 
	UCHIJAAAA	inventorytweaks{1.58-147-645ca10} [Inventory Tweaks] (Inventory-Tweaks-Mod-1.7.10.jar) 
	UCHIJAAAA	IronChest{6.0.60.741} [Iron Chest] (Iron-Chests-Mod-1.7.10.jar) 
	UCHIJAAAA	malisiscore{1.7.10-0.14.3} [MalisisCore] (malisiscore-1.7.10-0.14.3.jar) 
	UCHIJAAAA	malisisdoors{1.7.10-1.13.1} [Malisis' Doors] (malisisdoors-1.7.10-1.13.1.jar) 
	UCHIJAAAA	Mantle{1.7.10-0.3.2.jenkins191} [Mantle] (Mantle-Mod-1.7.10.jar) 
	UCHIJAAAA	MobDismemberment{4.0.0} [MobDismemberment] (Mob-Dismemberment-Mod-1.7.10.jar) 
	UCHIJAAAA	mobdrops{1.7.10_MD_Beta_1.4} [MobDrops] (MobDrops-Mod-1.7.10.jar) 
	UCHIJAAAA	Morph{0.9.2} [Morph] (Morphing-Mod-1.7.10.jar) 
	UCHIJAAAA	MultiPageChest{1.3.4} [Multi Page Chest] (Multi-Page-Chest-Mod-1.7.10.jar) 
	UCHIJAAAA	ObsidiPlates{3.0.0.18} [ObsidiPlates] (ObsidiPlates-1.7.10-universal-3.0.0.18.jar) 
	UCHIJAAAA	SophisticatedWolves{3.2.0} [SophisticatedWolves] (Sophisticated-Wolves-Mod-1.7.10.jar) 
	UCHIJAAAA	TConstruct{1.7.10-1.8.8.build988} [Tinkers' Construct] (TConstruct-Mod-1.7.10.jar) 
	UCHIJAAAA	telepads{1.6.4 v5} [Teleportation Pads] (TelePads-Mod-1.7.10.jar) 
	UCHIJAAAA	TMechworks{0.2.15.106} [Tinkers' Mechworks] (Tinkers-Mechworks-Mod-1.7.10.jar) 
	UCHIJAAAA	VeinMiner{0.31.1_build.unknown} [Vein Miner] (Vein-Miner-Mod-1.7.10.jar) 
	UCHIJAAAA	VeinMinerModSupport{0.31.1_build.unknown} [Mod Support] (Vein-Miner-Mod-1.7.10.jar) 
	UCHIJAAAA	WailaHarvestability{1.1.6} [Waila Harvestability] (Waila-Harvestability-Mod-1.7.10.jar) 
	UCHIJAAAA	wawla{1.3.3} [What Are We Looking At] (Wawla-1.3.3-1.7.10.jar) 
	AE2 Version: stable rv2-stable-10 for Forge 10.13.2.1291
	CoFHCore: -[1.7.10]3.1.2-325
	ThermalFoundation: -[1.7.10]1.2.3-112
	ThermalExpansion: -[1.7.10]4.0.3B1-218
	Mantle Environment: Environment healthy.
	TConstruct Environment: Environment healthy.
	EnderIO: Found the following problem(s) with your installation: "An unsupportted old RF API is installed (1.7.10R1.0.0 from buildcraft-6.1.8.jar). Ender IO needs at least 1.7.10R1.0.2 and will NOT work with older versions." This may have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
	AE2 Integration: IC2:OFF, RotaryCraft:OFF, RC:OFF, BC:OFF, RF:ON, RFItem:ON, MFR:OFF, DSU:ON, FZ:OFF, FMP:OFF, RB:OFF, CLApi:OFF, Waila:ON, InvTweaks:ON, NEI:ON, CraftGuide:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF
	Launched Version: 1.7.10-Forge10.13.4.1614-1.7.10
	LWJGL: 2.9.1
	OpenGL: AMD Radeon(TM) R4 Graphics GL version 4.5.13399 Compatibility Profile Context 15.200.1060.0, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by S0LD13Rjo** [comment]
Will better graphics work.For eg if i buy a gt730 and install it.Or i need better RAM

**Comment by Caasin** [comment]
Ok thanks, i'm on a potato so i'm definitely working on getting a new
computer
