### ISSUE TITLE
Breaking TE machines with PSI break block function gives free redstone furnace

### ISSUE THREAD

**Issue by JonoColwell** [CoFH/Feedback#93]
Observe, a Magma Crucible
http://i.imgur.com/K6jDzGn.png
Nothing up my sleeves
http://i.imgur.com/oJfDTSh.png
AND PRESTO, Free redstone furnace
http://i.imgur.com/q4zZyQb.png
http://i.imgur.com/HuPNvTw.png

**Comment by KingLemming** [comment]
Cute.

Also 110% on Psi, not us. Please report it to them.

**Comment by Eufranio** [comment]
@KingLemming, that's the code that runs when a player uses the spell. Could you point me to what is wrong? https://github.com/Vazkii/Psi/blob/master/src/main/java/vazkii/psi/common/spell/trick/block/PieceTrickBreakBlock.java
