### ISSUE TITLE
[CoFH Thermal Expansion] Autonomous Activator and Lever

### ISSUE THREAD

**Issue by TsumiHokiro** [CoFH/Feedback#930]
After activating a Lever close to a couple of Autonomous Activator and the world has crashed and won't start again, although the first time that I have tied entering the world back I was successful but not for more than a fraction of a second. I have tried to reproduce the error on a new world by placing levers close to AAs and enabling and disabling them without success.

Here is the log:
http://pastebin.com/GKME0zdy

**Comment by KingLemming** [comment]
Yeah, that's something with your redstone setup. Due to propagation, that's technically on whatever wire is carrying your signal.

**Comment by TsumiHokiro** [comment]
I have tried removing the wires from the mod Ender IO which I was using and I'm still having the same problem.

**Comment by KingLemming** [comment]
I'll need to see a screenshot of your setup.

**Comment by TsumiHokiro** [comment]
Here is the screenshot:
https://imgur.com/a/DGR5N

The offending block is the one right above the lever.
Even re-activating the setup after making it anew has not been able to reproduce the bug. I'm left to wonder what went wrong...

**Comment by KingLemming** [comment]
You sure the activator wasn't using the lever?

**Comment by TsumiHokiro** [comment]
Almost sure, however I have tried putting the activator to activate the lever and still unable to reproduce the bug.

**Comment by KingLemming** [comment]
Thinking about this, it's not an issue with the Activator, but with however you are propagating the signal.

And since you can't make it happen...ehh. Closing this one out.
