### ISSUE TITLE
[Thermal Expansion - Suggestion] Augment allowing machines to relay power

### ISSUE THREAD

**Issue by alphacentauri7** [CoFH/Feedback#932]
An augment making machines basically act as an extensions to your RF network.

Would help in space-constrained situations. For example you could have a setup of directly adjacent machines functioning with the auto-eject and auto-input augments and you would only need to connect power to one of them.

**Comment by KingLemming** [comment]
No, sorry. This is for computational reasons. At some point we may allow an Ender Reception Coil or something as an augment which would allow them to directly receive from a Tesseract network, but that's about as convenient as we can get.

Efficient, conduit-based networks are very complex and we can't just overlay that to machines.
