### ISSUE TITLE
[Enhancement] Copy Paste Function for Lumium Lamps

### ISSUE THREAD

**Issue by mikeloeven** [CoFH/Feedback#933]
Please add a feature to store a lamp configuration in the multimeter and apply the settings with one click Currently configuring a large number of these lamps is a major PITA and it would be nice to configure one and than just paste the settings to the rest of them

**Comment by KingLemming** [comment]
http://teamcofh.com/docs/thermal-expansion/storage/redprint/

**Comment by mikeloeven** [comment]
heh last time i checked the wiki it was under construction >.>

**Comment by KingLemming** [comment]
Fair, although the Redprint has been in for so long that there are probably 3 or 4 wikis with the info. ;) And a few minutes in Creative Mode would have revealed it pretty quickly too. Never discount that.
