### ISSUE TITLE
Lead fishing rod currupting my game

### ISSUE THREAD

**Issue by Sirtain** [CoFH/Feedback#934]
Hey guys, i need help with a problem. I play on the 1.7.10 pack wich include this mod, and i can open the game just fine, but my savefile wont open. I looked up on the log and it says it's caused by the lead fishing rod, but i tried disabling it but the problem is still there... any suggestion? (here the log btw)
[techniclauncher_2015-11-21.log.txt](https://github.com/CoFH/Feedback/files/40925/techniclauncher_2015-11-21.log.txt)

**Comment by skyboy** [comment]
You're using a broken version of forge. Use 1448.
