### ISSUE TITLE
[Request, Mod-Compat] Allow OreDict Inputs in Recipe Registration

### ISSUE THREAD

**Issue by ElvenChaos** [CoFH/Feedback#934]
Thermal Expansion machines should allow mods (mainly ModTweaker) to set recipes with Ore Dictionary or Ingredient inputs, not just Item Stack inputs.

Issue over on ModTweaker: https://github.com/jaredlll08/ModTweaker/issues/604

ThermalExpansion-1.12.2-5.3.10.15-universal
ThermalFoundation-1.12.2-2.3.10.6-universal
CoFHCore-1.12.2-4.3.10.5-universal
modtweaker-4.0.7
CraftTweaker2-1.12-4.1.3
MTLib-3.0.2
MC 1.12.2
Forge 2611

**Comment by KingLemming** [comment]
They automatically convert on the backend, so ehh...

I'll think about it, but there frankly isn't a great need for it.

**Comment by ElvenChaos** [comment]
Thank you for taking this under consideration :D

**Comment by KingLemming** [comment]
Merging this into #1008.
