### ISSUE TITLE
Config Option for Ore Secondary Outputs

### ISSUE THREAD

**Issue by DrakoAlcarus** [CoFH/Feedback#935]
Is it possible you can add an option to increase or decrease the chances of getting a secondary output in any of the machines? I was planning on removing silver from world gen and changing the name of lead to Galena Ore, that will give me lead as a main, and silver as a 75% chance output.

I also have a mod that uses a lot of Iron, so I want to increase the chance of iron from tin ore, as well as decrease the amount of nickel from iron ore.

**Comment by XFactHD** [comment]
I doubt that this config option will be added because it is possible to add and remove recipes from TE machines via IMC (Don't use Minetweaker!!!).

**Comment by DrakoAlcarus** [comment]
Care to elaborate?

**Comment by XFactHD** [comment]
IMC means InterModCommunication. You can send data from mod to mod without creating any dependencies. In this case you would create a mod that sends recipe data via IMC to ThermalExpansion to either add or remove a recipe.

**Comment by DrakoAlcarus** [comment]
I know this. But what is wrong with MineTweaker?

**Comment by XFactHD** [comment]
Using MineTweaker to change TE machine recipes is causing a lot of problems. It either crashes or it doesn't work at all.

**Comment by KingLemming** [comment]
As mentioned, there's IMC that can do this. In 4.1, we'll have jsons as well. But no config options.

**Comment by DrakoAlcarus** [comment]
How would I go about using this mod/feature?

**Comment by XFactHD** [comment]
Do you mean IMC?

**Comment by DrakoAlcarus** [comment]
Yes. I know very little about coding, besides simple strings and functions.

**Comment by XFactHD** [comment]
Take a look at the code of my mod XFactHD/EIORecipesTEInductionSmelter, it uses IMC to register recipes to TE.

**Comment by DrakoAlcarus** [comment]
I may end up creating my own mod. Possibly use what you said and more.

**Comment by XFactHD** [comment]
I could possible do that for you but at the moment I have too much work in school. I won't have time before the 19th December.

**Comment by DrakoAlcarus** [comment]
Honestly, I have been dreaming of making mod, and in fact games, for over three years now. It's time I stop being lazy and learn!

**Comment by XFactHD** [comment]
That's fine with me. If you need help, feel free to take my code as an example or ask me. Little tip: Take a look at CoFHCore, it contains a helper class with methods used to add or remove TE recipes.

**Comment by DrakoAlcarus** [comment]
If I get far enough, I want to make a nuclear mod specified for Thermal expansion, using thermal expansion materials, adding a few TE themed machines, ores, reactors, and reactor control. Basically what IC2 has, but more user friendly. Also, I may add a huge energy bank multi-block and a mass fabricator as well, complete with OreCruncher's Thermal Recycling scrap box compatibility.

**Comment by XFactHD** [comment]
Sounds awesome, can't wait to see what you come up with.

**Comment by DrakoAlcarus** [comment]
Is there any other way to contact you? I have a few mods I want to edit a little to suit my modpack.

I am learning coding, but it's slow.

**Comment by XFactHD** [comment]
If you have an account on curse.com we could chat there, although I always need a computer to do that and I am not at home until next weekend. May I ask what your main language is? Maybe we could also talk over Skype.

**Comment by DrakoAlcarus** [comment]
Yes, I have Curse Voice.

Drako9823 is the name of the account.

**Comment by XFactHD** [comment]
Nice, but you will have to wait until next weekend as there is no Curse Voice for smartphones ☹.

**Comment by DrakoAlcarus** [comment]
We could use Email or Google Hangouts if possible.

**Comment by XFactHD** [comment]
Ok, why not. But I will only have time from 5 to 10 o'clock pm German time. My E-Mail adress is xfacthd@gmx.de.
