### ISSUE TITLE
[Suggestion] Async Servo and Retriever Check

### ISSUE THREAD

**Issue by rojo8399** [CoFH/Feedback#937]
I haven't looked much into the thermal dynamics mod, and I apologize.
I'm having an issue on a low-pop server (10 players) with servos and retrievers. Even with a low amount (10 in the whole dimension) my server lags for two seconds. I've done some profiling and timings checks and it all points to servos.
I don't know if the inventory check is already async or if it's because I'm running with sponge, but having them in the world is causing lots of tps hiccups. 

I7 6700k
12G Ram
Forge 1.12.2 2615
Sponge 1.12.2 2611

**Comment by KingLemming** [comment]
Sorry, but Sponge isn't supported and there's a fair chance that's your problem, as this just isn't a thing that we see with a standard Forge install.
