### ISSUE TITLE
Upgrading dynamo while in progress gives inconsistent output

### ISSUE THREAD

**Issue by adudney** [CoFH/Feedback#939]
1. Place down and connect dynamo and energy cell
2. Place consumable in dynamo
3. Upgrade dynamo to higher tier while in progress
4. Wait until consumable has finished
5. Amount in energy cell is inconsistent, sometimes the intended value and sometimes a small amount higher

In my tests I used Enervation dynamos and Magmatic dynamos and the default config files. Enervation dynamos were given a single piece of Redstone (64kRF), Magmatic dynamos were given one bucket of lava (120kRF).

Enervation outputs:
64040, 64000, 64040, 64040, 64040

Magmatic outputs:
120040, 120040, 120040, 120040, 120080

What this appears to be is an extra tick or two of energy generation at the Basic tier without consuming input.

Minecraft 1.12.2
Forge 14.23.2.2611
Modlist:
CodeChickenLib-1.12.2-3.1.5.331-universal
CoFHCore-1.12.2-4.3.10.5-universal
CoFHWorld-1.12.2-1.1.1.12-universal
jei_1.12.2-4.8.5.147
RedstoneFlux-1.12-2.0.1.2-universal
ThermalDynamics-1.12.2-2.3.10.4-universal
ThermalExpansion-1.12.2-5.3.10.15-universal
ThermalFoundation-1.12.2-2.3.10.6-universal

**Comment by KingLemming** [comment]
This is actually just a general artifact of how fuel processing is done in general. It averages out over time. What happens is that the dynamo will have a negative energy balance and get less total RF from the next unit of fuel.

It's a tradeoff to keep dynamos extremely efficient.
