### ISSUE TITLE
[CoFHCore] Decoration Generation

### ISSUE THREAD

**Issue by SirWilli** [CoFH/Feedback#939]
hey,

is there any way to prevent decoration from generating in liquid?

My config:
```
    "brownGrass": {
        "template": "decoration",
        "generator": "decoration",
        "block": [
            {"name": "ExtrabiomesXL:grass", "weight": 100},
            {"name": "ExtrabiomesXL:grass", "metadata": 1, "weigh": 100},
            {"name": "ExtrabiomesXL:flower1", "metadata": 4, "weigh": 30}
        ],
        "material": [],
        "genSky": "true",
        "genSurface": "ExtrabiomesXL:terrain_blocks1",
        "clusterSize": 8,
        "numClusters": 3,
        "retrogen": "false",
        "biomeRestriction": "none",
        "biomes": [],
        "dimensionRestriction": "whitelist",
        "dimensions": [
            0
        ]
    }
```

**Comment by KingLemming** [comment]
Check the readme. IRC is for questions. This is an issue tracked, not a forum.

**Comment by SirWilli** [comment]
I already asked in the IRC but no one is active there and the only way to get an notification there is with a bouncer.
I opened the the issue page directly without going over the main repo page. You maybe should add a `CONTRIBUTING.md` file and the readme also doesn't say that you don't want to have questions here.

This is maybe also a bug as `genSky` is on true while it generates in the ocean where it has liquid blocks above it but thanks I appreciate your help.
