### ISSUE TITLE
Suggestion- Fluid Lexicon

### ISSUE THREAD

**Issue by CTH999** [CoFH/Feedback#940]
My idea is to simple have a fluid version of the Forge Lexicon. Simple as that. Uses would include [TE's Essence](https://minecraft.curseforge.com/projects/thermalexpansion) to [Industrial Foregoing's Mobs Esence](https://minecraft.curseforge.com/projects/industrial-foregoing?gameCategorySlug=mc-mods&projectID=266515)

It's just a thought though. It's your mod (Last Time I Checked!), and your descision!

**Comment by KingLemming** [comment]
Nope, sorry. That and Steam would literally be the only uses, and frankly I just don't see it being all that necessary nor really a great idea. The only real application would be resource arbitrage/triviality.

**Comment by CTH999** [comment]
Ok, fair enough!

That makes sense!
