### ISSUE TITLE
feature request for servo and retriever (aka give us powered pipe handlers)

### ISSUE THREAD

**Issue by KalaMiDeviL** [CoFH/Feedback#941]
Here's an issue:

I built a network for the item supply and extraction to and from 24 Deep Resonance generator setups. Now, TD can handle that, no questions asked, but it's ridiculously tedious to set up the pipe handlers. I can only use retrievers - obviously, lest I have to bomb the network with filters aside from the servos, so as not to have fresh crystals end up in the dump chests the pedestals unfortunately require.
Since the crystal uses up a single item ID and has no metadata, I have to be very specific in every single retriever UI.

Another issue:

A forestry arboretum requires a lot of items put in and out and recycled all the time. That means, there are a lot of items with different purposes going through a pipe network at the same time. I like to surround the farms with item collector blocks who pick up the drops of bigger oaks, for example, because the farms leave a lot of leaves drops. And here come the pipe handlers. Again, I am able to create a setup that works, but it so annoying, because I can't really force dedicated transport. I can only force-exclude everything else that might happen.
There is always a solution, but the system never progresses.

Side notes:

For a long time, my opinion was that retrievers and servos should require power. But that would make the mod annoying difficult to get into and destroy it's ability to be viable early-game (an aspect I really like).

You probably now about the tunnels in Applied Energetics 2. You can link them with a memory card - pretty neat.

Or have you heard of flux networks? It filled the hole you left in our hearts when you removed tesseracts. It's has a configuration tool that copies and pastes the setting of it's blocks. I love it.

My request:

There's three and a half options in order of most invasive and hard to code to least:

1
Introduce a powered variant for the two main item handlers, where:
    - a linking tool links the powered handler to the other type of handler only (powered servo to
       retrievers and vice-versa) OR
        - it links it to special connector plugins, which then mimic the expected behaviour
           (if you don't want to rewrite servo and retriever)
    - a subnet gets created using the scanned inventories of all linked pipe-plugins
    - the linked handlers can still - but no longer need to - be
       set up specially and also be forced to BECAUSE
        - all the settings of the powered handler can be set to either propagate to the linked
           handlers (if they didn't opt out themselves) or only affect itself
    - the powered handler now extracts or inserts items only inside the subnet
    - an option to ignore filters affecting the subnet exists OR
        - filters can be linked too, and don't bother the subnet otherwise
    - powering it by using it on signalum-plated ducts is an elegant solution
	
2
Introduce a third, powered handler, which:
    - combines the abilities of servo and retriever
	- basically, when powered, it can pull from multiple inventories through pipes AND
           push to multiple inventories trough pipes
	  
2+
You could add:
	- a setting for the access-order of the inventories and a setting for the pull-order from
           the slots AND
        - an option to interlace the loops in round-robin mode
           (for slot loop{for inventory loop} or for inventory loop{for slot loop})
	- the same for the push (making 6 UI buttons for order max)
			
2.5
Keep everything unpowered - no new handler, but:
    - have the servo realise a retriever has been placed in a pipe behind it
       (and vice-versa in front of)
	- have them behave like the thing in option two in that case
	- the retriever grabs items and gives them to the servo
	- the servo distributes the items it gets from the retriever

3
Just give us a config tool, that let's us save the EXACT settings (including filter items
   with meta and NBT) of a handler with a crouch-click and then paste them
   onto another with a click
   You could also add cross-handler compatibility (even with filters).

**Comment by covers1624** [comment]
Soo, The RedPrint is a thing, and can save and load basically any TE machine/device's config and any TD attachment's config..

**Comment by KingLemming** [comment]
Yeah, as covers says, option 3 already exists. So uh...yeah go do that.
