### ISSUE TITLE
[Enhancement][CoFHTweaks] Change ChunkCoordIntPair.chunkXZ2Int calculation

### ISSUE THREAD

**Issue by OreCruncher** [CoFH/Feedback#941]
In my sandbox I changed the calculation to use 3 bytes for each component rather than assuming 4.  When packed the upper two bytes are 0, and the bottom six contain the coordinate components.  The impact is approx 28% improvement in LongHashMap lookups (measured in ChunkIOProvider.provideChunk()) on my system when using CoFHTweaks.

The reason I believe you can get away with using 3 bytes is that the world is bounded at +-30M blocks.  When converted to chunks it can occupy 3 bytes.  Note the coord may need to be offset to ensure positive coords before the bit manipulation (sign extension).

Note that at this level we are talking nanos in improvement. But given that everything under the sun in Minecraft uses the chunkXZ2Int calculation and LongHashMap, and not to mention the high frequency of chunk lookup in ChunkIOProvider, such as  change may be valuable.

Downside to this are:

* Components may use inside knowledge of how the calculation is performed in order to reverse engineer coordinates.  I haven't come across any code thus far that does this, but I can't account for mods.

* Logic could perform their own chunkXZ2Int calculation and use the result with lists made with ChunkCoordIntPair.chunkXZ2Int.  At this point all bets are off since the resulting numbers would be different.

Anyways, thought I would toss this out there for evaluation.

EDIT: Forgot to give the mod list, etc.  Forge 1448, Tweaks 1.0.2B1-41-dev, and my mod (which replaces some core classes related to chunk IO).  No other mods in the environment.

**Comment by skyboy** [comment]
Other mods will definitely be broken by this.

A better solution would be to further improve the hashing function for LongHashMap: I made a change to it that improved performance significantly already (multiplying one 32 bit component by 7), but there are far better ways to mix a long for a hashmap.
