### ISSUE TITLE
Enhancement - support mods which do irresponsible things with enchantments and cause RF durability bar issues.

### ISSUE THREAD

**Issue by PG-Fuury** [CoFH/Feedback#942]
situation: removed the holding 3 from my resonant capacitor, causing it to have RF stored beyond it's limit, thus having the RF bar go beyond the "full" point and extending into the adjacent cell

Theory: Bar is calculated by current RF/max RF, causing weirdness beyond 100%

**Comment by KingLemming** [comment]
Your theory is correct. The issue is that there's really no expectation to support enchantment stripping. I'll consider it.

**Comment by PG-Fuury** [comment]
Well, multiple mods have disenchantment (IF, DE and AA all have such ways), but yes, it's not usually the case

**Comment by KingLemming** [comment]
So on the surface of it, I really dislike this change because it adds some computational overhead to fix what is generally going to be an aesthetic issue.

However, I went ahead and made the adjustments.

**Comment by PG-Fuury** [comment]
I agree that it's an aesthetic issue and it's actually not really that much of an issue, since it's understandable how it comes to be
