### ISSUE TITLE
Missing Mods:    Forge : [10.13.3.1448,10.14)------- Error when starting Cauldron server!

### ISSUE THREAD

**Issue by TheWesternComic** [CoFH/Feedback#943]
So I have been searching for the answer for this error and have come up with nothing. Apparently whenever I try to launch my server I get this error: ERROR]: The mod CoFHCore (CoFH Core) requires mod versions [Forge@[10.13.3.1448,10.14)] to be available. So I figured "hey I am just gonna download the latest 1.7.10 Universal Forge.jar and it should work right?" WRONG. So now I have no idea to fix this error and I am about to cry, also happy Thanksgiving!

**Comment by skyboy** [comment]
The latest forge will work, but you may not be able to use cauldron if it's not keeping up to date with Forge for 1.7.10.

**Comment by TheWesternComic** [comment]
Alright so what do I do if my Cauldron is up to date, where should I put Forge to make my server work?

**Comment by ExcitedGamerDud** [comment]
Not sure where to put forge file at in my Cauldron ? Any Ideas?
