### ISSUE TITLE
Suggestion: Energy Exchange Augment

### ISSUE THREAD

**Issue by Ricktrandom** [CoFH/Feedback#944]
Essentially the idea is that if you have enough power flow to use it, it would be an augment that makes a machine, output from its power contents automatically into adjacent machines, effectively balancing out the system if you were to say, not have enough space to put down the power ducting. It would be nice for building compact machine layouts.

**Comment by covers1624** [comment]
Not going to happen, Machines are optimized to be machines, not ducts, its not feasible. It has also been suggested multiple times, please check the tracker for past suggestions.
