### ISSUE TITLE
Update Mystical Agriculture Plugin

### ISSUE THREAD

**Issue by bogger33** [CoFH/Feedback#945]
See also https://github.com/BlakeBr0/MysticalAgriculture/issues/144

All the other seeds from this mod seem to work, but neither starmetal, rock crystal nor aquamarine seeds seem to work

**Comment by KingLemming** [comment]
Are those new? That would be why.

I have no record of those seeds existing.

**Comment by bogger33** [comment]
Sorry I didn't say this in the original issue, but it might also be worth adding the tier 6 inferium seed from mystical aggranditions. most other seeds from that mod are probably a bit too OP to add, but that one just gives one more inferium, and it can be a bit unexpected to craft it up a tier and then have it not work in the phytogenic insolator anymore

**Comment by tyler489** [comment]
Menril seeds  and fluxed electrum awwda are also quite new was support added for them

**Comment by KingLemming** [comment]
Yes.
