### ISSUE TITLE
client crash when mousing over rockwool

### ISSUE THREAD

**Issue by ProsperCraft** [CoFH/Feedback#945]
http://pastebin.com/A1kkzTjB

FTB Infinity Evolved in hardmode

**Comment by KingLemming** [comment]
Not on us, sorry. Check w/ Vazkii.

-32752 is absolutely an invalid metadata. That's being passed to a function where it isn't handled, nor should we handle it.

**Comment by Vazkii** [comment]
For this to have happened, a stack must've already been created with this metadata elsewhere.

**Comment by KingLemming** [comment]
Yeah I thought it was unlikely that it was you directly, but what can I say, your mods are like magic. ;)
