### ISSUE TITLE
Missing engines, little confused

### ISSUE THREAD

**Issue by grifneile** [CoFH/Feedback#947]
So I'm rather new to the whole modded community and I am trying to set up a pulverizer. I have Thermal Expansion 4.0.0 and Fundation 1.2.0 and they seem to work fine together but I dont have any of the engines required to run a pulverizer. So I am clearly a bit confused as to whether or not the difference in expansion and foundation are compatible or if there was just an error in the downloads that didnt give me my engines.

**Comment by grifneile** [comment]
Got it.

**Comment by KingLemming** [comment]
http://teamcofh.com/docs/

You're looking for "dynamos." :)

In general, if you have a question, please try the IRC or any of the many wikis on the web. This tracker is really only meant for bugs.
