### ISSUE TITLE
[Bug/Mod conflict]RF API is being weird with Mekanism's induction matrix

### ISSUE THREAD

**Issue by ringosham** [CoFH/Feedback#948]
The induction matrix from Mekanism kinda works like a giant energy cell. It stores MASSIVE amount of power. It uses an energy unit called joules. The RF API is trying to convert it back to RF and show it on the energy tooltip. However, if the matrix has a storage size over 2000000000 RF. The energy values starts to screw up(Fluctuating from positive and negative number). I talked to the creator of Mekanism and he said he uses a **double based energy storage** and he cannot do much about it.
I have tested this using the latest version of Mekanism mods(Base, tools and generators. All on 8.1.7) and CoFHCore 3.0.3-303 and Waila 1.5.10
UPDATE: After further testing, I **removed** Waila and use **OpenComputers**(version 1.5.20.38). I did some lua to check the amount of the induction matrix to see if this is a Waila bug. I found out that the number is still wrong. Probably the RF API needs to do a check on that double based energy storage.
Here is a list of mods I used during testing:
https://dl.dropboxusercontent.com/u/92020026/energytooltipbug.txt

**Comment by KingLemming** [comment]
No. RF uses integers - that is the API. The RF API does not accommodate mods that are intent on using it incorrectly or in an incompatible manner.

Let Mekanism know, but there is NOTHING that will be done on this end, nor should it be.
