### ISSUE TITLE
Platinum Ore Issue

### ISSUE THREAD

**Issue by JasonBourne007** [CoFH/Feedback#948]
Hello. I am trying to enable Platinum Ore to spawn, but no matter how much I try to add the config file, it doesn't seem to work. I tried the best I could to find help but no one really seems to explain how to enable that specific resorce. Can someone please help me? I'll paste the two versions I currently have in the config to see if I was even close. 

Also, I was just wondering, why have it disabled by default in the first place?

Any help with this issue would be greatly appreciated. 

Thank you!

VERSIONS:
- Minecraft- 1.12.2
- Forge- 1.12.2-14.23.2.2618
- ThermalDynamics-1.12.2-2.3.10.4-universal
- ThermalExpansion-1.12.2-5.3.10.15-universal
- ThermalFoundation-1.12.2-2.3.10.6-universal
- CoFHCore-1.12.2-4.3.10.5-universal
- CoFHWorld-1.12.2-1.1.1.12-universal

PATH:
ThermalFoundation/assets/thermalfoundation/world/01_thermalfoundation_ores.json

MY CONFIG:
	},
        "platinum": {
            "template": "uniform",
            "generator": {
                "block": [
                    {
					    "name": "thermalfoundation:Ore", 
						"metadata": 5, 
						"weight": 80	
					},
					{
					    "name": "ThermalFoundation:Ore", 
					    "metadata": 4, 
					    "weight": 20
				    }
                ],
				"material": "minecraft: stone",
                "clusterSize": 4
	        },
            "cluster-count": 3,
            "minHeight": 48,
            "maxHeight": 96,
            "retrogen": "true",
            "biomeRestriction": "none",
            "biome": "all",
            "dimension": {
			    "restriction": blacklist:,
				"value": [
				    -1,
					1
				]
			}
 	    }
	},

	    "platinum": {
    "template": "uniform",
    "generator": {
    "block": [
        {"name": "ThermalFoundation:Ore", "metadata": 5, "weight": 80},
        {"name": "ThermalFoundation:Ore", "metadata": 4, "weight": 20}
    ],
    "clusterSize": 3,
    "numClusters": 1,
    "minHeight": 5,
    "maxHeight": 30,
    "retrogen": "true",
    "biomeRestriction": "none",
    "biomes": [
        "all"
    ],
    "dimensionRestriction": "blacklist",
    "dimensions": [
        -1,
        1
    ]
}

**Comment by Mystogrigen** [comment]
Try:

`		},
		"platinum": {
			"distribution": "uniform",
			"generator": {
				"block": [
					{
						"name": "thermalfoundation:ore",
						"metadata": 5,
						"weight": 80
					},
					{
						"name": "thermalfoundation:ore",
						"metadata": 4,
						"weight": 20
					}
				],
				"material": "minecraft:stone",
				"cluster-size": 3
			},
			"cluster-count": 1,
			"min-height": 5,
			"max-height": 30,
			"retrogen": "true",
			"biome": "all",
			"dimension": {
				"restriction": "blacklist",
				"value": [
					-1,
					1
				]
			}
		},`

**Comment by Mystogrigen** [comment]
Try:

```
		},
		"platinum": {
			"distribution": "uniform",
			"generator": {
				"block": [
					{
						"name": "thermalfoundation:ore",
						"metadata": 5,
						"weight": 80
					},
					{
						"name": "thermalfoundation:ore",
						"metadata": 4,
						"weight": 20
					}
				],
				"material": "minecraft:stone",
				"cluster-size": 3
			},
			"cluster-count": 1,
			"min-height": 5,
			"max-height": 30,
			"retrogen": "true",
			"biome": "all",
			"dimension": {
				"restriction": "blacklist",
				"value": [
					-1,
					1
				]
			}
		},
```

**Comment by KingLemming** [comment]
This is not a forum and there is no issue. Please use the Discord chat for stuff like this and do not misuse the tracker.

**Comment by JasonBourne007** [comment]
Okay, thank you @Mystogrigen !

And you seem like a very happy and chipper person @KingLemming . Was just a quetsion. Not a lecture. It's also just a game. I don't think enabling an item that is in the mod, is ruining much of anything. 
Thank you for answering my question though. I understand it now.
