### ISSUE TITLE
crash client

### ISSUE THREAD

**Issue by demon57730** [CoFH/Feedback#949]
forge 1.12.2
ThermalCultivation-1.12.2-0.1.5.3-universal.jar
ThermalExpansion-1.12.2-5.3.10.15-universal.jar
ThermalFoundation-1.12.2-2.3.10.6-universal.jar
CoFHCore-1.12.2-4.3.10.5-universal.jar
CoFHWorld-1.12.2-1.1.1.12-universal.jar

termalexpansion + sneak = crash client  ( block )

termalfoundation + sneak = ras

**Comment by covers1624** [comment]
This report makes no sense, can you please attach your crash reports with a serive such as https://pastebin.com

**Comment by MrFlufficans** [comment]
Should have added Bazinga onto the end

**Comment by demon57730** [comment]
https://pastebin.com/TNyWZFUp


the crash is that with the objects of thermal expansion and when one shif the crash I had in hand the pulverizer and that I sneak with paf crash and that with thermal expansion the other world have no problem even the thermal block Foundation works

**Comment by covers1624** [comment]
Dark RP isn't properly handling ghost block rendering of TE machines. On the actual issue of the crash, ill add some checks CCL side to stop it crashing when people do dumb things to our models.

**Comment by demon57730** [comment]
for darkrp I know I need to download the update but the

the crash and that with thermal expasion

**Comment by covers1624** [comment]
What im saying is, Dark RP is the cause of this crash, DarkRP does not handle ThermalExpansions machine models correctly for its Ghost placement. This is not a ThermalExpansion issue. But, The actual crash can be masked in CCL (Where Thermal Expansion handles models) in such that it wont crash the game, but your log will be spammed instead.

**Comment by demon57730** [comment]
I updated darkrp I run it solo to see if we can not have the error

**Comment by demon57730** [comment]
thank you I will report to darkrp because it is the mod that messed up your because I launched minecraft with your mod and no problem
