### ISSUE TITLE
Forcing 3.1 of cofh

### ISSUE THREAD

**Issue by reedgamingstudio** [CoFH/Feedback#949]
I am pretty sure another mod is causing this issue but was wondering if anyone could shine some light. I was using the latest alpha version on curse for my modpack and when i updated all the mods i got an error saying i had to use either version 3.0.1 or 3.0.2  is there any known work around for this?

**Comment by reedgamingstudio** [comment]
I think i found the solution and it was downgrading MFR

**Comment by KingLemming** [comment]
In the future, please don't misuse this issue tracker for tech support requests.

**Comment by Zaflis** [comment]
All CofH mods have hidden releases, but only MFR updates publicly. Is it not possible to hide new MFR  releases too? They cannot be used.

**Comment by KingLemming** [comment]
They do not have "hidden" releases. Those releases are ALPHA and are not meant for you.

**Comment by Zaflis** [comment]
And MFR releases are? I mean there is no consistency. You may see them differently as author, but we don't have the rights to see alphas of CofhCore etc, but why do we see MFR? It's the reason these misunderstandings appear, and people (and me) blindly update what they can.

**Comment by skyboy** [comment]
Blindly updating has caused worlds to irrevocably corrupt. You might want to reconsider that stance, and instead use things marked release.
