### ISSUE TITLE
[Redstone Arsenal] Empowering the bow causes a shift in the arrows trajectory effect

### ISSUE THREAD

**Issue by bochen415** [CoFH/Feedback#95]
Bug name:
As title

Bug type:
Graphical glitch only

Bug description:
When shooting an arrow with an empowered Flux-Infused bow the arrow trajectory effect shifts right from the aim. The arrow then spawns at the right position when reaching the target.

What it should look like:
The arrow trajectory should be (almost) straight.

Log crash or picture:
http://i.imgur.com/qt9cwAI.png

Mods installed:
CodeChickenCore-1.7.10-1.0.4.29-universal.jar
CoFHCore-[1.7.10]3.0.0B9-40.jar
NotEnoughItems-1.7.10-1.0.4.83-universal.jar
RedstoneArsenal-[1.7.10]1.1.0RC1-19.jar
ThermalExpansion-[1.7.10]4.0.0B8-23.jar
ThermalFoundation-[1.7.10]1.0.0RC1-13.jar
Forge version: 1.7.10-Forge10.13.2.1291

How to recreate:
Enchant a Flux-Infused bow with Flame I (the effect is easier to spot),
shoot an arrow aimed pretty far away.

Sidenote: I know you guys are busy with UUIDs, no hurries.

**Comment by KingLemming** [comment]
It actually doesn't. This is a vanilla bug with how MC handles arrows, but the arrow lands and hits where it should. This is purely client/server sync disagreement.

**Comment by bochen415** [comment]
Ok. It's the difference between the empowered and not empowered bow effect that made me think it's a TE bug.

**Comment by KingLemming** [comment]
Right. Empowered arrows fly faster. That's basically what you're seeing.

**Comment by bochen415** [comment]
Ok. Thanks. Closing

**Comment by KingLemming** [comment]
I'm reopening this for reminder purposes. It's something I want to investigate. It *may* be fixable.

**Comment by KingLemming** [comment]
Fixed with 1.10.
