### ISSUE TITLE
Add option to disable Nausea effect from Blitz

### ISSUE THREAD

**Issue by mcdodge34** [CoFH/Feedback#95]
Ok, I have a real problem with the Nausea effect that Blitz can cause when they fire at you, it makes me sick in real life, makes me dizzy at least, so first mod I install in most modpacks is a nice NoNausea mod, that replace the Nausea effect with something more ok, by default it inverts the left and right key of your keyboard. Can you please add a config option in your mod to avoid this cause your Blitz override this effect and cause the normal Nausea effect, so I always disable them from spawning.

**Comment by KingLemming** [comment]
So upon thinking about it, I've gone about this a different way. No option, but I've changed the effect to Blindness. Nausea is indeed obnoxious.

**Comment by mcdodge34** [comment]
Hum, ok then, will see how I can manage to deal with them while blind, but if its anything like the old spiders from a certain mod that were spawning in jungles, I'll have to do anything to disable the Blitz from my pack, I already have problems with my eyes in real life which makes me really bad at any FPS games (only 30% of vision on my left eye and 70% on my right eye, I had cataracts removed at 3 yrs old, long story short, I'm lucky to be able to play games on PC and read and write, I can't even have a driving license, my dream was truck driver so, guess what I'm a PC support tech now)

**Comment by KingLemming** [comment]
Okay, so I've added configs for this, but I'm leaving the Blindness. Here's the thing though - they are in common.cfg. There's no good or fair way to make it a client-only thing.

**Comment by mcdodge34** [comment]
Can't wait to test them out, along with the Thermal Dynamics stuff, but I don't put any pressure, I know theses kind of things take time to program...
