### ISSUE TITLE
[1.12.2-2.3.10.4] Flux-Infused bow crash

### ISSUE THREAD

**Issue by elijahlorden** [CoFH/Feedback#950]
Upon right-clicking the flux-infused bow, the game crashes.  Logfile attached to post.
[crash-2018-02-27_19.34.49-client.txt](https://github.com/CoFH/Feedback/files/1765179/crash-2018-02-27_19.34.49-client.txt)

**Comment by KingLemming** [comment]
Are you in a development environment by chance?

And can you make this happen with *only* CoFH mods?

Because the error suggests that it is access transformer related and not the fault of our mods at all. If this method were private in our dev environment well...it would break.

So offhand I am guessing that you are in a dev environment and you didn't add the access transformers to your Forge setup.

**Comment by elijahlorden** [comment]
I am not in a dev environment.

**Comment by KingLemming** [comment]
Okay. Can you make it happen with *only* CoFH mods then?

The error you're describing isn't something that we see, or we literally couldn't build the mod.

**Comment by elijahlorden** [comment]
If you mean does the issue happen with items from other mods, then that is a no.  The only items this happens with is bows from CoFH mods.

**Comment by elijahlorden** [comment]
I found the problem!  While attempting to re-download the latest version of CoFH core, I noticed that Curse downloaded the file as a zip archive.  I had not noticed this previously, because I have all archives (zip, jar, etc) set to open with 7zip, and they have the same icon.  After renaming the file to CoFHCore-1.12.2-4.3.10.5-universal.jar, the issue vanished.  Now I'm not well versed in the specifics of MC modding, but I assume something about the fact that the mod was being loaded as a zip archive prevented the access transformers from working (but wouldn't this have broken other things?).  After seeing that this fixed the issue, I fixed the file extensions for the rest of the mod files.

**Comment by elijahlorden** [comment]
Sorry to have bothered you about this, as it was not the fault of your mod!

**Comment by elijahlorden** [comment]
I was using Edge, I did not try Chrome (i wasn't aware it was a browser issue).

**Comment by covers1624** [comment]
Ive had a few people have the exact same issue. Anyway, good that you fixed you issue. Ill close this up.
