### ISSUE TITLE
Where did Energy Cells and Energy Conduits go?

### ISSUE THREAD

**Issue by Sturp** [CoFH/Feedback#951]
I was watching a video on how to use BuildCraft and I noticed that the uploader of the video had used Redstone Energy Cells and Redstone Energy Conduits from the Thermal Expansion mod in their video. I cannot seem to find these items now. Is there any alternative to these? Thanks!

**Comment by KingLemming** [comment]
This is not a forum. Please direct questions to the Discord.

Energy Cells are in Thermal Expansion. Fluxducts are in Thermal Dynamics. They haven't gone anywhere in years. The fact that you called them Conduits though makes me think you watched something from many, many years ago.
