### ISSUE TITLE
[NetherOres] Can't find UID for block powercrystals.netherores.world.BlockHellfish

### ISSUE THREAD

**Issue by walkerjonny** [CoFH/Feedback#952]
Hi,
I'm getting this with the latest three versions of NetherOres.
The latest.log gets spammed with this and it causes the server module to hang. It is also not possible to close Minecraft properly because Minecraft hangs when i try to close the world and get back to the main menu. 
However, there is no server crash dump.
[latest.log.txt](https://github.com/CoFH/Feedback/files/50405/latest.log.txt)

**Comment by skyboy** [comment]
You're welcome to report the mod generating the error: Journeymap. I, however, am unable to fix other mods.
