### ISSUE TITLE
Arboreal Extractor stacking (bug?)

### ISSUE THREAD

**Issue by HarroldSaxon** [CoFH/Feedback#953]
it turns out you can grow a cannopy of leaves and add logs at 3 4 and 5 tall in a lattice pattern to stack your Arboreal Extractors up to 4 high... well, 3 with a space for pipes. 
really convenient for the one chunk survival challange server I play on, but maybe not as you intended? Not sure if this is a bug or if it's fine. Maybe make the leaves decay if you cramm too many extractors under one tree? To show you're stressing the tree to death XD

**Comment by KingLemming** [comment]
Do you have a picture of this? I'm not sure I quite understand.

**Comment by HarroldSaxon** [comment]
![20180303_211250](https://user-images.githubusercontent.com/16321509/36941748-62ac85da-1f28-11e8-8d40-bf0da9b52f98.jpg)
![20180303_211458](https://user-images.githubusercontent.com/16321509/36941751-7074bd04-1f28-11e8-840b-6f1fac4998f9.jpg)
![20180303_211550](https://user-images.githubusercontent.com/16321509/36941752-7ae96bc2-1f28-11e8-8a6a-7212b6396c51.jpg)

By adding a few logs, you can have 12 arboreal extractors running in a 3x3 area, under the leaves of one small tree.

**Comment by KingLemming** [comment]
Sort of a limitation of how they operate. Not strictly a bug though this isn't really a behavior I want.

I'll have an adjustment incoming.

**Comment by covers1624** [comment]
Did you mean to `Close and Comment` this?

**Comment by HarroldSaxon** [comment]
Most foolproof thing I can think of is to add a tag to logs from worldgen and tree generation, that user placed logs would lack. It'd slow down worldgen a tiny bit... but with how odd trees can turn out naturally, it's the only thing I can think of to differentiate user placed logs.

**Comment by KingLemming** [comment]
That's not how it works. That's literally not a thing you can do, unfortunately.

**Comment by HarroldSaxon** [comment]
Oh, is that so? Sorry then. Admittedly, the last time I went changing anything in world gen was back on 1.7.2, and I think I remember people not being so fond of ASM these days. Sorry for my bad suggestion.  :X
