### ISSUE TITLE
Suggestion: Reliquary Support for Enstabulation Apparatus

### ISSUE THREAD

**Issue by Ricktrandom** [CoFH/Feedback#954]
Support so creatures processed in the Enstablution Apparatus Augment will have a small chance to drop reliquary drops when reliquary is installed.

**Comment by Tora-B** [comment]
I believe there were a couple problems discussed on this topic: There are only four output slots in the centrifugal separator, some mobs have more than that many items in their drop table already, and one of those slots is probably going to be filled by returning the morb. I believe it was also mentioned that it's difficult to programmatically get an accurate list of drops, so the enstabulation recipes were created manually.

**Comment by KingLemming** [comment]
Sorry, this won't be happening without a major rewrite to a lot of backend systems, and that just isn't in the cards.
