### ISSUE TITLE
ThermalExpasion: ChiselsAndBits conflict

### ISSUE THREAD

**Issue by ggblbl** [CoFH/Feedback#955]
In my serverlog it says "[chiselsandbits]: Unable to determine blocks eligibility for chiseling" for some of the blocks in the mod.
I read up on the error (https://github.com/AlgorithmX2/Chisels-and-Bits/issues/49) and it seems it can't be fixed by @AlgorithmX2.
These are the blocks:
cofh.thermalexpansion.block.device.BlockDevice attempted to load net/minecraft/client/renderer/texture/TextureAtlasSprite

**Comment by covers1624** [comment]
Easy fix, https://github.com/CoFH/ThermalExpansion/commit/992f6b2e94d2a70b7ffcfa2c8f84826a8825d748
