### ISSUE TITLE
Weird crash with dynamos?

### ISSUE THREAD

**Issue by XFRGod** [CoFH/Feedback#957]
I updated to the latest versions and this started happening.
http://pastebin.com/EZ2mqSsi

**Comment by XFactHD** [comment]
Can reproduce this without Fastcraft?

**Comment by KingLemming** [comment]
That's not on us. Something is telling the dynamo to render with facing of 7. There is no facing 7, and dynamo rendering code didn't change.

If it worked before, it should work now, barring a corruption of your world, which is possible.

**Comment by skyboy** [comment]
Worse than facing 7 - metadata 7. That comes from the inventory.

**Comment by KingLemming** [comment]
It could actually be either.

**Comment by skyboy** [comment]
Not from the inventory. Facing is fixed at "1" so they face up, and cannot be altered by the stack.

**Comment by KingLemming** [comment]
Oh okay, didn't notice it was in inventory. I get ya now.

**Comment by XFRGod** [comment]
The weird thing is how I fixed it. I placed myself 1 block away and it worked.
