### ISSUE TITLE
Modpack Crashes and i see alot of cofh failure stuff.

### ISSUE THREAD

**Issue by Kingi-s** [CoFH/Feedback#958]
Link to pastebin: https://pastebin.com/niUqiYWH

Ask me if you need anymore information. i would be glad if someone could help me

**Comment by KingLemming** [comment]
Not the fault of CoFH in any way, sorry. Unsure what the actual issue is but it is not us, from the stacktrace.

**Comment by Kingi-s** [comment]
and how am i supposed to know what crashes my game if i get million words

**Comment by Kingi-s** [comment]
IT was aromas fault. sorry for posting my problems here
