### ISSUE TITLE
[Request] Config option to disable light from machines

### ISSUE THREAD

**Issue by artubi** [CoFH/Feedback#959]
Hi,
I would like to request a config option to disable light from running machines.
Reason: to reduce load on game / CPU caused by light calculation

This is handy in scenarios where has to be multiple machines (AE autocrafting / quarry) especially if the machines are inconsistently being turned on and off.

**Comment by XFactHD** [comment]
If I recall correctly this has already been requested and rejected because, no matter how long the machine runs, the texture change and the lighting are only recalculated after at least 10 seconds or so.

**Comment by artubi** [comment]
@XFactHD issue number #925, yes I'm aware of that. However, the issue was closed by its reporter, not by anyone from TeamCOFH.

For comparison:
- EnderIO machines doesn't produce any light when they are running (no option to turn it on)
- Mekanism machines by default produce light when they are running (there is option to turn it off)

Yes, that 10 second animation (during which light is still on) is far better than Mekanism instant turn on / off light after starting / stopping.

This is more prevalent in AE autocrafting, especially:
- being in close proximity to the machines
- if there is many steps to get that item.
- if different machines are working at different speed

**Comment by XFactHD** [comment]
Ok, seems like I didn't pay attention who closed the issue. I also have a big AE2 autocrafting system with TE involved and it doesn't lag but maybe even my graphics card is too powerful to make this happen.

**Comment by KingLemming** [comment]
Here's the thing - it doesn't matter if the light value is 0 or 15, the calculation *happens*. That's part of updating the block state. So basically you're asking for something that you think will help, but won't.

So I'm afraid not. Also, seriously, the way we do it is *incredibly* CPU friendly.
