### ISSUE TITLE
Suggestion\bug? - Thermal Foundation

### ISSUE THREAD

**Issue by Southier9** [CoFH/Feedback#959]
Hello, I don't know if this is a bug or I will be making a suggestions, but I was building a Molten Metal Checkpoint Cave, where I put all Molten Metal Liquids to get track of which Metal I have, but when I put the ones from Thermal Foundation, they came with no texture, just a blank pink texture.
It's the left one, a Signalum Reservoir.
In the Tanks it shows properly, just at the world it become a untextured fluid.
![2018-03-02_11 19 16](https://user-images.githubusercontent.com/36991161/36905221-86bced24-1e11-11e8-869a-6d4a88d2629e.png)

But at the other hand, the Destabilized Redstone works properly, both in the world and the tanks.

![2018-03-02_11 24 55](https://user-images.githubusercontent.com/36991161/36905404-0fd1ea2e-1e12-11e8-987c-701536ff954d.png)

Any idea what is happening?
This also happens with only both TiC and TF and their cores activated.

**Comment by KingLemming** [comment]
No idea what's happening there. It's not something I've seen before.

I think Forge recently changed some things with the base fluid model which may have affected this. Will investigate.

**Comment by Southier9** [comment]
There is a version you recommend me to use that the fluids don't become non-texturized?

**Comment by KingLemming** [comment]
Well, when I made the Plugin, this definitely never happened, so not sure what to tell you. I'm going to look into it.

**Comment by Southier9** [comment]
Can you try yourself with the lastest\ecommended build of Forge?
If this doesn't happen with you, I'll try reinstalling my mods.

**Comment by Southier9** [comment]
Sorry for double-posting, made a Creative World to test out, just some "bucketable" fluids are without texture.
Without Texture: Molten Enderium, Molten Limium, Molten Signalum, Molten Constatan, Molten Invar, Molten Iridium, Molten Platinum.
With Texture: Primal Mana, Tectonic Pretotheum, Gelid Cryotheum, Blazing Pyrotheum, Resonant Ender, Destabilized Redstone, Crude Oil.

**Comment by KingLemming** [comment]
Looked into it and figured out what's happening here, kinda.

I straight up don't create versions of those fluids with blocks attached. They aren't allowed to be placed in world at all, very intentionally (it's kind of irresponsible with block IDs in 1.12). So I don't know what is going on with you that you somehow have block versions, but that's not TF creating them. And that's probably the problem.

**Comment by laz2727** [comment]
Here's a funny thing.

TinkerIntegration:118
// we always register blocks for all integrated fluids to prevent issues with missing blocks
