### ISSUE TITLE
[Thermal Foundation] Lexicon "forgets" player's preferences upon death

### ISSUE THREAD

**Issue by hayesj1** [CoFH/Feedback#96]
I have come across a very annoying bug with the lexicon. No crash, just really frustrating. Steps to reproduce:
1. Set some preferences in the lexicon for auto transmutation
2. Verify intended functionality
3. Die somehow
4. Preferences are now set to the first choice possible for all entries

In addition, dropping and picking up the lexicon doesn't yield this bug, so it seems related to player death. The state of empowerment at the time of death also seems to not make any difference. just to be clear, items still _respect_ preferences post-respawn, the preferences _themselves_ have been reset to the first choice.

**Comment by KingLemming** [comment]
Issue with what the vanilla game does to player nbts upon death. Will see what we can do about it.

In the meantime, stop dying. ;)

**Comment by KingLemming** [comment]
Okay, need to issue a correction here. It's not Mojang's fault after all.

...it's Forge's fault.
