### ISSUE TITLE
A critical problem occurred registering the ASM transformer class 

### ISSUE THREAD

**Issue by Tsyklop** [CoFH/Feedback#962]
error in the log file:
http://pastebin.com/ZrrP8ntw

malisiscore-1.7.10-0.14.0 malisisdoors-1.7.10-1.13.0
CoFHCore-[1.7.10]3.1.0B1-319 CoFHLib-[1.7.10]1.1.0-178

https://github.com/Ordinastie/MalisisDoors/issues/66

**Comment by KingLemming** [comment]
Not us.
