### ISSUE TITLE
Crash with CoFHCore 1.12

### ISSUE THREAD

**Issue by Wasthereonce** [CoFH/Feedback#962]
https://pastebin.com/tBWYEjRF

**Comment by KingLemming** [comment]
What's happening here is that another mod has errored out during loading, the FontRenderer is not properly initialized, but the events still fire as if no mod has errored.

So basically you're seeing a crash before Forge is able to put up the screen showing the *actual* cause.

Sorry, not us.

**Comment by josephcsible** [comment]
Interesting. Any details about the Forge issue, or where exactly the other mod would have errored out?

**Comment by KingLemming** [comment]
It errored out somewhere during the init process. Basically the problem is that a mod errors for whatever reason, Forge *knows* that it errored out, but events begin firing anyways.

And the Client events specifically begin firing before the loading screen comes up. This might actually be unavoidable due to how Forge does the error screen. I'm not entirely sure, I just know that when this happens it means the vanilla Font Renderer hasn't been initialized due to an incoming crash.

**Comment by covers1624** [comment]
Basically, even if the instance is dead and loading will only ever display the missing mods / custom error screen, registered event handlers still receive events, and there is no way for CoFHCore to mitigate this, short of an ugly "hasPostInitFiredYet" field. The fix in forge is to force the EventBus to drop all its handlers when an error like this is thrown. Its unrecoverable anyway, there is no way a mod could "hack around" the error screen and mods wouldn't be in the correct state anyways, simply nuking the EventBus's handlers is the easiest solution.

**Comment by covers1624** [comment]
Poke @mezz maybe he has some thoughts on the situation.

**Comment by mezz** [comment]
I recently fixed the issue where stuff keeps running and events are fired after a mod crashes during loading, in this commit:
https://github.com/MinecraftForge/MinecraftForge/commit/603903db507a483fefd90445fd2b3bdafeb4b5e0
Which is in Forge 1.12.2-14.23.1.2603

**Comment by mezz** [comment]
Maybe there is still more to be done, but I am pretty sure that fixes most of the issues people were seeing.

**Comment by josephcsible** [comment]
This particular crash happened on Forge 2624, so it does indeed look that way.

**Comment by mezz** [comment]
If you can create a test case where this happens, it should be fairly simple to fix.
If you want to make a PR for this, use my commit above as an example. I just added an event handler to the test mod there to confirm the issue first, and then it was pretty straightforward to fix.
