### ISSUE TITLE
can't craft Sapling Infuser

### ISSUE THREAD

**Issue by Jrflies** [CoFH/Feedback#963]
can't craft Sapling Infuser. I think i got all the mods updated

Jrflies

**Comment by KingLemming** [comment]
Okay. Well you've done something wrong then or your modpack has disabled it.

I promise you if this were an actual issue we'd have had thousands of reports on it.

**Comment by Jrflies** [comment]
Redstone servo
lumium plate x2
signalum gear
piston
 just as on your crafting page. any other ideas

**Comment by KingLemming** [comment]
Use JEI.
