### ISSUE TITLE
Fluid Transposer treating water buckets as bottles

### ISSUE THREAD

**Issue by nodlek** [CoFH/Feedback#963]
I encountered a problem using the fluid transposer to empty water buckets. The fluid transposer outputs an emty bottle and has 333 mb in its tank instead of 1000 mb.
I play ftb infinity version 2.2.2.
I'm using:

ThermalDynamics-[1.7.10]1.1.0-161
ThermalExpansion-[1.7.10]4.0.3B1-218
ThermalFoundation-[1.7.10]1.2.0-102

You can find a complete mod list here:
http://paste.tribly.de/xv72x/

**Comment by KingLemming** [comment]
This isn't actually caused by us. It's the result of another mod using the oreDict improperly.
