### ISSUE TITLE
Bug: Breaking Filing Cabinet causes loss of folders using hammers

### ISSUE THREAD

**Issue by Akitori** [CoFH/Feedback#965]
Hiya. So i used the mod Real Filing cabinet, a neat little mod that lets me put eight folders per cabinet.

One of my users for the modpack broke a full filing cabinet with various resources, and uh...the cabinet normally drops with nbt. Ie: which folders are in, how much of each, kinda like a shulker box. 

Except the cabinet had no nbt whatsoever. They used a iron hammer to break it, so idk if its on your end or the mod maker's end.

Just reporting it here as well as the modder's github. Pickaxes work fine, but all hammers cause this strange bug.

**Comment by covers1624** [comment]
Its likely an issue with how they handle block dropping, There are specific methods they need to use and aren't, Lemming can fill in more, but all the code handling this(iirc) is in CoFHCore, it works fine with all other blocks in other mods, i suggest the the FilingCabinet mod look in to how vanilla handles this with the ShullkerBox.

**Comment by KingLemming** [comment]
Covers is probably right. For blocks to drop their contents correctly, they have to do some hacky stuff.

Hammers actually go through the normal block breaking process, so I'm quite confident it isn't on our end, but I'm willing to double check.

**Comment by Akitori** [comment]
Bug was caused by other mod, closing issue now. Thanks!
