### ISSUE TITLE
Machine "SmallStorage" setting makes Fluid Transposer almost unusable

### ISSUE THREAD

**Issue by adudney** [CoFH/Feedback#967]
The Fluid Transposer checks to see if it has enough RF for the entire operation before beginning. Unfortunately since most operations take more than 10 ticks, the "SmallStorage" setting makes the machine never start. This requires you to add speed augments to make the internal buffer big enough to process items, or raise the RF/t in the config to the same level (which would make all operations take <= 10 ticks for the basic machine).

Minecraft: 1.12.2
Forge: 14.23.2.2611
CoFH Core: 4.3.10.5
Thermal Foundation: 2.3.10.6
Thermal Expansion: 5.3.10.15

https://github.com/CoFH/ThermalExpansion/blob/1.12/src/main/java/cofh/thermalexpansion/block/machine/TileTransposer.java#L146

https://github.com/CoFH/ThermalExpansion/blob/1.12/src/main/java/cofh/thermalexpansion/block/machine/TileTransposer.java#L308

https://github.com/CoFH/ThermalExpansion/blob/1.12/src/main/java/cofh/thermalexpansion/block/machine/TileTransposer.java#L321

**Comment by KingLemming** [comment]
Hrm. I can probably safely change that now.

Going to look and make sure there isn't some strange corner case I kept that in.
