### ISSUE TITLE
[1.12.2] [ThermalExpansion] Client crash when open strongbox

### ISSUE THREAD

**Issue by KorDum** [CoFH/Feedback#969]
ThermalExpansion 5.3.10
https://gist.github.com/KorDum/9af1376d0df61a6b6b32370c41b1830a

**Comment by KingLemming** [comment]
Need more info. Something like this should happen consistently if it happens at all.

Try with only CoFH mods please.

**Comment by KingLemming** [comment]
If IE is causing the crash, then no - I can't add code to prevent it.

I'm still not sure what the cause is.

**Comment by KorDum** [comment]
Another mod served as a catalyst, I think.
```java.lang.ArrayIndexOutOfBoundsException: 0
	at cofh.thermalexpansion.block.TileInventory.func_70301_a(TileInventory.java:177)```
If it's not in ThermalExpansion, then close issue, well.

**Comment by KingLemming** [comment]
I still don't have enough info to understand what's happening. Does this happen with *every* strongbox, just a specific one? Does it happen only when a strongbox is next to a block from a certain mod?

Please provide details and/or a video.

**Comment by KorDum** [comment]
Sorry, i haven't screenshot.
The problem arose only once. The chest stands close to the IE Crusher (see screenshot above). The known problem of IE is the breaking textures of multi-block machines:
https://mineyourmind.net/forum/attachments/2017-04-30_15-39-52-png.11763/
In my situation, part of the texture has spread to the chest and when I tried to open - the client fell with an error. I don't know if these bugs are related, but that's all I can say.

**Comment by KingLemming** [comment]
Oh. Yeah that's definitely related then - IE corrupted the strongbox.

Sorry, there's no fix for that on our end. :/ That's entirely IE's problem.

**Comment by KorDum** [comment]
Ok, thanks for answer!
