### ISSUE TITLE
Thermal Foundation 1.0.0RC1-39 crashing on startup

### ISSUE THREAD

**Issue by topher2010** [CoFH/Feedback#97]
I tried updating Thermal Foundation on my private pack, and in testing before pushing to the server, i am getting the following crash in SSP: http://pastebin.com/4Mzx42sH

**Comment by skyboy** [comment]
The versions available on CurseForge are for alpha testers - they've hourly builds from the jenkins. Use the versions found on [Curse](http://www.curse.com/users/TeamCoFH/projects) if you do not intend to test alphas.

**Comment by topher2010** [comment]
I found that build 35 works in my environment.  I just wanted to post up the crash i got for you guys, in case it helps you at all.
