### ISSUE TITLE
[1.12.2] [CoFH World] "Enable Flat Bedrock" option generate dirt in Galacticraft dimensions

### ISSUE THREAD

**Issue by QuantumStatement** [CoFH/Feedback#970]
Minecraft 1.12.2
CoFH World 1.1.1.12
Galacticraft 4.0.1.150

![2018-03-09_14 11 33](https://user-images.githubusercontent.com/35406698/37205633-8221c484-23a6-11e8-9497-1fc1debc059b.png)

**Comment by KingLemming** [comment]
This is on GalactiCraft. They have not correctly specified the filler block for their biomes. Please let them know.
