### ISSUE TITLE
[Suggestion] sickle leaf harvesting behavior improvements

### ISSUE THREAD

**Issue by Ianaver** [CoFH/Feedback#970]
Sickles should harvest upper and lower levels as well when harvesting leaves, not just the leaves on the same Y level. This would not only speed up harvest time but make it easier on the players when harvesting leaves.

**Comment by KingLemming** [comment]
The Flux-Infused Sickle does this when empowered. This is quite intentional - use that one. ;)

I get that it'd be a QoL change, but it would sort of encroach on the Flux-Infused version.

**Comment by Ianaver** [comment]
ah I see
