### ISSUE TITLE
[Bug or Feature request] Satchel autosort

### ISSUE THREAD

**Issue by boggensagg** [CoFH/Feedback#971]
I am unsure if this is a bug or a feature request.

I am playing ATM3 and the one thing that bugs me is that the inventory autosort feature (I believe from Inventory Tweaks) is not available in Satchels.

I am not even sure if this is an issue with CoFH or Inventory Tweaks.

**Comment by KingLemming** [comment]
So this feature was removed as Inventory Tweaks for whatever reason is apparently not compatible with Satchels.

Sorry, just some limitation with it. Not exactly sure what, it just seems to complain.
