### ISSUE TITLE
Help For COFH mod crash!

### ISSUE THREAD

**Issue by Ralphy2405** [CoFH/Feedback#971]
Please make COFH Core compatible with intel because it is becoming extremely difficulty for us to use COFH mods use . Pls try because whenever we try to run any cofh mod (up to date) it gives an error message about javaw.exe crashing . Pls help!!!

**Comment by KingLemming** [comment]
It's already compatible...this is something on your end. But post a modlist as well as your hardware specs and java version.

**Comment by Ralphy2405** [comment]
I only tried using COFHCore and it still crashed . My java version is - JDK build 1.8.0_65-b17
Hardware Specs are - Windows 7 Ultimate 32 Bit
 Processor: Pentium(R) Dual-Core  CPU      E5700  @ 3.00GHz (2 CPUs), ~3.0GHz
             Memory: 2048MB RAM
Card name: Intel(R) G41 Express Chipset
       Manufacturer: Intel Corporation
          Chip type: Intel(R) 4 Series Express Chipset

**Comment by KingLemming** [comment]
Those specs can barely run Minecraft as is. Modding it isn't even a good idea.

**Comment by Ralphy2405** [comment]
Thank you so much KingLemming I upgraded my PC and now COFH mods are running perfectly fine . Thnx for helping! :-)

**Comment by skyboy** [comment]
I feel like that's snark, but we can't really help it. Modded, depending on what mods you have, has a higher minimum requirement than base Minecraft.
