### ISSUE TITLE
cofh killall feedback missing in console.

### ISSUE THREAD

**Issue by ProsperCraft** [CoFH/Feedback#972]
This has been going on for a really long time, and I thought I had reported but, but can't find it.

When you type cofh killall and in console, the feedback on how many mobs it killed is missing.

> cofh killall
[10:24:34] [Server thread/INFO] [nucleus]: Server ran the command: /cofh killall
[10:24:34] [Server thread/INFO]: chat.cofh.command.killall.successHostile

**Comment by KingLemming** [comment]
I think this is probably unfixable and is due to how Mojang handles localization (or rather, doesn't) in the server console.

I'll take a look, but I don't think this can be changed.

**Comment by KingLemming** [comment]
This can maybe be hacked around to kind of work, but ultimately, this is something that Forge needs to handle.
