### ISSUE TITLE
Request for being able to craft Magma Crucible without the need for Nether Brick

### ISSUE THREAD

**Issue by LegendLength** [CoFH/Feedback#972]
For sky block style games the only way to use Thermal Expansion is to include the Ex Nihilo mod so you can use the Crucible to create infinite lava.  I personally don't like infinite lava because it takes all the fun out of creating a power system.  You can simply make a row of crucibles that continually melt cobblestone and leave it to run forever.

But it is possible to play without the Ex Nihilo Crucible if you build a TE Magma Crucible.  Then you can get cobblestone by sifting dirt and creating lava in the Magma Crucible.  This way you actually have to earn your lava.

The problem is the Magma Crucible requires Netherbrick to build.  In sky block games you normally don't have access to The Nether.  So it's not possible to build a Magma Crucible to create that first bucket of lava.  If you could use some other brick instead of Netherbrick I think it could solve the issue of having to rely on infinite lava which feels cheaty to me (I'm not trying to tell other people how to play).

All that being said it does seem possible to obtain Netherrack using the Sludge Boiler (Minefactory Reloaded mod).  But I wonder if you'd consider this slight change to the Magma Crucible recipe so you don't need to rely on that mod.

**Comment by KingLemming** [comment]
No, sorry. The Nether Brick is *very* intentional as part of the mod's progression. Feel free to Minetweak/Modtweak.

**Comment by LegendLength** [comment]
Ok but then I don't understand the point of the Magma Crucible at all then, in terms of using it to make lava.  You can just use an infinite supply of lava from Ex Nihilo crucibles.

**Comment by KingLemming** [comment]
The mod isn't balanced around Ex Nihilo. Also, the machine does *way* more than make lava.
