### ISSUE TITLE
[Thermal Expansion] Workbench crash latest update.

### ISSUE THREAD

**Issue by Beelzaboss** [CoFH/Feedback#973]
Hi there,

With the latest update of Thermal Expansion, I am getting this crash on my multiplayer world, Server is fine, just the client that crashes. 

http://pastebin.com/yuesTAfW

**Comment by KingLemming** [comment]
Hrm...I feel like I had fixed this, but then I see @skyboy changed some things around. Maybe I didn't commit. :/

**Comment by skyboy** [comment]
I had a solution you had rebased over and wiped out, I apparently missed that line being removed and so didn't re-add it.

**Comment by KingLemming** [comment]
The rebase was a solution as well. :/ We discussed it.
