### ISSUE TITLE
Possible Performance issue 

### ISSUE THREAD

**Issue by JoeSGT** [CoFH/Feedback#974]
Hello i was scanning my WarmRoast tryin to find the source of my lag issues and i had found this 
![0ef291124062834061fe9f25a40c333f](https://user-images.githubusercontent.com/30296350/37237028-16ae8846-23dc-11e8-8b64-fec31e2cf882.png)

**Comment by KingLemming** [comment]
Yeah that's not us. Not directly anyways. The way that TD works, it'll get the blame for laggy tiles connected to the network. You can try removing overly complex tile entities (giant chests and such) and see what happens.

Also, strictly speaking, we can't offer any support for Sponge I'm afraid. We code only with Forge support.
