### ISSUE TITLE
[Thermal Dynamics] crashing when tryng to open inventory in creative mode

### ISSUE THREAD

**Issue by lightning02** [CoFH/Feedback#974]
crashing when tryng to open inventory in creative mode using ThermalDynamics-[1.7.10]1.1.0-161 
[crash-2015-12-16_00.23.41-client.txt](https://github.com/CoFH/Feedback/files/64481/crash-2015-12-16_00.23.41-client.txt)

**Comment by KingLemming** [comment]
Not us. It's farseek, whatever that is.

**Comment by lightning02** [comment]
how can i do this? in the config file?

**Comment by KingLemming** [comment]
Yes. It's a config option.
