### ISSUE TITLE
Cofh enchant command bug

### ISSUE THREAD

**Issue by bsaksida** [CoFH/Feedback#975]
Hello

Enchanting with a number greater of 127 will throw into negative number. I used nbtedit command and is possible to put a bigger number as such as 1000.

**Comment by KingLemming** [comment]
We use the vanilla Minecraft ItemStack enchanting interface. This is the correct way to handle it. Minecraft stores the enchant level as a byte using this method.

Working as intended, expected, and is reasonable.

**Comment by bsaksida** [comment]
Then is it possible to validate entry by forbiding going over that value
