### ISSUE TITLE
[1.12] Strongbox throws Payload may not be larger than 32767 bytes exception

### ISSUE THREAD

**Issue by Frontrider** [CoFH/Feedback#976]
I get this stacktrace along this error message:
Payload may not be larger than 32767 bytes
https://pastebin.com/GCQt1SwB

The situation:
I placed chisel and bits blocks inside an rf tools modular storage, than I placed this modular storage inside a resonant strongbox.

No crash, only kicks me out when I open it. Maybe a c&b issue, but I'm reporting it here, because the strongbox is the top layer of the situation.

Update: it can safely travel in my inventory.

**Comment by temp1011** [comment]
https://github.com/CoFH/Feedback/issues/865. Looks like it's probably a chisel and bits issue.

**Comment by KingLemming** [comment]
Duplicate and not on us.
