### ISSUE TITLE
[BUG] Insightful Condenser turns to infinite XP

### ISSUE THREAD

**Issue by Akitori** [CoFH/Feedback#977]
https://youtu.be/Hn87xJvfH2g

Written form: Fill up the insightful condenser with enough xp to fill it and adjacent machines. Throw exp bottles until experience stays in world. Start draining xp into tanks/bottles. Get mass profits.

**Comment by KingLemming** [comment]
Will look into it but this is actually specifically something I tested when I made the machine and this sure didn't happen at the time.

**Comment by Akitori** [comment]
I'm unsure how truly infinite it is, however its enough to fill a holding 4 resonant tank (not reservoir) at least 2 times over from my testing. I can keep testing however to find if there's a limit.

**Comment by Akitori** [comment]
Update: Have tested, turns out its a finite limit (granted, it took so long i thought it was infinite)

Apologies for the confusion, closing this.

**Comment by KingLemming** [comment]
No worries. :) There's a not-obvious mechanic with the device where it will buffer a whole lot of XP and then slowly turn that into fluid.

The idea is to keep orbs from lingering and causing a lot of lag.

**Comment by Akitori** [comment]
Also i will add as a note....

Assuming my video is the weakest output from this? It takes 250 xp to fill a bottle? The fact that my resonant reservoir got filled up makes me think this is still theoretically infinite xp. Just throw metric tons of the bottles and generate more than you had originally...

*course there's still the cost of glass and rf, but the point is still the same.

**Comment by KingLemming** [comment]
So I tested this again to be sure, and...it doesn't happen.

At least, it doesn't happen with only our stuff. The recipe is such that you get less XP out of a bottle than it takes to make. So this might be x-mod interference, but like I said - I can't get this to happen.
