### ISSUE TITLE
Cofh Nei plugin crash

### ISSUE THREAD

**Issue by RamboRambowski** [CoFH/Feedback#979]
Hi all,

I'm not sure whether you guys manage the nei plugin for your mods, but I encountered a crash that seems to be caused by it. 

If this isn't the right place for this, please point me to where it's supposed to go. I was running FTB Infinity Evolved version 2.2.2, in expert mode. I was checking the uses for uranium, and Java decided that someone divided by zero. 

Here's the pastebin of the crash report: http://pastebin.com/aWAd0rEJ

I just noticed my Java version is only 1.8.0_25, which might have something to do with it, but here's the crash report anyway.

Thanks,
Rambo

**Comment by KingLemming** [comment]
This is fundamentally a failing on whoever is adding those recipes, but I've added a stupid check to deal with stupid devs who do stupid things with their stupid mods.
