### ISSUE TITLE
CoFH World Generation problems generating surface decoration

### ISSUE THREAD

**Issue by RakDuhl** [CoFH/Feedback#979]
i am working on my modpack and currently modifying the ore gen and adding few features.
Right now i try to generate Avaritia Infinity block decorations on the surface, but it does not generate.
I don't see any errors in the log either, so i must have missed something somewhere.

## {
    "populate": {
        "Infinity Block decorations": {
            "distribution": "decoration",
                "material": [
                    "minecraft:grass",
                    "minecraft:tallgrass",
                    "minecraft:air"
                ],
                "generator": {
                    "type": "decoration",
                    "cluster-size": 5,
                    "block": [
                        {
                            "name": "avaritia:block_resource",
                            "metadata": 1,
                        }
                    ],
                    "surface": [
                        "minecraft:grass",
                        "minecraft:sand",
                        "minecraft:stone"
                    ],
                    "see-sky": false,
                    "check-stay": false,
                   "stack-height": 3,
                   "x-variance": 4,
                   "y-variance": 2,
                   "z-variance": 6
               },
               "cluster-count": 2,
               "chunk-chance": 2,
               "retrogen": true,
               "biome": "all",
               "dimension": "all",
           }
       }
}`

**Comment by KingLemming** [comment]
Tech support should go on the Discord, not here.

Please go there with your questions.

**Comment by RakDuhl** [comment]
oh, didn't know, thanks for telling me!
