### ISSUE TITLE
Strongbox rendering screen null pointer crash

### ISSUE THREAD

**Issue by PsionicArchon** [CoFH/Feedback#980]
A player on my server is crashing when hovering over their strongboxes if they're in their inventory.

Crash: http://pastebin.com/nX67wmFk

We're using the latest alpha build of Thermal Expansion, cofhcore, and cofhlib with version .1614 of Forge. 

Before anyone asks, the latest version of Forestry with the fix for the mutating bees crash requires a version of forge beyond the recommended version.

**Comment by Beelzaboss** [comment]
When will be the next dev build be released or is there a download/source link somewhere?
