### ISSUE TITLE
[Thermal Dynamics] getCoverStack crash on startup

### ISSUE THREAD

**Issue by Tencao** [CoFH/Feedback#980]
Crash Report - https://paste.ee/r/P5cCo
Forge - 14.23.2.2624
Thermal Dynamics - 2.3.10

I know this is probably caused by another mod, but the current crash report does nothing for saying what mod or what block caused this, resulting in a lot of guessing work just to figure out what's crashing.

**Comment by KingLemming** [comment]
Yup. You are correct. It's another mod.

Sorry that the crash isn't super helpful here, but frankly we don't have a great way to throw blame (and that's actually kind of dangerous to do anyways.)
