### ISSUE TITLE
[Thermal Foundation][Suggestion]Add Hardened Glass to Thermal Foundation

### ISSUE THREAD

**Issue by pjfranke** [CoFH/Feedback#981]
Much of the base materials and material alloys for the (now) various Thermal $FOO mods have been pulled into Thermal Foundation, although Hardened Glass was not.

Second point, Thermal Expansion is not a dependency of Thermal Dynamics...it will load just fine without it, and WORK just fine without it, with just a few uncraftable items.

Hardened Glass is a material added only by Thermal Expansion, but is needed for crafting the following Thermal Dynamics base items:

Itemducts
Hardened Fluiducts
Redstone Energy Fluxducts (empty)
Resonant Energy Fluxducts (empty)
Cryo-Stabilized Fluxducts (empty)

Without TE installed, they can be filled with a bucket of the appropriate fluid in a crafting grid, but you without Thermal Expansion installed you can't craft the base duct.  If TE is installed, there are other mod compatible ways to get Hardened Glass, such as via a Tinkers' Construct smeltery or the EnderIO Alloy Smeltery, possibly others I don't have experience with.

I recognize that Destabilized Redstone is required for a few material recipes, which requires either a machine from another mod, or sulfur and pulverized coal to make Pyrotheum to melt redstone down in a TiC smeltery...both TF materials, though requiring another mod (TE, EIO Sag Mill, AE Grindstone, Railcraft Sulfur ore, etc) to acquire or process from other materials.  This only affects Redstone and Cryo-Stabilized fluxducts, Impulse ducts, and Signalium and Resonant servos (resonant being crafted from Signalium servos without TE loaded).  Then again, Signalium servos can't be crafted from Reinforced servos, without Hardened Glass.

I do realize Vacuum and Dense ducts (requiring pulverized lead or silver) are also uncraftable without another mod to pulverize the ingots into dust.  That's a related, but separate issue.  It could be fixed in Thermal Dynamics by allowing Ingots to be used instead of the Pulverized dust, if Thermal Expansion is not detected, similar to how you can fill Redstone Energy Conduit in the crafting grid with a bucket of Destabilized Redstone, when TE is not installed.

Thermal Dynamics works at a basic level for item and cold-fluid transport, with Basic servos, filters, and retrievers (SF&R).  By adding a mod that allows for crafting alloys, you gain access to Hardened  tier SF&R with Invar.

I suggest adding Hardened Glass to Thermal Foundation, with the same cross-mod support it has in Thermal Expansion (supporting the crafting via TiC smeltery, EnderIO Alloy Smeltery, etc), but disabling the item from TF if TE is loaded.  Or just moving it from TE would work (bringing along the same cross-mod support), with the caveat that after everybody updates and launches their saves for the first time, there would be a warning about missing blocks/items.

This change would allow the Hardened Fluiducts, as well as crafting Reinforced tier and Resonant tier SF&R.  Depending on the other mods installed, the player may also then be able to smelt/craft Destabilized Redstone, to allow for alloying Signalium, for Signalium tier SF&R.

**Comment by ZeldoKavira** [comment]
I don't see why we can't do this but it will have to be when we update to 1.8 since it will break worlds.

In the mean time disable the requirement for hardened glass if you don't want to use TE with TD (It's in the config.)

**Comment by pjfranke** [comment]
The potential to cause issues I do make note of, and a suggestion for that.  Does not having a a check if Thermal Expansion is loaded, then keeping it disabled from Thermal Foundation work around that potential issue?

> I suggest adding Hardened Glass to Thermal Foundation....disabling the item from TF if TE is loaded. Or just moving it from TE would work (bringing along the same cross-mod support), with the caveat that after everybody updates and launches their saves for the first time, there would be a warning about missing blocks/items.

**Comment by KingLemming** [comment]
If this happens, it won't be happening until 1.8, sorry. Migrating a block is a huge pain in the ass.

**Comment by pjfranke** [comment]
Appreciate the followup.  I've edited my prior post, as it may not have been clear it was 2 directions.  Your point is likely still quite valid, that not moving, but even just copying a block from one mod to another (plus the conflict check), for the limited use case of someone running TF without TE, is not worth the effort.   

Especially given the previously mentioned workaround:
    
    Recipes {
        B:UseFluidTransposer=false
        B:UseHardenedGlass=false
    }

**Comment by KingLemming** [comment]
Done.
