### ISSUE TITLE
CoFH World: Cave Distribution with Min and Max Height

### ISSUE THREAD

**Issue by tommyTT** [CoFH/Feedback#982]
I'm playing on a custom modpack where I want to test different approaches. In the current version I tried to replace all ore generation with a customized one through CoFH World and wanted to use the distribution type "cave" in order to eliminate branch mining and emphasize caving (mob spawning will also be tweaked). The distribution works well, unfortunately I'm unable to restrict ores to only spawn around a certain level (similar to the uniform distribution). This means, that ores (e.g. diamonds, redstone) also generate near the surface that usually only generate on lower levels. This somewhat eliminates the need to go caving and doesn't fit what I try to accomplish.
It would be appreciated if you could use the same min-height and max-height attributes that the uniform distribution type has and restrict an ore to only generate inside that range. 
Thanks for the consideration.

**Comment by KingLemming** [comment]
Sorry, but I don't quite understand what you're trying to do here. Can you elaborate please?

**Comment by covers1624** [comment]
From the sounds if it, using cave distribution to only spawn ores in / around caves. The issue appears to be that a Y bound for the generator cannot be set, hence his idea for 'only spawn ores in and around caves' wont work as ores that are meant to be bound to lower levels are spawning at the top of the world.

**Comment by tommyTT** [comment]
Yes, exactly what covers1624 stated. As an example I simply switched over all distribution types in the vanilla configuration file from "uniform" to "cave" and now diamonds and redstone are also spawning in caves right around the surface (e.g. y=60). The only restriction to the y-level is the sea level. Using the "ceiling=true" setting, gives a bit better results and eliminates the ores right at the surface, but that is still not the desired effect. 
If "cave" distribution would use the same attributes the "uniform" distribution has in min-height and max-height (and that are already present in this example), the ores would spawn at the exact same y-levels as with the vanilla uniform distribution, but only in and around caves at those levels. 

RWTema tweeted about writing a mod that basically replaces all blocks more than a few blocks from an air block with obsidian (https://twitter.com/RWTema/status/972902137960239104) in order to eliminate strip mining. While that is *a* solution, I find it not fitting for my need. His solution would also eliminate building bases under ground, or at least make it very annoying and that is not what I'm going for. The solution through your cave distribution world gen would simply eliminate the incentive to go strip mining for resources, without altering other things.

**Comment by KingLemming** [comment]
CoFH World is slated for a rewrite. Too much will be changing to really comment on this at this time.
