### ISSUE TITLE
Compression engine bug with BC water shards

### ISSUE THREAD

**Issue by Cyakat** [CoFH/Feedback#983]
When I put BC water shards into a compression engine the game will stop working. I can still move but using containers and placing and breaking blocks does not work. When I place a block it just disappears and I lose the block. I can fix it by just restarting the world but placing a water shard back in just redoes it.

**Comment by KingLemming** [comment]
Need a video of this. There's nothing in the code that suggests this is even possible.

WTF are Water Shards anyways?

**Comment by KingLemming** [comment]
This is entirely on BC to fix. Somehow everyone else can get it right. It's only their item which is supposedly bugged.
