### ISSUE TITLE
[1.12.2] Reservoir to Milk Entities, specifically cows but also other entities if possible

### ISSUE THREAD

**Issue by Vyraal1** [CoFH/Feedback#984]
Would it be possible to add Reservoir support for milking entities? I mention a scope that's larger than just cows because I want to use [this mod - Alfinivia](https://minecraft.curseforge.com/projects/alfinivia) which gives you the ability to milk other entities, and wanted to see if could also be compatible with any custom milking interactions I add to my pack.

**Comment by KingLemming** [comment]
Ultimately, this is actually handled by the Entities themselves, so it's more appropriate for Forge to patch Cows to support this.

I took a look at MooFluids - it should actually work!
