### ISSUE TITLE
Strange Error

### ISSUE THREAD

**Issue by Beelzaboss** [CoFH/Feedback#984]
When someone hovers over a tesseract I crash with this error: http://files.enjin.com.s3.amazonaws.com/298611/modules/tickets/34164167-1450873135-crash-2015-12-23_14.17.51-client.txt

Any ideas?

**Comment by skyboy** [comment]
Duplicate of https://github.com/CoFH/Feedback/issues/980

Additionally, you are using alpha releases which are unstable and may corrupt your world.
