### ISSUE TITLE
Creative strongbox crashes game when placed?

### ISSUE THREAD

**Issue by SirAlden** [CoFH/Feedback#985]
The game crashed whilst unexpected error
Error: java.lang.NoSuchMethodError: cofh.api.tileentity.IReconfigurableFacing.setFacing(IZ)Z
[crash-2018-03-16_15.04.29-client.txt](https://github.com/CoFH/Feedback/files/1820519/crash-2018-03-16_15.04.29-client.txt)

**Comment by KingLemming** [comment]
Issue reports are like headlines. If there is a question mark, the answer is basically always, "No."

This doesn't happen with the correct, legitimate versions of the mods installed (and frankly shouldn't happen ever anyways). Please download the latest from Curseforge.
