### ISSUE TITLE
cofh tps is confusing and causes false conclusions

### ISSUE THREAD

**Issue by twothe** [CoFH/Feedback#986]
While I really like that feature, I often have to battle with other GMs and explain it to them, because the output display is irritating.

Please change the individual dimension output so that it only shows the MS spent, and not the TPS.

Explanation: A Minecraft tick takes 50ms and it doesn't matter where that time is spent, if the tick exceeds 50ms then there is lag. However with the TPS display everyone assumes that if a world is at 20 TPS that one isn't causing any lag, even though it probably does. That assumption however is plain wrong, as only the Overall statistic is relevant.

To remove that confusion (and save me countless seconds of lifetime explaining it to my GM mates) TPS should only be displayed for the Overall and not individual dimensions.

**Comment by XFactHD** [comment]
Your statement doesn't make sense. If a world that is at 20 TPS can be causing lag, this would mean that the lag doesn't start when a tick exceeds 50 ms but much earlier. From my unterstanding (I don't mind if anybody proves me wrong) any lag that is happening in a dimension that has 20 TPS is simply client lag. Example: In my SSP world in an RFTools dimension I have 20 TPS, a tickrate of 3,97 ms and I am lagging nontheless. This happens with a powerful cpu and 10 of 32 GB of RAM allocated to MC.

One thing that could possible be done is putting something like "Dimension: TPS / ms per Tick" as first line of the chat output.

**Comment by twothe** [comment]
You are proving my point well, thank you.

Worlds are not handled in parallel, but single-threaded. So if you have let's say DW20 pack with 8 dimensions open, and each takes a 10ms time to tick, then each world is at 20 TPS __if just that world would be loaded__. 
However the total tick time is 8 * 10ms so 80ms, which exceeds the 50ms that Minecraft has per tick. So overall you are at 16 TPS and therefore feel lag in all dimensions including the overworld.

**Comment by XFactHD** [comment]
OK, I get it now. But to be honest "Overall" is actually pretty clear (My mistake was that I thought of the wrong translation) and describes exactly what you said about MC being single-threaded.

**Comment by KingLemming** [comment]
Here's the thing - TPS is a really useful command to help figure out where something is going wrong. Showing it on a per-world type thing is actually really useful for determining the cause of lag.

I understand the confusion, but it's seriously a trivial thing to comprehend.

**Comment by twothe** [comment]
It is if you know the technical background, and so far I was able to explain it to everyone. But if 9/10 ppl get it wrong, then maybe the display of information need an upgrade.

TPS is a useful command, no doubt about that, but how the information is displayed is the problem. TPS/world is a value that provides no benefit but confuses. The relevant information is TPS/overall, and how many ms each world is contributing to that.

**Comment by KingLemming** [comment]
Well, sort of. Displaying the TPS on worlds individually gives you the extra information about what the overall TPS would be if that world were the only one loaded. It's a far simpler metric than displaying the raw ms. People don't like the level of conversion, and having to shift their process from low = bad to high = bad. Little things like this are why D&D left THAC0 behind.

As you've already pointed out, the Overall statistic is relevant. And it's there. But that doesn't automatically make the other statistics irrelevant.

**Comment by twothe** [comment]
What is the value of "How the TPS would be if that would be the only world loaded" if there is no way to only load that world?

I think that anyone who would need such a rather strange information could read that from the ms time as well. Everyone else is confused by it.

**Comment by Oxosorrel** [comment]
Not everyone is confused by it. I wasn't.

When I had a problem with my server I noticed the nether had a terrible TPS but the rest of the dimensions were fine. 

The cause of this lag isn't important for this thread. What is important is that using this command, as it is currently working started me down a path to solve the problem. It is one tool in a server admins tool box. 

If the change you suggest is accepted, I'd probably file a request to change it back... I personally like, and have directly benefitted form its current design. Thank you KingLemming for cofh_tps.

**Comment by KingLemming** [comment]
>What is the value of "How the TPS would be if that would be the only world loaded" if there is no way to only load that world?

If nobody is in a given world and there are no chunkloaders, the world should unload. If not, there are methods of force-unloading a dimension.

And given Oxosorrel's comment, I basically have to agree. For everyone who is confused by this, there are a lot of people that aren't, so changing it will only result in a request to change it back and I'm not about to play that game.
