### ISSUE TITLE
Game crashes with newly installed direwolf20 1.12.2 modpack due to placing creative strongbox

### ISSUE THREAD

**Issue by SirAlden** [CoFH/Feedback#986]
Modpack name: FTB Direwolf20 1.12.2
Modpack version: 1.10.0 
Mod name: Thermal Expansion
The game crashed whilst unexpected error
Error: java.lang.NoSuchMethodError: cofh.api.tileentity.IReconfigurableFacing.setFacing(IZ)Z
the report file: 
[crash-2018-03-16_15.04.29-client.txt](https://github.com/CoFH/Feedback/files/1820787/crash-2018-03-16_15.04.29-client.txt)

Can you plz help me with this error.

**Comment by KingLemming** [comment]
Do not open duplicate reports. This isn't something with our mod, but the modpack.

**Comment by SirAlden** [comment]
Everything is up to date tho

**Comment by KingLemming** [comment]
Okay, then it's something with the modpack. Let them know, because it's nothing in our code.

Your crash report literally says that some of our code is missing. That's absolutely not on us.
