### ISSUE TITLE
[Thermal Expansion 4][Bug] Trying to use a tesseract causes a crash

### ISSUE THREAD

**Issue by guruzaheer** [CoFH/Feedback#987]
Here's a pastebin of the crash log http://pastebin.com/iDUKvSV6

In my single player world, whenever I use a tesseract, the GUI will open and then MC freezes and crashes instantly. It was working fine until last night, and I can't figure out what is causing the crash. I can use a tesseract in a new world, so could it be some sort of chunk error? I've tried updating all the CoFH mods I use (TE4, Thermal Foundation + Dynamics, Core and Lib), to no avail. I'm not on my computer at home right now, so I can't include a complete list of mods, but I'll add that when I can.

Thanks for your time :)

**Comment by KingLemming** [comment]
That has literally nothing to do with a Tesseract at all.

I'll leave it up because it seems to be MFR, but yeah...not even close.

**Comment by guruzaheer** [comment]
Which is weird because I have had no issues with anything MFR related, I'll get rid of any the MFR stuff and uninstall it to see if I still get crashes.

**Comment by KingLemming** [comment]
Well don't do that. There's still something afoot here.

**Comment by guruzaheer** [comment]
I just meant to see if I can reproduce the crash with MFR uninstalled

**Comment by skyboy** [comment]
You won't. You have an invalid item in your inventory for whatever reason. Opening any GUI will cause you to crash.

We're seeing a lot of these lately, I'm thinking some mod has updated and is now just randomly corrupting items in people's inventories.

**Comment by guruzaheer** [comment]
I realized I recently installed mekanism and got rid of it, and voila no more crashing.
