### ISSUE TITLE
Thermal Dynamics: Optifine Anisotropic Filtering Bugg

### ISSUE THREAD

**Issue by Charismara** [CoFH/Feedback#988]
Forge: 14.23.2.2624 
MC 1.12.2
Thermal Dynamics: 2.3.10.4
Optifine: 1.12.2 HD U C9
No shaders in use.

If I enable Anisotropic Filtering in Optifine any duct looks grey.

![2018-03-17_17 10 31](https://user-images.githubusercontent.com/14293974/37557596-17acb854-2a07-11e8-9a8f-5386a5bbb32e.png)

![2018-03-17_17 10 48](https://user-images.githubusercontent.com/14293974/37557605-4759740c-2a07-11e8-95ed-cb3a70b52a7a.png)

**Comment by paul-soporan** [comment]
There's no support for mods like optifine. This isn't TD' s fault in any way.

**Comment by KingLemming** [comment]
Yup, we don't support Optifine and its hackery.
