### ISSUE TITLE
Nether Ores Overrides List Doesn't Seem to Work

### ISSUE THREAD

**Issue by UndeadZeratul** [CoFH/Feedback#99]
I've been trying to get the overrides list working for our server, so that any ores that generate in the Nether behave like NetherOres do.  However, after several Nether trips I've noticed none of the non-NetherOres ores summon pigmen, nor do they explode.

I'm running the following:
- Forge v10.13.2.1286
- CoFHCore v3.0.0B9-40
- CoFHLib v1.0.0B8-34
- NetherOres v2.3.0 RC4-4

[Here's](https://github.com/Nincraft/NincraftElectricBoogaloo2RevengeoftheFallen/blob/master/config/powercrystals/netherores/common.cfg#L10-L30) what I have set for our overrides array in the config.  I noticed in the past it would remove any incorrect ores, but now they seem to stay.  I would have thought this would work, but again, it doesn't seem to.  Am I doing something wrong, or does this functionality not work correctly yet?

**Comment by skyboy** [comment]
The override list doesn't support metadata.

**Comment by UndeadZeratul** [comment]
Oh, so I just need to call, say, B:"Metallurgy:nether.ore":true, and it should work?

If so, then I'll work on trimming that list up and do some testing later tonight and let you know if I have more problems.

**Comment by skyboy** [comment]
Yes, the entire block becomes a regular netherore, regardless of what different metadatas do. I generally recommend avoiding doing this to blocks that have custom renderers or tile entities.

**Comment by UndeadZeratul** [comment]
Hmm, well then I may have to disable the Seared Bricks entry, as that would potentially cause any and all smelteries to become pigmen traps and ticking timebombs...
