### ISSUE TITLE
issue with nei

### ISSUE THREAD

**Issue by 63502** [CoFH/Feedback#990]
I have noticed a small issue over the past few days. All Thermal Expansion recipes, for items in the mod and for the processing recipes for the machines seem to be missing from NEI. 

Also, and I don't know if this is related in any way, I get a strange event on starting a world. When I open a singleplayer world for the first time after I load minecraft, the world loads all the way to the point where I can see a glimpse of the in game hud, then the world closes and the game says " a fatal error has occured, this connection is terminated", and the game sends me to the multiplayer menu screen. As i said before, I don't know if this glitch is related, but both this and the nei issue started at the same time.

I am not using a modpack, and I am using the latest non alpha release of cofh core and lib, thermal expansion, thermal foundation, and thermal dynamics from curseforge. Since the game never actually crashes, i have no idea what log to include, sorry. :(

Please help me if you can. :(

**Comment by Fabboz** [comment]
I got a similar problem with immersive engineering installed.
For example the recipes for pulverizer are only shown for the crasher but still working in every TE machiness. Something like NEI won't show duplicate recipe for same input output of these machine...
but i haven't spent so much time on that with me all work fine... I only have to search hard in nei!

**Comment by 63502** [comment]
Exactly, except that for me, all recipes added by the thermal expansion mod seem to have vanished completely from nei. Ex. The processing recipes for the pulverizer and the recipe for the pulverizer itself are both missing. The same goes for all the other Thermal Expansion processing and machine recipes. The most annoying part is that only Thermal Expansion is affected. No other COFH mods I have installed are having any issues.

**Comment by KingLemming** [comment]
Sorry, but really dunno what to tell you here. This isn't something we've seen, and the NEI integration works correctly. It's possible that another mod is borking NEI, but that's not on us.

Try an instance with only CoFH mods and NEI.

**Comment by 63502** [comment]
I just did an extensive test, and it turns out both errors i mentioned above are related to Botanical Addons. It turns out the error is not even close to this end at all. :P

**Comment by skyboy** [comment]
Report it to them, I suppose.
