### ISSUE TITLE
cofhworld_update.json malformed

### ISSUE THREAD

**Issue by NicosaurusRex99** [CoFH/Feedback#991]
1.12.2": {
		"1.1.1": "Internal refactors.",
		**"1.0.2": "Preemptive bugfixing.",**
should become
1.12.2": {
		"1.1.1": "Internal refactors.",
		"1.0.2": "Preemptive bugfixing."
	},
https://pastebin.com/71z41niF

**Comment by KingLemming** [comment]
This really would have just been better as a comment on discord. It's not an issue with the code, strictly speaking.

**Comment by NicosaurusRex99** [comment]
kk, will keep in mind
