### ISSUE TITLE
[Thermal Dynamics] Tesselation Error Crash 

### ISSUE THREAD

**Issue by MinecraftWyvern** [CoFH/Feedback#992]
When using warp item ducts along side with ender IO pipes, there seems to be a problem when telling the EnderIO cables not to connect to the warp item ducts

Thanks for your mod and time!

http://pastebin.com/Sv97Lqm4

**Comment by XFactHD** [comment]
Please remove Optifine and see if it still happens.

**Comment by KingLemming** [comment]
We can't replicate this at all and there are no other reports of it happening. Unique to your setup and almost definitely not caused by us.
