### ISSUE TITLE
Suggestion:New Tool Types

### ISSUE THREAD

**Issue by Wotzinator** [CoFH/Feedback#992]
so the mod already adds a few very cool tool types like hammers and so on but it kinda feals odd that there is no special verient of the shovel wich can dig a bigger area (like the hammers).so i wanted to suggest adding spades wich would dig an area of 3x3x1 blocks.

**Comment by KingLemming** [comment]
Hmm...

We have drills coming out soon with Thermal Innovation (which actually sort of obsolete hammers, but need RF), but I'll give this some thought. :)

**Comment by Wotzinator** [comment]
wow drills will be added awsome.will ther be chainsaws to?

**Comment by CammyKun** [comment]
I'd like to second the idea of a chainsaw, though all of these awesome devices may make the Redstone Arsenal mod kind of redundant :)

**Comment by KingLemming** [comment]
The saw is happening, yeah.

And honestly, the purpose of Redstone Arsenal was to show people how to use the RF API and be *kind* of interesting. It's not "canonically" part of Thermal, just plays well alongside it.

**Comment by Wotzinator** [comment]
i just wanted to say that i tried making a spade myself (using the CoFH core api)but i dont really get how aoeBreak Works the only thing i could do was replekating the a hammer that can dig things like snow and sand but somehow dirt doesnt seme to work (and also im not good at making textures)

**Comment by KingLemming** [comment]
Eh. I've decided to go ahead and add these.

**Comment by Wotzinator** [comment]
thanks that's cool
