### ISSUE TITLE
Suggestion: Check through multiple available tanks to pull from when filtering

### ISSUE THREAD

**Issue by turbodiesel4598** [CoFH/Feedback#993]
Hi there,

It may be something that I need to do on my end, but I have certain machines that output more than one type of fluid, let's say fluid A and fluid B. Without any white/blacklisting, tank A is drained first, then tank B, as expected. However, if I whitelist fluid B in the servo, nothing is pulled. Through logging, it seems the servo is simulating a pull from tank A (the actual pull is prevented by the filter), but is not searching the next tank(s) for valid fluids to pull from.

**Comment by KingLemming** [comment]
This isn't how capabilities work, sorry. This is a fundamental design issue with Forge - the servo is only able to say "pull from handler," not "pull from tank A/B."

**Comment by turbodiesel4598** [comment]
Hmmm - maybe it's because I'm not streetwise when it comes to capabilities yet, and there may be other reasons that I don't know about that don't allow for this, but can you not get the properties of the handler's tanks and check through them to see if the contents are white/blacklisted by the servo?

**Comment by KingLemming** [comment]
You can't pull from a tank - you can only pull from the handler. The order that happens in is entirely up to the handler.

**Comment by turbodiesel4598** [comment]
But the servo can look for a particular fluid, no? The reason I've brought this up is because someone brought me into a similar conversation with the BC devs - [I believe this was their solution](https://github.com/BuildCraft/BuildCraft/blob/73ce66b7f3686a18c96bbb6a6b125a458fd3ba41/common/buildcraft/transport/pipe/flow/PipeFlowFluids.java#L215-L230).
