### ISSUE TITLE
ThermalFoundation Not Working

### ISSUE THREAD

**Issue by MoonCodeing** [CoFH/Feedback#994]
Hello, when I try and start my server I get this message **Caught exception from thermalfoundation (java.lang.NoClassDefFoundError: cofh/thermalfoundation/network/PacketTFBase**

**Comment by KingLemming** [comment]
Think about this for a second. If this were actually a problem on our end, how many reports do you think we'd have? ;)

Please go back and redownload all the mods and make sure they're the latest version.
