### ISSUE TITLE
[Thermal Dynamics 1.12] Unsafe cast BlockDuct#collisionRayTrace

### ISSUE THREAD

**Issue by DarkGuardsman** [CoFH/Feedback#995]
Received the following crash from a user for ICBM-Classic. After a quick check, the issue appears to be coming from Thermal Dynamics. Looking over the crash & code it seems BlockDuct does an unsafe cast. 

The issue likely could be related to vanilla MC feeding the block the wrong positions (rounding error), or some other condition causing the problem. The quick solution would be to do an _insanceof_ check to prevent future crashes.

**Crash:** https://pastebin.com/pCaa8xRx

**HighLight:** `java.lang.ClassCastException: icbm.classic.content.machines.launcher.frame.TileLauncherFrame cannot be cast to cofh.thermaldynamics.duct.tiles.TileGrid
    at cofh.thermaldynamics.block.BlockDuct.collisionRayTrace(BlockDuct.java:305)`

**Location in code:** https://github.com/CoFH/ThermalDynamics/blob/1.12/src/main/java/cofh/thermaldynamics/block/BlockDuct.java#L305

**Comment by KingLemming** [comment]
Rather than hiding the reason for the error, Forge and/or Mojang should be addressing this.

A rounding error won't be causing this - it's actively a mistake somewhere in their code.

**Comment by DarkGuardsman** [comment]
I agree, as this has been a problem with mods for a long time. Its the reason why every method I have in ICBM has an instanceof check when dealing with tiles. Since it is possible that MC or forge may not clean up the tile correctly. At least this is the theory, since its hard to track down sources of bad data.

As for ICBM being the source, it does nothing with the ray trace code. The tile that is being cast is a simple GUI with inventory and energy code. It doesn't even have collision checks outside the vanilla provided ones. If you follow the crash the call is coming from MC itself, then to BlockDuct. ICBM is not involved in the call tree outside of MC returning the wrong data.

Regardless its very easy to fix by adding an instanceof check. Assuming the code will always return good data is a bad idea when dealing with MC. The fact it has not errored for months doesn't mean there was not a flaw. It only means the issue has not surfaced or users have not reported the problem.

**Comment by KingLemming** [comment]
I'm not entirely averse to mitigating it, but this seriously does make me wonder because you're the first report of it.

**Comment by DarkGuardsman** [comment]
My theory is that you're just not getting reports. As this is not the first time I've seen this type of crash for a CoFH mod or other mods. Most of the time I tell users to send you the report. This time I decided to handle it myself and make the report for the user. Good thing I did :)

**Comment by Leviathan143** [comment]
It's worth noting that vanilla often does an instanceof check on the retrieved TE, e.g this snippet from `BlockFurnace#breakBlock()`
```java
            TileEntity tileentity = worldIn.getTileEntity(pos);

            if (tileentity instanceof TileEntityFurnace)
            {
                InventoryHelper.dropInventoryItems(worldIn, pos, (TileEntityFurnace)tileentity);
                worldIn.updateComparatorOutputLevel(pos, this);
            }
```
I've been looking through the call hierarchy for `World#getTileEntity()`, so far I haven't found a single call where Mojang has casted the returned value without an instanceof check first. I'd assume there's a reason for that.

**Comment by DarkGuardsman** [comment]
Generally, it's a good idea to always check type before casting. So its no surprise to see MC/Forge do this with the base code. Though I do know older tutorials use to teach that it was not necessary. As some returns could be assumed to be of a set type. From what I can tell this is no longer taught. Especially since instanceof check can double as a null check.
