### ISSUE TITLE
[Thermal Expansion] Creative Tanks not re-rendering

### ISSUE THREAD

**Issue by Delta72Knight** [CoFH/Feedback#995]
Not a large issue here, when using creative portable tanks in the latest infinity evolved pack I noticed that when you replace the fluid in the tank with another one, it doesn't render the new fluid in the tank or update WAILA.

I can confirm recreating this in a fresh 1.7.10 install of forge and minimum mods required to use creative tanks (Forge, CoFH Core, Thermal Foundation, Thermal Expansion)

Here is a link to a gif that shows this issue
https://gyazo.com/886c18f70033ecd660157222338f3ca3

As you can see, not a huge issue. But I for one use creative tanks alot in certain builds!

**Comment by Zsashas** [comment]
Hmm...because of this, I didn't even realize you COULD replace the fluid in a creative tank without breaking it and placing a new one.
