### ISSUE TITLE
[COFHTweaks] client render crash with carpentersblocks+natura

### ISSUE THREAD

**Issue by Saereth** [CoFH/Feedback#996]
Not sure exactly when this triggers, generated a fresh world and I'm just flying around. I've regenerated a new world with a different seed. Issue does not occur without cofhtweaks installed.

Server/client running forge 1558 and a ton of other mods

Here is the client crash log
http://pastebin.com/GvVC34wx

I was originally using 
CoFHTweaks-[1.7.10]1.0.1-37.jar
now I've switched to CoFHTweaks-[1.7.10]1.1.0B2-70

Issue occurs with both versions.

**Comment by skyboy** [comment]
@Mineshopper Is there anything that tweaks might be doing to cause this? I don't see anything, but you know your mod better than I do.

Relevant lines: 
https://github.com/CoFH/CoFHTweaks/blob/master/src/cofh/tweak/asmhooks/render/TweakedRenderer.java#L131
https://github.com/CoFH/CoFHTweaks/blob/master/src/cofh/tweak/asmhooks/render/RenderGlobal.java#L160

**Comment by Mineshopper** [comment]
It's probably something to due with my code but I won't be able to take a look until tomorrow, maybe Sunday.  Side 6 represents the block itself and is used internally, but never for grabbing textures.

**Comment by Saereth** [comment]
I was eventually able to reproduce this without cofhtweaks so doesnt appear to be on your end.
