### ISSUE TITLE
[1.12.2] Sawmill doesn't process dyed leather armor (maybe a bug, maybe not?)

### ISSUE THREAD

**Issue by glindsey** [CoFH/Feedback#999]
I'm not sure if this would be considered a bug or not, but currently the sawmill refuses to process any dyed leather items -- helmets, armor, leggings, etc. If it's working as intended, that's fine, but it seems like you should be able to cut up dyed items just as you would plain ones.

TF Versions:
CoFH Core 4.3.10.5
CoFH World 1.1.1.12
Thermal Dynamics 2.3.10.4
Thermal Expansion 5.3.10.15
Thermal Foundation 2.3.10.6

**Comment by KingLemming** [comment]
Bit of an edge case, since there isn't a "dyed leather" to transform it back into. More elegant solution is probably to remove the leather "recycling" recipes from the Sawmill.

Think I'll probably do that.

**Comment by glindsey** [comment]
Oh no, I did the opposite of what I had intended! XD

Nah, it’s cool. I would’ve suggested just having the dyed stuff revert to normal leather, since it’s just a cosmetic thing, but that works fine. Thanks for your work!
