### ISSUE TITLE
[Bug] [ThermalExpansion] Tesseract Crash

### ISSUE THREAD

**Issue by Ecluid** [CoFH/Feedback#999]
Version: 4.0.3B1-218 for 1.7.10.

Crash Report: (Mod List in bottom of the crash report?)
http://pastebin.com/UCRVER3W

I am currently getting a crash every time I try accessing any tesseracts. As soon as I click on a tesseract my game closes completely out. It is a new tesseract that I just made. It has nothing saved into it yet. Just a blank tesseract. Thanks for looking into this! :fist:

**Comment by KingLemming** [comment]
Please use only stable releases of mods. :( The version of CoFHCore you have isn't that.
